Update funceval.go
minio/minio pull request #10044
Opened 2020-07-14 14:05 UTC by BruceWangNo1

String might contain trimming spaces, which needs to be trimmed. For example, in csv files, there might be trimming spaces in a field that ought to meet a query condition that contains the value in the field without trimming spaces.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-07-14 14:19 UTC, klauspost requested changes
It doesn't seem the changes to `func floatCast(v *Value)` below made it in.

It has similar code and I think it should behave in the same way.

You can just commit the changes to your existing branch and push it, then they will show up here.

2020-07-14 14:20 UTC, klauspost commented
This is the function for your reference: https://github.com/minio/minio/blob/master/pkg/s3select/sql/funceval.go#L487

2020-07-14 14:47 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#9563d4c2-c300-4973-9062-7ff1aeba0500) |
| mint-gateway-azure.sh | :x: [more...](#729685bc-5bb0-4aa9-a399-ec5d463ba6b2) |
<a name="9563d4c2-c300-4973-9062-7ff1aeba0500"></a>
### 10044-1fbe814/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30144
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 426bd7d08feb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 21 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 0 seconds
(8/15) Running minio-dotnet tests ... done in 38 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 12 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 29 seconds
(11/15) Running minio-js tests ... FAILED in 22 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 23,
  "status": "FAIL",
  "error": "S3Error: Please reduce your request at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 2 minutes and 18 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 9 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="729685bc-5bb0-4aa9-a399-ec5d463ba6b2"></a>
### 10044-1fbe814/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31998
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb6d8373c441:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 2 minutes and 40 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 0 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 26 seconds
(10/15) Running minio-java tests ... done in 6 minutes and 9 seconds
(11/15) Running minio-js tests ... done in 2 minutes and 41 seconds
(12/15) Running minio-py tests ... done in 9 minutes and 47 seconds
(13/15) Running s3cmd tests ... FAILED in 39 seconds
{
  "name": "s3cmd",
  "duration": "379",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "ERROR: S3 error: 409 (BucketAlreadyOwnedByYou): Your previous request to create the named bucket succeeded and you already own it."
}
(13/15) Running s3select tests ... done in 1 minutes and 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-07-14 14:57 UTC, BruceWangNo1 commented
Hi @klauspost , I have seen your replies. Thank you for the advice. For some reason, git clone is very slow here. I can't wait. I really need to go to sleep now. I'll finish the pull request tomorrow. Cheers!

2020-07-15 00:53 UTC, harshavardhana commented
Closing this PR seems to be superseded by #10048

2020-07-15 00:53 UTC, closed without merging