Support HashiCorp Vault secrets in docker-entrypoint.sh
minio/minio pull request #10317
Opened 2020-08-21 09:16 UTC by unlimitedbits

## Description
Support fetching the access and secret key from HashiCorp Vault secrets injected into MinIO pods via docker-entrypoint.sh.

## Motivation and Context
At the moment, MinIO supports overriding generated access and secret keys via environment variables and Docker Secrets. As Vault is a commonly used Secret Management Tool and already supported as KMS, there should be a way to provide the MinIO access and secret keys via Vault natively.

Injecting secrets via HashiCorp Vault has a similar end result as Docker secrets by mounting the secrets into the container/pod. However, the secrets are mounted to /vault/secrets instead of /run/secrets. In docker-entrypoint.sh /run/secrets is hard-coded for the file paths for the keys, so I added another bash function using the mount path of Vault secrets and to not break existing deployments using Docker Secrets.

I've also added some basic documentation to configure MinIO with the usage of the official MinIO Helm chart. Honestly, I don't know if this is the most appropriate place. Probably, this documenation should be better added to the Helm chart repo (https://github.com/minio/charts).

## How to test this PR?
1) Setup and create the keys in Vault & deploy MinIO with the official Helm chart as described in the documentation added in this PR.
2) (without Vault) Mount some test secrets to /vault/secrets/{access_key,secret_key} and set the enviroment variables MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE accordingly.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-08-21 11:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#b0b97fe5-1596-4d9b-9ee2-5d6049b2d1f8) |
| mint-gateway-azure.sh | :x: [more...](#7872e2af-e4cd-470d-bf52-099a098ef33f) |
<a name="7872e2af-e4cd-470d-bf52-099a098ef33f"></a>
### 10317-af1a955/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31373
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 31cf318cc18f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 6 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 4 minutes and 40 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 7 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 10 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/15) Running minio-go tests ... FAILED in 5 minutes and 22 seconds
{
  "args": {},
  "duration": 1413,
  "error": "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
  "function": "CopyObjectPart(destination, source)",
  "message": "CompleteMultipartUpload call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 5 minutes and 57 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 37 seconds
(11/15) Running minio-py tests ... done in 10 minutes and 15 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 25 seconds
(13/15) Running s3select tests ... done in 49 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="b0b97fe5-1596-4d9b-9ee2-5d6049b2d1f8"></a>
### 10317-af1a955/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32337
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4bd50425a140:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 22 seconds
(8/15) Running minio-dotnet tests ... done in 27 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 21 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-nu2msf54q2vqmdkg",
      "Object": "srcObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-nu2msf54q2vqmdkg",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 541,
  "error": "This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.",
  "function": "CopyObject(destination, source)",
  "message": "CopyObject failed",
  "name": "minio-go: testEncryptedSSES3ToSSES3CopyObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 22 seconds
(10/15) Running minio-js tests ... done in 38 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 20 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 4 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10317-af1a955

2020-08-21 15:57 UTC, harshavardhana requested changes

2020-08-21 15:57 UTC, harshavardhana commented on docs/docker/README.md
> +```
you don't need to do this @unlimitedbits you can re-use the same path rather than using `/vault/secrets` 

We will not carry vault specific paths in our docker-entrypoint.sh that doesn't look right for us to do 

```
## Create headless service to StatefulSet to work.
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  labels:
    app: minio-headless
spec:
  ports:
  - port: 9000
  clusterIP: None
  selector:
    app: minio
---
apiVersion: apps/v1 #  for k8s versions before 1.9.0 use apps/v1beta2  and before 1.8.0 use extensions/v1beta1
kind: StatefulSet
metadata:
  name: minio
  labels:
     app: minio
spec:
  selector:
    matchLabels:
      app: minio
  serviceName: "minio-headless"
  replicas: 4
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-minio-secrets: "internal/data/minio/config"
        vault.hashicorp.com/role: "minio-app"
        vault.hashicorp.com/agent-inject-template-minio-secrets: |
          {{- with secret "internal/data/minio/config" -}}
             export MINIO_ACCESS_KEY="{{ .Data.data.access_key }}"
             export MINIO_SECRET_KEY="{{ .Data.data.secret_key }}"
          {{- end -}}
      labels:
        app: minio
    spec:
      serviceAccountName: minio-app
      containers:
      - name: minio
        image: minio/minio:RELEASE.2020-06-14T18-32-17Z
        command: [
        "/bin/sh",
        "-ce",
        "source /vault/secrets/minio-secrets && /usr/bin/docker-entrypoint.sh server http://minio-{0...3}.minio-headless.default.svc.cluster.local/data" ]
        ports:
        - containerPort: 9000
          hostPort: 9000
```

2020-08-21 21:48 UTC, unlimitedbits commented on docs/docker/README.md
> +```
I totally understand that you don't want to put vault specific paths into the entrypoint script.
This solution isn't also my preferred one. It was an attempt to add support for /vault/secrets by following the current implementation of docker secrets and without inventing new variables.

My preferred solution would be to get rid of the /run/secrets prefix, so that MINIO_ACCESS_KEY_FILE and MINIO_SECRET_KEY_FILE can be defined as absolute paths. But of course that would break existing deployment configurations which use docker secrets.

Another possibility would be to add a generic solution with new variables (e.g. MINIO_ACCESS_KEY_FILE_PATH & MINIO_SECRET_KEY_FILE_PATH) where you can define absolute paths to the secret files. This would be completely independent of the actual mechanism mounting secrets as files into containers. If you can accept such an approach, I would be pleased to submit a new PR.

Thanks for your alternative, I have already seen it in one of the issues. However, we would like to stick to helm deployments which already supports some sort of hack to make it work:

```yaml
environment:
  MINIO_ACCESS_KEY_FILE: "../../vault/secrets/minio-access-key"
  MINIO_SECRET_KEY_FILE: "../../vault/secrets/minio-secret-key"
```

Still, this is a rather dirty solution and is only working because /run/secrets exists in the container. I would love to have a possibility to define an absolut path for the keys as it's, in my opinion, the most effective and easiest solution to support path mounted key files.

2020-08-23 06:34 UTC, unlimitedbits commented on docs/docker/README.md
> +```
Some additional thoughts: if you're ok with ACCESS_KEY_FILE, SECRET_KEY_FILE & probably KMS_MASTER_KEY_FILE also being absolute paths, the PR could be very minimal and simple, e.g.

```bash
## Look for docker secrets at given absolute path or in default documented location.
docker_secrets_env() {
    if [ -f "$MINIO_ACCESS_KEY_FILE" ]; then
        ACCESS_KEY_FILE="$MINIO_ACCESS_KEY_FILE"
    else
        ACCESS_KEY_FILE="/run/secrets/$MINIO_ACCESS_KEY_FILE"
    fi
    if [ -f "$MINIO_SECRET_KEY_FILE" ]; then
        SECRET_KEY_FILE="$MINIO_SECRET_KEY_FILE"
    else
        SECRET_KEY_FILE="/run/secrets/$MINIO_SECRET_KEY_FILE"
    fi

    if [ -f "$ACCESS_KEY_FILE" ] && [ -f "$SECRET_KEY_FILE" ]; then
        if [ -f "$ACCESS_KEY_FILE" ]; then
            MINIO_ACCESS_KEY="$(cat "$ACCESS_KEY_FILE")"
            export MINIO_ACCESS_KEY
        fi
        if [ -f "$SECRET_KEY_FILE" ]; then
            MINIO_SECRET_KEY="$(cat "$SECRET_KEY_FILE")"
            export MINIO_SECRET_KEY
        fi
    fi
}
```

@harshavardhana your opinion?

2020-08-24 20:56 UTC, harshavardhana commented on docs/docker/README.md
> +```
Yes this makes sense @unlimitedbits we can do this - this is backward compatible as well as supports full custom paths.

2020-08-25 06:20 UTC, unlimitedbits commented
Closed because of https://github.com/minio/minio/pull/10344

2020-08-25 06:20 UTC, closed without merging