GET/HEAD of object with partNumber returns entire object content/length
minio/minio pull request #10338
Opened 2020-08-24 10:27 UTC by x11562

solved this problem: https://github.com/minio/minio/issues/9914

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-08-24 10:54 UTC, klauspost requested changes
Thanks for the contribution. A few changes needed.

`GetObjectHandler` should also have the call here: https://github.com/minio/minio/blob/e7ba78beee9bba0864cefb7393a253d1c5298994/cmd/object-handlers.go#L453 and maybe the web download here: https://github.com/minio/minio/blob/02729731751f5da35cb5e99669a8949169bbeb71/cmd/web-handlers.go#L1336

2020-08-24 10:54 UTC, klauspost commented on cmd/api-headers.go
> +func setPartsContenLengtHeaders(w http.ResponseWriter, objInfo ObjectInfo, partNumber int) {
```suggestion
func setPartsContentHeaders(w http.ResponseWriter, objInfo ObjectInfo, partNumber int) {
```

2020-08-24 10:54 UTC, klauspost commented on cmd/api-headers.go
> +// Modif parts content-lengh
```suggestion
// setPartsContentHeaders will set the part count and content length based on the part number.
```

2020-08-24 10:54 UTC, klauspost commented on cmd/api-headers.go
> +		w.Header()[xhttp.AmzMpPartsCount] = []string{strconv.Itoa(len(objInfo.Parts))}
```suggestion
		w.Header().Set(xhttp.AmzMpPartsCount, strconv.Itoa(len(objInfo.Parts)))
```

2020-08-24 10:54 UTC, klauspost commented on cmd/api-headers.go
> +			w.Header()[xhttp.ContentLength] = []string{strconv.FormatInt(objInfo.Parts[index].ActualSize,10)}
```suggestion
			w.Header().Set(xhttp.ContentLength, fmt.Sprint(part.ActualSize))
```

2020-08-24 10:54 UTC, klauspost commented on cmd/api-headers.go
> +	for index := range objInfo.Parts {
```suggestion
	for _, part := range objInfo.Parts {
```

2020-08-24 10:54 UTC, klauspost commented on cmd/api-headers.go
> +		if partNumber == objInfo.Parts[index].Number {
```suggestion
		if partNumber == part.Number {
```

2020-08-24 10:54 UTC, klauspost commented on cmd/api-headers.go
> +	if strings.Contains(objInfo.ETag, "-") && len(objInfo.Parts) > 0 {
This duplicates code in `setPartsCountHeaders`. Remove one or the other and only have one function call.

2020-08-24 12:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#92dc2c6a-5667-4a3b-9348-a6eb7cce649b) |
| mint-gateway-azure.sh | :x: [more...](#4c53d050-f4eb-4acc-ad09-d9185c41d122) |
<a name="4c53d050-f4eb-4acc-ad09-d9185c41d122"></a>
### 10338-81da942/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31273
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5b5459587362:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 14 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 36 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 4 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 30 seconds
(9/15) Running minio-go tests ... FAILED in 6 minutes and 7 seconds
{
  "args": {},
  "duration": 966,
  "error": "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
  "function": "CopyObjectPart(destination, source)",
  "message": "CompleteMultipartUpload call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 47 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 36 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 42 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 22 seconds
(13/15) Running s3select tests ... done in 1 minutes and 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="92dc2c6a-5667-4a3b-9348-a6eb7cce649b"></a>
### 10338-81da942/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32030
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8863d557e6fb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 7 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 39 seconds
(8/15) Running minio-dotnet tests ... done in 37 seconds
(9/15) Running minio-go tests ... FAILED in 16 minutes and 20 seconds
{
  "args": {
    "bucketName": "minio-go-test-tqld9ozro5wuxd1v",
    "fileName": "/mint/data/datafile-129-MB",
    "location": "us-east-1",
    "objectName": "minio-go-test-tqld9ozro5wuxd1vFPutObject-GTar",
    "opts": {
      "UserMetadata": null,
      "UserTags": null,
      "Progress": null,
      "ContentType": "",
      "ContentEncoding": "",
      "ContentDisposition": "",
      "ContentLanguage": "",
      "CacheControl": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "ServerSideEncryption": null,
      "NumThreads": 0,
      "StorageClass": "",
      "WebsiteRedirectLocation": "",
      "PartSize": 0,
      "LegalHold": "",
      "SendContentMd5": false,
      "DisableMultipart": false,
      "ReplicationVersionID": "",
      "ReplicationStatus": "",
      "ReplicationMTime": "0001-01-01T00:00:00Z"
    }
  },
  "duration": 952415,
  "error": "The specified bucket does not exist",
  "function": "FPutObject(bucketName, objectName, fileName, opts)",
  "message": "FPutObject failed",
  "name": "minio-go: testFPutObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 42 seconds
(10/15) Running minio-js tests ... done in 35 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 56 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 7 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 1 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10338-81da942

2020-08-24 14:59 UTC, kannappanr commented on cmd/object-handlers.go
> +		setPartsContenLengtHeaders(w, objInfo, opts.PartNumber)
```suggestion
		setPartsContenLengthHeaders(w, objInfo, opts.PartNumber)
```

2020-08-24 17:28 UTC, harshavardhana commented
This is not the only change that is needed, you need to make sure that the right content-length 
is read also from the disk for GetObject() scenarios. It is not a trivial change..

2020-08-25 03:13 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#3e9f2866-9e87-48c0-9e95-517e9c3308d1) |
| mint-gateway-azure.sh | :x: [more...](#a4583f38-b5a5-48d6-8005-90babbd61a81) |
| mint-zoned.sh | :x: [more...](#488bf211-26ab-4270-9d14-9ca0ab5b7b27) |
<a name="a4583f38-b5a5-48d6-8005-90babbd61a81"></a>
### 10338-9b57326/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31144
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0ec529426028:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 3 minutes and 44 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 0 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 36 seconds
(9/15) Running minio-go tests ... FAILED in 5 minutes and 19 seconds
{
  "args": {},
  "duration": 942,
  "error": "The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.",
  "function": "CopyObjectPart(destination, source)",
  "message": "CompleteMultipartUpload call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 6 minutes and 26 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 40 seconds
(11/15) Running minio-py tests ... done in 11 minutes and 28 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 30 seconds
(13/15) Running s3select tests ... done in 1 minutes and 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="3e9f2866-9e87-48c0-9e95-517e9c3308d1"></a>
### 10338-9b57326/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30480
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 01cbc4f00b3e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 7 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 53 seconds
(8/15) Running minio-dotnet tests ... done in 36 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 15 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-srmd0v6dip6nu3n5",
      "Object": "srcObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-srmd0v6dip6nu3n5",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 813,
  "error": "This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.",
  "function": "CopyObject(destination, source)",
  "message": "CopyObject failed",
  "name": "minio-go: testEncryptedSSES3ToSSES3CopyObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 56 seconds
(10/15) Running minio-js tests ... done in 42 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 18 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 3 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="488bf211-26ab-4270-9d14-9ca0ab5b7b27"></a>
### 10338-9b57326/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31051
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b198855b93a6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 13 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 3 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 19 seconds
(11/15) Running minio-js tests ... done in 49 seconds
(12/15) Running minio-py tests ... done in 2 minutes and 56 seconds
(13/15) Running s3cmd tests ... FAILED in 23 seconds
{
  "name": "s3cmd",
  "duration": "11482",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10338-9b57326

2020-08-26 10:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#cb01f8b5-f3c3-4d25-b350-5a89b0db22d8) |
<a name="cb01f8b5-f3c3-4d25-b350-5a89b0db22d8"></a>
### 10338-6548964/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32032
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9bec97fabbf1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 59 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... FAILED in 38 seconds
{
  "name": "awscli",
  "duration": 1561,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 22 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 22 seconds
(9/15) Running minio-java tests ... done in 6 minutes and 11 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(11/15) Running minio-py tests ... done in 10 minutes and 40 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 28 seconds
(13/15) Running s3select tests ... done in 52 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-08-31 05:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#669d5173-f862-4506-affa-0bcc17b9dd5e) |
| mint-erasure.sh | :x: [more...](#664a8732-18f4-4bf2-bcaf-cbec52ffc7dc) |
| mint-gateway-nas.sh | :x: [more...](#fa15b769-bcfc-4548-b21a-501743b19527) |
<a name="669d5173-f862-4506-affa-0bcc17b9dd5e"></a>
### 10338-778a928/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32660
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d8701957a68b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 41 seconds
(8/15) Running minio-dotnet tests ... done in 38 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 21 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-p4j300o0wxjctty1",
      "Object": "srcObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-p4j300o0wxjctty1",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 6128,
  "error": "This copy request is illegal because it is trying to copy an object to itself without changing the object's metadata, storage class, website redirect location or encryption attributes.",
  "function": "CopyObject(destination, source)",
  "message": "CopyObject failed",
  "name": "minio-go: testEncryptedSSES3ToSSES3CopyObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 45 seconds
(10/15) Running minio-js tests ... done in 38 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 2 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 5 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="fa15b769-bcfc-4548-b21a-501743b19527"></a>
### 10338-778a928/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32012
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e6f6950ca24b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 53 seconds
{
  "name": "awscli",
  "duration": 62698,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:32012 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-28166/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-28166/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-28166/datafile-1-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-28166/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-28166/datafile-10-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-28166/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-28166/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-28166/datafile-1.03-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-28166/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-28166/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-28166/datafile-10-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-28166/datafile-6-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-28166/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-28166/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-28166/datafile-129-MBupload failed: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-28166/datafile-1-MB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 19 seconds
(7/15) Running minio-dotnet tests ... done in 30 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 21 seconds
(9/15) Running minio-java tests ... done in 19 seconds
(10/15) Running minio-js tests ... done in 39 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 15 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="664a8732-18f4-4bf2-bcaf-cbec52ffc7dc"></a>
### 10338-778a928/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31713
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f8da3818eee2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 58 seconds
{
  "name": "awscli",
  "duration": 62502,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:31713 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-20345/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-20345/datafile-0-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-20345/datafile-10-kBupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-20345/datafile-1-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-20345/datafile-100-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-20345/datafile-33-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-20345/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-20345/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-20345/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-20345/datafile-5243880-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-20345/datafile-6-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-20345/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-20345/datafile-11-MBupload: ../../../data/da [...]

2020-08-31 06:01 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#60e13374-9aeb-475a-948f-6537a473d27f) |
| mint-gateway-nas.sh | :x: [more...](#36623ca5-9a1c-4cb7-9ffb-2c61cb6df64f) |
<a name="60e13374-9aeb-475a-948f-6537a473d27f"></a>
### 10338-80bc82f/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30136
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a625e23480e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 59 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 16 minutes and 22 seconds
{
  "args": {
    "bucketName": "minio-go-test-hltiin4uwd6z0t1y",
    "fileName": "/mint/data/datafile-129-MB",
    "location": "us-east-1",
    "objectName": "minio-go-test-hltiin4uwd6z0t1yFPutObject-GTar",
    "opts": {
      "UserMetadata": null,
      "UserTags": null,
      "Progress": null,
      "ContentType": "",
      "ContentEncoding": "",
      "ContentDisposition": "",
      "ContentLanguage": "",
      "CacheControl": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "ServerSideEncryption": null,
      "NumThreads": 0,
      "StorageClass": "",
      "WebsiteRedirectLocation": "",
      "PartSize": 0,
      "LegalHold": "",
      "SendContentMd5": false,
      "DisableMultipart": false,
      "ReplicationVersionID": "",
      "ReplicationETag": "",
      "ReplicationStatus": "",
      "ReplicationMTime": "0001-01-01T00:00:00Z"
    }
  },
  "duration": 956093,
  "error": "The specified bucket does not exist",
  "function": "FPutObject(bucketName, objectName, fileName, opts)",
  "message": "FPutObject failed",
  "name": "minio-go: testFPutObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 42 seconds
(10/15) Running minio-js tests ... done in 45 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 1 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="36623ca5-9a1c-4cb7-9ffb-2c61cb6df64f"></a>
### 10338-80bc82f/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31635
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c62ab6cfce3f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 53 seconds
{
  "name": "awscli",
  "duration": 62804,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:31635 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-10663/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-10663/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-10663/datafile-1-kBupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-10663/datafile-10-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-10663/datafile-1-bupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-10663/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-10663/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-10663/datafile-1.03-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-10663/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-10663/datafile-5243880-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-10663/datafile-6-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-10663/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-10663/datafile-11-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-10663/datafile-129-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-10663/datafile-65-MBupload failed: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-10663/datafile-1-MB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 24 seconds
(7/15) Running minio-dotnet tests ... done in 33 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 4 seconds
(9/15) Running minio-java tests ... done in 19 seconds
(10/15) Running minio-js tests ... done in 35 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 15 seconds
(12/15) Running s3cmd tests ... done in 16 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-08-31 06:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#2c368923-25b7-460f-a124-6dd768f1299f) |
| mint-gateway-azure.sh | :x: [more...](#7bb66c3a-deea-46b7-a50b-341ef213dd04) |
| mint-erasure.sh | :x: [more...](#70a22d6c-0ff8-442e-8044-1c17c11dd023) |
<a name="70a22d6c-0ff8-442e-8044-1c17c11dd023"></a>
### 10338-60a99ad/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31628
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aa6c7f27355d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 58 seconds
{
  "name": "awscli",
  "duration": 64349,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31628 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-3920/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-3920/datafile-1-bupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-3920/datafile-100-kBupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-3920/datafile-1-kBupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-3920/datafile-10-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-3920/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-3920/datafile-1-MBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-3920/datafile-33-kBupload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-3920/datafile-0-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-3920/datafile-6-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-3920/datafile-5243880-bupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-3920/datafile-5-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-3920/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-3920/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-3920/datafile-129-MBupload failed: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-3920/datafile-10-MB An error occurred (NoSuchBucket) when calling the UploadPart operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 36 seconds
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 2 seconds
(9/15) Running minio-java tests ... done in 21 seconds
(10/15) Running minio-js tests ... done in 46 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 24 seconds
(12/15) Running s3cmd tests ... done in 16 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="2c368923-25b7-460f-a124-6dd768f1299f"></a>
### 10338-60a99ad/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30059
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c997a19e80a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 56 seconds
{
  "name": "awscli",
  "duration": 63302,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30059 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-13644/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-13644/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-13644/datafile-1-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-13644/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-13644/datafile-10-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-13644/datafile-100-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-13644/datafile-33-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-13644/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-13644/datafile-1-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-13644/datafile-5243880-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-13644/datafile-6-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-13644/datafile-5-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-13644/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-13644/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-13644/datafile-129-MBupload failed: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-13644/datafile-10-MB An error occurred (NoSuchBucket) when calling the UploadPart operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 40 seconds
(7/15) Running minio-dotnet tests ... done in 33 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 17 seconds
(9/15) Running minio-java tests ... done in 52 seconds
(10/15) Running minio-js tests ... done in 37 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 7 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 4 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="7bb66c3a-deea-46b7-a50b-341ef213dd04"></a>
### 10338-60a99ad/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32574
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e2fe423687fd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 5 minutes and 51 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 2 minutes and 33 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 24 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 29 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 38 seconds
{
  "args": {
    "bucketName": "minio-go-test-slflojrhxa9l5hsf",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 650,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 11 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[unknown stream size, multi-part upload]",
  "duration": 1896,
  "status":  [...]

2020-08-31 07:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#09a027e8-ee90-4e1d-9162-8992176dd4f6) |
<a name="09a027e8-ee90-4e1d-9162-8992176dd4f6"></a>
### 10338-7f96095/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31886
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e2afb9300932:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 53 seconds
{
  "name": "awscli",
  "duration": 62766,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:31886 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-22033/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-22033/datafile-0-bupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-22033/datafile-100-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-22033/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-22033/datafile-10-kBupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-22033/datafile-1-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-22033/datafile-33-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-22033/datafile-1.03-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-22033/datafile-5243880-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-22033/datafile-6-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-22033/datafile-5-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-22033/datafile-11-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-22033/datafile-10-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-22033/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-22033/datafile-129-MBupload failed: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-22033/datafile-1-MB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 30 seconds
(7/15) Running minio-dotnet tests ... done in 30 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 13 seconds
(9/15) Running minio-java tests ... done in 21 seconds
(10/15) Running minio-js tests ... done in 34 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 14 seconds
(12/15) Running s3cmd tests ... done in 15 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-09-01 19:08 UTC, harshavardhana commented
Feel free to resubmit this PR with other comprehensive changes. Closing this PR since it's not sufficiently fixed.

2020-09-01 19:08 UTC, closed without merging