update KES docs to talk about 'mc encrypt' command
minio/minio pull request #10400
Opened 2020-09-02 03:58 UTC by harshavardhana

## Description
update KES docs to talk about 'mc encrypt' command

## Motivation and Context
add a deprecation notice for KMS_AUTO_ENCRYPTION

## How to test this PR?
Nothing special

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [ ] Unit tests needed

2020-09-02 04:55 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#18f58ade-8920-45dc-917c-87835de8e232) |
| mint-gateway-azure.sh | :x: [more...](#b4cfdd51-cade-41b2-be9b-535c25439867) |
<a name="b4cfdd51-cade-41b2-be9b-535c25439867"></a>
### 10400-0b73c22/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31357
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ebdca97bda73:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 22 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 45 seconds
{
  "name": "awscli",
  "duration": 4152,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:31357 s3api copy-object --bucket awscli-mint-test-bucket-26576 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-26576/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D84EF6F9182BEE-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 7 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 45 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 23 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 42 seconds
(11/15) Running minio-py tests ... done in 14 minutes and 1 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 24 seconds
(13/15) Running s3select tests ... done in 54 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="18f58ade-8920-45dc-917c-87835de8e232"></a>
### 10400-0b73c22/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32338
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4c1d9449f506:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 1 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 7 seconds
{
  "name": "mc",
  "duration": "3458",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7347 --quiet --no-color cp myminio/mc-test-bucket-26526/mc-test-object-24809 mc-test-object-24809.downloaded  >>> \n`myminio/mc-test-bucket-26526/mc-test-object-24809` -> `mc-test-object-24809.downloaded`\nmc: <ERROR> Failed to copy `http://minio-c3.minio.io:32338/mc-test-bucket-26526/mc-test-object-24809`. read tcp 172.17.0.2:35192->72.28.97.59:32338: read: connection reset by peer\nTotal: 0 B, Transferred: 19.53 MiB, Speed: 55.33 MiB/s"
}
(7/15) Running minio-dotnet tests ... done in 28 seconds
(8/15) Running minio-go tests ... done in 29 seconds
(9/15) Running minio-java tests ... done in 24 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 1 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 18 seconds
(12/15) Running s3cmd tests ... done in 15 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10400-0b73c22

2020-09-02 08:13 UTC, aead reviewed
Why are we deprecating server-wide auto-encryption?
AFAICS bucket-level encryption configuration is not a full replacement. In particular, an operator may:
 - want to ensure that an entire deployment is encrypted without configuring each and every bucket separately
 - want to ensure that all objects are encrypted even when applications can create buckets and may not use / set SSE headers

2020-09-02 08:13 UTC, aead commented on docs/kms/README.md
> +Auto-Encryption is useful when the MinIO administrato wants to ensure that all data stored on MinIO is encrypted at rest.
```suggestion
Auto-Encryption is useful when the MinIO administrator wants to ensure that all data stored on MinIO is encrypted at rest.
```

2020-09-02 08:28 UTC, harshavardhana commented
> Why are we deprecating server-wide auto-encryption?
> AFAICS bucket-level encryption configuration is not a full replacement. In particular, an operator may:
> 

It is a full replacement and will be behaving as expected per S3 API. 

> * want to ensure that an entire deployment is encrypted without configuring each and every bucket separately

This is possible per bucket

> * want to ensure that all objects are encrypted even when applications can create buckets and may not use / set SSE headers

This is possible per bucket. 

ENV only based approaches are basically hacks we added it before AWS implemented this feature.

Auto encryption issue is that it is not extensible to KMS key id, you cannot specify which key are you encrypting from.  It simply assumes the facts of single key used in SSE-S3.

Bucket level encryption is automated by minio/console, operator enables or disables encryption as and when needed without the need to restart the entire cluster.

I don't see any advantages of single env based approach and we should deprecate it as it is non standard behavior and lacks flexibility for our future needs.

Just like there is no site level 

- replication
- ILM tiering
- Versioning
- Compliance 

Buckets are the volume, and buckets have the right configuration set by the administrator.

2020-09-02 09:25 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#ea55177f-5df5-41be-b6a0-c64d0a0dbb39) |
<a name="ea55177f-5df5-41be-b6a0-c64d0a0dbb39"></a>
### 10400-e5d8e22/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31536
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8781acab75f7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 6 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 4045,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31536 s3api copy-object --bucket awscli-mint-test-bucket-2148 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-2148/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D84F1CC9F6C258-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 27 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 35 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 33 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 37 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 12 seconds
(13/15) Running s3select tests ... done in 54 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10400-e5d8e22

2020-09-02 09:41 UTC, aead commented
>> Why are we deprecating server-wide auto-encryption?
AFAICS bucket-level encryption configuration is not a full replacement. In particular, an operator may:

> It is a full replacement and will be behaving as expected per S3 API.

>> want to ensure that an entire deployment is encrypted without configuring each and every bucket separately

> This is possible per bucket

>> want to ensure that all objects are encrypted even when applications can create buckets and may not use / set SSE headers

> This is possible per bucket.

Just for the record, my point here was that SSE bucket configuration requires particular configuration **per bucket** (either from the application or the operator when creating the bucket) - which is not the case with an encryption configuration for the entire deployment. The "counter arg" to this cannot be that "this is possible per bucket". The fact that it has to be done per bucket is my point of criticism.

> Auto encryption issue is that it is not extensible to KMS key id, you cannot specify which key are you encrypting from. It simply assumes the facts of single key used in SSE-S3.

That is not really correct. In case of SSE-KMS would use the "default master key ID" (the same as SSE-S3). SSE-S3 and SSE-KMS would behave the same (except for S3-specific details - like ETag) in case of auto-encryption. Also, a key-ID is not mandatory for SSE-KMS. The client can choose to not send one and the server will either take the "default one" the whatever is configured as part of the bucket configuration.

> I don't see any advantages of single env based approach and we should deprecate it as it is non standard behavior and lacks flexibility for our future needs.

I agree that there no similar concept at AWS S3. However, I would not necessarily consider not having such an option an advantage. However, I don't see why it limits flexibility. An operator / application can always set a bucket configuration if they want to. Auto-encryption just prevents storing plaintext data **if they don't specify a SSE bucket configuration**.  It works as a catch-all.
Not encrypting all data by default is/has been a point for criticism - compared to e.g. GCP where SSE is the default.

2020-09-02 15:30 UTC, harshavardhana commented
> > > Why are we deprecating server-wide auto-encryption?
> > > AFAICS bucket-level encryption configuration is not a full replacement. In particular, an operator may:
> 
> > It is a full replacement and will be behaving as expected per S3 API.
> 
> > > want to ensure that an entire deployment is encrypted without configuring each and every bucket separately
> 
> > This is possible per bucket
> 
> > > want to ensure that all objects are encrypted even when applications can create buckets and may not use / set SSE headers
> 
> > This is possible per bucket.
> 
> Just for the record, my point here was that SSE bucket configuration requires particular configuration **per bucket** (either from the application or the operator when creating the bucket) - which is not the case with an encryption configuration for the entire deployment. The "counter arg" to this cannot be that "this is possible per bucket". The fact that it has to be done per bucket is my point of criticism.
> 
> > Auto encryption issue is that it is not extensible to KMS key id, you cannot specify which key are you encrypting from. It simply assumes the facts of single key used in SSE-S3.
> 
> That is not really correct. In case of SSE-KMS would use the "default master key ID" (the same as SSE-S3). SSE-S3 and SSE-KMS would behave the same (except for S3-specific details - like ETag) in case of auto-encryption. Also, a key-ID is not mandatory for SSE-KMS. The client can choose to not send one and the server will either take the "default one" the whatever is configured as part of the bucket configuration.
> 

You are assuming everyone understands that somehow.  It's not evident that this is how it done neither the env tells you that nor the value it carries.

> > I don't see any advantages of single env based approach and we should deprecate it as it is non standard behavior and lacks flexibility for our future needs.
> 
> I agree that there no similar concept at AWS S3. However, I would not necessarily consider not having such an option an advantage. However, I don't see why it limits flexibility. An operator / application can always set a bucket configuration if they want to. Auto-encryption just prevents storing plaintext data **if they don't specify a SSE bucket configuration**. It works as a catch-all.
> Not encrypting all data by default is/has been a point for criticism - compared to e.g. GCP where SSE is the default.
> 
> If an operator wants to enable encryption (at all) then I don't see why it should be enabled only for specific buckets. All objects should be encrypted. The bucket configuration controls specifics - like the method or key-ID - that is used.

It is an advantage because it avoids multiple ways to do the same thing, we should remove any ad-hoc support such as this as it requires confusing variations on software.

Without a bucket no one can upload data, GCP is conceptually different and do not have the same semantics. A bucket configuration guides everything in AWS and that is how it should be.

Global values such as these are inflexible in nature since they are not drive by API and are not configurable.

The value should be removed because it is non standard, our documents should talk about `mc encrypt` instead.

2020-09-02 20:10 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#acb6a5ae-bb61-4d8c-8136-664923545e27) |
| mint-gateway-nas.sh | :x: [more...](#237045d8-039a-4471-8397-479c92fc42b8) |
<a name="acb6a5ae-bb61-4d8c-8136-664923545e27"></a>
### 10400-e10cb10/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30887
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 80437d859bde:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 32 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 24 seconds
{"name": "awscli", "duration": 1912, "function": "aws --endpoint-url http://minio-c3.minio.io:30887 s3api put-object --body /mint/data/datafile-0-b --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-0-b\n", "status": "FAIL", "error": "usage: 
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.htmlusage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 5 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 46 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 46 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 41 seconds
(10/15) Running minio-js tests ... FAILED in 1 minutes and 36 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 109,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 13 minutes and 17 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 16 seconds
(12/15) Running s3select tests ... done in 52 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="237045d8-039a-4471-8397-479c92fc42b8"></a>
### 10400-e10cb10/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31740
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c12365415d94:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 12 seconds
{
  "name": "mc",
  "duration": "6318",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-30531 --quiet --no-color rm mc-test-object-24013.downloaded myminio/mc-test-bucket-20109/mc-test-object-24013  >>> \nRemoving `mc-test-object-24013.downloaded`.\nmc: <ERROR> Unable to list folder. Get \"http://minio-dev6.minio.io:31740/mc-test-bucket-20109/?location=\": dial tcp 72.28.97.55:31740: connect: connection refused\nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-20109/mc-test-object-24013`. "
}
(7/15) Running minio-dotnet tests ... done in 30 seconds
(8/15) Running minio-go tests ... done in 40 seconds
(9/15) Running minio-java tests ... done in 15 seconds
(10/15) Running minio-js tests ... done in 38 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 7 seconds
(12/15) Running s3cmd tests ... done in 15 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10400-e10cb10

2020-09-02 23:59 UTC, eco-minio requested changes

2020-09-02 23:59 UTC, eco-minio commented on docs/kms/README.md
> +Auto-Encryption is useful when the MinIO administrato wants to ensure that all data stored on MinIO is encrypted at rest.
```suggestion
Auto-Encryption is useful when the MinIO administrator wants to ensure that all data stored on MinIO is encrypted at rest.
```

2020-09-03 00:42 UTC, harshavardhana commented
NOTE: @aead the ENV itself is not removed it is advising users to migrate to a more suitable model for S3 API. So we will keep this for the near future at least for another 1yr+

2020-09-03 01:10 UTC, eco-minio approved these changes
LGTM

2020-09-03 01:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e359cd68-68af-4ac1-b133-4737127b3dbc) |
| mint-zoned.sh | :x: [more...](#febaf662-d2a7-4e6f-9701-e157db714d9c) |
<a name="febaf662-d2a7-4e6f-9701-e157db714d9c"></a>
### 10400-0a48440/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31664
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4e83d4932853:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 18 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 29 seconds
(8/15) Running minio-dotnet tests ... done in 44 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 11 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 19 seconds
(11/15) Running minio-js tests ... done in 52 seconds
(12/15) Running minio-py tests ... done in 3 minutes and 39 seconds
(13/15) Running s3cmd tests ... FAILED in 20 seconds
{
  "name": "s3cmd",
  "duration": "9614",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="e359cd68-68af-4ac1-b133-4737127b3dbc"></a>
### 10400-0a48440/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31670
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 066681093caf:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 3 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... FAILED in 45 seconds
{
  "name": "awscli",
  "duration": 3903,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31670 s3api copy-object --bucket awscli-mint-test-bucket-17605 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-17605/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D84FA4729F0188-1"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 12 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 50 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 40 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 58 seconds
(11/15) Running minio-py tests ... done in 13 minutes and 14 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 18 seconds
(13/15) Running s3select tests ... done in 55 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10400-0a48440

2020-09-03 14:47 UTC, aead commented
> It is an advantage because it avoids multiple ways to do the same thing, we should remove any ad-hoc support such as this as > it requires confusing variations on software.

As described above, SSE bucket configuration and auto-encryption don't address the same use case.

> Without a bucket no one can upload data, GCP is conceptually different and do not have the same semantics. A bucket configuration guides everything in AWS and that is how it should be.

The fact that a bucket has to be created before uploading objects is not in question here. My point is that relying only on SSE bucket configuration is an incomplete / fragile security mechanism. By only encrypting objects if a SSE config is present an operator has to ensure that this configuration is set whenever the bucket is created (and not removed at any point in time). And the operator has to ensure that for every bucket.
That is very similar to saying: "Anonymous access is enabled by default on a bucket. If an operator wants to disable it, it can be disabled"

However, what I would propose instead is removing/deprecating the `AUTO_ENCRYPTION` env. var. - but encrypting objects with SSE **whenever** there is a KMS configuration present. Currently, operators have to configure a KMS **and** set auto-encryption.
It seems not reasonable to me that an operator configures a KMS and then just encrypts specific objects. A SSE bucket configuration just describes **how** to encrypt - not that objects get encrypted in this case.

2020-09-03 14:47 UTC, aead approved these changes

2020-09-03 16:48 UTC, harshavardhana commented
> It seems not reasonable to me that an operator configures a KMS and then just encrypts specific objects. A SSE bucket configuration just describes **how** to encrypt - not that objects get encrypted in this case.

This I like @aead - I updated the PR to remove the ENV altogether :+1:

2020-09-03 17:02 UTC, harshavardhana commented
> > It seems not reasonable to me that an operator configures a KMS and then just encrypts specific objects. A SSE bucket configuration just describes **how** to encrypt - not that objects get encrypted in this case.
> 
> This I like @aead - I updated the PR to remove the ENV altogether

Actually going to revert back until we decide on this properly. But will bring back the deprecation notice for now.

2020-09-03 18:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#d0f45d66-873c-43da-a5e7-bdfc92369d2b) |
<a name="d0f45d66-873c-43da-a5e7-bdfc92369d2b"></a>
### 10400-b1b395e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32564
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 501942b5bd45:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 7 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 44 seconds
{
  "name": "awscli",
  "duration": 3637,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32564 s3api copy-object --bucket awscli-mint-test-bucket-22580 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-22580/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D8503615B13536-1"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 9 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(8/15) Running minio-go tests ... done in 6 minutes and 11 seconds
(9/15) Running minio-java tests ... FAILED in 7 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[multi-part upload]",
  "duration": 2349,
  "status": "FAIL",
  "error": "java.net.SocketException: Connection reset >>> [java.base/java.net.SocketInputStream.read(SocketInputStream.java:186), java.base/java.net.SocketInputStream.read(SocketInputStream.java:140), okio.Okio$2.read(Okio.java:140), okio.AsyncTimeout$2.read(AsyncTimeout.java:237), okio.RealBufferedSource.indexOf(RealBufferedSource.java:358), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230), okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:242), okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229), okhttp3.RealCall.execute(RealCall.java:81), io.minio.MinioClient.execute(MinioClient.java:1014), io.minio.MinioClient.uploadPart(MinioClient.java:7781), io.minio.MinioClient.putObject(MinioClient.java:4706), io.minio.MinioClient.putObject(MinioClient.java:4881), FunctionalTest.testPutObject(FunctionalTest.java:740), FunctionalTest.putObject_test(FunctionalTest.java:800), FunctionalTest.runTests(FunctionalTest.java:3789), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(9/15) Running minio-js tests ... done in 2 minutes and 37 seconds
(10/15) Running minio-py tests ... done in 13 minutes and 58 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 32 seconds
(12/15) Running s3select tests ... done in 1 minutes and 0 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10400-b1b395e

2020-09-03 19:43 UTC, merged

2020-09-03 19:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e04eeede-505b-40ec-b497-dd244cfdd907) |
| mint-gateway-azure.sh | :x: [more...](#9dbc5aa9-d03a-4060-9dd9-c6bb08cccae4) |
| mint-zoned.sh | :x: [more...](#9c951ba2-3ae1-4d27-85cb-873c40f82a42) |
<a name="e04eeede-505b-40ec-b497-dd244cfdd907"></a>
### 10400-891cdaa/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31927
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a694c0db9985:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... FAILED in 11 minutes and 39 seconds
{"name": "awscli", "duration": 639536, "function": "aws --endpoint-url http://minio-dev7.minio.io:31927 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-6128/\n", "status": "FAIL", "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-6128/datafile-0-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-6128/datafile-10-kBupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-6128/datafile-1-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-6128/datafile-1-bupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-6128/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-6128/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-6128/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-6128/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-6128/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-6128/datafile-6-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-6128/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-6128/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-6128/datafile-11-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-6128/datafile-129-MBupload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-6128/datafile-65-MB Connection was closed before we received a valid response from endpoint URL: "http://minio-dev7.minio.io:31927/awscli-mint-test-bucket-6128/datafile-65-MB?uploadId=e2283242-b469-4b37-bcd2-b21dbf28fd08&partNumber=4"."}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... FAILED in 3 seconds
{
  "name": "mc",
  "duration": "404",
  "function": "test_put_object_with_metadata",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-6407 --quiet --no-color rm myminio/mc-test-bucket-20384/mc-test-object-16561  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-20384/mc-test-object-16561`. Target object is not found "
}
(6/15) Running minio-dotnet tests ... done in 45 seconds
(7/15) Running minio-go tests ... done in 1 minutes and 49 seconds
(8/15) Running minio-java tests ... done in 1 minutes and 12 seconds
(9/15) Running minio-js tests ... done in 1 minutes and 0 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 17 seconds
(11/15) Running s3cmd tests ... done in 20 seconds
(12/15) Running s3select tests ... done in 8 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="9dbc5aa9-d03a-4060-9dd9-c6bb08cccae4"></a>
### 10400-891cdaa/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31957
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6f36b3260100:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 39 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... FAILED in 42 seconds
{
  "name": "awscli",
  "duration": 3818,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31957 s3api copy-object --bucket awscli-mint-test-bucket-12095 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-12095/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected a861ac626e0bee4421a50737c581233c, got 0x8D8503D066D3E12-1"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 26 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(8/15) Running minio-go tests ... done in 5 minutes and 57 seconds
(9/15) Running minio-java tests ... done in 7 minutes and 47 seconds
(10/15) Running minio-js tests ... done in 2 minutes and 45 seconds
(11/15) Running minio-py tests ... done in 14 minutes and 9 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 17 seconds
(13/15) Running s3select tests ... done in 59 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="9c951ba2-3ae1-4d27-85cb-873c40f82a42"></a>
### 10400-891cdaa/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32091
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5ef321343362:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 17 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 35 seconds
(8/15) Running minio-dotnet tests ... done in 45 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 0 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 12 seconds
(11/15) Running minio-js tests ... done in 52 seconds
(12/15) Running minio-py tests ... done in 3 minutes and 16 seconds
(13/15) Running s3cmd tests ... FAILED in 31 seconds
{
  "name": "s3cmd",
  "duration": "14699",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-09-03 20:44 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c7cdb4a2-b906-4108-b1c6-c6dee2ec4181) |
| mint-gateway-azure.sh | :x: [more...](#9e8197f6-9735-4f67-913b-2144fa8b4f0d) |
<a name="c7cdb4a2-b906-4108-b1c6-c6dee2ec4181"></a>
### 10400-dc05a03/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31903
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 54238615a878:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 11 minutes and 15 seconds
{"name": "awscli", "duration": 624568, "function": "aws --endpoint-url http://minio-dev7.minio.io:31903 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-7845/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (2.3 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (4.5 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (8.8 MiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (2.9 MiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (3.5 MiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (4.0 MiB/s) with 1 file(s) remaining  
Completed 2.0 MiB/65.0 MiB (4.6 MiB/s) with 1 file(s) remaining  
Completed 2.2 MiB/65.0 MiB (5.2 MiB/s) with 1 file(s) remaining  
Completed 2.5 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining  
Completed 2.8 MiB/65.0 MiB (6.2 MiB/s) with 1 file(s) remaining  
Completed 3.0 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining  
Completed 3.2 MiB/65.0 MiB (6.9 MiB/s) with 1 file(s) remaining  
Completed 3.5 MiB/65.0 MiB (7.3 MiB/s) with 1 file(s) remaining  
Completed 3.8 MiB/65.0 MiB (7.6 MiB/s) with 1 file(s) remaining  
Completed 4.0 MiB/65.0 MiB (8.0 MiB/s) with 1 file(s) remaining  
Completed 4.2 MiB/65.0 MiB (8.3 MiB/s) with 1 file(s) remaining  
Completed 4.5 MiB/65.0 MiB (8.6 MiB/s) with 1 file(s) remaining  
Completed 4.8 MiB/65.0 MiB (8.9 MiB/s) with 1 file(s) remaining  
Completed 5.0 MiB/65.0 MiB (9.3 MiB/s) with 1 file(s) remaining  
Completed 5.2 MiB/65.0 MiB (9.6 MiB/s) with 1 file(s) remaining  
Completed 5.5 MiB/65.0 MiB (9.9 MiB/s) with 1 file(s) remaining  
Completed 5.8 MiB/65.0 MiB (10.2 MiB/s) with 1 file(s) remaining 
Completed 6.0 MiB/65.0 MiB (10.4 MiB/s) with 1 file(s) remaining 
Completed 6.2 MiB/65.0 MiB (10.7 MiB/s) with 1 file(s) remaining 
Completed 6.5 MiB/65.0 MiB (11.0 MiB/s) with 1 file(s) remaining 
Completed 6.8 MiB/65.0 MiB (11.2 MiB/s) with 1 file(s) remaining 
Completed 7.0 MiB/65.0 MiB (11.5 MiB/s) with 1 file(s) remaining 
Completed 7.2 MiB/65.0 MiB (11.8 MiB/s) with 1 file(s) remaining 
Completed 7.5 MiB/65.0 MiB (12.0 MiB/s) with 1 file(s) remaining 
Completed 7.8 MiB/65.0 MiB (12.3 MiB/s) with 1 file(s) remaining 
Completed 8.0 MiB/65.0 MiB (12.5 MiB/s) with 1 file(s) remaining 
Completed 8.2 MiB/65.0 MiB (12.6 MiB/s) with 1 file(s) remaining 
Completed 8.5 MiB/65.0 MiB (12.7 MiB/s) with 1 file(s) remaining 
Completed 8.8 MiB/65.0 MiB (12.9 MiB/s) with 1 file(s) remaining 
Completed 9.0 MiB/65.0 MiB (13.0 MiB/s) with 1 file(s) remaining 
Completed 9.2 MiB/65.0 MiB (8.1 MiB/s) with 1 file(s) remaining  
Completed 9.5 MiB/65.0 MiB (8.3 MiB/s) with 1 file(s) remaining  
Completed 9.8 MiB/65.0 MiB (8.5 MiB/s) with 1 file(s) remaining  
Completed 10.0 MiB/65.0 MiB (8.7 MiB/s) with 1 file(s) remaining 
Completed 10.2 MiB/65.0 MiB (8.9 MiB/s) with 1 file(s) remaining 
Completed 10.5 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining 
Completed 10.8 MiB/65.0 MiB (9.3 MiB/s) with 1 file(s) remaining 
Completed 11.0 MiB/65.0 MiB (9.5 MiB/s) with 1 file(s) remaining 
Completed 11.2 MiB/65.0 MiB (9.6 MiB/s) with 1 file(s) remaining 
Completed 11.5 MiB/65.0 MiB (9.9 MiB/s) with 1 file(s) remaining 
Completed 11.8 MiB/65.0 MiB (10.0 MiB/s) with 1 file(s) remaining
Completed 12.0 MiB/65.0 MiB (10.2 MiB/s) with 1 file(s) remaining
Completed 12.2 MiB/65.0 MiB (10.4 MiB/s) with 1 file(s) remaining
Completed 12.5 MiB/65.0 MiB (10.6 MiB/s) with 1 file(s) remaining
Completed 12.8 MiB/65.0 MiB (10.8 MiB/s) with 1 file(s) remaining
Completed 13.0 MiB/65.0 MiB (11.0 MiB/s) with 1 file(s) remaining
Completed 13.2 MiB/65.0 MiB (11.2 MiB/s) with 1 file(s) remaining
Completed 13.5 MiB/65.0 MiB (11.4 MiB/s) with 1 file(s) remaining
Completed 13.8 MiB/65.0 MiB (11.6 MiB/s) with 1 file(s) remaining
Completed 14.0 MiB/65.0 MiB (11.8 MiB/s) with 1 file(s) remaining
Completed 14.2 MiB/65.0 MiB (11.9 MiB/s) with 1 file(s) remaining
Completed 14.5 MiB/65.0 MiB (12.1 MiB/s) with 1 file(s) remaining
Completed 14.8 MiB/65.0 MiB (12.3 MiB/s) with 1 file(s) remaining
Completed 15.0 MiB/65.0 MiB (12.5 MiB/s) with 1 file(s) remaining
Completed 15.2 MiB/65.0 MiB (12.7 MiB/s) with 1 file(s) remaining
Completed 15.5 MiB/65.0 MiB (12.9 MiB/s) with 1 file(s) remaining
Completed 15.8 MiB/65.0 MiB (13.1 MiB/s) with 1 file(s) remaining
Completed 16.0 MiB/65.0 MiB (13.3 MiB/s) with 1 file(s) remaining
Completed 16.2 MiB/65.0 MiB (13.4 MiB/s) with 1 file(s) remaining
Completed 16.5 MiB/65.0 MiB (13.6 MiB/s) with 1 file(s) remaining
Completed 16.8 MiB/65.0 MiB (13.8 MiB/s) with 1 file(s) remaining
Completed 17.0 MiB/65.0 MiB (14.0 MiB/s) with 1 file(s) remaining
Completed 17.2 MiB/65.0 MiB (14.1 MiB/s) with 1 file(s) remaining
Completed 17.5 MiB/65.0 MiB (14.3 MiB/s) with 1 file(s) remaining
Completed 17.8 MiB/65.0 MiB (14.5 MiB/s) with 1 file(s) remaining
Completed 18.0 MiB/65.0 MiB (14.7 MiB/s) with 1 file(s) remaining
Completed 18.2 MiB/65.0 MiB (14.9 MiB/s) with 1 file(s) remaining
Completed 18.5 MiB/65.0 MiB (15.1 MiB/s) with 1 file(s) remaining
Completed 18.8 MiB/65.0 MiB (15.2 MiB/s) with 1 file(s) remaining
Completed 19.0 MiB/65.0 MiB (15.4 MiB/s) with 1 file(s) remaining
Completed 19.2 MiB/65.0 MiB (15.6 MiB/s) with 1 file(s) remaining
Completed 19.5 MiB/65.0 MiB (15.8 MiB/s) with 1 file(s) remaining
Completed 19.8 MiB/65.0 MiB (14.7 MiB/s) with 1 file(s) remaining
Completed 20.0 MiB/65.0 MiB (14.8 MiB/s) with 1 file(s) remaining
Completed 20.2 MiB/65.0 MiB (14.9 MiB/s) with 1 file(s) remaining
Completed 20.5 MiB/65.0 MiB (15.0 MiB/s) with 1 file(s) remaining
Completed 20.8 MiB/65.0 MiB (15.1 MiB/s) with 1 file(s) remaining
Completed 21.0 MiB/65.0 MiB (15.2 MiB/s) with 1 file(s) remaining
Completed 21.2 MiB/65.0 MiB (15.3 MiB/s) with 1 file(s) remaining
Completed 21.5 MiB/65.0 MiB (15.5 MiB/s) with 1 file(s) remaining
Completed 21.8 MiB/65.0 MiB (15.6 MiB/s) with 1 file(s) remaining
Completed 22.0 MiB/65.0 MiB (15.6 MiB/s) with 1 file(s) remaining
Completed 22.2 MiB/65.0 MiB (15.7 MiB/s) with 1 file(s) remaining
Completed 22.5 MiB/65.0 MiB (15.8 MiB/s) with 1 file(s) remaining
Completed 22.8 MiB/65.0 MiB (15.9 MiB/s) with 1 file(s) remaining
Completed 23.0 MiB/65.0 MiB (15.9 MiB/s) with 1 file(s) remaining
Completed 23.2 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining
Completed 23.5 MiB/65.0 MiB (16.1 MiB/s) with 1 file(s) remaining
Completed 23.8 MiB/65.0 MiB (16.1 MiB/s) with 1 file(s) remaining
Completed 24.0 MiB/65.0 MiB (16.2 MiB/s) with 1 file(s) remaining
Completed 24.2 MiB/65.0 MiB (16.3 MiB/s) with 1 file(s) remaining
Completed 24.5 MiB/65.0 MiB (16.4 MiB/s) with 1 file(s) remaining
Completed 24.8 MiB/65.0 MiB (16.4 MiB/s) with 1 file(s) remaining
Completed 25.0 MiB/65.0 MiB (16.5 MiB/s) with 1 file(s) remai [...]