ilm: Remove null version if not latest with proper config
minio/minio pull request #10467
Opened 2020-09-11 15:04 UTC by vadmeste

## Description
An object with 'null' version is not removed when it is not latest
and 'NoncurrentVersionExpiration' is activated in the lifecycle
document. This commit fixes this.

## Motivation and Context
Fixing a bug with lfiecycle

## How to test this PR?
1. Start a MinIO server instance with 4 disks
2. Create a bucket and upload a file
3. Enable versioning on that bucket
4. Upload another file
5. Set the following ILM in that bucket:
```
{
    "Rules": [
        {
            "ID": "Remove old non current versions",
            "Status": "Enabled",
            "NoncurrentVersionExpiration": {
                "NoncurrentDays": 1
            }
        }
    ]
}
```
6. Add 3 days in your machine time and waits until lifecycle is kicked in

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-09-11 15:36 UTC, harshavardhana requested changes
This is already done at ObjectInfo conversion, does lifecycle access fileinfo directly?

2020-09-11 15:52 UTC, vadmeste commented
> This is already done at ObjectInfo conversion, does lifecycle access fileinfo directly?

yeah, crawling does, https://github.com/minio/minio/blob/master/cmd/xl-storage.go#L377

2020-09-11 18:39 UTC, harshavardhana commented
Okay 👌

2020-09-11 18:39 UTC, harshavardhana approved these changes

2020-09-11 19:55 UTC, kannappanr approved these changes
LGTM

2020-09-11 21:20 UTC, merged

2020-09-12 01:16 UTC, harshavardhana commented
Reverted this change due to `minio-py` failure for versioning tests, please take a look at them @vadmeste