Support for "directory" objects
minio/minio pull request #10499
Opened 2020-09-16 20:03 UTC by krishnasrinivas

## Description

This is a requirement from a potential customer:

Without the fix:
```
krishna@escape:~$ mc mb min/test/
Bucket created successfully `min/test/`.
krishna@escape:~$ mc mb min/test/prefix/
Bucket created successfully `min/test/prefix/`.
krishna@escape:~$ mc cp /etc/passwd min/test/prefix/
/etc/passwd:                          2.42 KiB / 2.42 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 50.28 KiB/s 0skrishna@escape:~$ mc rm min/test/prefix/passwd
Removing `min/test/prefix/passwd`.
krishna@escape:~$ mc ls min/test/
krishna@escape:~$ 
```
i.e "prefix/" is gone.

With fix, "prefix/" is not deleted:

```
krishna@escape:~$ mc mb min/test/
Bucket created successfully `min/test/`.
krishna@escape:~$ mc mb min/test/prefix/
Bucket created successfully `min/test/prefix/`.
krishna@escape:~$ mc cp /etc/passwd min/test/prefix/
/etc/passwd:                          2.42 KiB / 2.42 KiB ┃▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓┃ 43.41 KiB/s 0skrishna@escape:~$ mc rm min/test/prefix/passwd
Removing `min/test/prefix/passwd`.
krishna@escape:~$ mc ls min/test/
[2020-09-16 12:59:44 PDT]      0B prefix/
krishna@escape:~$ mc ls -r min/test/
[2020-09-16 12:59:30 PDT]      0B prefix/
krishna@escape:~$ 
```

Request to reviewers: Please see if this causes any side effects to healing of the "prefix/' object.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-09-16 20:13 UTC, harshavardhana requested changes

2020-09-16 20:13 UTC, harshavardhana commented on cmd/globals.go
> +	globalDirSuffixWithSlash       = "__MINIO_DIR__/"
```suggestion
	globalDirSuffixWithSlash       = "__MINIO_DIR__" + slashSeparator
```

2020-09-16 20:13 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if !strings.HasSuffix(entries[i], globalDirSuffixWithSlash) && !strings.HasSuffix(entries[j], globalDirSuffixWithSlash) {
```suggestion
		if !HasSuffix(entries[i], globalDirSuffixWithSlash) && !HasSuffix(entries[j], globalDirSuffixWithSlash) {
```

For windows

2020-09-16 20:13 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if strings.HasSuffix(first, globalDirSuffixWithSlash) {
```suggestion
		if HasSuffix(first, globalDirSuffixWithSlash) {
```

2020-09-16 20:13 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if strings.HasSuffix(second, globalDirSuffixWithSlash) {
```suggestion
		if HasSuffix(second, globalDirSuffixWithSlash) {
```

2020-09-16 20:13 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if strings.HasSuffix(first, globalDirSuffix) {
```suggestion
		if HasSuffix(first, globalDirSuffix) {
```

2020-09-16 20:13 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if !strings.HasSuffix(entries[i], globalDirSuffix) && !strings.HasSuffix(entries[j], globalDirSuffix) {
```suggestion
		if !HasSuffix(entries[i], globalDirSuffix) && !HasSuffix(entries[j], globalDirSuffix) {
```

2020-09-16 20:13 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if strings.HasSuffix(second, globalDirSuffix) {
```suggestion
		if HasSuffix(second, globalDirSuffix) {
```

2020-09-16 21:58 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#741d3fa0-375b-4689-b267-6cada87357f4) |
| mint-erasure.sh | :x: [more...](#adfddd6a-641c-4e98-88ea-f62a86b98cb3) |
<a name="741d3fa0-375b-4689-b267-6cada87357f4"></a>
### 10499-4b57265/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31226
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5320d8b6430c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 39 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 52 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 5 minutes and 47 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 51 seconds
{
  "args": {
    "bucketName": "minio-go-test-xt0csk6tx0h6l954",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 985,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 9 minutes and 47 seconds
(10/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 75,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:678:10) at endReadableNT (_stream_readable.js:1244:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 31 seconds
(11/15) Running s3cmd tests ... done in 3 minutes and 24 seconds
(12/15) Running s3select tests ... done in 50 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="adfddd6a-641c-4e98-88ea-f62a86b98cb3"></a>
### 10499-4b57265/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31641
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp db30cbfb10d1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 36 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 29 seconds
{
  "args": {
    "bucketName": "minio-go-test-z3fhgb49se42mjxw",
    "objectName": "4irvgg3rhau123lilywy6oyn3qqkxl"
  },
  "duration": 13539,
  "error": "read tcp 172.17.0.2:47328->72.28.97.56:31641: read: connection reset by peer",
  "function": "GetObject(bucketName, objectName)",
  "message": "CopyN failed",
  "name": "minio-go: testSSES3EncryptedGetObjectReadSeekFunctional",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 48 seconds
(10/15) Running minio-js tests ... done in 49 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 10 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10499-4b57265

2020-09-17 01:12 UTC, harshavardhana requested changes

2020-09-17 01:12 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if HasSuffix(entry, globalDirSuffixWithSlash) {
Add a comment on why its skipped?

2020-09-17 01:12 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if !HasSuffix(entries[i], globalDirSuffixWithSlash) && !HasSuffix(entries[j], globalDirSuffixWithSlash) {
Add a comment on how this handles the order for `__MINIO__DIR_`

2020-09-17 01:12 UTC, harshavardhana commented on cmd/tree-walk.go
> +	sort.Slice(entries, func(i, j int) bool {
Write a comment about this sorting as well..

2020-09-17 01:26 UTC, harshavardhana commented
Found that on versioning enabled buckets we end up creating versions for empty directories we need to fix that @krishnasrinivas 

```
~ mc rm -r --force myminio/testbucket1/
mc: <ERROR> Failed to remove `myminio/testbucket1/`. Object does not exist
```
```
```
~ mc ls myminio/testbucket1/ --versions
[2020-09-16 18:26:33 PDT]      0B prefix/
[2020-09-16 18:26:33 PDT]      0B prefix/
[2020-09-16 18:26:33 PDT]      0B prefix__MINIO_DIR__/
[2020-09-16 18:26:33 PDT]      0B prefix__MINIO_DIR__/
```

```
~ mc ls myminio/testbucket1/
```

2020-09-17 01:27 UTC, harshavardhana commented
```
~ ls /tmp/fs-new{1,2,3,4}/testbucket1/prefix__MINIO_DIR__/
[2020-09-16 18:20:56 PDT]  4.0KiB b2b4d7f9-83cc-4873-a567-7b8ba9f67197/
[2020-09-16 18:23:39 PDT]    356B xl.meta
[2020-09-16 18:20:56 PDT]  4.0KiB b2b4d7f9-83cc-4873-a567-7b8ba9f67197/
[2020-09-16 18:23:39 PDT]    356B xl.meta
[2020-09-16 18:20:56 PDT]  4.0KiB b2b4d7f9-83cc-4873-a567-7b8ba9f67197/
[2020-09-16 18:23:39 PDT]    356B xl.meta
[2020-09-16 18:20:56 PDT]  4.0KiB b2b4d7f9-83cc-4873-a567-7b8ba9f67197/
[2020-09-16 18:23:39 PDT]    356B xl.meta
```

2020-09-17 01:27 UTC, harshavardhana commented
I am not sure if this was intentional @krishnasrinivas

2020-09-17 01:31 UTC, harshavardhana requested changes
Looks we are also creating lots of versions for the same object, it is not a bad idea to support it but remember we have to support it properly

@krishnasrinivas 

```
~ mc ls myminio/testbucket1/ --versions
[2020-09-16 18:30:14 PDT]      0B prefix/
[2020-09-16 18:30:14 PDT]      0B prefix/
[2020-09-16 18:30:14 PDT]      0B prefix/
[2020-09-16 18:30:14 PDT]      0B prefix/
```

```
~ s /tmp/fs-new{1,2,3,4}/testbucket1/prefix__MINIO_DIR__/
[2020-09-16 18:29:44 PDT]  4.0KiB 513bf002-f5ce-473b-81cc-7b19157f319e/
[2020-09-16 18:30:11 PDT]  4.0KiB 6b299cb9-e671-4e53-912a-f2ce5e655a75/
[2020-09-16 18:30:05 PDT]  4.0KiB 95d03245-0c17-43a1-8d62-c44c49fec8fc/
[2020-09-16 18:30:12 PDT]  4.0KiB ab3c8568-33e5-41ca-94e7-ec5ad727bbe4/
[2020-09-16 18:30:12 PDT]  1.1KiB xl.meta
[2020-09-16 18:29:44 PDT]  4.0KiB 513bf002-f5ce-473b-81cc-7b19157f319e/
[2020-09-16 18:30:11 PDT]  4.0KiB 6b299cb9-e671-4e53-912a-f2ce5e655a75/
[2020-09-16 18:30:05 PDT]  4.0KiB 95d03245-0c17-43a1-8d62-c44c49fec8fc/
[2020-09-16 18:30:12 PDT]  4.0KiB ab3c8568-33e5-41ca-94e7-ec5ad727bbe4/
[2020-09-16 18:30:12 PDT]  1.1KiB xl.meta
[2020-09-16 18:29:44 PDT]  4.0KiB 513bf002-f5ce-473b-81cc-7b19157f319e/
[2020-09-16 18:30:11 PDT]  4.0KiB 6b299cb9-e671-4e53-912a-f2ce5e655a75/
[2020-09-16 18:30:05 PDT]  4.0KiB 95d03245-0c17-43a1-8d62-c44c49fec8fc/
[2020-09-16 18:30:12 PDT]  4.0KiB ab3c8568-33e5-41ca-94e7-ec5ad727bbe4/
[2020-09-16 18:30:12 PDT]  1.1KiB xl.meta
[2020-09-16 18:29:44 PDT]  4.0KiB 513bf002-f5ce-473b-81cc-7b19157f319e/
[2020-09-16 18:30:11 PDT]  4.0KiB 6b299cb9-e671-4e53-912a-f2ce5e655a75/
[2020-09-16 18:30:05 PDT]  4.0KiB 95d03245-0c17-43a1-8d62-c44c49fec8fc/
[2020-09-16 18:30:12 PDT]  4.0KiB ab3c8568-33e5-41ca-94e7-ec5ad727bbe4/
[2020-09-16 18:30:12 PDT]  1.1KiB xl.meta
```

2020-09-17 01:36 UTC, harshavardhana commented
To fix the `mc` output all you have to do is this

```
~ git diff
diff --git a/cmd/erasure-metadata.go b/cmd/erasure-metadata.go
index d421d5fce..537b64c08 100644
--- a/cmd/erasure-metadata.go
+++ b/cmd/erasure-metadata.go
@@ -96,22 +96,13 @@ func (fi FileInfo) IsValid() bool {
 
 // ToObjectInfo - Converts metadata to object info.
 func (fi FileInfo) ToObjectInfo(bucket, object string) ObjectInfo {
-       if HasSuffix(object, SlashSeparator) {
-               return ObjectInfo{
-                       Bucket:  bucket,
-                       Name:    object,
-                       IsDir:   true,
-                       ModTime: fi.ModTime,
-               }
-       }
-
        versionID := fi.VersionID
        if globalBucketVersioningSys.Enabled(bucket) && versionID == "" {
                versionID = nullVersionID
        }
 
        objInfo := ObjectInfo{
-               IsDir:           false,
+               IsDir:           HasSuffix(object, SlashSeparator),
                Bucket:          bucket,
                Name:            object,
                VersionID:       versionID,
```

2020-09-17 02:04 UTC, harshavardhana commented
This change is also needed @krishnasrinivas 

```diff
diff --git a/cmd/erasure-metadata.go b/cmd/erasure-metadata.go
index d421d5fce..537b64c08 100644
--- a/cmd/erasure-metadata.go
+++ b/cmd/erasure-metadata.go
@@ -96,22 +96,13 @@ func (fi FileInfo) IsValid() bool {
 
 // ToObjectInfo - Converts metadata to object info.
 func (fi FileInfo) ToObjectInfo(bucket, object string) ObjectInfo {
-       if HasSuffix(object, SlashSeparator) {
-               return ObjectInfo{
-                       Bucket:  bucket,
-                       Name:    object,
-                       IsDir:   true,
-                       ModTime: fi.ModTime,
-               }
-       }
-
        versionID := fi.VersionID
        if globalBucketVersioningSys.Enabled(bucket) && versionID == "" {
                versionID = nullVersionID
        }
 
        objInfo := ObjectInfo{
-               IsDir:           false,
+               IsDir:           HasSuffix(object, SlashSeparator),
                Bucket:          bucket,
                Name:            object,
                VersionID:       versionID,
diff --git a/cmd/erasure-zones.go b/cmd/erasure-zones.go
index be20ec8f5..8127f870b 100644
--- a/cmd/erasure-zones.go
+++ b/cmd/erasure-zones.go
@@ -761,7 +761,7 @@ func (z *erasureZones) listObjectsNonSlash(ctx context.Context, bucket, prefix,
 
        result := ListObjectsInfo{}
        for _, objInfo := range objInfos {
-               if objInfo.IsDir {
+               if objInfo.IsDir && !skipPresent(result.Prefixes, objInfo.Name) {
                        result.Prefixes = append(result.Prefixes, objInfo.Name)
                        continue
                }
@@ -778,6 +778,15 @@ func (z *erasureZones) listObjectsNonSlash(ctx context.Context, bucket, prefix,
        return result, nil
 }
 
+func skipPresent(slice []string, entry string) bool {
+       for _, str := range slice {
+               if str == entry {
+                       return true
+               }
+       }
+       return false
+}
+
 func (z *erasureZones) listObjectsSplunk(ctx context.Context, bucket, prefix, marker string, maxKeys int) (loi ListObjectsInfo, err error) {
        if strings.Contains(prefix, guidSplunk) {
                logger.LogIf(ctx, NotImplemented{})
@@ -819,6 +828,10 @@ func (z *erasureZones) listObjectsSplunk(ctx context.Context, bucket, prefix, ma
                        continue
                }
 
+               if skipPresent(loi.Prefixes, splits[0]+guidSplunk) {
+                       continue
+               }
+
                loi.Prefixes = append(loi.Prefixes, splits[0]+guidSplunk)
        }
 
@@ -905,7 +918,10 @@ func (z *erasureZones) listObjects(ctx context.Context, bucket, prefix, marker,
 
        for _, entry := range entries.Files {
                objInfo := entry.ToObjectInfo(entry.Volume, entry.Name)
-               if HasSuffix(objInfo.Name, SlashSeparator) && !recursive {
+               if objInfo.IsDir && !recursive {
+                       if skipPresent(loi.Prefixes, objInfo.Name) {
+                               continue
+                       }
                        loi.Prefixes = append(loi.Prefixes, objInfo.Name)
                        continue
                }
@@ -1301,7 +1317,10 @@ func (z *erasureZones) listObjectVersions(ctx context.Context, bucket, prefix, m
        for _, entry := range entries.FilesVersions {
                for _, version := range entry.Versions {
                        objInfo := version.ToObjectInfo(bucket, entry.Name)
-                       if HasSuffix(objInfo.Name, SlashSeparator) && !recursive {
+                       if objInfo.IsDir && !recursive {
+                               if skipPresent(loi.Prefixes, objInfo.Name) {
+                                       continue
+                               }
                                loi.Prefixes = append(loi.Prefixes, objInfo.Name)
                                continue
                        }
```

2020-09-17 02:14 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#a7fdd0fd-fa0e-47df-9731-703abcb6fd65) |
<a name="a7fdd0fd-fa0e-47df-9731-703abcb6fd65"></a>
### 10499-7e7afec/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32296
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 276047aaea9f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 45 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 55 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 39 seconds
(10/15) Running minio-java tests ... done in 10 minutes and 56 seconds
(11/15) Running minio-js tests ... done in 3 minutes and 40 seconds
(12/15) Running minio-py tests ... done in 19 minutes and 7 seconds
(13/15) Running s3cmd tests ... done in 2 minutes and 22 seconds
(14/15) Running s3select tests ... FAILED in 13 seconds
{
  "name": "s3select:test_csv_input_quote_char",
  "function": "select_object_content(bucket_name, object_name, opts)",
  "args": {
    "bucket_name": "s3select-test-d9c1cda4-8953-4723-9a92-7b7c15c27bf7"
  },
  "duration": 12709,
  "message": "Test test_15 unexpectedly failed with: 'event-type'",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/s3select/csv.py\", line 39, in test_sql_api\n    for d in data.stream(10*1024):\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select/reader.py\", line 211, in stream\n    message = self.__extract_message()\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select/reader.py\", line 161, in __extract_message\n    event_type = header_map[\"event-type\"]\nKeyError: 'event-type'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./tests.py\", line 52, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"/mint/run/core/s3select/csv.py\", line 119, in test_csv_input_custom_quote_char\n    data, sql_opts, expected_output)\n  File \"/mint/run/core/s3select/csv.py\", line 45, in test_sql_api\n    'Test {} unexpectedly failed with: {}'.format(test_name, select_err))\nValueError: Test test_15 unexpectedly failed with: 'event-type'\n",
  "status": "FAIL"
}
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10499-7e7afec

2020-09-17 03:11 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c0154208-c594-4e0c-866b-aeeb7f701556) |
<a name="c0154208-c594-4e0c-866b-aeeb7f701556"></a>
### 10499-266473c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31497
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 10b9bead1095:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 31 seconds
(5/15) Running awscli tests ... done in 3 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 35 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-6ub0dbqygyh3gjtu",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1023,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 39 seconds
(10/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... FAILED in 19 minutes and 4 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-cc66ccf8-1d94-4795-b885-bbf5eb2b7f89",
    "object_name": "3803ec17-d6b2-4f6e-8018-b7dc6647027d"
  },
  "message": "InvalidSizeError: message: Data written 0 bytes is smaller than the specified size 11534336 bytes",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 147, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1625, in test_thread_safe\n    raise exceptions[0]\n  File \"/mint/run/core/minio-py/tests.py\", line 1585, in get_object_and_check\n    _CLIENT.fget_object(bucket_name, object_name, local_file)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 816, in fget_object\n    raise InvalidSizeError(msg)\nminio.error.InvalidSizeError: InvalidSizeError: message: Data written 0 bytes is smaller than the specified size 11534336 bytes\n",
  "duration": 40041
}
(10/15) Running s3cmd tests ... done in 2 minutes and 16 seconds
(11/15) Running s3select tests ... done in 41 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10499-266473c

2020-09-17 22:43 UTC, harshavardhana requested changes

2020-09-17 22:43 UTC, harshavardhana commented on cmd/tree-walk.go
> +			return false
```suggestion
			return HasSuffix(entries[i], globalDirSuffix)
```

2020-09-17 23:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#6ee2ddd1-906b-43f9-bd5e-0b23d8390b8f) |
| mint-erasure.sh | :x: [more...](#290f1c5e-11f3-4e4c-8180-19de2a6b9767) |
<a name="6ee2ddd1-906b-43f9-bd5e-0b23d8390b8f"></a>
### 10499-d09785d/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30838
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e85c25711f45:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 49 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 44 seconds
(9/15) Running minio-go tests ... done in 7 minutes and 41 seconds
(10/15) Running minio-java tests ... done in 10 minutes and 51 seconds
(11/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(12/15) Running minio-py tests ... done in 19 minutes and 12 seconds
(13/15) Running s3cmd tests ... done in 2 minutes and 19 seconds
(14/15) Running s3select tests ... FAILED in 18 seconds
{
  "name": "s3select:test_csv_output_quote_char",
  "function": "select_object_content(bucket_name, object_name, opts)",
  "args": {
    "bucket_name": "s3select-test-21eec9c6-2212-4eac-832e-905398b26c92"
  },
  "duration": 3403,
  "message": "Test test_3 unexpectedly failed with: 'event-type'",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/s3select/csv.py\", line 39, in test_sql_api\n    for d in data.stream(10*1024):\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select/reader.py\", line 211, in stream\n    message = self.__extract_message()\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select/reader.py\", line 161, in __extract_message\n    event_type = header_map[\"event-type\"]\nKeyError: 'event-type'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./tests.py\", line 56, in main\n    test_csv_output_custom_quote_char(client, log_output)\n  File \"/mint/run/core/s3select/csv.py\", line 180, in test_csv_output_custom_quote_char\n    input_data, sql_opts, expected_output)\n  File \"/mint/run/core/s3select/csv.py\", line 45, in test_sql_api\n    'Test {} unexpectedly failed with: {}'.format(test_name, select_err))\nValueError: Test test_3 unexpectedly failed with: 'event-type'\n",
  "status": "FAIL"
}
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="290f1c5e-11f3-4e4c-8180-19de2a6b9767"></a>
### 10499-d09785d/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30744
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 381ecbaaa5ac:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 49 seconds
(8/15) Running minio-dotnet tests ... done in 36 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 18 seconds
(10/15) Running minio-java tests ... done in 45 seconds
(11/15) Running minio-js tests ... FAILED in 10 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 11,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(11/15) Running minio-py tests ... done in 2 minutes and 8 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10499-d09785d

2020-09-18 00:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#3313db59-a636-4a5d-9aea-91234b8d7e81) |
| mint-zoned.sh | :x: [more...](#477d6221-e64e-4e8e-9c10-540325aa632c) |
<a name="477d6221-e64e-4e8e-9c10-540325aa632c"></a>
### 10499-b8f7752/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30996
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25508cc8572e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 7 seconds
(8/15) Running minio-dotnet tests ... done in 53 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 46 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 25 seconds
(11/15) Running minio-js tests ... done in 52 seconds
(12/15) Running minio-py tests ... done in 3 minutes and 39 seconds
(13/15) Running s3cmd tests ... FAILED in 22 seconds
{
  "name": "s3cmd",
  "duration": "10753",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 9 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="3313db59-a636-4a5d-9aea-91234b8d7e81"></a>
### 10499-b8f7752/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30161
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ca9bbc700bf4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 2 minutes and 46 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 5 minutes and 55 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 51 seconds
{
  "args": {
    "bucketName": "minio-go-test-bauzdubxyffahrxu",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1054,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 11 minutes and 18 seconds
(10/15) Running minio-js tests ... FAILED in 45 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 20 minutes and 30 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 26 seconds
(12/15) Running s3select tests ... done in 40 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10499-b8f7752

2020-09-18 20:12 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10499-9778539

2020-09-18 20:16 UTC, harshavardhana requested changes

2020-09-18 20:16 UTC, harshavardhana commented on cmd/server_test.go
> +	// suite.TestCors(c)
can you enable all the tests? @krishnasrinivas they all seem to be running now.

2020-09-19 03:44 UTC, harshavardhana requested changes

2020-09-19 03:44 UTC, harshavardhana commented on cmd/server_test.go
> +	// suite.TestCors(c)
```suggestion
	suite.TestCors(c)
```

2020-09-19 03:44 UTC, harshavardhana commented on cmd/server_test.go
> +	// suite.TestObjectMultipart(c)
```suggestion
	suite.TestBucketPolicy(c)
	suite.TestDeleteBucket(c)
	suite.TestDeleteBucketNotEmpty(c)
	suite.TestDeleteMultipleObjects(c)
	suite.TestDeleteObject(c)
	suite.TestNonExistentBucket(c)
	suite.TestEmptyObject(c)
	suite.TestBucket(c)
	suite.TestObjectGetAnonymous(c)
	suite.TestMultipleObjects(c)
	suite.TestHeader(c)
	suite.TestPutBucket(c)
	suite.TestCopyObject(c)
	suite.TestPutObject(c)
	suite.TestListBuckets(c)
	suite.TestValidateSignature(c)
	suite.TestSHA256Mismatch(c)
	suite.TestPutObjectLongName(c)
	suite.TestNotBeAbleToCreateObjectInNonexistentBucket(c)
	suite.TestHeadOnObjectLastModified(c)
	suite.TestHeadOnBucket(c)
	suite.TestContentTypePersists(c)
	suite.TestPartialContent(c)
	suite.TestListObjectsHandler(c)
	suite.TestListObjectsHandlerErrors(c)
	suite.TestPutBucketErrors(c)
	suite.TestGetObjectLarge10MiB(c)
	suite.TestGetObjectLarge11MiB(c)
	suite.TestGetPartialObjectMisAligned(c)
	suite.TestGetPartialObjectLarge11MiB(c)
	suite.TestGetPartialObjectLarge10MiB(c)
	suite.TestGetObjectErrors(c)
	suite.TestGetObjectRangeErrors(c)
	suite.TestObjectMultipartAbort(c)
	suite.TestBucketMultipartList(c)
	suite.TestValidateObjectMultipartUploadID(c)
	suite.TestObjectMultipartListError(c)
	suite.TestObjectValidMD5(c)
	suite.TestObjectMultipart(c)
```

2020-09-19 03:45 UTC, harshavardhana requested changes

2020-09-19 03:45 UTC, harshavardhana commented on cmd/tree-walk.go
> +		if HasSuffix(entry, globalDirSuffixWithSlash) {
Please add comments in this portion of the code @krishnasrinivas

2020-09-19 03:45 UTC, harshavardhana commented on cmd/tree-walk.go
> +		return first < second
Please add comments in this portion of the code @krishnasrinivas

2020-09-19 03:45 UTC, harshavardhana commented on cmd/tree-walk.go
> +	sort.Slice(entries, func(i, j int) bool {
Please add comments in this portion of the code @krishnasrinivas

2020-09-19 04:08 UTC, harshavardhana commented
@krishnasrinivas the tests don't pass yet can you fix them?

Also, I did my Hadoop tests the migration jobs seem to run fine from hadoop to MinIO without much trouble.

2020-09-19 04:47 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10499-3be248e

2020-09-19 09:09 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#bb58cb0e-e511-432d-b532-1efb50aefbc9) |
<a name="bb58cb0e-e511-432d-b532-1efb50aefbc9"></a>
### 10499-6c421c2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31429
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4167803e4cd8:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 15 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 2 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 53 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 44 seconds
(9/15) Running minio-go tests ... FAILED in 8 minutes and 7 seconds
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x83fd53]

goroutine 1 [running]:
main.testGetObjectModified()
	/mint/run/core/minio-go/main.go:5688 +0xc63
main.main()
	/mint/run/core/minio-go/main.go:11269 +0x1e0
(9/15) Running minio-java tests ... done in 10 minutes and 49 seconds
(10/15) Running minio-js tests ... FAILED in 45 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 15 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 12 seconds
(12/15) Running s3select tests ... done in 41 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:10499-6c421c2

2020-09-19 15:39 UTC, harshavardhana approved these changes

2020-09-19 15:39 UTC, merged