Optimize FileInfo(Version) transfer
minio/minio pull request #10775
Opened 2020-10-28 13:48 UTC by klauspost

## Motivation and Context

File Info decoding in particular is showing up as a major allocator and time consumer.

Switch to messagepack for cross-server transfers:

```
MSGP:

Size: 945 bytes

BenchmarkEncodeFileInfoMsgp-32    	 1558444	       866 ns/op	   1.16 MB/s	       0 B/op	       0 allocs/op
BenchmarkDecodeFileInfoMsgp-32    	  479968	      2487 ns/op	   0.40 MB/s	     848 B/op	      18 allocs/op

GOB (existing):

Size: 1409 bytes

BenchmarkEncodeFileInfoGOB-32    	  333339	      3237 ns/op	   0.31 MB/s	     576 B/op	      19 allocs/op
BenchmarkDecodeFileInfoGOB-32    	   20869	     57837 ns/op	   0.02 MB/s	   16439 B/op	     428 allocs/op
```

Benchmark included. MB/s is FileInfo objects per second (1 byte per operation).

## How to test this PR?

Standard server operation should cover this.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2020-10-28 15:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#df81ff45-3fb4-45bb-8b9e-8acd71d26385) |
| mint-gateway-azure.sh | :x: [more...](#db136545-ac82-4d32-9b3d-8f78cbb1892b) |
| mint-dist-erasure.sh | :x: [more...](#0885b3b8-2f59-401f-8601-34ccf229acee) |
| mint-zoned.sh | :x: [more...](#651e5ece-d1f0-4e95-9099-dab56788f8c3) |
<a name="651e5ece-d1f0-4e95-9099-dab56788f8c3"></a>
### 10775-246d998/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32658
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 89fb56714f7a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-php",
  "function": "anonDeleteObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5f99868c03644",
    "Object": "obj1"
  },
  "duration": "161",
  "status": "FAIL",
  "error": "Incorrect response deleteObjects anonymous\n                                call for aws-sdk-php-5f99868c03644"
}
(3/15) Running aws-sdk-ruby tests ... done in 5 seconds
(4/15) Running awscli tests ... done in 1 minutes and 14 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... FAILED in 1 seconds
{
  "name": "mc",
  "duration": "308",
  "function": "test_put_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-25305 --quiet --no-color rm myminio/mc-test-bucket-29085/mc-test-object-17078  >>> \nRemoving `myminio/mc-test-bucket-29085/mc-test-object-17078`.\nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-29085/mc-test-object-17078`. We encountered an internal error, please try again."
}
(6/15) Running minio-dotnet tests ... done in 44 seconds
(7/15) Running minio-go tests ... FAILED in 37 seconds
{
  "args": {
    "bucketName": "minio-go-test-hifidzpeac2cze1h"
  },
  "duration": 7681,
  "error": "We encountered an internal error, please try again.",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}
(7/15) Running minio-java tests ... FAILED in 16 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 365,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-2lcro8k, objectName = null, resource = /minio-java-test-2lcro8k, requestId = 16422FF5D0DF609F, hostId = 03749551-c194-4c45-a658-441908bef51f)\nrequest={method=DELETE, url=http://minio-dev8.minio.io:32658/minio-java-test-2lcro8k, headers=Host: minio-dev8.minio.io:32658\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/7.1.4\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20201028T145910Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201028/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 328\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-10-28T14-50-16Z\nVary: Origin\nX-Amz-Request-Id: 16422FF5D0DF609F\nX-Xss-Protection: 1; mode=block\nDate: Wed, 28 Oct 2020 14:59:10 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1135), io.minio.MinioClient.execute(MinioClient.java:935), io.minio.MinioClient.executeDelete(MinioClient.java:1225), io.minio.MinioClient.removeBucket(MinioClient.java:4637), FunctionalTest.testListObjects(FunctionalTest.java:1437), FunctionalTest.listObjects_test(FunctionalTest.java:1449), FunctionalTest.runTests(FunctionalTest.java:3811), FunctionalTest.main(FunctionalTest.java:4058)]"
}
(7/15) Running minio-js tests ... FAILED in 1 minutes and 5 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 17,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(7/15) Running minio-py tests ... FAILED in 3 minutes and 34 seconds
{
  "name": "minio-py:test_remove_objects",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-34f7ae69-cc39-4935-9bea-146fc8186f2d",
    "objects_iter": [
      "prefix-0",
      "prefix-1",
      "prefix-2",
      "prefix-3",
      "prefix-4",
      "prefix-5",
      "prefix-6",
      "prefix-7",
      "prefix-8",
      "prefix-9"
    ]
  },
  "message": "Remove objects err: unable to remove object prefix-0; code: InternalError, message: We encountered an internal error, please try again.",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1865, in _test_remove_objects\n    raise ValueError(\"Remove objects err: {}\".format(err))\nValueError: Remove objects err: unable to remove object prefix-0; code: InternalError, message: We encountered an internal error, please try again.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 145, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1875, in test_remove_objects\n    _test_remove_objects(log_entry)\n  File \"/mint/run/core/minio-py/tests.py\", line 1869, in _test_remove_objects\n    raise ValueError(\"Remove objects err: {}\".format(err))\nValueError: Remove objects err: unable to remove object prefix-0; code: InternalError, message: We encountered an internal error, please try again.\n",
  "duration": 652
}
(7/15) Running s3cmd tests ... FAILED in 21 seconds
{
  "name": "s3cmd",
  "duration": "9832",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(7/15) Running s3select tests ... done in 9 seconds
(8/15) Running security tests ... done in 0 seconds

Executed 8 out of 15 tests successfully.
```
<a name="df81ff45-3fb4-45bb-8b9e-8acd71d26385"></a>
### 10775-246d998/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32361
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a55cd1139e40:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Runnin [...]

2020-10-28 16:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2ca988c4-e24e-4fdd-bd22-64b74c9808cf) |
| mint-gateway-azure.sh | :x: [more...](#aad257f4-8f75-46f7-9dcd-cf6fd1d8d387) |
| mint-dist-erasure.sh | :x: [more...](#396162c2-1815-48b3-9bde-65cbae1f4247) |
| mint-zoned.sh | :x: [more...](#fb49317e-9767-4389-b19c-04db7f48b882) |
<a name="fb49317e-9767-4389-b19c-04db7f48b882"></a>
### 10775-5c8cdee/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32461
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b49440830f93:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 18 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 6 seconds
(8/15) Running minio-dotnet tests ... done in 48 seconds
(9/15) Running minio-go tests ... FAILED in 45 seconds
{
  "args": {
    "bucketName": "minio-go-test-bcph32pqtk0xxmt3"
  },
  "duration": 13860,
  "error": "We encountered an internal error, please try again.",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 14 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 353,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = SlowDown, message = Please reduce your request, bucketName = minio-java-test-17n6a14, objectName = null, resource = /minio-java-test-17n6a14, requestId = 164234616DB80738, hostId = a5a196d5-0fb2-474c-b6c4-97268fa4bc2d)\nrequest={method=DELETE, url=http://minio-dev8.minio.io:32461/minio-java-test-17n6a14, headers=Host: minio-dev8.minio.io:32461\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/7.1.4\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20201028T162010Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201028/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 305\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2020-10-28T16-07-15Z\nVary: Origin\nX-Amz-Request-Id: 164234616DB80738\nX-Xss-Protection: 1; mode=block\nDate: Wed, 28 Oct 2020 16:20:10 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1135), io.minio.MinioClient.execute(MinioClient.java:935), io.minio.MinioClient.executeDelete(MinioClient.java:1225), io.minio.MinioClient.removeBucket(MinioClient.java:4637), FunctionalTest.testListObjects(FunctionalTest.java:1437), FunctionalTest.listObjects_test(FunctionalTest.java:1449), FunctionalTest.runTests(FunctionalTest.java:3811), FunctionalTest.main(FunctionalTest.java:4058)]"
}
(9/15) Running minio-js tests ... FAILED in 1 minutes and 2 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 10,
  "status": "FAIL",
  "error": "S3Error: Please reduce your request at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... FAILED in 3 minutes and 30 seconds
{
  "name": "minio-py:test_remove_objects",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-458b526f-997d-4009-b638-06c11bae2cec",
    "objects_iter": [
      "prefix-0",
      "prefix-1",
      "prefix-2",
      "prefix-3",
      "prefix-4",
      "prefix-5",
      "prefix-6",
      "prefix-7",
      "prefix-8",
      "prefix-9"
    ]
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-458b526f-997d-4009-b638-06c11bae2cec, request_id: 164234A0CF8BE6BB, host_id: a5a196d5-0fb2-474c-b6c4-97268fa4bc2d, bucket_name: minio-py-test-458b526f-997d-4009-b638-06c11bae2cec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 145, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1875, in test_remove_objects\n    _test_remove_objects(log_entry)\n  File \"/mint/run/core/minio-py/tests.py\", line 1870, in _test_remove_objects\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 649, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 403, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 379, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-458b526f-997d-4009-b638-06c11bae2cec, request_id: 164234A0CF8BE6BB, host_id: a5a196d5-0fb2-474c-b6c4-97268fa4bc2d, bucket_name: minio-py-test-458b526f-997d-4009-b638-06c11bae2cec\n",
  "duration": 620
}
(9/15) Running s3cmd tests ... FAILED in 22 seconds
{
  "name": "s3cmd",
  "duration": "10486",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\ndelete: 's3://s3cmd-test-bucket-13110/datafile-0-b'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-1-MB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-1-b'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-1-kB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-1.03-MB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-10-MB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-10-kB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-100-kB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-11-MB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-129-MB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-33-kB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-5-MB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-5243880-b'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-6-MB'\ndelete: 's3://s3cmd-test-bucket-13110/datafile-65-MB'\nERROR: S3 error: 409 (BucketNotEmpty): The bucket you tried to delete is not empty"
}
(9/15) Running s3select tests ... done in 8 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="aad257f4-8f75-46f7-9dcd-cf6fd1d8d387"></a>
### 10775-5c8cdee/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31950
ACCE [...]

2020-10-28 17:01 UTC, harshavardhana commented
looks like msgpack change is not working @klauspost 

> (9/15) Running minio-go tests ... FAILED in 1 minutes and 32 seconds
> {
>   "args": {
>     "bucketName": "minio-go-test-jhxz04bu521lpv02",
>     "objectName": "95kx9zec06htozj4jzo2a6ehnap0hq"
>   },
>   "duration": 427,
>   "function": "DeleteObjects()",
>   "message": "Unexpected versioning info, should not have any one ",
>   "name": "minio-go: testRemoveObjectsWithVersioning",
>   "status": "FAIL"
> }

2020-10-28 18:05 UTC, klauspost commented
@harshavardhana Yeah, I'll look at it tomorrow.

2020-10-29 15:50 UTC, klauspost commented
I suspect that is due to bloom filter race. Fix in https://github.com/minio/minio/pull/10775

2020-10-30 16:50 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 10775-a1155eb/gopath/src/github.com/minio
+ git -C 10775-a1155eb/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 10775-a1155eb/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 10775-a1155eb/gopath/src/github.com/minio/minio fetch --quiet minio pull/10775/head:pr10775
+ git -C 10775-a1155eb/gopath/src/github.com/minio/minio checkout --quiet pr10775
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/10775-a1155eb/gopath
+ make -C 10775-a1155eb/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: downloading github.com/minio/minio-go/v7 v7.0.6-0.20200929220449-755b5633803a
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/klauspost/compress v1.10.3
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading gopkg.in/olivere/elastic.v5 v5.0.86
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/nats-io/stan.go v0.7.0
go: downloading github.com/ncw/directio v1.0.5
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading github.com/minio/md5-simd v1.1.0
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading google.golang.org/api v0.5.0
go: downloading go.etcd.io/etcd/v3 v3.3.0-rc.0.0.20200707003333-58bb8ae09f8e
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading github.com/lib/pq v1.8.0
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/minio/sio v0.2.1
go: downloading golang.org/x/crypto v0.0.0-20200820211705-5c72a883971a
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/fatih/structs v1.1.0
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading google.golang.org/grpc v1.26.0
go: downloading github.com/klauspost/reedsolomon v1.9.9
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/nats-io/nkeys v0.1.4
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/cheggaaa/pb v1.0.28
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading github.com/golang/protobuf v1.4.0
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading go.uber.org/zap v1.14.1
go: downloading github.com/mailru/easyjson v0.7.1
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/mattn/go-isatty v0.0.8
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/miekg/dns v1.1.8
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/rs/xid v1.2.1
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/coreos/go-systemd/v22 v22.0.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/eapache/go-resiliency v1.1.0
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading golang.org/x/sys v0.0.0-20200915084602-288bc346aa39
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/prometheus/common v0.4.1
go: downloading github.com/djherbis/atime v1.0.0
go: downloading google.golang.org/protobuf v1.22.0
go: downloading go.uber.org/multierr v1.5.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/coredns/coredns v1.4.0
go: downloading go.uber.org/atomic v1.6.0
go: downloading github.com/tinylib/msgp v1.1.2
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/minio/simdjson-go v0.1.5
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/prometheus/procfs v0.0.8
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/mattn/go-runewidth v0.0.2
go: downloading go.opencensus.io v0.22.3
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/klauspost/pgzip v1.2.1
go: downloading github.com/gorilla/handlers v1.4.2
go: downloading github.com/beorn7/perks v1.0.0
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading githu [...]

2020-10-30 16:55 UTC, harshavardhana commented
> # github.com/minio/minio/cmd
> cmd/metacache-entries.go:125:4: cannot use os.ModeDir (type os.FileMode) as type uint32 in field value
> cmd/metacache-entries.go:149:6: cannot use os.ModeDir (type os.FileMode) as type uint32 in field value
> make: *** [build] Error 2

@klauspost

2020-10-30 16:57 UTC, klauspost commented
@harshavardhana on it :)

2020-11-02 16:50 UTC, harshavardhana requested changes

2020-11-02 16:50 UTC, harshavardhana commented on cmd/storage-rest-server.go
> +			if msgp.Cause(err) != io.EOF && i != totalVersions-1 {
```suggestion
			if msgp.Cause(err) != io.EOF {
```

EOF might occur since DeleteVersions doesn't populate `ErasureInfo` field

2020-11-02 17:07 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#45a8f845-f3f3-4e9b-8a28-f0c5cff6d8ba) |
| mint-gateway-azure.sh | :x: [more...](#be180c30-2fe8-469f-b288-19c1e9c5f1a4) |
| mint-dist-erasure.sh | :x: [more...](#20ad2d5f-8f99-490f-bfcb-a252c9e6144f) |
| mint-zoned.sh | :x: [more...](#8154f9e2-3794-4d33-af7e-e74a647cbd12) |
<a name="20ad2d5f-8f99-490f-bfcb-a252c9e6144f"></a>
### 10775-2b29f60/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31423
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 972f9ae24c24:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 25 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 4 seconds
(9/15) Running minio-go tests ... FAILED in 39 seconds
{
  "args": {
    "bucketName": "minio-go-test-xyu2rwh9jka2z3af"
  },
  "duration": 10674,
  "error": "We encountered an internal error, please try again.",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 15 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 357,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-eq200o, objectName = null, resource = /minio-java-test-eq200o, requestId = 1643BD900E4A40E5, hostId = 0900a98b-e558-480a-9608-460428bca2ed)\nrequest={method=DELETE, url=http://minio-dev8.minio.io:31423/minio-java-test-eq200o, headers=Host: minio-dev8.minio.io:31423\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/7.1.4\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20201102T162518Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201102/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 326\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-11-02T16-14-26Z\nVary: Origin\nX-Amz-Request-Id: 1643BD900E4A40E5\nX-Xss-Protection: 1; mode=block\nDate: Mon, 02 Nov 2020 16:25:18 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1135), io.minio.MinioClient.execute(MinioClient.java:935), io.minio.MinioClient.executeDelete(MinioClient.java:1225), io.minio.MinioClient.removeBucket(MinioClient.java:4637), FunctionalTest.testListObjects(FunctionalTest.java:1437), FunctionalTest.listObjects_test(FunctionalTest.java:1449), FunctionalTest.runTests(FunctionalTest.java:3811), FunctionalTest.main(FunctionalTest.java:4058)]"
}
(9/15) Running minio-js tests ... FAILED in 56 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 31,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... FAILED in 3 minutes and 55 seconds
{
  "name": "minio-py:test_remove_objects",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-b370d911-34af-4a06-80c8-80c13a56e29d",
    "objects_iter": [
      "prefix-0",
      "prefix-1",
      "prefix-2",
      "prefix-3",
      "prefix-4",
      "prefix-5",
      "prefix-6",
      "prefix-7",
      "prefix-8",
      "prefix-9"
    ]
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-b370d911-34af-4a06-80c8-80c13a56e29d, request_id: 1643BDD3D42DCC6E, host_id: 0900a98b-e558-480a-9608-460428bca2ed, bucket_name: minio-py-test-b370d911-34af-4a06-80c8-80c13a56e29d",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 145, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1875, in test_remove_objects\n    _test_remove_objects(log_entry)\n  File \"/mint/run/core/minio-py/tests.py\", line 1870, in _test_remove_objects\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 649, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 403, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 379, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-b370d911-34af-4a06-80c8-80c13a56e29d, request_id: 1643BDD3D42DCC6E, host_id: 0900a98b-e558-480a-9608-460428bca2ed, bucket_name: minio-py-test-b370d911-34af-4a06-80c8-80c13a56e29d\n",
  "duration": 678
}
(9/15) Running s3cmd tests ... FAILED in 45 seconds
{
  "name": "s3cmd",
  "duration": "27195",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\ndelete: 's3://s3cmd-test-bucket-21737/datafile-0-b'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-1-MB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-1-b'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-1-kB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-1.03-MB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-10-MB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-10-kB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-100-kB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-11-MB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-129-MB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-33-kB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-5-MB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-5243880-b'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-6-MB'\ndelete: 's3://s3cmd-test-bucket-21737/datafile-65-MB'\nERROR: S3 error: 409 (BucketNotEmpty): The bucket you tried to delete is not empty"
}
(9/15) Running s3select tests ... done in 8 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="be180c30-2fe8-469f-b288-19c1e9c5f1a4"></a>
### 10775-2b29f60/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio. [...]

2020-11-02 18:18 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3fc636a3-0bca-4caa-b81c-2fa96bc52386) |
| mint-gateway-s3.sh | :x: [more...](#03aa707b-d438-4ded-987a-720589846c76) |
| mint-gateway-azure.sh | :x: [more...](#af34caa0-befd-431c-9d3b-debb30dd7943) |
| mint-dist-erasure.sh | :x: [more...](#eef46100-009e-4fe0-bf79-3557a9203153) |
| mint-zoned.sh | :x: [more...](#49d1e5a9-0013-4bc1-a705-27a231c4e205) |
<a name="af34caa0-befd-431c-9d3b-debb30dd7943"></a>
### 10775-5c61f2c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30345
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 14a75f8902b6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 19 seconds
(4/15) Running aws-sdk-ruby tests ... done in 22 seconds
(5/15) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 1439,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 29 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 48 seconds
{
  "args": {
    "bucketName": "minio-go-test-eyqozl5iy6ei6npy",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1045,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 10 minutes and 34 seconds
(9/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 19 minutes and 40 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 15 seconds
(11/15) Running s3select tests ... done in 39 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="3fc636a3-0bca-4caa-b81c-2fa96bc52386"></a>
### 10775-5c61f2c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30377
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 09b91a7a5d31:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 25 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 33 seconds
(8/15) Running minio-dotnet tests ... done in 59 seconds
(9/15) Running minio-go tests ... FAILED in 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-nyfdi5lmj03yi6ra"
  },
  "duration": 14886,
  "error": "We encountered an internal error, please try again.",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 18 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 1054,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-ra0iv3, objectName = null, resource = /minio-java-test-ra0iv3, requestId = 1643C1844C8848CA, hostId = 1b06ca3c-99f5-4d9b-af62-3329dc5be324)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:30377/minio-java-test-ra0iv3, headers=Host: minio-dev4.minio.io:30377\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/7.1.4\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20201102T173746Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201102/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 326\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-11-02T17-26-59Z\nVary: Origin\nX-Amz-Request-Id: 1643C1844C8848CA\nX-Xss-Protection: 1; mode=block\nDate: Mon, 02 Nov 2020 17:37:46 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1135), io.minio.MinioClient.execute(MinioClient.java:935), io.minio.MinioClient.executeDelete(MinioClient.java:1225), io.minio.MinioClient.removeBucket(MinioClient.java:4637), FunctionalTest.testListObjects(FunctionalTest.java:1437), FunctionalTest.listObjects_test(FunctionalTest.java:1449), FunctionalTest.runTests(FunctionalTest.java:3811), FunctionalTest.main(FunctionalTest.java:4058)]"
}
(9/15) Running minio-js tests ... FAILED in 58 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 11,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... FAILED in 3 minutes and 26 seconds
{
  "name": "minio-py:test_remove_objects",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-20b9aeba-9727-4f79-9035-cc4c5e553028",
    "objects_iter": [
      "prefix-0",
      "prefix-1",
      "prefix-2",
      "pr [...]

2020-11-02 19:32 UTC, klauspost commented
@harshavardhana Thanks. Forgot to push master merge myself. I will go through the code again.

2020-11-02 20:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#1d8fae90-b396-45df-a1d4-7a65239e5b26) |
<a name="1d8fae90-b396-45df-a1d4-7a65239e5b26"></a>
### 10775-5654799/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31175
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp adb3af9ee409:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 27 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 59 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 22 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 48 seconds
{
  "args": {
    "bucketName": "minio-go-test-bguusjtb9k45eg2o",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1166,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 27 seconds
(10/15) Running minio-js tests ... FAILED in 48 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 27 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 14 seconds
(12/15) Running s3select tests ... done in 39 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-11-02 20:50 UTC, harshavardhana approved these changes

2020-11-03 01:07 UTC, merged

2020-11-03 03:05 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#ccd4c7ad-86ec-459b-b450-a73b3562bae9) |
<a name="ccd4c7ad-86ec-459b-b450-a73b3562bae9"></a>
### 10775-72e289b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31931
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 54e835f9b92a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 32 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 3 minutes and 1 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 21 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 42 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 50 seconds
{
  "args": {
    "bucketName": "minio-go-test-kc102i25hgs2v5ey",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1092,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 44 seconds
(10/15) Running minio-js tests ... FAILED in 48 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 19 minutes and 25 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 33 seconds
(12/15) Running s3select tests ... done in 39 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally