re-use remote transports in Peer,Storage,Locker clients
minio/minio pull request #10788
Opened 2020-10-30 03:47 UTC by harshavardhana

## Description
re-use remote transports in Peer,Storage,Locker clients

## Motivation and Context
initialize one transport per remote endpoint, this
allows re-using the same connection pool for all
internode communication

## How to test this PR?
A major change of sort for optimized connection usage

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-10-30 04:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#9351f9c2-1e03-4ffb-8212-c14dd4e4a1aa) |
<a name="9351f9c2-1e03-4ffb-8212-c14dd4e4a1aa"></a>
### 10788-8dc8b3e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32304
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ff2fd170e7d2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 1 seconds
(4/15) Running aws-sdk-ruby tests ... done in 22 seconds
(5/15) Running awscli tests ... done in 2 minutes and 47 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 17 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-cjfottczwvl6be6p",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1046,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 19 seconds
(10/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 1 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 19 seconds
(12/15) Running s3select tests ... done in 38 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-10-30 08:10 UTC, klauspost approved these changes
LGTM. A bit more than I expected from this change. Nice!

2020-10-30 09:02 UTC, klauspost commented
@harshavardhana 

This error message isn't really that clear:
```
Error: WARNING: Expected number of all hosts (8) to be remote +1 (4) (*errors.errorString)
       4: d:\minio\minio\cmd\peer-rest-client.go:870:cmd.newPeerRestClients()
       3: d:\minio\minio\cmd\notification.go:1287:cmd.NewNotificationSys()
       2: d:\minio\minio\cmd\server-main.go:160:cmd.newAllSubsystems()
       1: d:\minio\minio\cmd\server-main.go:397:cmd.serverMain()
Waiting for all MinIO sub-systems to be initialized.. lock acquired
```

This should be actionable or help in some way, listing why, etc.

Maybe `WARNING: Only 4 of 8 hosts are remote. For server failover at least 5 should be remote.`

2020-10-30 11:09 UTC, klauspost commented
@harshavardhana Drive listing in mc admin is wrong: `4,632 drives online, 0 drives offline`.

2020-10-30 11:39 UTC, klauspost requested changes, later dismissed
In subnet no 1073 the error is reported in a "good" setup and number of drives are wrong.

This needs some tweaks.

2020-10-30 16:28 UTC, harshavardhana commented
@klauspost what is your command line here?

2020-10-31 00:19 UTC, harshavardhana commented
all the issues mentioned here are resolved @klauspost PTAL

2020-10-31 01:11 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8a9fd5d5-48be-4195-95fc-761f77402082) |
| mint-gateway-azure.sh | :x: [more...](#410d3c51-ef90-4026-823d-d6d1d497f2bd) |
| mint-zoned.sh | :x: [more...](#25bd2331-89ef-4c15-9300-c1db6b4663f7) |
<a name="25bd2331-89ef-4c15-9300-c1db6b4663f7"></a>
### 10788-0438b18/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30184
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 061f7cbc3a1d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 28 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... FAILED in 4 seconds
{
  "name": "mc",
  "duration": "473",
  "function": "test_put_object_with_metadata",
  "status": "FAIL",
  "error": "unable to put object with metadata"
}
(7/15) Running minio-dotnet tests ... done in 1 minutes and 10 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 45 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 51 seconds
(10/15) Running minio-js tests ... FAILED in 18 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-8212cd9c-eda7-46d8-8cf3-e5fc2142a473",
  "duration": 14,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 3 minutes and 40 seconds
(11/15) Running s3cmd tests ... done in 23 seconds
(12/15) Running s3select tests ... done in 8 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="8a9fd5d5-48be-4195-95fc-761f77402082"></a>
### 10788-0438b18/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32053
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 147663028c2d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 26 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 31 seconds
{
  "name": "mc",
  "duration": "5662",
  "function": "test_copy_object_preserve_filesystem_attr",
  "status": "FAIL",
  "error": "unable to put object with file system attribute"
}
(7/15) Running minio-dotnet tests ... done in 48 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 22 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 50 seconds
(10/15) Running minio-js tests ... done in 55 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 33 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="410d3c51-ef90-4026-823d-d6d1d497f2bd"></a>
### 10788-0438b18/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32194
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ca352dd5ab2d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 10 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{"name": "awscli", "duration": 2155, "function": "aws --endpoint-url http://minio-dev7.minio.io:32194 s3api put-object --body /mint/data/datafile-1-kB --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-1-kB\n", "status": "FAIL", "error": "usage: 
Note: AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use. For more information, see the AWS CLI version 2 installation instructions at: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.htmlusage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 42 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 48 seconds
{
  "args": {
    "bucketName": "minio-go-test-exojgmx4rqvgiwsw",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1213,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 10 minutes and 48 seconds
(9/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1 [...]

2020-10-31 01:29 UTC, poornas approved these changes
LGTM

2020-10-31 05:28 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#058eab24-162c-4854-bebb-115613943e44) |
| mint-gateway-azure.sh | :x: [more...](#a7fe82f4-8b87-43cb-bc1c-34a633402123) |
| mint-zoned.sh | :x: [more...](#a5bbb862-9ee9-4b55-9d3d-66c6613dfc75) |
<a name="a7fe82f4-8b87-43cb-bc1c-34a633402123"></a>
### 10788-63ec945/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32126
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fde3f9c59d57:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 12 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 51 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 25 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-1ja41jnbxy4pxykq",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1041,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 19 seconds
(10/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 4 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 13 seconds
(12/15) Running s3select tests ... done in 38 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="a5bbb862-9ee9-4b55-9d3d-66c6613dfc75"></a>
### 10788-63ec945/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31136
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 255bd7d92f53:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 2 minutes and 14 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 4 seconds
{
  "name": "mc",
  "duration": "383",
  "function": "test_put_object_with_metadata",
  "status": "FAIL",
  "error": "unable to put object with metadata"
}
(7/15) Running minio-dotnet tests ... done in 52 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 39 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 52 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 0 seconds
(11/15) Running minio-py tests ... done in 4 minutes and 8 seconds
(12/15) Running s3cmd tests ... FAILED in 20 seconds
{
  "name": "s3cmd",
  "duration": "9372",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "sync and list differs"
}
(12/15) Running s3select tests ... done in 8 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="058eab24-162c-4854-bebb-115613943e44"></a>
### 10788-63ec945/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31866
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2008aacd1d90:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... FAILED in 4 seconds
{
  "name": "mc",
  "duration": "566",
  "function": "test_put_object_with_metadata",
  "status": "FAIL",
  "error": "unable to put object with metadata"
}
(7/15) Running minio-dotnet tests ... done in 1 minutes and 12 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 22 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 41 seconds
(10/15) Running minio-js tests ... FAILED in 27 seconds
{
  "name": "minio-js",
  "function": "getBucketPolicy(bucketName, cb)",
  "args": "bucketName:minio-js-test-c841521a-bd0d-43b9-8dbb-343502343729",
  "duration": 9,
  "status": "FAIL",
  "error": "S3Error: The bucket policy does not exist at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 3 minutes and 28 seconds
(11/15) Running s3cmd tests ... done in 25 seconds
(12/15) Running s3select tests ... done in 13 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-10-31 08:09 UTC, harshavardhana commented
> (7/15) Running mc tests ... FAILED in 4 seconds
> {
>   "name": "mc",
>   "duration": "383",
>   "function": "test_put_object_with_metadata",
>   "status": "FAIL",
>   "error": "unable to put object with metadata"
> }

Some strange problem introduced by this PR need to figure this out.

2020-10-31 08:36 UTC, harshavardhana commented
> Some strange problem introduced by this PR need to figure this out.

I shall verify this tomorrow my time.

2020-11-01 00:37 UTC, harshavardhana commented
I tried reproducing the issue seen here with `mc` but it looks strange that this change can cause this. I have tried reproducing it for last 3hrs and I am able to reproduce but have no idea what is the fix here. It almost looks like the request itself is not sent `mc` silently avoids sending the request to the server not sure why.

2020-11-01 01:09 UTC, harshavardhana commented
Found it looks like an issue with listing code there is a race with `mc stat` this seems to be aggravated by this change, perhaps introduced in the list caching change. For example

```
root@my-mint:/mint# /mint/run/core/mc/mc --config-dir /tmp/.mc-18298 --quiet --no-color --json stat myminio/mc-test-bucket-26464/mc-test-object-24919
root@my-mint:/mint# /mint/run/core/mc/mc --config-dir /tmp/.mc-18298 --quiet --no-color --json stat myminio/mc-test-bucket-26464/mc-test-object-24919
{
 "status": "success",
 "name": "mc-test-object-24919",
 "lastModified": "2020-10-14T02:06:42Z",
 "size": 1048576,
 "etag": "1f28021c1f2c5502a3b95329d80be3dc",
 "type": "file",
 "expires": "0001-01-01T00:00:00Z",
 "expiration": "0001-01-01T00:00:00Z",
 "expirationRuleID": "",
 "replicationStatus": "",
 "metadata": {
  "Content-Type": "application/octet-stream",
  "X-Amz-Meta-Key1": "val1",
  "X-Amz-Meta-Key2": "val2",
  "X-Amz-Meta-Mc-Attrs": "atime:1602641202#0/gid:0/gname:root/mode:33188/mtime:1602641202#0/uid:0/uname:root"
 }
}
```

The list goes to a different node due to load balancing in k8s the output is not available for some time.

2020-11-01 01:35 UTC, harshavardhana commented
Here is the output of two different commands one after the other @klauspost you can see the `mc` terminates because ListObjectsV2 doesn't respond with the `object` name when prefix=object-name is set.

```
st: minio-large-bucket-headless-dev:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20201101/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201101T012716Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 01 Nov 2020 01:27:16 GMT
Server: MinIO/DEVELOPMENT.2020-10-31T21-15-12Z
Vary: Origin
X-Amz-Request-Id: 16433DF9FF75752B
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  5.935486ms

mc: <DEBUG> HEAD /mc-test-bucket-2393/mc-test-object-30110 HTTP/1.1
Host: minio-large-bucket-headless-dev:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20201101/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201101T012716Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1048576
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Sun, 01 Nov 2020 01:27:16 GMT
Etag: "1f28021c1f2c5502a3b95329d80be3dc"
Last-Modified: Sun, 01 Nov 2020 01:27:05 GMT
Server: MinIO/DEVELOPMENT.2020-10-31T21-15-12Z
Vary: Origin
X-Amz-Meta-Key1: val1
X-Amz-Meta-Key2: val2
X-Amz-Meta-Mc-Attrs: atime:1602641202#0/gid:0/gname:root/mode:33188/mtime:1602641202#0/uid:0/uname:root
X-Amz-Request-Id: 16433DF9FFAE53CB
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  6.98001ms

mc: <DEBUG> GET /mc-test-bucket-2393/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=mc-test-object-30110 HTTP/1.1
Host: minio-large-bucket-headless-dev:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20201101/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201101T012716Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 326
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 01 Nov 2020 01:27:16 GMT
Server: MinIO/DEVELOPMENT.2020-10-31T21-15-12Z
Vary: Origin
X-Amz-Request-Id: 16433DFA0025E63B
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  6.885393ms

root@my-mint:/mint# /mint/run/core/mc/mc --config-dir /tmp/.mc-773 --quiet --no-color --json --debug stat myminio/mc-test-bucket-2393/mc-test-object-30110
mc: <DEBUG> GET /mc-test-bucket-2393/?location= HTTP/1.1
Host: minio-large-bucket-headless-dev:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20201101/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201101T012717Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 128
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 01 Nov 2020 01:27:17 GMT
Server: MinIO/DEVELOPMENT.2020-10-31T21-15-12Z
Vary: Origin
X-Amz-Request-Id: 16433DFA5FDDF9D7
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  6.931627ms

mc: <DEBUG> HEAD /mc-test-bucket-2393/mc-test-object-30110 HTTP/1.1
Host: minio-large-bucket-headless-dev:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20201101/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201101T012717Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1048576
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Sun, 01 Nov 2020 01:27:17 GMT
Etag: "1f28021c1f2c5502a3b95329d80be3dc"
Last-Modified: Sun, 01 Nov 2020 01:27:05 GMT
Server: MinIO/DEVELOPMENT.2020-10-31T21-15-12Z
Vary: Origin
X-Amz-Meta-Key1: val1
X-Amz-Meta-Key2: val2
X-Amz-Meta-Mc-Attrs: atime:1602641202#0/gid:0/gname:root/mode:33188/mtime:1602641202#0/uid:0/uname:root
X-Amz-Request-Id: 16433DFA601F8A4D
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  8.08868ms

mc: <DEBUG> GET /mc-test-bucket-2393/?delimiter=%2F&encoding-type=url&fetch-owner=true&list-type=2&prefix=mc-test-object-30110 HTTP/1.1
Host: minio-large-bucket-headless-dev:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20201101/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201101T012717Z
Accept-Encoding: gzip

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 658
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Date: Sun, 01 Nov 2020 01:27:17 GMT
Server: MinIO/DEVELOPMENT.2020-10-31T21-15-12Z
Vary: Origin
X-Amz-Request-Id: 16433DFA60A80E94
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  16.112384ms

mc: <DEBUG> HEAD /mc-test-bucket-2393/mc-test-object-30110 HTTP/1.1
Host: minio-large-bucket-headless-dev:9000
User-Agent: MinIO (linux; amd64) minio-go/v7.0.6 mc/2020-10-03T02:54:56Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20201101/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20201101T012717Z

mc: <DEBUG> HTTP/1.1 200 OK
Content-Length: 1048576
Accept-Ranges: bytes
Content-Security-Policy: block-all-mixed-content
Content-Type: application/octet-stream
Date: Sun, 01 Nov 2020 01:27:17 GMT
Etag: "1f28021c1f2c5502a3b95329d80be3dc"
Last-Modified: Sun, 01 Nov 2020 01:27:05 GMT
Server: MinIO/DEVELOPMENT.2020-10-31T21-15-12Z
Vary: Origin
X-Amz-Meta-Key1: val1
X-Amz-Meta-Key2: val2
X-Amz-Meta-Mc-Attrs: atime:1602641202#0/gid:0/gname:root/mode:33188/mtime:1602641202#0/uid:0/uname:root
X-Amz-Request-Id: 16433DFA61A4B9D4
X-Xss-Protection: 1; mode=block

mc: <DEBUG> Response Time:  8.117811ms

{
 "status": "success",
 "name": "mc-test-object-30110",
 "lastModified": "2020-10-14T02:06:42Z",
 "size": 1048576,
 "etag": "1f28021c1f2c5502a3b95329d80be3dc",
 "type": "file",
 "expires": "0001-01-01T00:00:00Z",
 "expiration": "0001-01-01T00:00:00Z",
 "expirationRuleID": "",
 "replicationStatus": "",
 "metadata": {
  "Content-Type": "application/octet-stream",
  "X-Amz-Meta-Key1": "val1",
  "X-Amz-Meta-Key2": "val2",
  "X-Amz-Meta-Mc-Attrs": "atime:1602641202#0/gid:0/gname:root/mode:33188/mtime:1602641202#0/uid:0/uname:root"
 }
}
```

2020-11-01 02:36 UTC, harshavardhana commented
There is some tiny race, hard to reproduce on my laptop.

2020-11-02 00:46 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0b5df154-eeef-4fee-bb0f-a93783596d18) |
| mint-gateway-azure.sh | :x: [more...](#ffdf525d-fe13-4117-8aea-3a732c65f05b) |
| mint-zoned.sh | :x: [more...](#88972f1b-eb4b-44cd-b79a-438837d91d03) |
<a name="0b5df154-eeef-4fee-bb0f-a93783596d18"></a>
### 10788-b28a1cf/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30299
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b20cd2c708d3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 44 seconds
{
  "name": "mc",
  "duration": "7550",
  "function": "test_copy_object_preserve_filesystem_attr",
  "status": "FAIL",
  "error": "unable to put object with file system attribute"
}
(7/15) Running minio-dotnet tests ... done in 1 minutes and 10 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 12 seconds
(9/15) Running minio-java tests ... 
Aborting Mint...
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30299
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b20cd2c708d3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 19 seconds
{
  "name": "mc",
  "duration": "5233",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(7/15) Running minio-dotnet tests ... done in 58 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 34 seconds
(9/15) Running minio-java tests ... 
Aborting Mint...
```
<a name="88972f1b-eb4b-44cd-b79a-438837d91d03"></a>
### 10788-b28a1cf/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31013
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7ac9ccd9a3ca:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 16 seconds
{
  "name": "mc",
  "duration": "4841",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(7/15) Running minio-dotnet tests ... done in 1 minutes and 17 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 36 seconds
(9/15) Running minio-java tests ... 
Aborting Mint...
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31013
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7ac9ccd9a3ca:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 23 seconds
{
  "name": "mc",
  "duration": "5895",
  "function": "test_copy_object_preserve_filesystem_attr",
  "status": "FAIL",
  "error": "unable to put object with file system attribute"
}
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 45 seconds
(9/15) Running minio-java tests ... 
Aborting Mint...
```
<a name="ffdf525d-fe13-4117-8aea-3a732c65f05b"></a>
### 10788-b28a1cf/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30801
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f3dfc8d3507d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 10 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 48 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 16 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 45 seconds
{
  "args": {
    "bucketName": "minio-go-test-6dpeqluyn09ypdk0",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1164,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 11 seconds
(10/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 76,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 17 minutes and 54 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 14 seconds
(12/15) Running s3select tests ... done in 38 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-11-02 00:48 UTC, harshavardhana commented
Pushed changes which should fix most problems in this PR

2020-11-02 04:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#04394b27-0819-4e4a-94a5-6a201b805b64) |
<a name="04394b27-0819-4e4a-94a5-6a201b805b64"></a>
### 10788-af74a11/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30654
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 204ad6d4533f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 21 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 53 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 30 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 46 seconds
{
  "args": {
    "bucketName": "minio-go-test-9zxj2e60f3svzt0n",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1026,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 10 minutes and 34 seconds
(10/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 77,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 27 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 14 seconds
(12/15) Running s3select tests ... done in 39 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-11-02 04:39 UTC, harshavardhana commented
PTAL @klauspost @poornas

2020-11-02 05:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e6f646a7-f799-4c28-80b2-67180943291e) |
<a name="e6f646a7-f799-4c28-80b2-67180943291e"></a>
### 10788-dfa252a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31522
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9aabf66fc753:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 23 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 52 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 31 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-p1szrowlvctmlj2o",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1185,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 11 minutes and 30 seconds
(10/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 85,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(10/15) Running minio-py tests ... done in 18 minutes and 39 seconds
(11/15) Running s3cmd tests ... done in 2 minutes and 15 seconds
(12/15) Running s3select tests ... done in 38 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-11-02 06:00 UTC, harshavardhana commented
> There is some tiny race, hard to reproduce on my laptop.

was not a race, after effect of this change in previous attempts.

2020-11-02 06:09 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#2b692599-73e5-4af6-94e0-511c3df8b60c) |
<a name="2b692599-73e5-4af6-94e0-511c3df8b60c"></a>
### 10788-d8ff6fc/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32414
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 246cdbe5ab03:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 23 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... FAILED in 48 seconds
{
  "name": "awscli",
  "duration": 1269,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 26 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 45 seconds
{
  "args": {
    "bucketName": "minio-go-test-l1l0gevrvfvmy65n",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1034,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 10 minutes and 36 seconds
(9/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 81,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:682:10) at endReadableNT (_stream_readable.js:1252:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 18 minutes and 52 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 22 seconds
(11/15) Running s3select tests ... done in 38 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-11-02 06:13 UTC, poornas approved these changes

2020-11-02 14:09 UTC, klauspost approved these changes

2020-11-02 15:43 UTC, merged