use argon2 with sync.Pool for better memory management
minio/minio pull request #11019
Opened 2020-12-03 02:44 UTC by harshavardhana

## Description
use argon2 with sync.Pool for better memory management

## Motivation and Context
Requires fork of upstream argon2 implementation, borrowing @aead work here from

https://gist.githubusercontent.com/aead/2f032134c1d08a3a05cb0e679a541416/raw/aa8f3ad07cef2eba93ea0e7b93e2693bcda7a52f/argon2.patch

## How to test this PR?
Verify with lots of users object-storage.loadAll() run every 5minutes doesn't allocate a lot, allowing
re-use for frequent use.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-12-03 02:45 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 11019-a44d7c5/gopath/src/github.com/minio
+ git -C 11019-a44d7c5/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 11019-a44d7c5/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 11019-a44d7c5/gopath/src/github.com/minio/minio fetch --quiet minio pull/11019/head:pr11019
+ git -C 11019-a44d7c5/gopath/src/github.com/minio/minio checkout --quiet pr11019
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/11019-a44d7c5/gopath
+ make -C 11019-a44d7c5/gopath/src/github.com/minio/minio --quiet
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/minio-go/v7 v7.0.6
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading github.com/klauspost/reedsolomon v1.9.9
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/klauspost/compress v1.11.3
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/shirou/gopsutil v2.20.9+incompatible
go: downloading golang.org/x/crypto v0.0.0-20201124201722-c8d3bf9c5392
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading gopkg.in/olivere/elastic.v5 v5.0.86
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/golang/protobuf v1.4.0
go: downloading github.com/prometheus/common v0.4.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading google.golang.org/protobuf v1.22.0
go: downloading github.com/beorn7/perks v1.0.0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/minio/sio v0.2.1
go: downloading golang.org/x/net v0.0.0-20200904194848-62affa334b73
go: downloading github.com/mailru/easyjson v0.7.1
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading go.etcd.io/etcd/v3 v3.3.0-rc.0.0.20200707003333-58bb8ae09f8e
go: downloading github.com/prometheus/procfs v0.0.8
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/fatih/color v1.9.0
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading github.com/tinylib/msgp v1.1.3
go: downloading golang.org/x/sys v0.0.0-20200915084602-288bc346aa39
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading google.golang.org/grpc v1.26.0
go: downloading github.com/minio/md5-simd v1.1.0
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/lib/pq v1.8.0
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/rcrowley/go-metrics v0.0.0-20181016184325-3113b8401b8a
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/gorilla/handlers v1.4.2
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/mattn/go-isatty v0.0.11
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading golang.org/x/text v0.3.3
go: downloading go.opencensus.io v0.22.3
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/nats-io/nkeys v0.1.4
go: downloading go.uber.org/zap v1.14.1
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/miekg/dns v1.1.8
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/nats-io/stan.go v0.7.0
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/coreos/go-systemd/v22 v22.0.0
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/prometheus/client_model v0.0.0-20190812154241-14fe0d1b01d4
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading go.uber.org/atomic v1.6.0
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/mattn/go-colorable v0.1.4
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading go.uber.org/multierr v1.5.0
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/minio/simdjson-go v0.1.5
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/eapache/go-resiliency v1.1.0
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading github.com/tidwall/match v1.0.1
# github.co [...]

2020-12-03 03:44 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ee3efafc-5754-4166-9f73-52a9a713b033) |
| mint-fs.sh | :x: [more...](#579bfbc8-33ba-4099-bead-01aae2c29608) |
| mint-gateway-azure.sh | :x: [more...](#a2dab7f9-d294-479a-b64e-0310c354e270) |
| mint-erasure.sh | :x: [more...](#5ac86675-bf5e-4885-9020-e6869fe2f615) |
| mint-dist-erasure.sh | :x: [more...](#142c9567-092c-45f2-b849-2176c3300ce6) |
| mint-zoned.sh | :x: [more...](#74fae811-7695-427b-8fa1-b0d1cfab0371) |
<a name="ee3efafc-5754-4166-9f73-52a9a713b033"></a>
### 11019-bef03a2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32190
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a5690085991b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 23 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 32 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 27 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 31 seconds
{
  "args": {
    "bucketName": "minio-go-test-603ixjljvhzj3wzu",
    "objectName": "4w4l95uuowy2646669qnz2ntvncf2y",
    "sse": {}
  },
  "duration": 128,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 5 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 291,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-1cd0uh0, objectName = null, resource = /minio-java-test-1cd0uh0, requestId = 164D158E7875AADB, hostId = 3f1d9c96-4c59-4c76-90df-5f6f68f779e0)\nrequest={method=PUT, url=http://minio-c2.minio.io:32190/minio-java-test-1cd0uh0?encryption=, headers=Host: minio-c2.minio.io:32190\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20201203T025903Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201203/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D158E7875AADB\nX-Xss-Protection: 1; mode=block\nDate: Thu, 03 Dec 2020 02:59:03 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 8 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 1 seconds
(11/15) Running s3cmd tests ... done in 23 seconds
(12/15) Running s3select tests ... done in 6 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="5ac86675-bf5e-4885-9020-e6869fe2f615"></a>
### 11019-bef03a2/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30345
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 239e4da726b2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 43 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 46 seconds
{
  "args": {
    "bucketName": "minio-go-test-j215goiddf991w51",
    "objectName": "exrfutgumljhjfwy9a6ln55n15lpwt",
    "sse": {}
  },
  "duration": 43,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 46,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-1cvt840, objectName = null, resource = /minio-java-test-1cvt840, requestId = 164D15743101F488, hostId = 36d34f21-2fb7-4931-b9b2-78d25826c24d)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30345/minio-java-test-1cvt840?encryption=, headers=Host: minio-dev4.minio.io:30345\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20201203T025710Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201203/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D15743101F488\nX-Xss-Protection: 1; mode=block\nDate: Thu, 03 Dec 2020 02:57:10 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 49 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 10 seconds
(11/15) Running s3cmd tests ... done in 19 seconds
(12/15) Running s3select tests ... done in 3 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="a2dab7f9-d294-479a-b64e-0310c354e270"></a>
### 11019-bef03a2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31551
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 88dd4e7f127f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running [...]

2020-12-03 04:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#62aca327-d23e-4ca2-9259-83edb1baf551) |
| mint-fs.sh | :x: [more...](#5434eee1-d7e8-44d4-bc6f-50ccb9d9d21b) |
| mint-gateway-azure.sh | :x: [more...](#b659b475-012f-4bf1-b6ba-e718568748c2) |
| mint-erasure.sh | :x: [more...](#ec67a10e-85a0-43ff-904e-bd3e8ddca022) |
| mint-dist-erasure.sh | :x: [more...](#ed024944-41be-4628-9fdb-41a1467d32e1) |
| mint-zoned.sh | :x: [more...](#49222818-57e5-477c-9c09-a91a88aaf1ea) |
<a name="49222818-57e5-477c-9c09-a91a88aaf1ea"></a>
### 11019-cb3dbcd/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31390
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8403d0c47e77:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 2 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 50 seconds
(8/15) Running minio-dotnet tests ... done in 57 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 46 seconds
{
  "args": {
    "bucketName": "minio-go-test-qbm69zxpbdybpd1p",
    "objectName": "kpn066kmw2dy15l4n611xzpg3th31z",
    "sse": {}
  },
  "duration": 239,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 8 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 248,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-347onif, objectName = null, resource = /minio-java-test-347onif, requestId = 164D18B9E8AD9627, hostId = 86b71b19-155b-416e-86f1-69f4f19e01bb)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31390/minio-java-test-347onif?encryption=, headers=Host: minio-dev6.minio.io:31390\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20201203T035708Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201203/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D18B9E8AD9627\nX-Xss-Protection: 1; mode=block\nDate: Thu, 03 Dec 2020 03:57:08 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 51 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 55 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 7 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="ed024944-41be-4628-9fdb-41a1467d32e1"></a>
### 11019-cb3dbcd/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30893
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a5e3bd7e53ca:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 47 seconds
(8/15) Running minio-dotnet tests ... done in 47 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 41 seconds
{
  "args": {
    "bucketName": "minio-go-test-03rv1c9p0x1uxitv",
    "objectName": "yzpwg5p1u2954f6cic9firvehsgiie",
    "sse": {}
  },
  "duration": 159,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 4 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 120,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-3onbtnc, objectName = null, resource = /minio-java-test-3onbtnc, requestId = 164D18B3DEF62AF9, hostId = e920c8a0-0a81-41c9-9fc5-90c030ffc760)\nrequest={method=PUT, url=http://minio-c2.minio.io:30893/minio-java-test-3onbtnc?encryption=, headers=Host: minio-c2.minio.io:30893\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20201203T035642Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201203/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D18B3DEF62AF9\nX-Xss-Protection: 1; mode=block\nDate: Thu, 03 Dec 2020 03:56:42 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 0 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 30 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="ec67a10e-85a0-43ff-904e-bd3e8ddca022"></a>
### 11019-cb3dbcd/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31127
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 204627dee805:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk- [...]

2020-12-03 06:15 UTC, harshavardhana commented
Looks like there are some fundamental challenges here, still a WIP

2020-12-03 06:15 UTC, harshavardhana commented
@aead please provide your feedback nonetheless

2020-12-03 08:53 UTC, harshavardhana commented
> https://gist.githubusercontent.com/aead/2f032134c1d08a3a05cb0e679a541416/raw/aa8f3ad07cef2eba93ea0e7b93e2693bcda7a52f/argon2.patch

This patch wasn't complete, added more changes to make it fully work now - all tests passing no more WIP.

2020-12-03 10:09 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6ef2cade-733c-4376-a49e-b0724e97c499) |
| mint-gateway-azure.sh | :x: [more...](#b0829031-b5bc-4602-9c70-489aa79f464a) |
| mint-zoned.sh | :x: [more...](#b5dbc672-2148-47b4-9b19-783dbd528393) |
<a name="6ef2cade-733c-4376-a49e-b0724e97c499"></a>
### 11019-842bfc7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31129
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f1878abbb2ed:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 6 minutes and 0 seconds
{
  "name": "awscli",
  "duration": 311323,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31129 s3api upload-part --bucket awscli-mint-test-bucket-8527 --key awscli-mint-test-bucket-8527-object --body /mint/data/datafile-10-MB --upload-id 076668a1-af8d-438a-88cd-9fdf8e7e551c --part-number 2\n",
  "status": "FAIL",
  "error": ""
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 39 seconds
(7/15) Running minio-dotnet tests ... done in 53 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 44 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 7 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 1 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="b0829031-b5bc-4602-9c70-489aa79f464a"></a>
### 11019-842bfc7/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31800
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8545ad28c07d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 40 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 3 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 49 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 42 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 51 seconds
{
  "args": {
    "bucketName": "minio-go-test-ubz1nfihys59keat",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1020,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 9 minutes and 2 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 178,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:91043952-d01e-0157-5355-c94236000000\nTime:2020-12-03T09:19:45.4707094Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'KH8kikH4KFmezd33Fe5M06ZoXoZGQjItokEL3ZzQoHY=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:33bfaef4-67e0-4722-68af-df0081a29a81\nx-ms-date:Thu, 03 Dec 2020 09:19:45 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-1706pg2/minio-java-test-1btcb7c\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-1706pg2/minio-java-test-1btcb7c?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-03T08:52:12Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [33bfaef4-67e0-4722-68af-df0081a29a81]\n   X-Ms-Date: [Thu, 03 Dec 2020 09:19:45 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Thu, 03 Dec 2020 09:19:44 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [91043952-d01e-0157-5355-c94236000000]\n\n\n, bucketName = minio-java-test-1706pg2, objectName = minio-java-test-1btcb7c, resource = /minio-java-test-1706pg2/minio-java-test-1btcb7c, requestId = 164D2A54B59DFCA3, hostId = 2eec2096-8710-4920-b700-787e187aba5b)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31800/minio-java-test-1706pg2/minio-java-test-1btcb7c, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev4.minio.io:31800\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201203T091945Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201203/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D2A54B59DFCA3\nX-Xss-Protection: 1; mode=block\nDate: Thu, 03 Dec 2020 09:19:45 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(Functional [...]

2020-12-03 14:57 UTC, klauspost reviewed
I don't have much to add to this.

2020-12-03 14:57 UTC, klauspost commented on pkg/argon2/.#argon2_test.go
> +harsha@backspace.1106284:1605587635
??

2020-12-03 14:57 UTC, klauspost commented on pkg/argon2/#argon2_test.go#
> +// Copyright 2017 The Go Authors. All rights reserved.
Accidental extra file?

2020-12-03 17:34 UTC, harshavardhana commented
> I don't have much to add to this.

Removed the `emacs` backup files @klauspost

2020-12-03 17:38 UTC, klauspost requested changes

2020-12-03 17:38 UTC, klauspost commented on cmd/data-crawler.go
> +	crawlerTimer := time.NewTimer(dataCrawlStartDelay)
No, this will only fire once, then never again.

Using a Ticker is tricky, since it will fire irregardsless of the time it takes.

2020-12-03 18:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#ce00f053-9959-4e61-baed-b29118d0b085) |
| mint-gateway-azure.sh | :x: [more...](#e867d0d3-7668-42ab-bd5e-ec2f7d0b47c8) |
<a name="e867d0d3-7668-42ab-bd5e-ec2f7d0b47c8"></a>
### 11019-d73ef73/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32377
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5655e3d2a501:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 54 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 34 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 59 seconds
{
  "args": {
    "bucketName": "minio-go-test-ftjnf90eqwe9d2ac",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1038,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 9 minutes and 4 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 177,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:ec217e35-501e-0146-09a1-c9752d000000\nTime:2020-12-03T18:26:44.5786884Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'sjEoBmoGy3zKjKESsjBMZwr8zM4qM3vXLJfwgjbMntk=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:9742cffc-7018-47e0-6646-7397406393ec\nx-ms-date:Thu, 03 Dec 2020 18:26:44 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-2sjagkp/minio-java-test-2hsg8r3\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-2sjagkp/minio-java-test-2hsg8r3?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-03T17:59:25Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [9742cffc-7018-47e0-6646-7397406393ec]\n   X-Ms-Date: [Thu, 03 Dec 2020 18:26:44 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Thu, 03 Dec 2020 18:26:43 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [ec217e35-501e-0146-09a1-c9752d000000]\n\n\n, bucketName = minio-java-test-2sjagkp, objectName = minio-java-test-2hsg8r3, resource = /minio-java-test-2sjagkp/minio-java-test-2hsg8r3, requestId = 164D482E00E8C6BD, hostId = b3400197-e531-4525-b6e4-be2cc9f6d8f7)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32377/minio-java-test-2sjagkp/minio-java-test-2hsg8r3, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev7.minio.io:32377\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201203T182644Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201203/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D482E00E8C6BD\nX-Xss-Protection: 1; mode=block\nDate: Thu, 03 Dec 2020 18:26:44 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:68:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:684:10) at endReadableNT (_stream_readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 18 minutes and 52 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 14 seconds
(11/15) Running s3select tests ... done in 39 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="ce00f053-9959-4e61-baed-b29118d0b085"></a>
### 11019-d73ef73/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30485
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:       [...]

2020-12-03 19:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#05666687-1567-49cf-acf1-7b886862194c) |
<a name="05666687-1567-49cf-acf1-7b886862194c"></a>
### 11019-3feeac4/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32751
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3544a775b542:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 3 minutes and 47 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 4 minutes and 0 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-bj0tk4qah1v0dvh1",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1179,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 9 minutes and 1 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 189,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:7669e232-c01e-004c-5aa9-c92af1000000\nTime:2020-12-03T19:18:23.6846015Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'tcu7tMP9fVFB4v3zmmPeqyZUyHfqw73PR/GvOh0VjMw=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:15c92c7c-80c1-4e06-752e-5622837bf26b\nx-ms-date:Thu, 03 Dec 2020 19:18:23 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-107d7h1/minio-java-test-2uaduia\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-107d7h1/minio-java-test-2uaduia?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-03T18:49:40Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [15c92c7c-80c1-4e06-752e-5622837bf26b]\n   X-Ms-Date: [Thu, 03 Dec 2020 19:18:23 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Thu, 03 Dec 2020 19:18:23 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [7669e232-c01e-004c-5aa9-c92af1000000]\n\n\n, bucketName = minio-java-test-107d7h1, objectName = minio-java-test-2uaduia, resource = /minio-java-test-107d7h1/minio-java-test-2uaduia, requestId = 164D4AFF9108636A, hostId = 5a1e1ff1-adc9-4ade-a9a8-0c6b5bafc384)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32751/minio-java-test-107d7h1/minio-java-test-2uaduia, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev6.minio.io:32751\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201203T191823Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201203/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D4AFF9108636A\nX-Xss-Protection: 1; mode=block\nDate: Thu, 03 Dec 2020 19:18:23 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:68:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:684:10) at endReadableNT (_stream_readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... FAILED in 18 minutes and 48 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-a4585b49-ef8c-405d-a2a7-9ac611777221",
    "object_name": "b4c5e110-cf72-42e5-a189-20db18dbe8d5"
  },
  "message": "Sha-sum mismatch on multi-threaded put and get objects",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1637, in  [...]

2020-12-03 23:15 UTC, aead approved these changes

2020-12-04 00:06 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#fb374517-f3c7-490e-bfb4-7cc2eb37f153) |
<a name="fb374517-f3c7-490e-bfb4-7cc2eb37f153"></a>
### 11019-19d4c1e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30523
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bb526570eb5f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 57 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 4 minutes and 40 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 52 seconds
{
  "args": {
    "bucketName": "minio-go-test-volnvushngxnabpc",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1031,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 10 minutes and 7 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 187,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:4f64d6d7-f01e-000b-1ecd-c9f59a000000\nTime:2020-12-03T23:42:24.0753194Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'lPJcTEZPaKRPzL4SbUMEQGTh7bBv3igqb7OReNnle5Y=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:ff4a7880-871f-4474-42b2-b2935fbf9dc0\nx-ms-date:Thu, 03 Dec 2020 23:42:24 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-1g4ssfu/minio-java-test-3airke8\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-1g4ssfu/minio-java-test-3airke8?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-03T23:12:54Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [ff4a7880-871f-4474-42b2-b2935fbf9dc0]\n   X-Ms-Date: [Thu, 03 Dec 2020 23:42:24 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Thu, 03 Dec 2020 23:42:23 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [4f64d6d7-f01e-000b-1ecd-c9f59a000000]\n\n\n, bucketName = minio-java-test-1g4ssfu, objectName = minio-java-test-3airke8, resource = /minio-java-test-1g4ssfu/minio-java-test-3airke8, requestId = 164D5967B2162755, hostId = e16db755-5d6b-4cf7-88c0-960f5228652c)\nrequest={method=PUT, url=http://minio-c2.minio.io:30523/minio-java-test-1g4ssfu/minio-java-test-3airke8, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-c2.minio.io:30523\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201203T234223Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201203/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164D5967B2162755\nX-Xss-Protection: 1; mode=block\nDate: Thu, 03 Dec 2020 23:42:24 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:68:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:684:10) at endReadableNT (_stream_readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 19 minutes and 2 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 23 seconds
(11/15) Running s3select tests ... done in 38 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-12-04 03:16 UTC, kannappanr approved these changes
LGTM

2020-12-04 03:23 UTC, merged