azure/s3 gateways: Pass ETag during GET call to avoid data corruption
minio/minio pull request #11024
Opened 2020-12-03 14:56 UTC by vadmeste

## Description
Both Azure & S3 gateways call for object information before returning
the stream of the object, however the object content/length could be
modified meanwhile, which means it can return a corrupted object.

Use ETag to ensure that the object was not modified during the GET call

## Motivation and Context
Fix #https://github.com/minio/minio/issues/11008

## How to test this PR?
1. Run Minio in Azure gateway mode
2. Use the sample code in https://github.com/minio/minio/issues/11008

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-12-03 17:47 UTC, harshavardhana approved these changes

2020-12-03 18:12 UTC, krisis approved these changes

2020-12-04 06:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#592b95a6-fb07-4022-9d6a-8cef3577877d) |
<a name="592b95a6-fb07-4022-9d6a-8cef3577877d"></a>
### 11024-064b834/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31548
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fd2f1b6bc6f1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-29gyhn6stcttr1",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 889,
  "error": "ConditionNotMet: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=ConditionNotMet) =====\nDescription=The condition specified using HTTP conditional header(s) is not met.\nRequestId:26fae229-101e-0023-7d04-ca8225000000\nTime:2020-12-04T06:15:53.2967720Z, Details: \n   Code: ConditionNotMet\n   GET https://minioazure.blob.core.windows.net/aws-sdk-go-test-29gyhn6stcttr1/object1.csv?timeout=1501\n   Authorization: REDACTED\n   If-Match: [41455327d3ce43e6c1d1fec0473922e3]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-04T06:09:58Z]\n   X-Ms-Client-Request-Id: [7a6392e6-b90a-44a5-7ad8-01bde33efc10]\n   X-Ms-Date: [Fri, 04 Dec 2020 06:15:53 GMT]\n   X-Ms-Range: [bytes=0-553]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 412 The condition specified using HTTP conditional header(s) is not met.\n   Content-Length: [252]\n   Content-Type: [application/xml]\n   Date: [Fri, 04 Dec 2020 06:15:53 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [7a6392e6-b90a-44a5-7ad8-01bde33efc10]\n   X-Ms-Error-Code: [ConditionNotMet]\n   X-Ms-Request-Id: [26fae229-101e-0023-7d04-ca8225000000]\n   X-Ms-Version: [2019-02-02]\n\n\n\n\tstatus code: 412, request id: 164D6EE0991F6FB3, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed ConditionNotMet: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=ConditionNotMet) =====\nDescription=The condition specified using HTTP conditional header(s) is not met.\nRequestId:26fae229-101e-0023-7d04-ca8225000000\nTime:2020-12-04T06:15:53.2967720Z, Details: \n   Code: ConditionNotMet\n   GET https://minioazure.blob.core.windows.net/aws-sdk-go-test-29gyhn6stcttr1/object1.csv?timeout=1501\n   Authorization: REDACTED\n   If-Match: [41455327d3ce43e6c1d1fec0473922e3]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-04T06:09:58Z]\n   X-Ms-Client-Request-Id: [7a6392e6-b90a-44a5-7ad8-01bde33efc10]\n   X-Ms-Date: [Fri, 04 Dec 2020 06:15:53 GMT]\n   X-Ms-Range: [bytes=0-553]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 412 The condition specified using HTTP conditional header(s) is not met.\n   Content-Length: [252]\n   Content-Type: [application/xml]\n   Date: [Fri, 04 Dec 2020 06:15:53 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [7a6392e6-b90a-44a5-7ad8-01bde33efc10]\n   X-Ms-Error-Code: [ConditionNotMet]\n   X-Ms-Request-Id: [26fae229-101e-0023-7d04-ca8225000000]\n   X-Ms-Version: [2019-02-02]\n\n\n\n\tstatus code: 412, request id: 164D6EE0991F6FB3, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... done in 2 seconds
(2/15) Running aws-sdk-php tests ... FAILED in 6 seconds
{
  "name": "aws-sdk-php",
  "function": "listMultipartUploads ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5fc9d41b2ff89",
    "Object": "obj1"
  },
  "duration": "691",
  "status": "FAIL",
  "error": "Error executing \"UploadPartCopy\" on \"http://minio-dev4.minio.io:31548/aws-sdk-php-5fc9d41b2ff89/obj1-copy?uploadId=da2c38a975761675&partNumber=1\"; AWS HTTP error: Client error: `PUT http://minio-dev4.minio.io:31548/aws-sdk-php-5fc9d41b2ff89/obj1-copy?uploadId=da2c38a975761675&partNumber=1` resulted in a `412 Precondition Failed` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>ConditionNotMet</Code><Message>-&gt; github.com/Azure/azure-storage- (truncated...)\n ConditionNotMet (client): -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=ConditionNotMet) =====\nDescription=The condition specified using HTTP conditional header(s) is not met.\nRequestId:f14af4bb-e01e-005b-3104-caea92000000\nTime:2020-12-04T06:16:00.7654257Z, Details: \n   Code: ConditionNotMet\n   GET https://minioazure.blob.core.windows.net/aws-sdk-php-5fc9d41b2ff89/obj1?timeout=1501\n   Authorization: REDACTED\n   If-Match: [c21b73aa229ee10d81eee0aa2044d4a8]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-04T06:09:58Z]\n   X-Ms-Client-Request-Id: [30d9f7c1-d17d-46dd-4b06-df674128142c]\n   X-Ms-Date: [Fri, 04 Dec 2020 06:16:00 GMT]\n   X-Ms-Range: [bytes=0-1023]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 412 The condition specified using HTTP conditional header(s) is not met.\n   Content-Length: [252]\n   Content-Type: [application/xml]\n   Date: [Fri, 04 Dec 2020 06:15:59 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [30d9f7c1-d17d-46dd-4b06-df674128142c]\n   X-Ms-Error-Code: [ConditionNotMet]\n   X-Ms-Request-Id: [f14af4bb-e01e-005b-3104-caea92000000]\n   X-Ms-Version: [2019-02-02]\n\n\n - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>ConditionNotMet</Code><Message>-&gt; github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42&#xA;===== RESPONSE ERROR (ServiceCode=ConditionNotMet) =====&#xA;Description=The condition specified using HTTP conditional header(s) is not met.&#xA;RequestId:f14af4bb-e01e-005b-3104-caea92000000&#xA;Time:2020-12-04T06:16:00.7654257Z, Details: &#xA;   Code: ConditionNotMet&#xA;   GET https://minioazure.blob.core.windows.net/aws-sdk-php-5fc9d41b2ff89/obj1?timeout=1501&#xA;   Authorization: REDACTED&#xA;   If-Match: [c21b73aa229ee10d81eee0aa2044d4a8]&#xA;   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-04T06:09:58Z]&#xA;   X-Ms-Client-Request-Id: [30d9f7c1-d17d-46dd-4b06-df674128142c]&#xA;   X-Ms-Date: [Fri, 04 Dec 2020 06:16:00 GMT]&#xA;   X-Ms-Range: [bytes=0-1023]&#xA;   X-Ms-Version: [2019-02-02]&#xA;   --------------------------------------------------------------------------------&#xA;   RESPONSE Status: 412 The condition specified using HTTP conditional header(s) is not met.&#xA;   Content-Length: [252]&#xA;   Content-Type: [application/xml]&#xA;   Date: [Fri, 04 Dec 2020 06:15:59 GMT]&#xA;   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]&#xA;   X-Ms-Client-Request-Id: [30d9f7c1-d17d-46dd-4b06-df674128142c]&#xA;   X-Ms-Error-Code: [ConditionNotMet]&#xA;   X-Ms-Request-Id: [f14af4bb-e01e-005b-3104-caea92000000]&#xA;   X-Ms-Version: [2019-02-02]&#xA;&#xA;&#xA;</Message><Key>obj1-copy</Key><BucketName>aws-sdk-php-5fc9d41b2ff89</BucketName><Resource>/aws-sdk-php-5fc9d41b2ff89/obj1-copy</Resourc [...]

2020-12-04 07:45 UTC, harshavardhana commented
@vadmeste it looks like most mint tests fail with this change - can you PTAL?

2020-12-04 07:46 UTC, harshavardhana requested changes
Investigate mint failures for azure gateway

2020-12-10 16:49 UTC, vadmeste commented
Okay, I investigated this and I know why this is not working. Azure gateway returns the MD5 as ETag instead of the real ETag stored in Azure blob backend. So If-Match won't work. Maybe we need to avoid that behavior since ETag is just a generic unique ID by definition.

2020-12-10 17:27 UTC, harshavardhana commented
> Okay, I investigated this and I know why this is not working. Azure gateway returns the MD5 as ETag instead of the real ETag stored in Azure blob backend. So If-Match won't work. Maybe we need to avoid that behavior since ETag is just a generic unique ID by definition.

@vadmeste then can we only do this PR with S3 gateway for now?

2020-12-14 22:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#94890947-bfba-4565-9984-e74e6bff7b57) |
<a name="94890947-bfba-4565-9984-e74e6bff7b57"></a>
### 11024-32c2b05/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31994
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b01eb627c873:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-tlpd6pxsoip361",
    "objectName1": "object1.csv",
    "objectName2": "object2.csv"
  },
  "duration": 922,
  "error": "ConditionNotMet: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=ConditionNotMet) =====\nDescription=The condition specified using HTTP conditional header(s) is not met.\nRequestId:5589354f-601e-000e-7d65-d201e5000000\nTime:2020-12-14T22:08:00.6370731Z, Details: \n   Code: ConditionNotMet\n   GET https://minioazure.blob.core.windows.net/aws-sdk-go-test-tlpd6pxsoip361/object1.csv?timeout=1501\n   Authorization: REDACTED\n   If-Match: [41455327d3ce43e6c1d1fec0473922e3]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-14T22:01:48Z]\n   X-Ms-Client-Request-Id: [1ac63ef2-0f2d-4563-5733-bd0e106cb518]\n   X-Ms-Date: [Mon, 14 Dec 2020 22:08:00 GMT]\n   X-Ms-Range: [bytes=0-553]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 412 The condition specified using HTTP conditional header(s) is not met.\n   Content-Length: [252]\n   Content-Type: [application/xml]\n   Date: [Mon, 14 Dec 2020 22:08:00 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [1ac63ef2-0f2d-4563-5733-bd0e106cb518]\n   X-Ms-Error-Code: [ConditionNotMet]\n   X-Ms-Request-Id: [5589354f-601e-000e-7d65-d201e5000000]\n   X-Ms-Version: [2019-02-02]\n\n\n\n\tstatus code: 412, request id: 1650B4A3424518AB, host id: ",
  "function": "testSelectObject",
  "message": "AWS SDK Go Select object failed ConditionNotMet: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=ConditionNotMet) =====\nDescription=The condition specified using HTTP conditional header(s) is not met.\nRequestId:5589354f-601e-000e-7d65-d201e5000000\nTime:2020-12-14T22:08:00.6370731Z, Details: \n   Code: ConditionNotMet\n   GET https://minioazure.blob.core.windows.net/aws-sdk-go-test-tlpd6pxsoip361/object1.csv?timeout=1501\n   Authorization: REDACTED\n   If-Match: [41455327d3ce43e6c1d1fec0473922e3]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-14T22:01:48Z]\n   X-Ms-Client-Request-Id: [1ac63ef2-0f2d-4563-5733-bd0e106cb518]\n   X-Ms-Date: [Mon, 14 Dec 2020 22:08:00 GMT]\n   X-Ms-Range: [bytes=0-553]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 412 The condition specified using HTTP conditional header(s) is not met.\n   Content-Length: [252]\n   Content-Type: [application/xml]\n   Date: [Mon, 14 Dec 2020 22:08:00 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [1ac63ef2-0f2d-4563-5733-bd0e106cb518]\n   X-Ms-Error-Code: [ConditionNotMet]\n   X-Ms-Request-Id: [5589354f-601e-000e-7d65-d201e5000000]\n   X-Ms-Version: [2019-02-02]\n\n\n\n\tstatus code: 412, request id: 1650B4A3424518AB, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... done in 2 seconds
(2/15) Running aws-sdk-php tests ... FAILED in 7 seconds
{
  "name": "aws-sdk-php",
  "function": "listMultipartUploads ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5fd7e24286b7e",
    "Object": "obj1"
  },
  "duration": "757",
  "status": "FAIL",
  "error": "Error executing \"UploadPartCopy\" on \"http://minio-dev7.minio.io:31994/aws-sdk-php-5fd7e24286b7e/obj1-copy?uploadId=53273dda077fc9fb&partNumber=1\"; AWS HTTP error: Client error: `PUT http://minio-dev7.minio.io:31994/aws-sdk-php-5fd7e24286b7e/obj1-copy?uploadId=53273dda077fc9fb&partNumber=1` resulted in a `412 Precondition Failed` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>ConditionNotMet</Code><Message>-&gt; github.com/Azure/azure-storage- (truncated...)\n ConditionNotMet (client): -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=ConditionNotMet) =====\nDescription=The condition specified using HTTP conditional header(s) is not met.\nRequestId:1bd3a78a-c01e-0148-5c65-d29926000000\nTime:2020-12-14T22:08:08.9917572Z, Details: \n   Code: ConditionNotMet\n   GET https://minioazure.blob.core.windows.net/aws-sdk-php-5fd7e24286b7e/obj1?timeout=1501\n   Authorization: REDACTED\n   If-Match: [c21b73aa229ee10d81eee0aa2044d4a8]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-14T22:01:48Z]\n   X-Ms-Client-Request-Id: [0dc2b9bc-e974-494d-478c-6da6d0d1c54f]\n   X-Ms-Date: [Mon, 14 Dec 2020 22:08:08 GMT]\n   X-Ms-Range: [bytes=0-1023]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 412 The condition specified using HTTP conditional header(s) is not met.\n   Content-Length: [252]\n   Content-Type: [application/xml]\n   Date: [Mon, 14 Dec 2020 22:08:08 GMT]\n   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]\n   X-Ms-Client-Request-Id: [0dc2b9bc-e974-494d-478c-6da6d0d1c54f]\n   X-Ms-Error-Code: [ConditionNotMet]\n   X-Ms-Request-Id: [1bd3a78a-c01e-0148-5c65-d29926000000]\n   X-Ms-Version: [2019-02-02]\n\n\n - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>ConditionNotMet</Code><Message>-&gt; github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42&#xA;===== RESPONSE ERROR (ServiceCode=ConditionNotMet) =====&#xA;Description=The condition specified using HTTP conditional header(s) is not met.&#xA;RequestId:1bd3a78a-c01e-0148-5c65-d29926000000&#xA;Time:2020-12-14T22:08:08.9917572Z, Details: &#xA;   Code: ConditionNotMet&#xA;   GET https://minioazure.blob.core.windows.net/aws-sdk-php-5fd7e24286b7e/obj1?timeout=1501&#xA;   Authorization: REDACTED&#xA;   If-Match: [c21b73aa229ee10d81eee0aa2044d4a8]&#xA;   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-14T22:01:48Z]&#xA;   X-Ms-Client-Request-Id: [0dc2b9bc-e974-494d-478c-6da6d0d1c54f]&#xA;   X-Ms-Date: [Mon, 14 Dec 2020 22:08:08 GMT]&#xA;   X-Ms-Range: [bytes=0-1023]&#xA;   X-Ms-Version: [2019-02-02]&#xA;   --------------------------------------------------------------------------------&#xA;   RESPONSE Status: 412 The condition specified using HTTP conditional header(s) is not met.&#xA;   Content-Length: [252]&#xA;   Content-Type: [application/xml]&#xA;   Date: [Mon, 14 Dec 2020 22:08:08 GMT]&#xA;   Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0]&#xA;   X-Ms-Client-Request-Id: [0dc2b9bc-e974-494d-478c-6da6d0d1c54f]&#xA;   X-Ms-Error-Code: [ConditionNotMet]&#xA;   X-Ms-Request-Id: [1bd3a78a-c01e-0148-5c65-d29926000000]&#xA;   X-Ms-Version: [2019-02-02]&#xA;&#xA;&#xA;</Message><Key>obj1-copy</Key><BucketName>aws-sdk-php-5fd7e24286b7e</BucketName><Resource>/aws-sdk-php-5fd7e24286b7e/obj1-copy</Resourc [...]

2020-12-15 11:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#03dac1aa-241d-4ac1-9b4a-8329ca57960b) |
<a name="03dac1aa-241d-4ac1-9b4a-8329ca57960b"></a>
### 11024-8006b04/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30461
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6b1d7e78c8a2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 51 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 44 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 26 seconds
(10/15) Running minio-java tests ... FAILED in 9 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 192,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:3d77e8a5-c01e-0021-0cd3-d280df000000\nTime:2020-12-15T11:17:48.1451933Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'esyv1FsRWopwHRTFD8lc5gYGijPou4xPj4peZixYPHY=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:ead9ba9b-07b2-4746-7499-c887d99b9e33\nx-ms-date:Tue, 15 Dec 2020 11:17:48 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-3ohk8cm/minio-java-test-2f7vkbb\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-3ohk8cm/minio-java-test-2f7vkbb?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-15T10:44:15Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [ead9ba9b-07b2-4746-7499-c887d99b9e33]\n   X-Ms-Date: [Tue, 15 Dec 2020 11:17:48 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Tue, 15 Dec 2020 11:17:47 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [3d77e8a5-c01e-0021-0cd3-d280df000000]\n\n\n, bucketName = minio-java-test-3ohk8cm, objectName = minio-java-test-2f7vkbb, resource = /minio-java-test-3ohk8cm/minio-java-test-2f7vkbb, requestId = 1650DFBC949764E1, hostId = 2baf5b84-0df5-41a4-8351-177f9c810fc5)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30461/minio-java-test-3ohk8cm/minio-java-test-2f7vkbb, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev6.minio.io:30461\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201215T111748Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201215/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1650DFBC949764E1\nX-Xss-Protection: 1; mode=block\nDate: Tue, 15 Dec 2020 11:17:48 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 42 seconds
(11/15) Running minio-py tests ... done in 19 minutes and 21 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 27 seconds
(13/15) Running s3select tests ... FAILED in 14 seconds
{
  "name": "s3select:test_csv_input_quote_char",
  "function": "select_object_content(bucket_name, object_name, request)",
  "args": {
    "bucket_name": "s3select-test-4bda4444-47e6-4bc1-a345-c41f2d3e60a8"
  },
  "duration": 13707,
  "message": "Test test_16 unexpectedly failed with: 'event-type'",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/s3select/csv.py\", line 43, in test_sql_api\n    for d in data.stream(10*1024):\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select/reader.py\", line 211, in stream\n    message = self.__extract_message()\n  File \"/usr/local/lib/python3.6/dist-packages/minio/select/reader.py\", line 161, in __extract_message\n    event_type = header_map[\"event-type\"]\nKeyError: 'event-type'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./tests.py\", line 53, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"/mint/run/core/s3select/csv.py\", line 119, in test_csv_input_custom_quote_char\n    data, sql_opts, expected_output)\n  File \"/mint/run/core/s3select/csv.py\", line 49, in test_sql_api\n    'Test {} unexpectedly failed with: {}'.format(test_name, select_err))\nValueError: Test test_16 unexpectedly failed with: 'event-type'\n",
  "status": "FAIL"
}
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-12-17 17:10 UTC, harshavardhana approved these changes

2020-12-17 17:11 UTC, merged