Add transition event notification
minio/minio pull request #11047
Opened 2020-12-07 19:44 UTC by poornas

- This is a MinIO specific extension to allow
monitoring transition events.

## Description

## Motivation and Context
Gives users a way to monitor status of transition.

## How to test this PR?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-12-07 19:57 UTC, harshavardhana requested changes

2020-12-07 19:57 UTC, harshavardhana commented on cmd/bucket-lifecycle.go
> +		Host: "Internal: [ILM-EXPIRY]",
ILM-Transition

2020-12-07 19:57 UTC, harshavardhana commented on pkg/event/name.go
>  	default:
```suggestion
	case "s3:ObjectTransition:Failed":
		return ObjectTransitionFailed, nil
	case "s3:ObjectTransition:Complete":
		return ObjectTransitionComplete, nil
        case "s3:ObjectTransition:*":
	default:
```

2020-12-07 19:57 UTC, harshavardhana commented on docs/bucket/lifecycle/README.md
> +`s3:ilm:OperationCompletedTransition` and `s3:ilm:OperationFailedTransition` events can be used to monitor transition events between the source cluster and transition tier. To watch lifecycle events,
```suggestion
`s3:ObjectTransition:Complete` and `s3:ObjectTransition:Failed` events can be used to monitor transition events between the source cluster and transition tier. To watch lifecycle events, you can enable bucket notification on the source bucket with `mc event add`  and specify `--event ilm` flag.
```

2020-12-07 20:39 UTC, harshavardhana approved these changes

2020-12-07 21:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#1e01dd08-4b24-437b-992b-94bec3a581f9) |
| mint-gateway-azure.sh | :x: [more...](#25fa801f-a4c6-4873-bfa5-f2d5699a11f1) |
| mint-erasure.sh | :x: [more...](#8d8d664b-3c7f-498a-ac8f-8eca752e721a) |
<a name="8d8d664b-3c7f-498a-ac8f-8eca752e721a"></a>
### 11047-d0e4970/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32082
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f9508b2ba8b9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 57 seconds
{
  "name": "awscli",
  "duration": 65487,
  "function": "aws --endpoint-url http://minio-c2.minio.io:32082 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-11803/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-11803/datafile-1-kBupload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-11803/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-11803/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-11803/datafile-10-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-11803/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-11803/datafile-100-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-11803/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-11803/datafile-1.03-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-11803/datafile-5-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-11803/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-11803/datafile-11-MBupload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-11803/datafile-65-MB An error occurred (NoSuchBucket) when calling the UploadPart operation: The specified bucket does not existupload failed: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-11803/datafile-6-MB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not existupload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-11803/datafile-129-MB An error occurred (NoSuchBucket) when calling the UploadPart operation: The specified bucket does not existupload failed: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-11803/datafile-5243880-b An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 48 seconds
(7/15) Running minio-dotnet tests ... done in 44 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 29 seconds
(9/15) Running minio-java tests ... done in 43 seconds
(10/15) Running minio-js tests ... done in 47 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 10 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1e01dd08-4b24-437b-992b-94bec3a581f9"></a>
### 11047-d0e4970/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32243
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 29d8693da01c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 53 seconds
{
  "name": "awscli",
  "duration": 62632,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32243 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-1319/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-1319/datafile-0-bupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-1319/datafile-1-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-1319/datafile-1-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-1319/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-1319/datafile-100-kBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-1319/datafile-1-MBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-1319/datafile-1.03-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-1319/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-1319/datafile-6-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-1319/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-1319/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-1319/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-1319/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-1319/datafile-129-MBupload failed: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-1319/datafile-10-kB An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 44 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 7 seconds
(9/15) Running minio-java tests ... done in 21 seconds
(10/15) Running minio-js tests ... done in 56 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 19 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="25fa801f-a4c6-4873-bfa5-f2d5699a11f1"></a>
### 11047-d0e4970/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30209
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d41b4a429136:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 58 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 46 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 39 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 53 seconds
{
  "args": {
    "bucketName": "minio-go-test-1tn2doluytqn0mhb",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1208,
  "function": "PutObject(bucketName, object [...]

2020-12-07 21:53 UTC, merged

2020-12-07 23:46 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#07f97780-a8a7-4529-bf87-947377fc2845) |
| mint-gateway-azure.sh | :x: [more...](#1e2da760-3c43-42dc-92a6-4fc08f6e2584) |
<a name="07f97780-a8a7-4529-bf87-947377fc2845"></a>
### 11047-8483d42/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32052
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4ad7198338f4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 1 hours 37 minutes and 53 seconds
{
  "name": "mc",
  "duration": "5859186",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-25640 --quiet --no-color mirror /mint/data myminio/mc-test-bucket-8836  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-8836/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-8836/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-8836/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-8836/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-8836/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-8836/datafile-1-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-8836/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-8836/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-8836/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-8836/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-8836/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-8836/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-8836/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-8836/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-8836/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. A timeout occurred while trying to lock a resource, please reduce your request rate\nTotal: 0 B, Transferred: 1.54 GiB, Speed: 275.03 KiB/s"
}
(7/15) Running minio-dotnet tests ... done in 44 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 16 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 3 seconds
(10/15) Running minio-js tests ... done in 48 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 47 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1e2da760-3c43-42dc-92a6-4fc08f6e2584"></a>
### 11047-8483d42/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31718
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 50761268f245:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 0 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 3 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 1 minutes and 14 seconds
{
  "name": "mc",
  "duration": "193",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-29478 --quiet --no-color mb myminio/mc-test-bucket-15044  >>> \nmc: <ERROR> Unable to make bucket `myminio/mc-test-bucket-15044`. Your previous request to create the named bucket succeeded and you already own it."
}
(7/15) Running minio-dotnet tests ... done in 1 minutes and 46 seconds
(8/15) Running minio-go tests ... FAILED in 3 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-2druwx4rpdyik5h1",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1022,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 10 minutes and 19 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 175,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:7a99bfcb-001e-0177-2ce7-cc2efa000000\nTime:2020-12-07T22:21:33.1711406Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'roHNT4JaoyjUvACqcIuqZZ6JJzlssdm70Pf0v+My6pQ=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:554f4f17-d5c8-4977-5794-7d4678f1c83a\nx-ms-date:Mon, 07 Dec 2020 22:21:33 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-3be89at/minio-java-test-3u7nv65\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-3be89at/minio-java-test-3u7nv65?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-07T21:52:56Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [554f4f17-d5c8-4977-5794-7d4678f1c83a]\n   X-Ms-Date: [Mon, 07 Dec 2020 22:21:33 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Mon, 07 Dec 2020 22:21:32 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [7a99bfcb-001e-0177-2ce7-cc2efa000000]\n\n\n, bucketName = minio-java-test-3be89at, objectName = minio-java-test-3u7nv65, resource = /minio-java [...]

2020-12-08 00:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#1e9c6947-ac49-4400-8095-0f41cda729b2) |
| mint-zoned.sh | :x: [more...](#86dcc56a-92ce-4d1c-9099-fad59fbf3839) |
<a name="86dcc56a-92ce-4d1c-9099-fad59fbf3839"></a>
### 11047-8b7746a/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30764
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 166378a44514:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 15 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 55 seconds
(8/15) Running minio-dotnet tests ... done in 53 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 27 seconds
{
  "args": {
    "bucketName": "minio-go-test-ea1t54ld0d4jg1lx",
    "objectName": "34jtvm0dou2jggkxhxp0jtw4q9htd0",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3779,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjects(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjects",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 1 minutes and 18 seconds
(10/15) Running minio-js tests ... done in 49 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 33 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="1e9c6947-ac49-4400-8095-0f41cda729b2"></a>
### 11047-8b7746a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31391
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 11d26e1a99a9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 0 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 3 minutes and 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 4 minutes and 29 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 55 seconds
{
  "args": {
    "bucketName": "minio-go-test-r2ezuxz6lzhl6tch",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1195,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 9 minutes and 4 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 173,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:4d7ddd8b-101e-000a-68f7-ccf467000000\nTime:2020-12-08T00:16:34.3775632Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request '53USOzXJOD6xWHpdD2g460O9DT08XqqyeBQPkCFmugo=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:1fd0fa26-062d-460e-61fc-72af6ec44de7\nx-ms-date:Tue, 08 Dec 2020 00:16:34 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-20ct316/minio-java-test-3a7i4pm\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-20ct316/minio-java-test-3a7i4pm?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-07T23:47:12Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [1fd0fa26-062d-460e-61fc-72af6ec44de7]\n   X-Ms-Date: [Tue, 08 Dec 2020 00:16:34 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Tue, 08 Dec 2020 00:16:34 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [4d7ddd8b-101e-000a-68f7-ccf467000000]\n\n\n, bucketName = minio-java-test-20ct316, objectName = minio-java-test-3a7i4pm, resource = /minio-java-test-20ct316/minio-java-test-3a7i4pm, requestId = 164E959757C009BA, hostId = ce289d92-5281-48f6-a75d-e8e48fd2ccb9)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31391/minio-java-test-20ct316/minio-java-test-3a7i4pm, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev7.minio.io:31391\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201208T001634Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201208/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 164E959757C009BA\nX-Xss-Protection: 1; mode=block\nDate: Tue, 08 Dec 2020 00:16:34 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(Func [...]