admin: ServerInfo returns info without object layer initialized
minio/minio pull request #11142
Opened 2020-12-19 16:10 UTC by vadmeste

## Description
The only function change in this PR is the ability of madmin ServerInfo (mc admin info)
to return even the object layer is not initialized yet. Otherwise all changes are either
moving or code simplification.

Also when the cluster is not initialized yet, ServerInfo returns 'initializing' mode.

## Motivation and Context
Users should be able to call mc admin info when the cluster is in initialization phase.
This will at least shows network connection status between nodes and disks status
if available.

## How to test this PR?
1. Run one node / 4 nodes 
2. mc admin info node1

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2020-12-19 17:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#4831b17f-7bc7-4472-bb9c-8326dfd50322) |
<a name="4831b17f-7bc7-4472-bb9c-8326dfd50322"></a>
### 11142-b2a7075/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31175
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fb7e44bfa729:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 51 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 47 seconds
(6/15) Running healthcheck tests ... done in 5 seconds
(7/15) Running mc tests ... done in 3 minutes and 37 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 17 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 48 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 172,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:fc412de4-c01e-010c-4426-d6454a000000\nTime:2020-12-19T16:43:36.1299540Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'qX8/Qv+sCDKM51ocqZNpFiDwDk8siFg0PO8ssCXSRmI=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:663c4bd3-56fe-4ac7-4bed-ce26c3863fe5\nx-ms-date:Sat, 19 Dec 2020 16:43:36 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-q16c51/minio-java-test-3vvqs0t\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-q16c51/minio-java-test-3vvqs0t?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-19T16:10:36Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [663c4bd3-56fe-4ac7-4bed-ce26c3863fe5]\n   X-Ms-Date: [Sat, 19 Dec 2020 16:43:36 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Sat, 19 Dec 2020 16:43:35 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [fc412de4-c01e-010c-4426-d6454a000000]\n\n\n, bucketName = minio-java-test-q16c51, objectName = minio-java-test-3vvqs0t, resource = /minio-java-test-q16c51/minio-java-test-3vvqs0t, requestId = 16522BD639B41724, hostId = 2b3db5c9-33b5-4243-a23c-43561300357b)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31175/minio-java-test-q16c51/minio-java-test-3vvqs0t, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev4.minio.io:31175\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201219T164336Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201219/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16522BD639B41724\nX-Xss-Protection: 1; mode=block\nDate: Sat, 19 Dec 2020 16:43:36 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 47 seconds
(11/15) Running minio-py tests ... done in 18 minutes and 17 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 15 seconds
(13/15) Running s3select tests ... done in 58 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-12-20 03:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#fcaca9f0-3792-49bd-801a-3d2fc612a47e) |
<a name="fcaca9f0-3792-49bd-801a-3d2fc612a47e"></a>
### 11142-38041b3/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32538
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 679c3f62a363:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 10 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 57 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 47 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 42 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 51 seconds
{
  "args": {
    "bucketName": "minio-go-test-rqbxe2ueym4cgwdq",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1235,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 9 minutes and 2 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 196,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:d0b8a566-901e-0136-0f7e-d606e9000000\nTime:2020-12-20T03:14:50.9111725Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request '+2maWNpc9nNotK5Wi7WlWex36rVYgCJ4SMhD4QmMAOg=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:a5c552be-1264-48e3-582b-c744eecf37f6\nx-ms-date:Sun, 20 Dec 2020 03:14:50 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-359q8vt/minio-java-test-1n90rgq\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-359q8vt/minio-java-test-1n90rgq?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-20T02:46:00Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [a5c552be-1264-48e3-582b-c744eecf37f6]\n   X-Ms-Date: [Sun, 20 Dec 2020 03:14:50 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Sun, 20 Dec 2020 03:14:50 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [d0b8a566-901e-0136-0f7e-d606e9000000]\n\n\n, bucketName = minio-java-test-359q8vt, objectName = minio-java-test-1n90rgq, resource = /minio-java-test-359q8vt/minio-java-test-1n90rgq, requestId = 16524E48A15E9921, hostId = 37aa6487-88a1-4f9b-a15f-e500bad72792)\nrequest={method=PUT, url=http://minio-c2.minio.io:32538/minio-java-test-359q8vt/minio-java-test-1n90rgq, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-c2.minio.io:32538\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201220T031450Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201220/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16524E48A15E9921\nX-Xss-Protection: 1; mode=block\nDate: Sun, 20 Dec 2020 03:14:50 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 78,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 18 minutes and 39 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 28 seconds
(11/15) Running s3select tests ... done in 41 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-12-20 23:43 UTC, Albadrany99 approved these changes

2020-12-21 00:07 UTC, harshavardhana requested changes
I did some downed server testing with this PR on docker-compose found it is beneficial to have the following settings and also some cleanup in the implementation


```diff
diff --git a/cmd/common-main.go b/cmd/common-main.go
index 68edba93c..956ee0fe3 100644
--- a/cmd/common-main.go
+++ b/cmd/common-main.go
@@ -51,7 +51,7 @@ func init() {
        logger.RegisterError(config.FmtError)
 
        rand.Seed(time.Now().UTC().UnixNano())
-       globalDNSCache = xhttp.NewDNSCache(3*time.Second, 10*time.Second)
+       globalDNSCache = xhttp.NewDNSCache(10*time.Second, 3*time.Second)
 
        initGlobalContext()
 
diff --git a/cmd/http/dial_dnscache.go b/cmd/http/dial_dnscache.go
index 8c139f9a1..91785e35b 100644
--- a/cmd/http/dial_dnscache.go
+++ b/cmd/http/dial_dnscache.go
@@ -97,8 +97,9 @@ type DNSCache struct {
        lookupHostFn  func(ctx context.Context, host string) ([]string, error)
        lookupTimeout time.Duration
 
-       cache  map[string][]string
-       closer func()
+       cache    map[string][]string
+       doneOnce sync.Once
+       doneCh   chan struct{}
 }
 
 // NewDNSCache initializes DNS cache resolver and starts auto refreshing
@@ -113,26 +114,24 @@ func NewDNSCache(freq time.Duration, lookupTimeout time.Duration) *DNSCache {
                lookupTimeout = defaultLookupTimeout
        }
 
-       ticker := time.NewTicker(freq)
-       ch := make(chan struct{})
-       closer := func() {
-               ticker.Stop()
-               close(ch)
-       }
-
        r := &DNSCache{
                lookupHostFn:  net.DefaultResolver.LookupHost,
                lookupTimeout: lookupTimeout,
                cache:         make(map[string][]string, cacheSize),
-               closer:        closer,
+               doneCh:        make(chan struct{}),
        }
 
+       timer := time.NewTimer(freq)
        go func() {
+               defer timer.Stop()
+
                for {
                        select {
-                       case <-ticker.C:
+                       case <-timer.C:
+                               timer.Reset(freq)
+
                                r.Refresh()
-                       case <-ch:
+                       case <-r.doneCh:
                                return
                        }
                }
@@ -188,10 +187,7 @@ func (r *DNSCache) Refresh() {
 
 // Stop stops auto refreshing.
 func (r *DNSCache) Stop() {
-       r.Lock()
-       defer r.Unlock()
-       if r.closer != nil {
-               r.closer()
-               r.closer = nil
-       }
+       r.doneOnce.Do(func() {
+               close(r.doneCh)
+       })
 }
```

Feel free to incorporate this into this PR.

2020-12-21 14:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#288cca3d-5697-44d5-be86-9964d8dc92eb) |
<a name="288cca3d-5697-44d5-be86-9964d8dc92eb"></a>
### 11142-ef5e770/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31735
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2d9edd263698:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 57 seconds
(4/15) Running aws-sdk-ruby tests ... done in 22 seconds
(5/15) Running awscli tests ... done in 2 minutes and 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 42 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 21 seconds
(10/15) Running minio-java tests ... FAILED in 9 minutes and 4 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 172,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:60a52f16-c01e-0008-2fa3-d7f69d000000\nTime:2020-12-21T14:15:47.2734888Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request '9ljk2B8JCI0ivJ4xZ2zYYdYkC34X617Urj0xlh9RD28=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:0bcade24-af24-40b6-443f-cbe649b0990b\nx-ms-date:Mon, 21 Dec 2020 14:15:47 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-1a3ppn4/minio-java-test-cge3hn\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-1a3ppn4/minio-java-test-cge3hn?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-12-21T13:42:17Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [0bcade24-af24-40b6-443f-cbe649b0990b]\n   X-Ms-Date: [Mon, 21 Dec 2020 14:15:47 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Mon, 21 Dec 2020 14:15:46 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [60a52f16-c01e-0008-2fa3-d7f69d000000]\n\n\n, bucketName = minio-java-test-1a3ppn4, objectName = minio-java-test-cge3hn, resource = /minio-java-test-1a3ppn4/minio-java-test-cge3hn, requestId = 1652C0EE6B3EC44E, hostId = 2ca4999a-c95b-411c-8f95-4f8c1482bdd3)\nrequest={method=PUT, url=http://minio-c2.minio.io:31735/minio-java-test-1a3ppn4/minio-java-test-cge3hn, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-c2.minio.io:31735\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20201221T141547Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20201221/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1652C0EE6B3EC44E\nX-Xss-Protection: 1; mode=block\nDate: Mon, 21 Dec 2020 14:15:47 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(11/15) Running minio-py tests ... done in 18 minutes and 21 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 14 seconds
(13/15) Running s3select tests ... done in 59 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-12-21 17:34 UTC, harshavardhana approved these changes

2020-12-21 17:35 UTC, merged