xl: Remove check-dir in ReadVersion
minio/minio pull request #11200
Opened 2021-01-01 12:39 UTC by vadmeste

## Description
The only purpose of check-dir flag in ReadVersion is to return 404 when
an object has xl.meta but without data.

This is causing an extract call to the disk which can be penalizing in case
of busy system where disks receive many concurrent access.

## Motivation and Context
Accelerate a little bit Head/Get objects

## How to test this PR?
Little performance increase with warp

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed

2021-01-01 13:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#ad21da37-47f5-4477-9fbe-71e341136079) |
<a name="ad21da37-47f5-4477-9fbe-71e341136079"></a>
### 11200-76f7bcc/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32273
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2d1319fbb941:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 25 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 3 minutes and 1 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 57 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/15) Running minio-go tests ... done in 7 minutes and 10 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 50 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 204,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:a10f78ef-701e-00d6-353f-e0a634000000\nTime:2021-01-01T13:12:08.9060903Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request '7gJEfRsmDQjXcU7uA1KkwcBQXCmEqUSY/13LhhqASkc=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:3b66f91f-c277-479d-6756-9713377e2da4\nx-ms-date:Fri, 01 Jan 2021 13:12:08 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-3p9i7g5/minio-java-test-k5lvsr\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-3p9i7g5/minio-java-test-k5lvsr?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-01T12:39:16Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [3b66f91f-c277-479d-6756-9713377e2da4]\n   X-Ms-Date: [Fri, 01 Jan 2021 13:12:08 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Fri, 01 Jan 2021 13:12:07 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [a10f78ef-701e-00d6-353f-e0a634000000]\n\n\n, bucketName = minio-java-test-3p9i7g5, objectName = minio-java-test-k5lvsr, resource = /minio-java-test-3p9i7g5/minio-java-test-k5lvsr, requestId = 16561DD79F836DC9, hostId = ef636a2a-ce02-47a3-a237-499de090d842)\nrequest={method=PUT, url=http://minio-dev8.minio.io:32273/minio-java-test-3p9i7g5/minio-java-test-k5lvsr, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev8.minio.io:32273\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210101T131208Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210101/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16561DD79F836DC9\nX-Xss-Protection: 1; mode=block\nDate: Fri, 01 Jan 2021 13:12:08 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 37 seconds
(11/15) Running minio-py tests ... done in 17 minutes and 59 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 27 seconds
(13/15) Running s3select tests ... done in 59 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-01-01 17:40 UTC, harshavardhana requested changes
Does healing code need this change?

2021-01-01 17:50 UTC, vadmeste commented
> Does healing code need this change?

Healing code is not connected to this at all

2021-01-01 20:34 UTC, harshavardhana approved these changes

2021-01-01 20:34 UTC, harshavardhana commented
@vadmeste does this change the fix here 

```
commit eb95353cb10546c2d7bff28af5bf5576a65741a4
Author: Anis Elleuch <vadmeste@users.noreply.github.com>
Date:   Mon Oct 26 18:30:46 2020 +0100

    fix: Get/HeadObject return 404 on non quorum objects (#10753)
```

2021-01-01 20:55 UTC, harshavardhana requested changes
Waiting on verifying the 503 situation with GetObject

2021-01-02 07:04 UTC, harshavardhana commented
```diff
 git diff
diff --git a/cmd/erasure-decode.go b/cmd/erasure-decode.go
index 14861cea2..d63e456be 100644
--- a/cmd/erasure-decode.go
+++ b/cmd/erasure-decode.go
@@ -32,6 +32,7 @@ var errHealRequired = errors.New("heal required")
 type parallelReader struct {
        readers       []io.ReaderAt
        orgReaders    []io.ReaderAt
+       errs          []error
        dataBlocks    int
        offset        int64
        shardSize     int64
@@ -49,6 +50,7 @@ func newParallelReader(readers []io.ReaderAt, e Erasure, offset, totalLength int
        return &parallelReader{
                readers:       readers,
                orgReaders:    readers,
+               errs:          make([]error, len(readers)),
                dataBlocks:    e.dataBlocks,
                offset:        (offset / e.blockSize) * e.ShardSize(),
                shardSize:     e.ShardSize(),
@@ -167,8 +169,10 @@ func (p *parallelReader) Read(dst [][]byte) ([][]byte, error) {
                                }
 
                                // This will be communicated upstream.
-                               p.orgReaders[bufIdx] = nil
                                p.readers[i] = nil
+                               p.orgReaders[bufIdx] = nil
+                               p.errs[i] = err
+
                                // Since ReadAt returned error, trigger another read.
                                readTriggerCh <- true
                                return
@@ -191,7 +195,7 @@ func (p *parallelReader) Read(dst [][]byte) ([][]byte, error) {
                return newBuf, nil
        }
 
-       return nil, errErasureReadQuorum
+       return nil, reduceReadQuorumErrs(context.Background(), p.errs, objectOpIgnoredErrs, p.dataBlocks)
 }
 
 type errDecodeHealRequired struct {
```

This adds the necessary error translation needed for GetObject() @vadmeste

2021-01-02 07:05 UTC, harshavardhana commented
We should also add unit tests for this @vadmeste

2021-01-02 11:53 UTC, vadmeste commented
All comments addressed @harshavardhana, thanks for the tip

2021-01-02 12:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#275b07e5-e37f-4c5d-b0a4-3c6ac1b8f7dd) |
<a name="275b07e5-e37f-4c5d-b0a4-3c6ac1b8f7dd"></a>
### 11200-f5edc40/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31816
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4edf9cac2cad:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 28 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 3 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 54 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 30 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 39 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 170,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:9897e624-201e-0160-6e02-e1ee99000000\nTime:2021-01-02T12:25:29.6094232Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'V+bNVdHp5TvhLmqIJwT6fM8L+dfHGiUV3neAOqbnsbA=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:ce4f17e8-52c6-46ec-582b-1980e4f06964\nx-ms-date:Sat, 02 Jan 2021 12:25:29 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-2vibt9c/minio-java-test-2hpvm3v\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-2vibt9c/minio-java-test-2hpvm3v?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-02T11:53:13Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [ce4f17e8-52c6-46ec-582b-1980e4f06964]\n   X-Ms-Date: [Sat, 02 Jan 2021 12:25:29 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Sat, 02 Jan 2021 12:25:29 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [9897e624-201e-0160-6e02-e1ee99000000]\n\n\n, bucketName = minio-java-test-2vibt9c, objectName = minio-java-test-2hpvm3v, resource = /minio-java-test-2vibt9c/minio-java-test-2hpvm3v, requestId = 165669E06F90038B, hostId = 0087f5a5-038e-4a53-98c7-9d6452c5dbb0)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31816/minio-java-test-2vibt9c/minio-java-test-2hpvm3v, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev7.minio.io:31816\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210102T122529Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210102/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 165669E06F90038B\nX-Xss-Protection: 1; mode=block\nDate: Sat, 02 Jan 2021 12:25:29 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 39 seconds
(11/15) Running minio-py tests ... done in 18 minutes and 12 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 13 seconds
(13/15) Running s3select tests ... done in 59 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-01-02 18:34 UTC, harshavardhana approved these changes

2021-01-02 18:35 UTC, merged