read-health check endpoint returns success if cluster can serve read
minio/minio pull request #11310
Opened 2021-01-20 08:22 UTC by krishnasrinivas

## Description
Customer request for sidekick feature such that sidekick should route requests to faileover site even if it's read-only.

## How to test this PR?
Have two sites. Use sidekick to test. As:
```
  5. Two sites, each site having two zones, each zone having 4 servers. After failover, allow read requests to site2 even if it has just read quorum:
     $ sidekick --health-path=/minio/health/cluster --read-health-path=/minio/health/cluster/read  http://site1-minio{1...4}:9000,http://site1-minio{5...8}:9000 \
               http://site2-minio{1...4}:9000,http://site2-minio{5...8}:9000
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-01-20 09:14 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#73f1f0fe-c458-4607-afdc-3763b103b890) |
<a name="73f1f0fe-c458-4607-afdc-3763b103b890"></a>
### 11310-809e4f0/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31601
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 92bc2a47eba9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 51 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 47 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 39 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 2 seconds
{
  "args": {
    "bucketName": "minio-go-test-dbpfujupb6pinsuh",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1061,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 8 minutes and 45 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 171,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:9566dd4b-601e-0068-4f09-efb3bf000000\nTime:2021-01-20T08:51:23.7293038Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'OsMD8VYYLGDtt0xBnzcdiYOgHvJbFIWwksDpn3LOEo8=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:da6b5a04-f071-43ad-72f1-c169f255eefc\nx-ms-date:Wed, 20 Jan 2021 08:51:23 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-2ld940e/minio-java-test-3ktbrh7\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-2ld940e/minio-java-test-3ktbrh7?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-20T08:22:42Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [da6b5a04-f071-43ad-72f1-c169f255eefc]\n   X-Ms-Date: [Wed, 20 Jan 2021 08:51:23 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1092]\n   Content-Type: [application/xml]\n   Date: [Wed, 20 Jan 2021 08:51:23 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [9566dd4b-601e-0068-4f09-efb3bf000000]\n\n\n, bucketName = minio-java-test-2ld940e, objectName = minio-java-test-3ktbrh7, resource = /minio-java-test-2ld940e/minio-java-test-3ktbrh7, requestId = 165BE4A3BD140CC1, hostId = 2c0c39ad-85d3-42c7-b5e5-4fc59e9850ce)\nrequest={method=PUT, url=http://minio-c2.minio.io:31601/minio-java-test-2ld940e/minio-java-test-3ktbrh7, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-c2.minio.io:31601\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210120T085123Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210120/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3086\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 165BE4A3BD140CC1\nX-Xss-Protection: 1; mode=block\nDate: Wed, 20 Jan 2021 08:51:23 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 80,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 18 minutes and 35 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 19 seconds
(11/15) Running s3select tests ... done in 40 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-01-20 14:02 UTC, klauspost reviewed
Minor stuff.

2021-01-20 14:02 UTC, klauspost commented on cmd/fs-v1.go
> +	return true
Maybe `os.Stat` the root?

2021-01-20 14:02 UTC, klauspost commented on cmd/gateway-unsupported.go
> +// HealthRead - No Op.
```suggestion
// ReadHealth - No Op.
```
Fixes lint.

2021-01-20 14:02 UTC, klauspost commented on cmd/gateway-unsupported.go
> +	return false
Can't this still be hit? Maybe return true?

2021-01-20 21:03 UTC, krishnasrinivas commented
@klauspost made the suggested changes

2021-01-20 21:06 UTC, harshavardhana requested changes

2021-01-20 21:06 UTC, harshavardhana commented on cmd/fs-v1.go
> +	return true
```suggestion

// ReadHealth returns "read" health of the object layer
func (fs *FSObjects) ReadHealth(ctx context.Context) bool {
	err := os.Stat(fs.fsPath)
	return err == nil
```

2021-01-20 22:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#8d95e0e4-d5d9-4598-8a8a-d3bcda293b87) |
<a name="8d95e0e4-d5d9-4598-8a8a-d3bcda293b87"></a>
### 11310-9533d8c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31407
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e7de8bd86a9f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 53 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 57 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 49 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 45 seconds
(9/15) Running minio-go tests ... done in 6 minutes and 45 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 57 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 196,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:05455e66-c01e-004c-7174-ef2af1000000\nTime:2021-01-20T21:36:42.0334456Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'bzt96R3zGrAFkB5zUtazmagbeXpJ/Fjni3orgyXsZdU=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:4d009fa7-430b-4810-7f04-0b85db7d7626\nx-ms-date:Wed, 20 Jan 2021 21:36:42 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-23p3206/minio-java-test-n6i51j\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-23p3206/minio-java-test-n6i51j?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-20T21:02:35Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [4d009fa7-430b-4810-7f04-0b85db7d7626]\n   X-Ms-Date: [Wed, 20 Jan 2021 21:36:42 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Wed, 20 Jan 2021 21:36:41 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [05455e66-c01e-004c-7174-ef2af1000000]\n\n\n, bucketName = minio-java-test-23p3206, objectName = minio-java-test-n6i51j, resource = /minio-java-test-23p3206/minio-java-test-n6i51j, requestId = 165C0E66EBEC9BD2, hostId = caf8b0f0-be9f-485b-81f4-0b3ee680e3c9)\nrequest={method=PUT, url=http://minio-c2.minio.io:31407/minio-java-test-23p3206/minio-java-test-n6i51j, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-c2.minio.io:31407\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210120T213641Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210120/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 165C0E66EBEC9BD2\nX-Xss-Protection: 1; mode=block\nDate: Wed, 20 Jan 2021 21:36:42 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 47 seconds
(11/15) Running minio-py tests ... done in 18 minutes and 53 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 39 seconds
(13/15) Running s3select tests ... done in 1 minutes and 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-01-20 22:02 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 11310-1599384/gopath/src/github.com/minio
+ git -C 11310-1599384/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 11310-1599384/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 11310-1599384/gopath/src/github.com/minio/minio fetch --quiet minio pull/11310/head:pr11310
+ git -C 11310-1599384/gopath/src/github.com/minio/minio checkout --quiet pr11310
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/11310-1599384/gopath
+ make -C 11310-1599384/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading github.com/minio/cli v1.22.0
go: downloading google.golang.org/api v0.5.0
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.5.0
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/minio/minio-go/v7 v7.0.7-0.20210105224719-8dddba43079f
go: downloading github.com/shirou/gopsutil v3.20.11+incompatible
go: downloading go.etcd.io/etcd v0.0.0-20201125193152-8a03d2e9614b
go: downloading github.com/klauspost/compress v1.11.7
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/gorilla/handlers v1.5.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/ncw/directio v1.0.5
go: downloading golang.org/x/net v0.0.0-20201216054612-986b41b23924
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading golang.org/x/sys v0.0.0-20201119102817-f84b799fce68
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/tinylib/msgp v1.1.3
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/felixge/httpsnoop v1.0.1
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading google.golang.org/grpc v1.26.0
go: downloading go.uber.org/zap v1.13.0
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading golang.org/x/crypto v0.0.0-20201124201722-c8d3bf9c5392
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/gomodule/redigo v1.8.3
go: downloading github.com/nats-io/nkeys v0.2.0
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/golang/snappy v0.0.1
go: downloading go.uber.org/atomic v1.5.0
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/google/uuid v1.1.2
go: downloading golang.org/x/text v0.3.3
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/lib/pq v1.8.0
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading github.com/pierrec/lz4 v2.5.2+incompatible
go: downloading github.com/minio/sio v0.2.1
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading github.com/klauspost/reedsolomon v1.9.9
go: downloading go.opencensus.io v0.22.5
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/nats-io/stan.go v0.7.0
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/nats-io/jwt v1.1.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/minio/md5-simd v1.1.0
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/olivere/elastic/v7 v7.0.22
go: downloading github.com/minio/simdjson-go v0.2.0
go: downloading github.com/prometheus/procfs v0.2.0
go: downloading github.com/json-iterator/go v1.1.10
go: downloading go.uber.org/multierr v1.3.0
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/coredns/coredns v1.4.0
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/prometheus/common v0.14.0
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/klauspost/cpuid/v2 v2.0.3
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/rcrowley/go-metrics v0.0.0-20200313005456-10cdbea86bc0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/tidwall/gjson v1.6.7
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github [...]

2021-01-20 23:18 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#1915bc4c-0bd0-438a-80b1-132e0ead2cc2) |
| mint-erasure.sh | :x: [more...](#8f173bca-19e3-4702-a3f2-c6618eb4e8da) |
<a name="1915bc4c-0bd0-438a-80b1-132e0ead2cc2"></a>
### 11310-dff14df/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32120
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 15730c126fe3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 52 seconds
(4/15) Running aws-sdk-ruby tests ... done in 21 seconds
(5/15) Running awscli tests ... done in 2 minutes and 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 58 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 40 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 49 seconds
{
  "args": {
    "bucketName": "minio-go-test-k6g3n9u5ggacu0p2",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1027,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 8 minutes and 58 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 169,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:2c95eada-101e-0141-7e7f-ef83a8000000\nTime:2021-01-20T22:55:17.1861563Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'o6MSapmFuh1glob0j9eeTxyaTKhBeafRD6SembJpSJw=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:2c66533c-6d39-46c0-5612-483f41ac88b9\nx-ms-date:Wed, 20 Jan 2021 22:55:17 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-21ct9h5/minio-java-test-3eavru\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-21ct9h5/minio-java-test-3eavru?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-20T22:26:08Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [2c66533c-6d39-46c0-5612-483f41ac88b9]\n   X-Ms-Date: [Wed, 20 Jan 2021 22:55:17 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Wed, 20 Jan 2021 22:55:16 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [2c95eada-101e-0141-7e7f-ef83a8000000]\n\n\n, bucketName = minio-java-test-21ct9h5, objectName = minio-java-test-3eavru, resource = /minio-java-test-21ct9h5/minio-java-test-3eavru, requestId = 165C12B0C1A6E45A, hostId = 511df374-28b1-46f0-9ef5-471f4ef637a2)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32120/minio-java-test-21ct9h5/minio-java-test-3eavru, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev6.minio.io:32120\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210120T225517Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210120/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 165C12B0C1A6E45A\nX-Xss-Protection: 1; mode=block\nDate: Wed, 20 Jan 2021 22:55:17 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 78,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... done in 18 minutes and 38 seconds
(10/15) Running s3cmd tests ... done in 2 minutes and 23 seconds
(11/15) Running s3select tests ... done in 40 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="8f173bca-19e3-4702-a3f2-c6618eb4e8da"></a>
### 11310-dff14df/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31778
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTT [...]

2021-01-23 20:45 UTC, harshavardhana requested changes
Can you document this at docs/metrics/healthcheck/

2021-01-26 07:19 UTC, harshavardhana commented
> Can you document this at docs/metrics/healthcheck/

@krishnasrinivas can you update the docs?

2021-01-29 00:15 UTC, harshavardhana commented
> @krishnasrinivas can you update the docs?

@krishnasrinivas can you update the docs?

2021-02-06 03:24 UTC, harshavardhana approved these changes

2021-02-06 03:26 UTC, harshavardhana commented
The build has failed @krishnasrinivas

2021-02-09 03:04 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#79893f55-64cf-43fa-87f1-39ba4dbe491c) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#7cd02c58-b10b-4b8b-bda3-624b66520cf9) |
<a name="7cd02c58-b10b-4b8b-bda3-624b66520cf9"></a>
### 11310-67588fc/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32093
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 103883ff420b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2670,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32093 s3api copy-object --bucket awscli-mint-test-bucket-6403 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-6403/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 53 seconds
(7/15) Running minio-dotnet tests ... done in 50 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 24 seconds
{
  "args": {},
  "duration": 540,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 30 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 185,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2nf2g7f, objectName = minio-java-test-2b8rb9u-copy, resource = /minio-java-test-2nf2g7f/minio-java-test-2b8rb9u-copy, requestId = 1661F4FADAF85767, hostId = 8dc183e9-e240-4d83-ba12-a96e1a6a1ec7)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32093/minio-java-test-2nf2g7f/minio-java-test-2b8rb9u-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2bgt07o/minio-java-test-2b8rb9u\nHost: minio-dev6.minio.io:32093\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210209T025819Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210209/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 09 Feb 2021 02:58:19 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1661F4FADAF85767\nX-Xss-Protection: 1; mode=block\nDate: Tue, 09 Feb 2021 02:58:19 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 50 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 51 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3182",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-778/s3cmd-test-object-18129 87573cb1-a39e-4ec6-abf3-8b42b1bb4900\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 87573cb1-a39e-4ec6-abf3-8b42b1bb4900 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="79893f55-64cf-43fa-87f1-39ba4dbe491c"></a>
### 11310-67588fc/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32432
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a094014411c2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 1 minutes and 25 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 52 seconds
(8/15) Running minio-dotnet tests ... done in 57 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 41 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 22 seconds
(11/15) Running minio-js tests ... done in 52 seconds
(12/15) Running minio-py tests ... done in 3 minutes and 15 seconds
(13/15) Running s3cmd tests ... FAILED in 23 seconds
{
  "name": "s3cmd",
  "duration": "10612",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\nERROR: S3 error: 404 (Not Found)"
}
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-02-09 03:31 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#65052d8c-8fc7-455f-902c-3ebf5402acc0) |
<a name="65052d8c-8fc7-455f-902c-3ebf5402acc0"></a>
### 11310-ca31675/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31335
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 350dab1a3306:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2642,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:31335 s3api copy-object --bucket awscli-mint-test-bucket-13633 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-13633/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 41 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 19 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-ebyekwnbtlgnzjjt",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-ebyekwnbtlgnzjjt",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5657,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 44 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 326,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-25hp1mq, objectName = minio-java-test-3gunutg-copy, resource = /minio-java-test-25hp1mq/minio-java-test-3gunutg-copy, requestId = 1661F662AA308F47, hostId = 874117d3-d3d6-4cdb-85ee-a702d73eab33)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31335/minio-java-test-25hp1mq/minio-java-test-3gunutg-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2mceemn/minio-java-test-3gunutg\nHost: minio-dev7.minio.io:31335\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210209T032405Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210209/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 09 Feb 2021 03:24:05 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1661F662AA308F47\nX-Xss-Protection: 1; mode=block\nDate: Tue, 09 Feb 2021 03:24:05 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 1 minutes and 1 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 17 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3188",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-23242/s3cmd-test-object-29057 05835edd-10bb-4cb2-97a9-1ab1af885cf7\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 05835edd-10bb-4cb2-97a9-1ab1af885cf7 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-02-09 09:00 UTC, merged