heal: Report skipping objects with normal healing mode
minio/minio pull request #11346
Opened 2021-01-25 12:06 UTC by vadmeste

## Description
Normal healing mode skips objects that have full quorum in disks.
However, mc admin heal command does not receive any information about
these objects and users don't see any progress at all.

This PR adds a field Skipped to the item heal result structure for those
skipped objects. We call them skipped because we only check for their
presence in all disks and it is not deep healing.

## Motivation and Context
Better mc admin user experience when normal scanning is passed

## How to test this PR?
mc admin heal -r myminio/testbucket/, with and without this PR. (Actually mc still needs a little enhancement)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-01-25 12:15 UTC, klauspost commented
Does this also check data files on disk?

Normal heal scan normally also checks if the expected data files are present on disk and that their sizes match the expected one.

I am just wondering if this will remove healing of objects where one or more data files are missing or (clearly) invalid. Could you check that if you didn't already?

2021-01-25 12:41 UTC, vadmeste commented
> Normal heal scan normally also checks if the expected data files are present on disk and that their sizes match the expected one.

the thing is that Normal healing doesn't do that anymore, take a look at HealinObjects() in erasure-server-pool.go. It just checks if an object has a quorum in all disks, @harshavardhana  wanted this so it is just much faster.

2021-01-25 12:51 UTC, klauspost commented
That is a bit sad. IMO it should be there for the automatic (crawling) health checks, since otherwise it will never find out. Maybe not for full disk or for manually triggered scans.

Would an inbetween mode be possible, maybe only exposed internally. Forcing users to do bitrot checks to detect these conditions is a bit extreme. Ping @harshavardhana

2021-01-25 16:26 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#ad25fd26-82a6-4bde-8e0d-9f0353c5cf8f) |
<a name="ad25fd26-82a6-4bde-8e0d-9f0353c5cf8f"></a>
### 11346-3cb21cd/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32409
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 03f6db0fd3dd:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 55 seconds
(4/15) Running aws-sdk-ruby tests ... done in 24 seconds
(5/15) Running awscli tests ... done in 2 minutes and 58 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 40 minutes and 31 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 43 seconds
(9/15) Running minio-go tests ... done in 12 minutes and 5 seconds
(10/15) Running minio-java tests ... FAILED in 9 minutes and 4 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 186,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:ea59d873-401e-0056-6330-f3059e000000\nTime:2021-01-25T15:44:05.4013602Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'lvc1SFRUFdj94RLQj5YS8CE7oR6r97cvmy/Sbvqshpg=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:17313d03-cc6d-419b-49e1-48a5e1661f34\nx-ms-date:Mon, 25 Jan 2021 15:44:05 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-3otup1l/minio-java-test-tkms27\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-3otup1l/minio-java-test-tkms27?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-01-25T14:24:54Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [17313d03-cc6d-419b-49e1-48a5e1661f34]\n   X-Ms-Date: [Mon, 25 Jan 2021 15:44:05 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Mon, 25 Jan 2021 15:44:04 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [ea59d873-401e-0056-6330-f3059e000000]\n\n\n, bucketName = minio-java-test-3otup1l, objectName = minio-java-test-tkms27, resource = /minio-java-test-3otup1l/minio-java-test-tkms27, requestId = 165D840FDA1FA8D8, hostId = a342081f-f8a9-43e6-9deb-fab7f5d6e3a0)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32409/minio-java-test-3otup1l/minio-java-test-tkms27, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev6.minio.io:32409\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210125T154405Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210125/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 165D840FDA1FA8D8\nX-Xss-Protection: 1; mode=block\nDate: Mon, 25 Jan 2021 15:44:05 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 15 minutes and 23 seconds
(11/15) Running minio-py tests ... done in 22 minutes and 6 seconds
(12/15) Running s3cmd tests ... done in 2 minutes and 56 seconds
(13/15) Running s3select tests ... done in 1 minutes and 9 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-01-26 21:57 UTC, harshavardhana commented
> the thing is that Normal healing doesn't do that anymore, take a look at HealinObjects() in erasure-server-pool.go. It just checks if an object has a quorum in all disks, @harshavardhana wanted this so it is just much faster.

Normal scan checks for parts missing 

```
                switch scanMode {
                case madmin.HealDeepScan:
                        // disk has a valid xl.meta but may not have all the
                        // parts. This is considered an outdated disk, since
                        // it needs healing too.
                        dataErrs[i] = onlineDisk.VerifyFile(ctx, bucket, object, partsMetadata[i])
                case madmin.HealNormalScan:
                        dataErrs[i] = onlineDisk.CheckParts(ctx, bucket, object, partsMetadata[i])
                }
```

It also verifies their size and the total number of parts present. 

Of course, this stage is reached after the xl.meta has incompatibilities in Listing() i.e less than expected disks are "intact".  So xl.meta is used as a basis for further verifying if the parts are missing. 

We could potentially just heal the content upon GetObject() when the parts are missing as well that would satisfy all the requirements - so that Healing by itself is not further verifying parts per object in a lengthly listing call.

2021-01-26 21:59 UTC, harshavardhana requested changes
A better approach is to heal during GetObject() when not enough parts are found on certain disks @vadmeste just like we do deep heal when bitrot is detected.

2021-01-27 10:01 UTC, vadmeste commented
> A better approach is to heal during GetObject() when not enough parts are found on certain disks @vadmeste just like we do deep heal when bitrot is detected.

The only goal of this PR is to send objects having full quorum in all disks to mc admin heal, so users can see progress in that case.

2021-01-27 10:21 UTC, harshavardhana commented
> The only goal of this PR is to send objects having full quorum in all disks to mc admin heal, so users can see progress in that case.

This goal conflicts with the new refactor we are doing for healing, so not sure what is the value this PR brings @vadmeste - It would be perhaps better to avoid it - `mc admin heal` is getting re-implemented.

2021-01-27 10:28 UTC, vadmeste commented
> This goal conflicts with the new refactor we are doing for healing, so not sure what is the value this PR brings @vadmeste - It would be perhaps better to avoid it - `mc admin heal` is getting re-implemented.

oh okay, understood, closing this PR then.

2021-01-27 10:28 UTC, closed without merging