health-info: Add tags to errors
minio/minio pull request #11412
Opened 2021-02-02 12:14 UTC by vadmeste

## Description
We use multiple libraries in health info, but the returned error does
not indicate exactly what library call is failing, hence adding named
tags to returned errors whenever applicable.

## Motivation and Context
Add little more descriptive errors in health info result

## How to test this PR?
Trivial

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-02-02 12:43 UTC, klauspost commented on cmd/healthinfo.go
> +						Error: fmt.Sprintf("stat: %s", err.Error()),
Wrap errors:
```suggestion
						Error: fmt.Sprintf("stat: %w", err.Error()),
```

2021-02-02 13:16 UTC, vadmeste commented on cmd/healthinfo.go
> +						Error: fmt.Sprintf("stat: %s", err.Error()),
@klauspost All Errors fields are string

2021-02-02 17:25 UTC, harshavardhana requested changes
We should repeat the changes everywhere and not use err.Error() instead just use `fmt.Sprintf("topic %v", err)`

2021-02-02 17:25 UTC, harshavardhana commented on cmd/healthinfo.go
> +			Error: fmt.Sprintf("info: %s", err.Error()),
```suggestion
			Error: fmt.Sprintf("info: %v", err),
```

2021-02-02 17:25 UTC, harshavardhana commented on cmd/healthinfo.go
> +			Error: fmt.Sprintf("times: %s", err.Error()),
```suggestion
			Error: fmt.Sprintf("times: %v", err),
```

2021-02-02 17:25 UTC, harshavardhana commented on cmd/healthinfo.go
> +						Error: fmt.Sprintf("stat: %s", err.Error()),
```suggestion
						Error: fmt.Sprintf("stat: %v", err),
```

2021-02-02 17:25 UTC, harshavardhana commented on cmd/healthinfo.go
> +						driveInfo.Error = fmt.Sprintf("health-info: %s", err.Error())
```suggestion
						driveInfo.Error = fmt.Sprintf("health-info: %v", err)
```

2021-02-02 17:25 UTC, harshavardhana commented on cmd/healthinfo.go
> +			Error: fmt.Sprintf("swap: %s", err.Error()),
```suggestion
			Error: fmt.Sprintf("swap: %v", err),
```

2021-02-02 17:25 UTC, harshavardhana commented on cmd/healthinfo.go
> +			Error: fmt.Sprintf("virtual-mem: %s", err.Error()),
```suggestion
			Error: fmt.Sprintf("virtual-mem: %v", err),
```

2021-02-05 16:11 UTC, vadmeste commented
@harshavardhana, I applied your suggestion, PTAL

2021-02-05 17:58 UTC, harshavardhana commented
PTAL @vadmeste

2021-02-05 18:06 UTC, vadmeste commented
> PTAL @vadmeste

you mean @klauspost ?


@klauspost PTAL

2021-02-05 18:43 UTC, klauspost approved these changes

2021-02-05 18:46 UTC, harshavardhana approved these changes

2021-02-05 20:20 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#fb48200f-e61f-4a84-baa7-c6c3066147b6) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#74031b4d-cd43-4f28-93cf-411a7c572aa3) |
<a name="fb48200f-e61f-4a84-baa7-c6c3066147b6"></a>
### 11412-2bb9c6b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32345
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 358f584709b2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 4 minutes and 31 seconds
(4/15) Running aws-sdk-ruby tests ... done in 57 seconds
(5/15) Running awscli tests ... done in 2 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 minutes and 22 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 56 seconds
(9/15) Running minio-go tests ... FAILED in 5 minutes and 20 seconds
{
  "args": {
    "bucketName": "minio-go-test-dnglxfqnpsdvv2n1",
    "objectName": "test-object",
    "opts": "",
    "size": -1
  },
  "duration": 1080,
  "function": "PutObject(bucketName, objectName, reader,size,opts)",
  "message": "Unexpected size",
  "name": "minio-go: testPutObjectStreaming",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 8 minutes and 41 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[user metadata]",
  "duration": 169,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = AuthenticationFailed, message = -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.10.0/azblob/zc_storage_error.go:42\n===== RESPONSE ERROR (ServiceCode=AuthenticationFailed) =====\nDescription=Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:9791910c-601e-00c2-57f8-fb6550000000\nTime:2021-02-05T19:54:59.6354207Z, Details: \n   AuthenticationErrorDetail: The MAC signature found in the HTTP request 'lG5/Ei3InL4qhSbMo5vWGZ+x5ypC4mTGzhoRBAKtwLA=' is not the same as any computed signature. Server used following string to sign: 'PUT\n\n\n128\n\napplication/xml\n\n\n\n\n\n\nx-ms-blob-cache-control:\nx-ms-blob-content-disposition:\nx-ms-blob-content-encoding:\nx-ms-blob-content-language:\nx-ms-blob-content-type:application/octet-stream\nx-ms-client-request-id:f7d0633e-f740-4603-5cf4-6d537aa20efa\nx-ms-date:Fri, 05 Feb 2021 19:54:59 GMT\nx-ms-meta-my_header1:a   b   c\nx-ms-meta-my_header2:\"a   b   c\"\nx-ms-meta-my_project:Project One\nx-ms-meta-my_unicode_tag:å•†å“\nx-ms-version:2019-02-02\n/minioazure/minio-java-test-juncvk/minio-java-test-2vn9d8r\ncomp:blocklist\ntimeout:1501'.\n   Code: AuthenticationFailed\n   PUT https://minioazure.blob.core.windows.net/minio-java-test-juncvk/minio-java-test-2vn9d8r?comp=blocklist&timeout=1501\n   Authorization: REDACTED\n   Content-Length: [128]\n   Content-Type: [application/xml]\n   User-Agent: [APN/1.0 MinIO/1.0 MinIO/2021-02-05T18:54:50Z]\n   X-Ms-Blob-Cache-Control: []\n   X-Ms-Blob-Content-Disposition: []\n   X-Ms-Blob-Content-Encoding: []\n   X-Ms-Blob-Content-Language: []\n   X-Ms-Blob-Content-Type: [application/octet-stream]\n   X-Ms-Client-Request-Id: [f7d0633e-f740-4603-5cf4-6d537aa20efa]\n   X-Ms-Date: [Fri, 05 Feb 2021 19:54:59 GMT]\n   X-Ms-Meta-My_header1: [a   b   c]\n   X-Ms-Meta-My_header2: [\"a   b   c\"]\n   X-Ms-Meta-My_project: [Project One]\n   X-Ms-Meta-My_unicode_tag: [商品]\n   X-Ms-Version: [2019-02-02]\n   --------------------------------------------------------------------------------\n   RESPONSE Status: 403 Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\n   Content-Length: [1091]\n   Content-Type: [application/xml]\n   Date: [Fri, 05 Feb 2021 19:54:58 GMT]\n   Server: [Microsoft-HTTPAPI/2.0]\n   X-Ms-Error-Code: [AuthenticationFailed]\n   X-Ms-Request-Id: [9791910c-601e-00c2-57f8-fb6550000000]\n\n\n, bucketName = minio-java-test-juncvk, objectName = minio-java-test-2vn9d8r, resource = /minio-java-test-juncvk/minio-java-test-2vn9d8r, requestId = 1660F2232EF75973, hostId = 8d33ae50-07fb-4bd2-b337-01aad6d98d10)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32345/minio-java-test-juncvk/minio-java-test-2vn9d8r, headers=x-amz-meta-My-Unicode-Tag: 商品\nx-amz-meta-My-Project: Project One\nx-amz-meta-My-header1: a   b   c\nx-amz-meta-My-Header2: \"a   b   c\"\nContent-Type: application/octet-stream\nHost: minio-dev7.minio.io:32345\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20210205T195459Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210205/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-meta-my-header1;x-amz-meta-my-header2;x-amz-meta-my-project;x-amz-meta-my-unicode-tag, Signature=*REDACTED*\n}\nresponse={code=403, headers=Accept-Ranges: bytes\nContent-Length: 3082\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1660F2232EF75973\nX-Xss-Protection: 1; mode=block\nDate: Fri, 05 Feb 2021 19:54:59 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.putObject(MinioClient.java:4547), io.minio.MinioClient.putObject(MinioClient.java:2713), io.minio.MinioClient.putObject(MinioClient.java:2830), FunctionalTest.testPutObject(FunctionalTest.java:763), FunctionalTest.putObject(FunctionalTest.java:890), FunctionalTest.runObjectTests(FunctionalTest.java:3751), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 49 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 79,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... FAILED in 19 minutes and 46 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-574d0880-8add-4e0e-85de-d9c68494f715",
    "object_name": "5cec2fcd-f17e-4456-a7f7-61fc831c7391"
  },
  "message": "Sha-sum mismatch on multi-threaded put and get objects",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, [...]

2021-02-05 20:37 UTC, merged