lifecycle: don't transition delete markers
minio/minio pull request #11692
Opened 2021-03-03 19:32 UTC by krisis

## Description
This change prevents MinIO server's scanner from attempting to transition object delete markers. Note: MinIO doesn't actually transition delete markers. But it prints unactionable errors in logs while trying to fetch metadata.

```
minio4_1  | 
minio4_1  | API: SYSTEM()
minio4_1  | Time: 21:23:28 UTC 03/01/2021
minio4_1  | DeploymentID: 8747719f-13f8-4952-b40e-b2a2cd3ff030
minio4_1  | Error: Method not allowed: versioned/obj-1 (cmd.MethodNotAllowed)
minio4_1  |       11: cmd/data-scanner.go:966:cmd.applyTransitionAction()
minio4_1  |       10: cmd/data-scanner.go:1057:cmd.applyLifecycleAction()
minio4_1  |        9: cmd/data-scanner.go:895:cmd.(*crawlItem).applyActions()
minio4_1  |        8: cmd/xl-storage.go:411:cmd.(*xlStorage).CrawlAndGetDataUsage.func1()
...
```

## Motivation and Context
`lifecycle.ComputeAction` method shouldn't return a `TransitionAction` for an object version which is a delete marker. 

## How to test this PR?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-03-03 19:36 UTC, harshavardhana requested changes

2021-03-03 19:36 UTC, harshavardhana commented on pkg/bucket/lifecycle/lifecycle.go
> +func (o ObjectOpts) IsExpiredObjectDeleteMarker() bool {
```suggestion
func (o ObjectOpts) ExpiredObjectDeleteMarker() bool {
```

Is enough `Is` is not needed

2021-03-03 19:50 UTC, vadmeste approved these changes
LGTM

2021-03-03 19:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#d6626f2e-584a-4b6c-aba4-65a2a7086f04) |
<a name="d6626f2e-584a-4b6c-aba4-65a2a7086f04"></a>
### 11692-4038d6b/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30668
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e523889e923c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2899,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30668 s3api copy-object --bucket awscli-mint-test-bucket-1290 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-1290/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 52 seconds
(7/15) Running minio-dotnet tests ... done in 50 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 24 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-1jwo1wzdjh4j4pz9",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-1jwo1wzdjh4j4pz9",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5674,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 42 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 251,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-114cgoh, objectName = minio-java-test-3uftsut-copy, resource = /minio-java-test-114cgoh/minio-java-test-3uftsut-copy, requestId = 1668ECBA8A78D20C, hostId = 1811f724-d109-4434-8087-33fb74b7b1ab)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30668/minio-java-test-114cgoh/minio-java-test-3uftsut-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3na1nh5/minio-java-test-3uftsut\nHost: minio-dev4.minio.io:30668\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210303T194552Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210303/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 03 Mar 2021 19:45:52 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1668ECBA8A78D20C\nX-Xss-Protection: 1; mode=block\nDate: Wed, 03 Mar 2021 19:45:52 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 49 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 12 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3001",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-10935/s3cmd-test-object-9663 c19f146e-e2f7-4370-83a4-529ec96e4394\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id c19f146e-e2f7-4370-83a4-529ec96e4394 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-03 20:18 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 11692-b259e79/gopath/src/github.com/minio
+ git -C 11692-b259e79/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 11692-b259e79/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 11692-b259e79/gopath/src/github.com/minio/minio fetch --quiet minio pull/11692/head:pr11692
+ git -C 11692-b259e79/gopath/src/github.com/minio/minio checkout --quiet pr11692
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/11692-b259e79/gopath
+ make -C 11692-b259e79/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/minio-go/v7 v7.0.11-0.20210302210017-6ae69c73ce78
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/shirou/gopsutil/v3 v3.21.1
go: downloading golang.org/x/crypto v0.0.0-20201124201722-c8d3bf9c5392
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/fatih/color v1.10.0
go: downloading golang.org/x/sys v0.0.0-20210119212857-b64e53b001e4
go: downloading github.com/klauspost/compress v1.11.7
go: downloading github.com/prometheus/procfs v0.2.0
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading go.uber.org/zap v1.13.0
go: downloading github.com/minio/highwayhash v1.0.1
go: downloading github.com/minio/sio v0.2.1
go: downloading github.com/google/uuid v1.1.2
go: downloading go.etcd.io/etcd v0.0.0-20201125193152-8a03d2e9614b
go: downloading github.com/tinylib/msgp v1.1.3
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading golang.org/x/net v0.0.0-20201216054612-986b41b23924
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/minio/md5-simd v1.1.1
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/klauspost/reedsolomon v1.9.11
go: downloading github.com/go-ldap/ldap v3.0.2+incompatible
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/prometheus/common v0.14.0
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20200615164410-66371956d46c
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading google.golang.org/grpc v1.26.0
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/gogo/protobuf v1.3.1
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/gorilla/handlers v1.5.1
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: downloading github.com/fatih/structs v1.1.0
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading github.com/klauspost/cpuid/v2 v2.0.4
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading golang.org/x/time v0.0.0-20191024005414-555d28b269f0
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.1
go: downloading go.opencensus.io v0.22.5
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/pierrec/lz4 v2.5.2+incompatible
go: downloading github.com/nats-io/stan.go v0.7.0
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.5.0
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/lib/pq v1.8.0
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/olivere/elastic/v7 v7.0.22
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/mailru/easyjson v0.7.6
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading github.com/felixge/httpsnoop v1.0.1
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/rcrowley/go-metrics v0.0.0-20200313005456-10cdbea86bc0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading go.uber.org/atomic v1.5.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading go.uber.org/multierr v1.3.0
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/gomodule/redigo v1.8.3
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/jcmturner/goidentity/v6 v6.0.1
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading githu [...]

2021-03-03 20:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#a27888d0-477e-48ed-81a4-9959145ede57) |
<a name="a27888d0-477e-48ed-81a4-9959145ede57"></a>
### 11692-7795286/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32350
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 45fc133a60f9:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 3122,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32350 s3api copy-object --bucket awscli-mint-test-bucket-19534 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-19534/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 51 seconds
(7/15) Running minio-dotnet tests ... done in 47 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 21 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-fdz1qrk02lie2pbn",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-fdz1qrk02lie2pbn",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 6995,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 31 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 264,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3pkt7b5, objectName = minio-java-test-3ut0fn0-copy, resource = /minio-java-test-3pkt7b5/minio-java-test-3ut0fn0-copy, requestId = 1668EF68407245C2, hostId = d82a92d7-e822-4b70-b2a8-9ac9a3f07838)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32350/minio-java-test-3pkt7b5/minio-java-test-3ut0fn0-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-19qcmjk/minio-java-test-3ut0fn0\nHost: minio-dev6.minio.io:32350\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210303T203457Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210303/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 03 Mar 2021 20:34:57 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1668EF68407245C2\nX-Xss-Protection: 1; mode=block\nDate: Wed, 03 Mar 2021 20:34:57 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 53 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 0 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3067",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-17421/s3cmd-test-object-25540 05a11775-3339-433f-9d98-df1c510a8251\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 05a11775-3339-433f-9d98-df1c510a8251 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-03 23:31 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8745ea63-0d94-4830-ad00-32e52d3a60ae) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#989c7dd4-af1b-4c3e-a92b-7a02ba215181) |
<a name="8745ea63-0d94-4830-ad00-32e52d3a60ae"></a>
### 11692-39892ea/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31158
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3e2620ead13a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 15 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 14 seconds
(8/15) Running minio-dotnet tests ... done in 56 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 11 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 19 seconds
(11/15) Running minio-js tests ... FAILED in 3 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 22,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(11/15) Running minio-py tests ... done in 3 minutes and 7 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="989c7dd4-af1b-4c3e-a92b-7a02ba215181"></a>
### 11692-39892ea/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32375
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 21d483d83eae:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2639,
  "function": "aws --endpoint-url http://minio-c2.minio.io:32375 s3api copy-object --bucket awscli-mint-test-bucket-7714 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-7714/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 44 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 27 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-6u2n11vxz45tt19s",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-6u2n11vxz45tt19s",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5759,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 42 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 417,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3c15pe3, objectName = minio-java-test-2l0tnq4-copy, resource = /minio-java-test-3c15pe3/minio-java-test-2l0tnq4-copy, requestId = 1668F8A8F190625A, hostId = 85fe1162-8b5d-4241-99bc-8e672712871d)\nrequest={method=PUT, url=http://minio-c2.minio.io:32375/minio-java-test-3c15pe3/minio-java-test-2l0tnq4-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-37eepn7/minio-java-test-2l0tnq4\nHost: minio-c2.minio.io:32375\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210303T232430Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210303/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 03 Mar 2021 23:24:30 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1668F8A8F190625A\nX-Xss-Protection: 1; mode=block\nDate: Wed, 03 Mar 2021 23:24:30 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 55 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 9 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3179",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: [...]

2021-03-05 01:35 UTC, krisis commented
@harshavardhana addressed your comments. PTAL.

2021-03-05 01:46 UTC, harshavardhana approved these changes

2021-03-05 02:10 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#dcb1a835-8ca2-49a1-a309-3f7c378e2e54) |
| mint-gateway-nas.sh | :x: [more...](#ef4e8656-c4fe-40df-8611-226a6b9cb419) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#6a234d2d-7889-4290-8220-8afeec09090d) |
<a name="dcb1a835-8ca2-49a1-a309-3f7c378e2e54"></a>
### 11692-4cc40a2/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31074
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 26ba8fa022ae:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 0 seconds
{
  "name": "awscli",
  "duration": 73616,
  "function": "aws --endpoint-url http://minio-c2.minio.io:31074 s3api upload-part --bucket awscli-mint-test-bucket-7371 --key awscli-mint-test-bucket-7371-object --body /mint/data/datafile-10-MB --upload-id add4a25c-3b82-4a09-b96e-1d689ec84e04 --part-number 1\n",
  "status": "FAIL",
  "error": ""
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 13 seconds
(7/15) Running minio-dotnet tests ... done in 57 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 5 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 59 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 7 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="ef4e8656-c4fe-40df-8611-226a6b9cb419"></a>
### 11692-4cc40a2/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30088
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3234125f8730:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 54 seconds
{
  "name": "awscli",
  "duration": 62663,
  "function": "aws --endpoint-url http://minio-c2.minio.io:30088 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-7397/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-7397/datafile-0-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-7397/datafile-10-kBupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-7397/datafile-1-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-7397/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-7397/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-7397/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-7397/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-7397/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-7397/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-7397/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-7397/datafile-11-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-7397/datafile-6-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-7397/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-7397/datafile-129-MBupload failed: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-7397/datafile-1-b An error occurred (NoSuchBucket) when calling the PutObject operation: The specified bucket does not exist"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 31 seconds
(7/15) Running minio-dotnet tests ... done in 38 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 13 seconds
(9/15) Running minio-java tests ... done in 19 seconds
(10/15) Running minio-js tests ... done in 35 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 27 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="6a234d2d-7889-4290-8220-8afeec09090d"></a>
### 11692-4cc40a2/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30841
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3c80d6ee4480:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2675,
  "function": "aws --endpoint-url http://minio-c2.minio.io:30841 s3api copy-object --bucket awscli-mint-test-bucket-11182 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-11182/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 39 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 31 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-wtb06mhep94yabqt",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-wtb06mhep94yabqt",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5317,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 49 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 497,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-1mefgpu, objectName = minio-java-test-2ka4jv-copy, resource = /minio-java-test-1mefgpu/minio-ja [...]

2021-03-05 23:29 UTC, merged