Resize replication pool dynamically after config update
minio/minio pull request #11737
Opened 2021-03-08 23:37 UTC by poornas

## Description

## Motivation and Context
resize number of replication workers dynamically as per configuration

## How to test this PR?
`mc admin config set alias api` change number of replication workers to scale up/down the number of workers needed,

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-03-08 23:39 UTC, harshavardhana requested changes
Please remove `browser/production/index_bundle-2020-06-04T16-50-12Z.js`

2021-03-08 23:56 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#b235e8b2-b333-48e8-a97a-6cf1a159a02f) |
<a name="b235e8b2-b333-48e8-a97a-6cf1a159a02f"></a>
### 11737-cf0568d/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30799
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5e6c97f8a09a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2583,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30799 s3api copy-object --bucket awscli-mint-test-bucket-31792 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-31792/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 52 seconds
(7/15) Running minio-dotnet tests ... done in 52 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 24 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-033bnjdbkkxblmu6",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-033bnjdbkkxblmu6",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5950,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 27 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 268,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-34nk4g4, objectName = minio-java-test-1mdebch-copy, resource = /minio-java-test-34nk4g4/minio-java-test-1mdebch-copy, requestId = 166A82FD2D061280, hostId = a975ead9-fffc-4fb6-b7f0-ce7492c67230)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30799/minio-java-test-34nk4g4/minio-java-test-1mdebch-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-1shfvq6/minio-java-test-1mdebch\nHost: minio-dev6.minio.io:30799\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210308T235041Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210308/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Mon, 08 Mar 2021 23:50:40 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166A82FD2D061280\nX-Xss-Protection: 1; mode=block\nDate: Mon, 08 Mar 2021 23:50:40 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 49 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 13 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "2733",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-19825/s3cmd-test-object-28835 2349dfa5-ea11-4960-949c-c6f66e98302d\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 2349dfa5-ea11-4960-949c-c6f66e98302d put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-09 00:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#9008391b-d6db-40f5-bbc7-e3a4a4f695a6) |
| mint-zoned.sh | :x: [more...](#c6da02ef-0caf-497b-9c6c-0401cee1a00d) |
| mint-gateway-nas.sh | :x: [more...](#8225fd56-6755-4a6a-bd40-f82ba61b6d25) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#3736e552-cda7-47ad-a6d9-6a57948c2207) |
<a name="8225fd56-6755-4a6a-bd40-f82ba61b6d25"></a>
### 11737-6de8238/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32000
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d4dc3b452cc4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 59 seconds
{"name": "awscli", "duration": 70196, "function": "aws --endpoint-url http://minio-dev8.minio.io:32000 s3 rm --recursive s3://awscli-mint-test-bucket-27890/\n", "status": "FAIL", "error": "delete failed: s3://awscli-mint-test-bucket-27890/datafile-1.03-MB Could not connect to the endpoint URL: "http://minio-dev8.minio.io:32000/awscli-mint-test-bucket-27890/datafile-1.03-MB"delete failed: s3://awscli-mint-test-bucket-27890/datafile-33-kB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-5-MB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-5243880-b An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-6-MB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-65-MB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-1-kB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-10-MB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-0-b An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-10-kB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-129-MB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-11-MB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-100-kB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-1-MB An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not existdelete failed: s3://awscli-mint-test-bucket-27890/datafile-1-b An error occurred (NoSuchBucket) when calling the DeleteObject operation: The specified bucket does not exist"}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 49 seconds
(7/15) Running minio-dotnet tests ... done in 34 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 12 seconds
(9/15) Running minio-java tests ... done in 20 seconds
(10/15) Running minio-js tests ... done in 37 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 26 seconds
(12/15) Running s3cmd tests ... done in 14 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="c6da02ef-0caf-497b-9c6c-0401cee1a00d"></a>
### 11737-6de8238/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:32478
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6973cc1ff72c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... FAILED in 52 seconds
Mar 09, 2021 12:03:23 AM com.amazonaws.util.Base64 warn
WARNING: JAXB is unavailable. Will fallback to SDK implementation which may be less performant.If you are using Java 9+, you will need to include javax.xml.bind:jaxb-api as a dependency.
com.amazonaws.services.s3.model.AmazonS3Exception: Your previous request to create the named bucket succeeded and you already own it. (Service: Amazon S3; Status Code: 409; Error Code: BucketAlreadyOwnedByYou; Request ID: 166A83BAF8C98ECC; S3 Extended Request ID: 7d820a45-2ed9-4b97-84c6-51ff9395bebe), S3 Extended Request ID: 7d820a45-2ed9-4b97-84c6-51ff9395bebe
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1371)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1347)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1127)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:784)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:752)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:5052)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4998)
	at com.amazonaws.services.s3.AmazonS3Client.createBucket(AmazonS3Client.java:1094)
	at io.minio.awssdk.tests.FunctionalTests.initTests(Unknown Source)
	at io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)
(2/15) Running aws-sdk-php tests ... done in 42 seconds
(3/15) Running aws-sdk-ruby tests ... done in 7 seconds
(4/15) Running awscli tests ... done in 1 minutes and 14 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 6 seconds
(7/15) Running minio-dotnet tests ... done in 56 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 4 seconds
(9/15) Running minio-java tests ... done in 1 minutes and 55 seconds
(10/15) Running minio-js tests ... done in 53 seconds
(11/15) Running minio-py tests ... done in 3 minutes and 10 seconds
(12/15) Running s3cmd tests ... done in 19 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ...  [...]

2021-03-09 01:18 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#2b6e2eeb-f634-4886-be31-cd4d944538c5) |
<a name="2b6e2eeb-f634-4886-be31-cd4d944538c5"></a>
### 11737-9a0d885/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31965
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a3fccd4d9e4f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2996,
  "function": "aws --endpoint-url http://minio-c2.minio.io:31965 s3api copy-object --bucket awscli-mint-test-bucket-804 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-804/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 52 seconds
(7/15) Running minio-dotnet tests ... done in 39 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 18 seconds
{
  "args": {
    "destination": {
      "Bucket": "minio-go-test-gs033ald39qheje5",
      "Object": "dstObject",
      "Encryption": {},
      "UserMetadata": null,
      "ReplaceMetadata": false,
      "UserTags": null,
      "ReplaceTags": false,
      "LegalHold": "",
      "Mode": "",
      "RetainUntilDate": "0001-01-01T00:00:00Z",
      "Size": 0,
      "Progress": null
    },
    "source": {
      "Bucket": "minio-go-test-gs033ald39qheje5",
      "Object": "srcObject",
      "VersionID": "",
      "MatchETag": "",
      "NoMatchETag": "",
      "MatchModifiedSince": "0001-01-01T00:00:00Z",
      "MatchUnmodifiedSince": "0001-01-01T00:00:00Z",
      "MatchRange": false,
      "Start": 0,
      "End": 0,
      "Encryption": null
    }
  },
  "duration": 5381,
  "error": "We encountered an internal error, please try again.: cause(s2: corrupt input)",
  "function": "CopyObject(destination, source)",
  "message": "GetObject failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObject",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 3 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 173,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-9f7q9m, objectName = minio-java-test-6r3st1-copy, resource = /minio-java-test-9f7q9m/minio-java-test-6r3st1-copy, requestId = 166A87691A1E68A9, hostId = bcb053f3-0f05-4a8e-b490-4185b4155d24)\nrequest={method=PUT, url=http://minio-c2.minio.io:31965/minio-java-test-9f7q9m/minio-java-test-6r3st1-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3ro4o9n/minio-java-test-6r3st1\nHost: minio-c2.minio.io:31965\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210309T011140Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210309/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 414\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 09 Mar 2021 01:11:41 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166A87691A1E68A9\nX-Xss-Protection: 1; mode=block\nDate: Tue, 09 Mar 2021 01:11:41 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 48 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 8 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2981",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-11387/s3cmd-test-object-3370 45a05a76-a0d5-4046-8ec2-3b6d0b8f83dd\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 45a05a76-a0d5-4046-8ec2-3b6d0b8f83dd put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-09 10:53 UTC, klauspost approved these changes
LGTM

2021-03-09 10:55 UTC, harshavardhana approved these changes

2021-03-09 10:56 UTC, merged