Inline small file data in xl.meta file
minio/minio pull request #11758
Opened 2021-03-10 16:47 UTC by klauspost

## Description

Inline small file data in xl file.

## Motivation and Context

When writing small files < 128KB write data into xl.meta files instead of `uuid/part.1` files. This reduces disk IO for reading and writing and reduces the number of IOPS needed for these operations.

Data is appended after the metadata and is a version + messagepack `map[string][]byte` where the index is the datapath (as string) with a byte slice. If this exists for any datapath, there should not be any part data on disk.

The data is kept in a marshalled form to not add any overhead other than the initial IO from disk. No compression or modification is performed to the data.

The metadata can be read without reading the file data, and the file data can easily be stripped if present.

XL metadata version is bumped.

## How to test this PR?

CI tests should pick up most issues.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] Unit tests added/updated
- [x] FIX HEALING.

2021-03-10 17:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d26d7747-7d1d-40f9-853e-e0c687abefe1) |
| mint-gateway-s3.sh | :x: [more...](#ef6145af-2a42-4c61-a3e7-18158670c5c5) |
| mint-erasure.sh | :x: [more...](#c8737607-ec62-471f-9c26-ee208e726e5d) |
| mint-dist-erasure.sh | :x: [more...](#5dedf966-a297-42e7-a904-6ad412052b3b) |
| mint-zoned.sh | :x: [more...](#8b78c99d-f6a5-4daf-91e8-00e35e99293d) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#873b99ca-9827-48f9-a248-63684baa5c40) |
<a name="d26d7747-7d1d-40f9-853e-e0c687abefe1"></a>
### 11758-dc5c594/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32302
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 08d4df6cd19c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 5792,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-10719/datafile-0-bdelete: s3://awscli-mint-test-bucket-10719/awscli-mint-test-bucket-10719-objectremove_bucket failed: s3://awscli-mint-test-bucket-10719 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 15 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 34 seconds
{
  "args": {
    "bucketName": "minio-go-test-tbkmqbeqqtjlnp0r",
    "objectName": "e60mnmv96ujia299i0kize6pgycy3o",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5206,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjects(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjects",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 55 seconds
{
  "name": "minio-java",
  "function": "removeBucket()",
  "duration": 8,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-2rjde86, objectName = null, resource = /minio-java-test-2rjde86, requestId = 166B09BC97279182, hostId = 8b019634-cacd-47d8-81c6-0c0ab86d41f6)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:32302/minio-java-test-2rjde86, headers=Host: minio-dev4.minio.io:32302\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210310T165956Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210310/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 328\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166B09BC97279182\nX-Xss-Protection: 1; mode=block\nDate: Wed, 10 Mar 2021 16:59:56 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executeDelete(MinioClient.java:879), io.minio.MinioClient.removeBucket(MinioClient.java:2669), FunctionalTest.teardown(FunctionalTest.java:707), FunctionalTest.runObjectTests(FunctionalTest.java:3778), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... FAILED in 20 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 4,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(8/15) Running minio-py tests ... FAILED in 4 seconds
{
  "name": "minio-py:test_fput_object_large_file",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-e743902b-a094-4703-88e1-513b7e7193a5",
    "object_name": "1d3022e1-622f-41dc-b69f-9eaf664c84f0-large",
    "file_path": "/mint/data/datafile-11-MB",
    "metadata": {
      "x-amz-storage-class": "STANDARD_IA"
    }
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-e743902b-a094-4703-88e1-513b7e7193a5, request_id: 166B09C23E3508D8, host_id: 8b019634-cacd-47d8-81c6-0c0ab86d41f6, bucket_name: minio-py-test-e743902b-a094-4703-88e1-513b7e7193a5",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 356, in test_fput_object_large_file\n    _test_fput_object(bucket_name, object_name, _LARGE_FILE, metadata, sse)\n  File \"/mint/run/core/minio-py/tests.py\", line 313, in _test_fput_object\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-e743902b-a094-4703-88e1-513b7e7193a5, request_id: 166B09C23E3508D8, host_id: 8b019634-cacd-47d8-81c6-0c0ab86d41f6, bucket_name: minio-py-test-e743902b-a094-4703-88e1-513b7e7193a5\n",
  "duration": 2154
}
(8/15) Running s3cmd tests ... FAILED in 19 seconds
{
  "name": "s3cmd",
  "duration": "9763",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\ndelete: 's3://s3cmd-test-bucket-21456/datafile-0-b'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-1-MB'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-1-b'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-1-kB'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-1.03-MB'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-10-MB'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-10-kB'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-100-kB'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-11-MB'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-129-MB'\ndelete: 's3://s3cmd-test-bucket-21456/datafile-33-kB'\ndelete: 's3://s3cmd-test-bu [...]

2021-03-10 17:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5062a154-b020-4fb4-bb62-5746a58d1eb7) |
| mint-gateway-s3.sh | :x: [more...](#23422ad2-922b-42c5-8874-d5c71ec3efd2) |
| mint-erasure.sh | :x: [more...](#8d802563-25c0-4149-a4d1-d053d7dfad31) |
| mint-dist-erasure.sh | :x: [more...](#db0aa3b4-9c18-41cb-a5e5-7e82e00d042b) |
| mint-zoned.sh | :x: [more...](#957dbb2c-26eb-4adb-b155-d46761e7d2ef) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#cc848b5e-0739-4dc8-979f-5d8516dd027a) |
<a name="23422ad2-922b-42c5-8874-d5c71ec3efd2"></a>
### 11758-4f7bc27/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32148
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 67a7615cfe0d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 4948,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-21658/datafile-0-bdelete: s3://awscli-mint-test-bucket-21658/awscli-mint-test-bucket-21658-objectremove_bucket failed: s3://awscli-mint-test-bucket-21658 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 6 seconds
(7/15) Running minio-dotnet tests ... done in 38 seconds
(8/15) Running minio-go tests ... done in 1 minutes and 8 seconds
(9/15) Running minio-java tests ... FAILED in 45 seconds
{
  "name": "minio-java",
  "function": "removeBucket()",
  "duration": 14,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-h8kol4, objectName = null, resource = /minio-java-test-h8kol4, requestId = 166B0BF29BFF13C5, hostId = 032edfc3-7d5b-42bd-a8a7-3cc7fc288a7e)\nrequest={method=DELETE, url=http://minio-c2.minio.io:32148/minio-java-test-h8kol4, headers=Host: minio-c2.minio.io:32148\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210310T174027Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210310/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 326\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166B0BF29BFF13C5\nX-Xss-Protection: 1; mode=block\nDate: Wed, 10 Mar 2021 17:40:27 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executeDelete(MinioClient.java:879), io.minio.MinioClient.removeBucket(MinioClient.java:2669), FunctionalTest.teardown(FunctionalTest.java:707), FunctionalTest.runObjectTests(FunctionalTest.java:3778), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 20 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... FAILED in 2 seconds
{
  "name": "minio-py:test_fput_object_large_file",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-b836d4e1-f367-4d13-bacb-23959a9be237",
    "object_name": "4f92a7ad-2be9-4e10-adcd-6aca0c08f0bc-large",
    "file_path": "/mint/data/datafile-11-MB",
    "metadata": {
      "x-amz-storage-class": "STANDARD_IA"
    }
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-b836d4e1-f367-4d13-bacb-23959a9be237, request_id: 166B0BF7D2D9DE08, host_id: 032edfc3-7d5b-42bd-a8a7-3cc7fc288a7e, bucket_name: minio-py-test-b836d4e1-f367-4d13-bacb-23959a9be237",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 356, in test_fput_object_large_file\n    _test_fput_object(bucket_name, object_name, _LARGE_FILE, metadata, sse)\n  File \"/mint/run/core/minio-py/tests.py\", line 313, in _test_fput_object\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-b836d4e1-f367-4d13-bacb-23959a9be237, request_id: 166B0BF7D2D9DE08, host_id: 032edfc3-7d5b-42bd-a8a7-3cc7fc288a7e, bucket_name: minio-py-test-b836d4e1-f367-4d13-bacb-23959a9be237\n",
  "duration": 1156
}
(9/15) Running s3cmd tests ... FAILED in 1 minutes and 9 seconds
{
  "name": "s3cmd",
  "duration": "11960",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\ndelete: 's3://s3cmd-test-bucket-12347/datafile-0-b'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-1-MB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-1-b'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-1-kB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-1.03-MB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-10-MB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-10-kB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-100-kB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-11-MB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-129-MB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-33-kB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-5-MB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-5243880-b'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-6-MB'\ndelete: 's3://s3cmd-test-bucket-12347/datafile-65-MB'\nERROR: S3 error: 409 (BucketNotEmpty): The bucket you tried to delete is not empty"
}
(9/15) Running s3select tests ... done in 4 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="957db [...]

2021-03-12 06:01 UTC, harshavardhana requested changes

2021-03-12 06:01 UTC, harshavardhana commented on cmd/xl-storage.go
> +		if err = s.WriteAll(ctx, dstVolume, pathJoin(dstPath, xlStorageFormatFile), dstBuf); err != nil {
why are you modifying the namespace directly @klauspost - since failure here might be challenging write - that can lead to truncated xl.meta? - currently the method of rename() allows for destination to be not truncated if the rename() fails. 

This is why the commit phase to `tmp/` is present and let rename() fail appropriately. Otherwise we are not messing around with xl.meta. 

I am contemplating what does this change entail.

2021-03-12 09:38 UTC, klauspost commented on cmd/xl-storage.go
> +		if err = s.WriteAll(ctx, dstVolume, pathJoin(dstPath, xlStorageFormatFile), dstBuf); err != nil {
@harshavardhana As mentioned on slack, When looking at the code that does the existing rename it seems to 

1) Write everything to a tmp localtion.
2) Merge the existing into the tmp metadata.
3) Rename the tmp to the destination.

If 2) fails nothing happens to the existing data if 3) fails it simply copies the successful back to the tmp locations, but never restores the original metadata, unless there is [some hidden magic done in RenameData](https://github.com/minio/minio/blob/eac66e67ecbb0adad918b6edc79aa09a00c7edf6/cmd/erasure-object.go#L541).

So my rationale is that this isn't less secure than the existing functionality, and much, much faster.

If we want this done without having to rely on healing, we must copy the existing metadata when a putObject call starts, or have `writeUniqueFileInfo`/`renameData` move existing data to a predetermined location so the operation can actually be reversed.

2021-03-12 15:16 UTC, harshavardhana commented on cmd/xl-storage.go
> +		if err = s.WriteAll(ctx, dstVolume, pathJoin(dstPath, xlStorageFormatFile), dstBuf); err != nil {
Okay, I see.. but for versioning, it becomes very challenging to move so much content back and forth and then again move it back.

2021-03-12 15:16 UTC, harshavardhana commented on cmd/xl-storage.go
> +		if err = s.WriteAll(ctx, dstVolume, pathJoin(dstPath, xlStorageFormatFile), dstBuf); err != nil {
I guess let's leave this as-is for now.

2021-03-12 16:38 UTC, klauspost commented on cmd/xl-storage.go
> +		if err = s.WriteAll(ctx, dstVolume, pathJoin(dstPath, xlStorageFormatFile), dstBuf); err != nil {
It is fixable, but we need a specific place to move the data. Handling this outside this PR.

2021-03-12 16:53 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#aaf0882a-9ed2-418b-804f-e74a757d09f8) |
| mint-gateway-s3.sh | :x: [more...](#f91540ff-4e92-4f80-b284-efea9622080c) |
| mint-erasure.sh | :x: [more...](#eba1871e-f551-4db1-bd33-760a551861b4) |
| mint-dist-erasure.sh | :x: [more...](#d857a0ad-4d7e-430e-adf6-546df52d6696) |
| mint-zoned.sh | :x: [more...](#cbd9c3cc-05fa-4f35-bef3-e43468a863fd) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#aa440dd1-b6d9-4e4b-b3e2-d9be24f4908d) |
<a name="aaf0882a-9ed2-418b-804f-e74a757d09f8"></a>
### 11758-7e4b74d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30399
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e974c9e1377:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 6188,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-9686/prefix/directory/datafile-1-kBremove_bucket failed: s3://awscli-mint-test-bucket-9686 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 12 seconds
(7/15) Running minio-dotnet tests ... done in 40 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 42 seconds
(9/15) Running minio-java tests ... FAILED in 45 seconds
{
  "name": "minio-java",
  "function": "removeBucket()",
  "duration": 7,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-2js1e8j, objectName = null, resource = /minio-java-test-2js1e8j, requestId = 166BA65EF1C306F6, hostId = 1d45681d-efb3-49e8-9ab6-8fb8258add6f)\nrequest={method=DELETE, url=http://minio-dev8.minio.io:30399/minio-java-test-2js1e8j, headers=Host: minio-dev8.minio.io:30399\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210312T165018Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210312/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 328\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166BA65EF1C306F6\nX-Xss-Protection: 1; mode=block\nDate: Fri, 12 Mar 2021 16:50:18 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executeDelete(MinioClient.java:879), io.minio.MinioClient.removeBucket(MinioClient.java:2669), FunctionalTest.teardown(FunctionalTest.java:707), FunctionalTest.runObjectTests(FunctionalTest.java:3778), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 19 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 8,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... FAILED in 19 seconds
{
  "name": "minio-py:test_negative_put_object_with_path_segment",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-5f806137-c621-4002-a806-90d251f2c483",
    "object_name": "/a/b/c/e3d71558-f958-46cf-88e3-de1b959a8a3b"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-5f806137-c621-4002-a806-90d251f2c483, request_id: 166BA667E2A8322C, host_id: 1d45681d-efb3-49e8-9ab6-8fb8258add6f, bucket_name: minio-py-test-5f806137-c621-4002-a806-90d251f2c483",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 744, in test_negative_put_object_with_path_segment\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-5f806137-c621-4002-a806-90d251f2c483, request_id: 166BA667E2A8322C, host_id: 1d45681d-efb3-49e8-9ab6-8fb8258add6f, bucket_name: minio-py-test-5f806137-c621-4002-a806-90d251f2c483\n",
  "duration": 174
}
(9/15) Running s3cmd tests ... done in 27 seconds
(10/15) Running s3select tests ... done in 4 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="cbd9c3cc-05fa-4f35-bef3-e43468a863fd"></a>
### 11758-7e4b74d/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31428
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 803a067d5600:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 6047,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-19135/prefix/directory/datafile-1-kBremove_bucket failed: s3://awscli-mint-test-bucket-19135 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 17 seconds
(7/15) Running minio-dotnet tests ... done in 43 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 37 seconds
(9/15) Running minio-java tests ... FAILED in 1 minutes and 25 seconds
{
  "name": "minio-java",
  "function": "removeBucket()",
  "durati [...]

2021-03-15 16:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#96b21d67-5800-43fa-8dd5-603a8440c3d1) |
| mint-gateway-s3.sh | :x: [more...](#2ecc0612-9f32-4593-ad36-a855cc435fa9) |
| mint-erasure.sh | :x: [more...](#88e460d7-6367-4cd2-ac92-01368d3a22a3) |
| mint-dist-erasure.sh | :x: [more...](#ceefd124-7813-4c1d-b2b3-9a0f166421d3) |
| mint-zoned.sh | :x: [more...](#ac4169a4-197e-44ef-9943-c2c9fd6703be) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#520f044f-a8ec-4991-8fff-17c7b7962496) |
<a name="2ecc0612-9f32-4593-ad36-a855cc435fa9"></a>
### 11758-276b1b3/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32069
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e916b18b2cf:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qfp6kjav5wefek",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 52,
  "error": "BucketNotEmpty: The bucket you tried to delete is not empty\n\tstatus code: 409, request id: 166C902EAE538CFB, host id: ",
  "function": "testListObjects",
  "message": "AWS SDK Go DeleteBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... done in 1 seconds
(2/15) Running aws-sdk-php tests ... done in 43 seconds
(3/15) Running aws-sdk-ruby tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-ruby",
  "function": "removeBucket(bucket_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-a874c04f92a1"
  },
  "duration": 326.64,
  "error": "Failed to clean-up bucket 'aws-sdk-ruby-bucket-a874c04f92a1', The bucket you tried to delete is not empty",
  "status": "FAIL"
}
(3/15) Running awscli tests ... FAILED in 8 seconds
{
  "name": "awscli",
  "duration": 3252,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-26596/datafile-1-kBremove_bucket failed: s3://awscli-mint-test-bucket-26596 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(3/15) Running healthcheck tests ... done in 0 seconds
(4/15) Running mc tests ... done in 1 minutes and 13 seconds
(5/15) Running minio-dotnet tests ... done in 38 seconds
(6/15) Running minio-go tests ... FAILED in 1 minutes and 3 seconds
{
  "args": {
    "bucketName": "minio-go-test-423mye4kptavagyf",
    "objectName": "4ws906ugfjaajhzjxv4uawfclo9suh"
  },
  "duration": 265,
  "error": "The bucket you tried to delete is not empty",
  "function": "GetObject(bucketName, objectName)",
  "message": "Cleanup failed",
  "name": "minio-go: testGetObjectReadSeekFunctional",
  "status": "FAIL"
}
(6/15) Running minio-java tests ... FAILED in 3 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 130,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-3e305hj, objectName = null, resource = /minio-java-test-3e305hj, requestId = 166C90644123F968, hostId = 3611e9e8-1c47-4bcf-b773-065e2708c189)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:32069/minio-java-test-3e305hj, headers=Host: minio-dev4.minio.io:32069\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210315T161846Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210315/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 328\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166C90644123F968\nX-Xss-Protection: 1; mode=block\nDate: Mon, 15 Mar 2021 16:18:46 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executeDelete(MinioClient.java:879), io.minio.MinioClient.removeBucket(MinioClient.java:2669), FunctionalTest.testListObjects(FunctionalTest.java:1416), FunctionalTest.listObjects(FunctionalTest.java:1428), FunctionalTest.runObjectTests(FunctionalTest.java:3747), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(6/15) Running minio-js tests ... FAILED in 27 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 12,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(6/15) Running minio-py tests ... FAILED in 2 seconds
{
  "name": "minio-py:test_copy_object_no_copy_condition",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-c349a2c8-6985-46b2-bd4d-5af511fe40dd",
    "object_source": "ebf1dfda-5386-40a3-944b-043e56838d4b-source",
    "object_name": "ebf1dfda-5386-40a3-944b-043e56838d4b-copy"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-c349a2c8-6985-46b2-bd4d-5af511fe40dd, request_id: 166C906B3E07A4F0, host_id: 3611e9e8-1c47-4bcf-b773-065e2708c189, bucket_name: minio-py-test-c349a2c8-6985-46b2-bd4d-5af511fe40dd",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 458, in test_copy_object_no_copy_condition\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-c349a2c8-6985-46b2-bd4d-5af511fe40dd, request_id: 166C906B3E07A4F0, host_id: 3611e9e8-1c47-4bcf-b773-065e2708c189, bucket_name: minio-py-test-c349a2c8-6985-46b2-bd4d-5af511fe40dd\n",
  "duration": 276
}
(6/15) Running s3cmd tests ... FAILED in 1 minutes and 7 seconds
{
  "name": "s3cmd",
  "duration": "9457",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\ndelete: 's3://s3cmd-test-bucket-8216/datafile-0-b'\ndelete: 's3://s3cmd-test-bucket-8216/datafile-1-MB'\ndelete: 's3://s3cmd- [...]

2021-03-16 11:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0252a734-81a4-4096-a86b-0d3123fb6d3e) |
| mint-gateway-s3.sh | :x: [more...](#82fd011a-5d27-4945-9270-9ca0812262d2) |
| mint-erasure.sh | :x: [more...](#be9d582b-4db4-4730-be5a-0ab092caa421) |
| mint-dist-erasure.sh | :x: [more...](#3fbc2191-2429-45a7-8b5e-7442259f3844) |
| mint-zoned.sh | :x: [more...](#a9b17c41-ac50-40d2-9361-c4f58b623b8b) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#d12e0251-9304-4926-b71a-210dc293ddf7) |
<a name="82fd011a-5d27-4945-9270-9ca0812262d2"></a>
### 11758-3c29f67/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31294
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c81b0747251f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 12 seconds
{
  "name": "awscli",
  "duration": 5896,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-433/prefix/directory/datafile-1-kBremove_bucket failed: s3://awscli-mint-test-bucket-433 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 53 seconds
(7/15) Running minio-dotnet tests ... done in 34 seconds
(8/15) Running minio-go tests ... done in 23 seconds
(9/15) Running minio-java tests ... FAILED in 18 seconds
{
  "name": "minio-java",
  "function": "removeBucket()",
  "duration": 19,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-ds9ilo, objectName = null, resource = /minio-java-test-ds9ilo, requestId = 166CCF681CE0D792, hostId = 9eac0346-8e1d-440a-b18d-9813100e34b6)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:31294/minio-java-test-ds9ilo, headers=Host: minio-dev6.minio.io:31294\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210316T113332Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210316/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 326\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166CCF681CE0D792\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Mar 2021 11:33:32 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executeDelete(MinioClient.java:879), io.minio.MinioClient.removeBucket(MinioClient.java:2669), FunctionalTest.teardown(FunctionalTest.java:707), FunctionalTest.runObjectTests(FunctionalTest.java:3778), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... FAILED in 29 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 8,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(9/15) Running minio-py tests ... FAILED in 18 seconds
{
  "name": "minio-py:test_negative_put_object_with_path_segment",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-91ee4d1d-fc30-4350-8be6-318ef5e5d30f",
    "object_name": "/a/b/c/3ac2dbb2-dd92-4e82-8030-e4aebe70b9fa"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-91ee4d1d-fc30-4350-8be6-318ef5e5d30f, request_id: 166CCF7307C4A730, host_id: 9eac0346-8e1d-440a-b18d-9813100e34b6, bucket_name: minio-py-test-91ee4d1d-fc30-4350-8be6-318ef5e5d30f",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 744, in test_negative_put_object_with_path_segment\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-91ee4d1d-fc30-4350-8be6-318ef5e5d30f, request_id: 166CCF7307C4A730, host_id: 9eac0346-8e1d-440a-b18d-9813100e34b6, bucket_name: minio-py-test-91ee4d1d-fc30-4350-8be6-318ef5e5d30f\n",
  "duration": 39
}
(9/15) Running s3cmd tests ... done in 1 minutes and 10 seconds
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="a9b17c41-ac50-40d2-9361-c4f58b623b8b"></a>
### 11758-3c29f67/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30775
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c1b4ce18d33:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 6368,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-14821/prefix/directory/datafile-1-kBremove_bucket failed: s3://awscli-mint-test-bucket-14821 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 18 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... done in 2 minutes and 20 seconds
(9/15) Running minio-java tests ... FAILED in 1 minutes and 26 seconds
{
  "name": "minio-java",
  "function": "removeBucket()",
  "duration": 12,
  "status":  [...]

2021-03-16 12:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3b87df6d-c84b-4da2-9beb-4033aeb0bdd6) |
| mint-gateway-s3.sh | :x: [more...](#98ba26d8-b55d-4ace-a40b-51506d425bc6) |
| mint-erasure.sh | :x: [more...](#c922f046-959e-43f3-a8a5-d81724cbdb26) |
| mint-dist-erasure.sh | :x: [more...](#04291547-3d0d-454a-a5f2-708bb1493ca6) |
| mint-zoned.sh | :x: [more...](#a5f4e77f-e747-413f-8f88-9001879a5cb3) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#8b27b729-8c40-4836-b6e8-79fd97ca8da5) |
<a name="8b27b729-8c40-4836-b6e8-79fd97ca8da5"></a>
### 11758-fe4be30/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30572
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7cd22bab9161:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 6230,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-5818/prefix/directory/datafile-1-kBremove_bucket failed: s3://awscli-mint-test-bucket-5818 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 1 minutes and 16 seconds
(7/15) Running minio-dotnet tests ... done in 40 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 9 seconds
{
  "args": {},
  "duration": 604,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 28 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 163,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3a9d80c, objectName = minio-java-test-h5dd1c-copy, resource = /minio-java-test-3a9d80c/minio-java-test-h5dd1c-copy, requestId = 166CD2FF31A0D6BD, hostId = df35add7-7342-4fad-8a38-d97e8433843f)\nrequest={method=PUT, url=http://minio-dev7.minio.io:30572/minio-java-test-3a9d80c/minio-java-test-h5dd1c-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2huauv1/minio-java-test-h5dd1c\nHost: minio-dev7.minio.io:30572\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210316T123919Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210316/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 16 Mar 2021 12:39:19 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166CD2FF31A0D6BD\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Mar 2021 12:39:19 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... FAILED in 18 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(8/15) Running minio-py tests ... FAILED in 18 seconds
{
  "name": "minio-py:test_negative_put_object_with_path_segment",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-6c2b1f71-f5a3-4d61-9f5d-c75442481a4f",
    "object_name": "/a/b/c/532359c1-1567-449f-9c93-18056922ba77"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-6c2b1f71-f5a3-4d61-9f5d-c75442481a4f, request_id: 166CD3078C8A9790, host_id: df35add7-7342-4fad-8a38-d97e8433843f, bucket_name: minio-py-test-6c2b1f71-f5a3-4d61-9f5d-c75442481a4f",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 744, in test_negative_put_object_with_path_segment\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-6c2b1f71-f5a3-4d61-9f5d-c75442481a4f, request_id: 166CD3078C8A9790, host_id: df35add7-7342-4fad-8a38-d97e8433843f, bucket_name: minio-py-test-6c2b1f71-f5a3-4d61-9f5d-c75442481a4f\n",
  "duration": 96
}
(8/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2692",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-4669/s3cmd-test-object-30674 baddfba2-f181- [...]

2021-03-16 15:56 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ed8c146d-f988-4449-a134-c446b7950d78) |
| mint-gateway-s3.sh | :x: [more...](#31378df3-3303-434d-921d-e414838cdf74) |
| mint-erasure.sh | :x: [more...](#55b819b5-4b43-4c19-a948-3412f94797ce) |
| mint-dist-erasure.sh | :x: [more...](#2c8994ee-b0aa-4b06-9831-60a50eefdda8) |
| mint-zoned.sh | :x: [more...](#d1292674-e3ee-47e8-9620-0b3b0fb7bb02) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#64a34ff6-1307-4c6f-9a10-fc59d020b271) |
<a name="64a34ff6-1307-4c6f-9a10-fc59d020b271"></a>
### 11758-9aedf28/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30127
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9f3a71e3c88b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 6328,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-9257/prefix/directory/datafile-1-kBremove_bucket failed: s3://awscli-mint-test-bucket-9257 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 1 minutes and 18 seconds
(7/15) Running minio-dotnet tests ... done in 43 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 35 seconds
{
  "args": {},
  "duration": 497,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 9 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 152,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2fvk897, objectName = minio-java-test-1d54gni-copy, resource = /minio-java-test-2fvk897/minio-java-test-1d54gni-copy, requestId = 166CDDA90CF11C46, hostId = d77ff2e7-ed26-480f-8d05-ddf7769c4ac6)\nrequest={method=PUT, url=http://minio-c3.minio.io:30127/minio-java-test-2fvk897/minio-java-test-1d54gni-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-k9trtm/minio-java-test-1d54gni\nHost: minio-c3.minio.io:30127\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210316T155444Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210316/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 16 Mar 2021 15:54:44 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166CDDA90CF11C46\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Mar 2021 15:54:44 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... FAILED in 21 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(8/15) Running minio-py tests ... FAILED in 20 seconds
{
  "name": "minio-py:test_negative_put_object_with_path_segment",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-664f42eb-7074-47f3-92d4-51a75a1cd929",
    "object_name": "/a/b/c/bd566bc9-a49e-4108-8f7f-35636863a63a"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-664f42eb-7074-47f3-92d4-51a75a1cd929, request_id: 166CDDB27E4B6A79, host_id: d77ff2e7-ed26-480f-8d05-ddf7769c4ac6, bucket_name: minio-py-test-664f42eb-7074-47f3-92d4-51a75a1cd929",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 744, in test_negative_put_object_with_path_segment\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-664f42eb-7074-47f3-92d4-51a75a1cd929, request_id: 166CDDB27E4B6A79, host_id: d77ff2e7-ed26-480f-8d05-ddf7769c4ac6, bucket_name: minio-py-test-664f42eb-7074-47f3-92d4-51a75a1cd929\n",
  "duration": 101
}
(8/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3244",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-6728/s3cmd-test-object-32279 36f6363d-4b4d-40 [...]

2021-03-18 12:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#604f6538-2440-4d3f-8f44-c612057db0fc) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#9e67991e-4f68-4233-b2fe-ad237246e600) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#65a1f00b-d2f5-48d9-a4e7-a58b6d599af7) |
| mint-zoned.sh | :heavy_exclamation_mark: [more...](#b5cb17cd-bed6-4cf0-a939-607bf8a2346b) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#0b9f72a7-cf95-4ca7-b555-283dad3d3237) |
<a name="65a1f00b-d2f5-48d9-a4e7-a58b6d599af7"></a>
### 11758-7a9d844/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="b5cb17cd-bed6-4cf0-a939-607bf8a2346b"></a>
### 11758-7a9d844/mint-zoned.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="9e67991e-4f68-4233-b2fe-ad237246e600"></a>
### 11758-7a9d844/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="604f6538-2440-4d3f-8f44-c612057db0fc"></a>
### 11758-7a9d844/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0b9f72a7-cf95-4ca7-b555-283dad3d3237"></a>
### 11758-7a9d844/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

2021-03-18 12:55 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#215e3a52-c9fa-41de-b0cf-4ce8acba0887) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#a9a6c039-28a9-44e0-a908-0835d507abc0) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#a9d763c4-1040-4a0a-b923-36c7d95aa6b1) |
| mint-zoned.sh | :heavy_exclamation_mark: [more...](#ec302be1-d89e-449e-bd5c-d058cc7734dd) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#6b09bf4a-6297-4b4d-a7de-924813f2790f) |
<a name="a9d763c4-1040-4a0a-b923-36c7d95aa6b1"></a>
### 11758-3a3ba87/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="ec302be1-d89e-449e-bd5c-d058cc7734dd"></a>
### 11758-3a3ba87/mint-zoned.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a9a6c039-28a9-44e0-a908-0835d507abc0"></a>
### 11758-3a3ba87/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="6b09bf4a-6297-4b4d-a7de-924813f2790f"></a>
### 11758-3a3ba87/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="215e3a52-c9fa-41de-b0cf-4ce8acba0887"></a>
### 11758-3a3ba87/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

2021-03-18 16:03 UTC, klauspost commented
@harshavardhana @aead @vadmeste Mint should work now, so please CR ASAP.

2021-03-18 16:16 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#f3a4ec93-900c-42c1-9e78-fc9ebcf31062) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#9e6f4365-e8ac-4668-b1ba-bbf98e83b4d1) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#a518798d-59ea-44f7-b9bf-8eb2392295a9) |
| mint-zoned.sh | :heavy_exclamation_mark: [more...](#68aa5ca9-a44b-4f6f-949a-84f2d835ca3e) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#8fb4a82b-c4f7-4e8c-b2ca-626e456682a6) |
<a name="68aa5ca9-a44b-4f6f-949a-84f2d835ca3e"></a>
### 11758-20ec6a5/mint-zoned.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a518798d-59ea-44f7-b9bf-8eb2392295a9"></a>
### 11758-20ec6a5/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="f3a4ec93-900c-42c1-9e78-fc9ebcf31062"></a>
### 11758-20ec6a5/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="9e6f4365-e8ac-4668-b1ba-bbf98e83b4d1"></a>
### 11758-20ec6a5/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="8fb4a82b-c4f7-4e8c-b2ca-626e456682a6"></a>
### 11758-20ec6a5/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

2021-03-19 09:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#8eeb3408-e9fe-4d02-a810-8a9f49cb715a) |
<a name="8eeb3408-e9fe-4d02-a810-8a9f49cb715a"></a>
### 11758-691b12b/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30126
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ae3b5d372b51:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2624,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30126 s3api copy-object --bucket awscli-mint-test-bucket-17263 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-17263/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 44 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 11 seconds
{
  "args": {},
  "duration": 538,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 40 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 350,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2rjih1d, objectName = minio-java-test-12k0sbq-copy, resource = /minio-java-test-2rjih1d/minio-java-test-12k0sbq-copy, requestId = 166DB5B7EE68988A, hostId = 764208e5-06b4-4254-ba24-cbe22c12ddd9)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30126/minio-java-test-2rjih1d/minio-java-test-12k0sbq-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-7ve3bd/minio-java-test-12k0sbq\nHost: minio-dev6.minio.io:30126\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210319T095402Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210319/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 19 Mar 2021 09:54:02 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166DB5B7EE68988A\nX-Xss-Protection: 1; mode=block\nDate: Fri, 19 Mar 2021 09:54:02 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 51 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 35 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3155",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-15403/s3cmd-test-object-8290 60b0a2a0-242c-46f9-861b-f91e05cd2fba\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 60b0a2a0-242c-46f9-861b-f91e05cd2fba put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-23 15:46 UTC, klauspost commented
@vadmeste @aead @vadmeste PTAL.

2021-03-23 16:07 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#8ffda5f3-bf2c-40f5-b4c6-8c271df8fad7) |
<a name="8ffda5f3-bf2c-40f5-b4c6-8c271df8fad7"></a>
### 11758-5d02ae1/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31911
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e914bc343a26:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2636,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31911 s3api copy-object --bucket awscli-mint-test-bucket-22350 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-22350/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 44 seconds
(7/15) Running minio-dotnet tests ... done in 43 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 15 seconds
{
  "args": {},
  "duration": 605,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 46 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 415,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-1290hu3, objectName = minio-java-test-oihs3m-copy, resource = /minio-java-test-1290hu3/minio-java-test-oihs3m-copy, requestId = 166F041764368B7E, hostId = 952b1498-cde5-4add-b192-48e2cfca0b1b)\nrequest={method=PUT, url=http://minio-c3.minio.io:31911/minio-java-test-1290hu3/minio-java-test-oihs3m-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-ggj631/minio-java-test-oihs3m\nHost: minio-c3.minio.io:31911\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210323T160129Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210323/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 23 Mar 2021 16:01:29 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166F041764368B7E\nX-Xss-Protection: 1; mode=block\nDate: Tue, 23 Mar 2021 16:01:29 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 51 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 27 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3406",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-5048/s3cmd-test-object-29985 d72ca5f5-5040-4034-953f-80f4f655649f\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id d72ca5f5-5040-4034-953f-80f4f655649f put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-25 20:20 UTC, harshavardhana requested changes
The implementation itself looks good, will be doing some tests on our hardware.

2021-03-25 20:20 UTC, harshavardhana commented on cmd/xl-storage.go
> +	logger.LogIf(ctx, s.deleteFile(volumeDir, filePath, false))
do we need this? @klauspost

2021-03-26 08:10 UTC, klauspost commented on cmd/xl-storage.go
> +	logger.LogIf(ctx, s.deleteFile(volumeDir, filePath, false))
Good point. Removing it.

2021-03-26 08:34 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#cc85f3b7-d9b9-4cf6-8cc4-4eee108d7f98) |
<a name="cc85f3b7-d9b9-4cf6-8cc4-4eee108d7f98"></a>
### 11758-9ee5835/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32303
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b923d614e58d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2643,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32303 s3api copy-object --bucket awscli-mint-test-bucket-31783 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-31783/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 43 seconds
(7/15) Running minio-dotnet tests ... done in 44 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 19 seconds
{
  "args": {},
  "duration": 490,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 35 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 195,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-25fi9qb, objectName = minio-java-test-3gu0klk-copy, resource = /minio-java-test-25fi9qb/minio-java-test-3gu0klk-copy, requestId = 166FD728EBEEAA34, hostId = 6b30d888-1b95-4c0a-aab6-257b84b83af1)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32303/minio-java-test-25fi9qb/minio-java-test-3gu0klk-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-1smsqat/minio-java-test-3gu0klk\nHost: minio-dev7.minio.io:32303\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210326T082922Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210326/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 26 Mar 2021 08:29:21 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166FD728EBEEAA34\nX-Xss-Protection: 1; mode=block\nDate: Fri, 26 Mar 2021 08:29:22 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 48 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 32 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2822",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-30648/s3cmd-test-object-29636 37ee39ad-85e8-458b-9404-ef258c0c365f\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 37ee39ad-85e8-458b-9404-ef258c0c365f put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-29 10:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#ed1c2ab9-1815-492b-bb5e-47e23e1ad0bc) |
<a name="ed1c2ab9-1815-492b-bb5e-47e23e1ad0bc"></a>
### 11758-d244a62/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32017
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 437166b38402:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2648,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:32017 s3api copy-object --bucket awscli-mint-test-bucket-31910 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-31910/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 36 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 24 seconds
{
  "args": {},
  "duration": 546,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 35 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 584,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-8acm1c, objectName = minio-java-test-1flhg6q-copy, resource = /minio-java-test-8acm1c/minio-java-test-1flhg6q-copy, requestId = 1670C7B98B8CE8E8, hostId = d72d36c9-ef98-4468-a3e0-4a2ac8f48837)\nrequest={method=PUT, url=http://minio-dev4.minio.io:32017/minio-java-test-8acm1c/minio-java-test-1flhg6q-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2uf7jtf/minio-java-test-1flhg6q\nHost: minio-dev4.minio.io:32017\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210329T095745Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210329/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Mon, 29 Mar 2021 09:57:45 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1670C7B98B8CE8E8\nX-Xss-Protection: 1; mode=block\nDate: Mon, 29 Mar 2021 09:57:45 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 53 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 27 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "2927",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-6045/s3cmd-test-object-4181 2d1bc30f-6ac0-4b97-8c9c-e4d6f7b6cd32\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 2d1bc30f-6ac0-4b97-8c9c-e4d6f7b6cd32 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-29 18:32 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#621bf617-e1c6-4874-9506-06f0c9e30d7e) |
<a name="621bf617-e1c6-4874-9506-06f0c9e30d7e"></a>
### 11758-2ec8265/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31534
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1610162792da:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2821,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31534 s3api copy-object --bucket awscli-mint-test-bucket-7063 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-7063/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 41 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 38 seconds
{
  "args": {},
  "duration": 649,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 29 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 298,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-1dek6k5, objectName = minio-java-test-32jlusg-copy, resource = /minio-java-test-1dek6k5/minio-java-test-32jlusg-copy, requestId = 1670E38F85ACF41F, hostId = b3e6a9ce-c96a-4165-8beb-ac44c242df9d)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31534/minio-java-test-1dek6k5/minio-java-test-32jlusg-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-63g2b3/minio-java-test-32jlusg\nHost: minio-dev6.minio.io:31534\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210329T182751Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210329/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Mon, 29 Mar 2021 18:27:51 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1670E38F85ACF41F\nX-Xss-Protection: 1; mode=block\nDate: Mon, 29 Mar 2021 18:27:51 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 49 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 32 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3110",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-394/s3cmd-test-object-23780 cdf93f6c-dfaf-47df-8615-cf051b42b811\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id cdf93f6c-dfaf-47df-8615-cf051b42b811 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-29 20:55 UTC, harshavardhana approved these changes

2021-03-29 22:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#d2e4d958-89df-41f3-b672-a18887bb1337) |
<a name="d2e4d958-89df-41f3-b672-a18887bb1337"></a>
### 11758-71589fe/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32469
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 51d3712c5f46:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2700,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32469 s3api copy-object --bucket awscli-mint-test-bucket-28453 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-28453/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 6 seconds
{
  "args": {},
  "duration": 359,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 30 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 154,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-1saab86, objectName = minio-java-test-18ok6g-copy, resource = /minio-java-test-1saab86/minio-java-test-18ok6g-copy, requestId = 1670F1B647EFE98A, hostId = 76c95870-bc81-4134-882f-cbbe4568c5e9)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32469/minio-java-test-1saab86/minio-java-test-18ok6g-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-27rnkv7/minio-java-test-18ok6g\nHost: minio-dev6.minio.io:32469\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210329T224711Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210329/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Mon, 29 Mar 2021 22:47:11 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1670F1B647EFE98A\nX-Xss-Protection: 1; mode=block\nDate: Mon, 29 Mar 2021 22:47:11 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 50 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 32 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3129",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-2/s3cmd-test-object-19903 6cdad7dc-37a2-4569-8ea8-40af111d3a33\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 6cdad7dc-37a2-4569-8ea8-40af111d3a33 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-29 23:09 UTC, kannappanr approved these changes
LGTM

2021-03-30 00:00 UTC, merged

2023-05-06 09:25 UTC, chenshi5012 commented
@harshavardhana harshavardhan 
@vadmeste @aead @vadmeste 

Have you considered data compatibility issues in rollback scenarios？  

is there any tools cloud splite meta file  and  part file ?

2023-05-08 09:55 UTC, klauspost commented
Instead of pinging everyone and the grandmother, you can ask questions in [discussions qa](https://github.com/minio/minio/discussions/categories/q-a).

A) MinIO does not support rollback B) [xl-meta tool](https://github.com/minio/minio/blob/master/docs/debugging/xl-meta/main.go) can decode xl.meta files to JSON and export inline data.