make KMS master keys first-class citizens at MinIO
minio/minio pull request #11787
Opened 2021-03-15 12:29 UTC by aead

## Description
This commit makes the KMS master key (specified as
env. variable) a first-class citizen. Now, master keys
are no longer used just for testing but can also be used
for production workloads.

This commit expects that the KMS master key is provided as
base64-encoded value - no longer as hex:
```
export MINIO_KMS_MASTER_KEY=<key-name>:<base64-value>
```

Further, the `MINIO_KMS_MASTER_KEY` now generates data encryption
keys exactly like KES. Therefore, it is now possible to import
a `MINIO_KMS_MASTER_KEY` into KES and switch to KES server.

Now, a user can start with a `MINIO_KMS_MASTER_KEY` and switch to
KES at any point in time. This makes it easier for users to start
with an encrypted setup and is the next step for auto-encryption by
default.

## Motivation and Context
KMS, auto-encryption

## How to test this PR?
Start with:
```
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_KMS_MASTER_KEY=my-key123:/NOfnXyb9Qcx1slCYULcHfxeD60pMF1lfM/E3DFpYvo=
export MINIO_KMS_AUTO_ENCRYPTION=on
minio server /tmp/1

mc mb <alias>/bucket
mc cp <file> <alias>/bucket/object
```
Then stop the server and set:
```
export KES_SERVER=https://play.min.io:7373 KES_CLIENT_CERT=root.cert KES_CLIENT_KEY=root.key
kes key create my-key123 "/NOfnXyb9Qcx1slCYULcHfxeD60pMF1lfM/E3DFpYvo="

unset MINIO_KMS_MASTER_KEY
export MINIO_KMS_KES_ENDPOINT=https://play.min.io:7373
export MINIO_KMS_KES_KEY_FILE=root.key
export MINIO_KMS_KES_CERT_FILE=root.cert
export MINIO_KMS_KES_KEY_NAME=my-key123
minio server /tmp/1

mc cat <alias>/bucket/object
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-03-15 12:48 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#fc01c89f-eac3-4b13-bca3-4108c1c5d4cc) |
| mint-fs.sh | :x: [more...](#ed7c4bee-be8a-4f35-a784-8e5d57341bfd) |
| mint-erasure.sh | :x: [more...](#5ab4e9c4-2b09-4e86-87a3-6be897f46f62) |
| mint-dist-erasure.sh | :x: [more...](#f3d77872-af1f-4f04-93fe-6adf80e770a9) |
| mint-zoned.sh | :x: [more...](#a86a4336-8b09-4d9b-af2e-eaf428a4c118) |
| mint-gateway-nas.sh | :x: [more...](#cd17777d-7d6f-4e34-84e5-fd5652a38140) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#17c18f3e-7cbc-44e3-a87c-0e2ef721fb34) |
<a name="a86a4336-8b09-4d9b-af2e-eaf428a4c118"></a>
### 11787-b52653a/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31299
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7ae036fc6e61:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 11 seconds
(8/15) Running minio-dotnet tests ... done in 48 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 23 seconds
{
  "args": {
    "bucketName": "minio-go-test-9uvipkxa6gvorodi",
    "objectName": "anzvnoh3nk15apdy1bsqhkbia9n31p",
    "sse": {}
  },
  "duration": 86,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 5 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 238,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-17nir4m, objectName = null, resource = /minio-java-test-17nir4m, requestId = 166C849C7A28DCAF, hostId = 59f99ab5-b39f-4d3e-91de-13ac66ab6456)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31299/minio-java-test-17nir4m?encryption=, headers=Host: minio-dev6.minio.io:31299\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210315T124253Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210315/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166C849C7A28DCAF\nX-Xss-Protection: 1; mode=block\nDate: Mon, 15 Mar 2021 12:42:53 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 53 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 28 seconds
(11/15) Running s3cmd tests ... done in 18 seconds
(12/15) Running s3select tests ... done in 6 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="f3d77872-af1f-4f04-93fe-6adf80e770a9"></a>
### 11787-b52653a/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30921
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4fc326f6e7fb:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 9 seconds
(8/15) Running minio-dotnet tests ... done in 50 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 18 seconds
{
  "args": {
    "bucketName": "minio-go-test-9kurebddlsl01hye",
    "objectName": "jo546tt4wtzkmqpme9wbyev6lfra3q",
    "sse": {}
  },
  "duration": 170,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 4 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 123,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-31qgmcg, objectName = null, resource = /minio-java-test-31qgmcg, requestId = 166C849B09BC4470, hostId = 456d5004-b8d6-43e7-9b8d-fdc982c86829)\nrequest={method=PUT, url=http://minio-c3.minio.io:30921/minio-java-test-31qgmcg?encryption=, headers=Host: minio-c3.minio.io:30921\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210315T124247Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210315/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166C849B09BC4470\nX-Xss-Protection: 1; mode=block\nDate: Mon, 15 Mar 2021 12:42:47 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 50 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 19 seconds
(11/15) Running s3cmd tests ... done in 18 seconds
(12/15) Running s3select tests ... done in 7 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="cd17777d-7d6f-4e34-84e5-fd5652a38140"></a>
### 11787-b52653a/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32459
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7276278c341c:/mint/log /tmp/mint-logs'

(1/15) Run [...]

2021-03-15 13:42 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c772948b-4839-4205-bfca-365bde42c02d) |
| mint-fs.sh | :x: [more...](#ae1dfb38-0c1d-4b60-a342-976a9ef440d5) |
| mint-erasure.sh | :x: [more...](#1233781c-b8a3-41b4-92de-a252ce50159e) |
| mint-dist-erasure.sh | :x: [more...](#dcafd26d-8186-4771-a073-8a7385440dbe) |
| mint-zoned.sh | :x: [more...](#737df835-72d8-4991-81b4-c23cf1af6047) |
| mint-gateway-nas.sh | :x: [more...](#32a6541d-2250-4729-af9b-43e202aacbf1) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#da429024-8f93-4b34-a422-10cc4a877a37) |
<a name="737df835-72d8-4991-81b4-c23cf1af6047"></a>
### 11787-9fc1fde/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32709
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d9a27a24435c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 26 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 54 seconds
(8/15) Running minio-dotnet tests ... done in 44 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 34 seconds
{
  "args": {
    "bucketName": "minio-go-test-ebo40vyjcdk43jjd",
    "objectName": "msflkz04u9jyvm1n4yurlcukk55yu2",
    "sse": {}
  },
  "duration": 137,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 5 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 123,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-288kiqb, objectName = null, resource = /minio-java-test-288kiqb, requestId = 166C878C8EE97CB4, hostId = 44f27124-ae6d-45ad-8253-7219f37e5485)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32709/minio-java-test-288kiqb?encryption=, headers=Host: minio-dev6.minio.io:32709\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210315T133644Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210315/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166C878C8EE97CB4\nX-Xss-Protection: 1; mode=block\nDate: Mon, 15 Mar 2021 13:36:44 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 50 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 16 seconds
(11/15) Running s3cmd tests ... done in 20 seconds
(12/15) Running s3select tests ... done in 8 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="da429024-8f93-4b34-a422-10cc4a877a37"></a>
### 11787-9fc1fde/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30819
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f77d42e7a02:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2708,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:30819 s3api copy-object --bucket awscli-mint-test-bucket-10869 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-10869/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 54 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 39 seconds
{
  "args": {
    "bucketName": "minio-go-test-tcd3o5zv2siz90z1",
    "objectName": "9oi6nroswk4jor5s9bzysw5zmlickj",
    "sse": {}
  },
  "duration": 798,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 6 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 254,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-bnllsc, objectName = null, resource = /minio-java-test-bnllsc, requestId = 166C8782700037FD, hostId = 89857985-b27a-4f9f-821b-3ecf79d17753)\nrequest={method=PUT, url=http://minio-dev7.minio.io:30819/minio-java-test-bnllsc?encryption=, headers=Host: minio-dev7.minio.io:30819\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210315T133600Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210315/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 342\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166C8782700037FD\nX-Xss-Protection: 1; mode=block\nDate: Mon, 15 Mar 2021 13:36:00 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 57 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 32 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "2974",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't matc [...]

2021-03-16 11:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#77aa60f1-8276-46a0-bf53-c2be25a7095f) |
| mint-fs.sh | :x: [more...](#09d5ce58-d188-4a7f-86b0-fd170f2a28f7) |
| mint-erasure.sh | :x: [more...](#0a9ea13e-e490-446d-9a0f-ed78fee67391) |
| mint-dist-erasure.sh | :x: [more...](#368c404d-9b7d-4ca9-8a9d-402c8eee220b) |
| mint-zoned.sh | :x: [more...](#9bffcd7e-6240-47b9-80af-3515df05aa17) |
| mint-gateway-nas.sh | :x: [more...](#f81c975a-d891-4c78-8fec-f5892585dabf) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#17056ce9-f8ff-4f8f-aa1c-d82e1ef24bd4) |
<a name="9bffcd7e-6240-47b9-80af-3515df05aa17"></a>
### 11787-196e1cb/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31744
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c310e5f3557c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 23 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 1 seconds
(8/15) Running minio-dotnet tests ... done in 55 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 34 seconds
{
  "args": {
    "bucketName": "minio-go-test-svo2gqkrqhj5c046",
    "objectName": "lnbvinhxyse3qxd4chyc4jfvvgl5oh",
    "sse": {}
  },
  "duration": 88,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 4 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 131,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-2lm9a1g, objectName = null, resource = /minio-java-test-2lm9a1g, requestId = 166CCE88AFBBA19F, hostId = b48a2ea1-1a54-4d36-bbfe-b6d271a9c065)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31744/minio-java-test-2lm9a1g?encryption=, headers=Host: minio-dev6.minio.io:31744\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210316T111732Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210316/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166CCE88AFBBA19F\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Mar 2021 11:17:32 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 53 seconds
(10/15) Running minio-py tests ... FAILED in 3 minutes and 40 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-dfa859a5-1d36-4f1a-a012-763c8a0428eb",
    "object_name": "e202d870-fe00-4e54-99d9-e256fdd23519"
  },
  "message": "(\"Connection broken: ConnectionResetError(104, 'Connection reset by peer')\", ConnectionResetError(104, 'Connection reset by peer'))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/response.py\", line 438, in _error_catcher\n    yield\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/response.py\", line 519, in read\n    data = self._fp.read(amt) if not fp_closed else b\"\"\n  File \"/usr/lib/python3.6/http/client.py\", line 463, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.6/http/client.py\", line 507, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1637, in test_thread_safe\n    raise exceptions[0]\n  File \"/mint/run/core/minio-py/tests.py\", line 1597, in get_object_and_check\n    _CLIENT.fget_object(bucket_name, object_name, local_file)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 1085, in fget_object\n    for data in response.stream(amt=1024*1024):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/response.py\", line 576, in stream\n    data = self.read(amt=amt, decode_content=decode_content)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/response.py\", line 541, in read\n    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)\n  File \"/usr/lib/python3.6/contextlib.py\", line 99, in __exit__\n    self.gen.throw(type, value, traceback)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/response.py\", line 455, in _error_catcher\n    raise ProtocolError(\"Connection broken: %r\" % e, e)\nurllib3.exceptions.ProtocolError: (\"Connection broken: ConnectionResetError(104, 'Connection reset by peer')\", ConnectionResetError(104, 'Connection reset by peer'))\n",
  "duration": 6775
}
(10/15) Running s3cmd tests ... done in 19 seconds
(11/15) Running s3select tests ... done in 9 seconds
(12/15) Running security tests ... done in 0 seconds

Executed 12 out of 15 tests successfully.
```
<a name="0a9ea13e-e490-446d-9a0f-ed78fee67391"></a>
### 11787-196e1cb/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30759
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 29f91756a587:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 2 seconds
(8/15) Running minio-dotnet tests ... done in 40 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 29 seconds
{
  "args": {
    "bucketName": "minio-go-test-rljfdveu1x1iboas",
    "objectName": "lj4snnr20qg33wojy5vh3s2m1zhkxv",
    "sse": {}
  },
  "duration": 55,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duratio [...]

2021-03-16 11:57 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#591d4e65-ee3f-471a-a914-99443ffc1da1) |
| mint-fs.sh | :x: [more...](#7db0b4f7-ab71-41bd-a6f0-229d683e9589) |
| mint-erasure.sh | :x: [more...](#566ae2f9-f884-4817-8bb0-dc8a7065f9f0) |
| mint-dist-erasure.sh | :x: [more...](#d92fb961-1f65-4785-88c6-e2dc2921f185) |
| mint-zoned.sh | :x: [more...](#4ac3e2c8-a146-422b-b712-72030a92a0ee) |
| mint-gateway-nas.sh | :x: [more...](#3f5d1624-431e-4b07-a603-71a8f89d3421) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#cf5ffcb6-40ce-4540-b2dd-37b99f48658d) |
<a name="7db0b4f7-ab71-41bd-a6f0-229d683e9589"></a>
### 11787-847851e/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31262
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a8485c8df97:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 29 seconds
(8/15) Running minio-dotnet tests ... done in 31 seconds
(9/15) Running minio-go tests ... FAILED in 42 seconds
{
  "args": {
    "bucketName": "minio-go-test-ks9pg0mmtedru1qd",
    "objectName": "p1wfnceofgdzdb0tyzv1i1ug6rlkjh",
    "sse": {}
  },
  "duration": 21,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 34,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-1ngscok, objectName = null, resource = /minio-java-test-1ngscok, requestId = 166CD03B510C086B, hostId = cace6cd4-e6c7-48b0-8b43-a3fec3eba4f6)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31262/minio-java-test-1ngscok?encryption=, headers=Host: minio-dev7.minio.io:31262\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210316T114839Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210316/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166CD03B510C086B\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Mar 2021 11:48:39 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 53 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 6 seconds
(11/15) Running s3cmd tests ... done in 17 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="4ac3e2c8-a146-422b-b712-72030a92a0ee"></a>
### 11787-847851e/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30562
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f2b484f985ea:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 52 seconds
(8/15) Running minio-dotnet tests ... done in 49 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 21 seconds
{
  "args": {
    "bucketName": "minio-go-test-lefqe9kyv3659dl4",
    "objectName": "w0g3jzf1vufvueoct4lecty1jx2zi9",
    "sse": {}
  },
  "duration": 124,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 5 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 193,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-3u433pc, objectName = null, resource = /minio-java-test-3u433pc, requestId = 166CD05F2E1CE306, hostId = 56f6bccd-832a-4f08-b7d4-09a0e9ebf375)\nrequest={method=PUT, url=http://minio-dev8.minio.io:30562/minio-java-test-3u433pc?encryption=, headers=Host: minio-dev8.minio.io:30562\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210316T115113Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210316/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166CD05F2E1CE306\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Mar 2021 11:51:13 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(9/15) Running minio-js tests ... done in 49 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 13 seconds
(11/15) Running s3cmd tests ... done in 23 seconds
(12/15) Running s3select tests ... done in 6 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="d92fb961-1f65-4785-88c6-e2dc2921f185"></a>
### 11787-847851e/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31230
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2e23c152e9de:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/ [...]

2021-03-16 15:45 UTC, harshavardhana requested changes
@aead this PR is breaking things 

- removal of SSE_FILE is okay but we should perhaps throw an error if specified?
- if BASE64 is supported how to handle existing deployments? as far I have seen users
  have used it the way it is done today.

2021-03-16 16:08 UTC, aead commented
@harshavardhana Yes, this PR fundamentally changes the semantics of master keys.

However, this is acceptable since `MINIO_KMS_MASTER_KEY` has never been supported for anything else then testing - i.e. to simplify KMS setups.

It is not expected to be backwards compatible. In particular,  master keys are not documented for over a year now and never haven been documented as anything else then "for testing purposes only". Users, who are using master keys, should use e.g. `mc mirror`
to copy their data.

2021-03-22 10:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#87683164-b139-4753-b836-71af44835bb8) |
| mint-fs.sh | :x: [more...](#76e0655c-ae25-4109-aa23-b21fc49d1c72) |
| mint-erasure.sh | :x: [more...](#89c76b40-2533-4a7e-b1a3-44e1f7cc2291) |
| mint-dist-erasure.sh | :x: [more...](#6639a3ac-c429-449e-ad66-3c2169c49350) |
| mint-zoned.sh | :x: [more...](#7c72a74a-ed54-4185-be0a-0d04848b9d12) |
| mint-gateway-nas.sh | :x: [more...](#4fdd857c-4b72-4c2b-85d6-438df661b28e) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#106c4437-9d42-4564-a194-278b928cd5b9) |
<a name="106c4437-9d42-4564-a194-278b928cd5b9"></a>
### 11787-c14bc59/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30402
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f204312b42bc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2525,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30402 s3api copy-object --bucket awscli-mint-test-bucket-19765 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-19765/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 52 seconds
(7/15) Running minio-dotnet tests ... done in 41 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 45 seconds
{
  "args": {
    "bucketName": "minio-go-test-uek6djoxa5gg31ic",
    "objectName": "fi666kcn1bkfymimuczismkw6vlh5n",
    "sse": {}
  },
  "duration": 225,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 5 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 153,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-3e2qkl6, objectName = null, resource = /minio-java-test-3e2qkl6, requestId = 166EA2AC5CA13A8E, hostId = 4d246858-6f9c-485f-937c-76f9f5d0c141)\nrequest={method=PUT, url=http://minio-c3.minio.io:30402/minio-java-test-3e2qkl6?encryption=, headers=Host: minio-c3.minio.io:30402\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210322T101617Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210322/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166EA2AC5CA13A8E\nX-Xss-Protection: 1; mode=block\nDate: Mon, 22 Mar 2021 10:16:17 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.setBucketEncryption(MinioClient.java:3507), FunctionalTest.setBucketEncryption(FunctionalTest.java:3261), FunctionalTest.runBucketTests(FunctionalTest.java:3719), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 56 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 40 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "2949",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-10612/s3cmd-test-object-7882 b7a499fc-4fd2-4289-bdf2-d7191fac2c7c\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id b7a499fc-4fd2-4289-bdf2-d7191fac2c7c put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 9 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="76e0655c-ae25-4109-aa23-b21fc49d1c72"></a>
### 11787-c14bc59/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30989
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c65d2663c76f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 1 minutes and 59 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 34 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 49 seconds
{
  "args": {
    "bucketName": "minio-go-test-c5srs1m9ci6qfpdp",
    "objectName": "gjvqh5hpcrom9we6f51vznobjwxpsv",
    "sse": {}
  },
  "duration": 14,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 33,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-3osln70, objectName = null, resource = /minio-java-test-3osln70, requestId = 166EA2AB61219835, hostId = 1d3ca89c-d8db-4fba-8885-ab144ebf985d)\nrequest={method=PUT, url=http://minio-c2.minio.io:30989/minio-java-test-3osln70?encryption=, headers=Host: minio-c2.minio.io:30989\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20210322T101613Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210322/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-con [...]

2021-04-23 08:32 UTC, aead commented
Closing this as already implemented by KMS IAM encryption #12041

2021-04-23 08:32 UTC, closed without merging