trace: Add storage tracing
minio/minio pull request #11889
Opened 2021-03-24 21:34 UTC by vadmeste

## Description
This PR adds storage tracing and threshold capability to tracing

## Motivation and Context
Enhance tracing experience

## How to test this PR?
mc admin trace 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-03-24 21:54 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f1218492-0e8c-4029-9a7f-766b2690f3ed) |
| mint-erasure.sh | :x: [more...](#1eb42e23-39c7-4c21-ae74-82b136c3de11) |
| mint-dist-erasure.sh | :x: [more...](#33e0cd1e-2497-48e5-96c4-4d3ecab1e88f) |
| mint-zoned.sh | :x: [more...](#b0fd15bb-a379-4bac-b999-e58df56033f9) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#51284677-ebc5-4c6c-b23b-a9be71f96362) |
<a name="33e0cd1e-2497-48e5-96c4-4d3ecab1e88f"></a>
### 11889-24238ab/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32695
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 33b141d8561b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-php",
  "function": "anonDeleteObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-605bb208704e4",
    "Object": "obj1"
  },
  "duration": "258",
  "status": "FAIL",
  "error": "Incorrect response deleteObjects anonymous\n                                call for aws-sdk-php-605bb208704e4"
}
(3/15) Running aws-sdk-ruby tests ... done in 5 seconds
(4/15) Running awscli tests ... done in 2 minutes and 7 seconds
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... FAILED in 4 seconds
{
  "name": "mc",
  "duration": "1200",
  "function": "test_put_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-22419 --quiet --no-color rm myminio/mc-test-bucket-28119/mc-test-object-23251  >>> \nRemoving `myminio/mc-test-bucket-28119/mc-test-object-23251`.\nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-28119/mc-test-object-23251`. Please reduce your request"
}
(6/15) Running minio-dotnet tests ... done in 54 seconds
(7/15) Running minio-go tests ... FAILED in 45 seconds
{
  "args": {
    "bucketName": "minio-go-test-dgf52bawf9pjt5u4"
  },
  "duration": 8638,
  "error": "Please reduce your request",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}
(7/15) Running minio-java tests ... FAILED in 15 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 480,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-32tl93l, objectName = null, resource = /minio-java-test-32tl93l, requestId = 166F6573F7698CC8, hostId = aa473141-5701-48fa-b424-ba8ecaa9f6e4)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:32695/minio-java-test-32tl93l, headers=Host: minio-dev6.minio.io:32695\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210324T214539Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210324/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 328\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166F6573F7698CC8\nX-Xss-Protection: 1; mode=block\nDate: Wed, 24 Mar 2021 21:45:39 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executeDelete(MinioClient.java:879), io.minio.MinioClient.removeBucket(MinioClient.java:2669), FunctionalTest.testListObjects(FunctionalTest.java:1416), FunctionalTest.listObjects(FunctionalTest.java:1428), FunctionalTest.runObjectTests(FunctionalTest.java:3747), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(7/15) Running minio-js tests ... FAILED in 56 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 12,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(7/15) Running minio-py tests ... FAILED in 4 minutes and 30 seconds
{
  "name": "minio-py:test_remove_objects",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-21431184-f503-4336-98c4-b8db1823f339",
    "delete_object_list": [
      "prefix-0",
      "prefix-1",
      "prefix-2",
      "prefix-3",
      "prefix-4",
      "prefix-5",
      "prefix-6",
      "prefix-7",
      "prefix-8",
      "prefix-9"
    ]
  },
  "message": "Remove objects err: <minio.deleteobjects.DeleteError object at 0x7f22438b99b0>",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1847, in _test_remove_objects\n    raise ValueError(\"Remove objects err: {}\".format(err))\nValueError: Remove objects err: <minio.deleteobjects.DeleteError object at 0x7f22438b92e8>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1858, in test_remove_objects\n    _test_remove_objects(log_entry)\n  File \"/mint/run/core/minio-py/tests.py\", line 1852, in _test_remove_objects\n    raise ValueError(\"Remove objects err: {}\".format(err))\nValueError: Remove objects err: <minio.deleteobjects.DeleteError object at 0x7f22438b99b0>\n",
  "duration": 768
}
(7/15) Running s3cmd tests ... FAILED in 21 seconds
{
  "name": "s3cmd",
  "duration": "9157",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "WARNING: Bucket is not empty. Removing all the objects from it first. This may take some time...\ndelete: 's3://s3cmd-test-bucket-21523/datafile-0-b'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-1-MB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-1-b'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-1-kB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-1.03-MB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-10-MB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-10-kB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-100-kB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-11-MB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-129-MB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-33-kB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-5-MB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-5243880-b'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-6-MB'\ndelete: 's3://s3cmd-test-bucket-21523/datafile-65-MB'\nERROR: S3 error: 409 (BucketNotEmpty): The bucket you tried to delete i [...]

2021-03-25 16:51 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3c25ac30-2141-4d9b-8ffc-dc7a9b0df16e) |
| mint-dist-erasure.sh | :x: [more...](#bbd719e0-bf19-4dab-9524-6214d663a4c3) |
| mint-zoned.sh | :x: [more...](#01ce1364-1b03-4dd9-b25c-bfb7f8f1bae2) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#01f64080-bd63-4afe-950c-e07b9860cf5d) |
<a name="01f64080-bd63-4afe-950c-e07b9860cf5d"></a>
### 11889-5390696/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32280
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4f91ecdf1f25:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 2 seconds
{
  "name": "aws-sdk-php",
  "function": "anonDeleteObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-605cbce04228e",
    "Object": "obj1"
  },
  "duration": "194",
  "status": "FAIL",
  "error": "Incorrect response deleteObjects anonymous\n                                call for aws-sdk-php-605cbce04228e"
}
(3/15) Running aws-sdk-ruby tests ... done in 5 seconds
(4/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2571,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32280 s3api copy-object --bucket awscli-mint-test-bucket-16289 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-16289/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(4/15) Running healthcheck tests ... done in 0 seconds
(5/15) Running mc tests ... FAILED in 2 seconds
{
  "name": "mc",
  "duration": "488",
  "function": "test_put_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-26876 --quiet --no-color rm myminio/mc-test-bucket-12622/mc-test-object-6750  >>> \nRemoving `myminio/mc-test-bucket-12622/mc-test-object-6750`.\nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-12622/mc-test-object-6750`. Please reduce your request"
}
(5/15) Running minio-dotnet tests ... done in 40 seconds
(6/15) Running minio-go tests ... FAILED in 32 seconds
{
  "args": {
    "bucketName": "minio-go-test-pq4kx0kcvr9jecbn"
  },
  "duration": 9979,
  "error": "Please reduce your request",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}
(6/15) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 1303,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-3he5j1a, objectName = null, resource = /minio-java-test-3he5j1a, requestId = 166FA37761D01241, hostId = 46132d86-012d-4348-8094-f31a6ad01785)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:32280/minio-java-test-3he5j1a, headers=Host: minio-dev7.minio.io:32280\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210325T164204Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210325/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 328\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166FA37761D01241\nX-Xss-Protection: 1; mode=block\nDate: Thu, 25 Mar 2021 16:42:04 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executeDelete(MinioClient.java:879), io.minio.MinioClient.removeBucket(MinioClient.java:2669), FunctionalTest.testListObjects(FunctionalTest.java:1416), FunctionalTest.listObjects(FunctionalTest.java:1428), FunctionalTest.runObjectTests(FunctionalTest.java:3747), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(6/15) Running minio-js tests ... FAILED in 50 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 9,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(6/15) Running minio-py tests ... FAILED in 4 minutes and 21 seconds
{
  "name": "minio-py:test_remove_objects",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-27fc7836-58ba-4468-a63b-f3d858c055f3",
    "delete_object_list": [
      "prefix-0",
      "prefix-1",
      "prefix-2",
      "prefix-3",
      "prefix-4",
      "prefix-5",
      "prefix-6",
      "prefix-7",
      "prefix-8",
      "prefix-9"
    ]
  },
  "message": "Remove objects err: <minio.deleteobjects.DeleteError object at 0x7f3a3c219cc0>",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1847, in _test_remove_objects\n    raise ValueError(\"Remove objects err: {}\".format(err))\nValueError: Remove objects err: <minio.deleteobjects.DeleteError object at 0x7f3a3c219860>\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1858, in test_remove_objects\n    _test_remove_objects(log_entry)\n  File \"/mint/run/core/minio-py/tests.py\", line 1852, in _test_remove_objects\n    raise ValueError(\"Remove objects err: {}\".format(err))\nValueError: Remove objects err: <minio.deleteobjects.DeleteError object at 0x7f3a3c219cc0>\n",
  "duration": 834
}
(6/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2940",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3 [...]

2021-03-25 17:25 UTC, harshavardhana requested changes

2021-03-25 17:25 UTC, harshavardhana commented on cmd/admin-handlers.go
> +func mustTrace(entry interface{}, trcS3, trcInternal, trcStorage, errOnly bool, threshold time.Duration) (shouldTrace bool) {
```suggestion
func mustTrace(entry interface{}, trcS3, trcInternal, trcStorage, errOnly bool, threshold time.Duration) (shouldTrace bool) {
```

Take a data structure now such as TraceOptions{} @vadmeste

2021-03-25 17:25 UTC, harshavardhana commented on cmd/admin-handlers.go
> +
write it in a function return TraceOptions data structure write ParseTraceOptions(r.Query())

2021-03-25 17:25 UTC, harshavardhana commented on pkg/trace/trace.go
> +type POSIXStats struct {
StorageStats() or DiskCallStats instead of POSIX since backend is not always POSIX

2021-03-25 17:26 UTC, harshavardhana commented
We can also plug this into an even lower level at os-instrument.go @vadmeste such trace for `os`  calls. and remove the MINIO_LOG_POSIX_TIMES env

2021-03-26 00:29 UTC, kerneltime commented
Any plans to extend this to the actual os syscalls?

2021-03-26 00:37 UTC, harshavardhana commented
> We can also plug this into an even lower level at os-instrument.go @vadmeste such trace for `os` calls. and remove the MINIO_LOG_POSIX_TIMES env

@kerneltime ^^

2021-03-26 10:44 UTC, klauspost commented on cmd/xl-storage.go
> +// No implemented
???

2021-03-26 18:16 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#0cba1264-ed1b-40d5-b3ab-42cf9fac57b0) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#3bbdb39b-76af-4f0e-8228-4af85d450e0b) |
<a name="0cba1264-ed1b-40d5-b3ab-42cf9fac57b0"></a>
### 11889-96cad7e/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31078
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 57d2243115ff:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 28 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 51 seconds
(8/15) Running minio-dotnet tests ... done in 54 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 21 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 30 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 73996,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = SlowDown, message = Please reduce your request, bucketName = minio-java-test-14ul72b, objectName = null, resource = /minio-java-test-14ul72b, requestId = 166FF6D9934F1FCB, hostId = 21da4d05-ad50-46bb-822d-f7a67114600e)\nrequest={method=DELETE, url=http://minio-dev8.minio.io:31078/minio-java-test-14ul72b, headers=Host: minio-dev8.minio.io:31078\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210326T181005Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210326/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 305\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166FF6D9934F1FCB\nX-Xss-Protection: 1; mode=block\nDate: Fri, 26 Mar 2021 18:10:05 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executeDelete(MinioClient.java:879), io.minio.MinioClient.removeBucket(MinioClient.java:2669), FunctionalTest.testListObjects(FunctionalTest.java:1416), FunctionalTest.listObjects(FunctionalTest.java:1455), FunctionalTest.runObjectTests(FunctionalTest.java:3747), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 4 minutes and 1 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 8 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="3bbdb39b-76af-4f0e-8228-4af85d450e0b"></a>
### 11889-96cad7e/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31869
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2ddd7a7c86e5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2584,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:31869 s3api copy-object --bucket awscli-mint-test-bucket-22527 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-22527/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 48 seconds
(7/15) Running minio-dotnet tests ... done in 51 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 40 seconds
{
  "args": {},
  "duration": 519,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 41 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 372,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-29h6o3v, objectName = minio-java-test-1s210si-copy, resource = /minio-java-test-29h6o3v/minio-java-test-1s210si-copy, requestId = 166FF6D20A12BBDE, hostId = a8fd5a29-e77c-4ba2-8095-c974d0f6beff)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31869/minio-java-test-29h6o3v/minio-java-test-1s210si-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-r5vtr0/minio-java-test-1s210si\nHost: minio-dev4.minio.io:31869\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210326T180933Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210326/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 26 Mar 2021 18:09:33 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166FF6D20A12BBDE\nX-Xss-Protection: 1; mode=block\nDate: Fri, 26 Mar 2021 18:09:33 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 48 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 43 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2893",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of [...]

2021-03-26 20:32 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#4ff310e3-24a1-4a1a-a16d-23615893d191) |
<a name="4ff310e3-24a1-4a1a-a16d-23615893d191"></a>
### 11889-1c26f73/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31818
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ad98ff1d8e81:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 3114,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:31818 s3api copy-object --bucket awscli-mint-test-bucket-6172 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-6172/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 49 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 43 seconds
{
  "args": {},
  "duration": 1224,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 55 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 263,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-e9jn6t, objectName = minio-java-test-3ef3psk-copy, resource = /minio-java-test-e9jn6t/minio-java-test-3ef3psk-copy, requestId = 166FFE375F7E6B4E, hostId = 4480dd56-64d9-44a0-afa2-cd2f9d0f79ef)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31818/minio-java-test-e9jn6t/minio-java-test-3ef3psk-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-172f86s/minio-java-test-3ef3psk\nHost: minio-dev6.minio.io:31818\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210326T202505Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210326/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 26 Mar 2021 20:25:04 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166FFE375F7E6B4E\nX-Xss-Protection: 1; mode=block\nDate: Fri, 26 Mar 2021 20:25:05 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 51 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 54 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2857",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-32015/s3cmd-test-object-1582 f5f42647-49f7-42a4-9207-da9639637749\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id f5f42647-49f7-42a4-9207-da9639637749 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 14 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-26 20:33 UTC, vadmeste commented
All comments addressed

2021-03-26 20:53 UTC, harshavardhana approved these changes

2021-03-26 20:54 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#d9940faf-dbf0-4e8d-a003-cc4011ab5dd9) |
<a name="d9940faf-dbf0-4e8d-a003-cc4011ab5dd9"></a>
### 11889-95b2cf2/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32626
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 120b7db047f2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 45 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2696,
  "function": "aws --endpoint-url http://minio-c2.minio.io:32626 s3api copy-object --bucket awscli-mint-test-bucket-18723 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-18723/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 46 seconds
(7/15) Running minio-dotnet tests ... done in 48 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 11 seconds
{
  "args": {},
  "duration": 532,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 57 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 305,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-7c3dt4, objectName = minio-java-test-13r3hch-copy, resource = /minio-java-test-7c3dt4/minio-java-test-13r3hch-copy, requestId = 166FFF5F7554A669, hostId = 3b48fff3-d9a5-4496-89a4-9b933d3f3b49)\nrequest={method=PUT, url=http://minio-c2.minio.io:32626/minio-java-test-7c3dt4/minio-java-test-13r3hch-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-12d11v2/minio-java-test-13r3hch\nHost: minio-c2.minio.io:32626\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210326T204616Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210326/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Fri, 26 Mar 2021 20:46:16 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 166FFF5F7554A669\nX-Xss-Protection: 1; mode=block\nDate: Fri, 26 Mar 2021 20:46:16 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 52 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 46 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2974",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-1382/s3cmd-test-object-28400 afa139a6-9cf0-4516-a184-5c193afaa183\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id afa139a6-9cf0-4516-a184-5c193afaa183 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 10 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-26 21:07 UTC, harshavardhana requested changes
```
 mc admin trace -a --response-threshold 1ms --debug myminio/
mc: <DEBUG> GET /minio/admin/v3/trace?err=false&internal=true&os=true&s3=true&storage=true&threshold=1ms HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.2021-03-26T21-01-19Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20210326//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210326T210644Z
Accept-Encoding: gzip

mc: <DEBUG> GET /minio/admin/v3/trace?err=false&internal=true&os=true&s3=true&storage=true&threshold=1ms HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.2021-03-26T21-01-19Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20210326//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210326T210644Z
Accept-Encoding: gzip

mc: <DEBUG> GET /minio/admin/v3/trace?err=false&internal=true&os=true&s3=true&storage=true&threshold=1ms HTTP/1.1
Host: 127.0.0.1:9000
User-Agent: MinIO (linux; amd64) madmin-go/0.0.1 mc/DEVELOPMENT.2021-03-26T21-01-19Z
Authorization: AWS4-HMAC-SHA256 Credential=minio/20210326//s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=**REDACTED**
X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
X-Amz-Date: 20210326T210645Z
Accept-Encoding: gzip

^Cmc: <ERROR> Unable to listen to http trace: context canceled
 (0) admin-trace.go:262 cmd.mainAdminTrace(..)
 Release-Tag:DEVELOPMENT.2021-03-26T21-01-19Z | Commit:786d05312456 | Host:backspace | OS:linux | Arch:amd64 | Lang:go1.16.2 | Mem:2.1 MB/75 MB | Heap:2.1 MB/67 MB.
```

Is not working..

2021-03-26 21:07 UTC, harshavardhana commented
```
 mc admin trace -a --response-threshold 1ms myminio/
mc: <ERROR> Unable to listen to http trace: read tcp 127.0.0.1:41308->127.0.0.1:9000: read: connection reset by peer.
```

2021-03-26 21:49 UTC, poornas commented
don't see any trace except for internal calls.  The example in service-trace.go needs to be fixed

2021-03-27 05:01 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#5781f973-5127-4210-9d69-3980c5cb2a9d) |
<a name="5781f973-5127-4210-9d69-3980c5cb2a9d"></a>
### 11889-4b84f06/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30078
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dd3d368fa02c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... FAILED in 33 seconds
{
  "name": "awscli",
  "duration": 2889,
  "function": "aws --endpoint-url http://minio-c2.minio.io:30078 s3api copy-object --bucket awscli-mint-test-bucket-8345 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-8345/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 41 seconds
(7/15) Running minio-dotnet tests ... done in 41 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 15 seconds
{
  "args": {},
  "duration": 642,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 43 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 275,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-13tikka, objectName = minio-java-test-19nke43-copy, resource = /minio-java-test-13tikka/minio-java-test-19nke43-copy, requestId = 16701A0229B745F6, hostId = a5d6abd0-8a5e-4343-9f18-c098508db97a)\nrequest={method=PUT, url=http://minio-c2.minio.io:30078/minio-java-test-13tikka/minio-java-test-19nke43-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3oendeu/minio-java-test-19nke43\nHost: minio-c2.minio.io:30078\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210327T045422Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210327/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Sat, 27 Mar 2021 04:54:22 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16701A0229B745F6\nX-Xss-Protection: 1; mode=block\nDate: Sat, 27 Mar 2021 04:54:22 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 54 seconds
(9/15) Running minio-py tests ... done in 3 minutes and 24 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2890",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-24050/s3cmd-test-object-11934 a7e08165-d06e-4f09-bbce-11af20184e88\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id a7e08165-d06e-4f09-bbce-11af20184e88 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 10 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-03-27 05:32 UTC, poornas approved these changes
LGTM with the fixes

2021-03-27 05:38 UTC, harshavardhana approved these changes

2021-03-27 06:24 UTC, merged