Add support for existing object replication.
minio/minio pull request #12109
Opened 2021-04-21 06:37 UTC by poornas

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-04-21 07:04 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#25a45c97-9c66-4cea-9a73-33fd9b15cb51) |
<a name="25a45c97-9c66-4cea-9a73-33fd9b15cb51"></a>
### 12109-a20f0d2/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:31670
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e8478fe47cf5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2973,
  "function": "aws --endpoint-url http://minio-c2.minio.io:31670 s3api copy-object --bucket awscli-mint-test-bucket-24094 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-24094/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 45 seconds
(7/15) Running minio-dotnet tests ... done in 45 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 6 seconds
{
  "args": {},
  "duration": 724,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 163,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3oac90o, objectName = minio-java-test-2nvp6jp-copy, resource = /minio-java-test-3oac90o/minio-java-test-2nvp6jp-copy, requestId = 1677CD5C1DA8F29B, hostId = bbf48cd8-0293-4be2-b2a0-2e92c72704cf)\nrequest={method=PUT, url=http://minio-c2.minio.io:31670/minio-java-test-3oac90o/minio-java-test-2nvp6jp-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3hckaj0/minio-java-test-2nvp6jp\nHost: minio-c2.minio.io:31670\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210421T065946Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210421/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 21 Apr 2021 06:59:46 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1677CD5C1DA8F29B\nX-Xss-Protection: 1; mode=block\nDate: Wed, 21 Apr 2021 06:59:46 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 47 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 40 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3085",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-11772/s3cmd-test-object-16552 bd1b2cdb-565f-433a-a8a4-9270d87fc3ad\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id bd1b2cdb-565f-433a-a8a4-9270d87fc3ad put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-04-21 07:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#cfd872b4-34da-44c8-882b-f3f2b7a5197c) |
<a name="cfd872b4-34da-44c8-882b-f3f2b7a5197c"></a>
### 12109-1225749/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32480
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d5489b64287c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2732,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:32480 s3api copy-object --bucket awscli-mint-test-bucket-28686 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-28686/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 45 seconds
(7/15) Running minio-dotnet tests ... done in 37 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 4 seconds
{
  "args": {},
  "duration": 413,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 9 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 323,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-84uqu8, objectName = minio-java-test-16njb8a-copy, resource = /minio-java-test-84uqu8/minio-java-test-16njb8a-copy, requestId = 1677CE60589119FD, hostId = 3ac27b1d-346a-42c5-976a-4834fe3a1aa1)\nrequest={method=PUT, url=http://minio-dev4.minio.io:32480/minio-java-test-84uqu8/minio-java-test-16njb8a-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-1504u1a/minio-java-test-16njb8a\nHost: minio-dev4.minio.io:32480\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210421T071824Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210421/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 21 Apr 2021 07:18:24 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1677CE60589119FD\nX-Xss-Protection: 1; mode=block\nDate: Wed, 21 Apr 2021 07:18:24 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 54 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 42 seconds
(10/15) Running s3cmd tests ... FAILED in 4 seconds
{
  "name": "s3cmd",
  "duration": "2567",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-21116/s3cmd-test-object-17291 31e8b148-2e4a-4d7a-94dc-8242d6fd15c6\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 31e8b148-2e4a-4d7a-94dc-8242d6fd15c6 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-04-21 16:18 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#dfe53b08-112e-46d8-aea5-9d02c0e7b925) |
<a name="dfe53b08-112e-46d8-aea5-9d02c0e7b925"></a>
### 12109-0885889/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32562
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4379812c0d1f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2513,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32562 s3api copy-object --bucket awscli-mint-test-bucket-10663 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-10663/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 45 seconds
(7/15) Running minio-dotnet tests ... done in 40 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 3 seconds
{
  "args": {},
  "duration": 680,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 36 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 252,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2jbmemc, objectName = minio-java-test-rqvj08-copy, resource = /minio-java-test-2jbmemc/minio-java-test-rqvj08-copy, requestId = 1677EB8E1CF83B94, hostId = 3c705a99-a5a1-44f5-9eae-9c476f501971)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32562/minio-java-test-2jbmemc/minio-java-test-rqvj08-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-35g0ff4/minio-java-test-rqvj08\nHost: minio-dev7.minio.io:32562\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210421T161306Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210421/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 21 Apr 2021 16:13:06 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1677EB8E1CF83B94\nX-Xss-Protection: 1; mode=block\nDate: Wed, 21 Apr 2021 16:13:06 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 49 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 44 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "3194",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-5833/s3cmd-test-object-3692 d69edc4c-032b-47d0-a8b0-f27ba64ec74d\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id d69edc4c-032b-47d0-a8b0-f27ba64ec74d put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 8 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-05-21 06:00 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 12109-f60ebf3/gopath/src/github.com/minio
+ git -C 12109-f60ebf3/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 12109-f60ebf3/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 12109-f60ebf3/gopath/src/github.com/minio/minio fetch --quiet minio pull/12109/head:pr12109
+ git -C 12109-f60ebf3/gopath/src/github.com/minio/minio checkout --quiet pr12109
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/12109-f60ebf3/gopath
+ make -C 12109-f60ebf3/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.0.2 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/12109-f60ebf3/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.0.2 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/12109-f60ebf3/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-05-21 16:32 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 12109-4a63600/gopath/src/github.com/minio
+ git -C 12109-4a63600/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 12109-4a63600/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 12109-4a63600/gopath/src/github.com/minio/minio fetch --quiet minio pull/12109/head:pr12109
+ git -C 12109-4a63600/gopath/src/github.com/minio/minio checkout --quiet pr12109
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/12109-4a63600/gopath
+ make -C 12109-4a63600/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.0.2 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/12109-4a63600/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.0.2 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/12109-4a63600/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-05-21 16:49 UTC, harshavardhana commented
Is this PR waiting on something? @poornas

2021-05-21 18:13 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 12109-7a25c60/gopath/src/github.com/minio
+ git -C 12109-7a25c60/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 12109-7a25c60/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 12109-7a25c60/gopath/src/github.com/minio/minio fetch --quiet minio pull/12109/head:pr12109
+ git -C 12109-7a25c60/gopath/src/github.com/minio/minio checkout --quiet pr12109
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/12109-7a25c60/gopath
+ make -C 12109-7a25c60/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.0.2 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/12109-7a25c60/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.0.2 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/12109-7a25c60/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-05-21 18:14 UTC, poornas commented
> Is this PR waiting on something? @poornas

This can be reviewed - will send a PR for mc and reference here.

2021-05-21 19:45 UTC, harshavardhana requested changes

2021-05-21 19:45 UTC, harshavardhana commented on pkg/bucket/replication/rule.go
>  	return nil
```suggestion
	return r.ExistingObjectReplication.Validate()
```

2021-05-21 19:45 UTC, harshavardhana commented on docs/bucket/replication/DESIGN.md
> +Multi site replication is currently not supported.
```suggestion
```

We do not need to mention this since this is out of scope for this API

2021-05-21 19:45 UTC, harshavardhana commented on cmd/object-handlers.go
> +	replicate, sync := mustReplicate(ctx, r, bucket, object, map[string]string{xhttp.AmzObjectTagging: tags.String()}, objInfo.ReplicationStatus.String(), true, false)
I think its time to for mustReplication to take `mustReplicateOptions{}`

2021-05-25 14:55 UTC, klauspost reviewed
Just a few nits.

I am wondering how the state ever gets back to ordinary scanning. In general the bloom filter cycles should be able to keep track of this, meaning if bloom cycle is n then all files should have been visited when it is > n+16. is there any such reset mechanism?

2021-05-25 14:55 UTC, klauspost commented on cmd/bucket-replication_test.go
> +
```suggestion
```

2021-05-25 14:55 UTC, klauspost commented on cmd/bucket-replication_test.go
> +	info         ObjectInfo
Don't use numbers, use names for reference:
```suggestion
	name         string
	info         ObjectInfo
```

2021-05-25 14:55 UTC, klauspost commented on cmd/bucket-replication_test.go
> +	{ //1. no replication config
```suggestion
	{
			name:         "no replication config",
```

2021-05-25 14:55 UTC, klauspost commented on cmd/bucket-replication_test.go
> +			t.Errorf("Test %d: Resync  got %t , want %t", i+1, sync, test.expectedSync)
```suggestion
			t.Errorf("Test %s: Resync  got %t , want %t", test.name, sync, test.expectedSync)
```

2021-05-25 14:55 UTC, klauspost commented on cmd/bucket-replication_test.go
> +		// 1: Pending replication
Add names...

2021-05-26 02:43 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 12109-d514035/gopath/src/github.com/minio
+ git -C 12109-d514035/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 12109-d514035/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 12109-d514035/gopath/src/github.com/minio/minio fetch --quiet minio pull/12109/head:pr12109
+ git -C 12109-d514035/gopath/src/github.com/minio/minio checkout --quiet pr12109
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/12109-d514035/gopath
+ make -C 12109-d514035/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.0.2 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/12109-d514035/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.0.2 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/12109-d514035/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-05-26 02:50 UTC, poornas commented
> Just a few nits.
> 
> I am wondering how the state ever gets back to ordinary scanning. In general the bloom filter cycles should be able to keep track of this, meaning if bloom cycle is n then all files should have been visited when it is > n+16. is there any such reset mechanism?

Didn't rely on the end of scan cycles here because there is only the additional cost of an extra check on the object metadata to see if the object should be re-replicated.  This is unavoidable as the replication rules can be disabled|re-enabled at any time and the scan needs to replicate those objects created in the interim if existing object replication is enabled. Any object that has already been replicated and is not being forcibly re-replicated via `mc replicate reset` would not be queued.

2021-05-26 16:00 UTC, klauspost commented
Yeah, I guess full-scanning the buckets with replication is pretty much always needed.

2021-05-26 16:02 UTC, klauspost approved these changes
LGTM

2021-06-01 16:19 UTC, harshavardhana commented
@poornas you can now update your PRs since health report PRs have been merged.

2021-06-01 19:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#4cfc1440-126c-4473-95dd-dd920f3e13b1) |
<a name="4cfc1440-126c-4473-95dd-dd920f3e13b1"></a>
### 12109-31e27b0/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30960
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 152381710b39:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 19 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 53 seconds
(8/15) Running minio-dotnet tests ... done in 45 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 28 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 37 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[single source with offset]",
  "duration": 36,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Range specified is not valid for source object, bucketName = minio-java-test-1e7amov, objectName = minio-java-test-147unnt, resource = /minio-java-test-1e7amov/minio-java-test-147unnt, requestId = 16848A484F4153E5, hostId = 3d104f33-429b-4921-a361-02ab8ec19261)\nrequest={method=PUT, url=http://minio-c3.minio.io:30960/minio-java-test-1e7amov/minio-java-test-147unnt?uploadId=54950ee1-0ab3-43dc-9fa7-34486cf72d94&partNumber=1, headers=x-amz-copy-source: /minio-java-test-1e7amov/minio-java-test-3m6vku5\nx-amz-copy-source-range: bytes=2048-1048575\nx-amz-copy-source-if-match: cb92d17a904ccec2e6e23b8bb66245fb\nHost: minio-c3.minio.io:30960\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210601T185648Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210601/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 390\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16848A484F4153E5\nX-Xss-Protection: 1; mode=block\nDate: Tue, 01 Jun 2021 18:56:48 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.uploadPartCopy(MinioClient.java:4804), io.minio.MinioClient.composeObject(MinioClient.java:1431), FunctionalTest.testComposeObject(FunctionalTest.java:2120), FunctionalTest.composeObjectTests(FunctionalTest.java:2145), FunctionalTest.composeObject(FunctionalTest.java:2300), FunctionalTest.runObjectTests(FunctionalTest.java:3758), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 59 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 5 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-06-01 19:27 UTC, harshavardhana requested changes

2021-06-01 19:27 UTC, harshavardhana commented on pkg/bucket/policy/action.go
> +// Copyright (c) 2015-2021 MinIO, Inc.
This file should be removed @poornas

2021-06-01 20:31 UTC, harshavardhana commented
You need to fix the 

```
Running lint check
pkg/bucket/replication/rule.go:155:2: `errExistingObjectReplicationMissing` is unused (deadcode)
	errExistingObjectReplicationMissing       = Errorf("Existing object replication must be specified")
	^
pkg/bucket/replication/replication.go:142:1: exported: exported method Type.Set should have comment or be unexported (revive)
func (t Type) Set() bool {
	return t > 0
}
```

Type `Type.Valid()` is better than `Type.Set()`  @poornas  Set is usually not named without an argument.

2021-06-01 20:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#b7c0eb60-90b1-41c7-a266-07cdb2c44533) |
<a name="b7c0eb60-90b1-41c7-a266-07cdb2c44533"></a>
### 12109-dc7ade1/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32259
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fafd4ed37150:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 17 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 4 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 29 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[single source with offset]",
  "duration": 76,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Range specified is not valid for source object, bucketName = minio-java-test-3cm8mrn, objectName = minio-java-test-2srd47b, resource = /minio-java-test-3cm8mrn/minio-java-test-2srd47b, requestId = 16848FC0275569F8, hostId = 9e694c1c-78b4-48bd-9725-aced8f885b20)\nrequest={method=PUT, url=http://minio-c2.minio.io:32259/minio-java-test-3cm8mrn/minio-java-test-2srd47b?uploadId=7c316f67-bf08-494b-93f8-4d48ad273aad&partNumber=1, headers=x-amz-copy-source: /minio-java-test-3cm8mrn/minio-java-test-35ikokh\nx-amz-copy-source-range: bytes=2048-1048575\nx-amz-copy-source-if-match: cb92d17a904ccec2e6e23b8bb66245fb\nHost: minio-c2.minio.io:32259\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210601T203701Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210601/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 390\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16848FC0275569F8\nX-Xss-Protection: 1; mode=block\nDate: Tue, 01 Jun 2021 20:37:01 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.uploadPartCopy(MinioClient.java:4804), io.minio.MinioClient.composeObject(MinioClient.java:1431), FunctionalTest.testComposeObject(FunctionalTest.java:2120), FunctionalTest.composeObjectTests(FunctionalTest.java:2145), FunctionalTest.composeObject(FunctionalTest.java:2300), FunctionalTest.runObjectTests(FunctionalTest.java:3758), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 48 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 49 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-06-01 22:04 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#f8d1b3c0-458b-4752-a36b-eb72699aa18d) |
<a name="f8d1b3c0-458b-4752-a36b-eb72699aa18d"></a>
### 12109-b204703/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32693
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4760e3332399:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 1 seconds
(8/15) Running minio-dotnet tests ... done in 48 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 56 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 25 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[single source with offset]",
  "duration": 30,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Range specified is not valid for source object, bucketName = minio-java-test-ua38t9, objectName = minio-java-test-3ovb4nt, resource = /minio-java-test-ua38t9/minio-java-test-3ovb4nt, requestId = 16849442514716AC, hostId = ccdc2564-7bb8-4ea0-9a13-105d4812015f)\nrequest={method=PUT, url=http://minio-dev4.minio.io:32693/minio-java-test-ua38t9/minio-java-test-3ovb4nt?uploadId=fc9e50e6-6232-4b30-90ef-b6d70756632a&partNumber=1, headers=x-amz-copy-source: /minio-java-test-ua38t9/minio-java-test-1d2guuv\nx-amz-copy-source-range: bytes=2048-1048575\nx-amz-copy-source-if-match: cb92d17a904ccec2e6e23b8bb66245fb\nHost: minio-dev4.minio.io:32693\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210601T215938Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210601/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 388\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16849442514716AC\nX-Xss-Protection: 1; mode=block\nDate: Tue, 01 Jun 2021 21:59:38 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.uploadPartCopy(MinioClient.java:4804), io.minio.MinioClient.composeObject(MinioClient.java:1431), FunctionalTest.testComposeObject(FunctionalTest.java:2120), FunctionalTest.composeObjectTests(FunctionalTest.java:2145), FunctionalTest.composeObject(FunctionalTest.java:2300), FunctionalTest.runObjectTests(FunctionalTest.java:3758), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 46 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 43 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-06-01 22:13 UTC, harshavardhana approved these changes

2021-06-01 22:37 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#4d4b3891-d651-4cde-ac99-66e6cf9b9dfe) |
<a name="4d4b3891-d651-4cde-ac99-66e6cf9b9dfe"></a>
### 12109-365806f/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30480
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b105cedf908f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 15 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 17 seconds
(8/15) Running minio-dotnet tests ... done in 47 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 13 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 29 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[single source with offset]",
  "duration": 29,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Range specified is not valid for source object, bucketName = minio-java-test-2achvnu, objectName = minio-java-test-at3btl, resource = /minio-java-test-2achvnu/minio-java-test-at3btl, requestId = 1684960BA3912E14, hostId = a97d80c4-72e6-451b-ad09-8fe62b86535d)\nrequest={method=PUT, url=http://minio-dev8.minio.io:30480/minio-java-test-2achvnu/minio-java-test-at3btl?uploadId=efd2086d-3f4a-42cd-9309-c4d20b23fd9e&partNumber=1, headers=x-amz-copy-source: /minio-java-test-2achvnu/minio-java-test-277mtsi\nx-amz-copy-source-range: bytes=2048-1048575\nx-amz-copy-source-if-match: cb92d17a904ccec2e6e23b8bb66245fb\nHost: minio-dev8.minio.io:30480\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210601T223222Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210601/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 388\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1684960BA3912E14\nX-Xss-Protection: 1; mode=block\nDate: Tue, 01 Jun 2021 22:32:22 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.uploadPartCopy(MinioClient.java:4804), io.minio.MinioClient.composeObject(MinioClient.java:1431), FunctionalTest.testComposeObject(FunctionalTest.java:2120), FunctionalTest.composeObjectTests(FunctionalTest.java:2145), FunctionalTest.composeObject(FunctionalTest.java:2300), FunctionalTest.runObjectTests(FunctionalTest.java:3758), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 47 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 51 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-06-02 00:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#03fa6adc-ded5-4beb-8434-1ebe61d0961c) |
<a name="03fa6adc-ded5-4beb-8434-1ebe61d0961c"></a>
### 12109-9b998f8/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32554
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fc32a40169f1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 31 seconds
(8/15) Running minio-dotnet tests ... done in 45 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 19 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 57 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[single source with offset]",
  "duration": 26,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Range specified is not valid for source object, bucketName = minio-java-test-3qnfv18, objectName = minio-java-test-20qnkb9, resource = /minio-java-test-3qnfv18/minio-java-test-20qnkb9, requestId = 16849BC3DD576FE3, hostId = 60e8261a-61ee-4cd8-a1ba-a62ab858be1f)\nrequest={method=PUT, url=http://minio-c3.minio.io:32554/minio-java-test-3qnfv18/minio-java-test-20qnkb9?uploadId=2dc0a7f0-83a0-48b5-a052-b2cc3850b9bd&partNumber=1, headers=x-amz-copy-source: /minio-java-test-3qnfv18/minio-java-test-1c9fv62\nx-amz-copy-source-range: bytes=2048-1048575\nx-amz-copy-source-if-match: cb92d17a904ccec2e6e23b8bb66245fb\nHost: minio-c3.minio.io:32554\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210602T001711Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210602/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 390\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16849BC3DD576FE3\nX-Xss-Protection: 1; mode=block\nDate: Wed, 02 Jun 2021 00:17:11 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.uploadPartCopy(MinioClient.java:4804), io.minio.MinioClient.composeObject(MinioClient.java:1431), FunctionalTest.testComposeObject(FunctionalTest.java:2120), FunctionalTest.composeObjectTests(FunctionalTest.java:2145), FunctionalTest.composeObject(FunctionalTest.java:2300), FunctionalTest.runObjectTests(FunctionalTest.java:3758), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 46 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 48 seconds
(12/15) Running s3cmd tests ... done in 21 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-06-02 00:53 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#a3209960-b67a-4ec9-9a3c-636ef33107bd) |
<a name="a3209960-b67a-4ec9-9a3c-636ef33107bd"></a>
### 12109-a30da5d/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30196
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5369891f239e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 12 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 58 seconds
(8/15) Running minio-dotnet tests ... done in 51 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 54 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 27 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[single source with offset]",
  "duration": 34,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Range specified is not valid for source object, bucketName = minio-java-test-3lqki5l, objectName = minio-java-test-c16lpt, resource = /minio-java-test-3lqki5l/minio-java-test-c16lpt, requestId = 16849D7FC977B0A3, hostId = 189ea096-c48c-4278-84bf-6c32138e4dcc)\nrequest={method=PUT, url=http://minio-c2.minio.io:30196/minio-java-test-3lqki5l/minio-java-test-c16lpt?uploadId=d83292db-ceaf-4988-a2f3-91b391348681&partNumber=1, headers=x-amz-copy-source: /minio-java-test-3lqki5l/minio-java-test-21e0gnk\nx-amz-copy-source-range: bytes=2048-1048575\nx-amz-copy-source-if-match: cb92d17a904ccec2e6e23b8bb66245fb\nHost: minio-c2.minio.io:30196\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210602T004857Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210602/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 388\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16849D7FC977B0A3\nX-Xss-Protection: 1; mode=block\nDate: Wed, 02 Jun 2021 00:48:57 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.uploadPartCopy(MinioClient.java:4804), io.minio.MinioClient.composeObject(MinioClient.java:1431), FunctionalTest.testComposeObject(FunctionalTest.java:2120), FunctionalTest.composeObjectTests(FunctionalTest.java:2145), FunctionalTest.composeObject(FunctionalTest.java:2300), FunctionalTest.runObjectTests(FunctionalTest.java:3758), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 51 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 48 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-06-02 02:59 UTC, merged