lock: Timeout Unlock RPC call
minio/minio pull request #12213
Opened 2021-05-04 13:06 UTC by vadmeste

## Description
RPC unlock call needs to be timeouted otherwise this can block
indefintely.

## Motivation and Context
Some reports that the scanner lock is not there and no server is sleeping to wait for
acquiring the scanner lock. I reviewed the code and it seems the only way that this happens
is that those nodes are blocked in GetLock() call and blocks in sendRelease() call because
this latter does not have any timeout.

Internode REST client has a header timeout (15m) but I also think it is better if we do
not rely completely on it.

## How to test this PR?
No easy way to reproduce the failure, only testing is to check if there is no regression

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-05-04 13:26 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#e12f3042-9776-4946-b5de-2361f064b022) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#677c0dfa-7c39-4c40-90c9-c46b9f6ffbf9) |
<a name="677c0dfa-7c39-4c40-90c9-c46b9f6ffbf9"></a>
### 12213-8e9a73f/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32399
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 695565c94ecc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2540,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32399 s3api copy-object --bucket awscli-mint-test-bucket-5685 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-5685/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 38 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 15 seconds
{
  "args": {},
  "duration": 706,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 21 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 130,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2f13c1o, objectName = minio-java-test-1dh4nmm-copy, resource = /minio-java-test-2f13c1o/minio-java-test-1dh4nmm-copy, requestId = 167BDFAB3F182BCF, hostId = c2d52341-e0d0-4dbc-a059-e6df3b93cbb3)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32399/minio-java-test-2f13c1o/minio-java-test-1dh4nmm-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-278rgsu/minio-java-test-1dh4nmm\nHost: minio-dev6.minio.io:32399\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210504T132017Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210504/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 04 May 2021 13:20:17 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167BDFAB3F182BCF\nX-Xss-Protection: 1; mode=block\nDate: Tue, 04 May 2021 13:20:17 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 46 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 38 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2738",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-12475/s3cmd-test-object-30291 48577086-e8b8-4c88-bcf2-ef4f0aa65a33\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 48577086-e8b8-4c88-bcf2-ef4f0aa65a33 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="e12f3042-9776-4946-b5de-2361f064b022"></a>
### 12213-8e9a73f/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32340
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a8a6dc89ef91:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 16 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 13 seconds
(8/15) Running minio-dotnet tests ... done in 50 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 59 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 50 seconds
(11/15) Running minio-js tests ... done in 46 seconds
(12/15) Running minio-py tests ... FAILED in 2 minutes and 45 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-8689e5eb-04dd-4cba-88cd-48d0a41f3752",
    "object_name": "1f249d32-b1a3-4265-8890-63e9551f8536"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-8689e5eb-04dd-4cba-88cd-48d0a41f3752, request_id: 167BDFF29CB8DB9B, host_id: f5d4b01f-409c-469c-b315-3ac35020fb26, bucket_name: minio-py-test-8689e5eb-04dd-4cba-88cd-48d0a41f3752",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1640, in test_thread_safe\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.e [...]

2021-05-04 13:47 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#cf32e9a3-aa71-4ce7-b4f8-bb8abaa32c53) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#b67e0886-2b5a-4f9c-8076-988b11ecace3) |
<a name="b67e0886-2b5a-4f9c-8076-988b11ecace3"></a>
### 12213-f24ad9e/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30657
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 14c298af24bf:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2523,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:30657 s3api copy-object --bucket awscli-mint-test-bucket-14786 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-14786/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 45 seconds
(7/15) Running minio-dotnet tests ... done in 46 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 8 seconds
{
  "args": {},
  "duration": 324,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 24 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 127,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2mm3j77, objectName = minio-java-test-3sra5u0-copy, resource = /minio-java-test-2mm3j77/minio-java-test-3sra5u0-copy, requestId = 167BE0C26E4A6835, hostId = c94f2b52-8295-4c7d-8519-53aa2b2b43f5)\nrequest={method=PUT, url=http://minio-dev7.minio.io:30657/minio-java-test-2mm3j77/minio-java-test-3sra5u0-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3ooi8cv/minio-java-test-3sra5u0\nHost: minio-dev7.minio.io:30657\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210504T134016Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210504/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 04 May 2021 13:40:16 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167BE0C26E4A6835\nX-Xss-Protection: 1; mode=block\nDate: Tue, 04 May 2021 13:40:16 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 46 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 39 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2572",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-6616/s3cmd-test-object-2924 45a3bf5e-b9d7-426c-879e-8fb3e5437475\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 45a3bf5e-b9d7-426c-879e-8fb3e5437475 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 6 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="cf32e9a3-aa71-4ce7-b4f8-bb8abaa32c53"></a>
### 12213-f24ad9e/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30198
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5a20de040cdf:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 16 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 9 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 4 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 3 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 50 seconds
(11/15) Running minio-js tests ... done in 44 seconds
(12/15) Running minio-py tests ... FAILED in 2 minutes and 41 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-0f1411f9-452d-45bb-84f6-1ab736d72d8f",
    "object_name": "098640bd-9f0b-424e-8bcd-eb786e82cd4a"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-0f1411f9-452d-45bb-84f6-1ab736d72d8f, request_id: 167BE10B70CE03ED, host_id: bef1bd6a-edfa-447f-a2a6-a49d7e0f4a8f, bucket_name: minio-py-test-0f1411f9-452d-45bb-84f6-1ab736d72d8f",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1640, in test_thread_safe\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_erro [...]

2021-05-04 20:17 UTC, harshavardhana requested changes
can you add a test case in pkg/dsync/drwmutex_test.go to cater for this new timeout? @vadmeste

2021-05-04 20:17 UTC, harshavardhana commented on pkg/dsync/drwmutex.go
> +const drwMutexUnlockCallTimeout = 20 * time.Second
```suggestion
const drwMutexUnlockCallTimeout = 30 * time.Second
```

2021-05-05 11:29 UTC, vadmeste commented
@harshavardhana comments addressed, PTAL.

2021-05-05 11:45 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#eb1825b4-d2ad-4573-bb39-3196dfb7b28b) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#dee6ed9e-db69-443e-a624-28045c693208) |
<a name="dee6ed9e-db69-443e-a624-28045c693208"></a>
### 12213-b832034/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:30381
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2326f87417db:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2604,
  "function": "aws --endpoint-url http://minio-dev8.minio.io:30381 s3api copy-object --bucket awscli-mint-test-bucket-14802 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-14802/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 34 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 6 seconds
{
  "args": {},
  "duration": 376,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 132,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-28dnmi7, objectName = minio-java-test-3mbs0hl-copy, resource = /minio-java-test-28dnmi7/minio-java-test-3mbs0hl-copy, requestId = 167C28C469C59868, hostId = 9f309381-849e-4183-ac86-aa574dc52656)\nrequest={method=PUT, url=http://minio-dev8.minio.io:30381/minio-java-test-28dnmi7/minio-java-test-3mbs0hl-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3v3ds98/minio-java-test-3mbs0hl\nHost: minio-dev8.minio.io:30381\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210505T113949Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210505/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 05 May 2021 11:39:49 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167C28C469C59868\nX-Xss-Protection: 1; mode=block\nDate: Wed, 05 May 2021 11:39:50 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 46 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 35 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2710",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-13609/s3cmd-test-object-27453 6046230d-3e9c-4692-9bbe-4421f1a64f6c\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 6046230d-3e9c-4692-9bbe-4421f1a64f6c put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="eb1825b4-d2ad-4573-bb39-3196dfb7b28b"></a>
### 12213-b832034/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32116
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e0b8c1e78a78:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 59 seconds
(8/15) Running minio-dotnet tests ... done in 45 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 56 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 41 seconds
(11/15) Running minio-js tests ... done in 47 seconds
(12/15) Running minio-py tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-018a1a01-a17b-4820-adea-d4a28beafba9",
    "object_name": "ca397729-a092-47ac-baaf-f589f34b5e3d"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-018a1a01-a17b-4820-adea-d4a28beafba9, request_id: 167C2905C3001553, host_id: be1f1967-780f-4c2c-a8ac-f2571b0cda0c, bucket_name: minio-py-test-018a1a01-a17b-4820-adea-d4a28beafba9",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1640, in test_thread_safe\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S [...]

2021-05-05 12:42 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#e1c483be-161b-432d-96e4-30eba0897d53) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#1a8b9369-6220-4d03-9975-457ae3dab95f) |
<a name="1a8b9369-6220-4d03-9975-457ae3dab95f"></a>
### 12213-50962a8/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30208
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 80a97a11cc8f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2565,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30208 s3api copy-object --bucket awscli-mint-test-bucket-4112 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-4112/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 16 seconds
{
  "args": {},
  "duration": 786,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 21 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 118,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-2aa3ctp, objectName = minio-java-test-29l6tl-copy, resource = /minio-java-test-2aa3ctp/minio-java-test-29l6tl-copy, requestId = 167C2BE72B989176, hostId = 2787fda7-62fe-45ba-8418-d6c1ab6cd942)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30208/minio-java-test-2aa3ctp/minio-java-test-29l6tl-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-3ba0314/minio-java-test-29l6tl\nHost: minio-dev6.minio.io:30208\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210505T123717Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210505/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Wed, 05 May 2021 12:37:17 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167C2BE72B989176\nX-Xss-Protection: 1; mode=block\nDate: Wed, 05 May 2021 12:37:17 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 47 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 50 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3334",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-19569/s3cmd-test-object-8441 5284e4dc-02b3-4f76-9d15-5065adbdd3e3\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 5284e4dc-02b3-4f76-9d15-5065adbdd3e3 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="e1c483be-161b-432d-96e4-30eba0897d53"></a>
### 12213-50962a8/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30306
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b24f5c9f2ee7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 14 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 2 seconds
(8/15) Running minio-dotnet tests ... done in 55 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 47 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 48 seconds
(11/15) Running minio-js tests ... done in 46 seconds
(12/15) Running minio-py tests ... FAILED in 2 minutes and 41 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-73711308-3c9c-4bb6-ac5b-480639c585a0",
    "object_name": "38cbbfec-6db7-4dbb-92d4-e04c4d4c2e4d"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-73711308-3c9c-4bb6-ac5b-480639c585a0, request_id: 167C2C26EA2BE51D, host_id: cf6b7580-fe01-4829-aa21-a76e88acda65, bucket_name: minio-py-test-73711308-3c9c-4bb6-ac5b-480639c585a0",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1640, in test_thread_safe\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3E [...]

2021-05-05 13:16 UTC, klauspost reviewed
Any particular reason this isn't done here: https://github.com/minio/minio/blob/069432566fcfac1f1053677cc925ddafd750730a/cmd/lock-rest-client.go#L136

There are a lot of inaccuracies in the returned bools.
`false` really means "maybe unlocked, maybe not", and `sendRelease` ignoring the bool makes it even fishier. But probably beyond this PR.

2021-05-05 13:16 UTC, klauspost commented on pkg/dsync/rpc-client-interface.go
> +	RUnlock(ctx context.Context, args LockArgs) (bool, error)
```suggestion
	// Canceling the context will abort the remote call.
	// In that case, the resource may or may not be unlocked.
	RUnlock(ctx context.Context, args LockArgs) (bool, error)
```

2021-05-05 13:16 UTC, klauspost commented on pkg/dsync/rpc-client-interface.go
> +	Unlock(ctx context.Context, args LockArgs) (bool, error)
```suggestion
	// Canceling the context will abort the remote call.
	// In that case, the resource may or may not be unlocked.
	Unlock(ctx context.Context, args LockArgs) (bool, error)
```

2021-05-06 04:32 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#bed9e876-920f-4f5c-a710-6a70293aa412) |
<a name="bed9e876-920f-4f5c-a710-6a70293aa412"></a>
### 12213-789bea2/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30053
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b697fcc4bd2a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2706,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30053 s3api copy-object --bucket awscli-mint-test-bucket-12898 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-12898/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 26 seconds
{
  "args": {},
  "duration": 426,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 2 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 159,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-v1ld6t, objectName = minio-java-test-3dp0ffg-copy, resource = /minio-java-test-v1ld6t/minio-java-test-3dp0ffg-copy, requestId = 167C5FC01EF4E0CF, hostId = 4137082c-705d-46d1-9d3b-32850cae9cc4)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30053/minio-java-test-v1ld6t/minio-java-test-3dp0ffg-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2hsg1t0/minio-java-test-3dp0ffg\nHost: minio-dev4.minio.io:30053\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210506T042724Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210506/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Thu, 06 May 2021 04:27:24 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167C5FC01EF4E0CF\nX-Xss-Protection: 1; mode=block\nDate: Thu, 06 May 2021 04:27:24 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 49 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 44 seconds
(10/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2534",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-32059/s3cmd-test-object-29004 b8d3dbfa-7f51-4cb2-a26f-c45b2bf9b30b\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id b8d3dbfa-7f51-4cb2-a26f-c45b2bf9b30b put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-05-06 09:54 UTC, vadmeste commented
@klauspost yeah, the whole PR won't work without context in lock-rpc-client, thanks for catching it. @harshavardhana fixed it already.

Unlock() should not timeout anyway, this will only timeout RPC calls in the low level, Unlock() will indefinitely try to unlock.

2021-05-06 12:54 UTC, klauspost commented
@vadmeste I was wondering if the unlock should block at all. Technically we could do the unlock async to reduce the latency. It may add short blocking if the same object is accessed right away, but usually that shouldn't be the case.

2021-05-06 15:28 UTC, harshavardhana commented
> @vadmeste I was wondering if the unlock should block at all. Technically we could do the unlock async to reduce the latency. It may add short blocking if the same object is accessed right away, but usually that shouldn't be the case.

The main reason is build up of such goroutines should be controlled and we are also blocking to slow down the client.

Otherwise server can get overwhelmed if there are too many short calls. You want to slow down client as per the behavior of their network.

2021-05-06 15:29 UTC, harshavardhana approved these changes

2021-05-07 04:13 UTC, harshavardhana commented
> > @vadmeste I was wondering if the unlock should block at all. Technically we could do the unlock async to reduce the latency. It may add short blocking if the same object is accessed right away, but usually that shouldn't be the case.
> 
> The main reason is build up of such goroutines should be controlled and we are also blocking to slow down the client.
> 
> Otherwise server can get overwhelmed if there are too many short calls. You want to slow down client as per the behavior of their network.

Another reason is we want the cost of Unlock() to be seen by the client call.

Otherwise potential risk of building up calls on slow servers that get backgrounded, potentially leading to large goroutine build up that may in-turn slow down the server.

Atleast right now the server costs are seen by the client, in-turn helping to shape their workload appropriately.  

It may be not a good idea to fake better response times, causing more load buildup on the server.

We took async approach with delete but there the cost is negligible and it doesn't interfere with namespace and locking.

IMO all namespace operations need to be blocking in some form.

2021-05-11 09:04 UTC, klauspost approved these changes

2021-05-11 09:11 UTC, merged