MRF: Better detection of offline disks during deletion
minio/minio pull request #12252
Opened 2021-05-07 12:28 UTC by vadmeste

## Description
MRF does not detect when a node is disconnected and reconnected quickly
this change will ensure that MRF is alerted by comparing the last disk
reconnection timestamp with the last MRF check time.

Signed-off-by: Anis Elleuch <anis@min.io>

## Motivation and Context
MRF does not work when there is a short node disconnection

## How to test this PR?
Contact me for a test script

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-05-07 16:09 UTC, harshavardhana approved these changes

2021-05-11 02:31 UTC, harshavardhana commented
PTAL @klauspost

2021-05-11 08:16 UTC, klauspost requested changes

2021-05-11 08:16 UTC, klauspost commented on cmd/rest/client.go
> +	lastConn  int64
See the bug noted above. This will have alignment problems on some platforms.
```suggestion
	_           int32
	lastConn    int64
```
This should AFAICT make it align.

2021-05-11 08:16 UTC, klauspost commented on cmd/storage-interface.go
> +	LastConn() time.Time
Doc what it is supposed to return.

2021-05-11 09:16 UTC, vadmeste commented on cmd/rest/client.go
> +	lastConn  int64
> This should AFAICT make it align.

Done, yes it looks like it needs 64 bits alignment

2021-05-11 09:16 UTC, vadmeste commented
All comments addressed!

2021-05-11 09:34 UTC, klauspost reviewed
Just clarify a bit.

2021-05-11 09:34 UTC, klauspost commented on cmd/storage-interface.go
> +	LastConn() time.Time // Returns the last time of this disk (re)-connection
```suggestion
	LastConn() time.Time // Returns the last time this disk (re)-connected
```

2021-05-11 10:54 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :x: [more...](#64fed358-dd2f-4ac6-92ef-28633a15b354) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#fb737739-0fee-4b62-9c4f-0a38fd494702) |
<a name="64fed358-dd2f-4ac6-92ef-28633a15b354"></a>
### 12252-ded89ba/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31540
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2da8f8f86f3d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 24 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 4 seconds
(8/15) Running minio-dotnet tests ... done in 52 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 52 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 18 seconds
(11/15) Running minio-js tests ... FAILED in 8 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 20,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:79:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:684:10) at endReadableNT (internal/streams/readable.js:1327:12) at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
(11/15) Running minio-py tests ... done in 2 minutes and 14 seconds
(12/15) Running s3cmd tests ... done in 19 seconds
(13/15) Running s3select tests ... done in 7 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="fb737739-0fee-4b62-9c4f-0a38fd494702"></a>
### 12252-ded89ba/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30444
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 146a80edd8f6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2640,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30444 s3api copy-object --bucket awscli-mint-test-bucket-2117 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-2117/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 49 seconds
(7/15) Running minio-dotnet tests ... done in 42 seconds
(8/15) Running minio-go tests ... FAILED in 2 minutes and 12 seconds
{
  "args": {},
  "duration": 579,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 13 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 123,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-38vagh5, objectName = minio-java-test-1fk1o45-copy, resource = /minio-java-test-38vagh5/minio-java-test-1fk1o45-copy, requestId = 167DFD750C1ECCD9, hostId = cd9aae55-5cb9-443f-b0c5-ec6c707c6935)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30444/minio-java-test-38vagh5/minio-java-test-1fk1o45-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-k0m14c/minio-java-test-1fk1o45\nHost: minio-dev4.minio.io:30444\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210511T104840Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210511/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 11 May 2021 10:48:40 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167DFD750C1ECCD9\nX-Xss-Protection: 1; mode=block\nDate: Tue, 11 May 2021 10:48:40 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 46 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 50 seconds
(10/15) Running s3cmd tests ... FAILED in 6 seconds
{
  "name": "s3cmd",
  "duration": "3522",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-9187/s3cmd-test-object-28334 5392fb3d-7b1c-4d06-9800-20a3515bd957\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 5392fb3d-7b1c-4d06-9800-20a3515bd957 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 7 seconds
(11/15) Running security tests ... do [...]

2021-05-11 15:27 UTC, klauspost approved these changes
LGTM

2021-05-11 16:06 UTC, harshavardhana approved these changes

2021-05-11 16:19 UTC, merged