Check buffer size to avoid copy in chunkreader
minio/minio pull request #12301
Opened 2021-05-15 12:25 UTC by kaplanlior

## Description
Choose whether to use internal buffer or use given buffer based on the size.

## Motivation and Context
This will allow us to remove the copy call, and improve performance since this
chuckreader is heavily used in minio.

## How to test this PR?
Existing unit tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-05-15 12:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#0a8a9a7a-f3de-4828-9f79-6c111bc0086b) |
| mint-fs.sh | :x: [more...](#b778e4e7-7ada-416e-bf74-77a897a15e4b) |
| mint-gateway-s3.sh | :x: [more...](#936b483c-f6ed-455b-8d37-1ea78485b0c2) |
| mint-erasure.sh | :x: [more...](#1206424e-66fa-4655-80e4-387ab5476b0a) |
| mint-dist-erasure.sh | :x: [more...](#70d864ec-fef5-4a2b-bced-9017b2b2c347) |
| mint-zoned.sh | :x: [more...](#c7a6e396-c9a0-4685-b791-32c56da025d6) |
| mint-gateway-nas.sh | :x: [more...](#334b1bb1-a7a6-4836-b1e9-f264c4d9aca8) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#74779924-c001-406e-baff-dd530e086cb5) |
<a name="70d864ec-fef5-4a2b-bced-9017b2b2c347"></a>
### 12301-2c7f09b/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32080
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fdfb8caed145:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 5 seconds
{
  "name": "mc",
  "duration": "468",
  "function": "test_get_object",
  "status": "FAIL",
  "error": "mc-test-object-30582.downloaded: md5sum mismatch"
}
(7/15) Running minio-dotnet tests ... done in 38 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 2 seconds
{
  "args": {
    "bucketName": "minio-go-test-1vuoi34vuzzb1hy4",
    "objectName": "minio-go-test-1vuoi34vuzzb1hy4unique"
  },
  "duration": 3039,
  "function": "GetObject(bucketName, objectName)",
  "message": "GetObject bytes mismatch",
  "name": "minio-go: testFunctional",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... done in 35 seconds
(9/15) Running minio-js tests ... done in 46 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 4 seconds
(11/15) Running s3cmd tests ... done in 16 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="74779924-c001-406e-baff-dd530e086cb5"></a>
### 12301-2c7f09b/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31032
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e19f00bf3c62:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2897,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:31032 s3api copy-object --bucket awscli-mint-test-bucket-11912 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-11912/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... FAILED in 4 seconds
{
  "name": "mc",
  "duration": "378",
  "function": "test_get_object",
  "status": "FAIL",
  "error": "mc-test-object-15993.downloaded: md5sum mismatch"
}
(6/15) Running minio-dotnet tests ... done in 39 seconds
(7/15) Running minio-go tests ... FAILED in 34 seconds
{
  "args": {
    "bucketName": "minio-go-test-cvod12xkeirzu0sa",
    "objectName": "minio-go-test-cvod12xkeirzu0saunique"
  },
  "duration": 445,
  "function": "GetObject(bucketName, objectName)",
  "message": "GetObject bytes mismatch",
  "name": "minio-go: testFunctional",
  "status": "FAIL"
}
(7/15) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 123,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3gghm5k, objectName = minio-java-test-20emvsd-copy, resource = /minio-java-test-3gghm5k/minio-java-test-20emvsd-copy, requestId = 167F3DA5DFA45DF8, hostId = fe71367e-4fdb-49be-b348-84b4a37f4b59)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31032/minio-java-test-3gghm5k/minio-java-test-20emvsd-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-15213nl/minio-java-test-20emvsd\nHost: minio-dev7.minio.io:31032\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210515T123613Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210515/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Sat, 15 May 2021 12:36:13 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167F3DA5DFA45DF8\nX-Xss-Protection: 1; mode=block\nDate: Sat, 15 May 2021 12:36:13 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(7/15) Running minio-js tests ... done in 47 seconds
(8/15) Running minio-py tests ... done in 2 minutes and 46 seconds
(9/15) Running s3cmd tests ... FAILED in 5 seconds
{
  "name": "s3cmd",
  "duration": "2986",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-2761/s3cmd-test-object-22996 006db6fa-8c7a-4315-a4dd-6563dd66c891\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 006db6fa-8c7a-4315-a4dd-6563dd66c891 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(9/15) Running s3select tests ... done in 6 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="c7a6e396-c9a0-4685-b791-32c56da025d6"></a>
### 12301-2c7f09b/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31902
ACCESS_KEY:           minio
SECRET_KEY:           * [...]

2021-05-15 16:13 UTC, harshavardhana requested changes
This change doesn't look correct, our functional tests are failing. 

Also please paste the benchmarking numbers to show improvement with the existing code.

2021-05-17 09:29 UTC, klauspost requested changes
Thanks for the PR. Please apply the fix and post benchmarks.

2021-05-17 09:29 UTC, klauspost commented on cmd/streaming-signature-v4.go
> +	if cap(buf) < size {
```suggestion
	internalBuf := cap(buf) < size
	if internalBuf {
```

2021-05-17 09:29 UTC, klauspost commented on cmd/streaming-signature-v4.go
> +		internalBuf = true
```suggestion
```

2021-05-17 09:29 UTC, klauspost commented on cmd/streaming-signature-v4.go
> +		n += len(buf)
Your read is most likely bigger than the size read.
```suggestion
		n += int64(size)
```

2021-05-17 13:17 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 12301-1975c48/gopath/src/github.com/minio
+ git -C 12301-1975c48/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 12301-1975c48/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 12301-1975c48/gopath/src/github.com/minio/minio fetch --quiet minio pull/12301/head:pr12301
+ git -C 12301-1975c48/gopath/src/github.com/minio/minio checkout --quiet pr12301
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/12301-1975c48/gopath
+ make -C 12301-1975c48/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/minio/minio-go/v7 v7.0.11-0.20210302210017-6ae69c73ce78
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading golang.org/x/sys v0.0.0-20210225134936-a50acf3fe073
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/minio/sio v0.2.1
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading golang.org/x/crypto v0.0.0-20210415154028-4f45737414dc
go: downloading github.com/shirou/gopsutil/v3 v3.21.1
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
go: downloading gopkg.in/yaml.v2 v2.3.0
go: downloading github.com/dswarbrick/smart v0.0.0-20190505152634-909a45200d6d
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/gorilla/handlers v1.5.1
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/klauspost/compress v1.11.12
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/klauspost/reedsolomon v1.9.11
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/pierrec/lz4 v2.5.2+incompatible
go: downloading github.com/prometheus/procfs v0.6.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/tinylib/msgp v1.1.3
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading go.etcd.io/etcd v0.0.0-20201125193152-8a03d2e9614b
go: downloading github.com/coredns/coredns v1.4.0
go: downloading go.uber.org/zap v1.13.0
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gomodule/redigo v1.8.3
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/nats-io/nats.go v1.10.0
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/olivere/elastic/v7 v7.0.22
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/golang/protobuf v1.4.3
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/willf/bitset v1.1.11
go: downloading github.com/klauspost/cpuid v1.3.1
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/tidwall/gjson v1.6.8
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20200615164410-66371956d46c
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.1
go: downloading go.uber.org/multierr v1.3.0
go: downloading go.uber.org/atomic v1.5.0
go: downloading github.com/felixge/httpsnoop v1.0.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/tidwall/pretty v1.0.2
go: downloading github.com/tidwall/match v1.0.3
go: downloading github.com/hashicorp/go-uuid v1.0.2
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading github.com/jcmturner/dnsutils/v2 v2.0.0
go: downloading github.com/jcmturner/aescts/v2 v2.0.0
go: downloading github.com/jcmturner/rpc/v2 v2.0.3
go: downloading golang.org/x/text v0.3.3
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading google.golang.org/genproto v0.0.0-20190819201941-24fa4b261c55
go: downloading google.golang.org/grpc v1.26.0
go: downloading go.opencensus.io v0.22.5
go: downloading github.com/nats-io/nkeys v0.2.0
go: downloading github.com/nats-io/jwt v1.1.0
go: downloading google.golang.org/protobuf v1.23.0
go: downloading github.com/prometheus/common v0.14.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading gopkg.in/ini.v1 v1.57.0
go: downloading github.com/minio/md5-simd v1.1.1
go: downloading github.com/rs/xid v1.2.1
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.5.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20200313005456-10cdbea86bc0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/klauspost/cpuid/v2 v2.0.4
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/golang/groupcache v0.0.0-20190702054246-869f871628b6
go: downloading golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: downloading github.com/jcmturner/goidentity/v6 v6.0.1
go: downloading github.com/coreos/go-semver v0.2.0
go: downloading github.com/coreos/go-systemd v0.0.0-20180511133405-39ca1b05acc7
go: downloading github.com/coreos/pkg v0.0.0-20160727233714-3ac0863d7acf
go: downloading github.com/mailru/easyjson v0.7.6
go: downloading github.com/josharian/intern v1.0.0
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
# github.com/minio/minio/cmd
cmd/streaming-signature-v4.go:366:5: invalid operation: n += int64(size) (mismatched types int and int64)
make: *** [build] Error 2

```

2021-05-17 13:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ebf20107-a9e8-4542-80a6-1af9ae5b42b1) |
| mint-fs.sh | :x: [more...](#1367e9b3-ab09-47a4-94f3-fb3e0ae53d69) |
| mint-erasure.sh | :x: [more...](#7d40aee2-1bfb-44a7-989a-c7e9040fc365) |
| mint-dist-erasure.sh | :x: [more...](#50434979-8ebf-4196-ba43-ae55145de1a3) |
| mint-zoned.sh | :x: [more...](#fdde0be5-f54a-4848-b1d7-9625fa89eaab) |
| mint-gateway-nas.sh | :x: [more...](#4accfefb-a743-43a1-890c-b3482c53f81a) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#47e966dc-b06b-4e14-b4d9-84fb18bf3833) |
<a name="7d40aee2-1bfb-44a7-989a-c7e9040fc365"></a>
### 12301-6e9a7af/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30052
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d14ccb43eed6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 35 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 20 seconds
{
  "args": {
    "bucketName": "minio-go-test-j0j3fedtlmkxa2i3",
    "objectName": "jbonqxyagknke0icw9m4xvdqoe19v6",
    "sse": {}
  },
  "duration": 36,
  "error": "You did not provide the number of bytes specified by the Content-Length HTTP header.",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 21 seconds
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 27 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="4accfefb-a743-43a1-890c-b3482c53f81a"></a>
### 12301-6e9a7af/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev8.minio.io:31111
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b81c7a15b4da:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 seconds
(5/15) Running awscli tests ... done in 1 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 43 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 13 seconds
{
  "args": {
    "bucketName": "minio-go-test-iwkmwhlkrsulvj5f",
    "objectName": "5iesa562efger5yoawrjuome6kaqc2",
    "sse": {}
  },
  "duration": 20,
  "error": "You did not provide the number of bytes specified by the Content-Length HTTP header.",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 11 seconds
(10/15) Running minio-js tests ... done in 32 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 3 seconds
(12/15) Running s3cmd tests ... done in 13 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="47e966dc-b06b-4e14-b4d9-84fb18bf3833"></a>
### 12301-6e9a7af/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31355
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c25f0de36d7a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2825,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:31355 s3api copy-object --bucket awscli-mint-test-bucket-12338 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-12338/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 51 seconds
(7/15) Running minio-dotnet tests ... done in 37 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 38 seconds
{
  "args": {
    "bucketName": "minio-go-test-c00lbslwmgblnwks",
    "objectName": "5pu2xq2hnt3oygt4biclhg3sfduw5k",
    "sse": {}
  },
  "duration": 99,
  "error": "You did not provide the number of bytes specified by the Content-Length HTTP header.",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 260,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3tp47p8, objectName = minio-java-test-368emk6-copy, resource = /minio-java-test-3tp47p8/minio-java-test-368emk6-copy, requestId = 167FDE151FD3A24A, hostId = 64ce8cf8-b554-4f60-b6bd-8ab1096c4d22)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31355/minio-java-test-3tp47p8/minio-java-test-368emk6-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-2rdnaqk/minio-java-test-368emk6\nHost: minio-dev4.minio.io:31355\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210517T133613Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210517/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 418\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Mon, 17 May 2021 13:36:13 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 167FDE151FD3A24A\nX-Xss-Protection: 1; mode=block\nDate: Mon, 17 May 2021 13:36:13 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runO [...]

2021-05-17 13:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#990d73c7-251a-4971-95c1-818c1d96a868) |
| mint-fs.sh | :x: [more...](#0db8442f-f7ef-45bc-9434-cddaa8ef53dc) |
| mint-erasure.sh | :x: [more...](#f94086ba-ad3c-46e0-b8e0-662cef59b456) |
| mint-dist-erasure.sh | :x: [more...](#8d53d5df-cb92-46a3-8844-40e7f70738b0) |
| mint-zoned.sh | :x: [more...](#4ae1b91c-1d13-4180-9455-fc8c0418c8ef) |
| mint-gateway-nas.sh | :x: [more...](#082f6d5b-95a4-4cb4-bb1c-1bd6b7ee9ca3) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#60d06f6f-0e40-4dfc-bc72-6039fa7952a2) |
<a name="082f6d5b-95a4-4cb4-bb1c-1bd6b7ee9ca3"></a>
### 12301-8969212/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:32476
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f9c3ad73fb69:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 0 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 58 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... FAILED in 38 seconds
{
  "args": {
    "bucketName": "minio-go-test-3unvty6lcxh95gej",
    "objectName": "f3cnmi4o3ei4s5nvjlw6353iagso1y",
    "sse": {}
  },
  "duration": 42,
  "error": "You did not provide the number of bytes specified by the Content-Length HTTP header.",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 13 seconds
(10/15) Running minio-js tests ... done in 34 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 0 seconds
(12/15) Running s3cmd tests ... done in 13 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="4ae1b91c-1d13-4180-9455-fc8c0418c8ef"></a>
### 12301-8969212/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31808
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cf620af9456e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 0 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-bgza9vm11c49jkhr",
    "objectName": "mfi1ywjk4kx9zkboup5400qozm0jap",
    "sse": {}
  },
  "duration": 314,
  "error": "You did not provide the number of bytes specified by the Content-Length HTTP header.",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 1 minutes and 10 seconds
(10/15) Running minio-js tests ... done in 47 seconds
(11/15) Running minio-py tests ... FAILED in 2 minutes and 24 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-51456c60-834b-4087-89d2-187e97aee34c",
    "object_name": "83412a5a-638e-4186-a36f-07e3bd43b016"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-51456c60-834b-4087-89d2-187e97aee34c, request_id: 167FDF4F1082BE04, host_id: e7ef613e-527b-404a-914a-761610507e65, bucket_name: minio-py-test-51456c60-834b-4087-89d2-187e97aee34c",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1640, in test_thread_safe\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-51456c60-834b-4087-89d2-187e97aee34c, request_id: 167FDF4F1082BE04, host_id: e7ef613e-527b-404a-914a-761610507e65, bucket_name: minio-py-test-51456c60-834b-4087-89d2-187e97aee34c\n",
  "duration": 6074
}
(11/15) Running s3cmd tests ... done in 18 seconds
(12/15) Running s3select tests ... done in 6 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="f94086ba-ad3c-46e0-b8e0-662cef59b456"></a>
### 12301-8969212/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32689
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ba2e67a05ae6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 0 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 2 seconds
(8/15) Running minio-dotnet tests ... done in 31 seconds
(9/15) Running minio-go tests ... FAILED in 59 seconds
{
  "args": {
    "bucketName": "minio-go-test-g0db395c2ci3ocui",
    "objectName": "yev4kypm9hi4o01325miozmd404ovp",
    "sse": {}
  },
  "duration": 30,
  "error": "You did not provide the number of bytes specified by the Content-Length HTTP header.",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 23 seconds
(10/15) Running minio-js tests ... done in 52 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 24 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="60d06f6f-0e40-4dfc-bc72-6039fa7952a2"></a>
### 12301-8969212/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31249
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 632d71768bbe:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-s [...]

2021-05-17 14:05 UTC, kaplanlior commented
Warp tool is used to simulate the stress test.
Average put throughput is increased by 4%.

Benchmark Results
----------------------------------------

**Before**
Operation: PUT
* Average: 198.71 MiB/s, 19.87 obj/s

Throughput, split into 297 x 1s:
 * Fastest: 245.7MiB/s, 24.57 obj/s
 * 50% Median: 198.3MiB/s, 19.83 obj/s
 * Slowest: 150.1MiB/s, 15.01 obj/s

**After**
Operation: PUT
* Average: 205.37 MiB/s, 20.54 obj/s

Throughput, split into 296 x 1s:
 * Fastest: 255.4MiB/s, 25.54 obj/s
 * 50% Median: 206.1MiB/s, 20.61 obj/s
 * Slowest: 157.6MiB/s, 15.76 obj/s

2021-05-17 14:07 UTC, klauspost commented
@kaplanlior 

Seems like there are still problems with the integration (mint) tests: 

```
  "error": "You did not provide the number of bytes specified by the Content-Length HTTP header.",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
```

etc.

2021-05-17 15:27 UTC, harshavardhana commented
> Warp tool is used to simulate the stress test.
> Average put throughput is increased by 4%.
> 
> ## Benchmark Results
> **Before**
> Operation: PUT
> 
> * Average: 198.71 MiB/s, 19.87 obj/s
> 
> Throughput, split into 297 x 1s:
> 
> * Fastest: 245.7MiB/s, 24.57 obj/s
> * 50% Median: 198.3MiB/s, 19.83 obj/s
> * Slowest: 150.1MiB/s, 15.01 obj/s
> 
> **After**
> Operation: PUT
> 
> * Average: 205.37 MiB/s, 20.54 obj/s
> 
> Throughput, split into 296 x 1s:
> 
> * Fastest: 255.4MiB/s, 25.54 obj/s
> * 50% Median: 206.1MiB/s, 20.61 obj/s
> * Slowest: 157.6MiB/s, 15.76 obj/s

Yeah I don't think this warrants, an intricate change. Make sure to run real workload and verify content as well that is uploaded.

Look at mint tests from project https://github.com/minio/mint

2021-05-18 07:45 UTC, aead commented on cmd/streaming-signature-v4.go
> +	internalBuf := cap(buf) < size
```suggestion
	internalBuf := len(buf) < size
```

We have to check the length of the caller-provided buffer - not its capacity.
The caller will only consume (at most) `len(buf)` bytes.

2021-05-18 07:52 UTC, aead commented
Just FWIW: This is a very dangerous optimisation. We have to make sure that we *never* return unverified content to the caller. Keep in mind that any data we read from the underlying connection may not be authentic (including the chunk/segment size).

We have to read in specific loop:
 1. Read from the underlying connection
 2. Parse required fields (size, delimiters a.s.o)
 3. Verify signature
 4. Return data to client

We *must never* return any data to the caller without doing 3. Therefore, we have to read a *complete* chunk / segment from the underling connection *before* returning the first byte of that chunk to the caller. Otherwise, we accept unauthentic / modified data.

2021-05-18 10:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :x: [more...](#d2e11c7a-382d-40b9-8a08-fb7aa9bd502c) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#64f91d1c-782a-4130-9bd0-3480e20a62e0) |
<a name="64f91d1c-782a-4130-9bd0-3480e20a62e0"></a>
### 12301-a3a97f7/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32151
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c112f26c4d21:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 2779,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32151 s3api copy-object --bucket awscli-mint-test-bucket-25881 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-25881/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 084e1383b70fb0c51acc680fef370023, got ac57de7156d7fc25ac1a65f81fa3989b"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 47 seconds
(7/15) Running minio-dotnet tests ... done in 33 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 59 seconds
{
  "args": {},
  "duration": 243,
  "error": "At least one of the pre-conditions you specified did not hold",
  "function": "CopyObjectPart(destination, source)",
  "message": "CopyObjectPart call failed",
  "name": "minio-go: testUnencryptedToSSES3CopyObjectPart",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 1 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "copyObject()",
  "args": "[match etag]",
  "duration": 207,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = PreconditionFailed, message = At least one of the pre-conditions you specified did not hold, bucketName = minio-java-test-3irpgtk, objectName = minio-java-test-9q2i27-copy, resource = /minio-java-test-3irpgtk/minio-java-test-9q2i27-copy, requestId = 168020AC4609ABFC, hostId = 8cc0d934-45f1-43ec-bee7-11f581a5bb5e)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32151/minio-java-test-3irpgtk/minio-java-test-9q2i27-copy, headers=x-amz-copy-source-if-match: 71cff0a060f852067e443ad1e24ae26c-1\nx-amz-copy-source: /minio-java-test-1b0ovnr/minio-java-test-9q2i27\nHost: minio-dev7.minio.io:32151\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210518T095630Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210518/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=412, headers=Accept-Ranges: bytes\nContent-Length: 416\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nETag: \"71cff0a060f852067e443ad1e24ae26c\"\nLast-Modified: Tue, 18 May 2021 09:56:30 GMT\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 168020AC4609ABFC\nX-Xss-Protection: 1; mode=block\nDate: Tue, 18 May 2021 09:56:30 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.execute(MinioClient.java:563), io.minio.MinioClient.executePut(MinioClient.java:904), io.minio.MinioClient.copyObject(MinioClient.java:1232), FunctionalTest.testCopyObjectMatchETag(FunctionalTest.java:1850), FunctionalTest.copyObject(FunctionalTest.java:2016), FunctionalTest.runObjectTests(FunctionalTest.java:3757), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(8/15) Running minio-js tests ... done in 57 seconds
(9/15) Running minio-py tests ... done in 2 minutes and 29 seconds
(10/15) Running s3cmd tests ... FAILED in 4 seconds
{
  "name": "s3cmd",
  "duration": "2453",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums don't match!\nWARNING: Too many failures. Giving up on '/mint/data/datafile-65-MB'\nERROR: \nUpload of '/mint/data/datafile-65-MB' part 1 failed. Use\n  /usr/local/bin/s3cmd abortmp s3://s3cmd-test-bucket-32376/s3cmd-test-object-12567 2255c9d2-0a9c-4dbf-b562-bef239925e34\nto abort the upload, or\n  /usr/local/bin/s3cmd --upload-id 2255c9d2-0a9c-4dbf-b562-bef239925e34 put ...\nto continue the upload.\nERROR: Upload of '/mint/data/datafile-65-MB' failed too many times (Last reason: )"
}
(10/15) Running s3select tests ... done in 5 seconds
(11/15) Running security tests ... done in 0 seconds

Executed 11 out of 15 tests successfully.
```
<a name="d2e11c7a-382d-40b9-8a08-fb7aa9bd502c"></a>
### 12301-a3a97f7/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32530
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 435ea9937745:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 15 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 6 seconds
(8/15) Running minio-dotnet tests ... done in 39 seconds
(9/15) Running minio-go tests ... done in 2 minutes and 2 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 15 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... FAILED in 2 minutes and 28 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-90711398-826f-47de-98c1-eed8fbec5a8c",
    "object_name": "f872b77b-0f50-41ff-bcca-490e4407174a"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-90711398-826f-47de-98c1-eed8fbec5a8c, request_id: 168020F730275CF3, host_id: f1c9df61-8f68-4cc7-b6ed-a8f23d2e8880, bucket_name: minio-py-test-90711398-826f-47de-98c1-eed8fbec5a8c",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1640, in test_thread_safe\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 676, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 409, in _execute\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 385, in _url_open\n    raise response_error\nminio.error.S [...]

2021-05-18 14:24 UTC, harshavardhana commented
> Just FWIW: This is a very dangerous optimisation. We have to make sure that we _never_ return unverified content to the caller. Keep in mind that any data we read from the underlying connection may not be authentic (including the chunk/segment size).
> 
> We have to read in specific loop:
> 
> 1. Read from the underlying connection
> 2. Parse required fields (size, delimiters a.s.o)
> 3. Verify signature
> 4. Return data to client
> 
> We _must never_ return any data to the caller without doing 3. Therefore, we have to read a _complete_ chunk / segment from the underling connection _before_ returning the first byte of that chunk to the caller. Otherwise, we accept unauthentic / modified data.

Yeah agreed if there are security implications we should avoid this PR.

2021-05-18 16:02 UTC, klauspost commented
@aead @harshavardhana I am not sure the potential improvements are worth it, and you are right it is a non-trivial change in the sense that there were 2 subtle bugs that was really hard to find for @aead and me. However, in terms of security this provides the same level as before AFAICT.

I think the numbers pretty much reflect what we can expect. Not sure this is worth it for an ~3% gain. Approving it and leaving the decision to you.

2021-05-18 16:02 UTC, klauspost approved these changes

2021-05-18 16:07 UTC, kaplanlior commented
Thanks @klauspost for the approval and feedback. It's a pleasure getting fast responses on this PR.

2021-05-18 19:42 UTC, harshavardhana commented
> @aead @harshavardhana I am not sure the potential improvements are worth it, and you are right it is a non-trivial change in the sense that there were 2 subtle bugs that were really hard to find for @aead and me. However, in terms of security this provides the same level as before AFAICT.
> 
> I think the numbers pretty much reflect what we can expect. Not sure this is worth it for an ~3% gain. Approving it and leaving the decision to you.

I am not okay with making changes in the incoming stream that has a direct impact on writing and corruption. @kaplanlior sorry we will have to stage this for later and do some more thorough testing - the chunked reader is tricky and lack of spec from AWS S3 makes it even harder on what needs to be done here. 

We really need to see some `go test -bench .`  results as well - a tiny improvement won't be noticeable over the network since disk and network become the bottleneck - the latency of I/O is much higher compared to tiny allocation latency hit here. 

To clearly see the benefits we would need to see `go test -bench .` results.

2021-05-26 05:08 UTC, kaplanlior commented
## Before
```
goos: linux
goarch: amd64
pkg: github.com/minio/minio/cmd
cpu: DO-Premium-AMD
BenchmarkChunkReader
BenchmarkChunkReader/benchmarking_chunk_reader_10mb
BenchmarkChunkReader/benchmarking_chunk_reader_10mb-4                  1        5104228091 ns/op        1472968616 B/op16712158 allocs/op
BenchmarkChunkReader/benchmarking_chunk_reader_80mb
BenchmarkChunkReader/benchmarking_chunk_reader_80mb-4                  1        4915628543 ns/op        1472968480 B/op16712154 allocs/op
```
## After
```
goos: linux
goarch: amd64
pkg: github.com/minio/minio/cmd
cpu: DO-Premium-AMD
BenchmarkChunkReader
BenchmarkChunkReader/benchmarking_chunk_reader_10mb
BenchmarkChunkReader/benchmarking_chunk_reader_10mb-4                  1        4455736412 ns/op        1472968056 B/op16712151 allocs/op
BenchmarkChunkReader/benchmarking_chunk_reader_80mb
BenchmarkChunkReader/benchmarking_chunk_reader_80mb-4                  1        4433445763 ns/op        1472969008 B/op16712161 allocs/op
```

2021-05-26 07:24 UTC, klauspost commented
@kaplanlior Those alloc numbers seem excessive. Could you share the benchmark code, maybe add it to the PR?

2021-06-07 16:01 UTC, harshavardhana commented
> @kaplanlior Those alloc numbers seem excessive (and are the same, say a few bytes) . Could you share the benchmark code, maybe add it to the PR?

Closing this as a stale PR, please share this when you have time we can re-look at this later.

2021-06-07 16:01 UTC, closed without merging