rest: healthcheck should not update failure metrics
minio/minio pull request #12458
Opened 2021-06-07 13:43 UTC by vadmeste

## Description
healthcheck should not update failure metrics, otherwise, we can see high numbers
of networking issues when a node is down.

## Motivation and Context
Avoid high number of minio_inter_node_traffic_errors_total metric

## How to test this PR?
1. Run four nodes with MINIO_PROMETHEUS_AUTH_TYPE="public"
2. Kill one node and get prometheus output:
`curl http://localhost:9001/minio/v2/metrics/node 2>/dev/null | grep minio_inter_node_traffic_errors_total`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-06-07 14:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#c1f7d18e-ada5-4127-b626-9988a656a359) |
<a name="c1f7d18e-ada5-4127-b626-9988a656a359"></a>
### 12458-8e18b9a/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32426
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dde7f8b4b810:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 56 seconds
(8/15) Running minio-dotnet tests ... done in 53 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 59 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[single source with offset]",
  "duration": 26,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Range specified is not valid for source object, bucketName = minio-java-test-2ckman, objectName = minio-java-test-8fc1f0, resource = /minio-java-test-2ckman/minio-java-test-8fc1f0, requestId = 1686516F86615244, hostId = f3e976d1-29dd-4c95-a93f-c6053f67a877)\nrequest={method=PUT, url=http://minio-dev7.minio.io:32426/minio-java-test-2ckman/minio-java-test-8fc1f0?uploadId=4b9d231c-8fd2-4b96-833e-e8b5760c499c&partNumber=1, headers=x-amz-copy-source: /minio-java-test-2ckman/minio-java-test-lcmo9i\nx-amz-copy-source-range: bytes=2048-1048575\nx-amz-copy-source-if-match: cb92d17a904ccec2e6e23b8bb66245fb\nHost: minio-dev7.minio.io:32426\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.0.3\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210607T135735Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210607/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-copy-source-range;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 386\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 1686516F86615244\nX-Xss-Protection: 1; mode=block\nDate: Mon, 07 Jun 2021 13:57:35 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:775), io.minio.MinioClient.uploadPartCopy(MinioClient.java:4804), io.minio.MinioClient.composeObject(MinioClient.java:1431), FunctionalTest.testComposeObject(FunctionalTest.java:2120), FunctionalTest.composeObjectTests(FunctionalTest.java:2145), FunctionalTest.composeObject(FunctionalTest.java:2300), FunctionalTest.runObjectTests(FunctionalTest.java:3758), FunctionalTest.runTests(FunctionalTest.java:3783), FunctionalTest.main(FunctionalTest.java:3927)]"
}
(10/15) Running minio-js tests ... done in 50 seconds
(11/15) Running minio-py tests ... done in 2 minutes and 42 seconds
(12/15) Running s3cmd tests ... done in 18 seconds
(13/15) Running s3select tests ... done in 6 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-06-07 14:26 UTC, harshavardhana requested changes
why not enhance this function

```
		respBody, err := healthClient.Call(ctx, lockRESTMethodHealth, nil, nil, -1)
```

to take in an input function that updates metrics?

2021-06-07 15:45 UTC, harshavardhana requested changes
Actually, this PR is fine with the boolean, just some redundant checks can be removed.

2021-06-07 15:45 UTC, harshavardhana commented on internal/rest/client.go
> +				if c.HealthCheckFn != nil {
MarkOffline already checks for `HealthCheckfn` @vadmeste

2021-06-08 20:07 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-06-08 21:09 UTC, harshavardhana approved these changes

2021-06-08 21:09 UTC, merged