Change replication to use read lock instead of writelock
minio/minio pull request #12581
Opened 2021-06-26 00:46 UTC by poornas

Fixes #12573

This PR also adding audit logging for replication activity

## Description

## Motivation and Context
Currently replication holds a write lock for the duration of the transaction - this is unnecessary and can cause reads/stats to block until the write lock is released. Integrity of the transaction is guaranteed by the immutability of the object version.

Also adding audit logging for internal replication activity.
## How to test this PR?
See repro in referenced issue

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-06-26 00:55 UTC, harshavardhana requested changes

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +		Trigger:   "replication-process",
```suggestion
		Trigger:   "replication:incoming",
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +		APIName:   "replicateObject",
```suggestion
		APIName:   "s3:ReplicateObject",
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
>  				poolIdx, err := z.getPoolIdx(ctx, bucket, object, objInfo.Size)
No reason to use `getPoolIdx()` @poornas you can simply remove the entire reflection code and directly called `PutObjectMetadata()`

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +							APIName:   "replicateObject",
needs the same changes as above..

2021-06-26 00:55 UTC, harshavardhana commented on cmd/data-scanner.go
> +		APIName: "DeleteObject",
```suggestion
		APIName: "s3:ExpireObject",
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +			APIName:   "replicateObject",
```suggestion
			APIName:   "s3:ReplicateObject",
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/data-scanner.go
> +		Trigger: "internal-scanner",
```suggestion
		Trigger: "ilm",
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +		qname = "replication-healing"
all these strings should be constants @poornas

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +		qname = "replication-healing"
```suggestion
		qname = "replication:heal"
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +		qname = "replication-existing-queue"
```suggestion
		qname = "replication:existing"
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +	qname := "replication-queue"
```suggestion
	qname := "replication:incoming"
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +			Trigger:   "replication-mrf-queue",
```suggestion
			Trigger:   "replication:mrf",
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +					Trigger:   "replication-process",
```suggestion
					Trigger:   "replication:incoming",
```

2021-06-26 00:55 UTC, harshavardhana commented on cmd/bucket-replication.go
> +			APIName:   "replicateDelete",
```suggestion
			APIName:   "s3:ReplicateDelete",
```

2021-06-26 00:56 UTC, harshavardhana commented
The reason I chose this `<sub-system>:[optional_location]` is to ensure that we follow S3 style strings in our audit formats, this would keep it easier to inter-operate between event targets as well as audit targets.  Nomenclature is already standardized lets not add our own newer meanings and try to keep it simpler.

2021-06-26 01:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-06-26 02:59 UTC, harshavardhana requested changes

2021-06-26 02:59 UTC, harshavardhana commented on cmd/data-scanner.go
> +		Trigger: "internal-scanner",
This can be `ilm:expiry` and transition can have `ilm:transition` instead of `internal-scanner`

2021-06-26 03:14 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-06-28 08:12 UTC, klauspost approved these changes
Nice. Even reduces complexity 👍🏼

2021-06-28 08:13 UTC, klauspost commented
```
cmd/bucket-replication.go:874:2: exported: exported const ReplicationQueuedActivity should have comment (or a comment on this block) or be unexported (revive)
	ReplicationQueuedActivity         = "replication:queue"
	^
```

2021-06-28 17:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-06-28 20:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-06-28 20:43 UTC, harshavardhana approved these changes

2021-06-29 06:58 UTC, merged

2021-06-29 07:13 UTC, hkirov commented
Thanks.