feat: Implement listing version 3.0
minio/minio pull request #12605
Opened 2021-06-30 14:34 UTC by klauspost

## Description

[design document](https://gist.github.com/klauspost/410fad038bc60b40700b3499a3c45363)

## Motivation and Context

See design doc above

## How to test this PR?

Start server, perform listing operations.

https://github.com/minio/mint/pull/327 required for mint.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)

## Checklist:
- [x] Unit tests added/updated

2021-06-30 14:54 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#779a4295-5346-482c-8d41-3cd4238b7da4) |
| mint-gateway-s3.sh | :x: [more...](#4af99818-0df9-40f8-92bf-268285c94079) |
| mint-erasure.sh | :x: [more...](#b2b37309-4d93-4fc8-b836-537abab586f5) |
| mint-dist-erasure.sh | :x: [more...](#085e648f-67c8-4112-93c8-87514ea33b2c) |
| mint-zoned.sh | :x: [more...](#c87fe0a6-3b83-4a1a-8827-e277afe579f0) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#f84e396c-14d7-4fda-b4e5-e95e74ee7823) |
<a name="779a4295-5346-482c-8d41-3cd4238b7da4"></a>
### 12605-6225012/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:31229
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 2 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 2 minutes and 0 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 33 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 54 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 10 seconds
(11/16) Running minio-js tests ... done in 50 seconds
(12/16) Running minio-py tests ... done in 1 minutes and 59 seconds
(13/16) Running s3cmd tests ... done in 25 seconds
(14/16) Running s3select tests ... done in 5 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 8 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-z69s36wupgjaj9",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 5871,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="4af99818-0df9-40f8-92bf-268285c94079"></a>
### 12605-6225012/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:31450
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 2 seconds
(5/16) Running awscli tests ... done in 1 minutes and 55 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 18 seconds
(8/16) Running minio-dotnet tests ... done in 28 seconds
(9/16) Running minio-go tests ... done in 43 seconds
(10/16) Running minio-java tests ... FAILED in 16 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 14145,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = XMinioBackendDown, message = Object storage backend is unreachable, bucketName = minio-java-test-16pdhoo, objectName = null, resource = /minio-java-test-16pdhoo, requestId = 168D6378BA6C9D40, hostId = 8f37266a-0caa-49e7-ad51-8eea141cdc46)\nrequest={method=GET, url=http://minio-k8s7:31450/minio-java-test-16pdhoo?list-type=2&prefix=minio&continuation-token=YldsdWFXOHRhbUYyWVMxMFpYTjBMWEJ2T0dOaVpGdHRhVzVwYjE5allXTm9aVHAyTWl4eVpYUjFjbTQ2WFE9PQ%3D%3D&max-keys=1000&encoding-type=url&delimiter=, headers=Host: minio-k8s7:31450\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.2.1\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210630T144650Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210630/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 325\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 168D6378BA6C9D40\nX-Xss-Protection: 1; mode=block\nDate: Wed, 30 Jun 2021 14:46:50 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:667), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 37 seconds
(11/16) Running minio-py tests ... FAILED in 1 minutes and 4 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-9e821c58-a1e4-4a3b-93a6-4e93728b35de",
    "object_name": "7984190e-e2ad-4d43-acf6-95cee3256347_0 ~ 7984190e-e2ad-4d43-acf6-95cee3256347_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s7', port=31450): Max retries exceeded with url: /minio-py-test-9e821c58-a1e4-4a3b-93a6-4e93728b35de?continuation-token=TnprNE5ERTVNR1V0WlRKaFpDMDBaRFF6TFdGalpqWXRPVFZqWldVek1qVTJNelEzWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=TnprNE5ERTVNR1V0WlRKaFpDMDBaRFF6TFdGalpqWXRPVFZqWldVek1qVTJNelEzWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 836, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPC [...]

2021-06-30 15:56 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#fde1a275-8e8e-46e7-9ea6-5ecc17efc314) |
| mint-gateway-s3.sh | :x: [more...](#c6526aa0-7590-46dc-81c6-1285dec9a645) |
| mint-erasure.sh | :x: [more...](#6bebbde5-67a3-4121-9ca1-13baa438a34a) |
| mint-dist-erasure.sh | :x: [more...](#4493738c-14e2-465d-97ad-95d4e7496bb0) |
| mint-zoned.sh | :x: [more...](#bc544f62-f6ca-4ad4-b546-493868505572) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#2f7fa482-d67b-419f-ad30-e2ceb0d1b208) |
<a name="2f7fa482-d67b-419f-ad30-e2ceb0d1b208"></a>
### 12605-4a2b0b2/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:30569
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 2 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 2 minutes and 2 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 43 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 33 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 14 seconds
(11/16) Running minio-js tests ... done in 51 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 8 seconds
(13/16) Running s3cmd tests ... done in 36 seconds
(14/16) Running s3select tests ... done in 4 seconds
(15/16) Running security tests ... done in 1 seconds
(16/16) Running versioning tests ... FAILED in 8 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-ppbkpj6v4kuauk",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 5912,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="6bebbde5-67a3-4121-9ca1-13baa438a34a"></a>
### 12605-4a2b0b2/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:30992
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 2 seconds
(5/16) Running awscli tests ... done in 1 minutes and 56 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 22 seconds
(8/16) Running minio-dotnet tests ... done in 40 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 24 seconds
(10/16) Running minio-java tests ... FAILED in 11 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7388,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s2:30992/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 49 seconds
(11/16) Running minio-py tests ... FAILED in 56 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-b9878119-1767-4051-8e08-61adc3fa599f",
    "object_name": "e75cf1d0-c4af-4d05-b17e-28f146ce5183_0 ~ e75cf1d0-c4af-4d05-b17e-28f146ce5183_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s2', port=30992): Max retries exceeded with url: /minio-py-test-b9878119-1767-4051-8e08-61adc3fa599f?continuation-token=ZTc1Y2YxZDAtYzRhZi00ZDA1LWIxN2UtMjhmMTQ2Y2U1MTgzXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=ZTc1Y2YxZDAtYzRhZi00ZDA1LWIxN2UtMjhmMTQ2Y2U1MTgzXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content= [...]

2021-06-30 16:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f9d21e8b-71aa-47e1-8273-d1b8a94fc5d8) |
| mint-gateway-s3.sh | :x: [more...](#4e5b80ee-8915-48c7-ab65-186b4a07bab3) |
| mint-erasure.sh | :x: [more...](#e3a4bf7f-e7b3-4e35-a5f4-26ecc41526d0) |
| mint-dist-erasure.sh | :x: [more...](#8c7f6c70-5a0f-491b-ac08-27e27db6a021) |
| mint-zoned.sh | :x: [more...](#cff1c2b4-49f9-4ca6-9b90-3f78579517e7) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#df90a1e1-1524-421d-993e-a2c0896e87e7) |
<a name="cff1c2b4-49f9-4ca6-9b90-3f78579517e7"></a>
### 12605-f9444c0/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:30183
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 2 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 59 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 27 seconds
(8/16) Running minio-dotnet tests ... done in 35 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 52 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 39 seconds
(11/16) Running minio-js tests ... done in 50 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 11 seconds
(13/16) Running s3cmd tests ... done in 37 seconds
(14/16) Running s3select tests ... done in 5 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 9 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-ekyhi2rsi9uxg2",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 5904,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="f9d21e8b-71aa-47e1-8273-d1b8a94fc5d8"></a>
### 12605-f9444c0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:32294
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 59 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 27 seconds
(8/16) Running minio-dotnet tests ... done in 33 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 42 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 11 seconds
(11/16) Running minio-js tests ... done in 51 seconds
(12/16) Running minio-py tests ... done in 1 minutes and 55 seconds
(13/16) Running s3cmd tests ... done in 26 seconds
(14/16) Running s3select tests ... done in 4 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 9 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-b3juru6xyntrm4",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 5918,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="df90a1e1-1524-421d-993e-a2c0896e87e7"></a>
### 12605-f9444c0/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:30398
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 2 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 58 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 34 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 44 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 21 seconds
(11/16) Running minio-js tests ... done in 51 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 12 seconds
(13/16) Running s3cmd tests ... done in 25 seconds
(14/16) Running s3select tests ... done in 5 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 8 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-p5bdrcqtrs4dkb",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 5944,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="8c7f6c70-5a0f-491b-ac08-27e27db6a021"></a>
### 12605-f9444c0/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:30033
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 58 seconds
(6/16) Running healthcheck tests ... done in 1 seconds
(7/16) Running mc tests ... done in 25 seconds
(8/16) Running minio-dotnet tests ... done in 52 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 59 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 1 seconds
(11/16) Running minio-js tests ... done in 50 seconds
(12/16) Running minio-py tests ... done in 1 minutes and 50 seconds
(13/16) Running s3cmd tests ... done in 26 seconds
(14/16) Running s3select tests ... done in 4 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 8 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-ddu6biumi5cjrb",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 5834,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="e3a4bf7f-e7b3-4e35-a5f4-26ecc41526d0"></a>
### 12605-f9444c0/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:31310
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws- [...]

2021-06-30 17:00 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3deadf78-b588-44c3-9392-17b94ff8b913) |
| mint-gateway-s3.sh | :x: [more...](#e69fa962-9487-4675-88e1-9cc1518c0ac5) |
| mint-erasure.sh | :x: [more...](#2f43a90e-67cb-46bf-8997-85fe325e664e) |
| mint-dist-erasure.sh | :x: [more...](#a0b5799f-23a1-4b01-ba1c-fade8ec3de54) |
| mint-zoned.sh | :x: [more...](#3a7991a2-8730-4294-85fc-cc1a15b29a5d) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#af3b3ae5-2dda-40bd-82a2-7605981caf24) |
<a name="a0b5799f-23a1-4b01-ba1c-fade8ec3de54"></a>
### 12605-5c57098/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:31265
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 58 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 32 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 48 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 2 seconds
(11/16) Running minio-js tests ... done in 50 seconds
(12/16) Running minio-py tests ... done in 1 minutes and 47 seconds
(13/16) Running s3cmd tests ... done in 24 seconds
(14/16) Running s3select tests ... done in 4 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 9 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-bcmdlnc1pxjxq4",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 5834,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="2f43a90e-67cb-46bf-8997-85fe325e664e"></a>
### 12605-5c57098/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:30832
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 2 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 2 seconds
(5/16) Running awscli tests ... done in 1 minutes and 54 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 29 seconds
(8/16) Running minio-dotnet tests ... done in 27 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 40 seconds
(10/16) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7560,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s8:30832/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 50 seconds
(11/16) Running minio-py tests ... FAILED in 56 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-52501f71-c6da-46c1-856a-466febe061c3",
    "object_name": "bab3226e-d493-4f7d-8628-bf24a9e220e2_0 ~ bab3226e-d493-4f7d-8628-bf24a9e220e2_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s8', port=30832): Max retries exceeded with url: /minio-py-test-52501f71-c6da-46c1-856a-466febe061c3?continuation-token=YmFiMzIyNmUtZDQ5My00ZjdkLTg2MjgtYmYyNGE5ZTIyMGUyXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=YmFiMzIyNmUtZDQ5My00ZjdkLTg2MjgtYmYyNGE5ZTIyMGUyXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content, [...]

2021-07-01 14:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3dfd66ad-0eda-41b6-9e2d-bab0430ff9a3) |
| mint-gateway-s3.sh | :x: [more...](#5da6ebd1-8279-4c09-b224-70b9cfbf82ab) |
| mint-erasure.sh | :x: [more...](#bd88944e-3f0d-44d9-9f81-f5b62e7a9ef3) |
| mint-dist-erasure.sh | :x: [more...](#59f109b6-d6ce-4f8d-82ac-a661a40da7a1) |
| mint-zoned.sh | :x: [more...](#9c9ad0da-a374-4078-a98d-99d4226c1b40) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#aa630579-54bb-4f71-a3e7-e57041247c34) |
<a name="bd88944e-3f0d-44d9-9f81-f5b62e7a9ef3"></a>
### 12605-94787cf/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:32714
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 2 seconds
(5/16) Running awscli tests ... done in 1 minutes and 56 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 20 seconds
(8/16) Running minio-dotnet tests ... done in 46 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 34 seconds
(10/16) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7115,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s8:32714/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 48 seconds
(11/16) Running minio-py tests ... FAILED in 56 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-67489cfe-b1af-4497-8818-68522aebe2ef",
    "object_name": "ab5e513c-fd1c-4135-a854-b65a11213174_0 ~ ab5e513c-fd1c-4135-a854-b65a11213174_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s8', port=32714): Max retries exceeded with url: /minio-py-test-67489cfe-b1af-4497-8818-68522aebe2ef?continuation-token=YWI1ZTUxM2MtZmQxYy00MTM1LWE4NTQtYjY1YTExMjEzMTc0XzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=YWI1ZTUxM2MtZmQxYy00MTM1LWE4NTQtYjY1YTExMjEzMTc0XzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s8', port=32714): Max retries exceeded with url: /minio-py-test-67489cfe-b1af-4497-8818-68522aebe2ef?continuation-token=YWI1ZTUxM2MtZmQxYy00MTM1LWE4NTQtYjY1YTExMjEzMTc0XzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=YWI1ZTUxM2MtZmQxYy00MTM1LWE4NTQtYjY1YTExMjEzMTc0XzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "duration": 29994
}
(11/16) Running s3cmd tests ... done in 34 seconds
(12/16) Running s3select tests ... done in 1 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning [...]

2021-07-01 16:44 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e2e44c24-40cf-42d2-85be-aa2c41171274) |
| mint-gateway-s3.sh | :x: [more...](#f1ebb406-03c5-46cb-8a35-9da408d70962) |
| mint-erasure.sh | :x: [more...](#89ac1fbd-eb53-42c3-8298-8b648ce70a95) |
| mint-dist-erasure.sh | :x: [more...](#3a812994-f057-44e5-a565-07586df1d7f0) |
| mint-zoned.sh | :x: [more...](#26c0269c-e304-47e8-9d73-4a6dbc00ec65) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#ccf8e061-7f05-49ad-ad22-0adb05ef7b6a) |
<a name="89ac1fbd-eb53-42c3-8298-8b648ce70a95"></a>
### 12605-656e253/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:30198
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 58 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 33 seconds
(8/16) Running minio-dotnet tests ... done in 36 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 22 seconds
(10/16) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7163,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s2:30198/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 49 seconds
(11/16) Running minio-py tests ... FAILED in 55 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-25a5c3dc-db37-4119-98df-eeea677e0c53",
    "object_name": "9e01d183-642f-4627-8f04-f2e3c39ac04f_0 ~ 9e01d183-642f-4627-8f04-f2e3c39ac04f_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s2', port=30198): Max retries exceeded with url: /minio-py-test-25a5c3dc-db37-4119-98df-eeea677e0c53?continuation-token=OWUwMWQxODMtNjQyZi00NjI3LThmMDQtZjJlM2MzOWFjMDRmXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=OWUwMWQxODMtNjQyZi00NjI3LThmMDQtZjJlM2MzOWFjMDRmXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s2', port=30198): Max retries exceeded with url: /minio-py-test-25a5c3dc-db37-4119-98df-eeea677e0c53?continuation-token=OWUwMWQxODMtNjQyZi00NjI3LThmMDQtZjJlM2MzOWFjMDRmXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=OWUwMWQxODMtNjQyZi00NjI3LThmMDQtZjJlM2MzOWFjMDRmXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "duration": 30143
}
(11/16) Running s3cmd tests ... done in 34 seconds
(12/16) Running s3select tests ... done in 2 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning [...]

2021-07-01 17:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#34bdb94c-e538-4316-af18-3f800a77e3a3) |
| mint-gateway-s3.sh | :x: [more...](#db18b91a-78d8-41f7-aee2-f645d6dc5505) |
| mint-erasure.sh | :x: [more...](#67ce9487-8814-4725-988c-43b2b6936dd2) |
| mint-dist-erasure.sh | :x: [more...](#38150ed3-53e9-45a1-88ab-58f88e989500) |
| mint-zoned.sh | :x: [more...](#8c927b65-6a9f-41e5-a01e-c2e21b45a33b) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#c1980484-7e2d-4cdc-b2a0-13b1d984018a) |
<a name="c1980484-7e2d-4cdc-b2a0-13b1d984018a"></a>
### 12605-66d2aaf/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:31445
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 59 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 24 seconds
(8/16) Running minio-dotnet tests ... done in 38 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 44 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 12 seconds
(11/16) Running minio-js tests ... done in 52 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 3 seconds
(13/16) Running s3cmd tests ... done in 36 seconds
(14/16) Running s3select tests ... done in 5 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-niwmz9kmvuwxzp",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 404,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="8c927b65-6a9f-41e5-a01e-c2e21b45a33b"></a>
### 12605-66d2aaf/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:32440
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 2 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 58 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 35 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 48 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 32 seconds
(11/16) Running minio-js tests ... done in 51 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 3 seconds
(13/16) Running s3cmd tests ... done in 26 seconds
(14/16) Running s3select tests ... done in 6 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-j1k6cxkitsbbuk",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 395,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="38150ed3-53e9-45a1-88ab-58f88e989500"></a>
### 12605-66d2aaf/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:31926
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 58 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 29 seconds
(8/16) Running minio-dotnet tests ... done in 33 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 35 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 0 seconds
(11/16) Running minio-js tests ... done in 51 seconds
(12/16) Running minio-py tests ... done in 1 minutes and 45 seconds
(13/16) Running s3cmd tests ... done in 26 seconds
(14/16) Running s3select tests ... done in 4 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-d1ef3fduxf04uo",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 313,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="db18b91a-78d8-41f7-aee2-f645d6dc5505"></a>
### 12605-66d2aaf/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:32622
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 54 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 21 seconds
(8/16) Running minio-dotnet tests ... done in 28 seconds
(9/16) Running minio-go tests ... done in 45 seconds
(10/16) Running minio-java tests ... FAILED in 17 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 14590,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = XMinioBackendDown, message = Object storage backend is unreachable, bucketName = minio-java-test-1psejep, objectName = null, resource = /minio-java-test-1psejep, requestId = 168DB916768BC076, hostId = 362bb685-8712-41dc-906c-d3881a3d7557)\nrequest={method=GET, url=http://minio-k8s3:32622/minio-java-test-1psejep?list-type=2&prefix=minio&continuation-token=YldsdWFXOHRhbUYyWVMxMFpYTjBMWEJ2WjNZM1lWdHRhVzVwYjE5allXTm9aVHAyTWl4eVpYUjFjbTQ2WFE9PQ%3D%3D&max-keys=1000&encoding-type=url&delimiter=, headers=Host: minio-k8s3:32622\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.2.1\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210701T165546Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210701/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nCon [...]

2021-07-02 08:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b72af16b-cd8d-425f-a8a8-8f83441520de) |
| mint-gateway-s3.sh | :x: [more...](#9befb075-4dab-4fbe-aa1b-5665abacf6c7) |
| mint-erasure.sh | :x: [more...](#4b6a7cee-65a9-4eda-b44b-83c61446b7cb) |
| mint-dist-erasure.sh | :x: [more...](#1f4f573e-dbb7-4d71-a8e0-faf112652357) |
| mint-zoned.sh | :x: [more...](#ea122eef-b527-4002-8dbe-d7807827fe3a) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#9d1d19e0-7ee5-42ec-89e0-8a7d74e54a54) |
<a name="4b6a7cee-65a9-4eda-b44b-83c61446b7cb"></a>
### 12605-f160e05/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:32248
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 56 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 20 seconds
(8/16) Running minio-dotnet tests ... done in 36 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 45 seconds
(10/16) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7394,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s7:32248/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 48 seconds
(11/16) Running minio-py tests ... FAILED in 57 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-7ab43e62-6b91-4fdc-b9d2-f5013f1bf99f",
    "object_name": "11383f63-b025-44a3-8388-8043458ffc92_0 ~ 11383f63-b025-44a3-8388-8043458ffc92_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s7', port=32248): Max retries exceeded with url: /minio-py-test-7ab43e62-6b91-4fdc-b9d2-f5013f1bf99f?continuation-token=MTEzODNmNjMtYjAyNS00NGEzLTgzODgtODA0MzQ1OGZmYzkyXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=MTEzODNmNjMtYjAyNS00NGEzLTgzODgtODA0MzQ1OGZmYzkyXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s7', port=32248): Max retries exceeded with url: /minio-py-test-7ab43e62-6b91-4fdc-b9d2-f5013f1bf99f?continuation-token=MTEzODNmNjMtYjAyNS00NGEzLTgzODgtODA0MzQ1OGZmYzkyXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=MTEzODNmNjMtYjAyNS00NGEzLTgzODgtODA0MzQ1OGZmYzkyXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "duration": 31554
}
(11/16) Running s3cmd tests ... done in 24 seconds
(12/16) Running s3select tests ... done in 1 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning [...]

2021-07-02 09:10 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b2e90e0d-0f24-4096-bee4-6b288ae512be) |
| mint-gateway-s3.sh | :x: [more...](#62cbbf66-aebd-43d8-bf4e-d092062f43af) |
| mint-erasure.sh | :x: [more...](#69d9dfae-dfc9-4cc1-9ffd-94e469b308e1) |
| mint-dist-erasure.sh | :x: [more...](#05deb85d-cf26-4882-954f-85f9393c879b) |
| mint-zoned.sh | :x: [more...](#92dd13ed-20eb-4a13-a059-e55320f2849b) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#490e0ae0-cfb3-49ec-a09b-e4bc48390788) |
<a name="92dd13ed-20eb-4a13-a059-e55320f2849b"></a>
### 12605-ba7affb/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:32631
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 2 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 45 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 2 minutes and 2 seconds
(6/16) Running healthcheck tests ... done in 1 seconds
(7/16) Running mc tests ... done in 27 seconds
(8/16) Running minio-dotnet tests ... done in 36 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 49 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 40 seconds
(11/16) Running minio-js tests ... done in 53 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 12 seconds
(13/16) Running s3cmd tests ... done in 28 seconds
(14/16) Running s3select tests ... done in 5 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-cygj4bwr41zk4a",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 376,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="62cbbf66-aebd-43d8-bf4e-d092062f43af"></a>
### 12605-ba7affb/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:32760
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 42 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 55 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 21 seconds
(8/16) Running minio-dotnet tests ... done in 28 seconds
(9/16) Running minio-go tests ... done in 48 seconds
(10/16) Running minio-java tests ... FAILED in 16 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 14472,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = XMinioBackendDown, message = Object storage backend is unreachable, bucketName = minio-java-test-2pgdji, objectName = null, resource = /minio-java-test-2pgdji, requestId = 168DEDE96A3FD166, hostId = 0b597ea2-9ad6-4239-8bb7-274a26ba81f5)\nrequest={method=GET, url=http://minio-k8s5:32760/minio-java-test-2pgdji?list-type=2&prefix=minio&continuation-token=YldsdWFXOHRhbUYyWVMxMFpYTjBMWEJ3Y1hWa2JWdHRhVzVwYjE5allXTm9aVHAyTWl4eVpYUjFjbTQ2WFE9PQ%3D%3D&max-keys=1000&encoding-type=url&delimiter=, headers=Host: minio-k8s5:32760\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.2.1\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210702T090347Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210702/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 323\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 168DEDE96A3FD166\nX-Xss-Protection: 1; mode=block\nDate: Fri, 02 Jul 2021 09:03:47 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:667), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 37 seconds
(11/16) Running minio-py tests ... FAILED in 1 minutes and 2 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-0c11d1e8-2646-4feb-90e5-8c573c8553c3",
    "object_name": "ae1b884e-12d1-4ac9-9d0e-7e035a62f085_0 ~ ae1b884e-12d1-4ac9-9d0e-7e035a62f085_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s5', port=32760): Max retries exceeded with url: /minio-py-test-0c11d1e8-2646-4feb-90e5-8c573c8553c3?continuation-token=WVdVeFlqZzROR1V0TVRKa01TMDBZV001TFRsa01HVXROMlV3TXpWaE5qSm1NRGcxWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=WVdVeFlqZzROR1V0TVRKa01TMDBZV001TFRsa01HVXROMlV3TXpWaE5qSm1NRGcxWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 836, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPo [...]

2021-07-02 09:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#eb30ccbf-215e-42d4-9385-748a5b55bd21) |
| mint-gateway-s3.sh | :x: [more...](#6be82e72-3287-4300-8033-7887c9349ca8) |
| mint-erasure.sh | :x: [more...](#c615baac-1b3d-4ad7-b3e8-74952b928ddb) |
| mint-dist-erasure.sh | :x: [more...](#6a443774-0bbc-470b-9743-3e92e330433d) |
| mint-zoned.sh | :x: [more...](#83a197ed-d63f-4600-bf54-63fc08dd1bd4) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#27637747-94c9-40aa-bacc-0a983f1ee3c1) |
<a name="6be82e72-3287-4300-8033-7887c9349ca8"></a>
### 12605-91d8750/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:31338
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 2 seconds
(5/16) Running awscli tests ... done in 1 minutes and 54 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 24 seconds
(8/16) Running minio-dotnet tests ... done in 28 seconds
(9/16) Running minio-go tests ... done in 50 seconds
(10/16) Running minio-java tests ... FAILED in 16 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 14044,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = XMinioBackendDown, message = Object storage backend is unreachable, bucketName = minio-java-test-2eh4qik, objectName = null, resource = /minio-java-test-2eh4qik, requestId = 168DEEF2100FF72F, hostId = a988a1c9-9432-495b-9d2a-14bd5003693a)\nrequest={method=GET, url=http://minio-k8s4:31338/minio-java-test-2eh4qik?list-type=2&prefix=minio&continuation-token=YldsdWFXOHRhbUYyWVMxMFpYTjBMWEU1WVhKck0xdHRhVzVwYjE5allXTm9aVHAyTWl4eVpYUjFjbTQ2WFE9PQ%3D%3D&max-keys=1000&encoding-type=url&delimiter=, headers=Host: minio-k8s4:31338\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.2.1\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210702T092243Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210702/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 325\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 168DEEF2100FF72F\nX-Xss-Protection: 1; mode=block\nDate: Fri, 02 Jul 2021 09:22:44 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:667), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 36 seconds
(11/16) Running minio-py tests ... FAILED in 1 minutes and 4 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-ea2da40f-7ae7-4008-87d5-c6b7dd05629c",
    "object_name": "c7d0f3be-4073-4fd5-ac55-b9ebc528af4f_0 ~ c7d0f3be-4073-4fd5-ac55-b9ebc528af4f_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s4', port=31338): Max retries exceeded with url: /minio-py-test-ea2da40f-7ae7-4008-87d5-c6b7dd05629c?continuation-token=WXpka01HWXpZbVV0TkRBM015MDBabVExTFdGak5UVXRZamxsWW1NMU1qaGhaalJtWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=WXpka01HWXpZbVV0TkRBM015MDBabVExTFdGak5UVXRZamxsWW1NMU1qaGhaalJtWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 836, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s4', port=31338): Max retries exceeded with url: /minio-py-test-ea2da40f-7ae7-4008-87d5-c6b7dd05629c?continuation-token=WXpka01HWXpZbVV0TkRBM015MDBabVExTFdGak5UVXRZamxsWW1NMU1qaGhaalJtWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=WXpka01HWXpZbVV0TkRBM015MDBabVExTFdGak5UVXRZamxsWW1NMU1qaGhaalJtWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))\n",
  "duration": 45086
}
(11/16) Running s3cmd tests ... done in 1 minutes and 6 seconds
(12/16) Running s3select tests ... done in 2 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... done in 1 seconds

Executed 14 out of 16 tests successfully.
```
<a name="eb30ccbf-215e-42d4-9385-748a5b55bd21"></a>
### 12605-91d8750/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:30221
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 0 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 31 seconds
(8/16) Running minio-dotnet tests ... done in 34 seconds
(9/16) Running minio-go tests .. [...]

2021-07-02 11:16 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e9fa0c2a-6eb4-4993-8bf6-898a0624758c) |
| mint-gateway-s3.sh | :x: [more...](#8fca7636-f1ac-4dbc-be95-a63094c41989) |
| mint-erasure.sh | :x: [more...](#b5090912-7e4b-4114-b2a9-4b94ef2013b1) |
| mint-dist-erasure.sh | :x: [more...](#eb0426b8-0561-46ba-b542-a64b56b128a9) |
| mint-zoned.sh | :x: [more...](#7286283f-9a02-43df-81f0-d48d5c08e150) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#204aaa39-6c7a-4f74-b5b6-df8a212321a0) |
<a name="eb0426b8-0561-46ba-b542-a64b56b128a9"></a>
### 12605-6c423f3/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:32110
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 57 seconds
(6/16) Running healthcheck tests ... done in 1 seconds
(7/16) Running mc tests ... done in 25 seconds
(8/16) Running minio-dotnet tests ... done in 41 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 36 seconds
(10/16) Running minio-java tests ... done in 57 seconds
(11/16) Running minio-js tests ... done in 50 seconds
(12/16) Running minio-py tests ... done in 1 minutes and 54 seconds
(13/16) Running s3cmd tests ... done in 25 seconds
(14/16) Running s3select tests ... done in 4 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-x4zmxyo032zmn0",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 277,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="204aaa39-6c7a-4f74-b5b6-df8a212321a0"></a>
### 12605-6c423f3/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:32335
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 58 seconds
(6/16) Running healthcheck tests ... done in 1 seconds
(7/16) Running mc tests ... done in 24 seconds
(8/16) Running minio-dotnet tests ... done in 34 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 43 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 10 seconds
(11/16) Running minio-js tests ... done in 50 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 2 seconds
(13/16) Running s3cmd tests ... done in 23 seconds
(14/16) Running s3select tests ... done in 4 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-dxbc4vbjb9ueas",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 367,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="e9fa0c2a-6eb4-4993-8bf6-898a0624758c"></a>
### 12605-6c423f3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:32026
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 2 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 5 seconds
(5/16) Running awscli tests ... done in 1 minutes and 59 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 25 seconds
(8/16) Running minio-dotnet tests ... done in 43 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 50 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 3 seconds
(11/16) Running minio-js tests ... done in 52 seconds
(12/16) Running minio-py tests ... done in 1 minutes and 48 seconds
(13/16) Running s3cmd tests ... done in 24 seconds
(14/16) Running s3select tests ... done in 5 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-2akn62gstycghh",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 294,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="7286283f-9a02-43df-81f0-d48d5c08e150"></a>
### 12605-6c423f3/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:30884
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 46 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 1 minutes and 58 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 25 seconds
(8/16) Running minio-dotnet tests ... done in 46 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 57 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 36 seconds
(11/16) Running minio-js tests ... done in 51 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 9 seconds
(13/16) Running s3cmd tests ... done in 26 seconds
(14/16) Running s3select tests ... done in 5 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-iu9zvnlnf9xllu",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 387,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="b5090912-7e4b-4114-b2a9-4b94ef2013b1"></a>
### 12605-6c423f3/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:30468
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... don [...]

2021-07-02 13:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#27020a4a-c69b-4697-86ae-50e4a137a11c) |
| mint-gateway-s3.sh | :x: [more...](#a1e81ea4-699e-4967-abcc-825ef387602c) |
| mint-erasure.sh | :x: [more...](#b50abf82-9878-4cf9-8cae-cdc4ff5eb6d1) |
| mint-dist-erasure.sh | :x: [more...](#60e59862-6d2f-4be0-a8fd-4afa1b7b2bab) |
| mint-zoned.sh | :x: [more...](#b79c4b30-ea59-4c05-addf-4698ca033549) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#bcf8661f-9382-4eea-ad18-0a6f65a18cd5) |
<a name="b50abf82-9878-4cf9-8cae-cdc4ff5eb6d1"></a>
### 12605-cbe8d5e/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:31591
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 2 seconds
(5/16) Running awscli tests ... done in 1 minutes and 54 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 20 seconds
(8/16) Running minio-dotnet tests ... done in 27 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 22 seconds
(10/16) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7701,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s4:31591/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 50 seconds
(11/16) Running minio-py tests ... FAILED in 57 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-5f559201-b4b5-4a71-b021-5dac747d7b85",
    "object_name": "cfc8bf04-27bf-4fac-b3a0-0eb98b04734a_0 ~ cfc8bf04-27bf-4fac-b3a0-0eb98b04734a_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s4', port=31591): Max retries exceeded with url: /minio-py-test-5f559201-b4b5-4a71-b021-5dac747d7b85?continuation-token=Y2ZjOGJmMDQtMjdiZi00ZmFjLWIzYTAtMGViOThiMDQ3MzRhXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=Y2ZjOGJmMDQtMjdiZi00ZmFjLWIzYTAtMGViOThiMDQ3MzRhXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s4', port=31591): Max retries exceeded with url: /minio-py-test-5f559201-b4b5-4a71-b021-5dac747d7b85?continuation-token=Y2ZjOGJmMDQtMjdiZi00ZmFjLWIzYTAtMGViOThiMDQ3MzRhXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=Y2ZjOGJmMDQtMjdiZi00ZmFjLWIzYTAtMGViOThiMDQ3MzRhXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "duration": 30765
}
(11/16) Running s3cmd tests ... done in 34 seconds
(12/16) Running s3select tests ... done in 1 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning [...]

2021-07-02 16:11 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2df31ec8-cf7f-4f23-bfa5-497285643c9e) |
| mint-gateway-s3.sh | :x: [more...](#dd4a84e8-e726-4a3f-b75c-4e3c23d4619d) |
| mint-erasure.sh | :x: [more...](#045fc04a-3402-4c42-bbe7-3696fc86fb59) |
| mint-dist-erasure.sh | :x: [more...](#8ae96524-cfe8-4d9f-9ca3-ecec71959c12) |
| mint-zoned.sh | :x: [more...](#6db59c28-45a2-4a0c-b9f0-6bb187d41324) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#4be7145e-dc58-45b1-b2db-75c515e0ab49) |
<a name="dd4a84e8-e726-4a3f-b75c-4e3c23d4619d"></a>
### 12605-70f7f45/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:31794
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 56 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 20 seconds
(8/16) Running minio-dotnet tests ... done in 29 seconds
(9/16) Running minio-go tests ... done in 57 seconds
(10/16) Running minio-java tests ... FAILED in 16 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 14347,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = XMinioBackendDown, message = Object storage backend is unreachable, bucketName = minio-java-test-18tb0mp, objectName = null, resource = /minio-java-test-18tb0mp, requestId = 168E04908E8F8C52, hostId = f4cbee57-3e3a-496d-a05c-e19a75bb1c84)\nrequest={method=GET, url=http://minio-k8s3:31794/minio-java-test-18tb0mp?list-type=2&prefix=minio&continuation-token=YldsdWFXOHRhbUYyWVMxMFpYTjBMWEU1TkRZNE9GdHRhVzVwYjE5allXTm9aVHAyTWl4eVpYUjFjbTQ2WFE9PQ%3D%3D&max-keys=1000&encoding-type=url&delimiter=, headers=Host: minio-k8s3:31794\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.2.1\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210702T155854Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210702/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 325\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 168E04908E8F8C52\nX-Xss-Protection: 1; mode=block\nDate: Fri, 02 Jul 2021 15:58:54 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:667), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 38 seconds
(11/16) Running minio-py tests ... FAILED in 1 minutes and 4 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-6e566abb-2189-450d-9a23-38777c2eac11",
    "object_name": "8bd94100-f213-47a2-a614-12b84d0abe97_0 ~ 8bd94100-f213-47a2-a614-12b84d0abe97_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s3', port=31794): Max retries exceeded with url: /minio-py-test-6e566abb-2189-450d-9a23-38777c2eac11?continuation-token=T0dKa09UUXhNREF0WmpJeE15MDBOMkV5TFdFMk1UUXRNVEppT0RSa01HRmlaVGszWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=T0dKa09UUXhNREF0WmpJeE15MDBOMkV5TFdFMk1UUXRNVEppT0RSa01HRmlaVGszWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 836, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s3', port=31794): Max retries exceeded with url: /minio-py-test-6e566abb-2189-450d-9a23-38777c2eac11?continuation-token=T0dKa09UUXhNREF0WmpJeE15MDBOMkV5TFdFMk1UUXRNVEppT0RSa01HRmlaVGszWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=T0dKa09UUXhNREF0WmpJeE15MDBOMkV5TFdFMk1UUXRNVEppT0RSa01HRmlaVGszWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))\n",
  "duration": 45154
}
(11/16) Running s3cmd tests ... done in 1 minutes and 5 seconds
(12/16) Running s3select tests ... done in 3 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... done in 0 seconds

Executed 14 out of 16 tests successfully.
```
<a name="6db59c28-45a2-4a0c-b9f0-6bb187d41324"></a>
### 12605-70f7f45/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:32217
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 45 seconds
(4/16) Running aws-sdk-ruby tests ... done in 5 seconds
(5/16) Running awscli tests ... done in 2 minutes and 0 seconds
(6/16) Running healthcheck tests ... done in 1 seconds
(7/16) Running mc tests ... done in 29 seconds
(8/16) Running minio-dotnet tests ... done in 35 seconds
(9/16) Running minio-go tests ... done in 1 minutes a [...]

2021-07-02 18:31 UTC, harshavardhana commented
@klauspost did you do any testing to indicate the amount of speed/optimization that we shall see after this change? 

Do you want me to do that ?

2021-07-02 18:41 UTC, klauspost commented
@harshavardhana Speed is largely unaffected. For returning listings (that has a second request) it takes a tiny bit longer.

This is mostly to reduce writes and excessive fetching. Abort time on readahead is 15 minutes. I will see if it is possible to bring that to 5 minutes, but it will require some tweaks.

By all means give it all you got. Also one of the mint tests are failing. I cannot repro locally, so if you can that would be awesome!

2021-07-03 18:33 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b25726e2-5077-48bd-9d2f-ac5bc446f26b) |
| mint-gateway-s3.sh | :x: [more...](#34a025a7-7487-4fef-abe1-0bf3b5ae6410) |
| mint-erasure.sh | :x: [more...](#0182ed7f-60dd-4459-b5c1-1165d680c827) |
| mint-dist-erasure.sh | :x: [more...](#08e8868d-82e0-409d-94c8-0832046dc894) |
| mint-zoned.sh | :x: [more...](#d682de19-11d0-4dbb-bca0-e6d4a5677d52) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#1b1a3861-e3cc-41a1-a892-34324e00dcc8) |
<a name="d682de19-11d0-4dbb-bca0-e6d4a5677d52"></a>
### 12605-0d3f41f/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:31726
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 2 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 45 seconds
(4/16) Running aws-sdk-ruby tests ... done in 4 seconds
(5/16) Running awscli tests ... done in 2 minutes and 1 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 36 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 43 seconds
(10/16) Running minio-java tests ... done in 1 minutes and 39 seconds
(11/16) Running minio-js tests ... done in 50 seconds
(12/16) Running minio-py tests ... done in 2 minutes and 8 seconds
(13/16) Running s3cmd tests ... done in 26 seconds
(14/16) Running s3select tests ... done in 6 seconds
(15/16) Running security tests ... done in 0 seconds
(16/16) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-byerjzgydm2tsi",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 372,
  "function": "testListObjectKeysContinuation",
  "message": "ListObjectVersions returned unexpected listing result",
  "name": "versioning",
  "status": "FAIL"
}

Executed 15 out of 16 tests successfully.
```
<a name="34a025a7-7487-4fef-abe1-0bf3b5ae6410"></a>
### 12605-0d3f41f/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:32482
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 2 minutes and 0 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 22 seconds
(8/16) Running minio-dotnet tests ... done in 48 seconds
(9/16) Running minio-go tests ... done in 55 seconds
(10/16) Running minio-java tests ... FAILED in 16 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 14154,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = XMinioBackendDown, message = Object storage backend is unreachable, bucketName = minio-java-test-voa523, objectName = null, resource = /minio-java-test-voa523, requestId = 168E5B31248CDE3D, hostId = 9c1e3411-3f5c-400a-bee8-41fe3261376d)\nrequest={method=GET, url=http://minio-k8s6:32482/minio-java-test-voa523?list-type=2&prefix=minio&continuation-token=YldsdWFXOHRhbUYyWVMxMFpYTjBMWEZoY3pJMU5sdHRhVzVwYjE5allXTm9aVHAyTWl4eVpYUjFjbTQ2WFE9PQ%3D%3D&max-keys=1000&encoding-type=url&delimiter=, headers=Host: minio-k8s6:32482\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.2.1\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210703T182622Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210703/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 323\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 168E5B31248CDE3D\nX-Xss-Protection: 1; mode=block\nDate: Sat, 03 Jul 2021 18:26:22 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:667), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 36 seconds
(11/16) Running minio-py tests ... FAILED in 1 minutes and 4 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-5ab6062a-1cd1-466e-ab4c-041cfd2fe174",
    "object_name": "0b522b11-a79a-49d7-8d90-4d31e96a1729_0 ~ 0b522b11-a79a-49d7-8d90-4d31e96a1729_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s6', port=32482): Max retries exceeded with url: /minio-py-test-5ab6062a-1cd1-466e-ab4c-041cfd2fe174?continuation-token=TUdJMU1qSmlNVEV0WVRjNVlTMDBPV1EzTFRoa09UQXROR1F6TVdVNU5tRXhOekk1WHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=TUdJMU1qSmlNVEV0WVRjNVlTMDBPV1EzTFRoa09UQXROR1F6TVdVNU5tRXhOekk1WHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1123, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 836, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool [...]

2021-07-03 18:57 UTC, harshavardhana commented
BTW I have updated the mint container with the nextMarker fix - but the tests seem to be still failing @klauspost

2021-07-04 08:28 UTC, klauspost commented
@harshavardhana I don't think it updated properly. `function": "testListObjectKeysContinuation",` would show file+line if it was.

2021-07-04 17:28 UTC, harshavardhana commented
> @harshavardhana I don't think it updated properly. `function": "testListObjectKeysContinuation",` would show file+line if it was.

Will run it again..

2021-07-04 21:09 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#dce1e4ca-24d1-4b3a-961c-ab2a430aef0e) |
| mint-erasure.sh | :x: [more...](#db686491-b820-40da-ace0-19e33c74bec2) |
<a name="db686491-b820-40da-ace0-19e33c74bec2"></a>
### 12605-0c30700/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:30422
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 2 seconds
(5/16) Running awscli tests ... done in 1 minutes and 56 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 22 seconds
(8/16) Running minio-dotnet tests ... done in 27 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 13 seconds
(10/16) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7589,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s8:30422/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 50 seconds
(11/16) Running minio-py tests ... FAILED in 57 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-a4fabe06-85c7-4136-82e3-cef643f6efaa",
    "object_name": "9e90ff6b-da9b-4351-a2fe-399485d52d23_0 ~ 9e90ff6b-da9b-4351-a2fe-399485d52d23_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s8', port=30422): Max retries exceeded with url: /minio-py-test-a4fabe06-85c7-4136-82e3-cef643f6efaa?continuation-token=OWU5MGZmNmItZGE5Yi00MzUxLWEyZmUtMzk5NDg1ZDUyZDIzXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=OWU5MGZmNmItZGE5Yi00MzUxLWEyZmUtMzk5NDg1ZDUyZDIzXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1247, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1127, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s8', port=30422): Max retries exceeded with url: /minio-py-test-a4fabe06-85c7-4136-82e3-cef643f6efaa?continuation-token=OWU5MGZmNmItZGE5Yi00MzUxLWEyZmUtMzk5NDg1ZDUyZDIzXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=OWU5MGZmNmItZGE5Yi00MzUxLWEyZmUtMzk5NDg1ZDUyZDIzXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "duration": 31302
}
(11/16) Running s3cmd tests ... done in 25 seconds
(12/16) Running s3select tests ... done in 2 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-llorvreplam39r",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 449,
  "error": "RequestError: send  [...]

2021-07-04 23:51 UTC, harshavardhana requested changes
Tested you are basically just missing this

```diff
diff --git a/cmd/metacache-server-pool.go b/cmd/metacache-server-pool.go
index 383b869d6..70ce62345 100644
--- a/cmd/metacache-server-pool.go
+++ b/cmd/metacache-server-pool.go
@@ -112,7 +112,13 @@ func (z *erasureServerPools) listPath(ctx context.Context, o *listPathOptions) (
                rpc := globalNotificationSys.restClientFromHash(o.Bucket)
                ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
                defer cancel()
-               c, err := rpc.GetMetacacheListing(ctx, *o)
+               var c *metacache
+               if rpc != nil {
+                       c, err = rpc.GetMetacacheListing(ctx, *o)
+               } else {
+                       resp := localMetacacheMgr.getBucket(ctx, o.Bucket).findCache(*o)
+                       c = &resp
+               }
                if err != nil {
                        if errors.Is(err, context.Canceled) {
                                // Context is canceled, return at once.
```

In this PR.

2021-07-05 00:31 UTC, harshavardhana commented
I ended up squashing all the commits and pushing to this branch @klauspost - since this is a simple enough change and also fixes the local erasure-coded setup behavior.

2021-07-05 00:33 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-07-05 06:21 UTC, harshavardhana approved these changes
This works great in initial tests, ready to take it in.

2021-07-05 06:44 UTC, harshavardhana commented
Although this PR is good there are perhaps a lot more tuning that we need to do, there are subtle bugs like this 

```
warp list --warp-client 192.168.103.{11...16} --host 192.168.103.{5...10}:9000 --access-key minio --secret-key minio123 --storage-class REDUCED_REDUNDANCY --noprefix
```

```
Throughput, split into 103 x 1s:
 * Fastest: 607.7KiB/s, 622.38 obj/s (1s, starting 00:30:11 MDT)
 * 50% Median: 570.2KiB/s, 584.04 obj/s (1s, starting 00:31:08 MDT)
 * Slowest: 420.8KiB/s, 430.95 obj/s (1s, starting 00:31:53 MDT)

----------------------------------------
Operation: LIST (409). Concurrency: 0.
Errors: 409
First Errors:
 * http://192.168.103.6:9000, 2021-07-05 00:34:08 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.8:9000, 2021-07-05 00:34:11 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.10:9000, 2021-07-05 00:33:40 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.5:9000, 2021-07-05 00:33:34 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.7:9000, 2021-07-05 00:33:34 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.9:9000, 2021-07-05 00:33:53 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.6:9000, 2021-07-05 00:35:19 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.8:9000, 2021-07-05 00:34:16 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.5:9000, 2021-07-05 00:33:55 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.10:9000, 2021-07-05 00:33:38 -0600 MDT: Unexpected object count, want 10000, got 60000

Skipping LIST too few samples. Longer benchmark run required for reliable results.
```

Without `--noprefix` things run fine of course because each prefix only has limited entries.

2021-07-05 07:05 UTC, harshavardhana commented
```
warp list --warp-client 192.168.103.{11...16} --host 192.168.103.{5...10}:9000 --access-key minio --secret-key minio123 --storage-class REDUCED_REDUNDANCY --noprefix --concurrent 1
```

```
----------------------------------------
Operation: LIST (154). Concurrency: 0.
Errors: 154
First Errors:
 * http://192.168.103.10:9000, 2021-07-05 00:53:41 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.10:9000, 2021-07-05 00:53:40 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.10:9000, 2021-07-05 00:53:40 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.10:9000, 2021-07-05 00:53:41 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.10:9000, 2021-07-05 00:53:40 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.10:9000, 2021-07-05 00:53:40 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.5:9000, 2021-07-05 00:53:47 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.5:9000, 2021-07-05 00:53:47 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.5:9000, 2021-07-05 00:55:46 -0600 MDT: Unexpected object count, want 10000, got 60000
 * http://192.168.103.5:9000, 2021-07-05 00:55:46 -0600 MDT: Unexpected object count, want 10000, got 60000

Skipping LIST too few samples. Longer benchmark run required for reliable results.
```

Also reproduces this situation @klauspost

2021-07-05 07:06 UTC, harshavardhana requested changes
👎🏽 until we investigate the `warp --noprefix` issue

2021-07-05 09:27 UTC, klauspost commented
Sure 👌

2021-07-05 13:15 UTC, klauspost commented
Interesting. Getting fine results, with set: `SET WARP_HOST=127.0.0.1:{9001...9002}`. Using 1 ss, 2 servers, 4 disks each or 4ss, 1 set each, 4 disks each.

Using `warp list -noprefix --concurrent 1 -duration=30s`. @harshavardhana What server setup are you using?

2021-07-05 14:35 UTC, harshavardhana commented
> Interesting. Getting fine results, with set: `SET WARP_HOST=127.0.0.1:{9001...9002}`. Using 1 ss, 2 servers, 4 disks each or 4ss, 1 set each, 4 disks each.
> 
> Using `warp list -noprefix --concurrent 1 -duration=30s`. @harshavardhana What server setup are you using?
> 

It's a 6 node setup with 20 drives each @klauspost  and 6 clients..

2021-07-05 15:00 UTC, klauspost commented
@harshavardhana Interesting. Are you cleaning between runs? Without prefixes all objects will be in the root, so without cleanup there will be too many objects. 

I got a ` want 50000, got 50001` when it failed to clean up a single file from the last run. Testing on 6 servers in one pool, 4 disks each ATM, but I guess I can add more disks.

2021-07-05 15:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#0732f107-a37f-441a-99c1-28e54f7e7f86) |
| mint-erasure.sh | :x: [more...](#15534b8c-c9be-4a6b-8090-34fdd79fc293) |
<a name="15534b8c-c9be-4a6b-8090-34fdd79fc293"></a>
### 12605-5611e04/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:31595
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 2 seconds
(3/16) Running aws-sdk-php tests ... done in 41 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 56 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 19 seconds
(8/16) Running minio-dotnet tests ... done in 35 seconds
(9/16) Running minio-go tests ... done in 56 seconds
(10/16) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7207,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s6:31595/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 50 seconds
(11/16) Running minio-py tests ... FAILED in 56 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-2393f6df-4ff3-48dd-a323-2b64dc408dc9",
    "object_name": "14fdfe44-e990-4004-bef2-867569f9a45e_0 ~ 14fdfe44-e990-4004-bef2-867569f9a45e_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s6', port=31595): Max retries exceeded with url: /minio-py-test-2393f6df-4ff3-48dd-a323-2b64dc408dc9?continuation-token=MTRmZGZlNDQtZTk5MC00MDA0LWJlZjItODY3NTY5ZjlhNDVlXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=MTRmZGZlNDQtZTk5MC00MDA0LWJlZjItODY3NTY5ZjlhNDVlXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1247, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1127, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s6', port=31595): Max retries exceeded with url: /minio-py-test-2393f6df-4ff3-48dd-a323-2b64dc408dc9?continuation-token=MTRmZGZlNDQtZTk5MC00MDA0LWJlZjItODY3NTY5ZjlhNDVlXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=MTRmZGZlNDQtZTk5MC00MDA0LWJlZjItODY3NTY5ZjlhNDVlXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "duration": 30390
}
(11/16) Running s3cmd tests ... done in 34 seconds
(12/16) Running s3select tests ... done in 1 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-u1w39erextgccn",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 429,
  "error": "RequestError: send request failed\ncaused by: G [...]

2021-07-05 16:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#caaf9ce8-fabb-47a7-9b58-4539645ba642) |
| mint-erasure.sh | :x: [more...](#1885d59d-f437-4731-8e04-b122b9a094c4) |
<a name="1885d59d-f437-4731-8e04-b122b9a094c4"></a>
### 12605-896e134/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:30733
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 2 seconds
(5/16) Running awscli tests ... done in 54 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 26 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 0 seconds
(10/16) Running minio-java tests ... FAILED in 11 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 7489,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on http://minio-k8s7:30733/... >>> [okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:202), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 50 seconds
(11/16) Running minio-py tests ... FAILED in 57 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-77f9f30b-ce5a-4d23-9b84-14461e80738f",
    "object_name": "11cd6a51-9925-439c-9cbd-4e84f63a433b_0 ~ 11cd6a51-9925-439c-9cbd-4e84f63a433b_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s7', port=30733): Max retries exceeded with url: /minio-py-test-77f9f30b-ce5a-4d23-9b84-14461e80738f?continuation-token=MTFjZDZhNTEtOTkyNS00MzljLTljYmQtNGU4NGY2M2E0MzNiXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=MTFjZDZhNTEtOTkyNS00MzljLTljYmQtNGU4NGY2M2E0MzNiXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 445, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 440, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.6/http/client.py\", line 1373, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.6/http/client.py\", line 311, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.6/http/client.py\", line 280, in _read_status\n    raise RemoteDisconnected(\"Remote end closed connection without\"\nhttp.client.RemoteDisconnected: Remote end closed connection without response\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1247, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1127, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 796, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 756, in urlopen\n    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s7', port=30733): Max retries exceeded with url: /minio-py-test-77f9f30b-ce5a-4d23-9b84-14461e80738f?continuation-token=MTFjZDZhNTEtOTkyNS00MzljLTljYmQtNGU4NGY2M2E0MzNiXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=MTFjZDZhNTEtOTkyNS00MzljLTljYmQtNGU4NGY2M2E0MzNiXzE4OThbbWluaW9fY2FjaGU6djIscmV0dXJuOl0%3D (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',)))\n",
  "duration": 31158
}
(11/16) Running s3cmd tests ... done in 24 seconds
(12/16) Running s3select tests ... done in 1 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-1dawfpoqj1zf05",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 463,
  "error": "RequestError: send request failed\ [...]

2021-07-05 16:52 UTC, harshavardhana commented
> @harshavardhana Interesting. Are you cleaning between runs? Without prefixes all objects will be in the root, so without cleanup there will be too many objects.
> 
> I got a ` want 50000, got 50001` when it failed to clean up a single file from the last run. Testing on 6 servers in one pool, 4 disks each ATM, but I guess I can add more disks.

Yes I just let warp clean itself, I don't specify --noclear

2021-07-05 17:19 UTC, harshavardhana commented
I suspect this issue to be some kind of a timeout problem, where the listing timesout and then ends up listing all the entries without honoring the max-keys @klauspost

2021-07-05 18:20 UTC, harshavardhana commented
@klauspost another thing I found is the master branch 

```
warp list --warp-client 192.168.103.{11...16} --host 192.168.103.{5...10}:9000 --access-key minio --secret-key minio123 --storage-class REDUCED_REDUNDANCY --noprefix
```

Works fine with this where as this PR does not, in-fact it seems to increase the load on the system significantly higher is that expected?

2021-07-05 18:26 UTC, harshavardhana commented
> @klauspost another thing I found is the master branch
> 
> ```
> warp list --warp-client 192.168.103.{11...16} --host 192.168.103.{5...10}:9000 --access-key minio --secret-key minio123 --storage-class REDUCED_REDUNDANCY --noprefix
> ```
> 
> Works fine with this where as this PR does not, in-fact it seems to increase the load on the system significantly higher is that expected?

Actually this is not correct - looks like even master branch has this issue

```
----------------------------------------
Operation: LIST (2276). Concurrency: 0.
Errors: 2276
First Errors:
 * http://192.168.103.5:9000, 2021-07-05 12:16:36 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.6:9000, 2021-07-05 12:16:38 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.8:9000, 2021-07-05 12:16:39 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.9:9000, 2021-07-05 12:16:39 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.7:9000, 2021-07-05 12:16:38 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.10:9000, 2021-07-05 12:16:36 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.5:9000, 2021-07-05 12:16:36 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.6:9000, 2021-07-05 12:16:38 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.8:9000, 2021-07-05 12:16:40 -0600 MDT: Unexpected object count, want 10000, got 59999
 * http://192.168.103.9:9000, 2021-07-05 12:16:38 -0600 MDT: Unexpected object count, want 10000, got 59999

Skipping LIST too few samples. Longer benchmark run required for reliable results.
```

2021-07-05 18:32 UTC, klauspost commented
@harshavardhana I can only repro if it is not cleaned up. I did find a bug where disks would be duplicated. Just sent a fix for that. That is this PR only, though.

I added a check for results in warp:

```
				// Wait for errCh to close.
				last := ""
				for oi := range listCh {
					if oi.Err != nil {
						d.Error(oi.Err)
						op.Err = oi.Err.Error()
					}
					if last >= oi.Key {
						console.Errorln("duplicate entry", oi.Key, "last was", last)
					}
					if true {
						found := false
						for _, o := range d.objects {
							for _, obj := range o {
								if obj.Name == oi.Key {
									found = true
									break
								}
							}
						}
						if !found {
							console.Errorln("Unknown key:", oi.Key)
						}
					}
					last = oi.Key
```					

This should detect unknown or duplicated entries returned.

2021-07-05 18:38 UTC, klauspost commented
@harshavardhana Yes, multiple clients will do that, since objects are dumped in the same folder, they cannot separate them when listing.

2021-07-05 18:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#1a6a33fc-677d-4c77-8304-65ae4b749547) |
| mint-erasure.sh | :x: [more...](#7a75732e-3258-4366-a92b-5c840e3e9ca1) |
<a name="1a6a33fc-677d-4c77-8304-65ae4b749547"></a>
### 12605-8372474/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:32347
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 54 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 18 seconds
(8/16) Running minio-dotnet tests ... done in 28 seconds
(9/16) Running minio-go tests ... done in 57 seconds
(10/16) Running minio-java tests ... FAILED in 16 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 14106,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = XMinioBackendDown, message = Object storage backend is unreachable, bucketName = minio-java-test-16fefbs, objectName = null, resource = /minio-java-test-16fefbs, requestId = 168EF8BEF45D5CB0, hostId = e050d302-a5c8-48a8-8775-e6ab33d17244)\nrequest={method=GET, url=http://minio-k8s3:32347/minio-java-test-16fefbs?list-type=2&prefix=minio&continuation-token=YldsdWFXOHRhbUYyWVMxMFpYTjBMVzl2Wm1obU1sdHRhVzVwYjE5allXTm9aVHAyTWl4eVpYUjFjbTQ2WFE9PQ%3D%3D&max-keys=1000&encoding-type=url&delimiter=, headers=Host: minio-k8s3:32347\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.2.2\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20210705T183334Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20210705/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 325\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 168EF8BEF45D5CB0\nX-Xss-Protection: 1; mode=block\nDate: Mon, 05 Jul 2021 18:33:34 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:667), io.minio.S3Base.listObjectsV2(S3Base.java:1820), io.minio.S3Base$1$1.populateResult(S3Base.java:1009), io.minio.S3Base$ObjectIterator.populate(S3Base.java:890), io.minio.S3Base$ObjectIterator.hasNext(S3Base.java:930), FunctionalTest.testListObjects(FunctionalTest.java:1393), FunctionalTest.listObjects(FunctionalTest.java:1447), FunctionalTest.runObjectTests(FunctionalTest.java:3684), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(10/16) Running minio-js tests ... done in 38 seconds
(11/16) Running minio-py tests ... FAILED in 1 minutes and 3 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-a5c65b53-bd82-4836-9265-9423b60c71be",
    "object_name": "387ed215-069d-4974-b5d9-de92d576fa3b_0 ~ 387ed215-069d-4974-b5d9-de92d576fa3b_1000"
  },
  "message": "HTTPConnectionPool(host='minio-k8s3', port=32347): Max retries exceeded with url: /minio-py-test-a5c65b53-bd82-4836-9265-9423b60c71be?continuation-token=TXpnM1pXUXlNVFV0TURZNVpDMDBPVGMwTFdJMVpEa3RaR1U1TW1RMU56Wm1ZVE5pWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=TXpnM1pXUXlNVFV0TURZNVpDMDBPVGMwTFdJMVpEa3RaR1U1TW1RMU56Wm1ZVE5pWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1247, in test_list_objects_with_1001_files\n    _test_list_objects_api(bucket_name, no_of_created_files)\n  File \"/mint/run/core/minio-py/tests.py\", line 1127, in _test_list_objects_api\n    for obj in objects:\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 2775, in _list_objects\n    response = self._execute(\"GET\", bucket_name, query_params=query)\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 422, in _execute\n    no_body_trace=no_body_trace,\n  File \"/usr/local/lib/python3.6/dist-packages/minio/api.py\", line 285, in _url_open\n    preload_content=preload_content,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/poolmanager.py\", line 375, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 859, in urlopen\n    **response_kw\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 836, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/retry.py\", line 574, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s3', port=32347): Max retries exceeded with url: /minio-py-test-a5c65b53-bd82-4836-9265-9423b60c71be?continuation-token=TXpnM1pXUXlNVFV0TURZNVpDMDBPVGMwTFdJMVpEa3RaR1U1TW1RMU56Wm1ZVE5pWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D&delimiter=%2F&list-type=2&max-keys=1000&prefix=&start-after=TXpnM1pXUXlNVFV0TURZNVpDMDBPVGMwTFdJMVpEa3RaR1U1TW1RMU56Wm1ZVE5pWHpFNE9UaGJiV2x1YVc5ZlkyRmphR1U2ZGpJc2NtVjBkWEp1T2wwPQ%3D%3D (Caused by ResponseError('too many 503 error responses',))\n",
  "duration": 44675
}
(11/16) Running s3cmd tests ... done in 1 minutes and 5 seconds
(12/16) Running s3select tests ... done in 3 seconds
(13/16) Running security tests ... done in 0 seconds
(14/16) Running versioning tests ... done in 0 seconds

Executed 14 out of 16 tests successfully.
```
<a name="7a75732e-3258-4366-a92b-5c840e3e9ca1"></a>
### 12605-8372474/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:31270
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 0 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 43 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 1 minutes and 55 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 21 seconds
(8/16) Running minio-dotnet tests ... done in 26 seconds
(9/16) Running minio-go tests ... done in 1 minutes and 3 seconds
(10/16) Running minio-java tests ... FAILED in 10 seconds
{
  "name": "minio-java",
  "function": "listObj [...]

2021-07-05 20:58 UTC, harshavardhana requested changes

2021-07-05 20:58 UTC, harshavardhana commented on cmd/metacache-server-pool.go
> +				// Context is canceled, return at once.
If you change this in this manner `rpc` is nil when its a local erasure setup, if you do not use `localCacheMgr` then  local erasure coded setups won't work - as you can see `mint` tests are again failing. 

This is the fix that I shared in a previous comment @klauspost

2021-07-05 22:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-07-05 22:33 UTC, harshavardhana approved these changes

2021-07-05 22:34 UTC, harshavardhana commented
The PR looks good and also fixes actually some existing problems in the server implementation. Taking this in to further tweak the master branch.

2021-07-05 22:34 UTC, merged