LDAP Test connection was not using GlobalRootCAs
minio/minio pull request #12612
Opened 2021-07-01 23:43 UTC by Alevsk

Signed-off-by: Lenin Alevski <alevsk.8772@gmail.com>

## Description

Initial LDAP check was failing because globalRootCAs were not passed correctly

## Motivation and Context

## How to test this PR?

## Types of changes
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-07-01 23:47 UTC, harshavardhana requested changes

2021-07-01 23:47 UTC, harshavardhana commented on internal/config/identity/ldap/config.go
> +	}
This code should be set right after we do `l.Enabled = true` not until then rootCAs should be referenced inside `l = Config{}`

2021-07-01 23:52 UTC, donatello approved these changes
Nice catch!

2021-07-01 23:57 UTC, kannappanr approved these changes
LGTM

2021-07-02 00:05 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-07-02 00:27 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-07-02 00:40 UTC, harshavardhana approved these changes

2021-07-02 00:41 UTC, merged