Add deployment-id and source bucket to transitioned object name
minio/minio pull request #12693
Opened 2021-07-13 01:00 UTC by krisis

## Description
This allows remote bucket admin to identify the origin of transitioned
objects by simply inspecting the object prefixes.

e.g let's take a remote tier TIER-1 pointing to a remote bucket (prefix)
testbucket/testprefix-1. The remote bucket admin can list all transitioned objects
from a MinIO deployment identified by '2e78e906-1c5d-4f94-8689-9df44cafde39' and
source bucket 'mybucket' like so,

$ ./mc ls -r minio-tier-target/testbucket/testprefix-1/2e78e906-1c5d-4f94-8689-9df44cafde39/mybucket/
[2021-07-12 17:15:50 PDT]   160B 48/fb/48fbc0e6-3a73-458b-9337-8e722c619ca4
[2021-07-12 16:58:46 PDT]   160B 7d/1c/7d1c96bd-031a-48d4-99ea-b1304e870830

## Motivation and Context
Allow a remote bucket admin to identify transitioned objects from a deleted MinIO deployment. 

## How to test this PR?
Listing on remote bucket (of a remote tier) should show deployment ID and source bucket. Additionally, objects tiered prior to this change must still be accessible.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-07-13 01:03 UTC, harshavardhana requested changes

2021-07-13 01:03 UTC, harshavardhana commented on cmd/bucket-lifecycle.go
> +	obj := fmt.Sprintf("%s/%s/%s/%s/%s", globalDeploymentID, bucket, us[0:2], us[2:4], us)
wouldn't this use up too many hierarchies here? we should perhaps flatten top-level entries? - 5 level nesting is not needed IMO

2021-07-13 01:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-07-13 16:38 UTC, harshavardhana approved these changes

2021-07-16 16:39 UTC, harshavardhana commented
Please resolve the conflicts @krisis

2021-07-16 18:30 UTC, poornas approved these changes
LGTM

2021-07-20 17:49 UTC, merged