Add round-robin sharing of ILM transition tasks
minio/minio pull request #12783
Opened 2021-07-23 21:36 UTC by krisis

## Description
This change implements a simple round robin scheme by which the MinIO server running the scanner distributes ILM transition tasks across all MinIO server nodes.

## Motivation and Context
ILM transition tasks are scheduled on the MinIO node where the scanner is running. This workload can be shared with other MinIO servers in the cluster thereby sharing the network bandwidth costs it entails.

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-07-23 21:40 UTC, harshavardhana requested changes

2021-07-23 21:40 UTC, harshavardhana commented on cmd/peer-rest-server.go
> +	opts := ObjectOptions{
```suggestion
	objAPI := newObjectLayerFn()
	opts := ObjectOptions{
```'

Check for `objAPI == nil`  for safety

2021-07-23 21:41 UTC, harshavardhana requested changes

2021-07-23 21:41 UTC, harshavardhana commented on cmd/peer-rest-server.go
> +	}
do you need to re-read - can you not just have all the information send over the wire from the node that notified you? @krisis

2021-07-23 21:41 UTC, harshavardhana commented on cmd/peer-rest-server.go
> +	if globalTransitionState != nil {
Perhaps throw an error to the PEER client that transition state is not ready?

2021-07-23 21:57 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-07-23 22:31 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-07-27 20:43 UTC, krisis commented
This PR is not needed. Scanner actions such as ILM policy action, object healing, etc happen at the MinIO server that scans an object. This distributes the corresponding workload close to the object.

2021-07-27 20:43 UTC, closed without merging