Add options to send notification to nats using jwt / nkey or using creds
minio/minio pull request #12898
Opened 2021-08-06 14:46 UTC by HugoDab

## Description

This Pull Request enables minio to connect to a nats server using jwt and nkey or credentials file.

## Motivation and Context

JWT, nkey and creds are useful to configure permissions on nats. Unfortunately, before this Pull Request, minio was not able to connect to nats this way.

## How to test this PR?

You have to create a notification for nats, for example by using :
`mc admin config set myminio notify_nats`
With the arguments, `jwt=` and `nkey_seed=` or `creds=`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [X] Documentation updated
- [ ] Unit tests added/updated

2021-08-06 14:49 UTC, harshavardhana requested changes
why does NATS have 100 different ways to authenticate?

2021-08-06 14:56 UTC, HugoDab commented
Nkey/jwt or creds are the efficient way to enable RBAC in NATS.

2021-08-06 15:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-06 15:12 UTC, harshavardhana commented
> Nkey/jwt or creds are the efficient way to enable RBAC in NATS.

Why are they efficient and why is that not the default choice? - every 6months some new technique gets introduced.

First, it was username/password
Next, it was token-based
Next, it was client TLS (mTLS)

and now this? 

How is it that it's efficient and none of the other options are not? what is the benchmark for such efficiency? 

We are the maintainers here it looks like a cockpit of authentication options with no clear idea what is correct and what is not. I would rather not have it in our project if it's used by some 3 users out there who know how to configure it. 

Enlighten me why other 3 existing options are not great?

2021-08-06 15:32 UTC, HugoDab commented
The user/password and token-based authentication are only available in a static way in the configuration file of Nats, whereas the 2.0 version of NATS server introduced the idea of decentralized authentication based on JSON Web Tokens (JWT). Clients interact with this new scheme using a user JWT and corresponding NKey private key.

In a multitenancy context, it enables to create a notification per bucket to a dedicated subject for user jwt/nkey. It allows a fine grained RBAC control with a dynamic user jwt/nkey creation.

2021-09-06 14:09 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-10-06 17:22 UTC, harshavardhana commented
Still relevant, PR is backlogged as we get other PRs merged.

2022-03-10 00:27 UTC, cameronbraid commented
This would be great to add.

Please also support JWT without nkey as the JWT can be configured as a bearer

2022-03-10 01:11 UTC, cameronbraid commented on internal/event/target/nats.go
> +	if n.JWT != "" && n.NkeySeed != nil {
Please support JWT without NkeySeed, as the JWT can be configured as a bearer

```
userSignature := func(nonce []byte) ([]byte, error) {
	if n.NkeySeed = nil {
		return nil, nil
	}

	return sigHandler(nonce, n.NkeySeed)
}
```

2024-01-24 07:35 UTC, harshavardhana commented
Please rebase with the latest master if this still needs to be merged. Thank you.

2024-01-24 07:35 UTC, closed without merging