Allow sending headers in amqp event notification
minio/minio pull request #12911
Opened 2021-08-09 13:41 UTC by rikatz

Signed-off-by: Ricardo Katz <rkatz@vmware.com>

## Description
This PR adds a feature to enable AMQP notifications to contain a header, with bucket and event name

## Motivation and Context
Minio allow sending notifications to AMQP compliant services (mostly notable RabbitMQ). The allowed ways of sending those notifications today demands the cluster admin to:
* Configure a notification that bucket owners can use in their own buckets, which might end on multiple users sending notifications to the same queue, due to this notification using the same routing key (or even being a fanout, and users receiving notifications from other users buckets)
* Configure a notification for each user and demanding multiple restarts of the environment (and this does not blocks users from sending notifications to the wrong exchanges)

With this PR, the exchange of type ["headers"](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges) can be used, and the header of the notification can be used to route messages.

On a simple way, users can configure their buckets to use the same single notification configuration, that will send to an exchange on RMQ that can use the metadata/headers to route, for example, messages with bucketname="ricardo" to a queue named "ricardo", and also allow the admins to route all messages containing "s3:PutObject" to an audit queue.

## How to test this PR?
* Run a simple RabbitMQ server, and configure an exchange of type headers and name "testexchange"
* Configure two bindings on this exchange: one with arguments: `bucket=bucket1` pointing to queue `bucket1` and other `bucket=bucket2` pointing to queue `bucket2`
* Run Minio with the following arguments:
```
MINIO_NOTIFY_AMQP_ADD_HEADERS_notifications="on"  
MINIO_NOTIFY_AMQP_ENABLE_notifications="on" MINIO_NOTIFY_AMQP_URL_notifications="amqp://guest:guest@localhost:5672" MINIO_NOTIFY_AMQP_EXCHANGE_TYPE_notifications="headers" MINIO_NOTIFY_AMQP_EXCHANGE_notifications="testexchange"
```

* Create bucket1 and bucket2 and configure both of them to point to `arn:minio:sqs::notifications:amqp` with all events. Generate some traffic (put, get objects)
* Verify in RMQ that notifications from bucket1 goes to queue bucket1, and bucket2 to queue bucket2
 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-08-09 13:56 UTC, harshavardhana requested changes
What if we remove this as an option instead make it default? What would break if we make it default?

2021-08-09 14:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-10 21:47 UTC, harshavardhana commented
> What if we remove this as an option instead make it default? What would break if we make it default?

@rikatz ^^

2021-08-10 22:16 UTC, rikatz commented
sorry, just saw :/

Nothing will break, headers are part of the AMQP specification. Will remove here and submit a new commit (do you want it already squashed?)

Thanks!

2021-08-10 22:18 UTC, harshavardhana commented
> Nothing will break, headers are part of the AMQP specification. Will remove here and submit a new commit (do you want it already squashed?)

yes squash it and change it here.. does it break deployments that do not have this header set?

2021-08-10 22:21 UTC, rikatz commented
> > Nothing will break, headers are part of the AMQP specification. Will remove here and submit a new commit (do you want it already squashed?)
> 
> yes squash it and change it here.. does it break deployments that do not have this header set?

It shouldn't:
* If Minio starts adding headers, deployments that uses exchange != header will keep working same way
* deployments using exchange == header will start adding those headers in the message. IF the exchange have some binding that relies on the keys "bucket" or "event" they will route wrong (if there's some chaining of exchanges). What we can do, is check if minio-bucket and minio-event are acceptable keys (instead of using common event or bucket), and on the next changelog inform that Minio now adds those informations into headers.

2021-08-10 22:24 UTC, harshavardhana commented
> > > Nothing will break, headers are part of the AMQP specification. Will remove here and submit a new commit (do you want it already squashed?)
> > 
> > 
> > yes squash it and change it here.. does it break deployments that do not have this header set?
> 
> It shouldn't:
> 
> * If Minio starts adding headers, deployments that uses exchange != header will keep working same way
> * deployments using exchange == header will start adding those headers in the message. IF the exchange have some binding that relies on the keys "bucket" or "event" they will route wrong (if there's some chaining of exchanges). What we can do, is check if minio-bucket and minio-event are acceptable keys (instead of using common event or bucket), and on the next changelog inform that Minio now adds that information into headers.

Sounds good as long as we can reduce new options the better - that is why add it as default from now on and there should be no option to disable/enable it - if it doesn't change anything fundamentally.

2021-08-11 12:45 UTC, rikatz commented
@harshavardhana this is weird. Force pushed and Github decided to close the PR....

Will open a new one if we cannot re-open this one

2021-08-11 12:58 UTC, rikatz commented
@harshavardhana sorry for the mess and the close/open, did a wrong commit here.

Anyway, squashed and added docs. I've also tested and the keys "minio-bucket" and "minio-event" works fine, including adding more than one "conflicting" key (like an event and a bucket key pointing to different queues and notification getting routed to both).

2021-08-11 13:05 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-11 13:26 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-11 13:48 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-11 14:28 UTC, harshavardhana approved these changes

2021-08-11 14:28 UTC, harshavardhana commented
> @harshavardhana sorry for the mess and the close/open, did a wrong commit here.
> 
> Anyway, squashed and added docs. I've also tested and the keys "minio-bucket" and "minio-event" works fine, including adding more than one "conflicting" key (like an event and a bucket key pointing to different queues and notification getting routed to both).

No problem @rikatz

2021-08-12 05:24 UTC, merged