Add dynamic reconfiguration of number of transition workers
minio/minio pull request #12926
Opened 2021-08-10 22:09 UTC by krisis

## Description
This change adds support for dynamically configuring number of transition workers per node.

## Motivation and Context
This would allow users to configure this number according to their transition workload.

## How to test this PR?
1. Configure remote tier, setup ILM policies on a bucket
2. `./mc admin config set minio-tier api transition_workers=95` 
3. Using `mc admin profile` you can confirm the number of `(*transitionState).worker` goroutines are running.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-08-10 23:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-11 00:29 UTC, harshavardhana approved these changes

2021-08-11 02:23 UTC, poornas requested changes
Need to add to env only help for config `mc admin config set --env`.

2021-08-11 09:51 UTC, klauspost approved these changes
LGTM

2021-08-11 21:01 UTC, krisis commented
@poornas nice catch, thanks. I have addressed your comment.

2021-08-11 21:08 UTC, poornas approved these changes
LGTM

2021-08-11 21:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-11 22:36 UTC, harshavardhana approved these changes

2021-08-12 05:23 UTC, merged