Remove inline data hack
minio/minio pull request #12946
Opened 2021-08-12 17:13 UTC by klauspost

## Description

Instead rewrite metadata for broken/outdated metadata.

## Motivation and Context

WIP: Mint test error.

Returned data is stripped based on numerical values that may not hold up in the future.

We have this at a lower level, and delete the inline data if overwritten by later data.

If not overwritten we add the internal header to indicate that we don't have to check externally any more.

## How to test this PR?

Current master fails long listings, making this easy to reproduce.

@harshavardhana I don't know if you still have a reproducible data set, otherwise I will try to generate one.

## Types of changes
- [x] Optimization/cleanup

2021-08-12 17:34 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#428ba5d7-5a77-4f03-9ca1-f34c46b32264) |
| mint-erasure.sh | :x: [more...](#2085c79d-4702-4d77-b407-4e34dd14cb71) |
| mint-dist-erasure.sh | :x: [more...](#d6916904-76fc-4543-889c-ec19d91fe9f7) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#0f841153-0c09-43ce-8188-f8d07390ab98) |
<a name="2085c79d-4702-4d77-b407-4e34dd14cb71"></a>
### 12946-7091ff5/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:30968
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 52 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 21 seconds
(8/15) Running minio-dotnet tests ... done in 46 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 5 seconds
(10/15) Running minio-java tests ... done in 20 seconds
(11/15) Running minio-js tests ... done in 51 seconds
(12/15) Running minio-py tests ... done in 52 seconds
(13/15) Running s3cmd tests ... done in 29 seconds
(14/15) Running s3select tests ... done in 1 seconds
(15/15) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-3h3vxiz5jlmzfr",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 378,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s3:30968/versioning-test-3h3vxiz5jlmzfr/testObject?versionId=fbb4acde-36c1-43cf-8b10-a89c16c365cf\": dial tcp 15.15.15.3:30968: connect: connection refused",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="d6916904-76fc-4543-889c-ec19d91fe9f7"></a>
### 12946-7091ff5/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:31280
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 25 seconds
(8/15) Running minio-dotnet tests ... done in 53 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 15 seconds
(10/15) Running minio-java tests ... done in 59 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 37 seconds
(13/15) Running s3cmd tests ... done in 24 seconds
(14/15) Running s3select tests ... done in 4 seconds
(15/15) Running versioning tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-f3sh0lttdvrgkp",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 613,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s3:31280/versioning-test-f3sh0lttdvrgkp/testObject?versionId=22394fe7-2a69-4fa3-815d-df0ec0d6339f\": EOF",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="428ba5d7-5a77-4f03-9ca1-f34c46b32264"></a>
### 12946-7091ff5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:30980
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 54 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 25 seconds
(8/15) Running minio-dotnet tests ... done in 54 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 30 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 1 seconds
(11/15) Running minio-js tests ... done in 51 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 38 seconds
(13/15) Running s3cmd tests ... done in 25 seconds
(14/15) Running s3select tests ... done in 4 seconds
(15/15) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-sn13p1e1htvt35",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 728,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s8:30980/versioning-test-sn13p1e1htvt35/testObject?versionId=117c4b2c-5a46-4d3a-88dd-9ad2b9cc60dd\": EOF",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="0f841153-0c09-43ce-8188-f8d07390ab98"></a>
### 12946-7091ff5/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:31484
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 1 minutes and 51 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 23 seconds
(8/15) Running minio-dotnet tests ... done in 52 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 31 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 8 seconds
(11/15) Running minio-js tests ... done in 51 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 55 seconds
(13/15) Running s3cmd tests ... done in 25 seconds
(14/15) Running s3select tests ... done in 5 seconds
(15/15) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-b66k19g1ekhg22",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 2638,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s8:31484/versioning-test-b66k19g1ekhg22/testObject?versionId=e4cee41c-0d2d-44e9-8f97-1dc992c3663d\": EOF",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "sta [...]

2021-08-12 18:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#29f27983-233b-4804-971a-d5b6de7eb483) |
| mint-erasure.sh | :x: [more...](#43a6835f-3a7a-4edb-b11c-3f0ac1d74aa6) |
| mint-dist-erasure.sh | :x: [more...](#ecca8501-787a-427e-9c51-b6fb4aa513a0) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#c15282a6-73df-489f-9556-b522acd00ffe) |
<a name="c15282a6-73df-489f-9556-b522acd00ffe"></a>
### 12946-34801b2/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:30859
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 23 seconds
(8/15) Running minio-dotnet tests ... done in 51 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/15) Running minio-java tests ... done in 56 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 39 seconds
(13/15) Running s3cmd tests ... done in 29 seconds
(14/15) Running s3select tests ... done in 3 seconds
(15/15) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-1kwsots3yldc1k",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 677,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s1:30859/versioning-test-1kwsots3yldc1k/testObject?versionId=ec09ce10-644e-4f34-8f10-c5a797c3e580\": dial tcp 15.15.15.1:30859: connect: connection refused",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="29f27983-233b-4804-971a-d5b6de7eb483"></a>
### 12946-34801b2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:32158
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 40 seconds
(8/15) Running minio-dotnet tests ... done in 58 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 25 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 0 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 35 seconds
(13/15) Running s3cmd tests ... done in 25 seconds
(14/15) Running s3select tests ... done in 4 seconds
(15/15) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-bnvav4lb6iear3",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 680,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s3:32158/versioning-test-bnvav4lb6iear3/testObject?versionId=7362c153-c64a-4c7d-9582-170f36e10ef8\": EOF",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="43a6835f-3a7a-4edb-b11c-3f0ac1d74aa6"></a>
### 12946-34801b2/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:31954
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 47 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 22 seconds
(8/15) Running minio-dotnet tests ... done in 47 seconds
(9/15) Running minio-go tests ... done in 58 seconds
(10/15) Running minio-java tests ... done in 19 seconds
(11/15) Running minio-js tests ... done in 49 seconds
(12/15) Running minio-py tests ... done in 57 seconds
(13/15) Running s3cmd tests ... done in 24 seconds
(14/15) Running s3select tests ... done in 1 seconds
(15/15) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-9m6pd50fjrqy94",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 424,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s4:31954/versioning-test-9m6pd50fjrqy94/testObject?versionId=84208dff-4ce3-4b0c-b448-d8ada97f0091\": dial tcp 15.15.15.4:31954: connect: connection refused",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="ecca8501-787a-427e-9c51-b6fb4aa513a0"></a>
### 12946-34801b2/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:30050
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 54 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 26 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 2 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 12 seconds
(10/15) Running minio-java tests ... done in 49 seconds
(11/15) Running minio-js tests ... done in 49 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 26 seconds
(13/15) Running s3cmd tests ... done in 25 seconds
(14/15) Running s3select tests ... done in 4 seconds
(15/15) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-hyaub2mdk0kafa",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 587,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s8:30050/versioning-test-hyaub2mdk0kafa/testObject?versionId=fc1ad665-2ef4-4bbd-b16b-dd5ab58facc1\": dial tcp 15.15.15.8:30050: connect: connection refused",
  "function": "/mint/build/versioning/get.go:151: m [...]

2021-08-13 03:46 UTC, harshavardhana requested changes
Rewriting data in this manner is complicated @klauspost it is preferred that you leave the data as is and only honor the situations for Reads() this way let the client upload perform the actual overwrite and this can be automatically addressed at that point.

Without that it becomes very tricky when you are performing disconnected system calls on different drives remotely. Now the logic has become sort of tricky as well. 

I would suggest rather than fixing the content on the drive just honor the read portion and that should be sufficient.

2021-08-13 08:13 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8e2ed93f-e65e-4835-8c1e-5c57c2cdbe1c) |
| mint-erasure.sh | :x: [more...](#d5048d79-00ca-4dbb-b6fa-a172769fc646) |
| mint-dist-erasure.sh | :x: [more...](#554cc1e5-9196-4bc9-bce4-4c7eac94547d) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#51127e1f-2868-499f-b496-733dba17b68b) |
<a name="d5048d79-00ca-4dbb-b6fa-a172769fc646"></a>
### 12946-c3ea0a1/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:31450
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 20 seconds
(8/15) Running minio-dotnet tests ... done in 56 seconds
(9/15) Running minio-go tests ... done in 57 seconds
(10/15) Running minio-java tests ... done in 20 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... done in 54 seconds
(13/15) Running s3cmd tests ... done in 25 seconds
(14/15) Running s3select tests ... done in 1 seconds
(15/15) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-o2ekg1uk90dvrk",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 430,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s3:31450/versioning-test-o2ekg1uk90dvrk/testObject?versionId=0dbb22fd-1d54-43d5-83ca-9e5f489d29e5\": dial tcp 15.15.15.3:31450: connect: connection refused",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="8e2ed93f-e65e-4835-8c1e-5c57c2cdbe1c"></a>
### 12946-c3ea0a1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:32628
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 53 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 7 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 15 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 0 seconds
(11/15) Running minio-js tests ... done in 51 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 35 seconds
(13/15) Running s3cmd tests ... done in 24 seconds
(14/15) Running s3select tests ... done in 5 seconds
(15/15) Running versioning tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-pxa1mmosteei0e",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 2481,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 169ACF64001239E9, host id: ",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="51127e1f-2868-499f-b496-733dba17b68b"></a>
### 12946-c3ea0a1/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:30190
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 1 minutes and 53 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 26 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 7 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 26 seconds
(10/15) Running minio-java tests ... done in 1 minutes and 11 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 54 seconds
(13/15) Running s3cmd tests ... done in 27 seconds
(14/15) Running s3select tests ... done in 5 seconds
(15/15) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-3hpakyic0rcn6e",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 777,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s7:30190/versioning-test-3hpakyic0rcn6e/testObject?versionId=7936a3ad-0efd-4f93-9ef9-6cd0ccb4f021\": dial tcp 15.15.15.7:30190: connect: connection refused",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="554cc1e5-9196-4bc9-bce4-4c7eac94547d"></a>
### 12946-c3ea0a1/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:31522
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 29 seconds
(8/15) Running minio-dotnet tests ... done in 52 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 27 seconds
(10/15) Running minio-java tests ... done in 53 seconds
(11/15) Running minio-js tests ... done in 49 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 32 seconds
(13/15) Running s3cmd tests ... done in 25 seconds
(14/15) Running s3select tests ... done in 3 seconds
(15/15) Running versioning tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-0wyaylm2spaf4y",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 704,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s8:31522/versioning-test-0wyaylm2spaf4y/testObject?versionId=60b593be-f188-42e0-a155-0046a707bdf3\": dial tcp 15.15.15.8:31522: connect: connection refused",
  "function": "/mint/build/versioning/get.go:151: main.testGetO [...]

2021-08-13 09:07 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c2ffc343-64e2-4f09-90a7-8260dd92ed72) |
| mint-erasure.sh | :x: [more...](#b3cc3245-2340-471e-baf2-930228e1bf70) |
| mint-dist-erasure.sh | :x: [more...](#91047954-65fd-4244-a908-4545e6f5d198) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#d0b61b61-61d6-4a7e-8a72-6c947e65ef5a) |
<a name="d0b61b61-61d6-4a7e-8a72-6c947e65ef5a"></a>
### 12946-7a86531/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:32013
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 53 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 26 seconds
(8/15) Running minio-dotnet tests ... done in 52 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 9 seconds
(10/15) Running minio-java tests ... done in 58 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 33 seconds
(13/15) Running s3cmd tests ... done in 25 seconds
(14/15) Running s3select tests ... done in 4 seconds
(15/15) Running versioning tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-yt5lbu329ossnb",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 703,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s4:32013/versioning-test-yt5lbu329ossnb/testObject?versionId=2b33beaa-1636-4670-9d7a-6e2b4b78910a\": EOF",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="c2ffc343-64e2-4f09-90a7-8260dd92ed72"></a>
### 12946-7a86531/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:30737
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 53 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
(8/15) Running minio-dotnet tests ... done in 52 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/15) Running minio-java tests ... done in 56 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 32 seconds
(13/15) Running s3cmd tests ... done in 30 seconds
(14/15) Running s3select tests ... done in 3 seconds
(15/15) Running versioning tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-90ra0ywcrdwih1",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 649,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s8:30737/versioning-test-90ra0ywcrdwih1/testObject?versionId=6ae7a2f0-cb98-4764-97e4-697104a61617\": dial tcp 15.15.15.8:30737: connect: connection refused",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="b3cc3245-2340-471e-baf2-930228e1bf70"></a>
### 12946-7a86531/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:30725
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 51 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 20 seconds
(8/15) Running minio-dotnet tests ... done in 56 seconds
(9/15) Running minio-go tests ... done in 53 seconds
(10/15) Running minio-java tests ... done in 22 seconds
(11/15) Running minio-js tests ... done in 49 seconds
(12/15) Running minio-py tests ... done in 49 seconds
(13/15) Running s3cmd tests ... done in 23 seconds
(14/15) Running s3select tests ... done in 2 seconds
(15/15) Running versioning tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-y6s3mcf25e0cyz",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 1504,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 169AD225D24C0F54, host id: ",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successfully.
```
<a name="91047954-65fd-4244-a908-4545e6f5d198"></a>
### 12946-7a86531/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:31564
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 24 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 2 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 12 seconds
(10/15) Running minio-java tests ... done in 56 seconds
(11/15) Running minio-js tests ... done in 50 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 29 seconds
(13/15) Running s3cmd tests ... done in 24 seconds
(14/15) Running s3select tests ... done in 3 seconds
(15/15) Running versioning tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-rxymqq9lifu0m6",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 576,
  "error": "RequestError: send request failed\ncaused by: Get \"http://minio-k8s8:31564/versioning-test-rxymqq9lifu0m6/testObject?versionId=e00afa6d-001a-45a4-ac34-9fe02dba41e3\": EOF",
  "function": "/mint/build/versioning/get.go:151: main.testGetObject",
  "message": "GetObject(1) unexpected error with delete marker",
  "name": "versioning",
  "status": "FAIL"
}

Executed 14 out of 15 tests successful [...]

2021-08-13 09:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-13 15:23 UTC, harshavardhana approved these changes

2021-08-13 15:25 UTC, merged