reduce extra getObjectInfo() calls during ILM transition
minio/minio pull request #13091
Opened 2021-08-27 17:26 UTC by harshavardhana

## Description
reduce extra getObjectInfo() calls during ILM transition

## Motivation and Context
This PR also changes expiration logic to be non-blocking,
scanner is now free from additional costs incurred due
to slower object layer calls and hitting the drives.

## How to test this PR?
Can be tested on a large enough namespace, wouldn't be
able to see any difference on smaller setups

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-08-27 17:36 UTC, harshavardhana commented on cmd/object-handlers.go
> +		}
This is a bug that is fixed in this PR @krisis @vadmeste

2021-08-27 17:36 UTC, harshavardhana commented on cmd/data-scanner.go
>  }
Made this non-blocking from blocking call

2021-08-27 18:07 UTC, poornas requested changes

2021-08-27 18:07 UTC, poornas commented on cmd/object-handlers.go
> +		}
cleaning up restored version successfully does not mean we should return an error on HEAD/GET. The remote version is still present - this clean up is best avoided here

2021-08-27 18:09 UTC, poornas commented on cmd/object-handlers.go
> +		case lifecycle.DeleteRestoredAction, lifecycle.DeleteRestoredVersionAction:
same issue as in GET - ErrNoSuchKey should not be returned when restored version is deleted

2021-08-27 18:10 UTC, harshavardhana commented on cmd/object-handlers.go
> +		}
That is a good catch but I would still trigger this here if necessary just not return an error to the client.

2021-08-27 18:28 UTC, poornas approved these changes

2021-08-27 18:30 UTC, krisis commented on cmd/data-scanner.go
> +	action = evalActionFromLifecycle(ctx, *i.lifeCycle, oi, i.debug)
Now that we are removing the GetObjectInfo call, we don't need to recompute the lifecycle action.

2021-08-27 18:43 UTC, vadmeste commented on cmd/data-scanner.go
> -	obj, err := o.GetObjectInfo(ctx, i.bucket, i.objectPath(), ObjectOptions{
I think we cannot really remove this. `oi` here is calculated per disk level and the disk can be outdated.

There was a comment that explains why this is needed but it seems it is removed now.

/cc @klauspost

2021-08-27 18:43 UTC, vadmeste requested changes
One comment

2021-08-27 18:53 UTC, harshavardhana commented on cmd/data-scanner.go
> +	action = evalActionFromLifecycle(ctx, *i.lifeCycle, oi, i.debug)
I thought it is needed because ComputeAction is slightly different than evalAction @krisis

2021-08-27 19:18 UTC, harshavardhana commented on cmd/data-scanner.go
> -	obj, err := o.GetObjectInfo(ctx, i.bucket, i.objectPath(), ObjectOptions{
@vadmeste it is not needed for two reasons 

- Transition re-reads objectInfo()
- DeleteObject doesn't need to know objectInfo()

2021-08-27 20:43 UTC, vadmeste commented on cmd/data-scanner.go
> -	obj, err := o.GetObjectInfo(ctx, i.bucket, i.objectPath(), ObjectOptions{
@harshavardhana applyLifecycle is called from xl-storage as well and sometimes it has outdated xl.meta. It is needed to decide the lifecycle expiration (object modtime, successor modtime, ..)

2021-08-27 20:46 UTC, harshavardhana commented on cmd/data-scanner.go
> -	obj, err := o.GetObjectInfo(ctx, i.bucket, i.objectPath(), ObjectOptions{
correct but in all situations, we are re-reading xl.meta @vadmeste DeleteObject() also re-reads xl.meta I don't see why we need to do that.

2021-08-27 21:59 UTC, poornas approved these changes

2021-08-27 22:22 UTC, krisis commented on cmd/erasure-object.go
> +		if action == lifecycle.NoneAction {
we need to return error if its not `DeleteAction` or `DeleteVersionAction`.
```go
switch action {
case DeleteAction, DeleteVersionAction:
default:
  if goi.VersionID != "" {
  ...
  }
  ...
}
```

2021-08-27 22:24 UTC, krisis commented on cmd/data-scanner.go
> +		fallthrough
we could combine all delete actions into single case.

2021-08-27 22:26 UTC, harshavardhana commented on cmd/erasure-object.go
> +		if action == lifecycle.NoneAction {
We are handling the DeleteRestoredVersion as well @krisis

2021-08-27 22:26 UTC, harshavardhana commented on cmd/data-scanner.go
> +		fallthrough
its just kept for readability

2021-08-27 23:16 UTC, krisis approved these changes

2021-08-27 23:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-27 23:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-28 00:04 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-08-28 00:06 UTC, merged