select: Add more compression formats
minio/minio pull request #13142
Opened 2021-09-03 11:38 UTC by klauspost

## Description

Support Zstandard, LZ4, S2 and snappy as additional compression formats for S3 Select.

When using gzip, speed and compression is significantly decreased due to format limitations in the file format.

Allow alternative compression methods. This extends S3 functionality.

## How to test this PR?

* Download [nyc-taxi-data-10M.csv.zst](https://files.klauspost.com/compress/nyc-taxi-data-10M.csv.zst)
* Upload to minio as `mybucket/nyc-taxi-data-10M.csv.zst`
* Example query: `mc sql --compression zstd --csv-input "rd=\n,fh=USE,fd=;" -query "select count(*) from S3Object" local2/testbucket/nyc-taxi-data-10M.csv.zst`

To generate snappy/s2 use s2c, download from [here](https://github.com/klauspost/compress/releases/tag/v1.13.5)

```
$ zstd -d -c nyc-taxi-data-10M.csv.zst|s2c -slower -o=nyc-taxi-data-10M.csv.s2 -
$ zstd -d -c nyc-taxi-data-10M.csv.zst|s2c -snappy -slower -o=nyc-taxi-data-10M.csv.snappy -
```
To generate lz4, use 

```
$ go install github.com/pierrec/lz4/v4/cmd/lz4c@latest
$ zstd -d -c nyc-taxi-data-10M.csv.zst|lz4c compress >nyc-taxi-data-10M.csv.lz4
```

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2021-09-03 11:58 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-09-03 16:45 UTC, harshavardhana requested changes
Perhaps we should update the docs at `docs/select/README.md` about the extended functionalities that users can use?

2021-09-06 08:47 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-09-06 16:09 UTC, harshavardhana approved these changes

2021-09-06 16:09 UTC, merged