fix: remove unnecessary retries in resuming Listing
minio/minio pull request #13249
Opened 2021-09-19 17:40 UTC by harshavardhana

## Description
fix: remove unnecessary retries in resuming Listing

## Motivation and Context
instead of attempt a fresh listing in cases of

- objectNotFound for part metadata entries
- io.ErrUnexpectedEOF, errFileNotFound.

These retries are not useful and can waste time
for actual listing operations, perform raw listing
that can proceed independently.

## How to test this PR?
Nothing should change, generally an optimization. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-09-19 18:01 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-09-20 09:17 UTC, klauspost requested changes
This is needed. The first block is often not written when the client returns, and it may be partially written.

I don't see anything unnecessary.

2021-09-20 15:36 UTC, harshavardhana commented
> This is needed. The first block is often not written when the client returns, and it may be partially written.
> 
> I don't see anything unnecessary.

@klauspost are we sure about that? - I don't see a retry is needed here since that involves unnecessary round trips. 

Especially if the resumable client comes before the server has written newer block? isn't this already happening at the same time while we return the results?

I would like to really reproduce the behavior here and see does it really make sense.

2021-09-21 10:21 UTC, klauspost commented
> Especially if the resumable client comes before the server has written newer block? isn't this already happening at the same time while we return the results?

No. When we start `listAndSave` the results are split, so the request will get a copy of the first `max_keys` results, which will return as soon as they are done. 

Filling a block requires 5K entries (unless it is done), which most often is more than the first request `max_keys`. So the returning request (typically the 3rd) will usually have to wait for the 1st block to be finished. On fast listing HW this will not be a wait, but on spinning disks it will typically have to wait and retry.

2021-09-23 18:06 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-09-23 23:59 UTC, krisis approved these changes

2021-09-24 00:17 UTC, poornas approved these changes

2021-09-24 00:24 UTC, merged