Add missing keys to API config help
minio/minio pull request #13255
Opened 2021-09-20 18:33 UTC by dreglad

Added missing `apiClusterDeadline` and `apiListQuorum` to API config.HelpKVS structure

## Description
Missing keys in the Help structure

## Motivation and Context
The MinIO Console relies on Help text to to parse key value options. So this is needed for this to work:
https://github.com/minio/console/issues/1062

## How to test this PR?

## Types of changes
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-09-20 18:34 UTC, harshavardhana requested changes
These are not added on purpose @dreglad

2021-09-20 18:53 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-09-21 01:31 UTC, dreglad commented
> These are not added on purpose @dreglad

Thanks for the clarification @harshavardhana   I guess that is because those keys are not meant to be set or changed directly by users, right?

2021-10-08 04:20 UTC, harshavardhana requested changes

2021-10-08 04:20 UTC, harshavardhana commented on internal/config/api/help.go
> +			Description: `set the acceptable quorum expected for list operations e.g. "optimal", "reduced", "disk", "strict", defaults to "optimal"`,
```suggestion
			Description: `set the acceptable quorum expected for list operations e.g. "optimal", "reduced", "disk", "strict", defaults to "strict"`,
```

2021-10-10 04:54 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-zoned.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-10-10 16:51 UTC, harshavardhana approved these changes

2021-10-10 16:52 UTC, merged