ilm: Make per-tier stats available via admin-tier-info
minio/minio pull request #13381
Opened 2021-10-08 00:17 UTC by krisis

## Description
This change includes per-tier stats like total bytes and number of versions of objects transitioned to a tier. These statistics are made available via `mc admin tier info`.

## Motivation and Context
With this change users can track objects transitioned to a tier at a per-tier level.

## How to test this PR?
1. Configure one or more remote tiers.
2. Setup ILM policies to transition object to these tiers.
3. Enable versioning on test buckets; to observe number of versions transitioned.
4. `mc admin tier info ALIAS` (mc compiled with https://github.com/minio/madmin-go/pull/43)

Sample output
```
      $ ./mc admin tier info minio-tier
      Tier Name  |API  |Type  |Usage    |Objects  |Versions  
      STANDARD   |s3   |hot   |130 MiB  |1        |1         
      S3TIER-1   |s3   |warm  |130 MiB  |1        |3         
      S3TIER-2   |s3   |warm  |2.8 KiB  |0        |2

      $ ./mc admin tier info minio-tier --json | jq . 
      {
        "status": "success",
        "tiers": [
          {
            "Name": "STANDARD",
            "Type": "internal",
            "Stats": {
              "totalSize": 136314880,
              "numVersions": 1,
              "numObjects": 1
            }
          },
          {
            "Name": "S3TIER-1",
            "Type": "s3",
            "Stats": {
              "totalSize": 136317777,
              "numVersions": 3,
              "numObjects": 1
            }
          },
          {
            "Name": "S3TIER-2",
            "Type": "s3",
            "Stats": {
              "totalSize": 2897,
              "numVersions": 2,
              "numObjects": 0
            }
          }
        ]
      }       
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-10-08 00:17 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 13381-0d7ede4/gopath/src/github.com/minio
+ git -C 13381-0d7ede4/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 13381-0d7ede4/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 13381-0d7ede4/gopath/src/github.com/minio/minio fetch --quiet minio pull/13381/head:pr13381
+ git -C 13381-0d7ede4/gopath/src/github.com/minio/minio checkout --quiet pr13381
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/13381-0d7ede4/gopath
+ make -C 13381-0d7ede4/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-0d7ede4/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-0d7ede4/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-0d7ede4/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/minio-go/v7 v7.0.15-0.20210928020726-a58653d41dd8
go: downloading github.com/json-iterator/go v1.1.11
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading google.golang.org/api v0.31.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/minio/pkg v1.1.4
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading golang.org/x/sys v0.0.0-20210819135213-f52c844e1c1c
go: downloading github.com/rs/dnscache v0.0.0-20210201191234-295bba877686
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/fatih/color v1.12.0
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/golang-jwt/jwt v3.2.1+incompatible
go: downloading golang.org/x/crypto v0.0.0-20210616213533-5ff15b29337e
go: downloading github.com/minio/kes v0.14.0
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/go-openapi/loads v0.20.2
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/bits-and-blooms/bloom/v3 v3.0.1
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/klauspost/compress v1.13.5
go: downloading github.com/klauspost/reedsolomon v1.9.13
go: downloading github.com/minio/console v0.10.3
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/pierrec/lz4 v2.6.0+incompatible
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/minio/zipindex v0.2.0
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/shirou/gopsutil/v3 v3.21.7
go: downloading github.com/tinylib/msgp v1.1.6-0.20210521143832-0becd170c402
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/yargevad/filepathx v1.0.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.0-beta.4
go: downloading go.etcd.io/etcd/client/v3 v3.5.0-beta.4
go: downloading go.uber.org/atomic v1.7.0
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading go.uber.org/zap v1.16.1-0.20210329175301-c23abee72d19
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/elastic/go-elasticsearch/v7 v7.12.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/nats-io/nats.go v1.11.1-0.20210623165838-4b75fc59ae30
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/klauspost/cpuid/v2 v2.0.6
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/minio/parquet-go v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading go.opencensus.io v0.22.5
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-0d7ede4/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-10-08 12:22 UTC, klauspost reviewed
Overall looks good, but we are bumping this too much. Let's use keyed values.

2021-10-08 12:22 UTC, klauspost commented on cmd/data-usage-cache.go
> +type dataUsageEntryV6 struct {
ok, since you are bumping lets remove `//msgp:tuple dataUsageEntry` and add small keys, like this:

```
type dataUsageEntry struct {
	Children dataUsageHashMap `msg:"ch"`
	// These fields do no include any children.
	Size             int64                `msg:"sz"`
	Objects          uint64               `msg:"os"`
	Versions         uint64               `msg:"vs"` // Versions that are not delete markers.
	ObjSizes         sizeHistogram        `msg:"szs"`
	ReplicationStats *replicationAllStats `msg:"rep,omitempty"`
	AllTierStats     *AllTierStats        `msg:"ats,omitempty"`
	Compacted        bool                 `msg:"c"`
}
```

Same for children we are adding.

2021-10-08 12:22 UTC, klauspost commented on cmd/data-usage-cache.go
> +}
```suggestion
type TierStats struct {
	TotalSize   uint64 `msg:"ts"`
	NumVersions int    `msg:"nv"`
}
```

2021-10-08 19:43 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 13381-ed66c5b/gopath/src/github.com/minio
+ git -C 13381-ed66c5b/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 13381-ed66c5b/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 13381-ed66c5b/gopath/src/github.com/minio/minio fetch --quiet minio pull/13381/head:pr13381
+ git -C 13381-ed66c5b/gopath/src/github.com/minio/minio checkout --quiet pr13381
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/13381-ed66c5b/gopath
+ make -C 13381-ed66c5b/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-ed66c5b/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-ed66c5b/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-ed66c5b/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading github.com/minio/minio-go/v7 v7.0.15-0.20210928020726-a58653d41dd8
go: downloading google.golang.org/api v0.31.0
go: downloading github.com/minio/pkg v1.1.4
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/json-iterator/go v1.1.11
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/fatih/color v1.12.0
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading golang.org/x/sys v0.0.0-20210819135213-f52c844e1c1c
go: downloading github.com/rs/dnscache v0.0.0-20210201191234-295bba877686
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/golang-jwt/jwt v3.2.1+incompatible
go: downloading golang.org/x/crypto v0.0.0-20210616213533-5ff15b29337e
go: downloading github.com/minio/kes v0.14.0
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/go-openapi/loads v0.20.2
go: downloading github.com/bits-and-blooms/bloom/v3 v3.0.1
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/klauspost/compress v1.13.5
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/klauspost/reedsolomon v1.9.13
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/minio/console v0.10.3
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/minio/zipindex v0.2.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/pierrec/lz4 v2.6.0+incompatible
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/shirou/gopsutil/v3 v3.21.7
go: downloading github.com/tinylib/msgp v1.1.6-0.20210521143832-0becd170c402
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/yargevad/filepathx v1.0.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.0-beta.4
go: downloading go.etcd.io/etcd/client/v3 v3.5.0-beta.4
go: downloading go.uber.org/atomic v1.7.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading go.uber.org/zap v1.16.1-0.20210329175301-c23abee72d19
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/elastic/go-elasticsearch/v7 v7.12.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/nats-io/nats.go v1.11.1-0.20210623165838-4b75fc59ae30
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/minio/parquet-go v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/klauspost/cpuid/v2 v2.0.6
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading go.opencensus.io v0.22.5
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-ed66c5b/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-10-08 23:37 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 13381-31ec1fc/gopath/src/github.com/minio
+ git -C 13381-31ec1fc/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 13381-31ec1fc/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 13381-31ec1fc/gopath/src/github.com/minio/minio fetch --quiet minio pull/13381/head:pr13381
+ git -C 13381-31ec1fc/gopath/src/github.com/minio/minio checkout --quiet pr13381
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/13381-31ec1fc/gopath
+ make -C 13381-31ec1fc/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-31ec1fc/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-31ec1fc/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-31ec1fc/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/minio/pkg v1.1.4
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading google.golang.org/api v0.31.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/minio/minio-go/v7 v7.0.15-0.20210928020726-a58653d41dd8
go: downloading github.com/json-iterator/go v1.1.11
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/fatih/color v1.12.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/rs/dnscache v0.0.0-20210201191234-295bba877686
go: downloading golang.org/x/sys v0.0.0-20210819135213-f52c844e1c1c
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/golang-jwt/jwt v3.2.1+incompatible
go: downloading golang.org/x/crypto v0.0.0-20210616213533-5ff15b29337e
go: downloading github.com/minio/kes v0.14.0
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/klauspost/compress v1.13.5
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/klauspost/reedsolomon v1.9.13
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/minio/console v0.10.3
go: downloading github.com/bits-and-blooms/bloom/v3 v3.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/go-openapi/loads v0.20.2
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/minio/zipindex v0.2.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/pierrec/lz4 v2.6.0+incompatible
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/tinylib/msgp v1.1.6-0.20210521143832-0becd170c402
go: downloading github.com/shirou/gopsutil/v3 v3.21.7
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/yargevad/filepathx v1.0.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.0-beta.4
go: downloading go.etcd.io/etcd/client/v3 v3.5.0-beta.4
go: downloading go.uber.org/atomic v1.7.0
go: downloading go.uber.org/zap v1.16.1-0.20210329175301-c23abee72d19
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/elastic/go-elasticsearch/v7 v7.12.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/nats-io/nats.go v1.11.1-0.20210623165838-4b75fc59ae30
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/minio/parquet-go v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/klauspost/cpuid/v2 v2.0.6
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading go.opencensus.io v0.22.5
go: github.com/minio/madmin-go@v1.1.7 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-31ec1fc/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-10-11 11:01 UTC, klauspost requested changes
Nice. Got two minor changes.

2021-10-11 11:01 UTC, klauspost commented on cmd/data-usage-cache.go
> +			due.Compacted = len(due.Children) == 0 && k != d.Info.Name
We shouldn't need to infer this (and will be wrong).
```suggestion
			due.Compacted = v.Compacted
```
(maybe just move it up, no biggie)

2021-10-11 11:01 UTC, klauspost commented on cmd/data-usage-utils.go
> +	TierStats *AllTierStats
This seems to be the convention:
```suggestion
	TierStats *AllTierStats `json:"tierStats,omitempty"`
```

2021-10-12 20:01 UTC, harshavardhana requested changes

2021-10-12 20:01 UTC, harshavardhana commented on cmd/data-usage-cache.go
> +	AllTierStats     *AllTierStats        `msg:"ats,omitempty"`
```suggestion
	AllTierStats     *allTierStats        `msg:"ats,omitempty"`
```

Doesn't need to capitalized is it?

2021-10-13 22:01 UTC, krisis commented
@harshavardhana I intend to include tier usage statistics like `size`, `versions` and `objects` for hot-tier too.

2021-10-13 22:03 UTC, harshavardhana approved these changes

2021-10-14 10:37 UTC, klauspost approved these changes
LGTM

2021-10-14 16:08 UTC, poornas approved these changes

2021-10-18 19:15 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 13381-b660c38/gopath/src/github.com/minio
+ git -C 13381-b660c38/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 13381-b660c38/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 13381-b660c38/gopath/src/github.com/minio/minio fetch --quiet minio pull/13381/head:pr13381
+ git -C 13381-b660c38/gopath/src/github.com/minio/minio checkout --quiet pr13381
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/13381-b660c38/gopath
+ make -C 13381-b660c38/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/madmin-go@v1.1.8 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-b660c38/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.8 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-b660c38/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: github.com/minio/madmin-go@v1.1.8 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-b660c38/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading google.golang.org/api v0.31.0
go: downloading github.com/minio/minio-go/v7 v7.0.15-0.20210928020726-a58653d41dd8
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/minio/pkg v1.1.5
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/json-iterator/go v1.1.11
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/fatih/color v1.12.0
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20210616213533-5ff15b29337e
go: downloading github.com/minio/kes v0.14.0
go: downloading github.com/golang-jwt/jwt v3.2.1+incompatible
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/klauspost/compress v1.13.5
go: downloading github.com/minio/console v0.10.4
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/go-openapi/loads v0.20.2
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/klauspost/reedsolomon v1.9.13
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/bits-and-blooms/bloom/v3 v3.0.1
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/google/uuid v1.1.2
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/minio/zipindex v0.2.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/philhofer/fwd v1.1.1
go: downloading github.com/pierrec/lz4 v2.6.0+incompatible
go: downloading github.com/prometheus/client_golang v1.8.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/shirou/gopsutil/v3 v3.21.7
go: downloading github.com/rs/dnscache v0.0.0-20210201191234-295bba877686
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/tinylib/msgp v1.1.6-0.20210521143832-0becd170c402
go: downloading github.com/yargevad/filepathx v1.0.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.0-beta.4
go: downloading go.etcd.io/etcd/client/v3 v3.5.0-beta.4
go: downloading go.uber.org/atomic v1.7.0
go: downloading golang.org/x/sys v0.0.0-20210819135213-f52c844e1c1c
go: downloading github.com/beevik/ntp v0.3.0
go: downloading go.uber.org/zap v1.16.1-0.20210329175301-c23abee72d19
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/elastic/go-elasticsearch/v7 v7.12.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/nats-io/nats.go v1.11.1-0.20210623165838-4b75fc59ae30
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/klauspost/cpuid/v2 v2.0.6
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/minio/parquet-go v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading go.opencensus.io v0.22.5
go: github.com/minio/madmin-go@v1.1.8 (replaced by ../madmin-go): reading ../madmin-go/go.mod: open /home/mint-auto/mint-auto/13381-b660c38/gopath/src/github.com/minio/madmin-go/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-10-19 09:47 UTC, klauspost commented
Upstream is merged. Can you update go.mod?

2021-10-22 13:37 UTC, krisis commented
Summary of recent updates to this PR,
  - `numObjects` was added to per-tier stats
  - current version of an object is accounted towards `numObjects`
  - admin API to get tier-stats returns zero-values for per-tier stats until they catch up with the ILM transition activity

```
  $ ./mc admin tier info minio-tier
      Tier Name  |API  |Type  |Usage    |Objects  |Versions  
      STANDARD   |s3   |hot   |130 MiB  |1        |1         
      S3TIER-1   |s3   |warm  |130 MiB  |1        |3         
      S3TIER-2   |s3   |warm  |2.8 KiB  |0        |2
```
In the above example, there are two objects in all, each with 3 versions (incl. the current version). Note that `Objects` column for `S3TIER-2` is zero. This indicates that only noncurrent versions have been transitioned to `S3TIER-2`.

2021-10-23 16:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-10-24 01:38 UTC, merged