Add IAM system tests
minio/minio pull request #13487
Opened 2021-10-20 23:05 UTC by donatello

## Description
- For internal IDP user, policy and groups

## Motivation and Context
- Improve test coverage and reduce technical debt.

## How to test this PR?
- No changes to behavior, tests should run in CI automatically.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] enhancement

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [x] Unit tests added/updated

2021-10-20 23:13 UTC, harshavardhana approved these changes

2021-10-21 10:13 UTC, vadmeste requested changes
One comment

2021-10-21 10:13 UTC, vadmeste commented on internal/auth/credentials.go
> +	accessKey, secretKey, err := GenerateCredentials()
You need to return an error here if err != nil

2021-10-21 18:53 UTC, donatello commented on internal/auth/credentials.go
> +	accessKey, secretKey, err := GenerateCredentials()
Good catch! Fixed.

2021-10-22 04:44 UTC, kannappanr approved these changes
LGTM

2021-10-22 08:26 UTC, vadmeste approved these changes
LGTM

2021-10-22 08:33 UTC, merged