Add support for caching multipart in writethrough mode
minio/minio pull request #13507
Opened 2021-10-25 14:35 UTC by poornas

## Description

## Motivation and Context
Allow write through caching for multipart uploads

## How to test this PR?
In gateway mode, enable cache settings and set `MINIO_CACHE_COMMIT` to writeback

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation updated
- [ ] Unit tests added/updated

2021-10-28 11:04 UTC, klauspost requested changes
Great work. A few Pipe+error related fixes.

2021-10-28 11:04 UTC, klauspost commented on cmd/disk-cache.go
> +			wPipe.CloseWithError(perr)
Close the side you are working on.
```suggestion
			rPipe.CloseWithError(perr)
			// Does not fail backend upload.
```

2021-10-28 11:04 UTC, klauspost commented on cmd/disk-cache.go
> +			pipeWriter.CloseWithError(err)
hashReader reads from pipeReader, so close the appropriate:
```suggestion
			pipeReader.CloseWithError(err)
```

2021-10-28 11:04 UTC, klauspost commented on cmd/disk-cache.go
> +			wPipe.CloseWithError(err)
Close the read side, so write gets notified.
```suggestion
			rPipe.CloseWithError(err)
```

2021-10-28 11:04 UTC, klauspost commented on cmd/disk-cache-utils.go
> +	}
```suggestion
	if err == nil && n != len(p) {
		err = io.ErrShortWrite
	}
	if err != nil {
		if !t.pipeClosed {
			t.cacheWriter.CloseWithError(err)
		}
		return
	}
```

2021-10-28 11:04 UTC, klauspost commented on cmd/disk-cache.go
> +	wPipe.Close()
Always close writer end on both, otherwise you risk leaking reader goroutines on errors. Upstream does not guarantee to close both.
```suggestion
	_, err = io.Copy(mwriter, data)
	pipeWriter.CloseWithError(err)
	wPipe.CloseWithError(err)
	if err != nil {
		err = <-errorCh
		return PartInfo{}, err
	}
```

2021-10-28 11:04 UTC, klauspost commented on cmd/disk-cache-utils.go
> +	pipeClosed    bool
Technically you don't need to keep track of this. The first error is kept and you can call multiple times.

2021-10-28 11:04 UTC, klauspost commented on cmd/disk-cache-backend.go
> +			pw.CloseWithError(err)
```suggestion
			pr.CloseWithError(err)
```

2021-10-28 19:21 UTC, poornas commented on cmd/disk-cache.go
> +			pipeWriter.CloseWithError(err)
Thanks, fixed

2021-10-29 13:09 UTC, klauspost requested changes
Sorry missed one in the first run-through.

2021-10-29 13:09 UTC, klauspost commented on cmd/disk-cache-backend.go
> +			pw.CloseWithError(err)
This goroutine operates on the writer.
```suggestion
			pr.CloseWithError(err)
```

2021-10-29 13:09 UTC, klauspost commented on cmd/disk-cache-backend.go
> +			pr.CloseWithError(err)
```suggestion
			pw.CloseWithError(err)
```

2021-10-29 19:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-10-30 03:02 UTC, harshavardhana requested changes

2021-10-30 03:02 UTC, harshavardhana commented on cmd/disk-cache.go
> +		migMutex:           sync.Mutex{},
```suggestion
		migMutex:           sync.Mutex{},
```

This is not needed

2021-10-30 03:02 UTC, harshavardhana commented on cmd/disk-cache.go
> +
should we not be checking for `diskSpaceAvailable` here as well? to make sure we can save the multipart in the first place?

2021-10-30 03:02 UTC, harshavardhana commented on cmd/disk-cache.go
> +	// fetch from backend if there is no space on cache drive
Update the comment..

2021-10-30 03:02 UTC, harshavardhana commented on docs/disk-caching/DESIGN.md
> +
shouldn't this be more meaningful with `MINIO_CACHE_COMMIT_MODE` ?   .. I see _CACHE_COMMIT is already present how about we change that to _MODE and deprecate just _COMMIT

2021-10-30 03:02 UTC, harshavardhana commented on docs/disk-caching/DESIGN.md
> +Note that `MINIO_CACHE_COMMIT` also has a setting of `writeback` which allows staging single uploads in cache before committing to remote. However for consistency reasons, staging uploads in cache is
```suggestion
NOTE:  `MINIO_CACHE_COMMIT` also has value of `writeback` which allows staging single uploads in cache before committing to remote. However, for consistency reasons, staging uploads in the cache are not permitted for multipart uploads. Partially cached stale uploads older than 24 hours are automatically cleaned up.
```

2021-10-30 09:56 UTC, klauspost approved these changes
LGTM

2021-11-01 13:49 UTC, poornas commented on cmd/disk-cache.go
> +
this is done in PutObjectPart which has size. If in the middle of upload we run out of space, caching is aborted

2021-11-01 14:06 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-01 15:10 UTC, harshavardhana approved these changes

2021-11-01 15:11 UTC, harshavardhana approved these changes

2021-11-01 15:11 UTC, merged