Update README.md prometheus
minio/minio pull request #13514
Opened 2021-10-26 12:09 UTC by titansmc

## Description
Make users aware that prometheus will add the port to the host header,

## Motivation and Context
Lack of documentation

## Checklist:
- [ x] Documentation updated

2021-10-26 15:14 UTC, harshavardhana requested changes

2021-10-26 15:14 UTC, harshavardhana commented on docs/metrics/prometheus/README.md
> +In case you are running MiniIO nodes behind a proxy (like HAProxy), consider adjusting the acl rules to match the header, since Prometheus will always add port to the hostname like `hostname:port`.
Can you explain what this is ?

// cc @eco-minio @ravindk89

2021-10-26 15:39 UTC, titansmc commented on docs/metrics/prometheus/README.md
> +In case you are running MiniIO nodes behind a proxy (like HAProxy), consider adjusting the acl rules to match the header, since Prometheus will always add port to the hostname like `hostname:port`.
so when running Minio behind a LB like HAProxy, prometheus scraper sends the header `Host: server.domain.com:port` , which might not match the rule that you have in your Load Balancer, so you might need to add another rule to match that header too. Regular requests from `mc` or web interface will have `Host: server.domain.com`

2021-10-26 16:02 UTC, ravindk89 commented on docs/metrics/prometheus/README.md
> +In case you are running MiniIO nodes behind a proxy (like HAProxy), consider adjusting the acl rules to match the header, since Prometheus will always add port to the hostname like `hostname:port`.
I think we want those explicit details / examples here if we want to document this case. Also guessing this might apply in general to any network control plane that has strict routing controls. Minor concern that this kind of documentation can lead to "tell me how to do the <thing>", which lends itself to scope creep over time (we are not an authority on network control), but this level of detail is probably OK.

Spitballing, not completely familiar with this knowledge area so might not be 100% accurate here.

"Prometheus sets the ``Host`` header to ``domain:port`` as part of HTTP operations against the MinIO metrics endpoint. For MinIO deployments behind a load balancer, reverse proxy, or other control plane (HAProxy, nginx, pfsense, opnsense, etc.), ensure the network service supports routing these requests to the deployment."

Or something along those lines. I'm inclined to not specify "ACL rules" because that might not be the only solution here, and it also begs the question of "what should my ACL look like"

2021-10-26 16:11 UTC, titansmc commented on docs/metrics/prometheus/README.md
> +In case you are running MiniIO nodes behind a proxy (like HAProxy), consider adjusting the acl rules to match the header, since Prometheus will always add port to the hostname like `hostname:port`.
You seem to have described it better than me. So for haproxy I had to add:
```
acl is_s3 hdr(host) -i s3.domain.com
use_backend s3_ssl_back if is_s3

acl is_s3 hdr(host) -i s3.domain.com:443
use_backend s3_ssl_back if is_s3
```
So the second request would catch only the prometheus probe.

2021-10-26 17:07 UTC, ravindk89 commented on docs/metrics/prometheus/README.md
> +In case you are running MiniIO nodes behind a proxy (like HAProxy), consider adjusting the acl rules to match the header, since Prometheus will always add port to the hostname like `hostname:port`.
OK - feel free to use what i wrote or tweak slightly. I would prefer not to get into specific configs for specific products, as we cannot meaningfully keep those maintained over time.

2021-10-27 06:46 UTC, titansmc commented on docs/metrics/prometheus/README.md
> +In case you are running MiniIO nodes behind a proxy (like HAProxy), consider adjusting the acl rules to match the header, since Prometheus will always add port to the hostname like `hostname:port`.
ok, I think now I have added the second commit which modifies the initial comment.

2021-11-02 05:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-02 06:01 UTC, harshavardhana approved these changes

2021-11-02 19:26 UTC, ravindk89 approved these changes

2021-11-02 19:27 UTC, merged