fix(AuditLog): Fix log panic while st is nil
minio/minio pull request #13510
Opened 2021-10-26 06:55 UTC by MoonJustry

## Description
Fix st(*logger.ResponseWriter) nil pointer bug

## Motivation and Context

## How to test this PR?
For example, client put request with Accept-Encoding：gzip，the gzhttp.ResponseWriter will overwrite logger.ResponseWriter, then panic.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-10-26 12:56 UTC, klauspost requested changes
Just one change. Rest LGTM.

2021-10-26 12:56 UTC, klauspost commented on internal/logger/audit.go
> +			st = v.ResponseWriter.(*ResponseWriter)
Lets remove the unchecked assert:
```suggestion
			if rw, ok = v.ResponseWriter.(*ResponseWriter); ok {
				st = rw
			}
```

2021-10-26 13:42 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-10-26 14:14 UTC, vadmeste approved these changes
LGTM, Thanks!

2021-10-27 08:42 UTC, klauspost approved these changes
LGTM. Thanks!

2021-10-27 16:29 UTC, merged