Move all IAM storage functionality into iam store type
minio/minio pull request #13541
Opened 2021-10-29 23:55 UTC by donatello

## Description

- Ensure all actions accessing storage lock properly.

- Behavior change: policies can be deleted only when they are not associated
with any live credentials.

- Fix a race in Delete User.

## Motivation and Context

The second commit in this PR has a test that can reproduce the race on master (just cherry pick that commit). The refactor is try and ensure that no further races can happen, and to isolate code accessing IAM storage into separate functions for easier review and auditing for races.

One behavior change is introduced. Policies attached to users may no longer be deleted. They must be unattached to any users to be able to delete them. This is similar to AWS policy deletion [behavior](https://docs.aws.amazon.com/IAM/latest/APIReference/API_DeletePolicy.html). 

## How to test this PR?

Usual way with internal IDP, openid and ldap.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [x] Unit tests added/updated

2021-10-30 00:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#d2091e41-888d-4a2b-b4a2-41dc17a18fbe) |
| mint-gateway-nas.sh | :x: [more...](#e5a34196-4a89-4599-ad3b-4126382348fb) |
<a name="e5a34196-4a89-4599-ad3b-4126382348fb"></a>
### 13541-70b53c6/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:30097
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-s9qj6l1wmvvhz3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 236,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s8:30097/aws-sdk-go-test-s9qj6l1wmvvhz3\": dial tcp 15.15.15.8:30097: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-java tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-s9qj6l1wmvvhz3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 236,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s8:30097/aws-sdk-go-test-s9qj6l1wmvvhz3\": dial tcp 15.15.15.8:30097: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-php tests ... FAILED in 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-s9qj6l1wmvvhz3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 236,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s8:30097/aws-sdk-go-test-s9qj6l1wmvvhz3\": dial tcp 15.15.15.8:30097: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-ruby tests ... FAILED in 4 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 3116.34,
  "error": "Failed to open TCP connection to minio-k8s8:30097 (Connection refused - connect(2) for \"minio-k8s8\" port 30097)",
  "status": "FAIL"
}
(1/16) Running awscli tests ... FAILED in 6 seconds
{"name": "awscli", "duration": 4162, "function": "make_bucket\n", "status": "FAIL", "error": "Could not connect to the endpoint URL: "http://minio-k8s8:30097/awscli-mint-test-bucket-13346""}
(1/16) Running healthcheck tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": null,
  "duration": 1,
  "error": "Get \"http://minio-k8s8:30097/minio/health/live\": dial tcp 15.15.15.8:30097: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(1/16) Running mc tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": null,
  "duration": 1,
  "error": "Get \"http://minio-k8s8:30097/minio/health/live\": dial tcp 15.15.15.8:30097: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(1/16) Running minio-dotnet tests ... done in 46 seconds
(2/16) Running minio-go tests ... FAILED in 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-ub2gcolypk2hibo0",
    "region": "eu-west-1"
  },
  "duration": 10226,
  "error": "Put \"http://minio-k8s8:30097/minio-go-test-ub2gcolypk2hibo0/\": dial tcp 15.15.15.8:30097: connect: connection refused",
  "function": "MakeBucket(bucketName, region)",
  "message": "MakeBucket failed",
  "name": "minio-go: testMakeBucketErrorV2",
  "status": "FAIL"
}
(2/16) Running minio-java tests ... FAILED in 1 seconds
{
  "name": "minio-java",
  "function": "makeBucket()",
  "args": "[basic check]",
  "duration": 61,
  "status": "FAIL",
  "error": "java.net.ConnectException: Failed to connect to minio-k8s8/15.15.15.8:30097 >>> [okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297), okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207), okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226), okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106), okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74), okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.MinioClient.makeBucket(MinioClient.java:1207), FunctionalTest.testBucketApi(FunctionalTest.java:442), FunctionalTest.testBucketApiCases(FunctionalTest.java:470), FunctionalTest.makeBucket(FunctionalTest.java:501), FunctionalTest.runBucketTests(FunctionalTest.java:3645), FunctionalTest.runTests(FunctionalTest.java:3719), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(2/16) Running minio-js tests ... FAILED in 1 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 1008,
  "status": "FAIL",
  "error": "Error: connect ECONNREFUSED 15.15.15.8:30097 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)"
}
(2/16) Running minio-py tests ... FAILED in 9 seconds
{
  "name": "minio-py:test_make_bucket_default_region",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-1e7cd224-eae2-47d5-a34f-6dfcdfbe15ba",
    "location": "default value ('us-east-1')"
  },
  "message": "HTTPConnectionPool(host='minio-k8s8', port=30097): Max retries exceeded with url: /minio-py-test-1e7cd224-eae2-47d5-a34f-6dfcdfbe15ba (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f0fefd3d828>: Failed to establish a new connection: [Errno 111] Connection refused',))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connection.py\", line 170, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py\", line 96, in create_connection\n    raise err\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py\", line 86, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 394, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File \ [...]

2021-10-30 00:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#9c3669e4-c3e9-4bca-a17e-7184564eaab2) |
| mint-gateway-nas.sh | :x: [more...](#6583d771-6be8-49e8-80e8-b612bbd473dd) |
<a name="6583d771-6be8-49e8-80e8-b612bbd473dd"></a>
### 13541-328b5b3/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:31993
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-lggm44cps6yf59",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 264,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s2:31993/aws-sdk-go-test-lggm44cps6yf59\": dial tcp 15.15.15.2:31993: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-java tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-lggm44cps6yf59",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 264,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s2:31993/aws-sdk-go-test-lggm44cps6yf59\": dial tcp 15.15.15.2:31993: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-php tests ... FAILED in 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-lggm44cps6yf59",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 264,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s2:31993/aws-sdk-go-test-lggm44cps6yf59\": dial tcp 15.15.15.2:31993: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-ruby tests ... FAILED in 4 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 3123.79,
  "error": "Failed to open TCP connection to minio-k8s2:31993 (Connection refused - connect(2) for \"minio-k8s2\" port 31993)",
  "status": "FAIL"
}
(1/16) Running awscli tests ... FAILED in 9 seconds
{"name": "awscli", "duration": 7230, "function": "make_bucket\n", "status": "FAIL", "error": "Could not connect to the endpoint URL: "http://minio-k8s2:31993/awscli-mint-test-bucket-31884""}
(1/16) Running healthcheck tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": null,
  "duration": 1,
  "error": "Get \"http://minio-k8s2:31993/minio/health/live\": dial tcp 15.15.15.2:31993: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(1/16) Running mc tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": null,
  "duration": 1,
  "error": "Get \"http://minio-k8s2:31993/minio/health/live\": dial tcp 15.15.15.2:31993: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(1/16) Running minio-dotnet tests ... done in 44 seconds
(2/16) Running minio-go tests ... FAILED in 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-iqkj1vsuhi5pggtq",
    "region": "eu-west-1"
  },
  "duration": 10226,
  "error": "Put \"http://minio-k8s2:31993/minio-go-test-iqkj1vsuhi5pggtq/\": dial tcp 15.15.15.2:31993: connect: connection refused",
  "function": "MakeBucket(bucketName, region)",
  "message": "MakeBucket failed",
  "name": "minio-go: testMakeBucketErrorV2",
  "status": "FAIL"
}
(2/16) Running minio-java tests ... FAILED in 1 seconds
{
  "name": "minio-java",
  "function": "makeBucket()",
  "args": "[basic check]",
  "duration": 74,
  "status": "FAIL",
  "error": "java.net.ConnectException: Failed to connect to minio-k8s2/15.15.15.2:31993 >>> [okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297), okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207), okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226), okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106), okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74), okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.MinioClient.makeBucket(MinioClient.java:1207), FunctionalTest.testBucketApi(FunctionalTest.java:442), FunctionalTest.testBucketApiCases(FunctionalTest.java:470), FunctionalTest.makeBucket(FunctionalTest.java:501), FunctionalTest.runBucketTests(FunctionalTest.java:3645), FunctionalTest.runTests(FunctionalTest.java:3719), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(2/16) Running minio-js tests ... FAILED in 3 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 1016,
  "status": "FAIL",
  "error": "Error: connect ECONNREFUSED 15.15.15.2:31993 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)"
}
(2/16) Running minio-py tests ... FAILED in 8 seconds
{
  "name": "minio-py:test_make_bucket_default_region",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-40061ca4-6b3e-4155-bff5-7570647c22cd",
    "location": "default value ('us-east-1')"
  },
  "message": "HTTPConnectionPool(host='minio-k8s2', port=31993): Max retries exceeded with url: /minio-py-test-40061ca4-6b3e-4155-bff5-7570647c22cd (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f386290c898>: Failed to establish a new connection: [Errno 111] Connection refused',))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connection.py\", line 170, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py\", line 96, in create_connection\n    raise err\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py\", line 86, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 394, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File \ [...]

2021-10-30 01:51 UTC, harshavardhana commented
> * Behavior change: policies can be deleted only when they are not associated
>   with any live credentials.

This is a breaking change @donatello right?

2021-10-30 01:52 UTC, harshavardhana requested changes
@donatello gateway implementations don't seem to work with this change - PTAL. 

> Fix a race in Delete User - the race could cause deleted users to re-appear as valid working credentials.

Also can this PR be sent separately? not as part of a large refactor?

2021-10-30 02:05 UTC, donatello commented
> @donatello gateway implementations don't seem to work with this change - PTAL. 
> 
> > Fix a race in Delete User - the race could cause deleted users to re-appear as valid working credentials.
> 
> Also can this PR be sent separately? not as part of a large refactor?

Sure I can send separately.

2021-10-30 07:31 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#fae5fe61-2b08-4f8e-8b77-ae5f1e24b7ea) |
| mint-gateway-nas.sh | :x: [more...](#ca7209d7-2302-41ba-b8d0-8d9d3f7072b3) |
<a name="ca7209d7-2302-41ba-b8d0-8d9d3f7072b3"></a>
### 13541-d362ae9/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:32113
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-53ue3d1p4e9tzx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 320,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s1:32113/aws-sdk-go-test-53ue3d1p4e9tzx\": dial tcp 15.15.15.1:32113: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-java tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-53ue3d1p4e9tzx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 320,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s1:32113/aws-sdk-go-test-53ue3d1p4e9tzx\": dial tcp 15.15.15.1:32113: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-php tests ... FAILED in 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-53ue3d1p4e9tzx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 320,
  "error": "RequestError: send request failed\ncaused by: Put \"http://minio-k8s1:32113/aws-sdk-go-test-53ue3d1p4e9tzx\": dial tcp 15.15.15.1:32113: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/16) Running aws-sdk-ruby tests ... FAILED in 5 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 4140.11,
  "error": "Failed to open TCP connection to minio-k8s1:32113 (Connection refused - connect(2) for \"minio-k8s1\" port 32113)",
  "status": "FAIL"
}
(1/16) Running awscli tests ... FAILED in 12 seconds
{"name": "awscli", "duration": 10293, "function": "make_bucket\n", "status": "FAIL", "error": "Could not connect to the endpoint URL: "http://minio-k8s1:32113/awscli-mint-test-bucket-4555""}
(1/16) Running healthcheck tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": null,
  "duration": 1,
  "error": "Get \"http://minio-k8s1:32113/minio/health/live\": dial tcp 15.15.15.1:32113: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(1/16) Running mc tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": null,
  "duration": 1,
  "error": "Get \"http://minio-k8s1:32113/minio/health/live\": dial tcp 15.15.15.1:32113: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(1/16) Running minio-dotnet tests ... done in 44 seconds
(2/16) Running minio-go tests ... FAILED in 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-bdxoonfflwoavz00",
    "region": "eu-west-1"
  },
  "duration": 10230,
  "error": "Put \"http://minio-k8s1:32113/minio-go-test-bdxoonfflwoavz00/\": dial tcp 15.15.15.1:32113: connect: connection refused",
  "function": "MakeBucket(bucketName, region)",
  "message": "MakeBucket failed",
  "name": "minio-go: testMakeBucketErrorV2",
  "status": "FAIL"
}
(2/16) Running minio-java tests ... FAILED in 1 seconds
{
  "name": "minio-java",
  "function": "makeBucket()",
  "args": "[basic check]",
  "duration": 62,
  "status": "FAIL",
  "error": "java.net.ConnectException: Failed to connect to minio-k8s1/15.15.15.1:32113 >>> [okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297), okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207), okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226), okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106), okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74), okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.S3Base.execute(S3Base.java:529), io.minio.MinioClient.makeBucket(MinioClient.java:1207), FunctionalTest.testBucketApi(FunctionalTest.java:442), FunctionalTest.testBucketApiCases(FunctionalTest.java:470), FunctionalTest.makeBucket(FunctionalTest.java:501), FunctionalTest.runBucketTests(FunctionalTest.java:3645), FunctionalTest.runTests(FunctionalTest.java:3719), FunctionalTest.main(FunctionalTest.java:3864)]"
}
(2/16) Running minio-js tests ... FAILED in 2 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 1016,
  "status": "FAIL",
  "error": "Error: connect ECONNREFUSED 15.15.15.1:32113 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)"
}
(2/16) Running minio-py tests ... FAILED in 9 seconds
{
  "name": "minio-py:test_make_bucket_default_region",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-1fa85a83-6e00-48f2-a2a8-0b6aca6ea7bf",
    "location": "default value ('us-east-1')"
  },
  "message": "HTTPConnectionPool(host='minio-k8s1', port=32113): Max retries exceeded with url: /minio-py-test-1fa85a83-6e00-48f2-a2a8-0b6aca6ea7bf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f48a2e19898>: Failed to establish a new connection: [Errno 111] Connection refused',))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connection.py\", line 170, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py\", line 96, in create_connection\n    raise err\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py\", line 86, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 706, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 394, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File  [...]

2021-10-30 09:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-01 10:28 UTC, vadmeste approved these changes
LGTM

2021-11-01 18:57 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-01 19:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-01 22:08 UTC, donatello commented
> > * Behavior change: policies can be deleted only when they are not associated
> >   with any live credentials.
> 
> This is a breaking change @donatello right?

It shouldn't break anything as it only prevents a canned/named policy from being deleted when it is associated with an existing user - this is similar to AWS, and should lead to less confusion if a policy is deletion is the reason when some credentials do not work.

2021-11-01 22:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-02 04:57 UTC, harshavardhana approved these changes

2021-11-02 04:58 UTC, merged