cache:fix commit lookup in config
minio/minio pull request #13551
Opened 2021-11-01 17:56 UTC by poornas

## Description

## Motivation and Context

## How to test this PR?
Starting disk cache with MINIO_CACHE_AFTER settings should work

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-11-01 18:01 UTC, harshavardhana requested changes

2021-11-01 18:01 UTC, harshavardhana commented on internal/config/cache/lookup.go
> +		if cfg.After > 0 && cfg.CacheCommitMode != "writethrough" {
can you have constants for `"writethrough"` and `"writeback"`

2021-11-01 18:34 UTC, harshavardhana approved these changes

2021-11-01 19:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-01 22:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-01 22:16 UTC, harshavardhana requested changes
```
=== RUN   TestComputeActions/#22
    lifecycle_test.go:429: Expected action: `TransitionAction`, got: `NoneAction`
=== RUN   TestComputeActions/#23
    lifecycle_test.go:429: Expected action: `TransitionVersionAction`, got: `NoneAction`
--- FAIL: TestComputeActions (0.00s)
```

Can you check these failures? @poornas @krisis

2021-11-02 05:21 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-02 15:12 UTC, harshavardhana approved these changes

2021-11-02 20:04 UTC, harshavardhana reviewed
PTAL @krisis

2021-11-02 21:05 UTC, krisis approved these changes

2021-11-02 21:20 UTC, merged