Move all IAM storage functionality into iam store type
minio/minio pull request #13567
Opened 2021-11-02 23:37 UTC by donatello

## Description
This reverts commit 091a7ae3590a510c51cd84981dccd6d45879b1d6.

- Ensure all actions accessing storage lock properly.

- Behavior change: policies can be deleted only when they
  are not associated with any active credentials.

Also adds fix for accidental canned policy removal

## Motivation and Context

The refactor is try and ensure that no further races can happen, and to isolate code accessing IAM storage into separate functions for easier review and auditing for races.

One behavior change is introduced. Policies attached to users may no longer be deleted. They must be unattached to any users to be able to delete them. This is similar to AWS policy deletion behavior.

## How to test this PR?
Usual way with internal IDP, openid and ldap.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [x] Unit tests added/updated

2021-11-02 23:37 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 13567-65efd6c/gopath/src/github.com/minio
+ git -C 13567-65efd6c/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 13567-65efd6c/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 13567-65efd6c/gopath/src/github.com/minio/minio fetch --quiet minio pull/13567/head:pr13567
+ git -C 13567-65efd6c/gopath/src/github.com/minio/minio checkout --quiet pr13567
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/13567-65efd6c/gopath
+ make -C 13567-65efd6c/gopath/src/github.com/minio/minio --quiet
go: github.com/minio/pkg@v1.1.5 (replaced by ../minio-pkg): reading ../minio-pkg/go.mod: open /home/mint-auto/mint-auto/13567-65efd6c/gopath/src/github.com/minio/minio-pkg/go.mod: no such file or directory
go: github.com/minio/pkg@v1.1.5 (replaced by ../minio-pkg): reading ../minio-pkg/go.mod: open /home/mint-auto/mint-auto/13567-65efd6c/gopath/src/github.com/minio/minio-pkg/go.mod: no such file or directory
go: github.com/minio/pkg@v1.1.5 (replaced by ../minio-pkg): reading ../minio-pkg/go.mod: open /home/mint-auto/mint-auto/13567-65efd6c/gopath/src/github.com/minio/minio-pkg/go.mod: no such file or directory
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/madmin-go v1.1.10
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/colinmarc/hdfs/v2 v2.2.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/minio/minio-go/v7 v7.0.15
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/json-iterator/go v1.1.12
go: downloading google.golang.org/api v0.31.0
go: downloading github.com/rs/dnscache v0.0.0-20210201191234-295bba877686
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/golang-jwt/jwt v3.2.2+incompatible
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading golang.org/x/sys v0.0.0-20211020174200-9d6173849985
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/minio/kes v0.14.0
go: downloading golang.org/x/crypto v0.0.0-20210921155107-089bfa567519
go: downloading github.com/klauspost/compress v1.13.6
go: downloading github.com/Shopify/sarama v1.27.2
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/bits-and-blooms/bloom/v3 v3.0.1
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/VividCortex/ewma v1.1.1
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/minio/console v0.11.1-0.20211028015028-610c8a46533c
go: downloading github.com/go-openapi/loads v0.20.2
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading github.com/klauspost/reedsolomon v1.9.13
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/minio/zipindex v0.2.1
go: downloading github.com/minio/selfupdate v0.3.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/philhofer/fwd v1.1.2-0.20210722190033-5c56ac6d0bb9
go: downloading github.com/pierrec/lz4 v2.6.0+incompatible
go: downloading github.com/prometheus/client_golang v1.11.0
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/tinylib/msgp v1.1.7-0.20211026165309-e818a1881b0e
go: downloading github.com/shirou/gopsutil/v3 v3.21.9
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/yargevad/filepathx v1.0.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading go.etcd.io/etcd/client/v3 v3.5.0
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.0
go: downloading github.com/elastic/go-elasticsearch/v7 v7.12.0
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: downloading golang.org/x/time v0.0.0-20210220033141-f8bda1e9f3ba
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/lib/pq v1.9.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/nats-io/nats.go v1.11.1-0.20210623165838-4b75fc59ae30
go: downloading github.com/nats-io/stan.go v0.8.3
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/go-ldap/ldap/v3 v3.2.4
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/ncw/directio v1.0.5
go: downloading go.uber.org/zap v1.19.1
go: downloading github.com/minio/simdjson-go v0.2.1
go: downloading github.com/minio/parquet-go v1.0.0
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading golang.org/x/net v0.0.0-20211020060615-d418f374d309
go: downloading github.com/klauspost/cpuid/v2 v2.0.9
go: downloading go.opencensus.io v0.22.5
go: github.com/minio/pkg@v1.1.5 (replaced by ../minio-pkg): reading ../minio-pkg/go.mod: open /home/mint-auto/mint-auto/13567-65efd6c/gopath/src/github.com/minio/minio-pkg/go.mod: no such file or directory
make: *** [build] Error 1

```

2021-11-02 23:38 UTC, donatello commented
This change needs https://github.com/minio/pkg/pull/14 to be merged first.

2021-11-03 00:14 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-03 19:36 UTC, poornas requested changes, later dismissed

2021-11-03 19:36 UTC, poornas commented on cmd/iam-store.go
> +	return set.CreateStringSet(policies...)
```suggestion
      policies := mp.toSlice()
	return set.CreateStringSet(policies...)
```

2021-11-03 19:36 UTC, poornas commented on cmd/iam-store.go
> +	return c, ok
```suggestion
	return cache.iamUsersMap[user]
```

2021-11-03 19:36 UTC, poornas commented on cmd/iam-store.go
> +		return v, ok
```suggestion
		return cache.iamGroupPolicyMap[name]
```

2021-11-03 19:36 UTC, poornas commented on cmd/iam-store.go
> +	return v, ok
```suggestion
	return cache.iamUserPolicyMap[name]
```

2021-11-03 19:53 UTC, donatello commented on cmd/iam-store.go
> +	return c, ok
It doesn't work - default is single value return - e.g. https://play.golang.org/p/nmWil3S88LO

2021-11-03 19:53 UTC, donatello commented on cmd/iam-store.go
> +		return v, ok
It doesn't work - default is single value return - e.g. https://play.golang.org/p/nmWil3S88LO

2021-11-03 19:53 UTC, donatello commented on cmd/iam-store.go
> +	return v, ok
It doesn't work - default is single value return - e.g. https://play.golang.org/p/nmWil3S88LO

2021-11-03 20:01 UTC, donatello commented on cmd/iam-store.go
> +	return set.CreateStringSet(policies...)
Fixed!

2021-11-03 20:12 UTC, poornas commented
@donatello, this PR is still exposing a bug in site replication - service account does not have "s3:ListBucket" permission and buckets are not created in the target sites
```
Requested sites were configured for replication successfully.
Site replication error(s): Site sitec (ff641af0-5c9f-4ca8-a839-b2cfe3d2c564): Access Denied.; Site siteb (7544a945-df3a-4a0a-95d8-2d46112600ac): Access Denied.
mc: <ERROR> Unable to make bucket `sitea/bucket`. Your previous request to create the named bucket succeeded and you already own it.
```

2021-11-03 20:51 UTC, donatello commented
> @donatello, this PR is still exposing a bug in site replication - service account does not have "s3:ListBucket" permission and buckets are not created in the target sites
> 
> ```
> Requested sites were configured for replication successfully.
> Site replication error(s): Site sitec (ff641af0-5c9f-4ca8-a839-b2cfe3d2c564): Access Denied.; Site siteb (7544a945-df3a-4a0a-95d8-2d46112600ac): Access Denied.
> mc: <ERROR> Unable to make bucket `sitea/bucket`. Your previous request to create the named bucket succeeded and you already own it.
> ```

CHecking, this was working earlier...

2021-11-03 22:17 UTC, donatello commented
@poornas - PTAL the issue is fixed - it was related a bug fixed here https://github.com/minio/pkg/pull/15 but forgot to update the dep in go.mod for this PR.

2021-11-03 22:44 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-04 02:20 UTC, poornas approved these changes
LGTM

2021-11-04 02:47 UTC, harshavardhana approved these changes

2021-11-04 02:47 UTC, merged