Add LDAP STS tests and workflow for CI
minio/minio pull request #13576
Opened 2021-11-03 19:39 UTC by donatello

## Description
- Runs LDAP tests with openldap container on GH Actions CI

## Motivation and Context
Add LDAP integration tests

## How to test this PR?
No behavior change.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] More Tests 

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [x] Unit tests added/updated

2021-11-03 21:04 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-03 21:14 UTC, harshavardhana approved these changes

2021-11-03 21:14 UTC, harshavardhana commented on .github/workflows/ldap-integration.yaml
> +        image: donatello/openldap:1
we can push this to quay.io/minio/openldap - do you want to do that?  - just pushed `quay.io/minio/openldap`

2021-11-03 21:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-03 21:40 UTC, harshavardhana requested changes

2021-11-03 21:40 UTC, harshavardhana commented on .github/workflows/ldap-integration.yaml
> +        image: donatello/openldap:1
```suggestion
        image: quay.io/minio/openldap
```

2021-11-03 21:40 UTC, harshavardhana approved these changes

2021-11-03 21:46 UTC, donatello commented on .github/workflows/ldap-integration.yaml
> +        image: donatello/openldap:1
👍🏾

2021-11-03 22:00 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-04 02:50 UTC, harshavardhana approved these changes
Nice 🍰

2021-11-04 15:16 UTC, merged