sts: always verify the key usage of client certificates
minio/minio pull request #13583
Opened 2021-11-04 14:14 UTC by aead

## Description
This commit makes the MinIO server behavior more consistent
w.r.t. key usage verification.

When MinIO verifies the client certificates it also checks
that the client certificate is valid of client authentication
(or any (i.e. wildcard) usage).

However, the MinIO server used to not verify the client key usage
when client certificate verification was disabled.
Now, the MinIO server verifies the client key usage even when
client certificate verification has been disabled. This makes
the MinIO behavior more consistent from a client perspective.

Now, a client certificate has to be valid for client authentication
in all cases.

## Motivation and Context
TLS, STS

## How to test this PR?
https://github.com/minio/minio/blob/master/docs/sts/tls.md

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-11-04 14:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-04 15:18 UTC, harshavardhana requested changes

2021-11-04 15:18 UTC, harshavardhana commented on cmd/sts-handlers.go
> +				validKeyUsage = true
break; 

Is perhaps missing here.

2021-11-04 18:53 UTC, harshavardhana requested changes

2021-11-04 18:53 UTC, harshavardhana commented on cmd/sts-handlers.go
> +				validKeyUsage = true
```suggestion
				validKeyUsage = true
				break
```

2021-11-04 19:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-04 20:26 UTC, harshavardhana approved these changes

2021-11-05 09:05 UTC, vadmeste approved these changes
LGTM

2021-11-05 09:16 UTC, merged