do not flush if Write() failed
minio/minio pull request #13597
Opened 2021-11-05 23:00 UTC by harshavardhana

## Description
do not flush if Write() failed

## Motivation and Context
Go might reset the internal http.ResponseWriter() to `nil`
after Write() failure, so due to some timing by the time
we get to Flush() the underlying response writer might be
empty.

## How to test this PR?
Really hard to reproduce crash - this is the place https://github.com/golang/go/blob/a59e33224e42d60a97fa720a45e1b74eb6aaa3d0/src/net/http/server.go#L1697 that can get triggered by this situation. 

The theory is that w.Write() fails which in turn internally requires that `w` will be `nil` - this might have problems because once there is an error there is no need to further Flush() errors. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-11-06 00:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-06 01:01 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-07 11:18 UTC, klauspost commented
@harshavardhana The Write itself will AFAICT cause the same crash, since the root cause is a race. The root cause is when the Write/Flush happens on another goroutine after the ResponseWriter has returned.

This doesn't really fix any problems AFAICT. The problem is that on a panic the goroutine that does the writes isn't closed. We must defer CloseWithError on panic operations when writes are happening async.

2021-11-07 16:02 UTC, harshavardhana commented
> @harshavardhana The Write itself will AFAICT cause the same crash, since the root cause is a race. The root cause is when the Write/Flush happens on another goroutine after the ResponseWriter has returned.
> 
> This doesn't really fix any problems AFAICT. The problem is that on a panic the goroutine that does the writes isn't closed. We must defer CloseWithError on panic operations when writes are happening async.

I tried to look for this is what I can find. Because the situation is racy.. however the changes in this PR also make sense IMO to avoid.

i.e never to ignore the errors underneath as implementations may choose to nil the connection underneath.

2021-11-07 17:03 UTC, harshavardhana commented
> @harshavardhana The Write itself will AFAICT cause the same crash, since the root cause is a race. The root cause is when the Write/Flush happens on another goroutine after the ResponseWriter has returned.
> 
> This doesn't really fix any problems AFAICT. The problem is that on a panic the goroutine that does the writes isn't closed. We must defer CloseWithError on panic operations when writes are happening async.

One more additional thing to remember, the crash reported indeed happened in Flush() not a Write()

```
panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4dc110]

goroutine 348587122 [running]: bufio.(*Writer).Available(...) bufio/bufio.go:624 bufio.(*Writer).Write(0x0, 0xc0028c7680, 0x3, 0x240, 0x1, 0x1, 0x0) bufio/bufio.go:634 +0x70 fmt.Fprintf(0x27e5ca0, 0x0, 0x1f77496, 0x4, 0xc00dcbcdc0, 0x1, 0x1, 0x0, 0xc00dcbcec8, 0x44c88e) fmt/print.go:205 +0xa5 net/http.(*chunkWriter).Write(0xc00baa4820, 0xc00210b800, 0x1, 0x800, 0x7fb91a7b4eb0, 0x14aebf1, 0xc00baa47e0) net/http/server.go:377 +0x20d bufio.(*Writer).Flush(0xc017eda640, 0xc00dcbce00, 0x7fb91a7b4eb0) bufio/bufio.go:607 +0x7b net/http.(*response).Flush(0xc00baa47e0) net/http/server.go:1681 +0x35 github.com/minio/minio/cmd/http/stats.(*OutgoingTrafficMeter).Flush(0xc0310c7020) github.com/minio/minio/cmd/http/stats/http-traffic-recorder.go:58 +0x59 github.com/minio/minio/cmd/logger.(*ResponseWriter).Flush(0xc00a1768c0) github.com/minio/minio/cmd/logger/audit.go:118 +0x59 github.com/minio/minio/cmd.streamHTTPResponse.func1(0x280f920, 0xc00a1768c0, 0xc02002d140, 0xc02002d1a0) github.com/minio/minio/cmd/storage-rest-server.go:842 +0x1b1 created by github.com/minio/minio/cmd.streamHTTPResponse github.com/minio/minio/cmd/storage-rest-server.go:835 +0xd9
```

2021-11-08 17:20 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-09 13:21 UTC, klauspost requested changes
Most looks good, some changes are needed.

2021-11-09 13:21 UTC, klauspost commented on cmd/admin-handlers.go
> +			w.(http.Flusher).Flush()
Revert. We don't want to flush for each write, only when nothing is queued.

2021-11-09 13:21 UTC, klauspost commented on cmd/admin-handlers.go
> +			if len(traceCh) == 0 {
Revert, we check above if we have queued data.

2021-11-09 13:21 UTC, klauspost commented on cmd/admin-handlers.go
> -			if len(logCh) == 0 {
Revert. We don't want to flush if we write right away anyway.

2021-11-09 13:21 UTC, klauspost commented on cmd/admin-handlers.go
> +			if len(logCh) == 0 {
Revert.

2021-11-09 13:21 UTC, klauspost commented on cmd/admin-handlers.go
> +			if len(healthInfoCh) == 0 {
Revert. If we don't flush writing a byte is pointless. You are welcome to implement as above, but this isn't a high frequency writer.

2021-11-09 13:21 UTC, klauspost commented on cmd/admin-handlers.go
> +			if len(reportCh) == 0 {
Same.

2021-11-09 13:21 UTC, klauspost commented on cmd/peer-rest-server.go
> -	w.WriteHeader(http.StatusOK)
This delays header until the first response is encoded. This can take quite a while, so caller could time out waiting for header since there is no keepalive ticker here.

2021-11-09 17:46 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-09 17:49 UTC, harshavardhana commented on cmd/storage-rest-server.go
> +		defer ticker.Stop()
@klauspost also found some ticker leaks that can happen

2021-11-09 18:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-10 14:02 UTC, klauspost approved these changes
LGTM

2021-11-12 14:52 UTC, klauspost approved these changes

2021-11-15 18:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-17 03:25 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-18 23:43 UTC, harshavardhana commented
Okay this PR is unblocked now - can you PTAL @poornas @krisis ?

2021-11-19 00:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-19 00:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-19 00:31 UTC, poornas approved these changes

2021-11-19 01:19 UTC, merged