Fix hdfs gateway concurrent map writes
minio/minio pull request #13596
Opened 2021-11-05 21:53 UTC by danochoa

## Description
Resolves https://github.com/minio/minio/issues/13587

## How to test this PR?
Listing files is working as usual after this change.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-11-05 22:13 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-05 22:34 UTC, harshavardhana reviewed
Here is the correct fix 

```diff
diff --git a/cmd/gateway/hdfs/gateway-hdfs.go b/cmd/gateway/hdfs/gateway-hdfs.go
index ebb5f32bc..62130d444 100644
--- a/cmd/gateway/hdfs/gateway-hdfs.go
+++ b/cmd/gateway/hdfs/gateway-hdfs.go
@@ -28,6 +28,7 @@ import (
        "path"
        "sort"
        "strings"
+       "sync"
        "syscall"
        "time"
 
@@ -407,6 +408,7 @@ func (n *hdfsObjects) listDirFactory() minio.ListDirFunc {
 
 // ListObjects lists all blobs in HDFS bucket filtered by prefix.
 func (n *hdfsObjects) ListObjects(ctx context.Context, bucket, prefix, marker, delimiter string, maxKeys int) (loi minio.ListObjectsInfo, err error) {
+       var mutex sync.Mutex
        fileInfos := make(map[string]os.FileInfo)
        targetPath := n.hdfsPathJoin(bucket, prefix)
 
@@ -430,6 +432,9 @@ func (n *hdfsObjects) ListObjects(ctx context.Context, bucket, prefix, marker, d
        }
 
        getObjectInfo := func(ctx context.Context, bucket, entry string) (minio.ObjectInfo, error) {
+               mutex.Lock()
+               defer mutex.Unlock()
+
                filePath := path.Clean(n.hdfsPathJoin(bucket, entry))
                fi, ok := fileInfos[filePath]
 
@@ -443,7 +448,6 @@ func (n *hdfsObjects) ListObjects(ctx context.Context, bucket, prefix, marker, d
                        }
 
                        fi, ok = fileInfos[filePath]
-
                        if !ok {
                                err = fmt.Errorf("could not get FileInfo for path '%s'", filePath)
                                return minio.ObjectInfo{}, hdfsToObjectErr(ctx, err, bucket, entry)
```

2021-11-05 22:50 UTC, harshavardhana commented on cmd/gateway/hdfs/gateway-hdfs.go
> +        var mutex sync.Mutex
```suggestion
       var mutex sync.Mutex
```

2021-11-05 22:50 UTC, harshavardhana requested changes
make sure to run `gofmt` on your code

2021-11-05 22:52 UTC, harshavardhana approved these changes

2021-11-05 23:00 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-05 23:02 UTC, harshavardhana approved these changes

2021-11-05 23:11 UTC, danochoa commented
@harshavardhana this seems to be failing in my local test environment

2021-11-05 23:21 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-05 23:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-05 23:54 UTC, harshavardhana commented
> @harshavardhana this seems to be failing in my local test environment

can you share the failure?

2021-11-06 00:00 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-06 00:21 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-06 01:18 UTC, danochoa commented
Minio gateway crashes in a loop on startup:
```
Nov 06 01:13:48  systemd[1]: Started MinIO.
Nov 06 01:13:48  minio[30838]: WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
Nov 06 01:13:48  minio[30838]: Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
Nov 06 01:13:50  minio[30838]: panic: runtime error: invalid memory address or nil pointer dereference 
Nov 06 01:13:50  minio[30838]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x28856e9]
Nov 06 01:13:50  minio[30838]: goroutine 70 [running]:
Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd.(*NotificationSys).ServerInfo(0x0, 0x2, 0x1e670aa, 0xc000022080)
Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd/notification.go:1205 +0x29
Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd.GetPeerOnlineCount(0x4a052a8, 0xc0015beed0) 
Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd/notification.go:1291 +0x3f
Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd.nodeHealthMetricsPrometheus(0xc000e12120)
Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd/metrics.go:111 +0x26
Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd.(*minioCollector).Collect(0xc000dd6290, 0xc000e12120)
Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd/metrics.go:101 +0xe5
Nov 06 01:13:50  minio[30838]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
Nov 06 01:13:50  minio[30838]: github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:446 +0x12b
Nov 06 01:13:50  minio[30838]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
Nov 06 01:13:50  minio[30838]: github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:538 +0xe4d
Nov 06 01:13:50  systemd[1]: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Nov 06 01:13:50  systemd[1]: Unit minio.service entered failed state.
Nov 06 01:13:50  systemd[1]: minio.service failed.
Nov 06 01:13:50  systemd[1]: minio.service holdoff time over, scheduling restart.
```

2021-11-06 01:19 UTC, harshavardhana commented
> Minio gateway crashes in a loop on startup:
> 
> ```
> Nov 06 01:13:48  systemd[1]: Started MinIO.
> Nov 06 01:13:48  minio[30838]: WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
> Nov 06 01:13:48  minio[30838]: Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
> Nov 06 01:13:50  minio[30838]: panic: runtime error: invalid memory address or nil pointer dereference 
> Nov 06 01:13:50  minio[30838]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x28856e9]
> Nov 06 01:13:50  minio[30838]: goroutine 70 [running]:
> Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd.(*NotificationSys).ServerInfo(0x0, 0x2, 0x1e670aa, 0xc000022080)
> Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd/notification.go:1205 +0x29
> Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd.GetPeerOnlineCount(0x4a052a8, 0xc0015beed0) 
> Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd/notification.go:1291 +0x3f
> Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd.nodeHealthMetricsPrometheus(0xc000e12120)
> Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd/metrics.go:111 +0x26
> Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd.(*minioCollector).Collect(0xc000dd6290, 0xc000e12120)
> Nov 06 01:13:50  minio[30838]: github.com/minio/minio/cmd/metrics.go:101 +0xe5
> Nov 06 01:13:50  minio[30838]: github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
> Nov 06 01:13:50  minio[30838]: github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:446 +0x12b
> Nov 06 01:13:50  minio[30838]: created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
> Nov 06 01:13:50  minio[30838]: github.com/prometheus/client_golang@v1.11.0/prometheus/registry.go:538 +0xe4d
> Nov 06 01:13:50  systemd[1]: minio.service: main process exited, code=exited, status=2/INVALIDARGUMENT
> Nov 06 01:13:50  systemd[1]: Unit minio.service entered failed state.
> Nov 06 01:13:50  systemd[1]: minio.service failed.
> Nov 06 01:13:50  systemd[1]: minio.service holdoff time over, scheduling restart.
> ```

This is something else.

2021-11-06 01:21 UTC, harshavardhana commented
You should set prometheus metrics to `/minio/v2/metrics/cluster`

2021-11-06 01:21 UTC, danochoa commented
I was wondering the same, currently rebuilding from latest to test without my recent pr changes.

2021-11-06 01:22 UTC, harshavardhana commented
```diff
git diff
diff --git a/cmd/metrics.go b/cmd/metrics.go
index 1ec4000c8..66f30bad7 100644
--- a/cmd/metrics.go
+++ b/cmd/metrics.go
@@ -108,6 +108,10 @@ func (c *minioCollector) Collect(ch chan<- prometheus.Metric) {
 }
 
 func nodeHealthMetricsPrometheus(ch chan<- prometheus.Metric) {
+       if globalIsGateway {
+               return
+       }
+
        nodesUp, nodesDown := GetPeerOnlineCount()
        ch <- prometheus.MustNewConstMetric(
                prometheus.NewDesc(
```

You need this as well.

2021-11-06 02:26 UTC, danochoa commented
Test succeeded by building from commit 9735f3d8f2af30e00ac7162bd8d61fddad4b2521 with the patches in this PR applied. Building from latest (19bbf3e142d62b69500ce9432b9fe07c3e490190) without patches failed with similar crash loop above.

2021-11-06 02:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-06 06:17 UTC, harshavardhana approved these changes

2021-11-07 11:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-07 16:10 UTC, harshavardhana approved these changes

2021-11-08 17:07 UTC, merged