svc: Fix evaluation with an empty policy
minio/minio pull request #13701
Opened 2021-11-19 12:37 UTC by vadmeste

## Description
For service accounts, it is clear how to test if an account has inherited
policy from a parent user or not by testing this claim:
   `embedded-policy` vs `inherited-policy`

We do not have to test if a policy is empty or not to ignore it and to
evaluate parent policy.

## Motivation and Context
Fix service accounts access with empty policy

## How to test this PR?
```
$ minio server /tmp/fs/
$ mc admin user add myminio/ tenant-x-user tenant-x-user
$ mc admin policy set myminio/ readwrite user=tenant-x-user
$ cat >/tmp/policy.json <<EOF
{
 "Version": "2012-10-17",
  "Statement": []
}
EOF
$ mc admin user svcacct add myminio/ tenant-x-user --access-key tenant-x-sa --secret-key tenant-x-sa --policy /tmp/policy.json
$ mc alias set local http://localhost:9000 tenant-x-sa tenant-x-sa
$ mc mb local/testbucket/
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-11-19 12:57 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-19 16:41 UTC, harshavardhana requested changes

2021-11-19 16:41 UTC, harshavardhana commented on cmd/iam.go
You can't remove this @vadmeste because console adds empty JSON here. This is not correct..

2021-11-20 17:07 UTC, harshavardhana commented
Closing this as per our discussion @vadmeste

2021-11-20 17:07 UTC, closed without merging