multi-delete: Avoid empty Delete tag in the response
minio/minio pull request #13725
Opened 2021-11-22 15:19 UTC by vadmeste

## Description
When removing an object fails, such as when it is WORM protected, an
wrong <Delete> will still be in the response. The commit fixes it.

## Motivation and Context
Fix multi-delete response

## How to test this PR?
1. mc mb myminio/testbucket/ --with-lock
2. mc cp file myminio/testbucket/file1
3. mc cp file myminio/testbucket/file2
4. mc ls -r --versions myminio/testbucket/
5. aws --debug --endpoint-url http://localhost:9000 s3api delete-objects --bucket testbucket --delete 'Objects=[{Key=file1,VersionId=22a5183b-c547-498d-9f89-e83ba95874ac},{Key=file2,VersionId=ac1776cd-ae15-4c34-96a3-3b0302647b1c}],Quiet=false'

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-11-22 16:00 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-22 18:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-22 19:20 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-22 20:43 UTC, harshavardhana commented
@vadmeste what does this PR fix ?

2021-11-23 09:08 UTC, vadmeste commented
> @vadmeste what does this PR fix ?

Basically wrong xml output. Sometimes there are some empty <Delete /> tag and that's not supposed to happen.

It happens if there are some deletion failures for some and not all objects, like when some objects are locked.

2021-11-23 17:27 UTC, harshavardhana approved these changes

2021-11-23 17:27 UTC, harshavardhana requested changes
can you add a test-case for this @vadmeste ?

2021-11-23 20:50 UTC, poornas approved these changes
LGTM

2021-11-24 12:12 UTC, vadmeste commented
> can you add a test-case for this @vadmeste ?

Done

2021-11-24 12:31 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-24 18:00 UTC, harshavardhana approved these changes

2021-11-24 18:01 UTC, merged

2021-11-24 23:05 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally