Improve listing consistency with version merging
minio/minio pull request #13723
Opened 2021-11-22 15:01 UTC by klauspost

## Description

Use xlMetaV2 for listing and add version merging.

## Motivation and Context

Instead of selecting one metadata per object, merge individual versions.

## How to test this PR?

Test included.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)

## Checklist:
- [x] Unit tests added/updated

2021-11-22 15:21 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-22 16:20 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-22 16:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-22 16:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-22 17:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-22 17:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-23 05:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#c2878d06-f674-4a95-b212-faf2f5d3844c) |
<a name="c2878d06-f674-4a95-b212-faf2f5d3844c"></a>
### 13723-6be1ea2/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:30561
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/16) Running aws-sdk-go tests ... done in 1 seconds
(2/16) Running aws-sdk-java tests ... done in 1 seconds
(3/16) Running aws-sdk-php tests ... done in 44 seconds
(4/16) Running aws-sdk-ruby tests ... done in 3 seconds
(5/16) Running awscli tests ... done in 2 minutes and 0 seconds
(6/16) Running healthcheck tests ... done in 0 seconds
(7/16) Running mc tests ... done in 26 seconds
(8/16) Running minio-dotnet tests ... done in 53 seconds
(9/16) Running minio-go tests ... FAILED in 1 minutes and 4 seconds
{
  "args": {
    "bucketName": "minio-go-test-hhfncz31uquvyzsi",
    "objectName": "msgqdwvwq63xtmqc5m0co33x03qhzy"
  },
  "duration": 3326,
  "error": "unexpected EOF",
  "function": "GetObject(bucketName, objectName)",
  "message": "CopyN failed",
  "name": "minio-go: testSSES3EncryptedGetObjectReadSeekFunctional",
  "status": "FAIL"
}
(9/16) Running minio-java tests ... done in 35 seconds
(10/16) Running minio-js tests ... done in 51 seconds
(11/16) Running minio-py tests ... done in 1 minutes and 40 seconds
(12/16) Running s3cmd tests ... done in 26 seconds
(13/16) Running s3select tests ... done in 4 seconds
(14/16) Running security tests ... done in 0 seconds
(15/16) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 15 out of 16 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-11-23 13:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-23 16:55 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-23 17:17 UTC, harshavardhana commented
I will check why upgrade tests are broken only in this PR.

2021-11-26 15:33 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#7d1244cf-4f6b-48b7-b78c-94a4864c9c97) |
| mint-gateway-nas.sh | :x: [more...](#0e0ba4ff-2f34-4fdb-b5e3-8ba62fffb110) |
<a name="0e0ba4ff-2f34-4fdb-b5e3-8ba62fffb110"></a>
### 13723-94e5450/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:30158
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 17 seconds
(8/15) Running minio-dotnet tests ... done in 27 seconds
(9/15) Running minio-go tests ... FAILED in 15 seconds
{
  "args": {
    "bucketName": "minio-go-test-9tgzx3hdlfuhuerv",
    "objectName": "441qudfmv5sf0jtixjxdlem6wt5gn0.zip",
    "x-minio-extract": true,
    "zipfile": "test/small/file-0.bin"
  },
  "duration": 3542,
  "error": "We encountered an internal error, please try again.: cause(invalid input: magic number mismatch)",
  "function": "GetObject(bucketName, objectName)",
  "message": "ReadAll failed",
  "name": "minio-go: testGetObjectS3Zip",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 14 seconds
(10/15) Running minio-js tests ... done in 38 seconds
(11/15) Running minio-py tests ... done in 37 seconds
(12/15) Running s3cmd tests ... done in 20 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running versioning tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="7d1244cf-4f6b-48b7-b78c-94a4864c9c97"></a>
### 13723-94e5450/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:30112
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 17 seconds
(8/15) Running minio-dotnet tests ... done in 46 seconds
(9/15) Running minio-go tests ... FAILED in 28 seconds
{
  "args": {
    "bucketName": "minio-go-test-5gel25uuodhwkney",
    "objectName": "6qcsct00nczutd5xvioz51nnyob0e3.zip",
    "x-minio-extract": true,
    "zipfile": "test/small/file-0.bin"
  },
  "duration": 5338,
  "error": "We encountered an internal error, please try again.: cause(invalid input: magic number mismatch)",
  "function": "GetObject(bucketName, objectName)",
  "message": "ReadAll failed",
  "name": "minio-go: testGetObjectS3Zip",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 15 seconds
(10/15) Running minio-js tests ... done in 46 seconds
(11/15) Running minio-py tests ... done in 38 seconds
(12/15) Running s3cmd tests ... done in 17 seconds
(13/15) Running s3select tests ... done in 2 seconds
(14/15) Running versioning tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-11-26 17:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-26 20:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 14:46 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 15:05 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 15:25 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 16:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 17:11 UTC, klauspost commented
I don't think it is related:
```
2021-11-29T16:50:50.7893403Z === RUN   TestRWMutex
2021-11-29T16:51:44.8396325Z race: limit on 8128 simultaneously alive goroutines is exceeded, dying
2021-11-29T16:51:45.0072627Z FAIL	github.com/minio/minio/internal/dsync	64.491s
```
Let's see if the next run fails as well.

2021-11-29 17:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 18:04 UTC, harshavardhana commented
> 2021-11-29T16:50:50.7893403Z === RUN   TestRWMutex
> 2021-11-29T16:51:44.8396325Z race: limit on 8128 simultaneously alive goroutines is exceeded, dying
> 2021-11-29T16:51:45.0072627Z FAIL	github.com/minio/minio/internal/dsync	64.491s

This is related to Go `-race` issue @klauspost

2021-11-29 18:06 UTC, harshavardhana commented
Not sure why upgrade tests are failing only in this PR

```
Bucket created successfully `minio/minio-test/`.
`minio` -> `minio/minio-test/to-read/minio`
Total: 0 B, Transferred: 101.62 MiB, Speed: 43.00 MiB/s
`/etc/hosts` -> `minio/minio-test/to-read/hosts`
Total: 0 B, Transferred: 484 B, Speed: 8.48 KiB/s
Access permission for `minio/minio-test` is set to `download`
matches - 9765cd4bf079efb7b86dc7314ff51b2b11d6b06df8027f888468a575c030e5db  -, got 9765cd4bf079efb7b86dc7314ff51b2b11d6b06df8027f888468a575c030e5db  -
0714131f96706f952a36431d24cba070dd38ec70bc78dc80cfdb14db9207e3a9  -
Stopping upgrade-tests_nginx_1  ... 
Stopping upgrade-tests_minio2_1 ... 
Stopping upgrade-tests_minio3_1 ... 
Stopping upgrade-tests_minio4_1 ... 
Stopping upgrade-tests_minio1_1 ... 
Stopping upgrade-tests_nginx_1  ... done
Stopping upgrade-tests_minio4_1 ... done
Stopping upgrade-tests_minio3_1 ... done
Stopping upgrade-tests_minio2_1 ... done
Stopping upgrade-tests_minio1_1 ... done
Recreating upgrade-tests_minio1_1 ... 
Recreating upgrade-tests_minio2_1 ... 
Recreating upgrade-tests_minio3_1 ... 
Recreating upgrade-tests_minio4_1 ... 
Recreating upgrade-tests_minio1_1 ... done
Recreating upgrade-tests_minio4_1 ... done
Recreating upgrade-tests_minio2_1 ... done
Recreating upgrade-tests_minio3_1 ... done
Recreating upgrade-tests_nginx_1  ... 
Recreating upgrade-tests_nginx_1  ... done
... attempting to add alias 1
mc: <ERROR> Unable to initialize new alias from the provided credentials. Server not initialized, please try again.
...waiting... for 5secs
Added `minio` successfully.
... attempting to add alias 2
Added `minio` successfully.
... attempting to add alias 3
Added `minio` successfully.
... attempting to add alias 4
Added `minio` successfully.
Sleeping for nginx
mismatch expected 1ccca416ec9ffbe0bf83b083aba7573a63cb81038383888f1d5822ec575911a8  -, got c5a58792aaeeca8648bc2091601154a0d155cf0f4058cb1f34a48ff59f0f1660  -
```

Will test this later today.

2021-11-29 20:00 UTC, harshavardhana commented
This PR is breaking things when loading public policies @klauspost i.e policies are not uploaded that were previously set. Here is the reproducer.

```
~/run-dist.sh old 
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of MinIO released 2 years ago ┃
┃ Update: Run `mc admin update`                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Waiting for all other servers to be online to format the disks.
Attempting encryption of all config, IAM users and policies on MinIO backend
Status:         4 Online, 0 Offline. 
Endpoint:  http://10.0.0.67:9000  http://172.16.3.3:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                
AccessKey: minio 
SecretKey: minio123 

Browser Access:
   http://10.0.0.67:9000  http://172.16.3.3:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000                

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide
```

Starts fine 

```
~ mc mb myminio/testbucket/
Bucket created successfully `myminio/testbucket/`.
```

```
~ mc policy set download myminio/testbucket/
Access permission for `myminio/testbucket/` is set to `download`
```

```
~ mc policy list myminio/testbucket/
testbucket/* => readonly
```

And then upgrade to this PR 
```
~ mc policy list myminio/testbucket/
```

It is empty - however, this works fine with master @klauspost - this looks like a bug in this PR - mostly listing is failing when loading metadata for the buckets.

2021-11-29 20:06 UTC, harshavardhana commented
Reproducible with the following script

```bash
#!/usr/bin/env bash

unset MINIO_KMS_KES_CERT_FILE
unset MINIO_KMS_KES_KEY_FILE
unset MINIO_KMS_KES_ENDPOINT
unset MINIO_KMS_KES_KEY_NAME
unset MINIO_KMS_AUTO_ENCRYPTION
unset MINIO_ACCESS_KEY
unset MINIO_SECRET_KEY
unset MINIO_ROOT_USER
unset MINIO_ROOT_PASSWORD

if [ "$1" == "old" ]; then
    rm -rf ~/disk*
fi

pkill -9 minio
export MINIO_ACCESS_KEY=minio
export MINIO_SECRET_KEY=minio123
export MINIO_ENDPOINTS="/home/harsha/disk0{1...4}"
if [ "$1" == "old" ]; then
    /home/harsha/mygo/src/github.com/minio/minio/minio.RELEASE.2019-12-19T22-52-26Z server &
else
    /home/harsha/mygo/src/github.com/minio/minio/minio server &
fi
```

Run with `./setup.sh old` to run old setup first and then proceed to do `./setup.sh new`

2021-11-29 20:40 UTC, harshavardhana commented
```
λ ~/run-dist.sh old
λ
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of MinIO released 2 years ago ┃
┃ Update: Run `mc admin update`                                  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Waiting for all other servers to be online to format the disks.
Attempting encryption of all config, IAM users and policies on MinIO backend
Status:         4 Online, 0 Offline.
Endpoint:  http://10.0.0.67:9000  http://172.16.3.3:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
AccessKey: minio
SecretKey: minio123

Browser Access:
   http://10.0.0.67:9000  http://172.16.3.3:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://10.0.0.67:9000 minio minio123

Object API (Amazon S3 compatible):
   Go:         https://docs.min.io/docs/golang-client-quickstart-guide
   Java:       https://docs.min.io/docs/java-client-quickstart-guide
   Python:     https://docs.min.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.min.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.min.io/docs/dotnet-client-quickstart-guide

λ mc mb myminio/testbucket/
Bucket created successfully `myminio/testbucket/`.
λ mc policy set download myminio/testbucket/
Access permission for `myminio/testbucket/` is set to `download`
λ mc policy list myminio/testbucket/
testbucket/* => readonly
λ ~/run-dist.sh new
λ WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
         Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
Verifying if 1 bucket is consistent across drives...
Automatically configured API requests per node based on available memory on the system: 91
Status:         4 Online, 0 Offline.
API: http://10.0.0.67:9000  http://172.16.3.3:9000  http://172.17.0.1:9000  http://172.18.0.1:9000  http://127.0.0.1:9000
RootUser: minio
RootPass: minio123

Console: http://10.0.0.67:33159 http://172.16.3.3:33159 http://172.17.0.1:33159 http://172.18.0.1:33159 http://127.0.0.1:33159
RootUser: minio
RootPass: minio123

Command-line: https://docs.min.io/docs/minio-client-quickstart-guide
   $ mc alias set myminio http://10.0.0.67:9000 minio minio123

Documentation: https://docs.min.io

WARNING: Console endpoint is listening on a dynamic port (33159), please use --console-address ":PORT" to choose a static port.

λ mc policy list myminio/testbucket/
testbucket/* => readonly
```

Test with master branch why upgrade tests succeed.  From the cursory review I can't see what might have to changed in this PR but it does look a regression.

2021-11-30 12:48 UTC, klauspost commented
@harshavardhana This was an unexpected side effect: https://github.com/minio/minio/pull/13723/files#diff-ea27fd99827bd8e85d59a69fc1bd041ba34b235f0175abd8e7018de33dedab57L1509

I moved it to the only other caller, where it belongs.

2021-11-30 13:06 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-30 17:21 UTC, harshavardhana approved these changes

2021-11-30 17:49 UTC, harshavardhana requested changes

2021-11-30 17:49 UTC, harshavardhana commented on cmd/xl-storage-format-v2.go
>  func (j xlMetaV2Version) getVersionID() [16]byte {
This looks unintentional.

2021-12-01 08:38 UTC, harshavardhana approved these changes

2021-12-01 08:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-01 22:05 UTC, krisis reviewed
LGTM overall except for minor comments.

2021-12-01 22:05 UTC, krisis commented on cmd/erasure-healing_test.go
> +		for i := range newDisks[:4] {
minor nit: the caller can pass the appropriate sub-slice. This function can use `newDisks` as supplied.
```suggestion
		for i := range newDisks {
```

2021-12-01 22:05 UTC, krisis commented on cmd/metacache-entries.go
> +			return other, false
At this point, shouldn't we return `prefer` if it's non-nil, since `prefer` stores the metacache entry which has a more recent version.
```suggestion
                        if prefer != nil {
                           return prefer, false
                        }
			if eVer.header.sortsBefore(oVer.header) {
				return e, false
			}
			return other, false
```

2021-12-02 11:11 UTC, vadmeste reviewed
Some comments, not tested yet

2021-12-02 11:11 UTC, vadmeste commented on cmd/metacache-entries.go
> +	if e.name != other.name {
In theory and in practice, names always match right ? maybe we should return nil in that case ?

2021-12-02 11:11 UTC, vadmeste commented on cmd/xl-storage-format-v2.go
> +// mergeXLV2Versions will merge all versions that have at least quorum
Can you just add 'found in different disks'

2021-12-02 11:11 UTC, vadmeste commented on cmd/xl-storage-format-v2.go
> +	if false {
It looks like this needs to be removed (or maybe commented if you still need it in the future)

2021-12-02 11:11 UTC, vadmeste commented on cmd/xl-storage-format-v2.go
> +			// Find the latest.
Double comment

2021-12-02 15:23 UTC, klauspost commented on cmd/metacache-entries.go
> +			return other, false
The `prefer` is only mostly interesting if we match non-strict (and only used in this case).

But I don't see anything bad with your suggestion.

2021-12-02 15:27 UTC, klauspost commented on cmd/metacache-entries.go
> +	if e.name != other.name {
It will in practice. This is just defensive. We return the earliest, if it should be called with differing names.

2021-12-02 15:44 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-02 16:16 UTC, krisis approved these changes

2021-12-02 16:24 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-02 16:45 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-02 17:06 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-02 17:27 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-02 18:07 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-02 19:29 UTC, merged