disable CI for draft PRs
minio/minio pull request #13784
Opened 2021-11-29 22:08 UTC by krisis

## Description
Disable running of CI for draft PRs

## Motivation and Context
Save CI/CD cycles

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] CI/CD

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-11-29 22:20 UTC, harshavardhana approved these changes

2021-11-29 22:21 UTC, harshavardhana requested changes
Looks like something wrong here @krisis

2021-11-29 22:27 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 22:41 UTC, harshavardhana requested changes

2021-11-29 22:41 UTC, harshavardhana commented on .github/workflows/go-cross.yml
> +    if: github.event.pull_request.draft == false
Seems like there is a better way

```
on:
  pull_request:
    types: [review_requested, ready_for_review]
```

- https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#pull-request-event-pull_request
- https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onevent_nametypes

2021-11-29 23:37 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 23:40 UTC, harshavardhana approved these changes

2021-11-29 23:58 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-30 07:35 UTC, merged

2021-11-30 13:00 UTC, klauspost commented
@krisis @harshavardhana I like having feedback on Draft PRs, so I disagree they are a waste of cycles.

I generally don't consider them ready for review before CI succeeds, so I like having that feedback before marking it ready for review.

2021-11-30 16:42 UTC, harshavardhana commented
> @krisis @harshavardhana I like having feedback on Draft PRs, so I disagree they are a waste of cycles.
> 
> I generally don't consider them ready for review before CI succeeds, so I like having that feedback before marking it ready for review.

Yes that is correct as well. What I think @krisis was trying to address is there are PRs that don't even build so why run them such as dependency updates etc.

But we can revert it if @krisis also agrees.

2021-11-30 16:57 UTC, krisis commented
@klauspost that's a valid point.  We can revert this change.