cache: in writeback mode skip etag verification
minio/minio pull request #13781
Opened 2021-11-29 19:56 UTC by poornas

if the commit is still in pending or failed status

This PR also does some minor code cleanup

## Description

## Motivation and Context

## How to test this PR?
Set up cache drives with `MINIO_CACHE_COMMIT` set to writeback - for single uploads even if the backend is down/slow and commit is in pending/failed status the content should be served

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-11-29 20:20 UTC, harshavardhana requested changes

2021-11-29 20:20 UTC, harshavardhana commented on cmd/disk-cache-backend.go
>  	cLock, lkctx, err := c.GetLockContext(ctx, bucket, object)
This is expected to be removed? @poornas

2021-11-29 20:20 UTC, harshavardhana commented on cmd/disk-cache.go
>  	}
A function is better for this @poornas

2021-11-29 21:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-29 23:53 UTC, poornas commented on cmd/disk-cache.go
>  	}
changed this

2021-11-29 23:57 UTC, poornas commented on cmd/disk-cache-backend.go
>  	cLock, lkctx, err := c.GetLockContext(ctx, bucket, object)
the wrapper function put() already does this check on line 818 - avoiding 2 calls to diskSpaceAvailable here

2021-11-30 00:01 UTC, harshavardhana approved these changes

2021-11-30 00:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-11-30 16:56 UTC, vadmeste approved these changes
LGTM

2021-11-30 18:22 UTC, merged