Avoid cache GC of writebacks before commit syncs
minio/minio pull request #13860
Opened 2021-12-07 21:15 UTC by poornas

Save part.1 for writebacks in a separate folder
and move it to cache dir atomically while saving
the cache metadata. This is to avoid GC mistaking
the part.1 as orphaned cache entries and purging them.

This PR also fixes object size being overwritten during
retries for writeback mode.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-12-07 21:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#8ff35acc-3d6b-4351-98de-187ba8b2d7ae) |
<a name="8ff35acc-3d6b-4351-98de-187ba8b2d7ae"></a>
### 13860-51036ab/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:32232
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 33 seconds
(8/15) Running minio-dotnet tests ... done in 50 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 9 seconds
(10/15) Running minio-java tests ... done in 29 seconds
(11/15) Running minio-js tests ... FAILED in 55 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook for \"removeObject(bucketName, objectName, removeOpts)",
  "args": "bucketName:minio-js-test-ver-presignae9afc5c-a978-4a8c-8fee-9f0d9f3aa9df ",
  "duration": 5,
  "alert": "datafile-1-b ",
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty. You must delete all versions in the bucket. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:89:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:164:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(11/15) Running minio-py tests ... done in 1 minutes and 16 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2021-12-08 00:38 UTC, harshavardhana commented
```
cmd/disk-cache_test.go:28:28: too many arguments in call to m.ToObjectInfo (typecheck)
	objInfo := m.ToObjectInfo("testbucket", "testobject")
	                          ^
make: *** [Makefile:38: lint] Error 1
Error: Process completed with exit code 2.
```

```
# github.com/minio/minio/cmd [github.com/minio/minio/cmd.test]
cmd/disk-cache_test.go:28:27: too many arguments in call to m.ToObjectInfo
	have (string, string)
	want ()
FAIL	github.com/minio/minio/cmd [build failed]
FAIL
make: *** [Makefile:55: test-iam] Error 2
```

@poornas

2021-12-08 01:59 UTC, harshavardhana requested changes
This PR also producers a crash

```diff
git diff
diff --git a/cmd/disk-cache-backend.go b/cmd/disk-cache-backend.go
index 34377199e..bc28fe620 100644
--- a/cmd/disk-cache-backend.go
+++ b/cmd/disk-cache-backend.go
@@ -411,6 +411,9 @@ func (c *diskCache) purge(ctx context.Context) {
                }
 
                for fname, fi := range cachedRngFiles {
+                       if fi == nil {
+                               continue
+                       }
                        if cc != nil {
                                if cc.isStale(objInfo.ModTime) {
                                        removeAll(fname)
@@ -427,10 +430,12 @@ func (c *diskCache) purge(ctx context.Context) {
                        scorer.addFile(fname, atime.Get(fi), fi.Size(), numHits)
                }
                // clean up stale cache.json files for objects that never got cached but access count was maintained in cache.json
-               fi, err := os.Stat(pathJoin(cacheDir, cacheMetaJSONFile))
-               if err != nil || (fi.ModTime().Before(expiry) && len(cachedRngFiles) == 0) {
+               fi, err := fsStatFile(ctx, pathJoin(cacheDir, cacheMetaJSONFile))
+               if err != nil || (fi != nil && fi.ModTime().Before(expiry) && len(cachedRngFiles) == 0) {
                        removeAll(cacheDir)
-                       scorer.adjustSaveBytes(-fi.Size())
+                       if fi != nil {
+                               scorer.adjustSaveBytes(-fi.Size())
+                       }
                        // Proceed to next file.
                        return nil
                }
```

2021-12-08 02:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-08 04:26 UTC, harshavardhana approved these changes

2021-12-08 22:52 UTC, harshavardhana commented
Taking this in this is tested in a customer environment already.

2021-12-08 22:52 UTC, merged