Backport replication fixes for 0422 hotfix
minio/minio pull request #13921
Opened 2021-12-15 23:31 UTC by poornas

## Description
Backport replication queuing changes and replication metadata fixes to the 0422 hotfix

## Motivation and Context

## How to test this PR?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2021-12-15 23:33 UTC, harshavardhana requested changes
We should add logs to indicate that worker queue might not be enough @poornas as well into this branch?

2021-12-16 00:16 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#9c8d1031-ff1c-4057-9938-ed34dabb0d87) |
| mint-fs.sh | :x: [more...](#f1f55fd0-ba74-46bc-8083-4b012a19c571) |
| mint-gateway-s3.sh | :x: [more...](#2a3a22ce-3a92-4bb2-872f-bb738bec295b) |
| mint-erasure.sh | :x: [more...](#6afb9343-322e-4a7f-96c8-d84ee081d7e5) |
| mint-dist-erasure.sh | :x: [more...](#fa523fc4-42a2-4d55-ae7a-f8aa9ef41d60) |
| mint-gateway-nas.sh | :x: [more...](#adf311f1-ce52-4bcf-8a7a-27779fbcdc5a) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#2f0ebacc-2c2a-4191-b3a9-c6369e1b2d0f) |
| mint-pools.sh | :x: [more...](#2f7742c0-11bb-4b13-8219-e31e1888daae) |
<a name="2f7742c0-11bb-4b13-8219-e31e1888daae"></a>
### 13921-0aa698a/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:30933
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 1 minutes and 53 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 22 seconds
{
  "args": {
    "bucketName": "minio-go-test-olptsnjztolwhmqr",
    "objectName": "o0b3kbjt3aggvhi55vjic5s0grrbgg"
  },
  "duration": 1274,
  "function": "GetObject()",
  "message": "Unexpected number of Version elements in listing objects",
  "name": "minio-go: testPutObjectWithVersioning",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 3 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 97,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-rg8fi4, objectName = null, resource = /minio-java-test-rg8fi4, requestId = 16C1123D8FC37DB1, hostId = 5556934a-25cf-4a98-b7b1-de1b64bd75cf)\nrequest={method=PUT, url=http://minio-k8s3:30933/minio-java-test-rg8fi4?encryption=, headers=Host: minio-k8s3:30933\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.3.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20211215T234314Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20211215/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 342\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16C1123D8FC37DB1\nX-Xss-Protection: 1; mode=block\nDate: Wed, 15 Dec 2021 23:43:14 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:645), io.minio.S3Base.execute(S3Base.java:440), io.minio.S3Base.executePut(S3Base.java:772), io.minio.MinioClient.setBucketEncryption(MinioClient.java:2328), FunctionalTest.setBucketEncryption(FunctionalTest.java:3222), FunctionalTest.runBucketTests(FunctionalTest.java:3655), FunctionalTest.runTests(FunctionalTest.java:3718), FunctionalTest.runEndpointTests(FunctionalTest.java:3818), FunctionalTest.main(FunctionalTest.java:3938)]"
}
(9/15) Running minio-js tests ... FAILED in 18 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:89:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:164:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1334:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(9/15) Running minio-py tests ... FAILED in 1 minutes and 37 seconds
{
  "name": "minio-py:test_thread_safe",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-abd901d8-db68-4934-a44b-7bf9efa727c8",
    "object_name": "3a4091aa-5034-487d-9eb6-62da959ebeea"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-abd901d8-db68-4934-a44b-7bf9efa727c8, request_id: 16C1125869F45604, host_id: 5556934a-25cf-4a98-b7b1-de1b64bd75cf, bucket_name: minio-py-test-abd901d8-db68-4934-a44b-7bf9efa727c8",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1611, in test_thread_safe\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 669, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 397, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 380, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-abd901d8-db68-4934-a44b-7bf9efa727c8, request_id: 16C1125869F45604, host_id: 5556934a-25cf-4a98-b7b1-de1b64bd75cf, bucket_name: minio-py-test-abd901d8-db68-4934-a44b-7bf9efa727c8\n",
  "duration": 3935
}
(9/15) Running s3cmd tests ... done in 25 seconds
(10/15) Running s3select tests ... done in 4 seconds
(11/15) Running versioning tests ... FAILED in 30 minutes and 7 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-303wqy99339dn2",
    "objectName": "testObject",
    "retentionMode": "COMPLIANCE"
  },
  "duration": 1802018,
  "function": "/mint/build/versioning/main.go:79: main.cleanupBucket",
  "message": "Unable to cleanup bucket after compliance tests",
  "name": "versioning",
  "status": "FAIL"
}

Executed 10 out of 15 tests successfully.
```
<a name="6afb9343-322e-4a7f-96c8-d84ee081d7e5"></a>
### 13921-0aa698a/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:32483
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 19 seconds
(8/15) Running minio-dotnet tests ... done in 27 seconds
(9/15) Running minio-go tests ... FAILED in 37 seconds
{
  "args": {
    "bucketName": "minio-go-test-kbcy5lxeokofj5zi",
    "objectName": "cpd691dlqcuwvfurf399mp2wos26hv",
     [...]

2021-12-16 01:00 UTC, poornas commented
> We should add logs to indicate that worker queue might not be enough @poornas as well into this branch?

done

2021-12-16 01:08 UTC, harshavardhana approved these changes

2021-12-16 01:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#e54a4ee8-1fa7-4fd6-be22-04694cfe703f) |
| mint-fs.sh | :x: [more...](#1f82864d-a500-491c-b03d-01c9560023f6) |
| mint-gateway-s3.sh | :x: [more...](#4e99d671-4653-4664-a4bf-74c4411a857d) |
| mint-erasure.sh | :x: [more...](#c22449ef-5918-41fb-8332-ab19a865c52f) |
| mint-dist-erasure.sh | :x: [more...](#05f033ff-840a-47eb-8e70-7b5cea09ed0f) |
| mint-gateway-nas.sh | :x: [more...](#21976fc4-07ec-45e7-b951-b244095e79b6) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#3898dcf2-7954-4be2-bded-1740cac23cac) |
| mint-pools.sh | :x: [more...](#537ddc02-ee3c-432b-8396-201b88e8a254) |
<a name="4e99d671-4653-4664-a4bf-74c4411a857d"></a>
### 13921-3cdd9b3/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:32324
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 51 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 24 seconds
(8/15) Running minio-dotnet tests ... done in 37 seconds
(9/15) Running minio-go tests ... done in 35 seconds
(10/15) Running minio-java tests ... FAILED in 28 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 322,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"XMinioAdminVersionMismatch\",\"Message\":\"This 'admin' API is not supported by server in 'mode-gateway-s3'\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"\",\"HostId\":\"04fb1ed8-de13-4dcf-b5a7-edd8d0cf38a0\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:190), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:221), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:143), FunctionalTest.runTests(FunctionalTest.java:3720), FunctionalTest.runEndpointTests(FunctionalTest.java:3818), FunctionalTest.main(FunctionalTest.java:3938)]"
}
(10/15) Running minio-js tests ... done in 35 seconds
(11/15) Running minio-py tests ... done in 59 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 6 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="e54a4ee8-1fa7-4fd6-be22-04694cfe703f"></a>
### 13921-3cdd9b3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s3:30006
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 1 minutes and 57 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 27 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... FAILED in 53 seconds
{
  "args": {
    "bucketName": "minio-go-test-l1rrsp0w3s23bkqk",
    "objectName": "bbvlufqgse4w965okl1lh031v69i9y",
    "sse": {}
  },
  "duration": 53,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 3 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 94,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-3otdl86, objectName = null, resource = /minio-java-test-3otdl86, requestId = 16C1180A667E86A4, hostId = a8209a06-ae52-48ec-b245-b2eabf98dc37)\nrequest={method=PUT, url=http://minio-k8s3:30006/minio-java-test-3otdl86?encryption=, headers=Host: minio-k8s3:30006\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.3.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20211216T012932Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20211216/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16C1180A667E86A4\nX-Xss-Protection: 1; mode=block\nDate: Thu, 16 Dec 2021 01:29:32 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:645), io.minio.S3Base.execute(S3Base.java:440), io.minio.S3Base.executePut(S3Base.java:772), io.minio.MinioClient.setBucketEncryption(MinioClient.java:2328), FunctionalTest.setBucketEncryption(FunctionalTest.java:3222), FunctionalTest.runBucketTests(FunctionalTest.java:3655), FunctionalTest.runTests(FunctionalTest.java:3718), FunctionalTest.runEndpointTests(FunctionalTest.java:3818), FunctionalTest.main(FunctionalTest.java:3938)]"
}
(9/15) Running minio-js tests ... done in 56 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 21 seconds
(11/15) Running s3cmd tests ... done in 26 seconds
(12/15) Running s3select tests ... done in 4 seconds
(13/15) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 15 tests successfully.
```
<a name="1f82864d-a500-491c-b03d-01c9560023f6"></a>
### 13921-3cdd9b3/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:30278
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 52 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 18 seconds
(8/15) Running minio-dotnet tests ... done in 26 seconds
(9/15) Running minio-go tests ... FAILED in 23 seconds
{
  "args": {
    "bucketName": "minio-go-test-rmcti5bvu3t1dp0d",
    "objectName": "i4jpja1qphg0wc1dzfi432emukechd",
    "sse": {}
  },
  "duration": 4,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 36,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-14fckre, objectName = null, resource = /minio-java-test-1 [...]

2021-12-16 03:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#8c2be50a-c21b-4067-b426-bcc0022a148c) |
| mint-fs.sh | :x: [more...](#15b3e352-d496-4767-85e5-42d3fd4b2090) |
| mint-gateway-s3.sh | :x: [more...](#97ccc2ef-adcf-4e32-adfd-822c3e601fc6) |
| mint-erasure.sh | :x: [more...](#ca295383-4d94-4af7-a68a-5db708e7b8dc) |
| mint-dist-erasure.sh | :x: [more...](#49d27c19-f810-4967-ac68-f381658009dd) |
| mint-gateway-nas.sh | :x: [more...](#32df7cc1-e9ab-4ee5-89f0-3e43d7d75743) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#8bd99014-5bfb-4f96-8ac8-473c76b19433) |
| mint-pools.sh | :x: [more...](#77f14cd8-138a-47ce-adfd-3ff85ca1aed1) |
<a name="ca295383-4d94-4af7-a68a-5db708e7b8dc"></a>
### 13921-e2ec51c/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:32541
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 50 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 21 seconds
(8/15) Running minio-dotnet tests ... done in 26 seconds
(9/15) Running minio-go tests ... FAILED in 39 seconds
{
  "args": {
    "bucketName": "minio-go-test-io4mcfebruv0dg02",
    "objectName": "zxksgikgnggm0fiqtildycj5rqd5wl",
    "sse": {}
  },
  "duration": 9,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 29,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-2tpblkp, objectName = null, resource = /minio-java-test-2tpblkp, requestId = 16C11B20DE309769, hostId = 32a0a7ff-8db1-43ee-8f3a-66194ab328c9)\nrequest={method=PUT, url=http://minio-k8s6:32541/minio-java-test-2tpblkp?encryption=, headers=Host: minio-k8s6:32541\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.3.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20211216T022607Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20211216/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16C11B20DE309769\nX-Xss-Protection: 1; mode=block\nDate: Thu, 16 Dec 2021 02:26:07 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:645), io.minio.S3Base.execute(S3Base.java:440), io.minio.S3Base.executePut(S3Base.java:772), io.minio.MinioClient.setBucketEncryption(MinioClient.java:2328), FunctionalTest.setBucketEncryption(FunctionalTest.java:3222), FunctionalTest.runBucketTests(FunctionalTest.java:3655), FunctionalTest.runTests(FunctionalTest.java:3718), FunctionalTest.runEndpointTests(FunctionalTest.java:3818), FunctionalTest.main(FunctionalTest.java:3938)]"
}
(9/15) Running minio-js tests ... done in 51 seconds
(10/15) Running minio-py tests ... done in 49 seconds
(11/15) Running s3cmd tests ... done in 24 seconds
(12/15) Running s3select tests ... done in 1 seconds
(13/15) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 13 out of 15 tests successfully.
```
<a name="8bd99014-5bfb-4f96-8ac8-473c76b19433"></a>
### 13921-e2ec51c/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:31153
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... FAILED in 25 seconds
{
  "name": "awscli",
  "duration": 1988,
  "function": "aws --endpoint-url http://minio-k8s7:31153 s3api copy-object --bucket awscli-mint-test-bucket-373 --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-373/datafile-1-kB\n",
  "status": "FAIL",
  "error": "Hash mismatch expected 5031940d37e7d4e4d51295d3032beaa6, got 280a62d1c1ff1836492619f06b45b044"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 25 seconds
(7/15) Running minio-dotnet tests ... done in 33 seconds
(8/15) Running minio-go tests ... FAILED in 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-ejbe6prsxkgflqoa",
    "objectName": "ujgxo5ivw34bpt6hdg55zzv6b1tmgc",
    "sse": {}
  },
  "duration": 52,
  "error": "Server side encryption specified but KMS is not configured",
  "function": "PutEncryptedObject(bucketName, objectName, reader, sse)",
  "message": "PutEncryptedObject failed",
  "name": "minio-go: testSSES3EncryptionPutGet",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 3 seconds
{
  "name": "minio-java",
  "function": "setBucketEncryption()",
  "duration": 106,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-1rkavh9, objectName = null, resource = /minio-java-test-1rkavh9, requestId = 16C11B35AF1F7BF2, hostId = 7daf229b-ced5-41b1-9b0b-4d9bd5a5171c)\nrequest={method=PUT, url=http://minio-k8s7:31153/minio-java-test-1rkavh9?encryption=, headers=Host: minio-k8s7:31153\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.3.3\nContent-MD5: 5bZurju84n5lUGMQ6mrGXQ==\nx-amz-content-sha256: df4e3e6cf7a0b4af67ba58f41eaa596d54579eea2ed2f993da09600f59413711\nx-amz-date: 20211216T022736Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20211216/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 344\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nVary: Origin\nX-Amz-Request-Id: 16C11B35AF1F7BF2\nX-Xss-Protection: 1; mode=block\nDate: Thu, 16 Dec 2021 02:27:36 GMT\n}\n >>> [io.minio.S3Base.execute(S3Base.java:645), io.minio.S3Base.execute(S3Base.java:440), io.minio.S3Base.executePut(S3Base.java:772), io.minio.MinioClient.setBucketEncryption(MinioClient.java:2328), FunctionalTest.setBucketEncryption(FunctionalTest.java:3222), FunctionalTest.runBucketTests(FunctionalTest.java:3655), FunctionalTest.runTests(FunctionalTest.java:3718), FunctionalTest.runEndpointTests(FunctionalTest.java:3818), FunctionalTest.main(FunctionalTest.java:3938)]"
}
(8/15) Running minio-js tests ... done in 57 seconds
(9/15) Running minio-py tests ... done in 1 minutes and 40 seconds
(10/15) Running s3cmd tests ... FAILED in 7 seconds
{
  "name": "s3cmd",
  "duration": "5223",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "WARNING: MD5 Sums don't match!\nWARNING: Retrying upload of /mint/data/datafile-65-MB\nWARNING: MD5 Sums  [...]

2021-12-16 03:11 UTC, harshavardhana approved these changes

2021-12-16 03:12 UTC, merged