doc: Wrong spelling
minio/minio pull request #14014
Opened 2021-12-31 15:54 UTC by wufeiwua

The spelling of a word is easy to misunderstand.

## Description
BareMetal is an exokernel-based single address space operating system (OS) created by Return Infinity.
[WikiPidia](https://en.wikipedia.org/wiki/BareMetal)

## Motivation and Context
When I read the document, I don’t understand the word "baremetal" very well, I think it should be "bare-metal"

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation updated
- [ ] Unit tests added/updated

2021-12-31 16:14 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2021-12-31 19:27 UTC, harshavardhana requested changes
This is the correct wording

2021-12-31 19:27 UTC, harshavardhana commented on README.md
> +This README provides quickstart instructions on running MinIO on bare-metal hardware, including container-based installations. For Kubernetes environments, use the [MinIO Kubernetes Operator](https:/
```suggestion
This README provides quickstart instructions on running MinIO on Bare metal hardware, including container-based installations. For Kubernetes environments, use the [MinIO Kubernetes Operator](https://github.com/minio/operator/blob/master/README.md).
```

2022-01-01 03:16 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-01 03:42 UTC, harshavardhana approved these changes

2022-01-01 16:39 UTC, merged