Fix replication of tag removal
minio/minio pull request #14056
Opened 2022-01-08 01:57 UTC by poornas

Currently tag removal leaves replication state as `PENDING` because
the `HEAD` api returns just a tag count but not the actual tags,
and this is treated as a no-op

## Description

## Motivation and Context
 

## How to test this PR?
Do a `mc tag set` followed by `mc tag remove` on an object version - Tag removal does not replicate 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-01-08 02:00 UTC, harshavardhana approved these changes

2022-01-08 02:10 UTC, harshavardhana requested changes
Please add a test here part of the `multi-site` tests? @poornas

2022-01-08 02:54 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-08 03:13 UTC, harshavardhana requested changes

2022-01-08 03:13 UTC, harshavardhana commented on docs/site-replication/run-multi-site-ldap.sh
> +fi
We should check the tag status on the destination @poornas isn't that we wanted to validate?

2022-01-08 03:14 UTC, harshavardhana requested changes

2022-01-08 03:14 UTC, harshavardhana commented on docs/site-replication/run-multi-site-ldap.sh
> +    exit_1;
also, the bucket name is wrong here.

2022-01-08 04:20 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-08 04:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-08 06:33 UTC, harshavardhana requested changes

2022-01-08 06:33 UTC, harshavardhana commented on docs/site-replication/run-multi-site-ldap.sh
> +    exit_1;
```suggestion
vID=$(./mc stat minio1/newbucket/README.md --json | jq .versionID)
if [ $? -ne 0 ]; then
    echo "expecting object to be present. exiting.."
    exit_1;
fi
./mc tag set --version-id "${vID}" minio1/newbucket/README.md "k=v"
if [ $? -ne 0 ]; then
    echo "expecting tag set to be successful. exiting.."
    exit_1;
fi
sleep 5

./mc tag remove --version-id "${vID}" minio1/newbucket/README.md
if [ $? -ne 0 ]; then
    echo "expecting tag removal to be successful. exiting.."
    exit_1;
fi
sleep 5

replStatus_minio1=$(./mc stat minio1/newbucket/README.md --json | jq .)
if [ $? -ne 0 ]; then
    echo "expecting object to be present. exiting.."
    exit_1;
fi
if [ "${replStatus_minio1}" != "COMPLETED" ]; then
    echo "expected tag removal to have replicated, exiting..."
    exit_1;
```

2022-01-08 06:53 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-08 07:09 UTC, harshavardhana commented
Looks like the test is failing 

```
Replication Status: REPLICA 
528
Tags set for http://localhost:9001/newbucket/README.md ("eb487fdb-f323-4182-876a-9b1fd77ba978").
529
Tags removed for http://localhost:9001/newbucket/README.md ("eb487fdb-f323-4182-876a-9b1fd77ba978").
530
expected tag removal to have replicated, exiting...
531
Cleaning up instances of MinIO
532
make: *** [Makefile:64: test-site-replication-ldap] Error 1
```

Not sure something needs to be fixed here.

2022-01-08 08:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-09 00:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-10 17:55 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-10 19:01 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-10 21:25 UTC, harshavardhana requested changes

2022-01-10 21:25 UTC, harshavardhana commented on docs/site-replication/run-multi-site.sh
> +
you don't need this script we have a script called `run-multi-site-minio-idp.sh` that needs to be updated here @poornas

2022-01-11 01:01 UTC, harshavardhana approved these changes

2022-01-11 02:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-11 03:06 UTC, merged