Add Subnet link in the issue template for urgency clause
minio/minio pull request #14131
Opened 2022-01-19 13:26 UTC by vadmeste

An update of the bug report template to show how to get quicker response for urgent issues.

2022-01-19 13:45 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-20 00:54 UTC, harshavardhana requested changes

2022-01-20 00:54 UTC, harshavardhana commented on .github/ISSUE_TEMPLATE.md
> +If this case is urgent, please subscribe to [Subnet](https://min.io/pricing) so that our 24/7 support team may help you faster.
Let's move this to the top of the template @vadmeste as a NOTE:

2022-01-20 00:54 UTC, harshavardhana commented on .github/ISSUE_TEMPLATE/bug_report.md
> +
Let's move this to the top of the template @vadmeste as a NOTE:

2022-01-20 09:48 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-20 17:37 UTC, harshavardhana approved these changes

2022-01-20 17:37 UTC, merged