Minor improvements to newXLStorage
minio/minio pull request #14166
Opened 2022-01-24 22:07 UTC by krisis

## Description
- Create internal erasure volumes only if disk is unformatted
- Return a copy of format data in xlStorage.ReadAll

## Motivation and Context
In setups with large number of disks per node, avoiding repetitive work on a single disk can result huge savings.

## How to test this PR?
Existing unit/functional tests should cover.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-01-24 22:09 UTC, harshavardhana approved these changes

2022-01-24 22:23 UTC, harshavardhana requested changes

2022-01-24 22:23 UTC, harshavardhana commented on cmd/xl-storage.go
> +		formatData := make([]byte, len(s.formatData))
This needs to be inside lock unfortunately @krisis

2022-01-24 22:26 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-25 00:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-25 00:18 UTC, harshavardhana approved these changes

2022-01-25 00:49 UTC, poornas approved these changes

2022-01-25 01:09 UTC, merged