Avoid deleting notification target if configured targets exist
minio/minio pull request #14203
Opened 2022-01-27 23:18 UTC by poornas

## Description

## Motivation and Context
`mc admin config reset alias notify_webhook` should fail when actively registered buckets exist. Currently, this succeeds but leaves behind stale bucket notification metadata on the registered buckets.  It would be cleaner to throw an error at the time of notify target reset so that `mc event remove` can be performed before removing the targets

## How to test this PR?
```
mc admin config set sitea notify_webhook enable=on endpoint=http://localhost:8080
mc admin service restart sitea
mc event add sitea/bucket
mc admin config reset sitea notify_webhook    
### with this PR, `reset` should report mc: <ERROR> Unable to reset 'notify_webhook:_' on the server. Unable to disable configured targets '_:webhook'.
### with master, this would succeed - an attempt to re-add the target fails 
```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-01-27 23:23 UTC, harshavardhana requested changes

2022-01-27 23:23 UTC, harshavardhana commented on cmd/admin-handlers-config-kv.go
> +		if err := notify.TestNotificationTargets(GlobalContext, cfg, NewGatewayHTTPTransport(), globalNotificationSys.ConfiguredTargetIDs()); err != nil {
```suggestion
		if err = notify.TestNotificationTargets(GlobalContext, cfg, NewGatewayHTTPTransport(), globalNotificationSys.ConfiguredTargetIDs()); err != nil {
```

2022-01-28 00:09 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-28 00:22 UTC, harshavardhana approved these changes

2022-01-28 00:24 UTC, harshavardhana approved these changes

2022-01-28 00:54 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-28 01:12 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-01-28 02:28 UTC, merged

2022-01-30 01:03 UTC, pfriedland commented
something is not right, maybe with this fix.
I can't add any web hooks right now. I updated to the latest minio on a distributed configuration that has been working PERFECT. Until I tried to add a new webhook:

mc admin config set develop notify_webhook enable=on endpoint=http://ercot-qenel8.develop.svc.cluster.local:5000/

healthmc: <ERROR> Unable to set 'notify_webhook enable=on endpoint=http://ercot-qenel8.develop.svc.cluster.local:5000/health' to server. Unable to disable configured targets 'minio-ercot-cop:webhook'.

I've tried to reset/remove minio-ercot-cop:webhook but it's not going away.

2022-01-30 02:14 UTC, poornas commented
@pfriedland , you probably have stale event notifications on buckets that need to be deleted first - 
```
for i in $(mc --json ls alias/ | jq -r .key); do echo $i; mc event list alias/$i; done
```
Above script should help identify buckets using this old webhook minio-ercot-cop:notify_webhook. If you do `mc event remove <alias>/<bucket> minio-ercot-cop:notify_webhook for such buckets, you should be able to add a new target - this PR is just ensuring that the config is valid at the time of saving

2022-01-30 03:24 UTC, harshavardhana commented
> Above script should help identify buckets using this old webhook minio-ercot-cop:notify_webhook. If you do `mc event remove / minio-ercot-cop:notify_webhook for such buckets, you should be able to add a new target - this PR is just ensuring that the config is valid at the time of saving and not deleting an actively referenced target

@pfriedland please do not comment on pull requests make new issues - this is merged and released as per requirement. 

> mc: Unable to set 'notify_webhook:abc enable=on endpoint=http://ercot-qenel8.develop.svc.cluster.local:5000/health' to server. Unable to disable configured targets 'minio-ercot-cop:webhook'.

You should make sure to disable and enable new targets that replace existing targets should be unregistered from existing bucket configurations.

2022-01-30 13:58 UTC, pfriedland commented
Guys - sorry about the comment that should have been an issue. Regardless,
I had to —force remove all events on the bucket I suspected it to be
attached. This odd event didn’t show up in any list. Things are back to
normal, I think.

On Sat, Jan 29, 2022 at 22:25 Harshavardhana ***@***.***>
wrote:

> Above script should help identify buckets using this old webhook
> minio-ercot-cop:notify_webhook. If you do `mc event remove /
> minio-ercot-cop:notify_webhook for such buckets, you should be able to add
> a new target - this PR is just ensuring that the config is valid at the
> time of saving and not deleting an actively referenced target
>
> @pfriedland <https://github.com/pfriedland> please do not comment on pull
> requests make new issues - this is merged and released as per requirement.
>
> mc: Unable to set 'notify_webhook:abc enable=on endpoint=
> http://ercot-qenel8.develop.svc.cluster.local:5000/health' to server.
> Unable to disable configured targets 'minio-ercot-cop:webhook'.
>
> You should make sure to disable and enable new targets that replace
> existing targets should be unregistered from existing bucket configurations.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/minio/minio/pull/14203#issuecomment-1025059564>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACEFZVMUMCN72MRMMWM7PLUYSVRDANCNFSM5M7JINZQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-30 17:20 UTC, harshavardhana commented
> I had to —force remove all events on the bucket I suspected it to be attached. This odd event didn’t show up in any list. Things are back to normal, I think.

👍🏽 we added this PR to potentially avoid the issue you had, so you shouldn't have future problems in this manner because unset or deletion of notification targets should require prior removal on the bucket notification configuration first. 

The PR ensures that an active setting is not allowed to be "reset" or "removed"