Minio helm chart improvements for user and policy creation
minio/minio pull request #14216
Opened 2022-01-31 14:03 UTC by jescalona-lf

## Description
Added support to helm chart to define policies in addition to default ones and create user with a secretKey based on existing secret.

## Motivation and Context
Looking forward to automate fine-grained permissions for users in Minio's helm chart and additionally, wanted to created new users based on existing K8S secrets.

## How to test this PR?

1. Clone repo and checkout branch
2. Change directory to cloned repo
3. Create 2 secrets in K8S:
`
$ kubectl create secret bucket1-secret --from-literal=secretKey=bucket1
$ kubectl create secret bucket2-secret --from-literal=secretKey=bucket2
`
4. Deploy Minio cluster using the following test-values.yml file:
`
$ cat test-values.yml
buckets:
  - name: bucket1
    policy: none
    purge: false
    versioning: false
  - name: bucket2
    policy: none
    purge: false
    versioning: false

policies:
  - name: bucket1
    statements:
      - resources: 
          - 'arn:aws:s3:::bucket1/*'
          - 'arn:aws:s3:::bucket1'
        actions:
          - "s3:ListBucket"
          - "s3:ListBucketMultipartUploads"          
          - "s3:AbortMultipartUpload"
          - "s3:GetObject"
          - "s3:DeleteObject"
          - "s3:PutObject"
          - "s3:ListMultipartUploadParts"
          - "s3:CreateBucket"
          - "s3:DeleteBucket"
          - "s3:GetBucketLocation"
  - name: bucket2
    statements:
      - resources: 
          - "arn:aws:s3:::bucket2/*"
          - "arn:aws:s3:::bucket2"
        actions:          
          - "s3:GetObject"
          - "s3:GetBucketLocation"
          - "s3:ListBucket"
          - "s3:ListBucketMultipartUploads"          

users:
  - accessKey: bucket1AccessKey
    existingSecretKey: secretKey
    existingSecret: bucket1-secret
    policy: bucket1
  - accessKey: bucket2AccessKey
    existingSecretKey: secretKey
    existingSecret: bucket2-secret
    policy: bucket2
$ helm install minio-test . -f values.yaml -f test-values.yml
`
5. Validate policies were created. 
6. Verify that users bucket1AccessKey and bucket2AccessKey
7. Verify that users can authenticate with the secrets created previously

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation updated
- [ ] Unit tests added/updated

2022-01-31 14:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>

Deleting image locally

2022-02-01 03:01 UTC, harshavardhana requested changes

2022-02-01 03:01 UTC, harshavardhana commented on helm/minio/templates/_helper_create_policy.txt
> +  MC_COMMAND="${MC} config host add myminio $SCHEME://$MINIO_ENDPOINT:$MINIO_PORT $ACCESS $SECRET" ;
```suggestion
  MC_COMMAND="${MC} alias set myminio $SCHEME://$MINIO_ENDPOINT:$MINIO_PORT $ACCESS $SECRET" ;
```

2022-02-01 03:01 UTC, harshavardhana commented on helm/minio/templates/_helper_policy.tpl
> +      },
```suggestion
      "Principal": {
        "AWS": [
          "*"
        ]
      },
```

IAM policies do not carry principals, remove please.

2022-02-01 03:01 UTC, harshavardhana commented on helm/minio/templates/configmap.yaml
> +{{ end }}
newline missing.

2022-02-01 03:01 UTC, harshavardhana commented on helm/minio/templates/post-install-create-policy-job.yaml
> +              path: CAs/public.crt
should this not be `/.mc/certs/CAs/public.crt` ?

2022-02-01 03:01 UTC, harshavardhana commented on helm/minio/templates/post-install-create-policy-job.yaml
> +{{- end }}
newline

2022-02-01 03:01 UTC, harshavardhana commented on helm/minio/values.yaml
> +#     - resources:
some of these resources need to have wildcard at the end to work can you update?

2022-02-01 09:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-01 09:48 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-01 10:07 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-01 23:54 UTC, harshavardhana approved these changes

2022-02-13 23:46 UTC, harshavardhana approved these changes

2022-02-14 00:22 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-14 01:14 UTC, harshavardhana approved these changes
Thanks for all the helpful changes.

2022-02-14 01:14 UTC, merged

2022-02-14 08:55 UTC, jescalona-lf commented
It's my pleasure @harshavardhana