Always check for root disks unless MINIO_CI_CD is set
minio/minio pull request #14232
Opened 2022-02-02 12:52 UTC by vadmeste

## Description
The code which is deciding that if we can write in a root disks is
sometimes per pool aware - which has bad consequence if another pool
is running over root disks, like when a user badly configures disk
mounts and restarts some nodes of the second pool.

Simplify the logic by requiring MINIO_CI_CD in order to skip root disk
check.

## Motivation and Context
Avoid writing in root disks when a user wrongly mounts disks
of one given pool.

## How to test this PR?
Hard without faking some code

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-02-02 13:11 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-03 06:08 UTC, harshavardhana commented
I did some improvements in this PR #14239

2022-02-03 08:51 UTC, harshavardhana commented on cmd/xl-storage.go
>  	}
removing this part won't work check there is a slight optimization as well when globalRootDiskThreshold is provided we don't have to detect RootDisk code at all we can directly do GetInfo()

PTAL #14239

2022-02-04 20:26 UTC, harshavardhana commented
PR https://github.com/minio/minio/pull/14239 already handles this part @vadmeste - I don't think this PR is needed.

2022-02-08 20:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-08 20:47 UTC, harshavardhana requested changes

2022-02-08 20:47 UTC, harshavardhana commented on cmd/xl-storage.go
> +		rootDisk = info.Total <= globalRootDiskThreshold
the problem with this approach is there are 'two' calls wasted when there is globalRootDiskThreshold set - the change that was done previously was to ensure that when `globalRootDiskThreshold` is set we have no reason to validate disk.IsRootDisk() or not. 

We simply have to just rely on either globalRootDiskThreshold or disk.IsRootDisk() - it is not required for disk.IsRootdisk() to be false to check globalRootDiskThreshold

2022-02-09 13:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#d4d6f037-8e93-4d4d-a00e-6d2f3c9ce3bb) |
<a name="d4d6f037-8e93-4d4d-a00e-6d2f3c9ce3bb"></a>
### 14232-4e35ca1/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:30225
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 10 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 56 seconds
(4/14) Running aws-sdk-ruby tests ... done in 22 seconds
(5/14) Running awscli tests ... FAILED in 2 minutes and 25 seconds
{
  "name": "awscli",
  "duration": 91612,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-25981/awscli-mint-test-bucket-25981-objectremove_bucket failed: s3://awscli-mint-test-bucket-25981 An error occurred (SlowDown) when calling the DeleteBucket operation (reached max retries: 4): Resource requested is unreadable, please reduce your request rate"
}
(5/14) Running healthcheck tests ... done in 10 seconds
(6/14) Running mc tests ... FAILED in 11 seconds
{
  "name": "mc",
  "duration": "4999",
  "function": "test_rb",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-29708 --quiet --no-color mb myminio/mc-test-bucket-26195-1  >>> \nmc: <ERROR> Unable to make bucket `myminio/mc-test-bucket-26195-1`. Resource requested is unreadable, please reduce your request rate"
}
(6/14) Running minio-dotnet tests ... done in 1 minutes and 29 seconds
(7/14) Running minio-go tests ... done in 5 minutes and 15 seconds
(8/14) Running minio-java tests ... done in 3 minutes and 45 seconds
(9/14) Running minio-py tests ... FAILED in 10 minutes and 45 seconds
{
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-b8e9edd5-e2a9-4fec-a76d-c3185f72ef05",
    "object_name": "c9dbdc36-8e21-4f0e-a8c2-416bdda4b65e_0 ~ 0_1000"
  },
  "message": "S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-b8e9edd5-e2a9-4fec-a76d-c3185f72ef05, request_id: 16D220FBC93B769A, host_id: f496f8e3-5127-4ff6-81a9-e2898a8aabeb, bucket_name: minio-py-test-b8e9edd5-e2a9-4fec-a76d-c3185f72ef05",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 1243, in test_list_objects_with_1001_files\n    _CLIENT.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 669, in remove_bucket\n    self._execute(\"DELETE\", bucket_name)\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 397, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 380, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketNotEmpty, message: The bucket you tried to delete is not empty, resource: /minio-py-test-b8e9edd5-e2a9-4fec-a76d-c3185f72ef05, request_id: 16D220FBC93B769A, host_id: f496f8e3-5127-4ff6-81a9-e2898a8aabeb, bucket_name: minio-py-test-b8e9edd5-e2a9-4fec-a76d-c3185f72ef05\n",
  "duration": 589247
}
(9/14) Running s3cmd tests ... done in 1 minutes and 22 seconds
(10/14) Running s3select tests ... done in 2 minutes and 32 seconds
(11/14) Running versioning tests ... done in 6 minutes and 1 seconds

Executed 11 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-02-09 18:12 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#2d4244bd-a8c3-4b86-b20f-9df26379eb6f) |
<a name="2d4244bd-a8c3-4b86-b20f-9df26379eb6f"></a>
### 14232-bfdc8e4/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:30485
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 22 seconds
(5/14) Running awscli tests ... FAILED in 3 minutes and 17 seconds
{
  "name": "awscli",
  "duration": 130618,
  "function": "aws --endpoint-url http://minio-k8s8:30485 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-12455/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-12455/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-12455/datafile-1-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-12455/datafile-1-bupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-12455/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-12455/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-12455/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-12455/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-12455/datafile-5-MBupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-12455/datafile-6-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-12455/datafile-5243880-bupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-12455/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-12455/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-12455/datafile-65-MBupload: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-12455/datafile-129-MBupload failed: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-12455/datafile-10-kB An error occurred (SlowDown) when calling the PutObject operation (reached max retries: 4): Resource requested is unreadable, please reduce your request rate"
}
(5/14) Running healthcheck tests ... done in 3 seconds
(6/14) Running mc tests ... FAILED in 7 seconds
{
  "name": "mc",
  "duration": "5245",
  "function": "test_rb",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-5307 --quiet --no-color rb myminio/mc-test-bucket-18459-1  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-18459-1`. Resource requested is unreadable, please reduce your request rate."
}
FAILED in 1 minutes and 22 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (MinIO API responded with message=Resource requested is unreadable, please reduce your request rate)) ---> System.AggregateException: One or more errors occurred. (MinIO API responded with message=Resource requested is unreadable, please reduce your request rate) ---> Minio.Exceptions.UnexpectedMinioException: MinIO API responded with message=Resource requested is unreadable, please reduce your request rate
   at Minio.MinioClient.ParseErrorFromContent(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 538
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 431
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 605
   at Minio.MinioClient.ExecuteTaskCoreAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 405
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 532
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 301
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 806
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2048
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/Program.cs:line 137
(6/14) Running minio-go tests ... done in 3 minutes and 0 seconds
(7/14) Running minio-java tests ... done in 33 seconds
(8/14) Running minio-py tests ... done in 1 minutes and 29 seconds
(9/14) Running s3cmd tests ... done in 23 seconds
(10/14) Running s3select tests ... done in 4 seconds
(11/14) Running versioning tests ... 
Aborting Mint...
Running with
SERVER_ENDPOINT:      minio-k8s8:30485
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... 
Aborting Mint...
Running with
SERVER_ENDPOINT:      minio-k8s8:30485
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 20 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 1 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 3 seconds
(10/14) Running minio-java tests ... done in 32 seconds
(11/14) Running minio-py tests ... done in 1 minutes and 27 seconds
(12/14) Running s3cmd tests ... done in 24 seconds
(13/14) Running s3select tests ... done in 5 seconds
(14/14) Running versioning tests ... done in 3 minutes and 4 seconds

All tests ran successfully
```
Deleting imag [...]

2022-02-09 19:47 UTC, harshavardhana approved these changes

2022-02-10 18:37 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-13 23:42 UTC, merged