Send deployment id and minio version in http header
minio/minio pull request #14378
Opened 2022-02-22 14:42 UTC by anjalshireesh

## Description

Send deployment id and minio version in the http headers
`x-minio-version` and `x-minio-deployment-id` respectively.

## Motivation and Context

Going forward, these can be used by the webhook targets to
- uniquely identify the cluster
- use the minio version to understand the payload format (in cases where the format has changed between versions)

## How to test this PR?

- Configure a logger webhook (where you can inspect headers of the webhook payload e.g. https://webhook.site/)
- Simulate an event in the cluster that triggers the webhook call
- Verify that the webhook request contains the two new headers

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-02-22 15:01 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-22 16:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-22 16:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-22 18:10 UTC, harshavardhana requested changes

2022-02-22 18:10 UTC, harshavardhana commented on internal/http/server.go
> +
```suggestion
var (
     // GlobalMinIOVersion - is sent in the header to all http targets 
     GlobalMinIOVersion string
     
     // GlobalDeploymentID - is sent in the header to all http targets
     GlobalDeploymentID string
```

2022-02-23 05:18 UTC, harshavardhana approved these changes

2022-02-23 05:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-23 05:21 UTC, anjalshireesh commented on internal/http/server.go
> +
Thanks, done.

2022-02-23 18:13 UTC, harshavardhana commented
ptal @donatello

2022-02-23 21:30 UTC, donatello approved these changes

2022-02-23 21:36 UTC, merged