select: add MISSING operator support
minio/minio pull request #14406
Opened 2022-02-24 17:04 UTC by klauspost

## Description
Probably not full support, but for regular checks it should work.

Fixes https://github.com/minio/minio/issues/14358
Includes https://github.com/minio/minio/pull/14405

## Types of changes
- [x] New feature (non-breaking change which adds functionality)
- [x] Unit tests added/updated

2022-02-24 17:12 UTC, harshavardhana requested changes

2022-02-24 17:12 UTC, harshavardhana commented on internal/s3select/sql/value.go
> +	fmt.Println("a:", a.GetTypeString(), op, "v:", v.GetTypeString())
Looks like needs to be removed.

2022-02-24 17:24 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-24 17:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-24 21:11 UTC, harshavardhana commented
Looks like some test failures with simdj

```
ok  	github.com/minio/minio/internal/s3select/simdj	0.004s
sql.Missing{} (sql.Missing) != <nil> (<nil>)
--- FAIL: TestJsonpathEval (0.00s)
    jsonpath_test.go:93: case: 4 2 failed
FAIL
```

2022-02-25 09:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-02-25 11:15 UTC, harshavardhana approved these changes

2022-02-25 19:58 UTC, donatello approved these changes

2022-02-25 20:31 UTC, merged