Disallow root disk to be used for cache drives
minio/minio pull request #14513
Opened 2022-03-09 23:13 UTC by poornas

## Description

## Motivation and Context

## How to test this PR?
Set MINIO_CACHE_DRIVES - should fail if root disk specified.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-03-09 23:16 UTC, harshavardhana requested changes

2022-03-09 23:16 UTC, harshavardhana commented on internal/config/cache/config.go
> +		if runtime.GOOS != "windows" && !isCICD {
IsRootDisk() handles windows so its  okay to only have this check when CICD is false.

2022-03-09 23:33 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-09 23:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-10 02:24 UTC, harshavardhana approved these changes

2022-03-10 10:33 UTC, vadmeste approved these changes
LGTM

2022-03-10 10:45 UTC, merged

2022-03-10 10:46 UTC, klauspost commented
@harshavardhana @poornas 

It seems user hostile to disable it on upgrade.

Could we add a strongly worded warning and disable it in 6 months?

2022-03-10 10:47 UTC, harshavardhana commented
> It seems user hostile to disable it on upgrade.

We can @klauspost  - we can support existing settings, and warn about it. however, disallow setting newer values.

2022-03-10 11:05 UTC, klauspost commented
@harshavardhana Yeah, it may require hardware changes to fix. It is not a critical error that will (short term) cause data corruption, so it shouldn't kill the server on upgrade, but we shouldn't allow it for new/changed installs.