do not crash readXLMetaNoData - if the `xl.meta` has incorrect content
minio/minio pull request #14538
Opened 2022-03-13 00:42 UTC by harshavardhana

## Description
do not crash readXLMetaNoData - if the `xl.meta` has incorrect content

## Motivation and Context
```
tmp = buf[want:]
```

Would potentially crash when `buf` is truncated for some reason
and does not have the expected bytes, this is of course considered
not normal and is an odd situation. But we do not attempt to crash
here instead allow for errors to be returned.

## How to test this PR?
Following attached xl.meta file will crash the server. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-03-13 01:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-13 04:44 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-13 05:28 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-13 09:38 UTC, klauspost requested changes

2022-03-13 09:38 UTC, klauspost commented on cmd/xl-storage-format-v2.go
> +				return nil, fmt.Errorf("readXLMetaNoData(msgp.ReadBytesHeader): uknown metadata version %w -> %s ", err, path)
```suggestion
				return nil, fmt.Errorf("readXLMetaNoData(read_meta): %w -> %s ", err, path)
```

2022-03-13 09:38 UTC, klauspost commented on cmd/xl-storage-format-v2.go
> +				return nil, fmt.Errorf("readXLMetaNoData(msgp.ReadUint32Bytes): unknown metadata version %w -> %s ", err, path)
```suggestion
				return nil, fmt.Errorf("readXLMetaNoData(read_crc): %w -> %s" , err, path)
```

2022-03-13 09:38 UTC, klauspost commented on cmd/xl-storage-format-v2.go
> +func readXLMetaNoData(r io.Reader, size int64, path string) ([]byte, error) {
Add the path to the error upstream.

2022-03-13 09:38 UTC, klauspost commented on cmd/xl-storage-format-v2.go
> +				return nil, fmt.Errorf("buffer shorter than expected buflen: %d, want: %d -> %s", len(buf), want, path)
Maybe wrap an errCorrupt

2022-03-13 20:55 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-13 21:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-14 07:19 UTC, klauspost approved these changes

2022-03-14 10:35 UTC, vadmeste approved these changes
LGTM

2022-03-14 16:07 UTC, merged