PutObjectPart: set SSE-KMS headers and truncate ETags.
minio/minio pull request #14578
Opened 2022-03-18 23:29 UTC by aead

## Description
This commit fixes two bugs in the `PutObjectPartHandler`.
First, `PutObjectPart` should return SSE-KMS headers
when the object is encrypted using SSE-KMS.
Before, this was not the case.

Second, the ETag should always be a 16 byte hex string,
perhaps followed by a `-X` (where `X` is the number of parts).
However, `PutObjectPart` used to return the encrypted ETag
in case of SSE-KMS. This leaks MinIO internal etag details
through the S3 API.

The combination of both bugs causes clients that use SSE-KMS
to fail when trying to validate the ETag. Since `PutObjectPart`
did not send the SSE-KMS response headers, the response looked
like a plaintext `PutObjectPart` response. Hence, the client
tries to verify that the ETag is the content-md5 of the part.
This could never be the case, since MinIO used to return the
encrypted ETag.

Therefore, clients behaving as specified by the S3 protocol
tried to verify the ETag in a situation they should not.

***

This needs a separate mint test.

## Motivation and Context
SSE-KMS, S3 compatibility.

## How to test this PR?
Start MinIO and configure a bucket with `SSE-KMS`: `mc encrypt set sse-kms <key-id> <alias>`
Upload a large file using `mc cp --debug` and compare the ETag and response header.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-03-18 23:30 UTC, harshavardhana approved these changes

2022-03-18 23:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-19 01:25 UTC, harshavardhana approved these changes

2022-03-19 01:42 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-19 02:19 UTC, harshavardhana commented
@aead - this ends up breaking `CompleteMultipart` since we need to validate the incoming Parts sent by the client 

```
"name": "mc", "duration": "582", "function": "test_put_object_multipart", "status": "FAIL", "error": "/home/runner/work/minio/minio/.verify-16095/mc --config-dir /tmp/.mc-9132 --quiet --no-color cp /home/runner/work/minio/minio/.verify-16095/data/datafile-65-MB myminio/mc-test-bucket-4065/mc-test-object-7083  >>> \n`/home/runner/work/minio/minio/.verify-16095/data/datafile-65-MB` -> `myminio/mc-test-bucket-4065/mc-test-object-7083`\nmc: <ERROR> Failed to copy `/home/runner/work/minio/minio/.verify-16095/data/datafile-65-MB`. One or more of the specified parts could not 
```

We need a way to "remap" the sent ETag back to its original form

2022-03-19 08:59 UTC, aead commented
@harshavardhana In case of multi-part upload the client has to do the following:
 1. If the object is not encrypted, verify that part ETag is `MD5(part)`. Further, verify that complete multi part ETag is `MD5(ETag1, ETag2, ...)`.
 2. If the object is encrypted with SSE-S3 apply the same checks as 1.
 3. If the object is encrypted using SSE-KMS only check that the complete multi part ETag is `MD5(ETag1, ETag2, ...)`.
     The ETag of each part has no connection to the part since it is a random 16 byte hex string.

2022-03-19 10:39 UTC, harshavardhana commented
> 3\. The ETag of each part has no connection to the part since it is a random 16 byte hex string.

no @aead complete multipart needs to verify what is the etag that is persisted on the server - if this etag is sent with a shorter version - server-side receiving end should verify this. 

that's why the CI is failing - this PR is an incomplete fix you need to fix the CompleteMultipart as well

2022-03-19 10:41 UTC, harshavardhana requested changes
CompleteMultIpart API also needs change to handle the incoming Etag translation and verification for correct part numbers to complete the upload successfully. 

this was working before because the etag was verified verbatim

2022-03-19 11:07 UTC, aead commented
> CompleteMultIpart API also needs change

2022-03-19 11:13 UTC, aead commented
> CompleteMultIpart API also needs change

Yes, agree.

Just to summarize what is the S3 behavior that should be implemented.
In all cases, for a multi-part object the final etag of the object is:
```
ETAg = Hex(MD5(ETag_p1, ETag_p2, ETag_p3, ...))+"-N`
```

The ETag of each part depends upon whether the object is encrypted and the encryption method.
In case of SSE-C and SSE-KMS the ETag of a part is not the MD5 of the part content. Instead, it is
a random value with the same length as a MD5 ETag.

2022-03-19 12:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-19 12:55 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-19 16:44 UTC, harshavardhana approved these changes

2022-03-19 16:44 UTC, harshavardhana approved these changes

2022-03-19 17:15 UTC, merged