ListObjects: Filter lifecycle expired objects
minio/minio pull request #14606
Opened 2022-03-22 09:55 UTC by klauspost

## Description

For ListObjects and ListObjectsV2 perform lifecycle checks on all objects before returning.

This will filter out objects that are pending lifecycle expiration.

Bonus: Cheaper server pool conflict resolution by not converting to FileInfo.

## How to test this PR?

Required expired objects that have not been cleaned. List them.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2022-03-22 10:16 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-22 16:18 UTC, harshavardhana requested changes

2022-03-22 16:18 UTC, harshavardhana commented on cmd/metacache-server-pool.go
> +		out <- obj
do we not want to do 

```
select {
case <-ctx.Done():
..
```

2022-03-22 16:51 UTC, klauspost commented on cmd/metacache-server-pool.go
> +		out <- obj
Could be - double checking call path.

2022-03-22 17:02 UTC, klauspost commented on cmd/metacache-server-pool.go
> +		out <- obj
@harshavardhana Added for both blocking operations 👍🏼

2022-03-22 17:25 UTC, harshavardhana approved these changes

2022-03-22 18:21 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-22 18:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-03-22 19:39 UTC, merged

2022-03-24 08:49 UTC, WolfspiritM commented
@klauspost I've a question about this change. Currently in our case with millions of files the lifecyclepolicy is way too slow and doesn't delete the files in time (even with a faster scanner). We have our files structured with the date in the path/prefix so we made a script that lists all old files and deletes them manually while still having the lifecyclepolicy available.

That script wouldn't work anymore as it won't be able to receive any files after this change, right?
Will the files be deleted right when listed or are they just filtered out and the scanner still needs to reach them?

Cause that would mean we have to disable the lifecyclepolicy completly now.

2022-03-24 08:53 UTC, klauspost commented
@WolfspiritM You can list versions. These are not filtered, as they are also needed for deleting all objects in a bucket, so that is not too likely to change.

2022-03-24 09:14 UTC, WolfspiritM commented
@klauspost We're not using versioning in that bucket to not create even more metadata for our millions of small files. Does listing versions work for a non versioned bucket? A quick test return 404 Not Found but I'm not sure if the reason is that Versioning is disabled.

2022-03-24 09:57 UTC, harshavardhana commented
> @klauspost We're not using versioning in that bucket to not create even more metadata for our millions of small files. Does listing versions work for a non versioned bucket? A quick test return 404 Not Found but I'm not sure if the reason is that Versioning is disabled.

Even without using versioning the API will behave as explained by @klauspost