Bring back listing LDAP users temporarly
minio/minio pull request #14760
Opened 2022-04-15 17:09 UTC by vadmeste

## Description
In previous releases, mc admin user list would return the list of users
that have policies mapped in IAM database. However, this was removed but
this commit will bring it back until we revmap this.

## Motivation and Context
Revert back mc admin user list to list LDAP users with associated policies

## How to test this PR?
- Have an LDAP server with a user in it
- Start MinIO with a configured LDAP
- List users with mc admin user list myminio

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-04-15 17:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-04-15 18:55 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-04-15 19:16 UTC, harshavardhana approved these changes

2022-04-15 19:20 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-04-15 21:12 UTC, harshavardhana commented
PTAL @donatello

2022-04-15 21:35 UTC, donatello commented
This does not yet list policies inherited via group memberships - I guess that's ok for now?

2022-04-15 22:36 UTC, vadmeste commented
> This does not yet list policies inherited via group memberships - I guess that's ok for now?

@donatello 'master' does that already. I did not have to add it.

2022-04-15 23:53 UTC, donatello requested changes

2022-04-15 23:53 UTC, donatello commented on cmd/iam-store.go
> +	for k, v := range cache.iamUserPolicyMap {
This map only contains users with directly mapped policies.

To get policies inherited from group memberships, see `cache.iamUserGroupMemberships` for a list of groups that the user belongs to and then lookup `cache.iamGroupPolicyMap` for a list of policies mapped to each such group.

2022-04-16 00:21 UTC, donatello commented on cmd/iam-store.go
> +	for k, v := range cache.iamUserPolicyMap {
Actually this is not right for ldap. Need to check group membership in the credentials, object and then check mapped policies.

2022-04-16 04:22 UTC, donatello approved these changes

2022-04-16 04:26 UTC, merged