Limit the number of parallel trace/bucket notifications listeners
minio/minio pull request #14799
Opened 2022-04-22 11:34 UTC by vadmeste

## Description
By default, MinIO calculates the number of the maximum parallel
connections based on the available memory. However, there is a use case
when a client sets up too many bucket notifications which can saturate
the number of total S3 requests.

This commit limits the number of trace listeners to 4, console logs
listeners to 4 and bucket notifications listeners to 256. All of them
per server.

## Motivation and Context
Limit the number of concurrent bucket notifications to limit rate requests starvation

## How to test this PR?
Maybe start a simple MinIO server
Start many mc watch commands until you see some erors

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-04-22 11:54 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-04-22 12:07 UTC, klauspost commented
Sounds reasonable with a limit. A few Qs

Are admin requests "S3" requests?
Would it be reasonable for bucket notifications (which are S3 requests) to be a fraction of the s3 request limit?

2022-04-22 13:07 UTC, vadmeste commented
> Would it be reasonable for bucket notifications (which are S3 requests) to be a fraction of the s3 request limit?

I guess so, maybe I can rewrite this PR to use a different requests queue for admin requests, this looks like a better idea

2022-04-22 14:00 UTC, mshanmu commented
@vadmeste , Suggestion, please try to make these limits configurable instead of hardcoding them.

2022-04-22 15:32 UTC, harshavardhana commented
> @vadmeste , Suggestion, please try to make these limits configurable instead of hardcoding them.

We should keep them sane values, this doesn't need to be configurable for now @vadmeste .

We need to absolutely sure why anyone needs this configurable because existing limits are already enough and should be sufficient to avoid abuse.

Keeping them as separate limits in API is not necessary. The functionality here is specific to certain calls that keep the client connections Open.. we need to make sure to manage them appropriately.

We should IMO skip the ListenBucket notification from the S3 request queue since it's a zero memory operation and has no I/O. We do not have to allow ListenBucket to take requests from the actual S3 request queue.

This automatically already fixes the problem we saw @vadmeste  - beyond that limiting these APIs to a certain top level number is something that can be done subsequently.

2022-04-25 11:14 UTC, vadmeste commented
> We should keep them sane values, this doesn't need to be configurable for now @vadmeste .

I like the idea of a separate queue because some users might be listening to many buckets at the same time. Something like `mc mirror --watch <alias> <destination`

The current value is 256 per node. I can bump to 1000.

2022-06-03 14:43 UTC, vadmeste commented
I updated the PR. Trace listeners is limited to 8 listeners per node. No limit for bucket notifications.

2022-06-03 15:05 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-03 15:54 UTC, harshavardhana requested changes

2022-06-03 15:54 UTC, harshavardhana commented on internal/pubsub/pubsub.go
> +		return errors.New("maximum clients subscribed exceeded")
fmt.Errorf() to indicate current subscribers and what is maximum allowed?

2022-06-03 17:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-05 21:27 UTC, harshavardhana approved these changes

2022-06-05 21:29 UTC, merged