If decom of an object fails, retry for 3 times
minio/minio pull request #14861
Opened 2022-05-04 17:38 UTC by krishnasrinivas

## Description
During decom, many objects were left in old pool. This can happen if there are network issues during decom of an object. Hence we can retry 3 times if decom of object fails.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-05-04 17:43 UTC, harshavardhana requested changes

2022-05-04 17:43 UTC, harshavardhana commented on cmd/erasure-server-pool-decom.go
> +					}
This retry will not work since the `gr` will be closed and the subsequent reads will fail @krishnasrinivas

2022-05-04 18:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-05-11 02:37 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-05-11 07:09 UTC, harshavardhana approved these changes

2022-05-11 10:29 UTC, klauspost approved these changes
LGTM

2022-05-11 18:37 UTC, merged