allow versioning config changes under site replication
minio/minio pull request #14876
Opened 2022-05-07 22:51 UTC by harshavardhana

## Description
allow versioning config changes under site replication

## Motivation and Context
PR #14828 introduced prefix-level exclusion of versioning
and replication - however our site replication implementation
since it defaults versioning on all buckets did not allow
changing versioning configuration once the bucket was created.

This PR changes this and ensures that such changes are honored
and also propagated/healed across sites appropriately.

## How to test this PR?
```
#!/bin/bash

set -x

export MINIO_ROOT_USER=minio
export MINIO_ROOT_PASSWORD=minio123

export MC_HOST_minio1=http://minio:minio123@localhost:9001/
export MC_HOST_minio2=http://minio:minio123@localhost:9002

rm -rf /tmp/xl*
pkill -9 minio

(minio server --address ":9001" /tmp/xl{1...4})&
pid1=$!

(minio server --address ":9002" /tmp/xl{5...8})&
pid2=$!

sleep 5

mc admin replicate add minio1 minio2

mc mb minio1/spark-bucket
mc version enable minio1/spark-bucket --excluded-prefixes "spark-job/*/_temporary/" --exclude-folders
```

Observe with `mc admin trace -v` that the versioning config is applied properly across sites.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-05-07 23:04 UTC, poornas requested changes

2022-05-07 23:04 UTC, poornas commented on cmd/site-replication.go
> +				logger.LogIf(ctx, fmt.Errorf("Error healing sse metadata from peer site %s : %w", latestPeerName, err))
```suggestion
				logger.LogIf(ctx, fmt.Errorf("Error healing versioning metadata from peer site %s : %w", latestPeerName, err))
```

2022-05-07 23:16 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-05-07 23:26 UTC, poornas approved these changes
LGTM

2022-05-07 23:42 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#316400ff-2e1a-45e8-a18d-4fce037f425f) |
<a name="316400ff-2e1a-45e8-a18d-4fce037f425f"></a>
### 14876-9a3246a/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:30486
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 8 seconds
(5/15) Running awscli tests ... done in 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 11 seconds
(9/15) Running minio-go tests ... FAILED in 24 seconds
panic: unexpected EOF

goroutine 1 [running]:
main.crcMatchesName({0x920d80, 0xc0008664e0}, {0x81a5be, 0x1e})
	/mint/run/core/minio-go/main.go:329 +0x145
main.testPutObjectWithMetadata()
	/mint/run/core/minio-go/main.go:2088 +0xe25
main.main()
	/mint/run/core/minio-go/main.go:12141 +0x305
(9/15) Running minio-java tests ... done in 38 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 7 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 50 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-05-08 00:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-05-08 00:13 UTC, krisis approved these changes

2022-05-08 01:39 UTC, merged