Cancel old logger/audit targets outside lock
minio/minio pull request #14927
Opened 2022-05-16 19:45 UTC by vadmeste

## Description
When configuring a new target, such as audit target, the server waits
until all audit events are sent to the audit target before doing the
swap from the old to the new audit target. Therefore current S3 operations
can suffer from this since the audit swap lock will be held.

This behavior is unnecessary as the new audit target can enter in a
functional mode immediatly and the old audit will just cancel itself
with its own pace.

## Motivation and Context
Accelerate audit config update when the audit endpoint is slow
and avoid causing S3 ops temporary freeze

## How to test this PR?
Have a slow audit endpoint and run `mc admin config set <minio> audit_webhook endpoint=http://localhost:8080`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-05-16 19:45 UTC, harshavardhana requested changes
@vadmeste this is a wrong implementation

2022-05-16 19:51 UTC, vadmeste commented
> @vadmeste this is a wrong implementation

Why ? This is just an optimization. We really don't have to run old target cancellations under a lock.

I will send the config decoupling in another PR

2022-05-16 20:12 UTC, harshavardhana approved these changes
LGTM - internally discussed

2022-05-16 20:32 UTC, merged

2022-05-17 00:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally