error out in listing service account if user not present
minio/minio pull request #14938
Opened 2022-05-18 05:52 UTC by sinhaashish

## Description
Details in issue https://github.com/minio/minio/issues/14937

Fixes #14937 
## Motivation and Context

## How to test this PR?

Do a service account listing on some non existing user 
It should error out as shown below
```
ashish@ashish:~/code/go/src/github/minio/mc$ ./mc admin user svcacct list myminio alpha1
mc: <ERROR> Unable to list service accounts. The specified user does not exist. (Specified user does not exist).
```

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-05-18 06:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-05-19 09:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-05-22 23:03 UTC, harshavardhana commented
@sinhaashish can you take a look at the CI/CD failure?

2022-05-22 23:39 UTC, donatello commented
@sinhaashish as mentioned offline, parent account is virtual in LDAP and openid

2022-05-23 09:16 UTC, vadmeste reviewed
Maybe you can do the same thing for ListTempAccounts(), LGTM otherwise

2022-05-23 09:17 UTC, vadmeste commented
> @sinhaashish as mentioned offline, parent account is virtual in LDAP and openid

oh just saw this

2022-05-24 08:42 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-05-24 13:29 UTC, harshavardhana requested changes

2022-05-24 13:29 UTC, harshavardhana commented on cmd/iam-store.go
> -	cache := store.rlock()
How will this work?

2022-05-25 22:29 UTC, harshavardhana commented
should this PR be closed since #14977 this is merged? @donatello @sinhaashish ?

2022-05-25 23:16 UTC, donatello commented
> should this PR be closed since #14977 this is merged? @donatello @sinhaashish ?

Yes

2022-05-26 04:26 UTC, closed without merging