Add API's to import/export IAM data
minio/minio pull request #15014
Opened 2022-06-01 02:40 UTC by poornas

## Description

## Motivation and Context
Ability to backup IAM data from a cluster and be able to import to a new cluster as needed.

## How to test this PR?
needs companion PR's https://github.com/minio/mc/pull/4102 and https://github.com/minio/madmin-go/pull/83

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-06-01 02:41 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 15014-511009d/gopath/src/github.com/minio
+ git -C 15014-511009d/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 15014-511009d/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 15014-511009d/gopath/src/github.com/minio/minio fetch --quiet minio pull/15014/head:pr15014
+ git -C 15014-511009d/gopath/src/github.com/minio/minio checkout --quiet pr15014
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/15014-511009d/gopath
+ make -C 15014-511009d/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/madmin-go v1.3.14
go: downloading github.com/minio/minio-go/v7 v7.0.27
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/klauspost/compress v1.15.1
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
go: downloading github.com/golang-jwt/jwt/v4 v4.4.1
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading golang.org/x/sys v0.0.0-20220502124256-b6088ccd6cba
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/Shopify/sarama v1.30.0
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/minio/kes v0.19.2
go: downloading golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
go: downloading github.com/bits-and-blooms/bloom/v3 v3.0.1
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/minio/console v0.17.2
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/go-openapi/loads v0.21.1
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/klauspost/readahead v1.4.0
go: downloading github.com/felixge/fgprof v0.9.2
go: downloading github.com/coreos/go-oidc v2.1.0+incompatible
go: downloading github.com/klauspost/reedsolomon v1.9.15
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/minio/dperf v0.3.6
go: downloading github.com/miekg/dns v1.1.48
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/minio/selfupdate v0.4.0
go: downloading github.com/prometheus/client_golang v1.12.1
go: downloading github.com/philhofer/fwd v1.1.2-0.20210722190033-5c56ac6d0bb9
go: downloading github.com/minio/zipindex v0.2.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/shirou/gopsutil/v3 v3.22.2
go: downloading github.com/tinylib/msgp v1.1.7-0.20211026165309-e818a1881b0e
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/yargevad/filepathx v1.0.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.4
go: downloading go.etcd.io/etcd/client/v3 v3.5.4
go: downloading go.uber.org/atomic v1.9.0
go: downloading golang.org/x/oauth2 v0.0.0-20220411215720-9780585627b5
go: downloading google.golang.org/api v0.78.0
go: downloading github.com/zeebo/xxh3 v1.0.0
go: downloading github.com/go-ldap/ldap/v3 v3.4.3
go: downloading github.com/minio/simdjson-go v0.4.2
go: downloading go.uber.org/zap v1.21.0
go: downloading golang.org/x/time v0.0.0-20220224211638-0e9765cccd65
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/coredns/coredns v1.9.2
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/fraugster/parquet-go v0.10.0
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.5
go: downloading github.com/elastic/go-elasticsearch/v7 v7.17.1
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/gomodule/redigo v1.8.8
go: downloading github.com/lib/pq v1.10.4
go: downloading github.com/nats-io/nats.go v1.13.1-0.20220308171302-2f2f6968e98d
go: downloading github.com/nats-io/stan.go v0.10.2
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/golang/protobuf v1.5.2
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4
go: downloading github.com/pquerna/cachecontrol v0.1.0
go: downloading gopkg.in/square/go-jose.v2 v2.5.1
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/klauspost/cpuid/v2 v2.0.11
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20211209120228-48547f28849e
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading github.com/bits-and-blooms/bitset v1.2.0
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading google.golang.org/grpc v1.46.0
go: downloading google.golang.org/genproto v0.0.0-20220429170224-98d788798c3e
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.4
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading golang.org/x/text v0.3.7
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/google/pprof v0.0.0-20211214055906-6f57359322fd
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading github.com/go-openapi/spec v0.20.5
go: downloading github.com/go-openapi/analysis v0.21.2
go: downloading github.com/go-openapi/swag v0.21.1
go: downloading go.uber.org/multierr v1.8.0
go: downloading google.golang.org/protobuf v1.28.0
go: downloading github.com/prometheus/common v0.34.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/coreos/go-systemd/v22 v22.3.2
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/apache/thrift v0.15.0
go: downloading github.com/rs/xid v1.4.0
go: downloading gopkg.in/ini.v1 v1.66.4
go: downloading github.com/nats-io/nkeys v0.3.0
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading github.com/tklauser/go-sysconf v0.3.10
go: downloading cloud.google.com/go v0.100.2
go: downloading github.com/josharian/intern v1.0.0
go: downloading github.com/go-openapi/strfmt v0.21.2
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/matttproud/golang_protobuf_ex [...]

2022-06-01 02:43 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 15014-3151827/gopath/src/github.com/minio
+ git -C 15014-3151827/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 15014-3151827/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 15014-3151827/gopath/src/github.com/minio/minio fetch --quiet minio pull/15014/head:pr15014
+ git -C 15014-3151827/gopath/src/github.com/minio/minio checkout --quiet pr15014
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/15014-3151827/gopath
+ make -C 15014-3151827/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/minio-go/v7 v7.0.27
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/minio/madmin-go v1.3.14
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading golang.org/x/sys v0.0.0-20220502124256-b6088ccd6cba
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/minio/kes v0.19.2
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/klauspost/compress v1.15.1
go: downloading github.com/fatih/color v1.13.0
go: downloading golang.org/x/crypto v0.0.0-20220411220226-7b82a4e95df4
go: downloading github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/golang-jwt/jwt/v4 v4.4.1
go: downloading github.com/Shopify/sarama v1.30.0
go: downloading github.com/Azure/azure-storage-blob-go v0.10.0
go: downloading github.com/dchest/siphash v1.2.1
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/gorilla/mux v1.8.0
go: downloading github.com/go-openapi/loads v0.21.1
go: downloading github.com/klauspost/readahead v1.4.0
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/miekg/dns v1.1.48
go: downloading github.com/yargevad/filepathx v1.0.0
go: downloading github.com/klauspost/reedsolomon v1.9.15
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading go.etcd.io/etcd/api/v3 v3.5.4
go: downloading github.com/minio/console v0.17.2
go: downloading github.com/minio/zipindex v0.2.1
go: downloading go.etcd.io/etcd/client/v3 v3.5.4
go: downloading github.com/coreos/go-oidc v2.1.0+incompatible
go: downloading github.com/bits-and-blooms/bloom/v3 v3.0.1
go: downloading github.com/zeebo/xxh3 v1.0.0
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/rs/cors v1.7.0
go: downloading go.uber.org/atomic v1.9.0
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/prometheus/client_model v0.2.0
go: downloading github.com/felixge/fgprof v0.9.2
go: downloading github.com/shirou/gopsutil/v3 v3.22.2
go: downloading github.com/minio/dperf v0.3.6
go: downloading github.com/tinylib/msgp v1.1.7-0.20211026165309-e818a1881b0e
go: downloading github.com/prometheus/procfs v0.7.3
go: downloading github.com/minio/selfupdate v0.4.0
go: downloading golang.org/x/oauth2 v0.0.0-20220411215720-9780585627b5
go: downloading google.golang.org/api v0.78.0
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/philhofer/fwd v1.1.2-0.20210722190033-5c56ac6d0bb9
go: downloading github.com/prometheus/client_golang v1.12.1
go: downloading github.com/cespare/xxhash/v2 v2.1.2
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/coredns/coredns v1.9.2
go: downloading go.uber.org/zap v1.21.0
go: downloading github.com/beevik/ntp v0.3.0
go: downloading golang.org/x/time v0.0.0-20220224211638-0e9765cccd65
go: downloading github.com/montanaflynn/stats v0.6.6
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/minio/simdjson-go v0.4.2
go: downloading github.com/go-ldap/ldap/v3 v3.4.3
go: downloading github.com/eclipse/paho.mqtt.golang v1.3.5
go: downloading github.com/elastic/go-elasticsearch/v7 v7.17.1
go: downloading github.com/go-sql-driver/mysql v1.6.0
go: downloading github.com/gomodule/redigo v1.8.8
go: downloading github.com/lib/pq v1.10.4
go: downloading github.com/nats-io/nats.go v1.13.1-0.20220308171302-2f2f6968e98d
go: downloading github.com/nats-io/stan.go v0.10.2
go: downloading github.com/nsqio/go-nsq v1.0.8
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/streadway/amqp v1.0.0
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/fraugster/parquet-go v0.10.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading golang.org/x/sync v0.0.0-20210220032951-036812b2e83c
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/bits-and-blooms/bitset v1.2.0
go: downloading golang.org/x/net v0.0.0-20220425223048-2871e0cb64e4
go: downloading github.com/klauspost/cpuid/v2 v2.0.11
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/pquerna/cachecontrol v0.1.0
go: downloading gopkg.in/square/go-jose.v2 v2.5.1
go: downloading github.com/xdg/stringprep v1.0.0
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20211209120228-48547f28849e
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading golang.org/x/text v0.3.7
go: downloading google.golang.org/genproto v0.0.0-20220429170224-98d788798c3e
go: downloading google.golang.org/grpc v1.46.0
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.4
go: downloading github.com/coreos/go-semver v0.3.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/prometheus/common v0.34.0
go: downloading github.com/google/pprof v0.0.0-20211214055906-6f57359322fd
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/go-openapi/analysis v0.21.2
go: downloading github.com/go-openapi/spec v0.20.5
go: downloading github.com/go-openapi/swag v0.21.1
go: downloading github.com/Azure/azure-pipeline-go v0.2.2
go: downloading google.golang.org/protobuf v1.28.0
go: downloading go.uber.org/multierr v1.8.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading cloud.google.com/go v0.100.2
go: downloading github.com/nats-io/nkeys v0.3.0
go: downloading github.com/apache/thrift v0.15.0
go: downloading github.com/coreos/go-systemd/v22 v22.3.2
go: downloading github.com/rs/xid v1.4.0
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading github.com/tklauser/go-sysconf v0.3.10
go: downloading gopkg.in/ini.v1 v1.66.4
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.2
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading github.com/jcmturner/gofork v1.0.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.2-0.20181231171920-c182affec369
go: downloading github.com/tklauser/numcpus v0.4.0
go: downloading github.com/josharian/intern v1.0.0
go: downloadin [...]

2022-06-11 01:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-19 01:03 UTC, harshavardhana commented
Please rebase @poornas

2022-06-19 06:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#c3d0ff96-851c-4a94-ac00-f81abdfe99a3) |
<a name="c3d0ff96-851c-4a94-ac00-f81abdfe99a3"></a>
### 15014-c81ea94/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:30085
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 6 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 8 seconds
(5/15) Running awscli tests ... done in 1 minutes and 1 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 31 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 19 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 35 seconds
(10/15) Running minio-java tests ... FAILED in 6 minutes and 33 seconds
{
  "name": "minio-java",
  "function": "removeObjects()",
  "args": "[3005 objects]",
  "duration": 300344,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: timeout >>> [okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:143), okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162), okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340), okio.RealBufferedSource.indexOf(RealBufferedSource.kt:449), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:333), okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29), okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(10/15) Running minio-js tests ... done in 1 minutes and 4 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 30 seconds
(12/15) Running s3cmd tests ... done in 25 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-06-19 16:27 UTC, harshavardhana requested changes

2022-06-19 16:27 UTC, harshavardhana commented on cmd/admin-bucket-handlers.go
>  }
Please send this change as a separate PR @poornas

2022-06-19 16:27 UTC, harshavardhana commented on cmd/admin-router.go
> -		adminRouter.Methods(http.MethodPut).Path(adminVersion+"/set-group-status").HandlerFunc(gz(httpTraceHdrs(adminAPI.SetGroupStatus))).Queries("group", "{group:.*}").Queries("status", "{status:.*}")
You need to preserve this API @poornas

2022-06-19 16:27 UTC, harshavardhana commented on go.mod
> +	github.com/minio/pkg v1.1.26-0.20220610225629-15e9d4ef003c
added v1.1.26 tag @poornas

2022-06-19 16:27 UTC, harshavardhana commented on go.sum
>  github.com/minio/pkg v1.1.25/go.mod h1:z9PfmEI804KFkF6eY4LoGe8IDVvTCsYGVuaf58Dr0WI=
`go mod tidy -compat=1.17`  must be run locally..

2022-06-22 06:27 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :x: [more...](#6253d4b2-f007-482e-8b6c-f26eefb84a83) |
<a name="6253d4b2-f007-482e-8b6c-f26eefb84a83"></a>
### 15014-4341b81/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:32737
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 31 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 18 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 22 seconds
(10/15) Running minio-java tests ... done in 28 seconds
(11/15) Running minio-js tests ... FAILED in 54 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook for \"removeObjects(bucketName, objectsList)",
  "args": "bucketName:minio-js-test-ver-presign-07b3910b-f0cb-4d9b-94b1-1f2756877a98\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty. You must delete all versions in the bucket. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(11/15) Running minio-py tests ... done in 1 minutes and 17 seconds
(12/15) Running s3cmd tests ... done in 24 seconds
(13/15) Running s3select tests ... done in 3 seconds
(14/15) Running versioning tests ... done in 3 minutes and 18 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-06-22 16:54 UTC, harshavardhana requested changes
We should avoid double gzip of the handler - it may ignore it but we can avoid the response body compression on this.

2022-06-22 16:54 UTC, harshavardhana commented on cmd/admin-router.go
> +		adminRouter.Methods(http.MethodGet).Path(adminVersion + "/export-iam").HandlerFunc(gz(httpTraceHdrs(adminAPI.ExportIAM)))
```suggestion
		adminRouter.Methods(http.MethodGet).Path(adminVersion + "/export-iam").HandlerFunc(httpTraceHdrs(adminAPI.ExportIAM))
```

2022-06-22 16:54 UTC, harshavardhana commented on cmd/admin-router.go
> +		adminRouter.Methods(http.MethodPut).Path(adminVersion + "/import-iam").HandlerFunc(gz(httpTraceHdrs(adminAPI.ImportIAM)))
```suggestion
		adminRouter.Methods(http.MethodPut).Path(adminVersion + "/import-iam").HandlerFunc(httpTraceHdrs(adminAPI.ImportIAM))
```

2022-06-22 18:04 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-23 16:24 UTC, harshavardhana approved these changes

2022-06-23 16:25 UTC, merged