Minor rewrite of Symlink section
minio/minio pull request #15106
Opened 2022-06-17 23:21 UTC by daniel-bogusz95

Rewrite Symlink section to group information and avoid repetition,
and minor corrections to grammar (eliminated nominalization).

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation updated
- [ ] Unit tests added/updated

2022-06-18 00:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-18 00:35 UTC, harshavardhana requested changes
rest of the words look good - please send these doc changes to grammar in a single PR - thanks @daniel-bogusz95

2022-06-18 00:35 UTC, harshavardhana commented on docs/gateway/nas.md
> +- For reads symlinks resolve to the file the symlink points to.
```suggestion
- For reads symlinks resolve to the file the symlink points to. 
```

This wording is wrong - `symlink` is single here and `resolves` is correct.

2022-06-19 22:36 UTC, closed without merging

2022-06-19 22:42 UTC, harshavardhana commented
Merged into single PR https://github.com/minio/minio/commit/ce6c23a360090fee242b6ce1fd490c5035ad78c0