Parallelize new disks healing of different erasure sets
minio/minio pull request #15112
Opened 2022-06-19 12:56 UTC by vadmeste

## Description
- Always reformat all disks when a new disk is detected, this will
  ensure new uploads to be written in new fresh disks
- Always heal all buckets first when an erasure set started to be healed
- Use a lock to prevent two disks belonging to different nodes but in
  the same erasure set to be healed in parallel
- Heal different sets in parallel - if it is too much, the user can slow healing
  using mc admin config set <alias> heal, which will ensure all healing in all 
  erasure sets to be slowed down

Bonus:
- Avoid logging errUnformattedDisk when a new fresh disk is inserted but
  not detected by healing mechanism yet (10 seconds lag)

## Motivation and Context
Implement parallel set erasure healing

## How to test this PR?
Remove disks in parallel in different sets

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-06-19 13:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-20 16:29 UTC, harshavardhana requested changes

2022-06-20 16:29 UTC, harshavardhana commented on cmd/admin-heal-ops.go
> +	healLocalDisks map[Endpoint]bool         // healing on going
```suggestion
	healLocalDisks map[Endpoint]bool         // healing inprogress
```

2022-06-20 16:29 UTC, harshavardhana commented on cmd/admin-heal-ops.go
> +func (ahs *allHealState) markDiskAsHealing(ep Endpoint) {
```suggestion
func (ahs *allHealState) markDiskForHealing(ep Endpoint) {
```

2022-06-20 16:29 UTC, harshavardhana commented on cmd/background-newdisks-heal-ops.go
> +		return errors.New("unexpected local node pool index")
```suggestion
		return fmt.Errorf("unexpected local node pool index: %s", disk.Endpoint())
```

2022-06-20 16:29 UTC, harshavardhana commented on cmd/background-newdisks-heal-ops.go
> +		return err
```suggestion
		return fmt.Errorf("Error: %w, %s", err, endpoint)
```

2022-06-20 16:29 UTC, harshavardhana commented on cmd/background-newdisks-heal-ops.go
> +	setIdx, _, err := findDiskIndex(z.serverPools[poolIdx].format, format)
verify if `setIdx` < 0

2022-06-20 16:29 UTC, harshavardhana commented on cmd/background-newdisks-heal-ops.go
> +	locker := z.NewNSLock(minioMetaBucket, fmt.Sprintf("new-disk-healing/%d/%d", poolIdx, setIdx))
```suggestion
	locker := z.NewNSLock(minioMetaBucket, fmt.Sprintf("new-disk-healing/%s-%d-%d", endpoint, poolIdx, setIdx))
```

2022-06-20 16:29 UTC, harshavardhana commented on cmd/global-heal.go
> +			// Log healing bucket error - we will retry again later anyway
```suggestion
			// Log bucket healing error if any, we shall retry again.
```

2022-06-20 16:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-20 17:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-20 17:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#9567d70f-6230-4271-88dd-f8d7417b1f27) |
<a name="9567d70f-6230-4271-88dd-f8d7417b1f27"></a>
### 15112-7344811/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:30454
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 7 seconds
(5/15) Running awscli tests ... done in 56 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 29 seconds
(8/15) Running minio-dotnet tests ... done in 6 minutes and 20 seconds
(9/15) Running minio-go tests ... FAILED in 5 minutes and 10 seconds
panic: Get "http://minio-k8s5:30454/minio-go-test-jizbi1cpdiy20tj6/50mzs6zkkszexulxgn5bloqxpilfy4": context deadline exceeded

goroutine 1 [running]:
main.crcMatches({0x955e00, 0xc000373a00}, 0xc5a7128a)
	/mint/run/core/minio-go/main.go:315 +0x12e
main.testGetObjectRanges()
	/mint/run/core/minio-go/main.go:11409 +0xe45
main.main()
	/mint/run/core/minio-go/main.go:12125 +0x2af
(9/15) Running minio-java tests ... done in 35 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 6 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 36 seconds
(12/15) Running s3cmd tests ... done in 26 seconds
(13/15) Running s3select tests ... done in 5 seconds
(14/15) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-06-20 18:00 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-20 18:03 UTC, harshavardhana approved these changes

2022-06-21 10:40 UTC, klauspost approved these changes

2022-06-21 10:40 UTC, klauspost commented on cmd/admin-heal-ops.go
> +	healLocalDisks map[Endpoint]bool         // healing in progress
What does the 3 states mean, `true`/ `false`, not existing? Please document.

2022-06-21 13:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-06-21 14:52 UTC, harshavardhana approved these changes

2022-06-21 14:53 UTC, merged