Fix Helm chart does not support special characters in access/secret key
minio/minio pull request #15243
Opened 2022-07-07 00:38 UTC by dormanze

## Description
fix #15221 

## Motivation and Context
Fix Helm chart does not support special characters in access/secret key.

## How to test this PR?
prefabricate users with access/secretkey containing special characters.
like:
```
users:
  - accessKey: "tv:(()KW5$`>@/c:dB6_=.4|{jv?@!"
    secretKey: ".B_ES205}Mjzrh}G{emJi'LEuUE#:R"
    policy: consoleAdmin
```
![image](https://user-images.githubusercontent.com/37854724/177665502-5d656d21-10ac-45a0-8c8e-0a384d549dfb.png)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-07-07 00:40 UTC, harshavardhana commented
@dormanze do not see any files changed ?

2022-07-07 00:43 UTC, dormanze commented
> @dormanze do not see any files changed ?
Sorry, there is something wrong with my Internet.

2022-07-07 01:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
{"detail": "Not found"}Deleting image locally

2022-07-07 03:45 UTC, harshavardhana requested changes
This change is too complicated what is the issue with helm chart not supporting these characters?

2022-07-07 04:23 UTC, dormanze commented
> This change is too complicated what is the issue with helm chart not supporting these characters?
In the shell, characters like {,',< will be parsed as keywords, so it will cause error messages.
You can create users by executing the following commands in the shell.
```
#accessKey is : tv:(()KW5$`>@/c:dB6_=.4|{jv?@!
#secretKey is : .B_ES205}Mjzrh}G{emJi'LEuUE#:R
mc admin user add myminio tv:(()KW5$`>@/c:dB6_=.4|{jv?@! .B_ES205}Mjzrh}G{emJi'LEuUE#:R --insecure
```
![image](https://user-images.githubusercontent.com/37854724/177690716-01ecc592-c6d0-4350-a106-d32a01550af7.png)

2022-07-07 05:24 UTC, harshavardhana commented
> #accessKey is : tv:(()KW5$`>@/c:dB6_=.4|{jv?@!
> #secretKey is : .B_ES205}Mjzrh}G{emJi'LEuUE#:R
> mc admin user add myminio tv:(()KW5$`>@/c:dB6_=.4|{jv?@! .B_ES205}Mjzrh}G{emJi'LEuUE#:R --insecure

All we need to do is save both the credentials in a file

```
tv:(()KW5$`>@/c:dB6_=.4|{jv?@!
.B_ES205}Mjzrh}G{emJi'LEuUE#:R
```

and then

```
cat credentials.txt | mc admin user add alias/
```

The PR should be simplified and not add new confusing variables.

2022-07-07 05:52 UTC, dormanze commented
> 



> > #accessKey is : tv:(()KW5$`>@/c:dB6_=.4|{jv?@! #secretKey is : .B_ES205}Mjzrh}G{emJi'LEuUE#:R mc admin user add myminio tv:(()KW5$`>@/c:dB6_=.4|{jv?@! .B_ES205}Mjzrh}G{emJi'LEuUE#:R --insecure
> 
> All we need to do is save both the credentials in a file
> 
> ```
> tv:(()KW5$`>@/c:dB6_=.4|{jv?@!
> .B_ES205}Mjzrh}G{emJi'LEuUE#:R
> ```
> 
> and then
> 
> ```
> cat credentials.txt | mc admin user add alias/
> ```
> 
> The PR should be simplified and not add new confusing variables.



> > #accessKey is : tv:(()KW5$`>@/c:dB6_=.4|{jv?@! #secretKey is : .B_ES205}Mjzrh}G{emJi'LEuUE#:R mc admin user add myminio tv:(()KW5$`>@/c:dB6_=.4|{jv?@! .B_ES205}Mjzrh}G{emJi'LEuUE#:R --insecure
> 
> All we need to do is save both the credentials in a file
> 
> ```
> tv:(()KW5$`>@/c:dB6_=.4|{jv?@!
> .B_ES205}Mjzrh}G{emJi'LEuUE#:R
> ```
> 
> and then
> 
> ```
> cat credentials.txt | mc admin user add alias/
> ```
> 
> The PR should be simplified and not add new confusing variables.

This is really a good idea. I'll revise my pr.

2022-07-07 06:51 UTC, dormanze commented
@harshavardhana Please review again.thank you very much.

2022-07-07 07:13 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-07-08 05:15 UTC, harshavardhana commented on helm/minio/templates/_helper_create_user.txt
> +    echo "tmp file is invalidate."
```suggestion
    echo "credentials file is invalid"
```

2022-07-08 05:17 UTC, harshavardhana requested changes

2022-07-08 05:17 UTC, harshavardhana commented on helm/minio/templates/_helper_create_user.txt
> +    echo "not find tmp file."
```suggestion
    echo "credentials file does not exist"
```

2022-07-08 05:17 UTC, harshavardhana commented on helm/minio/templates/_helper_create_user.txt
> +    ${MC} admin user add myminio $(head -1 $MINIO_ACCESSKEY_SECRETKEY_TMP) $(tail -1 $MINIO_ACCESSKEY_SECRETKEY_TMP)
```suggestion
    cat $MINIO_ACCESSKEY_SECRETKEY_TMP | ${MC} admin user add myminio
```

2022-07-08 05:17 UTC, harshavardhana commented on helm/minio/templates/_helper_create_user.txt
> +cat /config/secrets/{{ tpl .accessKey $global }} >> $MINIO_ACCESSKEY_SECRETKEY_TMP
```suggestion
cat /config/secrets/{{ tpl .secretKey $global }} >> $MINIO_ACCESSKEY_SECRETKEY_TMP
```

2022-07-08 05:35 UTC, dormanze commented on helm/minio/templates/_helper_create_user.txt
> +    ${MC} admin user add myminio $(head -1 $MINIO_ACCESSKEY_SECRETKEY_TMP) $(tail -1 $MINIO_ACCESSKEY_SECRETKEY_TMP)
This is a good idea.

2022-07-08 05:35 UTC, dormanze commented on helm/minio/templates/_helper_create_user.txt
> +    echo "tmp file is invalidate."
This is a good suggestion.

2022-07-08 05:36 UTC, dormanze commented on helm/minio/templates/_helper_create_user.txt
> +cat /config/secrets/{{ tpl .accessKey $global }} >> $MINIO_ACCESSKEY_SECRETKEY_TMP
This is a good suggestion.

2022-07-08 06:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#844ce654-74b9-472a-bc45-45fd0b07a40e) |
<a name="844ce654-74b9-472a-bc45-45fd0b07a40e"></a>
### 15243-5c1451f/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:32587
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 52 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 22 seconds
FAILED in 5 minutes and 10 seconds
Unhandled exception. System.AggregateException: One or more errors occurred. (A task was canceled.)
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.Task.GetExceptions(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 156
--- End of stack trace from previous location ---

   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/temp/Minio.Functional.Tests/Program.cs:line 156
(8/15) Running minio-go tests ... done in 56 seconds
(9/15) Running minio-java tests ... done in 19 seconds
(10/15) Running minio-js tests ... done in 59 seconds
(11/15) Running minio-py tests ... done in 45 seconds
(12/15) Running s3cmd tests ... done in 42 seconds
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-07-08 14:18 UTC, harshavardhana approved these changes

2022-07-08 14:20 UTC, merged

2022-07-22 10:52 UTC, sathieu commented
@dormanze The chart is now broken with:

```yaml
  users:
  - accessKey: "foobar"
    existingSecret: minio-secretkeys-gitops
    existingSecretKey: "foobar"
    policy: "readwrite_test"
```

2022-07-22 11:03 UTC, sathieu commented
Proposed fix: https://github.com/minio/minio/pull/15386

2022-07-22 11:12 UTC, dormanze commented
> @dormanze The chart is now broken with:
> 
> ```yaml
>   users:
>   - accessKey: "foobar"
>     existingSecret: minio-secretkeys-gitops
>     existingSecretKey: "foobar"
>     policy: "readwrite_test"
> ```
LGTM