enable using different ports for minioAPIPort/service.port and minioConsolePort/consoleService.port
minio/minio pull request #15259
Opened 2022-07-08 16:05 UTC by chel-ou

## Description
Improves [#15223] to fix [#15175]
[#15223] was breaking configuration where service port was different from 9000.
minioAPIPort and minioConsolePort can now be independent from respective services ports.

## Motivation and Context
Enable exposing services to common ports (for example http/80) while keeping 9000 for internal minioAPIPort.

## How to test this PR?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-07-11 05:54 UTC, harshavardhana requested changes
is this a breaking change?

2022-07-11 06:51 UTC, chel-ou commented
To my understanding, it is not a breaking change.
So far, the recommendation described in the `values.yaml` file was to have the same values on one hand for `minioAPIPort`/`service.port` and on the other hand for `minioConsolePort`/`consoleService.port`.

In this context, the commit only affects a different reference to the same value, and should not break anything.

The commit only gives new possibilities, in a sense that it will be possible to have a `containerPort` different from the service port.

2022-07-11 06:55 UTC, chel-ou commented
From a ease of understanding stand point, it may not be so clear what `minioAPIPort` and `minioConsolePort` are used for.
I will propose a further commit with a clarification in the comment section.

2022-07-11 07:34 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-07-14 04:45 UTC, harshavardhana approved these changes

2022-07-14 21:28 UTC, merged