resync: Avoid concurrent access/write on map
minio/minio pull request #15286
Opened 2022-07-13 22:29 UTC by poornas

## Description

## Motivation and Context
Fixes:
fatal error: concurrent map iteration and map write
minio[19309]: goroutine 18640 [running]:
minio[19309]: runtime.throw({0x27a3399?, 0x1785?})
minio[19309]: runtime/panic.go:992 +0x71 fp=0xc0062f1c80 sp=0xc0062f1c50 pc=0x438671
minio[19309]: runtime.mapiternext(0xc0062f1e90?)
minio[19309]: runtime/map.go:871 +0x4eb fp=0xc0062f1cf0 sp=0xc0062f1c80 pc=0x41002b
minio[19309]: github.com/minio/minio/cmd.(*ReplicationPool).periodicResyncMetaSave(0xc0056c00c0, {0x4d06a48, 0xc0005b2480}, {0x4d22fc0, 0xc0015ea0
minio[19309]: github.com/minio/minio/cmd/bucket-replication.go:1971 +0x247 fp=0xc0062f1fa8 sp=0xc0062f1cf0 pc=0x1d8c8e7
minio[19309]: github.com/minio/minio/cmd.NewReplicationPool.func2()
minio[19309]: github.com/minio/minio/cmd/bucket-replication.go:1367 +0x36 fp=0xc0062f1fe0 sp=0xc0062f1fa8 pc=0x1d86b96

## How to test this PR?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-07-13 22:31 UTC, harshavardhana requested changes

2022-07-13 22:31 UTC, harshavardhana commented on cmd/bucket-replication.go
> +		p.resyncState.Lock()
There is a read lock missing in the next for loop @poornas

2022-07-13 22:46 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-07-13 23:28 UTC, harshavardhana approved these changes

2022-07-13 23:29 UTC, merged

2022-07-14 01:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#38c7cdbd-734e-4b19-9755-24fb926a0a02) |
| mint-fs.sh | :x: [more...](#623dea4d-5e32-46bf-8ef2-57c430e6a224) |
| mint-erasure.sh | :x: [more...](#ab5f72d6-b99e-4b49-9c27-b4608770b632) |
<a name="623dea4d-5e32-46bf-8ef2-57c430e6a224"></a>
### 15286-3631877/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s7:30250
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running awscli tests ... done in 51 seconds
(2/14) Running aws-sdk-go tests ... done in 0 seconds
(3/14) Running aws-sdk-java tests ... done in 1 seconds
(4/14) Running aws-sdk-php tests ... done in 43 seconds
(5/14) Running aws-sdk-ruby tests ... done in 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 29 seconds
{
  "name": "mc",
  "duration": "23819",
  "function": "test_mv_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-13930 --quiet --no-color rm -r --force myminio/mc-test-bucket-12229/dir-21114-27528/  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-12229/dir-21114-27528/` recursively. Get \"http://minio-k8s7:30250/mc-test-bucket-12229/?location=\": dial tcp 15.15.15.7:30250: i/o timeout"
}
(7/14) Running minio-go tests ... done in 1 minutes and 16 seconds
(8/14) Running minio-java tests ... done in 18 seconds
(9/14) Running minio-js tests ... done in 1 minutes and 0 seconds
(10/14) Running minio-py tests ... done in 46 seconds
(11/14) Running s3cmd tests ... done in 22 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="ab5f72d6-b99e-4b49-9c27-b4608770b632"></a>
### 15286-3631877/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:30333
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running awscli tests ... done in 51 seconds
(2/14) Running aws-sdk-go tests ... done in 0 seconds
(3/14) Running aws-sdk-java tests ... done in 1 seconds
(4/14) Running aws-sdk-php tests ... done in 42 seconds
(5/14) Running aws-sdk-ruby tests ... done in 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-go tests ... FAILED in 40 seconds
{
  "args": {
    "bucketName": "minio-go-test-5jeaoosqeaye0bts",
    "expires": 3600000000000,
    "objectName": "minio-go-test-5jeaoosqeaye0btsunique-presigned"
  },
  "duration": 35061,
  "error": "Put \"http://minio-k8s1:30333/minio-go-test-5jeaoosqeaye0bts/minio-go-test-5jeaoosqeaye0btsunique-presigned?AWSAccessKeyId=minio&Expires=1657756528&Signature=2GlzMyoP0Af6HJYplUG5iNPr%2BJk%3D\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
  "function": "PresignedPutObject(bucketName, objectName, expires)",
  "message": "HTTP request to PresignedPutObject URL failed",
  "name": "minio-go: testFunctionalV2",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 25 seconds
(9/14) Running minio-js tests ... done in 58 seconds
(10/14) Running minio-py tests ... done in 52 seconds
(11/14) Running s3cmd tests ... done in 24 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="38c7cdbd-734e-4b19-9755-24fb926a0a02"></a>
### 15286-3631877/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:32722
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running awscli tests ... done in 1 minutes and 1 seconds
(2/14) Running aws-sdk-go tests ... done in 1 seconds
(3/14) Running aws-sdk-java tests ... done in 1 seconds
(4/14) Running aws-sdk-php tests ... done in 43 seconds
(5/14) Running aws-sdk-ruby tests ... done in 7 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 hours 13 minutes and 48 seconds
{
  "name": "mc",
  "duration": "8008801",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-31771 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-20303  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-20303/datafile-0-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-20303/datafile-1-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-20303/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-20303/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-20303/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-20303/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-20303/datafile-10-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-20303/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-20303/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-20303/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-20303/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-20303/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-20303/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-20303/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-20303/datafile-65-MB`\nSIGABRT: abort\nPC=0x46b7c1 m=0 sigcode=0\n\ngoroutine 0 [idle]:\nruntime.futex()\n\truntime/sys_linux_amd64.s:552 +0x21\nruntime.futexsleep(0x10000000000?, 0x0?, 0x4?)\n\truntime/os_linux.go:66 +0x36\nruntime.notesleep(0x1a3f388)\n\truntime/lock_futex.go:159 +0x87\nruntime.mPark(...)\n\truntime/proc.go:1449\nruntime.stopm()\n\truntime/proc.go:2228 +0x8d\nruntime.findrunnable()\n\truntime/proc.go:2804 +0x865\nruntime.schedule()\n\truntime/proc.go:3187 +0x239\nruntime.park_m(0xc0001a01a0?)\n\truntime/proc.go:3336 +0x14d\nruntime.mcall()\n\truntime/asm_amd64.s:425 +0x43\n\ngoroutine 1 [chan receive, 133 minutes]:\ngithub.com/minio/mc/cmd.(*mirrorJob).monitorMirrorStatus(0xc000b06680, 0xc0005207d0)\n\tgithub.com/minio/mc/cmd/mirror-main.go:487 +0x10f\ngithub.com/minio/mc/cmd.(*mirrorJob).mirror(0xc000b06680, {0x12e1bc0, 0xc000858980})\n\tgithub.com/minio/mc/cmd/mirror-main.go:775 +0x1ed\ngithub.com/minio/mc/cmd.runMirror({0x12e1bc0, 0xc000858980}, 0xc000242a00?, {0x7fff31ea8db0, 0xa}, {0x7fff31ea8dbb, 0x1c}, 0xc000702ea0, 0xc00052cf00)\n\tgithub.com/minio/mc/cmd/mirror-main.go:1000 +0xb05\ngithub.com/minio/mc/cmd.mainMirror(0xc000702ea0)\n\tgithub.com/minio/mc/cmd/mirror-main.go:1033 +0x376\ngithub.com/minio/cli.HandleAction({0xf726e0?, 0x1199f30?}, 0x6?)\n\tgithub.com/minio/cli@v1.22.0/app.go:498 +0x5a\ngithub.com/minio/cli.Command.Run({{0x1106b4f, 0x6}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x1137d5d, 0x26}, {0x0, ...}, ...}, ...)\n\tgithub.com/minio/cli@v1.22.0/command.go:225 +0x9f7\ngithub.com/minio/cli.(*App).Run(0xc000600820, {0xc00021c000, 0xa, 0xa})\n\tgithub.com/minio/cli@v1.22.0/app.g [...]