audit-log: Add time to get object from remote-tier
minio/minio pull request #15602
Opened 2022-08-26 22:30 UTC by krisis

## Description
Add time to response from remote tier for transitioned objects in audit-log when audit-log targets are configured.

Sample stats:
```
  "tags": {
    "objectLocation": { ... },
    "tierStats": {
      "tier": "WARMTIER-1",
      "timeToResponse": "6182821ns",
      "tx": 2793
    }
  }
```
## Motivation and Context
For observing the contribution to latency by remote-tier in the case of transitioned objects.

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-08-26 22:48 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#1ab1ce20-fd9a-451e-aaf3-ef48469e5386) |
<a name="1ab1ce20-fd9a-451e-aaf3-ef48469e5386"></a>
### 15602-77fe894/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s8:31882
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 24 seconds
(8/14) Running minio-go tests ... done in 44 seconds
(9/14) Running minio-java tests ... done in 31 seconds
(10/14) Running minio-js tests ... FAILED in 37 seconds
{
  "name": "minio-js",
  "function": "Check if bucket with object lock can be created:",
  "args": "bucketName:minio-js-test-lock-mb-8e83e4ee-3458-4fce-83ca-f767753660a3",
  "duration": 4,
  "status": "FAIL",
  "error": "Error: done() called multiple times in test <functional tests Object Lock API Bucket Options Test Object Lock support makeBucket API Tests Check if bucket with object lock can be created:_bucketName:minio-js-test-lock-mb-8e83e4ee-3458-4fce-83ca-f767753660a3> of file /mint/run/core/minio-js/test/functional-tests.js at /mint/run/core/minio-js/node_modules/mocha-steps/lib/step.js:67:11 at /mint/run/core/minio-js/test/functional-tests.js:2256:60 at processWithRetry (node_modules/minio/dist/main/minio.js:741:13) at DestroyableTransform.<anonymous> (node_modules/minio/dist/main/minio.js:559:13) at done (node_modules/readable-stream/lib/_stream_transform.js:192:25) at /mint/run/core/minio-js/node_modules/readable-stream/lib/_stream_transform.js:130:7 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:7) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(10/14) Running minio-py tests ... done in 55 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 5 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-08-26 23:06 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#5d428ef4-defc-4107-88b9-89019d5b3402) |
<a name="5d428ef4-defc-4107-88b9-89019d5b3402"></a>
### 15602-3b1c13f/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:31849
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 22 seconds
(8/14) Running minio-go tests ... done in 47 seconds
(9/14) Running minio-java tests ... done in 33 seconds
(10/14) Running minio-js tests ... FAILED in 36 seconds
{
  "name": "minio-js",
  "function": "Check if bucket with object lock can be created:",
  "args": "bucketName:minio-js-test-lock-mb-8eb508ab-dd6b-45a2-82fd-39cdaacc33fd",
  "duration": 5,
  "status": "FAIL",
  "error": "Error: done() called multiple times in test <functional tests Object Lock API Bucket Options Test Object Lock support makeBucket API Tests Check if bucket with object lock can be created:_bucketName:minio-js-test-lock-mb-8eb508ab-dd6b-45a2-82fd-39cdaacc33fd> of file /mint/run/core/minio-js/test/functional-tests.js at /mint/run/core/minio-js/node_modules/mocha-steps/lib/step.js:67:11 at /mint/run/core/minio-js/test/functional-tests.js:2256:60 at processWithRetry (node_modules/minio/dist/main/minio.js:741:13) at DestroyableTransform.<anonymous> (node_modules/minio/dist/main/minio.js:559:13) at done (node_modules/readable-stream/lib/_stream_transform.js:192:25) at /mint/run/core/minio-js/node_modules/readable-stream/lib/_stream_transform.js:130:7 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:7) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(10/14) Running minio-py tests ... done in 55 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 6 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-08-29 16:47 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-08-29 17:01 UTC, harshavardhana requested changes
Should we also indicate difference between just 

- GetObject
- RestoreObject 

??

2022-08-29 17:51 UTC, krisis commented
> Should we also indicate difference between just
> 
> * GetObject
> * RestoreObject
> 
> ??

This information is already present in `api.name` in the corresponding audit-log entry.

2022-08-29 19:20 UTC, harshavardhana approved these changes

2022-08-29 19:56 UTC, poornas approved these changes

2022-08-29 23:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#8546e520-3881-4475-95ae-83a836a66abc) |
<a name="8546e520-3881-4475-95ae-83a836a66abc"></a>
### 15602-9a2238a/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:32749
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 20 seconds
{
  "name": "mc",
  "duration": "10112",
  "function": "test_presigned_put_object",
  "status": "FAIL",
  "error": "unable to get presigned put object url"
}
(7/14) Running minio-go tests ... done in 1 minutes and 49 seconds
(8/14) Running minio-java tests ... done in 19 seconds
(9/14) Running minio-js tests ... done in 59 seconds
(10/14) Running minio-py tests ... done in 47 seconds
(11/14) Running s3cmd tests ... done in 23 seconds
(12/14) Running s3select tests ... done in 1 seconds
(13/14) Running versioning tests ... done in 1 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-08-30 00:46 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#e0258973-29fb-4b6e-8af3-48dd3204f4f1) |
<a name="e0258973-29fb-4b6e-8af3-48dd3204f4f1"></a>
### 15602-b7345ca/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s4:31337
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 54 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 20 seconds
(8/14) Running minio-go tests ... done in 53 seconds
(9/14) Running minio-java tests ... FAILED in 1 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 60327,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: connect timed out >>> [java.base/java.net.PlainSocketImpl.socketConnect(Native Method), java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:412), java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:255), java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:237), java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392), java.base/java.net.Socket.connect(Socket.java:609), okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120), okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295), okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207), okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226), okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106), okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74), okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall.execute(RealCall.kt:154), io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:177), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:225), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 59 seconds
(10/14) Running minio-py tests ... done in 47 seconds
(11/14) Running s3cmd tests ... done in 23 seconds
(12/14) Running s3select tests ... done in 1 seconds
(13/14) Running versioning tests ... done in 1 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-08-30 04:33 UTC, merged