feat:Deadlock caused by unlocking a non-existing lock
minio/minio pull request #15635
Opened 2022-09-01 05:24 UTC by yudoutingle

## Description
feat:Deadlock caused by unlocking a non-existing lock。
for example， minio-6 locks minio-5 at startup, but minio-5 restarts before minio-6 unlocked,
causing minio-6's lock to be lost, which leads to minio-6 deadlock.
In fixed code, it will return true if lock not exits.

issues :  https://github.com/minio/minio/issues/15519

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation updated
- [ ] Unit tests added/updated

2022-09-01 06:03 UTC, harshavardhana requested changes

2022-09-01 06:03 UTC, harshavardhana commented on cmd/local-locker.go
> +			reply = true
This is wrong @yudoutingle you should never return true for Unlocks() on non-existent resources. This shows bugs here is the simplest fix

```diff
diff --git a/cmd/local-locker.go b/cmd/local-locker.go
index f89efcc7c..8eff129df 100644
--- a/cmd/local-locker.go
+++ b/cmd/local-locker.go
@@ -129,12 +129,12 @@ func (l *localLocker) Unlock(_ context.Context, args dsync.LockArgs) (reply bool
        err = nil
 
        for _, resource := range args.Resources {
-               if !l.canTakeUnlock(resource) {
+               lri, ok := l.lockMap[resource]
+               if ok && !isWriteLock(lri) {
                        // Unless it is a write lock reject it.
                        err = fmt.Errorf("unlock attempted on a read locked entity: %s", resource)
                        continue
                }
-               lri, ok := l.lockMap[resource]
                if ok {
                        reply = l.removeEntry(resource, args, &lri) || reply
                }
```

2022-09-01 06:05 UTC, harshavardhana commented
Also this deadlock will not happen of the "Refresh()" routine 

> for example， minio-6 locks minio-5 at startup, but minio-5 restarts before minio-6 unlocked,

Your assessment here is based on an older release that had the problem of deadlocks minio-6 `unlock` now automatically refreshes the stale state. 

However, your fix is okay to take as an ice change.

2022-09-02 04:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-09-02 04:55 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-09-02 08:56 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-09-02 10:35 UTC, klauspost approved these changes
LGTM

2022-09-02 21:23 UTC, harshavardhana approved these changes

2022-09-02 21:24 UTC, merged