panic if replication config could not be read from disk
minio/minio pull request #15685
Opened 2022-09-13 17:17 UTC by poornas

## Description

## Motivation and Context
If replication config could not be read from bucket metadata for some reason, issue a panic so that unexpected replication outcomes can be avoided for replicated buckets.

For similar reasons, adding a panic while fetching object-lock config if it failed for reason other than non-existence of config.

## How to test this PR?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-09-13 17:20 UTC, harshavardhana requested changes

2022-09-13 17:20 UTC, harshavardhana commented on cmd/bucket-replication.go
> +	if _, ok := err.(BucketReplicationConfigNotFound); !ok {
safer to do 

```suggestion
	if _, ok := err.(BucketReplicationConfigNotFound); !ok && err != nil {
```

2022-09-13 17:20 UTC, harshavardhana commented on cmd/bucket-replication.go
> +	if _, ok := err.(BucketReplicationConfigNotFound); !ok {
or have explicit `if err != nil`

2022-09-13 18:13 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#b2bd34f8-70f7-4377-8d14-1171a8f60c37) |
<a name="b2bd34f8-70f7-4377-8d14-1171a8f60c37"></a>
### 15685-1c06652/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:30748
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 51 seconds
{
  "name": "mc",
  "duration": "42921",
  "function": "test_mv_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-10478 --quiet --no-color mv /tmp/tmp.mQEmyPbnOK/file myminio/mc-test-bucket-25285/dir-31724-23659/object-1  >>> \n`/tmp/tmp.mQEmyPbnOK/file` -> `myminio/mc-test-bucket-25285/dir-31724-23659/object-1`\nmc: <ERROR> Failed to copy `/tmp/tmp.mQEmyPbnOK/file`. Get \"http://minio-k8s2:30748/mc-test-bucket-25285/?location=\": dial tcp 15.15.15.2:30748: i/o timeout\nTotal: 0 B, Transferred: 0 B, Speed: 0 B/s"
}
(7/14) Running minio-go tests ... done in 1 minutes and 22 seconds
(8/14) Running minio-java tests ... done in 32 seconds
(9/14) Running minio-js tests ... done in 1 minutes and 4 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 20 seconds
(11/14) Running s3cmd tests ... done in 26 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-09-13 18:23 UTC, harshavardhana approved these changes

2022-09-13 18:32 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-09-13 21:49 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#82976513-a24c-4b2a-a6c9-a546ace72384) |
| mint-fs.sh | :x: [more...](#93fa822d-f30d-4861-b3b7-6c9ec2f073a8) |
| mint-erasure.sh | :x: [more...](#8bae96c5-1639-4e07-98b3-680bc8efa091) |
| mint-dist-erasure.sh | :x: [more...](#313f0f58-4f5b-4c94-8477-9e3fa53529cc) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#29349102-14ba-496c-8200-cc8a31410678) |
| mint-pools.sh | :x: [more...](#645cb4fe-72a2-4c11-8d0e-8a65df224bfa) |
<a name="313f0f58-4f5b-4c94-8477-9e3fa53529cc"></a>
### 15685-2c4b8ef/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s2:30564
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-go tests ... FAILED in 23 seconds
{
  "args": {
    "bucketName": "minio-go-test-z3soqj9h0hh36ddc",
    "objectName": "sy002cajrvirmy6pwpsd1qkd93ck1e"
  },
  "duration": 5464,
  "error": "We encountered an internal error, please try again.",
  "function": "GetObject()",
  "message": "PutObject failed",
  "name": "minio-go: testPutObjectWithVersioning",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "setBucketVersioning()",
  "duration": 186,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidBucketState, message = A replication configuration is present on this bucket, bucket wide versioning cannot be suspended., bucketName = minio-java-test-2nh6dbe, objectName = null, resource = /minio-java-test-2nh6dbe, requestId = 171489A66715D82B, hostId = 7d425b42-7a7c-4ab8-8838-65a740fceeeb)\nrequest={method=PUT, url=http://minio-k8s2:30564/minio-java-test-2nh6dbe?versioning=, headers=Host: minio-k8s2:30564\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.3\nContent-MD5: orZUUp7E9srl53Od8p1glA==\nx-amz-content-sha256: d7f1d7ed35d188f6a89d394cc2055f5910c14a3abccf41e808e7f7327d21e129\nx-amz-date: 20220913T214510Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20220913/us-east-1/s3/aws4_request, SignedHeaders=content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 387\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Request-Id: 171489A66715D82B\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Tue, 13 Sep 2022 21:45:10 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(8/14) Running minio-js tests ... FAILED in 51 seconds
{
  "name": "minio-js",
  "function": "Suspend versioning  on a bucket",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: A replication configuration is present on this bucket, bucket wide versioning cannot be suspended. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(8/14) Running minio-py tests ... FAILED in 19 seconds
{
  "name": "minio-py:test_stat_object_version",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-93ace169-4882-4056-bf87-79b6f6f49603",
    "object_name": "6d63da9a-23bf-4855-81a6-2761de0d455e",
    "length": 1048576,
    "data": "LimitedRandomReader(1 * MB)"
  },
  "message": "HTTPConnectionPool(host='minio-k8s2', port=30564): Max retries exceeded with url: /minio-py-test-93ace169-4882-4056-bf87-79b6f6f49603/6d63da9a-23bf-4855-81a6-2761de0d455e (Caused by ResponseError('too many 500 error responses'))",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 825, in test_stat_object_version\n    _test_stat_object(log_entry, sse, version_check=True)\n  File \"/mint/run/core/minio-py/tests.py\", line 777, in _test_stat_object\n    result = _CLIENT.put_object(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1755, in put_object\n    raise exc\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1709, in put_object\n    return self._put_object(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1567, in _put_object\n    response = self._execute(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 403, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 266, in _url_open\n    response = self._http.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 878, in urlopen\n    return self.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 878, in urlopen\n    return self.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 878, in urlopen\n    return self.urlopen(\n  [Previous line repeated 2 more times]\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 868, in urlopen\n    retries = retries.increment(method, url, response=response, _pool=self)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py\", line 592, in increment\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\nurllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='minio-k8s2', port=30564): Max retries exceeded with url: /minio-py-test-93ace169-4882-4056-bf87-79b6f6f49603/6d63da9a-23bf-4855-81a6-2761de0d455e (Caused by ResponseError('too many 500 error responses'))\n",
  "duration": 6546
}
(8/14) Running s3cmd tests ... done in 35 seconds
(9/14) Running s3select tests ... done in 4 seconds
(10/14) Running versioning tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-j4dny9l164j2fq",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 515,
  "error": "InternalError: We encountered an internal error, please try again.\n\tstatus code: 500, request id: 171489BFE6FE3A6B, host id: ",
  "function": "/mint/build/version [...]

2022-09-13 23:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#7da5da6e-2736-48c2-892b-a7efead21f2d) |
| mint-fs.sh | :x: [more...](#a8d12d04-af22-465b-addd-e29d3f05fa53) |
| mint-gateway-s3.sh | :x: [more...](#c7ceec02-9db4-4c03-b27b-ad0fdf4a4639) |
| mint-erasure.sh | :x: [more...](#6dcc9021-647b-4bd7-92b5-4e780c6ad862) |
| mint-dist-erasure.sh | :x: [more...](#d8b1abd8-ea6c-456a-98c2-b21a7aa7392f) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#2522320a-1959-421b-8e44-380ca4db5619) |
| mint-pools.sh | :x: [more...](#7da27a23-6ac6-4bda-8aff-73d12e024d7e) |
<a name="c7ceec02-9db4-4c03-b27b-ad0fdf4a4639"></a>
### 15685-c655357/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s6:31744
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 7 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-uztqlqgecs3mec",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 22,
  "error": "InvalidRequest: Bucket is missing ObjectLockConfiguration\n\tstatus code: 400, request id: 1714908293D6BCAC, host id: ",
  "function": "testListObjects",
  "message": "AWS SDK Go PUT expected to success but got InvalidRequest: Bucket is missing ObjectLockConfiguration\n\tstatus code: 400, request id: 1714908293D6BCAC, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-java tests ... done in 1 seconds
(2/14) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-uztqlqgecs3mec",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 22,
  "error": "InvalidRequest: Bucket is missing ObjectLockConfiguration\n\tstatus code: 400, request id: 1714908293D6BCAC, host id: ",
  "function": "testListObjects",
  "message": "AWS SDK Go PUT expected to success but got InvalidRequest: Bucket is missing ObjectLockConfiguration\n\tstatus code: 400, request id: 1714908293D6BCAC, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(2/14) Running aws-sdk-ruby tests ... FAILED in 3 seconds
{
  "name": "aws-sdk-ruby",
  "function": "putObject(bucket_name, file)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-dd45f8c0e230",
    "file": "/mint/data/datafile-1-kB"
  },
  "duration": 18.89,
  "error": "Bucket is missing ObjectLockConfiguration",
  "status": "FAIL"
}
(2/14) Running awscli tests ... FAILED in 3 seconds
{
  "name": "awscli",
  "duration": 1220,
  "function": "aws --endpoint-url http://minio-k8s6:31744 s3api put-object --body /mint/data/datafile-1-kB --bucket awscli-mint-test-bucket-17506 --key datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (InvalidRequest) when calling the PutObject operation: Bucket is missing ObjectLockConfiguration"
}
(2/14) Running healthcheck tests ... done in 0 seconds
(3/14) Running mc tests ... FAILED in 1 seconds
{
  "name": "mc",
  "duration": "371",
  "function": "test_rb",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-961 --quiet --no-color cp /mint/data/datafile-1-MB myminio/mc-test-bucket-17342-1/mc-test-object-28872  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-17342-1/mc-test-object-28872`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Bucket is missing ObjectLockConfiguration\nTotal: 0 B, Transferred: 384.00 KiB, Speed: 19.92 MiB/s"
}
(3/14) Running minio-go tests ... FAILED in 0 seconds
{
  "args": {
    "bucketName": "minio-go-test-ozypvo0btejqwntj",
    "objectName": "nqeogams9k4jg5ztczy3e3jf5z1mdy",
    "region": "eu-west-1"
  },
  "duration": 12,
  "error": "Bucket is missing ObjectLockConfiguration",
  "function": "MakeBucket(bucketName, region)",
  "message": "PutObject failed",
  "name": "minio-go: testGetObjectClosedTwiceV2",
  "status": "FAIL"
}
(3/14) Running minio-java tests ... FAILED in 2 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 40,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-3g0jiaq, objectName = minio-java-test-31b1sur, resource = /minio-java-test-3g0jiaq/minio-java-test-31b1sur, requestId = 1714908538AFACA4, hostId = 8d0bfb58-b5dd-46b8-acbf-01b6949dadc7)\nrequest={method=PUT, url=http://minio-k8s6:31744/minio-java-test-3g0jiaq/minio-java-test-31b1sur, headers=Content-Type: application/octet-stream\nHost: minio-k8s6:31744\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.3\nx-amz-content-sha256: d4735e3a265e16eee03f59718b9b5d03019c07d8b6c51f90da3a666eec13ab35\nx-amz-date: 20220913T235104Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20220913/us-east-1/s3/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Request-Id: 1714908538AFACA4\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Tue, 13 Sep 2022 23:51:04 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(3/14) Running minio-js tests ... FAILED in 1 seconds
{
  "name": "minio-js",
  "function": "putObject(bucketName, objectName, stream)",
  "args": "bucketName:minio-js-test-8bac6b6f-c03e-4f66-8f97-4dad9a02d3d9, objectName:path/to/datafile-100-kB.buffer, stream:100Kib",
  "duration": 23,
  "status": "FAIL",
  "error": "S3Error: Bucket is missing ObjectLockConfiguration at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(3/14) Running minio-py tests ... FAILED in 0 seconds
{
  "name": "minio-py:test_fput_object_small_file",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-677aeaad-fe75-4eef-80b3-9dfc62bfaaba",
    "object_name": "1f805c27-114f-4276-87de-e771ec57444a-f",
    "file_path": "/mint/data/datafile-1-MB",
    "metadata": {
      "x-amz-storage-class": "STANDARD_IA"
    }
  },
  "message": "S3 operation failed; code: InvalidRequest, message: Bucket is missing ObjectLockConfiguration, resource: /minio-py-test-677aeaad-fe75-4eef-80b3-9dfc62bfaaba/1f805c27-114f-4276-87de-e771ec57444a-f, request_id: 171490858EB5AED5, host_id: 8d0bfb58-b5dd-46b8-acbf-01b6949dadc7, bucket_name: minio-py-test-677aeaad-fe75-4eef-80b3-9dfc62bfaaba, object_name: 1f805c27-114f-4276-87de-e771ec57444a-f",
  "e [...]

2022-09-14 00:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-09-14 00:15 UTC, harshavardhana approved these changes

2022-09-14 04:23 UTC, merged