Avoid logging query parsing
minio/minio pull request #15805
Opened 2022-10-06 14:26 UTC by vadmeste

## Description
Avoid printing the following log

API: SYSTEM()
Time: 10:19:30 UTC 10/06/2022
DeploymentID: 7d0826bc-1c0d-43fa-aec9-b02ab16b809b
Error: invalid semicolon separator in query (*errors.errorString)
       4: internal/logger/logger.go:259:logger.LogIf()
       3: cmd/auth-handler.go:110:cmd.getRequestAuthType()
       2: cmd/auth-handler.go:505:cmd.setAuthHandler.func1()
       1: net/http/server.go:2084:http.HandlerFunc.ServeHTTP()

## Motivation and Context
Avoid log generated by bad formed requests

## How to test this PR?
Trivial change

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-10-06 14:34 UTC, harshavardhana requested changes

2022-10-06 14:34 UTC, harshavardhana commented on cmd/auth-handler.go
> -			logger.LogIf(r.Context(), err)
This is logged actually on purpose @vadmeste to look for odd requests that can be malicious

2022-10-06 14:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-06 15:04 UTC, vadmeste commented on cmd/auth-handler.go
> -			logger.LogIf(r.Context(), err)
> This is logged actually on purpose @vadmeste to look for odd requests that can be malicious

I do not think it will be really useful to see this in the logs, especially because it is caused by application side. Also we can see it in 'mc admin trace' after recent changes

2022-10-06 18:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-06 20:55 UTC, harshavardhana commented on cmd/auth-handler.go
> -			logger.LogIf(r.Context(), err)
yes but url.ParseQuery() failure is rare it is very rare and we should log it because it is part of unusual requests.

2022-10-06 21:03 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#a95e48aa-fa38-4a6c-94f0-92bb16cc79d6) |
| mint-erasure.sh | :x: [more...](#e51fb161-026d-4ada-958f-0af499b35852) |
<a name="e51fb161-026d-4ada-958f-0af499b35852"></a>
### 15805-4f7b7a7/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s5:31894
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 48 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 27 seconds
(8/14) Running minio-go tests ... done in 52 seconds
(9/14) Running minio-java tests ... FAILED in 17 seconds
{
  "name": "minio-java",
  "function": "getObjectRetention()",
  "duration": 35,
  "status": "FAIL",
  "error": "java.time.format.DateTimeParseException: Text '2022-10-07T20:55:45.2Z' could not be parsed at index 19 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioAsyncClient.lambda$getObjectRetention$34(MinioAsyncClient.java:1699), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506), java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073), io.minio.S3Base$1.onResponse(S3Base.java:559), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 1 minutes and 11 seconds
(10/14) Running minio-py tests ... done in 52 seconds
(11/14) Running s3cmd tests ... done in 33 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
<a name="a95e48aa-fa38-4a6c-94f0-92bb16cc79d6"></a>
### 15805-4f7b7a7/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-k8s1:32266
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp :/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 42 seconds
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "DeleteObject" on "http://minio-k8s1:32266/aws-sdk-php-633f400392008/obj1"; AWS HTTP error: Client error: `DELETE http://minio-k8s1:32266/aws-sdk-php-633f400392008/obj1` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Mes (truncated...)
 NoSuchBucket (client): The specified bucket does not exist - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key>obj1</Key><BucketName>aws-sdk-php-633f400392008</BucketName><Resource>/aws-sdk-php-633f400392008/obj1</Resource><RequestId>171B9627111DD57B</RequestId><HostId>3cf4c8c0-bcc5-45ce-9748-14a00cd936c8</HostId></Error>'

GuzzleHttp\Exception\ClientException: Client error: `DELETE http://minio-k8s1:32266/aws-sdk-php-633f400392008/obj1` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8 in /mint/run/core/aws-sdk-php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195
(3/14) Running aws-sdk-ruby tests ... done in 4 seconds
(4/14) Running awscli tests ... done in 49 seconds
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... done in 48 seconds
(7/14) Running minio-go tests ... done in 42 seconds
(8/14) Running minio-java tests ... done in 41 seconds
(9/14) Running minio-js tests ... done in 39 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 10 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 4 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-07 07:46 UTC, harshavardhana commented on cmd/auth-handler.go
> -			logger.LogIf(r.Context(), err)
> Error: invalid semicolon separator in query (*errors.errorString)

This error is actually part of a CVE that Golang fixed

2022-10-07 15:48 UTC, harshavardhana commented on cmd/auth-handler.go
> -			logger.LogIf(r.Context(), err)
do you still want this PR in ? @vadmeste

2022-10-08 15:49 UTC, closed without merging