Add LDAP IDP Configuration APIs
minio/minio pull request #15840
Opened 2022-10-11 21:49 UTC by donatello

## Description

Adds support for higher level LDAP configuration commands.

## How to test this PR?

Use https://github.com/minio/minio-iam-testing to setup an LDAP env.

Use `mc` from https://github.com/minio/mc/pull/4296

Some sample commands and outputs:

```
$ ./mc admin idp set myminio ldap           server_addr=localhost:1389                      lookup_bind_dn=cn=admin,dc=min,dc=io           lookup_bind_password=admin           user_dn_search_base_dn=dc=min,dc=io           user_dn_search_filter="(uid=%s)"           group_search_base_dn=ou=swengg,dc=min,dc=io           group_search_filter="(&(objectclass=groupofnames)(member=%d))" 
mc: <ERROR> Unable to set IDP config for 'ldap' to server. Result: LDAP Server Connection Error
Detail: Could not connect to LDAP server: LDAP Result Code 200 "Network Error": EOF
Suggestion: Check:
    (1) server address
    (2) TLS parameters, and
    (3) LDAP server's TLS certificate is trusted by MinIO (when using TLS - highly recommended)
Due to: LDAP Result Code 200 "Network Error": EOF.

$ ./mc admin idp set myminio ldap           server_addr=localhost:1389   server_insecure=on                   lookup_bind_dn=cn=admin,dc=min,dc=io           lookup_bind_password=admin1           user_dn_search_base_dn=dc=min,dc=io           user_dn_search_filter="(uid=%s)"           group_search_base_dn=ou=swengg,dc=min,dc=io           group_search_filter="(&(objectclass=groupofnames)(member=%d))" 
mc: <ERROR> Unable to set IDP config for 'ldap' to server. Result: LDAP Lookup Bind Error
Detail: Error connecting as LDAP Lookup Bind user: LDAP Lookup Bind user invalid credentials error: LDAP Result Code 49 "Invalid Credentials": 
Suggestion: Check LDAP Lookup Bind user credentials and if user is allowed to login
Due to: LDAP Lookup Bind user invalid credentials error: LDAP Result Code 49 "Invalid Credentials":.

$ ./mc admin idp set myminio ldap           server_addr=localhost:1389   server_insecure=on                   lookup_bind_dn=cn=admin,dc=min,dc=io           lookup_bind_password=admin           user_dn_search_base_dn=dc=min,dc=io           user_dn_search_filter="(uid=%s)"           group_search_base_dn=ou=swengg,dc=min,dc=io           group_search_filter="(&(objectclass=groupofnames)(member=%d))" 
Successfully applied new settings.
Please restart your server 'mc admin service restart myminio'.

```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-10-11 22:20 UTC, donatello commented
Needs https://github.com/minio/madmin-go/pull/138

2022-10-13 04:48 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#cc64e661-bfbc-46e4-addd-4ef84937f21f) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#24f0673b-4610-4b99-b1e2-bdd6ca7024f4) |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#1f87c5f7-f28c-4280-a1b8-82a40a22a89b) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#a0822147-7788-4ffe-9baa-96a132ee9ce1) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#6e3b504c-0c67-4c34-9656-c25f878d40a0) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#a020a85a-e662-486e-9c35-a588d23f431d) |
| mint-pools.sh | :heavy_exclamation_mark: [more...](#d7a01674-4d3f-4f05-a31d-19320072a6ae) |
<a name="a0822147-7788-4ffe-9baa-96a132ee9ce1"></a>
### 15840-142fa9e/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d7a01674-4d3f-4f05-a31d-19320072a6ae"></a>
### 15840-142fa9e/mint-pools.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="1f87c5f7-f28c-4280-a1b8-82a40a22a89b"></a>
### 15840-142fa9e/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="6e3b504c-0c67-4c34-9656-c25f878d40a0"></a>
### 15840-142fa9e/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="24f0673b-4610-4b99-b1e2-bdd6ca7024f4"></a>
### 15840-142fa9e/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="a020a85a-e662-486e-9c35-a588d23f431d"></a>
### 15840-142fa9e/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="cc64e661-bfbc-46e4-addd-4ef84937f21f"></a>
### 15840-142fa9e/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

2022-10-14 04:58 UTC, harshavardhana requested changes

2022-10-14 04:58 UTC, harshavardhana commented on cmd/admin-handlers-idp-config.go
> +		if ldapValidationErr, ok := err.(ldap.Validation); ok {
can we use `errors.Is()` here? @donatello

2022-10-14 04:58 UTC, harshavardhana commented on cmd/admin-handlers-idp-config.go
> +			if err == openid.ErrProviderConfigNotFound {
```suggestion
			if errors.Is(err, openid.ErrProviderConfigNotFound) {
```

2022-10-14 05:04 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#18220fdf-8999-4020-880f-450eb7f7854e) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#0a847c22-a3f2-4d12-bf38-34488d93306a) |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#7d3f08a8-cdf2-42ee-9661-4fa0a149f0a5) |
| mint-erasure.sh | :heavy_exclamation_mark: [more...](#1c2061b1-cc64-42d8-b2de-fdc7879e91f1) |
| mint-dist-erasure.sh | :heavy_exclamation_mark: [more...](#accfe54e-65a8-491e-a5ea-e73702125e60) |
| mint-compress-encrypt-dist-erasure.sh | :heavy_exclamation_mark: [more...](#11d70b9f-017c-467e-aea8-836cdc9e2277) |
| mint-pools.sh | :heavy_exclamation_mark: [more...](#2368f1d5-22d0-40aa-a230-f1ebf17c3767) |
<a name="2368f1d5-22d0-40aa-a230-f1ebf17c3767"></a>
### 15840-3b22489/mint-pools.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="0a847c22-a3f2-4d12-bf38-34488d93306a"></a>
### 15840-3b22489/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="7d3f08a8-cdf2-42ee-9661-4fa0a149f0a5"></a>
### 15840-3b22489/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="11d70b9f-017c-467e-aea8-836cdc9e2277"></a>
### 15840-3b22489/mint-compress-encrypt-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="accfe54e-65a8-491e-a5ea-e73702125e60"></a>
### 15840-3b22489/mint-dist-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="18220fdf-8999-4020-880f-450eb7f7854e"></a>
### 15840-3b22489/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="1c2061b1-cc64-42d8-b2de-fdc7879e91f1"></a>
### 15840-3b22489/mint-erasure.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

2022-10-14 07:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#f2fcde1d-a004-4999-a065-a16db92f6546) |
| mint-fs.sh | :x: [more...](#9d1a7248-f50e-4f95-ba38-a3e7aaff7a1f) |
| mint-gateway-s3.sh | :x: [more...](#9c3cc43f-c114-4e96-a49c-6066f45e6740) |
| mint-erasure.sh | :x: [more...](#8323eb7d-dd82-4c1d-8658-17f843b6d4a7) |
| mint-dist-erasure.sh | :x: [more...](#c40ffc98-400e-43b9-b486-6fd69b3c744a) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#55687366-34d8-493d-a477-614242e905e0) |
| mint-pools.sh | :x: [more...](#05028e5e-ab91-4551-929b-126885bda67c) |
<a name="05028e5e-ab91-4551-929b-126885bda67c"></a>
### 15840-3b22489/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:30471
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 47a64e9b3130:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-op2klaeegcmdegwm",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "1m3r4srltvthdfxabz4uyrw5zq6qaf",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2583,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 36 seconds
(9/14) Running minio-js tests ... done in 52 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 56 seconds
(11/14) Running s3cmd tests ... done in 18 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 13 out of 14 tests successfully.
```
<a name="9d1a7248-f50e-4f95-ba38-a3e7aaff7a1f"></a>
### 15840-3b22489/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.22:31155
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 61b90bba38b9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... FAILED in 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-ulizhuuwmbpcdxc1",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "nzbvg12nuo3a2eymqqw3takb3wvyau",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2874,
  "error": "want yXTVFQ==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 17 seconds
(9/14) Running minio-js tests ... done in 43 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 6 seconds
(11/14) Running s3cmd tests ... done in 13 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="f2fcde1d-a004-4999-a065-a16db92f6546"></a>
### 15840-3b22489/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.20:32377
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 837a58c35681:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... FAILED in 7 seconds
{
  "args": {
    "bucketName": "minio-go-test-cwuabs5j6ocv62a1",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "swe91uu46m12ysia4wgvjysa4pngvn",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2519,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 31 seconds
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 44 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
<a name="9c3cc43f-c114-4e96-a49c-6066f45e6740"></a>
### 15840-3b22489/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.20:30176
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 1128cc907c58:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... FAILED in 7 seconds
{
  "args": {
    "bucketName": "minio-go-test-6bdhum1wodvd62oi",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "1vl0qjfrspu5cjtoh9rpyxyqdb4zwx",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3324,
  "error": "want yXTVFQ==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 30 seconds
(9/14) Running minio-js tests ... done in 34 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 8 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 3 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
<a name="8323eb7d-dd82-4c1d-8658-17f843b6d4a7"></a>
### 15840-3b22489/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:32069
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA [...]

2022-10-14 23:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#09449118-24ce-41af-baa5-8b7be34cb536) |
| mint-gateway-s3.sh | :x: [more...](#2222b0fd-8a64-43c9-9f77-37ea2b44b1b1) |
<a name="2222b0fd-8a64-43c9-9f77-37ea2b44b1b1"></a>
### 15840-5566228/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:30866
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 4eb98db17fe9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-cubn5nal55551xwy",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "sgchhwpsf0lsindy5h9iskpymimwdx",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3735,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 38 seconds
(9/14) Running minio-js tests ... done in 37 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 17 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 5 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
<a name="09449118-24ce-41af-baa5-8b7be34cb536"></a>
### 15840-5566228/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.21:30971
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp c45cb2dbc0b4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 12 seconds
(8/14) Running minio-go tests ... FAILED in 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-4vw1y5r44cl32dw1",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "yu1d269wz4gbvo42ffjn9s2xuswwkm",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2935,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 15 seconds
(9/14) Running minio-js tests ... done in 42 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 4 seconds
(11/14) Running s3cmd tests ... done in 12 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-15 23:33 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-16 16:31 UTC, harshavardhana requested changes

2022-10-16 16:31 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/madmin-go => github.com/donatello/madmin-go v1.0.21-0.20221011212032-b48b2372e974
The PR is merged @donatello feel free to add a tag.

2022-10-17 18:24 UTC, harshavardhana approved these changes

2022-10-18 15:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#edca7e96-9aac-48b3-a92b-3175ad59dcee) |
<a name="edca7e96-9aac-48b3-a92b-3175ad59dcee"></a>
### 15840-068e2bb/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.4:32456
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp c4c546f95c80:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 20 seconds
{
  "name": "mc",
  "duration": "6373",
  "function": "test_mv_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-23274 --quiet --no-color stat myminio/mc-test-bucket-281/dir-31865-31948/object-2  >>> \nmc: <ERROR> Unable to list folder. We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\nmc: <ERROR> Unable to stat `myminio/mc-test-bucket-281/dir-31865-31948/object-2`. "
}
(7/14) Running minio-go tests ... FAILED in 1 minutes and 22 seconds
{
  "args": {
    "bucketName": "minio-go-test-61wu0d4boxswqiiw",
    "objectName": "9v6e0mpdnbyottc64mgpeccolxxxym"
  },
  "duration": 5241,
  "function": "CopyObject()",
  "message": "Unexpected error during listing objects",
  "name": "minio-go: testCopyObjectWithVersioning",
  "status": "FAIL"
}
(7/14) Running minio-java tests ... FAILED in 9 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket]",
  "duration": 192,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InternalError, message = We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided), bucketName = minio-java-test-3gie7jd, objectName = null, resource = /minio-java-test-3gie7jd, requestId = 171F33241D8AAC7F, hostId = 00c7681a-c4f1-4820-afd6-1ca906e65e49)\nrequest={method=GET, url=http://15.15.15.4:32456/minio-java-test-3gie7jd?list-type=2&prefix=&max-keys=1000&encoding-type=url&delimiter=%2F, headers=Host: 15.15.15.4:32456\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.5\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20221018T152337Z\nAuthorization: ██\n}\nresponse={code=500, headers=Accept-Ranges: bytes\nContent-Length: 374\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Request-Id: 171F33241D8AAC7F\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Tue, 18 Oct 2022 15:23:37 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(7/14) Running minio-js tests ... FAILED in 14 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(7/14) Running minio-py tests ... done in 2 minutes and 3 seconds
(8/14) Running s3cmd tests ... done in 18 seconds
(9/14) Running s3select tests ... done in 5 seconds
(10/14) Running versioning tests ... done in 3 minutes and 37 seconds

Executed 10 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-18 16:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#32355664-5e77-41a8-9ac5-ce0664e2e3d1) |
<a name="32355664-5e77-41a8-9ac5-ce0664e2e3d1"></a>
### 15840-e23535b/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:31919
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 91747ff66fbb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 15385,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "fatal error: An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 4): We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted."
}
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... FAILED in 18 seconds
{
  "name": "mc",
  "duration": "15362",
  "function": "test_list_dir",
  "status": "FAIL",
  "error": "unexpected listing dir"
}
(6/14) Running minio-go tests ... done in 1 minutes and 30 seconds
(7/14) Running minio-java tests ... done in 37 seconds
(8/14) Running minio-js tests ... FAILED in 11 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 15,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(8/14) Running minio-py tests ... done in 2 minutes and 1 seconds
(9/14) Running s3cmd tests ... done in 18 seconds
(10/14) Running s3select tests ... done in 5 seconds
(11/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 11 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-19 00:25 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-19 04:59 UTC, donatello commented
PTAL @harshavardhana @kannappanr - we need another review, but this one is ready.

2022-10-19 18:00 UTC, harshavardhana approved these changes

2022-10-19 18:00 UTC, merged