storage: Return errDiskNotFound when a peer is during shutdown
minio/minio pull request #15868
Opened 2022-10-14 14:01 UTC by vadmeste

## Description
This mainly to show 'offline' instead 'unknown' state of some disks in DiskInfo() result

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-10-14 14:16 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :x: [more...](#adfe384c-a5bd-4c82-836d-e34909dbf8a1) |
| mint-fs.sh | :x: [more...](#9c5de914-de84-479c-b5f7-30de5bd6ee22) |
| mint-gateway-s3.sh | :x: [more...](#c3501958-bca7-4278-9340-7ec8e900ae7b) |
| mint-erasure.sh | :x: [more...](#11de50a4-6e14-41ca-a5e4-eb10ee35b018) |
| mint-dist-erasure.sh | :x: [more...](#2ac25dc8-d826-4e06-9b43-c8d861f1b8f3) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#67127b43-97a3-4a8e-a31a-33fa94ac83e4) |
| mint-pools.sh | :x: [more...](#2b4e6bf3-6219-43db-bdba-9081bbfc3adb) |
<a name="c3501958-bca7-4278-9340-7ec8e900ae7b"></a>
### 15868-c7e0379/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.19:32264
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 9eb12e0e30e9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... FAILED in 7 seconds
{
  "args": {
    "bucketName": "minio-go-test-j9g0sjnkvsbx6apa",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "0odpma9tapfvlyzk36mwzpw92m0c1r",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3203,
  "error": "want yXTVFQ==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 30 seconds
(9/14) Running minio-js tests ... done in 34 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 10 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 3 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
<a name="9c5de914-de84-479c-b5f7-30de5bd6ee22"></a>
### 15868-c7e0379/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.2:31147
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 45fd539f1974:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... FAILED in 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-zqtohfpx5njrvuud",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "15bmgv553mrqyu1w9kxkfsfqep25tu",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2684,
  "error": "want yXTVFQ==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 17 seconds
(9/14) Running minio-js tests ... done in 43 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 7 seconds
(11/14) Running s3cmd tests ... done in 13 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="adfe384c-a5bd-4c82-836d-e34909dbf8a1"></a>
### 15868-c7e0379/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.19:31904
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp fbc188fa18de:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-gcg6rjcm1fwlpvc4",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "wyyp5cmn31rlb2e06i1fyitwd0jgxi",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2262,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 33 seconds
(9/14) Running minio-js tests ... done in 51 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 49 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
<a name="11de50a4-6e14-41ca-a5e4-eb10ee35b018"></a>
### 15868-c7e0379/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:30845
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp a24d84ebce20:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... FAILED in 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-p6tk4305tfotprgo",
    "metadata": {
      "x-amz-checksum-crc32": "Ac5tPw=="
    },
    "objectName": "lefrqavwt5ybkyk1j2utwv5peisuzv",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2499,
  "error": "want yXTVFQ==, got Ac5tPw==",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 18 seconds
(9/14) Running minio-js tests ... done in 45 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 9 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="67127b43-97a3-4a8e-a31a-33fa94ac83e4"></a>
### 15868-c7e0379/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.2:31486
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1 [...]

2022-10-14 17:10 UTC, harshavardhana requested changes

2022-10-14 17:10 UTC, harshavardhana commented on cmd/storage-rest-client.go
> +
This can be written in one line..

2022-10-14 23:53 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#aa1a7ae5-560b-4b20-b0d8-b3c102ea0fa1) |
| mint-gateway-s3.sh | :x: [more...](#ef664cff-0b27-4d9c-a37d-4077735323b1) |
| mint-pools.sh | :x: [more...](#d30910d4-c012-49c9-a679-d391208d1886) |
<a name="ef664cff-0b27-4d9c-a37d-4077735323b1"></a>
### 15868-1835f09/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.23:30506
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 3cb4011b05b3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... FAILED in 7 seconds
{
  "args": {
    "bucketName": "minio-go-test-qfifb341ou1unakg",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "i3bagghagxiszs3cvh3gw6rbnyna2d",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3397,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 30 seconds
(9/14) Running minio-js tests ... done in 34 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 9 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 2 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
<a name="aa1a7ae5-560b-4b20-b0d8-b3c102ea0fa1"></a>
### 15868-1835f09/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.19:31324
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp e4a8161ada40:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 12 seconds
(8/14) Running minio-go tests ... FAILED in 4 seconds
{
  "args": {
    "bucketName": "minio-go-test-xk9oey34zz2zbesd",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "d6ld4e0y2psmxlfqdzpbhqhpjn9hg2",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2425,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 15 seconds
(9/14) Running minio-js tests ... done in 41 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 5 seconds
(11/14) Running s3cmd tests ... done in 12 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="d30910d4-c012-49c9-a679-d391208d1886"></a>
### 15868-1835f09/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.22:30676
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2239fdb553ba:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "awscli",
  "duration": 12150,
  "function": "aws --endpoint-url http://15.15.15.22:30676 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-2546/\n",
  "status": "FAIL",
  "error": "fatal error: An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 4): We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)"
}
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... FAILED in 44 seconds
{
  "name": "mc",
  "duration": "5703",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "mirror and list differs"
}
(6/14) Running minio-go tests ... FAILED in 35 seconds
{
  "args": {
    "bucketName": "minio-go-test-u39wo1t1qmjzp22c",
    "region": "eu-central-1"
  },
  "duration": 5618,
  "error": "We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)",
  "function": "MakeBucket(bucketName, region)",
  "message": "CleanupBucket failed",
  "name": "minio-go: testMakeBucketRegions",
  "status": "FAIL"
}
(6/14) Running minio-java tests ... done in 40 seconds
(7/14) Running minio-js tests ... FAILED in 46 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook for \"removeObject(bucketName, objectName, removeOpts)",
  "args": "bucketName:minio-js-test-version-lista65490d5-d362-4d61-91b4-fc5027494043",
  "duration": 7,
  "alert": "Remove 5 objects\"",
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty. You must delete all versions in the bucket. at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(7/14) Running minio-py tests ... done in 2 minutes and 1 seconds
(8/14) Running s3cmd tests ... done in 26 seconds
(9/14) Running s3select tests ... done in 5 seconds
(10/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 10 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-15 02:51 UTC, harshavardhana commented
> (5/14) Running awscli tests ... FAILED in 1 minutes and 16 seconds
> {
>   "name": "awscli",
>   "duration": 12150,
>   "function": "aws --endpoint-url http://15.15.15.22:30676 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-2546/\n",
>   "status": "FAIL",
>   "error": "fatal error: An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 4): We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)"
> }

This error seems to be caused by this change?

2022-10-16 06:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-17 21:12 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#12ec3a67-821c-411d-b035-7db20d7fe68b) |
| mint-gateway-s3.sh | :x: [more...](#7599488e-3aed-4031-8c21-9fa3aa2cfb4c) |
<a name="7599488e-3aed-4031-8c21-9fa3aa2cfb4c"></a>
### 15868-2d705c2/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:30793
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp ddc250e8a15e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... FAILED in 8 seconds
{
  "args": {
    "bucketName": "minio-go-test-2vouyojsxnoacjbl",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "o1f0n2u5nrsdbv69d6xa6rihh3fdts",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 3367,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 37 seconds
(9/14) Running minio-js tests ... done in 38 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 17 seconds
(11/14) Running s3cmd tests ... done in 1 minutes and 5 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 0 seconds

Executed 13 out of 14 tests successfully.
```
<a name="12ec3a67-821c-411d-b035-7db20d7fe68b"></a>
### 15868-2d705c2/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.4:32592
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp e3abf9c8c1d4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 12 seconds
(8/14) Running minio-go tests ... FAILED in 6 seconds
{
  "args": {
    "bucketName": "minio-go-test-obqu3mr0tl0dau2n",
    "metadata": {
      "x-amz-checksum-crc32": "J6e2lA=="
    },
    "objectName": "spe4xltpqx0fjylqageit5xza1pp5t",
    "opts": "minio.PutObjectOptions{UserMetadata: metadata, Progress: progress}"
  },
  "duration": 2924,
  "error": "want J6e2lA==, got ",
  "function": "PutObject(bucketName, objectName, reader,size, opts)",
  "message": "checksum mismatch",
  "name": "minio-go: testPutObjectWithChecksums",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 17 seconds
(9/14) Running minio-js tests ... done in 42 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 8 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 1 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-17 22:00 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#95da0fd4-5221-49f4-9e8d-a2ed82405f8c) |
<a name="95da0fd4-5221-49f4-9e8d-a2ed82405f8c"></a>
### 15868-e1560c8/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.19:31411
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp f338eecdbce4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... done in 1 minutes and 3 seconds
(9/14) Running minio-java tests ... FAILED in 34 seconds
{
  "name": "minio-java",
  "function": "getObjectRetention()",
  "duration": 88,
  "status": "FAIL",
  "error": "java.time.format.DateTimeParseException: Text '2022-10-18T21:54:28.6Z' could not be parsed at index 19 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioAsyncClient.lambda$getObjectRetention$35(MinioAsyncClient.java:1738), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506), java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073), io.minio.S3Base$1.onResponse(S3Base.java:559), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 54 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 53 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 6 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-17 22:17 UTC, harshavardhana approved these changes

2022-10-18 18:51 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-18 20:50 UTC, merged