Update admin IDP APIs to be more RESTful
minio/minio pull request #15896
Opened 2022-10-19 00:14 UTC by donatello

## Description

IDP config create vs update API calls are now separate using PUT and PATCH http verbs.

## Motivation and Context

Allows for easier add/update/list/get/remove semantics.

## How to test this PR?

See the new commands in https://github.com/minio/mc/pull/4310.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-10-19 00:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-19 01:33 UTC, harshavardhana requested changes

2022-10-19 01:33 UTC, harshavardhana commented on cmd/admin-router.go
> +		adminRouter.Methods(http.MethodDelete).Path(adminVersion + "/idp-config/{type}/{name}").HandlerFunc(gz(httpTraceHdrs(adminAPI.DeleteIdentityProviderCfg)))
My suggestion @donatello lets not break it - we should have a newer API if needed.

2022-10-19 01:33 UTC, harshavardhana commented on cmd/admin-router.go
> +		adminRouter.Methods(http.MethodPatch).Path(adminVersion + "/idp-config/{type}/{name}").HandlerFunc(gz(httpTraceHdrs(adminAPI.UpdateIdentityProviderCfg)))
We actually do not encourage usage of Patch API and lets not add it. You can use POST instead.

2022-10-19 01:59 UTC, donatello commented on cmd/admin-router.go
> +		adminRouter.Methods(http.MethodDelete).Path(adminVersion + "/idp-config/{type}/{name}").HandlerFunc(gz(httpTraceHdrs(adminAPI.DeleteIdentityProviderCfg)))
Yeah I am trying to ensure that the breakage is not visible at the mc level by adding compatibility functionality in https://github.com/minio/madmin-go/pull/141 

`mc` will be updated to hide the `mc admin idp set|info|ls|rm` commands from help, but will continue to work as before.

Do you think there will still be a problem?

2022-10-19 02:42 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#f603b18d-3c86-443e-aafb-83b84f853b2e) |
<a name="f603b18d-3c86-443e-aafb-83b84f853b2e"></a>
### 15896-90c8374/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.23:32090
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 59752c03e933:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... FAILED in 21 seconds
{
  "name": "awscli",
  "duration": 10190,
  "function": "aws --endpoint-url http://15.15.15.23:32090 s3api list-objects-v2 --bucket awscli-mint-test-bucket-14965 --prefix datafile-1-kB\n",
  "status": "FAIL",
  "error": ""
}
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... FAILED in 44 seconds
{
  "name": "mc",
  "duration": "15307",
  "function": "test_copy_object_preserve_filesystem_attr",
  "status": "FAIL",
  "error": "unable to put object with file system attribute"
}
(6/14) Running minio-go tests ... FAILED in 12 seconds
{
  "args": {
    "bucketName": "minio-go-test-o3j9uw9jvekjcusu",
    "isRecursive": true,
    "objectName": "minio-go-test-o3j9uw9jvekjcusuunique"
  },
  "duration": 4305,
  "function": "ListObjects(bucketName, objectName, isRecursive, doneCh)",
  "message": "Could not find existing object minio-go-test-o3j9uw9jvekjcusuunique",
  "name": "minio-go: testFunctionalV2",
  "status": "FAIL"
}
(6/14) Running minio-java tests ... done in 40 seconds
(7/14) Running minio-js tests ... done in 53 seconds
(8/14) Running minio-py tests ... done in 1 minutes and 52 seconds
(9/14) Running s3cmd tests ... done in 17 seconds
(10/14) Running s3select tests ... done in 5 seconds
(11/14) Running versioning tests ... done in 3 minutes and 37 seconds

Executed 11 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-19 18:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-20 20:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-20 20:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-20 20:43 UTC, harshavardhana approved these changes

2022-10-24 09:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-10-31 18:27 UTC, krisis approved these changes

2022-10-31 18:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#451aeef5-e8e7-46bb-bc20-dfab676884b7) |
<a name="451aeef5-e8e7-46bb-bc20-dfab676884b7"></a>
### 15896-61c1e85/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.23:31610
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp eb8064877733:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 43 seconds
(9/14) Running minio-java tests ... FAILED in 17 seconds
{
  "name": "minio-java",
  "function": "getObjectRetention()",
  "duration": 23,
  "status": "FAIL",
  "error": "java.time.format.DateTimeParseException: Text '2022-11-03T18:28:36.7Z' could not be parsed at index 19 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioAsyncClient.lambda$getObjectRetention$35(MinioAsyncClient.java:1738), java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642), java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506), java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073), io.minio.S3Base$1.onResponse(S3Base.java:559), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 49 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 11 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-10-31 21:52 UTC, merged