config: Return XMinioConfigNotFound code for non existing config
minio/minio pull request #16065
Opened 2022-11-14 21:21 UTC by vadmeste

## Description
MinIO operator needs this error to ignore the error of not finding a logsearch webhook config.

## Motivation and Context
Return XMinioConfigNotFoundError instead of XMinioConfigError 
when trying to delete a configuration

## How to test this PR?
```
package main

import (
        "context"
        "fmt"
        "log"
        "reflect"

        "github.com/minio/madmin-go"
)

func main() {
        // Note: YOUR-ACCESSKEYID, YOUR-SECRETACCESSKEY and my-bucketname are
        // dummy values, please replace them with original values.

        // API requests are secure (HTTPS) if secure=true and insecure (HTTP) otherwise.
        // New returns an MinIO Admin client object.
        madmClnt, err := madmin.New("localhost:9000", "minioadmin", "minioadmin", false)
        if err != nil {
                log.Fatalln(err)
        }   

        _, err := madmClnt.DelConfigKV(context.Background(), "audit_webhook:abcd")
        if err != nil {
                adminErr := madmin.ToErrorResponse(err)
                fmt.Println(adminErr.Code, adminErr.Message)
                fmt.Println(reflect.TypeOf(err))
        }   
}
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-11-14 21:37 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-11-14 21:41 UTC, harshavardhana requested changes
This is fine we don't need to call it FmtWithType

2022-11-14 21:41 UTC, harshavardhana commented on internal/config/config.go
> +func ErrorFmtWithType[T Error, PT interface {
```suggestion
func Error[T Error, PT interface {
```

2022-11-15 07:28 UTC, harshavardhana commented
> Return XMinioConfigNotFoundError instead of XMinioConfigError

It can't rely on XMinioConfigError ?

2022-11-15 08:26 UTC, vadmeste commented
> It can't rely on XMinioConfigError ?

This is too generic

2022-11-15 09:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#152a3693-7c99-4fa9-b067-eb3aa920dc33) |
| mint-dist-erasure.sh | :x: [more...](#e3a55c6f-5c27-425d-bfb6-c1bf928a73d1) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#e7321fc6-34c2-41aa-b29c-36e89b4cdf68) |
| mint-pools.sh | :x: [more...](#e087f92f-f4b7-47b3-bd40-6eaa585056ef) |
<a name="152a3693-7c99-4fa9-b067-eb3aa920dc33"></a>
### 16065-9ca4515/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:31969
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 4db0ddcaadfc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-acmyewpk2lgun9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 274,
  "error": "RequestError: send request failed\ncaused by: Put \"http://15.15.15.7:31969/aws-sdk-go-test-acmyewpk2lgun9\": dial tcp 15.15.15.7:31969: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-java tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-acmyewpk2lgun9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 274,
  "error": "RequestError: send request failed\ncaused by: Put \"http://15.15.15.7:31969/aws-sdk-go-test-acmyewpk2lgun9\": dial tcp 15.15.15.7:31969: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-php tests ... FAILED in 7 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-acmyewpk2lgun9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 274,
  "error": "RequestError: send request failed\ncaused by: Put \"http://15.15.15.7:31969/aws-sdk-go-test-acmyewpk2lgun9\": dial tcp 15.15.15.7:31969: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/14) Running aws-sdk-ruby tests ... FAILED in 6 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 2109.28,
  "error": "Failed to open TCP connection to 15.15.15.7:31969 (Connection refused - connect(2) for \"15.15.15.7\" port 31969)",
  "status": "FAIL"
}
(1/14) Running awscli tests ... FAILED in 14 seconds
{"name": "awscli", "duration": 11720, "function": "make_bucket\n", "status": "FAIL", "error": "Could not connect to the endpoint URL: "http://15.15.15.7:31969/awscli-mint-test-bucket-10428""}
(1/14) Running healthcheck tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": null,
  "duration": 0,
  "error": "Get \"http://15.15.15.7:31969/minio/health/live\": dial tcp 15.15.15.7:31969: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(1/14) Running mc tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": null,
  "duration": 0,
  "error": "Get \"http://15.15.15.7:31969/minio/health/live\": dial tcp 15.15.15.7:31969: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(1/14) Running minio-go tests ... FAILED in 6 seconds
{
  "args": {
    "bucketName": "minio-go-test-vd99ysihupl0p1tg",
    "region": "eu-west-1"
  },
  "duration": 6932,
  "error": "Put \"http://15.15.15.7:31969/minio-go-test-vd99ysihupl0p1tg/\": dial tcp 15.15.15.7:31969: connect: connection refused",
  "function": "MakeBucket(bucketName, region)",
  "message": "MakeBucket failed",
  "name": "minio-go: testMakeBucketErrorV2",
  "status": "FAIL"
}
(1/14) Running minio-java tests ... FAILED in 1 seconds
{
  "name": "minio-java",
  "function": "makeBucket()",
  "args": "[basic check]",
  "duration": 64,
  "status": "FAIL",
  "error": "java.net.ConnectException: Failed to connect to /15.15.15.7:31969 >>> [okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297), okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207), okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226), okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106), okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74), okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(1/14) Running minio-js tests ... FAILED in 2 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 1010,
  "status": "FAIL",
  "error": "Error: connect ECONNREFUSED 15.15.15.7:31969 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16)"
}
(1/14) Running minio-py tests ... FAILED in 8 seconds
{
  "name": "minio-py:test_make_bucket_default_region",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-b10e69cd-8c6f-4263-b59f-30290910a94b",
    "location": "default value ('us-east-1')"
  },
  "message": "HTTPConnectionPool(host='15.15.15.7', port=31969): Max retries exceeded with url: /minio-py-test-b10e69cd-8c6f-4263-b59f-30290910a94b (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f3964e1a6a0>: Failed to establish a new connection: [Errno 111] Connection refused'))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connection.py\", line 174, in _new_conn\n    conn = connection.create_connection(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py\", line 95, in create_connection\n    raise err\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py\", line 85, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 398, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connection.py\", line 239, in request\n    super(HTTPConnection, self).request(method, url, body=body, headers=headers)\n  File \"/usr/lib/python3.8/http/client.py\", line 1256, in request\n    self._send_reques [...]

2022-11-15 21:52 UTC, harshavardhana commented
So this is a breaking change for the client as it has to look for a new error? @vadmeste

2022-11-16 08:51 UTC, vadmeste commented
> So this is a breaking change for the client as it has to look for a new error? @vadmeste

Yes, but I don't think there is a client out there doing that, currently madmin-go returns the error as it is. The code will need to convert the error to madmin.ErrorResponse and check for the Code field

2022-11-18 13:48 UTC, harshavardhana approved these changes

2022-11-18 14:55 UTC, klauspost approved these changes
Neat. I guess the config could also have the http status code.

Not that important right now.

2022-11-18 18:28 UTC, merged