wraped error will not equal
minio/minio pull request #16113
Opened 2022-11-23 07:45 UTC by jiuker

cmd/erasure-server-pool-decom.go:262
```go
			return fmt.Errorf("%w at index: %d", errDecommissionAlreadyRunning, i)
```
to cmd/erasure-server-pool-decom.go:1284
```go
	if err = z.poolMeta.Decommission(idx, pi); err != nil {
		return err
	}
```
to cmd/erasure-server-pool-decom.go:1043
```go
	if err := z.StartDecommission(ctx, idx); err != nil {
		return err
	}
```
cmd/erasure-server-pool-decom.go:541
```go
                                       if err := z.Decommission(ctx, pool.ID); err != nil {
							switch err {
							// we already started decommission
							case errDecommissionAlreadyRunning:
								// A previous decommission running found restart it.
								z.doDecommissionInRoutine(ctx, idx)
								return
							default:
								if configRetriableErrors(err) {
									logger.LogIf(ctx, fmt.Errorf("Unable to resume decommission of pool %v: %w: retrying..", pool, err))
									time.Sleep(time.Second + time.Duration(r.Float64()*float64(5*time.Second)))
									continue
								}
								logger.LogIf(ctx, fmt.Errorf("Unable to resume decommission of pool %v: %w", pool, err))
								return
							}
						}
```

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-11-23 08:01 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-11-23 09:40 UTC, klauspost requested changes
I think we can make it more readable:

2022-11-23 09:40 UTC, klauspost commented on cmd/erasure-server-pool-decom.go
> +							switch {
Suggestion for entire block:
```
	if errors.Is(err, errDecommissionAlreadyRunning) {
		// A previous decommission running found restart it.
		z.doDecommissionInRoutine(ctx, idx)
		return
	}
	if configRetriableErrors(err) {
		logger.LogIf(ctx, fmt.Errorf("Unable to resume decommission of pool %v: %w: retrying..", pool, err))
		time.Sleep(time.Second + time.Duration(r.Float64()*float64(5*time.Second)))
		continue
	}
	logger.LogIf(ctx, fmt.Errorf("Unable to resume decommission of pool %v: %w", pool, err))
	return
```

2022-11-23 10:34 UTC, klauspost approved these changes
LGTM

2022-11-23 10:44 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-11-24 01:51 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-11-24 11:38 UTC, klauspost approved these changes

2022-11-24 16:00 UTC, harshavardhana approved these changes

2022-11-24 16:00 UTC, merged