Add minimal setup command to helm chart's readme
minio/minio pull request #16165
Opened 2022-12-03 13:01 UTC by rebrendov

## Description
- add default helm chart's values for `replicas` and `resources.requests.memory` to readme
- add minimal setup command to readme

## Motivation and Context
Help new users to quickly setup a test instance.

#16164 also described here.

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-12-03 13:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#8ff5a830-5c7b-4da0-8903-005e7693314b) |
<a name="8ff5a830-5c7b-4da0-8903-005e7693314b"></a>
### 16165-1fe0e9e/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:30980
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp f07dbdde8de8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 8688,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "fatal error: An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 4): We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted."
}
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... FAILED in 26 seconds
{
  "name": "mc",
  "duration": "11313",
  "function": "test_mv_object",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21503 --quiet --no-color rm -r --force myminio/mc-test-bucket-27620/dir-3421-32373/  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-27620/dir-3421-32373/` recursively. We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)"
}
(6/14) Running minio-go tests ... FAILED in 11 seconds
{
  "args": {
    "bucketName": "minio-go-test-udtl0rpawnv2kv14",
    "isRecursive": true,
    "objectName": "minio-go-test-udtl0rpawnv2kv14unique"
  },
  "duration": 4415,
  "function": "ListObjects(bucketName, objectName, isRecursive, doneCh)",
  "message": "Could not find existing object minio-go-test-udtl0rpawnv2kv14unique",
  "name": "minio-go: testFunctionalV2",
  "status": "FAIL"
}
(6/14) Running minio-java tests ... done in 36 seconds
(7/14) Running minio-js tests ... FAILED in 12 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(7/14) Running minio-py tests ... done in 1 minutes and 54 seconds
(8/14) Running s3cmd tests ... done in 25 seconds
(9/14) Running s3select tests ... done in 4 seconds
(10/14) Running versioning tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "versioning-test-zqwxeyy5f6pojt",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 515,
  "error": "InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 172D4AB0742DD557, host id: ",
  "function": "/mint/build/versioning/put.go:103: main.testPutObject",
  "message": "PUT expected to succeed but got InternalError: We encountered an internal error, please try again.: cause(listPathRaw: 0 drives provided)\n\tstatus code: 500, request id: 172D4AB0742DD557, host id: ",
  "name": "versioning",
  "status": "FAIL"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2022-12-04 10:31 UTC, harshavardhana requested changes
Perhaps rewrite it like this

### Installing the Chart
Install this chart using:
```bash
helm install --namespace minio --set rootUser=rootuser,rootPassword=rootpass123 --generate-name minio/minio
```

The command deploys MinIO on the Kubernetes cluster in the default configuration. The [configuration](#configuration) section lists the parameters that can be configured during installation.

### Installing the Chart (toy-setup)
Minimal toy setup for testing purposes can be deployed using:

```bash
helm install --set resources.requests.memory=512Mi --set replicas=1 --set persistence.enabled=false --set mode=standalone --set rootUser=rootuser,rootPassword=rootpass123 --generate-name minio/minio
```

2022-12-05 11:07 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2022-12-05 21:21 UTC, harshavardhana approved these changes

2022-12-05 21:22 UTC, merged