decom: List pool after decom and error out if an object is found
minio/minio pull request #16277
Opened 2022-12-19 15:20 UTC by vadmeste

## Description
As a sanity check measurement, add a listing of the pool after decomissiing
and try if it can find any object, mark decomissionin status as failed if that is the case

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2022-12-20 11:29 UTC, klauspost reviewed
Great stuff. Some minor suggestions.

2022-12-20 11:29 UTC, klauspost commented on cmd/erasure-server-pool-decom.go
> +		logger.Info("Decommissioning almost complete - doing further checks")
```suggestion
		logger.Info("Decommissioning almost complete - checking for left over objects")
```

2022-12-20 11:29 UTC, klauspost commented on cmd/erasure-server-pool-decom.go
> +				objectsFound++
```suggestion
				if entry.isObject() {
					objectsFound++
				}
```

2022-12-20 11:29 UTC, klauspost commented on cmd/erasure-server-pool-decom.go
> +				return fmt.Errorf("at least %d objects were found after decommissioning", objectsFound)
Should we maybe move this to the outside to get the exact count?

2023-01-08 22:30 UTC, harshavardhana requested changes
Actually @vadmeste instead of listing the previous pool it is better to simply do ListBuckets() and attempt a "DeleteVol" on them?

Instead of recursively listing which is rather expensive you can use a cheaper way to know if the bucket is empty or not?

2023-01-09 12:57 UTC, vadmeste commented
> Actually @vadmeste instead of listing the previous pool it is better to simply do ListBuckets() and attempt a "DeleteVol" on them?

Well, my guess is that this can easily fail with some left over files.. like when removing an object was successful because quorum is reached on DELETE but there are still some left over data in some nodes. I think this can easily happen in case of decommissioning because it issues erasure DeleteObject calls for all objects in the decomissioned pool.

Maybe run healing with delete flag in it ?

>  Instead of recursively listing which is rather expensive you can use a cheaper way to know if the bucket is empty or not?

This should not be expensive in normal use case since buckets are supposed to be already empty.

2023-01-09 15:51 UTC, harshavardhana commented
> > Actually @vadmeste instead of listing the previous pool it is better to simply do ListBuckets() and attempt a "DeleteVol" on them?
> 
> Well, my guess is that this can easily fail with some left over files.. like when removing an object was successful because quorum is reached on DELETE but there are still some left over data in some nodes. I think this can easily happen in case of decommissioning because it issues erasure DeleteObject calls for all objects in the decomissioned pool.
> 
> Maybe run healing with delete flag in it ?
> 
> > Instead of recursively listing which is rather expensive you can use a cheaper way to know if the bucket is empty or not?
> 
> This should not be expensive in normal use case since buckets are supposed to be already empty.

Okay we can live with this PR.

2023-01-10 15:13 UTC, vadmeste commented on cmd/erasure-server-pool-decom.go
> +				return fmt.Errorf("at least %d objects were found after decommissioning", objectsFound)
> Should we maybe move this to the outside to get the exact count?

Not so keen doing it, because if something is wrong, it may take too much time to list everything. Though something is wrong here means a bug in the code and not bad external environment because decommissioning will stop automatically after the first encountered failure.

2023-01-10 15:27 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a9f43647-3f72-4915-9fae-559dd9fb82e8) |
| mint-dist-erasure.sh | :x: [more...](#0bebdc66-4d43-4c45-9bdb-7bfd280b9eb8) |
<a name="0bebdc66-4d43-4c45-9bdb-7bfd280b9eb8"></a>
### 16277-3b45e2a/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:31735
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp b5f472c07436:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... done in 46 seconds
(9/14) Running minio-java tests ... FAILED in 27 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 376,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"1738FBB6415175F7\",\"HostId\":\"d3e72246-cad2-49da-902b-1cd66d76a79a\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 49 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 40 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
<a name="a9f43647-3f72-4915-9fae-559dd9fb82e8"></a>
### 16277-3b45e2a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:31881
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 0c2a2b635e1b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 48 seconds
(9/14) Running minio-java tests ... FAILED in 30 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 348,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"1738FBB75673BB7B\",\"HostId\":\"a2772f5c-8b56-4cb3-9f8d-825878cef97b\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 47 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-01-10 15:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-01-10 16:10 UTC, harshavardhana approved these changes

2023-01-12 00:22 UTC, merged