xl: Quit early when EC config is not correct
minio/minio pull request #16390
Opened 2023-01-09 21:31 UTC by vadmeste

## Description
Currently, when export MINIO_STORAGE_CLASS_STANDARD 
is set with wrong EC value, a log is printed during startup. 
However, the server should exit instead.

Also add a warning at the end of the startup banner when 
the calculated standard EC is zero.

## Motivation and Context
Exit the server instead of printing a log when EC config is wrong

## How to test this PR?
export MINIO_STORAGE_CLASS_STANDARD=EC:3
./minio server /tmp/xl/{1...4}/

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-01-09 21:47 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :x: [more...](#a30fc506-8208-47fb-ba98-ee0c552d28b2) |
<a name="a30fc506-8208-47fb-ba98-ee0c552d28b2"></a>
### 16390-641f83b/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:30557
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2479bc2d25ac:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 46 seconds
(9/14) Running minio-java tests ... FAILED in 29 seconds
{
  "name": "minio-java",
  "function": "addUser()",
  "duration": 414,
  "status": "FAIL",
  "error": "java.lang.RuntimeException: Request failed with response: {\"Code\":\"InternalError\",\"Message\":\"We encountered an internal error, please try again. (Server not initialized, please try again)\",\"Resource\":\"/minio/admin/v3/add-user\",\"RequestId\":\"1738C1E532C7F0EF\",\"HostId\":\"917dc443-a8c2-4b65-a11a-7de1f957a1e6\"}\n >>> [io.minio.admin.MinioAdminClient.execute(MinioAdminClient.java:206), io.minio.admin.MinioAdminClient.addUser(MinioAdminClient.java:237), TestMinioAdminClient.addUser(TestMinioAdminClient.java:47), TestMinioAdminClient.runAdminTests(TestMinioAdminClient.java:160), FunctionalTest.runTests(FunctionalTest.java:3782), FunctionalTest.runEndpointTests(FunctionalTest.java:3881), FunctionalTest.main(FunctionalTest.java:4002)]"
}
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 35 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-01-09 21:56 UTC, poornas requested changes

2023-01-09 21:56 UTC, poornas commented on cmd/server-main.go
> +		}
can we colorize this warning msg? Otherwise, LGTM

2023-01-09 23:03 UTC, harshavardhana commented on cmd/server-main.go
> +		}
Not much valuable when you are anyway printing to a non terminal @poornas

2023-01-09 23:08 UTC, harshavardhana approved these changes

2023-01-09 23:21 UTC, poornas approved these changes

2023-01-10 07:07 UTC, kannappanr approved these changes

2023-01-10 07:07 UTC, merged