Optimize background heal status to use LocalStorageInfo
minio/minio pull request #16414
Opened 2023-01-14 12:05 UTC by vadmeste

## Description
DEPENDS on https://github.com/minio/madmin-go/pull/169

object-interface.StorageInfo() is called for each node 
when the heal status of the cluster is asked.

This is unnecessary and we can use LocalStorageInfo() instead.

## Motivation and Context
Reduce calls when heal status is asked

## How to test this PR?
mc admin heal -v myminio

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-01-14 12:21 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-01-15 17:40 UTC, harshavardhana approved these changes

2023-01-16 08:47 UTC, klauspost reviewed
LGTM.

madmin replace can now be removed.

2023-01-16 12:23 UTC, harshavardhana requested changes

2023-01-16 12:23 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/madmin-go/v2 => github.com/vadmeste/madmin-go/v2 v2.0.7-0.20230114115708-fa3e401ef0e3
please update this @vadmeste

2023-01-16 16:43 UTC, klauspost approved these changes

2023-01-16 16:57 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-01-16 23:31 UTC, harshavardhana approved these changes

2023-01-16 23:32 UTC, merged