Set meaningful message from minio with env variable KMS_SECRET_KEY
minio/minio pull request #16584
Opened 2023-02-10 02:33 UTC by allanrogerr

## Description
If env variable name MINIO_KMS_SECRET_KEY is set in minio and on the console:
if the user chooses SSE-KMS then an error appears:
```
A header you provided implies functionality that is not implemented
```
if the user tries to add a new key then an error appears
```
A header you provided implies functionality that is not implemented
```

## Motivation and Context
If the env variable name MINIO_KMS_SECRET_KEY is set in minio then the console should display this single, uneditable key. No further keys should be able to be added.
These errors do not help guide the user in fixing the issue and need to be more meaningful

## How to test this PR?
See issue https://github.com/miniohq/engineering/issues/1148

### Steps to reproduce
1. Generate a 256 bit random key via:
```
cat /dev/urandom | head -c 32 | base64
```
Example response
```
wz83JmWETiDPeoL4jKZNmYkxDIpIdfIDv7eJVxgeNNc=
```

2. Now, set MINIO_KMS_SECRET_KEY like this:
```
export MINIO_KMS_SECRET_KEY=my-minio-key:wz83JmWETiDPeoL4jKZNmYkxDIpIdfIDv7eJVxgeNNc=
```

3. Deploy minio with an old version of console. 
Clone, checkout, build and start old minio
```
git clone https://github.com/minio/minio.git
git checkout master
make build
./minio server --console-address :9091 /tmp/data
```

Clone, checkout, build and start old console. An old console is used since a workaround was introduced to avoid this issue in the UI. The backend APIs are being addressed in this PR.
```
git clone https://github.com/allanrogerr/console.git
git checkout master
make console
./console server
```

4. Login to the console and attempt to set the Encryption on a new bucket to SSE-KMS. Observe an error.

5. Attempt to add a new encryption key. Observe an error.

### Fix
1. Clone, checkout, build and start minio
```
git clone https://github.com/allanrogerr/minio.git
git checkout allow-kms-secret-key
make build
./minio server --console-address :9091 /tmp/data
```

2. (If not already done above) Clone, checkout, build and start old console. An old console is used since a workaround was introduced to avoid this issue in the UI. The backend APIs are being addressed in this PR.
```
git clone https://github.com/allanrogerr/console.git
git checkout master
make console
./console server
```

3. Attempt to set the Encryption on a new bucket to SSE-KMS. Observe no error.

4. Attempt to add a new encryption key. Observe a meaningful error.
```
MINIO_KMS_SECRET_KEY is configured. Additional keys cannot be configured.
```

5. Test removing the env variable. Then,
Restart minio. Attempt to set the Encryption on a new bucket to SSE-KMS. Observe a meaningful error.
```
Server side encryption specified but KMS is not configured
```

6. Attempt to add a new encryption key. Observe a meaningful error.
```
Server side encryption specified but KMS is not configured
``` 

7. Attempt to use both configurations
```
ubuntu@minio-kes:~$ export MINIO_KMS_SECRET_KEY=my-minio-key:wz83JmWETiDPeoL4jKZNmYkxDIpIdfIDv7eJVxgeNNc=
ubuntu@minio-kes:~$ minio server data --certs-dir .
ERROR The environment contains "MINIO_KMS_SECRET_KEY" as well as "MINIO_KMS_KES_ENDPOINT": ambigious KMS configuration
```

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-02-10 02:33 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 16584-65379e2/gopath/src/github.com/minio
+ git -C 16584-65379e2/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 16584-65379e2/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 16584-65379e2/gopath/src/github.com/minio/minio fetch --quiet minio pull/16584/head:pr16584
+ git -C 16584-65379e2/gopath/src/github.com/minio/minio checkout --quiet pr16584
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/16584-65379e2/gopath
+ make -C 16584-65379e2/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading cloud.google.com/go/storage v1.29.0
go: downloading github.com/Azure/azure-storage-blob-go v0.15.0
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/klauspost/readahead v1.4.0
go: downloading github.com/felixge/fgprof v0.9.3
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/minio/madmin-go/v2 v2.0.9
go: downloading github.com/bits-and-blooms/bloom/v3 v3.3.1
go: downloading github.com/minio/minio-go/v7 v7.0.47
go: downloading github.com/klauspost/reedsolomon v1.11.6
go: downloading github.com/zeebo/xxh3 v1.0.2
go: downloading github.com/dchest/siphash v1.2.3
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading github.com/tinylib/msgp v1.1.8
go: downloading github.com/lithammer/shortuuid/v4 v4.0.0
go: downloading github.com/miekg/dns v1.1.50
go: downloading github.com/djherbis/atime v1.1.0
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/dustin/go-humanize v1.0.1
go: downloading go.etcd.io/etcd/api/v3 v3.5.7
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/minio/mux v1.9.0
go: downloading github.com/minio/dperf v0.4.2
go: downloading github.com/golang-jwt/jwt/v4 v4.4.3
go: downloading github.com/minio/selfupdate v0.6.0
go: downloading github.com/inconshreveable/mousetrap v1.1.0
go: downloading github.com/minio/pkg v1.6.1
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/minio/xxml v0.0.3
go: downloading github.com/klauspost/compress v1.15.15
go: downloading github.com/coreos/go-oidc v2.2.1+incompatible
go: downloading github.com/minio/kes v0.22.3
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/klauspost/filepathx v1.1.1
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/fatih/color v1.14.1
go: downloading github.com/prometheus/common v0.39.0
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/minio/console v0.23.1
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/minio/zipindex v0.3.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/rs/cors v1.8.3
go: downloading github.com/shirou/gopsutil/v3 v3.23.1
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/prometheus/client_golang v1.14.0
go: downloading github.com/minio/cli v1.24.2
go: downloading github.com/prometheus/procfs v0.9.0
go: downloading github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
go: downloading github.com/philhofer/fwd v1.1.2
go: downloading go.etcd.io/etcd/client/v3 v3.5.7
go: downloading github.com/tidwall/gjson v1.14.4
go: downloading github.com/go-openapi/loads v0.21.2
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading go.uber.org/atomic v1.10.0
go: downloading golang.org/x/crypto v0.5.0
go: downloading golang.org/x/oauth2 v0.4.0
go: downloading golang.org/x/sys v0.4.0
go: downloading google.golang.org/api v0.109.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading go.uber.org/zap v1.24.0
go: downloading golang.org/x/time v0.3.0
go: downloading github.com/coredns/coredns v1.10.0
go: downloading github.com/go-ldap/ldap/v3 v3.4.4
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading github.com/minio/simdjson-go v0.4.2
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/Shopify/sarama v1.38.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.4.2
go: downloading github.com/elastic/go-elasticsearch/v7 v7.17.7
go: downloading github.com/go-sql-driver/mysql v1.7.0
go: downloading github.com/gomodule/redigo v1.8.9
go: downloading github.com/lib/pq v1.10.7
go: downloading github.com/nats-io/nats.go v1.23.0
go: downloading github.com/nats-io/stan.go v0.10.4
go: downloading github.com/nsqio/go-nsq v1.1.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/rabbitmq/amqp091-go v1.6.1
go: downloading github.com/xdg/scram v1.0.5
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.17
go: downloading github.com/golang/protobuf v1.5.2
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/bits-and-blooms/bitset v1.5.0
go: downloading github.com/fraugster/parquet-go v0.12.0
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.1
go: downloading github.com/alecthomas/participle v0.7.1
go: downloading github.com/pquerna/cachecontrol v0.1.0
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: downloading aead.dev/minisign v0.2.0
go: downloading golang.org/x/net v0.5.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading github.com/klauspost/cpuid/v2 v2.2.3
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20221128193559-754e69321358
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading github.com/google/pprof v0.0.0-20230131232505-5a9e8f65f08f
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/xdg/stringprep v1.0.3
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.7
go: downloading google.golang.org/grpc v1.52.3
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
go: downloading github.com/rivo/uniseg v0.4.3
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading google.golang.org/genproto v0.0.0-20230202175211-008b39050e57
go: downloading github.com/coreos/go-semver v0.3.1
go: downloading github.com/go-openapi/analysis v0.21.4
go: downloading github.com/go-openapi/spec v0.20.8
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading github.com/Azure/azure-pipeline-go v0.2.3
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading golang.org/x/text v0.6.0
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/lestrrat-go/jwx v1.2.25
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/rs/xid v1.4.0
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading go.uber.org/multierr v1.9.0
go: downloading github.com/montanaflynn/stats v0.7.0
go: downloading github.com/rjeczalik/notify v0.9.3
go: downloading github.com/fatih/structs v1.1.0
go: downloading aead.dev/mem v0.2.0
go: downloading github.com/coreos/go-systemd/v22 v22.5.0
go: downloading github.com/tklauser/go-sysconf v0.3.11
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading cloud.google.com/go v0.109.0
go: downloading github.com/apache/thrift v0.17.0
go: downloading github.com/nats-io/nkeys v0.3.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/rcrowley/go-metrics v0.0.0-20201227073835-cf1acfcdf475
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/jcmturner/gokrb5/v8 v8.4.3
go: downloading github.com/jcmturner/gofork v1.7.6
go: downloading github.com/eapache/go-xerial-sn [...]

2023-02-10 04:09 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c4bc3fb2-59d2-4e0d-bcce-65b981eca012) |
<a name="c4bc3fb2-59d2-4e0d-bcce-65b981eca012"></a>
### 16584-d77b3d5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:32667
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 4c0fed1d85c8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 53 seconds
(9/14) Running minio-java tests ... done in 29 seconds
(10/14) Running minio-js tests ... done in 50 seconds
(11/14) Running minio-py tests ... done in 1 minutes and 42 seconds
(12/14) Running s3cmd tests ... done in 16 seconds
(13/14) Running s3select tests ... FAILED in 7 minutes and 20 seconds
{
  "name": "s3select:test_csv_output_quote_char",
  "function": "select_object_content(bucket_name, object_name, request)",
  "args": {
    "bucket_name": "s3select-test-4c237adb-28c8-494e-a834-827ed1f14e6c"
  },
  "duration": 438599,
  "message": "S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /s3select-test-4c237adb-28c8-494e-a834-827ed1f14e6c, request_id: 17425AEB896CAF78, host_id: a908fce3-aca3-4771-a9f2-7a7963ad5272, bucket_name: s3select-test-4c237adb-28c8-494e-a834-827ed1f14e6c",
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 57, in main\n    test_csv_output_custom_quote_char(client, log_output)\n  File \"/mint/run/core/s3select/csv.py\", line 148, in test_csv_output_custom_quote_char\n    client.make_bucket(bucket_name)\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 618, in make_bucket\n    self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 386, in _url_open\n    raise response_error\nminio.error.S3Error: S3 operation failed; code: BucketAlreadyOwnedByYou, message: Your previous request to create the named bucket succeeded and you already own it., resource: /s3select-test-4c237adb-28c8-494e-a834-827ed1f14e6c, request_id: 17425AEB896CAF78, host_id: a908fce3-aca3-4771-a9f2-7a7963ad5272, bucket_name: s3select-test-4c237adb-28c8-494e-a834-827ed1f14e6c\n",
  "status": "FAIL"
}
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-10 14:07 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#949a2672-9758-4b2b-89f5-7c6d3082db28) |
| mint-dist-erasure.sh | :x: [more...](#034599a6-d0a9-4498-bd2a-53b34333461a) |
<a name="949a2672-9758-4b2b-89f5-7c6d3082db28"></a>
### 16584-51ae558/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.2:31956
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 583a5079d09f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... FAILED in 1 minutes and 40 seconds
{
  "args": {
    "bucketName": "minio-go-test-bf51xehnkqh6khvl",
    "objectName": "zurdsot0fpqn64ojm0qozdygy30dmy"
  },
  "duration": 61248,
  "error": "read tcp 172.17.0.5:57192->15.15.15.2:31956: read: connection reset by peer",
  "function": "GetObject(bucketName, objectName)",
  "message": "CopyN failed",
  "name": "minio-go: testSSES3EncryptedGetObjectReadSeekFunctional",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 16 seconds
(9/14) Running minio-js tests ... done in 45 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 8 seconds
(11/14) Running s3cmd tests ... done in 13 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
<a name="034599a6-d0a9-4498-bd2a-53b34333461a"></a>
### 16584-51ae558/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:30905
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp e737277c6b43:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 46 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 46 seconds
(9/14) Running minio-java tests ... done in 28 seconds
(10/14) Running minio-js tests ... done in 47 seconds
(11/14) Running minio-py tests ... done in 1 minutes and 33 seconds
(12/14) Running s3cmd tests ... FAILED in 5 minutes and 20 seconds
{
  "name": "s3cmd",
  "duration": "312282",
  "function": "test_sync_list_objects",
  "status": "FAIL",
  "error": "upload: '/mint/data/datafile-0-b' -> 's3://s3cmd-test-bucket-18467/datafile-0-b' (0 bytes in 0.0 seconds, -1.00 B/s) [1 of 15]\nupload: '/mint/data/datafile-1-MB' -> 's3://s3cmd-test-bucket-18467/datafile-1-MB' (1048576 bytes in 0.0 seconds, 31.31 MB/s) [2 of 15]\nupload: '/mint/data/datafile-1-b' -> 's3://s3cmd-test-bucket-18467/datafile-1-b' (1 bytes in 0.0 seconds, 80.32 B/s) [3 of 15]\nupload: '/mint/data/datafile-1-kB' -> 's3://s3cmd-test-bucket-18467/datafile-1-kB' (1024 bytes in 0.0 seconds, 81.53 KB/s) [4 of 15]\nupload: '/mint/data/datafile-1.03-MB' -> 's3://s3cmd-test-bucket-18467/datafile-1.03-MB' (1081344 bytes in 0.0 seconds, 32.43 MB/s) [5 of 15]\nupload: '/mint/data/datafile-10-MB' -> 's3://s3cmd-test-bucket-18467/datafile-10-MB' (10485760 bytes in 0.2 seconds, 51.51 MB/s) [6 of 15]\nupload: '/mint/data/datafile-10-kB' -> 's3://s3cmd-test-bucket-18467/datafile-10-kB' (10240 bytes in 0.0 seconds, 812.52 KB/s) [7 of 15]\nupload: '/mint/data/datafile-100-kB' -> 's3://s3cmd-test-bucket-18467/datafile-100-kB' (102400 bytes in 0.0 seconds, 5.48 MB/s) [8 of 15]\nupload: '/mint/data/datafile-11-MB' -> 's3://s3cmd-test-bucket-18467/datafile-11-MB' (11534336 bytes in 0.2 seconds, 49.61 MB/s) [9 of 15]\nupload: '/mint/data/datafile-129-MB' -> 's3://s3cmd-test-bucket-18467/datafile-129-MB' (135266304 bytes in 2.7 seconds, 47.37 MB/s) [10 of 15]\nupload: '/mint/data/datafile-33-kB' -> 's3://s3cmd-test-bucket-18467/datafile-33-kB' (33792 bytes in 0.0 seconds, 1879.19 KB/s) [11 of 15]\nupload: '/mint/data/datafile-5-MB' -> 's3://s3cmd-test-bucket-18467/datafile-5-MB' (5242880 bytes in 0.1 seconds, 46.44 MB/s) [12 of 15]\nupload: '/mint/data/datafile-5243880-b' -> 's3://s3cmd-test-bucket-18467/datafile-5243880-b' (5243880 bytes in 0.1 seconds, 46.45 MB/s) [13 of 15]\nupload: '/mint/data/datafile-6-MB' -> 's3://s3cmd-test-bucket-18467/datafile-6-MB' (6291456 bytes in 0.1 seconds, 48.23 MB/s) [14 of 15]\nWARNING: Retrying failed request: /datafile-65-MB?uploadId=MDY3ODRkNjEtOWIyNi00MzdhLWIxMDItZmI4OTU5YmExZTQ1LjNhNzc4OTcwLTM5ZWUtNGJjMS05OTE1LWU1MThiYTFiNjgwMg (timed out)\nWARNING: Waiting 3 sec...\nERROR: S3 error: 404 (NoSuchUpload): The specified multipart upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed."
}
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-10 15:25 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-02-10 15:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-02-10 15:58 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#9506f694-bf5d-4078-a044-1d27807033c6) |
<a name="9506f694-bf5d-4078-a044-1d27807033c6"></a>
### 16584-2d3b8e8/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.4:32767
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 0e7eddb07a61:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 13 seconds
{
  "name": "mc",
  "duration": "63007",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-10236 --quiet --no-color mirror /mint/data myminio/mc-test-bucket-9088  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-9088/datafile-0-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-9088/datafile-1-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-9088/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-9088/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-9088/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-9088/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-9088/datafile-10-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-9088/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-9088/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-9088/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-9088/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-9088/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-9088/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-9088/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-9088/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Put \"http://15.15.15.4:32767/mc-test-bucket-9088/datafile-129-MB?partNumber=9&uploadId=ODY0YmRhODMtMjMyZi00M2YwLWJhNWUtZGUxZjA2Y2Y5ZjFkLjRmOWM3NTcwLTI5MmEtNDcwNC1iYjMzLTVlNzE5ZmViM2U5Nw\": write tcp 172.17.0.2:52110->15.15.15.4:32767: use of closed network connection\nTotal: 0 B, Transferred: 466.91 MiB, Speed: 7.44 MiB/s"
}
(7/14) Running minio-go tests ... done in 34 seconds
(8/14) Running minio-java tests ... done in 16 seconds
(9/14) Running minio-js tests ... done in 45 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 6 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-10 18:06 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#88ed9f18-533c-4a77-b4aa-a8766c890dc7) |
<a name="88ed9f18-533c-4a77-b4aa-a8766c890dc7"></a>
### 16584-9e830f3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.1:31702
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 7263b320eee8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 38 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 1 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 15 seconds
(8/14) Running minio-go tests ... done in 53 seconds
(9/14) Running minio-java tests ... FAILED in 1 minutes and 3 seconds
{
  "name": "minio-java",
  "function": "getBucketEncryption()",
  "duration": 59886,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketAlreadyOwnedByYou, message = Your previous request to create the named bucket succeeded and you already own it., bucketName = minio-java-test-2t4lb8t, objectName = null, resource = /minio-java-test-2t4lb8t, requestId = 1742886CC99825B2, hostId = 86d55b7d-a004-4162-afe6-67345a509a11)\nrequest={method=PUT, url=http://15.15.15.1:31702/minio-java-test-2t4lb8t, headers=Host: 15.15.15.1:31702\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.6\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20230210T175912Z\nAuthorization: ██\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 376\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Id-2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nX-Amz-Request-Id: 1742886CC99825B2\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Fri, 10 Feb 2023 18:00:12 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 48 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 39 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 3 minutes and 11 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-11 00:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8b25b275-b3a8-47f1-8d8f-3305ad169e34) |
| mint-fs.sh | :x: [more...](#87672808-6ede-49d3-9384-926c6fe5d3d2) |
| mint-erasure.sh | :x: [more...](#02e990e3-6ebf-4b16-8da6-51ad395cff28) |
| mint-dist-erasure.sh | :x: [more...](#7fb954cc-f37b-4d49-9dfe-ae60149f5b74) |
<a name="87672808-6ede-49d3-9384-926c6fe5d3d2"></a>
### 16584-085cfc5/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:30464
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 5f871765aefa:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 11 seconds
{
  "name": "mc",
  "duration": "10125",
  "function": "test_rb",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-17058 --quiet --no-color mb myminio/mc-test-bucket-21501-1  >>> \nmc: <ERROR> Unable to make bucket `myminio/mc-test-bucket-21501-1`. Put \"http://15.15.15.6:30464/mc-test-bucket-21501-1/\": dial tcp 15.15.15.6:30464: i/o timeout"
}
(7/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(8/14) Running minio-java tests ... done in 15 seconds
(9/14) Running minio-js tests ... done in 42 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 5 seconds
(11/14) Running s3cmd tests ... done in 12 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="7fb954cc-f37b-4d49-9dfe-ae60149f5b74"></a>
### 16584-085cfc5/mint-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:30085
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 18f0c79ba4d0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 minutes and 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... FAILED in 1 minutes and 6 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 62231.23,
  "error": "execution expired",
  "status": "FAIL"
}
(4/14) Running awscli tests ... done in 2 minutes and 12 seconds
(5/14) Running healthcheck tests ... done in 0 seconds
(6/14) Running mc tests ... done in 15 seconds
(7/14) Running minio-go tests ... done in 45 seconds
(8/14) Running minio-java tests ... done in 28 seconds
(9/14) Running minio-js tests ... done in 49 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 37 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 11 seconds

Executed 13 out of 14 tests successfully.
```
<a name="02e990e3-6ebf-4b16-8da6-51ad395cff28"></a>
### 16584-085cfc5/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.2:32144
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 03fc8f36828f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 20 seconds
(7/14) Running minio-go tests ... done in 2 minutes and 13 seconds
(8/14) Running minio-java tests ... done in 16 seconds
(9/14) Running minio-js tests ... done in 44 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 8 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 1 seconds

Executed 13 out of 14 tests successfully.
```
<a name="8b25b275-b3a8-47f1-8d8f-3305ad169e34"></a>
### 16584-085cfc5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:31549
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp b581f9ab78dd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... FAILED in 6 minutes and 0 seconds
{"name": "awscli", "duration": 304980, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://15.15.15.7:31549/awscli-mint-test-bucket-14349""}
(5/14) Running healthcheck tests ... done in 7 seconds
(6/14) Running mc tests ... done in 15 seconds
(7/14) Running minio-go tests ... done in 49 seconds
(8/14) Running minio-java tests ... done in 29 seconds
(9/14) Running minio-js tests ... done in 49 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 41 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 12 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-11 00:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-erasure.sh | :heavy_check_mark: |
| mint-dist-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-02-13 16:15 UTC, harshavardhana requested changes

2023-02-13 16:15 UTC, harshavardhana commented on cmd/kms-handlers.go
> +		status, err := GlobalKMS.Stat(ctx)
```suggestion
		status, err := GlobalKMS.Stat(ctx)
```

why do we need to do an extra network call here? isn't it easier to use something like `

```
GlobalKMS.IsLocal()
```

It is very easier

```
if GlobalKMS.IsLocal() {
       writeErrorResponseJSON(ctx, w, errorCodes.ToAPIErr(ErrKMSDefaultKeyAlreadyConfigured), r.URL)
       return
}

2023-02-13 16:15 UTC, harshavardhana commented on cmd/kms-handlers.go
> +		writeErrorResponseJSON(ctx, w, errorCodes.ToAPIErr(ErrKMSNotConfigured), r.URL)
Instead of this implement List() call to succeed for ENV Key, avoids this kind of superflous code.

2023-02-16 06:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#2d5d3592-1c48-4320-b32b-d9e4509d072e) |
<a name="2d5d3592-1c48-4320-b32b-d9e4509d072e"></a>
### 16584-200df0c/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:30952
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp d23cffaadc64:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 19 seconds
{
  "name": "mc",
  "duration": "122985",
  "function": "test_presigned_put_object",
  "status": "FAIL",
  "error": "unable to upload /mint/data/datafile-1-MB presigned put object url"
}
(7/14) Running minio-go tests ... done in 46 seconds
(8/14) Running minio-java tests ... done in 27 seconds
(9/14) Running minio-js tests ... done in 49 seconds
(10/14) Running minio-py tests ... done in 6 minutes and 41 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 3 seconds
(13/14) Running versioning tests ... done in 3 minutes and 4 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-16 07:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#c1523b5a-11ab-4c59-8f21-747d35d52426) |
<a name="c1523b5a-11ab-4c59-8f21-747d35d52426"></a>
### 16584-31036ba/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.4:30586
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 0f42f37dbeef:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 16 seconds
(8/14) Running minio-go tests ... done in 54 seconds
(9/14) Running minio-java tests ... done in 35 seconds
(10/14) Running minio-js tests ... done in 51 seconds
(11/14) Running minio-py tests ... FAILED in 1 minutes and 21 seconds
{
  "name": "minio-py:test_stat_object_version",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-4b29d5b0-2524-4795-b648-73aaceeb787b",
    "object_name": "823fe605-acd6-4f6a-ba8c-0eaee1683e3f-metadata",
    "length": 11534336,
    "data": "LimitedRandomReader(11 * MB)",
    "metadata": {
      "X-Amz-Meta-Testing": "value"
    },
    "content_type": "application/octet-stream"
  },
  "message": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 825, in test_stat_object_version\n    _test_stat_object(log_entry, sse, version_check=True)\n  File \"/mint/run/core/minio-py/tests.py\", line 794, in _test_stat_object\n    result = _CLIENT.put_object(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1766, in put_object\n    raise exc\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1725, in put_object\n    upload_id = self._create_multipart_upload(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1565, in _create_multipart_upload\n    response = self._execute(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 403, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 266, in _url_open\n    response = self._http.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
  "duration": 60272
}
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 5 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-16 07:33 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#c73670b1-09f2-4bcd-8059-d9e8980292e6) |
| mint-pools.sh | :x: [more...](#822615b0-d635-404b-935b-04e339e18687) |
<a name="c73670b1-09f2-4bcd-8059-d9e8980292e6"></a>
### 16584-d2b5bdd/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:31521
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2f3e16cff71e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... done in 35 seconds
(9/14) Running minio-java tests ... done in 18 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 25 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 6,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:71:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:166:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:90:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (internal/streams/readable.js:670:10) at endReadableNT (internal/streams/readable.js:1333:12) at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 7 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 28 seconds

Executed 13 out of 14 tests successfully.
```
<a name="822615b0-d635-404b-935b-04e339e18687"></a>
### 16584-d2b5bdd/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:30435
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 4c255fbdd590:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 54 seconds
(9/14) Running minio-java tests ... FAILED in 2 minutes and 9 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 120737,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-1jdpi98, objectName = null, resource = /minio-java-test-1jdpi98, requestId = 17443D5787393FE3, hostId = 54d26876-d7a6-4b99-aa22-4f68fd74daab)\nrequest={method=DELETE, url=http://15.15.15.6:30435/minio-java-test-1jdpi98, headers=Host: 15.15.15.6:30435\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.6\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20230216T072647Z\nAuthorization: ██\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 328\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Id-2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nX-Amz-Request-Id: 17443D5787393FE3\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Thu, 16 Feb 2023 07:26:47 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 50 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 43 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 32 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-16 11:06 UTC, klauspost reviewed
Some suggestions.

2023-02-16 11:06 UTC, klauspost commented on cmd/api-errors.go
> +		Description:    "Addition of new encryption key unsupported by KMS",
```suggestion
		Description:    "A default encryption already exists and cannot be changed on KMS",
```

2023-02-16 11:06 UTC, klauspost commented on cmd/api-errors.go
> +		HTTPStatusCode: http.StatusBadRequest,
```suggestion
		HTTPStatusCode: http.StatusConflict,
```
Maybe?

2023-02-16 11:06 UTC, klauspost commented on cmd/encryption-v1.go
> +	errKMSNotConfigured               = errors.New("KMS not configured for a server side encrypted object")
```suggestion
	errKMSNotConfigured               = errors.New("KMS not configured for a server side encrypted objects")
```

2023-02-16 11:06 UTC, klauspost commented on cmd/encryption-v1.go
> +	errKMSKeyNotFound                 = errors.New("Invalid KMS keyId")
```suggestion
	errKMSKeyNotFound                 = errors.New("Unknown KMS key ID")
```

2023-02-16 11:06 UTC, klauspost commented on cmd/encryption-v1.go
> +	errKMSDefaultKeyAlreadyConfigured = errors.New("Addition of new encryption key unsupported by KMS")
```suggestion
	errKMSDefaultKeyAlreadyConfigured = errors.New("A default encryption already exists on KMS")
```

2023-02-16 17:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#f08781fe-1a53-4f5a-a891-40ceee26c027) |
<a name="f08781fe-1a53-4f5a-a891-40ceee26c027"></a>
### 16584-452d4a2/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.3:32371
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp c889eab520be:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 17 seconds
{
  "name": "mc",
  "duration": "130385",
  "function": "test_presigned_put_object",
  "status": "FAIL",
  "error": "unable to upload /mint/data/datafile-1-MB presigned put object url"
}
(7/14) Running minio-go tests ... done in 1 minutes and 23 seconds
(8/14) Running minio-java tests ... done in 17 seconds
(9/14) Running minio-js tests ... done in 46 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 9 seconds
(11/14) Running s3cmd tests ... done in 17 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 3 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-16 17:56 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :x: [more...](#5cf8033c-1902-49a2-a857-bcbcccc81611) |
<a name="5cf8033c-1902-49a2-a857-bcbcccc81611"></a>
### 16584-a482ade/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:31805
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 1d4ea7f7d393:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-go tests ... done in 55 seconds
(9/14) Running minio-java tests ... done in 36 seconds
(10/14) Running minio-js tests ... done in 52 seconds
(11/14) Running minio-py tests ... FAILED in 1 minutes and 55 seconds
{
  "name": "minio-py:test_put_object",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-d478b6b1-16f0-4ac5-a2b0-985b7f610564",
    "object_name": "e73baae2-ca8b-400f-975c-8dff07529ac4-metadata",
    "length": 11534336,
    "data": "LimitedRandomReader(11 * MB)",
    "metadata": {
      "x-amz-meta-testing": "value",
      "test-key": "value2"
    },
    "content_type": "application/octet-stream"
  },
  "message": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 697, in test_put_object\n    _CLIENT.put_object(bucket_name, object_name + \"-metadata\", reader,\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1766, in put_object\n    raise exc\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1725, in put_object\n    upload_id = self._create_multipart_upload(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1565, in _create_multipart_upload\n    response = self._execute(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 403, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 266, in _url_open\n    response = self._http.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
  "duration": 112769
}
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 12 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-16 18:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#aa185a12-8d86-445b-b1f0-fdae778d4fb0) |
<a name="aa185a12-8d86-445b-b1f0-fdae778d4fb0"></a>
### 16584-0760130/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:32691
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp fdb8d886147f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... done in 34 seconds
(9/14) Running minio-java tests ... done in 16 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 15 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-d69c4202-be49-4f4d-96fb-52b13b7338e2, events: s3:ObjectCreated:*",
  "duration": 64040,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 8 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 15 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-16 18:52 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :x: [more...](#fa5be5ec-a2eb-4949-9e06-020ef2cb84af) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#73adb7ba-2e51-4899-8917-8c39bfcbabfd) |
| mint-pools.sh | :x: [more...](#cd0b9b97-c4ef-4433-bbc6-e064e1bd91f6) |
<a name="73adb7ba-2e51-4899-8917-8c39bfcbabfd"></a>
### 16584-c19ad60/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:30209
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2c05bbf34805:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 3 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 47 seconds
(9/14) Running minio-java tests ... done in 29 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 43 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 56473,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 40 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 18 seconds

Executed 13 out of 14 tests successfully.
```
<a name="fa5be5ec-a2eb-4949-9e06-020ef2cb84af"></a>
### 16584-c19ad60/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.5:32027
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 1bd8687dacc4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 4 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... done in 34 seconds
(9/14) Running minio-java tests ... FAILED in 6 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "composeObject()",
  "args": "[two multipart sources with offset and length]",
  "duration": 364333,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: timeout >>> [okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147), okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158), okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337), okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320), okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29), okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 47 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 8 seconds
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 15 seconds

Executed 13 out of 14 tests successfully.
```
<a name="cd0b9b97-c4ef-4433-bbc6-e064e1bd91f6"></a>
### 16584-c19ad60/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:31456
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 2cade46a0c0b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 3 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 20 seconds
(8/14) Running minio-go tests ... done in 57 seconds
(9/14) Running minio-java tests ... done in 37 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-fe0701a2-a754-4aa7-846c-b40f66d515c6, events: s3:ObjectCreated:*",
  "duration": 63751,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 52 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 5 seconds
(13/14) Running versioning tests ... done in 3 minutes and 7 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-16 19:09 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-02-16 19:28 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-02-17 09:49 UTC, harshavardhana requested changes

2023-02-17 09:49 UTC, harshavardhana commented on cmd/kms-handlers.go
> +		if GlobalKMS.IsLocal() {
```suggestion
	if GlobalKMS != nil && GlobalKMS.IsLocal() {
```

2023-02-17 09:49 UTC, harshavardhana commented on cmd/kms-handlers.go
> +		if GlobalKMS.IsLocal() {
```suggestion
	if GlobalKMS != nil && GlobalKMS.IsLocal() {
```

2023-02-17 09:49 UTC, harshavardhana commented on cmd/kms-handlers.go
> +			secretKey := GlobalKMS.ListLocal()
We could simply call this `List()` not sure why we need ListLocal() a List simply returns what is the default keyID.

2023-02-17 09:49 UTC, harshavardhana commented on cmd/kms-handlers.go
> +			secretKey := GlobalKMS.ListLocal()
this is not a secretKey since we use secretKey to designate `access credentials` - perhaps call this `kmsSecret` ?

2023-02-17 09:49 UTC, harshavardhana commented on cmd/kms-handlers.go
> +			writeErrorResponseJSON(ctx, w, errorCodes.ToAPIErr(ErrKMSNotConfigured), r.URL)
is this ever possible after `IsLocal()` is true?

2023-02-17 09:49 UTC, harshavardhana commented on internal/kms/kes.go
> +	return env.IsSet("MINIO_KMS_SECRET_KEY")
you can use `config.EnvKMSSecretKey` for this.

2023-02-17 09:49 UTC, harshavardhana commented on internal/kms/kes.go
> +	envKMSSecretKey := env.Get("MINIO_KMS_SECRET_KEY", "")
isn't this already parsed?

2023-02-17 17:03 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 16584-8c00133/gopath/src/github.com/minio
+ git -C 16584-8c00133/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 16584-8c00133/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 16584-8c00133/gopath/src/github.com/minio/minio fetch --quiet minio pull/16584/head:pr16584
+ git -C 16584-8c00133/gopath/src/github.com/minio/minio checkout --quiet pr16584
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/16584-8c00133/gopath
+ make -C 16584-8c00133/gopath/src/github.com/minio/minio --quiet
go: downloading cloud.google.com/go/storage v1.29.0
go: downloading github.com/cheggaaa/pb v1.0.29
go: downloading github.com/miekg/dns v1.1.50
go: downloading go.etcd.io/etcd/client/v3 v3.5.7
go: downloading go.etcd.io/etcd/api/v3 v3.5.7
go: downloading github.com/minio/madmin-go/v2 v2.0.11
go: downloading github.com/minio/highwayhash v1.0.2
go: downloading github.com/Azure/azure-storage-blob-go v0.15.0
go: downloading github.com/minio/kes-go v0.1.0
go: downloading github.com/coreos/go-oidc v2.2.1+incompatible
go: downloading github.com/bcicen/jstream v1.0.1
go: downloading github.com/minio/minio-go/v7 v7.0.47
go: downloading github.com/minio/mux v1.9.0
go: downloading github.com/cespare/xxhash/v2 v2.2.0
go: downloading github.com/bits-and-blooms/bloom/v3 v3.3.1
go: downloading github.com/dchest/siphash v1.2.3
go: downloading github.com/minio/pkg v1.6.1
go: downloading github.com/djherbis/atime v1.1.0
go: downloading github.com/felixge/fgprof v0.9.3
go: downloading github.com/fatih/color v1.14.1
go: downloading github.com/minio/selfupdate v0.6.0
go: downloading github.com/dustin/go-humanize v1.0.1
go: downloading github.com/minio/zipindex v0.3.0
go: downloading github.com/go-openapi/loads v0.21.2
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/minio/xxml v0.0.3
go: downloading github.com/cosnicolaou/pbzip2 v1.0.1
go: downloading github.com/minio/sio v0.3.0
go: downloading github.com/klauspost/readahead v1.4.0
go: downloading github.com/klauspost/pgzip v1.2.5
go: downloading github.com/philhofer/fwd v1.1.2
go: downloading github.com/pierrec/lz4 v2.6.1+incompatible
go: downloading github.com/klauspost/compress v1.15.15
go: downloading github.com/klauspost/reedsolomon v1.11.7
go: downloading github.com/prometheus/procfs v0.9.0
go: downloading github.com/prometheus/common v0.39.0
go: downloading github.com/prometheus/client_golang v1.14.0
go: downloading github.com/rs/cors v1.8.3
go: downloading github.com/rs/dnscache v0.0.0-20211102005908-e0241e321417
go: downloading github.com/golang-jwt/jwt/v4 v4.4.3
go: downloading github.com/tidwall/gjson v1.14.4
go: downloading github.com/inconshreveable/mousetrap v1.1.0
go: downloading github.com/minio/console v0.23.1
go: downloading github.com/tinylib/msgp v1.1.8
go: downloading github.com/hashicorp/golang-lru v0.5.4
go: downloading github.com/json-iterator/go v1.1.12
go: downloading github.com/shirou/gopsutil/v3 v3.23.1
go: downloading github.com/zeebo/xxh3 v1.0.2
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/klauspost/filepathx v1.1.1
go: downloading github.com/prometheus/client_model v0.3.0
go: downloading github.com/lithammer/shortuuid/v4 v4.0.0
go: downloading github.com/secure-io/sio-go v0.3.1
go: downloading github.com/minio/cli v1.24.2
go: downloading github.com/minio/dperf v0.4.2
go: downloading go.uber.org/atomic v1.10.0
go: downloading golang.org/x/crypto v0.5.0
go: downloading golang.org/x/oauth2 v0.4.0
go: downloading golang.org/x/sys v0.4.0
go: downloading google.golang.org/api v0.109.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading golang.org/x/time v0.3.0
go: downloading github.com/coredns/coredns v1.10.0
go: downloading github.com/go-ldap/ldap/v3 v3.4.4
go: downloading github.com/beevik/ntp v0.3.0
go: downloading github.com/minio/sha256-simd v1.0.0
go: downloading go.uber.org/zap v1.24.0
go: downloading github.com/buger/jsonparser v1.1.1
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/minio/simdjson-go v0.4.2
go: downloading github.com/Shopify/sarama v1.38.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.4.2
go: downloading github.com/elastic/go-elasticsearch/v7 v7.17.7
go: downloading github.com/go-sql-driver/mysql v1.7.0
go: downloading github.com/gomodule/redigo v1.8.9
go: downloading github.com/lib/pq v1.10.7
go: downloading github.com/nats-io/nats.go v1.23.0
go: downloading github.com/nats-io/stan.go v0.10.4
go: downloading github.com/nsqio/go-nsq v1.1.0
go: downloading github.com/pkg/errors v0.9.1
go: downloading github.com/rabbitmq/amqp091-go v1.6.1
go: downloading github.com/xdg/scram v1.0.5
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.17
go: downloading github.com/pquerna/cachecontrol v0.1.0
go: downloading gopkg.in/square/go-jose.v2 v2.6.0
go: downloading golang.org/x/sync v0.1.0
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/bits-and-blooms/bitset v1.5.0
go: downloading github.com/minio/csvparser v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.14
go: downloading github.com/fraugster/parquet-go v0.12.0
go: downloading github.com/tidwall/match v1.1.1
go: downloading github.com/tidwall/pretty v1.2.1
go: downloading github.com/alecthomas/participle v0.7.1
go: downloading aead.dev/mem v0.2.0
go: downloading aead.dev/minisign v0.2.0
go: downloading github.com/gogo/protobuf v1.3.2
go: downloading golang.org/x/net v0.5.0
go: downloading github.com/google/pprof v0.0.0-20230131232505-5a9e8f65f08f
go: downloading github.com/klauspost/cpuid/v2 v2.2.3
go: downloading github.com/Azure/go-ntlmssp v0.0.0-20221128193559-754e69321358
go: downloading github.com/go-asn1-ber/asn1-ber v1.5.4
go: downloading go.etcd.io/etcd/client/pkg/v3 v3.5.7
go: downloading google.golang.org/grpc v1.52.3
go: downloading github.com/golang/snappy v0.0.4
go: downloading github.com/xdg/stringprep v1.0.3
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.4
go: downloading google.golang.org/genproto v0.0.0-20230202175211-008b39050e57
go: downloading github.com/coreos/go-semver v0.3.1
go: downloading github.com/Azure/azure-pipeline-go v0.2.3
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.2
go: downloading github.com/rivo/uniseg v0.4.3
go: downloading github.com/go-openapi/analysis v0.21.4
go: downloading github.com/go-openapi/spec v0.20.8
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading github.com/lestrrat-go/jwx v1.2.25
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/montanaflynn/stats v0.7.0
go: downloading github.com/rjeczalik/notify v0.9.3
go: downloading github.com/gorilla/websocket v1.5.0
go: downloading github.com/minio/md5-simd v1.1.2
go: downloading github.com/rs/xid v1.4.0
go: downloading gopkg.in/ini.v1 v1.67.0
go: downloading github.com/beorn7/perks v1.0.1
go: downloading google.golang.org/protobuf v1.28.1
go: downloading github.com/mattn/go-ieproxy v0.0.1
go: downloading cloud.google.com/go v0.109.0
go: downloading golang.org/x/text v0.6.0
go: downloading github.com/tklauser/go-sysconf v0.3.11
go: downloading github.com/coreos/go-systemd/v22 v22.5.0
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading go.uber.org/multierr v1.9.0
go: downloading github.com/apache/thrift v0.17.0
go: downloading github.com/nats-io/nkeys v0.3.0
go: downloading github.com/tklauser/numcpus v0.6.0
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20230111030713-bf00bc1b [...]

2023-02-17 18:11 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#3af393de-e933-4072-99c9-c8afb6ba7b1e) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#7646ec92-9d52-46c9-99d3-9effa3be8630) |
<a name="3af393de-e933-4072-99c9-c8afb6ba7b1e"></a>
### 16584-5114d75/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.8:31812
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 76cf4889a9c1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 56 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... done in 35 seconds
(9/14) Running minio-java tests ... done in 17 seconds
(10/14) Running minio-js tests ... done in 46 seconds
(11/14) Running minio-py tests ... FAILED in 1 minutes and 8 seconds
{
  "name": "minio-py:test_stat_object",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-4237759b-9165-4442-b379-1b9874a5c466",
    "object_name": "304317fb-bf24-4db2-9326-d579172264a6-metadata",
    "length": 11534336,
    "data": "LimitedRandomReader(11 * MB)",
    "metadata": {
      "X-Amz-Meta-Testing": "value"
    },
    "content_type": "application/octet-stream"
  },
  "message": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 820, in test_stat_object\n    _test_stat_object(log_entry, sse)\n  File \"/mint/run/core/minio-py/tests.py\", line 794, in _test_stat_object\n    result = _CLIENT.put_object(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1766, in put_object\n    raise exc\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1725, in put_object\n    upload_id = self._create_multipart_upload(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1565, in _create_multipart_upload\n    response = self._execute(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 403, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 266, in _url_open\n    response = self._http.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
  "duration": 58368
}
(11/14) Running s3cmd tests ... done in 15 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
<a name="7646ec92-9d52-46c9-99d3-9effa3be8630"></a>
### 16584-5114d75/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:30566
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 87a489742f0a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 20 seconds
(8/14) Running minio-go tests ... done in 56 seconds
(9/14) Running minio-java tests ... done in 29 seconds
(10/14) Running minio-js tests ... FAILED in 47 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-e25c73a4-3cd7-4759-9a83-41f7d38780da, events: s3:ObjectCreated:*",
  "duration": 36652,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 42 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 30 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-17 18:33 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2023-02-22 00:28 UTC, kannappanr approved these changes

2023-02-22 01:42 UTC, harshavardhana approved these changes

2023-02-22 01:43 UTC, merged