fix: avoid printing certain errors under few locations
minio/minio pull request #16631
Opened 2023-02-16 05:50 UTC by harshavardhana

## Description
fix: avoid printing certain errors under few locations

## Motivation and Context
- listPathRaw() apparently was printing context.Canceled as error
- kms.Metrics() was printing "unsupported" instead of returning NotImplemented

## How to test this PR?
Not easy to test. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-02-16 06:17 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#90f26a1e-9fd7-4312-a7fc-08cbbeb740b9) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#801c033e-8573-4c9c-a01a-9111154ca4aa) |
<a name="90f26a1e-9fd7-4312-a7fc-08cbbeb740b9"></a>
### 16631-aa7f727/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.4:31578
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 7757861c7f82:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 1 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 13 seconds
(8/14) Running minio-go tests ... done in 46 seconds
(9/14) Running minio-java tests ... FAILED in 2 minutes and 3 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 118334,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-1cf6ak6, objectName = null, resource = /minio-java-test-1cf6ak6, requestId = 1744393FEA56B7ED, hostId = a69b102b-9078-48b2-ab82-327dc09851c8)\nrequest={method=DELETE, url=http://15.15.15.4:31578/minio-java-test-1cf6ak6, headers=Host: 15.15.15.4:31578\nAccept-Encoding: identity\nUser-Agent: MinIO (Linux; amd64) minio-java/8.4.6\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20230216T061147Z\nAuthorization: ██\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 328\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO\nStrict-Transport-Security: max-age=31536000; includeSubDomains\nVary: Origin\nVary: Accept-Encoding\nX-Amz-Id-2: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nX-Amz-Request-Id: 1744393FEA56B7ED\nX-Content-Type-Options: nosniff\nX-Xss-Protection: 1; mode=block\nDate: Thu, 16 Feb 2023 06:11:47 GMT\n}\n >>> [io.minio.S3Base$1.onResponse(S3Base.java:690), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(9/14) Running minio-js tests ... done in 44 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 6 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 14 seconds

Executed 13 out of 14 tests successfully.
```
<a name="801c033e-8573-4c9c-a01a-9111154ca4aa"></a>
### 16631-aa7f727/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.2:32461
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp d4f73d99bb75:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 1 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 19 seconds
(8/14) Running minio-go tests ... FAILED in 1 minutes and 50 seconds
{
  "args": {
    "bucketName": "minio-go-test-5l2h0cffujmbjq2w",
    "objectName": "2n3usnekteiv9fmn96wqx0yom4661t"
  },
  "duration": 61930,
  "error": "read tcp 172.17.0.3:39504->15.15.15.2:32461: read: connection reset by peer",
  "function": "GetObject(bucketName, objectName)",
  "message": "ReadAt failed",
  "name": "minio-go: testSSES3EncryptedGetObjectReadAtFunctional",
  "status": "FAIL"
}
(8/14) Running minio-java tests ... done in 31 seconds
(9/14) Running minio-js tests ... done in 48 seconds
(10/14) Running minio-py tests ... done in 1 minutes and 31 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 17 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-16 11:00 UTC, klauspost requested changes

2023-02-16 11:00 UTC, klauspost commented on cmd/metacache-set.go
> +				werr.Error() != context.Canceled.Error() {
```suggestion
				werr.Error() != context.Canceled.Error() &&
				!errors.Is(werr, context.Canceled) {
```

Otherwise we start printing wrapped context canceled arrors.

2023-02-16 11:00 UTC, klauspost commented on internal/kms/single-key.go
> +	return kes.Metric{}, errors.New("kms: metrics is not supported")
```suggestion
	return kes.Metric{}, errors.New("kms: metrics not supported")
```
"Metrics" is plural -> "are"... but let's just sidestep it :)

2023-02-16 14:27 UTC, harshavardhana commented on cmd/metacache-set.go
> +				werr.Error() != context.Canceled.Error() {
It is changed on purpose because errors.Is() didn't ignore it @klauspost - I wouldn't have changed it otherwise

2023-02-16 16:48 UTC, harshavardhana commented on cmd/metacache-set.go
> +				werr.Error() != context.Canceled.Error() {
PTAL @klauspost it may be that something is changing underneath the context.Canceled error.

2023-02-17 05:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compress-encrypt-dist-erasure.sh | :heavy_check_mark: |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#c49e2f67-50c8-4c32-ba6d-e59c45b578b4) |
<a name="c49e2f67-50c8-4c32-ba6d-e59c45b578b4"></a>
### 16631-036616f/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.4:32359
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 3a2354edaffd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... done in 32 seconds
(9/14) Running minio-java tests ... done in 16 seconds
(10/14) Running minio-js tests ... FAILED in 2 minutes and 8 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-5727f588-0e84-477a-b829-6ba8c7e4e176, events: s3:ObjectCreated:*",
  "duration": 117681,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 7 seconds
(11/14) Running s3cmd tests ... done in 14 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 28 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-17 08:10 UTC, harshavardhana commented on cmd/metacache-set.go
> +				werr.Error() != context.Canceled.Error() {
I actually completely removed this log since it's not useful.

2023-02-17 09:03 UTC, klauspost approved these changes
👍🏼

2023-02-17 09:40 UTC, merged