(#16606) add native vrf support
minio/minio pull request #16659
Opened 2023-02-20 08:18 UTC by 4xoc

## Description
This PR implements the suggested solution for #16606 to implement native VRF support for Linux.

## Motivation and Context
See #16606 for details. tldr: s3 api endpoints should run natively in a specified VRF using a new command line flag.

## How to test this PR?
Testing is a bit tricky because it requires a test system with an existing vrf in place. This practically eliminates testing in containers and otherwise requires set up of such vrf using root permissions (which imho shouldn't be done in scripts without testers knowledge). I'm very much open for suggestions on this.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [X] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-02-20 08:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-erasure.sh | :heavy_check_mark: |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#e1ac1fb0-548b-475c-b749-45d3b71e359c) |
| mint-pools.sh | :x: [more...](#4513d094-9a97-4111-a25a-ceab9e9ed09f) |
<a name="4513d094-9a97-4111-a25a-ceab9e9ed09f"></a>
### 16659-972e25c/mint-pools.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:30815
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp 40ad4a19f963:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 3 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 26 seconds
{
  "name": "mc",
  "duration": "14168",
  "function": "test_copy_object_preserve_filesystem_attr",
  "status": "FAIL",
  "error": "unable to put object with file system attribute"
}
(7/14) Running minio-go tests ... done in 58 seconds
(8/14) Running minio-java tests ... FAILED in 5 minutes and 25 seconds
{
  "name": "minio-java",
  "function": "listObjects()",
  "args": "[bucket, prefix, recursive, 1050 objects]",
  "duration": 316011,
  "status": "FAIL",
  "error": "java.net.SocketTimeoutException: timeout >>> [okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:147), okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:158), okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:337), okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427), okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320), okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29), okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178), okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109), okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201), okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517), java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128), java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628), java.base/java.lang.Thread.run(Thread.java:829)]"
}
(8/14) Running minio-js tests ... done in 1 minutes and 58 seconds
(9/14) Running minio-py tests ... done in 1 minutes and 54 seconds
(10/14) Running s3cmd tests ... done in 16 seconds
(11/14) Running s3select tests ... done in 4 seconds
(12/14) Running versioning tests ... done in 3 minutes and 19 seconds

Executed 12 out of 14 tests successfully.
```
<a name="e1ac1fb0-548b-475c-b749-45d3b71e359c"></a>
### 16659-972e25c/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:31076
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp c257704b62dd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 7 seconds
(5/14) Running awscli tests ... done in 3 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 19 seconds
(8/14) Running minio-go tests ... done in 49 seconds
(9/14) Running minio-java tests ... done in 28 seconds
(10/14) Running minio-js tests ... FAILED in 48 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-8a277bbb-5e56-4640-97a8-3a95c4084f61, events: s3:ObjectCreated:*",
  "duration": 36802,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 1 minutes and 42 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 12 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-02-23 15:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-pools.sh | :heavy_check_mark: |
| mint-erasure.sh | :x: [more...](#c00e225d-8a2e-4d47-9b27-4eea740c0364) |
| mint-compress-encrypt-dist-erasure.sh | :x: [more...](#bea825e9-2e5c-48f1-9b47-41a5227f2743) |
<a name="c00e225d-8a2e-4d47-9b27-4eea740c0364"></a>
### 16659-df4f173/mint-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.6:31583
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp eca82ef95eb4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 1 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 14 seconds
(8/14) Running minio-go tests ... done in 34 seconds
(9/14) Running minio-java tests ... done in 18 seconds
(10/14) Running minio-js tests ... done in 46 seconds
(11/14) Running minio-py tests ... FAILED in 1 minutes and 2 seconds
{
  "name": "minio-py:test_put_object",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-92c471cb-4893-4b0d-a2e2-640c588568d6",
    "object_name": "17a4f19b-5414-4b40-83b0-9063bfba1332-metadata",
    "length": 11534336,
    "data": "LimitedRandomReader(11 * MB)",
    "metadata": {
      "x-amz-meta-testing": "value",
      "test-key": "value2"
    },
    "content_type": "application/octet-stream"
  },
  "message": "('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 126, in _call_test\n    func(log_entry, *args, **kwargs)\n  File \"/mint/run/core/minio-py/tests.py\", line 697, in test_put_object\n    _CLIENT.put_object(bucket_name, object_name + \"-metadata\", reader,\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1766, in put_object\n    raise exc\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1725, in put_object\n    upload_id = self._create_multipart_upload(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 1565, in _create_multipart_upload\n    response = self._execute(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 403, in _execute\n    return self._url_open(\n  File \"/usr/local/lib/python3.8/dist-packages/minio/api.py\", line 266, in _url_open\n    response = self._http.urlopen(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py\", line 376, in urlopen\n    response = conn.urlopen(method, u.request_uri, **kw)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 787, in urlopen\n    retries = retries.increment(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py\", line 550, in increment\n    raise six.reraise(type(error), error, _stacktrace)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/packages/six.py\", line 769, in reraise\n    raise value.with_traceback(tb)\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 703, in urlopen\n    httplib_response = self._make_request(\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 449, in _make_request\n    six.raise_from(e, None)\n  File \"<string>\", line 3, in raise_from\n  File \"/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py\", line 444, in _make_request\n    httplib_response = conn.getresponse()\n  File \"/usr/lib/python3.8/http/client.py\", line 1348, in getresponse\n    response.begin()\n  File \"/usr/lib/python3.8/http/client.py\", line 316, in begin\n    version, status, reason = self._read_status()\n  File \"/usr/lib/python3.8/http/client.py\", line 277, in _read_status\n    line = str(self.fp.readline(_MAXLINE + 1), \"iso-8859-1\")\n  File \"/usr/lib/python3.8/socket.py\", line 669, in readinto\n    return self._sock.recv_into(b)\nurllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))\n",
  "duration": 60528
}
(11/14) Running s3cmd tests ... done in 19 seconds
(12/14) Running s3select tests ... done in 2 seconds
(13/14) Running versioning tests ... done in 3 minutes and 2 seconds

Executed 13 out of 14 tests successfully.
```
<a name="bea825e9-2e5c-48f1-9b47-41a5227f2743"></a>
### 16659-df4f173/mint-compress-encrypt-dist-erasure.sh.log:
```
Running with
SERVER_ENDPOINT:      15.15.15.7:31084
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
RUN_ON_FAIL:          0

To get logs, run 'docker cp d7d8e884973e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 9 seconds
(5/14) Running awscli tests ... done in 1 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 17 seconds
(8/14) Running minio-go tests ... done in 47 seconds
(9/14) Running minio-java tests ... done in 30 seconds
(10/14) Running minio-js tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "minio-js",
  "function": "listenBucketNotification(bucketName, prefix, suffix, events)",
  "args": "bucketName:minio-js-test-7828406b-905c-4bce-8902-6070ef214b8f, events: s3:ObjectCreated:*",
  "duration": 64493,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:209:20)"
}
(10/14) Running minio-py tests ... done in 2 minutes and 3 seconds
(11/14) Running s3cmd tests ... done in 16 seconds
(12/14) Running s3select tests ... done in 4 seconds
(13/14) Running versioning tests ... done in 3 minutes and 11 seconds

Executed 13 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2023-04-15 15:11 UTC, harshavardhana commented
@4xoc isn't binding to the device possible via choosing the right network? 

```
--address "VRF-IP:<PORT>"
```

Then detect if the IP belongs to a VRF device via `net.Interfaces()`, then subsequently use this to detect if we need to enable `SOLBINDEVICE`. 

I am not sure why would we need an explicit device name as input.

2023-04-17 14:08 UTC, 4xoc commented
VRFs allow you to bind to same IP already in use by another VRF. Therefore an implicit selection of VRF could result in the selection of the wrong VRF. Additionally, having a quick look through the net documentation, there's nothing to identify the VRF an interface may be part of.

2023-04-17 16:36 UTC, harshavardhana commented
Let me discuss this with others if this is how we want to do it, I shall get back.

2023-04-19 07:16 UTC, harshavardhana requested changes

2023-04-19 07:16 UTC, harshavardhana commented on cmd/server-main.go
> +	xhttp.SetVRFDeviceName(ctx.String("vrf-device"))
You should change this to use the same pattern as `.UseHandler()`  change it to `UseVRFDeviceName(ctx.String("vrf-device"))` 

and this information must be stored in the `httpServer` struct instead of a global value.

2023-04-19 07:16 UTC, harshavardhana commented on cmd/server-main.go
> +		Name:   "vrf-device",
we do not need this to be `vrf` only lets make this `--interface` instead @4xoc

2023-04-19 07:16 UTC, harshavardhana commented on cmd/server-main.go
> +		Usage:  "bind to a specific vrf device name (Linux only)",
```suggestion
		Usage:  "bind to a specific interface",
```

2023-04-19 07:16 UTC, harshavardhana commented on cmd/server-main.go
> +	logger.FatalIf(checkPortAvailability(globalMinioHost, globalMinioPort, ctx.String("vrf-device")), "Unable to start the server")
```suggestion
	logger.FatalIf(checkPortAvailability(globalMinioHost, globalMinioPort, ctx.String("interface")), "Unable to start the server")
```

2023-04-19 07:16 UTC, harshavardhana commented on internal/http/dial_linux.go
> +			if !strings.HasPrefix(address, "127.") &&
why do we need to filter on `address` for localhosts?

2023-04-19 07:16 UTC, harshavardhana commented on cmd/net_linux.go
> +// Copyright (c) 2015-2021 MinIO, Inc.
```suggestion
// Copyright (c) 2015-2023 MinIO, Inc.
```

2023-04-19 07:16 UTC, harshavardhana commented on cmd/net_linux.go
> +	return l.Close()
It may require refactor of this code as well. Do you want me to implement this instead? as this looks like might be easier if done by us.

2023-04-21 13:34 UTC, 4xoc commented on internal/http/dial_linux.go
> +			if !strings.HasPrefix(address, "127.") &&
This is needed to not break console access. Somewhere minio always binds explicitly to localhost for console access. To keep compatibility I decided to keep localhost in the default vrf and filter here. It also removes the need to update mc or other tools to support vrf only for talking to the console.

2023-04-21 13:34 UTC, 4xoc commented on cmd/net_linux.go
> +	return l.Close()
I'm very happy if you can handle the refactor. Honestly I'm not too familiar with the code base.

2023-04-26 08:07 UTC, 4xoc commented on cmd/server-main.go
> +	xhttp.SetVRFDeviceName(ctx.String("vrf-device"))
The reason the information is a global is because the https://pkg.go.dev/net#Dialer expects a specific function signature for `Control` that doesn't allow for additional arguments.  The only way I can think of would be appending the details to either `network` or `address` like `2001:db8::1%eth0` and then split that information off. Not sure that's any better than a global value. Any ideas?

2023-04-30 22:43 UTC, harshavardhana commented
PTAL at #17108 @4xoc closing this PR.

2023-04-30 22:43 UTC, closed without merging