replication: perform bucket resync in parallel
minio/minio pull request #16707
Opened 2023-02-24 20:20 UTC by poornas

Default number of parallel resync operations for a bucket to 10 to speed up resync.

## Description

## Motivation and Context
speed up resync operation

## How to test this PR?
perform `mc replicate resync` on a replicated bucket after removing all contents of target bucket ( in 1-way replication)
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-04-03 15:12 UTC, harshavardhana requested changes

2023-04-03 15:12 UTC, harshavardhana commented on cmd/bucket-replication.go
> +	resyncWorkerCnt        = 50 // limit of number of bucket resyncs is progress at any given time
We can limit it to 10 so in total it's 10*10 = 100

2023-04-07 05:43 UTC, harshavardhana approved these changes

2023-04-12 18:35 UTC, vadmeste approved these changes
LGTM

2023-04-13 21:41 UTC, merged