Allow setting sync mode for site replication
minio/minio pull request #16876
Opened 2023-03-22 19:31 UTC by poornas

## Description

## Motivation and Context
Allow enabling/disabling sync replication to a peer site

## How to test this PR?
with companion mc PR - `mc admin replicate update --deployment-id <remote-depl-id> --sync enable|disable alias`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-03-22 19:39 UTC, harshavardhana requested changes

2023-03-22 19:39 UTC, harshavardhana commented on cmd/site-replication.go
> +				if peer.Endpoint == "" {
```suggestion
				if peer.Endpoint == "" {
```

when is this expected to happen? can you add a comment

2023-03-22 21:28 UTC, poornas commented on cmd/site-replication.go
> +				if peer.Endpoint == "" {
added a comment - `mc admin replicate update` can choose to update endpoint or sync/async mode or both.

2023-03-22 21:37 UTC, harshavardhana commented
@poornas use the `replace` directive to let the build succeed otherwise we can't tell if CI/CD will run or not. 

Once the `madmin-go` changes get merged you can remove the replace directives. 

replace directives with direct link to your fork and branch is better than just doing `../madmin-go`

2023-03-24 21:40 UTC, harshavardhana approved these changes

2023-03-24 21:41 UTC, merged