batch jobs: add support to replicate from remote to local cluster
minio/minio pull request #16922
Opened 2023-03-30 00:35 UTC by poornas

between 2 minio instances

## Description

## Motivation and Context
This option may be useful when remote cluster is on older release that does not support batch jobs yet

## How to test this PR?
```
replicate:
  apiVersion: v1
  # source of the objects to be replicated
  source:
    type: minio # valid values are "minio"
    bucket: bucket
    prefix:  # 'PREFIX' is optional
    # NOTE: if source is remote then target must be "local"
    endpoint: http://localhost:9004
    credentials:
      accessKey: minio
      secretKey: minio123
  #  #   sessionToken: SESSION-TOKEN # Optional only available when rotating credentials are used

  # target where the objects must be replicated
  target:
    type: minio # valid values are "minio"
    bucket: bucketa
    prefix: xxx # 'PREFIX' is optional
    # NOTE: if target is remote then source must be "local"
    # endpoint: http://localhost:9004
    # credentials:
    #   accessKey: minio
    #   secretKey: minio123
    # #   sessionToken: SESSION-TOKEN # Optional only available when rotating credentials are used
...
```

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-03-30 07:15 UTC, harshavardhana requested changes
Rest if the changes look good

2023-03-30 07:15 UTC, harshavardhana commented on cmd/batch-handlers.go
> +					if err := job.Replicate.startReplFromSource(job.ctx, j.objLayer, *job); err != nil {
```suggestion
					if err := job.Replicate.StartFromSource(job.ctx, j.objLayer, *job); err != nil {
```

2023-03-30 07:15 UTC, harshavardhana commented on cmd/batch-handlers.go
> +					if err := job.Replicate.startReplFromSource(job.ctx, j.objLayer, *job); err != nil {
Replicate is already the parent variable.

2023-03-30 07:15 UTC, harshavardhana commented on cmd/batch-handlers.go
> +				aerr := c.AbortMultipartUpload(ctx, tgtBucket, tgtObject, res.UploadID)
should the multipart abort be local not remote? @poornas

2023-03-30 18:56 UTC, harshavardhana approved these changes

2023-03-31 16:39 UTC, harshavardhana commented
Is the source type always MinIO currently?

2023-03-31 16:40 UTC, poornas commented
> Is the source type always MinIO currently?

yes

2023-03-31 17:48 UTC, merged