Reorganization and Migration of README and internal docs
minio/minio pull request #16933
Opened 2023-03-30 22:19 UTC by ravindk89

## Description

As part of internal discussions, we want to do two big things:

1) Simplify the README and guide users to our Documentation, which is far more in-depth and has better overall coverage
2) Move the `/docs` folder to an internal repository to be a resource for engineers, as the existing content is already generally better suited for ongoing development of MinIO

## Motivation and Context

The `/docs` folder has been engineer-maintained since MinIO's inception. However, it's not a priority for maintenance, cleanups, or updates - it's entirely driven by whether or not an engineer has the time and resources to make meaningful updates.

Furthermore, some content is designed for an audience that is already very familiar with MinIO and S3. This leads to some friction where users turn to the Github docs first, and the web docs second.

By moving the `/docs` folder to an internal repository, we can continue using it as a knowledge base for guiding ongoing development and engineering while keeping a clean and simple README for getting users to the most basic form of usage.

## How to test this PR?

The big test to come will be whether or not to submodule out the internal docs directory.
If we go in that direction, I'll update this part of the PR with instructions on how to init and update a submodule, and push updates and commits as part of a submodule.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [X] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-03-31 17:47 UTC, djwfyi requested changes
I think this is a good restructuring of this page.
I think the docs links can use some headings to help with scannability.

We should work on the recommendation for upgrading. Is it within 6 months? Or is it "at your convenience to take advantage of features and other updates"? We offer both at the moment in this doc.

2023-03-31 17:47 UTC, djwfyi commented on README.md
> +The fastest way to start experimenting with MinIO is to run it as a container on local machine.
> ... on **a** local machine.

2023-03-31 17:47 UTC, djwfyi commented on README.md
> +For more complete documentation on installing and deploying MinIO, see the following:
I'd add an h2 just above this:

> `## Official Documentation`

> `### Production Deployments'

   Links to prod quickstarts

> `### Local Testing Deployments`

   Links to OS quickstarts.

2023-03-31 17:47 UTC, djwfyi commented on README.md
> +Community users should follow within 6 months of the latest stable version of MinIO for best results.
Awkward sentence. Maybe;

> MinIO recommends that Community users alway use the latest version of MinIO for access to the latest features, performance enhancements, and security improvements. As a best practice, Community users should use a release within six months of the latest stable version of MinIO for best results.

2023-03-31 17:47 UTC, djwfyi commented on README.md
> +| Always test upgrades in a lower environment (DEV, QA, UAT) before applying to production. Always read the MinIO release notes before performing any upgrade. Performing blind upgrades in production
I'd make "release notes" a link to https://github.com/minio/minio/releases.

2023-03-31 17:47 UTC, djwfyi commented on README.md
> +Community users can receive free best-effort assistance through the [MinIO Community Slack]() or the MinIO Github through [Issues]() or [Discussions]().
Missing the URLs for these three links.

https://slack.min.io
https://github.com/minio/minio/issues
https://github.com/minio/minio/discussions

2023-03-31 17:47 UTC, djwfyi commented on README.md
> +| Always test upgrades in a lower environment (DEV, QA, UAT) before applying to production. Always read the MinIO release notes before performing any upgrade. Performing blind upgrades in production
The second sentence here may conflict with my recommendation above on ln 126.

2023-03-31 17:47 UTC, djwfyi commented on README.md
> +Community users should follow within 6 months of the latest stable version of MinIO for best results.
These may conflict with the second sentence on ln 140.

2023-03-31 17:47 UTC, djwfyi commented on README.md
> +For more complete documentation on installing and deploying MinIO, see the following:
Might also consider moving all of these links to the bottom with the Explore Further links.
Though I think we need _some_ link to docs site(s) close to the top of this.

2023-04-11 19:33 UTC, harshavardhana commented
@ravindk89 I do not think we are ready for this yet, there are many things that we need from `docs/` folder that are not present in the newer docs.

We should also keep some of these developer-centric docs as well, with code and examples.

2023-04-11 20:13 UTC, ravindk89 commented
@harshavardhana @klauspost what about a middle-point:

- We revise the README.md as suggested
- We cull those sections which have been migrated, linking to the appropriate docs

For developer-centric docs, we could keep those in the private repository and then submodule it here - or keep it entirely public. @abperiasamy for additional insight.

2023-04-12 08:57 UTC, klauspost commented
@ravindk89 

> For developer-centric docs, we could keep those in the private repository and then submodule it here - or keep it entirely public.

1. We are OSS. Keeping developer information private is pointless at best. 
2. Implementation specific extensions should be fully public - otherwise why should we have them.
3. Git Submodules are a nightmare.

2023-06-06 13:52 UTC, harshavardhana commented
I will close this for now, as we are not there yet and we need some of the markdowns in the docs/ folder

2023-06-06 13:52 UTC, closed without merging