add: isMaxPartID(xhttp.PartNumber) Error
minio/minio pull request #17015
Opened 2023-04-12 03:43 UTC by jiuker

## Description

```go
	partIDString := r.Form.Get(xhttp.PartNumber)

	partID, err := strconv.Atoi(partIDString)
	if err != nil {
		writeErrorResponse(ctx, w, errorCodes.ToAPIErr(ErrInvalidPart), r.URL)
		return
	}

	// check partID with maximum part ID for multipart objects
	if isMaxPartID(partID) {
		writeErrorResponse(ctx, w, errorCodes.ToAPIErr(ErrInvalidMaxParts), r.URL)
		return
	}
```
We can do like this?
Close it if on purpose.
## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-04-12 04:09 UTC, harshavardhana commented
In getOpts() the part number is validated at lower layer, so what you are adding is fine.

2023-04-15 09:23 UTC, jiuker commented
@harshavardhana close this if on purpose

2023-04-17 19:18 UTC, harshavardhana requested changes

2023-04-17 19:18 UTC, harshavardhana commented on cmd/object-api-options.go
> +			return opts, fmt.Errorf("ErrInvalidMaxParts")
We need to return correct errors here @jiuker

2023-04-18 03:56 UTC, harshavardhana requested changes

2023-04-18 03:56 UTC, harshavardhana commented on cmd/typed-errors.go
> +// error returned when request.From http.PartNumber is greater than the maximum allowed ID.
```suggestion
// error returned when PartNumber is greater than the maximum allowed 10000 parts
```

2023-04-18 03:56 UTC, harshavardhana commented on cmd/typed-errors.go
> +var errInvalidMaxParts = errors.New("Part ID is greater than the maximum allowed ID.")
```suggestion
var errInvalidMaxParts = errors.New("Part number is greater than the maximum allowed 10000 parts")
```

2023-04-18 07:06 UTC, harshavardhana approved these changes

2023-04-18 08:53 UTC, klauspost approved these changes

2023-04-19 05:34 UTC, merged