fix: call wg.Done twice
minio/minio pull request #17075
Opened 2023-04-25 08:45 UTC by jiuker

## Description

fix call wg.Done twice
simple like
```go
	var wg sync.WaitGroup
	wg.Add(1)
	wg.Done()
	wg.Done()
	wg.Wait()
```
It will panic

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-04-25 15:25 UTC, krisis approved these changes

2023-04-26 20:33 UTC, harshavardhana requested changes

2023-04-26 20:33 UTC, harshavardhana commented on cmd/disk-cache-backend.go
> -					pw.CloseWithError(err)
This is wrong you shouldn't remove this instead you should do this change

```diff
diff --git a/internal/ioutil/wait_pipe.go b/internal/ioutil/wait_pipe.go
index 124cde78f..67f490ba4 100644
--- a/internal/ioutil/wait_pipe.go
+++ b/internal/ioutil/wait_pipe.go
@@ -25,13 +25,16 @@ import (
 // PipeWriter is similar to io.PipeWriter with wait group
 type PipeWriter struct {
        *io.PipeWriter
+       once sync.Once
        done func()
 }
 
 // CloseWithError close with supplied error the writer end.
 func (w *PipeWriter) CloseWithError(err error) error {
        err = w.PipeWriter.CloseWithError(err)
-       w.done()
+       w.once.Do(func() {
+               w.done()
+       })
        return err
 }
```

2023-04-27 08:19 UTC, harshavardhana approved these changes

2023-04-27 14:55 UTC, merged