Add "name" and "description" params to service acc
minio/minio pull request #17172
Opened 2023-05-10 02:58 UTC by donatello

## Description

- "name" is a friendly name for a service account (it is not required, but it is recommented to be unique).

- "description" replaces existing "comment" parameter - comment value in existing deployments is read into the description field.

- name and description have length and other restrictions that are validated.

## Motivation and Context

Improve service account usability.

## How to test this PR?

There is a corresponding mc PR with the CLI changes.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-05-10 07:55 UTC, harshavardhana requested changes

2023-05-10 07:55 UTC, harshavardhana commented on internal/auth/credentials.go
> +	// Deprecated in favor of Description - when reading credentials from
```suggestion
	// Deprecated: In favor of Description - when reading credentials from
```

2023-05-15 19:16 UTC, donatello commented
Looks like we need this mc PR https://github.com/minio/mc/pull/4569 to go in before this PR can be merged because we get conflicting deps: 
1. minio -> console -> mc -> madmin-go
2. minio -> madmin-go
3. minio -> console -> madmin-go

2023-05-17 19:29 UTC, donatello commented
Updated mc dep here, should be ready to go in.

2023-05-17 19:39 UTC, harshavardhana approved these changes

2023-05-17 23:57 UTC, krisis approved these changes

2023-05-18 00:05 UTC, merged