heal: Update object parity with the latest configured SC
minio/minio pull request #17187
Opened 2023-05-11 10:58 UTC by vadmeste

## Description
If the user asks for it, rewrite objects if its parity is different 
to the one currently configured.

Avoid .minio.sys since all of objects there are already written 
with MaxParity.

## Motivation and Context
Add rewrite parity capability

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-05-11 18:26 UTC, harshavardhana requested changes

2023-05-11 18:26 UTC, harshavardhana commented on cmd/erasure-healing.go
> +				tillOffset := erasureReader.ShardFileOffset(0, partSize, partSize)
why calculate this for every disk? @vadmeste

2023-05-12 15:02 UTC, harshavardhana approved these changes

2023-05-12 15:02 UTC, harshavardhana approved these changes

2023-05-15 20:28 UTC, harshavardhana approved these changes

2023-05-15 20:29 UTC, krisis approved these changes

2023-05-16 04:32 UTC, merged