make slice cap right
minio/minio pull request #17192
Opened 2023-05-12 02:54 UTC by jiuker

## Description

make slice cap right
It seems should be `len*4` not `len`

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-05-12 03:29 UTC, harshavardhana requested changes

2023-05-12 03:29 UTC, harshavardhana commented on cmd/metrics-v2.go
>  		for _, t := range tgts {
It doesn't really matter here, this is just an optimization.

Eventual slice could be always bigger. Not sure where the 4* comes here.

So this change is not needed.

2023-05-16 12:33 UTC, klauspost commented
@harshavardhana Each loop writes exactly 4 times per target, so the capacity is exact.

2023-05-16 12:33 UTC, klauspost approved these changes

2023-05-16 15:09 UTC, harshavardhana approved these changes

2023-05-16 15:10 UTC, merged