Prevents writing incorrect data twice
minio/minio pull request #17205
Opened 2023-05-14 08:27 UTC by jiuker

## Description

https://github.com/minio/minio/blob/a7f266c9075a8c2eee5fec39dac0b5411763d2a4/cmd/admin-handler-utils.go#L37-L61
It looks like this exception has been handled here.

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-05-14 08:42 UTC, harshavardhana commented
We need to make sure we return error for `globalTierConfigMgr` is nil.

2023-05-14 08:50 UTC, jiuker commented
@harshavardhana /cc now?

2023-05-14 10:14 UTC, harshavardhana requested changes

2023-05-14 10:14 UTC, harshavardhana commented on cmd/tier-handlers.go
> +	}
Looks like copy paste error?

2023-05-14 10:14 UTC, harshavardhana approved these changes

2023-05-15 17:06 UTC, krisis reviewed
Good catch!

2023-05-15 17:06 UTC, krisis commented on cmd/tier-handlers.go
> +	if globalTierConfigMgr == nil {
`globalTierConfigMgr` is [initialized](https://github.com/minio/minio/blob/master/cmd/server-main.go#L366) to a non-nil value before the object layer is [initialized](https://github.com/minio/minio/blob/master/cmd/server-main.go#L416). So, we don't need to check `if globalTierConfigMgr == nil` in any of the tier handlers. I realized this only on reviewing this PR.

2023-05-16 00:46 UTC, krisis approved these changes

2023-05-16 05:03 UTC, harshavardhana approved these changes

2023-05-16 06:56 UTC, merged