batch: default to path style lookup for remote client
minio/minio pull request #17201
Opened 2023-05-12 23:46 UTC by poornas

## Description

## Motivation and Context
for compatibility with other S3 remotes

## How to test this PR?
mc batch start with this yaml to replicate to local minio bucket `vbucket`
```
replicate:
  apiVersion: v1
  # source of the objects to be replicated
  source:
    type: s3 # valid values are "minio", "s3"
    bucket: mybucket
    prefix:   # 'PREFIX' is optional
    # NOTE: if source is remote then target must be "local"
    endpoint: https://storage.googleapis.com
    credentials:
      accessKey: xxx
      secretKey:  yyyyy
  #  #   sessionToken: SESSION-TOKEN # Optional only available when rotating credentials are used

  # target where the objects must be replicated
  target:
    type: minio # valid values are "minio"
    bucket: vbucket
    prefix:  # 'PREFIX' is optional
    # NOTE: if target is remote then source must be "local"
    # endpoint: http://localhost:9004
    # credentials:
    #   accessKey: minio
    #   secretKey: minio123
    # #   sessionToken: SESSION-TOKEN # Optional only available when rotating credentials are used

  # NOTE: All flags are optional
  # - filtering criteria only applies for all source objects match the criteria
  # - configurable notification endpoints
  # - configurable retries for the job (each retry skips successfully previously replaced objects)
  flags:
    filter:
    #  newerThan: "8h" # match objects newer than this value (e.g. 7d10h31s)
    #   olderThan: "8h" # match objects older than this value (e.g. 7d10h31s)
    #  createdAfter: "date" # match objects created after "date"
    #  createdBefore: "date" # match objects created before "date"

    #     ## NOTE: tags are not supported when "source" is remote.
    # tags:
    #   - key: "name"
    #     value: "pick*" # match objects with tag 'name', with all values starting with 'pick'

    #     ## NOTE: metadata filter not supported when "source" is non MinIO.
    #     # metadata:
    #     #   - key: "content-type"
    #     #     value: "image/*" # match objects with 'content-type', with all values starting with 'image/'

  #   notify:
  #     endpoint: "https://notify.endpoint" # notification endpoint to receive job status events
  #     token: "Bearer xxxxx" # optional authentication token for the notification endpoint

    retry:
      attempts: 10 # number of retries for the job before giving up
      delay: "500ms" # least amount of delay between each retry

```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-05-13 02:32 UTC, harshavardhana requested changes

2023-05-13 02:32 UTC, harshavardhana commented on cmd/batch-handlers.go
> +	case "on", "off", "auto", "":
Don't need a switch case for a simple one liner

2023-05-18 00:06 UTC, harshavardhana commented on cmd/batch-handlers.go
> +	case "on", "off", "auto", "":
@poornas ^^

2023-05-18 08:55 UTC, harshavardhana approved these changes

2023-05-21 15:40 UTC, vadmeste approved these changes
LGTM

2023-05-21 22:16 UTC, merged