When workers.New get err should return
minio/minio pull request #17208
Opened 2023-05-15 01:59 UTC by jiuker

## Description

When workers.New get err should return

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-05-15 09:35 UTC, vadmeste approved these changes
LGTM

2023-05-15 15:03 UTC, harshavardhana approved these changes

2023-05-15 16:08 UTC, harshavardhana requested changes

2023-05-15 16:08 UTC, harshavardhana commented on cmd/bucket-lifecycle.go
> +		return
actually this PR is wrong we should always initialize ILM and never return errors, initialize this with some random valid value.

```
```suggestion
		ewk = 4
```

2023-05-15 16:08 UTC, harshavardhana commented on cmd/bucket-lifecycle.go
> +		return
```suggestion
		nwk = 4
```

2023-05-15 16:16 UTC, jiuker commented
@harshavardhana it seems that is wrong which you suggested.

2023-05-16 05:02 UTC, harshavardhana commented
> @harshavardhana it seems that is wrong which you suggested.Do you mean workerSize should be 4 by default?

Correct if someone sets the wrong value @jiuker - we should never fail to initialize, we should always initialize with sane defaults.

2023-05-16 05:02 UTC, harshavardhana approved these changes

2023-05-16 10:23 UTC, klauspost approved these changes

2023-05-16 15:08 UTC, merged