Add PostObject Checksum
minio/minio pull request #17244
Opened 2023-05-19 12:22 UTC by klauspost

## Description

This adds checksums as described in https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPOST.html

## How to test this PR?

Mint test PR:  (TBD)

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2023-05-19 14:06 UTC, klauspost commented
(should be trivial to merge with https://github.com/minio/minio/pull/17233 )

2023-05-20 23:14 UTC, harshavardhana requested changes

2023-05-20 23:14 UTC, harshavardhana commented on cmd/bucket-handlers.go
> +		writeErrorResponse(ctx, w, apiErr, r.URL)
missing return

2023-05-20 23:14 UTC, harshavardhana commented on cmd/bucket-handlers.go
> +		writeErrorResponse(ctx, w, apiErr, r.URL)
missing return

2023-05-22 21:55 UTC, harshavardhana approved these changes

2023-05-23 10:05 UTC, vadmeste approved these changes
LGTM

2023-05-23 14:58 UTC, merged