s3: Add x-minio-error-code header for S3 HEAD requests
minio/minio pull request #17283
Opened 2023-05-25 18:03 UTC by vadmeste

## Description
For HeadObject and HeadBucket, it is hard to understand the reason 
of a 403 response since the HEAD request does not return a response body.

This PR will add a header which contains the error code that will be 
sent if this was a GET and not a HEAD request.

e.g.: AccessDenied, SignatureDoesNotMatch, InvalidAccessKeyId

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-05-25 18:06 UTC, harshavardhana requested changes

2023-05-25 18:06 UTC, harshavardhana commented on cmd/bucket-handlers.go
> +		w.Header().Set(xMinIOErrCodeHeader, errCode.Code)
```suggestion
		w.Header().Set(xMinIOErrCodeHeader, errCode.Code)
		w.Header().set(xMinIOErrDescHeader, "\"" + errCode.Description + "\"")
```

2023-05-26 15:50 UTC, klauspost approved these changes

2023-05-26 16:58 UTC, harshavardhana approved these changes

2023-05-26 17:13 UTC, merged