fix: mc head will close the connection
minio/minio pull request #17329
Opened 2023-06-01 14:40 UTC by jiuker

## Description

fix: mc head will close the connection

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-06-01 14:53 UTC, harshavardhana commented
This PR doesn't make sense @jiuker mc head will invoke only HeadObject not GetObject you are fixing something in the wrong path.

All client connections close when the handler returns, so not sure what is being fixed here.

2023-06-01 14:59 UTC, harshavardhana requested changes

2023-06-01 14:59 UTC, harshavardhana commented on cmd/object-handlers.go
> +		// `mc head` will close the connection, will make this error
We need to move this type of check into IsNetworkOrHostDown(err) 

So that we can ignore printing the logs instead of introducing a goto jump

2023-06-16 03:40 UTC, jiuker commented
update go depend will fix by auto.

2023-06-16 03:40 UTC, closed without merging