Redact all secrets from config viewing APIs
minio/minio pull request #17380
Opened 2023-06-07 22:24 UTC by donatello

## Description
This change adds a `Secret` property to `HelpKV` to identify secrets like passwords and auth tokens that should not be revealed by the server in its configuration fetching APIs. Functions that retrieve secrets for display purposes now return `***` as the secret values.

## Motivation and Context

## How to test this PR?
Query configuration with mc or UI and ensure that secrets are redacted.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-06-07 22:38 UTC, harshavardhana requested changes, later dismissed
how will use take backups of their config during `mc admin config export`  if we redact them?

2023-06-07 22:43 UTC, donatello commented
> how will use take backups of their config during `mc admin config export` if we redact them?

Yeah just noticed, fixing.

2023-06-20 05:59 UTC, harshavardhana commented
@donatello wanted one internal discussion on this before we merge and make a release with @abperiasamy - it will be short.

2023-06-21 20:23 UTC, donatello commented
This PR is now updated - secrets are never returned by configuration reporting APIs. They are not redacted as `***` or some other dummy string to prevent them from being treated as data or passwords as discussed with @abperiasamy 

The export API which exports configuration for backup purposes is not affected by this change and will continue to work as expected. Access to that API can be controlled via denying the `GetConfig` IAM permission, and with an upcoming change in how policies may be attached to users.

This PR is now ready for review.

2023-06-21 20:30 UTC, harshavardhana approved these changes

2023-06-22 15:17 UTC, harshavardhana commented
PTAL @allanrogerr @cniackz @cesnietor

2023-06-23 09:42 UTC, vadmeste approved these changes
I would say viewing secrets can be allowed to users who have SetConfig permission but this can be confusing to users.

(whoever can set a new config or doing import IAM should be able to see secrets)

LGTM otherwise

2023-06-23 14:45 UTC, merged