fix:set header when url.Value have multi value
minio/minio pull request #17392
Opened 2023-06-10 13:59 UTC by jiuker

fix:set header when url.Value have multi value
releted #17390 
## Description

When url.Value define multi values. Will set a wrong header here. 
make it will works for download 
```url
http://127.0.0.1:9000/mytest/R-C.jfif?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minioadmin%2F20230610%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20230610T135713Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&response-content-disposition=file&response-content-disposition=name&X-Amz-Signature=9cd0138a9ec5632462835575db36f79750dea2e8bb6881f0764cadf05416ca59
```
if  not , the Browser will close the connection by unexpected.
I make it by
```go
v := url.Values{}
	v["response-content-disposition"] = []string{"file", "name"}
	//v.Set("response-content-disposition", "file&name")
	fmt.Println(minioClient.PresignedGetObject(ctx, bucketName, "R-C.jfif", time.Hour, v))
```
## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-06-12 10:00 UTC, vadmeste approved these changes
LGTM

Can you fix this PR title @jiuker ?

2023-06-12 10:06 UTC, klauspost approved these changes

2023-06-12 16:16 UTC, harshavardhana requested changes

2023-06-12 16:16 UTC, harshavardhana commented on cmd/object-handlers.go
> +			w.Header()[header] = []string{strings.Join(v, ";")}
```suggestion
			w.Header()[header] = []string{strings.Join(v, ",")}
```

Multiple values in HTTP header must be `comma` separated

You'll want to take a look at the HTTP spec RFC 2616 where it says:

```
Multiple message-header fields with the same field-name MAY be present in a message if and only if the entire field-value for that header field is defined as a comma-separated list [i.e., #(values)]. It MUST be possible to combine the multiple header fields into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field-value to the first, each separated by a comma. The order in which header fields with the same field-name are received is therefore significant to the interpretation of the combined field value, and thus a proxy MUST NOT change the order of these field values when a message is forwarded.
```

2023-06-13 18:03 UTC, harshavardhana approved these changes

2023-06-13 18:38 UTC, merged