s3: Make/Delete buckets to use error quorum per pool
minio/minio pull request #17467
Opened 2023-06-19 20:41 UTC by vadmeste

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-06-19 21:35 UTC, harshavardhana commented
this is unnecessary why are we doing this? @vadmeste

2023-06-22 15:15 UTC, harshavardhana requested changes

2023-06-22 15:15 UTC, harshavardhana commented on cmd/globals.go
> +	// All nodesof this deployment
```suggestion
	// All unique nodes for this deployment
```

2023-06-22 15:15 UTC, harshavardhana commented on cmd/globals.go
> +	// All drives endpoints of this deployment
```suggestion
	// All drives for this deployment
```

2023-06-23 17:48 UTC, harshavardhana approved these changes

2023-06-23 18:27 UTC, poornas approved these changes

2023-06-23 18:48 UTC, merged