Test arn to avoid regression
minio/minio pull request #17566
Opened 2023-07-04 08:02 UTC by Joffref

## Description
It adds test for ARN to ensure consistency in definition for future versions, plus it changes error format to comply with [Golang standard](https://google.github.io/styleguide/go/decisions.html#error-strings)

## Motivation and Context
This PR is here to improve code test coverage and it is good way to me for improving my golang coding level and hands on minio codebase while helping community to have a codebase more sure.

> Feel free to close this PR if it is not relevant to you

## How to test this PR?
Just run `make test`

## Types of changes
- [x] Unit tests added/updated

## Checklist:
- [x] Unit tests added/updated

2023-07-11 19:08 UTC, donatello approved these changes

2023-07-15 14:47 UTC, jiuker approved these changes

2023-07-15 19:16 UTC, harshavardhana requested changes

2023-07-15 19:16 UTC, harshavardhana commented on internal/arn/arn_test.go
> +package arn
missing license header @Joffref please add it looking at the arn.go

2023-07-17 20:11 UTC, harshavardhana requested changes

2023-07-17 20:11 UTC, harshavardhana commented on internal/arn/arn_test.go
> +// Copyright (c) 2015-2021 MinIO, Inc.
```suggestion
// Copyright (c) 2015-2023 MinIO, Inc.
```

2024-01-24 07:36 UTC, harshavardhana commented
Please resolve the conflicts with latest master.

2024-04-04 06:32 UTC, closed without merging