Avoid extra GetObjectInfo call in DeleteObject API
minio/minio pull request #17599
Opened 2023-07-07 18:42 UTC by poornas

on the replicating side. For receiving side, it is just a regular DeleteObject call.

Also fixing a corner case where version being purged is absent on target (either due to replication not yet complete or target version already deleted in a one-way replication or while replication was disabled). In such cases, mark version purge complete.

## Description

## Motivation and Context
optimization

## How to test this PR?
regular replication of deletes/delete markers; setting compliance retention on object version should throw errors if deleting the version before retention expiry

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-07-07 22:29 UTC, harshavardhana requested changes

2023-07-07 22:29 UTC, harshavardhana commented on cmd/object-handlers.go
> -		os.SetTransitionState(goi.TransitionedObject)
Is this not necessary anymore?

2023-07-08 13:39 UTC, poornas commented on cmd/object-handlers.go
> -		os.SetTransitionState(goi.TransitionedObject)
fixed this

2023-07-08 17:41 UTC, harshavardhana approved these changes

2023-07-10 14:50 UTC, klauspost approved these changes
LGTM

2023-07-10 14:57 UTC, merged