Fix helm templating syntax in post-job
minio/minio pull request #17600
Opened 2023-07-07 21:45 UTC by aztechian

## Description

I was getting a parse error when updating my helm deployment using this chart. Not sure if helm actually fails on the brackets with spaces in between, but at a minimum this isn't consistent with the rest of the chart.

## Motivation and Context

Troubleshooting an operational error, I came across this potential issue.

```
Error: parse error at (minio/templates/post-job.yaml:255): unexpected {{end}} Use --debug flag to render out invalid YAML
```

## How to test this PR?

`helm template --debug --dry-run --generate-name .`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression #17554 
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-07-07 22:26 UTC, harshavardhana requested changes

2023-07-07 22:26 UTC, harshavardhana commented on helm/minio/Chart.yaml
> +version: 5.0.13
Don't update the version, we will do it.

2023-07-07 22:30 UTC, harshavardhana approved these changes

2023-07-08 00:43 UTC, jiuker approved these changes

2023-07-08 05:06 UTC, merged