return tags as part of Head/Get calls
minio/minio pull request #17635
Opened 2023-07-11 20:16 UTC by harshavardhana

## Description
return tags as part of Head/Get calls

## Motivation and Context
AWS S3 only returns the number of tag
counts, along with that we must return
the tags as well to avoid another metadata
call to the server.

## How to test this PR?
Verify after attaching new tags on the object
that `mc stat` returns the tags as part
of the Head call.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-07-11 21:37 UTC, krisis approved these changes

2023-07-11 21:41 UTC, poornas approved these changes

2023-07-12 01:47 UTC, harshavardhana commented
Need to test one scenario with large tag key names and values.

2023-07-12 08:16 UTC, klauspost requested changes
Please gate this behind a feature header.

Several if not all reverse proxies have header size limits, and adding up to 8K of extra data is likely to exceed default config.

2023-07-22 06:59 UTC, harshavardhana commented
This is not returned by default, however setting `x-amz-tagging-directive: ACCESS` makes the server return the tags with `x-amz-tagging: <tags>`

2023-07-22 11:00 UTC, klauspost approved these changes
👍🏼

2023-07-22 14:19 UTC, merged