fix:copy the req.body into io.Discard always
minio/minio pull request #17881
Opened 2023-08-19 15:52 UTC by jiuker

## Contribution License
All contributions in this pull request are licensed to the project maintainers 
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

copy the req.body into io.Discard always 

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-08-19 15:53 UTC, vadmeste approved these changes
LGTM

2023-08-19 16:16 UTC, donatello approved these changes

2023-08-19 16:31 UTC, harshavardhana requested changes

2023-08-19 16:31 UTC, harshavardhana commented on internal/event/target/elasticsearch.go
> +		defer io.Copy(io.Discard, resp.Body)
You should drain before and then call Close().

2023-08-19 16:34 UTC, harshavardhana commented on internal/event/target/elasticsearch.go
> +		defer io.Copy(io.Discard, resp.Body)
Move them into same defer statement

```
defer func() {
   io.CopyN(io.Discard, resp.Body, humanize.MiByte)
   resp.Body.Close()
}
```

2023-08-21 02:45 UTC, harshavardhana requested changes

2023-08-21 02:45 UTC, harshavardhana commented on internal/event/target/elasticsearch.go
> +			return fmt.Errorf("Create index err: %s", res.String())
```suggestion
			return fmt.Errorf("Create index err: %v", res)
```

2023-08-21 02:45 UTC, harshavardhana commented on internal/event/target/webhook.go
> +	}
We should limit the size of io.Copy() otherwise it will never end. So we can drain up-to 1MiB

2023-08-21 03:29 UTC, harshavardhana approved these changes

2023-08-21 08:09 UTC, merged