Reduce the number of calls to import bucket metadata@@@
minio/minio pull request #17899
Opened 2023-08-22 21:34 UTC by vadmeste

For each bucket, save the bucket metadata once, call the site replication hook once

## Contribution License
All contributions in this pull request are licensed to the project maintainers 
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-08-23 03:26 UTC, harshavardhana requested changes

2023-08-23 03:26 UTC, harshavardhana commented on cmd/admin-handlers-site-replication.go
> +		err := a.doSRPeerReplicateBucketItem(ctx, typ, item)
we should do multiple types at once as well @vadmeste - we should support that would that require a breaking change?

2023-08-24 22:32 UTC, harshavardhana approved these changes

2023-08-25 04:47 UTC, shtripat approved these changes
lgtm

2023-08-25 14:59 UTC, merged