heal: calculate the number of workers based on  NRRequests
minio/minio pull request #17945
Opened 2023-08-29 20:42 UTC by vadmeste

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-09-06 17:59 UTC, harshavardhana requested changes

2023-09-06 17:59 UTC, harshavardhana commented on cmd/global-heal.go
> +
```suggestion
	numHealers := uint64(4)
	if info.NRRequests > runtime.GOMAXPROCS(0) {
	      numHealers = runtime.GOMAXPROCS(0)/4
	} else {
	      numHealers = info.NRRequests/4
	}
	if numHealers == 0 || numHealers == 1 {
	       numHealers = 4
	}
	// allow overriding this value as well..
	if v := globalAPIConfig.getHealWorkers(); v > 0 {
	     numHealers = v
	}
```

2023-09-06 22:20 UTC, harshavardhana requested changes

2023-09-06 22:20 UTC, harshavardhana commented on internal/config/heal/heal.go
> +		Deprecated: true,
```suggestion
		Deprecated: true,
```

:P

2023-09-11 06:12 UTC, harshavardhana requested changes

2023-09-11 06:12 UTC, harshavardhana commented on internal/config/heal/heal.go
> +		Deprecated: true,
@vadmeste you need to remove "Deprecated: true"

2023-09-11 17:23 UTC, vadmeste commented
> @vadmeste you need to remove "Deprecated: true"

The point is to make this variable hidden from users, until someone expliclity sets it

2023-09-11 17:28 UTC, harshavardhana commented
> The point is to make this variable hidden from users, until someone explicitly sets it

For that we can't reuse this boolean, we should simply have this available to all users but document that it is not needed to be set without expert guidance via SUBNET

2023-09-11 17:30 UTC, harshavardhana requested changes

2023-09-11 17:30 UTC, harshavardhana commented on cmd/xl-storage.go
> +	// Sanitaize before setting it
```suggestion
	// Sanitize before setting it
```

2023-09-11 18:46 UTC, harshavardhana requested changes

2023-09-11 18:46 UTC, harshavardhana commented on cmd/global-heal.go
> +
let's also update https://github.com/minio/minio/blob/e3fbcaeb729f5dd02f4b7c96c10b952c1d7dfe2a/docs/config/README.md?plain=1#L274

To show this configurable value

2023-09-11 18:46 UTC, harshavardhana commented on cmd/global-heal.go
> +
We have to say that this is Linux only optimization, for example on Windows and other OS we will use `number of cores / 4`

2023-09-11 18:46 UTC, harshavardhana requested changes

2023-09-11 18:46 UTC, harshavardhana commented on cmd/global-heal.go
> +	if numHealers == 0 || numHealers == 1 {
```suggestion
	if numHealers < 4 {
```

We expect this to be 4 minimum, unless user wants this to be some other value.

2023-09-11 21:48 UTC, harshavardhana approved these changes

2023-09-11 21:48 UTC, merged