scanner: Scan buckets asynchronously
minio/minio pull request #18107
Opened 2023-09-25 23:07 UTC by vadmeste

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
- Scan buckets asynchrounously; multiple erasure sets scan in parallel, multiple disks in the same erasure set scan different buckets in parallel
- No data format is changed
- Cycle concept changed to be per bucket focused, the cycle is incremented ecah time a bucket is successfully or unsuccesfully scanned
- Next bucket to scan is chosen based on the lowest possible cycle number

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-09-25 23:18 UTC, harshavardhana reviewed
do you know how far this improves to share? @vadmeste

2023-09-25 23:18 UTC, harshavardhana commented on cmd/erasure.go
> +	scanWg := sync.WaitGroup{}
```suggestion
	var scanWg sync.WaitGroup
```

2023-09-27 10:44 UTC, klauspost commented
@vadmeste Could you describe the changes in more detail?

2023-09-30 23:33 UTC, vadmeste commented
> @vadmeste Could you describe the changes in more detail?

So basically here, I tried to keep the change as minimal as possible; and I did not need to do any data format change as well;

So we will use everything as usual; the total usage; the data cache per erasure set; the data cache per bucket per erasure set; This should not be a problem even if we scan buckets in parallel; because after all, we will still scan one bucket per erasure set at a time, this should not cause any confusion in calculation at all.

The differences from the old code:
- Each bucket in each erasure set has its own scan cycle
- A bucket scan manager decides what is the next bucket to scan for a given erasure set 
- erasure-server-pools.NSScanner call (and lower calls) will not return anymore, and will continously scan for buckets

Let's chat while you review this PR if you want

2023-12-30 06:57 UTC, harshavardhana commented
I have rebased and pushed the changes @vadmeste

2024-01-02 06:58 UTC, shtripat commented on cmd/data-scanner-metric.go
> +// addCycleEvent updates the current cycle metrics.
Comment `addCycleEvent` doesn't match the function name.

2024-01-02 06:58 UTC, shtripat commented on cmd/data-scanner-metric.go
> +	cycleCompleted []time.Time
suggestion: lets add a comment that last 10 cycle completed timestamps are maintained

2024-01-02 06:58 UTC, shtripat commented on cmd/data-scanner-metric.go
>  // getCycle returns the current cycle metrics.
Match the function name in comment with correct name

2024-01-03 06:00 UTC, shtripat approved these changes
looks good to me

2024-01-03 06:00 UTC, shtripat commented on cmd/buckets-scan-mgr.go
> +// Mark a bucket as done in a specific erasure set - returns true if successful,
`%s/Mark a bucket as done in a specific erasure set/Mark a bucket as scan started in a specific erasure set/g`

2024-02-29 00:46 UTC, harshavardhana commented
@vadmeste please rebase this and let the team know what is waiting on us for merging this PR.

2024-03-11 12:12 UTC, harshavardhana commented
PTAL @klauspost need your review here 

Is there any breakage in mc admin scanner status ?

2024-03-24 10:04 UTC, harshavardhana commented
@vadmeste read the code again. Why do we need a change in data structure and why madmin-go needs to break here ?

2024-03-25 13:08 UTC, vadmeste commented
> @vadmeste read the code again. Why do we need a change in data structure and why madmin-go needs to break here ?

Basically after implementing the asynchronous bucket scanning, a cluster scan cycle will lose its meaning. The cycle will be per bucket per erasure set instead:

```
           (pool, set, bucket-name) => cycle
```

By the way, madmin-go wil still work with older MinIO deployments, later mc will show the approriate UI. If the cluster cycle information is available, then we know this is an old version and

2024-05-16 19:29 UTC, poornas commented on cmd/buckets-scan-mgr.go
> +// Copyright (c) 2015-2023 MinIO, Inc.
```suggestion
// Copyright (c) 2015-2024 MinIO, Inc.
```

2024-07-15 22:19 UTC, harshavardhana commented
Please rebase this with master @vadmeste

2024-07-16 18:00 UTC, harshavardhana requested changes

2024-07-16 18:00 UTC, harshavardhana commented on cmd/buckets-scan-mgr.go
> +	internal     map[setID]map[string]bucketScanStat // A map of an erasure set identifier and bucket scan stats
can we add comments and some design explanation in this file? @vadmeste

2024-07-16 18:02 UTC, harshavardhana commented
Also madmin-go is merged please remove the replace tag @vadmeste

2024-07-17 21:13 UTC, harshavardhana approved these changes

2024-07-17 21:14 UTC, harshavardhana commented
```
Non-committed changes in auto-generated go.sum is detected, please commit them to proceed.
make: *** [Makefile:39: check-gen] Error 1
```

2024-07-18 14:37 UTC, harshavardhana approved these changes

2024-07-18 14:37 UTC, harshavardhana commented
PTAL @poornas @klauspost

2024-07-18 22:27 UTC, poornas requested changes

2024-07-18 22:27 UTC, poornas commented on cmd/buckets-scan-mgr.go
> +	defer mgr.mu.Unlock()
```suggestion
	mgr.mu.RLock()
	defer mgr.mu.RUnlock()
```

2024-07-18 22:27 UTC, poornas commented on cmd/buckets-scan-mgr.go
> +	defer mgr.mu.Unlock()
```suggestion
	mgr.mu.RLock()
	defer mgr.mu.RUnlock()
```

2024-07-19 10:01 UTC, klauspost reviewed
Just a few minors.

Can't vouch for functionality, but overall LGTM

2024-07-19 10:01 UTC, klauspost commented on cmd/buckets-scan-mgr.go
> +	c := sync.NewCond(m)
I'd much prefer the simplicity of...
```suggestion
	m := make(chan struct{}, 1)
```

Then do a select with default to send. and a simple `<-m` to wait for the first. 

Technically what you have here is racy, since the broadcast can be done before you are waiting for it - and you'll miss it.

2024-07-19 10:01 UTC, klauspost commented on cmd/buckets-scan-mgr.go
> +func (mgr *bucketsScanMgr) unsafeGetNextBucket(id setID) string {
I prefer to use "unsafe" for memory safety. IMO this more clearly signifies that the caller has locked m.
```suggestion
func (mgr *bucketsScanMgr) getNextBucketLocked(id setID) string {
```

2024-07-19 10:01 UTC, klauspost commented on cmd/buckets-scan-mgr.go
> +	return ret
Sort to make it consistent?
```suggestion
	sort.Strings(ret)
	return ret
```

2024-07-19 10:01 UTC, klauspost commented on cmd/buckets-scan-mgr.go
> +	internal     map[setID]map[string]bucketScanStat // A map of an erasure set identifier and bucket scan stats
`internal` is not really a good name. Maybe
```suggestion
	bucketStats     map[setID]map[string]bucketScanStat // A map of an erasure set identifier and bucket scan stats
```

2024-07-19 10:01 UTC, klauspost commented on cmd/buckets-scan-mgr.go
> +					mgr.knownBuckets = make(map[string]struct{}, len(buckets))
Maybe create the map without the lock and replace with a short held lock?

That way `globalLifecycleSys.Get(bucket)` cannot block everything else.

2024-07-19 21:17 UTC, poornas approved these changes

2024-07-27 10:24 UTC, harshavardhana commented on cmd/buckets-scan-mgr.go
> +	return ret
@vadmeste ^^

2024-07-27 10:24 UTC, harshavardhana commented
please resolve conflicts @vadmeste

2024-08-02 22:27 UTC, harshavardhana commented
Lets move this PR to mineos only @vadmeste

2024-08-13 22:23 UTC, harshavardhana commented
@vadmeste can you move this to `mineos`?

2024-08-13 22:23 UTC, closed without merging

2024-10-31 12:39 UTC, mrsrvman commented
What happened to this request?
Will this feature be committed?

2024-10-31 13:12 UTC, klauspost commented
No

2024-11-09 16:28 UTC, mrsrvman commented
Do you have plans to switch to multi-threaded scanning?

Single-threaded scanning causes problems on a large number of files.

2024-11-09 20:43 UTC, klauspost commented
Scanning is multithreaded. Sets are scanned in parallel. Buckets are scanned in parallel in sets.