Fix current_send_in_progress metric always being zero
minio/minio pull request #18160
Opened 2023-10-03 10:18 UTC by mctoohey

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license] (https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Fixes https://github.com/minio/minio/issues/18159

## Motivation and Context

See https://github.com/minio/minio/issues/18159

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-10-03 15:13 UTC, harshavardhana approved these changes

2023-10-03 15:14 UTC, harshavardhana requested changes
We should add a check such that event notifier if nil we must not crash the handler. Also fix the actual code internally perhaps to return stats() correctly.

2023-10-04 00:29 UTC, mctoohey commented
@harshavardhana  I've add a check to only include these metrics if `globalEventNotifier` is not `nil`.


> Also fix the actual code internally perhaps to return stats() correctly.

I'm not quite sure what you would want to see changed for this.

2023-10-09 04:56 UTC, harshavardhana approved these changes

2023-10-10 00:28 UTC, merged