Ignore "File" key on policy conditions and don't enforce filename
minio/minio pull request #18336
Opened 2023-10-28 14:17 UTC by DaniElectra

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
As per the [Amazon S3 docs](http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTConstructPolicy.html), the `file` field must be ignored when checking the policy conditions for `PostPolicy`:

> Each form field that you specify in a form (except `x-amz-signature`, `file`, `policy`, and field names that have an `x-ignore-` prefix) must appear in the list of conditions.

The filename on the `file` field isn't required, but it's being used as reference for checking if we have reached the `file` field on the multipart fields loop. Check the current field using it's name instead.

## Motivation and Context
Since PR #18074, the minio server has been giving the message `Access Denied. (Each form field that you specify in a form (except File) must appear in the list of conditions.)` when sending a `PostPolicy`.

If the filename isn't set, the `fileName == ""` check is always true and the file reader never gets assigned, which causes a nullptr dereference when calling `PutObject` on `PostPolicyBucketHandler`. This fully fixes issue #18235

## How to test this PR?
```go
package main

import (
	"bytes"
	"context"
	"fmt"
	"log"
	"mime/multipart"
	"net/http"
	"time"

	"github.com/minio/minio-go/v7"
	"github.com/minio/minio-go/v7/pkg/credentials"
)

func main() {
	endpoint := "example.com"
	accessKeyID := "ACCESS_KEY"
	secretAccessKey := "ACCESS_SECRET"
	useSSL := true

	// Initialize minio client object.
	minioClient, err := minio.New(endpoint, &minio.Options{
		Creds:  credentials.NewStaticV4(accessKeyID, secretAccessKey, ""),
		Secure: useSSL,
	})
	if err != nil {
		log.Fatalln(err)
	}

	// Initialize policy condition config.
	policy := minio.NewPostPolicy()

	// Apply upload policy restrictions:
	policy.SetBucket("bucket")
	policy.SetKey("data/somedata")
	policy.SetExpires(time.Now().UTC().AddDate(0, 0, 10))

	// Get the POST form key/value object:
	url, formData, err := minioClient.PresignedPostPolicy(context.Background(), policy)
	if err != nil {
		fmt.Println(err)
		return
	}

	body := &bytes.Buffer{}
	writer := multipart.NewWriter(body)

	for fieldName, fieldValue := range formData {
		part, _ := writer.CreateFormField(fieldName)
		part.Write([]byte(fieldValue))
	}

	// Set the file field using CreateFormField to skip filename assignment
	part, _ := writer.CreateFormField("file")
	part.Write([]byte{30}) // "0"

	writer.Close()

	r, _ := http.NewRequest("POST", url.String(), body)
	r.Header.Add("Content-Type", writer.FormDataContentType())
	client := &http.Client{}
	client.Do(r)
}
```

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [X] Fixes a regression (PR #18074)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-10-30 09:38 UTC, jiuker commented
You should use 
```go
	fw, err := w.CreateFormFile("file", "test.png")
	if err != nil {
		panic(err)
	}
	_, err = io.Copy(fw, file)
	if err != nil {
		panic(err)
	}
```
To create the file.

2023-10-30 09:40 UTC, jiuker requested changes
You should use

	fw, err := w.CreateFormFile("file", "test.png")
	if err != nil {
		panic(err)
	}
	_, err = io.Copy(fw, file)
	if err != nil {
		panic(err)
	}
To create the file.
Don't use CreateFormField instead.
@DaniElectra

2023-10-30 10:14 UTC, DaniElectra commented
@jiuker I think there is a misunderstanding. The code that I've shown above is *an example* to test the PR, and doesn't represent the real code that the client is running. I have the same issue as #18235 where I can't control the client that makes the request, and you had made PR #18240 to fix this.

But this case still doesn't work for the reason that I had explained (the file reader not getting assigned). In any case, as it was explained on the issue I mention, the filename **isn't mandatory**, so this helps making the server compliant to the spec.

2023-10-30 10:19 UTC, jiuker commented
No. Go, Java, Python or else. All have this function similar method. @DaniElectra

2023-10-30 10:28 UTC, jiuker commented
@harshavardhana Any advices?

2023-10-30 10:31 UTC, harshavardhana commented
> @harshavardhana Any advices?

This PR is correct @jiuker `Filename()` is not a required field in AWS S3 spec, however `file` is. So the code change is correct.

@DaniElectra please add a test in `TestPostPolicyBucketHandler`

2023-10-30 21:55 UTC, DaniElectra commented
I added the test for the filename. I also removed the ignore key for `"File"` since it wasn't really needed.

2023-10-30 22:10 UTC, harshavardhana approved these changes

2023-10-31 01:36 UTC, jiuker approved these changes

2023-10-31 04:06 UTC, merged