feat: drive subsys to max timeout reload
minio/minio pull request #18501
Opened 2023-11-22 09:40 UTC by jiuker

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

feat: add drive max timeout reload

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-11-24 18:02 UTC, harshavardhana requested changes

2023-11-24 18:02 UTC, harshavardhana commented on cmd/config-current.go
> +			Description: "enable drive config",
```suggestion
			Description: "enable drive specific settings",
```

2023-11-24 18:02 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/jiuker/madmin-go/v3 v3.0.0-20231122072459-e88ab8ab6645
```suggestion
replace github.com/minio/madmin-go/v3 => github.com/jiuker/madmin-go/v3 v3.0.0-20231122072459-e88ab8ab6645
```

Please use v3.0.33

2023-11-24 18:02 UTC, harshavardhana commented on internal/config/drive/help.go
> +			Description: "set max_timeout for drive, default 2min",
```suggestion
			Description: "set per call max_timeout for the drive, defaults to 2 minutes",
```

2023-11-27 01:51 UTC, harshavardhana approved these changes

2023-11-27 08:14 UTC, klauspost requested changes

2023-11-27 08:14 UTC, klauspost commented on internal/config/drive/drive.go
> +var mutex sync.RWMutex
This seems misplaced.

Add the mutex to the data it is protecting. Ie inside the Config. Package level locks are a no-no.

2023-11-27 09:13 UTC, klauspost approved these changes

2023-11-27 17:15 UTC, merged