fix(cmd/notification.go): no error when retry successful
minio/minio pull request #18530
Opened 2023-11-27 13:48 UTC by bestgopher

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

When retrying, the last error should be discarded, otherwise the execution will be successful, but the error will still exist.
## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-11-27 13:55 UTC, klauspost approved these changes
LGTM

2023-11-27 19:36 UTC, vadmeste approved these changes
LGTM

2023-11-27 19:39 UTC, harshavardhana approved these changes

2023-11-27 20:33 UTC, harshavardhana requested changes

2023-11-27 20:33 UTC, harshavardhana commented on cmd/notification.go
> -	"github.com/minio/madmin-go/v3"
This is incorrectly removed

2023-11-28 06:40 UTC, harshavardhana approved these changes

2023-11-28 06:41 UTC, merged