xl: Rename Force to ImmediatePurge for clarity
minio/minio pull request #18540
Opened 2023-11-28 02:41 UTC by vadmeste

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-11-28 09:54 UTC, klauspost commented
`2023-11-28T03:13:27.5234227Z ##[error]cmd\xl-storage_windows_test.go:67:5: unknown field Force in struct literal of type DeleteOptions`

2023-11-28 09:58 UTC, klauspost approved these changes
I can live with the long form, so approving, but I'd prefer a shorter name since it doesn't give additional information.

2023-11-28 09:58 UTC, klauspost commented on cmd/storage-datatypes.go
> +	ImmediatePurge bool `msg:"ip"`
If it isn't too much of a hazzle, I think "Immediate" is enough. "Purge" is implied by it being a delete function.
```suggestion
	Immediate bool `msg:"i"`
```

2023-11-29 00:28 UTC, harshavardhana requested changes

2023-11-29 00:28 UTC, harshavardhana commented on cmd/xl-storage.go
> +func (s *xlStorage) deleteFile(basePath, deletePath string, recursive, immediatePurge bool) error {
```suggestion
func (s *xlStorage) deleteFile(basePath, deletePath string, recursive, immediate bool) error {
```

2023-11-29 00:28 UTC, harshavardhana commented on cmd/xl-storage.go
> +		err = s.moveToTrash(deletePath, true, immediatePurge)
```suggestion
		err = s.moveToTrash(deletePath, true, immediate)
```

2023-11-29 00:34 UTC, harshavardhana approved these changes

2023-11-29 06:35 UTC, merged