fix: trans cancel error into interval error when context is not cancaled
minio/minio pull request #18588
Opened 2023-12-04 11:45 UTC by jiuker

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
before , we have this.
```go
	// Only return ErrClientDisconnected if the provided context is actually canceled.
	// This way downstream context.Canceled will still report ErrRequestTimedout
	if contextCanceled(ctx) && errors.Is(ctx.Err(), context.Canceled) {
		return ErrClientDisconnected
	}
```
So the context is no canceled when:
```go
	case context.Canceled:
		apiErr = ErrClientDisconnected
```
fix: trans cancel error into interval error when context is not cancaled
When we got `Client disconnected before response was ready`, we can't found that if the client do cancel really.
It's  a timeout between the minio-servers maybe.

## Motivation and Context

## How to test this PR?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-12-04 19:11 UTC, vadmeste commented
> When we got Client disconnected before response was ready, we can't found that if the client do cancel really.
It's a timeout between the minio-servers maybe.

A timeout is usually a context.DeadlineExceeded error; However I don't see clearly what is wrong exactly; is there any specific bug you wanted to address ?

2023-12-05 01:37 UTC, jiuker commented
> > When we got Client disconnected before response was ready, we can't found that if the client do cancel really.
> > It's a timeout between the minio-servers maybe.
> 
> A timeout is usually a context.DeadlineExceeded error; However I don't see clearly what is wrong exactly; is there any specific bug you wanted to address ?

Yeah. Some issue just log out `Client disconnected before response was ready` at `PutObjectPart`. There have two ways to log this. One is client cancel the request, another one is minio-server interval peer call time-out. we can't found that if the client do cancel really for just one error log out. @vadmeste

2023-12-05 10:54 UTC, klauspost requested changes
This is mostly a wrong fix. You are fixing one case, where there are 100 correct ones. 

You need to figure out what is returning the "context canceled" and fix that up at a lower level.

2023-12-05 11:18 UTC, jiuker commented
> This is mostly a wrong fix. You are fixing one case, where there are 100 correct ones.
> 
> You need to figure out what is returning the "context canceled" and fix that up at a lower level.

Yeah. @vadmeste Should have some thoughts here. @klauspost

2023-12-05 11:18 UTC, closed without merging