Add sample web-identitiy-login script and supporting service.
minio/minio pull request #18582
Opened 2023-12-03 03:37 UTC by jamie-pate

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Fixes #18579

## Motivation and Context

In order to use minio for e.g. a terraform backend it would be useful to have a clear 'login' command that works with e.g. oidc

## How to test this PR?

1. Run `dev-init.sh` in the `docs/sts/web-identity-service` directory.
2. Fill in the `.env` file and run `<space>export WI_OP_CLIENT_SECRET=your_secret` into your shell. (to avoid saving it to disk/history)
3. Run `./web-identity.py`
4. Run `./web-identity-login.sh` or connect to the service to log in using OIDC to get STS credentials

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-01-24 07:52 UTC, jiuker approved these changes

2024-01-24 07:58 UTC, jiuker requested changes
Could you use golang instead? I think golang is better. Minio should keep simple.

2024-01-30 18:00 UTC, jamie-pate commented
> Could you use golang instead? I think golang is better. Minio should keep simple.

I could, but I don't have time to rewrite.. if you want to close this and keep it as a PR only then it would still serve the purpose of documenting how this works (just harder to find.)

I used python because the original doc example was python.

2024-04-04 06:06 UTC, harshavardhana commented
Thanks for the PR, @jamie-pate; however, this doesn't look like it should exist on this repo. Please keep this in a separate repo under your name or you can send this to minio/minio-iam-testing repo instead

2024-04-04 06:06 UTC, closed without merging