support LDAP service accounts via SFTP, FTP logins
minio/minio pull request #18599
Opened 2023-12-05 22:51 UTC by harshavardhana

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request, I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
support LDAP service accounts via SFTP, FTP logins

## Motivation and Context
just extending support from LDAP users to service
accounts.

## How to test this PR?
Setup service accounts after LDAP is enabled, you
can use these service accounts via SFTP.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-12-05 23:18 UTC, vadmeste requested changes

2023-12-05 23:18 UTC, vadmeste commented on cmd/ftp-server-driver.go
> +		return true, nil
I think there is a missing check for the service account secret key here

2023-12-06 00:51 UTC, harshavardhana commented on cmd/ftp-server-driver.go
> +		return true, nil
yeah good catch, fixed.

2023-12-06 04:32 UTC, prakashsvmx commented
i have tried the sftp with the LDAP user's service account, it does not login:

LDAP settings:

<details>

```

➜ sftp -P 8022 bobsa@localhost
bobsa@localhost's password: 
Permission denied, please try again.
bobsa@localhost's password: 


➜ mc idp ldap policy attach local22 consoleAdmin --user='uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io'
Attached Policies: [consoleAdmin]
To User: uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io


 ➜ mc admin user svcacct list local22 'uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io'
   Access Key        | Expiry                       
bob-sa               | no-expiry                    
bobsa                | no-expiry                    


 ➜ mc admin user svcacct info local22 bob-sa                                          
AccessKey: bob-sa
ParentUser: uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io
Status: on
Name: 
Description: 
Policy: implied
Expiration: no-expiry



# Parent User login works fine:
➜ sftp -P 8022 bobfisher@localhost 
bobfisher@localhost's password: 
Connected to localhost.
sftp> ls
bob-fisher-bucket  minio-user-bucket  
sftp> exit


 ➜ minio --version                                                                    
minio version DEVELOPMENT.2023-12-06T00-51-47Z (commit-id=69f85658bd698d2c6326b00ffd88403b2193bea3)
Runtime: go1.21.1 linux/amd64
License: GNU AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>
Copyright: 2015-2023 MinIO, Inc.

```
</details>


In server logs , the following is found

<details>

```
API: SYSTEM()
Time: 04:17:07 UTC 12/06/2023
DeploymentID: ca2cf7ec-cbb5-4c76-a4e6-e09533924a41
Error: [ssh: no auth passed yet, Unable to find user DN: User DN for bobsa not found] (*ssh.ServerAuthError)
       4: internal/logger/logonce.go:118:logger.(*logOnceType).logOnceIf()
       3: internal/logger/logonce.go:149:logger.LogOnceIf()
       2: cmd/sftp-server.go:50:cmd.(*sftpLogger).Error()
       1: github.com/minio/pkg/v2@v2.0.4/sftp/sftp.go:212:sftp.(*Server).handleConnection()
```

</details>

2023-12-06 06:11 UTC, shtripat commented
> i have tried the sftp with the LDAP user's service account, it does not login:
> 
> LDAP settings:
> 
> In server logs , the following is found

I hit the same issue as mentioned here while testing with SFTP. Tried FTP as well and with SA login fails but usual user works fine as below

```
$ ftp localhost 8021 
Trying ::1...
Connected to localhost (::1).
220 Welcome to MinIO FTP Server Version='2023-12-06T00:51:47Z' License='GNU AGPLv3'
Name (localhost:shubhendu): bobsa
331 User name ok, password required
Password:
530 Incorrect password, not logged in
Login failed.
ftp> exit
221 Goodbye

$ ftp localhost 8021 
Trying ::1...
Connected to localhost (::1).
220 Welcome to MinIO FTP Server Version='2023-12-06T00:51:47Z' License='GNU AGPLv3'
Name (localhost:shubhendu): bobfisher
331 User name ok, password required
Password:
230 Password ok, continue
Remote system type is UNIX.
Using binary mode to transfer files.
ftp> ls
229 Entering Extended Passive Mode (|||36957|)
150 Opening ASCII mode data connection for file list
drwxrwxrwx 1 nobody nobody            0 Dec  5 12:40 test-bucket
226 Closing data connection, sent 66 bytes
ftp> 
```

2023-12-06 06:17 UTC, harshavardhana commented
> ➜ sftp -P 8022 bobsa@localhost
> bobsa@localhost's password: 
> Permission denied, please try again.
> bobsa@localhost's password: 
> 
> 
> ➜ mc idp ldap policy attach local22 consoleAdmin --user='uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io'
> Attached Policies: [consoleAdmin]
> To User: uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io
> 
> 
>  ➜ mc admin user svcacct list local22 'uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io'
>    Access Key        | Expiry                       
> bob-sa               | no-expiry                    
> bobsa                | no-expiry                    
> 
> 
>  ➜ mc admin user svcacct info local22 bob-sa                                          
> AccessKey: bob-sa
> ParentUser: uid=bobfisher,ou=people,ou=hwengg,dc=min,dc=io
> Status: on
> Name: 
> Description: 
> Policy: implied
> Expiration: no-expiry

your service account accesskey says `bob-sa` you are logging in as `bobsa`

2023-12-06 06:29 UTC, prakashsvmx commented
i created 2 service accounts just to check and tried both, both of them did not work.

2023-12-06 09:36 UTC, harshavardhana commented
> i created 2 service accounts just to check and tried both, both of them did not work. `bob-sa` and `bobsa`

This is fixed properly now, and there was another place where I forgot to add the relevant checks. 

@prakashsvmx @shtripat thanks for taking a look

2023-12-06 09:50 UTC, shtripat approved these changes
LGTM. Verified and both sftp and ftp work as expected with SA creds.

2023-12-06 10:02 UTC, jiuker approved these changes

2023-12-06 10:22 UTC, prakashsvmx approved these changes

2023-12-06 10:27 UTC, zveinn approved these changes

2023-12-06 12:31 UTC, merged