add configuration to limit replication workers
minio/minio pull request #18601
Opened 2023-12-06 03:03 UTC by poornas

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context
Provide option to cap number of replication workers

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-12-06 03:28 UTC, harshavardhana requested changes

2023-12-06 03:28 UTC, harshavardhana commented on internal/config/api/api.go
> +	apiReplicationMaxWorkers   = "replication_workers_max"
```suggestion
	apiReplicationMaxWorkers   = "replication_max_workers"
```

2023-12-06 03:28 UTC, harshavardhana commented on internal/config/api/api.go
> +	EnvAPIReplicationWorkersMax       = "MINIO_API_REPLICATION_MAX_WORKERS"
```suggestion
	EnvAPIReplicationMaxWorkers       = "MINIO_API_REPLICATION_MAX_WORKERS"
```

2023-12-06 03:28 UTC, harshavardhana commented on internal/config/api/api.go
> +	ReplicationMaxWorkers       int           `json:"replication_workers_limit"`
```suggestion
	ReplicationMaxWorkers       int           `json:"replication_max_workers"`
```

2023-12-06 08:26 UTC, harshavardhana approved these changes

2023-12-06 13:52 UTC, shtripat commented on cmd/handler-api.go
> +			MaxWorkers: 500,
Should we define a const for this max value of 500?

2023-12-07 21:20 UTC, krisis commented on cmd/bucket-replication.go
>  				workers := int(math.Min(float64(p.mrfWorkerSize+1), MRFWorkerMaxLimit))
Shouldn't this be,
```suggestion
				workers := int(math.Min(float64(p.mrfWorkerSize+1), maxMRFWorkers))
```

2023-12-07 22:20 UTC, krisis approved these changes

2023-12-08 00:22 UTC, merged