keep DisableContentSha256 as defaut value during mc perf test
minio/minio pull request #18692
Opened 2023-12-21 06:06 UTC by moting9

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
when I use 'mc perf' to test MinIO cluster performance, I found GET result by mc is similar as that by warp, but PUT result by mc is better than that by warp.  I noticed mc put has disabled sha256 by default.

## Motivation and Context
The change is to keep DisableContentSha256 in PutObjectOptions as default value in mc perf test  to align with warp

## How to test this PR?
 ./mc support perf object  myminio/ 

 ./mc admin trace -v myminio     
original PUT request header is:
 X-Amz-Content-Sha256: UNSIGNED-PAYLOAD
new PUT request header is 
 X-Amz-Content-Sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2023-12-21 06:12 UTC, harshavardhana requested changes

2023-12-21 06:12 UTC, harshavardhana commented on cmd/perf-tests.go
> -		DisableContentSha256: true,
This needs to come as a configurable parameter @moting9 - I ended up changing warp https://github.com/minio/warp/pull/292 to have `--disable-sha256-payload`

2023-12-21 08:46 UTC, moting9 commented
Yes, it's better to set "disable-sha256-payload" and "disable-mutlipart" configurable in mc perf, not only to align with warp, but also benefit user to check the performance difference with different parameters.  The change will impact madmin-go, minio, mc with checkin dependency. I will try to do it one by one.

2023-12-25 10:28 UTC, closed without merging

2023-12-25 10:29 UTC, moting9 commented
I made some wrong operations, close this PR and will submit a new PR.