audit: Add the count of drives from where the dangling object is removed
minio/minio pull request #18737
Opened 2024-01-03 22:35 UTC by vadmeste

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Add 'removedFromDrivesCount' to the audit log of a dangling object removal operation.

This means how many drives have been able to successfuly remove the dangling object.

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-01-04 12:42 UTC, shtripat approved these changes
lgtm

2024-01-04 23:04 UTC, harshavardhana requested changes

2024-01-04 23:04 UTC, harshavardhana commented on cmd/erasure-object.go
> +		tags["removedFromDrivesCount"] = removedFromDrivesCount
Better to show exactly which drives we removed this instead of a count

2024-01-05 20:49 UTC, harshavardhana approved these changes

2024-01-05 22:16 UTC, harshavardhana approved these changes

2024-01-05 22:17 UTC, merged