svc: Add env variables for max/default service accounts expiration
minio/minio pull request #18738
Opened 2024-01-04 02:18 UTC by vadmeste

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-01-04 12:44 UTC, shtripat commented on cmd/common-main.go
> +		logger.Fatal(errors.New("TTL cannot be greated than MINIO_IAM_SERVICE_ACCOUNTS_MAX_TTL"), "Unexpected MINIO_IAM_SERVICE_ACCOUNTS_DEFAULT_TTL value")
`%s/greated/greater/g`

2024-01-04 23:03 UTC, harshavardhana requested changes
Who is asking for this ?

2024-01-09 08:58 UTC, harshavardhana commented
@vadmeste While this is okay for the most part, we cannot standardize this kind of approach.  Adding new ENVs for every new feature will not work, and it's hard to document it cleanly.

https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html We should go via this kind of approach where we can indicate that

```
svc:DurationSeconds
```

To be conceptually allowed as per policy this way, we can permanently restrict this per user via a central policy.

2024-01-24 07:26 UTC, harshavardhana commented
Closing this PR since https://github.com/minio/minio/pull/18835 is already sent

2024-01-24 07:26 UTC, closed without merging