Add clientId existing secret option
minio/minio pull request #18768
Opened 2024-01-09 20:35 UTC by thomaspetit

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Currently the OIDC block allows you to use your own kubernetes secret for the `clientSecret`. Sadly no implementation was given for the clientId.  This PR introduces a similar key in the `values` file to what we've seen for the `clientSecret`. As I was hesitant to make a breaking change I kept this one to a minimum.

## Motivation and Context

In both enterprise setups (as well as in my homelab) both `clientId` and `clientSecret`are generated in an automated way by my OIDC provider. The setup that is implemented allows for easy rotation from the UI.

Alternatively we allow for `.Values.env` to be duplicated into an `.Values.envFrom`.

## How to test this PR?

Self explanatory

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-01-11 08:15 UTC, thomaspetit commented
@klauspost @harshavardhana if you mind reviewing this? :grin:

2024-01-12 17:21 UTC, arnouthoebreckx commented
Would be a really nice change as our automation can take automatically retrieve updates to the clientId that does not require editing the values file

2024-01-18 21:52 UTC, thomaspetit commented
@harshavardhana can you and a colleague of yours approve this or provide comments so I can improve the solution? 😁

2024-01-24 07:32 UTC, harshavardhana requested changes

2024-01-24 07:32 UTC, harshavardhana commented on helm/minio/Chart.yaml
> +version: 5.1.0
Please do not change helm chart versions, this is a maintainers job.

2024-01-26 18:02 UTC, thomaspetit commented
@harshavardhana fixed! ☺️

2024-02-04 12:13 UTC, thomaspetit reviewed
Can anyone review and approve? 😁

2024-02-04 12:13 UTC, thomaspetit commented on helm/minio/Chart.yaml
> +version: 5.1.0
Really sorry for the delay (my 2 kids held me hostage last week). I'll fix it right away 😁

2024-02-04 12:13 UTC, thomaspetit commented on helm/minio/Chart.yaml
> +version: 5.1.0
@harshavardhana fixed!

2024-02-10 22:45 UTC, arnouthoebreckx commented
@harshavardhana can anyone of your team please have a look? This change can help our setup greatly

2024-03-03 12:26 UTC, thomaspetit commented
@shtripat @bh4t can you have a look please?

2024-03-03 16:16 UTC, harshavardhana approved these changes

2024-03-03 16:17 UTC, merged