Enable expired-object-all-versions
minio/minio pull request #18954
Opened 2024-02-02 18:41 UTC by shtripat

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?
Test as per https://github.com/minio/mc/pull/4840

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-02-03 22:11 UTC, harshavardhana requested changes
Please add unit tests explain the title of the PR and also add description on the motivation on what it is and how reviewers must test it.

2024-02-05 11:57 UTC, shtripat commented
> Please add unit tests explain the title of the PR and also add description on the motivation on what it is and how reviewers must test it.

Ack. Will do that and update the PR.

2024-02-06 17:38 UTC, harshavardhana approved these changes

2024-02-06 21:12 UTC, vadmeste approved these changes
LGTM

2024-02-06 21:15 UTC, poornas approved these changes

2024-02-06 21:36 UTC, merged