metrics: add replication metrics on proxied requests
minio/minio pull request #18957
Opened 2024-02-02 23:34 UTC by poornas

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?
set up bucket/site replication and see prometheus metrics for `mc stat` or `mc head` on non-existent object/version - the metrics count should reflect proxied requests.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-02-03 22:04 UTC, harshavardhana approved these changes

2024-02-03 22:10 UTC, harshavardhana requested changes

2024-02-03 22:10 UTC, harshavardhana commented on docs/metrics/prometheus/list.md
> +| `minio_bucket_replication_proxied_get_requests_count` | Number of GET requests proxied to replication target                          |
```suggestion
| `minio_bucket_replication_proxied_get_requests_total` | Number of GET requests proxied to replication target                          |
```

2024-02-03 22:10 UTC, harshavardhana commented on docs/metrics/prometheus/list.md
> +| `minio_bucket_replication_proxied_head_requests_count` | Number of HEAD requests proxied to replication target                          |
```suggestion
| `minio_bucket_replication_proxied_head_requests_total` | Number of HEAD requests proxied to replication target                          |
```

2024-02-03 22:10 UTC, harshavardhana commented on docs/metrics/prometheus/list.md
> +| `minio_bucket_replication_proxied_delete_tagging_requests_count` | Number of DELETE requests proxied to replication target                          |
```suggestion
| `minio_bucket_replication_proxied_delete_tagging_requests_total` | Number of DELETE requests proxied to replication target                          |
```

2024-02-03 22:10 UTC, harshavardhana commented on docs/metrics/prometheus/list.md
> +| `minio_bucket_replication_proxied_get_tagging_requests_count` | Number of GET tagging requests proxied to replication target                          |
```suggestion
| `minio_bucket_replication_proxied_get_tagging_requests_total` | Number of GET tagging requests proxied to replication target                          |
```

2024-02-03 22:10 UTC, harshavardhana commented on docs/metrics/prometheus/list.md
> +| `minio_bucket_replication_proxied_put_tagging_requests_count` | Number of PUT tagging requests proxied to replication target                          |
```suggestion
| `minio_bucket_replication_proxied_put_tagging_requests_total` | Number of PUT tagging requests proxied to replication target                          |
```

2024-02-03 22:10 UTC, harshavardhana commented on docs/metrics/prometheus/list.md
> +| `minio_bucket_replication_proxied_put_tagging_requests_count` | Number of PUT tagging requests proxied to replication target                          |
We should also capture the proxies that failed and if the failed is increasing or not.

2024-02-05 19:49 UTC, poornas commented on docs/metrics/prometheus/list.md
> +| `minio_bucket_replication_proxied_put_tagging_requests_count` | Number of PUT tagging requests proxied to replication target                          |
done

2024-02-05 22:10 UTC, harshavardhana requested changes

2024-02-05 22:10 UTC, harshavardhana commented on cmd/metrics-v2.go
> +	proxiedGetTagReqFailed MetricName = "proxied_get_tagging_requests_failures"
```suggestion
	proxiedGetReqFailed    MetricName = "proxied_get_requests_failed"
	proxiedHeadReqFailed   MetricName = "proxied_head_requests_failed"
	proxiedPutTagReqFailed MetricName = "proxied_put_tagging_requests_failed"
	proxiedGetTagReqFailed MetricName = "proxied_get_tagging_requests_failed"
```

Match the name of the metric

2024-02-05 22:11 UTC, harshavardhana requested changes

2024-02-05 22:11 UTC, harshavardhana commented on docs/metrics/prometheus/list.md
> +| `minio_bucket_replication_proxied_get_requests_count` | Number of GET requests proxied to replication target                          |
This list still says _count

2024-02-06 05:55 UTC, kannappanr approved these changes

2024-02-06 06:00 UTC, harshavardhana approved these changes

2024-02-06 06:00 UTC, merged