Add context support to cachevalue
minio/minio pull request #19137
Opened 2024-02-27 01:37 UTC by donatello

## Description

- Also add cache options type, and simplify the exported interface of
the package.

## Motivation and Context

Passing a context value to the Get* method allows quicker cancellation of the update method if the value is no longer needed.

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-02-27 01:45 UTC, donatello commented on cmd/admin-handlers-users.go
> -	dataUsageInfo, _ := bucketStorageCache.Get()
There was a double initialization that is removed here (see bucket-quota.go).

2024-02-27 09:30 UTC, vadmeste approved these changes
LGTM

2024-02-27 11:00 UTC, klauspost requested changes

2024-02-27 11:00 UTC, klauspost commented on cmd/admin-handlers-users.go
> -	dataUsageInfo, _ := bucketStorageCache.Get()
What if it hits here first? Only one will ever be called anyway.

2024-02-27 11:00 UTC, klauspost commented on internal/cachevalue/cache.go
> +				t.update(ctx)
This context cannot be used async - it will likely be canceled before it is done.

2024-02-27 11:00 UTC, klauspost commented on internal/cachevalue/cache.go
> +	t.update(ctx)
The context/lifetime of a request should not affect how the cache is populated.

I looked at this, but actively decided not to go this route. The cache population should not be affected by random cancelation of whatever context happens to be used for the repopulation.

2024-02-27 11:02 UTC, klauspost commented
You are welcome to keep the initialization alternative. But I disagree on propagating the context as being an improvement.

2024-02-27 17:06 UTC, harshavardhana commented
We need the cache to be populated without any hindrance from the top level caller.

2024-02-27 18:01 UTC, donatello commented on cmd/admin-handlers-users.go
> -	dataUsageInfo, _ := bucketStorageCache.Get()
Ah well I thought, the other init spot would always finish first, but I see this is not guaranteed. I'll bring the second init code back and try to remove it in a better way. In server-main.go we initialize many subsystems asynchronously, so perhaps there are more such situations where the subsystem starts getting used before init completes.

2024-02-27 18:26 UTC, donatello commented on internal/cachevalue/cache.go
> +	t.update(ctx)
I wanted to let the caller have some control over how long the Get+Update could take. An update operation could take an unusually long time - it is better to cancel and retry later. We already take steps for this by setting a constant deadline/timeout within the context created inside the update function (where needed). It seems the amount of the constant timeout being set is arbitrary (we usually cannot foresee how long is "long enough" for the operation in question in all kinds of situations and scales) - thus the reason to make it dependent on the request context.

2024-02-27 18:26 UTC, donatello commented
> We need the cache to be populated without any hindrance from the top level caller.

Replied here https://github.com/minio/minio/pull/19137/files#r1504745343

2024-02-27 21:19 UTC, donatello commented
Updated the PR and removed the context passing (we can bring it back if we are convinced). Added the duplicate initialization as well.

2024-02-28 13:30 UTC, klauspost approved these changes

2024-02-28 13:52 UTC, vadmeste approved these changes

2024-02-28 17:09 UTC, merged