fix: crash on 32bit systems during pre-allocation
minio/minio pull request #19225
Opened 2024-03-07 22:45 UTC by harshavardhana

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
fix: crash on 32bit systems during pre-allocation

## Motivation and Context
pre-allocate < 2GiB on 32bit systems

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-03-07 22:58 UTC, poornas requested changes

2024-03-07 22:58 UTC, poornas commented on cmd/handler-api.go
> +			available = limit * (3 / 4)
```suggestion
			available = uint64(float64(limit)*.75)
```

2024-03-07 22:58 UTC, poornas commented on cmd/handler-api.go
> +	available = memStats.Available * (3 / 4)
```suggestion
	available =  uint64(float64(memStats.Available)*.75)
```

2024-03-08 08:03 UTC, klauspost commented on cmd/handler-api.go
> +	available = memStats.Available * (3 / 4)
```suggestion
	available = (memStats.Available * 3) / 4
```
parenthesis for clarity

2024-03-08 08:03 UTC, klauspost commented on cmd/handler-api.go
> +			available = limit * (3 / 4)
```suggestion
			available = (limit * 3) / 4
```

2024-03-08 11:25 UTC, klauspost approved these changes

2024-03-08 13:45 UTC, vadmeste approved these changes
LGTM

2024-03-08 13:55 UTC, merged