batch rotate filter() must return true to skip the matching objects
minio/minio pull request #19291
Opened 2024-03-18 22:38 UTC by harshavardhana

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
batch rotate filter() must return true to skip the matching objects

## Motivation and Context
the current implementation was doing the reverse

## How to test this PR?
```yaml

Harshavardhana11:44 AM
check

mc batch status myminio/ H4HAJ9QnGVErdpsq6cEQyp:0 

V
Vishal Verma11:47 AM
$ mc batch start myminio test.yml; mc batch list myminio
Successfully started 'keyrotate' job `ZGUojMKLdNADLaNFbQjtSm:0` on '2024-03-18 18:47:11.140618022 +0000 UTC'
currently no jobs are running
$ mc batch status myminio ZGUojMKLdNADLaNFbQjtSm:0
mc: Unable to find an active job, attempting to list from previously run jobs
✔ ✔ ✔

Harshavardhana11:48 AM
yeah this looks like wrong

@Poorna can you please take a loook?

V
Vishal Verma11:49 AM
probably returning an error when validating maybe there is some debug flag ?

Edited by Vishal Verma Today at 11:49 AM.

Harshavardhana12:10 PM
no not really @Vishal Verma

its not running properly

can you remove createdAfter ?

V
Vishal Verma12:15 PM
hmm same thing:

$ mc batch start myminio test.yml; mc batch list myminio
Successfully started 'keyrotate' job `VcyRgrXJdyCvSbN4fCRWYj:0` on '2024-03-18 19:14:28.392297208 +0000 UTC'
currently no jobs are running
keyrotate:
  apiVersion: v1
  bucket: heal-bucket1-0
  encryption:
    type: sse-kms # valid values are sse-s3 and sse-kms
    key: "my-minio-sse-kms-key" # valid only for sse-kms

  # optional flags based filtering criteria
  # for all objects
  flags:
    filter:
      #createdAfter: "2024-03-10T15:04:05Z" # match objects created after "date"
      kmskey: "my-minio-sse-kms-key" # match objects with KMS key-id (applicable only for sse-kms)
    retry:
      attempts: 10 # number of retries for the job before giving up
      delay: "500ms" # least amount of delay between each retry
just to verify SSE-KMS:

$ mc stat myminio/heal-bucket1-0/ 
Name      : object-1-16777216
Date      : 2024-03-18 19:15:59 UTC
Size      : 16 MiB
ETag      : 71ff344a1c5f4fd9b7dbb03d2d13d196-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream

Name      : object-2-16777216
Date      : 2024-03-18 19:15:59 UTC
Size      : 16 MiB
ETag      : 1705205c9d66baa6a4e215851802fb07-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream

Name      : object-3-16777216
Date      : 2024-03-18 19:15:59 UTC
Size      : 16 MiB
ETag      : 3ca4be20e40abe038e1e4843bf279dab-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream

Name      : object-4-16777216
Date      : 2024-03-18 19:15:59 UTC
Size      : 16 MiB
ETag      : 3221e30f7b0ae911b9d767df625c6b2a-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream

Name      : object-5-16777216
Date      : 2024-03-18 19:15:59 UTC
Size      : 16 MiB
ETag      : 439f27854c6444f2332b9c655b7bb9e9-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream
Edited by Vishal Verma Today at 12:19 PM.
oh actually the Date is getting updated after I spawn the roration job:

$ mc stat myminio/heal-bucket1-0/
Name      : object-1-16777216
Date      : 2024-03-18 19:20:08 UTC
Size      : 16 MiB
ETag      : 71ff344a1c5f4fd9b7dbb03d2d13d196-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream

Name      : object-2-16777216
Date      : 2024-03-18 19:20:08 UTC
Size      : 16 MiB
ETag      : 1705205c9d66baa6a4e215851802fb07-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream

Name      : object-3-16777216
Date      : 2024-03-18 19:20:08 UTC
Size      : 16 MiB
ETag      : 3ca4be20e40abe038e1e4843bf279dab-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream

Name      : object-4-16777216
Date      : 2024-03-18 19:20:08 UTC
Size      : 16 MiB
ETag      : 3221e30f7b0ae911b9d767df625c6b2a-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream

Name      : object-5-16777216
Date      : 2024-03-18 19:20:08 UTC
Size      : 16 MiB
ETag      : 439f27854c6444f2332b9c655b7bb9e9-1
Type      : file
Encryption: SSE-KMS (arn:aws:kms:my-minio-sse-kms-key)
Metadata  :
  Content-Type: application/octet-stream
Edited by Vishal Verma Today at 12:22 PM.
minio-user@pdx05-c01-swds025:/mnt/disk6/heal-bucket1-0/object-2-16777216$ ls -lrt
total 4
drwxr-xr-x 2 minio minio   28 Mar 18 17:57 e9b52c79-a0be-4d5c-a533-3b3602cbcf9b
-rw-r--r-- 1 minio minio 1139 Mar 18 19:23 xl.meta

minio-user@pdx05-c01-swds025:/mnt/disk6/heal-bucket1-0/object-2-16777216$ mc batch start myminio /home/minio-user/test.yml
Successfully started 'keyrotate' job `ate7CgK5uDAg6Xb3EGgZin:0` on '2024-03-18 19:24:26.462431386 +0000 UTC'
minio-user@pdx05-c01-swds025:/mnt/disk6/heal-bucket1-0/object-2-16777216$ ls -lrt
total 4
drwxr-xr-x 2 minio minio   28 Mar 18 17:57 e9b52c79-a0be-4d5c-a533-3b3602cbcf9b
-rw-r--r-- 1 minio minio 1139 Mar 18 19:24 xl.meta
I specified: createdAfter: "2025-03-02T15:04:05Z" and still saw metadata getting update for the object within the bucket specified

Kaan Kabalak01:07 PM
Understood @Vishal Verma, we will keep you updated 👍

V
Vishal Verma01:12 PM
its actually this code:

if !r.Flags.Filter.CreatedAfter.IsZero() && r.Flags.Filter.CreatedAfter.Before(info.ModTime) {
                        // skip all objects that are created before the specified time.
                        return false
                }

                if !r.Flags.Filter.CreatedBefore.IsZero() && r.Flags.Filter.CreatedBefore.After(info.ModTime) {
                        // skip all objects that are created after the specified time.
                        return false
                }
but its working inversely i.e its rotating keys for objects that were created before specified createdAfter

K
Kannappan01:39 PM
Are you unable to see key rotation working? Let me try this out quickly locally and get back to you

V
Vishal Verma01:40 PM
how can I verify? I can see metadata gets updated

Harshavardhana01:47 PM
I think you can stop experimenting more on this

We will have to sit and see what all is working and what is not.

V
Vishal Verma02:01 PM
ack- we need this feature for production

Harshavardhana02:50 PM
Sure

V
Vishal Verma02:53 PM
and I think it is working just some interpretation/clarification is needed

Harshavardhana02:56 PM
Does the final object have the new key?

V
Vishal Verma02:56 PM
dumb q: how to check this?

as in we have auto encryption on and using root key in the KMS vault

what I think is this code needs a flip:
https://github.com/minio/minio/blob/master/cmd/batch-rotate.go#L288:L296

Harshavardhana03:26 PM
mc stat alias/bucket/<object>

would show new key if its sse-kms

wait looks like its working, you are not even trying to rotate

  kmskey: "my-minio-sse-kms-key" # match objects with KMS key-id (applicable only for sse-kms)
your key is basically the same?

Edited by Harshavardhana Today at 03:27 PM.

V
Vishal Verma03:29 PM
yes!

oh sorry I removed this

Harshavardhana03:30 PM
yeah this won't do anything

V
Vishal Verma03:30 PM
keyrotate:
  apiVersion: v1
  bucket: heal-bucket1-1
  encryption:
    type: sse-kms # valid values are sse-s3 and sse-kms
    key: "my-minio-sse-kms-key" # valid only for sse-kms

  # optional flags  [...]

2024-03-18 23:55 UTC, poornas requested changes

2024-03-18 23:55 UTC, poornas commented on cmd/batch-rotate.go
> +			return true
skip was written this way to filter by more than one criteria - e.g. metadata match and creation date criteria, which will not work with this change prematurely matching just one.  Perhaps just invert previous when passing to Walk Filter opts?

2024-03-19 04:45 UTC, poornas approved these changes

2024-03-19 10:23 UTC, vadmeste requested changes

2024-03-19 10:23 UTC, vadmeste commented on cmd/batch-rotate.go
> +			if v, ok := info.Metadata[xhttp.AmzServerSideEncryptionKmsID]; ok && strings.TrimPrefix(v, crypto.ARNPrefix) == r.Flags.Filter.KMSKeyID {
I do not think this is correct. It is correct to rename skip to select object, but here we are returning false when the kms key id matches?

2024-03-19 20:58 UTC, closed without merging