feat: add env to choose which node to decom
minio/minio pull request #19310
Opened 2024-03-21 10:11 UTC by jiuker

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

now is always choose the first pool first endpoint to decom

but if someone have a broken endpoint, the user need to fix that node to keep decom go on always.

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (19001)https://github.com/minio/minio/issues/19001
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-03-21 10:49 UTC, shtripat commented
@jiuker can you please add verification steps for PR?
Is it like bring a distributed multi node, multi pool setup and bring down the first node of first pool, and then try decom operation?

2024-03-21 14:34 UTC, jiuker commented
> @jiuker can you please add verification steps for PR? Is it like bring a distributed multi node, multi pool setup and bring down the first node of first pool, and then try decom operation?

1. Deploy minio with two pools with two nodes. (Env:  _MINIO_DECOM_ENDPOINT: The second endpoint.)
2. mc alias set minio firstEndPoint user password.
3. use console to create bucket and uploads file 
4. mc admin decommission minio start firstCmd.

Without this pr The decommission will start at first pool and first endpoint.
This pr is made that you can set the second endpoint to do the decommission for if first endpoint have a broken status.
@shtripat

2024-03-22 19:28 UTC, harshavardhana requested changes

2024-03-22 19:28 UTC, harshavardhana commented on cmd/admin-handlers-pools.go
> +	ep := os.Getenv("_MINIO_DECOM_ENDPOINT")
This is temporary for now - we will add a more official one later.
```suggestion
	host := env.Get("_MINIO_DECOM_ENDPOINT_HOST", "")
```

2024-03-22 19:28 UTC, harshavardhana commented on cmd/admin-handlers-pools.go
> +			if proxyEp.Endpoint.String() == ep && !proxyEp.IsLocal {
```suggestion
			if proxyEp.Endpoint.Host == host && !proxyEp.IsLocal {
```

2024-03-22 19:28 UTC, harshavardhana commented on cmd/admin-handlers-pools.go
> +	if ep != "" {
```suggestion
	if host != "" {
```

2024-03-26 18:57 UTC, harshavardhana reviewed
A bit of simplification

2024-03-26 18:57 UTC, harshavardhana commented on cmd/admin-handlers-pools.go
> +}
```suggestion
	host := env.Get("_MINIO_DECOM_ENDPOINT_HOST", defaultEndPoint.Host)
	if host == "" {
	        return false
	}
	for nodeIdx, proxyEp := range globalProxyEndpoints {
		if proxyEp.Endpoint.Host == host && !proxyEp.IsLocal {
			if proxyRequestByNodeIndex(ctx, w, r, nodeIdx) {
				return true
			}
		}
	}
	return false
}
```

2024-03-27 23:17 UTC, harshavardhana approved these changes

2024-03-27 23:18 UTC, merged

2024-04-03 08:32 UTC, broferek commented
Hi @jiuker @harshavardhana 

I have upgraded my cluster to the latest release which includes this PR.

I'm trying testing this new env var but I'm struggling with it.

What should be the expected value of the new var _MINIO_DECOM_ENDPOINT_HOST ?

Say I have 2 pools like dc1_node{1...8} and dc2_node{1...16}.

Without setting the var, dc1_node1 is chosen by default to be the responsible of the decommission.

So if I want another host to do the decom, should I set the var to :
- dc2_node1
- https://dc2_node1:9000
- dc2_node{1...16}
- etc ...

Thanks for your answer

2024-04-03 09:04 UTC, jiuker commented
> * dc2_node1

dc2_node1 I think. Just host. @broferek