use bigger partSize per part for tiering to MinIO
minio/minio pull request #19361
Opened 2024-03-27 23:13 UTC by harshavardhana

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
use bigger partSize per part for tiering to MinIO

## Motivation and Context
Bonus: Remove the persistent md5sum calculation and 
turn off sha256 as well. Instead, we always enable crc32c, 
which is enough for payload verification and 
supports trailing header checksum.

## How to test this PR?
Tiering must work as is CI/CD should help

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-03-27 23:56 UTC, poornas requested changes

2024-03-27 23:56 UTC, poornas commented on cmd/warm-backend-s3.go
> +	SendContentMd5 bool
this is not used?

2024-03-28 01:08 UTC, harshavardhana commented on cmd/warm-backend-s3.go
> +	SendContentMd5 bool
hmm no it won't be needed.

2024-03-28 01:31 UTC, poornas approved these changes

2024-03-28 04:37 UTC, krisis approved these changes

2024-03-28 06:45 UTC, merged