feat: add memlimit flags for setMaxResources
minio/minio pull request #19400
Opened 2024-04-03 07:33 UTC by jiuker

feat: add memlimit flags for runtime

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

add memlimit flags for setMaxResources

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-04-03 08:02 UTC, shtripat reviewed
Mostly looks good. A simple suggestion.

2024-04-03 08:02 UTC, shtripat commented on cmd/server-rlimit.go
> +	return nil
```suggestion
        if ctx == nil {
            return nil
        }
	if ctx.IsSet("memlimit") {
		memlimit := ctx.String("memlimit")
		if memlimit == "" {
			memlimit = ctx.GlobalString("memlimit")
		}
		mlimit, err := humanize.ParseBytes(memlimit)
		if err != nil {
			return err
		}
		debug.SetMemoryLimit(int64(mlimit))
	}
	return nil
```

2024-04-03 08:51 UTC, shtripat approved these changes
lgtm

2024-04-03 13:32 UTC, vadmeste requested changes

2024-04-03 13:32 UTC, vadmeste commented on cmd/server-rlimit.go
> +	if ctx.IsSet("memlimit") {
I do not see memlimit flag defined anywhere, you need to define it ServerFlags in server-main.go

2024-04-03 18:31 UTC, harshavardhana requested changes

2024-04-03 18:31 UTC, harshavardhana commented on cmd/server-main.go
> +		Usage:  "set debug memory limit instead of GOMEMLIMIT env",
```suggestion
		Usage:  "set global memory limit per server via GOMEMLIMIT",
```

2024-04-04 08:22 UTC, harshavardhana approved these changes

2024-04-04 08:23 UTC, harshavardhana requested changes

2024-04-04 08:23 UTC, harshavardhana commented on cmd/server-main.go
> +		Hidden: true,
```suggestion
		Hidden: true,
		EnvVar: "MINIO_MEMLIMIT",
```

2024-04-04 12:06 UTC, harshavardhana approved these changes

2024-04-04 12:06 UTC, merged