fix: ldap: use validated base DNs
minio/minio pull request #19406
Opened 2024-04-03 18:11 UTC by donatello

## Description

This fixes a regression from #19358 which prevents policy mappings created in the latest release from being displayed in policy entity listing APIs.

This is due to the possibility that the base DNs in the LDAP config are not in a normalized form and #19358 introduced normalized of mapping keys (user DNs and group DNs). When listing, we check if the policy mappings are on entities that parse as valid DNs that are descendants of the base DNs in the config.

## Motivation and Context

## How to test this PR?

Use a non-normalized DN in the base DN config like `DC=min,dc=io` instead of `dc=min,dc=io` for example.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (#19358)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-04-03 18:17 UTC, harshavardhana requested changes
Can you add some unit tests to cover this scenario?

2024-04-03 18:40 UTC, donatello commented
Needs https://github.com/minio/pkg/pull/106

2024-04-04 06:33 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/pkg/v2 => github.com/donatello/pkg/v2 v2.0.0-20240403174644-37c5f6a91d42
```suggestion
replace github.com/minio/pkg/v2 => github.com/donatello/pkg/v2 v2.0.0-20240403174644-37c5f6a91d42
```

v2.0.16 released

2024-04-04 09:23 UTC, vadmeste reviewed
LGTM, except the import in go.mod as mentionned by Harsha

2024-04-04 16:50 UTC, harshavardhana approved these changes

2024-04-04 18:36 UTC, merged