Added new API errors for LDAP
minio/minio pull request #19415
Opened 2024-04-05 00:00 UTC by taran-p

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Adds API errors:
If LDAP is not enabled with an LDAP command
If LDAP short username is expected but DN is given

Uses these in the code

## Motivation and Context
Currently these known errors return as internal errors

## How to test this PR?
`mc idp ldap accesskey create` with LDAP not enabled, with incorrect username, or with a DN
`mc idp ldap policy attach/detach` with LDAP not enabled

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-04-05 09:23 UTC, vadmeste approved these changes
LGTM

2024-04-05 15:59 UTC, donatello requested changes

2024-04-05 15:59 UTC, donatello commented on cmd/api-errors.go
> +	ErrAdminLDAPExpectedShortName
Could you change this to login name? Short name is an internal term.

2024-04-05 15:59 UTC, donatello commented on cmd/api-errors.go
> +		Description:    "Expected LDAP short username but was given full DN.",
Here as well. Use Login username

2024-04-05 15:59 UTC, donatello commented on cmd/admin-handlers-idp-ldap.go
> +			if strings.Contains(err.Error(), "not found") {
Not found may not be specific enough here. Our ldap wrapper library returns a more specific DN not found or similar, could you use that instead?

2024-04-06 01:19 UTC, harshavardhana approved these changes

2024-04-06 05:25 UTC, donatello approved these changes

2024-04-06 05:26 UTC, merged