Add cluster config metrics in metrics-v3
minio/minio pull request #19507
Opened 2024-04-15 14:14 UTC by anjalshireesh

## Community Contribution License

All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

endpoint: /minio/metrics/v3/cluster/config
metrics:
- write_quorum
- rrs_parity
- standard_parity

## Motivation and Context

https://github.com/miniohq/engineering/issues/1510

## How to test this PR?

`mc admin prometheus metrics <alias> system`

should return the new cluster config related metrics
(will need some changes in mc to invoke the metrics-v3 api)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [x] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-04-17 09:24 UTC, vadmeste commented on cmd/metrics-v3-cluster-config.go
> +	clusterDriveMetrics, _ := c.clusterDriveMetrics.Get()
Do we really need to ignore this error ?

2024-04-17 09:24 UTC, vadmeste commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
Let's return an error if objLayer is nil

2024-04-17 09:31 UTC, harshavardhana commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
That must be done centrally before even coming here.

2024-04-17 10:44 UTC, anjalshireesh commented on cmd/metrics-v3-cluster-config.go
> +	clusterDriveMetrics, _ := c.clusterDriveMetrics.Get()
@vadmeste my understanding is that `Get()` will always return a value (either already cached one or a newly retrieved one), so the error can be ignored here, but I could be wrong. I've taken this code from `metrics-v3-cluster-health.go`

@donatello can you please confirm what's the right way?

2024-04-17 10:50 UTC, anjalshireesh commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
@vadmeste for now changing to use it only if not `nil`

@harshavardhana I didn't understand, could you please elaborate?

2024-04-26 07:47 UTC, minio-trusted commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
mainly look at metrics-v2.go object layer is checked centrally to avoid passing a nil before populating the values.

2024-04-26 14:33 UTC, anjalshireesh commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
Thanks @harshavardhana , I've added logic to centrally check if the obj layer is initialized (when the metric group needs it).

This is done at the metric group level, similar to metrics-v2. One issue with this is that, none of the metrics from that group will be loaded till the obj layer is initialized, even when some of them don't really depend on the obj layer e.g. the `standard_parity` and `rrs_parity` in this case.

Let me know what you think..

2024-04-28 10:10 UTC, harshavardhana requested changes

2024-04-28 10:10 UTC, harshavardhana commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
``` suggestion
	objLayer := newObjectLayerFn()
```

This can be nil; pass this via `loader()` as an optional value.

2024-04-28 10:10 UTC, harshavardhana commented on cmd/metrics-v3-types.go
> +func (mg *MetricsGroup) requiresObjectLayer(labels ...string) *MetricsGroup {
why label input?

2024-04-28 13:39 UTC, anjalshireesh commented on cmd/metrics-v3-types.go
> +func (mg *MetricsGroup) requiresObjectLayer(labels ...string) *MetricsGroup {
thanks, removed

2024-04-28 13:41 UTC, anjalshireesh commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
the function will not be called when objLayer is not initialized; so it cannot be nil here.

2024-04-28 16:45 UTC, harshavardhana commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
Yeah but that is a very ugly style. In future when this code will move elsewhere it will crash.

2024-04-29 04:28 UTC, anjalshireesh commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
@harshavardhana I added the central checking because of this comment: https://github.com/minio/minio/pull/19507#discussion_r1580620169

> mainly look at metrics-v2.go object layer is checked centrally to avoid passing a nil before populating the values.

Did I misunderstand it? If so, and if that's not required, then the previous code should just work fine? something like

```
objLayer := newObjectLayerFn()
if objLayer != nil {
 // load metrics
}
```

2024-04-29 13:00 UTC, anjalshireesh commented on cmd/metrics-v3-cluster-config.go
> +	objLayer := newObjectLayerFn()
@harshavardhana I found that the the metric for which I was using `objLayer` (`write_quorum`) is already implemented under `/cluster/erasure-set` and would have become a duplicate here. So I have removed this metric (and other changes related to it) altogether from this PR.

2024-05-06 16:07 UTC, shtripat commented on cmd/metrics-v3-cluster-config.go
> +	configWriteQuorum    = "write_quorum"
don't see populating this metric. needed?

2024-05-13 14:23 UTC, anjalshireesh commented on cmd/metrics-v3-cluster-config.go
> +	configWriteQuorum    = "write_quorum"
@shtripat thanks, removed.

2024-05-13 16:33 UTC, shtripat approved these changes
lgtm

2024-05-14 09:48 UTC, klauspost approved these changes

2024-05-23 16:42 UTC, harshavardhana approved these changes

2024-05-24 12:50 UTC, merged