allow caller context during reloads() to cancel
minio/minio pull request #19687
Opened 2024-05-07 07:44 UTC by harshavardhana

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
allow caller context during reloads() to cancel

## Motivation and Context

Canceled callers might linger around longer
and can potentially overwhelm the system. Instead,
provider a caller context, and canceled callers
don't hold on to them.
    
Bonus: we have no reason to cache errors; we should
never cache errors otherwise, we can potentially have
quorum errors creeping in unexpectedly. We should
let the cache, when invalidating, hit the actual resources
instead.

## How to test this PR?
Add faster client timeouts, retries
and observe the goroutine build-up on the server.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-05-07 10:13 UTC, vadmeste reviewed
Compilation issue for _test.go but other LGTM

2024-05-07 10:46 UTC, klauspost reviewed
AFAICT This would cause a call with a canceled context to stick for the TTL of the cache.

That seems to me like it would de-stabilize running systems. Caller contexts can be canceled at any time for any reason.

I see it would be nice if a canceled context would make the caller return, but it shouldn't be coupled to the validity of the cached value.

2024-05-07 10:55 UTC, klauspost requested changes
Much simpler is just to add...
```
// GetCtx will return a cached value or fetch a new one.
// The fetch can be cancelled by the context.
func (t *Cache[T]) GetCtx(ctx context.Context) (T, error) {
	var resErr error
	var resVal T
	getDone := make(chan T)
	go func() {
		defer close(getDone)
		resVal, resErr = t.Get()
	}()
	select {
	case <-ctx.Done():
		var t T
		return t, ctx.Err()
	case <-getDone:
		return resVal, resErr
	}
}
```

2024-05-07 17:35 UTC, harshavardhana commented
> AFAICT This would cause a call with a canceled context to stick for the TTL of the cache.
> 
> That seems to me like it would de-stabilize running systems. Caller contexts can be canceled at any time for any reason.
> 
> I see it would be nice if a canceled context would make the caller return, but it shouldn't be coupled to the validity of the cached value.

how? the context is only honored for the update() operation, otherwise we will be returning cached values. 

Unlike previous behavior, where we incorrectly passed a cached context, we are not caching the context anymore, so I don't see how this is destabilizing in any manner. 

Remember, I am still not passing the passed context when `NoWait: true` to avoid passing a possible canceled context into a goroutine. 

Instead, it is still passing context.Background() to update the value in a non-blocking manner. However, for the places where `NoWait: false` we apply caller context to ensure that
The resources will be relinquished right away if the caller is gone.

makes sense?

2024-05-07 17:38 UTC, harshavardhana commented
you can always pass context.Background() to have this fully blocking and governed via any specific timeout each cached value might have.

2024-05-07 19:44 UTC, klauspost commented
My main concern is that the update function should be invariant to the caller context. I will review tomorrow.

2024-05-07 19:49 UTC, harshavardhana commented
> My main concern is that the update function should be invariant to the caller context. I will review tomorrow.

I also removed caching of errors, I saw a case where DiskInfo() will keep returning context.Deadline error which is not expected since we want the call to be made fresh upon such errors.

An update() error must be returned unless caller asks for ReportLastGood copy.

2024-05-08 16:05 UTC, harshavardhana commented
PTAL @klauspost @vadmeste

2024-05-08 16:21 UTC, vadmeste approved these changes
LGTM

2024-05-08 21:08 UTC, poornas approved these changes

2024-05-09 00:51 UTC, merged