Consolidate drive health related metrics into single metric
minio/minio pull request #19706
Opened 2024-05-09 13:54 UTC by anjalshireesh

## Community Contribution License

All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Instead of having "online" and "healing" as two metrics, replace with a single metric "health" which can have following values:

0 = offline
1 = healthy
2 = healing

## Motivation and Context

better metrics

## How to test this PR?

`curl "http://<endpoint>/minio/metrics/v3/system/drive"`

should return a new metric `minio_system_drive_health` in place of the two erstwhile metrics `minio_system_drive_online` and `minio_system_drive_healing` 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [x] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-05-09 18:20 UTC, harshavardhana approved these changes

2024-05-09 18:57 UTC, donatello requested changes
Using an "enum" here doesn't seem very understandable. If this metric is graphed, it seems more complicated to understand - why do we need to do this? At the very least, it seems better to let the numbers indicate health value (higher => more healthy in a sense):
0 -> offline 
1 -> healing
2 -> healthy

2024-05-10 05:28 UTC, donatello approved these changes

2024-05-10 12:04 UTC, shtripat approved these changes
lgtm

2024-05-12 17:23 UTC, merged