Added tests for resiliency check
minio/minio pull request #19947
Opened 2024-06-18 16:15 UTC by shtripat

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Runs `mint` tests in a loop for multiple rounds to make sure it all goes fine without any errors with 503 response

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-10-01 12:42 UTC, zveinn approved these changes

2024-10-28 10:36 UTC, klauspost commented
@shtripat Ready for review?

2024-10-28 10:47 UTC, shtripat commented
> @shtripat Ready for review?

This was idea to have mint runs in rounds for stress and resiliency test. If we are fine for this long running test, its actually ready.

2024-12-19 23:19 UTC, allanrogerr requested changes
This PR doesnt seem valid any more. I am moving the tests from https://github.com/miniohq/aistor-operator/tree/master/testing/resiliency-tests to this repo.

2025-01-05 15:35 UTC, allanrogerr commented
@shtripat PTAL

2025-01-06 03:47 UTC, shtripat commented
> @shtripat PTAL

We can close this.

2025-01-06 04:15 UTC, closed without merging