info: Always refresh the root disk status
minio/minio pull request #20023
Opened 2024-07-01 14:13 UTC by vadmeste

Add root drive status in the disk info cache function, so unmounting a drive without restarting a local node reflects the correct value.

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-07-01 15:07 UTC, harshavardhana requested changes

2024-07-01 15:07 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/madmin-go/v3 => github.com/vadmeste/madmin-go/v3 v3.0.0-20240701132159-8d7ae8baee2e
you can remove this.

2024-07-01 22:03 UTC, harshavardhana approved these changes

2024-07-01 22:03 UTC, harshavardhana commented
PTAL at the conflicts @vadmeste

2024-07-02 09:33 UTC, harshavardhana approved these changes

2024-07-02 18:24 UTC, poornas approved these changes

2024-07-02 20:41 UTC, merged