Allow a KMS Action to specify keys in the Resources of a policy
minio/minio pull request #20079
Opened 2024-07-12 03:06 UTC by marktheunissen

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

With this PR, policies that specify resources for KMS actions will match on those resources, e.g:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "kms:CreateKey",
                "kms:KeyStatus",
                "kms:ListKeys"
            ],
            "Resource": [
                "arn:minio:kms:::keys-abc-*",
                "arn:minio:kms:::myuser-*"
            ]
        }
    ]
}
```

This PR also adds tests for all handlers that are involved with KMS and adds some test coverage that wasn't there before

## Motivation and Context

`kms:` actions currently disregard Resources, users have asked for restrictions to be applied to these KMS actions.

## How to test this PR?

- Needs https://github.com/minio/pkg/pull/121
- Apply a policy as above
- `mc admin kms key create ALIAS KEYNAME`
- `mc admin kms key status ALIAS KEYNAME`
- `mc admin kms key list ALIAS`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-07-12 03:07 UTC, marktheunissen commented on go.mod
> +replace github.com/minio/pkg/v3 => github.com/marktheunissen/pkg v0.0.0-20240712-307f039
Remove before merge

2024-07-12 14:37 UTC, klauspost reviewed
👍🏼 LGTM. Will do final review when upstream is merged and this is out of Draft.

2024-07-15 16:12 UTC, harshavardhana requested changes

2024-07-15 16:12 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/pkg/v3 => github.com/marktheunissen/pkg/v3 v3.0.0-20240715013114-8e0d6a8ddddd
You can point to master now

2024-07-15 23:58 UTC, marktheunissen commented
We need a new tag (v3.0.8) on pkg repo, is that a process done manually or by a bot somewhere?

2024-07-16 07:55 UTC, harshavardhana approved these changes

2024-07-16 08:53 UTC, klauspost approved these changes

2024-07-16 14:03 UTC, merged