ListKeys will now return CreatedBy and CreatedAt when information is …
minio/minio pull request #20223
Opened 2024-08-07 03:03 UTC by marktheunissen

…available

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Return the metadata about the key in ListKeys, when available.

Fixes https://github.com/minio/minio/issues/20132

## Motivation and Context

> The KMSListKeysHandler returns a structure that holds the CreatedBy and CreatedAt fields, but these are never filled by the KMSListKeysHandler. Code must be updated, so these fields are properly filled for MinKMS and KES (when possible).

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-08-07 04:15 UTC, marktheunissen commented on internal/kms/kes.go
> +	return keyInfos, continueAt, nil
Manually tested this one with KES on play.min.io

2024-08-07 04:57 UTC, marktheunissen commented on internal/kms/kms.go
> +		keyInfos[i].CreatedAt = fmt.Sprintf("%d", v.CreatedAt.Unix())
I'm using unix timestamp for this format, let me know if it should be something else.

2024-08-07 04:57 UTC, marktheunissen commented on internal/kms/kms.go
> +	return keyInfos, resp.ContinueAt, nil
Tested this with a local KMS server

2024-08-07 09:00 UTC, klauspost commented on internal/kms/kms.go
> +		keyInfos[i].CreatedAt = fmt.Sprintf("%d", v.CreatedAt.Unix())
`v.CreatedAt.Format(time.RFC3339)`?

Not really sure why `madmin.KMSKeyInfo.CreatedAt` isn't a time.Time field.

2024-08-07 12:33 UTC, ramondeklein approved these changes
We may consider changing the API for CreatedAt, because using a string is silly.

2024-08-07 12:33 UTC, ramondeklein commented on internal/kms/kms.go
> +		keyInfos[i].CreatedAt = fmt.Sprintf("%d", v.CreatedAt.Unix())
Can't we just change this type to a time.Time field? That breaks the API, but this call never returned something before, so I doubt if that would be an issue.

2024-08-08 03:28 UTC, marktheunissen commented on internal/kms/kms.go
> +		keyInfos[i].CreatedAt = fmt.Sprintf("%d", v.CreatedAt.Unix())
Yes we can, it just pushes the conversion to a `string` out into the console, which ultimately needs to do so in order to render the JSON response. The PR to make this change is here: https://github.com/minio/console/pull/3421/files

KMSKeyInfo.CreatedAt is a string, but so are all the other `CreatedAt` fields for those KMS structs. To keep them consistent, this PR changes all of them to `time.Time`: https://github.com/minio/madmin-go/pull/296/files

Let me know your thoughts, I think it's good to be consistent in a SDK. It doesn't look like those other ones are used, and might be dead code? For example I can't find a `/minio/kms/v1/policy` or `/minio/kms/v1/identity` route in the MinIO server, yet madmin has methods for those API calls. Am I missing something here?

2024-08-08 03:35 UTC, marktheunissen commented on go.sum
> -github.com/minio/madmin-go/v3 v3.0.59-0.20240725120704-3cfbffc45f08/go.mod h1:IFAwr0XMrdsLovxAdCcuq/eoL4nRuMVQQv0iubJANQw=
TODO: remove

2024-08-08 14:15 UTC, ramondeklein requested changes
Please update `go.mod` references before merging.

2024-08-17 22:02 UTC, harshavardhana approved these changes

2024-08-17 22:02 UTC, harshavardhana commented
Updated the `go.mod` pointing to the latest console master @marktheunissen. Once built, I will merge this.

2024-08-17 23:39 UTC, poornas approved these changes

2024-08-18 06:43 UTC, merged