tier: Add force param to force tiering removal
minio/minio pull request #20355
Opened 2024-08-30 12:39 UTC by vadmeste

REQUIRES https://github.com/minio/mc/pull/5031 and https://github.com/minio/console/pull/3429/ and https://github.com/minio/madmin-go/pull/301

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description
Currently, it is not possible to remove a tier if it is not accessible or contains some data, add a force flag to make the removal successful in that case.

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-09-06 20:41 UTC, harshavardhana requested changes

2024-09-06 20:41 UTC, harshavardhana commented on go.mod
> +replace github.com/minio/mc => github.com/vadmeste/mc v0.0.0-20240905090634-fcb235b9b149 // github.com/vadmeste/mc v0.0.0-20240830121251-777f349abd74
please fix the dependency

2024-09-12 15:44 UTC, harshavardhana approved these changes

2024-09-12 20:37 UTC, krisis approved these changes

2024-09-12 20:44 UTC, merged