run IAM purge routines deterministically every hr
minio/minio pull request #20587
Opened 2024-10-27 02:17 UTC by donatello

## Community Contribution License
All community contributions in this pull request are licensed to the project maintainers
under the terms of the [Apache 2 license](https://www.apache.org/licenses/LICENSE-2.0). 
By creating this pull request I represent that I have the right to license the 
contributions to the project maintainers under the Apache 2 license.

## Description

Existing implementation runs IAM purge routines for expired LDAP and OIDC accounts with a probability of 0.25 after every IAM refresh. This change ensures that they are run once in each hour.

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Optimization (provides speedup with no functional changes)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Unit tests added/updated
- [ ] Internal documentation updated
- [ ] Create a documentation update request [here](https://github.com/minio/docs/issues/new?label=doc-change,title=Doc+Updated+Needed+For+PR+github.com%2fminio%2fminio%2fpull%2fNNNNN)

2024-10-28 01:10 UTC, taran-p requested changes

2024-10-28 01:10 UTC, taran-p commented on cmd/iam.go
> +	lastPurgeHour := 0
```suggestion
	lastPurgeHour := -1
```

Right now if first refresh happens in the midnight hour (`refreshStart.Hour()=0`) then the purges will not happen until the next hour. This should make it so purges are always run on the first refresh after startup.

2024-10-29 09:17 UTC, harshavardhana approved these changes

2024-10-29 10:30 UTC, taran-p approved these changes

2024-10-29 16:01 UTC, merged