docs: Add bucket notification documentation.
minio/minio pull request #2589
Opened 2016-08-31 23:50 UTC by harshavardhana

Fixes #2286

2016-12-03 01:05 UTC, harshavardhana commented
@deekoder will be updating this doc soon it is not complete yet, but it is ready for cursory review.

2017-01-02 04:35 UTC, krisis requested changes

2017-01-02 04:35 UTC, krisis commented on docs/bucket/notification/README.md
> +Minio can send bucket notifications to one or more of the following supported targets. The target is identified uniquely through an unique resource identifier called [ARN](http://docs.aws.amazon.com/
We are switching between event notifications and bucket notifications. We should either use one of them everywhere or explain how they could be used interchangeably.

2017-01-02 04:35 UTC, krisis commented on docs/bucket/notification/README.md
> +				"enable": true,
Can we add a note describe the inputs supplied via config for notification purposes? e.g, how does one choose the values for exchange and routingKey? Are other values permissible?

2017-01-02 04:35 UTC, krisis commented on docs/bucket/notification/README.md
> +Elasticsearch is a search engine based on Lucene. It provides a distributed, multitenant-capable full-text search engine with an HTTP web interface and schema-free JSON documents. To know more detail
The link to server configuration guide should appear in other targets' documentation too. It is missing in AMQP section.

2017-01-02 04:35 UTC, krisis commented on docs/bucket/notification/README.md
> +You may also look at [mc watch](https://docs.minio.io/docs/minio-client-complete-guide#watch) command to write useful shell scripts around bucket events.
We are calling event-notifications by different names within this document. We need a uniform convention for this.

2017-01-02 06:12 UTC, harshavardhana commented
This document is not ready for review @krisis .

2017-02-06 04:07 UTC, closed without merging