fs: Remove object append file if found since it is not always used
minio/minio pull request #3139
Opened 2016-10-31 15:45 UTC by vadmeste

## Description
Disk gets filled in FS because append file in tmp/ is not removed when not used

## Motivation and Context
Fixes #3137 

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2016-10-31 15:56 UTC, harshavardhana approved these changes

2016-10-31 17:21 UTC, harshavardhana commented
ping @krishnasrinivas

2016-10-31 18:17 UTC, krishnasrinivas commented
The tmp data file should have got appended properly and renamed, the problem is somewhere else. Checking it.

2016-10-31 18:19 UTC, vadmeste commented
> The tmp data file should have got appended properly and renamed, the problem is somewhere else. Checking it.

As I understood, there is one case when a client calls Complete MultiPart before append all parts is done in background, that is how we have this tmp file not renamed and not used, am I correct ?

2016-10-31 18:53 UTC, krishnasrinivas commented
> As I understood, there is one case when a client calls Complete MultiPart before append all parts is done in background, that is how we have this tmp file not renamed and not used, am I correct ?

correct.

@vadmeste a race i had dismissed (to keep the code simple) that it will not happen is happening. Basically after PutObjectPart is done we call `go appendParts(fs.storage, bucket, object, uploadID, opsID)` but before this new go routine is spawned if we get `CompleteMultipartUpload()` then the behavior we see here can happen. 

try:
```
while true; do mc --debug cp 70mb myminio/testbucket/ ; done
```

i.e with --debug flag, this race will not be seen because the client will be a little slow in sending CompleteMultipartUpload()

fix is that before spawning go routine we have to do `nsMutex.Lock(minioMetaBucket, fsAppendMetaPath, opsID)` but thinking how it will affect the code flow.

2016-10-31 19:56 UTC, krishnasrinivas commented
@vadmeste your current fix will still be needed to clean things up, but there are a couple of comments i have added.

I am fixing the bug where the appended file won't go waste because of the race condition.

2016-10-31 19:57 UTC, krishnasrinivas commented on cmd/fs-v1-multipart.go
> -		fs.storage.DeleteFile(minioMetaBucket, fsAppendMetaPath)
you can keep this line and move the below new two lines you have added into else block. That way it will be more clear.

2016-10-31 20:02 UTC, krishnasrinivas requested changes
minor comment added.

2016-10-31 20:58 UTC, harshavardhana commented
what is the final consensus here @krishnasrinivas ?

2016-11-01 02:22 UTC, krishnasrinivas approved these changes

2016-11-01 02:59 UTC, krishnasrinivas commented
@harshavardhana can be merged

2016-11-01 07:55 UTC, harshavardhana commented
> I am fixing the bug where the appended file won't go waste because of the race condition.

We should open a bug for this @vadmeste @krishnasrinivas

2016-11-01 07:56 UTC, merged