[WIP] Management API library
minio/minio pull request #3426
Opened 2016-12-10 21:13 UTC by vadmeste

Just a first attempt of a code that works but probably needs some discussion

2016-12-16 10:08 UTC, krisis reviewed
Initial comments.

2016-12-16 10:08 UTC, krisis commented on pkg/madmin/utils.go
> +		return ErrInvalidArgument("Endpoint url cannot have fully qualified paths.")
Isn't this error different from the one below? This means the URL was malformed and not parseable.

2016-12-16 10:49 UTC, vadmeste commented on pkg/madmin/utils.go
> +		return ErrInvalidArgument("Endpoint url cannot have fully qualified paths.")
> Isn't this error different from the one below? This means the URL was malformed and not parseable.

Agree

2016-12-16 17:47 UTC, vadmeste commented
@harshavardhana, issues were addressed, but I am thinking to add a new package under minio-go/pkg/utils which has some useful like isValidEndpointURL, isValidDomain, isValidIP etc, .. what do you think ?

2016-12-16 17:58 UTC, harshavardhana commented
> @harshavardhana, issues were addressed, but I am thinking to add a new package under minio-go/pkg/utils which has some useful functions like isValidEndpointURL, isValidDomain, isValidIP etc, .. what do you think ?

@vadmeste if we can make it generic enough but as a thumb rule naming `utils` as a package can cause lot of unrelated functions to be dumped there which is a bad practice for a package itself -  `urlutil` is a better word for this, like httputil package. Deals with anything URL related.

2016-12-20 04:25 UTC, harshavardhana commented
Is this still a WIP @vadmeste ?

2016-12-20 10:45 UTC, vadmeste commented
> Is this still a WIP @vadmeste ?

No, I've updated the title.

2016-12-20 17:08 UTC, harshavardhana requested changes
Everything else looks good.

2016-12-20 17:08 UTC, harshavardhana commented on pkg/madmin/client_test.go
> +	/* cl, _ := madmin.NewAdminClient("localhost:9000", "minio", "minio123", false)
Can we remove the comment?

2016-12-20 17:08 UTC, harshavardhana commented on pkg/madmin/service-api.go
> +// ServiceStatus - Call Service Status API
Little more descriptive comment describing the purpose.

2016-12-20 17:08 UTC, harshavardhana commented on pkg/madmin/service-api.go
> +// ServiceStop - Call Service Stop API
Little more descriptive comment describing the purpose.

2016-12-20 17:08 UTC, harshavardhana commented on pkg/madmin/service-api.go
> +// ServiceRestart - Call Service Restart API
Little more descriptive comment describing the purpose.

2016-12-20 17:08 UTC, harshavardhana commented on pkg/madmin/utils.go
> +		if !isValidIP(host) && !isValidDomain(host) {
You can use s3utils here..

2016-12-20 17:08 UTC, harshavardhana commented on pkg/madmin/requests.go
> +	endpointURL string
You can use endpointURL to be url.URL here not string. Makes validation easier.

2016-12-20 20:29 UTC, vadmeste commented
All issues are addressed @harshavardhana, also I vendorized s3utils package.

2016-12-20 21:46 UTC, vadmeste commented
All issues are addressed @harshavardhana, also I vendorized s3utils and s3signer packages.

2016-12-20 22:45 UTC, harshavardhana approved these changes

2016-12-20 22:45 UTC, merged