[WIP] Add support for Kafka as a notifications target (#2869)
minio/minio pull request #3439
Opened 2016-12-13 09:55 UTC by donatello

## Description

Same as title

## Motivation and Context

Fixes #2869

## How Has This Been Tested?

Testing is pending. DO NOT MERGE.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2016-12-13 16:04 UTC, harshavardhana commented on cmd/config-migrate.go
> +func migrateV10ToV11() error {
You need to add a test for this.

2016-12-13 18:03 UTC, harshavardhana commented on cmd/notify-kafka.go
> +	// Dial kafka
This comment just names the function name should be more descriptive.

2016-12-13 18:05 UTC, harshavardhana requested changes

2016-12-13 18:05 UTC, harshavardhana commented on cmd/notify-kafka.go
> +type kafkaConn struct {
Comments for each struct.

2016-12-14 09:35 UTC, donatello commented on cmd/config-migrate.go
> +func migrateV10ToV11() error {
Updated the test in `config-migrate_test.go` to include this migration.

2016-12-14 09:35 UTC, donatello commented on cmd/notify-kafka.go
> +	// Dial kafka
Done

2016-12-14 09:35 UTC, donatello commented on cmd/notify-kafka.go
> +type kafkaConn struct {
Done.

2016-12-14 22:08 UTC, vadmeste commented on cmd/config-migrate.go
> +		return fmt.Errorf("Unable to load config version ‘9’. %v", err)
You mean version 10 and not 9 here.

2016-12-15 06:16 UTC, donatello commented on cmd/config-migrate.go
> +		return fmt.Errorf("Unable to load config version ‘9’. %v", err)
Good catch. This is fixed now.

2016-12-15 08:02 UTC, harshavardhana approved these changes

2016-12-15 10:20 UTC, krisis approved these changes
LGTM

2016-12-15 11:40 UTC, vadmeste approved these changes

2016-12-15 16:23 UTC, merged