Code: Enhanced the output message to include minimum 3 characters Bucket Name limit.
minio/minio pull request #3454
Opened 2016-12-15 06:52 UTC by koolhead17

Enhanced the output message to include minimum 3 characters Bucket Name limit.

## Description
Enhanced the output message to include minimum 3 characters Bucket Name limit. Current error code output does not mention about it.

## Motivation and Context
This PR will make the error output more informative especially when someone selects a Bucket Name with 2 characters. 

## How Has This Been Tested?

## Types of changes

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
Name limit.

2016-12-15 07:48 UTC, harshavardhana commented
Fix the commit message and the title here to be proper you don't have to say "Code:"  we don't need to mention the obvious.  The thumb rule is reference the component which is being modified choose

`web:`  or `browser:` 

In a commit title do not include more than 60 characters, more information if needed goes into the body of the commit itself. Title should be concise and meaningful.

2016-12-15 08:15 UTC, koolhead17 commented
@harshavardhana modified as suggested.

2016-12-15 16:30 UTC, harshavardhana commented
Not just in the PR also in the commit message

2016-12-15 20:03 UTC, harshavardhana requested changes

2016-12-15 20:03 UTC, harshavardhana commented on cmd/web-handlers.go
> +				Message: fmt.Sprintf("Bucket Name %s is invalid. Lowercase letters, period and numerals are the only allowed characters. Bucket Name must be at least 3 characters.", params[0]),
"Must be atleast 3 characters long" Not need to add "Bucket name" again.

2016-12-16 06:29 UTC, koolhead17 commented on cmd/web-handlers.go
> +				Message: fmt.Sprintf("Bucket Name %s is invalid. Lowercase letters, period and numerals are the only allowed characters. Bucket Name must be at least 3 characters.", params[0]),
ok. let me modify and send it.

2016-12-16 06:48 UTC, harshavardhana approved these changes

2016-12-16 09:18 UTC, harshavardhana commented on cmd/web-handlers.go
> +				Message: fmt.Sprintf("Bucket Name %s is invalid. Lowercase letters, period, numerals are the only allowed with minimum number of 3 characters.", params[0]),
Let's fix this further to

"Bucket Name %s is invalid. Lowercase letters, period, numerals are the only allowed characters and should be minimum 3 characters in length."

2016-12-16 10:17 UTC, koolhead17 commented on cmd/web-handlers.go
> +				Message: fmt.Sprintf("Bucket Name %s is invalid. Lowercase letters, period, numerals are the only allowed with minimum number of 3 characters.", params[0]),
sure. just made the modification.

2016-12-16 17:59 UTC, merged