tmp: Use testTmpDir var to specify tmp directory
minio/minio pull request #3459
Opened 2016-12-15 22:04 UTC by vadmeste

## Description
To be able to specify the directory where tests will be done.  This way,
it will be easier to run Minio tests on a mounted directory like NFS, ..

## Motivation and Context
Testing go test on NFS

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2016-12-15 22:23 UTC, harshavardhana requested changes
How do you specify NFS directory?

2016-12-15 22:23 UTC, harshavardhana commented on cmd/test-utils_test.go
> +var testTmpDir = os.TempDir()
name this as 'globalTestTmpDir'

2016-12-15 23:09 UTC, vadmeste commented
> How do you specify NFS directory?

Currently no way, I am thinking of adding a function which returns the content of an environment variable if non nil or default value

2016-12-15 23:32 UTC, harshavardhana approved these changes

2016-12-16 00:23 UTC, harshavardhana commented
Don't bring any new environment variables. See if go test can take custom cli options.

2016-12-16 06:25 UTC, merged