[WIP] s3peer: Rewrite to add support for new peer clients
minio/minio pull request #3492
Opened 2016-12-22 22:51 UTC by vadmeste

## Description
Make it easier to add new s3 peer clients and avoid being limited to only BMS client

## Motivation and Context
Pave the way for new RPC clients for inter nodes communications, like Get Server Info

## How Has This Been Tested?
go test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-12-22 22:56 UTC, harshavardhana commented on cmd/s3-peer-bms-client.go
> +	return "bms"
You should type the API name than using generic string like this, hard to catch bugs.

2016-12-22 22:57 UTC, harshavardhana commented on cmd/s3-peer-bms-client.go
> +func (c s3PeerBucketMetaStateAPI) NewLocalClient() interface{} {
Catch all interface should be avoided in the return statement.. The functionaliy which localBucketMetaState would provide should be put into a concrete type.

2016-12-22 22:58 UTC, harshavardhana commented on cmd/s3-peer-bms-client.go
> +func (c s3PeerBucketMetaStateAPI) NewLocalClient() interface{} {
A concrete type here should put into an interface like below 

```
type UpdateBucketMetadata interface {
... add relevant methods generic for all metadata updates ...
}
```

2016-12-22 22:59 UTC, harshavardhana requested changes
Overall this is a good change but we need to make sure to concrete types either by writing a common interface compatible type or use a proper struct.

2016-12-22 23:17 UTC, vadmeste commented on cmd/s3-peer-bms-client.go
> +func (c s3PeerBucketMetaStateAPI) NewLocalClient() interface{} {
Actually this PR will help to implement new calls (local and remote) like Get Storage Info (https://github.com/minio/minio/issues/3475).. that's why I am using generic interface{}

2016-12-23 02:11 UTC, harshavardhana commented on cmd/s3-peer-bms-client.go
> +func (c s3PeerBucketMetaStateAPI) NewLocalClient() interface{} {
Still we need to explore all possible ways before we can say that we have to use a generic interface{} like this.

2017-02-05 06:06 UTC, harshavardhana commented
@vadmeste is this still valid ?

2017-02-05 18:24 UTC, vadmeste commented
> @vadmeste is this still valid ?

Not valid anymore since @balamurugana is taking over this

2017-02-05 18:26 UTC, closed without merging