[WIP] Adopt dsync interface changes and major cleanup on RPC server/c…
minio/minio pull request #3495
Opened 2016-12-25 00:58 UTC by balamurugana

…lient.

## Description
Adopt dsync interface changes and major cleanup on RPC server/client.

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-12-26 16:24 UTC, balamurugana commented
Tests on Appveyor fail due to client request time vs server time is beyond or less than 3 Seconds.  Not sure why its such slow.

```
--- FAIL: TestLogin (3.14s)
	auth-rpc-server_test.go:112: Test 4: Expected error Invalid access key, access key should be 5 to 20 characters in length but received Server times are too far apart
	auth-rpc-server_test.go:112: Test 5: Expected error Invalid secret key, secret key should be 8 to 40 characters in length but received Server times are too far apart
	auth-rpc-server_test.go:112: Test 6: Expected error The access key ID you provided does not exist in our records but received Server times are too far apart
	auth-rpc-server_test.go:112: Test 7: Expected error Authentication failed, check your access credentials but received Server times are too far apart
--- FAIL: TestLockRpcServerLock (3.18s)
	lock-rpc-server_test.go:96: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:128: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
--- FAIL: TestLockRpcServerUnlock (3.19s)
	lock-rpc-server_test.go:162: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:170: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
--- FAIL: TestLockRpcServerRLock (3.17s)
	lock-rpc-server_test.go:204: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:236: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
--- FAIL: TestLockRpcServerRUnlock (3.18s)
	lock-rpc-server_test.go:270: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:288: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:296: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:320: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
--- FAIL: TestLockRpcServerForceUnlock (3.20s)
	lock-rpc-server_test.go:361: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:376: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:384: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:390: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:398: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
--- FAIL: TestLockRpcServerExpired (3.24s)
	lock-rpc-server_test.go:421: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:432: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
	lock-rpc-server_test.go:439: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
OK: 193 passed
FAIL
FAIL	github.com/minio/minio/cmd	413.199s
```

2016-12-26 18:25 UTC, harshavardhana commented
> --- FAIL: TestLogin (3.14s)
> 	auth-rpc-server_test.go:112: Test 4: Expected error Invalid access key, access key should be 5 to 20 characters in length but received Server times are too far apart
> 	auth-rpc-server_test.go:112: Test 5: Expected error Invalid secret key, secret key should be 8 to 40 characters in length but received Server times are too far apart
> 	auth-rpc-server_test.go:112: Test 6: Expected error The access key ID you provided does not exist in our records but received Server times are too far apart
> 	auth-rpc-server_test.go:112: Test 7: Expected error Authentication failed, check your access credentials but received Server times are too far apart
> --- FAIL: TestLockRpcServerLock (3.18s)
> 	lock-rpc-server_test.go:96: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:128: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> --- FAIL: TestLockRpcServerUnlock (3.19s)
> 	lock-rpc-server_test.go:162: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:170: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> --- FAIL: TestLockRpcServerRLock (3.17s)
> 	lock-rpc-server_test.go:204: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:236: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> --- FAIL: TestLockRpcServerRUnlock (3.18s)
> 	lock-rpc-server_test.go:270: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:288: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:296: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:320: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> --- FAIL: TestLockRpcServerForceUnlock (3.20s)
> 	lock-rpc-server_test.go:361: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:376: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:384: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:390: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:398: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
> --- FAIL: TestLockRpcServerExpired (3.24s)
> 	lock-rpc-server_test.go:421: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:432: Expected <nil>, got &errors.errorString{s:"Server times are too far apart"}
> 	lock-rpc-server_test.go:439: Expected no error, got &errors.errorString{s:"Server times are too far apart"}
> OK: 193 passed

Keep it as it is before not 3secs atleast keep it 5mins - perhaps there is another bug which we need to fix - can you try it outside of CI - perhaps on a local windows box?

2016-12-28 09:26 UTC, harshavardhana commented on cmd/rpc-common.go
> +const rpcSkewTimeAllowed = 3 * time.Second
3 sec is a really short period of time for the delivery, on a saturated network this might be a really low value IMHO.

2016-12-28 09:26 UTC, harshavardhana commented on cmd/net-rpc-client.go
> +				Err:  errors.New("Unable to parse server address <" + rpcClient.serverAddr + ">: " + err.Error()),
We can use `fmt.Errorf()` for stringifying `err`

2016-12-28 09:26 UTC, harshavardhana commented on cmd/rpc-common.go
> +func newLockArgs(args dsync.LockArgs) LockArgs {
why this kind of wrapper? and also we are not validating the input arguments for new()? .. Wouldn't it be simple to just use `LockArgs{dsyncLockArgs: args}` everywhere?

2016-12-28 09:26 UTC, harshavardhana commented on cmd/rpc-common.go
> +	if curTime.Sub(args.RequestTime) > rpcSkewTimeAllowed || args.RequestTime.Sub(curTime) > rpcSkewTimeAllowed {
Can you move the second operand to the first one? like how it is done in LoginRPCArgs - IsValid()

2016-12-28 09:26 UTC, harshavardhana commented on cmd/storage-rpc-client.go
> +	// return n.rpcClient.Login()
why is this commented out?

2016-12-29 00:15 UTC, balamurugana commented on cmd/rpc-common.go
> +const rpcSkewTimeAllowed = 3 * time.Second
I am not sure. A request is reached after 3s (3000ms) is big delay even in a saturated network. We would need to benchmark and get real number.

Failing on MS Windows looks like a bug.

2016-12-29 00:32 UTC, harshavardhana commented on cmd/rpc-common.go
> +const rpcSkewTimeAllowed = 3 * time.Second
Until then can you keep a higher value perhaps like 10secs?

2016-12-30 00:47 UTC, balamurugana commented on cmd/storage-rpc-client.go
> +	// return n.rpcClient.Login()
The `Init()` itself is not required.  Removing it.

2016-12-30 00:47 UTC, balamurugana commented on cmd/net-rpc-client.go
> +				Err:  errors.New("Unable to parse server address <" + rpcClient.serverAddr + ">: " + err.Error()),
Done

2016-12-30 00:53 UTC, balamurugana commented on cmd/rpc-common.go
> +func newLockArgs(args dsync.LockArgs) LockArgs {
Yes. `NewLockArgs()` is not required now.  I thought of adding validation of `args`.  When Its added, I bring the function back.

2016-12-30 03:04 UTC, balamurugana commented on cmd/rpc-common.go
> +	if curTime.Sub(args.RequestTime) > rpcSkewTimeAllowed || args.RequestTime.Sub(curTime) > rpcSkewTimeAllowed {
Actually I am making it as a separate function.

2016-12-30 03:05 UTC, balamurugana commented on cmd/rpc-common.go
> +const rpcSkewTimeAllowed = 3 * time.Second
We can keep higher value for MS Windows only. However its better to fix the bug now.

2016-12-31 07:54 UTC, balamurugana commented
After adding a debug `fmt.Println()` found a data race in `lockMaintenance()`.  @fwessels @krisis @harshavardhana  Any idea?

2016-12-31 09:30 UTC, harshavardhana commented on cmd/storage-rpc-client.go
> +	rpcClient         *AuthRPCClient
You can't inherit from AuthRPC - we need a separate implementation to make sure that the storage client doesn't connect and start initiating calls directly to server. 

Will send a PR to your PR incorporating those changes.

2016-12-31 10:18 UTC, harshavardhana commented
Fixed some things about the patch for storage RPC only - https://github.com/balamurugana/minio/pull/2/commits/47ce69f3c8ffa2b2c64c4f9d40a1f949d19cf479 also fixed a bug in dsync lockRPCClient. Can you merge @balamurugana ?

2016-12-31 10:19 UTC, harshavardhana commented on cmd/lock-rpc-client.go
> +	err = lockRPCClient.AuthRPCClient.Call("dsync.RLock", &lockArgs, &reply)
dsync small case should Dsync instead.

2016-12-31 10:19 UTC, harshavardhana commented on cmd/lock-rpc-client.go
> +	err = lockRPCClient.AuthRPCClient.Call("dsync.RLock", &lockArgs, &reply)
Fixed in the PR i sent.

2017-01-01 20:12 UTC, harshavardhana commented
Reproduced the windows issue on linux as well 

```
make: [spelling] Error 2 (ignored)
Running all minio testing:
--- FAIL: TestLogin (3.04s)
	auth-rpc-server_test.go:112: Test 4: Expected error Invalid access key, access key should be 5 to 20 characters in length but received Server times are too far apart
	auth-rpc-server_test.go:112: Test 5: Expected error Invalid secret key, secret key should be 8 to 40 characters in length but received Server times are too far apart
	auth-rpc-server_test.go:112: Test 6: Expected error The access key ID you provided does not exist in our records but received Server times are too far apart
	auth-rpc-server_test.go:112: Test 7: Expected error Authentication failed, check your access credentials but received Server times are too far apart
OK: 193 passed
```

2017-01-01 20:30 UTC, harshavardhana commented
> make: [spelling] Error 2 (ignored)
> Running all minio testing:
> --- FAIL: TestLogin (3.04s)
> 	auth-rpc-server_test.go:112: Test 4: Expected error Invalid access key, access key should be 5 to 20 characters in length but received Server times are too far apart
> 	auth-rpc-server_test.go:112: Test 5: Expected error Invalid secret key, secret key should be 8 to 40 characters in length but received Server times are too far apart
> 	auth-rpc-server_test.go:112: Test 6: Expected error The access key ID you provided does not exist in our records but received Server times are too far apart
> 	auth-rpc-server_test.go:112: Test 7: Expected error Authentication failed, check your access credentials but received Server times are too far apart
> OK: 193 passed

Happens very rarely.

2017-01-01 20:33 UTC, harshavardhana commented
https://github.com/balamurugana/minio/pull/3 - sent another PR @balamurugana  fixing the lock maintenance loop bug . Also i think the server time far apart is some other bug in our code itself reproducible rarely but you can check with 

```
go test -count 1000 -race 
```

2017-01-02 00:40 UTC, balamurugana commented
> balamurugana#3 - sent another PR @balamurugana fixing the lock maintenance loop bug .

Cool. Merged. :+1: 



> Also i think the server time far apart is some other bug in our code itself reproducible rarely

Yes. The bug is causing data race as well.

2017-01-02 06:11 UTC, krisis requested changes

2017-01-02 06:11 UTC, krisis commented on cmd/auth-rpc-client.go
> +	// errorCheckFunc is called when RPC call is not successful.
nit: update comment, s/errorCheckFunc/retryCheckFunc

2017-01-02 06:11 UTC, krisis commented on cmd/auth-rpc-client.go
> +	retryTimerUnit    time.Duration
suggestion: we can remove retry prefix in all variables, since the type itself signifies that these are values pertaining to retry of some sort.

2017-01-02 06:11 UTC, krisis commented on cmd/auth-rpc-client.go
> +// AuthRPCClient is a authenticated RPC client which does authentication before doing Call().
s/is a authenticated/is an authenticated/

2017-01-02 06:11 UTC, krisis commented on cmd/auth-rpc-client.go
> +// authConfig requires to make new AuthRPCClient.
s/requires/required/

2017-01-02 06:11 UTC, krisis commented on cmd/auth-rpc-client.go
> +// call makes a RPC call after logs into the server.
How about "call makes an RPC call after logging into the server."?

2017-01-02 06:11 UTC, krisis commented on cmd/auth-rpc-client.go
> +		authClient.Close()
Why should AuthRPCClient login afresh after every call?

2017-01-02 06:11 UTC, krisis commented on cmd/lock-rpc-client.go
> +// RLock calls read lock RPC.
dsync performs retry on network failures. So, it doesn't make sense to use defaultRetryConfig here. LockRPCClient should _not_ retry on rpc call failure.

2017-01-02 06:11 UTC, krisis commented on cmd/lock-rpc-server_test.go
> +
Pass ``currentIsDistXL`` as argument to the anonymous function to avoid any runtime surprises.

2017-01-02 06:11 UTC, krisis commented on cmd/utils_test.go
> +	}()
Pass ``currentIsDistXL`` as an argument to anonymous to force binding of its current value.

2017-01-02 08:55 UTC, harshavardhana commented on cmd/lock-rpc-client.go
> +// RLock calls read lock RPC.
It should reconnect dsync doesn't reconnect on its own, dsync just calls the same lock on the resource.  That is what the retry does in `defaultRetryConfig`

2017-01-02 08:56 UTC, harshavardhana commented on cmd/lock-rpc-client.go
> +// RLock calls read lock RPC.
Basically a retry is attempted on rpc.ErrShutdown which is needed since we need to connect back.

2017-01-02 08:58 UTC, krisis commented on cmd/lock-rpc-client.go
> +// RLock calls read lock RPC.
Yeah, makes sense.

2017-01-02 09:38 UTC, harshavardhana commented on cmd/lock-rpc-server_test.go
> +
Done

2017-01-02 09:38 UTC, harshavardhana commented on cmd/utils_test.go
> +	}()
Done

2017-01-02 18:20 UTC, harshavardhana approved these changes
Works with all the cases disconnection and re-connection.

2017-01-02 18:53 UTC, merged