docs: Added guide for distributed minio on Windows
minio/minio pull request #3507
Opened 2016-12-30 03:24 UTC by koolhead17

Added guide for distributed minio on Windows with Docker.

## Description
Added docs as requested from community for installation steps via docker on setting up minio distributed.

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2016-12-31 01:35 UTC, deekoder commented
Where does this guide reside? Is it a recipe ?

2016-12-31 01:37 UTC, deekoder reviewed
If this is not a recipe, remove numbers next to headings. Otherwise LGTM (assuming testing is complete).

2016-12-31 01:41 UTC, harshavardhana commented
> If this is not a recipe, remove numbers next to headings. Otherwise LGTM (assuming testing is complete).

This is not a recipe and it should be part of the docker quick start guide (perhaps under windows) section. what do you think @deekoder ?

2017-01-02 04:25 UTC, krisis requested changes

2017-01-02 04:25 UTC, krisis commented on docs/docker/distributed-minio-docker-windows.md
> +Install Install Docker Toolbox for Windows from [here](http://www.docker.com/products/docker-toolbox)
typo: s/Install Install/Install

2017-01-02 04:25 UTC, krisis commented on docs/docker/distributed-minio-docker-windows.md
> +Minio browser will be simply accessible at one of the port 9001-9004.
s/port/ports

2017-01-02 04:27 UTC, deekoder commented on docs/docker/distributed-minio-docker-windows.md
> +Install Install Docker Toolbox for Windows from [here](http://www.docker.com/products/docker-toolbox)
ack.

2017-01-02 04:27 UTC, deekoder commented on docs/docker/distributed-minio-docker-windows.md
> +Minio browser will be simply accessible at one of the port 9001-9004.
ack.

2017-01-02 05:46 UTC, deekoder commented
@harshavardhana - It should be in the docker quickstart guide.

2017-01-06 08:51 UTC, koolhead17 commented
@deekoder @harshavardhana If you can suggest me on where it should go, i will do specific amendments and sent updated PR. 

Also @deekoder https://github.com/minio/minio/tree/master/docs/docker  the docker quick start guide has numbering in it, are you suggesting to remove those as well?

2017-01-07 03:15 UTC, deekoder commented
@koolhead17 - We need to be consistent thats all. Minio QS has no #s. Where as others do. Let's make them all exactly similar.

2017-01-07 03:28 UTC, koolhead17 commented
@deekoder sure. It is following the style guideline with existing docker quick start guide which has numbering in it.

2017-01-08 02:33 UTC, deekoder commented
ok LGTM.

2017-01-08 02:35 UTC, merged