docs: added event-notification back end doc.
minio/minio pull request #3510
Opened 2016-12-30 15:38 UTC by koolhead17

added event-notification back end doc. 
## Description

The patch adds minio event-notification documentation with backend elastic, nats, rabbitmq, redis and PostgreSQL.

2016-12-31 01:56 UTC, deekoder requested changes
- [Minio](https://www.minio.io) server supports Amazon S3 compatible bucket event notifications. <-Plural

- The default location of Minio server configuration file is ``~/.minio/config.json``. Update the Elasticsearch configuration block in ``config.json`` as follows : <-- instead of period use :
- If you are running [distributed Minio](https://docs.minio.io/docs/distributed-minio-quickstart-guide), modify ``~/.minio/config.json`` with these local changes on all the nodes.
- Step 2 should not start with "In this recipe" again. 
- Step 3 : Testing *at* Elasticsearch sounds incorrect.

2016-12-31 01:58 UTC, deekoder requested changes
Same changes should be applied to NATS & Postgres.

2017-01-06 09:04 UTC, koolhead17 commented
@deekoder 
Step 2 should not start with "In this recipe" again.

Step 3 : Testing at Elasticsearch sounds incorrect.

Please what is appropriate & will make the changes.

2017-01-07 03:36 UTC, deekoder commented
>Please advice, what will be appropriate & will make the changes.
Step 2 should not start with "In this recipe" again. 
Please propose an alternative for me to review. 

Step 3 : Testing at Elasticsearch sounds incorrect.
Testing on ElasticSearch will be correct.

2017-01-11 19:20 UTC, deekoder requested changes
- line 35 Restart the Minio server to reflect config changes
 Drop the (in all recipes).

- Below terminal running nats.go program prints event notification on console.
Sentence fragment. Please propose a more clearer sentence.

- Below PostgresSQL terminal lists... 
Propose rephrased sentence.

- line 55 : It uses [pika python client] .. for RabbitMQ.
Ambiguous on what It is. Better to say : Pika Python Client, a library for RabbitMQ will be used in this python program.
-  Redis comes with handy command line interface.. 
Redis comes with a handy command line interface .. to print all notifications on the console

- Change line 60 to :  Below redis-cli prints event notifications on the console.

- Below PostgreSQL terminal lists table ``bucketevents`` stored log of event notification. 
Rephrase.

2017-01-17 00:30 UTC, harshavardhana commented
ping @koolhead17

2017-01-17 08:03 UTC, koolhead17 commented
will send a PR this week.

2017-01-17 15:11 UTC, donatello requested changes
Each document can be structured and written better. No need to repetitively say that Minio, mc and BackendX (Redis/ES/etc) needs to be installed - that is obvious. Also, calling it a recipe in a documentation section sounds wrong, and many technical details are actually missing (such as the meaning of each service configuration parameter and differences between notification backends). 

Here is a sample template:

#### [Edited after feedback from @deekoder in the following comments]
# Sending Minio Event Notifications to BackendX

Write how notifications to this backend work - and highlight differences - for e.g. in postgresql delete object removes entry from table, but in NATS/Kafka, a delete object is just sent as a message to the service.

## Pre-requisites

To configure BackendX in your Minio server/cluster, you will need information about the BackendX service:

1. BackendX Hostname
2. BackendX portname
3. Credentials if needed for BackendX

## Recipe to configure BackendX in your Minio server/cluster

1. In each Minio server in your cluster, locate the configuration file, usually `~/.minio/config.json`. The file will already contain an empty configuration entry for `backendX`.
2. The configuration entry for `backendX` has the following fields - [list and describe the fields]
3. After filling in the details, update/copy over the changes to each config file in your Minio cluster, and restart each server.

## Recipe to configure notifications for a Minio bucket

You can configure notification settings on a bucket to send events to BackendX, using APIs in our Minio Client SDKs.

The following are steps to accomplish this using the command line [`mc` tool](https://minio.io/downloads/#minio-client):
[List steps with mc]

## Recipe to test that notifications are received by BackendX

1. Create an event on the bucket with notifications configured.
2. Show that the event is received by BackendX

2017-01-17 20:57 UTC, deekoder commented
- We list the prerequisites so that the document is self contained. I believe it sounds repetitive to us but it is designed to serve our users well without assuming how they land on our pages. 

-  The term recipe need not be overused. However recipe & cookbook are well understood metaphors for developers to indicate what type of documents these are.

2017-01-17 21:46 UTC, donatello commented
@deekoder 

> * We list the prerequisites so that the document is self contained. I believe it sounds repetitive to us but it is designed to serve our users well without assuming how they land on our pages.

I agree with you on this - I have updated the template above with a pre-requisites section where we just highlight information about the required backend service that receives notifications.
 
> * The term recipe need not be overused. However recipe & cookbook are well understood metaphors for developers to indicate what type of documents these are.

Ah ok, I get your point. I have incorporated this into the template above.

This template seems a bit better to me.

2017-01-19 09:30 UTC, koolhead17 commented
line 35 Restart the Minio server to reflect config changes
Drop the (in all recipes).

Below terminal running nats.go program prints event notification on console.
Sentence fragment. Please propose a more clearer sentence.

Below PostgresSQL terminal lists...
Propose rephrased sentence.

* line 55 : It uses [pika python client] .. for RabbitMQ.
Ambiguous on what It is. Better to say : Pika Python Client, a library for RabbitMQ will be used in this python program.
* Redis comes with handy command line interface..
* Redis comes with a handy command line interface .. to print all notifications on the console
* Change line 60 to : Below redis-cli prints event notifications on the console.
*Below PostgreSQL terminal lists table bucketevents stored log of event notification.
Rephrase.

@deekoder I have modified and made the amendments. Regarding the re-phrasing, please help me if the modified ones are not correct.

2017-01-31 06:28 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Minio server supports Amazon S3 compatible bucket event notification for following targets [AMQP](https://www.amqp.org/about/what), [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/refer
..for the following targets

2017-01-31 06:29 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Restart Minio server to reflect config changes. Minio supports all the exchange available in [RabbitMQ](https://www.rabbitmq.com/). For this setup we are using ``fanout`` exchange.
- Minio supports all the exchanges available in.
- For this setup we are using the ``fanout`` exchange.

2017-01-31 06:56 UTC, deekoder requested changes
This document is getting there. Please consider my requested changes and apply them if you agree.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +If you are running [distributed Minio](https://docs.minio.io/docs/distributed-minio-quickstart-guide), modify ``~/.minio/config.json`` with these local changes on all the nodes.
Move this note up where you do talk about the changes in the config.json.  These local changes is without context. Move it in front of the Restart Minio server...

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Minio server supports Amazon S3 compatible bucket event notification for following targets [AMQP](https://www.amqp.org/about/what), [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/refer
inio server supports Amazon S3 compatible bucket event notification for *the* following targets

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +
Bring the minio distributed note up here.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Restart Minio server to reflect config changes. Minio supports all the exchange available in [RabbitMQ](https://www.rabbitmq.com/). For this setup we are using ``fanout`` exchange.
- Minio supports all the *exchanges* available in..
- For this setup, we are using *the* fanout exchange.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:amqp``. To understand more about
We will enable bucket event notification to trigger whenever a JPEG image is uploaded or deleted ...

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Below python script waits on queue exchange ``bucketevents`` and prints event notification on console. It uses [Pika Python Client](https://www.rabbitmq.com/tutorials/tutorial-three-python.html), a l
The python program below waits on *the* (please check I am not sure of the) queue exchange and  prints event notifications on the console. We use Pika Python Client library to do this.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Execute this example python script to watch for RabbitMQ events on the console.
Let's stick to python program. Drop the script.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on RabbitMQ
Step 1 & 2 were : Add, Enable. Therefore Step 3 : Test on RabbitMQ not Testing on RabbitMQ.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +If you are running [distributed Minio](https://docs.minio.io/docs/distributed-minio-quickstart-guide), modify ``~/.minio/config.json`` with these local changes on all the nodes.
This line here is hanging with no context. User will not understand what "these" local changes on all nodes are.
Move it before the Restart Minio server to reflect..

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:elasticsearch``. To understand m
Same changes in this line as suggested for RabbitMQ.
 - We will enable bucket event notification to trigger whenever a JPEG image is uploaded or deleted ...

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Running ``curl`` we can see Elasticsearch has created a new index name ``bucketevents``.
Change Running to Run (reason : You Upload a jpeg. Same tense).

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on Elasticsearch
Testing should be Test on Elasticsearch. (Keep the tense)

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +If you are running [distributed Minio](https://docs.minio.io/docs/distributed-minio-quickstart-guide), modify ``~/.minio/config.json`` with these local changes on all the nodes.
Move up before Restart Minio server.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:redis``. To understand more abou
Same changes as mention for Elasticsearch and RabbitMQ.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on Redis
Test

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Redis comes with handy command line interface ``redis-cli`` to print all notifications on the console.
Redis comes with *a* handy command line...

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +If you are running [distributed Minio](https://docs.minio.io/docs/distributed-minio-quickstart-guide), modify ``~/.minio/config.json`` with these local changes on all the nodes.
Move up before Restart.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:nats``. To understand more about
Same changes as before

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on NATS
Test

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +If you are running [distributed Minio](https://docs.minio.io/docs/distributed-minio-quickstart-guide), modify ``~/.minio/config.json`` with these local changes on all the nodes.
Move up before Restart.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:postgresql``. To understand more
Same as before.

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on PostgreSQL
Test

2017-01-31 06:56 UTC, deekoder commented on docs/bucket-notifications/README.md
> +Open PostgreSQL terminal to list saved event notification logs.
to list *the* saved event ...

2017-01-31 08:40 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +Minio server supports Amazon S3 compatible bucket event notification for following targets [AMQP](https://www.amqp.org/about/what), [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/refer
ack

2017-01-31 08:44 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +
It is a saperate note we have added, makes sense to be kept in bottom. 

That way someone will not get confused with distributed while the example workflow explaining stand alone. 

Please advice.

2017-01-31 08:46 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +Restart Minio server to reflect config changes. Minio supports all the exchange available in [RabbitMQ](https://www.rabbitmq.com/). For this setup we are using ``fanout`` exchange.
ack

2017-01-31 08:47 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +If you are running [distributed Minio](https://docs.minio.io/docs/distributed-minio-quickstart-guide), modify ``~/.minio/config.json`` with these local changes on all the nodes.
explained above the reason behind keeping this in last line.

2017-01-31 08:48 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:amqp``. To understand more about
ack

2017-01-31 08:49 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on RabbitMQ
ack

2017-01-31 08:57 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +Below python script waits on queue exchange ``bucketevents`` and prints event notification on console. It uses [Pika Python Client](https://www.rabbitmq.com/tutorials/tutorial-three-python.html), a l
ack

2017-01-31 08:57 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +Execute this example python script to watch for RabbitMQ events on the console.
ack

2017-01-31 09:00 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +If you are running [distributed Minio](https://docs.minio.io/docs/distributed-minio-quickstart-guide), modify ``~/.minio/config.json`` with these local changes on all the nodes.
Should we not add a note in footer of the doc with mention of Distributed, instead repeating in all the event notification?

Something like:
Note: If you are running distributed Minio then all the node should have modified config.json with respective event notification configuration?

2017-01-31 09:00 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on Elasticsearch
ack

2017-01-31 09:07 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:elasticsearch``. To understand m
ack

2017-01-31 09:08 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +Running ``curl`` we can see Elasticsearch has created a new index name ``bucketevents``.
ack

2017-01-31 09:09 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:redis``. To understand more abou
ack

2017-01-31 09:10 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on Redis
ack

2017-01-31 09:10 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +Redis comes with handy command line interface ``redis-cli`` to print all notifications on the console.
ack

2017-01-31 09:11 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:nats``. To understand more about
ack

2017-01-31 09:11 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on NATS
ack

2017-01-31 09:11 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +We will enable bucket events only when JPEG images are uploaded or deleted from ``images`` bucket on ``myminio`` server. Here ARN value is ``arn:minio:sqs:us-east-1:1:postgresql``. To understand more
ack

2017-01-31 09:11 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +### Step 3: Testing on PostgreSQL
ack

2017-01-31 09:12 UTC, koolhead17 commented on docs/bucket-notifications/README.md
> +Open PostgreSQL terminal to list saved event notification logs.
ack

2017-01-31 20:06 UTC, deekoder approved these changes

2017-02-01 01:04 UTC, harshavardhana approved these changes

2017-02-01 01:04 UTC, merged