xl: bit-rot algo was not set in get-object.
minio/minio pull request #3652
Opened 2017-01-28 21:29 UTC by krishnasrinivas

fixes #3650

## Description

bit rot algo was not set.

## Motivation and Context

https://github.com/minio/minio/issues/3650

## How Has This Been Tested?

make test
manual

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-01-28 22:19 UTC, vadmeste approved these changes

2017-01-29 03:00 UTC, harshavardhana requested changes

2017-01-29 03:00 UTC, harshavardhana commented on cmd/xl-v1-object.go
>  			// Set checksum algo only once, while it is possible to have
This comment needs to be removed, is it still valid?

2017-01-30 22:25 UTC, harshavardhana approved these changes

2017-01-30 22:25 UTC, merged

2017-01-30 22:41 UTC, krishnasrinivas commented on cmd/xl-v1-object.go
>  			// Set checksum algo only once, while it is possible to have
it's still valid, yes