Fix go routine leaks.
minio/minio pull request #3667
Opened 2017-01-31 16:34 UTC by hackintoshrao

- Fix the Sleep call to make the done channel responsive.

## Description

The issue is described in https://github.com/minio/minio/issues/3666 . 
## Motivation and Context

Fix the Go routine leak by making the done channel responsive all the time.
## How Has This Been Tested?

The test is described in https://github.com/minio/minio/issues/3666 , 

The number of goroutines in the system of after the load test stabilized with this fix.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-01-31 16:52 UTC, vadmeste commented on cmd/retry.go
> +				attemptCh = make(chan int)
Actually, attemptCh channel is returned to the caller of newRetryTimer(), setting it here means we will not able to signal the caller to make its next try

2017-01-31 16:56 UTC, hackintoshrao commented on cmd/retry.go
> +				attemptCh = make(chan int)
Right. Should see how else the `done` channel be made responsive without the routine going to sleep.

2017-01-31 16:58 UTC, hackintoshrao commented on cmd/retry.go
> +				attemptCh = make(chan int)
Will send an alternative fix.

2017-01-31 18:34 UTC, harshavardhana requested changes

2017-01-31 18:34 UTC, harshavardhana commented on cmd/retry.go
> +		var backoffWait <-chan time.Time
Don't use this you don't need this variable at all.  what you need to do is a simple behavior change. 

All you need is this 

```go
$ git diff cmd/retry.go
diff --git a/cmd/retry.go b/cmd/retry.go
index d3ad59e..6a5fe6b 100644
--- a/cmd/retry.go
+++ b/cmd/retry.go
@@ -91,16 +91,19 @@ func newRetryTimer(unit time.Duration, cap time.Duration, jitter float64, doneCh
        go func() {
                defer close(attemptCh)
                nextBackoff := 0
+               var timer *time.Timer
                for {
                        select {
                        // Attempts starts.
                        case attemptCh <- nextBackoff:
                                nextBackoff++
+                               timer = time.NewTimer(exponentialBackoffWait(nextBackoff))
                        case <-doneCh:
                                // Stop the routine.
+                               timer.Stop()
                                return
                        }
-                       time.Sleep(exponentialBackoffWait(nextBackoff))
+                       <-timer.C
                }
        }()
        return attemptCh
```

2017-01-31 18:39 UTC, hackintoshrao commented on cmd/retry.go
> +		var backoffWait <-chan time.Time
What if `doneCh` gets a message when the goroutine blocked on `<-timer.C`? Its still not responsive right ?

2017-02-01 08:01 UTC, krisis requested changes
Please add a unit test for this function.

2017-02-01 08:01 UTC, krisis commented on cmd/retry.go
> +				return
nit: stop the timer and return.
... and the comment should appear before the code.

2017-02-01 08:13 UTC, harshavardhana commented on cmd/retry.go
> +				timer = time.NewTimer(exponentialBackoffWait(nextBackoff))
You can actually move this out of the select.. so that we can avoid allocating a timer when a doneCh is involved right after timer is allocated.

2017-02-01 17:17 UTC, harshavardhana approved these changes

2017-02-01 17:17 UTC, merged