Added documentation for orchestration platforms
minio/minio pull request #3684
Opened 2017-02-04 20:25 UTC by NitishT

## Description
Added documentation for orchestration platforms

## Motivation and Context
It is required for community members to get started with Minio on various platforms like Kubernetes, DC/OS and Swarm
#2825 https://github.com/minio/cookbook/issues/97

## How Has This Been Tested?
Executed locally. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-02-04 20:26 UTC, harshavardhana commented
Please squash all the commits @NitishT

2017-02-05 06:04 UTC, harshavardhana requested changes

2017-02-05 06:04 UTC, harshavardhana commented on docs/orchestration/README.md
> +| [`Docker Swarm`](./docker-swarm) |
You should put a RAW url here..

2017-02-06 04:32 UTC, harshavardhana requested changes

2017-02-06 04:32 UTC, harshavardhana commented on docs/orchestration/README.md
> +| [`Kubernetes`](./kubernetes/README.md) |
You need to point to full URL not just this like this 

[`Kubernetes`](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/kubernetes/README.md)

2017-02-06 04:38 UTC, NitishT commented on docs/orchestration/README.md
> +| [`Kubernetes`](./kubernetes/README.md) |
done

2017-02-06 05:13 UTC, harshavardhana approved these changes

2017-02-06 05:14 UTC, harshavardhana commented
Pending on @abperiasamy review

2017-02-14 15:18 UTC, pascalandy commented
When this is merged, I will add my use case. 
https://github.com/minio/minio/issues/3713#issuecomment-279722533

2017-02-15 04:02 UTC, NitishT commented
That will be great @pascalandy. We can add your blog to the further reading/community maintained list of Minio + Swarm setups.

2017-02-22 02:01 UTC, harshavardhana approved these changes

2017-03-09 16:48 UTC, harshavardhana commented
Can you rebase this @NitishT ?

2017-03-09 18:01 UTC, NitishT commented
done @harshavardhana

2017-03-09 22:06 UTC, harshavardhana approved these changes
There are some changes needed but we will take this in and work on top of it..

2017-03-09 22:06 UTC, merged