[WIP] Browser: Implement multi select user interface for object listings
minio/minio pull request #3730
Opened 2017-02-10 10:13 UTC by rushenn

## Description
Implement multi-select user interface for object listings. This is only the non-functional view part and need further work to make it functional. 

## Motivation and Context
https://github.com/minio/minio/issues/2854

## How Has This Been Tested?
Tested only the UI manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-02-10 14:52 UTC, rushenn commented
Sample markup for action header:

![action-header](https://cloud.githubusercontent.com/assets/13393018/22830977/93a9e798-efce-11e6-9d14-2602bb6e6030.png)

```
<div className="list-actions">
      <span className="la-label">
           <i className="fa fa-check-circle"></i> 
           25 Objects selected
      </span>
      <span className="la-actions pull-right">
             <button>Download all as zip</button>
      </span>
</div>
```

2017-02-13 08:25 UTC, harshavardhana commented
ping @rushenn @krishnasrinivas is this ready for review?

2017-02-13 14:03 UTC, rushenn commented
@krishnasrinivas

2017-02-15 03:43 UTC, harshavardhana commented
> @krishnasrinivas

@rushenn what else is pending here?

2017-02-15 05:56 UTC, rushenn commented
@harshavardhana working on the functionality.

2017-02-15 18:59 UTC, krishnasrinivas commented
checking

2017-02-15 19:05 UTC, krishnasrinivas commented
@harshavardhana this has the html/less changes, now @rushenn is working on the JS/redux changes. We had a chat on how to go about the JS changes for zip/multi-delete issues.

2017-02-19 23:44 UTC, harshavardhana requested changes

2017-02-19 23:44 UTC, harshavardhana commented on .minio.sys/buckets/browser/policy.json
> +{"Version":"2012-10-17","Statement":[{"Action":["s3:GetBucketLocation"],"Effect":"Allow","Principal":{"AWS":["*"]},"Resource":["arn:aws:s3:::browser"],"Sid":""},{"Action":["s3:ListBucket"],"Condition
You shouldn't add these files into your commit.  Also make sure to run minio on a separate directory.

2017-02-20 23:16 UTC, harshavardhana commented
Tests are failing 

```
time="2017-02-20T22:25:32Z" level=error msg="Unable to parse JWT token string" cause="token contains an invalid number of segments" source="[jwt.go:113:isAuthTokenValid()]" 
--- FAIL: TestWebHandlerDownloadZip (0.26s)
	web-handlers_test.go:863: Expected to receive authentication error
```

2017-02-21 00:31 UTC, harshavardhana requested changes

2017-02-21 00:31 UTC, harshavardhana commented on browser/app/js/actions.js
> +    xhr.open('PUT', url, true)
Why would this be a PUT request, it should be "GET"

2017-02-21 00:31 UTC, harshavardhana commented on cmd/web-router.go
> -	webBrowserRouter.Methods("GET").Path("/zip").Queries("token", "{token:.*}").HandlerFunc(web.DownloadZip)
We should keep it as "GET" not PUT.  Get returns the reader not PUT.

2017-02-21 06:50 UTC, rushenn commented on browser/app/js/actions.js
> +    xhr.open('PUT', url, true)
We couldn't send content using GET. I'll ask @krishnasrinivas more about this

2017-02-21 07:19 UTC, harshavardhana commented on browser/app/js/actions.js
> +    xhr.open('PUT', url, true)
in that case we should use POST instead of PUT,  PUT is not expected to do what is being done here.

2017-02-21 07:19 UTC, harshavardhana commented on browser/app/js/actions.js
> +    xhr.open('PUT', url, true)
Also update the test case that is failing along with it.

2017-02-21 18:14 UTC, krishnasrinivas commented
@harshavardhana after changing from PUT to POST it does not work for rushan (MacOS chrome) but works for me (linux chrome)
can you check if it works for you?

2017-02-21 18:17 UTC, krishnasrinivas commented
> can you check if it works for you?

OK, it works for him too

2017-02-21 21:02 UTC, harshavardhana commented
Odd that windows tests are failing, rebuilding them again.

2017-02-21 21:02 UTC, harshavardhana approved these changes

2017-02-21 21:39 UTC, harshavardhana commented
There is some problem in the PR which is causing some problems on windows, not sure what would trigger this only change is POST handler.

2017-02-22 00:22 UTC, krishnasrinivas commented
```
... obtained int = 411
... expected int = 200
```

411 is content-length required, weird
is triggering the test again a good idea? just in case it was some transient error.

2017-02-22 00:24 UTC, harshavardhana commented
> is triggering the test again a good idea? just in case it was some transient error.

Already did it twice. I think we can pull this locally and see what is going on. Must be handlers are tripping over each other after adding POST>

2017-02-22 00:46 UTC, krishnasrinivas commented
> Already did it twice. I think we can pull this locally and see what is going on. Must be handlers are tripping over each other after adding POST>
>  Show all reviewers

let me check on a windows machine

2017-02-22 02:00 UTC, krishnasrinivas commented
@rushenn can you rebase and push it again? the windows appveyor issue is fixed in master.

2017-02-22 22:51 UTC, harshavardhana approved these changes

2017-02-22 22:51 UTC, merged