WIP: Implement ServerConfig admin REST API
minio/minio pull request #3741
Opened 2017-02-13 14:14 UTC by krisis

Returns a valid config.json of the setup. In case of distributed
setup, it checks if quorum or more number of nodes have the same
config.json.

## Description

Fetches config.json from all disks and returns a valid config.json if present.

## Motivation and Context

For users to be able to read config.json of a minio instance without having to log onto the corresponding server and fetch the config.json.
## How Has This Been Tested?

Manually tested using pkg/madmin API also part of this PR.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-02-13 14:21 UTC, krisis commented
TBD:
- Type to represent config.json in pkg/madmin. For now it is the same as that used in minio server.

Rationale for getPeerConfig to use ``interface{}`` to ``Unmarshal`` the json bytes
- type-specific un-marshalling need not be unique for a given value of the type.
- un-marshalling to ``interface{}`` type invokes the rules as described [here](https://golang.org/pkg/encoding/json/#Unmarshal). This is guaranteed to be canonical.

2017-02-14 00:07 UTC, harshavardhana commented
> Rationale for getPeerConfig to use interface{} to Unmarshal the json bytes
> 
> type-specific un-marshalling need not be unique for a given value of the type.
> un-marshalling to interface{} type invokes the rules as described here. This is guaranteed to be canonical.

Not sure i understand this can you elaborate? @krisis

2017-02-14 03:11 UTC, krisis commented
@harshavardhana there are 2 reasons to use `interface{}` as the map key and not `ServerConfigV13`,
1. `ServerConfigV13` is not a valid key type - fails to compile.
2. `json` Unmarshal/Marshal for a given type may change with newer versions of the package.

2017-02-14 03:15 UTC, harshavardhana commented
> ServerConfigV13 is not a valid key type - fails to compile.

Why do you need 'ServerConfigV13' ? you can use what is available `serverConfigV13` 

> json Unmarshal/Marshal for a given type may change with newer versions of the package.

That is why we need to keep the migration code - interface{} doesn't add any value - all the more it will mask issues.

2017-02-14 03:21 UTC, krisis commented
> >   ServerConfigV13 is not a valid key type - fails to compile.
> > Why do you need ServerConfigV13 ? you can use what is available serverConfigV13
`serverConfigV13` is the same as `ServerConfigV13`. We are capitalizing the type name to export it in pkg/madmin. So, both the types are not valid key type.

2017-02-20 08:18 UTC, harshavardhana requested changes

2017-02-20 08:18 UTC, harshavardhana commented on cmd/admin-handlers.go
> +
Can you write a comment here.

2017-02-20 08:18 UTC, harshavardhana commented on cmd/admin-handlers.go
> +	}
i guess we should avoid meddling with server config if object layer is not initialized, safer that way.

2017-02-20 08:18 UTC, harshavardhana commented on cmd/admin-rpc-client.go
> +func (lc localAdminClient) GetConfig() ([]byte, error) {
Comment.

2017-02-20 08:18 UTC, harshavardhana commented on cmd/admin-rpc-client.go
> +
Comment.

2017-02-20 08:18 UTC, harshavardhana commented on cmd/admin-rpc-client.go
> +func getPeerConfig(peers adminPeers) ([]byte, error) {
A comment.

2017-02-20 08:18 UTC, harshavardhana commented on cmd/admin-rpc-client.go
> +
Comment.

2017-02-20 08:28 UTC, krisis commented on cmd/admin-handlers.go
> +
Done

2017-02-20 08:28 UTC, krisis commented on cmd/admin-handlers.go
> +	}
Ok

2017-02-20 08:28 UTC, krisis commented on cmd/admin-rpc-client.go
> +
Done.

2017-02-20 08:28 UTC, krisis commented on cmd/admin-rpc-client.go
> +
Done

2017-02-20 10:32 UTC, donatello approved these changes
LGTM

2017-02-20 10:32 UTC, donatello commented on cmd/admin-rpc-client.go
> +		// Skip nodes were getConfig failed.
`s/were/where/`

2017-02-20 10:32 UTC, donatello commented on cmd/admin-rpc-client.go
> +			} // else invariance is violated.
What is the invariance? It doesn't seem to be precisely stated anywhere.

The invariance is after `i-`th iteration, `sum of configCounter slice = number of server - errors seen upto i-th iteration`. Hopefully there's a nicer way to state it.

2017-02-20 10:32 UTC, donatello commented on cmd/admin-rpc-client.go
> +				// value that was already seen. See e.g above
`s/e.g/example/`

2017-02-20 10:32 UTC, donatello commented on cmd/admin-rpc-client.go
> +				// other value seen before. i.e, it is
`s/i.e, it/It`

2017-02-20 10:32 UTC, donatello commented on cmd/admin-rpc-client.go
> +	// same value.  e.g, let us take the following serverConfigs
`s/value. e.g,/value; e.g./`

2017-02-20 20:08 UTC, harshavardhana approved these changes

2017-02-20 20:58 UTC, merged