mainUpdate: refactor to handle quiet flag properly
minio/minio pull request #3744
Opened 2017-02-14 10:43 UTC by balamurugana

## Description

## Motivation and Context

## How Has This Been Tested?

`make test` and manually ran the command `minio update`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-02-14 22:27 UTC, harshavardhana requested changes

2017-02-14 22:27 UTC, harshavardhana commented on cmd/update-main.go
> +func _getCurrentReleaseTime(minioVersion, minioBinaryPath string) (releaseTime time.Time, err error) {
Do not use `_` in function names it not a convention we follow and also its not idiomatic Go.  Keep the function names to take the values directly if you have default values then put a closure on it.

2017-02-14 23:44 UTC, balamurugana commented on cmd/update-main.go
> +func _getCurrentReleaseTime(minioVersion, minioBinaryPath string) (releaseTime time.Time, err error) {
Closure can't help to make a function unit testable. I will rename `_getCurrentReleaseTime()` into `getCurrentReleaseTime()` and `getCurrentReleaseTime()` into `GetCurrentReleasetime()`

2017-02-15 08:30 UTC, harshavardhana approved these changes

2017-02-15 08:31 UTC, merged