quick: Add yaml format support
minio/minio pull request #3833
Opened 2017-03-02 19:38 UTC by vadmeste

## Description
quick Save() and Load() infers config file's format from
file name extension.

## Motivation and Context
Switching to yaml config file format

## How Has This Been Tested?
go test + Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-03-02 20:28 UTC, harshavardhana reviewed
Also add another helper function to migrate from json to yaml, given that we make sure json as "Version" string we can do the same for yaml.  

This should be done transparently without usage of any structs along the way.

2017-03-02 20:30 UTC, harshavardhana reviewed
An example like 

```yml
---
version: '14'
credential:
  accessKey: USWUXHGYZQYFYFFIT3RE
  secretKey: MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03
region: us-east-1
browser: 'on'
logger:
  console:
    enable: true
    level: error
  file:
    enable: false
    fileName: test.log
    level: error
notify:
  amqp:
    '2':
      enable: false
      url: amqp://guest:guest@localhost:5672/
      exchange: minio
      routingKey: minio
      exchangeType: direct
      mandatory: false
      immediate: false
      durable: false
      internal: false
      noWait: false
      autoDeleted: false
  nats:
    '1':
      enable: false
      address: ''
      subject: ''
      username: ''
      password: ''
      token: ''
      secure: false
      pingInterval: 0
      streaming:
        enable: false
        clusterID: ''
        clientID: ''
        async: false
        maxPubAcksInflight: 0
  elasticsearch:
    '1':
      enable: false
      url: http://localhost:9200
      index: minioevents
  redis:
    '1':
      enable: false
      address: 127.0.0.1:6379
      password: ''
      key: ''
  postgresql:
    '1':
      enable: false
      connectionString: ''
      table: ''
      host: ''
      port: ''
      user: ''
      password: ''
      database: ''
  kafka:
    '1':
      enable: false
      brokers: 
      topic: ''
  webhook:
    '1':
      enable: false
      endpoint: ''
```

```js
{
	"version": "14",
	"credential": {
		"accessKey": "USWUXHGYZQYFYFFIT3RE",
		"secretKey": "MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03"
	},
	"region": "us-east-1",
	"browser": "on",
	"logger": {
		"console": {
			"enable": true,
			"level": "error"
		},
		"file": {
			"enable": false,
			"fileName": "test.log",
			"level": "error"
		}
	},
	"notify": {
		"amqp": {
			"2": {
				"enable": false,
				"url": "amqp://guest:guest@localhost:5672/",
				"exchange": "minio",
				"routingKey": "minio",
				"exchangeType": "direct",
				"mandatory": false,
				"immediate": false,
				"durable": false,
				"internal": false,
				"noWait": false,
				"autoDeleted": false
			}
		},
		"nats": {
			"1": {
				"enable": false,
				"address": "",
				"subject": "",
				"username": "",
				"password": "",
				"token": "",
				"secure": false,
				"pingInterval": 0,
				"streaming": {
					"enable": false,
					"clusterID": "",
					"clientID": "",
					"async": false,
					"maxPubAcksInflight": 0
				}
			}
		},
		"elasticsearch": {
			"1": {
				"enable": false,
				"url": "http://localhost:9200",
				"index": "minioevents"
			}
		},
		"redis": {
			"1": {
				"enable": false,
				"address": "127.0.0.1:6379",
				"password": "",
				"key": ""
			}
		},
		"postgresql": {
			"1": {
				"enable": false,
				"connectionString": "",
				"table": "",
				"host": "",
				"port": "",
				"user": "",
				"password": "",
				"database": ""
			}
		},
		"kafka": {
			"1": {
				"enable": false,
				"brokers": null,
				"topic": ""
			}
		},
		"webhook": {
			"1": {
				"enable": false,
				"endpoint": ""
			}
		}
	}
}
```

2017-03-03 07:41 UTC, harshavardhana requested changes
Windows build failed..

2017-03-03 07:41 UTC, harshavardhana commented on pkg/quick/config_encoding.go
> + * Minio Client (C) 2015 Minio, Inc.
Fix the copyRight header.

2017-03-03 07:41 UTC, harshavardhana commented on pkg/quick/config_encoding.go
> +
Unnecessary space

2017-03-03 11:07 UTC, vadmeste commented
> Also add another helper function to migrate from json to yaml, given that we make sure json as "Version" string we can do the same for yaml.
> 
> This should be done transparently without usage of any structs along the way.

Migrating is easy with quick now: quick.Load("config.json") then quick.Save("config.yaml")

2017-03-03 11:08 UTC, vadmeste commented
> Migrating is easy with quick now: quick.Load("config.json") then quick.Save("config.yaml")

I understand it is better without structs, but we don't need it now I guess, right?

2017-03-03 11:11 UTC, harshavardhana commented
> Migrating is easy with quick now: quick.Load("config.json") then quick.Save("config.yaml")

True but was thinking that we can have a helper in quick to translate between json to yaml and vice versa.

2017-03-03 12:10 UTC, harshavardhana requested changes

2017-03-03 12:10 UTC, harshavardhana commented on pkg/quick/config_encoding.go
> + * Minio Client (C) 2017 Minio, Inc.
shouldnt be minio client..

2017-03-03 12:10 UTC, harshavardhana commented on pkg/quick/config_encoding.go
> +/*
rename the file as just encoding.go

2017-03-03 18:21 UTC, harshavardhana approved these changes

2017-03-03 18:22 UTC, merged