browser: Send correct arguments for RemoveObjects web handler.
minio/minio pull request #3848
Opened 2017-03-03 23:48 UTC by krishnasrinivas

## Description

Deleting file from bucket does not work from webUI

## Motivation and Context

Fixes #3839

## How Has This Been Tested?

manual and go test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-03-03 23:52 UTC, harshavardhana requested changes

2017-03-03 23:52 UTC, harshavardhana commented on cmd/web-handlers.go
> -			err = remove(pathJoin(args.Prefix, object))
Can you add a test case for this change/bug?

2017-03-04 01:05 UTC, krishnasrinivas commented on cmd/web-handlers.go
> -			err = remove(pathJoin(args.Prefix, object))
test case was already there, but the browser code also needed. i had assumed rushenn would do multi-delete before a release is made which did not happen. i have made the browser changes now.

2017-03-04 01:06 UTC, harshavardhana commented on cmd/web-handlers.go
> -			err = remove(pathJoin(args.Prefix, object))
Okay

2017-03-04 01:06 UTC, harshavardhana approved these changes

2017-03-04 01:07 UTC, merged