config: Check for duplicated entries in all scopes
minio/minio pull request #3872
Opened 2017-03-08 17:25 UTC by vadmeste

## Description
Validate Minio config by checking if there is double json key
in any scope level. The returned error contains the json path
to the duplicated key.

## Motivation and Context
Fixes #3812 

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-03-08 21:19 UTC, krishnasrinivas approved these changes

2017-03-08 21:41 UTC, harshavardhana requested changes

2017-03-08 21:41 UTC, harshavardhana commented on cmd/config-v14.go
> +		return err
As discussed we need to do in the following manner

 - checkVersion()
 - checkDuplicateKeys()
 - checkValidTypes()
 - checkEachNotificationTargets()

Each step also should have an error which guides the user on fixing the problem.

2017-03-08 22:02 UTC, vadmeste commented on cmd/config-v14.go
> +		return err
Yes, I was going to do that in a separate PR, (for extensive validation issue)

2017-03-08 22:38 UTC, harshavardhana commented on cmd/config-v14.go
> +		return err
Actually we need to do it in this one, because this PR is not complete without the other changes.

2017-03-09 11:58 UTC, vadmeste commented on cmd/config-v14.go
> +		return err
Not sure what do you exactly by checkValidTypes(), by the way, json already checks for type validation, it cannot accept "version : 14" for example.

Otherise, I added some empty validation functions, each field and sub fields will take care of their proper validation.

2017-03-09 22:00 UTC, harshavardhana commented on cmd/config-v14.go
> +		return err
What i mean you load and parse it once.. So that allows for type validation.

2017-03-13 04:22 UTC, harshavardhana commented
ping @balamurugana this is waiting on your review as well.

2017-03-13 10:32 UTC, vadmeste commented
> ping @balamurugana this is waiting on your review as well.

@team Notification target are not extensively validated yet, please if someone implemented a notification target, can he tell me what parameters need to be validated? (for example, with postgreSQL it is obviously that database field shouldn't be empty)

2017-03-13 19:14 UTC, harshavardhana commented
```
Running cyclo:
cmd/config-v14.go:169:8: "occurences" is a misspelling of "occurrences"
cmd/config-v14.go:169:8: "occurences" is a misspelling of "occurrences"
make: *** [spelling] Error 2
``` 

@vadmeste please run `mispell -w`

2017-03-14 09:55 UTC, vadmeste commented
> @vadmeste please run mispell -w

Done

2017-03-14 18:10 UTC, harshavardhana approved these changes

2017-03-15 23:28 UTC, vadmeste commented
@harshavardhana, tests are added

2017-03-15 23:30 UTC, merged