Add MySQL notifications support
minio/minio pull request #3907
Opened 2017-03-15 15:00 UTC by donatello

Adds a new database target (MySQL, tested with Ver 14.14 Distrib 5.7.17) for notifications.

## Description

The implementation is similar to postgres notifications:

- Notifications are written to a user-specified table (but a specific table structure is required).
- The table is created if it does not exist.
- Event data is stored in a JSON column type.
- Creation of objects results in new rows being inserted if the object name is new, or existing row is updated if an existing object is over-written.
- Deleted objects, cause the corresponding row in the table to be deleted.

In summary, the table will represent all objects in a bucket. 

Additionally the minio server configuration has been bumped up so mysql configuration can be added. Configuration migration code is added with tests.

## Motivation and Context

Adds a feature requested by https://github.com/minio/minio/issues/3818.

## How Has This Been Tested?

Configuration migration related changes have associated test cases updated.

The new target was tested manually. A overview of the process is below:

1. Download mysql docker container
2. Start server with `docker run --name some-mysql -p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -d mysql:latest`
3. Start minio server. It will update configuration version. Then update minio server configuration's mysql section like below and restart the server.
```json
		"mysql": {
			"1": {
				"enable": true,
				"dsnString": "",
				"table": "minio_events",
				"host": "172.17.0.1",
				"port": "3306",
				"user": "root",
				"password": "password",
				"database": "miniodb"
			}
		}

```
4. The server's initial log output will display the ARN with a line like: `SQS ARNs:  arn:minio:sqs:us-east-1:1:mysql`
5. Next use mc to configure events from a bucket to be sent to mysql with something like `mc events add myminio/test arn:minio:sqs:us-east-1:1:mysql`
6. Use mc to copy a file to the server, like `mc cp /etc/issue myminio/test`
7. Connect to mysql server with mysql terminal client with a command similar to `mysql -h 172.17.0.1 -P 3306 -u root -p miniodb`.
8. Type `select * from minio_events` to list the table and you should see the event for the the upload done in step 6, for e.g.:
```
mysql> select * from minio_events;
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| key_name   | value                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| test/issue | {"Records": [{"s3": {"bucket": {"arn": "arn:aws:s3:::test", "name": "test", "ownerIdentity": {"principalId": "minio"}}, "object": {"key": "issue", "eTag": "467886be95c8ecfd71a2900e3f461b4f", "size": 26, "sequencer": "14AC142C6D62ABE6"}, "configurationId": "Config", "s3SchemaVersion": "1.0"}, "awsRegion": "us-east-1", "eventName": "s3:ObjectCreated:Put", "eventTime": "2017-03-15T14:22:37Z", "eventSource": "aws:s3", "eventVersion": "2.0", "userIdentity": {"principalId": "minio"}, "responseElements": {"x-amz-request-id": "14AC142C6D62ABE6", "x-minio-origin-endpoint": "http://192.168.0.103:9000"}, "requestParameters": {"sourceIPAddress": "127.0.0.1:58312"}}]} |
+------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-03-15 15:25 UTC, harshavardhana requested changes

2017-03-15 15:25 UTC, harshavardhana commented on cmd/notify-mysql.go
> + * Minio Cloud Storage, (C) 2014-2016 Minio, Inc.
License header 2017

2017-03-15 21:35 UTC, harshavardhana reviewed
One more thing we should also update https://github.com/minio/minio/tree/master/docs/bucket/notifications notifications doc by adding MySQL entry.

2017-03-16 11:21 UTC, donatello commented on cmd/notify-mysql.go
> + * Minio Cloud Storage, (C) 2014-2016 Minio, Inc.
Fixed

2017-03-16 11:42 UTC, vadmeste commented on cmd/config-migrate.go
> +		return fmt.Errorf("Unable to load config version ‘13’. %v", err)
version 13

2017-03-16 11:45 UTC, donatello commented
> One more thing we should also update https://github.com/minio/minio/tree/master/docs/bucket/notifications notifications doc by adding MySQL entry.

@harshavardhana This is added now. I have departed from the existing format to be able to more details and for completeness. If accepted, I will send more complete documentation PRs for Postgres, Kafka and Redis too.

2017-03-16 11:59 UTC, donatello commented on cmd/config-migrate.go
> +		return fmt.Errorf("Unable to load config version ‘13’. %v", err)
Fixed!

2017-03-16 12:29 UTC, vadmeste commented on cmd/notify-mysql.go
> +	_ "github.com/go-sql-driver/mysql"
Not needed ?

2017-03-16 12:35 UTC, vadmeste commented on cmd/notify-mysql.go
> +	if msql.Table == "" {
It is easier to do this check in config validate along with database name.

2017-03-16 13:59 UTC, donatello commented on cmd/notify-mysql.go
> +	_ "github.com/go-sql-driver/mysql"
Yep, fixed.

2017-03-16 14:01 UTC, donatello commented on cmd/notify-mysql.go
> +	if msql.Table == "" {
Yep, done this also. But checking for empty database name is not necessary. If `dsnString` is provided, then `database` can be empty. `dsnString` provides more flexibility in connecting to the database than the remaining parameters and that is why it is retained.

2017-03-16 15:26 UTC, harshavardhana commented
@NitishT can you take a look at the added docs for MySQL ?

2017-03-16 16:55 UTC, NitishT commented on docs/bucket/notifications/README.md
> +The default location of Minio server configuration file is ``~/.minio/config.json``. Under the `notify` key, in the `mysql` sub-key, we may add as many MySQL server endpoint configurations as desired
How about splitting this information as -- 

The default location of Minio server configuration file is ``~/.minio/config.json``. Find the mysql sub-key under the notify key in the config file and update the relevant sections.

2017-03-16 16:55 UTC, NitishT commented on docs/bucket/notifications/README.md
> +
Note that, you can add as many MySQL server endpoint configurations as needed by providing an identifier for the server and an object of per-server configuration parameters.

2017-03-16 16:55 UTC, NitishT commented on docs/bucket/notifications/README.md
> +Update the MySQL configuration block in your ``config.json`` similar to the above. Restart the Minio server to put the configuration changes into effect. The server will print a like like `SQS ARNs:
The server will print ARN like `SQS ARNs:  arn:minio:sqs:us-east-1:1:mysql`

2017-03-16 16:55 UTC, NitishT commented on docs/bucket/notifications/README.md
> +
This table is a great idea. 👍

2017-03-16 16:55 UTC, NitishT commented on docs/bucket/notifications/README.md
> +Update the MySQL configuration block in your ``config.json`` similar to the above. Restart the Minio server to put the configuration changes into effect. The server will print a like like `SQS ARNs:
Also, you can drop the `Update the MySQL configuration block in your ``config.json`` similar to the above` if you accept above suggestions

2017-03-16 16:55 UTC, NitishT commented on docs/bucket/notifications/README.md
> +We will now setup bucket notifications on a bucket named `images`, so that whenever an JPEG image object is created or deleted we send an event to MySQL. By doing this, we will get a table in MySQL w
We will now setup bucket notifications on a bucket named `images`. This means, whenever an JPEG image object is created or deleted in bucket `images`, Minio server/cluster will create a new row corresponding to the image, in the table configured above (`minio-images` in this case).

2017-03-17 12:18 UTC, donatello commented
Made some final fixes and improved documentation. Please let me know if there are any more review points @NitishT @vadmeste @harshavardhana - otherwise, I believe it is good for merge.

2017-03-17 12:21 UTC, NitishT commented
LGTM 👍

2017-03-17 16:29 UTC, harshavardhana approved these changes

2017-03-17 16:29 UTC, merged