limits: Rise max threads number to max open fds
minio/minio pull request #3964
Opened 2017-03-23 23:13 UTC by vadmeste

## Description
Set a new max threads number if it is less than the maximum
open file descriptors.

## Motivation and Context
Fixes #3883 

## How Has This Been Tested?
go test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-03-24 07:10 UTC, krisis commented on cmd/server-rlimit.go
> +	increaseMaxThreads(int(maxLimit))
shouldn't we check if `increaseMaxThreads` returns `maxLimit` and return error if it doesn't?

2017-03-24 07:15 UTC, krishnasrinivas commented
https://github.com/minio/minio/issues/3883 :

> Yes. we have about 4000-5000 concurrent uploads going on at the same time, and about 4-5 mts. Minio service crashed. could you please let me know how to increase the thread ?

for 5000 concurrent uploads, assuming all the goroutines are blocking, there would be roughly 5000 threads, right? but if the thread count is 10000 then there must be some other underlying problem? does the thread count come back to original number once the concurrent uploads stops? (when tested with a high concurrent upload count not enough to crash minio i.e)

2017-03-24 11:13 UTC, vadmeste commented on cmd/server-rlimit.go
> +	increaseMaxThreads(int(maxLimit))
> shouldn't we check if increaseMaxThreads returns maxLimit and return error if it doesn't?

Actually no. maxLimit could be less than the original value of MaxThreads. This function is not supposed to fail.

2017-03-24 11:39 UTC, vadmeste commented
> for 5000 concurrent uploads, assuming all the goroutines are blocking, there would be roughly 5000 threads, right?

No. In addition to the thread which is processing the client request, the server creates an additional goroutine here  https://github.com/minio/minio/blob/master/cmd/server-mux.go#L238. I know this latter is supposed to die but if I test in my local machine, I can see threads number increasing to roughly the double.

How I tested ?

1. I added a simple goroutine in Minio server which prints number of threads each 500 ms https://golang.org/pkg/runtime/#NumGoroutine

2. I uploaded a 1kb file to the server and made it public.

3. I run this command with httperf `httperf --ssl --server=127.0.0.1 --port=9000 --hog --timeout 300.0 --num-conns 5000 --rate=5000 --uri=/testbucket/public/file`

httperf shows me that the server was able to treat around 400 requests per seconds, at the same time, I can see the number of threads reaching until 800 or 1000.

2017-03-26 08:19 UTC, harshavardhana reviewed
Lets bring the change of blocking connections or rejecting new connections also in this patch. 

So that we can avoid run-away effect of crashing the server.

2017-03-26 09:28 UTC, vadmeste commented
> Lets bring the change of blocking connections or rejecting new connections also in this patch.
> 
> So that we can avoid run-away effect of crashing the server.

:+1:, will do.

2017-03-28 22:00 UTC, vadmeste commented
I've added a new commit which returns http 503 / service unavailable when the number of concurrent requests reaches 9k, this is less than 10k.

By the way, I was wrong interpreting the problem in the first place. Having 4000 parallels connections means we should have 8000 maximum goroutines but not threads. Number of threads is usually less than the number of goroutines, especially when many goroutines are blocked. But anyway, this patch will protect Minio from all use cases I can think of.

2017-03-28 23:16 UTC, krishnasrinivas commented
> By the way, I was wrong interpreting the problem in the first place. Having 4000 parallels connections means we should have 8000 maximum goroutines but not threads. Number of threads is usually less than the number of goroutines, especially when many goroutines are blocked. But anyway, this patch will protect Minio from all use cases I can think of.

@vadmeste hence my previous comment:
```
for 5000 concurrent uploads, assuming all the goroutines are blocking, there would be roughly 5000 threads, right? but if the thread count is 10000 then there must be some other underlying problem? does the thread count come back to original number once the concurrent uploads stops? (when tested with a high concurrent upload count not enough to crash minio i.e)
```

Hope there is no underlying problem in minio causing high thread count.
Does the thread count come back to normalcy after the load completes?

2017-03-28 23:44 UTC, balamurugana commented on cmd/server-rlimit.go
> +		return debug.SetMaxThreads(oldMax)
As per https://golang.org/pkg/runtime/debug/#SetMaxThreads, the default value is 10,000 threads. If max value is < 10,000, you reset back to 10,000 threads.

In the above `maxLimit` of `sys.GetMaxOpenFileLimit()` is used which is 4096 in Linux by default.   In this case, the function sets back 10,000 again.

I think this function doesn't work practically.

Have you tried with other *nix?

2017-03-28 23:55 UTC, krishnasrinivas commented
@vadmeste you can undo the increaseMaxThreads related changes in the previous commit

2017-03-28 23:57 UTC, vadmeste commented
@krishnasrinivas, actually there is a difference between number of goroutines and number of threads. I've tested the following example that I wanted to share with you:

sample.go: 

```
package main

import (
        "fmt"
        "sync"
        "time"
)

func main() {

        wg := sync.WaitGroup{}

        for i := 0; i < 20000; i++ {
                wg.Add(1)
                go func() {
                        defer wg.Done()
                        time.Sleep(2 * 60 * time.Second)
                }()
        }
        fmt.Println("waiting for all finishing sleeping..")
        wg.Wait()
}
```

`$ go build sample.go`
`$ ./sample`

sample will create 20k goroutines sleep for about 2 minutes.

In another term:
`$ cat /proc/$(pidof sample)/status | grep Threads`

You can notice that the number of threads is very low. It is 7 threads in my case.

2017-03-29 00:14 UTC, vadmeste commented on cmd/server-rlimit.go
> +		return debug.SetMaxThreads(oldMax)
> In the above maxLimit of sys.GetMaxOpenFileLimit() is used which is 4096 in Linux by default. In this case, the function sets back 10,000 again.

In my case, maxLimit is 65k, (ubuntu 16.04, 64 bits)

> Have you tried with other *nix?

Actually no, that's why this code is generic and does revert SetMaxThreads when need.

2017-03-29 00:33 UTC, vadmeste commented
> Does the thread count come back to normalcy after the load completes?

Number of threads desn't come back to normal but it was always low (~ 30 threads)

2017-03-29 00:39 UTC, vadmeste commented
> @vadmeste you can undo the increaseMaxThreads related changes in the previous commit

Done

2017-03-29 00:52 UTC, krishnasrinivas approved these changes

2017-03-29 01:38 UTC, harshavardhana requested changes

2017-03-29 01:38 UTC, harshavardhana commented on cmd/server-mux.go
> +	serverMaxParallelConns = 9000
Can you add a comment on why this is chosen, perhaps even reference the github issue here for understanding.

2017-03-29 01:38 UTC, harshavardhana commented on cmd/server-mux.go
> +	maxParallelReqs int32
maxConcurrentReqs perhaps is better.. than parallel.

2017-03-29 01:38 UTC, harshavardhana commented on cmd/server-mux.go
> +			// Return ServiceUnavailable when we hit a limit of number
This is better --> `// Return HTTP service unavailable when we have reached maximum concurrent HTTP requests.`

2017-03-30 18:26 UTC, vadmeste commented
@harshavardhana, done

2017-03-30 19:03 UTC, harshavardhana approved these changes

2017-04-15 18:51 UTC, harshavardhana commented
We should close this PR @vadmeste - we don't need this. We can bring this back as needed.

2017-04-15 19:01 UTC, closed without merging