Browser: Update UI
minio/minio pull request #3969
Opened 2017-03-24 13:28 UTC by rushenn

## Description
New UI for browser
![browser-new-ui](https://cloud.githubusercontent.com/assets/13393018/24295903/e702ed8a-10c2-11e7-8988-a17df724ba06.png)

**Todo**
- Image preview
- Mobile support (Responsive)
- IE testing

## Motivation and Context

## How Has This Been Tested?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-03-24 13:35 UTC, vadmeste commented
:1st_place_medal:

2017-03-24 17:15 UTC, harshavardhana approved these changes

2017-03-25 02:04 UTC, krishnasrinivas commented
@harshavardhana i could send a separate fix for `the svgs are returning index.html` problem.

2017-03-25 02:05 UTC, harshavardhana commented
> @harshavardhana i could send a separate fix for the svgs are returning index.html problem.

Rushen already fixed it.. i tested can you test on your end?

2017-03-25 02:06 UTC, krishnasrinivas commented
> Rushen already fixed it.. i tested can you test on your end?

ah, will do.

2017-03-25 02:06 UTC, harshavardhana requested changes

2017-03-25 02:06 UTC, harshavardhana commented on README.md
This change is unrelated to this can you rebase properly locally @rushenn ?

2017-03-25 18:37 UTC, rushenn commented
@harshavardhana Rebase, please check.

2017-03-25 19:18 UTC, harshavardhana approved these changes

2017-03-27 01:35 UTC, krishnasrinivas commented
![path](https://cloud.githubusercontent.com/assets/634494/24337513/c2ad82ec-1252-11e7-82e5-e8c79e7b6fec.png)


Previously `>` was `/` which looks more intuitive as a path separator.

i.e the path would look as `test / 1 / 2 / 3`

2017-03-27 01:44 UTC, krishnasrinivas commented
![click-outside1](https://cloud.githubusercontent.com/assets/634494/24337587/abaf7d1a-1253-11e7-869d-3fc6b0109dda.png)

Here it is not obvious that you have to click somewhere outside to remove the "share-url" and "delete" buttons from the view.

Older style:


![click-outside2](https://cloud.githubusercontent.com/assets/634494/24337649/2183e68e-1254-11e7-8790-352b28050ba7.png)

Here it is obvious that you have to click outside .... as the "share-url" and "delete" buttons looks overlaid on a background.

2017-03-27 01:48 UTC, krishnasrinivas commented
![create](https://cloud.githubusercontent.com/assets/634494/24337711/a305371c-1254-11e7-802c-d90e7a61028d.png)

On mouse-over it should show a tool tip. Right now the icons are not clear on its purpose.

2017-03-27 01:52 UTC, krishnasrinivas commented
![policy](https://cloud.githubusercontent.com/assets/634494/24337786/286d0b8c-1255-11e7-901b-9bc8e3ae648b.png)

Previously we had three dots and it was intuitive that you had to click it for more options. Now it is not intuitive that you have to click the circle icon (marked in the image)

2017-03-27 01:56 UTC, krishnasrinivas commented
![bucketlist](https://cloud.githubusercontent.com/assets/634494/24337850/c14a466c-1255-11e7-81b4-d53483845310.png)

Will it be better to darken the background of the bucket selected as well?

2017-03-27 02:04 UTC, krishnasrinivas commented
![miniobrowser1](https://cloud.githubusercontent.com/assets/634494/24337954/7cbda5f6-1256-11e7-9bed-d94106beda7f.png)
![miniobrowser2](https://cloud.githubusercontent.com/assets/634494/24338022/d61cc186-1256-11e7-92fc-4e8c0263a964.png)


does the lower case look better?

2017-03-27 02:05 UTC, krishnasrinivas commented
![topicons](https://cloud.githubusercontent.com/assets/634494/24338038/1df5311e-1257-11e7-9dc3-0e2f666cc2aa.png)

Needs tooltip

2017-03-27 02:10 UTC, krishnasrinivas commented
![select-file](https://cloud.githubusercontent.com/assets/634494/24338080/7b42b300-1257-11e7-9f9e-89d155fc3923.png)

It will be better to change the file-select icon to circle when the mouse is moved over the icon, now it changes to circle if the mouse is anywhere on the row.

2017-03-27 02:15 UTC, krishnasrinivas commented
![signout](https://cloud.githubusercontent.com/assets/634494/24338176/245a5d94-1258-11e7-916b-7911ca2642ef.png)

you can use the `sign-out` icon instead of `power-off` icon

2017-03-27 10:10 UTC, rushenn commented
@krishnasrinivas Thank you, I will make sure to include these fixes as part of my next push.

2017-03-27 10:26 UTC, rushenn commented
> It will be better to change the file-select icon to circle when the mouse is moved over the icon, now it changes to circle if the mouse is anywhere on the row.

If the checkbox toggle is set to the icon only, it won't be noticed much. Since the checkboxes are hidden by default, i think it's better to keep the toggle set to the entire row.

2017-04-24 16:48 UTC, deekoder commented
Update PR with responsiveness changes.

2017-07-27 16:39 UTC, closed without merging