[WIP] lock, Windows: O_CREAT infers only GENERIC_WRITE
minio/minio pull request #3981
Opened 2017-03-27 11:28 UTC by vadmeste

Avoid using GENERIC_ALL flag when creating a file since it could
return permission denied in some Windows versions.

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-03-27 16:44 UTC, vadmeste commented
> Also can you print the relevant windows docs providing details on why GENERIC_ALL is an issue ?

GENERIC_ALL means read + write + execute, we don't really need execute in the first place that's why I didn't bother doing any investigation.

> You don't need to remove this part to avoid the perm denied.

TestLockFail() in lock_test.go doesn't like O_APPEND, so I made lock_windows.go follow lock_nix.go, let's discuss internally to validate this.

2017-03-27 18:25 UTC, harshavardhana requested changes

2017-03-27 18:25 UTC, harshavardhana commented on pkg/lock/lock_windows.go
> +	case syscall.O_RDWR,
Use a `fallthrough` don't put all of them in the same line.

2017-03-27 18:56 UTC, harshavardhana approved these changes

2017-03-27 19:47 UTC, merged

2017-03-28 08:24 UTC, imosk commented
Is there a Windows executable file produced from master which I can get to test if the problem has been fixed on my machine?

2017-03-28 10:17 UTC, vadmeste commented
> Is there a Windows executable file produced from master which I can get to test if the problem has been fixed on my machine?

@imosk, no. You will need to install go on Windows and run `go get -u github.com/minio/minio`, we are available in the slack channel (https://minio.slack.com) to assist if you want.

2017-03-28 16:00 UTC, harshavardhana commented
> Is there a Windows executable file produced from master which I can get to test if the problem has been fixed on my machine?

You could also use `docker pull minio/minio:edge` on windows.