[need-review] Return possible states a heal operation
minio/minio pull request #4045
Opened 2017-04-04 15:38 UTC by krisis

## Description

## Background
Healing algorithm returns failure only if an attempt to heal any of the disks failed. It returns success even if all disks needing heal were offline.
In its current form, heal admin REST APIs returns the above boolean state making it impossible for clients like `mc` to distinguish between an object being healed completely, partially and not.

## Solution
The fix (so far) is to return `struct { HealedCount int, OfflineCount int}` in addition to `error` for a heal-object and heal-upload operation. `mc` can make use of this to guide users better.

## Future-proof solution
This brings us to whether it is right by design to provide internal details of the healing process in admin API. We return an enumerated constant in heal-object and heal-upload API that captures the 3 result states of the heal operation, namely, `CompletelyHealed`, `PartiallyHealed` and `NotHealed`. In addition, we would return `error` to indicate if the healing operation failed to due to other I/O related errors.

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-06 00:44 UTC, deekoder commented
Can you update the API doc https://github.com/minio/minio/tree/master/docs/admin-api with the details?

2017-04-06 01:18 UTC, deekoder requested changes
Change looks ok. But please update the admin-api docs as mentioned in the comments.

2017-04-08 08:06 UTC, krisis commented
@deekoder I have added necessary admin-API docs.

2017-04-08 08:20 UTC, harshavardhana requested changes

2017-04-08 08:20 UTC, harshavardhana commented on cmd/admin-handlers.go
> +// number of disks offline
Can you add a test case for this alone?

2017-04-08 08:44 UTC, krisis commented on cmd/admin-handlers.go
> +// number of disks offline
@harshavardhana Added a unit test.

2017-04-08 09:12 UTC, harshavardhana approved these changes

2017-04-09 06:51 UTC, harshavardhana commented
@deekoder @krisis has fixed the admin API docs can you review again?

2017-04-09 06:51 UTC, harshavardhana commented
ping @vadmeste need your review here..

2017-04-09 15:37 UTC, vadmeste commented on pkg/madmin/heal-commands.go
> +	State HealState
Can you set a json tag here? `json:"state"`

2017-04-09 15:38 UTC, vadmeste requested changes
One comment, LGTM otherwise

2017-04-11 18:34 UTC, deekoder commented
I will schedule the gist review today with @abperiasamy

2017-04-11 20:15 UTC, harshavardhana commented
> I will schedule the gist review today with @abperiasamy

Is this PR waiting on the gist review? - we can merge this and proceed with gist review with a separate PR as a doc cleanup.

2017-04-12 18:48 UTC, vadmeste approved these changes

2017-04-12 21:59 UTC, deekoder commented on cmd/admin-handlers.go
> +	notHealed healState = iota
@abperiasamy :  By prefixing heal, there is namespace pollution. Use healOK, healFailed, healPartial. Always group them with common prefix to help IDEs autocomplete.

2017-04-12 22:03 UTC, deekoder commented on pkg/madmin/heal-commands.go
>  // HealResult - represents result of heal-object admin API.
@abperiasamy :  healState is duplicated in cmd/admin-handlers.go

2017-04-12 22:07 UTC, harshavardhana commented on pkg/madmin/heal-commands.go
>  // HealResult - represents result of heal-object admin API.
This is on purpose the struct on cmd/ cannot be used with `madmin` package.. Just like how `minio-go` has ListObjectsV1 struct which is similar to what server has as ListObjectInfo.

2017-04-12 22:10 UTC, harshavardhana commented
> @abperiasamy : healState is duplicated in cmd/admin-handlers.go

This is on purpose the struct on cmd/ cannot be used with madmin package.. Just like how minio-go has ListObjects struct which is similar to what server has as ListObjects.

Since madmin is imported into mc it is not required for minio server to be vendorized in mc to get admin API working. So it is written like an independent SDK capable of parsing all the Admin API REST responses and requests.

2017-04-13 06:22 UTC, harshavardhana requested changes

2017-04-13 06:22 UTC, harshavardhana commented on pkg/madmin/API.md
> +|`NotHealed` | Object/Upload wasn't healed on any of the disks |
This should be fixed as well @krisis ?

2017-04-13 06:22 UTC, krisis commented
@deekoder I have changed the `healState` values to be `HealNone`, `HealPartial` and `HealOK` respectively.

2017-04-13 06:27 UTC, krisis commented on pkg/madmin/API.md
> +|`NotHealed` | Object/Upload wasn't healed on any of the disks |
@harshavardhana yes, thanks for catching that. I have updated the PR fixing this.

2017-04-13 06:29 UTC, harshavardhana approved these changes

2017-04-14 17:06 UTC, deekoder approved these changes

2017-04-14 17:28 UTC, merged