035
minio/minio pull request #4075
Opened 2017-04-08 13:06 UTC by koolhead17

## Description
This PR cleans docker quick-start guide and adds relevant project URLS in the ``Explore Further`` section. 
## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-08 14:56 UTC, nitisht requested changes
LGTM except few small comments.

2017-04-08 14:56 UTC, NitishT commented on docs/orchestration/docker-compose/README.md
> +- [Minio Docker Quickstart Guide](https://docs.minio.io/docs/minio-docker-quickstart-guide)
Minio Docker Swarm doc link can be added here. https://docs.minio.io/docs/deploy-minio-on-docker-swarm

2017-04-08 14:56 UTC, NitishT commented on docs/orchestration/docker-swarm/README.md
> +- [Minio Docker Quickstart Guide](https://docs.minio.io/docs/minio-docker-quickstart-guide)
Minio Docker compose link can be added here, https://docs.minio.io/docs/deploy-minio-on-docker-compose

2017-04-08 14:56 UTC, NitishT commented on docs/orchestration/dcos/README.md
> +- [DC/OS Project](https://dcos.io/)
DC/OS documentation link can be added https://docs.mesosphere.com/ instead of dcos.io

2017-04-08 17:39 UTC, harshavardhana commented
What is supposed to be the PR title here ? What is 035 ?

2017-04-09 20:13 UTC, harshavardhana requested changes
PR title needs to be fixed first.  A PR title should concisely address what the PR is supposed to be before being submitted for review.

PR is also a way of documentation for future reference and understanding. When we observe something like this, the owner of the PR should quickly fix it as well.

2017-04-10 07:08 UTC, nitisht approved these changes

2017-04-10 15:06 UTC, harshavardhana requested changes

2017-04-10 15:06 UTC, harshavardhana commented on docs/orchestration/docker-swarm/README.md
> +
Spurious space m

2017-04-10 15:06 UTC, harshavardhana commented on docs/orchestration/docker-swarm/README.md
> +
Spurious space

2017-04-10 15:06 UTC, harshavardhana commented on docs/docker/README.md
> +
Spurious space.

2017-04-11 07:25 UTC, harshavardhana approved these changes

2017-04-11 07:53 UTC, merged