gateway: Support for custom endpoint.
minio/minio pull request #4086
Opened 2017-04-10 19:55 UTC by krishnasrinivas

fixes #4083

2017-04-10 20:07 UTC, harshavardhana requested changes

2017-04-10 20:07 UTC, harshavardhana commented on cmd/gateway-main.go
> +	endPoint := ctx.Args().Get(1)
is there no input validation? - I think we should.

2017-04-10 21:34 UTC, harshavardhana commented on cmd/gateway-main.go
perhaps a better name is `parseGatewayEndpoint`  and also a comment as well.

2017-04-10 21:34 UTC, harshavardhana commented on cmd/gateway-main.go
> +		// url.Parse("play.minio.io") puts play.minio.io in u.Path
In go1.8 this wouldn't happen anymore and an error will be generated, if we need to support a scenario like this. We should handle it like `net.SplitHostPort()` style.

2017-04-10 22:10 UTC, krishnasrinivas commented on cmd/gateway-main.go
> +		// url.Parse("play.minio.io") puts play.minio.io in u.Path
but it seems to work:
```
krishna@escape:~/tmp$ cat url.go
package main

import (
	"fmt"
	"net/url"
)

var asd = "asd"

func main() {
	u, err := url.Parse("play.minio.io")
	fmt.Println(err, u.Path)
}
krishna@escape:~/tmp$ go version
go version go1.8.1 linux/amd64
krishna@escape:~/tmp$ go run url.go
<nil> play.minio.io
krishna@escape:~/tmp$ 

```

2017-04-10 22:30 UTC, harshavardhana commented on cmd/gateway-main.go
> +		// url.Parse("play.minio.io") puts play.minio.io in u.Path
Doesn't work with IP @krishnasrinivas 

```
$ go run url.go
parse 192.168.1.106:9000: first path segment in URL cannot contain colon <nil>
```

2017-04-11 00:19 UTC, harshavardhana commented on cmd/gateway-main.go
> +func parseGatewayEndpoint(arg string) (endPoint string, secure bool, err error) {
add a test case? @krishnasrinivas

2017-04-11 11:18 UTC, donatello requested changes

2017-04-11 11:18 UTC, donatello commented on cmd/gateway-main.go
> +	schemeSpecified, err := regexp.MatchString(".*://", endPoint)
`arg` instead of `endPoint`? `endPoint` is part of return and at this point it is an empty string.

2017-04-11 11:18 UTC, donatello commented on cmd/gateway-main.go
> +	schemeSpecified, err := regexp.MatchString(".*://", endPoint)
Also, for a simple check like this, it is not necessary to use regular expressions:

```
schemeSpecified := len(strings.Split(arg, "://")) > 1
```

This is faster, and there is no error checking needed.

2017-04-11 20:19 UTC, harshavardhana commented
can you add a test case @krishnasrinivas ?

2017-04-11 22:42 UTC, harshavardhana approved these changes

2017-04-11 22:44 UTC, harshavardhana commented
@krishnasrinivas error in tests 

```
Installing ineffassign: Done.
Running vet: cmd/gateway-main_test.go:45: wrong number of args for format in Errorf call: 7 needed but 8 args
make: *** [vet] Error 1
```

2017-04-11 23:09 UTC, harshavardhana approved these changes

2017-04-12 00:44 UTC, merged