handlers: Ignore malformatted datetime type header
minio/minio pull request #4097
Opened 2017-04-11 20:47 UTC by vadmeste

## Description
Ignore headers, such as If-Modified-Since, If-Unmodified-Since, etc.. when they
are received with a format other than HTTP date.

## Motivation and Context
Fixes #4082 

## How Has This Been Tested?
go test

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-04-11 22:43 UTC, harshavardhana requested changes

2017-04-11 22:43 UTC, harshavardhana commented on cmd/object-handlers-common.go
> +		if givenTime, err := time.Parse(http.TimeFormat, ifModifiedSinceHeader); err == nil {
We can add a test case for this.. in CopyObject test? @vadmeste

2017-04-11 23:35 UTC, harshavardhana approved these changes

2017-04-11 23:35 UTC, harshavardhana commented
// cc @hackintoshrao - mint should capture this.

2017-04-12 19:10 UTC, krishnasrinivas approved these changes

2017-04-12 19:34 UTC, merged