fs: Remove fs meta lock when PutObject() fails
minio/minio pull request #4114
Opened 2017-04-13 21:00 UTC by vadmeste

## Description
Removing the fs meta lock file when PutObject() encounters any error
during its execution, such as upload getting permatuerly cancelled
by the client.

## Motivation and Context
Fixes #4090 

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-04-13 21:55 UTC, harshavardhana requested changes

2017-04-13 21:55 UTC, harshavardhana commented on cmd/fs-v1.go
> +			if err != nil {
Create a new function as `fsRemoveMeta()`  can be tested independently.

2017-04-14 06:53 UTC, harshavardhana requested changes

2017-04-14 06:53 UTC, harshavardhana commented on cmd/fs-v1-helpers_test.go
> +		t.Fatalf("Unable to lock file %s\n", filePath)
No need for `\n`

2017-04-14 06:53 UTC, harshavardhana commented on cmd/fs-v1-helpers_test.go
> +		t.Fatal("`%s` file found though it should have been deleted.", filePath)
t.Fatalf

2017-04-14 14:58 UTC, harshavardhana approved these changes

2017-04-14 16:43 UTC, deekoder commented
ping @krisis

2017-04-14 16:58 UTC, krisis commented on cmd/fs-v1.go
> +			if err != nil {
Pass `err` as argument to the anonymous function being deferred to make the value of `err` used inside the function predictable.

2017-04-14 17:01 UTC, krisis commented
@vadmeste, besides the one comment rest of the change look good to me

2017-04-14 17:04 UTC, harshavardhana commented on cmd/fs-v1.go
> +			if err != nil {
Keep the err in defer to be of different to avoid this .  Would be easier.

2017-04-14 17:07 UTC, vadmeste commented on cmd/fs-v1.go
> +			if err != nil {
> Pass err as argument to the anonymous function being deferred to make the value of err used inside the function predictable.

`err` here is not initialized inside the function, it is the returned error value, it looks easier to read this way.

2017-04-14 17:18 UTC, krisis commented on cmd/fs-v1.go
> +			if err != nil {
@vadmeste, I agree that `err` is not initialized inside the function. The value of `err` used inside the anonymous function is deferred to time of calling. This allows for programming errors like shadowing to cause unexpected value of `err ` to be bound inside the anonymous function. The code in its current form is fine. I am only cautioning of the kind of bugs that could creep in. These situations can be avoided by having conventions similar to avoiding shadowing of variables. This comment is meant in that spirit.

2017-04-14 17:34 UTC, vadmeste commented on cmd/fs-v1.go
> +			if err != nil {
I updated the PR, yeah it is much better.

2017-04-14 18:07 UTC, krisis approved these changes

2017-04-14 19:06 UTC, merged