docs: Add Minikube deployment to k8s docs
minio/minio pull request #4133
Opened 2017-04-15 07:11 UTC by NitishT

## Description
This PR adds docs on how to deploy Minio on Minikube

## Motivation and Context
This will help users trying to get started with Minio on Kubernetes without having to set a real container cluster. 

## How Has This Been Tested?
Run locally

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-18 02:47 UTC, harshavardhana approved these changes

2017-04-18 03:44 UTC, deekoder requested changes

2017-04-18 03:44 UTC, deekoder commented on docs/orchestration/minikube/README.md
> +* Download [`minio_distributed.sh`](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/minikube/minio_distributed.sh) and [`statefulset.yaml`](https://raw.githubusercontent.com/m
You could simply give a wget command for easy cut copy paste.

2017-04-18 03:44 UTC, deekoder commented on docs/orchestration/minikube/README.md
> +
It's better to show than ask user to execute. Makes for easy cut copy paste.

2017-04-18 03:44 UTC, deekoder commented on docs/orchestration/minikube/README.md
> +This setup is supposed to run on a laptop/computer. Hence only one disk is used as the backend for all the minio instance PVs. Minio sees these PVs as separate disks and reports the available storage
"supposed" to run sounds like we are speculating. We should sound more definitive IMO :)

2017-04-20 06:20 UTC, NitishT commented on docs/orchestration/minikube/README.md
> +* Download [`minio_distributed.sh`](https://raw.githubusercontent.com/minio/minio/master/docs/orchestration/minikube/minio_distributed.sh) and [`statefulset.yaml`](https://raw.githubusercontent.com/m
done.

2017-04-20 06:20 UTC, NitishT commented on docs/orchestration/minikube/README.md
> +
done.

2017-04-20 06:21 UTC, NitishT commented on docs/orchestration/minikube/README.md
> +This setup is supposed to run on a laptop/computer. Hence only one disk is used as the backend for all the minio instance PVs. Minio sees these PVs as separate disks and reports the available storage
I agree @deekoder . Removed `supposed`

2017-04-20 06:21 UTC, NitishT commented
Thanks for the review @deekoder. Addressed the comments, please take a look.

2017-04-21 06:17 UTC, deekoder commented
will wrap this up tomorrow. ETA : Apt 21 EOD

2017-04-21 21:30 UTC, deekoder requested changes

2017-04-21 21:30 UTC, deekoder commented on docs/orchestration/kubernetes/README.md
> +Kubernetes constructs like Deployments and StatefulSets provide perfect platform to deploy Minio server in standalone, distributed or shared mode. There are multiple options to deploy Minio on Kubern
constructs like.. sounds odd to me. I don't have kubernetes domain expertise. Just wanted to check.

2017-04-21 21:30 UTC, deekoder commented on docs/orchestration/kubernetes/README.md
> +- Minio [Helm](https://helm.sh) Chart offers a customizeable yet easy Minio deployment, with a single command. Read more about Minio Helm deployment [here](#prerequisites).
Minio Helm Chart offers a customizable (american spelling) and easy Minio deployment with a single command.

2017-04-21 21:30 UTC, deekoder commented on docs/orchestration/kubernetes/README.md
> +- If you'd like get started with Minio on Kubernetes without having to create a real container cluster, you can also [deploy Minio locally](https://raw.githubusercontent.com/minio/minio/master/docs/o
If you'd like *to* get started...

2017-04-21 21:30 UTC, deekoder commented on docs/orchestration/minikube/README.md
> +Minikube currently does not support dynamic provisioning, so we manually create PersistentVolumes(PV) and PersistentVolumeClaims(PVC) to be
..to be used by.. could it be refactored.

2017-04-22 00:18 UTC, NitishT commented
Addressed the comments @deekoder

2017-04-22 00:49 UTC, deekoder commented
I am trying it out now on my laptop.

2017-04-23 08:11 UTC, harshavardhana commented
> I am trying it out now on my laptop.

Is this validation complete @deekoder ? any surprises?

2017-04-24 16:19 UTC, deekoder commented
it works i believe.

2017-04-24 16:20 UTC, deekoder approved these changes

2017-04-24 16:20 UTC, merged