[WIP] heal: Send whitespaces to keep connections open
minio/minio pull request #4137
Opened 2017-04-17 00:07 UTC by vadmeste

## Description
Heal objects can take time to finish, send whitespaces so clients
won't get timeout error.

## Motivation and Context
Fixes #4132 

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-17 03:41 UTC, krisis commented
@vadmeste, the approach looks good to me. I shall review again once you include `newKeepConnUp` definition in the PR.

2017-04-17 17:51 UTC, harshavardhana commented on cmd/admin-handlers.go
> +type ListUploadsHealResponse struct {
Add a comment..

2017-04-17 19:50 UTC, vadmeste commented
Ready for review.

2017-04-18 06:02 UTC, krisis commented on cmd/admin-handlers.go
> +			resp.HealResult = jsonBytes
IIUC, we are sending json value inside an xml response. Isn't that unconventional and possibly inconvenient for alternate minio admin SDK authors (in the future)?

2017-04-18 06:02 UTC, krisis commented on cmd/api-errors.go
> +func getAPIErrorFromCode(errorCode APIErrorCode, resource string) *APIErrorResponse {
`getAPIErrorResponse` would be better.

2017-04-18 08:22 UTC, vadmeste commented on cmd/admin-handlers.go
> +			resp.HealResult = jsonBytes
> IIUC, we are sending json value inside an xml response. Isn't that unconventional and possibly inconvenient for alternate minio admin SDK authors (in the future)?

yes you are right, we probably need to change heal result from json to xml, what do you think ?

2017-04-18 08:23 UTC, vadmeste commented on cmd/api-errors.go
> +func getAPIErrorFromCode(errorCode APIErrorCode, resource string) *APIErrorResponse {
> getAPIErrorResponse would be better.

We already have a function with the same exact name :)

2017-04-18 08:25 UTC, krisis commented on cmd/api-errors.go
> +func getAPIErrorFromCode(errorCode APIErrorCode, resource string) *APIErrorResponse {
Oops :)

2017-04-18 08:27 UTC, krisis commented on cmd/admin-handlers.go
> +			resp.HealResult = jsonBytes
As per the new admin REST API proposal [here](https://gist.github.com/krishnasrinivas/4b216a6ec03925645253788d8e0e241d), we are moving towards JSON encoding for all our responses. We should keep that in mind.

2017-04-19 20:09 UTC, deekoder commented
Can this be merged.

2017-04-20 16:06 UTC, harshavardhana commented
It is not ready to be merged yet @deekoder reviewing and testing.

2017-04-21 13:19 UTC, vadmeste commented
I made some changes, no keep connection up structure anymore, just sending whitespaces the same way listening buckets sends notifications to clients.

2017-04-21 14:23 UTC, harshavardhana requested changes

2017-04-21 14:23 UTC, harshavardhana commented on cmd/admin-handlers.go
> +			writeBody(w, encodeResponse(elem))
We should also breakout of this loop if writes return error.

2017-04-21 14:23 UTC, harshavardhana commented on cmd/admin-handlers.go
> +			writeBody(w, []byte(" "))
Breakout if the loop if the clients return error. They closed connection.

2017-04-21 14:54 UTC, vadmeste commented on cmd/admin-handlers.go
> +			writeBody(w, []byte(" "))
Thanks, fixed now.

2017-04-21 20:38 UTC, harshavardhana commented on cmd/admin-handlers.go
> +const pingInterval = 5 * time.Second
Add a comment on why we choose this..

2017-04-21 20:40 UTC, harshavardhana approved these changes
Tested with large sets of directories, connections are properly open and wait..

2017-04-24 16:44 UTC, deekoder commented
Need to know if this can be closed?

2017-04-24 16:45 UTC, closed without merging