docs: Document homebrew install path changes for minio.
minio/minio pull request #4178
Opened 2017-04-25 19:32 UTC by deekoder

Fixes #4177 
 
## Description
Document this change so that users install the latest version of minio on macOS correctly.

## Motivation and Context
Solves the problem of installing an old version of minio using brew. Also communicates our rationale on why they have to temporarily use minio/stable/minio in their brew paths.

## How Has This Been Tested?
Locally on my mac.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ X ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ X ] My change requires a change to the documentation.
- [ X ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-25 19:37 UTC, NitishT commented on docs/minio_installation_macOS.md
> +> `brew upgrade minio` and `brew install minio` commands will no longer install the latest minio on macOS. We recommend you update to using `brew install minio/stable/minio` in all your brew paths.
`brew upgrade minio` and `brew install minio` commands will no longer install latest Minio on macOS. We recommend you update to using `brew install minio/stable/minio` in all your brew paths.

2017-04-25 19:40 UTC, harshavardhana requested changes

2017-04-25 19:40 UTC, harshavardhana commented on docs/minio_installation_macOS.md
> +# Minio Installation on macOS
We should rename the file name as a `homebrew.md`  which would provide more insights on why we choose this and link this with README.md `macOS` installation section.

2017-04-25 22:12 UTC, deekoder commented
incorporated changes. Fixed grammar @NitishT  and renamed to minio_homebrew.md @harshavardhana

2017-04-26 00:37 UTC, harshavardhana approved these changes

2017-04-26 00:43 UTC, NitishT commented on docs/minio_homebrew.md
> +Install Minio packages for macOS via brew.
Minio `binaries`?

2017-04-26 00:45 UTC, NitishT commented on docs/minio_homebrew.md
> +Step 2: Fresh Install using new path
All the words can be either capitalized or none. Since this not a header, I think small letters will be better.

2017-04-26 00:46 UTC, NitishT commented on docs/minio_homebrew.md
> +> `brew upgrade minio` and `brew install minio` commands will no longer install the latest minio binaries on macOS. We recommend you update using `brew install minio/stable/minio` in all your brew pa
We recommend you update ~using~ `brew install minio/stable/minio` in all your brew paths.?

2017-04-26 00:46 UTC, NitishT commented
Added some comments @deekoder

2017-04-26 01:43 UTC, deekoder commented on docs/minio_homebrew.md
> +Step 2: Fresh Install using new path
But I think this is fine @NitishT

2017-04-26 01:44 UTC, deekoder commented on docs/minio_homebrew.md
> +> `brew upgrade minio` and `brew install minio` commands will no longer install the latest minio binaries on macOS. We recommend you update using `brew install minio/stable/minio` in all your brew pa
Using seems necessary to me in this sentence.

2017-04-26 02:41 UTC, nitisht approved these changes

2017-04-26 02:43 UTC, merged