web: Simplify and converge common functions in web/obj API.
minio/minio pull request #4179
Opened 2017-04-26 00:41 UTC by harshavardhana

## Description
RemoveObject() in webAPI currently re-implements some part
of the code to remove objects combine them for simplicity
and code convergence.

## Motivation and Context
web: Simplify and converge common functions in web/obj API.

## How Has This Been Tested?
Manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-26 02:00 UTC, krishnasrinivas approved these changes

2017-04-26 07:30 UTC, krisis requested changes

2017-04-26 07:30 UTC, krisis commented on cmd/object-handlers-common.go
> +	// Stacke purposefully after Unlock(), to use defer's execution
typo: Stacked?

2017-04-26 07:30 UTC, krisis commented on cmd/object-handlers-common.go
> +// DeleteObject is a convenient wrapper to delete an object, this
s/DeleteObject/deleteObject/

2017-04-26 07:30 UTC, krisis commented on cmd/object-handlers-common.go
> +		if err == nil {
we can simply write the body of the function after `err = api.DeleteObject(...)` instead of using `defer` and having to explain the evaluation order.

2017-04-26 07:30 UTC, krisis commented on cmd/object-handlers-common.go
> +func deleteObject(api ObjectLayer, bucket, object string, r *http.Request) (err error) {
How about name it `obj` instead of `api` for a parameter of type `ObjectLayer`? `api` seems out of place.

2017-04-26 07:30 UTC, krisis commented on cmd/web-handlers.go
> +	} else if err == errInvalidArgument {
Why is only `errInvalidArgument` being checked?

2017-04-26 07:50 UTC, harshavardhana commented on cmd/web-handlers.go
> +	} else if err == errInvalidArgument {
Its a new addition.

2017-04-26 07:53 UTC, krisis commented on cmd/web-handlers.go
> +	} else if err == errInvalidArgument {
@harshavardhana could you add a comment on when this error will be seen? Could you provide a test to verify that we receive `errInvalidArgument` as expected?

2017-04-26 07:58 UTC, harshavardhana commented on cmd/object-handlers-common.go
> +		if err == nil {
Done

2017-04-26 07:58 UTC, harshavardhana commented on cmd/object-handlers-common.go
> +	// Stacke purposefully after Unlock(), to use defer's execution
Removed.

2017-04-26 07:58 UTC, harshavardhana commented on cmd/object-handlers-common.go
> +func deleteObject(api ObjectLayer, bucket, object string, r *http.Request) (err error) {
Done

2017-04-26 07:58 UTC, harshavardhana commented on cmd/object-handlers-common.go
> +// DeleteObject is a convenient wrapper to delete an object, this
done

2017-04-26 07:58 UTC, harshavardhana commented on cmd/web-handlers.go
> +	} else if err == errInvalidArgument {
Already added @krisis - look at the web-handlers_test.go

2017-04-27 04:12 UTC, krisis approved these changes

2017-04-27 06:27 UTC, merged