[WIP] Add HTTP server supporting TLS certificate from PKCS#12 key
minio/minio pull request #4197
Opened 2017-04-28 18:24 UTC by balamurugana

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-04-28 19:04 UTC, vadmeste commented on cmd/server-mux.go
> -/*
Can you do server-mux refactoring in a separate PR ? (if adding pcks#12 support doesn't require that)

2017-04-28 19:28 UTC, harshavardhana commented on cmd/server-mux.go
> -/*
I concur @balamurugana we should avoid server-mux refactoring in this PR.

2017-04-29 02:40 UTC, balamurugana commented
@vadmeste @harshavardhana removed refactored HTTP server.

2017-04-29 14:59 UTC, vadmeste commented on cmd/config-dir.go
> +	minioPFXFile = "minio.pfx"
Probably this name is better 
`pfxFile = "cert.pfx"`

2017-04-29 14:59 UTC, vadmeste commented on cmd/config-dir.go
> +	minioP12File = "minio.p12"
p12 and pfx looks like to be the same exact format, I think we can keep only one.

2017-04-29 15:01 UTC, vadmeste commented on cmd/globals.go
> +	globalTLSCertificate *tls.Certificate
I think this name is better `globalSrvTLSCertificate`

2017-04-29 15:02 UTC, vadmeste commented on cmd/server-mux.go
> +func (m *ServerMux) ListenAndServe(tlsCert *tls.Certificate) (err error) {
I think `srvTLSCert` name is better

2017-04-29 15:02 UTC, vadmeste commented on cmd/server-mux.go
> +	var tlsConfig *tls.Config
I think `srvTLSConfig` name is better.

2017-04-29 15:26 UTC, vadmeste commented
Missing some documentation, you can add some paragraphs here `docs/tls/README.md`

By the way @balamurugana, how to generate this pfx file ?

I tested with this `openssl pkcs12 -export -nodes -out minio.pfx -inkey private.key -in public.crt -passout pass:` which is supposed to generate passwordless minio.pfx file from private.key and public.key.

2017-04-29 15:27 UTC, vadmeste requested changes
Documentation is missing

2017-04-29 15:58 UTC, balamurugana commented on cmd/config-dir.go
> +	minioPFXFile = "minio.pfx"
Done

2017-04-29 16:03 UTC, balamurugana commented on cmd/config-dir.go
> +	minioP12File = "minio.p12"
It is UX decision. But I am going with `.pfx`

2017-04-29 16:05 UTC, balamurugana commented on cmd/globals.go
> +	globalTLSCertificate *tls.Certificate
I think `Srv` is a duplicate meaning as this certificate is used only in server and there is no client TLS certificate we have now.

2017-04-29 16:05 UTC, balamurugana commented on cmd/server-mux.go
> +func (m *ServerMux) ListenAndServe(tlsCert *tls.Certificate) (err error) {
I think `Srv` is a duplicate meaning as this certificate is used only in server and there is no client TLS certificate we have now.

2017-04-29 16:05 UTC, balamurugana commented on cmd/server-mux.go
> +	var tlsConfig *tls.Config
I think `Srv` is a duplicate meaning as this certificate is used only in server and there is no client TLS certificate we have now.

2017-04-29 16:28 UTC, balamurugana commented
> Missing some documentation, you can add some paragraphs here docs/tls/README.md

Done



> I tested with this openssl pkcs12 -export -nodes -out minio.pfx -inkey private.key -in public.crt -passout pass: which is supposed to generate passwordless minio.pfx file from private.key and public.key.

:+1:

2017-04-29 16:29 UTC, balamurugana commented
> Documentation is missing

What are other documentation than `docs/tls/README.md`?

2017-04-29 16:37 UTC, vadmeste commented
> I tested with this openssl pkcs12 -export -nodes -out minio.pfx -inkey private.key -in public.crt -passout pass: which is supposed to generate passwordless minio.pfx file from private.key and public.key.

sorry @balamurugana, I believe that I unintentionally removed one sentence, I wanted to say that it didn't work with openssl, I am not sure what I am missing.

2017-04-29 16:49 UTC, balamurugana commented
> sorry @balamurugana, I believe that I unintentionally removed one sentence, I wanted to say that it didn't work with openssl, I am not sure what I am missing.

You can try below commands
```sh
openssl genrsa -out server.key 2048
openssl req -new -key server.key -out server.csr
openssl x509 -req -days 3650 -in server.csr -signkey server.key -out server.crt
openssl pkcs12 -keypbe PBE-SHA1-3DES -certpbe PBE-SHA1-3DES -export -in server.crt -inkey server.key -out cert.pfx -name "my-cert-name"
```

2017-05-01 02:01 UTC, harshavardhana requested changes

2017-05-01 02:01 UTC, harshavardhana commented on cmd/certs.go
> +	if decodedData, err = ioutil.ReadAll(base64.NewDecoder(base64.StdEncoding, bytes.NewBuffer(data))); err == nil {
It is better to fail here if err != nil  - rather than getting overwritten by the next `pkcs12.ToPEM()`

2017-05-01 02:01 UTC, harshavardhana commented on cmd/certs.go
> +		return nil, nil, nil, false, nil
It is more readable if we can use a switch statement here i think.

2017-05-01 02:01 UTC, harshavardhana commented on cmd/certs.go
> +	if err == nil {
Why not do `if err != nil {` and return and then do the rest?

2017-05-01 02:01 UTC, harshavardhana commented on cmd/server-mux_test.go
> +		t.Error(err)
You can do 't.Fatal(err)` instead of 'return' it is more idiomatic Go test.

2017-05-01 02:01 UTC, harshavardhana commented on docs/tls/README.md
> +Assuming that you are already having private and public certificates, or passwordless PKCS#12 certificate, you will need to copy them under `certs` in your Minio config directory using the names `pri
Is there a password based approach as well? should we mention that we don't support it?.  Have you explored about can we support it? @balamurugana

2017-05-01 02:15 UTC, balamurugana commented on cmd/certs.go
> +	if decodedData, err = ioutil.ReadAll(base64.NewDecoder(base64.StdEncoding, bytes.NewBuffer(data))); err == nil {
No. PKCS#12 certificate can be in binary format or base64 encoded.   Here `data` is tried to base64 decode if successful decoded data is taken, else the read data is used.

2017-05-01 02:21 UTC, balamurugana commented on cmd/certs.go
> +		return nil, nil, nil, false, nil
Done

2017-05-01 02:27 UTC, balamurugana commented on cmd/certs.go
> +	if err == nil {
Done

2017-05-01 02:31 UTC, balamurugana commented on cmd/server-mux_test.go
> +		t.Error(err)
Both does different where `t.Fatal()` aborts test run whereas `t.Error(); return` exits `TestServerListenAndServeTLS()`.

However I am doing `t.Fatal()` now

2017-05-01 02:38 UTC, balamurugana commented on docs/tls/README.md
> +Assuming that you are already having private and public certificates, or passwordless PKCS#12 certificate, you will need to copy them under `certs` in your Minio config directory using the names `pri
> Is there a password based approach as well?

Yes.

> should we mention that we don't support it?

I mentioned as `passwordless`. Do you want more elaborate message?

> Have you explored about can we support it? @balamurugana

As a password, for security reasons, it should be read from stdin   Other ways are insecure.  Its UX decision how password needs to be read.

2017-05-01 03:17 UTC, harshavardhana commented on docs/tls/README.md
> +Assuming that you are already having private and public certificates, or passwordless PKCS#12 certificate, you will need to copy them under `certs` in your Minio config directory using the names `pri
We can discuss that @balamurugana - should we even do it. Can we detect if a given pfx file requires password?

2017-05-01 08:38 UTC, balamurugana commented on docs/tls/README.md
> +Assuming that you are already having private and public certificates, or passwordless PKCS#12 certificate, you will need to copy them under `certs` in your Minio config directory using the names `pri
IMO storing password of the certificate for every run is as insecure as passwordless certificate.  Asking password for every run will lead some service functionality breakage eg. restart.  


> Can we detect if a given pfx file requires password?

Its possible to do

2017-05-01 17:31 UTC, deekoder commented
Document using openssl.

2017-05-10 17:23 UTC, deekoder commented
We just need to document this. I will open one and assign it to @remco.

2017-05-15 17:25 UTC, deekoder commented
Closing this PR. @nl5887  will help us document this.

2017-05-15 17:25 UTC, closed without merging