gateway-s3: vendor-update minio-go
minio/minio pull request #4220
Opened 2017-05-02 21:47 UTC by krishnasrinivas

fixes #4218

## Description

Server was using old minio-go causing signature mismatch when sha256 was empty

Also disable sha256 verification in gateway as the backend server will do it for us.

## Motivation and Context

fixes #4218

## How Has This Been Tested?

manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-02 22:28 UTC, harshavardhana requested changes

2017-05-02 22:28 UTC, harshavardhana commented on cmd/gateway-s3-anonymous.go
> +	r.SetRange(startOffset, startOffset+length-1)
Check for the error.. in-case the offsets are wrong.

2017-05-02 22:28 UTC, harshavardhana commented on cmd/gateway-s3.go
> +	r.SetRange(startOffset, startOffset+length-1)
Check for the error..

2017-05-02 22:28 UTC, harshavardhana commented on cmd/gateway-s3.go
> +	r := minio.NewGetReqHeaders()
Keep it as  `minio.NewHeadReqHeaders()`

2017-05-03 00:37 UTC, harshavardhana approved these changes

2017-05-03 01:31 UTC, nl5887 approved these changes

2017-05-03 01:46 UTC, harshavardhana approved these changes

2017-05-03 01:46 UTC, merged