Add s3 backend to help, fixes #4219
minio/minio pull request #4221
Opened 2017-05-02 21:50 UTC by nl5887

2017-05-02 22:11 UTC, harshavardhana requested changes

2017-05-02 22:11 UTC, harshavardhana commented on cmd/gateway-main.go
An example needs to be added as well - just mentioning this is not useful.

2017-05-02 22:11 UTC, krishnasrinivas commented
you can add examples as well:
```
  2. Start minio gateway server for S3 backend.
      $ export MINIO_ACCESS_KEY=accesskey
      $ export MINIO_SECRET_KEY=secretkey
      $ minio gateway s3

  3. Start minio gateway server for S3 backend on custom endpoint.
      $ export MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      $ export MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      $ minio gateway s3 https://play.minio.io:9000

```

2017-05-02 22:11 UTC, harshavardhana commented
> 3. Start minio gateway server for S3 backend on custom endpoint.
>       $ export MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
>       $ export MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
>       $ minio gateway s3 https://play.minio.io:9000

We should also show AWS S3.

2017-05-02 22:13 UTC, krishnasrinivas commented
> We should also show AWS S3.

already there:

```
  2. Start minio gateway server for S3 backend.
      $ export MINIO_ACCESS_KEY=accesskey
      $ export MINIO_SECRET_KEY=secretkey
      $ minio gateway s3
```

2017-05-02 22:29 UTC, harshavardhana commented
> already there:
> 
>   2. Start minio gateway server for S3 backend.
>       $ export MINIO_ACCESS_KEY=accesskey
>       $ export MINIO_SECRET_KEY=secretkey
>       $ minio gateway s3

Strange then why its not present in the master branch 

```
  {{.HelpName}} - {{.Usage}}

USAGE:
  {{.HelpName}} {{if .VisibleFlags}}[FLAGS]{{end}} BACKEND [ENDPOINT]
{{if .VisibleFlags}}
FLAGS:
  {{range .VisibleFlags}}{{.}}
  {{end}}{{end}}
BACKEND:
  azure: Microsoft Azure Blob Storage. Default ENDPOINT is https://core.windows.net

ENVIRONMENT VARIABLES:
  ACCESS:
     MINIO_ACCESS_KEY: Username or access key of your storage backend.
     MINIO_SECRET_KEY: Password or secret key of your storage backend.

EXAMPLES:
  1. Start minio gateway server for Azure Blob Storage backend.
      $ export MINIO_ACCESS_KEY=azureaccountname
      $ export MINIO_SECRET_KEY=azureaccountkey
      $ {{.HelpName}} azure
```

2017-05-02 22:30 UTC, harshavardhana commented
I don't see it locally 

```
minio gateway
NAME:
  minio gateway - Start object storage gateway.

USAGE:
  minio gateway [FLAGS] BACKEND [ENDPOINT]

FLAGS:
  --address value  Bind to a specific ADDRESS:PORT, ADDRESS can be an IP or hostname. (default: ":9000")
  --quiet          Disable startup banner.
  --help, -h       Show help.
  
BACKEND:
  azure: Microsoft Azure Blob Storage. Default ENDPOINT is https://core.windows.net

ENVIRONMENT VARIABLES:
  ACCESS:
     MINIO_ACCESS_KEY: Username or access key of your storage backend.
     MINIO_SECRET_KEY: Password or secret key of your storage backend.

EXAMPLES:
  1. Start minio gateway server for Azure Blob Storage backend.
      $ export MINIO_ACCESS_KEY=azureaccountname
      $ export MINIO_SECRET_KEY=azureaccountkey
      $ minio gateway azure
```

2017-05-02 22:32 UTC, krishnasrinivas commented
it's not on master, it's my comment. This was my comment:


----------------------------------------
you can add examples as well:
```
  2. Start minio gateway server for S3 backend.
      $ export MINIO_ACCESS_KEY=accesskey
      $ export MINIO_SECRET_KEY=secretkey
      $ minio gateway s3

  3. Start minio gateway server for S3 backend on custom endpoint.
      $ export MINIO_ACCESS_KEY=Q3AM3UQ867SPQQA43P2F
      $ export MINIO_SECRET_KEY=zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
      $ minio gateway s3 https://play.minio.io:9000

```

2017-05-03 22:31 UTC, deekoder commented
So what is needed further here?

2017-05-04 00:17 UTC, harshavardhana approved these changes

2017-05-04 00:37 UTC, krishnasrinivas approved these changes

2017-05-04 00:55 UTC, merged