Implement anonymous uploads, fixes #4250
minio/minio pull request #4259
Opened 2017-05-04 20:49 UTC by nl5887

2017-05-04 21:04 UTC, harshavardhana requested changes

2017-05-04 21:04 UTC, harshavardhana commented on cmd/gateway-handlers.go
> +	// Notify object created event.
We don't need this part of the code for Gateway. since we won't implement notifications in Gateway.

2017-05-04 21:40 UTC, krishnasrinivas commented on cmd/gateway-azure-anonymous.go
> +}
Azure does not support anonymous PUT, so here you can just return NotImplemented

2017-05-04 23:17 UTC, krishnasrinivas requested changes

2017-05-04 23:17 UTC, krishnasrinivas commented on cmd/gateway-s3-anonymous.go
> +	oi, err := l.Client.PutObject(bucket, object, size, data, md5sumBytes, sha256sumBytes, toMinioClientMetadata(metadata))
l.anonClient should be used

2017-05-04 23:17 UTC, krishnasrinivas commented on cmd/gateway-handlers.go
> +	reqAuthType := getRequestAuthType(r)
this is repeated again at line 190

2017-05-04 23:17 UTC, krishnasrinivas commented on cmd/gateway-handlers.go
> +
signature is not being verified when authtype is authTypeSignedV2, authTypePresignedV2, authTypePresigned, authTypeSigned

2017-05-05 00:18 UTC, krishnasrinivas approved these changes

2017-05-05 03:03 UTC, harshavardhana approved these changes

2017-05-05 03:03 UTC, merged