Add minimum requirements for MySQL notification
minio/minio pull request #4260
Opened 2017-05-04 22:46 UTC by NitishT

## Description
Added the minimum requirements for MySQL support in notification targets.

## Motivation and Context
This is important for users to know if they have proper setup to use Minio Mysql target.

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-04 22:51 UTC, donatello requested changes

2017-05-04 22:51 UTC, donatello commented on docs/bucket/notifications/README.md
> +Install MySQL from [here](https://dev.mysql.com/downloads/mysql/). To publish Minio events, you'll need `JSON` support in MySQL, available on MySQL `5.7.8` and above. We tested this setup on MySQL `5
Can remove trailing space at end of line?

2017-05-04 22:51 UTC, donatello commented on docs/bucket/notifications/README.md
> +This notification target supports two formats: _namespace_ and _access_.
Can remove trailing space at end of line?

2017-05-04 22:56 UTC, deekoder requested changes

2017-05-04 22:56 UTC, deekoder commented on docs/bucket/notifications/README.md
> +Install MySQL from [here](https://dev.mysql.com/downloads/mysql/). To publish Minio events, you'll need `JSON` support in MySQL, available on MySQL `5.7.8` and above. We tested this setup on MySQL `5
How does the user get JSON support? Just upgrade MySQL?

2017-05-04 22:57 UTC, donatello commented on docs/bucket/notifications/README.md
> +Install MySQL from [here](https://dev.mysql.com/downloads/mysql/). To publish Minio events, you'll need `JSON` support in MySQL, available on MySQL `5.7.8` and above. We tested this setup on MySQL `5
Yes, JSON data-type support in MySQL is available from a particular version onwards.

2017-05-04 23:00 UTC, deekoder commented on docs/bucket/notifications/README.md
> +Install MySQL from [here](https://dev.mysql.com/downloads/mysql/). To publish Minio events, you'll need `JSON` support in MySQL, available on MySQL `5.7.8` and above. We tested this setup on MySQL `5
ok. i approve pending the space removals.

2017-05-04 23:00 UTC, deekoder submitted a review, later dismissed
Pending : space removals.

2017-05-04 23:13 UTC, donatello approved these changes

2017-05-05 00:30 UTC, harshavardhana approved these changes

2017-05-05 00:30 UTC, merged