Add slack channel link to corrupted disk msg
minio/minio pull request #4270
Opened 2017-05-05 22:31 UTC by vadmeste

## Description
Add slack channel link to corrupted disk msg

## Motivation and Context
Better corrupted disk message.

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-05 22:35 UTC, harshavardhana requested changes

2017-05-05 22:35 UTC, harshavardhana commented on cmd/storage-errors.go
> +var errCorruptedFormat = errors.New("corrupted backend format, please join https://slack.minio.io to get assistance")
`corrupted backend format, please join https://slack.minio.io for assistance`

2017-05-05 22:39 UTC, harshavardhana submitted a review, later dismissed

2017-05-07 07:40 UTC, harshavardhana commented
Can you fix the build issues @vadmeste ..

2017-05-10 17:20 UTC, vadmeste commented
CI build detected this error:
```
=== RUN   TestServerListenAndServeTLS
panic: test timed out after 15m0s
goroutine 2281784 [running]:
panic(0x1395ee0, 0xc427f98e30)
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/runtime/panic.go:500 +0x1ae
testing.startAlarm.func1()
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/testing/testing.go:918 +0x14e
created by time.goFunc
	/home/travis/.gimme/versions/go1.7.5.linux.amd64/src/time/sleep.go:154 +0x78
```

I locally tested with go test -count=1000 many times but it didn't show any error, did soemone see this before ?

2017-05-11 08:15 UTC, harshavardhana approved these changes

2017-05-11 08:15 UTC, harshavardhana commented
@deekoder waiting on your review.

2017-05-11 19:55 UTC, deekoder approved these changes

2017-05-11 21:27 UTC, merged