[browser] Prevent duplicate policy rows from being created
minio/minio pull request #4276
Opened 2017-05-07 01:44 UTC by poornas

## Description

Duplicate bucket policy rows are created in existing browser UI when user enters same prefix or no prefix. This code change validates against existing prefixes for the bucket, and adds a new row only if it is not on file.
## Motivation and Context

Fixes issue #4267
## How Has This Been Tested?

Manually
## Types of changes

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-07 03:49 UTC, harshavardhana requested changes
Don't Make asset changes in this PR. Asset changes are done after some PRs have gone in.

2017-05-07 12:25 UTC, rushenn approved these changes
LGTM

2017-05-07 19:24 UTC, poornas commented on browser/app/js/components/PolicyInput.js
> +    this.prefix.focus()
@harshavardhana , removed ui-assets.go from the commit.

2017-05-07 19:27 UTC, harshavardhana requested changes
I think by mistake you have deleted ui-assets.go from the repo itself. Just keep it as is and only send changes related to browser component changes.

2017-05-07 19:31 UTC, harshavardhana requested changes

2017-05-07 19:31 UTC, harshavardhana commented on browser/app/js/components/PolicyInput.js
> +        message: "This prefix already exists."
"Policy already exists on this prefix, please choose a different prefix." - word it better.

2017-05-07 19:31 UTC, harshavardhana commented on browser/app/js/components/PolicyInput.js
> +  canBeSubmitted() {
canPolicyBeApplied() is better.. than a generic function name like this.

2017-05-07 22:44 UTC, krishnasrinivas commented
@poornas this is more readable:
```
--- a/browser/app/js/components/PolicyInput.js
+++ b/browser/app/js/components/PolicyInput.js
@@ -27,8 +27,22 @@ class PolicyInput extends Component {
 
   handlePolicySubmit(e) {
     e.preventDefault()
-    const {web, dispatch} = this.props
+    const {web, dispatch, currentBucket} = this.props
+
+    let prefix = currentBucket + '/' + this.prefix.value
+    let policy = this.policy.value
+
+    if (!prefix.endsWith('*')) prefix = prefix + '*'
 
+    let prefixAlreadyExists = this.props.policies.some(elem => prefix === elem.prefix)
+
+    if (prefixAlreadyExists) {
+      dispatch(actions.showAlert({
+       type: 'danger',
+       message: "Policy for this prefix already exists."
+      }))
+      return
+    }
     web.SetBucketPolicy({
       bucketName: this.props.currentBucket,
       prefix: this.prefix.value,
@@ -36,8 +50,7 @@ class PolicyInput extends Component {
     })
       .then(() => {
         dispatch(actions.setPolicies([{
-          policy: this.policy.value,
-          prefix: this.prefix.value + '*',
+         prefix, policy
         }, ...this.props.policies]))
         this.prefix.value = ''
       })
@@ -80,4 +93,4 @@ class PolicyInput extends Component {
   }
 }
```

2017-05-08 23:37 UTC, deekoder commented
how will new ux be?

2017-05-09 00:40 UTC, poornas commented
ux wont change - only change is to validate the policy prefix being added against the ones already created for that bucket so that we dont create duplicate entries.

2017-05-09 02:28 UTC, harshavardhana approved these changes

2017-05-09 02:29 UTC, harshavardhana approved these changes

2017-05-10 16:52 UTC, merged