Implementing Gateway backend Google Cloud Storage
minio/minio pull request #4298
Opened 2017-05-08 22:48 UTC by nl5887

2017-05-08 23:44 UTC, harshavardhana requested changes

2017-05-08 23:44 UTC, harshavardhana commented on cmd/gateway-main.go
> +	newObject, err := newGatewayLayer(backendType, ctx.Args()[1:])
You can use `ctx.Args().Tail()` is more meaningful in this context and also pass in as `newGatewayLayer(backendType, cli.Args)`

2017-05-08 23:44 UTC, harshavardhana commented on cmd/gateway-main.go
> +	newObject, err := newGatewayLayer(backendType, ctx.Args()[1:])
cli.Args have helpers which implement things like `cli.Args.First()`, `cli.Args.Get(0)`, `cli.Args.Get(1)`

2017-05-08 23:44 UTC, harshavardhana commented on cmd/gateway-main.go
> +	newObject, err := newGatewayLayer(backendType, ctx.Args()[1:])
These are safer methods and they don't crash.. if there are less args on the CLI.

2017-05-08 23:48 UTC, donatello approved these changes

2017-05-08 23:55 UTC, harshavardhana requested changes

2017-05-08 23:55 UTC, harshavardhana commented on cmd/gateway-gcs-layer.go
> +	_ = profile
I think there is no API or way right now, perhaps the way to customize this with GCS IAM [1] is that to use service account file. 

https://cloud.google.com/iam/docs/creating-managing-service-account-keys
```
gcloud iam service-accounts keys create \
    ~/key.json \
    --iam-account my-sa-123@my-project-123.iam.gserviceaccount.com
```

[1] - https://github.com/GoogleCloudPlatform/google-cloud-go#authorization

2017-05-08 23:55 UTC, harshavardhana commented on cmd/gateway-gcs-layer.go
> +	anonClient, err := minio.NewCore(endpoint, "", "", secure)
Azure uses basic http client for anonymous operations, we should use that instead here as well. Using two SDKs for the GCS backend is not a good idea IMHO.

2017-05-09 00:05 UTC, nl5887 commented on cmd/gateway-gcs-layer.go
> +	anonClient, err := minio.NewCore(endpoint, "", "", secure)
I agree, but this adds a lot of extra code where we will parse S3 XML output. Also we need to maintain the same code in and the minio-go client and here. Minio-go has been added as library already by the s3 gateway.

2017-05-09 00:07 UTC, fwessels commented on cmd/gateway-gcs-layer.go
> +	if v, ok := map[string]string{
Maybe just look at the first part of the AWS region, i.e. all 'ap's to asia, 'eu's to eu, etc.
This way it is a bit more resilient against future addtions of AWS regions.

2017-05-09 00:09 UTC, fwessels approved these changes

2017-05-09 00:10 UTC, nl5887 commented on cmd/gateway-gcs-layer.go
> +	if v, ok := map[string]string{
Yes, but we need to make exceptions then for ca- and sa-. Thought this was cleaner.

2017-05-09 00:12 UTC, fwessels commented on cmd/gateway-gcs-layer.go
> +	if v, ok := map[string]string{
I see, and ok.

2017-05-09 01:35 UTC, harshavardhana commented
Something failed on travis-ci @nl5887 can you take a look.. If the build is fixed we can merge this to gateway-gcs branch.

2017-05-09 06:11 UTC, nl5887 commented
This is an interesting case, as the linting is not right here. The other if branches are passing, I'll see if I can rewrite the code or make a PR for the linting.

2017-05-09 19:22 UTC, deekoder commented
@nl5887 - Can you fix the travis test. We cannot approve the PR till it passes.

2017-05-10 17:10 UTC, harshavardhana approved these changes

2017-05-10 17:40 UTC, vadmeste commented on cmd/gateway-azure.go
> +	endPoint, secure, err := parseGatewayEndpoint(args[0])
If each gateway will take care of its arguments, you need to check if `len(args) > 0` here

2017-05-10 17:42 UTC, vadmeste commented on cmd/gateway-s3.go
> +	endpoint, secure, err := parseGatewayEndpoint(args[0])
You need to check if args has elements as described above.

2017-05-10 18:21 UTC, merged

2017-05-10 18:21 UTC, harshavardhana commented
The PR is merged @vadmeste send fixes to the feature-gcs branch.