Feature gcs
minio/minio pull request #4327
Opened 2017-05-11 19:00 UTC by nl5887

Closes several issues

2017-05-11 21:05 UTC, vadmeste commented on cmd/gateway-gcs.go
> +	s = filepath.Base(s)
filepath.Base doesn't seem to work on all operating systems. I saw its internal code and it depends on os.IsPathSeparator which is '/' on unix and '\' on Windows.

2017-05-11 21:28 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	s = filepath.Base(s)
Yes it won't we need to always use path.Base() not filepath.  All incoming object names are expected to be separated by "/" not by "\\" even on windows.

2017-05-11 21:30 UTC, harshavardhana requested changes

2017-05-11 21:30 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	delimiter := "/"
We already have this variable.. as `slashSeparator`  use it.

2017-05-11 21:30 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	prefix := fmt.Sprintf("%s/multipart-%s-%s", ZZZZMinioPrefix, key, uploadID)
Use `pathJoin()`  helper.

2017-05-11 21:34 UTC, harshavardhana requested changes

2017-05-11 21:34 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	return fmt.Sprintf("%s/multipart-%s-%s-%05d", ZZZZMinioPrefix, escape(key), uploadID, partID)
use `pathJoin(ZZZMinipPrefix, fmt.Sprintf("multipart-%s-%s-%05d", escape(key), uploadID, partID)` instead.

2017-05-11 21:34 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	uploadID = strings.Replace(uploadID, "-", "", -1)
You can put this into a function and get a different UUID representation. @nl5887

2017-05-11 21:34 UTC, harshavardhana commented on cmd/gcs/gateway-gcs-url.go
> +	if spaceCount == 0 && hexCount == 0 {
why do you need this @nl5887 ?

2017-05-11 21:37 UTC, nl5887 commented on cmd/gcs/gateway-gcs-url.go
> +	if spaceCount == 0 && hexCount == 0 {
Has been removed already, doing it differently.

2017-05-12 00:33 UTC, harshavardhana commented on cmd/gcs/gateway-gcs-url.go
> +	if spaceCount == 0 && hexCount == 0 {
Cool.

2017-05-12 05:39 UTC, harshavardhana commented
You might have to rebase @nl5887

2017-05-12 20:28 UTC, nl5887 commented
@harshavardhana your opinion about the bucket translation? The reason / advantage of doing this is to make all s3 compatible libraries compatible with this feature. Libraries that don't support custom regions, won't work otherwise.

2017-05-13 05:35 UTC, harshavardhana commented
> @harshavardhana your opinion about the bucket translation? The reason / advantage of doing this is to make all s3 compatible libraries compatible with this feature. Libraries that don't support custom regions, won't work otherwise.

@krishnasrinivas @nl5887 - looks like the advantage of doing region mapping for GCS is that it creates multi region buckets. Which in a way is nicer and also default recommended way to create bucket on the Google Cloud Console. 

Disadvantage is that it disallows doing anything else other than multi regions. We can see what is the default behavior that we can follow here with @abperiasamy

2017-05-14 18:41 UTC, nl5887 commented
Actually, we don't have that issue. The naming of google regions is different (https://cloud.google.com/storage/docs/bucket-locations), so you can choose specific regions (like us-central1).

2017-05-14 19:07 UTC, harshavardhana commented
> @harshavardhana @krishnasrinivas Actually, we don't have that issue. The naming of google regions is different (https://cloud.google.com/storage/docs/bucket-locations), so you can choose specific regions (like us-central1).

Oh i see so the change here is done to allow for S3 specific region mapping to GCS.

2017-05-14 19:43 UTC, krishnasrinivas commented
> @harshavardhana your opinion about the bucket translation? The reason / advantage of doing this is to make all s3 compatible libraries compatible with this feature. Libraries that don't support custom regions, won't work otherwise.

@nl5887 S3 client libs will not be tied to regions else they will not be forward compatible with new regions being added to AWS.

The thought of doing the translation makes sense when you are doing it for object metadata (i.e x-amz-meta-key should be translated to x-ms-meta-key)

But doing so for regions has cons and no pros.
cons:
* if GCS introduces new region `australia` then it won't have a corresponding AWS region
* GCS gateway users have to be aware of this map to create region specific buckets

2017-05-15 08:19 UTC, nl5887 commented
@krishnasrinivas There are all kind of legacy applications, that should want to migrate to Minio but cannot because they cannot modify the software (anymore). Anyhow, I think enough has been said about this, time for @harshavardhana and @abperiasamy to decide on this.

2017-05-16 20:16 UTC, krishnasrinivas commented
Discussed with @abperiasamy the mapping should be there only for default region. i.e `us-east-1` -> `us` because clients can call makebucket with default region `us-east-1`

The s3-libs are only tied to default region (when regions are not specified) and no other regions.
Legacy applications should never have hardcoded region settings, if indeed we come across such applications, then we can re-visit this.

2017-05-17 15:14 UTC, harshavardhana approved these changes

2017-05-17 15:16 UTC, merged