Add minimum requirements sections to notifications docs
minio/minio pull request #4328
Opened 2017-05-11 19:44 UTC by donatello

## Description

Adds extra info in docs about minimum versions of external notification targets

## Motivation and Context

Improve docs

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-11 21:42 UTC, deekoder requested changes

2017-05-11 21:42 UTC, deekoder commented on docs/bucket/notifications/README.md
> +### Step 0: Ensure minimum requirements are met
Hate to nitpick. Please use step 1, step 2  instead of 0, 1. Just to be consistent with other docs.

2017-05-11 21:42 UTC, deekoder commented on docs/bucket/notifications/README.md
> +### Step 0: Ensure minimum requirements are met
Same Step 0 to Step 1.

2017-05-11 21:56 UTC, donatello commented on docs/bucket/notifications/README.md
> +### Step 0: Ensure minimum requirements are met
Fixed.

2017-05-11 23:38 UTC, deekoder submitted a review, later dismissed
Did not test it but since its a text change. I approve.

2017-05-11 23:56 UTC, NitishT commented on docs/bucket/notifications/README.md
> +We tested Minio with Kafka version version 0.10.1.0. More recent versions should also work. Internally Minio uses the [Shopify/sarama](https://github.com/Shopify/sarama/) library distributed from [go
Text here is a little vague, can you try to be specific about the supported version?

2017-05-11 23:59 UTC, nitisht approved these changes

2017-05-12 00:01 UTC, deekoder approved these changes

2017-05-12 00:34 UTC, merged