gateway: allow buckets to be created in regions requested by client
minio/minio pull request #4335
Opened 2017-05-12 01:45 UTC by krishnasrinivas

## Description

Allow buckets to be created in the client requested region in gateway mode.

## Motivation and Context

fixes #4241

## How Has This Been Tested?

manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-12 02:28 UTC, harshavardhana requested changes

2017-05-12 02:28 UTC, harshavardhana commented on cmd/gateway-handlers.go
> -	if serverRegion != location {
We can use isValidLocation instead here. And return error properly. Since we need to honor if gateway region was set manually.

2017-05-12 17:14 UTC, krishnasrinivas commented on cmd/gateway-handlers.go
> -	if serverRegion != location {
> Its a behavior problem @krishnasrinivas if user says that this is my region. We are ought to honor it IMHO. For the most part they won't set it. But we willfully ignoring what was set by user is not right.

I see what you mean, if user needs to create a bucket in specific region he should run the gateway in empty reason.

we can use isValidLocation from here:
https://github.com/minio/minio/pull/4329/commits/b58048f1e6ebe980160de40feb819c6a77a931c1

2017-05-13 15:28 UTC, nl5887 commented
This one is already included in https://github.com/dutchcoders/minio/commit/0954addaad8a6395fca57de0b69d0296dc12b8f3, with fix as discussed.

2017-05-14 20:29 UTC, krishnasrinivas commented
@nl5887 will close this PR then

2017-05-14 20:29 UTC, closed without merging