Browser: Fix Safari Blob download issue
minio/minio pull request #4357
Opened 2017-05-16 20:11 UTC by rushenn

## Description
Make "Download all as zip" button functional in Safari by setting proper Blob type and filename.

## Motivation and Context
https://github.com/minio/minio/issues/3943

## How Has This Been Tested?
Tested manually on latest Safari (10.1).

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-16 21:24 UTC, harshavardhana commented on browser/app/js/actions.js
> +        anchor.download = req.bucketName+'-'+req.prefix.slice(0, -1)+'.zip';
what is the final name of the file downloaded ? can you provide an example say bucketName is "testbucket"  and prefix is "a/b/c/d/movies/"

2017-05-16 22:28 UTC, poornas requested changes
download file name will end with "-" even when there is no prefix. "-" should be added conditionally only when there is a prefix.

2017-05-17 07:08 UTC, rushenn commented on browser/app/js/actions.js
> +        anchor.download = req.bucketName+'-'+req.prefix.slice(0, -1)+'.zip';
It'll be `testbucket-a-b-c-d-movies.zip`

2017-05-17 07:11 UTC, rushenn commented
@poornas I'm using a slice function `req.prefix.slice(0, -1)` to trim the last character which is '-'

2017-05-17 07:26 UTC, rushenn commented
@poornas Conditionally added the separator

`var separator = req.prefix.length > 1 ? '-' : ''`

2017-05-17 07:31 UTC, rushenn commented
@harshavardhana Example filename for the following will be `test-a-b-c-d-movies.zip`

Bucket Name: test
Prefix: a/b/c/d/movies 

And if there is no any prefix available, it'll be just `test.zip`

2017-05-17 07:32 UTC, harshavardhana commented
> @harshavardhana Example filename for the following will be test-a-b-c-d-movies.zip
> 
> Bucket Name: test
> Prefix: a/b/c/d/movies
> 
> And if there is no any prefix available, it'll be just test.zip

:+1:

2017-05-17 21:50 UTC, deekoder requested changes
Rushenn can you set this up change for me to test it via my safari?

2017-05-17 22:11 UTC, rushenn commented
@deekoder Can you try pulling the changes from [this](https://github.com/rushenn/minio/tree/downloads) branch?

2017-05-17 23:07 UTC, poornas approved these changes

2017-05-17 23:07 UTC, deekoder commented
done. fix fails. Updated the bug.

2017-05-18 00:02 UTC, deekoder approved these changes

2017-05-18 00:03 UTC, deekoder commented
Approved now.

2017-05-18 00:03 UTC, merged