added secrets to distributed swarm minio
minio/minio pull request #4374
Opened 2017-05-19 08:56 UTC by morph027

## Description

I've just added the supports for swarm secrets to the docker compose file for distributed minio.

## Motivation and Context

Secrets are just better than env. vars.

## How Has This Been Tested?

* created secrets according to https://docs.minio.io/docs/minio-docker-quickstart-guide
* deployed stack

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] contrib/3rdparty improvement

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-19 17:07 UTC, NitishT commented
@morph027 This looks great. Could you also add details on how to run this in the Swarm guide - https://github.com/minio/minio/blob/master/docs/orchestration/docker-swarm/README.md

2017-05-19 18:20 UTC, morph027 commented
Jip, coming up.

2017-05-20 06:07 UTC, krisis approved these changes
LGTM. Thank you @morph027 for the PR.

2017-05-20 06:07 UTC, harshavardhana submitted a review, later dismissed

2017-05-20 06:08 UTC, harshavardhana commented
@NitishT any other changes needed ?

2017-05-20 06:12 UTC, NitishT commented
@harshavardhana I need to try it out locally once, will update once done.

2017-05-20 18:02 UTC, deekoder commented
@NitishT i will merge this after you complete testing.

2017-05-20 20:10 UTC, nitisht requested changes
@morph027 When I tried running the command `docker stack deploy --compose-file=docker-compose-secrets.yaml minio_stack` (with the new file) 

I get the error `secrets Additional property secrets is not allowed`. Can you help me with what is wrong here.

2017-05-20 20:10 UTC, NitishT commented on docs/orchestration/docker-swarm/README.md
>  Download the [Docker Compose file](https://github.com/minio/minio/blob/master/docs/orchestration/docker-swarm/docker-compose.yaml?raw=true) on your Swarm master. Then execute the command
Can you change the `Docker Compose file` link to the new compose file as well.

2017-05-20 20:10 UTC, NitishT commented on docs/orchestration/docker-swarm/README.md
>  docker stack deploy --compose-file=docker-compose.yaml minio_stack
Command line argument needs to be changed as well.

2017-05-22 07:07 UTC, harshavardhana approved these changes

2017-05-22 17:31 UTC, NitishT commented
Thanks for the update @morph027 works fine now. LGTM

2017-05-22 17:31 UTC, nitisht approved these changes

2017-05-22 18:30 UTC, merged