Add support for timeouts for locks
minio/minio pull request #4377
Opened 2017-05-20 05:37 UTC by fwessels

This is a (p)review of timeout support for the namespace-lock. In addition to an updated `dsync`, also a new package `lsync` is introduced. Both packages support the same API for locks that can time out.

When a timeout occurs this is propagated back up  so that an error can be communicated to the client instead of the current behaviour where long/infinite hangs occur.

The default timeout value has been set at 10 minutes, we may want to use different timeout values in different places (or even simulate a blocking lock by passing in 'indefinite' in some cases).

Preliminary testing has been done, but more testing needs to be done.

2017-05-20 07:50 UTC, balamurugana commented
@fwessels It would be very helpful why `sync.{RW}Mutex` does not fit in cases where `lsync` is better to go WRT minio?  Unfortunately I don't see any issue# related to this PR and `lsync`

2017-05-20 18:00 UTC, fwessels commented
@bala the default sync package has just blocking behaviour which is in most cases (in combination with spinning up a Go routine) a good way of handling.
In our case it can however lead to "indefinite" locks when e.g. quorum is missing or there is a long or stale lock. By allowing locks to time out we can properly report an error back to the client.
See for instance #3185.

2017-05-20 18:37 UTC, harshavardhana commented
Locking a critical piece in the stack - @deekoder this PR requires a separate testing cycle not just PR review and local testing, just like `feature-gcs` to validate this in all necessary conditions. 

Especially to go through https://github.com/minio/chaos, mint, perftest etc.

2017-05-24 17:17 UTC, deekoder commented
ok @harshavardhana are we blocked from beginning review ?

2017-05-24 17:58 UTC, harshavardhana commented
> ok @harshavardhana are we blocked from beginning review ?

Reviewing point of view the PR is fine and it is doing what is expected from the originally discussed idea, what essentially needs to be done is validating this at scale like how we did for distributed server testing on perhaps a good number of servers.

It is also required that @abperiasamy takes a look at this and provides his feedback on the type of timeouts we are using, should they be made configurable under various scenarios etc. 

- Object API calls should have lower timeout than 10minutes default? say in matter of 30secs?
- Healing API calls should have higher timeout or defaulted to 10minutes? 
- Listing, Stat operations should have lower timeout than even 30secs? like 10secs? 

We need to discuss and decide on this.

2017-05-24 18:37 UTC, fwessels commented
Also ties in to https://github.com/minio/minio/issues/4367 (dynamic timeouts)

2017-06-06 22:59 UTC, deekoder commented
Marking it blocked since we have to extensively test after the release.

2017-06-28 13:58 UTC, fwessels commented
Rebased this PR on master.

## `dynamicTimeout`

Other changes include the addition of `dynamicTimeout` for dynamically adapting timeout values. A `dynamicTimeout` object is instantiated with an initial value and a minimum timeout value. Based on the actual results of using the timeout value, it can be increased or lowered, like for instance in: 

```
func (li *lockInstance) GetLock(timeout *dynamicTimeout) (timedOutErr error) {
	lockSource := getSource()
	start := UTCNow()
	readLock := false
	if !li.ns.lock(li.volume, li.path, lockSource, li.opsID, readLock, timeout.Timeout()) {
		timeout.LogFailure()
		return OperationTimedOut{Path: li.path}
	}
	timeout.LogSuccess(UTCNow().Sub(start))
	return
}
```

`LogFailure` means that a lock has not been acquired (and thus the timeout value can be considered too short), in case a lock is acquired the actual time is passed in logged via `LogSuccess`. After registering a series of either failures or successes the timeout value is then adjusted.

## Initial timeout values

Four categories of timeouts have been defined, each with their own timeout values:

```
	globalListingTimeout   = newDynamicTimeout(30*time.Second, 5*time.Second)  // timeout for listing related ops
	globalObjectTimeout    = newDynamicTimeout(1*time.Minute, 10*time.Second)  // timeout for Object API related ops
	globalOperationTimeout = newDynamicTimeout(10*time.Minute, 30*time.Second) // default timeout for general ops
	globalHealingTimeout   = newDynamicTimeout(30*time.Minute, 1*time.Minute)  // timeout for healing related ops
```

However I would proposed to do the initial release with longer timeouts, as per:

```
	globalListingTimeout   = newDynamicTimeout( /*30*/ 600*time.Second /*5*/, 600*time.Second) // timeout for listing related ops
	globalObjectTimeout    = newDynamicTimeout( /*1*/ 10*time.Minute /*10*/, 600*time.Second)  // timeout for Object API related ops
	globalOperationTimeout = newDynamicTimeout(10*time.Minute /*30*/, 600*time.Second)         // default timeout for general ops
	globalHealingTimeout   = newDynamicTimeout(30*time.Minute /*1*/, 30*time.Minute)           // timeout for healing related ops
```
(thus all 10 minutes, plus healing at 30 minutes).

We can then first see if there are no “logical” errors without too tight timeout values, once this has been found okay in practice, we can then gradually “tighten” the timeout values in a couple of steps to the eventual values as we see fit. (And note that using very large timeout values would effectively imply no functional changes at all, as the timeouts would never be hit.)

## Testing 

As testing with long timeouts is kind of hard/tedious, I’ve actually tested manually (both XL and distributed) with a custom build with low values (eg. 3 seconds for timeouts above), so as to force timeout occurring.

2017-08-03 21:48 UTC, deekoder commented
@fwessels  we are ready to review. Can you please rebase once again.

2017-08-04 06:27 UTC, balamurugana commented
Conflict needs to be resolved.

2017-08-04 06:59 UTC, harshavardhana requested changes

2017-08-04 06:59 UTC, harshavardhana commented on vendor/github.com/minio/lsync/lmutex.go
> +	doneCh, start := make(chan struct{}), time.Now()
Perhaps UTC is better?

2017-08-04 06:59 UTC, harshavardhana commented on vendor/github.com/minio/lsync/lrwmutex.go
> +const WRITELOCK = -1
Perhaps constants can be defined like this? 

```
const (
     WRITELOCK = -1 + iota
     NOLOCKS
     READLOCKS
)
```

2017-08-04 06:59 UTC, harshavardhana commented on vendor/github.com/minio/lsync/lrwmutex.go
> +	doneCh, start := make(chan struct{}), time.Now()
UTC as well.

2017-08-09 21:09 UTC, fwessels commented on vendor/github.com/minio/lsync/lmutex.go
> +	doneCh, start := make(chan struct{}), time.Now()
Will do.

2017-08-09 21:09 UTC, fwessels commented on vendor/github.com/minio/lsync/lrwmutex.go
> +const WRITELOCK = -1
Yes, this is nicer, will change.

2017-08-09 21:09 UTC, fwessels commented on vendor/github.com/minio/lsync/lrwmutex.go
> +	doneCh, start := make(chan struct{}), time.Now()
Will do.

2017-08-09 21:42 UTC, harshavardhana requested changes
Minor things, codewise LGTM.  Continuing to test.

2017-08-09 21:42 UTC, harshavardhana commented on cmd/dynamic-timeouts.go
> + * Minio Cloud Storage, (C) 2016 Minio, Inc.
Copyright should be 2017 here.

2017-08-09 21:42 UTC, harshavardhana commented on cmd/dynamic-timeouts_test.go
> + * Minio Cloud Storage, (C) 2016 Minio, Inc.
Same here..

2017-08-09 22:58 UTC, fwessels commented on cmd/dynamic-timeouts.go
> + * Minio Cloud Storage, (C) 2016 Minio, Inc.
Will do

2017-08-09 22:58 UTC, fwessels commented on cmd/dynamic-timeouts_test.go
> + * Minio Cloud Storage, (C) 2016 Minio, Inc.
Will do

2017-08-10 17:38 UTC, krisis requested changes
These are some initial review comments. Overall the changes look OK, I will be running some tests locally.

2017-08-10 17:38 UTC, krisis commented on cmd/namespace-lock.go
> +			errorIf(err, "Failed to delete lock info entry")
we could add `params` and `opsID` to the error log. It would come handy during debugging.

2017-08-10 17:38 UTC, krisis commented on cmd/namespace-lock.go
>  	// Locking here can block.
minor nit: Locking here can block until timeout?

2017-08-10 17:38 UTC, krisis commented on cmd/namespace-lock.go
> +				errorIf(err, "Failed to delete lock info entry")
printing `param` in error log will be useful during debugging.

2017-08-10 17:38 UTC, krisis commented on cmd/namespace-lock_test.go
> +	if !testCase.lk("a", "b", "c", 60*time.Second) { // lock once.
we should check for the lock entry only if we acquired the lock.

2017-08-10 17:38 UTC, krisis commented on cmd/namespace-lock_test.go
> +// This test fails -- disabled for now
Is this still the case?

2017-08-10 17:38 UTC, krisis commented on cmd/namespace-lock_test.go
> +	// sleeping so that we can predict the order of the write locks held. <---- order cannot be predicted
should we just rewrite this test differently if it is non-deterministic?

2017-08-10 22:39 UTC, fwessels commented on cmd/namespace-lock.go
>  	// Locking here can block.
Will update comment

2017-08-10 22:43 UTC, fwessels commented on cmd/namespace-lock.go
> +			errorIf(err, "Failed to delete lock info entry")
Will do.

2017-08-10 22:43 UTC, fwessels commented on cmd/namespace-lock.go
> +				errorIf(err, "Failed to delete lock info entry")
Will do.

2017-08-11 00:45 UTC, fwessels commented on cmd/namespace-lock_test.go
> +	if !testCase.lk("a", "b", "c", 60*time.Second) { // lock once.
Will change to Fatalf()

2017-08-11 00:51 UTC, fwessels commented on cmd/namespace-lock_test.go
> +// This test fails -- disabled for now
This test case is flawed as it is making implicit assumptions about the order of events (plus explicit synchronisation) so it is actually a bit of surprise that it is working.
Removing this testcase (also in lieu of additional test cases in lsync).

2017-08-11 00:51 UTC, fwessels commented on cmd/namespace-lock_test.go
> +	// sleeping so that we can predict the order of the write locks held. <---- order cannot be predicted
See above, removing

2017-08-19 01:24 UTC, balamurugana reviewed
LGTM

2017-08-21 05:43 UTC, harshavardhana commented
Sorry @fwessels lagging behind on testing this. Will be doing it this week.

2017-08-21 16:52 UTC, fwessels commented
@harshavardhana no worries, better safe than sorry on this one...

2017-08-25 21:56 UTC, krisis approved these changes
Tested locally, LGTM :+1:

2017-08-25 23:37 UTC, balamurugana approved these changes
mint succeeded

2017-08-31 18:10 UTC, harshavardhana approved these changes

2017-08-31 18:23 UTC, harshavardhana approved these changes
Approving despite decrease in code coverage. Large parts of the code can only be tested outside in mint.

2017-08-31 18:29 UTC, merged