Add nsswitch.conf to our docker image
minio/minio pull request #4379
Opened 2017-05-20 10:43 UTC by harshavardhana

## Description
Add nsswitch.conf to our docker image

## Motivation and Context
This will cause the alpine images to resolve DNS 
using /etc/hosts along with the normal DNS resolver.

## How Has This Been Tested?
Manually setting /etc/hosts

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-20 11:02 UTC, balamurugana commented on Dockerfile
> +RUN echo 'hosts: files dns' >> /etc/nsswitch.conf
Is it good idea to conditionally add/edit `hosts: files dns` than forceful append?

2017-05-20 16:26 UTC, harshavardhana commented on Dockerfile
> +RUN echo 'hosts: files dns' >> /etc/nsswitch.conf
In-fact this file doesn't even exist @balamurugana inside the container. It is meant for only one purpose.

2017-05-21 01:09 UTC, balamurugana requested changes

2017-05-21 01:09 UTC, balamurugana commented on Dockerfile.aarch64
> +     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
Two `RUN` have `/etc/nsswitch.conf` updated.  Is it expected?

2017-05-21 01:09 UTC, balamurugana commented on Dockerfile.armhf
> +     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
same as above.

2017-05-21 02:49 UTC, harshavardhana commented on Dockerfile.aarch64
> +     echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf && \
Should be updated my mistake

2017-05-21 15:50 UTC, nitisht approved these changes

2017-05-22 07:10 UTC, harshavardhana commented
@balamurugana can you review once again?

2017-05-22 07:22 UTC, balamurugana approved these changes

2017-05-22 14:05 UTC, merged