gateway-azure: Convert S3 metadata to azure metadata
minio/minio pull request #4384
Opened 2017-05-22 06:59 UTC by krishnasrinivas

fixes #4292

## Description

S3 server expects metadata as
`X-Amz-Meta-Firstname: Krishna`

Azure expects metadata as
`X-Ms-Meta-Firstname: Krishna`

We need to do suitable conversion.

## Motivation and Context

fixes #4292

## How Has This Been Tested?

manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-22 16:52 UTC, hackintoshrao commented
We probably need to create a sub category of tests at Mint or temporarily maintain at which tests exclusive features for Gateways with different backends. Need Discussion around this, we are witnessing bunch of them now.

2017-05-22 18:34 UTC, harshavardhana commented
> We probably need to create a sub category of tests at Mint or temporarily maintain at which tests exclusive features for Gateways with different backends. Need Discussion around this, we are witnessing bunch of them now.

There is no need to write backend specific tests if you set x-amz-meta you expect it back from all backends unless otherwise mentioned.

2017-05-22 21:37 UTC, krishnasrinivas commented
> We probably need to create a sub category of tests at Mint or temporarily maintain at which tests exclusive features for Gateways with different backends. Need Discussion around this, we are witnessing bunch of them now.

Gateway tests will be a subset of server tests (for ex. azure backend does not support write-only policy)
So:
`mint --gateway azure ENDPOINT` will be helpful

2017-05-23 19:09 UTC, harshavardhana approved these changes

2017-05-24 18:57 UTC, poornas approved these changes
LGTM

2017-05-24 19:14 UTC, harshavardhana requested changes
With the newly agreed expectations @krishnasrinivas can add unit tests by refactoring the code?

We need to put a unit test for `blobMeta` being coverted back to Amz-Meta.

2017-05-31 02:01 UTC, harshavardhana approved these changes

2017-05-31 03:05 UTC, merged