fix: Check project id before starting gateway
minio/minio pull request #4412
Opened 2017-05-23 20:23 UTC by vadmeste

## Description
Check the format of the passed project id to show meaningful error message before passing it to GCS web services.

## Motivation and Context
Fix #4393 

## How Has This Been Tested?
go test + Manual.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-23 20:37 UTC, harshavardhana requested changes

2017-05-23 20:37 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +// ASCII letters, digits or hyphens. Project IDs must be between 6 and 30 characters.
Can you reference a link where is this documented?.

2017-05-23 20:37 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	fatalIf(err, "Unable to parse regexp string")
Don't call fatalIf inside this function.. Keep a global variale for this `regexp.MusCompile()` and then use `projectID.MatchString()`

2017-05-23 20:37 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +		fatalIf(errors.New("invalid project id"), "Unable to initialize GCS gateway")
This `errors.New` can to go to gcs-errors.go

2017-05-23 20:37 UTC, harshavardhana commented on cmd/gateway-gcs_test.go
> +
A comment for the test..

2017-05-23 20:37 UTC, harshavardhana commented on cmd/gateway-gcs_test.go
> +		{"projectid1414", true},
Add one case of 'hostnames' such as valid endpoints as well.

2017-05-23 21:36 UTC, harshavardhana commented
> fix: Check project id before starting gateway

There is no strict convention that you need to follow here @vadmeste - just that we need to keep commit title meaningful.

2017-05-23 21:37 UTC, harshavardhana approved these changes

2017-05-24 01:28 UTC, krishnasrinivas commented on cmd/gateway-gcs.go
> +	}
`^[a-z][a-z0-9-]{5,29}$` is better instead of the above if condition?

2017-05-24 10:34 UTC, vadmeste commented on cmd/gateway-gcs.go
> +	}
> ^[a-z][a-z0-9-]{5,29}$ is better instead of the above if condition?

Done

2017-05-24 14:15 UTC, harshavardhana approved these changes

2017-05-25 01:36 UTC, krishnasrinivas approved these changes

2017-05-25 01:39 UTC, merged