Filter out internal object prefix during listing
minio/minio pull request #4418
Opened 2017-05-24 07:03 UTC by krisis

## Description

We use ZZZZ-Minio/ prefix internally in our GCS gateway which should be
filtered out in the response to ListObjects.

Fixes #4415 
## Motivation and Context

See #4415 
## How Has This Been Tested?

Added a unit test for a helper function and manually tested functionality using the following program,
```go
package main

import (
	"encoding/json"
	"fmt"
	"log"

	minio "github.com/minio/minio-go"
)

func main() {
	clnt, err := minio.NewCore("localhost:9000", "minio", "minio123", false)
	if err != nil {
		log.Fatalln(err)
	}

	bucket := "krisis"
	res, err := clnt.ListObjects(bucket, "", "", "/", 1000)
	if err != nil {
		log.Fatalln(err)
	}

	if len(res.CommonPrefixes) != 1 {
		log.Fatalln("Expected only one prefix but have more %v", res.CommonPrefixes)
	}

	jsonBytes, err := json.Marshal(res)
	if err != nil {
		log.Fatalln(err)
	}
	fmt.Println(string(jsonBytes))
}
```
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-24 14:07 UTC, harshavardhana approved these changes
LGTM tested.

2017-05-24 17:30 UTC, krishnasrinivas approved these changes

2017-05-25 21:12 UTC, harshavardhana requested changes

2017-05-25 21:12 UTC, harshavardhana commented on browser/app/js/components/Browse.js
> +          info: res.MinioGlobalInfo
You have changes here from master branch.. which is not needed @krisis . Can you clean this up?

2017-05-26 04:12 UTC, krisis commented on browser/app/js/components/Browse.js
> +          info: res.MinioGlobalInfo
@harshavardhana i will be closing this PR and opening a new one with the same changes (without the confusion we have in this PR due to an incorrect rebase with master branch).

2017-05-26 04:13 UTC, closed without merging