Fix help message for GCS
minio/minio pull request #4424
Opened 2017-05-24 23:38 UTC by krishnasrinivas

## Description

`gcloud init` or `gcloud beta auth application-default login` way of providing credentials in not suitable for applications like minio.

When users want to deploy minio gateway on VMs or using docker containers we can't expect them to do "gloud init" the deployment would have to be automated/scriptable.

https://cloud.google.com/storage/docs/authentication the section Other Environments points to https://developers.google.com/identity/protocols/application-default-credentials#howtheywork which has instructions on how to use GOOGLE_APPLICATION_CREDENTIALS This is most suitable for applications like minio.

I have edited the help message accordingly. We can use the same way for our testing as well, i.e the admin will have to generate and give us credentials.json for testing.

and:

```
export GOOGLE_APPLICATION_CREDENTIALS=/home/krishna/Downloads/miniotest-d4530e7be663.json
minio gateway gcs PROJECTID
```

## Motivation and Context

https://github.com/minio/minio/issues/4391

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-25 04:54 UTC, balamurugana reviewed
What will happen if `gcloud init --console-only` is used instead of `GOOGLE_APPLICATION_CREDENTIALS`?

2017-05-25 10:34 UTC, krisis requested changes

2017-05-25 10:34 UTC, krisis commented on cmd/gateway-main.go
> +      $ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json
What a user needs to do for Minio GCS gateway to successfully authenticate with the GCS account depends on the environment it is being run. This message applies only when the gateway is run _outside_ GCP. Is it possible for the gateway to know if it's running in a GCP instance? If not, we could modify the message to,

> (When run outside Google Cloud Platform)
$ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json

2017-05-30 23:57 UTC, harshavardhana commented
@krishnasrinivas can you rebase this ?

2017-06-01 03:27 UTC, krishnasrinivas commented on cmd/gateway-main.go
> +      $ export GOOGLE_APPLICATION_CREDENTIALS=/path/to/credentials.json
Not true @krisis this step works everywhere

2017-06-01 03:31 UTC, krishnasrinivas commented
This PR is temporary fix till we fix https://github.com/minio/minio/issues/4457

2017-06-02 00:26 UTC, krishnasrinivas commented
@harshavardhana done

2017-06-20 02:47 UTC, harshavardhana commented
Is this still valid @krishnasrinivas ?

2017-06-20 21:59 UTC, closed without merging