Enable browser support for gateway
minio/minio pull request #4425
Opened 2017-05-24 23:58 UTC by poornas

Minio browser should work seamlessly when in gateway mode
## Description

Added browser support to gateway. MakeBucket requires location in gateway mode whereas object layer does not. MakeBucket was unified to use location in both modes. 
## Motivation and Context

For #4024
## How Has This Been Tested?

Locally unit tested for azure, s3 and server modes.
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-25 00:22 UTC, harshavardhana requested changes
It would also be nice to tell what type of backend the browser is talking to along with the server ip. 

https://github.com/minio/minio/pull/4422

This PR is needed to help facilitate such a feature. But this can be done outside of this PR.

Have some comments.. please check relevant to this PR.

2017-05-25 00:22 UTC, harshavardhana commented on cmd/gateway-main.go
> +		registerGatewayAPIRouter(router, newObject)
registerGatewayAPIRouter(router, newObject) should be outside this `if` block.  Browser can be disabled.. by user.

2017-05-25 00:22 UTC, harshavardhana commented on docs/gateway/README.md
> +Minio Server comes with an embedded web based object browser. Point your web browser to http://127.0.0.1:9000 ensure your server has started successfully.
Should be `Minio Gateway comes with an embedded browser UI. Point your web browser to http://127.0.0.1:9000 to ensure your server has started successfully. `

2017-05-25 18:00 UTC, poornas commented on cmd/gateway-main.go
> +		registerGatewayAPIRouter(router, newObject)
fixed.Also need to set globalIsBrowserEnabled here and update docs.

2017-05-25 21:29 UTC, harshavardhana requested changes

2017-05-25 21:29 UTC, harshavardhana commented on cmd/gateway-main.go
> +	mustGetBrowserSettingFromEnv()
Rather than `mustGet` it must be `mustSet` since Get is supposed to return, Set is supposed to set / save.

2017-05-25 21:29 UTC, harshavardhana commented on cmd/gateway-main.go
>  	// TODO: add support for custom region when we add
This TODO can be removed..

2017-05-25 22:57 UTC, harshavardhana requested changes

2017-05-25 22:57 UTC, harshavardhana commented on cmd/bucket-handlers.go
> +		return false
Can you add a test case for this? its reported that this is not covered..

2017-05-26 18:50 UTC, poornas commented
Added unit test

2017-05-26 19:31 UTC, harshavardhana submitted a review, later dismissed

2017-05-26 19:31 UTC, harshavardhana commented
Build needs to be fixed @poornas

2017-05-26 20:01 UTC, krishnasrinivas commented on cmd/web-handlers.go
> +	}
@poornas you can use go's switch statement for this which is more idiomatic in this situation:
```
switch layer := objectAPI.(type) {
case *s3Objects:
    policyInfo, err = layer.GetBucketPolicies(args.BucketName)
case *azureObjects:
    policyInfo, err = layer.GetBucketPolicies(args.BucketName)
default:
    policyInfo, err = readBucketAccessPolicy(objectAPI, args.BucketName)
}
```
You can make similar changes at other places where this is needed

2017-05-26 20:32 UTC, poornas commented on cmd/web-handlers.go
> +	}
made the change

2017-05-26 21:53 UTC, krishnasrinivas approved these changes

2017-05-26 22:25 UTC, harshavardhana requested changes

2017-05-26 22:25 UTC, harshavardhana commented on cmd/gateway-main.go
> +func mustSetBrowserSettingFromEnv(){
This needs a test case.. @poornas

2017-05-26 22:25 UTC, harshavardhana commented on cmd/gateway-s3.go
> +
This newline is not needed for this PR.

2017-05-26 22:25 UTC, harshavardhana commented on cmd/gateway-s3.go
> +
This newline is not needed for this PR..

2017-05-26 22:25 UTC, harshavardhana commented on cmd/web-handlers.go
> +	case *s3Objects:
Convert this to a function and use it in both SetBucketPolicy and ListAllBucketPolicies.

2017-05-26 22:25 UTC, harshavardhana commented on cmd/web-handlers.go
> +		if _, ok := errorCause(err).(PolicyNotFound); ok {
Refactor this slightly differently.. 

```
if _, ok := errorCause(err).(PolicyNotFound); !ok {
            return toJSONError(err, args.BucketName)
} // else PolicyNotFound found.

policyInfo = policy.BucketAccessPolicy{Version: "2012-10-17"}
```

2017-05-26 22:25 UTC, harshavardhana commented on cmd/web-handlers.go
> +	if layer, ok := objectAPI.(*s3Objects); ok {
This is not needed to be separate you can do one style here

```
switch g := objectAPI.(type) {
case GatewayLayer:
         g.SetBucketPolicies(args.BucketName, policyInfo)
```

2017-05-26 22:25 UTC, harshavardhana commented on cmd/web-handlers.go
> -	reply.UIVersion = browser.UIVersion
Sending a UIVersion is important for successful operation. otherwise it won't work.

2017-05-30 17:16 UTC, poornas commented on cmd/bucket-handlers.go
> +		return false
done

2017-05-30 17:20 UTC, harshavardhana requested changes

2017-05-30 17:20 UTC, harshavardhana commented on cmd/web-handlers.go
> +	"github.com/dustin/go-humanize"
imports should be organized little differently follow this -
 https://github.com/golang/go/wiki/CodeReviewComments#imports

2017-05-31 01:58 UTC, harshavardhana commented
ping @poornas were you able to see my comment..

2017-05-31 03:03 UTC, poornas commented on cmd/web-handlers.go
> +	"github.com/dustin/go-humanize"
this gets autoformatted in sublime editor.  Reorg'd the imports.

2017-05-31 03:04 UTC, harshavardhana commented on cmd/web-handlers.go
> +	"github.com/dustin/go-humanize"
Then perhaps sublime is formatting it wrong, they should avoid that.  You should use `goimports` which would properly format the files.

2017-06-01 01:07 UTC, harshavardhana submitted a review, later dismissed

2017-06-01 01:08 UTC, harshavardhana commented
@poornas CI tests are failing..

2017-06-01 01:42 UTC, deekoder commented
code coverage is falling @poornas can this be addressed?

2017-06-01 16:42 UTC, harshavardhana approved these changes

2017-06-01 16:43 UTC, merged