gateway: No hasPrefix check in ListObjectsV1 API
minio/minio pull request #4430
Opened 2017-05-25 11:21 UTC by krisis

Fixes #4411 

## Description

We remove the hasPrefix(marker, prefix) check from gateway's
ListObjectsV1 API delegating it to respective gateway backends (like
azure, gcs and s3).

## Motivation and Context

See #4411 
## How Has This Been Tested?

Manually using sample code snippet here - https://github.com/minio/minio/issues/4411#issuecomment-303645129
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-25 16:22 UTC, harshavardhana approved these changes

2017-05-28 15:56 UTC, harshavardhana commented
@krisis looks like your branch locally some history issue. It looks like you are sending a PR with wrong history. That is why GitHub is trying to reap in other patches.

Can you check this and resubmit.?

2017-05-30 22:53 UTC, krishnasrinivas requested changes
https://github.com/minio/minio/issues/4411 is updated with the fix we decided
```
for ListV1, in the response we will set marker as the continuation token returned by GCS just like how we do today, but with small change, we'll prefix the token with ##minio
This way if the client sends a marker with this prefix we know that we need to use it as token for GCS List
If the marker does not have ##minio prefix we'll List the GCS from the beginning and wait till we reach the marker so that we can send the client appropriate response

For ListV2, the implementation is more straight forward as both S3 and GCS will operate on a token. However if the client sends start-after then we will list from the server to filter out the entries till that entry.
```

2017-06-07 14:01 UTC, krisis commented
Closing this PR due to confusing history of commits. Will open a new PR with suggested improvements.

2017-06-07 14:01 UTC, closed without merging