Each gateway does manual params validation
minio/minio pull request #4431
Opened 2017-05-25 16:22 UTC by vadmeste

## Description
To control the order of validation, each gateway checks for
access/secret keys by itself and generates a gateway specific
error when needed.

```
$ minio gateway s3
FATA[0000] Unable to initialize gateway layer            cause=No S3 access and secret key source=[gateway-main.go:222:gatewayMain()]
~/work/gospace/src/github.com/minio/minio (issues/4396)
$ minio gateway azure
FATA[0000] Unable to initialize gateway layer            cause=No Azure account and key set source=[gateway-main.go:222:gatewayMain()]
~/work/gospace/src/github.com/minio/minio (issues/4396)
$ minio gateway gcs
FATA[0000] Unable to initialize gateway layer            cause=GCS project ID expected source=[gateway-main.go:222:gatewayMain()]
```

## Motivation and Context
Fixed #4396 

## How Has This Been Tested?
go test + Manual

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-25 16:26 UTC, harshavardhana requested changes

2017-05-25 16:26 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +		return nil, errors.New("No GCS credentials set")
`No credentials set` is correct instead of `No GCS credentials set`

2017-05-25 16:26 UTC, vadmeste commented on cmd/gateway-gcs.go
> +		return nil, errors.New("No GCS credentials set")
oups yes.

2017-05-25 16:40 UTC, vadmeste commented on cmd/gateway-gcs.go
> +		return nil, errors.New("No GCS credentials set")
> No credentials set is correct instead of No GCS credentials set

Done

2017-05-27 11:05 UTC, vadmeste commented
Comments addressed and rebased.

2017-05-31 01:55 UTC, harshavardhana commented
Can you rebase this PR @vadmeste ?

2017-05-31 10:43 UTC, vadmeste commented
> Can you rebase this PR @vadmeste ?

Done

2017-06-12 23:13 UTC, krishnasrinivas approved these changes
Can you rebase @vadmeste

2017-06-14 16:51 UTC, vadmeste commented
> Can you rebase @vadmeste

@krishnasrinivas: I rebased, but since this PR is quite old, we still need to see if we need it.

Currently this PR checks if gcs project id is provided and if access/secret keys are set in the environment. In contrary to S3 and Azure gateways which can work with credentials from config.json and not necessarily from the environment.

We need to check if we still need this.

2017-06-17 22:38 UTC, harshavardhana commented
> n contrary to S3 and Azure gateways which can work with credentials from config.json and not necessarily from the environment.

Actually it is expected that for AWS S3 and Azure credentials are always provided through ENV regardless of them being saved in the config.json, GCS also has same requirements.

You can test and update us here if the feature-gcs branch is doing all the things which are handled here.

2017-06-19 10:51 UTC, vadmeste commented
@harshavardhana, all gateways in feature-gcs branch don't require access and secret keys set in the environment.

2017-06-19 14:34 UTC, harshavardhana commented
Then its a bug @vadmeste . All gateways require env to be set regardless of saving them in config file. Config file was introduced for configs like bucket notifications which we are going to support next. But setting envs is a must and it should fail otherwise.

2017-06-22 17:38 UTC, vadmeste commented
> Then its a bug @vadmeste . All gateways require env to be set regardless of saving them in config file. Config file was introduced for configs like bucket notifications which we are going to support next. But setting envs is a must and it should fail otherwise.

Minio master requires access/secret keys from env when runnig s3 and azure, but feature-gcs branch doesn't. This PR also requires keys from env. So I guess things will be fine once feature-gcs got merged.

2017-06-22 17:38 UTC, vadmeste commented
Overall, I think we can merge this PR now if no more comments.

2017-06-22 18:56 UTC, closed without merging