Some minor fixes
minio/minio pull request #4441
Opened 2017-05-29 08:32 UTC by calvernaz

Word terminations

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-05-29 17:48 UTC, deekoder requested changes
Omg really need this PR. Thanks for fixing this @calvernaz

2017-05-29 18:06 UTC, nitisht reviewed
Thanks for the PR @calvernaz

2017-05-30 17:33 UTC, deekoder approved these changes

2017-05-30 17:35 UTC, nitisht approved these changes

2017-05-30 18:03 UTC, merged