gcs: Check if the given project id argument exists
minio/minio pull request #4453
Opened 2017-05-31 22:40 UTC by vadmeste

## Description

Using resource manager GCS API, check if the provided
project id is already created and associated to the current
user account.

## Motivation and Context
Fixes #4449 

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-05-31 22:42 UTC, harshavardhana requested changes

2017-05-31 22:42 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	"google.golang.org/api/cloudresourcemanager/v1"
Is this vendorized properly?

2017-05-31 22:45 UTC, vadmeste commented on cmd/gateway-gcs.go
> +	"google.golang.org/api/cloudresourcemanager/v1"
> Is this vendorized properly?

Not sure yet, make pkg-add doesn't automatically add dependencies, I'll wait until this test shows some errors if something is missing.

2017-05-31 23:21 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	"google.golang.org/api/cloudresourcemanager/v1"
It won't ideally show.. @vadmeste you might have to do `make pkg-list` to see what is missing.

2017-06-03 02:06 UTC, balamurugana requested changes
Is this big change required to check project id validation?
Unable to understand non-gcs changes in this PR.

2017-06-03 15:09 UTC, vadmeste commented
> Is this big change required to check project id validation?
> Unable to understand non-gcs changes in this PR.

@balamurugana, I rebased this PR, please take a look again.

2017-06-05 02:16 UTC, balamurugana requested changes

2017-06-05 02:16 UTC, balamurugana commented on cmd/gateway-gcs.go
>  	return gcsProjectIDRegex.MatchString(projectID)
This one liner function is not needed as its used only below.

2017-06-05 02:16 UTC, balamurugana commented on cmd/gateway-gcs.go
> +func checkGCSProjectID(ctx context.Context, projectID string) error {
Can't this be unit testable?

2017-06-05 11:50 UTC, vadmeste commented on cmd/gateway-gcs.go
>  	return gcsProjectIDRegex.MatchString(projectID)
> This one liner function is not needed as its used only below.

yes, the reason is to make it testable.

2017-06-05 11:51 UTC, vadmeste commented on cmd/gateway-gcs.go
> +func checkGCSProjectID(ctx context.Context, projectID string) error {
> Can't this be unit testable?

only isValidGCSProjectID can be testable. Otherwise we need a real GCS account with an existing bucket.

2017-06-22 16:47 UTC, deekoder commented
All gateways have to do a series of operations to make sure the connection is established with gateway backend.

2017-06-22 18:56 UTC, closed without merging