[WIP] Bypass network in lock requests to local server
minio/minio pull request #4465
Opened 2017-06-02 18:14 UTC by donatello

This makes lock RPCs similar to other RPCs where requests to the local
server bypass the network. Requests to the local lock-subsystem may
bypass the network layer and directly access the locking
data-structures.

This incidentally fixes #4451.

## Description

With this change, there should finally be no more scenarios in which the minio server sends a request to itself via the network - instead it directly accesses the associated data-structures in-process.

This resolves #4451 - the CA for own TLS certificate need not be added as a trusted root certificate. WIthout this change, it is required for the sole (unnecessary) purpose of making network requests to same process.

## Motivation and Context

Makes all RPCs similar - remote requests actually perform a RPC call, and local requests directly access the concerned data-structures in-process, bypassing the network.

## How Has This Been Tested?

Manually tested - but some tests are yet to be done. **Please do not merge yet.**

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-06-02 18:29 UTC, harshavardhana requested changes
Cursory review,, will do full review when this moves from WIP --> no-WIPh

2017-06-02 18:29 UTC, harshavardhana commented on cmd/namespace-lock.go
> +		if !endpoint.IsLocal {
You can use `if endpoint.Local { ... do the work. ... ; continue }` style.  That way `if else is just harder`  to read inside a for loop.

2017-06-02 18:29 UTC, harshavardhana commented on cmd/namespace-lock.go
> +		if !endpoint.IsLocal {
This also helps moving the check `if endpoint.IsLocal && mynode == -1 { myNode = index }` together to the same `if` condition.

2017-06-02 18:31 UTC, harshavardhana commented
// cc Also want @fwessels to take a look at the implementation here.. This will conflict with the lsync timeout PR submitted for lock with timeouts.

2017-06-02 21:14 UTC, vadmeste commented on cmd/namespace-lock.go
> +			clnts[index] = &(globalLockServers[localLockServerIndex].ll)
I really didn't understand the purpose of `localLockServerIndex`, don't we have only one local ?

2017-06-02 22:02 UTC, donatello commented on cmd/namespace-lock.go
> +			clnts[index] = &(globalLockServers[localLockServerIndex].ll)
This is changed in latest version.

2017-06-02 22:23 UTC, donatello commented
I have tested the change locally now by creating a 4 node cluster - m{1,2,3,4}.localhost - each of these domains is set in `/etc/hosts` to resolve to 127.0.0.1, and self-signed certs were generated for them.

For server m1, only certs for m2, m3 and m4 were copied into m1's `certs/CAs` directory, and so on for each of the other servers.

Finally, make bucket, put object and get object were tested with mc and found to be working.

2017-06-02 22:26 UTC, donatello commented on cmd/namespace-lock.go
> +		if !endpoint.IsLocal {
This is done in latest version of the PR.

2017-06-02 22:26 UTC, fwessels commented
Looked in depth at the code, looks good, should not result in any issues with locking and lock maintenance AFAIC.
Have not actually run the code.

2017-06-03 01:26 UTC, donatello commented
@vadmeste @harshavardhana - this PR is ready for review.

2017-06-03 14:37 UTC, vadmeste approved these changes
Tested with distributed/standalone erasure

2017-06-03 15:48 UTC, harshavardhana approved these changes

2017-06-05 19:02 UTC, fwessels approved these changes
As discussed this morning LGTM (and as tested by Harsha and Anis)

2017-06-05 19:25 UTC, merged