config: Avoid stale credentials in memory.
minio/minio pull request #4466
Opened 2017-06-02 20:08 UTC by harshavardhana

## Description
Avoid saving stale credentials in memory.

## Motivation and Context
Stale credentials can cause cluster failure in case of issues in config save.

## How Has This Been Tested?
Manually, by triggering of saving config.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-08-05 08:03 UTC, harshavardhana commented
can you guys review this? @donatello @balamurugana ?

2017-08-07 07:26 UTC, donatello requested changes

2017-08-07 07:26 UTC, donatello commented on cmd/admin-handlers.go
> +	currentCred := serverConfig.SetCredential(creds)
I think this should be called `prevCred` - the operation will succeed if the lock is acquired. This also makes the error handling for `.Save()` more understandable.

2017-08-07 07:26 UTC, donatello commented on cmd/config-v19.go
> +// SetRegion set new region. SetRegion retruns previous region.
Type `returns`

2017-08-07 07:26 UTC, donatello commented on cmd/config-v19.go
> +func (s *serverConfigV19) SetRegion(region string) (prevRegion string) {
Since `prevRegion` returned is not used at any of the call-sites, it appears unnecessary to add this change in.

2017-08-07 07:55 UTC, harshavardhana commented on cmd/config-v19.go
> +func (s *serverConfigV19) SetRegion(region string) (prevRegion string) {
Sure

2017-08-07 08:00 UTC, harshavardhana commented on cmd/config-v19.go
> +// SetRegion set new region. SetRegion retruns previous region.
Done

2017-08-07 08:00 UTC, harshavardhana commented on cmd/admin-handlers.go
> +	currentCred := serverConfig.SetCredential(creds)
Done

2017-08-07 10:46 UTC, donatello approved these changes

2017-08-08 19:07 UTC, balamurugana approved these changes

2017-08-08 19:14 UTC, merged