disable settings change on browser in gateway mode
minio/minio pull request #4472
Opened 2017-06-03 00:56 UTC by poornas

## Description

Browser should not allow accesskey /secret key to be changed in gateway mode for azure and s3
## Motivation and Context

Since settings for gateway mode are controlled through environment vars, browser should not allow changing these credentials
## How Has This Been Tested?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-06-05 16:14 UTC, harshavardhana requested changes
Actually we need to fix this.. globalIsEnvCreds should be set only when the ENVs are set. It shouldn't be based on the type of backend IMHO. 

This would work for GCS since GCS has custom access/secret keys.

2017-06-05 18:33 UTC, harshavardhana requested changes

2017-06-05 18:33 UTC, harshavardhana commented on cmd/gateway-main.go
> +	globalIsEnvCreds = true
Add a comment.. here @poornas - perhaps in the unit test you can check for this value to be set appropriately?

2017-06-05 18:54 UTC, krishnasrinivas approved these changes

2017-06-06 02:52 UTC, harshavardhana requested changes

2017-06-06 02:52 UTC, harshavardhana commented on cmd/gateway-main.go
> +	return accessKey, secretKey, nil
We don't need to return `accessKey, secretKey`  here in `printGatewayStartupMessage` should use similar to how `printServerStartupMessage`  calling `serverConfig.GetCredential()` 

I see that this type restructuring can wait in another PR @poornas - you can keep the code as is and send the one line change that you did in `mustGetGatewayCredsFromEnv()`

2017-06-06 21:56 UTC, harshavardhana approved these changes

2017-06-06 21:56 UTC, merged