Give more specific error message on browser for nested policies
minio/minio pull request #4488
Opened 2017-06-06 21:57 UTC by poornas

For Azure, nested policies are not implemented. Provide a more specific error message when user attempts to set nested policy. When all policies are removed for a bucket, the bucket policy also needs to be removed from gateway server.
## Description

## Motivation and Context

Fixes #4485 

## How Has This Been Tested?

Manually on Azure, S3 and server mode.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-06-06 23:39 UTC, harshavardhana submitted a review, later dismissed

2017-06-07 21:11 UTC, donatello requested changes

2017-06-07 21:11 UTC, donatello commented on cmd/web-handlers.go
> +		apiErrCode = ErrNotImplemented
For the original issue, the error message now shown is:
![image](https://user-images.githubusercontent.com/200059/26901495-e8ffb796-4b8a-11e7-82e6-51e08b428e4d.png)

It says that functionality is not implemented, but the phrasing can be made more general. The missing functionality here is not really related to headers.

2017-06-07 22:32 UTC, krishnasrinivas commented on cmd/web-handlers.go
> +		apiErrCode = ErrNotImplemented
I had suggested to use ErrNotImplemented, but @poornas you can use this as it gives more control on the error message:

```
krishna@escape:~/gocode/src/github.com/minio/minio$ git diff
diff --git a/cmd/web-handlers.go b/cmd/web-handlers.go
index bc4992e..29d25d8 100644
--- a/cmd/web-handlers.go
+++ b/cmd/web-handlers.go
@@ -1037,6 +1037,12 @@ func toWebAPIError(err error) APIError {
                apiErrCode = ErrReadQuorum
        case PolicyNesting:
                apiErrCode = ErrPolicyNesting
+       case NotImplemented:
+               return APIError{
+                       Code:           "NotImplemented",
+                       HTTPStatusCode: http.StatusBadRequest,
+                       Description:    "Functionality not implemented",
+               }
        default:
                // Log unexpected and unhandled errors.
                errorIf(err, errUnexpected.Error())
krishna@escape:~/gocode/src/github.com/minio/minio$ 
```

But now the code looks inconsistent as we return only in one case statement. So you can do this:
```
        // Convert error type to api error code.
        var apiErrCode APIErrorCode
        switch err.(type) {
        case StorageFull:
                return getAPIError(ErrStorageFull)
        case BucketNotFound:
                return getAPIError(ErrNoSuchBucket)
        case BucketExists:
                return getAPIError(ErrBucketAlreadyOwnedByYou)
        case BucketNameInvalid:
                return getAPIError(ErrInvalidBucketName)
        case BadDigest:
                return getAPIError(ErrBadDigest)
        case IncompleteBody:
                return getAPIError(ErrIncompleteBody)
        case ObjectExistsAsDirectory:
                return getAPIError(ErrObjectExistsAsDirectory)
        case ObjectNotFound:
                return getAPIError(ErrNoSuchKey)
        case ObjectNameInvalid:
                return getAPIError(ErrNoSuchKey)
        case InsufficientWriteQuorum:
                return getAPIError(ErrWriteQuorum)
        case InsufficientReadQuorum:
                return getAPIError(ErrReadQuorum)
        case PolicyNesting:
                return getAPIError(ErrPolicyNesting)
        case NotImplemented:
                return APIError{
                        Code:           "NotImplemented",
                        HTTPStatusCode: http.StatusBadRequest,
                        Description:    "Functionality not implemented",
                }
        }
        // Log unexpected and unhandled errors.
        errorIf(err, errUnexpected.Error())
        return APIError{
                Code:           "InternalError",
                HTTPStatusCode: http.StatusInternalServerError,
                Description:    err.Error(),
        }
```

2017-06-07 23:21 UTC, poornas commented on cmd/web-handlers.go
> +		apiErrCode = ErrNotImplemented
updated the PR with suggestions

2017-06-07 23:32 UTC, krishnasrinivas approved these changes

2017-06-08 00:17 UTC, donatello approved these changes

2017-06-08 00:23 UTC, harshavardhana requested changes

2017-06-08 00:23 UTC, harshavardhana commented on cmd/web-handlers.go
> +	case NotImplemented:
unit test for toWebAPIError

2017-06-08 02:30 UTC, harshavardhana approved these changes

2017-06-08 02:31 UTC, merged