GCS gateway allows apps to supply their own marker
minio/minio pull request #4495
Opened 2017-06-07 14:17 UTC by krisis

## Description

Most s3 compatible apps use object keys returned in listing as
marker. This change allows this behaviour with gateway-gcs too.

## Motivation and Context

See #4411 
## How Has This Been Tested?

Manually using both the methods discussed in #4411 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-06-07 19:27 UTC, harshavardhana reviewed
Do not know the entire gist on why ##minio is used and why and what are the consequences of doing this. 

// cc @krishnasrinivas for more information.

2017-06-07 19:27 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	ZZZZMinioPrefix  = "ZZZZ-Minio"
Needs a comment. on what this prefix means.

2017-06-08 03:17 UTC, krisis commented
@harshavardhana, the explanation from @krishnasrinivas is in the issue. I have included this in the source code comments too. Do you have any specific question regrading the solution?

2017-06-08 03:22 UTC, harshavardhana commented
> @harshavardhana, the explanation from @krishnasrinivas is in the issue. I have included this in the source code comments too. Do you have any specific question regrading the solution?

I actually saw now.. looks good .

2017-06-08 03:23 UTC, harshavardhana requested changes

2017-06-08 03:23 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	if strings.HasPrefix(marker, minioTokenPrefix) {
Can this be converted into a GCS specific function with varying inputs tested? for hasPrefix.

2017-06-08 07:25 UTC, krisis commented on cmd/gateway-gcs.go
> +	if strings.HasPrefix(marker, minioTokenPrefix) {
done

2017-06-08 07:58 UTC, krisis commented
@harshavardhana All comments are addressed.

2017-06-08 08:29 UTC, harshavardhana approved these changes

2017-06-09 23:15 UTC, krishnasrinivas approved these changes

2017-06-10 02:48 UTC, merged