[Proposal] Clarify macOS instructions on brew paths.
minio/minio pull request #4501
Opened 2017-06-08 03:02 UTC by deekoder

Clarifying to the reader about brew paths updation

## Description
Textual change to clarify language in the macOS section.

## Motivation and Context
Outdated and needs updates
 
## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-08 03:08 UTC, harshavardhana approved these changes

2017-06-08 16:17 UTC, harshavardhana requested changes
Keeping this unapproved until the minio_homebrew.md is deleted.

2017-06-09 17:33 UTC, harshavardhana approved these changes

2017-06-09 17:40 UTC, deekoder commented
@abperiasamy  approved.

2017-06-09 21:24 UTC, merged