Removed references to docker-machine in Swarm guide
minio/minio pull request #4502
Opened 2017-06-08 03:24 UTC by NitishT

## Description
Removed references to docker-machine in Swarm guide

## Motivation and Context
`docker-machine` command is not relevant for Swarm mode. It makes sense to remove all the references to `docker-machine` and just provide steps on using Swarm related commands. Also see https://github.com/minio/minio/issues/4477

## How Has This Been Tested?
Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-08 07:05 UTC, harshavardhana submitted a review, later dismissed

2017-06-08 11:00 UTC, krisis requested changes

2017-06-08 11:00 UTC, krisis commented on docs/orchestration/docker-swarm/README.md
> +Logon to the machine supposed to work as Swarm manager machines, and initialize the Swarm by
I think we can say this at a high-level as below.
```
Create a swarm on the manager node by,
<docker swarm command goes here>
```

2017-06-08 11:00 UTC, krisis commented on docs/orchestration/docker-swarm/README.md
> +To add other nodes to the Swarm, run the above command to [add worker nodes](https://docs.docker.com/engine/swarm/swarm-tutorial/add-nodes/) to the Swarm. Find detailed steps to create the Swarm on [
We should refer to the container orchestration solution as the "Swarm" and the cluster of machines hosting docker containers amongst them as the "swarm". So, we should say, "To add other nodes to the swarm ...".


> To add other nodes to the Swarm, run the above command to [add worker nodes]

In this sentence, "to add worker nodes" is superfluous. We could say, "To add other nodes to the swarm, run the above [command](https://docs.docker.com/engine/swarm/swarm-tutorial/add-nodes/)."

2017-06-10 01:25 UTC, NitishT commented on docs/orchestration/docker-swarm/README.md
> +To add other nodes to the Swarm, run the above command to [add worker nodes](https://docs.docker.com/engine/swarm/swarm-tutorial/add-nodes/) to the Swarm. Find detailed steps to create the Swarm on [
> We should refer to the container orchestration solution as the "Swarm" and the cluster of machines hosting docker containers amongst them as the "swarm".

Agreed. 

> In this sentence, "to add worker nodes" is superfluous. We could say, "To add other nodes to the swarm, run the above command."

Nodes themselves are of two types, and one can add new `master` or `worker` nodes based on their needs. I will rephrase it to make it simpler.

2017-06-10 01:26 UTC, NitishT commented on docs/orchestration/docker-swarm/README.md
> +Logon to the machine supposed to work as Swarm manager machines, and initialize the Swarm by
Done

2017-06-10 17:33 UTC, harshavardhana commented
@krisis are there any other pending changes to this doc?

2017-06-10 17:33 UTC, harshavardhana submitted a review, later dismissed

2017-06-11 02:40 UTC, krisis requested changes
Overall looks good to me except for couple of Swarm/swarm mix-ups.

2017-06-11 02:40 UTC, krisis commented on docs/orchestration/docker-swarm/README.md
> +You can now [add worker nodes](https://docs.docker.com/engine/swarm/swarm-tutorial/add-nodes/) to the swarm by running the above command. Find detailed steps to create the Swarm on [Docker documentat
s/create the Swarm/create the swarm

2017-06-11 02:40 UTC, krisis commented on docs/orchestration/docker-swarm/README.md
> +Once the Swarm is initialized, you'll see the below response.
s/Once the Swarm/Once the swarm

2017-06-11 04:12 UTC, NitishT commented on docs/orchestration/docker-swarm/README.md
> +Once the Swarm is initialized, you'll see the below response.
done.

2017-06-11 04:13 UTC, NitishT commented on docs/orchestration/docker-swarm/README.md
> +You can now [add worker nodes](https://docs.docker.com/engine/swarm/swarm-tutorial/add-nodes/) to the swarm by running the above command. Find detailed steps to create the Swarm on [Docker documentat
done

2017-06-11 04:34 UTC, krisis approved these changes

2017-06-11 04:42 UTC, harshavardhana approved these changes

2017-06-11 04:44 UTC, merged