Update Kubernetes deployment docs
minio/minio pull request #4515
Opened 2017-06-09 03:28 UTC by NitishT

## Description
Added steps for updating Minio deployment in 
- Kubernetes-yaml example 
- Helm deployment doc 

## Motivation and Context
Minio users should be able to update their deployment on Kubernetes with minimal downtime. This PR adds steps on how to update Minio Docker image in a Kubernetes cluster.

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-09 03:47 UTC, harshavardhana submitted a review, later dismissed
This is tested locally, please check for the upgrade steps.

2017-06-09 17:40 UTC, deekoder requested changes

2017-06-09 17:40 UTC, deekoder commented on docs/orchestration/kubernetes-yaml/README.md
>  Now that you have a Minio deployment running, you may either want to access it internally (within the cluster) or expose it as a Service onto an external (outside of your cluster, maybe public intern
Service or service?

2017-06-09 17:40 UTC, deekoder commented on docs/orchestration/kubernetes-yaml/README.md
>  Now that you have a Minio statefulset running, you may either want to access it internally (within the cluster) or expose it as a Service onto an external (outside of your cluster, maybe public inter
Service here reads oddly to me. Could we simply use service.

2017-06-09 17:40 UTC, deekoder commented on docs/orchestration/kubernetes-yaml/README.md
> +On successful update, you'll see a message like
Have to rephrase you'll see a message like. Too colloquial. And comes across as you will see something approximately to what we show below.

2017-06-09 17:40 UTC, deekoder commented on docs/orchestration/kubernetes/README.md
> +On successful update, you'll get output like
Same as above.

2017-06-09 19:00 UTC, NitishT commented on docs/orchestration/kubernetes-yaml/README.md
>  Now that you have a Minio deployment running, you may either want to access it internally (within the cluster) or expose it as a Service onto an external (outside of your cluster, maybe public intern
We're referring to Kubernetes Service here (https://kubernetes.io/docs/concepts/services-networking/service/) not a service in general, hence the captialization. We can change it but I felt this is a Kubernetes feature so it made sense to write it as Service.

2017-06-09 19:06 UTC, NitishT commented on docs/orchestration/kubernetes-yaml/README.md
> +On successful update, you'll see a message like
@deekoder done.

2017-06-09 19:07 UTC, NitishT commented on docs/orchestration/kubernetes/README.md
> +On successful update, you'll get output like
@deekoder done.

2017-06-10 00:39 UTC, deekoder requested changes

2017-06-10 00:39 UTC, deekoder commented on docs/orchestration/kubernetes/README.md
> +You'll get output as shown below, on a successful update.
How about : On successful update,  you should see the output below

2017-06-10 00:39 UTC, deekoder commented on docs/orchestration/kubernetes-yaml/README.md
> +You'll get a message as shown below on a successful update.
How about : On successful update, you should see the output below

2017-06-13 02:58 UTC, NitishT commented on docs/orchestration/kubernetes/README.md
> +You'll get output as shown below, on a successful update.
done @deekoder

2017-06-13 02:58 UTC, NitishT commented on docs/orchestration/kubernetes-yaml/README.md
> +You'll get a message as shown below on a successful update.
done @deekoder

2017-06-13 03:23 UTC, harshavardhana approved these changes

2017-06-13 07:44 UTC, deekoder commented on docs/orchestration/kubernetes-yaml/README.md
>  Now that you have a Minio deployment running, you may either want to access it internally (within the cluster) or expose it as a Service onto an external (outside of your cluster, maybe public intern
Ok then.

2017-06-13 07:45 UTC, deekoder approved these changes

2017-06-13 08:37 UTC, merged