Investigate issue #4461
minio/minio pull request #4521
Opened 2017-06-09 18:46 UTC by fwessels

This commit adds some code to investigate issue #4461 (rare test failure in TestListenAndServeTLS)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.

2017-06-12 16:43 UTC, harshavardhana requested changes

2017-06-12 16:43 UTC, harshavardhana commented on cmd/server-mux_test.go
> +		start := time.Now().UTC()
We can use UTCNow()

2017-06-12 20:52 UTC, fwessels commented on cmd/server-mux_test.go
> +		start := time.Now().UTC()
Done

2017-06-12 21:03 UTC, harshavardhana approved these changes

2017-06-13 00:02 UTC, harshavardhana commented
ping @NitishT

2017-06-13 00:10 UTC, nitisht approved these changes

2017-06-13 00:20 UTC, merged