Add a doc explaining various Minio server backends
minio/minio pull request #4538
Opened 2017-06-13 22:43 UTC by NitishT

## Description
This adds a new document explaining various storage backends supported by Minio server. 

## Motivation and Context
See #4529 

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-14 15:03 UTC, harshavardhana commented
Travis build has failed.. run `mispell` tool on your markdown locally to know.

2017-06-14 16:42 UTC, NitishT commented
Spelling fixed, `TestServerListenAndServeTLS` fails

2017-06-17 02:07 UTC, harshavardhana approved these changes

2017-06-17 02:08 UTC, harshavardhana requested changes
We need to talk about windows as well.

2017-06-17 02:08 UTC, harshavardhana commented on docs/deployment/backends/README.md
> +Minio server runs on a POSIX compatible filesystem like `XFS`,`EXT4` and `NTFS`. To run Minio on a filesystem backend, download Minio server binary and run as
Not just POSIX we also run in Windows platforms, we need to cover that here..

2017-06-17 02:08 UTC, harshavardhana commented on docs/deployment/backends/README.md
> +minio server /path/to/NAS
Not just NFS we also run on CIFS Samba on windows share.

2017-06-17 13:29 UTC, lbguilherme commented on docs/deployment/backends/README.md
> +Minio server can also run on JBOD attached to a single server. When you have 4 or more (and less than 16) disks attached to your server, Minio automatically enables erasure code to protect data from
`and less than 16` should be `at most 16`, as 16 itself is valid

2017-06-21 00:01 UTC, krishnasrinivas commented on docs/deployment/backends/README.md
> +minio server /path/to/node1/disk1 /path/to/node2/disk2 /path/to/node3/disk3 /path/to/node4/disk4
hostname/ip-address missing

2017-06-21 00:02 UTC, krishnasrinivas commented on docs/deployment/backends/README.md
> +
S3 missing

2017-07-26 02:07 UTC, fwessels commented on docs/deployment/backends/README.md
> +## JBOD (Just a Bunch of Disks)
of -> Of (so that the abbreviation is correct)

2017-07-26 02:08 UTC, fwessels commented on docs/deployment/backends/README.md
> +Minio also allows running multiple server instances backed by a single NAS. This will help you handle high network traffic. Read more on Minio shared-backend in [Minio shared-mode guide](https://gith
It is not just a single NAS but also a single shared directory on the NAS

2017-07-26 02:10 UTC, fwessels commented on docs/deployment/backends/README.md
> +minio server /path/to/node1/disk1 /path/to/node2/disk2 /path/to/node3/disk3 /path/to/node4/disk4
I would also say node1/disk node2/disk node3/disk etc.
(otherwise people could think that they need to select the "third" disk on node 3 etc.)

2017-07-26 02:10 UTC, fwessels commented on docs/deployment/backends/README.md
> +If you have multiple JBODs distributed across a network, you can use them as Minio server backend. With distributed JBOD, you also get protection against specific node failures, in addition to data p
protection from by erasure --> protection by erase

2017-07-26 02:11 UTC, fwessels commented on docs/deployment/backends/README.md
> +Minio server also allows using cloud storage platforms like Microsoft Azure and AWS S3 as storage backend for your Minio server. To Minio in gateway mode, run as
To Minio in gateway --> To run Minio in gateway

2017-08-04 17:50 UTC, deekoder commented
@NitishT - please advise on whether this is ready for review again

2017-08-04 17:52 UTC, NitishT commented
as per last discussion with @abperiasamy this is not required any more, given the new design being implemented.

2017-08-04 18:04 UTC, deekoder commented
Then we can close this pr @NitishT

2017-08-04 18:09 UTC, NitishT commented
closing as discussed

2017-08-04 18:09 UTC, closed without merging