xl: prepare storage should Abort properly.
minio/minio pull request #4542
Opened 2017-06-15 01:33 UTC by harshavardhana

## Description
Current state-machine didn't honor a situation
which can arise when there is a combination of

 - formatted
 - unformatted
 - corrupted

disks - this combination invariably goes into a
mode where all servers are waiting perpetually
forever thinking we will get quorum in future.

At this point there is a distant possibility of
ever getting a quorum since we don't even have
quorum number of disks offline.

We should exit and print a proper message per disk
to indicate what went wrong and what was detected
by the server.

## Motivation and Context
Refer #4477

## How Has This Been Tested?
Manually while testing the swarm cluster.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-15 07:03 UTC, krisis requested changes

2017-06-15 07:03 UTC, krisis commented on cmd/prepare-storage.go
> +	if disksCorrupted+disksUnformatted == readQuorum && disksFormatted < readQuorum {
With heal-format command becoming available, we should abort only when `disksFormatted + disksOffline < readQuorum`. I.e, optimistically assuming that all disksOffline are in fact formatted disks. For all other configurations, it is worth waiting for a heal-format command being run in future. Thoughts?

2017-06-15 23:33 UTC, harshavardhana commented on cmd/prepare-storage.go
> +	if disksCorrupted+disksUnformatted == readQuorum && disksFormatted < readQuorum {
Agreed, i found further simplification updated the PR.

2017-06-16 12:52 UTC, krisis commented on cmd/prepare-storage.go
>  	disksUnformatted := errMap[errUnformattedDisk]
@harshavardhana, this PR may fix the issue but `prepForInitXL` is difficult to read and has been source of bugs like the one you are fixing. So, to make sure we don't leave behind bugs like these I have tried to list all user-visible states and corresponding error conditions. If this exercise comes in the way of fixing a known bug in search of bugs that are yet to be discovered by testing or user, we can open a new issue to track the readability problem and take this PR as is. Let me know what you think.

## Possible states and conditions

### Formatted setup
- InitObjectLayer
`disksFormatted >= readQuorum`

- Wait for quorum
`disksFormatted < readQuorum && disksFormatted + disksOffline >= readQuorum`
(we don't know yet if there are unformatted disks)
  - Wait for heal
` disksFormatted >= readQuorum && disksUnformatted > 0`
(here we know there is at least one unformatted disk which requires healing)

### Unformatted setup
- Format/Wait for format
`disksUnformatted == diskCount`
- Wait for all
`disksUnformatted + disksOffline == disksCount`

All other conditions should lead to abort of server.

2017-06-16 16:44 UTC, harshavardhana commented on cmd/prepare-storage.go
>  	disksUnformatted := errMap[errUnformattedDisk]
Updated @krisis

2017-06-17 15:49 UTC, vadmeste approved these changes
LGTM and tested with basic operations

2017-06-17 18:20 UTC, merged