gateway-azure: Parse error responses for anonymous requests for Azure
minio/minio pull request #4543
Opened 2017-06-15 02:30 UTC by krishnasrinivas

fixes #4481

## Description

For anonymous requests to Azure we were not parsing the Error XML responses.

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-15 21:10 UTC, harshavardhana commented
@krishnasrinivas can you add unit tests for the changes?

2017-06-15 22:43 UTC, krishnasrinivas commented
@harshavardhana azureAnonRequest can't be unit tested as it needs to talk to azure backend. This would be covered under mint.

2017-06-15 22:49 UTC, harshavardhana commented
> @harshavardhana azureAnonRequest can't be unit tested as it needs to talk to azure backend. This would be covered under mint.

The parsing part if possible can go in unit test since it is specific for azure to s3 translation.

2017-06-16 18:55 UTC, krishnasrinivas commented
> The parsing part if possible can go in unit test since it is specific for azure to s3 translation.

```
+		if len(respBody) == 0 {
 +			// no error in response body, might happen in HEAD requests
 +			return nil, storage.AzureStorageServiceError{
 +				StatusCode: resp.StatusCode,
 +				Code:       resp.Status,
 +				Message:    "no response body was available for error status code",
 +			}
 +		}
 +		// Response contains Azure storage service error object.
 +		var storageErr storage.AzureStorageServiceError
 +		if err := xml.Unmarshal(respBody, &storageErr); err != nil {
 +			return nil, err
 +		}
 +		storageErr.StatusCode = resp.StatusCode
 +		return nil, storageErr
```

This part can be separated out into a function, but the downside is it will create a small function which is not reused. Let me check with @abperiasamy once what he thinks

2017-06-16 19:09 UTC, harshavardhana commented
> This part can be separated out into a function, but the downside is it will create a small function which is not reused. Let me check with @abperiasamy once what he thinks

It doesn't need to be reused the problem is that we have many functions like this which are not unit tested because they are deep inside, if we do have one function for this we can add test cases for all common and corner cases where this can fail. 

Say if we do reflection or something internally.  My suggestion is we add tests..

2017-06-19 17:51 UTC, krisis requested changes
Overall the changes look good to me. @krishnasrinivas do you plan to add unit tests? I see that there was a discussion but no decision mentioned in the conversation.

2017-06-19 17:51 UTC, krisis commented on cmd/gateway-azure-anonymous.go
> +	if resp.StatusCode >= 400 && resp.StatusCode <= 505 {
A comment explaining why we pick status code between 400 and 505 is required.

2017-06-22 12:12 UTC, balamurugana requested changes

2017-06-22 12:12 UTC, balamurugana commented on cmd/gateway-azure-anonymous.go
> +func azureAnonRequest(verb, urlStr string, header http.Header) (*http.Response, error) {
Please add unit test to this function

2017-06-22 12:12 UTC, balamurugana commented on cmd/gateway-azure-anonymous.go
> +				Message:    "no response body was available for error status code",
Why is missing response body wrong?

2017-06-22 22:16 UTC, krishnasrinivas commented on cmd/gateway-azure-anonymous.go
> +func azureAnonRequest(verb, urlStr string, header http.Header) (*http.Response, error) {
We had decided not to do mock tests. i.e we should not start a mock server and test instead should use the actual backend in functional tests in mint to cover cases like these.

2017-06-22 22:21 UTC, krishnasrinivas commented on cmd/gateway-azure-anonymous.go
> +	if resp.StatusCode >= 400 && resp.StatusCode <= 505 {
I just picked this code from azure sdk
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes says 4xx 5xx are error codes

2017-06-22 22:22 UTC, krishnasrinivas commented on cmd/gateway-azure-anonymous.go
> +				Message:    "no response body was available for error status code",
@balamurugana note that this is inside the if condition: 
```
if resp.StatusCode >= 400 && resp.StatusCode <= 505
```

hence it is an error condition regardless of whether body is available or not

2017-06-23 18:01 UTC, krishnasrinivas commented
> Overall the changes look good to me. @krishnasrinivas do you plan to add unit tests? I see that there was a discussion but no decision mentioned in the conversation.

@krisis AB said functions like this which needs to talk to GCS backend should be covered under functional tests (to test against the actual backend) and that we should not do mock/unit tests.

2017-06-24 01:34 UTC, balamurugana approved these changes
Not tested

2017-06-24 02:01 UTC, krisis approved these changes
Looks like we have decided what to do about unit tests. Lgtm otherwise.

2017-06-24 05:07 UTC, merged