Added ListObjectsV2 support to gateway
minio/minio pull request #4547
Opened 2017-06-15 21:38 UTC by NitishT

## Description
Added ListObjectsV2 and ListObjectsV2 Anon support to Gateway S3 and Azure 

## Motivation and Context
- Added ListObjectsV2 to GatewayLayer
- Added AnonListObjectsV2 in S3/Azure gateway
- Added ListObjectsV2 to Azure gateway implementation

## How Has This Been Tested?
This adds anonymous list object V2 support to S3 gateway.
Methods ListObjectsV2and AnonListObjectsV2 are now added to GatewayLayer interface.

Partially fixes #4413. Will send another PR to `feature-gcs` branch. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-15 22:47 UTC, krishnasrinivas approved these changes
Just remember to send another commit to use azureAnonRequest() once https://github.com/minio/minio/pull/4543 is merged.

2017-06-15 22:52 UTC, harshavardhana requested changes

2017-06-15 22:52 UTC, harshavardhana commented on cmd/gateway-azure-anonymous.go
> +	q := azureListBlobsGetParameters(params)
We need to add unit tests for all this parsing logic.. and converting to S3 compatible format.

2017-06-16 01:57 UTC, NitishT commented on cmd/gateway-azure-anonymous.go
> +	q := azureListBlobsGetParameters(params)
Added tests for azureListBlobsGetParameters. Will check if there are more such parsing methods, will add tests for those as well

2017-06-16 04:12 UTC, krisis requested changes

2017-06-16 04:12 UTC, krisis commented on cmd/gateway-azure.go
> +// ListObjectsV2 - lists all blobs in GCS bucket filtered by prefix
s/list all blobs in GCS bucket/list all blobs in Azure bucket/

2017-06-16 04:12 UTC, krisis commented on cmd/gateway-handlers.go
> +		errorIf(err, "Unable to list objects.")
We could improve the error log by adding `bucket`, `prefix`, `delimiter` and `marker`. This will help debug when such an error does occur.

2017-06-16 04:12 UTC, krisis commented on cmd/gateway-handlers.go
> +	// marshalled into S3 compatible XML header.
ListObjectsInfo is serialized as XML and is sent as part of the response body, _not_ header.

2017-06-17 01:05 UTC, nitisht commented on cmd/gateway-azure-anonymous.go
> +	q := azureListBlobsGetParameters(params)
Added tests for `anonErrToObjectErr`. Looks like there are no more parsing/response translation methods without unit tests in gateway-azure.go

2017-06-17 01:05 UTC, NitishT commented
Updated, @harshavardhana @krisis PTAL

2017-06-17 01:07 UTC, harshavardhana approved these changes

2017-06-17 04:56 UTC, krisis approved these changes
LGTM. Tested locally and works as expected.

2017-06-17 05:17 UTC, merged