Added HEALTHCHECK in release Dockerfiles
minio/minio pull request #4550
Opened 2017-06-16 23:23 UTC by NitishT

## Description
Added `HEALTHCHECK` in release related Dockerfiles

## Motivation and Context
This is needed to check Minio Docker container health status. Currently Docker performs curl to http://127.0.0.1:9000/minio/index.html every `30s` with a timeout of `5s`. After straight 3 failures, Docker will mark it as `unhealthy`. 

## How Has This Been Tested?
Manually 

```
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                   PORTS               NAMES
51415f1ac8f3        31d1385dfe2e        "/usr/bin/docker-e..."   5 minutes ago       Up 5 minutes (healthy)   9000/tcp            elegant_lalande

```

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-17 18:04 UTC, NitishT commented
Updated with another approach to handle cases when MINIO_BROWSER=off

2017-06-19 05:56 UTC, harshavardhana commented
whats the final size of our docker image after this change? @NitishT

2017-06-19 17:20 UTC, harshavardhana requested changes

2017-06-19 17:20 UTC, harshavardhana commented on buildscripts/healthcheck.sh
> +HealthCheckMain
It would look like since there is no exit code, this healthcheck script might not report faulty status..

2017-06-19 17:20 UTC, harshavardhana commented on buildscripts/healthcheck.sh
> +    http_response=$(curl -s -o /dev/null -I -w "%{http_code}" http://127.0.0.1:9000/minio/index.html)
Perhaps keep `ip, resource` as part of the constants.. and then reference here..

2017-06-19 17:20 UTC, harshavardhana commented on buildscripts/healthcheck.sh
> +    if [ $http_response -eq "200" ] || [ $http_response -eq "404" ]; then
You can concisely write this in the following manner

```
[ $http_response -ne "200" ] && [ $http_response -ne "404" ] && exit 1
```

2017-06-19 19:36 UTC, poornas requested changes

2017-06-19 19:36 UTC, poornas commented on Dockerfile.release
> +COPY buildscripts/healthcheck.sh /usr/bin/
@nitisht, we can combine 
COPY buildscripts/docker-entrypoint.sh /usr/bin/
COPY buildscripts/healthcheck.sh /usr/bin/

as COPY buildscripts/docker-entrypoint.sh  buildscripts/healthcheck.sh  /usr/bin  to reduce layers. 

Also, the RUN command for docker-entrypoint.sh can be  folded into the first RUN command if the COPY and EXPOSE commands are moved up further in the script.

2017-06-21 01:51 UTC, NitishT commented
Updated, @poornas @harshavardhana

2017-06-21 01:55 UTC, harshavardhana approved these changes

2017-06-21 02:14 UTC, poornas approved these changes

2017-06-21 02:24 UTC, merged