gateway-gcs: use minio.sys.temp/multipart/v1 as url base
minio/minio pull request #4562
Opened 2017-06-19 22:35 UTC by krishnasrinivas

## Description

This helps when we want to use a different backend format in future.

As discussed in today's meeting we will handle the backend format this way. i.e when we move to a different format we will start using minio.sys.temp/multipart/v2 and not worry about migrating the data in v1

## Motivation and Context

To support change in backend format for multipart files.

## How Has This Been Tested?

manual

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-19 23:02 UTC, harshavardhana requested changes

2017-06-19 23:02 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	gcsMinioMultipartPath = gcsMinioPath + "/multipart/v1"
Perhaps call this `gcsMinioMultipartPathV1` ?

2017-06-20 00:16 UTC, krishnasrinivas commented on cmd/gateway-gcs.go
> +	gcsMinioMultipartPath = gcsMinioPath + "/multipart/v1"
will do that ... to be consistent with the rest of the code base

2017-06-20 02:46 UTC, harshavardhana approved these changes
LGTM and works.

2017-06-21 17:22 UTC, balamurugana approved these changes
Not tested

2017-06-21 17:27 UTC, merged