build: Error out properly when unsupported arch is given.
minio/minio pull request #4585
Opened 2017-06-23 07:18 UTC by harshavardhana

## Description
Release build with unsupported arch selected should error out.

## Motivation and Context
Release build cleanup.

## How Has This Been Tested?
Manually with `make release`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-23 22:18 UTC, donatello approved these changes

2017-06-24 07:43 UTC, nitisht requested changes

2017-06-24 07:43 UTC, NitishT commented on buildscripts/build.sh
> +            if [ "$chosen_osarch" = "$each_osarch" ]; then
`==` instead of `=`

2017-06-24 07:44 UTC, harshavardhana commented on buildscripts/build.sh
> +            if [ "$chosen_osarch" = "$each_osarch" ]; then
No @NitishT - test it locally `=` is also same as `==`

2017-06-24 07:48 UTC, NitishT commented on buildscripts/build.sh
> +            if [ "$chosen_osarch" = "$each_osarch" ]; then
I see. Let me build locally.

2017-06-24 07:54 UTC, nitisht approved these changes
LGTM.

2017-06-24 08:05 UTC, merged