Add support for helm package info in useragent
minio/minio pull request #4592
Opened 2017-06-23 21:26 UTC by NitishT

## Description
Adds helm chart version detection

Minio Helm Chart uses DownwardFileAPI to create a file with pod labels in the path `/podinfo/labels`. This file has info about the Helm Chart version. We check if this file exists to read the chart version. 

## Motivation and Context
See issue https://github.com/minio/minio/issues/4456

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-06-23 23:15 UTC, harshavardhana requested changes

2017-06-23 23:15 UTC, harshavardhana commented on cmd/update-main.go
> +		podLabelsInfo, err := ioutil.ReadFile("/podinfo/labels")
Create a function for this and add a unit test..

2017-06-23 23:15 UTC, harshavardhana commented on cmd/update-main.go
> +		podLabelsInfo, err := ioutil.ReadFile("/podinfo/labels")
Use scanner instead for scanning line by line.. 

```
package main

import (
	"bufio"
	"fmt"
	"os"
)

func main() {
	scanner := bufio.NewScanner(os.Stdin)
	for scanner.Scan() {
		fmt.Println(scanner.Text()) // Println will add back the final '\n'
	}
	if err := scanner.Err(); err != nil {
		fmt.Fprintln(os.Stderr, "reading standard input:", err)
	}
```

2017-06-24 09:27 UTC, NitishT commented
Updated @harshavardhana .

2017-06-24 17:33 UTC, harshavardhana requested changes

2017-06-24 17:33 UTC, harshavardhana commented on cmd/update-main.go
> +				helmChartVersion = strings.Trim(helmChartVersion, `"`)
You don't need to re-assign here.. just do `return strings.Trim(helmChartVersion, `"`)`

2017-06-24 17:33 UTC, harshavardhana commented on cmd/update-main.go
> +	if err == nil {
Don't write it like this write it like , follow this pattern of eliminating errors first. 

```
helmInfoFile, err := os.Open(helmInfoFilePath)
if err != nil  && !os.IsNotExist(err) {
       errorIf(err, "Unable to read %s", helmInfoFilePath)
       return ""
}
... scanner 
```

2017-06-24 19:30 UTC, NitishT commented on cmd/update-main.go
> +	if err == nil {
done.

2017-06-24 19:30 UTC, NitishT commented on cmd/update-main.go
> +				helmChartVersion = strings.Trim(helmChartVersion, `"`)
done

2017-06-24 20:05 UTC, harshavardhana approved these changes

2017-06-24 20:13 UTC, donatello approved these changes

2017-06-24 20:17 UTC, merged