Adds 'gcs not ready for production' msg
minio/minio pull request #4604
Opened 2017-06-27 22:26 UTC by ebozduman

Fix for Issue#4581
## Description
` *** Warning: Not Ready for Production ***` message is added to warn user when minio server is started with `gcs` gateway option.

## Motivation and Context
`gcs` is not ready for production yet.

## How Has This Been Tested?
I tested manually starting server with all possible gateway options and without gateway option to make sure the warning message only appears for `gcs`

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-06-27 22:47 UTC, harshavardhana requested changes

2017-06-27 22:47 UTC, harshavardhana commented on cmd/gateway-main.go
> +		// 06/27/2017  -- Ersan Bozduman
We don't need to add the name here we don't follow this convention. you can just add a line as `FIXME: The following print command is temporary and will be removed when gcs is ready for production use.`

2017-06-27 23:01 UTC, ebozduman commented on cmd/gateway-main.go
> +		// 06/27/2017  -- Ersan Bozduman
Done.

2017-06-27 23:03 UTC, harshavardhana approved these changes

2017-06-28 00:49 UTC, krishnasrinivas approved these changes

2017-06-28 01:01 UTC, harshavardhana requested changes
There is a formatting issue..check the Travis logs.

2017-06-28 02:26 UTC, harshavardhana approved these changes

2017-06-28 02:44 UTC, merged