gcs: Cleanup, code-reuse, fix writer/reader go-routine leaks.
minio/minio pull request #4651
Opened 2017-07-09 05:06 UTC by harshavardhana

## Description
This PR serves to fix a few things in GCS gateway.

- fixes leaks in object reader and writer, not getting closed
  under certain situations. This led to go-routine leaks.

- apparent confusing issue in case of complete multipart upload,
  where it is currently possible for an entirely different
  object name to concatenate parts of a different object name
  if you happen to know the upload-id and parts of the object.
  This is a very rare scenario but it is possible.

- succint usage of certain parts of code base and re-use.
  

## Motivation and Context
A precursor change towards #4637

## How Has This Been Tested?
Manually.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-07-10 02:23 UTC, krisis requested changes

2017-07-10 02:23 UTC, krisis commented on cmd/gateway-gcs.go
> +	w.Metadata = metadata
Is there any reason we are not resorting to `defer w.Close()`?

2017-07-10 02:23 UTC, krisis commented on cmd/gateway-gcs.go
>  	w := object.NewWriter(l.ctx)
We can consistently use `defer w.Close()` in these situations.

2017-07-10 02:23 UTC, krisis commented on cmd/gateway-gcs.go
> +	if len(uploadedParts) > maxPartCount {
We should check if sum of component count of all components exceed 1024.

2017-07-10 02:23 UTC, krisis commented on cmd/gateway-gcs.go
>  	r, err := object.NewReader(l.ctx)
We can use `defer r.Close()` instead of closing the `ReadCloser` in every failure branch individually.

2017-07-10 02:41 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	w.Metadata = metadata
The reason is that only after w.Close() we can validate the sha256sum. i.e after a flush.

2017-07-10 02:42 UTC, harshavardhana commented on cmd/gateway-gcs.go
>  	w := object.NewWriter(l.ctx)
Explained above why.

2017-07-10 02:43 UTC, harshavardhana commented on cmd/gateway-gcs.go
> +	if len(uploadedParts) > maxPartCount {
If we have input list > 1024 we can't concatenate anyways.. not sure if i understand you correct.

2017-07-10 02:43 UTC, harshavardhana commented on cmd/gateway-gcs.go
>  	r, err := object.NewReader(l.ctx)
We can do that.. for readers.

2017-07-10 03:03 UTC, harshavardhana commented on cmd/gateway-gcs.go
>  	r, err := object.NewReader(l.ctx)
Actually i want to close the reader ASAP not in defer.. it is just to purge resources quickly.

2017-07-11 06:49 UTC, balamurugana approved these changes
Not tested

2017-07-11 07:28 UTC, krisis approved these changes

2017-07-11 16:25 UTC, merged