build: ditch verifiers on make
minio/minio pull request #4679
Opened 2017-07-14 18:34 UTC by brendanashworth

## Description
This commit ditches running verifiers automatically when just building
the server. It retains the verifiers when running tests.

There is very little point to running the verifiers each time a
developer builds the library but has no intent of running the tests.
They're expensive in time; this commit halves the build time on my
system, from 57 seconds to 29 seconds. This is because verifiers updates
the libraries from GitHub each time, which is slightly wasteful.
Additionally, computing cyclomatic complexity is expensive
computationally and isn't necessary to build the library.

Additionally, this allows the library to be built offline. It no longer
requires internet to run make.

## Motivation and Context
When the internet died I had to build the library

2017-07-14 18:49 UTC, krishnasrinivas commented
It's better if default `make` does everything including tests, linting etc. During development I just do `go install` go see if it compiles and to build the binary. i.e I don't do make as it is time consuming. However just before doing `git push` I don `make` to make sure that everything passes.

2017-07-14 21:24 UTC, brendanashworth commented
@krishnasrinivas I'm not sure if thats very idiomatic, [convention](https://www.gnu.org/prep/standards/html_node/Standard-Targets.html#Standard-Targets) would be to run tests with `make test` and just compile the program with `make`, no? To me, it doesn't make sense to just run the verifiers on `make` but not tests, and running tests without `make test` might seem unexpected to someone unfamiliar with the project.

2017-07-14 22:25 UTC, krishnasrinivas commented
> @krishnasrinivas I'm not sure if thats very idiomatic, convention would be to run tests with make test and just compile the program with make, no?

https://www.gnu.org/prep/standards/html_node/Standard-Targets.html#Standard-Targets

Then we will need
make - just build
make check - lint, test and build
make install - build and install

@harshavardhana what do you think?

2017-07-14 23:04 UTC, harshavardhana commented
> Then we will need
> make - just build
> make check - lint, test and build
> make install - build and install
> 
> @harshavardhana what do you think?

This makes sense for me.. :+1:

2017-07-14 23:49 UTC, brendanashworth commented
I can do that. Should we worry about people who might expect `make` to install the binary to $GOPATH/bin? (as it does right now)

2017-07-14 23:52 UTC, krishnasrinivas commented
>  Should we worry about people who might expect make to install the binary to $GOPATH/bin? 

`make install` should install the binary to $GOPATH/bin

2017-07-14 23:53 UTC, harshavardhana commented
If we indicate to user the path where the binary was built into then we will good. We should say perhaps ` ./minio server export` ;-)

2017-07-15 00:34 UTC, harshavardhana requested changes

2017-07-15 00:34 UTC, harshavardhana commented on Makefile
> +	@cp $(PWD)/minio $(GOPATH)/bin/minio
We can print some friendly message like `Minio compiled successfully  'minio server export' to start.`

2017-07-15 00:44 UTC, krishnasrinivas commented on Makefile
> +	@cp $(PWD)/minio $(GOPATH)/bin/minio
users might type `minio server export` in the source directory which is not preferred. Telling users to do `minio server ~/export` will also not be correct for windows users.

We could just leave it at this. So users will type "minio -h" for help

2017-07-15 00:50 UTC, brendanashworth commented on Makefile
> +	@cp $(PWD)/minio $(GOPATH)/bin/minio
Perhaps it could say "Minio installed successfully. Use 'minio -h' for usage."?

2017-07-15 00:54 UTC, harshavardhana commented on Makefile
> +	@cp $(PWD)/minio $(GOPATH)/bin/minio
We can say minio -h

2017-07-15 00:57 UTC, brendanashworth commented on Makefile
> +	@cp $(PWD)/minio $(GOPATH)/bin/minio
So like this?
```
$ make install
Building minio to /.../Go/src/github.com/minio/minio/minio ...
Installing minio at /.../Go/bin/minio ...

NAME:
  minio - Cloud Storage Server.

DESCRIPTION:
  Minio is an Amazon S3 compatible object storage server. Use it to store photos, videos, VMs, containers, log files, or any blob of data as objects.

USAGE:
  minio [FLAGS] COMMAND [ARGS...]

COMMANDS:
  server   Start object storage server.
  version  Print version.
  update   Check for a new software update.
  gateway  Start object storage gateway.
  
FLAGS:
  --config-dir value, -C value  Path to configuration directory. (default: "/Users/brendanashworth/.minio")
  --quiet                       Disable startup information.
  --help, -h                    Show help.
  
VERSION:
  2017-07-15T00:46:01Z
```

2017-07-15 01:00 UTC, krishnasrinivas commented on Makefile
> +	@cp $(PWD)/minio $(GOPATH)/bin/minio
no, like this:
```
$ make install
Building minio to /.../Go/src/github.com/minio/minio/minio ...
Installing minio at /.../Go/bin/minio ...
Check "minio -h" for help
```

2017-07-15 01:40 UTC, brendanashworth commented on Makefile
> +	@cp $(PWD)/minio $(GOPATH)/bin/minio
Done!

2017-07-15 02:31 UTC, balamurugana approved these changes
This simplifies my two commands (make && make test) to one (make check)

2017-07-15 02:36 UTC, krishnasrinivas commented on Makefile
> +test: verifiers build
verifiers can also be under `check`

2017-07-15 18:24 UTC, harshavardhana approved these changes

2017-07-15 18:57 UTC, merged