New UI migration
minio/minio pull request #4697
Opened 2017-07-19 18:45 UTC by rushenn

Add missing files

2017-07-19 23:13 UTC, brendanashworth requested changes
Generally looking good! Just a few changes as of now. Indentation/spacing imo should be kept for a later PR to keep this as specific as possible.

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Browse.js
> +        <Dropdown.Menu>
Can we get rid of the indentation changes here? It obscures the diff.

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Browse.js
> +                        sub='This cannot be undone!'
I was under the impression that removing a bucket from the browser doesn't remove objects inside (will only delete empty bucket). If that's true, it can be undone — if it's false, we probably want a more intricate confirmation modal. Perhaps something like GitHub's "type repository name to continue", we can have "type bucket name to continue"?

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Browse.js
> +                      <input ref="expireMins" type="number" min={ 0 } max={ 59 }defaultValue={ 0 }/>
Nit: should be a space between `max={ 59 }` and `defaultValue`

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Login.js
> +  handleSubmit (event) {
The spacing changes here and below aren't necessary, could you remove these?

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Login.js
> +      <div className='text-center'>
the indentation changes aren't necessary here as well. If you'd like to change the rest of the code base, I think what we should do is land this PR without the indentation/spacing changes, and then afterwards do a separate PR with those changes + a linter. I'd rather not change the preferred style without adding a linter

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Login.js
> +
@rushenn do you have any thoughts about adding a text warning here for HTTP? Not a modal or anything, just a simple "You are not using HTTPS. Your access key and secret key will be sent as plaintext to the server." ?

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/ObjectsList.js
> +    const list = objects.map ((object, i) => {
This file should be indented as two spaces, not four.

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Policy.js
> +        .then(() => {
The indentation changes here are unrelated.

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/SideBar.js
> +                <span>read and write</span>
This should load the bucket policy, right? Are we able to do that?

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/less-2/inc/animate/fadeIn.less
> +	0% {opacity: 0;}
In this file, here and below, there's extra whitespace at the end of a few lines.

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/less-2/inc/animate/fadeInUp.less
> +
Sorry for the whitespace nits, there's some here and in a few other files.

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/less-2/inc/animate/fadeInDown.less
> +		-webkit-transform: translateY(-20px);
Are we able to DRY these animations, transformations, etc? There's a lot of repeated code here. Could we do something like `.transform(-20px)` and write a `transform (from) { ... }` LESS thing? That'd do `fadeInDown` and `fadeInUp`, with perhaps similar things in other files.

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/less-2/inc/ie-warning.less
> +  background-color: #ff5252;
The indentation choices are off in these LESS files. Sometimes you use two, four, or even eight spaces to indent (not sure if any are tabs). Should we pick one?

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Browse.js
> +          <Dropdown.Toggle noCaret className="create-new__toggle"><i className="zmdi zmdi-times"></i></Dropdown.Toggle>
This toggle isn't centered correctly when clicked on my mac:
![screen shot 2017-07-19 at 3 34 23 pm](https://user-images.githubusercontent.com/3038254/28392916-069f23c0-6c99-11e7-8667-bd96a500b27a.png)

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Browse.js
> +      uploadFile: <Tooltip id="tooltip-upload-file">Upload file</Tooltip>,
The rest of these tooltips are capitalized, this one is "Upload file", should be "Upload File"

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/less-2/inc/alert.less
> +    .close {
I'm not sure where the issue is with this one, but the close icon isn't correctly centered in the alert for me.
![screen shot 2017-07-19 at 3 51 23 pm](https://user-images.githubusercontent.com/3038254/28393321-f7f2b8c6-6c9a-11e7-87f9-0faca597fd5a.png)

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Browse.js
> +                <button className="btn btn--lg btn--primary">Preview</button>
What's the intent of this button if the preview is shown above? It's like having "Download" when the object is already downloading, no?

![screen shot 2017-07-19 at 4 05 43 pm](https://user-images.githubusercontent.com/3038254/28393547-2683f492-6c9c-11e7-89d5-228f928874f6.png)

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Browse.js
> +                        icon={ 'zmdi-alert-polygon c-red' }
Is this icon correct/loaded? I don't see it:

![screen shot 2017-07-19 at 4 07 01 pm](https://user-images.githubusercontent.com/3038254/28393580-5c398fac-6c9c-11e7-919f-5b6646e33b04.png)

2017-07-19 23:13 UTC, brendanashworth commented on browser/app/js/components/Browse.js
> +                <button onClick={ this.downloadSelected.bind (this) } disabled={ checkedObjects.length == 0 } className="zmdi zmdi-download" />
This button doesn't do anything when pushed with objects selected on my mac, is it supposed to work?

2017-07-20 02:30 UTC, poornas requested changes

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/SettingsModal.js
> +          })
indentation is off here as well

2017-07-20 02:30 UTC, poornas commented on browser/app/less/inc/create-new.less
> +
extra spaces here

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/ObjectsList.js
> +    const list = objects.map ((object, i) => {
![screenshot from 2017-07-19 18-20-17](https://user-images.githubusercontent.com/791968/28396766-54945780-6cb2-11e7-9ca5-ba15731a6295.png)

Is there a missing icon on the delete confirmation modal? This is on Linux

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/ObjectsList.js
> +            <div key={ i } className={ "objects__row " + folderClass + loadingClass + activeClass } onClick={ (e) => showObjectPreview(e) }>
![image](https://user-images.githubusercontent.com/791968/28396938-605d47c4-6cb3-11e7-83fb-1cad793eb24a.png)

I understand that the placeholder is for image previews. Is the oblong placeholder intended? Neither the Download button nor the Preview button work on Linux

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/PolicyInput.js
> -export default connect(state => state)(PolicyInput)
There may be an issue here with policyInput add/remove functionality. If Add button is clicked, default prefix with * is added to bucket and prevents adding any other prefix with Read only action. On the other hand, if the string  "*" is entered as prefix and Add button pressed,"*" is saved as bucket prefix. However, this also allows "someotherprefix" to also be added to policy. Likewise, if "prefix" is added first, followed by *, this allows both * and "prefix" as valid policy prefixes. The string "*" should be interpreted as default here.

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/PolicyInput.js
> -export default connect(state => state)(PolicyInput)
Clicking Add button on  Prefix add functionality also creates duplicate rows with * as prefix

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/ObjectsList.js
> +            <div key={ i } className={ "objects__row " + folderClass + loadingClass + activeClass } onClick={ (e) => showObjectPreview(e) }>
While downloading a image by clicking on object name, console shows a warning on resource mime type
![image](https://user-images.githubusercontent.com/791968/28397152-a0ae075e-6cb4-11e7-9120-df213857c284.png)

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/ObjectsList.js
> +            <div key={ i } className={ "objects__row " + folderClass + loadingClass + activeClass } onClick={ (e) => showObjectPreview(e) }>
@rushenn, clicking the Upload Folder button does nothing for me. This is on Linux.

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/ObjectsList.js
> +            <div key={ i } className={ "objects__row " + folderClass + loadingClass + activeClass } onClick={ (e) => showObjectPreview(e) }>
The UI doesnt reflect the policy for bucket correctly. The policy for tempbucket shows Read and Write on the list of buckets , whereas the policies were deleted subsequently and changed to default ReadOnly. The modal shows it correctly as ReadOnly

Also see the error displayed on console - I am not sure how that happened. Also observed a React nesting error which I am not able to replicate on PolicyInput.js
![image](https://user-images.githubusercontent.com/791968/28397595-6dd4d12a-6cb7-11e7-8aeb-3d5866df2603.png)

2017-07-20 02:30 UTC, poornas commented on browser/app/js/components/ObjectsList.js
> +            <div key={ i } className={ "objects__row " + folderClass + loadingClass + activeClass } onClick={ (e) => showObjectPreview(e) }>
![image](https://user-images.githubusercontent.com/791968/28397685-01fc135e-6cb8-11e7-8d50-0c9da4d5047d.png)

@rushenn , pls revisit PolicyInput.js.  This is with random addition/deletion of policies.

2017-07-20 08:27 UTC, rushenn commented on browser/app/js/components/Browse.js
> +                <button className="btn btn--lg btn--primary">Preview</button>
This is a link to open the selected full size image in a tab.

2017-07-20 08:43 UTC, rushenn commented on browser/app/less-2/inc/ie-warning.less
> +  background-color: #ff5252;
I use the default indention of the editor. I'm gonna do a mass code reformat for all the LESS files.

2017-07-20 08:46 UTC, rushenn commented on browser/app/less-2/inc/alert.less
> +    .close {
![close_icon](https://user-images.githubusercontent.com/13393018/28408591-9db7f824-6d55-11e7-87e6-0e8215f8e3b4.png)

![close_icon_2](https://user-images.githubusercontent.com/13393018/28408710-000a75a6-6d56-11e7-9a64-7af5ba212769.png)


This is how it's rendered in my browser (MacOS Chrome, Firefox and Safari). Are you on a Windows machine?

2017-07-20 08:51 UTC, rushenn commented on browser/app/js/components/ObjectsList.js
> +            <div key={ i } className={ "objects__row " + folderClass + loadingClass + activeClass } onClick={ (e) => showObjectPreview(e) }>
@poornas This PR is to merge the ongoing UI changes to the newux branch of the upstream. There are more works and fixes still required to merge this in to the master.

Upload folder, Preview, Download and all the thumbnail related elements are only for UI purposes and there is no any functionality behind them

2017-07-20 08:53 UTC, rushenn commented on browser/app/js/components/Browse.js
> +      uploadFile: <Tooltip id="tooltip-upload-file">Upload file</Tooltip>,
Yeah, that should be capitalized. Will update.

2017-07-20 08:54 UTC, rushenn commented on browser/app/js/components/Browse.js
> +          <Dropdown.Toggle noCaret className="create-new__toggle"><i className="zmdi zmdi-times"></i></Dropdown.Toggle>
![add](https://user-images.githubusercontent.com/13393018/28409030-03712ed2-6d57-11e7-8def-566a0a87dcdb.png)

It looks fine on my Chrome on MacOS. What is your OS/Browser?

2017-07-20 08:57 UTC, rushenn commented on browser/app/js/components/Browse.js
> +                <button onClick={ this.downloadSelected.bind (this) } disabled={ checkedObjects.length == 0 } className="zmdi zmdi-download" />
Yeah, except the grid view switch icon, rest should work. You'll have to select one or more objects before you perform any actions.

2017-07-20 08:57 UTC, rushenn commented on browser/app/js/components/Browse.js
> +                <button className="btn btn--lg btn--primary">Preview</button>
May be we need proper labeling here.

2017-07-20 09:00 UTC, rushenn commented on browser/app/js/components/Browse.js
> +                        sub='This cannot be undone!'
Good one! We can discuss this (and anything functionality related) with AB and others.

2017-07-20 09:00 UTC, rushenn commented on browser/app/js/components/Browse.js
> +                      <input ref="expireMins" type="number" min={ 0 } max={ 59 }defaultValue={ 0 }/>
Oh! Fixing...

2017-07-20 09:01 UTC, rushenn commented on browser/app/js/components/ObjectsList.js
> +    const list = objects.map ((object, i) => {
Oh! it's still using the old markups. Updating...

2017-07-20 09:07 UTC, rushenn commented
Closing this PR for further discussion with @deekoder

2017-07-20 16:49 UTC, rushenn commented on browser/app/js/components/SideBar.js
> +                <span>read and write</span>
It's still in the discussion level. I have added this only for UI purposes. We may add any other information to cover this.

2017-07-20 16:51 UTC, rushenn commented on browser/app/less-2/inc/animate/fadeInDown.less
> +		-webkit-transform: translateY(-20px);
Need to perform a code clean on styles. We can use some of the simplified mixins to use with keyframes.

2017-07-20 16:52 UTC, rushenn commented
@poornas @brendanashworth Used `yarn format` to resolve all the indention issues.

2017-07-20 17:08 UTC, closed without merging