posix: test isDirEmpty, change error conditional
minio/minio pull request #4743
Opened 2017-07-31 23:43 UTC by brendanashworth

## Description
This commit adds a new test for `isDirEmpty` (for code coverage) and
changes around the error conditional. Previously, there was a `return
nil` statement that would only be triggered under a race condition and
would trip up our test coverage for no reason. With this new error
conditional, there's no awkward 'else'-esque condition, which means test
coverage will not change between runs for no reason in this specific
test. It's also a cleaner read.

## Motivation and Context
Fixes `cmd/posix.go` in https://github.com/minio/minio/issues/4658.

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-08-01 02:18 UTC, aead approved these changes
LGTM, nice find!

2017-08-03 21:49 UTC, vadmeste commented on cmd/posix_test.go
> +func TestPosixIsDirEmpty(t *testing.T) {
Can you add a successful test case? an empty directory and isEmpty() returning true.

2017-08-03 21:50 UTC, vadmeste requested changes
One minor comment

2017-08-04 01:29 UTC, brendanashworth commented on cmd/posix_test.go
> +func TestPosixIsDirEmpty(t *testing.T) {
Ah yes of course! Added, thanks.

2017-08-04 10:47 UTC, vadmeste approved these changes
LGTM

2017-08-04 17:43 UTC, merged