fs: drop Stat() call from fsDeleteFile,deleteFile
minio/minio pull request #4744
Opened 2017-07-31 23:45 UTC by brendanashworth

## Description
This commit makes `fsDeleteFile()` simply call `deleteFile()` after calling
the relevant path length checking functions. This DRYs the code base.

This commit removes the `Stat()` call from `deleteFile()`. This improves
performance and removes any possibility of a race condition.

This additionally adds tests and a benchmark for said function. Here are
the results from before and after this commit:

```
benchmark                   old ns/op     new ns/op     delta
BenchmarkFSDeleteFile-4     2694884       1900661       -29.47%
```

## Motivation and Context
Fixes `cmd/fs-v1-helpers.go` in https://github.com/minio/minio/issues/4658#issuecomment-318495587.

## How Has This Been Tested?
Tests are added.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-08-01 03:04 UTC, aead requested changes

2017-08-01 03:04 UTC, aead commented on cmd/fs-v1-helpers_test.go
>  	reader.Seek(0, 0)
We may want to use io.SeekStart  (0 is a magic constant)
It's not directly in your PR but maybe you can patch it, too?

2017-08-01 06:13 UTC, brendanashworth commented on cmd/fs-v1-helpers_test.go
>  	reader.Seek(0, 0)
So this, right?
```go
reader.Seek(0, io.SeekStart)
```

2017-08-01 06:51 UTC, harshavardhana commented on cmd/fs-v1-helpers_test.go
>  	reader.Seek(0, 0)
> reader.Seek(0, io.SeekStart)

:+1:

2017-08-01 17:42 UTC, brendanashworth commented
Updated, PTAL @aead @harshavardhana

2017-08-01 18:12 UTC, aead approved these changes
LGTM
Nice simplification :+1:

2017-08-01 19:02 UTC, harshavardhana requested changes

2017-08-01 19:02 UTC, harshavardhana commented on cmd/posix.go
> +		} else if isSysErrNotEmpty(err) {
We need to talk about this .. why we need to return `nil` in this scenario.

2017-08-02 07:26 UTC, harshavardhana commented on cmd/posix.go
> +		if isSysErrNotEmpty(err) {
We need to add a comment.. on why this is an ignored error.

2017-08-04 01:49 UTC, brendanashworth commented on cmd/posix.go
> +		if isSysErrNotEmpty(err) {
Commented added, ptal

2017-08-04 01:52 UTC, harshavardhana approved these changes

2017-08-04 03:04 UTC, merged