fs: Fix Shutdown() behavior and handle tests properly.
minio/minio pull request #4796
Opened 2017-08-08 20:15 UTC by harshavardhana

## Description
Fix Shutdown() behavior and handle tests properly.

## Motivation and Context
Fixes #4795

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-08-09 17:22 UTC, krisis requested changes

2017-08-09 17:22 UTC, krisis commented on cmd/fs-v1_test.go
>  	// Delete bucker should get error disk not found.
unrelated typo, yet close enough to change.
s/bucker/bucket

2017-08-09 17:22 UTC, krisis commented on cmd/fs-v1-multipart_test.go
> +	time.Sleep(40 * time.Millisecond)
comment and code are not in sync. Either the comment should be 40ms or Sleep should take 200ms.

2017-08-09 17:22 UTC, krisis commented on cmd/fs-v1-multipart_test.go
> +	close(fs.staleMultipartUploadsDoneCh)
Close the (active) go-routine before NewMultipartUpload request  to ensure that the new routine is the one that performed the clean up.

2017-08-09 17:22 UTC, krisis commented on cmd/fs-v1-multipart_test.go
> +	close(fs.staleMultipartUploadsDoneCh)
we should add a check that verifies that the clean up happened.

2017-08-09 17:22 UTC, krisis commented on cmd/fs-v1-multipart.go
>  // Remove multipart uploads left unattended for more than `fsMultipartExpiry` seconds.
comment should be updated to indicate use of multipartExpiry argument.

2017-08-09 17:22 UTC, krisis commented on cmd/fs-v1-multipart.go
>  // Remove multipart uploads left unattended in a given bucket older than `fsMultipartExpiry`
comment needs to be updated to use `expiry` argument.

2017-08-09 17:22 UTC, krisis commented on cmd/fs-v1-multipart_test.go
> +	// Close the current active go-routine.
this should happen before creating a new multipart upload to ensure that the following cleanup is the one removing 'stale' uploads

2017-08-09 17:22 UTC, krisis commented on cmd/fs-v1-multipart_test.go
> +	}
need to check that the uploadId directory is removed as expected.

2017-08-09 18:54 UTC, balamurugana requested changes

2017-08-09 18:54 UTC, balamurugana commented on cmd/fs-v1-multipart.go
> +				bucket, fsMultipartExpiry)
This error message is not clear or too verbose.

2017-08-09 18:54 UTC, balamurugana commented on cmd/fs-v1-multipart.go
> +			var st os.FileInfo
you could move out of `st` from `for` loop

2017-08-09 18:54 UTC, balamurugana commented on cmd/fs-v1-multipart.go
> +				errorIf(err, "Failed to list buckets for cleaning up of multipart uploads older than %d weeks",
This error message is too verbose.

2017-08-10 17:21 UTC, krisis approved these changes

2017-08-10 17:21 UTC, balamurugana approved these changes

2017-08-10 21:11 UTC, merged