fs: Avoid non-idempotent code flow in ListBuckets()
minio/minio pull request #4798
Opened 2017-08-09 07:35 UTC by harshavardhana

## Description
Under the call flow

```
Readdir
   +
   |
   |
   | path-entry
   |
   |
   v
StatDir
```

Existing code was written in a manner where say
a bucket/top-level directory was indeed deleted
between Readdir() and before StatDir() we would
ignore certain errors. This is not a plausible
situation and might not happen in almost all
practical cases. We do not have to look for
or interpret these errors returned by StatDir()
instead we can just collect the successful
values and return back to the client. We do not
need to pre-maturely decide on bucket access
we just let filesystem decide subsequently for
real I/O operations.

## Motivation and Context
Refer #4658

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-08-09 18:02 UTC, balamurugana requested changes

2017-08-09 18:02 UTC, balamurugana commented on cmd/fs-v1.go
> +		if fi != nil {
checking `err` is appropriate way than `fi` i.e. `err == nil`.  If `err` is not nil, we don't even consider what `fi` has.

2017-08-09 18:24 UTC, harshavardhana commented on cmd/fs-v1.go
> +		if fi != nil {
done @balamurugana

2017-08-09 18:43 UTC, balamurugana approved these changes

2017-08-10 18:49 UTC, krishnasrinivas approved these changes

2017-08-10 20:36 UTC, merged