tests: create temporary dir/files than /usr directory.
minio/minio pull request #4820
Opened 2017-08-15 22:12 UTC by balamurugana

Fixes #4816

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-08-17 17:45 UTC, vadmeste commented on cmd/posix_test.go
> +		if ioutil.WriteFile(slashpath.Join(permDeniedDir, "bin", "yes"), []byte(""), 0400); err != nil {
`if err = ioutil.WriteFile(...`

2017-08-17 17:49 UTC, vadmeste commented on cmd/posix_test.go
> +		if ioutil.WriteFile(slashpath.Join(permDeniedDir, "bin", "yes"), []byte(""), 0400); err != nil {
`if err = ioutil.WriteFile(`, err is missing

2017-08-17 17:52 UTC, vadmeste requested changes
LGTM but only minor comments are needed to be addressed

2017-08-17 17:54 UTC, balamurugana commented on cmd/posix_test.go
> +		if ioutil.WriteFile(slashpath.Join(permDeniedDir, "bin", "yes"), []byte(""), 0400); err != nil {
Done

2017-08-17 17:54 UTC, balamurugana commented on cmd/posix_test.go
> +		if ioutil.WriteFile(slashpath.Join(permDeniedDir, "bin", "yes"), []byte(""), 0400); err != nil {
Done

2017-08-17 17:56 UTC, vadmeste submitted a review, later dismissed
LGTM

2017-08-17 18:17 UTC, harshavardhana commented
PR seems to be failing travis-ci

 ```	
posix_test.go:729: Unable to create file /tmp/minio-371757886/bin/yes. open /tmp/minio-371757886/bin/yes: permission denied
```

2017-08-17 18:23 UTC, donatello submitted a review, later dismissed
LGTM. Perhaps it would be less repetitive to put the perm denied dir and file creation into separate test helper.

2017-08-17 21:41 UTC, vadmeste commented
By the way @bala, won't we have stale files after those tests, since we change dir permissions, probably os.RemoveAll() won't be able to cleanup, can you check that ?

2017-08-17 21:57 UTC, balamurugana commented
@vadmeste Due to permission is set, `os.RemoveAll()` doesn't succeed.  Fixing it now.

2017-08-17 22:20 UTC, balamurugana commented
@vadmeste the latest refresh fixed stale files

2017-08-17 22:21 UTC, vadmeste approved these changes
LGTM

2017-08-18 05:00 UTC, donatello approved these changes

2017-08-18 18:44 UTC, merged