fix: bufconn and listener tests for megacheck
minio/minio pull request #4827
Opened 2017-08-16 20:11 UTC by balamurugana

Fixes #4824

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-08-16 22:54 UTC, krisis requested changes

2017-08-16 22:54 UTC, krisis commented on pkg/http/listener_test.go
> +// As t.Fatalf() is not goroutine safe, use this closure.
update comment since `fail` is no longer a function closure.

2017-08-18 22:10 UTC, harshavardhana reviewed
LGTM. waiting for CI to give :+1:

2017-08-18 22:11 UTC, krisis approved these changes

2017-08-19 08:13 UTC, harshavardhana approved these changes

2017-08-20 19:25 UTC, merged