Expose Content-Length header in CORS setting
minio/minio pull request #4839
Opened 2017-08-21 20:39 UTC by krishnasrinivas

fixes #4838

## Description

When minio is accessed in browser using a JS lib like aws-sdk-js the browser does not expose content-length to JS unless there is a CORS setting.

## Motivation and Context

fixes #4838

## How Has This Been Tested?

manually 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-08-21 21:14 UTC, harshavardhana reviewed
LGTM.

2017-08-21 21:28 UTC, vadmeste approved these changes
LGTM

2017-08-24 23:35 UTC, harshavardhana requested changes

2017-08-24 23:35 UTC, harshavardhana commented on cmd/generic-handlers.go
> +		ExposedHeaders:   []string{"ETag", "Content-Length"},
Can you add Date header as well? @krishnasrinivas - AWS indicates that all [Common Response Headers](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html) can be exposed. 

We can perhaps Expose all headers here. 

> ### ExposeHeader Element
Each ExposeHeader element identifies a header in the response that you want customers to be able to access from their applications (for example, from a JavaScript XMLHttpRequest object). For a list of common Amazon S3 response headers, go to Common Response Headers in the Amazon Simple Storage Service API Reference guide.

2017-08-26 09:18 UTC, harshavardhana commented on cmd/generic-handlers.go
> +		ExposedHeaders:   []string{"ETag", "Content-Length"},
ping @krishnasrinivas did you see my above comment?

2017-09-11 06:37 UTC, harshavardhana approved these changes

2017-09-11 15:15 UTC, merged