fs: ListObjects() was reading ETag at wrong offsets
minio/minio pull request #4846
Opened 2017-08-22 18:24 UTC by harshavardhana

## Description
Current code was just using io.ReadAll() on an fd()
which might have moved underneath due to a concurrent
read operation. Subsequent read will result in EOF
We should always seek back and read again. pread()
is allowed on all platforms use io.SectionReader to
read from the beginning of the file.

## Motivation and Context
Fixes #4842

## How Has This Been Tested?
Manually and using the reproducer. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-08-22 18:53 UTC, vadmeste commented
This fixes the issue as I tested it. You mean, in a GNU/Linux, a call to a read() of a moved file returns io.EOF ?

2017-08-22 18:58 UTC, harshavardhana commented
> This fixes the issue as I tested it. You mean, in a GNU/Linux, a call to a read() of a moved file returns io.EOF ?

Well the underlying offset would have moved if there is a concurrent . io.SectionReader helps in seeking back the offsets for the requested Size() and Offset.

2017-08-22 23:29 UTC, balamurugana requested changes

2017-08-22 23:29 UTC, balamurugana commented on cmd/fs-v1.go
> +	if len(fsMetaBuf) == 0 {
You could use `fi.Size()` to validate before `ioutil.ReadAll()`

2017-08-22 23:29 UTC, balamurugana commented on cmd/fs-v1.go
> +	fi, err := rlk.LockedFile.Stat()
You could add a comment why `Stat()` then `ioutil.ReadAll()` approach is required with `ReadAt()`

2017-08-23 18:23 UTC, harshavardhana commented
@balamurugana can you take a look again?

2017-08-23 18:56 UTC, balamurugana approved these changes

2017-08-23 22:59 UTC, ebozduman approved these changes
LGTM

2017-08-24 00:59 UTC, merged