Refactor CONTRIBUTING.md to make it more reader friendly
minio/minio pull request #4918
Opened 2017-09-14 07:46 UTC by NitishT

## Description
This PR cleans up the Minio Contributing guide to make it more organized and reader friendly.

## Motivation and Context
This document provides clear steps for contributing to Minio and will help new contributors get onboard quickly. 

## How Has This Been Tested?
NA

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-09-14 23:25 UTC, harshavardhana approved these changes

2017-09-14 23:48 UTC, deekoder requested changes

2017-09-14 23:48 UTC, deekoder commented on CONTRIBUTING.md
> +Pull Request gets peer reviewed and merged after approvals.
Use link https://help.github.com/articles/creating-a-pull-request/

2017-09-14 23:48 UTC, deekoder commented on CONTRIBUTING.md
> +- To run `go test -race ./...` and `go build` completes.
How to test minio server heading.

2017-09-15 00:45 UTC, deekoder commented on CONTRIBUTING.md
> +Pull Request gets peer reviewed and merged after approvals.
A full example would be so much more helpful.

2017-09-15 01:52 UTC, deekoder commented on CONTRIBUTING.md
> +Pull Requests can be created via GItHub. Refer to [this document](https://help.github.com/articles/creating-a-pull-request/) for detailed steps on how to create a Pull Request. After a Pull Request g
GitHub

2017-09-15 18:36 UTC, deekoder approved these changes

2017-09-15 18:38 UTC, harshavardhana approved these changes

2017-09-16 08:06 UTC, harshavardhana approved these changes

2017-09-18 09:48 UTC, harshavardhana commented
This can be merged @deekoder

2017-09-18 18:00 UTC, deekoder commented
@harshavardhana it happened again. Your Approval is missing. Readded you.

2017-09-18 18:00 UTC, harshavardhana approved these changes

2017-09-18 18:02 UTC, harshavardhana approved these changes

2017-09-18 18:02 UTC, merged