Use mc functional tests for verifying build
minio/minio pull request #4934
Opened 2017-09-18 01:23 UTC by balamurugana

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-09-18 18:30 UTC, poornas requested changes
Couldn't test this script as the reference to https://raw.githubusercontent.com/minio/mc/master/functional-tests.sh will be resolved only after the minio/mc PR #2253 to add functional tests  is merged.

2017-09-18 18:30 UTC, poornas commented on buildscripts/verify-build.sh
> +    echo "minio excutable binary not found in current directory"
typo here - should be executable

2017-09-18 23:09 UTC, balamurugana commented on buildscripts/verify-build.sh
> +    echo "minio excutable binary not found in current directory"
I am trying to say `minio binary as executable` not found.  Is it good idea to say `minio binary executable not found ...`?

2017-09-18 23:10 UTC, poornas commented on buildscripts/verify-build.sh
> +    echo "minio excutable binary not found in current directory"
s/excutable/executable/

2017-09-18 23:13 UTC, balamurugana commented on buildscripts/verify-build.sh
> +    echo "minio excutable binary not found in current directory"
got it

2017-09-19 22:44 UTC, balamurugana commented
@poornas This PR is testable now.

2017-09-19 23:03 UTC, poornas requested changes
functional-tests.sh needs to be made executable. I get a permission denied.

2017-09-19 23:06 UTC, balamurugana commented
> functional-tests.sh needs to be made executable. I get a permission denied.

You could need to use the latest refresh of this PR

2017-09-20 00:06 UTC, poornas approved these changes
Looks good.

2017-09-20 17:11 UTC, kannappanr approved these changes
Verified the changes. LGTM.

2017-09-20 20:22 UTC, merged