[WIP] Support in-place upgrades of new minio binary and releases.
minio/minio pull request #4961
Opened 2017-09-25 04:43 UTC by harshavardhana

## Description
This PR allows 'minio update' to not only shows update banner
but also allows for in-place upgrades.

Updates are done safely by validating the downloaded
sha256 of the binary.

## Motivation and Context
Fixes #4781

## How Has This Been Tested?
Manually using `minio update`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-10-18 18:14 UTC, harshavardhana commented
This PR is ready for review to test this patch out just do the following steps.

```
$ go build --ldflags "-s -w -X github.com/minio/minio/cmd.Version=2017-09-18T08:38:47Z -X github.com/minio/minio/cmd.ReleaseTag=RELEASE.2017-09-18T08-38-47Z -X github.com/minio/minio/cmd.CommitID=64bde1340cf3530decfca58059cb4196a273490b -X github.com/minio/minio/cmd.ShortCommitID=64bde1340cf3 -X github.com/minio/minio/cmd.GOPATH=/home/harsha/mygo"
```

```
$ ./minio server ~/test

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 1 week ago      ┃
┃ Update: https://dl.minio.io/server/minio/release/linux-amd64/minio ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

```
$ ./minio update

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 1 week ago      ┃
┃ Update: https://dl.minio.io/server/minio/release/linux-amd64/minio ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Update to RELEASE.2017-09-29T19-16-56Z [yes]: yes
Minio updated to version RELEASE.2017-09-29T19-16-56Z successfully.
```

```
$ ./minio version
Version: 2017-09-29T19:16:56Z
Release-Tag: RELEASE.2017-09-29T19-16-56Z
Commit-ID: 60cc6184d253efee4a3120683517028342229e21
```

2017-10-18 18:15 UTC, harshavardhana commented
The UI needs discussion with @abperiasamy but PR can be reviewed for other things.

2017-10-20 06:23 UTC, harshavardhana commented
One more additional thing to notice is

- Docker containers
- Kubernetes
- Mesos 

Are ignored for this update feature since each of them have their own update requirements.

2017-10-20 06:28 UTC, nitisht commented
> The UI needs discussion with @abperiasamy but PR can be reviewed for other things.

Merging blocked till this happens, but code review can be done

2017-10-26 01:33 UTC, deekoder commented
Is this now again ready for review?

2017-10-26 01:36 UTC, harshavardhana commented
> Is this now again ready for review?

Its been ready for a while @deekoder - requires discussion with @abperiasamy as well.

2017-11-23 19:05 UTC, harshavardhana commented
Discussed this with @abperiasamy  and we have a way of addressing the problems of update functionality on orchestration platforms. 

We will be adding a ENV such as MINIO_UPDATE which will be set to off on each orchestration platforms such that this functionality is disabled.

2017-11-29 00:54 UTC, harshavardhana commented
This is approved by @abperiasamy from the UI perspective, fixing the remaining MINIO_UPDATE env for orchestration platforms to turn-off auto updates.

2017-11-29 01:17 UTC, harshavardhana commented
The UI changes are following when server starts

```
$ ./minio server ~/test

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 2 months ago ┃
┃ Update: Run `minio update`                                      ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Endpoint:  http://192.168.1.17:9000  http://172.17.0.1:9000  http://127.0.0.1:9000
AccessKey: USWUXHGYZQYFYFFIT3RE 
SecretKey: MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03 
SQS ARNs:  arn:minio:sqs::test1:redis arn:minio:sqs::test2:redis

Browser Access:
   http://192.168.1.17:9000  http://172.17.0.1:9000  http://127.0.0.1:9000

Command-line Access: https://docs.minio.io/docs/minio-client-quickstart-guide
   $ mc config host add myminio http://192.168.1.17:9000 USWUXHGYZQYFYFFIT3RE MOJRH0mkL1IPauahWITSVvyDrQbEEIwljvmxdq03

Object API (Amazon S3 compatible):
   Go:         https://docs.minio.io/docs/golang-client-quickstart-guide
   Java:       https://docs.minio.io/docs/java-client-quickstart-guide
   Python:     https://docs.minio.io/docs/python-client-quickstart-guide
   JavaScript: https://docs.minio.io/docs/javascript-client-quickstart-guide
   .NET:       https://docs.minio.io/docs/dotnet-client-quickstart-guide

Drive Capacity: 71 GiB Free, 156 GiB Total
```

```
$ ./minio update

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ You are running an older version of Minio released 2 months ago    ┃
┃ Update: https://dl.minio.io/server/minio/release/linux-amd64/minio ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

Update to RELEASE.2017-11-22T19-55-46Z [yes]: yes
Minio updated to version RELEASE.2017-11-22T19-55-46Z successfully.
```

If the MINIO_UPDATE=off is set then all the update functionality is disabled and kept as is with current master. 

This PR is ready for review and merge @nitisht @krisis

2017-12-01 19:38 UTC, harshavardhana commented
Assigning review to @donatello - @krisis is unavailable.

2017-12-02 10:08 UTC, nitisht requested changes

2017-12-02 10:08 UTC, nitisht commented on cmd/gateway-sia.go
> +     MINIO_UPDATE: Turn off in-place upgrades, set this value to "off".
_To_ Turn off in-place upgrades, set this value to "off". Same in other places

2017-12-03 04:37 UTC, nitisht requested changes

2017-12-03 04:37 UTC, nitisht commented on cmd/common-main.go
> +	if updateMsg, _, currentReleaseTime, latestReleaseTime, err := getUpdateInfo(1*time.Second, mode); err == nil {
1s timeout seems too little for non-US clients, for example I get a timeout while `getUpdateInfo` checks for update

2017-12-03 05:12 UTC, nitisht submitted a review, later dismissed
LGTM & Tested

2017-12-06 08:01 UTC, harshavardhana commented
@nitisht @donatello please review this again.

2017-12-12 03:57 UTC, harshavardhana commented
@nitisht @donatello can you review/approve again?

2017-12-13 09:56 UTC, nitisht approved these changes

2017-12-14 15:03 UTC, harshavardhana commented
@donatello can you take a look ?

2017-12-14 21:30 UTC, donatello approved these changes

2017-12-14 21:37 UTC, deekoder commented
@donatello @nitisht  how about codecoverage and mint for this pr?

2017-12-14 21:44 UTC, donatello commented
The code depends on the output of external systems (minio binary download server) - currently due to tight coupling (of external systems) it is not possible to write unit tests to improve the coverage (perhaps a mint test is possible). If we refactor to loosen the coupling I think the code would be more complicated (it was attempted before, and ultimately was not merged).

I think it is ok to merge this ignoring code coverage.

2017-12-15 20:32 UTC, deekoder commented
@y4m4 ran mint.so merging.

2017-12-15 20:33 UTC, merged