Fix S3-Gateway PutObject
minio/minio pull request #4972
Opened 2017-09-26 14:27 UTC by nitisht

## Description
PutObject and PutObjectPart should parse md5 and shaSum only if present in metadata/data. 

## Motivation and Context
See https://github.com/minio/minio-java/issues/615

## How Has This Been Tested?
Running `minio-java` functional tests. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-09-26 16:34 UTC, harshavardhana approved these changes

2017-09-26 18:06 UTC, aead requested changes
This change is not needed as far as I can see.
We can discuss whether we should use a separate function for parsing MD5 and SHA256.

hex.DecodeString("") procudes []byte{}

2017-09-26 18:21 UTC, nitisht commented
> hex.DecodeString("") procudes []byte{}

yes, @aead . The function `getMD5AndSha256SumBytes` returns `nil, nil, nil` if both `md5Hex, sha256Hex` are "" (https://play.golang.org/p/LXnBEteiPa).

Not adding a method will cause same checks to be added in PutObject and PutObjectPart so a function is needed IMHO.

2017-09-26 18:28 UTC, aead commented
I agree on the function argument - but we don't need a this check: `md5Hex == ""`.
Instead of differencing between nil and []byte{} we should fix those places to len(slice) == 0.

2017-09-27 04:49 UTC, nitisht commented
Discussed with @aead and his suggestion is that `minio-go` should not differentiate between empty byte arrays ("") and `nil` byte arrays. As HTTP headers do not differentiate between value is not set and value is `""`. 

A better approach to fix this issue would be to fix the `contentMD5Bytes` []byte handling in `minio-go`. Will send a PR to `minio-go`.

2017-09-27 05:22 UTC, nitisht commented
> Will send a PR to minio-go

PR sent to `minio-go` : https://github.com/minio/minio-go/pull/828 If minio-go PR is accepted, we can close current PR.

2017-09-27 19:04 UTC, deekoder commented
Closing this since https://github.com/minio/minio-go/pull/828 is merged.

2017-09-27 19:04 UTC, closed without merging