Enable ListMultipartUploads and ListObjectParts for FS
minio/minio pull request #4996
Opened 2017-09-29 04:01 UTC by krishnasrinivas

Prefix based ListMultipartUploads is not supported.

## Description

Previously we had disabled ListMultipartUploads and ListObjectParts to see if any clients break. Docker registry broke. This patch enables ListMultipartUploads and ListObjectParts, however ListMultipartUploads with prefix based listing is not supported (which is not used by docker registry anyway). 

In the near future we will simplify our backend to support this behaviour.

## How Has This Been Tested?

Tested with docker registry. Manual testing also done.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2017-09-29 18:35 UTC, harshavardhana commented
> Prefix based ListMultipartUploads is not supported.

is this PR addressing this feature as well? i see that the code supports delimiter as well.

2017-09-29 19:02 UTC, krishnasrinivas commented
> is this PR addressing this feature as well? i see that the code supports delimiter as well.

The value of delimiter will not matter for us. We use use the prefix as the object name for our operation.

We neither support recursive listMultipartUploads nor non-recursive prefix based listing.

2017-09-29 19:20 UTC, harshavardhana commented
> The value of delimiter will not matter for us. We use use the prefix as the object name for our operation.
> 
> We neither support recursive listMultipartUploads nor non-recursive prefix based listing.

are you saying that if prefix based listing is not available? i still see code which handles CommonPrefixes  why does this PR indicate that?

2017-10-03 01:36 UTC, krishnasrinivas commented
> are you saying that if prefix based listing is not available?

yes, because for us prefix will be object name

> i still see code which handles CommonPrefixes why does this PR indicate that?

where? can you paste the line number/code causing confusion?

2017-10-03 01:50 UTC, harshavardhana commented
> where? can you paste the line number/code causing confusion?

https://github.com/minio/minio/pull/4996/files#diff-648cda9ed6a65f8067d93043830d8bc0R285 this one.

2017-10-03 19:44 UTC, krishnasrinivas commented
> https://github.com/minio/minio/pull/4996/files#diff-648cda9ed6a65f8067d93043830d8bc0R285 this one.

`fs.listMultipartUploads()` is untouched in this patch, it is does not get used by `fs.ListMultipartUploads()`

`fs.listMultipartUploads()` is getting used by `cleanupStaleMultipartUpload()` in a recursive mode. Hence entire `fs.listMultipartUploads()` can be removed when we move to the new backend.

2017-10-05 04:24 UTC, harshavardhana requested changes
> fs.listMultipartUploads() is untouched in this patch, it is does not get used by fs.ListMultipartUploads()
> 
> fs.listMultipartUploads() is getting used by cleanupStaleMultipartUpload() in a recursive mode. Hence entire fs.listMultipartUploads() can be removed when we move to the new backend.

Can we make this more apparent with the function names listMultipartUploads() and listMultipartUploadIDs() do not look different. ?

2017-10-05 06:09 UTC, krishnasrinivas commented
i have renamed fs.listMultipartUploads() to fs.listMultipartUploadsCleanup()

2017-10-05 06:11 UTC, harshavardhana approved these changes

2017-10-05 19:24 UTC, balamurugana commented
@krishnasrinivas can you squash/rebase this PR and having PR's description in comment log as well?

2017-10-05 19:45 UTC, krishnasrinivas commented
@balamurugana added the commit message

2017-10-05 20:02 UTC, balamurugana approved these changes

2017-10-05 23:08 UTC, merged