Push max threads to little less than kernel limit
minio/minio pull request #5001
Opened 2017-09-30 20:14 UTC by vadmeste

## Description
Let Minio server use more threads than allowed by golang runtime. This
is important to better deal with high load.

## Motivation and Context
Fixes #issue/4490

## How Has This Been Tested?
Manually, by printing log

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2017-10-02 16:47 UTC, fwessels commented on cmd/server-rlimit.go
> +				minioMaxThreads := (sysMaxThreads / 100) * 90
Minor comment: I would multiply first and then divide (less changes of some errors) and the size of the int is large enough

2017-10-02 16:47 UTC, fwessels approved these changes
LGTM

2017-10-02 16:51 UTC, harshavardhana requested changes

2017-10-02 16:51 UTC, harshavardhana commented on cmd/server-rlimit.go
> +	if runtime.GOOS == "linux" {
Lets move this to `pkg/sys` ? to have a platform dependent code in its own selective files? for example we can also use cgroup limits here as well.

2017-10-02 16:54 UTC, fwessels commented
Looks like the issue referenced is incorrect (4490)

2017-10-02 21:05 UTC, vadmeste commented
Can you review again @fwessels and @harshavardhana ?

2017-10-02 21:33 UTC, harshavardhana approved these changes

2017-10-03 02:46 UTC, deekoder commented
@vadmeste  is looking into codecov marking blocked until then.

2017-10-03 17:20 UTC, vadmeste commented
@deekoder, as @harshavardhana stated, codecov calculates the code coverage based on Windows & Linux code coverage.

Now, this PR adds a feature that only works for Linux, but not for Windows, that's why we can't enhance Windows code coverage here.

I think we can merge this since the code coverage for Linux is perfect.

2017-10-03 17:37 UTC, merged