Chinese translation
minio/minio pull request #5164
Opened 2017-11-10 05:23 UTC by dingjs

Got the tranlsation reviewed and fix some typos.
## Description
 fix some typos.

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2017-11-10 20:16 UTC, harshavardhana approved these changes
LGTM

2017-11-19 08:11 UTC, yihuaf approved these changes
Looks good to me. Please address the one comment and check in.

2017-11-19 08:11 UTC, yihuaf commented on docs/zh_CN/shared-backend/README.md
> +为了让共享后端存储的Minio实例运行起来，你需要启动多个Minio服务，这些服务指向同一个后端存储。下面我们就来讲解如何设置。
为了让共享后端存储的Minio实例运行起来 ->  为了让Minio在共享后端上运行起来

2017-11-20 20:40 UTC, deekoder commented on docs/zh_CN/shared-backend/README.md
> +为了让共享后端存储的Minio实例运行起来，你需要启动多个Minio服务，这些服务指向同一个后端存储。下面我们就来讲解如何设置。
@dingjs I will wait for you to address @yihuaf  comment above and then merge this PR.

2017-11-20 20:41 UTC, deekoder requested changes
PTAL @yihuaf  comments

2017-11-21 05:37 UTC, dingjs commented on docs/zh_CN/shared-backend/README.md
> +为了让共享后端存储的Minio实例运行起来，你需要启动多个Minio服务，这些服务指向同一个后端存储。下面我们就来讲解如何设置。
@deekoder OK,I just fixed the issue.
@yihuaf 多谢，已修改。

2017-11-21 21:09 UTC, yihuaf commented
@deekoder The change was good.

2017-11-22 00:54 UTC, deekoder approved these changes

2017-11-22 20:13 UTC, merged