Return ErrContentSHA256Mismatch if sha256 sum is invalid
minio/minio pull request #5188
Opened 2017-11-15 09:16 UTC by krisis

## Description

Minio server and gateway returned `500 Internal Error` if `X-Amz-Content-SHA256` had an invalid hex. 
With this change, we would return ErrContentSHA256Mismatch if the underlying hash reader fails to decode the sha256 sum hex. This is because no payload can have an invalid sha256sum and trivially an invalid sha256 sum hex would be a mismatch.

## Motivation and Context

Fixes minio/mint#216
## How Has This Been Tested?

Using mint
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2017-11-15 09:45 UTC, harshavardhana requested changes

2017-11-15 09:45 UTC, harshavardhana commented on cmd/object-handlers.go
> +			writeErrorResponse(w, ErrContentSHA256Mismatch, r.URL)
we have a `pkg/hash/errors.go`  to return this error SHA256Mismatch{} @krisis we so we can return from the hash.NewReader() internally we don't need to do this here. 

We can perhaps do this for md5sum as well while we are at it.

2017-11-15 09:45 UTC, harshavardhana commented on cmd/object-handlers.go
> +			writeErrorResponse(w, ErrContentSHA256Mismatch, r.URL)
You can also bring a test case inside the package pkg/hash for this.

2017-11-15 22:08 UTC, harshavardhana submitted a review, later dismissed

2017-11-16 18:13 UTC, harshavardhana approved these changes
LGTM - tested

2017-11-16 19:08 UTC, donatello approved these changes

2017-11-16 19:13 UTC, merged