Support for ListObjectParts in azure-gateway
minio/minio pull request #5198
Opened 2017-11-16 20:15 UTC by krishnasrinivas

fixes #5169

## Description

## Motivation and Context

## How Has This Been Tested?

manual. mint functional test should be added: https://github.com/minio/mint/issues/223

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2017-11-17 10:34 UTC, krisis requested changes

2017-11-17 10:34 UTC, krisis commented on cmd/gateway-azure.go
> +		partNumberStr := strconv.Itoa(partNumber)
can't we use a `map[int]PartInfo` and avoid converting `partNumber` to `string`?

2017-11-17 10:34 UTC, krisis commented on cmd/gateway-azure.go
> +		if partsCount != 0 {
will `partsCount` ever be here?

2017-11-17 20:12 UTC, krishnasrinivas commented on cmd/gateway-azure.go
> +		partNumberStr := strconv.Itoa(partNumber)
fixed it

2017-11-17 20:12 UTC, krishnasrinivas commented on cmd/gateway-azure.go
> +		if partsCount != 0 {
Yes, if a misbehaving client does:
```
GET /test/testobject?max-parts=0&part-number-marker=0&uploadId=0239618213468449 HTTP/1.1
Host: localhost:9000

```

2017-11-20 11:17 UTC, balamurugana approved these changes
LGTM

2017-11-20 11:26 UTC, krisis approved these changes

2017-11-20 22:03 UTC, merged