dynamic port in docker’s healthcheck
minio/minio pull request #5228
Opened 2017-11-23 16:19 UTC by dehy

Because :9000 is not always the way it is

## Description
Made the minio port in docker's healthcheck dynamic. Falls back to 9000 if can't define the port. If you find a better (more elegant) way to dynamically find the listening port, feel free to bash me!

## Motivation and Context
When starting a docker container with `server --address ":80" /export` command for instance, the healthcheck.sh script fails after the 120s grace period and marks the container as "unhealthy". And an unhealthy container is not dns-resolvable anymore. And a non-resolvable container is often not a good thing.

## How Has This Been Tested?
I rebuilt an image and ran it in a docker-compose setup with a custom listener port command (`command: server --address ":80" /data`). I waited for 120s and yay, the container was still healthy!

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2017-11-23 17:46 UTC, harshavardhana requested changes

2017-11-23 17:46 UTC, harshavardhana commented on dockerscripts/healthcheck.sh
> +    port="$(netstat -npta | grep 1/minio | grep LISTEN | awk '{ print $4 }' | cut -d: -f4)"
Good bug fix - we need to actually expand the scope a bit, following code would work fine.

```
address=$(netstat -nplt 2>/dev/null | awk ' /(.*\/minio)/ { gsub(":::","127.0.0.1:",$4); print $4}')
```

The reason is we need to support two different type of scenarios here

- Listening on tcp6 by default i.e and user chooses a different port. 
- Listening on tcp only i.e user provided `--address` the right IP or hostname

2017-11-24 07:15 UTC, harshavardhana commented
Would you mind squashing your commits ?

2017-11-24 07:15 UTC, harshavardhana submitted a review, later dismissed

2017-11-24 07:56 UTC, nitisht approved these changes
LGTM & Tested

2017-11-24 08:39 UTC, harshavardhana approved these changes

2017-11-24 08:41 UTC, merged