Consolidate Quickstart Guide links on server console
minio/minio pull request #5249
Opened 2017-11-30 22:11 UTC by shruthied

Added README file under sdks folder describing Minio SDKs along with
quickstart guides and API reference links.
Modified the code in the server startup message file accordingly.
Fixes #5238

2017-11-30 22:31 UTC, shruthied commented
@nitisht  and @kannappanr plz review my changes

2017-11-30 22:42 UTC, harshavardhana requested changes

2017-11-30 22:42 UTC, harshavardhana commented on docs/sdks/README.md
> +
Remove frivolous space above.

2017-11-30 22:42 UTC, harshavardhana commented on docs/sdks/README.md
> +
Frivolous space.

2017-11-30 22:42 UTC, harshavardhana commented on docs/sdks/README.md
> +| `Golang` | [Quick start guide](https://docs.minio.io/docs/golang-client-quickstart-guide)| [API Reference](https://docs.minio.io/docs/golang-client-api-reference) |
s/Golang/Go

2017-12-01 00:01 UTC, harshavardhana commented
This PR is blocked for review until @abperiasamy takes a look, there is a bit revamping that needs to be done before we bring this in. 

@shruthied will update you with new changes once we have finalized.

2018-01-04 10:20 UTC, kannappanr commented
After discussion, it has been decided that we will not be merging this PR, as quite a few users feel that the existing links to the SDKs is good and consolidating them is not required.

2018-01-04 10:20 UTC, closed without merging