Remove "logger" field from config.json
minio/minio pull request #5253
Opened 2017-12-01 22:40 UTC by kannappanr

File logging is removed as part of improvement to server logging.

Change the config.json structure version from 20 to 21.

Upgrade the config.json structure to version 21 upon startup.

Added unit tests to cover this change.

Fixes #5176

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2017-12-02 03:28 UTC, ebozduman requested changes
Just commented about 2 comments.

2017-12-02 03:28 UTC, ebozduman commented on cmd/config-current.go
>  // SetCredentials set new credentials. SetCredential returns the previous credential.
`// SetCredentials set new credentials. SetCredential returns the previous credential.`
 =>
`// SetCredential sets the new credentials and returns the previous credential.`

2017-12-02 03:28 UTC, ebozduman commented on cmd/config-versions.go
> +// serverConfigV21 server configuration version '21' which is like
```
// serverConfigV21 server configuration version '21' which is like
// version '20' except it removes logger field
```
 => 
```
// serverConfigV21 is just like version '20' without logger field
```

2017-12-02 05:49 UTC, kannappanr commented on cmd/config-current.go
>  // SetCredentials set new credentials. SetCredential returns the previous credential.
done

2017-12-02 05:50 UTC, kannappanr commented on cmd/config-versions.go
> +// serverConfigV21 server configuration version '21' which is like
done

2017-12-02 20:14 UTC, kannappanr commented
@krishnasrinivas @ebozduman Can you take a look?

2017-12-04 11:00 UTC, krishnasrinivas submitted a review, later dismissed

2017-12-04 19:14 UTC, ebozduman submitted a review, later dismissed

2017-12-04 23:48 UTC, deekoder commented
codecoverage needs to complete.

2017-12-05 03:09 UTC, kannappanr commented
Code coverage is saying ` Waiting for status to be reported ` . Will close this PR and open a new one to see if this status goes away

2017-12-05 03:09 UTC, closed without merging