Put quorum lock connection on cooldown after net timeout -error.
minio/minio pull request #5442
Opened 2018-01-23 19:09 UTC by TKffTK

Put lock connection on cooldown after net timeout -error.

## Description
Lock request to each server is done with every action, multible times on some actions. If server is totally offline, it will wait for timeout on each lock request, which slows things up.
Implements cooldown -period for lock connection, which is _only_ enabled after timeout -error. Default cooldown -period is globalStorageHealthCheckInterval / 2, so we try twice same time disk tries once.

This basically is same thing that the offline -mode for disk

## Motivation and Context
While fixing freeze problem (https://github.com/remodoy/minio/commit/13aa21b5ea1342628941d20b190dbf0a7ac8cbb2) I did notice that minio is still slow if one node is down -> lock request waiting for connection to timeout where the reason.

## How Has This Been Tested?
2 virtual machines in virtualbox (which is in my development laptop) and one minio instance in same laptop's goland. 2 disks on each minio. Bring everything up. test that it works (mainly using mc from different servers). Kill one sever from virtualbox control panel. Test again reading, writing, etc. files. Bring virtual machine back up.Test. Wait disk cooldown time (5min). Test again. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x]  All test passes which passes against current master.

2018-01-24 00:42 UTC, harshavardhana requested changes
Please fix the CI error.

```
/home/travis/gopath/src/github.com/minio/minio/cmd/lock-rpc-client.go:93:21: error strings should not be capitalized or end with punctuation or a newline
```

2018-01-24 00:45 UTC, harshavardhana reviewed
Would like to see some numbers/benchmarks on how useful this change is across some few thousand files such as `mc mirror` or `aws sync` operation. 

Without this we don't need to do this here instead we can do this in dsync project itself which in-fact does backoff and retries.

2018-01-24 12:19 UTC, TKffTK commented
I will do those benchmark tests on this week.

2018-02-16 01:51 UTC, harshavardhana commented
> I will do those benchmark tests on this week.

Just checking back on how are things going @TKffTK

2018-02-21 19:11 UTC, deekoder commented
@TKffTK - Let us know if we can help you in anyway!

2018-02-22 08:10 UTC, TKffTK commented
Ah, sorry, I'm juggling between projects atm. I will be back on project which needs on next week and finnish changes :).

2018-02-23 05:19 UTC, harshavardhana commented
Thanks @TKffTK

2018-03-20 18:24 UTC, deekoder commented
@TKffTK  we will close this PR as stale. Please feel free to send a new one with our feedback.

2018-03-20 18:24 UTC, closed without merging