Support creating directories on erasure coded backend
minio/minio pull request #5443
Opened 2018-01-24 00:57 UTC by harshavardhana

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2018-01-26 00:28 UTC, harshavardhana commented
@balamurugana @poornas can i get some reviews?

2018-01-26 01:15 UTC, poornas requested changes

2018-01-26 01:15 UTC, poornas commented on cmd/xl-v1-object.go
> +	// Prepare object creation in a all disks
in a all disks -> redundant "a'

2018-01-26 01:15 UTC, poornas commented on cmd/xl-v1-object.go
function needs a comment

2018-01-26 02:31 UTC, poornas commented
How is clean up of these empty directories supposed to work? mc rm will not delete these files. 
```curl -X DELETE localhost:9000/tt1/a1/a2/``` deletes the a2  subdirectory for FS whereas in XL it  does not do so.

2018-01-26 02:58 UTC, harshavardhana commented
> How is clean up of these empty directories supposed to work? mc rm will not delete these files.
> curl -X DELETE localhost:9000/tt1/a1/a2/ deletes the a2 subdirectory for FS whereas in XL it does not do so.

It is supposed to delete just like FS @poornas

2018-01-26 19:49 UTC, michacassola commented
Do you have a rough estimate when you will be able to solve this to enable multi host multi tenant docker swarm volumes?

2018-01-26 19:52 UTC, harshavardhana commented
> Do you have a rough estimate when you will be able to solve this to enable multi host multi tenant docker swarm volumes?

Hopefully soon by end of next week @michacassola

2018-01-29 08:09 UTC, harshavardhana commented
> How is clean up of these empty directories supposed to work? mc rm will not delete these files.
> curl -X DELETE localhost:9000/tt1/a1/a2/ deletes the a2 subdirectory for FS whereas in XL it does not do s

Updated the PR with proper delete support as well @poornas @balamurugana  PTAL

2018-01-29 18:02 UTC, poornas approved these changes
Tested locally. LGTM.

2018-01-30 01:45 UTC, balamurugana approved these changes
LGTM

2018-01-30 02:43 UTC, merged