[WIP] Move error strings into a file
minio/minio pull request #5450
Opened 2018-01-26 09:08 UTC by kannappanr

Moves all the error strings to a single file. Each error string
is contained within a corresponding error logging function.

Fixes #5264

## Description

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-02-04 06:34 UTC, harshavardhana requested changes

2018-02-04 06:34 UTC, harshavardhana commented on cmd/log-errors.go
> +package cmd
Add license header, we should move the logger to a new package along with errorIf and fatalIf.

2018-02-08 11:15 UTC, vadmeste commented on cmd/log-errors.go
> +// test-utils_test.go
I don't think we need to include *_test.go stuffs in this file.

2018-02-13 23:27 UTC, ebozduman requested changes

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	fatalIf(err, funcName(), "Unable to load config.", m)
`"Unable to load config."` => `"Unable to load server config."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Possibly failed to get uptime from majority of servers.", nil)
`"Possibly failed to get uptime from majority of servers."` => `"Failed to get up-time from majority of servers."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Failed to write temporary config file.", m)
`"Failed to write temporary config file."` => `"Failed to write to server temporary config file."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +func LogFailedConfigRename(err error, source, destination string) {
`LogFailedConfigRename` => `LogFailedRenameConfig`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Failed to rename config file.", m)
`"Failed to rename config file."` => `"Failed to rename local config file."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +func LogFailedRemoteConfigRename(err error) {
`LogFailedRemoteConfigRename` => `LogFailedRenameRemoteConfig`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Failed to write temporary config file.", nil)
`"Failed to write temporary config file."` => `"Failed to write to local temporary config file."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Failed to rename config file on a remote node.", nil)
`"Failed to rename config file on a remote node."` => `"Failed to rename remote config file."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Failed to unmarshal serverConfig.", m)
`"Failed to unmarshal serverConfig."` => `"Failed to unmarshal server config."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Unable to finad a valid server config.", nil)
`"Unable to finad a valid server config."` => `"Unable to find a valid server config."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Unable to initialize hashReader.", nil)
`"Unable to initialize hashReader."` => `"Unable to initialize hash reader."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	fatalIf(err, funcName(), "unexpected error when resolving host.", m)
`"unexpected error when resolving host."` => `"Unexpected error when resolving host."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["UUID"] = uuid
`"UUID"` => `"DiskID"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["UUID"] = uuid
"UUID" => "DiskID"

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["UploadIdsPath"] = uploadIDPath
"UploadIdsPath"` => `"UploadsIdPath"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +func LogFailedRemoveFile(err error, path, basePath string) {
`"path"` is defined as `pathJoin(basePath, object)` , so it already has the `"basePath"` information in it. Hence, there is no point printing `"basePath"` information as part of error `"variables"`.

`"Unable to remove file."` => `"Unable to remove object."`

We can get rid of it in the function definition and the call:
```
func LogFailedRemoveFile(err error, path string) {
   m := make(map[string]string)
   m["Path"] = path
   errorIf(err, funcName(), "Unable to remove object.", m)
}

```

and on line#1014 in `"cmd/fs-v1-multipart.go"`:
```
LogFailedRemoveFile(derr, pathJoin(basePath, object))
```

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Addr"] = addr
`"Addr"` => `"ServerAddress"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	fatalIf(err, funcName(), "Invalid address in command line argument", m)
`"Invalid address in command line argument"` => `"Invalid server address in command line argument"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Addr"] = addr
`"Addr"` => `"ServerAddress"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "project-id should be provided as argument or GOOGLE_APPLICATION_CREDENTIALS should be set with path to credentials.json.", nil)
```"project-id should be provided as argument or GOOGLE_APPLICATION_CREDENTIALS should be set with path to credentials.json."```
 => 
```"project-id should be provided as argument or GOOGLE_APPLICATION_CREDENTIALS should be set with path in credentials.json."```

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Object listing error during purging of old files in minio.sys.tmp.", m)
`"Object listing error during purging of old files in minio.sys.tmp."` => `"Object listing error on bucket during purging of old files in minio.sys.tmp."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Attribute"] = attribute
`"Attribute"` => `"ObjectName"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Unable to find file uploaded to Sia path.", m)
`"Unable to find file uploaded to Sia path."` => `"Unable to find object uploaded to Sia path."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Failed to delete lock info entry.", m)
`"Failed to delete lock info entry."` => `"Failed to delete lock info entry for operation."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +func LogFailedDeleteLockInfoEntry(err error) {
We don't need this function. 
It is the exact same function `"LogFailedDeleteLockInfoEntryForVolumePath()"` created for `"deleteLockInfoEntryForVolumePath()"` action the same way.

Removing this function also requires the following changes:
in Line#240 of `cmd/namespace-lock.go`:
`LogFailedDeleteLockInfoEntry(err)` => `LogFailedDeleteLockInfoEntryForOpsID(err, param.volume, param.path, opsID)`

in Line#251 of `cmd/namespace-lock.go`:
`LogFailedDeleteLockInfoEntry(err)` => `LogFailedDeleteLockInfoEntryForVolumePath(err, param.volume, param.path)`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Address"] = addr
`"Address"` => `"ServerAddress"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Failed to delete lock info entry for volume path.", m)
`"Failed to delete lock info entry for volume path."` => `"Unable to establish secure connection to server."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Unable to connect to PostGreSQL service.", nil)
`"Unable to connect to PostGreSQL service."` => `"Unable to connect to PostgreSQL server."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Unable to dial kafka server.", nil)
`"Unable to dial kafka server."` => `"Unable to dial Kafka server."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Unable to lookup webhook endpoint.", m)
`"Unable to lookup webhook endpoint."` => `"Unable to lookup WebHook endpoint."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "found invalid http request header", nil)
`"found invalid http request header"` => `"Invalid http request header"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Disk detected in unexpected format.", m)
`"Disk detected in unexpected format."` => `"Unexpected format on disk."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "rpc hijacking failed.", m)
`"rpc hijacking failed."` => `"Failure during HTTP/RPC hijack."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "peerIndex out of bounds.", m)
`"peerIndex out of bounds."` => `"Peer index out of bounds."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Index"] = strconv.Itoa(index)
`"Index"` => `"PeerIndex"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Addr"] = addr
`"Addr"` => `"PeerAddress"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Error sending update bucket notification.", m)
`"Error sending update bucket notification."` => `"Error sending update bucket notification to peer."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Addr"] = addr
`"Addr"` => `"PeerAddress"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Error sending update bucket listener.", m)
`"Error sending update bucket listener."` => `"Error sending update bucket listener to peer."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Addr"] = addr
`"Addr"` => `"PeerAddress"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Error sending update bucket policy.", m)
`"Error sending update bucket policy."` => `"Error sending update bucket policy to peer."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["HelmPath"] = helmPath
`"HelmPath"` => `"HelmFilePath"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Unable to close httpTraceFile.", m)
`"Unable to close httpTraceFile."` => `"Unable to close http trace file."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	m["Addr"] = addr
`"Addr"` => `"RemoteAddress"`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "unable to evaluate internal disks.", nil)
`"unable to evaluate internal disks."` => `"Unable to evaluate internal disks."`

2018-02-13 23:27 UTC, ebozduman commented on cmd/log-errors.go
> +	errorIf(err, funcName(), "Unable to fetch disk info.", m)
`"Unable to fetch disk info."` => `"Unable to fetch info for disk."`

2018-04-09 17:53 UTC, kannappanr commented
Not needed anymore. Closing this PR.

2018-04-09 17:53 UTC, closed without merging