FS: Always read bucket policy directly from the backend
minio/minio pull request #5466
Opened 2018-01-29 14:58 UTC by vadmeste

## Description
Multiple instances of shared FS have no way to share in realtime
a bucket policy change. This PR changes the behavior of GetBucketPolicy
to always read and parse bucket policy document from the backend
if this is an FS.

## Motivation and Context
Fixes #4458 

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-01-30 23:07 UTC, donatello requested changes

2018-01-30 23:07 UTC, donatello commented on cmd/bucket-policy.go
> +		alwaysRefresh:       objAPI.StorageInfo().Backend.Type == FS,
Would it not be better to use `globalObjectAPI` instead of storing it inside the bucket policies struct?

2018-01-30 23:13 UTC, harshavardhana commented
This PR is not needed @poornas is converging the layers for both Gateway and Object API where this style of functionality will be handling by NAS gateway. 

Implementation would move the code for reading and accessing BucketPolicy to the objectLayer code such as caching etc. will move to the lower layer.  Top layer simply performs GetBucketPolicy() and applies the policy returned to the incoming request. 

Now underneath if the GetBucketPolicy() implementation caches or not is implementation dependent such as erasure coding, single disk fs mode all will cache at their respective object layers where as NAS will directly read from the backend.

2018-01-31 09:12 UTC, vadmeste commented
@harshavardhana makes sense.. closing this.

2018-01-31 09:12 UTC, closed without merging