Fix delete bucket policies properly
minio/minio pull request #5540
Opened 2018-02-16 02:17 UTC by harshavardhana

## Description
Fix delete bucket policies properly

## Motivation and Context
There was bug in previous PR where deleteBucketMetadata() was never called,
fix it correctly.

## How Has This Been Tested?
Manually using `aws-sdk-php` mint tests. 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2018-02-16 02:51 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#8fc5b3b1-32f5-4f1e-92b0-aa52ed1e67d3) |
| mint-dist-xl.sh | :x: [more...](#db6475af-c35b-46ff-91c4-a79be68db088) |
<a name="8fc5b3b1-32f5-4f1e-92b0-aa52ed1e67d3"></a>
### 5540-1822a4f/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30383
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp cbc69e49bcca:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 0 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 44 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5a8640491d308"
  },
  "duration": "40085",
  "status": "FAIL",
  "error": "Expected getBucketPolicy to fail with 404"
}

Executed 1 out of 12 tests successfully.
```
<a name="db6475af-c35b-46ff-91c4-a79be68db088"></a>
### 5540-1822a4f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30614
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 0ff5f27e92cf:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-m1x1cfhwb2420i",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 283,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30614/aws-sdk-go-test-m1x1cfhwb2420i: dial tcp 192.168.122.45:30614: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

2018-02-16 04:49 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#fda91fae-ba1f-4dd6-a9b9-5da9f77f3a0d) |
<a name="fda91fae-ba1f-4dd6-a9b9-5da9f77f3a0d"></a>
### 5540-442af44/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31703
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp e8120a1c8d10:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-aza5r9nbdv0waq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 1377,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:31703/aws-sdk-go-test-aza5r9nbdv0waq: dial tcp 192.168.122.45:31703: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

2018-02-16 05:14 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#890319a0-04b9-451f-9e7d-4ede6e7f05ee) |
| mint-gateway-azure.sh | :x: [more...](#43cee7d2-cd5d-4d0c-8ccc-e8c28df28cf1) |
<a name="43cee7d2-cd5d-4d0c-8ccc-e8c28df28cf1"></a>
### 5540-ce4ec07/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30633
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 6d6a1442040f:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 4 minutes and 12 seconds
(3/12) Running aws-sdk-ruby tests ... done in 1 minutes and 8 seconds
(4/12) Running awscli tests ... FAILED in 1 minutes and 9 seconds
{
  "name": "awscli",
  "duration": 11840,
  "function": "aws --endpoint-url http://minikube:30633 s3api head-object --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key prefix/directory/\n",
  "status": "FAIL",
  "error": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"
}

Executed 3 out of 12 tests successfully.
```
<a name="890319a0-04b9-451f-9e7d-4ede6e7f05ee"></a>
### 5540-ce4ec07/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30654
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 37c2282441b0:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-myxeuaach6obkr",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 320,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30654/aws-sdk-go-test-myxeuaach6obkr: dial tcp 192.168.122.45:30654: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

2018-02-16 12:18 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#8682e142-eb27-4470-b1ca-b34ee4722640) |
<a name="8682e142-eb27-4470-b1ca-b34ee4722640"></a>
### 5540-c57a866/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32597
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp b1a20c21a909:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yxknaqxj9oj5rt",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 319,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:32597/aws-sdk-go-test-yxknaqxj9oj5rt: dial tcp 192.168.122.45:32597: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

2018-02-16 18:46 UTC, poornas requested changes

2018-02-16 18:46 UTC, poornas commented on cmd/fs-v1.go
> +	return writeBucketPolicy(bucket, fs, policy)
@harshavardhana , the S3PeersUpdateBucketPolicy(bucket) was also refreshing the policy cache - both SetBucketPolicy and DeleteBucketPolicy  will need to do that.

2018-02-16 18:46 UTC, poornas commented on cmd/fs-v1.go
> +	return fs.bucketPolicies.DeleteBucketPolicy(bucket)
same as above - policy cache in memory needs to be updated.

2018-02-16 19:11 UTC, poornas approved these changes
LGTM.

2018-02-16 19:42 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#0ef95d60-86c3-4b74-bff2-d5bd9916bf53) |
| mint-dist-xl.sh | :x: [more...](#00b3b2cc-34f7-423b-b544-f81f68d785af) |
<a name="0ef95d60-86c3-4b74-bff2-d5bd9916bf53"></a>
### 5540-64afe92/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31959
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 3add2df845e5:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 0 seconds
(2/12) Running aws-sdk-php tests ... FAILED in 45 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5a872d62be400"
  },
  "duration": "40046",
  "status": "FAIL",
  "error": "Expected getBucketPolicy to fail with 404"
}

Executed 1 out of 12 tests successfully.
```
<a name="00b3b2cc-34f7-423b-b544-f81f68d785af"></a>
### 5540-64afe92/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:30559
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp d5bcc6f9be3e:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-tsntu0cu0ey15w",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 335,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:30559/aws-sdk-go-test-tsntu0cu0ey15w: dial tcp 192.168.122.45:30559: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

2018-02-16 20:27 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#a46db479-bc78-4249-9f4e-6fe7c9d73a38) |
<a name="a46db479-bc78-4249-9f4e-6fe7c9d73a38"></a>
### 5540-6119d1a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32612
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 14f987e235b8:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qom5wohqu9bv0j",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 352,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:32612/aws-sdk-go-test-qom5wohqu9bv0j: dial tcp 192.168.122.45:32612: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

2018-02-17 03:42 UTC, krishnasrinivas approved these changes

2018-02-17 04:16 UTC, merged