Add healthcheck endpoints
minio/minio pull request #5543
Opened 2018-02-16 09:07 UTC by nitisht

## Description
This PR adds readiness and liveness endpoints to probe Minio server
instance health. Endpoints can only be accessed without authentication
and the paths are /minio/health/live and /minio/health/ready for
liveness and readiness respectively.

Also removes the healthcheck script used currently for Dockerfiles.
The unauthenticated healthcheck liveness endpoint is used for healthcheck
now.

## Motivation and Context
See #5357 and #5514

## How Has This Been Tested?
Manually with checking the endpoints

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2018-02-16 09:08 UTC, balamurugana commented
```
Error running mint automation
+ mkdir -p 5543-9c8e803/gopath/src/github.com/minio
+ git -C 5543-9c8e803/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5543-9c8e803/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5543-9c8e803/gopath/src/github.com/minio/minio fetch --quiet minio pull/5543/head:pr5543
+ git -C 5543-9c8e803/gopath/src/github.com/minio/minio checkout --quiet pr5543
+ GOPATH=/home/bala/mintauto/5543-9c8e803/gopath
+ make -C 5543-9c8e803/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.45:2376"
export DOCKER_CERT_PATH="/home/bala/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.45:2376
++ DOCKER_HOST=tcp://192.168.39.45:2376
++ export DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ export DOCKER_API_VERSION=1.23
++ DOCKER_API_VERSION=1.23
+ cp -af Dockerfile.mint-auto 5543-9c8e803/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-5543-9c8e803 --file 5543-9c8e803/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 5543-9c8e803/gopath/src/github.com/minio/minio
Sending build context to Docker daemon  83.98MB

Step 1/10 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 27367480dd9b
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder154963472/dockerscripts/healthcheck.sh: no such file or directory

```

2018-02-16 09:19 UTC, balamurugana commented
```
Error running mint automation
+ mkdir -p 5543-9c74f34/gopath/src/github.com/minio
+ git -C 5543-9c74f34/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5543-9c74f34/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5543-9c74f34/gopath/src/github.com/minio/minio fetch --quiet minio pull/5543/head:pr5543
+ git -C 5543-9c74f34/gopath/src/github.com/minio/minio checkout --quiet pr5543
+ GOPATH=/home/bala/mintauto/5543-9c74f34/gopath
+ make -C 5543-9c74f34/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.45:2376"
export DOCKER_CERT_PATH="/home/bala/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.45:2376
++ DOCKER_HOST=tcp://192.168.39.45:2376
++ export DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ export DOCKER_API_VERSION=1.23
++ DOCKER_API_VERSION=1.23
+ cp -af Dockerfile.mint-auto 5543-9c74f34/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-5543-9c74f34 --file 5543-9c74f34/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 5543-9c74f34/gopath/src/github.com/minio/minio
Sending build context to Docker daemon  83.98MB

Step 1/10 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 27367480dd9b
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder239740975/dockerscripts/healthcheck.sh: no such file or directory

```

2018-02-16 09:32 UTC, balamurugana commented
```
Error running mint automation
+ mkdir -p 5543-a5b15e8/gopath/src/github.com/minio
+ git -C 5543-a5b15e8/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5543-a5b15e8/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5543-a5b15e8/gopath/src/github.com/minio/minio fetch --quiet minio pull/5543/head:pr5543
+ git -C 5543-a5b15e8/gopath/src/github.com/minio/minio checkout --quiet pr5543
+ GOPATH=/home/bala/mintauto/5543-a5b15e8/gopath
+ make -C 5543-a5b15e8/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.45:2376"
export DOCKER_CERT_PATH="/home/bala/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.45:2376
++ DOCKER_HOST=tcp://192.168.39.45:2376
++ export DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ export DOCKER_API_VERSION=1.23
++ DOCKER_API_VERSION=1.23
+ cp -af Dockerfile.mint-auto 5543-a5b15e8/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-5543-a5b15e8 --file 5543-a5b15e8/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 5543-a5b15e8/gopath/src/github.com/minio/minio
Sending build context to Docker daemon  83.98MB

Step 1/10 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 27367480dd9b
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder606977986/dockerscripts/healthcheck.sh: no such file or directory

```

2018-02-16 09:59 UTC, balamurugana commented
```
Error running mint automation
+ mkdir -p 5543-fb0b606/gopath/src/github.com/minio
+ git -C 5543-fb0b606/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5543-fb0b606/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5543-fb0b606/gopath/src/github.com/minio/minio fetch --quiet minio pull/5543/head:pr5543
+ git -C 5543-fb0b606/gopath/src/github.com/minio/minio checkout --quiet pr5543
+ GOPATH=/home/bala/mintauto/5543-fb0b606/gopath
+ make -C 5543-fb0b606/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.45:2376"
export DOCKER_CERT_PATH="/home/bala/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.45:2376
++ DOCKER_HOST=tcp://192.168.39.45:2376
++ export DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ export DOCKER_API_VERSION=1.23
++ DOCKER_API_VERSION=1.23
+ cp -af Dockerfile.mint-auto 5543-fb0b606/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-5543-fb0b606 --file 5543-fb0b606/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 5543-fb0b606/gopath/src/github.com/minio/minio
Sending build context to Docker daemon  83.98MB

Step 1/10 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 27367480dd9b
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder119209017/dockerscripts/healthcheck.sh: no such file or directory

```

2018-02-18 17:01 UTC, harshavardhana commented
We should discuss this with @abperiasamy

2018-02-27 06:53 UTC, harshavardhana commented
> We should discuss this with @abperiasamy

@nitisht were able to unblock this PR?

2018-02-27 07:44 UTC, nitisht commented
> @nitisht were you able to unblock this PR?

Not yet, will ping @abperiasamy today

2018-03-04 18:14 UTC, abperiasamy commented
This patch looks good. In the "healthcheck.md", update this line..
- Liveness probe handler does a list object internally,
+ Liveness probe handler performs a list-buckets operation internally,

2018-03-04 21:39 UTC, harshavardhana requested changes

2018-03-04 21:39 UTC, harshavardhana commented on cmd/healthcheck-handler.go
> +		writeResponse(w, http.StatusServiceUnavailable, nil, mimeNone)
you have to return right here otherwise you will write two responses on clients.

2018-03-04 21:39 UTC, harshavardhana commented on cmd/healthcheck-handler.go
> +		writeResponse(w, http.StatusServiceUnavailable, nil, mimeNone)
you have to return right here otherwise you will write two responses on clients.

2018-03-04 21:39 UTC, harshavardhana commented on cmd/healthcheck-handler.go
> +		writeResponse(w, http.StatusServiceUnavailable, nil, mimeNone)
you have to return right here otherwise you will write two responses on clients.

2018-03-04 21:39 UTC, harshavardhana commented on cmd/healthcheck-handler.go
> +	minioHealthGoroutineThreshold = 500
500 go-routines might be really small @nitisht i would suggest we move this value to `MaxOpenFileLimit-1000`

2018-03-05 04:44 UTC, balamurugana commented
```
Error running mint automation
+ mkdir -p 5543-3fbda03/gopath/src/github.com/minio
+ git -C 5543-3fbda03/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5543-3fbda03/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5543-3fbda03/gopath/src/github.com/minio/minio fetch --quiet minio pull/5543/head:pr5543
+ git -C 5543-3fbda03/gopath/src/github.com/minio/minio checkout --quiet pr5543
+ GOPATH=/home/bala/mintauto/5543-3fbda03/gopath
+ make -C 5543-3fbda03/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.45:2376"
export DOCKER_CERT_PATH="/home/bala/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.45:2376
++ DOCKER_HOST=tcp://192.168.39.45:2376
++ export DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ export DOCKER_API_VERSION=1.23
++ DOCKER_API_VERSION=1.23
+ cp -af Dockerfile.mint-auto 5543-3fbda03/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-5543-3fbda03 --file 5543-3fbda03/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 5543-3fbda03/gopath/src/github.com/minio/minio
Sending build context to Docker daemon   84.5MB

Step 1/10 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 27367480dd9b
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder101396079/dockerscripts/healthcheck.sh: no such file or directory

```

2018-03-05 05:35 UTC, balamurugana commented
```
Error running mint automation
+ mkdir -p 5543-a676c10/gopath/src/github.com/minio
+ git -C 5543-a676c10/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5543-a676c10/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5543-a676c10/gopath/src/github.com/minio/minio fetch --quiet minio pull/5543/head:pr5543
+ git -C 5543-a676c10/gopath/src/github.com/minio/minio checkout --quiet pr5543
+ GOPATH=/home/bala/mintauto/5543-a676c10/gopath
+ make -C 5543-a676c10/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.45:2376"
export DOCKER_CERT_PATH="/home/bala/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.45:2376
++ DOCKER_HOST=tcp://192.168.39.45:2376
++ export DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ export DOCKER_API_VERSION=1.23
++ DOCKER_API_VERSION=1.23
+ cp -af Dockerfile.mint-auto 5543-a676c10/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-5543-a676c10 --file 5543-a676c10/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 5543-a676c10/gopath/src/github.com/minio/minio
Sending build context to Docker daemon   84.5MB

Step 1/10 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 27367480dd9b
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder035505922/dockerscripts/healthcheck.sh: no such file or directory

```

2018-03-05 05:36 UTC, nitisht commented
Addressed the comments @harshavardhana PTAL.

2018-03-05 05:48 UTC, balamurugana commented
```
Error running mint automation
+ mkdir -p 5543-c9ff71a/gopath/src/github.com/minio
+ git -C 5543-c9ff71a/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5543-c9ff71a/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5543-c9ff71a/gopath/src/github.com/minio/minio fetch --quiet minio pull/5543/head:pr5543
+ git -C 5543-c9ff71a/gopath/src/github.com/minio/minio checkout --quiet pr5543
+ GOPATH=/home/bala/mintauto/5543-c9ff71a/gopath
+ make -C 5543-c9ff71a/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.45:2376"
export DOCKER_CERT_PATH="/home/bala/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.45:2376
++ DOCKER_HOST=tcp://192.168.39.45:2376
++ export DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ export DOCKER_API_VERSION=1.23
++ DOCKER_API_VERSION=1.23
+ cp -af Dockerfile.mint-auto 5543-c9ff71a/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-5543-c9ff71a --file 5543-c9ff71a/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 5543-c9ff71a/gopath/src/github.com/minio/minio
Sending build context to Docker daemon   84.5MB

Step 1/10 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 27367480dd9b
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder298261625/dockerscripts/healthcheck.sh: no such file or directory

```

2018-03-05 16:41 UTC, balamurugana commented
```
Error running mint automation
+ mkdir -p 5543-4c35acc/gopath/src/github.com/minio
+ git -C 5543-4c35acc/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 5543-4c35acc/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 5543-4c35acc/gopath/src/github.com/minio/minio fetch --quiet minio pull/5543/head:pr5543
+ git -C 5543-4c35acc/gopath/src/github.com/minio/minio checkout --quiet pr5543
+ GOPATH=/home/bala/mintauto/5543-4c35acc/gopath
+ make -C 5543-4c35acc/gopath/src/github.com/minio/minio --quiet
++ minikube docker-env
+ eval 'export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.39.45:2376"
export DOCKER_CERT_PATH="/home/bala/.minikube/certs"
export DOCKER_API_VERSION="1.23"
# Run this command to configure your shell:
# eval $(minikube docker-env)'
++ export DOCKER_TLS_VERIFY=1
++ DOCKER_TLS_VERIFY=1
++ export DOCKER_HOST=tcp://192.168.39.45:2376
++ DOCKER_HOST=tcp://192.168.39.45:2376
++ export DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ DOCKER_CERT_PATH=/home/bala/.minikube/certs
++ export DOCKER_API_VERSION=1.23
++ DOCKER_API_VERSION=1.23
+ cp -af Dockerfile.mint-auto 5543-4c35acc/gopath/src/github.com/minio/minio/
+ docker build --quiet --tag minio/minio-5543-4c35acc --file 5543-4c35acc/gopath/src/github.com/minio/minio/Dockerfile.mint-auto 5543-4c35acc/gopath/src/github.com/minio/minio
Sending build context to Docker daemon   84.5MB

Step 1/10 : FROM alpine:3.6
 ---> 77144d8c6bdc
Step 2/10 : MAINTAINER Minio Inc <dev@minio.io>
 ---> Using cache
 ---> 27367480dd9b
Step 3/10 : COPY minio dockerscripts/docker-entrypoint.sh dockerscripts/healthcheck.sh /usr/bin/
COPY failed: stat /var/lib/docker/tmp/docker-builder928965798/dockerscripts/healthcheck.sh: no such file or directory

```

2018-03-05 18:03 UTC, nitisht commented
Updated the PR @harshavardhana PTAL

2018-03-05 18:06 UTC, harshavardhana submitted a review, later dismissed
LGTM

2018-03-07 02:44 UTC, nitisht commented
ping @donatello

2018-03-08 07:05 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#a88ffd2b-6808-45d9-a203-e82880fa37bb) |
<a name="a88ffd2b-6808-45d9-a203-e82880fa37bb"></a>
### 5543-c82735c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31635
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp b51e0f5a1b8d:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 2 seconds
(2/12) Running aws-sdk-php tests ... done in 6 minutes and 6 seconds
(3/12) Running aws-sdk-ruby tests ... done in 53 seconds
(4/12) Running awscli tests ... FAILED in 38 seconds
{
  "name": "awscli",
  "duration": 9320,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 3 out of 12 tests successfully.
```

2018-03-08 07:12 UTC, harshavardhana approved these changes
LGTM

2018-03-08 07:54 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#64f8f0f2-36f7-4c33-bb86-8e9f3ee567eb) |
<a name="64f8f0f2-36f7-4c33-bb86-8e9f3ee567eb"></a>
### 5543-4ac25e5/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31651
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp cf0026e92d25:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 5 minutes and 31 seconds
(3/12) Running aws-sdk-ruby tests ... done in 1 minutes and 4 seconds
(4/12) Running awscli tests ... FAILED in 3 minutes and 54 seconds
{
  "name": "awscli",
  "duration": 8531,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 3 out of 12 tests successfully.
```

2018-03-12 04:38 UTC, krisis approved these changes

2018-03-12 06:16 UTC, merged