posix.RenameFile(): Allow overwriting an empty directory
minio/minio pull request #5551
Opened 2018-02-19 16:52 UTC by vadmeste

## Description
Overwriting files is allowed, but since the introduction of
the object directory, we will aslo need to allow overwriting
an empty directory. Putting twice the same object directory
won't fail with 403 error anymore.

## Motivation and Context
Fixes #5549 

## How Has This Been Tested?
go test + Manually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-02-19 17:28 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#f9257117-6e06-4288-b35d-6d11eeb96756) |
| mint-gateway-azure.sh | :x: [more...](#2caa5150-2a1a-417d-9db3-5ca34779f954) |
<a name="f9257117-6e06-4288-b35d-6d11eeb96756"></a>
### 5551-9b39a54/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32044
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 266a282accd6:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0nr35dfw6bxxe6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 381,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:32044/aws-sdk-go-test-0nr35dfw6bxxe6: dial tcp 192.168.122.45:32044: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```
<a name="2caa5150-2a1a-417d-9db3-5ca34779f954"></a>
### 5551-9b39a54/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:32299
ACCESS_KEY:      minioazure1
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp c86297c16301:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... done in 1 seconds
(2/12) Running aws-sdk-php tests ... done in 4 minutes and 41 seconds
(3/12) Running aws-sdk-ruby tests ... done in 54 seconds
(4/12) Running awscli tests ... FAILED in 1 minutes and 45 seconds
{
  "name": "awscli",
  "duration": 15173,
  "function": "aws --endpoint-url http://minikube:32299 s3api put-object --body /mint/data/datafile-1-MB --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-1-MB\n",
  "status": "FAIL",
  "error": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"
}

Executed 3 out of 12 tests successfully.
```

2018-02-19 18:44 UTC, harshavardhana approved these changes
LGTM testsd

2018-02-20 07:28 UTC, krishnasrinivas requested changes
@vadmeste `fs` backend also needs similar change?

2018-02-20 07:36 UTC, harshavardhana commented
> @vadmeste fs backend also needs similar change?

It doesn't need such a change @krishnasrinivas

2018-02-20 10:58 UTC, vadmeste commented
> @vadmeste fs backend also needs similar change?

@krishnasrinivas it doesn't.. it works fine with FS.

2018-02-20 18:36 UTC, krishnasrinivas approved these changes

2018-02-20 20:20 UTC, merged