Add a a PoC for #5305 to enable multiple credential pairs
minio/minio pull request #5588
Opened 2018-02-28 10:35 UTC by antmanler

Add a CredentialProvider to enable multiple credential pairs for embedded Minio server

## Description

In our internal FaaS, we need to assign different  credential pairs for each function and jail API access under certain prefix(we call scope), we embed Minio gateway in custom server sync credentials from controller.

I think may be this will help to solve #5305 or a PoC at least.

Interface `CredentialProvider` can be implemented for different backends, in [embeded_example_main.go](https://github.com/antmanler/minio/blob/1aabdd88075a1fe285706e2ea701d41a561f1580/embeded_example_main.go) it simple uses a dict to provides extra credentials.

```go
type CredentialProvider interface {
	Get(key string) (CustomCredentials, APIErrorCode)
}
```

`Secondary credentials` are indexed by accessKey in `CredentialProvider`,

 `AccessKey` , `SecretKey` in config or passed from Env is `master credentials`.

Secondary credentials can access most of S3 apis but admin and internal apis require master credentials.

## Motivation and Context

#5305

## How Has This Been Tested?

Manual, unit tests not ready yet

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2018-02-28 11:17 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

2018-02-28 15:26 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

2018-02-28 22:27 UTC, harshavardhana requested changes
-1 for now since this changes the behavior of current Minio and is not in line with the approach we are going to take implementing multiple credentials. 

Will write in detailed why there is a conflict.

2018-03-08 07:25 UTC, harshavardhana requested changes
@antmanler - thanks for working on this PR. We are currently actively designing a system to provide a multi-tenant system by implementing a federation system. 

The approach in this PR conflicts with the above design.  The basic important requirement of Minio is that it serves the needs of the single tenant and nothing more. One credential per server is an important requirement from a security point of view, multiple credentials would complicate the server. Without a proper access control model, we cannot implement multiple credentials on the server side and we wish to avoid going the route of access controls which invariably complicates our server system. 

To implement proper access controls you should implement this in your application or run multiple Minio servers with different creds.

2018-03-08 09:16 UTC, antmanler commented
@harshavardhana I agree implementing a fine grained access control is complicated, and we should keep Minio server as simple as possible.  It's good to close this PR

2018-03-08 09:17 UTC, closed without merging