check that the server supports encryption for SSE-C requests
minio/minio pull request #5597
Opened 2018-03-01 20:16 UTC by aead

## Description

This change adds a check to verify that the server backend does support
encryption if a request contains SSE-C headers. If not the server
should fail - with Not Implemented - instead of given the impression
of e.g. encrypting the object while it actually stores the object in plaintext.

## Motivation and Context
Fixes #5511

## How Has This Been Tested?
manually - as described in the issue. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-03-01 20:16 UTC, harshavardhana approved these changes
LGTM

2018-03-01 20:17 UTC, harshavardhana commented
One problem here is that @aead we will not be able to translate SSE headers back to gateway backends - how do you think we should address that?

2018-03-01 20:19 UTC, aead commented
> One problem here is that @aead we will not be able to translate SSE headers back to gateway backends - how do you think we should address that?

Do you mean that we cannot check whether the gateway supports SSE-C? Or that we cannot send SSE-C headers to gateway?

2018-03-01 20:23 UTC, harshavardhana commented
> Do you mean that we cannot check whether the gateway supports SSE-C? Or that we cannot send SSE-C headers to gateway?

IsObjectEncryptionEnabled() to true would mean that DARE will be created on gateway backend. But we want to perhaps do pass through for now as well. So rejecting in SSE-C headers are set would actually make it short handed? is what i think.

2018-03-01 20:27 UTC, aead commented
Okay, so it depends - if we want to terminate SSE-C on gateway, than everything is fine - backend has no clue that we store encrypted blobs. It does not know whether the client requested SSE-C.

2018-03-01 20:28 UTC, harshavardhana commented
> Okay, so it depends - if we want to terminate SSE-C on gateway, than everything is fine - backend has no clue that we store encrypted blobs. It does not know whether the client requested SSE-C.

That is why perhaps existing behavior is fine for now.

2018-03-01 20:32 UTC, aead commented
> That is why perhaps existing behavior is fine for now.

For a gateway implementation (e.g. S3 gateway) we can return always true for `objectAPI.IsEncryptionSupported()` - So handler-layer will always create DARE objects if SSE-C is provided. So basically **all** gateway backend implementation support encryption - since the server does it for them.

The only thing we have to decide is whether we want to do passthrough as well...

2018-03-01 20:34 UTC, harshavardhana commented
> For a gateway implementation (e.g. S3 gateway) we can return always true for objectAPI.IsEncryptionSupported() - So handler-layer will always create DARE objects if SSE-C is provided. So basically all gateway backend implementations support encryption - since the server does it for them.

Yes but doing this is something @abperiasamy doesn't want yet - perhaps you can ping him and ask. But i see that it could be a hindrance if we don't support pass through.

2018-03-01 20:38 UTC, vadmeste approved these changes
LGTM

2018-03-01 20:39 UTC, aead commented
>Yes but doing this is something @abperiasamy doesn't want yet - perhaps you can ping him and ask. But i see that it could be a hindrance if we don't support pass through.

I'll ask him. But the point is: at the moment we do this already - So AFAIKS if someone starts gateway and sends SSE-C requests we create DARE objects. So the only thing we have to add is a check whether we want to do pass-through (set by ENV_VAR or ....) and if so delegate directly to backend implementation.

2018-03-01 20:53 UTC, aead commented
I put this on hold until we have a decision.

2018-03-06 00:06 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

2018-03-06 02:13 UTC, harshavardhana requested changes
-1 until this PR gets unblocked

2018-03-20 18:17 UTC, harshavardhana commented
We should close this @aead and re-send if we decide to do. Since current implementation is expected.

2018-03-20 20:07 UTC, aead commented
@harshavardhana Agree, closing.

2018-03-20 20:07 UTC, closed without merging