Ensure to load only regular files for CAs
minio/minio pull request #5612
Opened 2018-03-06 23:32 UTC by harshavardhana

## Description
Ensure to load only regular files for CAs

## Motivation and Context
In kubernetes statefulset like environments when secrets
are mounted to pods they have sub-directories, we should
ideally be only looking for regular files here and skip
all others.

## How Has This Been Tested?
Manually using kubernetes statefulset deployment.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2018-03-06 23:35 UTC, xdire approved these changes
Great thing to have

2018-03-07 05:10 UTC, nitisht submitted a review, later dismissed
LGTM

2018-03-07 05:22 UTC, harshavardhana commented
Don't merge this yet.. still working with the user.

2018-03-07 05:51 UTC, kannappanr commented
marked as blocked as this PR is still undergoing changes. will unblock it once @harshavardhana says so

2018-03-07 07:27 UTC, harshavardhana commented
Removing blocked as this is finally tested and validated correctly.

2018-03-07 10:09 UTC, nitisht approved these changes
LGTM and tested with self-signed certs

2018-03-07 14:40 UTC, nitisht requested changes
`CAs` directory is not mounted, so self signed certs not working at the moment. Investigating now.

2018-03-07 15:54 UTC, nitisht approved these changes
LGTM & tested

2018-03-07 16:46 UTC, merged