Modify fatalIf, startup and update message logging code
minio/minio pull request #5620
Opened 2018-03-08 00:45 UTC by kannappanr

## Description
Change fatalIf implementation in logger.go. Do not log trace, as all
of the fatalIf calls are made during startup.

Use new functions to and a common logging framework to make sure that
startup and update messages get logged in both console and json mode.

## Motivation and Context
These changes are part of error logging pod.

## How Has This Been Tested?
Manually

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-03-08 01:49 UTC, ebozduman requested changes

2018-03-08 01:49 UTC, ebozduman commented on cmd/logger.go
> +	i.pretty(cause, msg, args...)
Don't we need to be quite for info messages when `--quite` flag is turned on?

2018-03-08 01:49 UTC, ebozduman commented on cmd/prepare-storage.go
> +					LogInfoMessage("Waiting for the first server to format the disks.\n")
You already have a new line character, `\n`, added in `LogInfoMessage` definition.
Is there any  other reason you need it here again?

2018-03-08 01:49 UTC, ebozduman commented on cmd/prepare-storage.go
> +			LogInfoMessage("Waiting for a minimum of %d disks to come online (elapsed %s)\n", len(endpoints)/2, getElapsedTime())
You already have a new line character, \n, added in LogInfoMessage definition.
Is there any other reason you need it here again?

2018-03-08 01:49 UTC, ebozduman commented on cmd/signals.go
> +			LogInfoMessage("Exiting on signal %v\n", osSignal)
You already have a new line character, \n, added in LogInfoMessage definition.
Is there any other reason you need it here again?

2018-03-09 20:30 UTC, kannappanr commented on cmd/logger.go
> +	i.pretty(cause, msg, args...)
No. Only for startup messages.

2018-03-10 02:14 UTC, kannappanr commented on cmd/signals.go
> +			LogInfoMessage("Exiting on signal %v\n", osSignal)
done

2018-03-10 02:14 UTC, kannappanr commented on cmd/prepare-storage.go
> +			LogInfoMessage("Waiting for a minimum of %d disks to come online (elapsed %s)\n", len(endpoints)/2, getElapsedTime())
done

2018-03-10 02:14 UTC, kannappanr commented on cmd/prepare-storage.go
> +					LogInfoMessage("Waiting for the first server to format the disks.\n")
done

2018-03-10 02:50 UTC, ebozduman approved these changes

2018-03-10 03:16 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

2018-03-20 19:06 UTC, kannappanr commented
blocked on https://github.com/minio/minio/pull/5678

2018-04-10 16:38 UTC, kannappanr commented
Closing this PR. Not needed anymore.

2018-04-10 16:38 UTC, closed without merging