Cleanup large bucket support documents
minio/minio pull request #5641
Opened 2018-03-13 05:46 UTC by nitisht

## Description
Updated large bucket related documents for clarity. 

## Motivation and Context
cleanup

## How Has This Been Tested?
NA

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2018-03-13 05:57 UTC, harshavardhana requested changes

2018-03-13 05:57 UTC, harshavardhana commented on docs/large-bucket/DESIGN.md
> +## Limitations
actually this should be mentioned as `limits` not limitations

2018-03-13 06:18 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#bb4d5a0d-cd24-4b99-a7bb-74f15391bc5b) |
<a name="bb4d5a0d-cd24-4b99-a7bb-74f15391bc5b"></a>
### 5641-0562964/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT: minikube:31522
ACCESS_KEY:      minio
SECRET_KEY:      ***REDACTED***
ENABLE_HTTPS:    0
SERVER_REGION:   us-east-1
MINT_DATA_DIR:   /mint/data
MINT_MODE:       core

To get logs, run 'docker cp 0dc70a07499d:/mint/log /tmp/mint-logs'
(1/12) Running aws-sdk-go tests ... FAILED in 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-c3h3vr1almcexr",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 4427,
  "error": "RequestError: send request failed\ncaused by: Put http://minikube:31522/aws-sdk-go-test-c3h3vr1almcexr: dial tcp 192.168.122.45:31522: getsockopt: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 12 tests successfully.
```

2018-03-13 06:26 UTC, harshavardhana approved these changes

2018-03-13 06:53 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

2018-03-14 21:48 UTC, deekoder approved these changes

2018-03-14 22:22 UTC, merged