Update disk cache documentation
minio/minio pull request #5743
Opened 2018-03-30 21:18 UTC by poornas

fixes #5739 
## Description

## Motivation and Context

## How Has This Been Tested?

manually
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-03-30 21:38 UTC, harshavardhana requested changes

2018-03-30 21:38 UTC, harshavardhana commented on docs/disk-caching/DESIGN.md
> +cached entries are served from cache.
don't manually press enter let markdown to wrap itself.

2018-03-30 21:38 UTC, harshavardhana commented on docs/disk-caching/DESIGN.md
> +  with atime support can be specified in MINIO_CACHE_DRIVES
don't manually press enter let markdown to wrap itself.

2018-03-30 21:53 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

2018-03-30 23:01 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

2018-04-01 15:01 UTC, nitisht requested changes

2018-04-01 15:01 UTC, nitisht commented on docs/disk-caching/README.md
> +Disk caching can be enabled by updating the `cache` config settings for Minio server. Config `cache` settings takes the mounted drive(s) or director(ies) paths, cache expiry duration (in days) and an
We can just say directory path(s) instead of `director(ies) paths`

2018-04-02 03:01 UTC, balamurugana commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |

2018-04-02 04:23 UTC, nitisht approved these changes

2018-04-02 04:54 UTC, harshavardhana approved these changes

2018-04-02 04:55 UTC, merged