Allow head requests for prefixes without trailing "/"
minio/minio pull request #5966
Opened 2018-05-21 10:49 UTC by nitisht

## Description
Reverted some of the changes from #5900 to allow Spark to work with Minio 
server in FS mode. 

## Motivation and Context
To ensure Spark runs with Minio server in FS mode.

## How Has This Been Tested?
Manually with Spark and Minio FS server

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2018-05-21 17:29 UTC, vadmeste commented
@nitisht, are you saying that this PR will return 200 OK for HEAD requests for all existing prefixes even without trailing slashes ?

2018-05-22 02:41 UTC, nitisht commented
> are you saying that this PR will return 200 OK for HEAD requests for all existing prefixes even without trailing slashes ?

No, this returns 404 instead of 403 being thrown currently. AFAICS Spark doesn't complain for 404 but complains for 403

2018-05-22 22:15 UTC, vadmeste commented
@nitisht could you ping me to see what error did you see in Spark? I knew about 403 thing but as I remember it wasn't affecting Spark, though it would be good to comply to S3 spec.

2018-05-23 04:51 UTC, nitisht commented
@vadmeste there are the typical error messages - when running spark jobs on Minio FS mode

```
API: HeadObject(bucket=spark-test, object=test-write/_temporary/0/_temporary/attempt_20180520160214_0001_m_000000_0)
Time: 16:02:21 IST 05/20/2018
RemoteHost: 127.0.0.1:52204
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=spark-test, object=test-write/_temporary/0/_temporary/attempt_20180520160214_0001_m_000000_0)
Time: 16:02:21 IST 05/20/2018
RemoteHost: 127.0.0.1:52206
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=spark-test, object=test-write/_temporary/0/_temporary/attempt_20180520160214_0001_m_000002_0)
Time: 16:02:21 IST 05/20/2018
RemoteHost: 127.0.0.1:52198
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=spark-test, object=test-write/_temporary/0/_temporary/attempt_20180520160214_0001_m_000003_0)
Time: 16:02:21 IST 05/20/2018
RemoteHost: 127.0.0.1:52202
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=spark-test, object=test-write/_temporary/0/_temporary/attempt_20180520160214_0001_m_000001_0)
Time: 16:02:21 IST 05/20/2018
RemoteHost: 127.0.0.1:52196
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=spark-test, object=test-write/_temporary/0/_temporary/attempt_20180520160214_0001_m_000003_0)
Time: 16:02:21 IST 05/20/2018
RemoteHost: 127.0.0.1:52208
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=spark-test, object=test-write/_temporary/0/_temporary/attempt_20180520160214_0001_m_000001_0)
Time: 16:02:21 IST 05/20/2018
RemoteHost: 127.0.0.1:52210
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=spark-test, object=test-write/_temporary/0/_temporary/attempt_20180520160214_0001_m_000002_0)
Time: 16:02:21 IST 05/20/2018
RemoteHost: 127.0.0.1:52212
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()

API: HeadObject(bucket=spark-test, object=test-write/_temporary)
Time: 16:02:22 IST 05/20/2018
RemoteHost: 127.0.0.1:52214
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:239:cmd.fsStatFile()
       2: cmd/fs-v1.go:604:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:629:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:634:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

2018-06-05 07:47 UTC, harshavardhana requested changes
As suggested we should avoid using `fsIsDir` instead use `fs.isObjectDir` 

```diff
diff --git a/cmd/fs-v1-helpers.go b/cmd/fs-v1-helpers.go
index a3cd1f95..bb650b67 100644
--- a/cmd/fs-v1-helpers.go
+++ b/cmd/fs-v1-helpers.go
@@ -225,15 +225,6 @@ func fsStatDir(ctx context.Context, statDir string) (os.FileInfo, error) {
        return fi, nil
 }
 
-// Returns if the dirPath is a directory.
-func fsIsDir(ctx context.Context, dirPath string) bool {
-       fi, err := fsStat(ctx, dirPath)
-       if err != nil {
-               return false
-       }
-       return fi.IsDir()
-}
-
 // Lookup if file exists, returns file attributes upon success.
 func fsStatFile(ctx context.Context, statFile string) (os.FileInfo, error) {
        fi, err := fsStat(ctx, statFile)
diff --git a/cmd/fs-v1-helpers_test.go b/cmd/fs-v1-helpers_test.go
index 0df862a3..227e495b 100644
--- a/cmd/fs-v1-helpers_test.go
+++ b/cmd/fs-v1-helpers_test.go
@@ -548,18 +548,6 @@ func TestFSRemoveMeta(t *testing.T) {
        }
 }
 
-func TestFSIsDir(t *testing.T) {
-       dirPath, err := ioutil.TempDir(globalTestTmpDir, "minio-")
-       if err != nil {
-               t.Fatalf("Unable to create tmp directory %s", err)
-       }
-       defer os.RemoveAll(dirPath)
-
-       if !fsIsDir(context.Background(), dirPath) {
-               t.Fatalf("Expected %s to be a directory", dirPath)
-       }
-}
-
 func TestFSIsFile(t *testing.T) {
        dirPath, err := ioutil.TempDir(globalTestTmpDir, "minio-")
        if err != nil {
diff --git a/cmd/fs-v1.go b/cmd/fs-v1.go
index ececb7b2..eba4a171 100644
--- a/cmd/fs-v1.go
+++ b/cmd/fs-v1.go
@@ -563,9 +563,10 @@ func (fs *FSObjects) defaultFsJSON(object string) fsMetaV1 {
 // getObjectInfo - wrapper for reading object metadata and constructs ObjectInfo.
 func (fs *FSObjects) getObjectInfo(ctx context.Context, bucket, object string) (oi ObjectInfo, e error) {
        fsMeta := fsMetaV1{}
+       isDir := fs.isObjectDir(bucket, object)
        if hasSuffix(object, slashSeparator) {
                // Since we support PUT of a "directory" object, we allow HEAD.
-               if !fsIsDir(ctx, pathJoin(fs.fsPath, bucket, object)) {
+               if !isDir {
                        return oi, errFileNotFound
                }
                fi, err := fsStatDir(ctx, pathJoin(fs.fsPath, bucket, object))
@@ -573,6 +574,8 @@ func (fs *FSObjects) getObjectInfo(ctx context.Context, bucket, object string) (
                        return oi, err
                }
                return fsMeta.ToObjectInfo(bucket, object, fi), nil
+       } else if isDir {
+               return oi, errFileNotFound
        }
 
        fsMetaPath := pathJoin(fs.fsPath, minioMetaBucket, bucketMetaPrefix, bucket, object, fs.metaJSONFile)
@@ -623,11 +626,7 @@ func (fs *FSObjects) getObjectInfoWithLock(ctx context.Context, bucket, object s
        }
 
        if _, err := fs.statBucketDir(ctx, bucket); err != nil {
-               return oi, toObjectErr(err, bucket)
-       }
-
-       if strings.HasSuffix(object, slashSeparator) && !fs.isObjectDir(bucket, object) {
-               return oi, errFileNotFound
+               return oi, err
        }
 
        return fs.getObjectInfo(ctx, bucket, object)
```

2018-06-07 18:00 UTC, vadmeste commented
@harshavardhana actually, your suggestion won't work because  getObjectInfo() is called here https://github.com/minio/minio/blob/master/cmd/fs-v1.go#L1095 when listing, and there we expect we return information for all objects & directories.

2018-06-07 18:38 UTC, harshavardhana commented
> @harshavardhana actually, your suggestion won't work because getObjectInfo() is called here https://github.com/minio/minio/blob/master/cmd/fs-v1.go#L1095 when listing, and there we expect we return information for all objects & directories.

No it shouldn't be the case even there we shouldn't return incorrectly, the behavior is simple 

- If there is a directory and it has files in it then it's not a directory we consider it to be an object.
- If there is a directory and it has no files in it (its empty) is a directory.

2018-06-08 10:56 UTC, nitisht commented
> If there is a directory and it has files in it then it's not a directory we consider it to be an object.

@harshavardhana I have updated the PR, but Spark still fails. The problem is Spark tries to HeadObject 
`test-write/_temporary` where `_temporary` is a non-empty directory. 


```sh
API: HeadObject(bucket=spark-test, object=test-write/_temporary)
Time: 16:13:41 IST 06/08/2018
RemoteHost: 127.0.0.1:15074
UserAgent: Hadoop 2.8.2, aws-sdk-java/1.11.234 Linux/4.15.0-20-generic OpenJDK_64-Bit_Server_VM/25.171-b11 java/1.8.0_171 scala/2.11.8
Error: file access denied
       1: cmd/fs-v1-helpers.go:238:cmd.fsStatFile()
       2: cmd/fs-v1.go:680:cmd.(*FSObjects).getObjectInfo()
       3: cmd/fs-v1.go:705:cmd.(*FSObjects).getObjectInfoWithLock()
       4: cmd/fs-v1.go:710:cmd.(*FSObjects).GetObjectInfo()
       5: cmd/object-handlers.go:82:cmd.(ObjectLayer).GetObjectInfo-fm()
       6: cmd/object-handlers.go:258:cmd.objectAPIHandlers.HeadObjectHandler()
       7: cmd/api-router.go:59:cmd.(objectAPIHandlers).HeadObjectHandler-fm()
       8: net/http/server.go:1947:http.HandlerFunc.ServeHTTP()
```

2018-06-08 16:09 UTC, harshavardhana commented
A non empty directory should return 404 let me see why the PR doesn't work .

2018-06-08 16:15 UTC, vadmeste commented
@nitisht tests are also not passing.. getObjectInfo() name is little misleading, we should rename it to getStatInfo() because it is is used by https://github.com/minio/minio/blob/master/cmd/fs-v1.go#L1095 and should return stat information for every file/directory empty or not empty (for listing purposes)

@nitisht if you do this:
`mc cp file alias/bucket/dir/file` and then `mc ls alias/bucket/dir/` then you won't have any result because getObjectInfo for ('bucket', 'dir/') is not returning success & valid information.

Let's talk privately to fix this.

2018-06-25 18:09 UTC, nitisht commented
Updated the PR, PTAL @vadmeste @harshavardhana

2018-06-25 18:10 UTC, harshavardhana commented
> Updated the PR, PTAL @vadmeste @harshavardhana

The changes were validated against both hadoop and apache drill @vadmeste

2018-06-25 18:10 UTC, harshavardhana approved these changes

2018-06-25 22:28 UTC, vadmeste approved these changes
LGTM

2018-06-26 01:24 UTC, merged