[WIP] Healing remove stale objects
minio/minio pull request #6569
Opened 2018-10-05 00:10 UTC by vadmeste

### Not ready yet, need more thinking and more discussion

## Description

## Motivation and Context

## Regression

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2018-10-05 02:07 UTC, harshavardhana requested changes

2018-10-05 02:07 UTC, harshavardhana commented on cmd/xl-v1-healing.go
> +					disk.DeleteFile(minioMetaTrashBucket, object)
we should do this for missing `part.1`s as well

2018-10-05 22:57 UTC, vadmeste commented
Fixing this https://github.com/minio/minio/issues/6575 will make an object visible, which means we can remove an object using regular `mc rm` command even if it doesn't have read quorum.

Downloading it will generate an error anyway.

2018-10-11 07:35 UTC, harshavardhana commented
This is not considered as a valid fix for this issue after discussing with @abperiasamy, the basic fundamental is healing doesn't remove any data, https://github.com/minio/minio/pull/6592 has enough requirements.

This PR can be closed.

2018-10-11 09:49 UTC, vadmeste commented
> This is not considered as a valid fix for this issue after discussing with @abperiasamy, the basic fundamental is healing doesn't remove any data, #6592 has enough requirements.

Yes, closing

2018-10-11 09:49 UTC, closed without merging