Add error handling in api-resource.go
minio/minio pull request #6651
Opened 2018-10-17 12:29 UTC by leitzler

## Description
There are several calls to `strconv.Atoi(...)` that silently ignores errors and relies on the returned value even if the convert fails.  This PR adds error handling to prevent this.

## Motivation and Context
If an error is returned, you can't rely on the returned value. A nice side effect is that the API will comply more to S3 since it now provides more real S3 errors.

## How Has This Been Tested?
Updated testcases where applied and `make test`

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-10-17 13:50 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-10-17 18:37 UTC, kannappanr commented on cmd/api-resources.go
> +		if maxkeys, err = strconv.Atoi(values.Get("max-keys")); err != nil {
`var err error` can be moved between lines 58 and 59

2018-10-17 18:38 UTC, kannappanr commented on cmd/api-resources.go
> +		if maxkeys, err = strconv.Atoi(values.Get("max-keys")); err != nil {
line 26 `var err error `can be moved between lines 29 and 30

2018-10-17 18:40 UTC, kannappanr commented on cmd/api-resources.go
> +		if maxUploads, err = strconv.Atoi(values.Get("max-uploads")); err != nil {
line 78 `var err error` can be moved between lines 81 and 82

2018-10-17 18:40 UTC, kannappanr commented on cmd/api-resources.go
> +		if maxParts, err = strconv.Atoi(values.Get("max-parts")); err != nil {
line 100 `var err error` can be moved between lines 103 and 104

2018-10-17 20:07 UTC, kannappanr submitted a review, later dismissed
LGTM

2018-10-17 21:09 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-10-18 04:13 UTC, Praveenrajmani commented on cmd/api-resources.go
> +	partNumberMarker, _ = strconv.Atoi(values.Get("part-number-marker"))
This can also be handled similarly

2018-10-18 04:25 UTC, Praveenrajmani requested changes

2018-10-18 04:25 UTC, Praveenrajmani commented on cmd/api-resources.go
> +	partNumberMarker, _ = strconv.Atoi(values.Get("part-number-marker"))
This can also be handled similarly

2018-10-18 05:38 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :x: [more...](#ecb4b2ae-c1c8-487b-81a6-c5ea7e989fa8) |
| mint-xl.sh | :x: [more...](#e4459061-14b4-462a-b2fc-500ed67a2253) |
| mint-gateway-nas.sh | :x: [more...](#f245c077-b33c-49e1-ac02-10d17eb72c2c) |
| mint-large-bucket.sh | :x: [more...](#76aa0b73-5572-4dd3-be9a-f9fd85174ad5) |
| mint-worm.sh | :x: [more...](#be3ba49d-55d3-4284-84b0-4c0ce86a2327) |
| mint-fs.sh | :x: [more...](#d871faef-8485-4b9c-8a35-0bf07714fcac) |
| mint-dist-xl.sh | :x: [more...](#c3059b5d-43e9-40d1-8caa-e820a5177f68) |
<a name="76aa0b73-5572-4dd3-be9a-f9fd85174ad5"></a>
### 6651-0fb2410/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31300
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a413daac2fd2:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 20 seconds
{"name": "awscli", "duration": 6851, "function": "aws --endpoint-url http://minikube:31300 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-5118/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (817.4 KiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (1.5 MiB/s) with 1 file(s) remaining  
Completed 768.0 KiB/65.0 MiB (2.2 MiB/s) with 1 file(s) remaining  
Completed 1.0 MiB/65.0 MiB (2.7 MiB/s) with 1 file(s) remaining    
Completed 1.2 MiB/65.0 MiB (1.8 MiB/s) with 1 file(s) remaining    
Completed 1.5 MiB/65.0 MiB (2.1 MiB/s) with 1 file(s) remaining    
Completed 1.8 MiB/65.0 MiB (2.4 MiB/s) with 1 file(s) remaining    
Completed 2.0 MiB/65.0 MiB (2.8 MiB/s) with 1 file(s) remaining    
Completed 2.2 MiB/65.0 MiB (3.1 MiB/s) with 1 file(s) remaining    
Completed 2.5 MiB/65.0 MiB (3.4 MiB/s) with 1 file(s) remaining    
Completed 2.8 MiB/65.0 MiB (3.8 MiB/s) with 1 file(s) remaining    
Completed 3.0 MiB/65.0 MiB (4.1 MiB/s) with 1 file(s) remaining    
Completed 3.2 MiB/65.0 MiB (4.4 MiB/s) with 1 file(s) remaining    
Completed 3.5 MiB/65.0 MiB (4.7 MiB/s) with 1 file(s) remaining    
Completed 3.8 MiB/65.0 MiB (5.1 MiB/s) with 1 file(s) remaining    
Completed 4.0 MiB/65.0 MiB (5.4 MiB/s) with 1 file(s) remaining    
Completed 4.2 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining    
Completed 4.5 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining    
Completed 4.8 MiB/65.0 MiB (6.4 MiB/s) with 1 file(s) remaining    
Completed 5.0 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining    
Completed 5.2 MiB/65.0 MiB (7.0 MiB/s) with 1 file(s) remaining    
Completed 5.5 MiB/65.0 MiB (7.3 MiB/s) with 1 file(s) remaining    
Completed 5.8 MiB/65.0 MiB (7.6 MiB/s) with 1 file(s) remaining    
Completed 6.0 MiB/65.0 MiB (7.9 MiB/s) with 1 file(s) remaining    
Completed 6.2 MiB/65.0 MiB (8.2 MiB/s) with 1 file(s) remaining    
Completed 6.5 MiB/65.0 MiB (8.5 MiB/s) with 1 file(s) remaining    
Completed 6.8 MiB/65.0 MiB (8.8 MiB/s) with 1 file(s) remaining    
Completed 7.0 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining    
Completed 7.2 MiB/65.0 MiB (9.4 MiB/s) with 1 file(s) remaining    
Completed 7.5 MiB/65.0 MiB (9.8 MiB/s) with 1 file(s) remaining    
Completed 7.8 MiB/65.0 MiB (10.1 MiB/s) with 1 file(s) remaining   
Completed 8.0 MiB/65.0 MiB (10.4 MiB/s) with 1 file(s) remaining   
Completed 8.2 MiB/65.0 MiB (10.6 MiB/s) with 1 file(s) remaining   
Completed 8.5 MiB/65.0 MiB (10.8 MiB/s) with 1 file(s) remaining   
Completed 8.8 MiB/65.0 MiB (11.2 MiB/s) with 1 file(s) remaining   
Completed 9.0 MiB/65.0 MiB (11.4 MiB/s) with 1 file(s) remaining   
Completed 9.2 MiB/65.0 MiB (9.2 MiB/s) with 1 file(s) remaining    
Completed 9.5 MiB/65.0 MiB (9.4 MiB/s) with 1 file(s) remaining    
Completed 9.8 MiB/65.0 MiB (9.7 MiB/s) with 1 file(s) remaining    
Completed 10.0 MiB/65.0 MiB (9.8 MiB/s) with 1 file(s) remaining   
Completed 10.2 MiB/65.0 MiB (10.1 MiB/s) with 1 file(s) remaining  
Completed 10.5 MiB/65.0 MiB (10.2 MiB/s) with 1 file(s) remaining  
Completed 10.8 MiB/65.0 MiB (10.5 MiB/s) with 1 file(s) remaining  
Completed 11.0 MiB/65.0 MiB (10.7 MiB/s) with 1 file(s) remaining  
Completed 11.2 MiB/65.0 MiB (10.9 MiB/s) with 1 file(s) remaining  
Completed 11.5 MiB/65.0 MiB (11.0 MiB/s) with 1 file(s) remaining  
Completed 11.8 MiB/65.0 MiB (11.2 MiB/s) with 1 file(s) remaining  
Completed 12.0 MiB/65.0 MiB (11.4 MiB/s) with 1 file(s) remaining  
Completed 12.2 MiB/65.0 MiB (11.6 MiB/s) with 1 file(s) remaining  
Completed 12.5 MiB/65.0 MiB (11.8 MiB/s) with 1 file(s) remaining  
Completed 12.8 MiB/65.0 MiB (12.0 MiB/s) with 1 file(s) remaining  
Completed 13.0 MiB/65.0 MiB (12.2 MiB/s) with 1 file(s) remaining  
Completed 13.2 MiB/65.0 MiB (12.4 MiB/s) with 1 file(s) remaining  
Completed 13.5 MiB/65.0 MiB (12.6 MiB/s) with 1 file(s) remaining  
Completed 13.8 MiB/65.0 MiB (12.8 MiB/s) with 1 file(s) remaining  
Completed 14.0 MiB/65.0 MiB (13.0 MiB/s) with 1 file(s) remaining  
Completed 14.2 MiB/65.0 MiB (13.1 MiB/s) with 1 file(s) remaining  
Completed 14.5 MiB/65.0 MiB (13.3 MiB/s) with 1 file(s) remaining  
Completed 14.8 MiB/65.0 MiB (13.4 MiB/s) with 1 file(s) remaining  
Completed 15.0 MiB/65.0 MiB (13.6 MiB/s) with 1 file(s) remaining  
Completed 15.2 MiB/65.0 MiB (13.8 MiB/s) with 1 file(s) remaining  
Completed 15.5 MiB/65.0 MiB (14.0 MiB/s) with 1 file(s) remaining  
Completed 15.8 MiB/65.0 MiB (14.2 MiB/s) with 1 file(s) remaining  
Completed 16.0 MiB/65.0 MiB (14.4 MiB/s) with 1 file(s) remaining  
Completed 16.2 MiB/65.0 MiB (14.6 MiB/s) with 1 file(s) remaining  
Completed 16.5 MiB/65.0 MiB (14.8 MiB/s) with 1 file(s) remaining  
Completed 16.8 MiB/65.0 MiB (14.9 MiB/s) with 1 file(s) remaining  
Completed 17.0 MiB/65.0 MiB (15.1 MiB/s) with 1 file(s) remaining  
Completed 17.2 MiB/65.0 MiB (15.1 MiB/s) with 1 file(s) remaining  
Completed 17.5 MiB/65.0 MiB (15.2 MiB/s) with 1 file(s) remaining  
Completed 17.8 MiB/65.0 MiB (15.3 MiB/s) with 1 file(s) remaining  
Completed 18.0 MiB/65.0 MiB (15.4 MiB/s) with 1 file(s) remaining  
Completed 18.2 MiB/65.0 MiB (15.6 MiB/s) with 1 file(s) remaining  
Completed 18.5 MiB/65.0 MiB (15.7 MiB/s) with 1 file(s) remaining  
Completed 18.8 MiB/65.0 MiB (15.9 MiB/s) with 1 file(s) remaining  
Completed 19.0 MiB/65.0 MiB (16.1 MiB/s) with 1 file(s) remaining  
Completed 19.2 MiB/65.0 MiB (16.2 MiB/s) with 1 file(s) remaining  
Completed 19.5 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining  
Completed 19.8 MiB/65.0 MiB (16.2 MiB/s) with 1 file(s) remaining  
Completed 20.0 MiB/65.0 MiB (16.4 MiB/s) with 1 file(s) remaining  
Completed 20.2 MiB/65.0 MiB (16.5 MiB/s) with 1 file(s) remaining  
Completed 20.5 MiB/65.0 MiB (16.7 MiB/s) with 1 file(s) remaining  
Completed 20.8 MiB/65.0 MiB (16.9 MiB/s) with 1 file(s) remaining  
Completed 21.0 MiB/65.0 MiB (17.0 MiB/s) with 1 file(s) remaining  
Completed 21.2 MiB/65.0 MiB (17.2 MiB/s) with 1 file(s) remaining  
Completed 21.5 MiB/65.0 MiB (17.4 MiB/s) with 1 file(s) remaining  
Completed 21.8 MiB/65.0 MiB (17.6 MiB/s) with 1 file(s) remaining  
Completed 22.0 MiB/65.0 MiB (17.7 MiB/s) with 1 file(s) remaining  
Completed 22.2 MiB/65.0 MiB (17.9 MiB/s) with 1 file(s) remaining  
Completed 22.5 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining  
Completed 22.8 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining  
Completed 23.0 MiB/65.0 MiB (18.4 MiB/s) with 1 file(s) remaining  
Completed 23.2 MiB/65.0 MiB (18.6 MiB/s) with 1 file(s) remaining  
Completed 23.5 MiB/65.0 MiB (18.8 MiB/s) with 1 file(s) remaining  
Completed 23.8 MiB/65.0 MiB (19.0 MiB/s) with 1 file(s) remaining  
Completed 24.0 MiB/65.0 MiB (19.1 MiB/s) with 1 file(s) remaining  
Completed 24.2 MiB/65.0 MiB (19.3 MiB/s) with 1 file(s) remaining  
Completed 24.5 MiB/65.0 MiB (19.5 MiB/s) with 1 file(s) remaining  
Completed 24.8 MiB/65.0 MiB (19.6 MiB/s) with 1 file(s) remaining  
Completed 25.0 MiB/65 [...]

2018-10-18 06:27 UTC, Praveenrajmani commented
Hey @leitzler.. Can you fix the travis failures also? The `make test GOFLAGS="-race"` will fail here because of a golint bug. This is already fixed in the master. You can do a `git rebase -i master` and then squash/fixup the commits to a single commit

2018-10-18 06:47 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :x: [more...](#624449e4-fc20-4122-bcbf-03b38ac1b716) |
| mint-xl.sh | :x: [more...](#9f11d5fe-4b69-44b2-85a9-49058d443c56) |
| mint-gateway-nas.sh | :x: [more...](#f80b31d3-6bb7-4c0c-aed6-3efc939714ed) |
| mint-large-bucket.sh | :x: [more...](#0b61e7cd-e374-441d-b68b-903c2887714e) |
| mint-worm.sh | :x: [more...](#536b845e-248e-44a6-9912-3b704bfad2b3) |
| mint-fs.sh | :x: [more...](#0698f42c-4c23-4f13-9521-dce6344bfaab) |
| mint-dist-xl.sh | :x: [more...](#d817997e-fcc3-4b83-8c72-697f53f0da11) |
<a name="624449e4-fc20-4122-bcbf-03b38ac1b716"></a>
### 6651-076f26f/mint-tls.sh.log:
```
Running with
SERVER_ENDPOINT:      192.168.39.64:9000
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         1
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d57466f21ae8:/mint/log /tmp/mint-logs'
(1/7) Running aws-sdk-go tests ... done in 0 seconds
(2/7) Running aws-sdk-java tests ... FAILED in 11 seconds
{
  "name": "aws-sdk-java",
  "function": "copyObject(String bucketName, String objectName, SSECustomerKey sseKey, String destBucketName, String dstObjectName, SSECustomerKey sseKey2, boolean replaceDirective)",
  "args": "bucketName: aws-java-sdk-test-173v6ci, objectName: testobject, SSECustomerKey: com.amazonaws.services.s3.model.SSECustomerKey@5a56cdacDstbucketName: aws-java-sdk-test-173v6ci, DstObjectName: dir/newobject, SSECustomerKey: com.amazonaws.services.s3.model.SSECustomerKey@537f60bf, replaceDirective: false",
  "duration": 1013,
  "status": "FAIL",
  "error": "com.amazonaws.services.s3.model.AmazonS3Exception: Argument partNumberMarker must be an integer. (Service: Amazon S3; Status Code: 400; Error Code: InvalidArgument; Request ID: 155EA0C40CDA374C; S3 Extended Request ID: 3L137), S3 Extended Request ID: 3L137 >>> [com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1630), com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1302), com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056), com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743), com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717), com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699), com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667), com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649), com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513), com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4330), com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4277), com.amazonaws.services.s3.AmazonS3Client.completeMultipartUpload(AmazonS3Client.java:3066), io.minio.awssdk.tests.S3TestUtils.uploadMultipartObject(Unknown Source), io.minio.awssdk.tests.FunctionalTests.copyObjectEncryption_test3(Unknown Source), io.minio.awssdk.tests.FunctionalTests.runTests(Unknown Source), io.minio.awssdk.tests.FunctionalTests.main(Unknown Source)]"
}

Executed 1 out of 7 tests successfully.
```
<a name="f80b31d3-6bb7-4c0c-aed6-3efc939714ed"></a>
### 6651-076f26f/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31072
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 241e59182906:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 33 seconds
{"name": "awscli", "duration": 6624, "function": "aws --endpoint-url http://minikube:31072 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-31927/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (794.2 KiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (1.5 MiB/s) with 1 file(s) remaining  
Completed 768.0 KiB/65.0 MiB (2.1 MiB/s) with 1 file(s) remaining  
Completed 1.0 MiB/65.0 MiB (2.5 MiB/s) with 1 file(s) remaining    
Completed 1.2 MiB/65.0 MiB (1.0 MiB/s) with 1 file(s) remaining    
Completed 1.5 MiB/65.0 MiB (1.2 MiB/s) with 1 file(s) remaining    
Completed 1.8 MiB/65.0 MiB (1.4 MiB/s) with 1 file(s) remaining    
Completed 2.0 MiB/65.0 MiB (1.5 MiB/s) with 1 file(s) remaining    
Completed 2.2 MiB/65.0 MiB (1.7 MiB/s) with 1 file(s) remaining    
Completed 2.5 MiB/65.0 MiB (1.9 MiB/s) with 1 file(s) remaining    
Completed 2.8 MiB/65.0 MiB (2.1 MiB/s) with 1 file(s) remaining    
Completed 3.0 MiB/65.0 MiB (2.3 MiB/s) with 1 file(s) remaining    
Completed 3.2 MiB/65.0 MiB (2.5 MiB/s) with 1 file(s) remaining    
Completed 3.5 MiB/65.0 MiB (2.6 MiB/s) with 1 file(s) remaining    
Completed 3.8 MiB/65.0 MiB (2.8 MiB/s) with 1 file(s) remaining    
Completed 4.0 MiB/65.0 MiB (3.0 MiB/s) with 1 file(s) remaining    
Completed 4.2 MiB/65.0 MiB (3.1 MiB/s) with 1 file(s) remaining    
Completed 4.5 MiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining    
Completed 4.8 MiB/65.0 MiB (3.5 MiB/s) with 1 file(s) remaining    
Completed 5.0 MiB/65.0 MiB (3.6 MiB/s) with 1 file(s) remaining    
Completed 5.2 MiB/65.0 MiB (3.8 MiB/s) with 1 file(s) remaining    
Completed 5.5 MiB/65.0 MiB (4.0 MiB/s) with 1 file(s) remaining    
Completed 5.8 MiB/65.0 MiB (4.1 MiB/s) with 1 file(s) remaining    
Completed 6.0 MiB/65.0 MiB (4.3 MiB/s) with 1 file(s) remaining    
Completed 6.2 MiB/65.0 MiB (4.4 MiB/s) with 1 file(s) remaining    
Completed 6.5 MiB/65.0 MiB (4.6 MiB/s) with 1 file(s) remaining    
Completed 6.8 MiB/65.0 MiB (4.8 MiB/s) with 1 file(s) remaining    
Completed 7.0 MiB/65.0 MiB (4.9 MiB/s) with 1 file(s) remaining    
Completed 7.2 MiB/65.0 MiB (5.0 MiB/s) with 1 file(s) remaining    
Completed 7.5 MiB/65.0 MiB (5.0 MiB/s) with 1 file(s) remaining    
Completed 7.8 MiB/65.0 MiB (5.2 MiB/s) with 1 file(s) remaining    
Completed 8.0 MiB/65.0 MiB (5.3 MiB/s) with 1 file(s) remaining    
Completed 8.2 MiB/65.0 MiB (5.4 MiB/s) with 1 file(s) remaining    
Completed 8.5 MiB/65.0 MiB (5.5 MiB/s) with 1 file(s) remaining    
Completed 8.8 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining    
Completed 9.0 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining    
Completed 9.2 MiB/65.0 MiB (5.7 MiB/s) with 1 file(s) remaining    
Completed 9.5 MiB/65.0 MiB (5.8 MiB/s) with 1 file(s) remaining    
Completed 9.8 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining    
Completed 10.0 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining   
Completed 10.2 MiB/65.0 MiB (6.1 MiB/s) with 1 file(s) remaining   
Completed 10.5 MiB/65.0 MiB (6.3 MiB/s) with 1 file(s) remaining   
Completed 10.8 MiB/65.0 MiB (6.4 MiB/s) with 1 file(s) remaining   
Completed 11.0 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining   
Completed 11.2 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining   
Completed 11.5 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining   
Completed 11.8 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining   
Completed 12.0 MiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining   
Completed 12.2 MiB/65.0 MiB (7.0 MiB/s) with 1 file(s) remaining   
Completed 12.5 MiB/65.0 MiB (7.1 MiB/s) with 1 file(s) remaining   
Completed 12.8 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining   
Completed 13.0 MiB/65.0 MiB (7.3 MiB/s) with 1 file(s) remaining   
Completed 13.2 MiB/65.0 MiB (7.5 MiB/s) with 1 file(s) remaining   
Completed 13.5 MiB/65.0 MiB (7.5 MiB/s) with 1 file(s) remaining   
Completed 13.8 MiB/65.0 MiB (7.7 MiB/s) with 1 file(s) remaining   
Completed 14.0 MiB/65.0 MiB (7.8 MiB/s) with 1 file(s) remaining   
Completed 14.2 MiB/65.0 MiB (7.9 MiB/s) with 1 file(s) remaining   
Completed 14.5 MiB/65.0 MiB (8.0 MiB/s) with 1 file(s) remaining   
Completed 14.8 MiB/65.0 MiB (8.2 MiB/ [...]

2018-10-18 07:33 UTC, leitzler commented
@Praveenrajmani don't think it was the lint error, I accidentally made "part number marker" required so lots of tests failed. Should be fixed now!

2018-10-18 07:40 UTC, Praveenrajmani commented
> @Praveenrajmani don't think it was the lint error, I accidentally made "part number marker" required so lots of tests failed. Should be fixed now!

Yes there was also a golint error prevailing. Which was an old error in master and is fixed now.

2018-10-18 08:10 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-10-18 08:31 UTC, Praveenrajmani reviewed
Just a small comment here .. The commits can be squashed/fixed up to a single commit log. By `git rebase -i HEAD~6` or `git rebase -i master`. Everything else LGTM

2018-10-18 08:35 UTC, leitzler commented
Would it make any difference to if you select "Squash and merge" when you merge the PR?

2018-10-18 08:40 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-10-18 09:41 UTC, Praveenrajmani commented
> Would it make any difference to if you select "Squash and merge" when you merge the PR?

We can either squash it and do `git commit --amend` or fixup the commits to a single commit while rebasing.

2018-10-18 09:46 UTC, leitzler commented
> We can either squash it and do git commit --amend or fixup the commits to a single commit while rebasing.

I'm not sure I follow, I'm talking about the "Merge pull request" button in Github where you can select "Squash and merge" instead of just merge. Then all my commits will be squashed into a single one when you merge it to master.

2018-10-18 09:55 UTC, Praveenrajmani commented
> > We can either squash it and do git commit --amend or fixup the commits to a single commit while rebasing.
> 
> I'm not sure I follow, I'm talking about the "Merge pull request" button in Github where you can select "Squash and merge" instead of just merge. Then all my commits will be squashed into a single one when you merge it to master.

Yes that makes no difference. But i think it is better by having it this way, so that the contributor can have his own customized log message (feature specific) rather changing it. But this is fine.. LGTM

2018-10-18 09:56 UTC, Praveenrajmani approved these changes
LGTM

2018-10-18 09:59 UTC, leitzler commented
:+1: Will keep it in mind for the next PR :)

2018-10-18 14:21 UTC, kannappanr approved these changes

2018-10-18 14:31 UTC, merged