Fix multi-user doc typo
minio/minio pull request #6662
Opened 2018-10-18 01:24 UTC by harshavardhana

## Description
Fix multi-user doc typo

## Motivation and Context
Fixes a typo

## Regression
No

## How Has This Been Tested?
Fixes typo in the doc and improve upon existing one a bit. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-10-18 05:38 UTC, poornas requested changes

2018-10-18 05:38 UTC, poornas commented on docs/multi-user/README.md
> +Use [`mc admin policies`](https://docs.minio.io/docs/minio-admin-complete-guide.html#policies) to create canned policies. This policy enables users to download all objects under `my-bucketname`.
> This policy enables users to download all objects under `my-bucketname`.

This line seems out of place here.

2018-10-18 05:45 UTC, harshavardhana commented on docs/multi-user/README.md
> +Use [`mc admin policies`](https://docs.minio.io/docs/minio-admin-complete-guide.html#policies) to create canned policies. This policy enables users to download all objects under `my-bucketname`.
fixed

2018-10-18 05:53 UTC, poornas commented on docs/multi-user/README.md
> +mc admin user policy myminio newuser putonly
user -> users

2018-10-18 06:12 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#1145d77a-48fb-4e21-bdc9-d2778373ad80) |
<a name="1145d77a-48fb-4e21-bdc9-d2778373ad80"></a>
### 6662-fa11295/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30726
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 19d5398b7d60:/mint/log /tmp/mint-logs'
(1/13) Running awscli tests ... FAILED in 25 seconds
{
  "name": "awscli",
  "duration": 12121,
  "function": "aws --endpoint-url http://minikube:30726 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-8202/datafile-65-MB\n",
  "status": "FAIL",
  "error": "upload failed: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-8202/datafile-65-MB An error occurred (XMinioServerNotInitialized) when calling the CreateMultipartUpload operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```

2018-10-18 07:40 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-10-19 05:01 UTC, nitisht requested changes

2018-10-19 05:01 UTC, nitisht commented on docs/multi-user/README.md
> +This document explains how to add, disable users. Multi-user as name implies means Minio supports long term users other than default credentials, each of these users can be configured to deny or allo
```suggestion
Minio supports multiple long term users in addition to default user created during server startup. New users can be added after server starts up, and server can be configured to deny or allow access to buckets and resources to each of these users. This document explains how to add/remove users and modify their access rights.

```

2018-10-19 06:31 UTC, harshavardhana commented
Ping @nitisht @poornas

2018-10-19 06:33 UTC, nitisht approved these changes

2018-10-19 06:39 UTC, poornas approved these changes

2018-10-19 07:00 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-10-19 07:05 UTC, merged