Update KMS readme with vault quick start guide
minio/minio pull request #6747
Opened 2018-11-01 17:12 UTC by poornas

## Description

Adding a quick start guide to configure Vault for use as KMS with minio server
## Motivation and Context

Helps guide new users
## Regression
 No

## How Has This Been Tested?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-11-01 17:43 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-11-01 18:31 UTC, harshavardhana commented
We don't need a separate vault quick start guide, we should simply add it in the same documentation in the prerequisite section.

2018-11-01 19:22 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-11-01 21:01 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-11-01 21:37 UTC, eco-minio commented on docs/kms/README.md
>  You'll need the Vault endpoint, AppRole ID, AppRole SecretID, encryption key-ring name before starting Minio server with Vault as KMS
Should provide sample snippet with output that users can verify things are successfully working

2018-11-01 21:37 UTC, eco-minio commented on docs/kms/README.md
> +Note that this is insecure and stores all its data in memory,and not meant for production
Should clarify that running in -dev mode is what is insecure

2018-11-01 21:37 UTC, eco-minio commented on docs/kms/README.md
>  - AppRole based authentication with read/update policy for transit backend. In particular, read and update policy
Should include reference to Vault docs regarding transit

2018-11-01 21:37 UTC, eco-minio commented on docs/kms/README.md
> +vault policy write minio-policy ~/code/src/github.com/minio/vaultpolicy.hcl  #define a policy for AppRole to access transit path
Should amend to a shorter path to the sample file (from the heredoc it implies `pwd`?)

2018-11-01 21:37 UTC, eco-minio commented on docs/kms/README.md
> +vault write auth/approle/role/my-role token_num_uses=0  secret_id_num_uses=0  period=60s # period indicates it is renewable if tok renewed before the period is over
"...if token is renewed..."

2018-11-01 21:37 UTC, eco-minio commented on docs/kms/README.md
>  You'll need the Vault endpoint, AppRole ID, AppRole SecretID, encryption key-ring name before starting Minio server with Vault as KMS
"...AppRole ID, AppRole SecretID and encryption key-ring name..."

2018-11-01 22:57 UTC, ebozduman submitted a review, later dismissed

2018-11-01 22:57 UTC, ebozduman commented on docs/kms/README.md
> +Here is a sample quick start to configuring vault with a transit backend and Approle with correct policy
`start to configuring vault` => `start for configuring vault`
IMHO

2018-11-02 18:07 UTC, poornas commented
@eco-minio  && @ebozduman - updated PR.

2018-11-02 18:38 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-11-02 19:45 UTC, eco-minio requested changes
>objects.This document explains how to configure Minio with Vault as KMS.
objects. This document explains how to configure Minio with Vault as KMS.

2018-11-02 20:49 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-11-02 23:48 UTC, poornas commented
@ebozduman , addressed your feedback

2018-11-03 01:21 UTC, ebozduman requested changes

2018-11-03 01:21 UTC, ebozduman commented on docs/kms/README.md
> +  are required for the Generate Data Key](https://www.vaultproject.io/api/secret/transit/index.html#generate-data-key) endpoint and [Decrypt Data](https://www.vaultproject.io/api/secret/transit/index
Missing `[` in `...for the Generate Data Key](...`

2018-11-03 01:31 UTC, poornas commented on docs/kms/README.md
> +  are required for the Generate Data Key](https://www.vaultproject.io/api/secret/transit/index.html#generate-data-key) endpoint and [Decrypt Data](https://www.vaultproject.io/api/secret/transit/index
thanks,fixed.

2018-11-03 02:38 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-11-05 07:14 UTC, ebozduman approved these changes
LGTM

2018-11-05 07:22 UTC, ebozduman commented
I noticed there is travis failure after giving my LGTM.
I don't think the failure is related to this PR, but it is about:
```
--- FAIL: TestAPICopyObjectPartHandler (1.73s)
	object-handlers_test.go:1767: Test 1: FS: Expected the response status to be `200`, but instead found `500`
```

2018-11-05 20:45 UTC, poornas commented
@ebozduman , travis passed on restart

2018-11-05 20:48 UTC, eco-minio approved these changes
LGTM

2018-11-05 21:01 UTC, merged