Update to Distributed Minio Quickstart Guide
minio/minio pull request #6842
Opened 2018-11-20 21:51 UTC by jamesneimanconsulting

This is a complete copy edit of the guide.

- [X ] I have updated the documentation accordingly.

2018-11-20 22:11 UTC, deekoder commented
Needs erasure coded guide to be merged first.

2018-11-26 21:00 UTC, eco-minio requested changes

2018-11-26 21:00 UTC, eco-minio commented on docs/distributed/README.md
> +When running Minio in distributed mode (_distributed Minio_), multiple drives from different machines can be pooled into a single object storage server. As drives are distributed across several nodes
"into a single storage server" might be confusing for some users, maybe single namespace is better here? @deekoder

2018-11-26 21:00 UTC, eco-minio commented on docs/distributed/README.md
> +Running Minio in distributed mode allows for the deployment of a high-availability, object storage system, enabling optimal use of storage devices regardless of their location on a network.
"regardless of their location on a network" needs to be said in such a way that it implies that each cluster should reside in the same network (but multiple clusters from multiple networks can be federated).

2018-11-26 21:00 UTC, eco-minio commented on docs/distributed/README.md
> +A standalone server running Minio Server will go down if the hard drives go offline. In contrast, a distributed Minio configuration with N disks will keep data safe as long as N/2 or more hard drives
Did we finalize on whether to capitalize server?

2018-11-26 21:00 UTC, eco-minio commented on docs/distributed/README.md
> +As with Minio running in standalone mode, distributed Minio supports 2-32 servers per tenant. There are no limits on the number of hard drives shared across these servers. For a multi-tenant configur
This sentence is confusing as it implies that standalone uses more than one server.  Should also note that Minio itself does not impose limits on the number of hard drives.

2018-11-26 21:00 UTC, eco-minio commented on docs/distributed/README.md
> +**Note:** With distributed Minio, the number of nodes and hard drives can be adjusted within the limits. For example, a configuration can have 2 nodes with 4 hard drives each, 4 nodes with 4 hard dri
Need to replace adjusted, it implies a cluster can have nodes added and removed.

2018-11-26 21:00 UTC, eco-minio commented on docs/distributed/README.md
> +**Note:** The drives can be shared with other applications if required.
"The drives can be shared with other applications" - This isn't clear, we should either point to a way to do this or remove it as it is too ambiguous.  @deekoder thoughts?

2018-11-26 21:00 UTC, eco-minio commented on docs/distributed/README.md
> +To test this configuration, access the Minio server via a browser or invoke it as described in the [Minio Client Quickstart Guide](https://docs.minio.io/docs/minio-client-quickstart-guide).
Do we need to mention how to check the browser?  Since we don't give an example of server startup output new users might not know how

2018-11-28 23:44 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#fe21cf72-3c0e-43e9-b578-79b42f249875) |
| mint-xl.sh | :x: [more...](#6043f5d6-cf75-46bd-a682-945422de1101) |
| mint-large-bucket.sh | :x: [more...](#c1ea881a-3edc-4ea4-b9ed-fbd81261ba14) |
| mint-dist-xl.sh | :x: [more...](#f87c67da-8ea6-413a-b5cc-71049dd9751a) |
<a name="f87c67da-8ea6-413a-b5cc-71049dd9751a"></a>
### 6842-b8c84ff/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30479
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f94d43a5812:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 35 seconds
{
  "name": "awscli",
  "duration": 17573,
  "function": "aws --endpoint-url http://minikube:30479 s3api get-object --bucket awscli-mint-test-bucket-3672 --key awscli-mint-test-bucket-3672-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="c1ea881a-3edc-4ea4-b9ed-fbd81261ba14"></a>
### 6842-b8c84ff/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30614
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4db25c8c409b:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 36 seconds
{
  "name": "awscli",
  "duration": 15588,
  "function": "aws --endpoint-url http://minikube:30614 s3api get-object --bucket awscli-mint-test-bucket-19773 --key awscli-mint-test-bucket-19773-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="6043f5d6-cf75-46bd-a682-945422de1101"></a>
### 6842-b8c84ff/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32418
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ae3130b6641e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 19 seconds
{
  "name": "awscli",
  "duration": 28497,
  "function": "aws --endpoint-url http://minikube:32418 s3api get-object --bucket awscli-mint-test-bucket-2594 --key awscli-mint-test-bucket-2594-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="fe21cf72-3c0e-43e9-b578-79b42f249875"></a>
### 6842-b8c84ff/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30435
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fb6601434cad:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 20 seconds
{
  "name": "awscli",
  "duration": 29799,
  "function": "aws --endpoint-url http://minikube:30435 s3api get-object --bucket awscli-mint-test-bucket-30469 --key awscli-mint-test-bucket-30469-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```

2018-11-30 10:16 UTC, nitisht commented on docs/distributed/README.md
> +A standalone server running Minio Server will go down if the hard drives go offline. In contrast, a distributed Minio configuration with N disks will keep data safe as long as N/2 or more hard drives
> N disks will keep data safe as long as N/2 or more hard drives are online

We can finalise on one of `disk` or `drive` and use that uniformly. I think `drive` is better as it refers the whole spectrum from HDDs to NVMes

2018-11-30 10:16 UTC, nitisht commented on docs/distributed/README.md
> +Running Minio in distributed mode allows for the deployment of a high-availability, object storage system, enabling optimal use of storage devices regardless of their location on a network.
> deployment of a high-availability

IMO we can call it as `deployment of a highly-available`

2018-11-30 10:16 UTC, nitisht commented on docs/distributed/README.md
> +**Note:** Each cluster must reside in the same network, but multiple clusters from multiple networks can be federated.
We can probably link to the federation guide here https://docs.minio.io/docs/minio-federation-quickstart-guide.html

2018-11-30 10:16 UTC, nitisht commented on docs/distributed/README.md
> +For example, an 8-node distributed Minio configuration with one hard drive per node will continue serving files even if as many as 4 hard drives are offline. This configuration requires at least 5 ha
> with one hard drive

Should be `with one drive` . As we recommend fast NVMe / flash / SSDs, using the term hard drive is not a good idea in this document

2018-11-30 10:16 UTC, nitisht commented on docs/distributed/README.md
> +Distributed Minio supports 2-32 servers per tenant. There are no limits on the number of hard drives shared across these servers and nor does Minio impose a limit to the number of hard drives used. F
Suggest rewording to something like this

`Distributed Minio requires at least 2 nodes and supports upto 32 nodes. There are no limits on the number of drives on each server, but total number of drives in the deployment should be even. For a multi-tenant configuration, orchestrate multiple Minio instances using a tool like Kubernetes.`

2018-11-30 10:16 UTC, nitisht commented on docs/distributed/README.md
> +**Note:** The of number of nodes in a Distributed Minio configuration must be within the limits. For example, a configuration can have 2 nodes with 4 hard drives each, 4 nodes with 4 hard drives each
> The of number of nodes

Change to `The number of nodes`

2018-11-30 21:40 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#1d27f2b7-b2a9-4fd3-bce8-400f3b17357f) |
| mint-xl.sh | :x: [more...](#e86f6310-36f6-441d-9576-4b3da7243665) |
| mint-large-bucket.sh | :x: [more...](#9d6589e1-9a21-4f82-9b7a-6b994ae09693) |
| mint-dist-xl.sh | :x: [more...](#6e86a091-fcf4-464c-acbb-b6639781f3aa) |
<a name="1d27f2b7-b2a9-4fd3-bce8-400f3b17357f"></a>
### 6842-62d86f9/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30848
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9a8b14de717d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 20 seconds
{
  "name": "awscli",
  "duration": 28487,
  "function": "aws --endpoint-url http://minikube:30848 s3api get-object --bucket awscli-mint-test-bucket-26007 --key awscli-mint-test-bucket-26007-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="6e86a091-fcf4-464c-acbb-b6639781f3aa"></a>
### 6842-62d86f9/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32165
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 785b7d819b8d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 32 seconds
{
  "name": "awscli",
  "duration": 15412,
  "function": "aws --endpoint-url http://minikube:32165 s3api get-object --bucket awscli-mint-test-bucket-25257 --key awscli-mint-test-bucket-25257-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="9d6589e1-9a21-4f82-9b7a-6b994ae09693"></a>
### 6842-62d86f9/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:30122
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e5a51b370805:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 38 seconds
{
  "name": "awscli",
  "duration": 16676,
  "function": "aws --endpoint-url http://minikube:30122 s3api get-object --bucket awscli-mint-test-bucket-2727 --key awscli-mint-test-bucket-2727-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="e86f6310-36f6-441d-9576-4b3da7243665"></a>
### 6842-62d86f9/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31851
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bdf0f7c23e08:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "awscli",
  "duration": 25778,
  "function": "aws --endpoint-url http://minikube:31851 s3api get-object --bucket awscli-mint-test-bucket-30835 --key awscli-mint-test-bucket-30835-object /tmp/datafile-0-b\n",
  "status": "FAIL",
  "error": "An error occurred (InternalError) when calling the GetObject operation (reached max retries: 4): We encountered an internal error, please try again."
}

Executed 0 out of 13 tests successfully.
```

2018-12-01 11:03 UTC, nitisht approved these changes

2018-12-04 23:22 UTC, eco-minio commented on docs/distributed/README.md
> +When running Minio in distributed mode (_distributed Minio_), multiple drives from different machines can be pooled into a single object storage server. As drives are distributed across several nodes
Per conversation with @deekoder this is fine

2018-12-04 23:45 UTC, eco-minio commented on docs/distributed/README.md
> +Run the following command on all eight nodes:
@belvid will change the graphic from 11 - 18 to 1 - 8

2018-12-17 20:20 UTC, merged