Fix CloudBerry rename object failed
minio/minio pull request #6850
Opened 2018-11-22 06:18 UTC by ssuio

CloudBerry rename object does PUT request and query acl key. Server  responses not implement causing rename failed.

1. Make acl query pass through dummy api.
2. Create putObject/Bucket dummy api.

## Description
CloudBerry rename object does PUT request in the last step.
1. Add put method when generic-handler checking queries with acl key.
2. Create putObject/Bucket dummy api.

## Motivation and Context
Cloud berry explorer show failed when renaming objects(Actually it did rename). But server still return "Not implement" response.

## Regression
 No

## How Has This Been Tested?
Rename an object by Cloud berry explorer. And make sure no failed msg popup.

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x ] All new and existing tests passed.

2018-11-22 06:20 UTC, nitisht commented
Thanks for the PR @ssuio

2018-11-22 08:05 UTC, harshavardhana commented
We are not going to implement PUT dummy handlers they do not make sense. We only did that for GET because we can return back default value. We cannot do that with PUT since it's a mutation of server state. Faking a PUT operation is hacky and doesn't serve any purpose.

CBB should handle this either on client or you should use Minio specific connector - https://www.cloudberrylab.com/resources/blog/support-for-minio-in-cloudberry-backup-5-6/

2018-11-22 10:52 UTC, harshavardhana requested changes
:-1: we shouldn't do this

2018-11-23 02:22 UTC, ssuio commented
Got it. But I am using Cloud berry explorer, not backup one. And I think rename is a basic operation.
I tested Openstack swift and Amazon S3, they both can rename successfully. What changing should I do to make Minio support it too ?

2018-11-23 06:41 UTC, harshavardhana commented
So here is our take - ACL is legacy functionality and we are not planning to implement it. ACLs are tricky and buggy to implement in S3 API. Amazon S3 recommends apps to move to bucket policies instead. So we implement this instead.

In this situation i would suggest that Cloud Berry explorer should migrate from legacy implementation. Implementing in the manner in this PR will not be acceptable since it is not a proper implementation.

2018-11-23 08:11 UTC, ssuio commented
Thanks for the reply.

2018-11-23 08:11 UTC, closed without merging