Fix gateway crash when using certain object stores
minio/minio pull request #6879
Opened 2018-11-28 02:58 UTC by richardkiene

## Description
This commit replaces `nil` with `context.Background()` when deleting objects via the Gateway WebUI. The Gateway WebUI crashes with object stores like Manta which were written to expect a context to be passed in.

## Motivation and Context
This fixes a crash when deleting objects with certain gateway object stores through the WebUI

## Regression
Is this PR fixing a regression? **Yes**
I believe it was introduced in the following commit https://github.com/minio/minio/commit/e452377b247ca5f9155e780f4b9aac45266d3ea7#diff-a332614ad2487d48ea82260329c81b9a

## How Has This Been Tested?
I've loaded up the gateway, uploaded a file, and deleted a file. I'm using MacOS and Go 1.11.2

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2018-11-28 03:31 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-11-28 17:23 UTC, richardkiene commented
FWIW it appears that the travis-ci check failed only on Windows because of completely unrelated tests/code.

2018-11-28 20:30 UTC, kannappanr commented
The fix needs to be added in Line 518 also, https://github.com/minio/minio/pull/6879/files#diff-a332614ad2487d48ea82260329c81b9aL518

2018-11-29 19:13 UTC, harshavardhana requested changes
As suggested by @kannappanr needs to be fixed at line 518 as well

2018-12-19 21:56 UTC, harshavardhana commented
This is fixed in #6891 - closing this PR here as not needed.

2018-12-19 21:56 UTC, closed without merging

2018-12-31 19:05 UTC, richardkiene commented
@harshavardhana Thank you, and sorry about the delay on this PR. I was hospitalized for a bit and didn't have access to a computer. I imagine it looked like I abandoned this, sorry about that.

2018-12-31 19:08 UTC, harshavardhana commented
> @harshavardhana Thank you, and sorry about the delay on this PR. I was hospitalized for a bit and didn't have access to a computer. I imagine it looked like I abandoned this, sorry about that.

No problem, hope you are okay right now. Feel free to send new PRs our way happy to accept. Happy New Year!