Update to Minio GCS Gateway
minio/minio pull request #6887
Opened 2018-11-28 23:27 UTC by jamesneimanconsulting

Initial edits

- [X] I have updated the documentation accordingly.

2018-11-29 00:19 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-11-29 00:54 UTC, poornas requested changes

2018-11-29 00:54 UTC, poornas commented on docs/gateway/gcs.md
> +This topic describes how to use Minio GCS Gateway to add Amazon S3 compatibility to Google Cloud Storage (GCS).
```Minio GCS Gateway allows you to access Google Cloud Storage (GCS) with Amazon S3 compatible APIs``` seems better

2018-11-29 22:29 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-12-05 19:20 UTC, eco-minio approved these changes
LGTM

2018-12-05 19:33 UTC, poornas approved these changes

2018-12-06 18:09 UTC, merged