Update to Minio NAS Gateway
minio/minio pull request #6892
Opened 2018-11-29 18:46 UTC by jamesneimanconsulting

Initial edit

- [X] I have updated the documentation accordingly.

2018-11-29 19:50 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-12-05 19:37 UTC, poornas requested changes

2018-12-05 19:37 UTC, poornas commented on docs/gateway/nas.md
> +Use the following command to list the containers on NAS:
list the containers -> list buckets

2018-12-05 19:37 UTC, poornas commented on docs/gateway/nas.md
> +This topic describes how to use Minio Gateway to add Amazon S3 compatibility to NAS storage.
topic -> guide would be better

2018-12-05 19:47 UTC, eco-minio requested changes

2018-12-05 19:47 UTC, eco-minio commented on docs/gateway/nas.md
> +This topic describes how to use Minio Gateway to add Amazon S3 compatibility to NAS storage.
Change topic to guide

2018-12-05 19:47 UTC, eco-minio commented on docs/gateway/nas.md
> +Use the following command to list the containers on NAS:
Should change containers to buckets

2018-12-17 20:15 UTC, merged