Update to Disk Caching Design
minio/minio pull request #6900
Opened 2018-11-30 21:53 UTC by jamesneimanconsulting

Initial edits. Merge before merging Disk Cache Quickstart Guide. I suggest adding the following to site.yml:

      - Disk Caching Design:
        Link: ../minio/docs/disk-caching/README.md
        Slug: minio-disk-cache-design
        Options: hidden

- [X] I have updated the documentation accordingly.

2018-11-30 22:29 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-12-05 00:49 UTC, eco-minio approved these changes
LGTM

2018-12-05 01:10 UTC, eco-minio requested changes

2018-12-05 01:10 UTC, eco-minio commented on docs/disk-caching/DESIGN.md
> +  7. Start Minio Server with edge caching enabled on '/mnt/drive1', '/mnt/drive2' and '/mnt/export1 ... /mnt/export24',
We need to copy over the mc `get / set` config per section 2 of the disk cache quickstart guide

2018-12-17 20:15 UTC, merged