Update to Disk Cache Quickstart Guide
minio/minio pull request #6901
Opened 2018-11-30 21:54 UTC by jamesneimanconsulting

Initial edits. Merge only after merging https://github.com/minio/minio/pull/6900.

- [X] I have updated the documentation accordingly.

2018-11-30 23:04 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-12-05 01:13 UTC, eco-minio requested changes

2018-12-05 01:13 UTC, eco-minio commented on docs/disk-caching/README.md
>  $ mc admin config get myminio/ > /tmp/myconfig
Should we add Windows direction as well?  Per @harshavardhana:

`mc cat C:\temp\myconfig.json | mc admin config set local_minio`

2018-12-05 01:17 UTC, eco-minio requested changes

2018-12-05 01:17 UTC, eco-minio commented on docs/disk-caching/README.md
> +This topic describes how to get started with the disk caching feature. For more information about advanced uses and limitations, see the [design document](./minio-disk-cache-design.html).
Per discussion with @deekoder we should change topic to guide

2018-12-17 20:14 UTC, merged