Updates to Large Bucket Support Design Guide
minio/minio pull request #6903
Opened 2018-11-30 21:57 UTC by jamesneimanconsulting

Initial edits. Must be approved and merged before merging https://github.com/minio/minio/pull/6902.

This should now become a topic rendered by gluegun. For that reason I recommend adding the following to the site.yml file:

      - Large Bucket Support Design Guide:
        Link: ../minio/docs/large-bucket/DESIGN.md
        Slug: minio-large-bucket-support-design-guide
        Options: hidden

- [X] I have updated the documentation accordingly.

2018-12-01 00:14 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2018-12-02 07:37 UTC, harshavardhana requested changes

2018-12-02 07:37 UTC, harshavardhana commented on docs/large-bucket/DESIGN.md
> +Large-bucket support has the following limitations:
These are not limitations but just `limits` - the word limitations signify entirely different context than `limits`.

2018-12-04 23:13 UTC, eco-minio requested changes

2018-12-04 23:13 UTC, eco-minio commented on docs/large-bucket/DESIGN.md
> +* A maximum of 32 distinct nodes are supported for distributed configurations.
Should mention max 32 nodes per cluster, would be good to reference federation here for use cases that want to utilize more than 32 nodes or to add additional clusters.

2018-12-17 20:10 UTC, merged