Fix server side copy of files with `?` in - fixes #7058
minio/minio pull request #7059
Opened 2019-01-09 12:26 UTC by ncw

## Description

Before this change the CopyObjectHandler and the CopyObjectPartHandler
both looked for a `versionId` parameter on the `X-Amz-Copy-Source` URL
for the version of the object to be copied.  According to S3
documentation the version should be found in the
`X-Amz-Copy-Source-Version-Id` field.

A consequence of this was that files with `?` in their names could not
be server side copied.

This fixes the problem by reading the version ID from the correct
header instead of the URL.

S3 Docs:
- https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectCOPY.html
- https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPartCopy.html

## Motivation and Context

See #7058 

## Regression

## How Has This Been Tested?

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-01-09 13:12 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-09 13:25 UTC, harshavardhana commented
You shouldn't remove the previous code @ncw we need to honor the legacy way of copying versionId as well which is supported by quite a few applications such as pcf backup etc https://github.com/minio/minio/issues/6935

This implementation should be in conjunction with VersionId query string and also if we cannot find VersionId query string we should honor the filenames with `?` automatically. Only special handling is required for VersionId

2019-01-09 13:39 UTC, ncw commented
> You shouldn't remove the previous code @ncw we need to honor the legacy way of copying versionId as well which is supported by quite a few applications such as pcf backup etc #6935
> 
> This implementation should be in conjunction with VersionId query string and also if we cannot find VersionId query string we should honor the filenames with `?` automatically. Only special handling is required for VersionId

Yes this form of copying is mentioned in the examples in the s3 docs....

I'll have a go at a better fix

2019-01-09 15:06 UTC, ncw commented
@harshavardhana I've updated the commit.

It could possibly be two commits now - let me know what you think.

2019-01-09 15:21 UTC, harshavardhana requested changes

2019-01-09 15:21 UTC, harshavardhana commented on cmd/object-handlers.go
> +	if err != nil {
Shouldn't this be `if err == nil`

2019-01-09 15:21 UTC, harshavardhana commented on cmd/object-handlers.go
> +	if err != nil {
Shouldn't this be `if err == nil` ?

2019-01-09 15:42 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-09 16:17 UTC, ncw commented on cmd/object-handlers.go
> +	if err != nil {
Yes - well spotted!

2019-01-09 16:17 UTC, ncw commented on cmd/object-handlers.go
> +	if err != nil {
Yes - well spotted!

2019-01-09 16:58 UTC, ncw commented
I will post a fix with some tests either later today or tomorrow :-)

2019-01-09 17:52 UTC, ncw commented
I've addressed your concerns from the review and added tests for all the new code.

PTAL!

2019-01-09 18:41 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-10 01:56 UTC, harshavardhana submitted a review, later dismissed
LGTM

2019-01-10 10:56 UTC, ncw commented
I have fixed the CI so this is ready for review/merge I think.

2019-01-10 11:15 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-10 13:53 UTC, harshavardhana approved these changes

2019-01-10 20:18 UTC, donatello approved these changes

2019-01-10 21:10 UTC, merged

2019-01-10 21:35 UTC, ncw commented
Thank you :-)