Move metadata into ObjectOptions for NewMultipart and PutObject
minio/minio pull request #7060
Opened 2019-01-09 17:13 UTC by poornas

## Description

## Motivation and Context

Consolidate metadata and encryption options into ObjectOptions, to make the api interface cleaner.
## Regression
 No

## How Has This Been Tested?

Test put and multipart calls in fs, xl and gateway modes

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-01-09 18:05 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#097bdaf1-38dd-42f8-8794-928789664bf0) |
<a name="097bdaf1-38dd-42f8-8794-928789664bf0"></a>
### 7060-3d5d49f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31535
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bc241568d05e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 43 seconds
(2/13) Running aws-sdk-go tests ... done in 0 seconds
(3/13) Running aws-sdk-java tests ... done in 8 seconds
(4/13) Running aws-sdk-php tests ... done in 43 seconds
(5/13) Running aws-sdk-ruby tests ... done in 3 seconds
(6/13) Running mc tests ... done in 29 seconds
(7/13) Running minio-dotnet tests ... FAILED in 3 minutes and 5 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (Assert.Fail failed. ) ---> Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. 
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFail(String assertionName, String message, Object[] parameters)
   at Minio.Functional.Tests.FunctionalTest.<>c.<ListIncompleteUpload_Test2>b__85_1(Exception ex) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2138
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 76
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Throw.cs:line 42
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 83
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 127
   at System.Reactive.Linq.QueryLanguage.<>c__DisplayClass330_0`1.<Create>b__0(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Creation.cs:line 46
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObservable.cs:line 37
   at System.Reactive.ObservableBase`1.ScheduledSubscribe(IScheduler _, AutoDetachObserver`1 autoDetachObserver) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 82
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 126
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 94
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 51
   at Minio.Functional.Tests.FunctionalTest.ListIncompleteUpload_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2136
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 241

Executed 6 out of 13 tests successfully.
```

2019-01-12 02:16 UTC, ebozduman requested changes

2019-01-12 02:16 UTC, ebozduman commented on cmd/gateway/s3/gateway-s3-sse.go
> +	var sseOpts encrypt.ServerSide
This function's first part can be restructured as :
```
func (l *s3EncObjects) NewMultipartUpload(ctx context.Context, bucket string, object string, o minio.ObjectOptions) (uploadID string, err error) {
	var sseOpts encrypt.ServerSide
	if o.ServerSideEncryption == nil {
		return l.s3Objects.NewMultipartUpload(ctx, bucket, object, minio.ObjectOptions{UserDefined: o.UserDefined})
	}
	// Decide if sse options needed to be passed to backend
	if (minio.GlobalGatewaySSE.SSEC() && o.ServerSideEncryption.Type() == encrypt.SSEC) ||
	   (minio.GlobalGatewaySSE.SSES3() && o.ServerSideEncryption.Type() == encrypt.S3) {
		sseOpts = o.ServerSideEncryption
	}
	uploadID, err = l.s3Objects.NewMultipartUpload(ctx, bucket, getGWContentPath(object),	minio.ObjectOptions{ServerSideEncryption: sseOpts})
	:
	:
```

2019-01-15 21:34 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-18 21:24 UTC, poornas commented
rebased - PTAL

2019-01-18 22:52 UTC, ebozduman requested changes

2019-01-18 22:52 UTC, ebozduman commented on cmd/benchmark-utils_test.go
> +	opts := ObjectOptions{UserDefined: metadata}
There is no additional benefit for this change. The effect is the same.
```
opts := ObjectOptions{}
```
 is the same with
```
metadata := make(map[string]string)
opts := ObjectOptions{UserDefined: metadata}
```

2019-01-18 22:52 UTC, ebozduman commented on cmd/benchmark-utils_test.go
> +			mustGetPutObjReader(b, bytes.NewBuffer(textData), int64(len(textData)), md5hex, sha256hex), ObjectOptions{UserDefined: metadata})
Since `metadata` information comes with `ObjectOptions`, we can clean it up and and call `mustGetPutObjReader` with empty object options, `ObjectOptions{}`, as it was in the original code.

**`Delete line#197`**~~`metadata := make(map[string]string)`~~

and modify the following line:

**`Modify line#206`**`mustGetPutObjReader(b, bytes.NewBuffer(textData), int64(len(textData)), md5hex, sha256hex),  ObjectOptions{})`

The same above comment is also valid for the following line# pairs:
292 & 307
338 & 347

2019-01-18 23:03 UTC, poornas commented on cmd/benchmark-utils_test.go
> +			mustGetPutObjReader(b, bytes.NewBuffer(textData), int64(len(textData)), md5hex, sha256hex), ObjectOptions{UserDefined: metadata})
fixed.

2019-01-19 03:17 UTC, harshavardhana commented on cmd/benchmark-utils_test.go
> +	opts := ObjectOptions{UserDefined: metadata}
No it is not @ebozduman variables in a struct don't get allocated automatically upon just `{}`

2019-01-23 00:08 UTC, ebozduman requested changes

2019-01-23 00:08 UTC, ebozduman commented on cmd/encryption-v1.go
> +		opts, err = getOpts(ctx, r, bucket, object)
what if `err` happens here ?

2019-01-23 00:11 UTC, poornas commented on cmd/encryption-v1.go
> +		opts, err = getOpts(ctx, r, bucket, object)
err is a named return

2019-01-23 01:33 UTC, ebozduman submitted a review, later dismissed
LGTM

2019-01-23 07:25 UTC, sinhaashish commented
@poornas  Can you rebase it.

2019-01-23 18:11 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-25 16:46 UTC, sinhaashish commented
LGTM

2019-01-29 22:35 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-30 19:47 UTC, ebozduman commented
@poornas,
Please check the Travis failure...

2019-01-30 20:09 UTC, poornas commented
rebased to master

2019-02-07 02:29 UTC, poornas commented
@harshavardhana ,@ebozduman and @sinhaashish , ping

2019-02-07 02:52 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#5af8b577-316a-4356-ba8d-ab89400f2b5d) |
<a name="5af8b577-316a-4356-ba8d-ab89400f2b5d"></a>
### 7060-49ee855/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30548
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 87b810584db8:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 seconds
(5/13) Running awscli tests ... FAILED in 3 seconds
{
  "name": "awscli",
  "duration": 1450,
  "function": "aws --endpoint-url http://72.28.97.60:30548 s3api head-bucket --bucket awscli-mint-test-bucket-28227\n",
  "status": "FAIL",
  "error": "awscli-mint-test-bucket-28227"
}

Executed 4 out of 13 tests successfully.
```

2019-02-07 19:20 UTC, ebozduman commented
I still see the travis failure. There must be more than one problem

2019-02-07 19:26 UTC, poornas commented
> I still see the travis failure. There must be more than one problem
basically sia gateway file was deleted from master, but not deleted during rebase

2019-02-07 19:46 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :x: [more...](#88727682-8597-4aea-be8b-0c8889bcfae1) |
<a name="88727682-8597-4aea-be8b-0c8889bcfae1"></a>
### 7060-8cb32ce/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31902
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 66f71d23c957:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-ruby",
  "function": "presignedPut(bucket_name,file_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-5e58436a2c8f",
    "file_name": "datafile-1-MB"
  },
  "duration": 26.43,
  "error": "Connection reset by peer",
  "status": "FAIL"
}

Executed 3 out of 13 tests successfully.
```

2019-02-07 21:39 UTC, ebozduman approved these changes
LGTM

2019-02-09 05:00 UTC, sinhaashish approved these changes
LGTM

2019-02-09 05:31 UTC, merged