Healing process should not heal root disk
minio/minio pull request #7089
Opened 2019-01-16 01:49 UTC by krishnasrinivas

Description
-----------

If an admin umounts a disk and runs heal, currently we endup healing a directory on the root FS. This PR ensures that when we heal, format healing is done only on non-root disks.

Motivation and Context
-------------

If we heal a directory on root disk we will end up filling up the root disk

Regression
---

No

How Has This Been Tested?
----
By using a loop mounted FS, I was able to simulate actualy disk mount to test this.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2019-01-16 01:50 UTC, harshavardhana approved these changes

2019-01-16 02:36 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-16 03:05 UTC, harshavardhana requested changes

2019-01-16 03:05 UTC, harshavardhana commented on cmd/posix.go
> +			IsRootDisk = true
Can be simplied to `IsRootDisk = diskStat.Dev == rootStat.Dev` , also variable name can be just rootDisk which has true/false

I like the idea to determine this during Heal instead of newPosix() avoids state and false positives.

2019-01-17 15:14 UTC, harshavardhana commented on cmd/posix.go
> +			IsRootDisk = true
@krishnasrinivas can you take a look

2019-01-17 19:30 UTC, harshavardhana submitted a review, later dismissed
LGTM and tested

2019-01-17 19:40 UTC, harshavardhana commented
@krishnasrinivas you need to fix windows build issues https://travis-ci.org/minio/minio/jobs/481015811

2019-01-19 11:00 UTC, harshavardhana approved these changes

2019-01-23 18:14 UTC, harshavardhana approved these changes
LGTM and tested

2019-01-23 23:29 UTC, kannappanr approved these changes
LGTM. Tested.

2019-01-23 23:29 UTC, merged