Do not do StorageInfo() and ListBuckets() for FS/Erasure in health check handler
minio/minio pull request #7090
Opened 2019-01-16 03:22 UTC by krishnasrinivas

Description
---
The problem was first observed in minio-internal-blobstore where HAProxy was calling /minio/health/live every second. Hence xlSets.StorgeInfo()
was reading format.json from all the disks every second. This can be avoided.

Health checking programs very frequently use /minio/health/live to check health,
hence we can avoid doing StorageInfo() and ListBuckets() for FS/Erasure backend.

Motivation and Context
---

health check was causing unnecessary network/cpu usage.

Regression
--
no

How Has This Been Tested?
---
using curl command on the health endpoint

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2019-01-16 03:46 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0d09cc4d-2ceb-4125-a9c2-2d7569d77a3c) |
<a name="0d09cc4d-2ceb-4125-a9c2-2d7569d77a3c"></a>
### 7090-a244618/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:31333
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 41162582369e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 3 minutes and 6 seconds
{
  "name": "awscli",
  "duration": 72039,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "remove_bucket failed: s3://awscli-mint-test-bucket-8584 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 0 out of 13 tests successfully.
```

2019-01-16 04:07 UTC, harshavardhana requested changes
Can be simplied further to use globalIsXL and globalIsDistXL instead of globalEndpoints()

2019-01-20 04:42 UTC, nitisht approved these changes
LGTM

2019-01-20 04:54 UTC, harshavardhana approved these changes

2019-01-20 04:58 UTC, merged