[Proposal] Reorder credential providers for gateway s3
minio/minio pull request #7101
Opened 2019-01-17 01:22 UTC by donatello

## Description

Reorder credential providers so that:

1. Minio env is always tried first.
2. Then AWS standard envs
3. Then AWS config file
4. And finally IAM

The current behaviour makes it weird to run minio gateway in EC2 as experienced by @wlan0 - it is necessary to set AWS env vars to get it to work in the existing ordering.

@y4m4 For discussion

## How Has This Been Tested?

Manually 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-01-17 01:23 UTC, donatello commented
CC: @krishnasrinivas for discussion.

2019-01-17 02:02 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-17 02:38 UTC, wlan0 commented
LGTM

2019-01-17 03:12 UTC, harshavardhana requested changes
The current ordering was on purpose, can you explain more what was the issue?

I will write the current intention of ordering.

2019-01-17 04:32 UTC, harshavardhana commented
The current credential ordering was basically to provide a mechanism where incoming Signature V4 requests to be terminated at Minio gateway and all the backend communication happens with rotating credentials.

Now with this in mind, the current ordering is to make sure that we always use IAM roles instead of static credentials when the gateway is deployed under ec2. IAM role credentials rotate every3hrs or and can be configured to be lower. This way applications can be deployed with a minimal set of permissions for a given role. In-fact IAM roles also uses EC2 container rotating credentials as well to get rotating credentials inside a container service. This was an important requirement for one of our customers 

see commits 

```
commit 052a7b8eec644cdf0db0754c8d722487ab7b7b23
Author: Jay Mundrawala <jdmundrawala@gmail.com>
Date:   Wed Sep 19 07:35:30 2018 -0500

    Allow minio s3 gateway to use different AWS auth mechanisms (#6422)
    
    Allow minio s3 gateway to use aws environment credentials,
    IAM instance credentials, or AWS file credentials.
    
    If AWS_ACCESS_KEY_ID, AWS_SECRET_ACCSES_KEY are set,
    or minio is running on an ec2 instance with IAM instance credentials,
    or there is a file $HOME/.aws/credentials, minio running as an S3
    gateway will authenticate with AWS S3 using those one of credentials.
    
    The lookup order:
    1. AWS environment varaibles
    2. IAM instance credentials
    3. $HOME/.aws/credentials
    4. minio environment variables
    
    To authenticate with the minio gateway, you will always use the
    minio environment variables MINIO_ACCESS_KEY MINIO_SECRET_KEY.
```

Also, another PR on similar lines by https://github.com/minio/minio/pull/6478 and this feature is actively used right now by many users. 

Now, this PR is changing this behavior by always using MINIO_ACCESS_KEY which is always going to be set, so the chaining is not useful and we will never get to use rotating creds for backend communication. So in essence chaining is not used that is Minio ENVs should always come last because that is the last line of communication when all else fails.

What I see might be a problem is that @wlan0 deployment might have not been properly configured i.e doesn't have enough permissions. So would need to see in detail what is the issue.

2019-01-17 04:37 UTC, harshavardhana commented
All one needs is a IAM role with following permissions.

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:ListAllMyBuckets",
                "s3:ListBucket",
                "s3:HeadBucket"
            ],
            "Resource": "*"
        },
        {
            "Sid": "VisualEditor1",
            "Effect": "Allow",
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::mybucket/*"
        }
    ]
}
```

2019-01-17 18:56 UTC, donatello commented
Hmm, I wasn't aware that Minio would use both the static and iam simultaneously - i.e. backend s3 creds are different from gateway creds.

Then, I think we can close this PR @wlan0 - this is the not the right fix.

The problem @wlan0 was facing is that the backend s3 he was using was not S3 but play (or say some other minio server) - in this case the credential ordering interferes and the failure is silent (we just get creds are invalid). 

We need a fix where the backend S3 is not automatically assumed to be Amazon S3 on EC2 - this is often the case even when the server is explicitly given on the minio command line, leading to non-intuitive behaviour.

2019-01-17 19:13 UTC, harshavardhana commented
> The problem @wlan0 was facing is that the backend s3 he was using was not S3 but play (or say some other minio server) - in this case the credential ordering interferes and the failure is silent (we just get creds are invalid).
> 
> We need a fix where the backend S3 is not automatically assumed to be Amazon S3 on EC2 - this is often the case even when the gateway server path is explicitly given on the minio command line, leading to non-intuitive behaviour.

This type of approach requires dynamic ordering or chaining. I.e use IAM chaining only for S3 endpoints and for rest just use MinioEnvs - in this PR you can do that change @donatello 

we have s3utils.IsAmazonEndpoint() which should satisfy both requirements.

2019-01-17 19:27 UTC, harshavardhana commented
```diff
diff --git a/cmd/gateway/s3/gateway-s3.go b/cmd/gateway/s3/gateway-s3.go
index f706d34ca..e8100b88d 100644
--- a/cmd/gateway/s3/gateway-s3.go
+++ b/cmd/gateway/s3/gateway-s3.go
@@ -22,6 +22,7 @@ import (
        "io"
        "math/rand"
        "net/http"
+       "net/url"
        "strings"
        "time"
 
@@ -168,6 +169,14 @@ func randString(n int, src rand.Source, prefix string) string {
        return prefix + string(b[0:30-len(prefix)])
 }
 
+func isAmazonEndpoint(urlStr string) bool {
+       u, err := url.Parse(urlStr)
+       if err != nil {
+               return false
+       }
+       return s3utils.IsAmazonEndpoint(*u)
+}
+
 // newS3 - Initializes a new client by auto probing S3 server signature.
 func newS3(url string) (*miniogo.Core, error) {
        if url == "" {
@@ -180,23 +189,28 @@ func newS3(url string) (*miniogo.Core, error) {
                return nil, err
        }
 
-       // Chains all credential types, in the following order:
-       //  - AWS env vars (i.e. AWS_ACCESS_KEY_ID)
-       //  - AWS creds file (i.e. AWS_SHARED_CREDENTIALS_FILE or ~/.aws/credentials)
-       //  - IAM profile based credentials. (performs an HTTP
-       //    call to a pre-defined endpoint, only valid inside
-       //    configured ec2 instances)
-       //  - Static credentials provided by user (i.e. MINIO_ACCESS_KEY)
        creds := credentials.NewChainCredentials([]credentials.Provider{
-               &credentials.EnvAWS{},
-               &credentials.FileAWSCredentials{},
-               &credentials.IAM{
-                       Client: &http.Client{
-                               Transport: minio.NewCustomHTTPTransport(),
-                       },
-               },
                &credentials.EnvMinio{},
        })
+       if isAmazonEndpoint(url) {
+               // Chains all credential types, in the following order:
+               //  - AWS env vars (i.e. AWS_ACCESS_KEY_ID)
+               //  - AWS creds file (i.e. AWS_SHARED_CREDENTIALS_FILE or ~/.aws/credentials)
+               //  - IAM profile based credentials. (performs an HTTP
+               //    call to a pre-defined endpoint, only valid inside
+               //    configured ec2 instances)
+               //  - Static credentials provided by user (i.e. MINIO_ACCESS_KEY)
+               creds = credentials.NewChainCredentials([]credentials.Provider{
+                       &credentials.EnvAWS{},
+                       &credentials.FileAWSCredentials{},
+                       &credentials.IAM{
+                               Client: &http.Client{
+                                       Transport: minio.NewCustomHTTPTransport(),
+                               },
+                       },
+                       &credentials.EnvMinio{},
+               })
+       }
 
        clnt, err := miniogo.NewWithCredentials(endpoint, creds, secure, "")
        if err != nil {
```

Should address the concerns

2019-01-18 09:03 UTC, harshavardhana commented
Closing this PR - another PR https://github.com/minio/minio/pull/7111 sent to address the issues.

2019-01-18 09:03 UTC, closed without merging