Use IAM creds only if endpoint is S3
minio/minio pull request #7111
Opened 2019-01-18 09:01 UTC by harshavardhana

## Description
Use IAM creds only if endpoint is S3

## Motivation and Context
Requirements like being able to run minio gateway in ec2
pointing to a Minio deployment wouldn't work properly
because IAM creds take precendence on ec2.

Add checks such that we only enable AWS specific features
if our backend URL points to actual AWS S3 not S3 compatible
endpoints.

## Regression
No

## How Has This Been Tested?
You may need to deploy in ec2 with this patch to test this PR, with two different mechanisms

- One with S3 gateway pointing to our https://play.minio.io:9000 deployment
- One with S3 gateway pointing to AWS S3 itself.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-01-19 04:21 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-20 08:53 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-20 19:17 UTC, donatello submitted a review, later dismissed

2019-01-21 02:46 UTC, harshavardhana commented
ping @wlan0

2019-01-22 20:18 UTC, wlan0 requested changes

2019-01-22 20:18 UTC, wlan0 commented on cmd/gateway/s3/gateway-s3.go
> +			&credentials.EnvMinio{},
I would remove this line and push the default creds below this `if` statement block. That way, if we need to update the default, we wont have to do it in two places, or miss the default inside the `if` statement.

2019-01-23 03:25 UTC, harshavardhana commented on cmd/gateway/s3/gateway-s3.go
> +			&credentials.EnvMinio{},
Minio ENV is always the last preferred in case of S3 endpoints, so it cannot be moved @wlan0 - I am not sure I understood you correctly. 

The approach here is to ensure that for S3 endpoints we use rotating or AWS specific credentials. This is because Minio ENVs are used to terminate signature at the gateway while we use a different credential to talk to backend.  This is required by some users to avoid exposing AWS creds to the client and use a random cred for Minio and use AWS creds for backend communication.

2019-01-23 06:01 UTC, wlan0 commented on cmd/gateway/s3/gateway-s3.go
> +			&credentials.EnvMinio{},
It's simple - Don't have two copies of the same code.

Do this instead:

```go

providers := []credentials.Provider{}

if isAmazonS3Endpoint(urlStr) {
    providers = append(providers, 
       &credentials.EnvAWS{}, 
       &credentials.FileAWSCredentials{}, 
       &credentials.IAM{
        Client: &http.Client{
		Transport: minio.NewCustomHTTPTransport(),
	},
  })
}

providers = append(providers, &credentials.EnvMinio{})

creds := credentials.NewChainCredentials(providers)
```

This reduces technical debt from not having to update the same code in two places.

2019-01-23 06:08 UTC, harshavardhana commented on cmd/gateway/s3/gateway-s3.go
> +			&credentials.EnvMinio{},
Yeah this is doable.

2019-01-23 06:55 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#f1e3f643-d724-40ec-8418-89bcf2f34b3b) |
<a name="f1e3f643-d724-40ec-8418-89bcf2f34b3b"></a>
### 7111-f6209d1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minikube:32060
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4427eeed79e6:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 47 seconds
(2/13) Running aws-sdk-go tests ... done in 1 seconds
(3/13) Running aws-sdk-java tests ... done in 11 seconds
(4/13) Running aws-sdk-php tests ... done in 54 seconds
(5/13) Running aws-sdk-ruby tests ... done in 13 seconds
(6/13) Running mc tests ... done in 1 minutes and 20 seconds
(7/13) Running minio-dotnet tests ... FAILED in 4 minutes and 19 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=We encountered an internal error, please try again.) (Minio API responded with message=We encountered an internal error, please try again.)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=We encountered an internal error, please try again.) (Minio API responded with message=We encountered an internal error, please try again.) ---> Minio.Exceptions.MinioException: Minio API responded with message=We encountered an internal error, please try again.
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 371
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 513
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 359
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 492
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 254
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 923
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2134
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 221

Executed 6 out of 13 tests successfully.
```

2019-01-23 18:11 UTC, harshavardhana commented
This PR is ready again @donatello @wlan0

2019-01-23 18:13 UTC, donatello approved these changes

2019-01-23 18:50 UTC, wlan0 commented
LGTM

2019-01-23 18:52 UTC, wlan0 commented on cmd/gateway/s3/gateway-s3.go
> +			&credentials.EnvMinio{},
Thanks

2019-01-23 18:52 UTC, wlan0 approved these changes

2019-01-23 19:12 UTC, merged