Fix healing whole file bitrot
minio/minio pull request #7123
Opened 2019-01-19 08:29 UTC by krishnasrinivas

Fixes https://github.com/minio/minio/issues/7121

## Description

Healing code had these issues:
* bitrotCheckFile was passing bigger buffer than size of the file causing errors
* incorrect checksum were passed to newBitrotReader() causing it to fail
* newXLMetaFromXLMeta() was not copying xlMeta.Stat

## Motivation and Context

## Regression

Yes PR #7004

## How Has This Been Tested?

By simulating various heal scenarios:
* removing a file from a disk
* causing bitrot corruption

Both wholefile bitrot and streaming bitrot were verified.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2019-01-19 08:34 UTC, krishnasrinivas commented
Requesting reviews from @harshavardhana @vadmeste

2019-01-19 09:06 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-19 11:15 UTC, vadmeste commented
```diff
diff --git a/cmd/bitrot_test.go b/cmd/bitrot_test.go
index 94b32594..36a6ec7e 100644
--- a/cmd/bitrot_test.go
+++ b/cmd/bitrot_test.go
@@ -24,7 +24,7 @@ import (
 	"testing"
 )
 
-func TestBitrotReaderWriter(t *testing.T) {
+func testBitrotReaderWriterAlgo(t *testing.T, bitrotAlgo BitrotAlgorithm) {
 	tmpDir, err := ioutil.TempDir("", "")
 	if err != nil {
 		log.Fatal(err)
@@ -41,7 +41,7 @@ func TestBitrotReaderWriter(t *testing.T) {
 
 	disk.MakeVol(volume)
 
-	writer := newBitrotWriter(disk, volume, filePath, 35, HighwayHash256S, 10)
+	writer := newBitrotWriter(disk, volume, filePath, 35, bitrotAlgo, 10)
 
 	_, err = writer.Write([]byte("aaaaaaaaaa"))
 	if err != nil {
@@ -61,7 +61,7 @@ func TestBitrotReaderWriter(t *testing.T) {
 	}
 	writer.(io.Closer).Close()
 
-	reader := newStreamingBitrotReader(disk, volume, filePath, 35, HighwayHash256S, 10)
+	reader := newStreamingBitrotReader(disk, volume, filePath, 35, bitrotAlgo, 10)
 	b := make([]byte, 10)
 	if _, err = reader.ReadAt(b, 0); err != nil {
 		log.Fatal(err)
@@ -76,3 +76,9 @@ func TestBitrotReaderWriter(t *testing.T) {
 		log.Fatal(err)
 	}
 }
+
+func TestAllBitrotAlgorithms(t *testing.T) {
+	for bitrotAlgo, _ := range bitrotAlgorithms {
+		testBitrotReaderWriterAlgo(t, bitrotAlgo)
+	}
+}
```

This is a quick diff of bitrot_test.go to check all bitrot algorithms (default and no default algorithms)

2019-01-19 11:27 UTC, harshavardhana commented
Thanks @vadmeste

2019-01-19 11:53 UTC, vadmeste commented
@krishnasrinivas healing a highwayhash256 object still throws an error, also above unit tests throw an EOF error.

2019-01-19 19:04 UTC, krishnasrinivas commented
> @krishnasrinivas healing a highwayhash256 object still throws an error

how to reproduce this @vadmeste 

> also above unit tests throw an EOF error.

you have to do this and it will work:
```
-       reader := newStreamingBitrotReader(disk, volume, filePath, 35, HighwayHash256S, 10)
+       reader := newBitrotReader(disk, volume, filePath, 35, bitrotAlgo, bitrotWriterSum(writer), 10)
```

2019-01-19 19:20 UTC, harshavardhana requested changes

2019-01-19 19:20 UTC, harshavardhana commented on cmd/xl-v1-object_test.go
> +		fmt.Println(xlMetaPreHeal)
This needs to be removed

2019-01-19 19:21 UTC, krishnasrinivas commented on cmd/xl-v1-object_test.go
> +		fmt.Println(xlMetaPreHeal)
:+1:

2019-01-19 19:38 UTC, harshavardhana submitted a review, later dismissed

2019-01-19 20:00 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-19 20:25 UTC, vadmeste commented
LGTM but Travis is failing @krishnasrinivas

2019-01-19 20:49 UTC, vadmeste approved these changes
LGTM and tested

2019-01-19 21:51 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-01-20 02:28 UTC, harshavardhana approved these changes

2019-01-20 02:28 UTC, merged