xl: ListObjectParts uses the latest valid xl meta
minio/minio pull request #7184
Opened 2019-01-31 19:54 UTC by vadmeste

## Description
ListObjectParts is using xl.readXLMetaParts which picks the first
xl meta found in any disk, which is an inconsistent information.

E.g.: In a middle of a multipart upload, one node can go offline
and get back later with an outdated multipart information.

## Motivation and Context
Fix the following mc error during mirroring a large bucket

```
One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.
```

## Regression
No

## How Has This Been Tested?
- Run 4 nodes with 4 disks with a round robin load balancer.
- Create testbucket bucket
- Parallel upload of multiple encrypted objects (see code above)
- Kill one node and get it back sporadically.

```go
package main

import (
	"bytes"
	"fmt"
	"log"
	"strings"
	"sync"

	"github.com/minio/minio-go"
	"github.com/minio/minio-go/pkg/encrypt"
)

func main() {
	s3Client, err := minio.New("minio:9121", "minio", "minio123", true)
	if err != nil {
		log.Fatalln(err)
	}

	var wg sync.WaitGroup

	for i := 1; i <= 20; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()
			content := bytes.Repeat([]byte("A"), 1024*1024*6)
			size := int64(len(content))

			bucketname := "testbucket"                 // Specify a bucket name - the bucket must already exist
			objectName := "testfile"                   // Specify a object name
			password := "correct horse battery staple" // Specify your password. DO NOT USE THIS ONE - USE YOUR OWN.

			// New SSE-C where the cryptographic key is derived from a password and the objectname + bucketname as salt
			encryption := encrypt.DefaultPBKDF([]byte(password), []byte(bucketname+objectName))

			index := fmt.Sprintf("%v", i)
			objName := fmt.Sprintf("%s-%v", objectName, index)

			for {
				// Encrypt file content and upload to the server
				_, err := s3Client.PutObject(bucketname, objName, bytes.NewReader(content), size, minio.PutObjectOptions{ServerSideEncryption: encryption})
				if err != nil {
					if !strings.Contains(err.Error(), "internal error") &&
						!strings.Contains(err.Error(), "Server not initialized") &&
						!strings.Contains(err.Error(), "Bad Gateway") {
						log.Fatalf(err.Error())
					}
				}
			}
		}(i)
	}

	wg.Wait()
}
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-01-31 20:07 UTC, harshavardhana commented
Thanks @vadmeste - added myself as a reviewer, working on this internally.

2019-01-31 21:47 UTC, harshavardhana requested changes
LGTM - thanks for the nice fix.

2019-01-31 21:47 UTC, harshavardhana commented on cmd/xl-v1-multipart.go
> +	partsMetadata, errs := readAllXLMetadata(ctx, xl.getDisks(), minioMetaMultipartBucket, uploadIDPath)
We should use the same storageDisks @vadmeste 

```
storageDisks := xl.getDisks()
```

And use this everywhere.

2019-02-01 02:23 UTC, kannappanr commented on cmd/xl-v1-multipart.go
> +	partsMetadata, errs := readAllXLMetadata(ctx, xl.getDisks(), minioMetaMultipartBucket, uploadIDPath)
Should we add this code into a separate function?

2019-02-01 03:30 UTC, harshavardhana commented on cmd/xl-v1-multipart.go
> +	partsMetadata, errs := readAllXLMetadata(ctx, xl.getDisks(), minioMetaMultipartBucket, uploadIDPath)
It can be added but refactoring is not needed perhaps in this PR.

2019-02-01 10:55 UTC, vadmeste commented on cmd/xl-v1-multipart.go
> +	partsMetadata, errs := readAllXLMetadata(ctx, xl.getDisks(), minioMetaMultipartBucket, uploadIDPath)
> We should use the same storageDisks @vadmeste

Fixed



> Should we add this code into a separate function?

Yes I also prefer to do this in a separate PR since we have this in multiple places

2019-02-01 11:19 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-tls.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |

2019-02-01 14:07 UTC, kannappanr approved these changes
LGTM

2019-02-01 16:49 UTC, harshavardhana approved these changes

2019-02-01 16:58 UTC, merged