storage: Increase the timeout of storage REST requests
minio/minio pull request #7218
Opened 2019-02-09 22:17 UTC by vadmeste

## Description
This commit increases storage REST requests to 5 minutes, this includes
the opening TCP connection, and sending/receiving data. This will reduce
clients receiving errors when the server is under high load.

## Motivation and Context
Reduce the likewise of S3 clients having errors when the server is a bit of high load.

## Regression
No

## How Has This Been Tested?
1. Start a Minio cluster of 12 nodes
2. Run this following script

```
package main

import (
	"bytes"
	"fmt"
	"log"
	"math"
	"sync"
	"time"

	"github.com/minio/minio-go"
	"github.com/minio/minio-go/pkg/encrypt"
)

func main() {

	const parallelWorkers = 32
	const hostName = "minio"

	var wg sync.WaitGroup
	var totalTransfer int64

	objectContent := bytes.Repeat(bytes.Repeat([]byte("A"), int(math.Pow(2, 19))), 1)
	objectSize := int64(len(objectContent))

	for i := 1; i <= parallelWorkers; i++ {
		wg.Add(1)
		go func(i int) {
			defer wg.Done()

			hostAddr := fmt.Sprintf("%s:%d", hostName, 9001+i%12)

			s3Client, err := minio.New(hostAddr, "minio", "minio123", true)
			if err != nil {
				log.Fatalln(err)
			}

			bucketName := "testbucket"
			objectName := fmt.Sprintf("my-object-%d", i)

			password := "correct horse battery staple"
			encryption := encrypt.DefaultPBKDF([]byte(password),
				[]byte(bucketName+objectName))

			for {
				startTime := time.Now()
				_, err := s3Client.PutObject(bucketName,
					objectName,
					bytes.NewReader(objectContent),
					objectSize,
					minio.PutObjectOptions{
						ServerSideEncryption: encryption,
					},
				)
				if err != nil {
					log.Fatalln(err)
				} else {
					totalTransfer += objectSize
				}
				elapsed := time.Since(startTime)
				if elapsed > 3*time.Second {
					log.Println(elapsed)
				}
			}
		}(i)
	}

	wg.Wait()
}
```

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-02-09 22:56 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-02-09 23:35 UTC, harshavardhana requested changes
We should also do this change for rpc/* @vadmeste

2019-02-10 11:19 UTC, vadmeste commented
> We should also do this change for rpc/* @vadmeste

Done

2019-02-10 11:34 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-02-10 14:58 UTC, harshavardhana requested changes
Only one comment rest looks okay.

2019-02-10 14:58 UTC, harshavardhana commented on cmd/rpc.go
> +			client.setRetryTicker(time.NewTicker(defaultRPCTimeout))
Retry perhaps should be faster but not timeout.

2019-02-11 04:19 UTC, krishnasrinivas commented
@vadmeste for dist-xl minio{1...4} setup, if S3 client is talking to minio1 and minio4's network is brought down, will it cause S3 client to hang for 5 mins? It might be a bit

2019-02-12 00:42 UTC, harshavardhana commented on cmd/rpc.go
> +			client.setRetryTicker(time.NewTicker(defaultRPCTimeout))
PTAL @vadmeste

2019-02-12 19:01 UTC, harshavardhana approved these changes

2019-02-13 00:01 UTC, krishnasrinivas approved these changes

2019-02-13 07:25 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-02-13 07:27 UTC, merged