s3: Add support of encodingType parameter
minio/minio pull request #7265
Opened 2019-02-21 14:09 UTC by vadmeste

## Description

## Motivation and Context

## Regression

## How Has This Been Tested?

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2019-02-21 14:16 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#0bd813a0-e95d-4e7a-bbca-a7d94d0d435f) |
| mint-xl.sh | :x: [more...](#09b5c35e-7864-431a-ad20-a1e0ecb28efb) |
| mint-large-bucket.sh | :x: [more...](#a6c50fd6-bf1e-403c-b867-32cbd806a6eb) |
| mint-compression-dist-xl.sh | :x: [more...](#4e6a4ba7-89df-4fc8-8cb9-e095412c5431) |
| mint-compression-fs.sh | :x: [more...](#ac826a9a-b751-4de9-a834-1d2823660ed5) |
| mint-fs.sh | :x: [more...](#c89bbafb-c698-4442-bca1-5edac862237e) |
| mint-dist-xl.sh | :x: [more...](#4a43a9e4-deae-4d7d-b628-a08cd103e707) |
| mint-gateway-nas.sh | :x: [more...](#e548fb71-d180-4af2-afd8-f5462e00ff00) |
<a name="ac826a9a-b751-4de9-a834-1d2823660ed5"></a>
### 7265-f1c52fd/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32394
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5bc9ca6a4ff9:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 seconds
(5/13) Running awscli tests ... FAILED in 9 seconds
{
  "name": "awscli",
  "duration": 4340,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-22231/prefix%2Fdirectory%2Fdatafile-1-MBremove_bucket failed: s3://awscli-mint-test-bucket-22231 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 4 out of 13 tests successfully.
```
<a name="a6c50fd6-bf1e-403c-b867-32cbd806a6eb"></a>
### 7265-f1c52fd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32029
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3dfe56b7884a:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 49 seconds
(4/13) Running aws-sdk-ruby tests ... done in 15 seconds
(5/13) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 4806,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-7914/prefix%2Fdirectory%2Fdatafile-1-MBremove_bucket failed: s3://awscli-mint-test-bucket-7914 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 4 out of 13 tests successfully.
```
<a name="4a43a9e4-deae-4d7d-b628-a08cd103e707"></a>
### 7265-f1c52fd/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32289
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e6cbe5451787:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 1 seconds
(2/13) Running aws-sdk-java tests ... done in 0 seconds
(3/13) Running aws-sdk-php tests ... done in 45 seconds
(4/13) Running aws-sdk-ruby tests ... done in 4 seconds
(5/13) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 4430,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-16605/prefix%2Fdirectory%2Fdatafile-1-MBremove_bucket failed: s3://awscli-mint-test-bucket-16605 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 4 out of 13 tests successfully.
```
<a name="0bd813a0-e95d-4e7a-bbca-a7d94d0d435f"></a>
### 7265-f1c52fd/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30856
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 12fe7444961c:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 seconds
(5/13) Running awscli tests ... FAILED in 9 seconds
{
  "name": "awscli",
  "duration": 4322,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-32610/prefix%2Fdirectory%2Fdatafile-1-MBremove_bucket failed: s3://awscli-mint-test-bucket-32610 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 4 out of 13 tests successfully.
```
<a name="c89bbafb-c698-4442-bca1-5edac862237e"></a>
### 7265-f1c52fd/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31714
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b98102c9535c:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 1 seconds
(2/13) Running aws-sdk-java tests ... done in 0 seconds
(3/13) Running aws-sdk-php tests ... done in 42 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 seconds
(5/13) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 4386,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-28039/prefix%2Fdirectory%2Fdatafile-1-MBremove_bucket failed: s3://awscli-mint-test-bucket-28039 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 4 out of 13 tests successfully.
```
<a name="e548fb71-d180-4af2-afd8-f5462e00ff00"></a>
### 7265-f1c52fd/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31969
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp de1c05c30be6:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 seconds
(5/13) Running awscli tests ... FAILED in 9 seconds
{
  "name": "awscli",
  "duration": 4388,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-27107/prefix%2Fdirectory%2Fdatafile-1-MBremove_bucket failed: s3://awscli-mint-test-bucket-27107 An error occurred (BucketNotEmpty) when calling the DeleteBucket operation: The bucket you tried to delete is not empty"
}

Executed 4 out of 13 tests successfully.
```
<a name="09b5c35e-7864-431a-ad20-a1e0ecb28efb"></a>
### 7265-f1c52fd/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32035
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ab62ecdaffab:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 0 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 41 seconds
(4/13) Running aws-sdk-ruby tests ... done in 2 second [...]

2019-02-22 19:32 UTC, minio-ops commented
```
Error running mint automation
+ mkdir -p 7265-a456ce5/gopath/src/github.com/minio
+ git -C 7265-a456ce5/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 7265-a456ce5/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 7265-a456ce5/gopath/src/github.com/minio/minio fetch --quiet minio pull/7265/head:pr7265
+ git -C 7265-a456ce5/gopath/src/github.com/minio/minio checkout --quiet pr7265
+ GOPATH=/mnt/nvme/mint-auto/7265-a456ce5/gopath
+ make -C 7265-a456ce5/gopath/src/github.com/minio/minio --quiet
+ docker build --quiet --tag minio/minio:7265-a456ce5 --file 7265-a456ce5/gopath/src/github.com/minio/minio/Dockerfile.dev 7265-a456ce5/gopath/src/github.com/minio/minio
+ docker push minio/minio:7265-a456ce5

```

2019-02-22 19:32 UTC, minio-ops commented
```
Error running mint automation
+ mkdir -p 7265-a456ce5/gopath/src/github.com/minio
+ git -C 7265-a456ce5/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
fatal: destination path 'minio' already exists and is not an empty directory.

```

2019-02-23 17:03 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-02-23 17:27 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-02-23 18:54 UTC, vadmeste commented
Can I get some reviewers ?

2019-02-23 19:15 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#fac19f3e-7bc9-4530-9ee3-87a8415bc030) |
<a name="fac19f3e-7bc9-4530-9ee3-87a8415bc030"></a>
### 7265-d27d816/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30973
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 88886ad79e66:/mint/log /tmp/mint-logs'

(1/13) Running aws-sdk-go tests ... done in 2 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-php tests ... done in 50 seconds
(4/13) Running aws-sdk-ruby tests ... done in 15 seconds
(5/13) Running awscli tests ... done in 16 minutes and 12 seconds
(6/13) Running mc tests ... FAILED in 2 minutes and 6 seconds
{
  "name": "mc",
  "duration": "62829",
  "function": "test_put_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-11530 --quiet --no-color rm myminio/mc-test-bucket-10768/mc-test-object-12588  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-10768/mc-test-object-12588`. Get http://72.28.97.60:30973/mc-test-bucket-10768/?location=: dial tcp 72.28.97.60:30973: i/o timeout"
}

Executed 5 out of 13 tests successfully.
```

2019-02-23 19:41 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-02-23 19:50 UTC, harshavardhana requested changes
Any clue why some tests are commented ?

2019-02-23 21:20 UTC, vadmeste commented
> Any clue why some tests are commented ?

I commented old tests as I rewrote them but forgot to remove comments

2019-02-23 21:27 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-02-23 21:53 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-02-23 22:43 UTC, harshavardhana approved these changes

2019-02-24 06:01 UTC, poornas approved these changes
LGTM, tested

2019-02-24 06:14 UTC, merged