Add more detail about where config.json is located
minio/minio pull request #7419
Opened 2019-03-24 03:25 UTC by davidpendraykalibrate

2019-03-24 03:42 UTC, minio-ops commented
```
Error running mint automation
+ mkdir -p 7419-e7e7943/gopath/src/github.com/minio
+ git -C 7419-e7e7943/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 7419-e7e7943/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 7419-e7e7943/gopath/src/github.com/minio/minio fetch --quiet minio pull/7419/head:pr7419
+ git -C 7419-e7e7943/gopath/src/github.com/minio/minio checkout --quiet pr7419
+ GOPATH=/mnt/nvme/mint-auto/7419-e7e7943/gopath
+ make -C 7419-e7e7943/gopath/src/github.com/minio/minio --quiet
+ docker build --quiet --tag minio/minio:7419-e7e7943 --file 7419-e7e7943/gopath/src/github.com/minio/minio/Dockerfile.dev 7419-e7e7943/gopath/src/github.com/minio/minio
+ docker push minio/minio:7419-e7e7943
+ docker pull minio/mint:edge
+ declare -A mint_jobs
+ for job in mint-*.sh
+ mint_jobs["$job"]=6636
+ for job in mint-*.sh
+ mint_jobs["$job"]=6637
+ for job in mint-*.sh
+ bash mint-compression-dist-xl.sh
+ mint_jobs["$job"]=6638
+ for job in mint-*.sh
+ bash mint-compression-fs.sh
+ bash mint-compression-xl.sh
+ mint_jobs["$job"]=6639
+ for job in mint-*.sh
+ mint_jobs["$job"]=6640
+ for job in mint-*.sh
+ bash mint-dist-xl.sh
+ mint_jobs["$job"]=6641
+ for job in mint-*.sh
+ bash mint-fs.sh
+ mint_jobs["$job"]=6642
+ bash mint-gateway-nas.sh
+ for job in mint-*.sh
+ bash mint-large-bucket.sh
+ mint_jobs["$job"]=6643
+ for job in mint-*.sh
+ mint_jobs["$job"]=6644
+ bash mint-worm.sh
+ wait 6638 6644 6642 6636 6637 6643 6640 6639 6641
+ bash mint-xl.sh
+ declare -a success_jobs
+ declare -a failed_jobs
+ for job in "${!mint_jobs[@]}"
+ wait 6638
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 6644
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 6642
+ failed_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 6636
+ failed_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 6637
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 6643
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 6640
+ success_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 6639
+ failed_jobs+=("$job")
+ for job in "${!mint_jobs[@]}"
+ wait 6641
+ success_jobs+=("$job")
+ echo '## Mint Automation'
+ echo '| Test | Result |'
+ echo '|:--- |:--- |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-compression-xl.sh | :heavy_check_mark: |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-xl.sh | :heavy_check_mark: |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-compression-fs.sh | :heavy_check_mark: |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-worm.sh | :heavy_check_mark: |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-fs.sh | :heavy_check_mark: |'
+ for job in "${success_jobs[@]}"
+ echo '| mint-gateway-nas.sh | :heavy_check_mark: |'
+ declare -A uuid_log_file_map
+ declare -A uuid_xtrace_map
+ for job in "${failed_jobs[@]}"
++ uuidgen
+ uuid=957817a6-31c6-48aa-9c0c-66a25767c628
+ '[' -s 7419-e7e7943/mint-large-bucket.sh.log ']'
+ echo '| mint-large-bucket.sh | :x: [more...](#957817a6-31c6-48aa-9c0c-66a25767c628) |'
+ uuid_log_file_map["$uuid"]=7419-e7e7943/mint-large-bucket.sh.log
+ for job in "${failed_jobs[@]}"
++ uuidgen
+ uuid=0bd9b51c-f4f8-4fb9-95ac-18add638269e
+ '[' -s 7419-e7e7943/mint-compression-dist-xl.sh.log ']'
+ echo '| mint-compression-dist-xl.sh | :x: [more...](#0bd9b51c-f4f8-4fb9-95ac-18add638269e) |'
+ uuid_log_file_map["$uuid"]=7419-e7e7943/mint-compression-dist-xl.sh.log
+ for job in "${failed_jobs[@]}"
++ uuidgen
+ uuid=e1304bfa-c9d0-4aff-9193-03700eb91dba
+ '[' -s 7419-e7e7943/mint-dist-xl.sh.log ']'
+ echo '| mint-dist-xl.sh | :x: [more...](#e1304bfa-c9d0-4aff-9193-03700eb91dba) |'
+ uuid_log_file_map["$uuid"]=7419-e7e7943/mint-dist-xl.sh.log
+ for uuid in "${!uuid_log_file_map[@]}"
+ echo '<a name="e1304bfa-c9d0-4aff-9193-03700eb91dba"></a>'
+ echo '### 7419-e7e7943/mint-dist-xl.sh.log:'
+ echo '```'
+ cat 7419-e7e7943/mint-dist-xl.sh.log
+ echo '```'
+ for uuid in "${!uuid_log_file_map[@]}"
+ echo '<a name="957817a6-31c6-48aa-9c0c-66a25767c628"></a>'
+ echo '### 7419-e7e7943/mint-large-bucket.sh.log:'
+ echo '```'
+ cat 7419-e7e7943/mint-large-bucket.sh.log
+ echo '```'
+ for uuid in "${!uuid_log_file_map[@]}"
+ echo '<a name="0bd9b51c-f4f8-4fb9-95ac-18add638269e"></a>'
+ echo '### 7419-e7e7943/mint-compression-dist-xl.sh.log:'
+ echo '```'
+ cat 7419-e7e7943/mint-compression-dist-xl.sh.log
+ echo '```'
+ sudo rm -fr 7419-e7e7943
+ docker rmi -f minio/minio:7419-e7e7943

```

2019-03-24 04:00 UTC, harshavardhana requested changes

2019-03-24 04:00 UTC, harshavardhana commented on docs/config/README.md
> +In the storage backend, the config directory is named ```.minio.sys```. The config file is found under ```config``` directory below this. For the example above, the config will would thus be found at
This is true for the most part but not true for erasure coded setup. If we are going to add this we should elaborate for all setups.

2019-04-18 23:41 UTC, harshavardhana commented
We don't need to mention this in our docs, users interact with `config.json` using `mc admin config` - so closing this PR.

2019-04-18 23:41 UTC, closed without merging