Use O_DIRECT while writing to disk
minio/minio pull request #7479
Opened 2019-04-04 01:43 UTC by krishnasrinivas

## Description

Writing on O_DIRECT|O_SYNC mode gives 2 advantages:
* commits to the disk, so in case of power failure we dont have to worry about losing page cache
* higher performance numbers (since CPU usage for page cache related activity is significant which is avoided)

## Regression

No

## How Has This Been Tested?

go test

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [ ] All new and existing tests passed.

2019-04-04 03:08 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#f0a5474c-afcd-4b1b-8725-c95dfd10a836) |
| mint-xl.sh | :x: [more...](#7dde0935-64cd-4e0d-9834-10dbb60d7570) |
| mint-compression-dist-xl.sh | :x: [more...](#d11cd89b-ed60-4877-b819-c70dd7391d68) |
| mint-fs.sh | :x: [more...](#7792c39a-7b4f-47e8-a67a-323ea4d3553c) |
<a name="7792c39a-7b4f-47e8-a67a-323ea4d3553c"></a>
### 7479-2a82792/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30785
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3018cff09c08:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 12 seconds
(8/14) Running minio-dotnet tests ... done in 29 seconds
(9/14) Running minio-go tests ... done in 38 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 44 seconds
(11/14) Running minio-js tests ... done in 37 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 33 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1220, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1885, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1228, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "bucket_name": "minio-py-test-0fc4c346-4cf1-4c67-9ffe-1d77eec7a4e0",
    "object_name": "02a2f06c-73b3-44a1-acd4-99491022b9cf"
  },
  "duration": 81,
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="7dde0935-64cd-4e0d-9834-10dbb60d7570"></a>
### 7479-2a82792/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31253
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 70af1fa79af2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-3ocmnnx95ki0md",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3077,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31253/aws-sdk-go-test-3ocmnnx95ki0md: dial tcp 72.28.97.57:31253: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d11cd89b-ed60-4877-b819-c70dd7391d68"></a>
### 7479-2a82792/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30475
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 17a9b078f147:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5ca570ac279e1",
    "Object": "obj1"
  },
  "duration": "648",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.52:30475/aws-sdk-php-5ca570ac279e1/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.52:30475/aws-sdk-php-5ca570ac279e1/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5ca570ac279e1</BucketName><Resource>/aws-sdk-php-5ca570ac279e1/obj1-copy-0</Resource><RequestId>159225982AD99205</RequestId><HostId>bbe0b36d-8b01-4641-97ab-ee1ff7a47763</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="f0a5474c-afcd-4b1b-8725-c95dfd10a836"></a>
### 7479-2a82792/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32483
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d0f72316211b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5ca570abdc13d",
    "Object": "obj1"
  },
  "duration": "498",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.59:32483/aws-sdk-php-5ca570abdc13d/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.59:32483/aws-sdk-php-5ca570abdc13d/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5ca570abdc13d</BucketName><Resource>/aws-sdk-php-5ca570abdc13d/obj1-copy-0</Resource><RequestId>1592259810515588</RequestId><HostId>3825d385-6d0f-4ca3-a448-2219acd49192</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```

2019-04-05 20:11 UTC, harshavardhana commented
@krishnasrinivas please remove from WIP ?

2019-04-05 20:13 UTC, harshavardhana commented
Some interesting failures already

```
--- FAIL: TestAdminVersionHandler (2.88s)
954
    admin-handlers_test.go:385: Failed to initialize a single node XL backend for admin handler tests.
955
=== RUN   TestServiceStatusHandler
956
--- FAIL: TestServiceStatusHandler (2.77s)
957
    admin-handlers_test.go:533: Failed to initialize a single node XL backend for admin handler tests.
958
=== RUN   TestServiceRestartHandler
959
--- FAIL: TestServiceRestartHandler (8.17s)
960
    admin-handlers_test.go:533: Failed to initialize a single node XL backend for admin handler tests.
961
=== RUN   TestServiceSetCreds
962
--- FAIL: TestServiceSetCreds (8.40s)
963
    admin-handlers_test.go:606: Failed to initialize a single node XL backend for admin handler tests.
964
=== RUN   TestGetConfigHandler
965
--- FAIL: TestGetConfigHandler (1.64s)
966
    admin-handlers_test.go:706: Failed to initialize a single node XL backend for admin handler tests.
967
=== RUN   TestSetConfigHandler
968
--- FAIL: TestSetConfigHandler (6.03s)
969
    admin-handlers_test.go:734: Failed to initialize a single node XL backend for admin handler tests.
970
=== RUN   TestAdminServerInfo
971
--- FAIL: TestAdminServerInfo (4.73s)
972
    admin-handlers_test.go:805: Failed to initialize a single node XL backend for admin handler tests.
```

2019-04-10 01:03 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#9c1742ea-c716-4604-8953-e10fc1d9e834) |
| mint-large-bucket.sh | :x: [more...](#c6220b8d-9615-44fa-930b-f091f42d89de) |
| mint-compression-dist-xl.sh | :x: [more...](#d3058726-525c-4b75-bcc2-cfa2ad63a9d9) |
| mint-dist-xl.sh | :x: [more...](#cf4fc36c-8f0c-4fbc-978e-927778cf0f61) |
<a name="9c1742ea-c716-4604-8953-e10fc1d9e834"></a>
### 7479-3c471ee/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30304
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b95bca710056:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-o6glltx31hyhaz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360012,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1593F74B03BF7C68, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cf4fc36c-8f0c-4fbc-978e-927778cf0f61"></a>
### 7479-3c471ee/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30949
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c027c93064e5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wkk3mzvr5grgr4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360026,
  "error": "XMinioWriteQuorum: Multiple disks failures, unable to write data.\n\tstatus code: 503, request id: 1593F74B1DACA090, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d3058726-525c-4b75-bcc2-cfa2ad63a9d9"></a>
### 7479-3c471ee/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31833
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2a343f1f851c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wdxpugud1psvdv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3069,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31833/aws-sdk-go-test-wdxpugud1psvdv: dial tcp 72.28.97.57:31833: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c6220b8d-9615-44fa-930b-f091f42d89de"></a>
### 7479-3c471ee/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31486
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f64c349dfe6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 59 seconds
(4/14) Running aws-sdk-ruby tests ... done in 25 seconds
(5/14) Running awscli tests ... done in 1 minutes and 37 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... FAILED in 21 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Minio API responded with message=Unsuccessful response from server without XML error: Connection refused Connection refused)) ---> System.AggregateException: One or more errors occurred. (Minio API responded with message=Unsuccessful response from server without XML error: Connection refused Connection refused) ---> Minio.Exceptions.InternalClientException: Minio API responded with message=Unsuccessful response from server without XML error: Connection refused Connection refused
   at Minio.Functional.Tests.FunctionalTest.<>c.<ListObjects_Test>b__83_1(Exception ex) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2079
   at System.Reactive.AutoDetachObserver`1.OnErrorCore(Exception exception) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\AutoDetachObserver.cs:line 76
   at System.Reactive.AnonymousSafeObserver`1.OnError(Exception error) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousSafeObserver.cs:line 62
   at System.Reactive.Linq.ObservableImpl.Throw`1._.Invoke() in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\Observable\Throw.cs:line 42
   at System.Reactive.Concurrency.Scheduler.Invoke(IScheduler scheduler, Action action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\Scheduler.Simple.cs:line 83
   at System.Reactive.Producer`2.SubscribeRaw(IObserver`1 observer, Boolean enableSafeguard) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Internal\Producer.cs:line 127
   at System.Reactive.Linq.QueryLanguage.<>c__DisplayClass330_0`1.<Create>b__0(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Linq\QueryLanguage.Creation.cs:line 46
   at System.Reactive.AnonymousObservable`1.SubscribeCore(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\AnonymousObservable.cs:line 37
   at System.Reactive.ObservableBase`1.ScheduledSubscribe(IScheduler _, AutoDetachObserver`1 autoDetachObserver) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 82
   at System.Reactive.Concurrency.CurrentThreadScheduler.Trampoline.Run(SchedulerQueue`1 queue) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 126
   at System.Reactive.Concurrency.CurrentThreadScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\Concurrency\CurrentThreadScheduler.cs:line 94
   at System.Reactive.ObservableBase`1.Subscribe(IObserver`1 observer) in D:\a\1\s\Rx.NET\Source\src\System.Reactive\ObservableBase.cs:line 51
   at Minio.Functional.Tests.FunctionalTest.ListObjects_Test(MinioClient minio, String bucketName, String prefix, Int32 numObjects, Boolean recursive) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2073
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.ListObjects_Test1(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 1924
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.Main(String[] args) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 218

Executed 7 out of 14 tests successfully.
```

2019-04-10 19:33 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#f065b8bf-f769-4819-9310-b61535597287) |
| mint-xl.sh | :x: [more...](#9ed296cc-4755-430c-b659-7767f00fe386) |
| mint-large-bucket.sh | :x: [more...](#d0558876-55c2-45b3-b9ea-e756ea37b57b) |
| mint-compression-dist-xl.sh | :x: [more...](#fb4d0b2e-b6a3-4897-a51e-6100735e2967) |
| mint-dist-xl.sh | :x: [more...](#59fb1136-8318-4853-8985-7cdf90331193) |
<a name="59fb1136-8318-4853-8985-7cdf90331193"></a>
### 7479-5ea35fa/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30861
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 04d4bc049c9f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-jq4iomasprs6rz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360010,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159433E2EABEC46D, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="fb4d0b2e-b6a3-4897-a51e-6100735e2967"></a>
### 7479-5ea35fa/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30809
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ec0bfb79bed9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ibe2pvlygn2xcx",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 297,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30809/aws-sdk-go-test-ibe2pvlygn2xcx: dial tcp 72.28.97.57:30809: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="9ed296cc-4755-430c-b659-7767f00fe386"></a>
### 7479-5ea35fa/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32557
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2b3ec6e4b9d6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i35xmm95kblxjs",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120315,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32557/aws-sdk-go-test-i35xmm95kblxjs: dial tcp 72.28.97.55:32557: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d0558876-55c2-45b3-b9ea-e756ea37b57b"></a>
### 7479-5ea35fa/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30798
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 09b86abe8d41:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-sqkk90gfwlqpz4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 287,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:30798/aws-sdk-go-test-sqkk90gfwlqpz4: dial tcp 72.28.97.59:30798: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f065b8bf-f769-4819-9310-b61535597287"></a>
### 7479-5ea35fa/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31246
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8c84af74ec46:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cae43ad4a3c5",
    "Object": "obj1"
  },
  "duration": "495",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.59:31246/aws-sdk-php-5cae43ad4a3c5/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.59:31246/aws-sdk-php-5cae43ad4a3c5/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cae43ad4a3c5</BucketName><Resource>/aws-sdk-php-5cae43ad4a3c5/obj1-copy-0</Resource><RequestId>1594338F48CAEBCA</RequestId><HostId>dfdb6760-daad-4f8a-938c-91756f17abe9</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```

2019-04-15 06:11 UTC, harshavardhana commented
Can you resolve your conflicts @krishnasrinivas ?

2019-04-15 08:05 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#9fc18ef9-6c26-4c16-8345-c3294cf9df9c) |
| mint-large-bucket.sh | :x: [more...](#5c08251e-f4e1-4cd8-a60e-109baa64b890) |
| mint-compression-dist-xl.sh | :x: [more...](#91fce9ae-7d09-4a98-9f35-b578652d653a) |
| mint-dist-xl.sh | :x: [more...](#2efb7275-0a68-4f95-bb11-2ccebd5e625b) |
<a name="91fce9ae-7d09-4a98-9f35-b578652d653a"></a>
### 7479-5b5bb31/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32329
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 45bc7d5dfc18:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-p05n50m5eahd1w",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3054,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32329/aws-sdk-go-test-p05n50m5eahd1w: dial tcp 72.28.97.57:32329: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="5c08251e-f4e1-4cd8-a60e-109baa64b890"></a>
### 7479-5b5bb31/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30844
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8676bfa3de6a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vwrdt3usqci1ym",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 291,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30844/aws-sdk-go-test-vwrdt3usqci1ym: dial tcp 72.28.97.60:30844: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="2efb7275-0a68-4f95-bb11-2ccebd5e625b"></a>
### 7479-5b5bb31/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30647
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d85fc352c455:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rffwgdliukwhyl",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 361,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30647/aws-sdk-go-test-rffwgdliukwhyl: dial tcp 72.28.97.60:30647: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="9fc18ef9-6c26-4c16-8345-c3294cf9df9c"></a>
### 7479-5b5bb31/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31099
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c017bfc7f34:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cb43961b97bf",
    "Object": "obj1"
  },
  "duration": "232",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.52:31099/aws-sdk-php-5cb43961b97bf/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.52:31099/aws-sdk-php-5cb43961b97bf/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cb43961b97bf</BucketName><Resource>/aws-sdk-php-5cb43961b97bf/obj1-copy-0</Resource><RequestId>159596CA527594D8</RequestId><HostId>2dd1969e-8cb1-4664-9b1d-6e8d459e6c51</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```

2019-04-15 23:09 UTC, harshavardhana commented
@donatello @vadmeste need reviews on this PR.

2019-04-15 23:50 UTC, donatello reviewed
Some print statements need to be removed - code looks good, but I think we should get the tests to pass fully before taking this in.

2019-04-15 23:50 UTC, donatello commented on cmd/posix.go
> +			fmt.Println("Fallocate", filePath, e)
This print statement needs to be a log?

2019-04-15 23:50 UTC, donatello commented on cmd/posix.go
> +			fmt.Println("w.Write(buf)", filePath, err)
Print statement needs to be changed.

2019-04-15 23:50 UTC, donatello commented on cmd/posix.go
> +				fmt.Println("w.Write(remainingAlignedBuf)", filePath, err)
Print statement

2019-04-15 23:50 UTC, donatello commented on cmd/posix.go
> +				fmt.Println("w.Write(remainingUnalignedBuf)", filePath, err)
Another one.

2019-04-16 00:55 UTC, uroni commented
Note that e.g. the current stable version of ZFSOnLinux doesn't support O_DIRECT (file won't open) https://github.com/zfsonlinux/zfs/pull/7823#issuecomment-417437898 , so a fallback would perhaps be useful? (note also that ZFSOnLinux nearly ignores the O_DIRECT in 0.8)

2019-04-16 01:03 UTC, harshavardhana commented
Yes @uroni a fallback is to sync

2019-04-16 01:16 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#0a506ba4-74a4-4232-bd4c-77c0cad2508b) |
| mint-xl.sh | :x: [more...](#237f73a2-7516-4a26-8474-a70ca7c06b7c) |
| mint-large-bucket.sh | :x: [more...](#8a4a7168-7e7d-47fd-a5b7-3ca653e07f13) |
| mint-compression-dist-xl.sh | :x: [more...](#66040142-d65c-457d-bd3f-e521a2ec94b6) |
| mint-gateway-nas.sh | :x: [more...](#9749e887-23e2-4429-9452-e92a867b5960) |
<a name="8a4a7168-7e7d-47fd-a5b7-3ca653e07f13"></a>
### 7479-e33c306/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31124
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0ae8684889b2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-nheqp2p1yreoax",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 246,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.54:31124/aws-sdk-go-test-nheqp2p1yreoax: dial tcp 72.28.97.54:31124: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="237f73a2-7516-4a26-8474-a70ca7c06b7c"></a>
### 7479-e33c306/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32215
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6f31623170cf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-0e9nbqxhqmiqke",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 4415,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32215/aws-sdk-go-test-0e9nbqxhqmiqke: dial tcp 72.28.97.55:32215: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="9749e887-23e2-4429-9452-e92a867b5960"></a>
### 7479-e33c306/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32648
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 487cc4c7d5b8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-3tyjx49qleam5i",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 4338,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32648/aws-sdk-go-test-3tyjx49qleam5i: dial tcp 72.28.97.55:32648: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0a506ba4-74a4-4232-bd4c-77c0cad2508b"></a>
### 7479-e33c306/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30974
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e28855f50619:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cb529945d537",
    "Object": "obj1"
  },
  "duration": "486",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.60:30974/aws-sdk-php-5cb529945d537/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.60:30974/aws-sdk-php-5cb529945d537/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cb529945d537</BucketName><Resource>/aws-sdk-php-5cb529945d537/obj1-copy-0</Resource><RequestId>1595CEB74847AA15</RequestId><HostId>dabaa2d7-fff5-4f8c-a1c3-43703168ba62</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="66040142-d65c-457d-bd3f-e521a2ec94b6"></a>
### 7479-e33c306/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32110
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d38f5a276d21:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 1 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cb5299566759",
    "Object": "obj1"
  },
  "duration": "338",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.54:32110/aws-sdk-php-5cb5299566759/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.54:32110/aws-sdk-php-5cb5299566759/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cb5299566759</BucketName><Resource>/aws-sdk-php-5cb5299566759/obj1-copy-0</Resource><RequestId>1595CEB784AA75DD</RequestId><HostId>ccb98aee-8960-487c-8fdc-daa7bbf3716f</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```

2019-04-16 17:11 UTC, donatello submitted a review, later dismissed

2019-04-16 18:34 UTC, harshavardhana requested changes

2019-04-16 18:34 UTC, harshavardhana commented on pkg/disk/directio_darwin.go
> + * Minio Cloud Storage, (C) 2017 Minio, Inc.
License headers are old @krishnasrinivas needs to be fixed

2019-04-18 00:01 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#baf5ca7d-e08f-4060-b745-31674c22e003) |
| mint-xl.sh | :x: [more...](#11d00a21-1664-40a3-80da-86a1b829657b) |
| mint-large-bucket.sh | :x: [more...](#2b738c14-89b9-4020-9011-07b22208d23b) |
| mint-compression-dist-xl.sh | :x: [more...](#2ed84d44-af58-4610-8d47-aa9b8dcb5b84) |
| mint-dist-xl.sh | :x: [more...](#709be096-beae-4bf3-ad74-b675cc049dd6) |
<a name="2ed84d44-af58-4610-8d47-aa9b8dcb5b84"></a>
### 7479-fc8075e/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30282
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6acd2567fb05:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-3q6vxgnkrp6foe",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 391,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.56:30282/aws-sdk-go-test-3q6vxgnkrp6foe: dial tcp 72.28.97.56:30282: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="2b738c14-89b9-4020-9011-07b22208d23b"></a>
### 7479-fc8075e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32764
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c9a8aef6257d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-12aeakswul3rt1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 269,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32764/aws-sdk-go-test-12aeakswul3rt1: dial tcp 72.28.97.55:32764: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="11d00a21-1664-40a3-80da-86a1b829657b"></a>
### 7479-fc8075e/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32477
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a23c422c7576:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-new9b3muedahnk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 261,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:32477/aws-sdk-go-test-new9b3muedahnk: dial tcp 72.28.97.60:32477: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="709be096-beae-4bf3-ad74-b675cc049dd6"></a>
### 7479-fc8075e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30750
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a7b4f7d8b0be:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i459qczuuccm9c",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 298,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30750/aws-sdk-go-test-i459qczuuccm9c: dial tcp 72.28.97.60:30750: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="baf5ca7d-e08f-4060-b745-31674c22e003"></a>
### 7479-fc8075e/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31322
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2e09725e03ae:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-vkllfk6aevkzj6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1596687A059A962C, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-04-18 01:52 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#e2a7d3e7-612b-4bbb-ac3a-01706138a5d5) |
| mint-xl.sh | :x: [more...](#b9047a45-0234-4a1d-9c4a-aa4d9dcd5c21) |
| mint-large-bucket.sh | :x: [more...](#af0da23d-525a-43e4-84b4-fe882b8f95d2) |
| mint-compression-dist-xl.sh | :x: [more...](#ae468aa3-9d1c-4fa6-8268-98c3e63cad41) |
<a name="e2a7d3e7-612b-4bbb-ac3a-01706138a5d5"></a>
### 7479-53d8ed8/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32171
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d14dc7fdbdc8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cb7d54c4323c",
    "Object": "obj1"
  },
  "duration": "562",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.57:32171/aws-sdk-php-5cb7d54c4323c/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.57:32171/aws-sdk-php-5cb7d54c4323c/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cb7d54c4323c</BucketName><Resource>/aws-sdk-php-5cb7d54c4323c/obj1-copy-0</Resource><RequestId>15966DE8167E954B</RequestId><HostId>20eb8cff-6a91-41bf-a644-5d45e72c0539</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="ae468aa3-9d1c-4fa6-8268-98c3e63cad41"></a>
### 7479-53d8ed8/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32528
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fc9d2a21612a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 0 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5cb7d54d6b72a",
    "Object": "obj1"
  },
  "duration": "379",
  "status": "FAIL",
  "error": "Error executing \"CopyObject\" on \"http://72.28.97.56:32528/aws-sdk-php-5cb7d54d6b72a/obj1-copy-0\"; AWS HTTP error: Server error: `PUT http://72.28.97.56:32528/aws-sdk-php-5cb7d54d6b72a/obj1-copy-0` resulted in a `503 Service Unavailable` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to re (truncated...)\n XMinioReadQuorum (server): Multiple disk failures, unable to reconstruct data. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>XMinioReadQuorum</Code><Message>Multiple disk failures, unable to reconstruct data.</Message><Key>obj1-copy-0</Key><BucketName>aws-sdk-php-5cb7d54d6b72a</BucketName><Resource>/aws-sdk-php-5cb7d54d6b72a/obj1-copy-0</Resource><RequestId>15966DE853A95AA5</RequestId><HostId>d28b60dd-f907-4260-982d-054e5734efc9</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="b9047a45-0234-4a1d-9c4a-aa4d9dcd5c21"></a>
### 7479-53d8ed8/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32129
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 596baf55a31b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-diyrd2rom1w10p",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 346,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.56:32129/aws-sdk-go-test-diyrd2rom1w10p: dial tcp 72.28.97.56:32129: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="af0da23d-525a-43e4-84b4-fe882b8f95d2"></a>
### 7479-53d8ed8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31869
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7e5c3404d77b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-6uzs51vz09po90",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 268,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:31869/aws-sdk-go-test-6uzs51vz09po90: dial tcp 72.28.97.59:31869: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-04-18 17:46 UTC, harshavardhana approved these changes

2019-04-18 18:17 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#fc3c5ec1-a609-4fe1-b0e2-ecde5a03585c) |
| mint-large-bucket.sh | :x: [more...](#c1edd09c-79d3-4b5f-8692-87ace9930c31) |
| mint-compression-dist-xl.sh | :x: [more...](#4ebcc202-daf9-4a98-87a6-ecb524d9e56d) |
| mint-gateway-nas.sh | :x: [more...](#20b0093f-ca98-4eaf-aa5c-3b55ae407239) |
<a name="fc3c5ec1-a609-4fe1-b0e2-ecde5a03585c"></a>
### 7479-c477ddb/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31844
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 97a0cfd0f313:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 18 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-s2yyprn2r4rhuk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 18378,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31844/aws-sdk-go-test-s2yyprn2r4rhuk: dial tcp 72.28.97.57:31844: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="20b0093f-ca98-4eaf-aa5c-3b55ae407239"></a>
### 7479-c477ddb/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30843
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8015655d0321:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 18 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-o4ojhy1bna9ztn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 17828,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30843/aws-sdk-go-test-o4ojhy1bna9ztn: dial tcp 72.28.97.57:30843: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c1edd09c-79d3-4b5f-8692-87ace9930c31"></a>
### 7479-c477ddb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30618
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 14bdb38d2ecd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ohyvzrf0u0urnq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 300,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.51:30618/aws-sdk-go-test-ohyvzrf0u0urnq: dial tcp 72.28.97.51:30618: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="4ebcc202-daf9-4a98-87a6-ecb524d9e56d"></a>
### 7479-c477ddb/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30851
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f194e653fbbb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-unntxmx5qub5px",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 332,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30851/aws-sdk-go-test-unntxmx5qub5px: dial tcp 72.28.97.55:30851: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-04-18 22:14 UTC, harshavardhana commented
ping @donatello

2019-04-22 08:26 UTC, harshavardhana commented
ping @donatello

2019-04-22 09:33 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#f1341418-7651-4260-b753-ffd1b7706e69) |
| mint-large-bucket.sh | :x: [more...](#551c6471-fb0b-4536-8034-704eb73b053d) |
| mint-compression-dist-xl.sh | :x: [more...](#35fb99a3-7291-481f-97da-2c187d51ea8a) |
| mint-dist-xl.sh | :x: [more...](#abf1e1a3-d517-45b1-b0e2-bfa2f85010bc) |
<a name="abf1e1a3-d517-45b1-b0e2-bfa2f85010bc"></a>
### 7479-289f1e8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30863
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 34bd8d7beadf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-jp6gfjaxzx0p32",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1597C1F8086E7ABB, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="35fb99a3-7291-481f-97da-2c187d51ea8a"></a>
### 7479-289f1e8/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32386
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3aaa6ba83ffd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i55zhkzswwfmew",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3061,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32386/aws-sdk-go-test-i55zhkzswwfmew: dial tcp 72.28.97.57:32386: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="f1341418-7651-4260-b753-ffd1b7706e69"></a>
### 7479-289f1e8/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31945
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d6c3b4fcf17:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-t9jtrl140ek2q0",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 4402,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31945/aws-sdk-go-test-t9jtrl140ek2q0: dial tcp 72.28.97.55:31945: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="551c6471-fb0b-4536-8034-704eb73b053d"></a>
### 7479-289f1e8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32662
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b010ed969690:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-acjxf3q2wyp4kj",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360011,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 1597C1F807453E58, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-04-24 03:47 UTC, balamurugana approved these changes

2019-04-24 04:00 UTC, harshavardhana approved these changes

2019-04-24 04:25 UTC, merged