Enable event-persistence in NATS and NATS-Streaming
minio/minio pull request #7612
Opened 2019-05-03 10:21 UTC by Praveenrajmani

## Description
NATS events will be persisted in a queue dir if configured, else persisted in memory.

## Motivation and Context
To provide offline backup/persistence for events, so that no events are lost.

## Regression
Its a feature

## How Has This Been Tested?
<b> Nats Mode </b>
-  Start MinIO without an active nsq broker with the following config
```
"nats": {
    "1": {
        "enable": true,
        "address": "0.0.0.0:4222",
        "subject": "bucketevents",
        "username": "yourusername",
        "password": "yoursecret",
        "token": "",
        "secure": false,
        "pingInterval": 0,
        "queueDir": "/tmp/nats",
        "queueLimit": 1000
        "streaming": {
            "enable": false,
            "clusterID": "",
            "clientID": "",
            "async": false,
            "maxPubAcksInflight": 0
        }
    }
},
```
- Start the following consumer script 
```
package main

// Import Go and NATS packages
import (
    "log"
    "runtime"

    "github.com/nats-io/nats"
)

func main() {

    // Create server connection
    natsConnection, _ := nats.Connect("nats://yourusername:yoursecret@localhost:4222")
    log.Println("Connected")

    // Subscribe to subject
    log.Printf("Subscribing to subject 'bucketevents'\n")
    natsConnection.Subscribe("bucketevents", func(msg *nats.Msg) {

        // Handle the message
        log.Printf("Received message '%s\n", string(msg.Data)+"'")
    })

    // Keep the connection alive
    runtime.Goexit()
}

```
- Enable bucket notification using mc
- Start sending events
- The events will persist in /tmp/nats and gets replayed when the broker is turned on. (/tmp/nats - will be empty if all the events are successfully sent)
- Start the broker
- The evens will be replayed as you can see in consumer console.

<b> Nats-Streaming Mode </b>
-  Start MinIO without an active nsq broker with the following config
```
"nats": {
    "1": {
        "enable": true,
        "address": "0.0.0.0:4222",
        "subject": "bucketevents",
        "username": "yourusername",
        "password": "yoursecret",
        "token": "",
        "secure": false,
        "pingInterval": 0,
        "queueDir": "/tmp/nats",
        "queueLimit": 1000
        "streaming": {
            "enable": true,
            "clusterID": "test-cluster",
            "async": true,
            "maxPubAcksInflight": 10
        }
    }
},
```
- Start the following consumer script.
```
package main

// Import Go and NATS packages
import (
	"fmt"
	"runtime"

	"github.com/nats-io/go-nats-streaming"
)

func main() {

	var stanConnection stan.Conn
	
	subscribe := func() {
		fmt.Printf("Subscribing to subject 'bucketevents'\n")
		stanConnection.Subscribe("bucketevents", func(m *stan.Msg) {

			// Handle the message
			fmt.Printf("Received a message: %s\n", string(m.Data))
		})
	}

	stanConnection, _ = stan.Connect("test-cluster", "test-client", stan.NatsURL("nats://yourusername:yoursecret@0.0.0.0:4222"), stan.SetConnectionLostHandler(func(c stan.Conn, _ error) {
		go func() {
			for {
				// Reconnect if the connection is lost.
				if stanConnection == nil || stanConnection.NatsConn() == nil ||  !stanConnection.NatsConn().IsConnected() {
					stanConnection, _ = stan.Connect("test-cluster", "test-client", stan.NatsURL("nats://yourusername:yoursecret@0.0.0.0:4222"), stan.SetConnectionLostHandler(func(c stan.Conn, _ error) {
						if c.NatsConn() != nil {
							c.NatsConn().Close()
						}
						_ = c.Close()
					}))
					if stanConnection != nil {
						subscribe()
					}
					
				}
			}
			
		}()
	}))
	
	// Subscribe to subject
	subscribe()

	// Keep the connection alive
	runtime.Goexit()
}

```
- Enable bucket notification using mc
- Start sending events
- The events will persist in /tmp/nats and gets replayed when the broker is turned on. (/tmp/nats - will be empty if all the events are successfully sent)
- Start the broker
- The evens will be replayed as you can see in consumer console.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-05-03 11:00 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#010542f5-026a-43ca-aaeb-baadd1437d69) |
<a name="010542f5-026a-43ca-aaeb-baadd1437d69"></a>
### 7612-dc69303/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31721
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 60df0b0e2625:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-sia0ahx1oft2bh",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360009,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159B26417DEEFB93, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-05-03 14:15 UTC, kannappanr commented
@Praveenrajmani Please resolve the conflict

2019-05-03 19:47 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-05-06 05:19 UTC, nitisht requested changes

2019-05-06 05:19 UTC, nitisht commented on docs/bucket/notifications/README.md
> +> > > > > > > dc693038... Enable event-persistence in NATS and NATS-Streaming
Stale diff seems to be added here

2019-05-06 10:29 UTC, Praveenrajmani commented on docs/bucket/notifications/README.md
> +> > > > > > > dc693038... Enable event-persistence in NATS and NATS-Streaming
removed :+1:

2019-05-06 11:05 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-05-21 06:20 UTC, nitisht commented
blocked till #7658 is merged

2019-05-23 12:31 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#5f920cba-70e8-43f5-9cd7-70354a89099e) |
<a name="5f920cba-70e8-43f5-9cd7-70354a89099e"></a>
### 7612-fc29f50/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31264
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b36214cd79c9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 1 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 9 seconds
{
  "name": "mc",
  "duration": "111821",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-13400 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-25352  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-25352/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-25352/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-25352/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-25352/datafile-1-b`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-25352/datafile-100-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-25352/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-25352/datafile-1.03-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-25352/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-25352/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-25352/datafile-6-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-25352/datafile-10-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-25352/datafile-33-kB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-25352/datafile-65-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-25352/datafile-5243880-b`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 309.42 MiB, Speed: 2.77 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-05-23 14:17 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#e412bb86-c59f-470e-8b16-cfa70b0dc464) |
| mint-large-bucket.sh | :x: [more...](#4dac6ca0-fc81-4085-893c-a3afd38fc219) |
<a name="4dac6ca0-fc81-4085-893c-a3afd38fc219"></a>
### 7612-8422dc0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32306
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 76946e7b0ddd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 3 seconds
{
  "name": "mc",
  "duration": "100304",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-8563 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-24752  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-24752/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-24752/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-24752/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-24752/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-24752/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-24752/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-24752/datafile-11-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-24752/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-24752/datafile-100-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-24752/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-24752/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-24752/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-24752/datafile-65-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-24752/datafile-5243880-b`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Multiple disks failures, unable to write data.\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Multiple disks failures, unable to write data.\nTotal: 104.17 MiB, Transferred: 380.30 MiB, Speed: 3.79 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="e412bb86-c59f-470e-8b16-cfa70b0dc464"></a>
### 7612-8422dc0/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31899
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f6c5a1a9fd5d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 18 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5vyaihxek23bwn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 18445,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31899/aws-sdk-go-test-5vyaihxek23bwn: dial tcp 72.28.97.57:31899: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-05-30 16:46 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#81c02f10-f3d7-4422-90e2-ef01163f7854) |
| mint-dist-xl.sh | :x: [more...](#f92c8a2e-897c-4cea-bbea-34c614849f4a) |
<a name="81c02f10-f3d7-4422-90e2-ef01163f7854"></a>
### 7612-2d7e219/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30334
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7735b5d59cd4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 3 minutes and 0 seconds
{
  "name": "mc",
  "duration": "141161",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28159 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-2139  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-2139/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-2139/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-2139/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-2139/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-2139/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-2139/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-2139/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-2139/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-2139/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-2139/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-2139/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-2139/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-2139/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-2139/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-2139/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 524.11 MiB, Speed: 3.71 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="f92c8a2e-897c-4cea-bbea-34c614849f4a"></a>
### 7612-2d7e219/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32128
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4169aa1826df:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 0 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 53 seconds
(8/14) Running minio-dotnet tests ... done in 44 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 13 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 51 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 1311,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-36gmq66, objectName=minio-java-test-2i9h0mt, resource=/minio-java-test-36gmq66/minio-java-test-2i9h0mt, requestId=15A383A3DEEA36D7, hostId=7a35f932-e2fe-453d-93f1-0510df3a2613)\nrequest={method=DELETE, url=http://72.28.97.59:32128/minio-java-test-36gmq66/minio-java-test-2i9h0mt?uploadId=81edf098-f8c9-41b1-ae90-18814289965a, headers=Host: 72.28.97.59:32128\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190530T164355Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190530/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-30T16-23-42Z\nVary: Origin\nX-Amz-Request-Id: 15A383A3DEEA36D7\nX-Minio-Deployment-Id: 7a35f932-e2fe-453d-93f1-0510df3a2613\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 May 2019 16:43:56 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-06-10 06:28 UTC, Praveenrajmani commented
Resolved a conflict. PTAL @nitisht @balamurugana

2019-06-10 07:56 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#4915e500-42a9-4e11-b650-773ffc865f51) |
<a name="4915e500-42a9-4e11-b650-773ffc865f51"></a>
### 7612-270ca73/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31292
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f149044fd03d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "mc",
  "duration": "101869",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-16434 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-27517  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-27517/datafile-1-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-27517/datafile-1-kB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-27517/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-27517/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-27517/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-27517/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-27517/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-27517/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-27517/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-27517/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-27517/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-27517/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-27517/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-27517/datafile-65-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-27517/datafile-5243880-b`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 518.56 MiB, Speed: 5.09 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-06-21 06:26 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#aa5e2c56-ed8f-4e6f-88f6-008e8bf48aed) |
| mint-large-bucket.sh | :x: [more...](#f2383c01-7af0-4b1e-9b04-baedb3ac3060) |
| mint-worm.sh | :x: [more...](#eba4490f-20c3-4e8a-a124-e58c17484b41) |
| mint-dist-xl.sh | :x: [more...](#8a247e3e-2169-4e37-8128-4d0a4e6e5c85) |
<a name="aa5e2c56-ed8f-4e6f-88f6-008e8bf48aed"></a>
### 7612-2117c38/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31227
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 19f854604730:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-n9z3sm5wjrwhk9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3060,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31227/aws-sdk-go-test-n9z3sm5wjrwhk9: dial tcp 72.28.97.57:31227: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="8a247e3e-2169-4e37-8128-4d0a4e6e5c85"></a>
### 7612-2117c38/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30425
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 53141b4c8674:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 47 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 928,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1es43uf, objectName=minio-java-test-3v4t01e, resource=/minio-java-test-1es43uf/minio-java-test-3v4t01e, requestId=15AA2290F9E48969, hostId=81844ac2-576d-4e12-824f-706be2f0fe6a)\nrequest={method=DELETE, url=http://72.28.97.59:30425/minio-java-test-1es43uf/minio-java-test-3v4t01e?uploadId=55d7d46e-0a9c-46cf-93ff-3c44387b0175, headers=Host: 72.28.97.59:30425\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190621T062346Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190621/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-06-21T06-04-11Z\nVary: Origin\nX-Amz-Request-Id: 15AA2290F9E48969\nX-Minio-Deployment-Id: 81844ac2-576d-4e12-824f-706be2f0fe6a\nX-Xss-Protection: 1; mode=block\nDate: Fri, 21 Jun 2019 06:23:47 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="f2383c01-7af0-4b1e-9b04-baedb3ac3060"></a>
### 7612-2117c38/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30326
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 731d79cc6c4f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 57 seconds
{
  "name": "mc",
  "duration": "113765",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-12210 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-28838/mc-test-object-1878  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-28838/mc-test-object-1878`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume XfAxUlMo`"
}

Executed 6 out of 14 tests successfully.
```
<a name="eba4490f-20c3-4e8a-a124-e58c17484b41"></a>
### 7612-2117c38/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30680
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d03ba4c8b8fa:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-6z4g38bk2kr99g90y6zqwmvpvq8r6bzn72dajkiuqntxpgdeghacoji",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 2892,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30680/bucket-6z4g38bk2kr99g90y6zqwmvpvq8r6bzn72dajkiuqntxpgdeghacoji: dial tcp 72.28.97.57:30680: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
{"name": "7612-2117c38", "full_size": 63690167, "images": [{"size": 63690167, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 59628979, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-06-21T06:05:10.484752Z", "image_id": null, "v2": true}

2019-07-12 04:55 UTC, Praveenrajmani commented
resolved a conflict - PTAL @nitisht @balamurugana

2019-07-12 05:45 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#e112cb53-9d9a-4c9e-bf26-c9d3bac99e95) |
| mint-large-bucket.sh | :x: [more...](#114c7482-6fb1-4d23-8fa3-a32884d57912) |
<a name="114c7482-6fb1-4d23-8fa3-a32884d57912"></a>
### 7612-e9086fe/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31956
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6a7f1d6cb645:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 34 seconds
{
  "name": "mc",
  "duration": "121261",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-9054 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-4042  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-4042/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-4042/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-4042/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-4042/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-4042/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-4042/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-4042/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-4042/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-4042/datafile-129-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-4042/datafile-10-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-4042/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-4042/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-4042/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-4042/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-4042/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 514.86 MiB, Speed: 4.25 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="e112cb53-9d9a-4c9e-bf26-c9d3bac99e95"></a>
### 7612-e9086fe/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30039
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1000a2bd4e8c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-llzduxyg1pghpf",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360016,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B0926DFB7FB2A5, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-07-17 01:29 UTC, kannappanr commented
ping @nitisht @balamurugana

2019-07-17 03:45 UTC, nitisht approved these changes

2019-07-23 17:34 UTC, kannappanr commented on docs/bucket/notifications/README.md
> +		fmt.Printf("Subscribing to subject 'bucketevents'\n")
```suggestion
```

2019-07-23 17:37 UTC, kannappanr approved these changes
LGTM

2019-07-23 17:37 UTC, merged