Add unit tests and refactor to improve coverage
minio/minio pull request #7617
Opened 2019-05-03 19:58 UTC by donatello

- for admin-handlers.go

## Motivation and Context

Towards https://github.com/minio/minio/issues/7445

## Regression

No

2019-05-03 19:59 UTC, donatello commented on cmd/admin-handlers.go
> +		}
Some extra validation is added here so that invalid json is not accepted silently.

2019-05-04 02:01 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#77e00542-8dfd-4360-b7c0-1b16ed3ab540) |
<a name="77e00542-8dfd-4360-b7c0-1b16ed3ab540"></a>
### 7617-f5498aa/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31668
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 653000a1487e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bdp903t60nqdi2",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360011,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159B57AC43898CB1, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-05-07 18:25 UTC, ebozduman commented
@donatello,
I've checked the coverage after the new unit tests, and it jumped a little, per your expectations, from 15.6% to 22.3%.
Do you think this is all we can do ? 
If I am not missing anything, It looks to me like we can have more unit tests to cover:
- Case statement values and the case default values, in functions like `ServiceStopNRestartHandler`, `PerfInfoHandler`
- The error conditions/messages could be covered in functions like `ServiceStopNRestartHandler`
- Functions `TopLocksHandler`, `StartProfilingHandler`, `DownloadProfilingHandler`, ... et.al.

2019-05-07 18:26 UTC, ebozduman requested changes

2019-05-07 18:26 UTC, ebozduman commented on cmd/admin-handlers.go
> +	//   receiving logs, so cannot start of stop;
Couple of minor typos:

`// - Cannot`**have**`both forceStart and forceStop in the same request;`
`// - If clientToken is provided, request`~~is~~ **can**`only`**be**`to continue receiving logs, so`**it**`cannot`**be**`start`~~of~~ **or**`stop;`

2019-05-07 18:59 UTC, donatello commented on cmd/admin-handlers.go
> +	//   receiving logs, so cannot start of stop;
Fixed.

2019-05-07 19:01 UTC, donatello commented
> I've checked the coverage after the new unit tests, and it jumped a little, per your expectations, from 15.6% to 22.3%.
> Do you think this is all we can do ?

@ebozduman We cannot do more without writing functional style tests involving a large amount of mocking (of object layer, etc). Currently we are planning to move all such functional tests into mint instead of in the server code.

2019-05-07 19:43 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#f5eda434-c585-4ca2-b0d3-649f2a4955f4) |
<a name="f5eda434-c585-4ca2-b0d3-649f2a4955f4"></a>
### 7617-1dba9c2/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30540
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 13480ecc640e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-oyttulg9poi1zc",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360010,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 159C7D4D2AD91B1B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-05-07 20:48 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-05-07 21:29 UTC, ebozduman commented
It looks like there are 21 functions/api handlers in `admin-handlers.go` file and 6 unit tests were already created for 6 apis by having mock up data to validate admin requests that appears at the beginning of each api implementation.
However, no unit tests are created for the rest of the 15 apis. That's because we wanted to stay away from creating or using mock up data.
This is inconsistent and we need to make a decision on whether to give up mock up data and remove the already existing 6 unit tests or accept using mock-up data and create 15 more unit tests to cover all 21.
We need to talk to Ab.

2019-05-23 18:53 UTC, ebozduman commented
@abperiasamy wants to remove 6/21 existing api tests which uses the mock-up data and setup. These tests do not qualify to be unit tests. They are supposed to be part of the mint/functional tests.

However, I am not sure if we would like to remove 6 api unit tests right away, since immediately removing  them would mean we won't be able to test those 6 apis until the functional tests are written and ready to be run.

I suggest the removal of unit tests to be done only when the functional tests are ready to run. 
I'll confirm this with @abperiasamy.

2019-07-11 16:56 UTC, harshavardhana commented
If we are not taking this PR in shall we close this? @ebozduman @donatello ?

2019-07-12 18:53 UTC, ebozduman commented
Actually @donatello 's fix is pure unit test.
(!Please confirm @donatello!)
We'll touch and remove the unit tests which runs with mock up data. So, I suggest to accept this PR, additional unit tests @donatello worked on. 

@vadmeste, @donatello  ???

2019-08-09 19:44 UTC, harshavardhana commented
Please review @ebozduman @vadmeste

2019-08-12 02:42 UTC, ebozduman approved these changes
LGTM

2019-08-13 21:28 UTC, donatello commented
Rebased this PR onto master. It is only a unit test change.

2019-08-13 21:29 UTC, donatello commented
PTAL @vadmeste

2019-08-13 22:15 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#6ce0f1c2-013b-4ec7-b0fd-ed26914d0017) |
| mint-large-bucket.sh | :x: [more...](#18da9d47-5395-4dda-8c46-1149a7dc0462) |
| mint-compression-dist-xl.sh | :x: [more...](#f976a098-031e-450b-8edc-92f6a1923f48) |
| mint-worm.sh | :x: [more...](#952edfed-fb19-46d5-ae79-dd70024b612d) |
| mint-dist-xl.sh | :x: [more...](#d51346d3-8a31-47d6-ae31-34901508c00c) |
<a name="f976a098-031e-450b-8edc-92f6a1923f48"></a>
### 7617-4f32028/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31943
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 95a9747adaf4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... FAILED in 48 seconds
{"name": "awscli", "duration": 4141, "function": "aws --endpoint-url http://72.28.97.55:31943 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-15944/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (1.5 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (2.5 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (3.3 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (4.1 MiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (5.0 MiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (5.5 MiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (6.0 MiB/s) with 1 file(s) remaining  
Completed 2.0 MiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining  
Completed 2.2 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining  
Completed 2.5 MiB/65.0 MiB (7.7 MiB/s) with 1 file(s) remaining  
Completed 2.8 MiB/65.0 MiB (8.2 MiB/s) with 1 file(s) remaining  
Completed 3.0 MiB/65.0 MiB (8.6 MiB/s) with 1 file(s) remaining  
Completed 3.2 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining  
Completed 3.5 MiB/65.0 MiB (9.4 MiB/s) with 1 file(s) remaining  
Completed 3.8 MiB/65.0 MiB (9.8 MiB/s) with 1 file(s) remaining  
Completed 4.0 MiB/65.0 MiB (10.1 MiB/s) with 1 file(s) remaining 
Completed 4.2 MiB/65.0 MiB (10.5 MiB/s) with 1 file(s) remaining 
Completed 4.5 MiB/65.0 MiB (10.7 MiB/s) with 1 file(s) remaining 
Completed 4.8 MiB/65.0 MiB (11.2 MiB/s) with 1 file(s) remaining 
Completed 5.0 MiB/65.0 MiB (11.5 MiB/s) with 1 file(s) remaining 
Completed 5.2 MiB/65.0 MiB (11.7 MiB/s) with 1 file(s) remaining 
Completed 5.5 MiB/65.0 MiB (12.2 MiB/s) with 1 file(s) remaining 
Completed 5.8 MiB/65.0 MiB (12.4 MiB/s) with 1 file(s) remaining 
Completed 6.0 MiB/65.0 MiB (12.9 MiB/s) with 1 file(s) remaining 
Completed 6.2 MiB/65.0 MiB (13.2 MiB/s) with 1 file(s) remaining 
Completed 6.5 MiB/65.0 MiB (13.6 MiB/s) with 1 file(s) remaining 
Completed 6.8 MiB/65.0 MiB (13.9 MiB/s) with 1 file(s) remaining 
Completed 7.0 MiB/65.0 MiB (14.3 MiB/s) with 1 file(s) remaining 
Completed 7.2 MiB/65.0 MiB (14.7 MiB/s) with 1 file(s) remaining 
Completed 7.5 MiB/65.0 MiB (14.8 MiB/s) with 1 file(s) remaining 
Completed 7.8 MiB/65.0 MiB (15.2 MiB/s) with 1 file(s) remaining 
Completed 8.0 MiB/65.0 MiB (15.4 MiB/s) with 1 file(s) remaining 
Completed 8.2 MiB/65.0 MiB (15.9 MiB/s) with 1 file(s) remaining 
Completed 8.5 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining 
Completed 8.8 MiB/65.0 MiB (16.5 MiB/s) with 1 file(s) remaining 
Completed 9.0 MiB/65.0 MiB (16.7 MiB/s) with 1 file(s) remaining 
Completed 9.2 MiB/65.0 MiB (17.1 MiB/s) with 1 file(s) remaining 
Completed 9.5 MiB/65.0 MiB (17.3 MiB/s) with 1 file(s) remaining 
Completed 9.8 MiB/65.0 MiB (17.6 MiB/s) with 1 file(s) remaining 
Completed 10.0 MiB/65.0 MiB (17.7 MiB/s) with 1 file(s) remaining
Completed 10.2 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining
Completed 10.5 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining
Completed 10.8 MiB/65.0 MiB (18.5 MiB/s) with 1 file(s) remaining
Completed 11.0 MiB/65.0 MiB (18.6 MiB/s) with 1 file(s) remaining
Completed 11.2 MiB/65.0 MiB (18.9 MiB/s) with 1 file(s) remaining
Completed 11.5 MiB/65.0 MiB (18.9 MiB/s) with 1 file(s) remaining
Completed 11.8 MiB/65.0 MiB (19.2 MiB/s) with 1 file(s) remaining
Completed 12.0 MiB/65.0 MiB (19.2 MiB/s) with 1 file(s) remaining
Completed 12.2 MiB/65.0 MiB (19.6 MiB/s) with 1 file(s) remaining
Completed 12.5 MiB/65.0 MiB (19.8 MiB/s) with 1 file(s) remaining
Completed 12.8 MiB/65.0 MiB (20.1 MiB/s) with 1 file(s) remaining
Completed 13.0 MiB/65.0 MiB (20.4 MiB/s) with 1 file(s) remaining
Completed 13.2 MiB/65.0 MiB (20.6 MiB/s) with 1 file(s) remaining
Completed 13.5 MiB/65.0 MiB (20.8 MiB/s) with 1 file(s) remaining
Completed 13.8 MiB/65.0 MiB (21.0 MiB/s) with 1 file(s) remaining
Completed 14.0 MiB/65.0 MiB (21.4 MiB/s) with 1 file(s) remaining
Completed 14.2 MiB/65.0 MiB (21.6 MiB/s) with 1 file(s) remaining
Completed 14.5 MiB/65.0 MiB (21.9 MiB/s) with 1 file(s) remaining
Completed 14.8 MiB/65.0 MiB (22.3 MiB/s) with 1 file(s) remaining
Completed 15.0 MiB/65.0 MiB (22.5 MiB/s) with 1 file(s) remaining
Completed 15.2 MiB/65.0 MiB (22.7 MiB/s) with 1 file(s) remaining
Completed 15.5 MiB/65.0 MiB (22.8 MiB/s) with 1 file(s) remaining
Completed 15.8 MiB/65.0 MiB (23.0 MiB/s) with 1 file(s) remaining
Completed 16.0 MiB/65.0 MiB (23.3 MiB/s) with 1 file(s) remaining
Completed 16.2 MiB/65.0 MiB (23.5 MiB/s) with 1 file(s) remaining
Completed 16.5 MiB/65.0 MiB (23.7 MiB/s) with 1 file(s) remaining
Completed 16.8 MiB/65.0 MiB (24.0 MiB/s) with 1 file(s) remaining
Completed 17.0 MiB/65.0 MiB (24.2 MiB/s) with 1 file(s) remaining
Completed 17.2 MiB/65.0 MiB (22.4 MiB/s) with 1 file(s) remaining
Completed 17.5 MiB/65.0 MiB (22.6 MiB/s) with 1 file(s) remaining
Completed 17.8 MiB/65.0 MiB (22.8 MiB/s) with 1 file(s) remaining
Completed 18.0 MiB/65.0 MiB (23.0 MiB/s) with 1 file(s) remaining
Completed 18.2 MiB/65.0 MiB (23.3 MiB/s) with 1 file(s) remaining
Completed 18.5 MiB/65.0 MiB (23.5 MiB/s) with 1 file(s) remaining
Completed 18.8 MiB/65.0 MiB (23.7 MiB/s) with 1 file(s) remaining
Completed 19.0 MiB/65.0 MiB (24.0 MiB/s) with 1 file(s) remaining
Completed 19.2 MiB/65.0 MiB (24.2 MiB/s) with 1 file(s) remaining
Completed 19.5 MiB/65.0 MiB (24.4 MiB/s) with 1 file(s) remaining
Completed 19.8 MiB/65.0 MiB (24.6 MiB/s) with 1 file(s) remaining
Completed 20.0 MiB/65.0 MiB (24.8 MiB/s) with 1 file(s) remaining
Completed 20.2 MiB/65.0 MiB (25.1 MiB/s) with 1 file(s) remaining
Completed 20.5 MiB/65.0 MiB (25.3 MiB/s) with 1 file(s) remaining
Completed 20.8 MiB/65.0 MiB (25.5 MiB/s) with 1 file(s) remaining
Completed 21.0 MiB/65.0 MiB (25.7 MiB/s) with 1 file(s) remaining
Completed 21.2 MiB/65.0 MiB (25.9 MiB/s) with 1 file(s) remaining
Completed 21.5 MiB/65.0 MiB (26.2 MiB/s) with 1 file(s) remaining
Completed 21.8 MiB/65.0 MiB (26.4 MiB/s) with 1 file(s) remaining
Completed 22.0 MiB/65.0 MiB (26.6 MiB/s) with 1 file(s) remaining
Completed 22.2 MiB/65.0 MiB (26.8 MiB/s) with 1 file(s) remaining
Completed 22.5 MiB/65.0 MiB (27.0 MiB/s) with 1 file(s) remaining
Completed 22.8 MiB/65.0 MiB (27.2 MiB/s) with 1 file(s) remaining
Completed 23.0 MiB/65.0 MiB (27.4 MiB/s) with 1 file(s) remaining
Completed 23.2 MiB/65.0 MiB (27.6 MiB/s) with 1 file(s) remaining
Completed 23.5 MiB/65.0 MiB (27.8 MiB/s) with 1 file(s) remaining
Completed 23.8 MiB/65.0 MiB (28.0 MiB/s) with 1 file(s) remaining
Completed 24.0 MiB/65.0 MiB (28.2 MiB/s) with 1 file(s) remaining
Completed 24.2 MiB/65.0 MiB (28.4 MiB/s) with 1 file(s) remaining
Completed 24.5 MiB/65.0 MiB (28.6 MiB/s) with 1 file(s) remaining
Comp [...]

2019-08-21 23:46 UTC, donatello commented
@vadmeste PTAL

2019-08-22 00:35 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c1c4c649-b655-4de9-87f1-06d2510582ab) |
| mint-dist-xl.sh | :x: [more...](#f8d8bd9c-0845-4bdd-8841-7f75395a5f42) |
<a name="f8d8bd9c-0845-4bdd-8841-7f75395a5f42"></a>
### 7617-f21bc99/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31900
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a447a1b4c675:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... FAILED in 58 seconds
{"name": "awscli", "duration": 8964, "function": "aws --endpoint-url http://72.28.97.58:31900 s3 sync /mint/data s3://awscli-mint-test-bucket-7927/\n", "status": "FAIL", "error": "Completed 256.0 KiB/233.2 MiB (5.2 MiB/s) with 15 file(s) remaining
Completed 512.0 KiB/233.2 MiB (10.0 MiB/s) with 15 file(s) remaining
Completed 768.0 KiB/233.2 MiB (14.2 MiB/s) with 15 file(s) remaining
Completed 1.0 MiB/233.2 MiB (18.8 MiB/s) with 15 file(s) remaining  
Completed 1.2 MiB/233.2 MiB (20.8 MiB/s) with 15 file(s) remaining  
Completed 1.5 MiB/233.2 MiB (24.9 MiB/s) with 15 file(s) remaining  
upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-7927/datafile-0-bCompleted 1.5 MiB/233.2 MiB (24.9 MiB/s) with 14 file(s) remaining
Completed 1.8 MiB/233.2 MiB (26.7 MiB/s) with 14 file(s) remaining
Completed 2.0 MiB/233.2 MiB (30.2 MiB/s) with 14 file(s) remaining
Completed 2.0 MiB/233.2 MiB (19.4 MiB/s) with 14 file(s) remaining
Completed 2.0 MiB/233.2 MiB (19.0 MiB/s) with 14 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-7927/datafile-1-kBCompleted 2.0 MiB/233.2 MiB (19.0 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-7927/datafile-1-bCompleted 2.0 MiB/233.2 MiB (19.0 MiB/s) with 12 file(s) remaining
Completed 2.3 MiB/233.2 MiB (14.7 MiB/s) with 12 file(s) remaining
Completed 2.5 MiB/233.2 MiB (15.9 MiB/s) with 12 file(s) remaining
Completed 2.8 MiB/233.2 MiB (17.1 MiB/s) with 12 file(s) remaining
Completed 2.8 MiB/233.2 MiB (17.1 MiB/s) with 12 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-7927/datafile-1.03-MBCompleted 2.8 MiB/233.2 MiB (17.1 MiB/s) with 11 file(s) remaining
Completed 2.8 MiB/233.2 MiB (16.6 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-7927/datafile-10-kBCompleted 2.8 MiB/233.2 MiB (16.6 MiB/s) with 10 file(s) remaining
Completed 2.9 MiB/233.2 MiB (17.1 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-7927/datafile-100-kBCompleted 2.9 MiB/233.2 MiB (17.1 MiB/s) with 9 file(s) remaining
Completed 3.1 MiB/233.2 MiB (18.4 MiB/s) with 9 file(s) remaining
Completed 3.4 MiB/233.2 MiB (19.6 MiB/s) with 9 file(s) remaining
Completed 3.6 MiB/233.2 MiB (21.0 MiB/s) with 9 file(s) remaining
Completed 3.9 MiB/233.2 MiB (22.2 MiB/s) with 9 file(s) remaining
Completed 4.1 MiB/233.2 MiB (23.6 MiB/s) with 9 file(s) remaining
Completed 4.4 MiB/233.2 MiB (24.6 MiB/s) with 9 file(s) remaining
Completed 4.6 MiB/233.2 MiB (26.0 MiB/s) with 9 file(s) remaining
Completed 4.9 MiB/233.2 MiB (27.1 MiB/s) with 9 file(s) remaining
Completed 5.1 MiB/233.2 MiB (28.0 MiB/s) with 9 file(s) remaining
Completed 5.4 MiB/233.2 MiB (28.8 MiB/s) with 9 file(s) remaining
Completed 5.6 MiB/233.2 MiB (30.0 MiB/s) with 9 file(s) remaining
Completed 5.9 MiB/233.2 MiB (31.1 MiB/s) with 9 file(s) remaining
Completed 6.1 MiB/233.2 MiB (32.2 MiB/s) with 9 file(s) remaining
Completed 6.4 MiB/233.2 MiB (33.0 MiB/s) with 9 file(s) remaining
Completed 6.6 MiB/233.2 MiB (33.8 MiB/s) with 9 file(s) remaining
Completed 6.9 MiB/233.2 MiB (35.0 MiB/s) with 9 file(s) remaining
Completed 7.1 MiB/233.2 MiB (35.9 MiB/s) with 9 file(s) remaining
Completed 7.4 MiB/233.2 MiB (36.6 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-7927/datafile-1-MBCompleted 7.4 MiB/233.2 MiB (36.6 MiB/s) with 8 file(s) remaining
Completed 7.4 MiB/233.2 MiB (35.7 MiB/s) with 8 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-7927/datafile-33-kBCompleted 7.4 MiB/233.2 MiB (35.7 MiB/s) with 7 file(s) remaining
Completed 7.7 MiB/233.2 MiB (36.2 MiB/s) with 7 file(s) remaining
Completed 7.9 MiB/233.2 MiB (37.1 MiB/s) with 7 file(s) remaining
Completed 8.2 MiB/233.2 MiB (37.8 MiB/s) with 7 file(s) remaining
Completed 8.4 MiB/233.2 MiB (39.0 MiB/s) with 7 file(s) remaining
Completed 8.7 MiB/233.2 MiB (39.9 MiB/s) with 7 file(s) remaining
Completed 8.9 MiB/233.2 MiB (40.4 MiB/s) with 7 file(s) remaining
Completed 9.2 MiB/233.2 MiB (41.5 MiB/s) with 7 file(s) remaining
Completed 9.4 MiB/233.2 MiB (42.4 MiB/s) with 7 file(s) remaining
Completed 9.7 MiB/233.2 MiB (42.5 MiB/s) with 7 file(s) remaining
Completed 9.9 MiB/233.2 MiB (43.3 MiB/s) with 7 file(s) remaining
Completed 10.2 MiB/233.2 MiB (43.4 MiB/s) with 7 file(s) remaining
Completed 10.4 MiB/233.2 MiB (43.0 MiB/s) with 7 file(s) remaining
Completed 10.7 MiB/233.2 MiB (42.1 MiB/s) with 7 file(s) remaining
Completed 10.9 MiB/233.2 MiB (40.8 MiB/s) with 7 file(s) remaining
Completed 11.2 MiB/233.2 MiB (41.7 MiB/s) with 7 file(s) remaining
Completed 11.4 MiB/233.2 MiB (41.9 MiB/s) with 7 file(s) remaining
Completed 11.7 MiB/233.2 MiB (40.9 MiB/s) with 7 file(s) remaining
Completed 11.9 MiB/233.2 MiB (41.0 MiB/s) with 7 file(s) remaining
Completed 12.2 MiB/233.2 MiB (40.5 MiB/s) with 7 file(s) remaining
Completed 12.4 MiB/233.2 MiB (41.2 MiB/s) with 7 file(s) remaining
Completed 12.7 MiB/233.2 MiB (41.4 MiB/s) with 7 file(s) remaining
Completed 12.9 MiB/233.2 MiB (41.6 MiB/s) with 7 file(s) remaining
Completed 13.2 MiB/233.2 MiB (41.6 MiB/s) with 7 file(s) remaining
Completed 13.4 MiB/233.2 MiB (41.9 MiB/s) with 7 file(s) remaining
Completed 13.7 MiB/233.2 MiB (42.5 MiB/s) with 7 file(s) remaining
Completed 13.9 MiB/233.2 MiB (42.7 MiB/s) with 7 file(s) remaining
Completed 14.2 MiB/233.2 MiB (42.8 MiB/s) with 7 file(s) remaining
Completed 14.4 MiB/233.2 MiB (43.5 MiB/s) with 7 file(s) remaining
Completed 14.7 MiB/233.2 MiB (43.1 MiB/s) with 7 file(s) remaining
Completed 14.9 MiB/233.2 MiB (43.7 MiB/s) with 7 file(s) remaining
Completed 15.2 MiB/233.2 MiB (44.3 MiB/s) with 7 file(s) remaining
Completed 15.4 MiB/233.2 MiB (44.6 MiB/s) with 7 file(s) remaining
Completed 15.7 MiB/233.2 MiB (45.2 MiB/s) with 7 file(s) remaining
Completed 15.9 MiB/233.2 MiB (44.9 MiB/s) with 7 file(s) remaining
Completed 16.2 MiB/233.2 MiB (45.0 MiB/s) with 7 file(s) remaining
Completed 16.4 MiB/233.2 MiB (45.4 MiB/s) with 7 file(s) remaining
Completed 16.7 MiB/233.2 MiB (46.1 MiB/s) with 7 file(s) remaining
Completed 16.9 MiB/233.2 MiB (46.1 MiB/s) with 7 file(s) remaining
Completed 17.2 MiB/233.2 MiB (45.9 MiB/s) with 7 file(s) remaining
Completed 17.4 MiB/233.2 MiB (46.6 MiB/s) with 7 file(s) remaining
Completed 17.7 MiB/233.2 MiB (46.9 MiB/s) with 7 file(s) remaining
Completed 17.9 MiB/233.2 MiB (47.5 MiB/s) with 7 file(s) remaining
Completed 18.2 MiB/233.2 MiB (48.1 MiB/s) with 7 file(s) remaining
Completed 18.4 MiB/233.2 MiB (48.2 MiB/s) with 7 file(s) remaining
Completed 18.7 MiB/233.2 MiB (48.6 MiB/s) with 7 file(s) remaining
Completed 18.9 MiB/233.2 MiB (49.2 MiB/s) [...]

2019-08-22 06:38 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#99814463-78b2-42c9-99e3-9fdfccd20506) |
<a name="99814463-78b2-42c9-99e3-9fdfccd20506"></a>
### 7617-16151ee/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31963
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dbc1f196c852:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 15 seconds
(4/14) Running aws-sdk-ruby tests ... done in 20 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 33 seconds
{
  "name": "mc",
  "duration": "98648",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-22361 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-14150  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-14150/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-14150/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-14150/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-14150/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-14150/datafile-1-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-14150/datafile-100-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-14150/datafile-10-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-14150/datafile-129-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-14150/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-14150/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-14150/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-14150/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-14150/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-14150/datafile-65-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-14150/datafile-33-kB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 444.25 MiB, Speed: 4.51 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-08-22 09:32 UTC, harshavardhana commented
ping @vadmeste

2019-08-29 16:13 UTC, harshavardhana approved these changes

2019-08-29 17:28 UTC, minio-ops commented
```
Error running mint automation
+ mkdir -p 7617-0694818/gopath/src/github.com/minio
+ git -C 7617-0694818/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 7617-0694818/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 7617-0694818/gopath/src/github.com/minio/minio fetch --quiet minio pull/7617/head:pr7617
+ git -C 7617-0694818/gopath/src/github.com/minio/minio checkout --quiet pr7617
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/7617-0694818/gopath
+ make -C 7617-0694818/gopath/src/github.com/minio/minio --quiet
go: finding github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding github.com/Azure/go-autorest v11.7.0+incompatible
go: finding github.com/sirupsen/logrus v1.4.2
go: finding github.com/gorilla/mux v1.7.0
go: finding github.com/golang/snappy v0.0.1
go: finding github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: finding github.com/minio/mc v0.0.0-20190529152718-f4bb0b8850cb
go: finding github.com/elazarl/go-bindata-assetfs v1.0.0
go: finding gopkg.in/Shopify/sarama.v1 v1.20.0
go: finding github.com/DataDog/zstd v1.4.0
go: finding github.com/klauspost/compress v1.5.0
go: finding github.com/minio/sha256-simd v0.1.0
go: finding github.com/minio/parquet-go v0.0.0-20190318185229-9d767baf1679
go: finding github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: finding github.com/nats-io/gnatsd v1.4.1
go: finding contrib.go.opencensus.io/exporter/ocagent v0.5.0
go: finding github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: finding golang.org/x/net v0.0.0-20190522155817-f3200d17e092
go: finding github.com/hashicorp/go-version v1.1.0
go: finding github.com/minio/lsync v1.0.1
go: finding github.com/nats-io/nats-server v1.4.1
go: finding github.com/minio/cli v1.21.0
go: finding golang.org/x/sys v0.0.0-20190422165155-953cdadca894
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: finding github.com/minio/gokrb5/v7 v7.2.5
go: finding github.com/grpc-ecosystem/grpc-gateway v1.8.5
go: finding github.com/minio/hdfs/v3 v3.0.1
go: finding github.com/klauspost/cpuid v1.2.1
go: finding golang.org/x/sys v0.0.0-20190304154630-e844e0132e93
go: finding go.uber.org/zap v1.10.0
go: finding gopkg.in/ini.v1 v1.42.0
go: finding golang.org/x/crypto v0.0.0-20190308221718-c2843e01d9a2
go: finding github.com/posener/complete v1.2.1
go: finding github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding go.opencensus.io v0.21.0
go: finding github.com/lib/pq v1.0.0
go: finding github.com/jtolds/gls v4.20.0+incompatible
go: finding github.com/rs/cors v1.6.0
go: finding github.com/gorilla/handlers v1.4.0
go: finding github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: finding golang.org/x/sys v0.0.0-20181107165924-66b7b1311ac8
go: finding google.golang.org/api v0.4.0
go: finding github.com/hashicorp/go-sockaddr v1.0.2
go: finding github.com/golang/protobuf v1.3.1
go: finding github.com/tidwall/gjson v1.2.1
go: finding go.uber.org/atomic v1.3.2
go: finding github.com/pkg/profile v1.3.0
go: finding golang.org/x/net v0.0.0-20190827160401-ba9fcec4b297
go: finding github.com/segmentio/go-prompt v1.2.1-0.20161017233205-f0d19b6901ad
go: finding golang.org/x/crypto v0.0.0-20190228161510-8dd112bcdc25
go: finding github.com/hashicorp/raft v1.1.0
go: finding github.com/hashicorp/vault v1.1.0
go: finding github.com/coreos/go-semver v0.3.0
go: finding github.com/mattn/go-isatty v0.0.7
go: finding github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: finding github.com/golang/protobuf v1.2.0
go: finding cloud.google.com/go v0.37.2
go: finding github.com/coreos/go-systemd v0.0.0-20190321100706-95778dfbb74e
go: finding github.com/go-sql-driver/mysql v1.4.1
go: finding golang.org/x/sync v0.0.0-20190423024810-112230192c58
go: finding google.golang.org/genproto v0.0.0-20180817151627-c66870c02cf8
go: finding gopkg.in/olivere/elastic.v5 v5.0.80
go: finding github.com/minio/minio v0.0.0-20190510004154-ac3b59645e92
go: finding github.com/klauspost/pgzip v1.2.1
go: finding golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586
go: finding github.com/hashicorp/hcl v1.0.0
go: finding go.etcd.io/bbolt v1.3.3
go: finding github.com/rjeczalik/notify v0.9.2
go: finding github.com/coreos/bbolt v1.3.3
go: finding gopkg.in/urfave/cli.v1 v1.20.0
go: finding github.com/prometheus/common v0.2.0
go: finding golang.org/x/sys v0.0.0-20190215142949-d0b11bdaac8a
go: finding github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: finding github.com/tidwall/pretty v1.0.0
go: finding github.com/pborman/getopt v0.0.0-20180729010549-6fdd0a2c7117
go: finding golang.org/x/oauth2 v0.0.0-20190226205417-e64efc72b421
go: finding google.golang.org/grpc v1.19.0
go: finding golang.org/x/sys v0.0.0-20180926160741-c2ed4eda69e7
go: finding github.com/google/go-cmp v0.2.0
go: finding github.com/minio/minio-go/v6 v6.0.29
go: finding honnef.co/go/tools v0.0.0-20190106161140-3f1c8253044a
go: finding github.com/mitchellh/cli v1.0.0
go: finding github.com/hashicorp/errwrap v1.0.0
go: finding github.com/fatih/structs v1.1.0
go: finding github.com/Azure/azure-sdk-for-go v27.0.0+incompatible
go: finding github.com/cheggaaa/pb v1.0.28
go: finding github.com/valyala/fastjson v1.4.1
go: finding go.opencensus.io v0.19.2
go: finding github.com/djherbis/atime v1.0.0
go: finding github.com/aws/aws-sdk-go v1.20.21
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/go-kit/kit v0.8.0
go: finding honnef.co/go/tools v0.0.0-20190102054323-c2f93a96b099
go: finding github.com/stretchr/objx v0.1.1
go: finding github.com/stretchr/testify v1.3.0
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding github.com/smartystreets/goconvey v0.0.0-20190330032615-68dc04aab96a
go: finding github.com/gernest/wow v0.1.0
go: finding github.com/minio/minio-go/v6 v6.0.26
go: finding gopkg.in/h2non/filetype.v1 v1.0.5
go: finding golang.org/x/sys v0.0.0-20180830151530-49385e6e1522
go: finding google.golang.org/api v0.3.0
go: finding github.com/tidwall/sjson v1.0.4
go: finding github.com/golang/protobuf v1.1.0
go: finding github.com/fatih/color v1.7.0
go: finding github.com/posener/complete v1.1.1
go: finding github.com/satori/go.uuid v1.2.0
go: finding github.com/dnaeon/go-vcr v1.0.1
go: finding github.com/kr/logfmt v0.0.0-20140226030751-b84e30acd515
go: finding golang.org/x/lint v0.0.0-20181026193005-c67002cb31c3
go: finding github.com/apache/thrift v0.12.0
go: finding github.com/eapache/go-resiliency v1.2.0
go: finding github.com/coredns/coredns v1.4.0
go: finding gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: finding github.com/ncw/directio v1.0.5
go: finding github.com/dustin/go-humanize v1.0.0
go: finding golang.org/x/tools v0.0.0-20190114222345-bf090417da8b
go: finding github.com/hashicorp/go-uuid v1.0.1
go: finding gopkg.in/check.v1 v0.0.0-20161208181325-20d25e280405
go: finding github.com/pkg/errors v0.8.0
go: finding github.com/golang/mock v1.2.0
go: finding github.com/minio/sio v0.2.0
go: finding github.com/gomodule/redigo v2.0.0+incompatible
go: finding github.com/prometheus/client_golang v0.9.1
go: finding github.com/nsqio/go-nsq v1.0.7
go: finding golang.org/x/text v0.3.1-0.20180807135948-17ff2d5776d2
go: finding golang.org/x/net v0.0.0-20181220203305-927f97764cc3
go: finding github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf
go: finding gopkg.in/jcmturner/aescts.v1 v1.0.1
go: finding golang.org/x/text v0.3.0
go: finding github.com/rogpeppe/fastuuid v0.0.0-20150106093220-6724a57986af
go: finding github.com/minio/cli v1.20.0
go: finding golang.org/x/tools v0.0.0-20190312170243-e65039ee4138
go: finding golang.org/x/crypto v0.0.0-20190103213133-ff983b9c42bc
go: finding golang.org/x/net v0.0.0-20190125091013-d26f9f9a57f3
go [...]

2019-08-29 17:32 UTC, harshavardhana commented
ping @donatello PTAL

2019-08-29 19:25 UTC, donatello commented
@harshavardhana Build passed!

2019-08-29 20:31 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#781aff52-034c-4eed-8287-97210876b83b) |
<a name="781aff52-034c-4eed-8287-97210876b83b"></a>
### 7617-b122658/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31781
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 12b771216b0e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 14 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 25 seconds
(9/14) Running minio-go tests ... done in 2 minutes and 22 seconds
(10/14) Running minio-java tests ... done in 3 minutes and 47 seconds
(11/14) Running minio-js tests ... done in 51 seconds
(12/14) Running minio-py tests ... FAILED in 5 minutes and 7 seconds
{
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 394, in test_copy_object_with_metadata\n    client.put_object(bucket_name, object_source, KB_1_reader, KB_1)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 838, in put_object\n    progress=progress)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1551, in _do_put_object\n    content_sha256=sha256_hex\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1901, in _url_open\n    object_name).get_exception()\nminio.error.IncompleteBody: IncompleteBody: message: You did not provide the number of bytes specified by the Content-Length HTTP header\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1838, in main\n    test_copy_object_with_metadata(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 404, in test_copy_object_with_metadata\n    raise Exception(err)\nException: IncompleteBody: message: You did not provide the number of bytes specified by the Content-Length HTTP header\n",
  "name": "minio-py:test_copy_object_with_metadata",
  "function": "copy_object(bucket_name, object_name, object_source, conditions, source_sse, sse, metadata)",
  "message": "IncompleteBody: message: You did not provide the number of bytes specified by the Content-Length HTTP header",
  "args": {
    "bucket_name": "minio-py-test-998576f0-a02c-4494-941c-62e505795705",
    "object_name": "0bd953a8-6405-43aa-a2ea-448c8d4a1665-copy",
    "object_source": "0bd953a8-6405-43aa-a2ea-448c8d4a1665-source",
    "metadata": {
      "testing-string": "string",
      "testing-int": 1
    }
  },
  "duration": 876
}

Executed 11 out of 14 tests successfully.
```

2019-08-29 20:53 UTC, merged