Enable event persistence in MySQL and PostgreSQL
minio/minio pull request #7629
Opened 2019-05-08 13:58 UTC by Praveenrajmani

## Description
MySQL/PostgreSQL events will be persisted in a queue dir if configured, else persisted in memory.

## Motivation and Context
To provide offline backup/persistence for events, so that no events are lost.

## Regression
Its a feature

## How Has This Been Tested?

- Start MinIO without an active PostgreSQL with the following config
```
"postgresql": {
    "1": {
        "enable": true,
        "format": "namespace",
        "connectionString": "sslmode=disable",
        "table": "bucketevents",
        "host": "127.0.0.1",
        "port": "5432",
        "user": "postgres",
        "password": "password",
        "database": "minio_events",
        "queueDir": "/tmp/postgres",
        "queueLimit": 1000
    }
}
```
- Enable bucket notification using mc
- Start sending events
- The events will persist in /tmp/postgres and gets replayed when the broker is turned on. (/tmp/postgres - will be empty if all the events are successfully sent)
- Start postgres
- The evens will be replayed as you can see in consumer console.

Repeat the same for SQL

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-05-08 14:28 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-05-21 06:18 UTC, nitisht commented
blocked till #7658 is merged

2019-05-23 09:27 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#303dc08e-404c-422f-a913-879cbf2d46e4) |
<a name="303dc08e-404c-422f-a913-879cbf2d46e4"></a>
### 7629-58c4673/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31958
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 620fd2b0ae4e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-z53905qnso6kd6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360010,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A145629780A5EF, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-05-23 10:25 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-05-28 10:06 UTC, nitisht requested changes
Testing with mysql and following sequence:

- MySql setup and running
- Event notification set with queueDir and queueLimit
- I can see events being written to mysql
- Shutdown MySql
- upload object and expect it to be persisted in queueDir, but I see this error on server side

```
API: SYSTEM(bucket=images1, object=3)
Time: 15:24:25 IST 05/28/2019
Error: dial tcp 127.0.0.1:3306: connect: connection refused
       EventName=s3:ObjectCreated:Put, targetID=mysql
       3: cmd/logger/logonce.go:52:logger.(*logOnceType).logOnceIf()
       2: cmd/logger/logonce.go:80:logger.LogOnceIf()
       1: cmd/notification.go:925:cmd.sendEvent.func1()
```
While queueDir remains empty.

2019-05-30 05:47 UTC, nitisht commented
After discussion with @Praveenrajmani looks like above issue is independent of this PR (ref: https://github.com/minio/minio/issues/7707).

2019-05-30 05:47 UTC, nitisht submitted a review, later dismissed
LGTM & Tested

2019-05-30 14:43 UTC, Praveenrajmani commented
Resolved a conflict - PTAL @nitisht @balamurugana

2019-05-30 15:45 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#42d2ce10-6639-42d0-8812-4649e8519e76) |
| mint-large-bucket.sh | :x: [more...](#f2f62acf-d1ba-4270-bb0a-130c30db0144) |
| mint-dist-xl.sh | :x: [more...](#45b3e5f9-5928-43c5-a16d-8f67aab943ea) |
<a name="42d2ce10-6639-42d0-8812-4649e8519e76"></a>
### 7629-f1a6ac1/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30452
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c7efed09761b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mhn6h3p9yrqqju",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360014,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A3804D5EBE1E69, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="45b3e5f9-5928-43c5-a16d-8f67aab943ea"></a>
### 7629-f1a6ac1/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31245
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 97238470a3ce:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 53 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... done in 54 seconds
(10/14) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 504,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3339pl5, objectName=minio-java-test-1nd7qdj, resource=/minio-java-test-3339pl5/minio-java-test-1nd7qdj, requestId=15A3804A64B17955, hostId=874100ce-4c89-4e22-8c72-59751266d832)\nrequest={method=DELETE, url=http://72.28.97.55:31245/minio-java-test-3339pl5/minio-java-test-1nd7qdj?uploadId=b75b2f37-a04e-49bf-a4ea-c5e08034b38e, headers=Host: 72.28.97.55:31245\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190530T154233Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190530/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-30T15-23-49Z\nVary: Origin\nX-Amz-Request-Id: 15A3804A64B17955\nX-Minio-Deployment-Id: 874100ce-4c89-4e22-8c72-59751266d832\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 May 2019 15:42:33 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="f2f62acf-d1ba-4270-bb0a-130c30db0144"></a>
### 7629-f1a6ac1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32166
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2508a611fb75:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 36 seconds
{
  "name": "mc",
  "duration": "122463",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-30854 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-30636  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-30636/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-30636/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-30636/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-30636/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-30636/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-30636/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-30636/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-30636/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-30636/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-30636/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-30636/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-30636/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-30636/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-30636/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-30636/datafile-5243880-b`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 473.83 MiB, Speed: 3.87 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-06-10 06:20 UTC, Praveenrajmani commented
PTAL @balamurugana @nitisht

2019-06-21 06:01 UTC, nitisht approved these changes

2019-07-12 04:49 UTC, Praveenrajmani commented
resolved a conflict. PTAL @balamurugana @nitisht

2019-07-12 05:20 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#25590402-5872-4684-8f61-b73da4370b24) |
| mint-large-bucket.sh | :x: [more...](#6d92f34f-8fea-4a5a-bbc8-0d84137db36b) |
| mint-fs.sh | :x: [more...](#a3ba7cdd-dcdd-4d57-b273-fecb4b08d12c) |
| mint-dist-xl.sh | :x: [more...](#01f3e9a8-a3d8-4a0e-8945-738fb6a145f8) |
<a name="01f3e9a8-a3d8-4a0e-8945-738fb6a145f8"></a>
### 7629-81a6734/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32674
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d87a714d7283:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 40 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/14) Running minio-java tests ... FAILED in 54 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 974,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2a5n80r, objectName=minio-java-test-3u817d, resource=/minio-java-test-2a5n80r/minio-java-test-3u817d, requestId=15B090F4ABD0468A, hostId=53672a41-7fd1-4abf-86d9-27d8f5d7e641)\nrequest={method=DELETE, url=http://72.28.97.58:32674/minio-java-test-2a5n80r/minio-java-test-3u817d?uploadId=d439cfe5-b0b5-4838-85fb-d176ce7db097, headers=Host: 72.28.97.58:32674\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190712T051411Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190712/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-12T04-56-02Z\nVary: Origin\nX-Amz-Request-Id: 15B090F4ABD0468A\nX-Xss-Protection: 1; mode=block\nDate: Fri, 12 Jul 2019 05:14:11 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="25590402-5872-4684-8f61-b73da4370b24"></a>
### 7629-81a6734/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31700
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e916453d779f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 22 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-a529q9dmd46zzi",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 21721,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31700/aws-sdk-go-test-a529q9dmd46zzi: dial tcp 72.28.97.57:31700: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a3ba7cdd-dcdd-4d57-b273-fecb4b08d12c"></a>
### 7629-81a6734/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31608
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 403887d4dde8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-kqvfjywnyrzb6y",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 344,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:31608/aws-sdk-go-test-kqvfjywnyrzb6y: dial tcp 72.28.97.59:31608: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="6d92f34f-8fea-4a5a-bbc8-0d84137db36b"></a>
### 7629-81a6734/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30371
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e48053f1e89d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 3 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 21 seconds
{
  "name": "mc",
  "duration": "70028",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-1911 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-4960/mc-test-object-5891  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-4960/mc-test-object-5891`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume TpeCoxRG`"
}

Executed 6 out of 14 tests successfully.
```

2019-07-17 01:29 UTC, kannappanr commented
ping @nitisht @balamurugana

2019-07-23 17:38 UTC, kannappanr commented
Please resolve the conflicts @Praveenrajmani

2019-07-23 18:45 UTC, Praveenrajmani commented
Resolved the conflicts @kannappanr @nitisht @balamurugana :+1:

2019-07-23 18:50 UTC, kannappanr approved these changes
LGTM

2019-07-23 19:26 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#16c13b9a-011d-4f97-aa44-700b31af25cd) |
| mint-dist-xl.sh | :x: [more...](#5a4a564a-79b2-44a6-bb6b-7ec41cd330df) |
<a name="16c13b9a-011d-4f97-aa44-700b31af25cd"></a>
### 7629-84f1054/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30419
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 851b9f07275a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 25 seconds
{
  "name": "mc",
  "duration": "109850",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-5775 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-8112  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-8112/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-8112/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-8112/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-8112/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-8112/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-8112/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-8112/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-8112/datafile-129-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-8112/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-8112/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-8112/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-8112/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-8112/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-8112/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-8112/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 472.55 MiB, Speed: 4.30 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="5a4a564a-79b2-44a6-bb6b-7ec41cd330df"></a>
### 7629-84f1054/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31794
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 03beabf9bb8b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 30 seconds
(8/14) Running minio-dotnet tests ... done in 47 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 34 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 21 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 619,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2o87pat, objectName=minio-java-test-4gv8t3, resource=/minio-java-test-2o87pat/minio-java-test-4gv8t3, requestId=15B41F99F9189F50, hostId=e0a8ee56-b23c-475f-bc38-8cbffbc65f11)\nrequest={method=DELETE, url=http://72.28.97.56:31794/minio-java-test-2o87pat/minio-java-test-4gv8t3?uploadId=fceb3372-3dad-45a8-b76d-b4bb87ccd341, headers=Host: 72.28.97.56:31794\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190723T192156Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190723/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-23T19-02-47Z\nVary: Origin\nX-Amz-Request-Id: 15B41F99F9189F50\nX-Xss-Protection: 1; mode=block\nDate: Tue, 23 Jul 2019 19:21:57 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-24 04:29 UTC, nitisht commented on docs/bucket/notifications/README.md
> +    }
} seems misplaced @Praveenrajmani

2019-07-24 04:30 UTC, nitisht commented on docs/config/config.sample.json
> +                                "queueLimit": 0
`queueDir` and `queueLimit` are not aligned properly.

2019-07-24 11:41 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#f26e91aa-5ddb-4f89-9614-950ca90e3b8c) |
| mint-large-bucket.sh | :x: [more...](#e97d65df-f87b-424b-89d3-9455a71b8539) |
| mint-dist-xl.sh | :x: [more...](#66897722-ad89-49cf-bd2c-7e911d5f9d48) |
<a name="f26e91aa-5ddb-4f89-9614-950ca90e3b8c"></a>
### 7629-89ded06/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30054
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e0aa20f75579:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wwh9ytegj63a90",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12567,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30054/aws-sdk-go-test-wwh9ytegj63a90: dial tcp 72.28.97.57:30054: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="66897722-ad89-49cf-bd2c-7e911d5f9d48"></a>
### 7629-89ded06/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31988
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d00eeeb28fc6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 9 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 33 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires, Map<String, String> reqParams)",
  "duration": 90,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.53:31988/minio-java-test-1qs2kfa/minio-java-test-202u6mj?response-content-type=application%2Fjson&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190724%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190724T113832Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=46f2560f39c9778578915e1cf0bbb279e48095b97a1da34bcdcad46c0434e14a}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-202u6mj</Key><BucketName>minio-java-test-1qs2kfa</BucketName><Resource>/minio-java-test-1qs2kfa/minio-java-test-202u6mj</Resource><RequestId>15B454E4BF201F5E</RequestId><HostId>49eeb9ae-0032-4961-a0b2-a7b94dc2c3dc</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test3(FunctionalTest.java:1842), FunctionalTest.runTests(FunctionalTest.java:2996), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="e97d65df-f87b-424b-89d3-9455a71b8539"></a>
### 7629-89ded06/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32404
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4bfbfac276bf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 1 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 54 seconds
{
  "name": "mc",
  "duration": "133990",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7086 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-16660  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-16660/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-16660/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-16660/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-16660/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-16660/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-16660/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-16660/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-16660/datafile-129-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-16660/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-16660/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-16660/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-16660/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-16660/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-16660/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-16660/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 478.47 MiB, Speed: 3.57 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-07-24 12:08 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#9a8ff599-c137-4226-a052-05759d66167a) |
| mint-large-bucket.sh | :x: [more...](#539e81ab-b8a7-4692-a21c-517a9e0aef56) |
| mint-dist-xl.sh | :x: [more...](#374a4a38-4c02-4467-877b-4f5d33da19de) |
<a name="9a8ff599-c137-4226-a052-05759d66167a"></a>
### 7629-6c72d7e/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32606
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b60995ff38fd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fh6tjkwypy442h",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12561,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32606/aws-sdk-go-test-fh6tjkwypy442h: dial tcp 72.28.97.57:32606: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="539e81ab-b8a7-4692-a21c-517a9e0aef56"></a>
### 7629-6c72d7e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30993
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dc2380182818:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 51 seconds
{
  "name": "mc",
  "duration": "130643",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28173 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-3012  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-3012/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-3012/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-3012/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-3012/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-3012/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-3012/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-3012/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-3012/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-3012/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-3012/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-3012/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-3012/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-3012/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-3012/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-3012/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 412.67 MiB, Speed: 3.16 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="374a4a38-4c02-4467-877b-4f5d33da19de"></a>
### 7629-6c72d7e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30897
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1f7e9f9d75d5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 55 seconds
(10/14) Running minio-java tests ... FAILED in 39 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName, Integer expires)",
  "duration": 36,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.51:30897/minio-java-test-18n6qqf/minio-java-test-7n7gf7?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190724%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190724T120305Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=4f2a34c4b085cb7b9b2e695bc736b7b030cdedabcfa71a2b930e7c2ecf5751db}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-7n7gf7</Key><BucketName>minio-java-test-18n6qqf</BucketName><Resource>/minio-java-test-18n6qqf/minio-java-test-7n7gf7</Resource><RequestId>15B4563BE190CA8A</RequestId><HostId>4d424c9d-d93e-4902-aa89-2db4b6d506e1</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test2(FunctionalTest.java:1803), FunctionalTest.runTests(FunctionalTest.java:2995), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-24 12:32 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9f6e96c1-f464-431b-a51d-632cff523d42) |
| mint-fs.sh | :x: [more...](#41554ae8-f42d-4a15-87e3-22b956deb1d8) |
| mint-dist-xl.sh | :x: [more...](#985c757d-c77e-4890-8ea9-ed49ced01af1) |
<a name="41554ae8-f42d-4a15-87e3-22b956deb1d8"></a>
### 7629-5827ac8/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31868
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 230e3743b7ce:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 40 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... FAILED in 1 minutes and 43 seconds
{"name": "awscli", "duration": 62410, "function": "aws --endpoint-url http://72.28.97.56:31868 s3 sync /mint/data s3://awscli-mint-test-bucket-21192/\n", "status": "FAIL", "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-21192/datafile-0-bCompleted 0 Bytes/~152.2 MiB (0 Bytes/s) with ~10 file(s) remaining (calculating...)
Completed 1 Byte/233.2 MiB (16 Bytes/s) with 14 file(s) remaining                   
upload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-21192/datafile-1-bCompleted 1 Byte/233.2 MiB (16 Bytes/s) with 13 file(s) remaining
Completed 256.0 KiB/233.2 MiB (4.0 MiB/s) with 13 file(s) remaining
Completed 257.0 KiB/233.2 MiB (3.8 MiB/s) with 13 file(s) remaining
upload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-21192/datafile-1-kBCompleted 257.0 KiB/233.2 MiB (3.8 MiB/s) with 12 file(s) remaining
Completed 513.0 KiB/233.2 MiB (7.3 MiB/s) with 12 file(s) remaining
Completed 769.0 KiB/233.2 MiB (11.0 MiB/s) with 12 file(s) remaining
Completed 1.0 MiB/233.2 MiB (14.1 MiB/s) with 12 file(s) remaining  
Completed 1.3 MiB/233.2 MiB (17.4 MiB/s) with 12 file(s) remaining  
Completed 1.3 MiB/233.2 MiB (17.4 MiB/s) with 12 file(s) remaining  
Completed 1.4 MiB/233.2 MiB (18.5 MiB/s) with 12 file(s) remaining  
upload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-21192/datafile-100-kBCompleted 1.4 MiB/233.2 MiB (18.5 MiB/s) with 11 file(s) remaining
upload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-21192/datafile-33-kBCompleted 1.4 MiB/233.2 MiB (18.5 MiB/s) with 10 file(s) remaining
Completed 1.6 MiB/233.2 MiB (20.9 MiB/s) with 10 file(s) remaining
Completed 1.9 MiB/233.2 MiB (23.0 MiB/s) with 10 file(s) remaining
Completed 2.1 MiB/233.2 MiB (25.8 MiB/s) with 10 file(s) remaining
Completed 2.4 MiB/233.2 MiB (26.2 MiB/s) with 10 file(s) remaining
Completed 2.6 MiB/233.2 MiB (28.7 MiB/s) with 10 file(s) remaining
Completed 2.9 MiB/233.2 MiB (31.0 MiB/s) with 10 file(s) remaining
Completed 3.1 MiB/233.2 MiB (28.4 MiB/s) with 10 file(s) remaining
Completed 3.4 MiB/233.2 MiB (30.5 MiB/s) with 10 file(s) remaining
Completed 3.6 MiB/233.2 MiB (32.2 MiB/s) with 10 file(s) remaining
Completed 3.9 MiB/233.2 MiB (33.7 MiB/s) with 10 file(s) remaining
Completed 4.1 MiB/233.2 MiB (35.1 MiB/s) with 10 file(s) remaining
Completed 4.4 MiB/233.2 MiB (36.4 MiB/s) with 10 file(s) remaining
Completed 4.6 MiB/233.2 MiB (37.9 MiB/s) with 10 file(s) remaining
Completed 4.9 MiB/233.2 MiB (38.9 MiB/s) with 10 file(s) remaining
Completed 5.1 MiB/233.2 MiB (40.6 MiB/s) with 10 file(s) remaining
Completed 5.4 MiB/233.2 MiB (42.3 MiB/s) with 10 file(s) remaining
upload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-21192/datafile-1-MBCompleted 5.4 MiB/233.2 MiB (42.3 MiB/s) with 9 file(s) remaining
Completed 5.6 MiB/233.2 MiB (43.4 MiB/s) with 9 file(s) remaining
Completed 5.9 MiB/233.2 MiB (44.8 MiB/s) with 9 file(s) remaining
Completed 6.1 MiB/233.2 MiB (46.2 MiB/s) with 9 file(s) remaining
Completed 6.4 MiB/233.2 MiB (47.1 MiB/s) with 9 file(s) remaining
Completed 6.6 MiB/233.2 MiB (48.4 MiB/s) with 9 file(s) remaining
Completed 6.9 MiB/233.2 MiB (49.9 MiB/s) with 9 file(s) remaining
Completed 7.1 MiB/233.2 MiB (50.5 MiB/s) with 9 file(s) remaining
Completed 7.4 MiB/233.2 MiB (49.6 MiB/s) with 9 file(s) remaining
Completed 7.6 MiB/233.2 MiB (50.5 MiB/s) with 9 file(s) remaining
Completed 7.7 MiB/233.2 MiB (50.2 MiB/s) with 9 file(s) remaining
upload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-21192/datafile-1.03-MBCompleted 7.7 MiB/233.2 MiB (50.2 MiB/s) with 8 file(s) remaining
Completed 7.9 MiB/233.2 MiB (51.1 MiB/s) with 8 file(s) remaining
Completed 8.2 MiB/233.2 MiB (52.5 MiB/s) with 8 file(s) remaining
Completed 8.4 MiB/233.2 MiB (54.0 MiB/s) with 8 file(s) remaining
Completed 8.7 MiB/233.2 MiB (55.4 MiB/s) with 8 file(s) remaining
Completed 8.9 MiB/233.2 MiB (56.5 MiB/s) with 8 file(s) remaining
Completed 9.2 MiB/233.2 MiB (57.3 MiB/s) with 8 file(s) remaining
Completed 9.4 MiB/233.2 MiB (58.3 MiB/s) with 8 file(s) remaining
Completed 9.7 MiB/233.2 MiB (59.3 MiB/s) with 8 file(s) remaining
Completed 9.9 MiB/233.2 MiB (57.5 MiB/s) with 8 file(s) remaining
Completed 10.2 MiB/233.2 MiB (58.3 MiB/s) with 8 file(s) remaining
Completed 10.4 MiB/233.2 MiB (58.9 MiB/s) with 8 file(s) remaining
Completed 10.7 MiB/233.2 MiB (58.3 MiB/s) with 8 file(s) remaining
Completed 10.9 MiB/233.2 MiB (58.1 MiB/s) with 8 file(s) remaining
Completed 11.2 MiB/233.2 MiB (58.8 MiB/s) with 8 file(s) remaining
Completed 11.4 MiB/233.2 MiB (59.2 MiB/s) with 8 file(s) remaining
Completed 11.7 MiB/233.2 MiB (59.5 MiB/s) with 8 file(s) remaining
Completed 11.9 MiB/233.2 MiB (58.8 MiB/s) with 8 file(s) remaining
Completed 12.2 MiB/233.2 MiB (59.9 MiB/s) with 8 file(s) remaining
Completed 12.4 MiB/233.2 MiB (61.0 MiB/s) with 8 file(s) remaining
Completed 12.7 MiB/233.2 MiB (60.8 MiB/s) with 8 file(s) remaining
Completed 12.9 MiB/233.2 MiB (59.0 MiB/s) with 8 file(s) remaining
Completed 13.2 MiB/233.2 MiB (58.4 MiB/s) with 8 file(s) remaining
Completed 13.4 MiB/233.2 MiB (57.8 MiB/s) with 8 file(s) remaining
Completed 13.7 MiB/233.2 MiB (58.7 MiB/s) with 8 file(s) remaining
Completed 13.9 MiB/233.2 MiB (58.0 MiB/s) with 8 file(s) remaining
Completed 14.2 MiB/233.2 MiB (57.2 MiB/s) with 8 file(s) remaining
Completed 14.4 MiB/233.2 MiB (54.6 MiB/s) with 8 file(s) remaining
Completed 14.7 MiB/233.2 MiB (54.3 MiB/s) with 8 file(s) remaining
Completed 14.9 MiB/233.2 MiB (54.5 MiB/s) with 8 file(s) remaining
Completed 15.2 MiB/233.2 MiB (55.3 MiB/s) with 8 file(s) remaining
Completed 15.4 MiB/233.2 MiB (55.4 MiB/s) with 8 file(s) remaining
Completed 15.7 MiB/233.2 MiB (56.1 MiB/s) with 8 file(s) remaining
Completed 15.9 MiB/233.2 MiB (56.5 MiB/s) with 8 file(s) remaining
Completed 16.2 MiB/233.2 MiB (53.2 MiB/s) with 8 file(s) remaining
Completed 16.4 MiB/233.2 MiB (53.7 MiB/s) with 8 file(s) remaining
Completed 16.7 MiB/233.2 MiB (53.2 MiB/s) with 8 file(s) remaining
Completed 16.9 MiB/233.2 MiB (53.8 MiB/s) with 8 file(s) remaining
Completed 17.2 MiB/233.2 MiB (53.8 MiB/s) with 8 file(s) remaining
Completed 17.4 MiB/233.2 MiB (51.5 MiB/s) with 8 file(s) remaining
Completed 17.7 MiB/233.2 MiB (51.8 MiB/s) with 8 file(s) remaining
Completed 17.9 MiB/233.2 MiB (52.2 MiB/s) with 8 file(s) remaining
Completed 18.2 MiB/233.2 MiB (52.1 MiB/s) with 8 file(s) remaining
Completed 18.4 MiB/233.2 MiB (52.8 MiB/s) with 8 file(s) remaining
Completed 18.7 MiB/233.2 MiB (53.5 MiB/s) with 8 file(s) remaining
Completed 18.9 MiB/233.2 MiB (54.1 MiB/s) with 8 file(s) remaining
Completed 19.2 MiB/233.2 MiB (53.2 MiB/s) with 8 file(s) remaining
Completed 19.4 MiB/233.2 MiB [...]

2019-07-24 12:59 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#92bed548-fb8f-43b2-b57c-0e375e5527af) |
| mint-dist-xl.sh | :x: [more...](#71c18f19-1d3b-46cc-b4c5-d376f7022ba2) |
<a name="71c18f19-1d3b-46cc-b4c5-d376f7022ba2"></a>
### 7629-f63aa1c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30091
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 90ff94609e9b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 9 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 2 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 22 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 926,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2t3ct8d, objectName=minio-java-test-2rg2395, resource=/minio-java-test-2t3ct8d/minio-java-test-2rg2395, requestId=15B4590CAF3135D7, hostId=cd1a292c-b9d7-4303-9e03-b54e6804fcaa)\nrequest={method=DELETE, url=http://72.28.97.61:30091/minio-java-test-2t3ct8d/minio-java-test-2rg2395?uploadId=8d7d8389-3cb2-4874-a4bd-45521cc28902, headers=Host: 72.28.97.61:30091\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190724T125441Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190724/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-24T12-34-39Z\nVary: Origin\nX-Amz-Request-Id: 15B4590CAF3135D7\nX-Xss-Protection: 1; mode=block\nDate: Wed, 24 Jul 2019 12:54:42 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="92bed548-fb8f-43b2-b57c-0e375e5527af"></a>
### 7629-f63aa1c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31785
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d1947706497d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 37 seconds
{
  "name": "mc",
  "duration": "111938",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-26646 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-15351  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-15351/datafile-0-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-15351/datafile-1-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-15351/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-15351/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-15351/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-15351/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-15351/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-15351/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-15351/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-15351/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-15351/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-15351/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-15351/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-15351/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-15351/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 409.86 MiB, Speed: 3.66 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-07-24 13:04 UTC, nitisht commented
@Praveenrajmani can you please check the Travis failure

2019-07-24 13:23 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#10ebd3cc-923b-4dc5-9b02-879ad2be68d1) |
| mint-xl.sh | :x: [more...](#9d90ec2f-44de-40f0-8391-7aa792672881) |
| mint-large-bucket.sh | :x: [more...](#265301cd-60da-4e35-92f7-27c9c87db73b) |
| mint-dist-xl.sh | :x: [more...](#d4549782-c133-4ccd-a82e-1140eadaaac8) |
<a name="9d90ec2f-44de-40f0-8391-7aa792672881"></a>
### 7629-681f83a/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31464
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 99d03e9ea237:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-kvv2d1ugegl9pg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12580,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31464/aws-sdk-go-test-kvv2d1ugegl9pg: dial tcp 72.28.97.57:31464: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="265301cd-60da-4e35-92f7-27c9c87db73b"></a>
### 7629-681f83a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31054
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 169653a98732:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 42 seconds
{
  "name": "mc",
  "duration": "69093",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-4059 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-27409  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-27409/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-27409/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-27409/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-27409/datafile-1.03-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-27409/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-27409/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-27409/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-27409/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-27409/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-27409/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-27409/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-27409/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-27409/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-27409/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-27409/datafile-5-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 424.18 MiB, Speed: 6.15 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="d4549782-c133-4ccd-a82e-1140eadaaac8"></a>
### 7629-681f83a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31391
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 919b146e83bf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 7 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 21 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 539,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-309gqq4, objectName=minio-java-test-2k2pfqv, resource=/minio-java-test-309gqq4/minio-java-test-2k2pfqv, requestId=15B45A7FEF40F85A, hostId=75ec8c8f-f277-4ccd-81a7-ab25f13c3d77)\nrequest={method=DELETE, url=http://72.28.97.56:31391/minio-java-test-309gqq4/minio-java-test-2k2pfqv?uploadId=8e03b4c3-2012-44b6-9e20-fc2e804c3331, headers=Host: 72.28.97.56:31391\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190724T132116Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190724/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-24T13-01-39Z\nVary: Origin\nX-Amz-Request-Id: 15B45A7FEF40F85A\nX-Xss-Protection: 1; mode=block\nDate: Wed, 24 Jul 2019 13:21:16 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="10ebd3cc-923b-4dc5-9b02-879ad2be68d1"></a>
### 7629-681f83a/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32294
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ce09fab5422:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-sorhpjfihywt4r",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360018,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B45A752DE76E1A, host id: ",
  "function": "PresignedPut",
  [...]

2019-07-24 14:43 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#20f6de09-4c03-4f01-a040-37023ed115aa) |
| mint-large-bucket.sh | :x: [more...](#0ba15a0e-3724-4ba4-8f43-f3fc675512d9) |
| mint-worm.sh | :x: [more...](#0597f596-1fed-4097-a0a5-93b650e70bb7) |
| mint-dist-xl.sh | :x: [more...](#09bbb8c4-cb31-43cd-af6b-5ddd3b8c0bed) |
<a name="20f6de09-4c03-4f01-a040-37023ed115aa"></a>
### 7629-c936ff7/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31145
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 06d7de634d22:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-cnp9093thou0e4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360019,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B45EC6118D2125, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0ba15a0e-3724-4ba4-8f43-f3fc675512d9"></a>
### 7629-c936ff7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31765
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 01a39095054a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-tpkv6uyo6amzf6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 11879,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31765/aws-sdk-go-test-tpkv6uyo6amzf6: dial tcp 72.28.97.57:31765: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="09bbb8c4-cb31-43cd-af6b-5ddd3b8c0bed"></a>
### 7629-c936ff7/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32149
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e24a3a615954:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 45 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 56 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 8 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 630,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-16ilgh9, objectName=minio-java-test-1vnp2u4, resource=/minio-java-test-16ilgh9/minio-java-test-1vnp2u4, requestId=15B45ECA37589F94, hostId=6219e6c7-3bfa-475a-b1cc-fdddd492d5c3)\nrequest={method=DELETE, url=http://72.28.97.55:32149/minio-java-test-16ilgh9/minio-java-test-1vnp2u4?uploadId=1232f543-ccf1-45cc-841e-74efd138c5d3, headers=Host: 72.28.97.55:32149\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190724T143953Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190724/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-24T14-20-30Z\nVary: Origin\nX-Amz-Request-Id: 15B45ECA37589F94\nX-Xss-Protection: 1; mode=block\nDate: Wed, 24 Jul 2019 14:39:53 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="0597f596-1fed-4097-a0a5-93b650e70bb7"></a>
### 7629-c936ff7/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30197
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 815bc4b51a53:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-amkbk1jrfxf4wkng1nlfj2dheip9297nnbj9ldaojinyj0dnyp3khn4",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 12271,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30197/bucket-amkbk1jrfxf4wkng1nlfj2dheip9297nnbj9ldaojinyj0dnyp3khn4: dial tcp 72.28.97.57:30197: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```

2019-07-24 15:18 UTC, kannappanr commented
```
--- FAIL: TestSetConfigHandler (2.46s)
    admin-handlers_test.go:643: Expected to succeed but failed with 400, body: {"Code":"XMinioAdminConfigBadJSON","Message":"invalid character '\"' after object key:value pair","Resource":"/minio/admin/v1/config","RequestId":"","HostId":"f8ed1c12-d243-46c4-bf76-9cbe15845eb5"}
```

2019-07-24 16:50 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#2ccd5e4f-ff07-4200-b7b1-c5a65d3069fc) |
| mint-large-bucket.sh | :x: [more...](#31be8b98-aed8-42a3-aa9a-2826b3a50aa9) |
| mint-fs.sh | :x: [more...](#d7dfcf76-a9d4-4c95-9c00-45ab7ec96c7a) |
| mint-dist-xl.sh | :x: [more...](#340e2831-4e64-46a4-b439-196a91ca87bd) |
<a name="2ccd5e4f-ff07-4200-b7b1-c5a65d3069fc"></a>
### 7629-4511ad5/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32627
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3f8c2e8863c9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-xlkimbvleulqrw",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360014,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B465ABE79D18E2, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d7dfcf76-a9d4-4c95-9c00-45ab7ec96c7a"></a>
### 7629-4511ad5/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31282
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e9681e6f92da:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-tanvwc6ho3x51r",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12679,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31282/aws-sdk-go-test-tanvwc6ho3x51r: dial tcp 72.28.97.57:31282: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="31be8b98-aed8-42a3-aa9a-2826b3a50aa9"></a>
### 7629-4511ad5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30558
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fafe01fc77b9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 19 seconds
(6/14) Running healthcheck tests ... done in 2 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 0 seconds
{
  "name": "mc",
  "duration": "97195",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21568 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-30084  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-30084/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-30084/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-30084/datafile-1-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-30084/datafile-10-MB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-30084/datafile-1-b`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-30084/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-30084/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-30084/datafile-1.03-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-30084/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-30084/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-30084/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-30084/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-30084/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-30084/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-30084/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 486.36 MiB, Speed: 5.01 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="340e2831-4e64-46a4-b439-196a91ca87bd"></a>
### 7629-4511ad5/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31753
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 38e41287a425:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 41 seconds
{
  "name": "mc",
  "duration": "16076",
  "function": "test_mirror_list_objects",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-15571 --quiet --no-color rb --force myminio/mc-test-bucket-20664  >>> \nmc: <ERROR> Failed to remove `myminio/mc-test-bucket-20664`. The bucket you tried to delete is not empty."
}

Executed 6 out of 14 tests successfully.
```

2019-07-24 17:18 UTC, merged