[WIP] sets: Correctly set isTruncated in listing
minio/minio pull request #7675
Opened 2019-05-20 12:46 UTC by vadmeste

## Description
isTruncated should not be set to true if there is no further
possible entries beyond maxKeys.

This commit will also move wide testing on object API from xl
to xl sets.

## Motivation and Context
Fixing a regression

## Regression
Yes, https://github.com/minio/minio/pull/7611

## How Has This Been Tested?
Check isTruncated in listing XML response when maxKeys is equal to the last element of the list

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-05-20 13:58 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#80a44267-38e7-44f6-9aec-a223997646a5) |
| mint-dist-xl.sh | :x: [more...](#54bc3bc5-617f-4276-b87f-f2255e44d5c5) |
<a name="80a44267-38e7-44f6-9aec-a223997646a5"></a>
### 7675-8225fef/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31682
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 31fdac53a281:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 11 minutes and 12 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 minutes and 17 seconds
(5/14) Running awscli tests ... done in 4 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 3 minutes and 20 seconds
{
  "name": "mc",
  "duration": "30119",
  "function": "test_find",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28287 --quiet --no-color mirror /mint/data myminio/mc-test-bucket-16215  >>> \nmc: <ERROR> Failed to perform mirroring action. Get http://72.28.97.51:31682/mc-test-bucket-16215/?location=: dial tcp 72.28.97.51:31682: i/o timeout\nTotal: 0 B, Transferred: 0 B, Speed: 0 B/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="54bc3bc5-617f-4276-b87f-f2255e44d5c5"></a>
### 7675-8225fef/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32589
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 27951e0955ab:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 46 seconds
{
  "name": "aws-sdk-php",
  "function": "getBucketPolicy ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5ce2ad69d3c3f"
  },
  "duration": "40404",
  "status": "FAIL",
  "error": "Expected getObject to fail with 403"
}

Executed 2 out of 14 tests successfully.
```

2019-05-20 14:34 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9387387e-d1ce-4fdd-92a9-6e6d46f6d0a3) |
<a name="9387387e-d1ce-4fdd-92a9-6e6d46f6d0a3"></a>
### 7675-a09b32e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31780
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b16a9f6dafa6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 15 minutes and 49 seconds
(4/14) Running aws-sdk-ruby tests ... FAILED in 4 minutes and 11 seconds
{
  "name": "aws-sdk-ruby",
  "function": "copyObject(source_bucket_name, target_bucket_name, source_file_name, target_file_name = )",
  "args": {
    "source_bucket_name": "aws-sdk-ruby-bucket-6050d9f804fc",
    "target_bucket_name": "aws-sdk-ruby-bucket-b29afb5868c0",
    "source_file_name": "datafile-1-kB",
    "target_file_name": "datafile-1-kB-copy"
  },
  "duration": 242530.15,
  "error": "Net::ReadTimeout",
  "status": "FAIL"
}

Executed 3 out of 14 tests successfully.
```

2019-05-20 15:24 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#f07d3bee-b17d-4ca0-9fd3-94f0da7514d9) |
<a name="f07d3bee-b17d-4ca0-9fd3-94f0da7514d9"></a>
### 7675-c364126/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30010
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 15b23266de55:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 25 minutes and 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 30 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 10 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 52 seconds
(10/14) Running minio-java tests ... FAILED in 2 minutes and 48 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 156610,
  "status": "FAIL",
  "error": "java.lang.Exception: item count differs, expected: 1050, got: 1049 >>> [FunctionalTest.listObject_test5(FunctionalTest.java:1473), FunctionalTest.runTests(FunctionalTest.java:2985), FunctionalTest.main(FunctionalTest.java:3121)]"
}

Executed 9 out of 14 tests successfully.
```

2019-05-20 15:50 UTC, kannappanr commented
Please look at SimpleCI and minio-java failures

2019-05-20 16:48 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#4472d2b7-02f0-40fe-a9ab-c555b38fde81) |
<a name="4472d2b7-02f0-40fe-a9ab-c555b38fde81"></a>
### 7675-298625d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30490
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3229420dedf5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 40 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 2 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 21 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 48 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 97876,
  "status": "FAIL",
  "error": "java.lang.Exception: item count differs, expected: 1050, got: 1049 >>> [FunctionalTest.listObject_test5(FunctionalTest.java:1473), FunctionalTest.runTests(FunctionalTest.java:2985), FunctionalTest.main(FunctionalTest.java:3121)]"
}

Executed 9 out of 14 tests successfully.
```

2019-05-20 21:23 UTC, kannappanr commented
Please check the `minio-java` functional test failure.

2019-05-21 01:40 UTC, harshavardhana requested changes
CI failure is indicative of a bug in the current PR @vadmeste - PTAL

2019-05-21 14:23 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#09eab86d-a811-401b-94df-7a6d5bf597bc) |
<a name="09eab86d-a811-401b-94df-7a6d5bf597bc"></a>
### 7675-0dd3849/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31839
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0062ddf0d830:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2c0rw9e6cl4j5o",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360017,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A0B8485E06C303, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-05-21 16:14 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#ca6ca483-ac28-4c4d-859c-f8889efdfbca) |
<a name="ca6ca483-ac28-4c4d-859c-f8889efdfbca"></a>
### 7675-ee05fd2/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30390
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 303f7e315aae:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... FAILED in 3 minutes and 56 seconds
{
  "name": "awscli",
  "duration": 135422,
  "function": "aws --endpoint-url http://72.28.97.51:30390 s3api upload-part --bucket awscli-mint-test-bucket-9863 --key awscli-mint-test-bucket-9863-object --body /mint/data/datafile-1-kB --upload-id 3590b488-a864-439f-bd7a-257aff069f01 --part-number 2\n",
  "status": "FAIL",
  "error": ""
}

Executed 4 out of 14 tests successfully.
```

2019-05-21 21:49 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |

2019-05-22 14:29 UTC, harshavardhana approved these changes

2019-05-22 20:36 UTC, kannappanr approved these changes
Tested. LGTM

2019-05-22 20:36 UTC, merged