Fix docs.min.io linking issues
minio/minio pull request #7710
Opened 2019-05-29 18:06 UTC by harshavardhana

## Description
Fix docs.min.io linking issues

## Motivation and Context
Change markdown formatting on GitHub UI and also linking issues with relative images

## Regression
No

## How Has This Been Tested?
Just visually

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added unit tests to cover my changes.
- [ ] I have added/updated functional tests in [mint](https://github.com/minio/mint). (If yes, add `mint` PR # here: )
- [x] All new and existing tests passed.

2019-05-29 18:30 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#42162ea4-b18e-4bb8-8d23-3b77b7e01e44) |
| mint-dist-xl.sh | :x: [more...](#27686be6-809a-4b06-9785-bc0724208e0f) |
<a name="42162ea4-b18e-4bb8-8d23-3b77b7e01e44"></a>
### 7710-3f5fa31/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30282
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b034a2c22326:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 8 seconds
{
  "name": "mc",
  "duration": "107022",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-6325 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-12796  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-12796/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-12796/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-12796/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-12796/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-12796/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-12796/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-12796/datafile-100-kB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-12796/datafile-33-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-12796/datafile-11-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-12796/datafile-10-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-12796/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-12796/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-12796/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-12796/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 104.17 MiB, Transferred: 347.80 MiB, Speed: 3.25 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="27686be6-809a-4b06-9785-bc0724208e0f"></a>
### 7710-3f5fa31/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30617
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3e962458bf76:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 24 seconds
(8/14) Running minio-dotnet tests ... done in 32 seconds
(9/14) Running minio-go tests ... done in 38 seconds
(10/14) Running minio-java tests ... FAILED in 43 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 475,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-kvbfbk, objectName=minio-java-test-3pblre9, resource=/minio-java-test-kvbfbk/minio-java-test-3pblre9, requestId=15A33ABD04990A04, hostId=5994d52a-ca5f-4dc9-81ae-0952fcb41140)\nrequest={method=DELETE, url=http://72.28.97.52:30617/minio-java-test-kvbfbk/minio-java-test-3pblre9?uploadId=6f1c78d9-1001-4c8d-9d7f-88f36d85b458, headers=Host: 72.28.97.52:30617\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190529T182759Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190529/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-29T18-10-13Z\nVary: Origin\nX-Amz-Request-Id: 15A33ABD04990A04\nX-Minio-Deployment-Id: 5994d52a-ca5f-4dc9-81ae-0952fcb41140\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 May 2019 18:27:59 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-05-29 18:54 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c9161b5b-bb08-49d7-8657-f5b6159880b7) |
| mint-dist-xl.sh | :x: [more...](#2d7d29b0-8472-46a5-9190-65f4c01d7cce) |
<a name="2d7d29b0-8472-46a5-9190-65f4c01d7cce"></a>
### 7710-d3ca45f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32035
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9bed11cd1ade:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-dotnet tests ... done in 32 seconds
(9/14) Running minio-go tests ... done in 39 seconds
(10/14) Running minio-java tests ... FAILED in 41 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName)",
  "duration": 1173,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2luiav0, objectName=minio-java-test-16uf5l2, resource=/minio-java-test-2luiav0/minio-java-test-16uf5l2, requestId=15A33BEFA2779D40, hostId=036cec88-15f8-4a67-9f81-35ccfb4f0a71)\nrequest={method=DELETE, url=http://72.28.97.58:32035/minio-java-test-2luiav0/minio-java-test-16uf5l2?uploadId=aab494f3-a8f8-4a60-9aa1-e39d1f00bf0d, headers=Host: 72.28.97.58:32035\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190529T184956Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190529/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-29T18-32-05Z\nVary: Origin\nX-Amz-Request-Id: 15A33BEFA2779D40\nX-Minio-Deployment-Id: 036cec88-15f8-4a67-9f81-35ccfb4f0a71\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 May 2019 18:49:57 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test1(FunctionalTest.java:1601), FunctionalTest.runTests(FunctionalTest.java:2988), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="c9161b5b-bb08-49d7-8657-f5b6159880b7"></a>
### 7710-d3ca45f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30295
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d01faa392fd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 1 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 41 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 8 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 21 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 52 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 362,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-v3nqgn, objectName=minio-java-test-4schsh, resource=/minio-java-test-v3nqgn/minio-java-test-4schsh, requestId=15A33C0E1B1A8905, hostId=595237df-be5e-4cba-8270-1c321f376224)\nrequest={method=DELETE, url=http://72.28.97.60:30295/minio-java-test-v3nqgn/minio-java-test-4schsh?uploadId=2361a427-1ed2-4a3b-a853-04fe48e8b5bc, headers=Host: 72.28.97.60:30295\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190529T185207Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190529/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-29T18-32-05Z\nVary: Origin\nX-Amz-Request-Id: 15A33C0E1B1A8905\nX-Minio-Deployment-Id: 595237df-be5e-4cba-8270-1c321f376224\nX-Xss-Protection: 1; mode=block\nDate: Wed, 29 May 2019 18:52:07 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-05-30 00:04 UTC, eco-minio requested changes

2019-05-30 00:04 UTC, eco-minio commented on docs/tls/README.md
> +* Location of custom certs directory can be specified using `--certs-dir` command line option.
```suggestion
* The location of the custom certs directory can be specified using `--certs-dir` command line option.
```

2019-05-30 00:05 UTC, eco-minio submitted a review, later dismissed
LGTM

2019-05-30 00:53 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0929bc67-1c95-4e46-9c49-55296227865b) |
| mint-dist-xl.sh | :x: [more...](#79575fb9-8464-4c13-b81d-8f5ef5ff1984) |
<a name="79575fb9-8464-4c13-b81d-8f5ef5ff1984"></a>
### 7710-950301f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30747
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4a6651039092:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 59 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 44 seconds
(10/14) Running minio-java tests ... FAILED in 43 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 226,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-d3r2u7, objectName=minio-java-test-3iu3igs, resource=/minio-java-test-d3r2u7/minio-java-test-3iu3igs, requestId=15A34F95FA27864A, hostId=ed35941a-a49f-42ce-b097-47568ab9a371)\nrequest={method=DELETE, url=http://72.28.97.55:30747/minio-java-test-d3r2u7/minio-java-test-3iu3igs?uploadId=0f9d452a-6347-480c-b577-9ae89676d4db, headers=Host: 72.28.97.55:30747\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190530T005001Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190530/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-30T00-31-12Z\nVary: Origin\nX-Amz-Request-Id: 15A34F95FA27864A\nX-Minio-Deployment-Id: ed35941a-a49f-42ce-b097-47568ab9a371\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 May 2019 00:50:01 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="0929bc67-1c95-4e46-9c49-55296227865b"></a>
### 7710-950301f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32615
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp df5f6f2e32ba:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 32 seconds
{
  "name": "mc",
  "duration": "117637",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-22959 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-30235  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-30235/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-30235/datafile-0-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-30235/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-30235/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-30235/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-30235/datafile-129-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-30235/datafile-11-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-30235/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-30235/datafile-10-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-30235/datafile-1-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-30235/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-30235/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-30235/datafile-65-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-30235/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-30235/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 491.58 MiB, Speed: 4.18 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-05-30 16:07 UTC, ebozduman requested changes

2019-05-30 16:07 UTC, ebozduman commented on docs/bigdata/README.md
> +*  _fs.s3a.endpoint=http://minio-address/_
We should not show http://minio-address as if it is a link. Markup Language's auto-linking feature. 

It should show up as =>  ht<span>tp://<span>minio-address

I used this trick: `ht<span>tp://<span>minio-address`

2019-05-30 18:26 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#0b3cb3a4-2367-4f59-bf64-641c1bade993) |
<a name="0b3cb3a4-2367-4f59-bf64-641c1bade993"></a>
### 7710-be129c6/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32502
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 859ac0432437:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 2 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 44 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName)",
  "duration": 756,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-l35k7m, objectName=minio-java-test-2r2f7tb, resource=/minio-java-test-l35k7m/minio-java-test-2r2f7tb, requestId=15A388D635B078A3, hostId=b276eb7d-a556-4697-a32c-039c28d6c7fa)\nrequest={method=DELETE, url=http://72.28.97.58:32502/minio-java-test-l35k7m/minio-java-test-2r2f7tb?uploadId=c8502a9f-f104-4b66-b8e6-6fe800533a2a, headers=Host: 72.28.97.58:32502\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190530T181909Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190530/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-30T17-59-15Z\nVary: Origin\nX-Amz-Request-Id: 15A388D635B078A3\nX-Minio-Deployment-Id: b276eb7d-a556-4697-a32c-039c28d6c7fa\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 May 2019 18:19:10 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test1(FunctionalTest.java:1601), FunctionalTest.runTests(FunctionalTest.java:2988), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-05-30 22:17 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#41f059fc-6084-4713-980a-2841f1e19ee3) |
| mint-large-bucket.sh | :x: [more...](#6ff5f18b-08e1-453e-9ad1-a18019083c80) |
| mint-dist-xl.sh | :x: [more...](#e1ae5ba2-d93d-4b91-b8f3-ff1e3a9a348f) |
<a name="e1ae5ba2-d93d-4b91-b8f3-ff1e3a9a348f"></a>
### 7710-fc784a8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31600
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 372f11a849ab:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 59 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 35 seconds
{
  "name": "minio-java",
  "function": "listenBucketNotification(String bucketName)",
  "duration": 559,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2edhijp, objectName=null, resource=/minio-java-test-2edhijp/, requestId=15A395CC6A5F2688, hostId=2696d629-c412-4cdd-9432-92c2e4025f6a)\nrequest={method=GET, url=http://72.28.97.55:31600/minio-java-test-2edhijp/?prefix=prefix&suffix=suffix&events=s3%3AObjectCreated%3A%2A&events=s3%3AObjectAccessed%3A%2A, headers=Host: 72.28.97.55:31600\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190530T221641Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190530/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-05-30T21-56-38Z\nVary: Origin\nX-Amz-Request-Id: 15A395CC6A5F2688\nX-Minio-Deployment-Id: 2696d629-c412-4cdd-9432-92c2e4025f6a\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 May 2019 22:16:41 GMT\nTransfer-Encoding: chunked\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.listenBucketNotification(MinioClient.java:5232), FunctionalTest$1.run(FunctionalTest.java:2880), java.lang.Thread.run(Thread.java:748)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="6ff5f18b-08e1-453e-9ad1-a18019083c80"></a>
### 7710-fc784a8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30549
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ffe7809aeb40:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 25 seconds
{
  "name": "mc",
  "duration": "110930",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28782 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-15796  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-15796/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-15796/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-15796/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-15796/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-15796/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-15796/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-15796/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-15796/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-15796/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-15796/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-15796/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-15796/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-15796/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-15796/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-15796/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 564.71 MiB, Speed: 5.09 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="41f059fc-6084-4713-980a-2841f1e19ee3"></a>
### 7710-fc784a8/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30649
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7b097fc99bf2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-y5po41f40ceonn",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360017,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15A395BBD3B07263, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-05-30 23:59 UTC, ebozduman approved these changes
LGTM

2019-05-31 00:01 UTC, eco-minio approved these changes

2019-05-31 00:19 UTC, merged