Update the documents under the directory docs
minio/minio pull request #7858
Opened 2019-07-01 10:54 UTC by Diracal

## Description
Update some documents, mainly the Chinese documents under the directory files 

## Motivation and Context
The English documents have been updated for many times, but the Chinese documents have not been yet, which brings many difficulties to Chinese programmers.  

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-07-01 11:19 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#d5756eb9-1964-4bb7-978d-28a6c801fe69) |
| mint-compression-dist-xl.sh | :x: [more...](#9092b71c-b708-4946-bd77-cd86f56bb3b9) |
| mint-dist-xl.sh | :x: [more...](#409bc3de-00a0-46c4-972b-958984303c2a) |
<a name="9092b71c-b708-4946-bd77-cd86f56bb3b9"></a>
### 7858-ef8fcff/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32204
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 50e3a369643f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2r46ay9uygewrv",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3075,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32204/aws-sdk-go-test-2r46ay9uygewrv: dial tcp 72.28.97.57:32204: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="409bc3de-00a0-46c4-972b-958984303c2a"></a>
### 7858-ef8fcff/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30458
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8afd41a646f8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 35 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 22 seconds
(10/14) Running minio-java tests ... FAILED in 44 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 368,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1gh9j02, objectName=minio-java-test-184h5e2, resource=/minio-java-test-1gh9j02/minio-java-test-184h5e2, requestId=15AD4444F810B4D7, hostId=dea27704-cf38-46a8-8ffe-481b88c0aab6)\nrequest={method=DELETE, url=http://72.28.97.59:30458/minio-java-test-1gh9j02/minio-java-test-184h5e2?uploadId=8b66d475-746a-4c0c-8c03-63883a236928, headers=Host: 72.28.97.59:30458\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190701T111508Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190701/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-01T10-57-02Z\nVary: Origin\nX-Amz-Request-Id: 15AD4444F810B4D7\nX-Minio-Deployment-Id: dea27704-cf38-46a8-8ffe-481b88c0aab6\nX-Xss-Protection: 1; mode=block\nDate: Mon, 01 Jul 2019 11:15:08 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="d5756eb9-1964-4bb7-978d-28a6c801fe69"></a>
### 7858-ef8fcff/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30134
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp df2f20ee17a8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 52 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 8 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 28 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName)",
  "duration": 988,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-cnq6tg, objectName=minio-java-test-1vguq56, resource=/minio-java-test-cnq6tg/minio-java-test-1vguq56, requestId=15AD446E3605EA6D, hostId=2116e356-d331-4e0a-87d5-dcb9aa78e626)\nrequest={method=DELETE, url=http://72.28.97.53:30134/minio-java-test-cnq6tg/minio-java-test-1vguq56?uploadId=6f6a5a53-506d-4f8a-9720-9b7494065836, headers=Host: 72.28.97.53:30134\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190701T111805Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190701/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-01T10-57-02Z\nVary: Origin\nX-Amz-Request-Id: 15AD446E3605EA6D\nX-Minio-Deployment-Id: 2116e356-d331-4e0a-87d5-dcb9aa78e626\nX-Xss-Protection: 1; mode=block\nDate: Mon, 01 Jul 2019 11:18:06 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test1(FunctionalTest.java:1601), FunctionalTest.runTests(FunctionalTest.java:2988), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-01 17:18 UTC, ebozduman requested changes

2019-07-01 17:18 UTC, ebozduman commented on README_zh_CN.md
> +[![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio) [![Docker Pulls](htt
We've decided to remove the following code coverage info:

[![codecov](https://codecov.io/gh/minio/minio/branch/master/graph/badge.svg)](https://codecov.io/gh/minio/minio)

`[![codecov](https://codecov.io/gh/minio/minio/branch/master/graph/badge.svg)](https://codecov.io/gh/minio/minio)`

2019-07-01 17:18 UTC, ebozduman commented on docs/chroot/README.md
> +# Deploy MinIO on Chrooted Environment [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/r
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/config/README.md
> +# MinIO Server Config Guide [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/deployment/kernel-tuning/README.md
> +# Kernel Tuning for MinIO Production Deployment on Linux Servers [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/distributed/README.md
> +# Distributed MinIO Quickstart Guide [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/rep
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/docker/README.md
> +# MinIO Docker Quickstart Guide [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/m
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/large-bucket/README.md
> +# Large Bucket Support Quickstart Guide [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/multi-tenancy/README.md
> +# MinIO Multi-Tenant Deployment Guide [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/re
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/orchestration/README.md
> +# MinIO Deployment Quickstart Guide [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/repo
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/orchestration/dcos/README.md
> +# Deploy MinIO on DC/OS [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/min
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/orchestration/docker-compose/README.md
> +# Deploy MinIO on Docker Compose [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/orchestration/docker-swarm/README.md
> +# Deploy MinIO on Docker Swarm [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/mi
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/orchestration/kubernetes/README.md
> +# Deploy MinIO on Kubernetes [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/mini
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/shared-backend/README.md
> +# Shared Backend MinIO Quickstart Guide [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/config/README.md
> +# Minio Server 配置指南 [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio)
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/deployment/kernel-tuning/README.md
> +# Linux服务器上Minio生产环境的内核调优 [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/m
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/distributed/README.md
> +# 分布式MinIO快速入门 [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio) [![Do
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/docker/README.md
> +# MinIO Docker 快速入门 [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio)
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/large-bucket/README.md
> +# 超大存储桶快速入门 [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio) [![Docke
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/multi-tenancy/README.md
> +# MinIO多租户（Multi-tenant）部署指南 [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/mini
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/orchestration/README.md
> +# Minio部署快速入门 [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio) [![Doc
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/orchestration/dcos/README.md
> +# 在 DC/OS上部署minio [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio) [!
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/orchestration/docker-compose/README.md
> +# 使用Docker Compose部署MinIO [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/m
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/orchestration/docker-swarm/README.md
> +# 使用Docker Swarm部署MinIO [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/min
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/orchestration/kubernetes-yaml/README.md
> +# 使用Kubernetes做MinIO的云原生部署 [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/orchestration/kubernetes/README.md
> +# 使用Kubernetes部署MinIO [![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio
Remove `codecov` info

2019-07-01 17:18 UTC, ebozduman commented on docs/zh_CN/shared-backend/README.md
> +# MinIO共享后端存储快速入门[![Slack](https://slack.min.io/slack?type=svg)](https://slack.min.io) [![Go Report Card](https://goreportcard.com/badge/minio/minio)](https://goreportcard.com/report/minio/minio) [![
Remove `codecov` info

2019-07-01 20:52 UTC, ebozduman requested changes

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +| 微软Windows系统 | 64位     | https://dl.min.io/server/minio/release/windows-amd64/minio |
@Diracal,
I still see the original doc has `minio.exe`.
I think you need to match the original doc.

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +源码安装仅供开发人员和高级用户使用,如果你还没有可以工作的Golang环境， 请参考 [How to install Golang](https://docs.min.io/cn/how-to-install-golang).
And it continues with:
`Minimum version required is [go1.12](https://golang.org/dl/#stable)`

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +service iptalbes restart
Typo:
`iptalbes` => `iptables`

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +iptables -A INPUT -p top -dport 9000 -j ACCEPT
Typo:
`top` => `tcp`

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +firewall-cmd -get-active-zones
`-get-active-zones` => `--get-active-zones`

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +这个命令可以激活zone（s）。现在，应用端口规则到返回以上的相关zones中。例如，如果zone是`public`,使用
`zone（s)` => `zone(s)`

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +firewall-cmd -zone=public -add-port=9000/tcp -permanent
All options are with `--`, rather than a single hyphen `-`:
`-zone=public -add-port=9000/tcp -permanent` => `--zone=public --add-port=9000/tcp --permanent`

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +firewall-cmd -reload
The same hyphen problem:
`-reload` => `--reload`

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +`mc` 提供了UNIX常用命令的替代品，像ls, cat, cp, mirror, diff等。 它支持文件系统和亚马逊S3云存储服务。 更多信息请参考 [mc快速入门](https://docs.min.io/docs/minio-client-quickstart-guide) 。
Original doc calls the link `MinIO Client [Quickstart Guide]`
Yours, `[mc快速入门]`, does not loook the same.

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
> +当在单块磁盘上部署MinIO server,MinIO server允许客户端访问数据目录下已经存在的数据。比如，如果使用`minio server /mnt/data`启动MinIO，那么所有已经在`/mnt/data`目录下存在的数据都可以被客户端访问到。
Of course I don't know Chinese, but repeating the same word twice in this sentence, `MinIO server,MinIO server`, alerted me to ask you to double check if the sentence is ok. If they are needed, then you may add a space in between them.

2019-07-01 20:52 UTC, ebozduman commented on README_zh_CN.md
>  - [使用 `s3cmd`](https://docs.min.io/docs/s3cmd-with-minio)
This link also needs to be replaced with its Chinese version, right?
`https://docs.min.io/docs/s3cmd-with-minio` => `https://docs.min.io/cn/s3cmd-with-minio`

2019-07-10 00:24 UTC, ebozduman commented
@Diracal ,
Your branch has some conflicting files as listed above. Please look into them and resolve.

2019-07-10 19:01 UTC, deekoder commented
for correctness, i will move this review to @harshavardhana since I am not sure about the changes from an exact correctness pov.

2019-07-10 19:03 UTC, deekoder commented
Please fix conflicts @Diracal

2019-08-15 22:31 UTC, harshavardhana commented
Closing this PR as stale, please re-open when you have fixed the review comments by @ebozduman and conflicts.

2019-08-15 22:31 UTC, closed without merging