fix unicode support related bugs in s3select
minio/minio pull request #7877
Opened 2019-07-04 08:04 UTC by yaozongyou

## Description
1. If csv field has leading space, maybe we better not trim it to keep consistent with aws s3.

2. char length is the unicode character length, not the bytes length.

3. fix substring's bug

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-07-04 08:51 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3b68b453-fe36-47e0-bd8a-be10022bc822) |
| mint-large-bucket.sh | :x: [more...](#b9993814-c9bc-4402-9c0d-c2ff0cd3ab66) |
| mint-dist-xl.sh | :x: [more...](#3d079c27-b390-4839-afce-d15b98286d7d) |
<a name="3d079c27-b390-4839-afce-d15b98286d7d"></a>
### 7877-72f4896/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30423
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5dd219797de8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 39 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 17 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 6 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 68,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.56:30423/minio-java-test-2kpnv2/minio-java-test-2hdve21?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190704%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190704T084806Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=498d8500e30365f0606409fef79594e17dc6a0666dc2a512aab13c96bd05da3b}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-2hdve21</Key><BucketName>minio-java-test-2kpnv2</BucketName><Resource>/minio-java-test-2kpnv2/minio-java-test-2hdve21</Resource><RequestId>15AE27FC91FA4AAA</RequestId><HostId>753dc6a4-53b5-4033-b297-3eaa42c2334a</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="3b68b453-fe36-47e0-bd8a-be10022bc822"></a>
### 7877-72f4896/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31350
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 09ee0f1543a0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bw3ytm00i93bdd",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360013,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15AE2802C303B4DD, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="b9993814-c9bc-4402-9c0d-c2ff0cd3ab66"></a>
### 7877-72f4896/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30926
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 11a6459f4e0a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 43 seconds
{
  "name": "mc",
  "duration": "130537",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7044 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-24129  >>> \n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-24129/datafile-0-b`\n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-24129/datafile-1-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-24129/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-24129/datafile-1-b`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-24129/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-24129/datafile-1.03-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-24129/datafile-11-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-24129/datafile-10-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-24129/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-24129/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-24129/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-24129/datafile-33-kB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-24129/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-24129/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-24129/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 457.30 MiB, Speed: 3.51 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-07-04 09:17 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#7e014936-04b0-49dd-a39f-5832b3a0c982) |
| mint-fs.sh | :x: [more...](#3ba4c742-db09-4b53-987e-14563ae20720) |
| mint-dist-xl.sh | :x: [more...](#dc8ea8ca-1886-4b82-a73d-15cb8e687043) |
<a name="3ba4c742-db09-4b53-987e-14563ae20720"></a>
### 7877-ed5be7c/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31710
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5acda5280eec:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gbo20t4beoaiwz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3053,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:31710/aws-sdk-go-test-gbo20t4beoaiwz: dial tcp 72.28.97.60:31710: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="7e014936-04b0-49dd-a39f-5832b3a0c982"></a>
### 7877-ed5be7c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30055
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4b469a067240:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5yolg4re4urunk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 2173,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.60:30055/aws-sdk-go-test-5yolg4re4urunk: dial tcp 72.28.97.60:30055: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="dc8ea8ca-1886-4b82-a73d-15cb8e687043"></a>
### 7877-ed5be7c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31774
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9f5c122f3571:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qig94irvudmh34",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 3056,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:31774/aws-sdk-go-test-qig94irvudmh34: dial tcp 72.28.97.57:31774: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-07-04 15:14 UTC, harshavardhana requested changes

2019-07-04 15:14 UTC, harshavardhana commented on pkg/s3select/csv/reader.go
>  	// This is done even if the field delimiter, Comma, is white space.
We should remove this comment..

2019-07-05 02:01 UTC, yaozongyou commented on pkg/s3select/csv/reader.go
>  	// This is done even if the field delimiter, Comma, is white space.
this comment has been removed.

2019-07-05 02:10 UTC, harshavardhana approved these changes

2019-07-05 02:27 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#204fe8aa-b962-47dc-8d69-4a9ecf80fa1d) |
| mint-large-bucket.sh | :x: [more...](#2a832924-d256-4d21-a3be-18cc4b5244f8) |
| mint-dist-xl.sh | :x: [more...](#f1d51a5a-df94-4bfc-9d6c-d591902da574) |
| mint-gateway-nas.sh | :x: [more...](#26e49935-c77d-431f-8260-363aa6bb0675) |
<a name="26e49935-c77d-431f-8260-363aa6bb0675"></a>
### 7877-713a6ca/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32259
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0a79b85637fa:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 55 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 18 seconds
(8/14) Running minio-dotnet tests ... done in 21 seconds
(9/14) Running minio-go tests ... done in 16 seconds
(10/14) Running minio-java tests ... FAILED in 12 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 194,
  "status": "FAIL",
  "error": "java.net.SocketException: Connection reset >>> [java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115), java.net.SocketOutputStream.write(SocketOutputStream.java:155), okio.Okio$1.write(Okio.java:79), okio.AsyncTimeout$1.write(AsyncTimeout.java:180), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179), okio.RealBufferedSink.write(RealBufferedSink.java:42), okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:306), okio.ForwardingSink.write(ForwardingSink.java:35), okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:163), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179), okio.RealBufferedSink.writeAll(RealBufferedSink.java:107), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:74), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264), okhttp3.RealCall.execute(RealCall.java:93), io.minio.MinioClient.executeReq(MinioClient.java:1111), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executePut(MinioClient.java:1405), io.minio.MinioClient.executePut(MinioClient.java:1427), io.minio.MinioClient.putObject(MinioClient.java:4216), io.minio.MinioClient.putObject(MinioClient.java:4328), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="2a832924-d256-4d21-a3be-18cc4b5244f8"></a>
### 7877-713a6ca/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32533
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e33dc9a66de5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 20 seconds
{
  "name": "mc",
  "duration": "105607",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-25146 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-31733  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-31733/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-31733/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-31733/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-31733/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-31733/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-31733/datafile-10-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-31733/datafile-10-kB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-31733/datafile-100-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-31733/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-31733/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-31733/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-31733/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-31733/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-31733/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-31733/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 494.47 MiB, Speed: 4.69 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="f1d51a5a-df94-4bfc-9d6c-d591902da574"></a>
### 7877-713a6ca/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32460
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp da485d3a7b56:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 25 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 0 seconds
(10/14) Ru [...]

2019-07-05 16:33 UTC, donatello approved these changes

2019-07-05 16:43 UTC, merged