Add text/event-stream for long running http connections
minio/minio pull request #7909
Opened 2019-07-10 22:57 UTC by harshavardhana

## Description
Add text/event-stream for long running http connections

## Motivation and Context
When MinIO is behind a proxy, proxies end up killing
clients when no data is seen on the connection, adding
the right content-type ensures that proxies do not come
in the way.

## How to test this PR?
Setup Nginx proxy in front of MinIO and run `mc admin trace` -without this patch
the clients will timeout prematurely. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (If yes, please add `commit-id` or `PR #` here) It is an old regression
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-07-10 23:05 UTC, poornas requested changes

2019-07-10 23:05 UTC, poornas commented on cmd/admin-handlers.go
>  				switch hr.apiErr {
the TraceHandler itself needs this header set doesn't it @harshavardhana ?

2019-07-10 23:27 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#01d7e2a0-42d9-4a9c-8ed3-a41c440284ce) |
| mint-dist-xl.sh | :x: [more...](#120614c2-7f71-4820-9d54-7e98d9e9ed1c) |
<a name="01d7e2a0-42d9-4a9c-8ed3-a41c440284ce"></a>
### 7909-06a6d6f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32136
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 02935baa4cbc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 14 seconds
{
  "name": "mc",
  "duration": "105014",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21535 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-8637  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-8637/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-8637/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-8637/datafile-1-b`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-8637/datafile-1.03-MB`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-8637/datafile-1-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-8637/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-8637/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-8637/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-8637/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-8637/datafile-33-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-8637/datafile-5-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-8637/datafile-100-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-8637/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-8637/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-8637/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 375.30 MiB, Speed: 3.58 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="120614c2-7f71-4820-9d54-7e98d9e9ed1c"></a>
### 7909-06a6d6f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31340
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f8cf486e933c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 15 seconds
(8/14) Running minio-dotnet tests ... done in 47 seconds
(9/14) Running minio-go tests ... done in 46 seconds
(10/14) Running minio-java tests ... FAILED in 36 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 302,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2i2ek36, objectName=minio-java-test-2rbfrbn, resource=/minio-java-test-2i2ek36/minio-java-test-2rbfrbn, requestId=15B02F3120F5168A, hostId=719d597f-8d29-45ec-a579-c7d02fcbf052)\nrequest={method=DELETE, url=http://72.28.97.55:31340/minio-java-test-2i2ek36/minio-java-test-2rbfrbn?uploadId=ebc71253-ab9f-4be6-b0d6-250775aa5102, headers=Host: 72.28.97.55:31340\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190710T232238Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190710/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-10T23-03-14Z\nVary: Origin\nX-Amz-Request-Id: 15B02F3120F5168A\nX-Xss-Protection: 1; mode=block\nDate: Wed, 10 Jul 2019 23:22:38 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-11 02:25 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b6d86136-83b6-4d0d-ab33-d96fc490a597) |
| mint-compression-dist-xl.sh | :x: [more...](#17e86157-deaa-4e04-a09d-46efa7e5d526) |
| mint-dist-xl.sh | :x: [more...](#80a5f9b0-aa2d-49ec-a95f-4e6aecc52a73) |
<a name="80a5f9b0-aa2d-49ec-a95f-4e6aecc52a73"></a>
### 7909-a9ae75e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32690
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 371ab3441ee4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 15 minutes and 40 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-a3hzgaet4l16ny",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 22,
  "error": "IncompleteBody: You did not provide the number of bytes specified by the Content-Length HTTP header.\n\tstatus code: 400, request id: 15B038DE4547BCFB, host id: ",
  "function": "testListObjects",
  "message": "AWS SDK Go PUT expected to success but got IncompleteBody: You did not provide the number of bytes specified by the Content-Length HTTP header.\n\tstatus code: 400, request id: 15B038DE4547BCFB, host id: ",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="b6d86136-83b6-4d0d-ab33-d96fc490a597"></a>
### 7909-a9ae75e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32670
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c4cbae23495d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 minutes and 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 22 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 32 seconds
{
  "name": "mc",
  "duration": "90431",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7076 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-23192/mc-test-object-8861  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-23192/mc-test-object-8861`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume SThzzDPR`"
}

Executed 6 out of 14 tests successfully.
```
<a name="17e86157-deaa-4e04-a09d-46efa7e5d526"></a>
### 7909-a9ae75e/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31044
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aae97f3cdb48:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 15 minutes and 40 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 27 seconds
(8/14) Running minio-dotnet tests ... done in 28 seconds
(9/14) Running minio-go tests ... done in 40 seconds
(10/14) Running minio-java tests ... FAILED in 33 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 266,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2fjauu7, objectName=null, resource=/minio-java-test-2fjauu7, requestId=15B03920BABCC906, hostId=071b0a8d-95e6-4029-a2d1-ebbc698a039d)\nrequest={method=GET, url=http://72.28.97.61:31044/minio-java-test-2fjauu7?max-uploads=1000&prefix=&delimiter=&uploads=, headers=Host: 72.28.97.61:31044\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190711T022443Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190711/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 305\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-11T01-51-11Z\nVary: Origin\nX-Amz-Request-Id: 15B03920BABCC906\nX-Xss-Protection: 1; mode=block\nDate: Thu, 11 Jul 2019 02:24:43 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeGet(MinioClient.java:1298), io.minio.MinioClient.listIncompleteUploads(MinioClient.java:4946), io.minio.MinioClient.access$300(MinioClient.java:155), io.minio.MinioClient$6$1.populate(MinioClient.java:4796), io.minio.MinioClient$6$1.hasNext(MinioClient.java:4831), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1729), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-11 16:24 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#10a03b0f-cc89-4a90-86b5-c6720c2e9b31) |
| mint-dist-xl.sh | :x: [more...](#c173c810-1eb6-4d5d-b5c3-2de9f7acdbec) |
<a name="10a03b0f-cc89-4a90-86b5-c6720c2e9b31"></a>
### 7909-b797440/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32179
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d2d81ffe99cf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 40 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 28 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 29 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 56 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 352,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3s076t3, objectName=minio-java-test-71krm9, resource=/minio-java-test-3s076t3/minio-java-test-71krm9, requestId=15B066DCE029C82D, hostId=388480d6-f5e2-4d72-b4c4-4a9744aebb5b)\nrequest={method=DELETE, url=http://72.28.97.54:32179/minio-java-test-3s076t3/minio-java-test-71krm9?uploadId=df8e5f15-91da-4146-83dd-7b8e55656d92, headers=Host: 72.28.97.54:32179\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190711T162249Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190711/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-11T16-00-58Z\nVary: Origin\nX-Amz-Request-Id: 15B066DCE029C82D\nX-Xss-Protection: 1; mode=block\nDate: Thu, 11 Jul 2019 16:22:49 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="c173c810-1eb6-4d5d-b5c3-2de9f7acdbec"></a>
### 7909-b797440/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30638
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d5a242a002dd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 1 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 1 seconds
(8/14) Running minio-dotnet tests ... done in 48 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 22 seconds
(10/14) Running minio-java tests ... FAILED in 41 seconds
{
  "name": "minio-java",
  "function": "presignedGetObject(String bucketName, String objectName)",
  "duration": 55,
  "status": "FAIL",
  "error": "java.lang.Exception: failed to read object. Response: Response{protocol=http/1.1, code=503, message=Service Unavailable, url=http://72.28.97.58:30638/minio-java-test-2dg9he0/minio-java-test-2dja93q?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190711%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190711T161946Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=766da8b647d9ff0e172c3776a970c51114ef4049fa4d0dec727a8e38998fd451}, Response body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>SlowDown</Code><Message>Please reduce your request</Message><Key>minio-java-test-2dja93q</Key><BucketName>minio-java-test-2dg9he0</BucketName><Resource>/minio-java-test-2dg9he0/minio-java-test-2dja93q</Resource><RequestId>15B066B234B9374F</RequestId><HostId>4523ca1d-2223-44f5-a41b-5210f368d8b9</HostId></Error> >>> [FunctionalTest.readObject(FunctionalTest.java:201), FunctionalTest.presignedGetObject_test1(FunctionalTest.java:1767), FunctionalTest.runTests(FunctionalTest.java:2994), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-11 17:49 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3ec6a05b-27a9-4012-9198-0a42fade15e9) |
| mint-dist-xl.sh | :x: [more...](#61e983fd-d7bb-4d32-adfb-992308a49d2d) |
<a name="61e983fd-d7bb-4d32-adfb-992308a49d2d"></a>
### 7909-ad40a67/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31895
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 99fe663e4da1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 41 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 48 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 7 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 728,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2v5mtu, objectName=minio-java-test-1ob3ilr, resource=/minio-java-test-2v5mtu/minio-java-test-1ob3ilr, requestId=15B06B75F87C234B, hostId=efd23d6e-9c5b-463a-9211-c758d324b61e)\nrequest={method=DELETE, url=http://72.28.97.58:31895/minio-java-test-2v5mtu/minio-java-test-1ob3ilr?uploadId=42844a20-f0ce-4d7a-8d62-cb094f5b751c, headers=Host: 72.28.97.58:31895\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190711T174705Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190711/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-11T17-26-44Z\nVary: Origin\nX-Amz-Request-Id: 15B06B75F87C234B\nX-Xss-Protection: 1; mode=block\nDate: Thu, 11 Jul 2019 17:47:05 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="3ec6a05b-27a9-4012-9198-0a42fade15e9"></a>
### 7909-ad40a67/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30451
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0d175cac20be:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 3 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 18 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 37 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 39 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 346,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3n4gigl, objectName=minio-java-test-1c6m4jg, resource=/minio-java-test-3n4gigl/minio-java-test-1c6m4jg, requestId=15B06B9004B9018B, hostId=58c91586-8793-4713-8351-59267fcc65c8)\nrequest={method=DELETE, url=http://72.28.97.53:30451/minio-java-test-3n4gigl/minio-java-test-1c6m4jg?uploadId=44bdd3c9-0c4b-44da-827a-93058e950e26, headers=Host: 72.28.97.53:30451\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190711T174856Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190711/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-11T17-26-44Z\nVary: Origin\nX-Amz-Request-Id: 15B06B9004B9018B\nX-Xss-Protection: 1; mode=block\nDate: Thu, 11 Jul 2019 17:48:57 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-11 18:23 UTC, poornas approved these changes

2019-07-11 19:09 UTC, Praveenrajmani approved these changes
LGTM

2019-07-11 20:19 UTC, merged