Enable config for NAS gateway mode
minio/minio pull request #7948
Opened 2019-07-18 18:22 UTC by harshavardhana

## Description
Enable config for NAS gateway mode

## Motivation and Context
Starting with #7751 we don't store config
in etcd anymore, allow NAS to honor config
on disk.

## How to test this PR?
Just use `minio gateway nas ~/test` and use `mc admin config set` commands. 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-07-18 18:48 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#5f7aa474-5fdf-46ac-856d-d435f434038a) |
| mint-large-bucket.sh | :x: [more...](#672fb2a4-5332-4824-8f1f-0415cf628a6e) |
| mint-dist-xl.sh | :x: [more...](#07c71b0d-8b36-431b-b7cd-fd48be56a44d) |
<a name="672fb2a4-5332-4824-8f1f-0415cf628a6e"></a>
### 7948-f7c8ce7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32460
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ef821ebbb4f1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 19 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 23 seconds
{
  "name": "mc",
  "duration": "105057",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-6221 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-7694  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-7694/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-7694/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-7694/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-7694/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-7694/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-7694/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-7694/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-7694/datafile-10-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-7694/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-7694/datafile-33-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-7694/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-7694/datafile-5-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-7694/datafile-6-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-7694/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-7694/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 490.49 MiB, Speed: 4.67 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="07c71b0d-8b36-431b-b7cd-fd48be56a44d"></a>
### 7948-f7c8ce7/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30824
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ff6ab6f424b7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 54 seconds
(8/14) Running minio-dotnet tests ... done in 46 seconds
(9/14) Running minio-go tests ... done in 59 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 10 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 466,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-11rnv7b, objectName=minio-java-test-2tqmd39, resource=/minio-java-test-11rnv7b/minio-java-test-2tqmd39, requestId=15B294B6BA943FD4, hostId=d0c5cd9d-8458-4041-b61a-685f2a9d6907)\nrequest={method=DELETE, url=http://72.28.97.59:30824/minio-java-test-11rnv7b/minio-java-test-2tqmd39?uploadId=66de96a3-3ec8-474f-9fd6-c4cb6675d96b, headers=Host: 72.28.97.59:30824\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190718T184533Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190718/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-18T18-25-57Z\nVary: Origin\nX-Amz-Request-Id: 15B294B6BA943FD4\nX-Xss-Protection: 1; mode=block\nDate: Thu, 18 Jul 2019 18:45:33 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="5f7aa474-5fdf-46ac-856d-d435f434038a"></a>
### 7948-f7c8ce7/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30523
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5ea5c3e4ab20:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yihwi02a0gkpj6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360013,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B294AC0E65134C, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-07-23 05:36 UTC, harshavardhana commented
Ping @vadmeste @poornas

2019-07-23 06:03 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#4d64698e-2225-42e1-98b3-d6513b639a2e) |
| mint-dist-xl.sh | :x: [more...](#28ba2570-aa06-4fc6-974c-de32f258112b) |
<a name="4d64698e-2225-42e1-98b3-d6513b639a2e"></a>
### 7948-7883574/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32508
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b625302bc6f8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 5 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 7 seconds
{
  "name": "mc",
  "duration": "120975",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-19937 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-17202/mc-test-object-18534  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-17202/mc-test-object-18534`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume stCdIABB`"
}

Executed 6 out of 14 tests successfully.
```
<a name="28ba2570-aa06-4fc6-974c-de32f258112b"></a>
### 7948-7883574/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31860
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ad9dd00d618c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 32 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 47 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 16 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 658,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3nhfsd9, objectName=minio-java-test-urdlan, resource=/minio-java-test-3nhfsd9/minio-java-test-urdlan, requestId=15B3F3D917D6A59D, hostId=33e878cf-fb9b-4f1e-b323-02021eb4517a)\nrequest={method=DELETE, url=http://72.28.97.57:31860/minio-java-test-3nhfsd9/minio-java-test-urdlan?uploadId=d6918afe-877a-4c8b-a56d-da624ede91de, headers=Host: 72.28.97.57:31860\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190723T060009Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190723/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-23T05-40-56Z\nVary: Origin\nX-Amz-Request-Id: 15B3F3D917D6A59D\nX-Xss-Protection: 1; mode=block\nDate: Tue, 23 Jul 2019 06:00:09 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-24 09:59 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0cdefb0f-2a62-4f12-ac1e-a5573a7757cc) |
| mint-compression-fs.sh | :x: [more...](#048f165a-c091-4d00-b90e-53bd3bd25767) |
| mint-dist-xl.sh | :x: [more...](#ca31d992-b937-4761-8088-389064a3b9c9) |
<a name="048f165a-c091-4d00-b90e-53bd3bd25767"></a>
### 7948-ce54d68/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32384
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 369ddc3690d5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-3jfnyk6csjphqf",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12282,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32384/aws-sdk-go-test-3jfnyk6csjphqf: dial tcp 72.28.97.57:32384: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="ca31d992-b937-4761-8088-389064a3b9c9"></a>
### 7948-ce54d68/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:30406
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fba941e479cf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-i1j1sw6e0iikpw",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 11543,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:30406/aws-sdk-go-test-i1j1sw6e0iikpw: dial tcp 72.28.97.57:30406: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0cdefb0f-2a62-4f12-ac1e-a5573a7757cc"></a>
### 7948-ce54d68/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32453
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 719b1331bc81:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 14 seconds
(5/14) Running awscli tests ... done in 2 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 32 seconds
{
  "name": "mc",
  "duration": "88245",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7616 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-16546/mc-test-object-9284  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-16546/mc-test-object-9284`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume ZbyIqeGB`"
}

Executed 6 out of 14 tests successfully.
```

2019-07-24 15:59 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#9c9416ec-dc74-466f-bc1f-ad4da0f12846) |
| mint-dist-xl.sh | :x: [more...](#17f3eafb-0c64-48ba-a754-c21519491c89) |
<a name="17f3eafb-0c64-48ba-a754-c21519491c89"></a>
### 7948-0ec3211/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30592
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f0c5c235f7c3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 7 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 6 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 22 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix: minio, recursive: true",
  "duration": 598,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-16ev2vk, objectName=minio-java-test-2vsn552, resource=/minio-java-test-16ev2vk/minio-java-test-2vsn552, requestId=15B462FF6278B4D5, hostId=6a1db0b9-71cf-450f-ba34-6ec8eafc3410)\nrequest={method=DELETE, url=http://72.28.97.52:30592/minio-java-test-16ev2vk/minio-java-test-2vsn552?uploadId=bfe90f40-80c8-45be-8cf2-325c2179d5ab, headers=Host: 72.28.97.52:30592\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190724T155659Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190724/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-24T15-36-52Z\nVary: Origin\nX-Amz-Request-Id: 15B462FF6278B4D5\nX-Xss-Protection: 1; mode=block\nDate: Wed, 24 Jul 2019 15:56:59 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test3(FunctionalTest.java:1679), FunctionalTest.runTests(FunctionalTest.java:2990), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="9c9416ec-dc74-466f-bc1f-ad4da0f12846"></a>
### 7948-0ec3211/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32185
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d67a7f8188a9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 13 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-jewvormquuliiz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12628,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32185/aws-sdk-go-test-jewvormquuliiz: dial tcp 72.28.97.57:32185: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-07-24 16:24 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#74cb93cc-173d-4e9c-8530-6ebcb0c0cb98) |
| mint-dist-xl.sh | :x: [more...](#b2f25bcc-890a-4d2f-9a24-8bd360f389ba) |
<a name="74cb93cc-173d-4e9c-8530-6ebcb0c0cb98"></a>
### 7948-a3e8033/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32450
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aa862a0169f9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ap6uo94ios25nq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12552,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32450/aws-sdk-go-test-ap6uo94ios25nq: dial tcp 72.28.97.57:32450: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="b2f25bcc-890a-4d2f-9a24-8bd360f389ba"></a>
### 7948-a3e8033/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30749
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 64d8681a74bc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 11 seconds
(8/14) Running minio-dotnet tests ... done in 45 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 9 seconds
(10/14) Running minio-java tests ... FAILED in 47 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 521,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-26j5iu, objectName=minio-java-test-i1q7j7, resource=/minio-java-test-26j5iu/minio-java-test-i1q7j7, requestId=15B46457607A463E, hostId=9ea391c6-9cec-4d13-bf95-a19d8dffd78f)\nrequest={method=DELETE, url=http://72.28.97.61:30749/minio-java-test-26j5iu/minio-java-test-i1q7j7?uploadId=e01dcd96-86e3-4a78-b26f-d49132c91703, headers=Host: 72.28.97.61:30749\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190724T162137Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190724/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 359\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-24T16-01-55Z\nVary: Origin\nX-Amz-Request-Id: 15B46457607A463E\nX-Xss-Protection: 1; mode=block\nDate: Wed, 24 Jul 2019 16:21:37 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.removeIncompleteUploads_test(FunctionalTest.java:1719), FunctionalTest.runTests(FunctionalTest.java:2992), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-24 20:35 UTC, poornas requested changes
if user edits the backend config json instead of using mc admin config get/set [with the incoming PR) and leaves the config in an inconsistent state, it will neither get reloaded nor reported. Suggest logging if error in validating config.

2019-07-24 20:47 UTC, harshavardhana commented
> if user edits the backend config json instead of using mc admin config get/set [with the incoming PR) and leaves the config in an inconsistent state, it will neither get reloaded nor reported. Suggest logging if error in validating config.

If user edits backend he is on his own @poornas - config.json is considered like metadata maintained by MinIO we don't need to be paranoid about it.

2019-07-24 20:51 UTC, poornas approved these changes

2019-07-24 21:31 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#bc285109-4851-42d8-a481-923d9af8e511) |
| mint-large-bucket.sh | :x: [more...](#16f17196-aaf5-42e1-a073-9817435ef034) |
| mint-dist-xl.sh | :x: [more...](#de7ee19a-33ff-4004-91a3-c17ec51be8f2) |
<a name="16f17196-aaf5-42e1-a073-9817435ef034"></a>
### 7948-7b4ef13/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30811
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ed62f9b221bf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 3 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 38 seconds
{
  "name": "mc",
  "duration": "111471",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-29163 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-23261  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-23261/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-23261/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-23261/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-23261/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-23261/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-23261/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-23261/datafile-100-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-23261/datafile-129-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-23261/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-23261/datafile-11-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-23261/datafile-5-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-23261/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-23261/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-23261/datafile-6-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-23261/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 501.87 MiB, Speed: 4.52 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="de7ee19a-33ff-4004-91a3-c17ec51be8f2"></a>
### 7948-7b4ef13/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30226
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 77baead05a5e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 51 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 0 seconds
(10/14) Running minio-java tests ... FAILED in 40 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName)",
  "duration": 1196,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2atls0t, objectName=minio-java-test-21ges1o, resource=/minio-java-test-2atls0t/minio-java-test-21ges1o, requestId=15B474E515B5D65D, hostId=e695a6bb-74d6-4469-b4f3-2cd4f0c00aad)\nrequest={method=DELETE, url=http://72.28.97.55:30226/minio-java-test-2atls0t/minio-java-test-21ges1o?uploadId=f8e28905-5e2f-42cc-b45c-c344979db69b, headers=Host: 72.28.97.55:30226\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190724T212457Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190724/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-24T21-04-29Z\nVary: Origin\nX-Amz-Request-Id: 15B474E515B5D65D\nX-Xss-Protection: 1; mode=block\nDate: Wed, 24 Jul 2019 21:24:58 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test1(FunctionalTest.java:1601), FunctionalTest.runTests(FunctionalTest.java:2988), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="bc285109-4851-42d8-a481-923d9af8e511"></a>
### 7948-7b4ef13/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32321
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bec2d6f2936f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 2 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 42 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 49 seconds
(10/14) Running minio-java tests ... done in 17 seconds
(11/14) Running minio-js tests ... done in 38 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 12 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1050, in test_list_objects_with_1001_files\n    client.put_object(bucket_name, path_prefix + object_name + '_' + str_i, KB_1_reader, KB_1)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 838, in put_object\n    progress=progress)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1551, in _do_put_object\n    content_sha256=sha256_hex\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1901, in _url_open\n    object_name).get_exception()\nminio.error.NoSuchBucket: NoSuchBucket: message: The specified bucket does not exist.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most  [...]

2019-07-25 23:29 UTC, kannappanr approved these changes
LGTM

2019-07-25 23:56 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#094cc7dd-81b6-4a05-9781-04755160eed7) |
| mint-dist-xl.sh | :x: [more...](#ee8b9a16-2dc2-4bd9-ae9c-87af2e1dbf8c) |
<a name="094cc7dd-81b6-4a05-9781-04755160eed7"></a>
### 7948-54e0624/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31416
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ae2a84029e79:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 11 seconds
(5/14) Running awscli tests ... done in 2 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 1 minutes and 49 seconds
{
  "name": "mc",
  "duration": "106109",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-334 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-19282/mc-test-object-30468  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-19282/mc-test-object-30468`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nmc: <ERROR> Session safely terminated. To resume session `mc session resume bSTYLmmr`"
}

Executed 6 out of 14 tests successfully.
```
<a name="ee8b9a16-2dc2-4bd9-ae9c-87af2e1dbf8c"></a>
### 7948-54e0624/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32392
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d0701361125f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 40 seconds
(8/14) Running minio-dotnet tests ... done in 37 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 12 seconds
(10/14) Running minio-java tests ... FAILED in 45 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 985,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1dsoeoi, objectName=minio-java-test-1tlltg1, resource=/minio-java-test-1dsoeoi/minio-java-test-1tlltg1, requestId=15B4CB6A0BF922B1, hostId=a3b45ab5-376b-4327-b853-2df54aadff77)\nrequest={method=DELETE, url=http://72.28.97.56:32392/minio-java-test-1dsoeoi/minio-java-test-1tlltg1?uploadId=bcf891f9-8138-441c-97a7-000db254a859, headers=Host: 72.28.97.56:32392\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20190725T235026Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20190725/us-east-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-07-25T23-32-26Z\nVary: Origin\nX-Amz-Request-Id: 15B4CB6A0BF922B1\nX-Xss-Protection: 1; mode=block\nDate: Thu, 25 Jul 2019 23:50:27 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executeDelete(MinioClient.java:1347), io.minio.MinioClient.abortMultipartUpload(MinioClient.java:5149), io.minio.MinioClient.putObject(MinioClient.java:4337), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1639), FunctionalTest.runTests(FunctionalTest.java:2989), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```

2019-07-26 00:41 UTC, merged