[web-router] update the white list for favicons
minio/minio pull request #8024
Opened 2019-08-03 14:56 UTC by das7pad

## Description
Complete #7408 in adding the new favicon routes to the white list.

## Motivation and Context
See #8023 

## How to test this PR?
Request `http://HOST:PORT/minio/favicon-32x32.png`, should return 200 with icon data.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression #7408 22b4fe0a51bc58a63a11b3d5311b17bb5909f70c
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed

Closes #8023

2019-08-03 15:21 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#97346afd-fed8-4ea2-8579-847529e7cbc3) |
| mint-dist-xl.sh | :x: [more...](#e5df0fe8-e3ff-405c-9ccb-7f2c03414886) |
<a name="e5df0fe8-e3ff-405c-9ccb-7f2c03414886"></a>
### 8024-9c01763/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31811
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d21eb07a9261:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 35 seconds
(8/14) Running minio-dotnet tests ... done in 42 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 43 seconds
(10/14) Running minio-java tests ... FAILED in 6 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream body, long size, String contentType)",
  "args": "contentType: application/javascript",
  "duration": 781,
  "status": "FAIL",
  "error": "java.net.ProtocolException: unexpected end of stream >>> [okhttp3.internal.http1.Http1Codec$FixedLengthSink.close(Http1Codec.java:318), okio.ForwardingSink.close(ForwardingSink.java:47), okio.RealBufferedSink.close(RealBufferedSink.java:248), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264), okhttp3.RealCall.execute(RealCall.java:93), io.minio.MinioClient.executeReq(MinioClient.java:1111), io.minio.MinioClient.execute(MinioClient.java:1070), io.minio.MinioClient.executePut(MinioClient.java:1405), io.minio.MinioClient.executePut(MinioClient.java:1427), io.minio.MinioClient.putObject(MinioClient.java:4216), io.minio.MinioClient.putObject(MinioClient.java:4328), io.minio.MinioClient.putObject(MinioClient.java:4183), FunctionalTest.testPutObjectUnknownStreamSize(FunctionalTest.java:548), FunctionalTest.putObject_test8(FunctionalTest.java:576), FunctionalTest.runTests(FunctionalTest.java:2962), FunctionalTest.main(FunctionalTest.java:3118)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="97346afd-fed8-4ea2-8579-847529e7cbc3"></a>
### 8024-9c01763/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32156
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e4e03f99facf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 24 seconds
{
  "name": "mc",
  "duration": "110808",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-6789 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-3751  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-3751/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-3751/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-3751/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-3751/datafile-1-b`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-3751/datafile-10-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-3751/datafile-1.03-MB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-3751/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-3751/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-3751/datafile-100-kB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-3751/datafile-5-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-3751/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-3751/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-3751/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-3751/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-3751/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 496.02 MiB, Speed: 4.48 MiB/s"
}

Executed 6 out of 14 tests successfully.
```

2019-08-05 09:16 UTC, kanagarajkm approved these changes

2019-08-05 21:31 UTC, kaankabalak approved these changes

2019-08-05 21:33 UTC, harshavardhana requested changes
We should also change generic-handlers.go usage of `favicon.ico`

2019-08-06 09:21 UTC, das7pad commented
@harshavardhana done in ee41afe37bd255cb35434d2badd365c0fdc1525e.

2019-08-06 09:45 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#42a155af-5100-499a-afcb-71306d4052da) |
| mint-compression-fs.sh | :x: [more...](#66114f3b-e06e-4baf-879f-b9ff6be4fa2b) |
| mint-worm.sh | :x: [more...](#35cba5ef-be34-4eff-875a-cbe224dbc9cb) |
<a name="42a155af-5100-499a-afcb-71306d4052da"></a>
### 8024-ee41afe/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31714
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2366ba229916:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 18 seconds
{
  "name": "mc",
  "duration": "100293",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-28199 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-10404  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-10404/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-10404/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-10404/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-10404/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-10404/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-10404/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-10404/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-10404/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-10404/datafile-11-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-10404/datafile-129-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-10404/datafile-33-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-10404/datafile-5243880-b`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-10404/datafile-6-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-10404/datafile-5-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-10404/datafile-65-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 525.13 MiB, Speed: 5.24 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="66114f3b-e06e-4baf-879f-b9ff6be4fa2b"></a>
### 8024-ee41afe/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32409
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a172bf843766:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-n5pku2j356oee6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 12283,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32409/aws-sdk-go-test-n5pku2j356oee6: dial tcp 72.28.97.57:32409: connect: no route to host",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="35cba5ef-be34-4eff-875a-cbe224dbc9cb"></a>
### 8024-ee41afe/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32526
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ba17f62d31e:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 12 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-i07b2f42tasrlohun2w01qdtxwmg8z6wdhg69xvni7cx15bsoi4ezra",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 12054,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.57:32526/bucket-i07b2f42tasrlohun2w01qdtxwmg8z6wdhg69xvni7cx15bsoi4ezra: dial tcp 72.28.97.57:32526: connect: no route to host",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```

2019-08-06 12:07 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#c165a80c-f34e-49bb-9521-8cc7172f50de) |
| mint-large-bucket.sh | :x: [more...](#ada70f22-e59a-4339-b5c2-728ddbb2fb07) |
<a name="ada70f22-e59a-4339-b5c2-728ddbb2fb07"></a>
### 8024-92b285d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32767
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ca476d1a0a4b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 12 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 2 minutes and 36 seconds
{
  "name": "mc",
  "duration": "115158",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-128 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-10066  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-10066/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-10066/datafile-0-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-10066/datafile-1-kB`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-10066/datafile-1-b`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-10066/datafile-10-MB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-10066/datafile-1.03-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-10066/datafile-100-kB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-10066/datafile-10-kB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-10066/datafile-11-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-10066/datafile-33-kB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-10066/datafile-129-MB`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-10066/datafile-5-MB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-10066/datafile-5243880-b`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-10066/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-10066/datafile-6-MB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-10-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-11-MB`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-65-MB`. Please reduce your request\nTotal: 233.17 MiB, Transferred: 525.42 MiB, Speed: 4.57 MiB/s"
}

Executed 6 out of 14 tests successfully.
```
<a name="c165a80c-f34e-49bb-9521-8cc7172f50de"></a>
### 8024-92b285d/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30438
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c1ae384916b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5x9p52g3trsg4n",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 360016,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15B853C4FD15BBE5, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
{"detail": "Authentication credentials were not provided."}

2019-08-10 22:38 UTC, kannappanr commented
ping @kaankabalak @kanagarajkm please review the new commit

2019-08-12 04:58 UTC, kanagarajkm approved these changes

2019-08-12 05:16 UTC, harshavardhana approved these changes

2019-08-12 05:17 UTC, merged