Build staticcheck and misspell as pre-built binaries are not available on all archs
minio/minio pull request #8220
Opened 2019-09-11 13:51 UTC by vivkong

## Description
Build staticcheck and misspell as pre-built binaries are not available on all archs

## Motivation and Context
Allow `make test` to run on s390x

## How to test this PR?
Running `make test` on s390x would now pass as it was failing.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-09-11 14:13 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#1098cd4c-c069-479f-82d9-b5f1fc8938ef) |
| mint-compression-dist-xl.sh | :x: [more...](#00cdf846-1809-4f3d-975f-c7e962497c7e) |
| mint-dist-xl.sh | :x: [more...](#dae36d79-7da9-4e29-91a1-ad5d99938b43) |
<a name="dae36d79-7da9-4e29-91a1-ad5d99938b43"></a>
### 8220-84b6a0a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31714
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bf5f742f953f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... FAILED in 51 seconds
{"name": "awscli", "duration": 4178, "function": "aws --endpoint-url http://72.28.97.56:31714 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-12783/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (2.3 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (4.6 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (9.0 MiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (7.1 MiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (8.3 MiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (9.0 MiB/s) with 1 file(s) remaining  
Completed 2.0 MiB/65.0 MiB (9.8 MiB/s) with 1 file(s) remaining  
Completed 2.2 MiB/65.0 MiB (10.5 MiB/s) with 1 file(s) remaining 
Completed 2.5 MiB/65.0 MiB (11.2 MiB/s) with 1 file(s) remaining 
Completed 2.8 MiB/65.0 MiB (12.1 MiB/s) with 1 file(s) remaining 
Completed 3.0 MiB/65.0 MiB (12.6 MiB/s) with 1 file(s) remaining 
Completed 3.2 MiB/65.0 MiB (13.3 MiB/s) with 1 file(s) remaining 
Completed 3.5 MiB/65.0 MiB (14.1 MiB/s) with 1 file(s) remaining 
Completed 3.8 MiB/65.0 MiB (14.8 MiB/s) with 1 file(s) remaining 
Completed 4.0 MiB/65.0 MiB (15.5 MiB/s) with 1 file(s) remaining 
Completed 4.2 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining 
Completed 4.5 MiB/65.0 MiB (16.4 MiB/s) with 1 file(s) remaining 
Completed 4.8 MiB/65.0 MiB (16.8 MiB/s) with 1 file(s) remaining 
Completed 5.0 MiB/65.0 MiB (17.6 MiB/s) with 1 file(s) remaining 
Completed 5.2 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining 
Completed 5.5 MiB/65.0 MiB (18.5 MiB/s) with 1 file(s) remaining 
Completed 5.8 MiB/65.0 MiB (19.0 MiB/s) with 1 file(s) remaining 
Completed 6.0 MiB/65.0 MiB (19.3 MiB/s) with 1 file(s) remaining 
Completed 6.2 MiB/65.0 MiB (20.0 MiB/s) with 1 file(s) remaining 
Completed 6.5 MiB/65.0 MiB (20.4 MiB/s) with 1 file(s) remaining 
Completed 6.8 MiB/65.0 MiB (20.9 MiB/s) with 1 file(s) remaining 
Completed 7.0 MiB/65.0 MiB (21.2 MiB/s) with 1 file(s) remaining 
Completed 7.2 MiB/65.0 MiB (21.8 MiB/s) with 1 file(s) remaining 
Completed 7.5 MiB/65.0 MiB (22.3 MiB/s) with 1 file(s) remaining 
Completed 7.8 MiB/65.0 MiB (22.7 MiB/s) with 1 file(s) remaining 
Completed 8.0 MiB/65.0 MiB (23.0 MiB/s) with 1 file(s) remaining 
Completed 8.2 MiB/65.0 MiB (23.6 MiB/s) with 1 file(s) remaining 
Completed 8.5 MiB/65.0 MiB (24.1 MiB/s) with 1 file(s) remaining 
Completed 8.8 MiB/65.0 MiB (24.8 MiB/s) with 1 file(s) remaining 
Completed 9.0 MiB/65.0 MiB (25.4 MiB/s) with 1 file(s) remaining 
Completed 9.2 MiB/65.0 MiB (26.0 MiB/s) with 1 file(s) remaining 
Completed 9.5 MiB/65.0 MiB (26.5 MiB/s) with 1 file(s) remaining 
Completed 9.8 MiB/65.0 MiB (27.0 MiB/s) with 1 file(s) remaining 
Completed 10.0 MiB/65.0 MiB (27.5 MiB/s) with 1 file(s) remaining
Completed 10.2 MiB/65.0 MiB (28.2 MiB/s) with 1 file(s) remaining
Completed 10.5 MiB/65.0 MiB (28.5 MiB/s) with 1 file(s) remaining
Completed 10.8 MiB/65.0 MiB (28.7 MiB/s) with 1 file(s) remaining
Completed 11.0 MiB/65.0 MiB (29.4 MiB/s) with 1 file(s) remaining
Completed 11.2 MiB/65.0 MiB (29.9 MiB/s) with 1 file(s) remaining
Completed 11.5 MiB/65.0 MiB (30.3 MiB/s) with 1 file(s) remaining
Completed 11.8 MiB/65.0 MiB (30.5 MiB/s) with 1 file(s) remaining
Completed 12.0 MiB/65.0 MiB (31.1 MiB/s) with 1 file(s) remaining
Completed 12.2 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining
Completed 12.5 MiB/65.0 MiB (32.1 MiB/s) with 1 file(s) remaining
Completed 12.8 MiB/65.0 MiB (32.5 MiB/s) with 1 file(s) remaining
Completed 13.0 MiB/65.0 MiB (33.0 MiB/s) with 1 file(s) remaining
Completed 13.2 MiB/65.0 MiB (33.0 MiB/s) with 1 file(s) remaining
Completed 13.5 MiB/65.0 MiB (33.4 MiB/s) with 1 file(s) remaining
Completed 13.8 MiB/65.0 MiB (33.5 MiB/s) with 1 file(s) remaining
Completed 14.0 MiB/65.0 MiB (34.0 MiB/s) with 1 file(s) remaining
Completed 14.2 MiB/65.0 MiB (34.3 MiB/s) with 1 file(s) remaining
Completed 14.5 MiB/65.0 MiB (34.5 MiB/s) with 1 file(s) remaining
Completed 14.8 MiB/65.0 MiB (35.0 MiB/s) with 1 file(s) remaining
Completed 15.0 MiB/65.0 MiB (35.2 MiB/s) with 1 file(s) remaining
Completed 15.2 MiB/65.0 MiB (35.6 MiB/s) with 1 file(s) remaining
Completed 15.5 MiB/65.0 MiB (36.1 MiB/s) with 1 file(s) remaining
Completed 15.8 MiB/65.0 MiB (36.2 MiB/s) with 1 file(s) remaining
Completed 16.0 MiB/65.0 MiB (36.6 MiB/s) with 1 file(s) remaining
Completed 16.2 MiB/65.0 MiB (36.8 MiB/s) with 1 file(s) remaining
Completed 16.5 MiB/65.0 MiB (37.2 MiB/s) with 1 file(s) remaining
Completed 16.8 MiB/65.0 MiB (37.5 MiB/s) with 1 file(s) remaining
Completed 17.0 MiB/65.0 MiB (37.6 MiB/s) with 1 file(s) remaining
Completed 17.2 MiB/65.0 MiB (38.1 MiB/s) with 1 file(s) remaining
Completed 17.5 MiB/65.0 MiB (38.1 MiB/s) with 1 file(s) remaining
Completed 17.8 MiB/65.0 MiB (38.6 MiB/s) with 1 file(s) remaining
Completed 18.0 MiB/65.0 MiB (38.6 MiB/s) with 1 file(s) remaining
Completed 18.2 MiB/65.0 MiB (38.9 MiB/s) with 1 file(s) remaining
Completed 18.5 MiB/65.0 MiB (39.0 MiB/s) with 1 file(s) remaining
Completed 18.8 MiB/65.0 MiB (39.2 MiB/s) with 1 file(s) remaining
Completed 19.0 MiB/65.0 MiB (39.2 MiB/s) with 1 file(s) remaining
Completed 19.2 MiB/65.0 MiB (39.5 MiB/s) with 1 file(s) remaining
Completed 19.5 MiB/65.0 MiB (39.5 MiB/s) with 1 file(s) remaining
Completed 19.8 MiB/65.0 MiB (39.8 MiB/s) with 1 file(s) remaining
Completed 20.0 MiB/65.0 MiB (39.7 MiB/s) with 1 file(s) remaining
Completed 20.2 MiB/65.0 MiB (39.9 MiB/s) with 1 file(s) remaining
Completed 20.5 MiB/65.0 MiB (40.1 MiB/s) with 1 file(s) remaining
Completed 20.8 MiB/65.0 MiB (40.3 MiB/s) with 1 file(s) remaining
Completed 21.0 MiB/65.0 MiB (40.2 MiB/s) with 1 file(s) remaining
Completed 21.2 MiB/65.0 MiB (39.9 MiB/s) with 1 file(s) remaining
Completed 21.5 MiB/65.0 MiB (40.0 MiB/s) with 1 file(s) remaining
Completed 21.8 MiB/65.0 MiB (39.9 MiB/s) with 1 file(s) remaining
Completed 22.0 MiB/65.0 MiB (40.0 MiB/s) with 1 file(s) remaining
Completed 22.2 MiB/65.0 MiB (40.0 MiB/s) with 1 file(s) remaining
Completed 22.5 MiB/65.0 MiB (39.9 MiB/s) with 1 file(s) remaining
Completed 22.8 MiB/65.0 MiB (39.7 MiB/s) with 1 file(s) remaining
Completed 23.0 MiB/65.0 MiB (39.4 MiB/s) with 1 file(s) remaining
Completed 23.2 MiB/65.0 MiB (39.6 MiB/s) with 1 file(s) remaining
Completed 23.5 MiB/65.0 MiB (39.4 MiB/s) with 1 file(s) remaining
Completed 23.8 MiB/65.0 MiB (39.3 MiB/s) with 1 file(s) remaining
Completed 24.0 MiB/65.0 MiB (39.0 MiB/s) with 1 file(s) remaining
Completed 24.2 MiB/65.0 MiB (38.8 MiB/s) with 1 file(s) remaining
Completed 24.5 MiB/65.0 MiB (39.1 MiB/s) with 1 file(s) remaining
Completed 24.8 MiB/65.0 MiB (38.5 MiB/s) with 1 file(s) remaining
Completed 25.0 MiB [...]

2019-09-11 21:40 UTC, harshavardhana commented
https://github.com/minio/minio/pull/8222 proper fix is added here @vivkong - we shall close this PR.

2019-09-12 01:37 UTC, harshavardhana commented
@vivkong please update the code in `mc` PR to follow current master.

2019-09-12 15:27 UTC, vivkong commented
Thanks @harshavardhana.  But `staticcheck` doesn't have prebuilt binaries for s390x.  I will need to do `go get` for s390x.  I'll update my change to incorporate the latest changes from #8222.

2019-09-12 15:30 UTC, harshavardhana commented
> Thanks @harshavardhana. But `staticcheck` doesn't have prebuilt binaries for s390x. I will need to do `go get` for s390x. I'll update my change to incorporate the latest changes from #8222.

Understood you may do `go get` as a fallback but remember that PRs should be sent to the latest master, not to the tagged releases.

2019-09-12 15:35 UTC, vivkong commented
Right this PR is targetting minio's `master` branch - my own branch name is confusing but it is intended for master.  I don't think I can change the branch name at this point.

2019-09-12 15:38 UTC, harshavardhana commented
> Right this PR is targetting minio's `master` branch - my own branch name is confusing but it is intended for master. I don't think I can change the branch name at this point.

If you did you won't have conflict @vivkong on Makefile. It looks like you did check out the release tag instead based on the latest master.

2019-09-12 15:47 UTC, vivkong commented
I had a conflict earlier but it should be resolved now.  I've updated this PR so my change can be applied on top of the latest `Makefile` from `master`.  Thanks.

I'll also start updating the PR for `mc`.

2019-09-12 15:50 UTC, harshavardhana requested changes

2019-09-12 15:50 UTC, harshavardhana commented on Makefile
> +	@which staticcheck 1>/dev/null || (echo "Installing staticcheck" && GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck@2019.2.3)
make sure that `GO111MODULE=off` - to avoid modifying current working directory `go.mod`

2019-09-12 16:12 UTC, vivkong commented on Makefile
> +	@which staticcheck 1>/dev/null || (echo "Installing staticcheck" && GO111MODULE=on go get honnef.co/go/tools/cmd/staticcheck@2019.2.3)
Thanks I've made the change

2019-09-12 16:20 UTC, harshavardhana approved these changes

2019-09-15 06:24 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#52653185-79e2-430c-909b-a98854ea28c8) |
| mint-xl.sh | :x: [more...](#c67f6841-037c-4069-aa40-5325c2bf2d47) |
| mint-compression-dist-xl.sh | :x: [more...](#3a98c4be-40bc-4ee6-bc27-698e2eac0b5c) |
<a name="52653185-79e2-430c-909b-a98854ea28c8"></a>
### 8220-26783b2/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30900
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dceafd8a1bd3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-o1ib1q6krolfb6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365043,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C487BDD56F9833, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="3a98c4be-40bc-4ee6-bc27-698e2eac0b5c"></a>
### 8220-26783b2/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30088
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 087aee84996e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 48 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 5 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 36 seconds
(11/14) Running minio-js tests ... done in 56 seconds
(12/14) Running minio-py tests ... FAILED in 4 minutes and 28 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "duration": 292,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 152, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "args": {
    "bucket_name": "minio-py-test-9210f3ee-70a2-45b1-92f5-1feba3aee1bc",
    "presigned_get_object_url": "http://72.28.97.52:30088/minio-py-test-9210f3ee-70a2-45b1-92f5-1feba3aee1bc/b787f04c-e25c-48d6-a89e-7726dcc00d39?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190915%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190915T061640Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=947b4c47731ebc83025d32d8803c0f74cc67a7b3a9c97e3723f8f93554463762",
    "object_name": "b787f04c-e25c-48d6-a89e-7726dcc00d39"
  },
  "message": "'content-language'",
  "name": "minio-py:test_presigned_get_object_response_headers",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="c67f6841-037c-4069-aa40-5325c2bf2d47"></a>
### 8220-26783b2/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31270
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0bd17b572cd9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5rihanrbf2sevk",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365923,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C487BF075AA27B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```

2019-09-16 20:10 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#97d57bc0-968e-4d52-a363-d8ab932cd6c6) |
| mint-large-bucket.sh | :x: [more...](#b807785e-914a-4183-a47b-079bcbc53d49) |
<a name="97d57bc0-968e-4d52-a363-d8ab932cd6c6"></a>
### 8220-d53f2f3/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31101
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9b881f6bd92c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-miqheaukgi2se6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365190,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C503E672733BBB, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="b807785e-914a-4183-a47b-079bcbc53d49"></a>
### 8220-d53f2f3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30597
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 56f2d9bb5da4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 59 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 16 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 7 seconds
{
  "args": {},
  "duration": 105570,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

2019-09-16 21:33 UTC, vadmeste approved these changes
LGTM

2019-09-17 00:29 UTC, merged