Allow caching only in gateway mode.
minio/minio pull request #8232
Opened 2019-09-12 21:16 UTC by poornas

This PR changes cache on PUT behavior to background fill the cache
after PutObject completes. This will avoid concurrency issues as in #8219.

Added cleanup of partially filled cache to prevent cache corruption
- Fixes #8208

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-09-12 21:56 UTC, harshavardhana requested changes

2019-09-12 21:56 UTC, harshavardhana commented on docs/disk-caching/DESIGN.md
>  - Bucket policies are not cached, so anonymous operations are not supported when backend is offline.
Does this still hold true?

2019-09-12 21:57 UTC, poornas commented on docs/disk-caching/DESIGN.md
>  - Bucket policies are not cached, so anonymous operations are not supported when backend is offline.
yes

2019-09-12 23:10 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#056a1161-80cf-41b7-95fa-c1f31a12c6b8) |
| mint-large-bucket.sh | :x: [more...](#7eca6b34-40fd-4461-a413-25f13e2ee69c) |
<a name="056a1161-80cf-41b7-95fa-c1f31a12c6b8"></a>
### 8232-d6df7e0/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31691
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 53f80cbae19f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-aakzcxjp6swq9s",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365506,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C3D34A5B9D401A, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="7eca6b34-40fd-4461-a413-25f13e2ee69c"></a>
### 8232-d6df7e0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31343
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 64ffe5e1337e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 4 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... FAILED in 19 seconds
{
  "name": "mc",
  "duration": "6504",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-21571 --quiet --no-color cp myminio/mc-test-bucket-22139/mc-test-object-2854 mc-test-object-2854.downloaded  >>> \n`myminio/mc-test-bucket-22139/mc-test-object-2854` -> `mc-test-object-2854.downloaded`\nmc: <ERROR> Failed to copy `http://72.28.97.54:31343/mc-test-bucket-22139/mc-test-object-2854`. read tcp 172.17.0.10:35144->72.28.97.54:31343: read: connection reset by peer\nmc: <ERROR> Session safely terminated. To resume session `mc session resume xhixQSIU`"
}

Executed 6 out of 14 tests successfully.
```

2019-09-16 21:12 UTC, harshavardhana approved these changes

2019-09-16 21:23 UTC, kannappanr approved these changes
LGTM

2019-09-16 21:24 UTC, merged