log server startup messages to admin console api
minio/minio pull request #8264
Opened 2019-09-17 23:45 UTC by poornas

## Description

## Motivation and Context
allow `mc admin console` to show server startup messages on remote console.

## How to test this PR?
use corresponding mc PR.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-09-18 01:51 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#92d5b965-ada9-49e9-b520-6963f29e83e6) |
| mint-large-bucket.sh | :x: [more...](#647d752a-e833-4a8f-ab98-a7e0b863d9af) |
| mint-dist-xl.sh | :x: [more...](#eb1a2863-9435-48ba-984e-196735e808d8) |
| mint-gateway-nas.sh | :x: [more...](#271dac27-6fac-4132-88a7-53782c539147) |
<a name="647d752a-e833-4a8f-ab98-a7e0b863d9af"></a>
### 8264-e63c919/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30981
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 16930e2a0a44:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... FAILED in 5 minutes and 8 seconds
{
  "name": "aws-sdk-php",
  "function": "getObject ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5d818a906e08b",
    "Object": "obj1"
  },
  "duration": "21",
  "status": "FAIL",
  "error": "Error executing \"PutObject\" on \"http://72.28.97.55:30981/aws-sdk-php-5d818a906e08b/obj1\"; AWS HTTP error: Client error: `PUT http://72.28.97.55:30981/aws-sdk-php-5d818a906e08b/obj1` resulted in a `400 Bad Request` response:\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of byte (truncated...)\n IncompleteBody (client): You did not provide the number of bytes specified by the Content-Length HTTP header. - <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>IncompleteBody</Code><Message>You did not provide the number of bytes specified by the Content-Length HTTP header.</Message><Key>obj1</Key><BucketName>aws-sdk-php-5d818a906e08b</BucketName><Resource>/aws-sdk-php-5d818a906e08b/obj1</Resource><RequestId>15C564ECAC16302B</RequestId><HostId>a292be13-6411-4a75-886f-1ea94176effc</HostId></Error>"
}

Executed 2 out of 14 tests successfully.
```
<a name="eb1a2863-9435-48ba-984e-196735e808d8"></a>
### 8264-e63c919/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31138
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4a820151393c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 5 seconds
(8/14) Running minio-dotnet tests ... done in 46 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 28 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 4 seconds
(11/14) Running minio-js tests ... done in 53 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 41 seconds
{
  "status": "FAIL",
  "duration": 110,
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 152, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "message": "'content-language'",
  "name": "minio-py:test_presigned_get_object_response_headers",
  "args": {
    "object_name": "38d0c116-8cb7-44d3-9417-ef7c108b1320",
    "bucket_name": "minio-py-test-860df687-5ab1-4893-acbb-60e42ac9ce7b",
    "presigned_get_object_url": "http://72.28.97.60:31138/minio-py-test-860df687-5ab1-4893-acbb-60e42ac9ce7b/38d0c116-8cb7-44d3-9417-ef7c108b1320?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190918%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190918T015111Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=ee8c2a98d04fd7649430e5d1702233e402034cfcefbfdb36c3287c2347438a2b"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="271dac27-6fac-4132-88a7-53782c539147"></a>
### 8264-e63c919/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32503
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 88a20b7b8f78:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 37 seconds
(8/14) Running minio-dotnet tests ... done in 27 seconds
(9/14) Running minio-go tests ... done in 41 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 10 seconds
(11/14) Running minio-js tests ... done in 32 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 52 seconds
{
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"404\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-18T01-25-28Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C56521B3825054\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Wed, 18 Sep 2019 01:47:20 GMT\"]}}",
    "bucket_name": "minio-py-test-1c19fc18-eeee-4bc6-b2d6-e49531cdddfb",
    "response.status": 403,
    "presigned_get_object_url": "http://72.28.97.58:32503/minio-py-test-1c19fc18-eeee-4bc6-b2d6-e49531cdddfb/45ea8a16-4478-4832-9c53-17cec6d044b7?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190918%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190918T014715Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=a8d0681acbc04789056f5922058a2964a8214ebcba7706aa5060ccc99cbca4df",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>45ea8a16-4478-4832-9c53-17cec6d044b7</Key><BucketName>minio-py-test-1c19fc18-eeee-4bc6-b2d6-e49531cdddfb</BucketName><Resource>/minio-py-test-1c19fc18-eeee-4bc6-b2d6-e49531cdddfb/45ea8a16-4478-4832-9c53-17cec6d044b7</Resource><RequestId>15C56521B3825054</RequestId><HostId></HostId></Error>",
    "object_name": "45ea8a16-4478-4832-9c53-17cec6d044b7",
    "response.reason": "Forbidden"
   [...]

2019-09-18 03:23 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#1b8088e6-daa8-4491-9aca-a199ce2626bf) |
| mint-compression-dist-xl.sh | :x: [more...](#11570ce3-6f9d-46ce-8cf3-e5a5ef37e64a) |
| mint-gateway-nas.sh | :x: [more...](#82fd7387-375d-491a-bff1-e928a0da2550) |
<a name="82fd7387-375d-491a-bff1-e928a0da2550"></a>
### 8264-d100476/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32210
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 524b942f55e0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 54 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 1 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 1 seconds
(11/14) Running minio-js tests ... done in 32 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 19 seconds
{
  "args": {
    "bucket_name": "minio-py-test-412ee696-d819-405e-9d8d-f25cd37321f2",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>9333c414-1c02-4159-aa29-30588a06aae6</Key><BucketName>minio-py-test-412ee696-d819-405e-9d8d-f25cd37321f2</BucketName><Resource>/minio-py-test-412ee696-d819-405e-9d8d-f25cd37321f2/9333c414-1c02-4159-aa29-30588a06aae6</Resource><RequestId>15C56A21FF2B8144</RequestId><HostId></HostId></Error>",
    "presigned_get_object_url": "http://72.28.97.53:32210/minio-py-test-412ee696-d819-405e-9d8d-f25cd37321f2/9333c414-1c02-4159-aa29-30588a06aae6?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190918%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190918T031854Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=e5226598613ea1be86b1c33779e9ebe54a756f848bc96c4aa6687cccfc098b4d",
    "response.status": 403,
    "response.reason": "Forbidden",
    "object_name": "9333c414-1c02-4159-aa29-30588a06aae6",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"404\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-18T02-57-13Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C56A21FF2B8144\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Wed, 18 Sep 2019 03:18:59 GMT\"]}}"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "status": "FAIL",
  "duration": 55
}

Executed 11 out of 14 tests successfully.
```
<a name="1b8088e6-daa8-4491-9aca-a199ce2626bf"></a>
### 8264-d100476/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32168
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 86abebb1b798:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 25 seconds
(8/14) Running minio-dotnet tests ... done in 3 minutes and 10 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 31 seconds
{
  "args": {},
  "duration": 116405,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="11570ce3-6f9d-46ce-8cf3-e5a5ef37e64a"></a>
### 8264-d100476/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32276
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aad49bad388c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 6 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 43 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 23 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 48 seconds
(11/14) Running minio-js tests ... done in 53 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 35 seconds
{
  "args": {
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>f0ac99c9-1a06-49e9-8814-ab3bc1e87bf9</Key><BucketName>minio-py-test-029eebd5-a031-41e3-a1e0-0263bc001c34</BucketName><Resource>/minio-py-test-029eebd5-a031-41e3-a1e0-0263bc001c34/f0ac99c9-1a06-49e9-8814-ab3bc1e87bf9</Resource><RequestId>15C56A528D25B513</RequestId><HostId>0a8c1b28-a631-47bb-9db7-45a79b9ecb65</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-18T02-57-13Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C56A528D25B513\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Wed, 18 Sep 2019 03:22:27 GMT\"]}}",
    "bucket_name": "minio-py-test-029eebd5-a031-41e3-a1e0-0263bc001c34",
    "response.status": 403,
    "presigned_get_object_url": "http://72.28.97.59:32276/minio-py-test-029eebd5-a031-41e3-a1e0-0263bc001c34/f0ac99c9-1a06-49e9-8814-ab3bc1e87bf9?X-Amz [...]

2019-09-18 03:55 UTC, harshavardhana requested changes

2019-09-18 03:55 UTC, harshavardhana commented on cmd/peer-rest-server.go
> +			switch entry := entry.(type) {
enc.Encode(entry) is good enough there is no reason for type conversion..

2019-09-18 03:55 UTC, harshavardhana commented on cmd/consolelogger.go
> +	var lg interface{}
`var lg madmin.LogInfo` is enough here too it doesn't need to be an interface..

2019-09-19 20:53 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e43eae1b-5295-4489-bb48-929479d2c8dc) |
| mint-fs.sh | :x: [more...](#5ccde02d-6c52-4eb9-b02e-680f29b8c756) |
<a name="e43eae1b-5295-4489-bb48-929479d2c8dc"></a>
### 8264-d6278b7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31844
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9382ac1cf266:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 1 minutes and 33 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 34 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 54 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 38 seconds
{
  "args": {},
  "duration": 80691,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="5ccde02d-6c52-4eb9-b02e-680f29b8c756"></a>
### 8264-d6278b7/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30597
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b3bf66470922:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 26 seconds
(8/14) Running minio-dotnet tests ... done in 22 seconds
(9/14) Running minio-go tests ... done in 39 seconds
(10/14) Running minio-java tests ... done in 11 seconds
(11/14) Running minio-js tests ... FAILED in 11 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-9e7ca935-ce7f-48b0-ab1a-f6068b831faa, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 2327,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TCP.onread (net.js:580:26)"
}

Executed 10 out of 14 tests successfully.
```

2019-09-20 17:51 UTC, krisis approved these changes

2019-09-22 08:20 UTC, harshavardhana approved these changes

2019-09-22 08:24 UTC, merged

2019-09-22 10:16 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#daa03f59-0edf-4895-aa50-cd8185e63132) |
| mint-xl.sh | :x: [more...](#f6c5cafb-76f9-4c75-a1e3-a6b7d91cf2cb) |
| mint-large-bucket.sh | :x: [more...](#d8a1c555-e1da-4741-9c22-83b0cd1e6fc4) |
| mint-compression-fs.sh | :x: [more...](#b023c857-7890-4d82-bdc2-7f9b804fa634) |
| mint-dist-xl.sh | :x: [more...](#0df8a073-aa9b-4a9e-84b9-46455d29e439) |
<a name="b023c857-7890-4d82-bdc2-7f9b804fa634"></a>
### 8264-937c2dc/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31999
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2952b97362f8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 50 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 36 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 41 seconds
(10/14) Running minio-java tests ... done in 14 seconds
(11/14) Running minio-js tests ... FAILED in 6 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-c0315531-a254-4d58-b215-dbb0016dddca, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 1273,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at exports._errnoException (util.js:1020:11) at TCP.onread (net.js:580:26)"
}

Executed 10 out of 14 tests successfully.
```
<a name="f6c5cafb-76f9-4c75-a1e3-a6b7d91cf2cb"></a>
### 8264-937c2dc/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31324
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 391c1d7ca7be:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 31 seconds
(8/14) Running minio-dotnet tests ... done in 22 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 5 seconds
(10/14) Running minio-java tests ... done in 22 seconds
(11/14) Running minio-js tests ... FAILED in 3 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 14,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:83:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:153:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:77:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```
<a name="d8a1c555-e1da-4741-9c22-83b0cd1e6fc4"></a>
### 8264-937c2dc/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31549
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 78c8a17e033a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 21 seconds
(5/14) Running awscli tests ... done in 2 minutes and 31 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 23 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 30 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 9 seconds
{
  "args": {},
  "duration": 97835,
  "error": "The specified key does not exist.",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "Stat failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="daa03f59-0edf-4895-aa50-cd8185e63132"></a>
### 8264-937c2dc/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31503
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7da3c831aa77:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 36 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 5 seconds
(10/14) Running minio-java tests ... FAILED in 17 seconds
{
  "name": "minio-java",
  "function": "removeIncompleteUpload(String bucketName, String objectName)",
  "duration": 733,
  "status": "FAIL",
  "error": "java.net.SocketException: Connection reset >>> [java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:115), java.net.SocketOutputStream.write(SocketOutputStream.java:155), okio.Okio$1.write(Okio.java:79), okio.AsyncTimeout$1.write(AsyncTimeout.java:180), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179), okio.RealBufferedSink.write(RealBufferedSink.java:42), okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:306), okio.ForwardingSink.write(ForwardingSink.java:35), okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:163), okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:179), okio.RealBufferedSink.writeAll(RealBufferedSink.java:107), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:74), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInte [...]