Cleanup audit and trace ResponseWriter functions
minio/minio pull request #8283
Opened 2019-09-20 22:21 UTC by poornas

## Description

## Motivation and Context
Reduce code duplication across audit and trace functions.

## How to test this PR?

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-09-20 22:59 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#cd389be4-6451-4e2a-afb8-4eea859dff02) |
| mint-xl.sh | :x: [more...](#01d871b6-7f7e-4ba9-ae9a-86b8be2d05ee) |
<a name="01d871b6-7f7e-4ba9-ae9a-86b8be2d05ee"></a>
### 8283-68abccc/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31912
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 098ca2f3cf2c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-jaygshctmsvipo",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365712,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C646F419A7F13F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="cd389be4-6451-4e2a-afb8-4eea859dff02"></a>
### 8283-68abccc/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30291
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c2570c511b7c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 47 seconds
(8/14) Running minio-dotnet tests ... done in 28 seconds
(9/14) Running minio-go tests ... done in 44 seconds
(10/14) Running minio-java tests ... done in 26 seconds
(11/14) Running minio-js tests ... FAILED in 16 seconds
{
  "name": "minio-js",
  "function": "fGetObject(bucketName, objectName, filePath)",
  "args": "bucketName:minio-js-test-1d1a58b3-b77e-4060-8471-c2fd2a818000, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB.download",
  "duration": 1654,
  "status": "FAIL",
  "error": "Error: Size mismatch between downloaded file and the object at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:965:12 at nextTask (node_modules/minio/node_modules/async/dist/async.js:4578:13) at next (node_modules/minio/node_modules/async/dist/async.js:4586:13) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:325:20 at FSReqWrap.oncomplete (fs.js:123:15)"
}

Executed 10 out of 14 tests successfully.
```

2019-09-21 01:14 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#687be8e1-0948-44f4-bf81-4a5a77d860e4) |
| mint-compression-fs.sh | :x: [more...](#afbcfee3-1e80-4090-956d-cd4a52b56900) |
| mint-fs.sh | :x: [more...](#93455837-b6b5-4276-88dd-22c47b42a337) |
<a name="93455837-b6b5-4276-88dd-22c47b42a337"></a>
### 8283-7bb83e2/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30387
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 437868c0bf9d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 50 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 39 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 55 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 1 seconds
(11/14) Running minio-js tests ... done in 46 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 38 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "AccessDenied: message: Access Denied",
  "status": "FAIL",
  "duration": 106,
  "args": {
    "object_name": "d26a39aa-9892-4881-9ae8-c225c0d6818d",
    "response.status": 403,
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-21T00-47-17Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C64EE673E549CE\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Sat, 21 Sep 2019 01:11:11 GMT\"]}}",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>d26a39aa-9892-4881-9ae8-c225c0d6818d</Key><BucketName>minio-py-test-870e25fc-4ffd-46e2-8784-d20e5b84abbe</BucketName><Resource>/minio-py-test-870e25fc-4ffd-46e2-8784-d20e5b84abbe/d26a39aa-9892-4881-9ae8-c225c0d6818d</Resource><RequestId>15C64EE673E549CE</RequestId><HostId>2357f4a7-e2c7-4901-9af1-88ea92e69c28</HostId></Error>",
    "bucket_name": "minio-py-test-870e25fc-4ffd-46e2-8784-d20e5b84abbe",
    "presigned_get_object_url": "http://72.28.97.52:30387/minio-py-test-870e25fc-4ffd-46e2-8784-d20e5b84abbe/d26a39aa-9892-4881-9ae8-c225c0d6818d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190921%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190921T011106Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=ba7af58420e800f62eafa67589b4cf65f857d372f4b7b0231a4dcbd99285dd27"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="afbcfee3-1e80-4090-956d-cd4a52b56900"></a>
### 8283-7bb83e2/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31891
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8e7ed7e6bcac:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 53 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 41 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 57 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 3 seconds
(11/14) Running minio-js tests ... done in 45 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 42 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "status": "FAIL",
  "duration": 62,
  "args": {
    "response.status": 403,
    "bucket_name": "minio-py-test-a5e6b07a-3c01-44b2-afb1-f319e5912e76",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>2c06f9f3-19e1-49ff-b2b7-75478d2bc3ae</Key><BucketName>minio-py-test-a5e6b07a-3c01-44b2-afb1-f319e5912e76</BucketName><Resource>/minio-py-test-a5e6b07a-3c01-44b2-afb1-f319e5912e76/2c06f9f3-19e1-49ff-b2b7-75478d2bc3ae</Resource><RequestId>15C64EE8E334578B</RequestId><HostId>0fc5b432-ab87-44f7-b518-998db54f10fe</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-21T00-47-17Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C64EE8E334578B\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Sat, 21 Sep 2019 01:11:22 GMT\"]}}",
    "object_name": "2c06f9f3-19e1-49ff-b2b7-75478d2bc3ae",
    "presigned_get_object_url": "http://72.28.97.53:31891/minio-py-test-a5e6b07a-3c01-44b2-afb1-f319e5912e76/2c06f9f3-19e1-49ff-b2b7-75478d2bc3ae?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190921%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190921T011116Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=f1dc1f6d6293d77476c3a4e24435c3abf01e8a0bf1d49691b545afe4c8492eee",
    "response.reason": "Forbidden"
  },
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Execute [...]

2019-09-21 06:52 UTC, harshavardhana requested changes

2019-09-21 06:52 UTC, harshavardhana commented on cmd/logger/audit.go
> + * MinIO Cloud Storage, (C) 2018,2019 MinIO, Inc.
```suggestion
 * MinIO Cloud Storage, (C) 2018, 2019 MinIO, Inc.
```

2019-09-21 06:52 UTC, harshavardhana commented on cmd/logger/audit.go
> +	LogBody bool
can all the exposed fields come together and all the private after for readability?

2019-09-21 06:52 UTC, harshavardhana commented on cmd/logger/audit.go
> +	}
timeToFirstByte might have slight timing mistakes here for example time taken to fill the bytes.Buffer might get added for large headers and bodies, which may not capture the right timeToFirstByte perhaps the logic

```
if lrw.timeToFirstByte == 0 {
		lrw.timeToFirstByte = time.Now().UTC().Sub(lrw.startTime)
	}
```

should be done right at L59

2019-09-21 06:52 UTC, harshavardhana commented on cmd/logger/audit.go
>  	timeToFirstByte time.Duration
btw we should use this in Trace.Info() output timeToFirstByte, atleast as part of the struct and provided in --json output

2019-09-21 06:52 UTC, harshavardhana commented on cmd/http-tracer.go
>  		Latency:     rs.Time.Sub(rq.Time),
this can also be calculated using rs.Time.Sub(rw.startTime) which may be a bit more accurate...

2019-09-23 06:33 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#3946d307-6f66-4ed2-9725-c0f009b77aca) |
| mint-dist-xl.sh | :x: [more...](#20ddf03f-b9aa-43cb-9f7b-d73356543c8c) |
<a name="20ddf03f-b9aa-43cb-9f7b-d73356543c8c"></a>
### 8283-d9e4304/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31650
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2ca85ba0e619:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 4 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 57 seconds
(8/14) Running minio-dotnet tests ... done in 47 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 11 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 43 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 2 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 32 seconds
{
  "args": {
    "presigned_get_object_url": "http://72.28.97.58:31650/minio-py-test-2dfe410b-c4f0-4271-bd60-09b3b8dc02e8/95a10c64-cad1-4acc-8528-6e72337e4426?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190923%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190923T062636Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=94c88868e990786bf164418e7811e97094cc1021a67cc5224de701edee7ccdac",
    "object_name": "95a10c64-cad1-4acc-8528-6e72337e4426",
    "bucket_name": "minio-py-test-2dfe410b-c4f0-4271-bd60-09b3b8dc02e8"
  },
  "message": "'content-language'",
  "status": "FAIL",
  "duration": 188,
  "name": "minio-py:test_presigned_get_object_response_headers",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="3946d307-6f66-4ed2-9725-c0f009b77aca"></a>
### 8283-d9e4304/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31604
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a9c11dd5fd0b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 43 seconds
(8/14) Running minio-dotnet tests ... done in 25 seconds
(9/14) Running minio-go tests ... done in 56 seconds
(10/14) Running minio-java tests ... done in 25 seconds
(11/14) Running minio-js tests ... FAILED in 14 seconds
{
  "name": "minio-js",
  "function": "fGetObject(bucketName, objectName, filePath, callback)",
  "args": "bucketName:minio-js-test-7ada3ea9-fd70-40e9-a6c5-b0f45a310bbf, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB.download",
  "duration": 587,
  "status": "FAIL",
  "error": "Error: Size mismatch between downloaded file and the object at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:965:12 at nextTask (node_modules/minio/node_modules/async/dist/async.js:4578:13) at next (node_modules/minio/node_modules/async/dist/async.js:4586:13) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:325:20 at FSReqWrap.oncomplete (fs.js:123:15)"
}

Executed 10 out of 14 tests successfully.
```

2019-09-23 06:44 UTC, harshavardhana submitted a review, later dismissed

2019-09-23 06:44 UTC, harshavardhana commented
PTAL at the build failures @poornas

2019-09-23 17:47 UTC, harshavardhana approved these changes

2019-09-23 18:09 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3fdf94b7-b211-4b7e-868b-1f4ca545dc75) |
| mint-large-bucket.sh | :x: [more...](#a1d6bcca-eb84-4a81-a823-4dabb618a3d6) |
| mint-fs.sh | :x: [more...](#ad8cb0ed-2cec-426d-811c-02794ca6c1b6) |
<a name="ad8cb0ed-2cec-426d-811c-02794ca6c1b6"></a>
### 8283-cd154e6/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32597
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp db620960710f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 59 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 22 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 39 seconds
(10/14) Running minio-java tests ... done in 15 seconds
(11/14) Running minio-js tests ... FAILED in 11 seconds
{
  "name": "minio-js",
  "function": "fGetObject(bucketName, objectName, filePath)",
  "args": "bucketName:minio-js-test-e82d8608-fa1f-4af5-9d55-211c6124f652, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB.download",
  "duration": 525,
  "status": "FAIL",
  "error": "Error: Size mismatch between downloaded file and the object at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:965:12 at nextTask (node_modules/minio/node_modules/async/dist/async.js:4578:13) at next (node_modules/minio/node_modules/async/dist/async.js:4586:13) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:325:20 at FSReqWrap.oncomplete (fs.js:123:15)"
}

Executed 10 out of 14 tests successfully.
```
<a name="3fdf94b7-b211-4b7e-868b-1f4ca545dc75"></a>
### 8283-cd154e6/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31314
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f21431095914:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2bfvt3yxuc6amf",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364921,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C7234046D1D15B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a1d6bcca-eb84-4a81-a823-4dabb618a3d6"></a>
### 8283-cd154e6/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31672
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5a3fe77b44b2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 15 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 29 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 1 seconds
{
  "args": {},
  "duration": 97519,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```

2019-09-23 19:34 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#fedae440-c3e7-4c22-a504-0cf559157cd1) |
| mint-fs.sh | :x: [more...](#4995143d-0bba-41d9-a69f-0de37682ba9a) |
<a name="fedae440-c3e7-4c22-a504-0cf559157cd1"></a>
### 8283-ff2e6b9/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32652
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a6910649a210:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 6 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 13 seconds
(5/14) Running awscli tests ... done in 2 minutes and 23 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 18 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 5 seconds
{
  "args": {},
  "duration": 106092,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="4995143d-0bba-41d9-a69f-0de37682ba9a"></a>
### 8283-ff2e6b9/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32461
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aa50a66f356e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 54 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 45 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 45 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 22 seconds
(11/14) Running minio-js tests ... done in 48 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 53 seconds
{
  "duration": 49,
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "status": "FAIL",
  "message": "AccessDenied: message: Access Denied",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "args": {
    "bucket_name": "minio-py-test-eccdfc77-1ecd-4266-a983-29402f44c8db",
    "object_name": "3f447074-f089-4b37-b46e-c3dc78380d88",
    "response.status": 403,
    "presigned_get_object_url": "http://72.28.97.54:32461/minio-py-test-eccdfc77-1ecd-4266-a983-29402f44c8db/3f447074-f089-4b37-b46e-c3dc78380d88?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190923%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190923T192928Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=b55835a3fbfc0827d2815ee880bacdab07c3a7a0a36fe40537fb58324db7c968",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>3f447074-f089-4b37-b46e-c3dc78380d88</Key><BucketName>minio-py-test-eccdfc77-1ecd-4266-a983-29402f44c8db</BucketName><Resource>/minio-py-test-eccdfc77-1ecd-4266-a983-29402f44c8db/3f447074-f089-4b37-b46e-c3dc78380d88</Resource><RequestId>15C727FFD4B1415C</RequestId><HostId>6e53083b-3ab7-4e1a-85aa-3e03a496290b</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-23T19-07-01Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C727FFD4B1415C\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Mon, 23 Sep 2019 19:29:34 GMT\"]}}"
  }
}

Executed 11 out of 14 tests successfully.
```

2019-09-23 20:20 UTC, donatello approved these changes

2019-09-23 20:34 UTC, merged