xl: Avoid healing a bucket in an unformatted disk
minio/minio pull request #8309
Opened 2019-09-25 16:19 UTC by vadmeste

## Description
Healing bucket will create a directory in a disk whether
it is formatted or not. An unformatted disk with data in
it is considered corrupted. This PR will check for
.minio.sys/format.json in each disk before creating the
bucket directory.

## Motivation and Context
Fixes #8188 

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-09-25 16:53 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#887ef373-5095-4761-81b0-1e5b1ffccb64) |
| mint-large-bucket.sh | :x: [more...](#a79e59f6-fda0-4045-aab6-daaece6630b4) |
| mint-compression-fs.sh | :x: [more...](#c77f6c3a-8576-413e-8fd9-747b537368ca) |
| mint-fs.sh | :x: [more...](#b89cf375-fd81-45f4-a383-f3a7ad309346) |
| mint-gateway-nas.sh | :x: [more...](#3032c528-7e7f-4561-810f-a50f1df3f260) |
<a name="a79e59f6-fda0-4045-aab6-daaece6630b4"></a>
### 8309-d20237a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31003
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2a0db97aa887:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 30 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 26 seconds
(9/14) Running minio-go tests ... done in 2 minutes and 23 seconds
(10/14) Running minio-java tests ... done in 3 minutes and 13 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 9 seconds
(12/14) Running minio-py tests ... FAILED in 7 minutes and 44 seconds
{
  "function": "list_objects(bucket_name, prefix, recursive)",
  "args": {
    "object_name": "cd24eed3-10e0-4c2a-84f8-efd256618052_0 ~ cd24eed3-10e0-4c2a-84f8-efd256618052_1000",
    "bucket_name": "minio-py-test-e16af78a-9deb-4ce5-8add-1aaa099dd1bc"
  },
  "duration": 410354,
  "name": "minio-py:test_list_objects_with_1001_files",
  "status": "FAIL",
  "message": "BucketNotEmpty: message: The bucket you tried to delete is not empty.",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1168, in test_list_objects_with_1001_files\n    client.remove_bucket(bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 416, in remove_bucket\n    self._url_open('DELETE', bucket_name=bucket_name)\n  File \"/usr/local/lib/python3.5/dist-packages/minio/api.py\", line 1951, in _url_open\n    object_name).get_exception()\nminio.error.BucketNotEmpty: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2024, in main\n    test_list_objects_with_1001_files(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1170, in test_list_objects_with_1001_files\n    raise Exception(err)\nException: BucketNotEmpty: message: The bucket you tried to delete is not empty.\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="3032c528-7e7f-4561-810f-a50f1df3f260"></a>
### 8309-d20237a/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31324
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 211c3fce6c17:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 42 seconds
(8/14) Running minio-dotnet tests ... done in 26 seconds
(9/14) Running minio-go tests ... done in 54 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 58 seconds
(11/14) Running minio-js tests ... done in 35 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 46 seconds
{
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "message": "AccessDenied: message: Access Denied",
  "args": {
    "presigned_get_object_url": "http://72.28.97.54:31324/minio-py-test-930a1ae6-6cb2-4cb3-86fc-73277880e02a/78b9c47d-99d0-450b-ada0-36fa12b6445d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190925%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190925T164328Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=1fb610fd3d00494238c7c502401c04482d7caaf8ad244ed757636ba8d3252c75",
    "bucket_name": "minio-py-test-930a1ae6-6cb2-4cb3-86fc-73277880e02a",
    "response.reason": "Forbidden",
    "object_name": "78b9c47d-99d0-450b-ada0-36fa12b6445d",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"404\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-25T16-19-37Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C7BC1A17FC8479\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Wed, 25 Sep 2019 16:43:35 GMT\"]}}",
    "response.status": 403,
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>78b9c47d-99d0-450b-ada0-36fa12b6445d</Key><BucketName>minio-py-test-930a1ae6-6cb2-4cb3-86fc-73277880e02a</BucketName><Resource>/minio-py-test-930a1ae6-6cb2-4cb3-86fc-73277880e02a/78b9c47d-99d0-450b-ada0-36fa12b6445d</Resource><RequestId>15C7BC1A17FC8479</RequestId><HostId></HostId></Error>"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "duration": 82,
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="c77f6c3a-8576-413e-8fd9-747b537368ca"></a>
### 8309-d20237a/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32026
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cf5488d08ea0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 1 minutes and 51 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 48 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 54 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 59 seconds
(11/14) Running minio-j [...]

2019-09-26 15:05 UTC, vadmeste commented
Ready for review

2019-09-26 17:32 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#be5f9bfe-d15b-4b50-b351-de907d62a2ba) |
| mint-large-bucket.sh | :x: [more...](#eec2662a-bbdd-473f-9004-b8cb58b807db) |
| mint-dist-xl.sh | :x: [more...](#561e9cdb-86ee-477a-bd49-d8bdca5393fd) |
<a name="be5f9bfe-d15b-4b50-b351-de907d62a2ba"></a>
### 8309-f5a7e65/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31374
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d9135420f6aa:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-c16l4my44pnkt6",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365546,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15C805E0DCD9CE1C, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="561e9cdb-86ee-477a-bd49-d8bdca5393fd"></a>
### 8309-f5a7e65/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30556
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d8379333f45e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 1 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 15 seconds
{
  "name": "mc",
  "duration": "5650",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-25941 --quiet --no-color cp myminio/mc-test-bucket-3442/mc-test-object-1729 mc-test-object-1729.downloaded  >>> \n`myminio/mc-test-bucket-3442/mc-test-object-1729` -> `mc-test-object-1729.downloaded`\nmc: <ERROR> Failed to copy `http://72.28.97.52:30556/mc-test-bucket-3442/mc-test-object-1729`. read tcp 172.17.0.10:39352->72.28.97.52:30556: read: connection reset by peer\nmc: <ERROR> Session safely terminated. To resume session `mc session resume fMgFOUhT`"
}

Executed 6 out of 14 tests successfully.
```
<a name="eec2662a-bbdd-473f-9004-b8cb58b807db"></a>
### 8309-f5a7e65/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31414
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ea2db0f686b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 47 seconds
(2/14) Running aws-sdk-java tests ... done in 13 seconds
(3/14) Running aws-sdk-php tests ... done in 3 minutes and 28 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 minutes and 35 seconds
(5/14) Running awscli tests ... done in 19 minutes and 25 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 7 minutes and 57 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 3 seconds
(9/14) Running minio-go tests ... done in 7 minutes and 49 seconds
(10/14) Running minio-java tests ... done in 1 hours 30 minutes and 19 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 4 seconds
(12/14) Running minio-py tests ... FAILED in 6 minutes and 24 seconds
{
  "status": "FAIL",
  "args": {
    "response.status": 403,
    "bucket_name": "minio-py-test-48b4c2ca-0fe4-43fd-9f2c-ca9c79d325e9",
    "presigned_get_object_url": "http://72.28.97.55:31414/minio-py-test-48b4c2ca-0fe4-43fd-9f2c-ca9c79d325e9/00cbff84-3722-44b7-ab0c-9b35eec81d6d?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20190926%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20190926T173231Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=90543740b73dd850e15527b8781fa7a318177aae9ceec127f1814a8010865221",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>00cbff84-3722-44b7-ab0c-9b35eec81d6d</Key><BucketName>minio-py-test-48b4c2ca-0fe4-43fd-9f2c-ca9c79d325e9</BucketName><Resource>/minio-py-test-48b4c2ca-0fe4-43fd-9f2c-ca9c79d325e9/00cbff84-3722-44b7-ab0c-9b35eec81d6d</Resource><RequestId>15C80D5BC15E9758</RequestId><HostId>a7f189c7-0faa-49f8-9328-1fe900b193bc</HostId></Error>",
    "object_name": "00cbff84-3722-44b7-ab0c-9b35eec81d6d",
    "response.reason": "Forbidden",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-09-26T14-56-35Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15C80D5BC15E9758\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Thu, 26 Sep 2019 17:32:37 GMT\"]}}"
  },
  "duration": 1008,
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```

2019-09-27 20:56 UTC, harshavardhana requested changes
Replacing disks on a live system is not allowed @vadmeste - I am not able to see when will see this problem. We can certainly add this check but it is superfluous because admins are not supposed to replace drives on a running system. Even if they replace today MinIO will actively reject such disks because posix remembers previous DiskInfo. 

The procedure to replace a disk is to take down the concerned server when you are replacing drives for maintenance. 

Now the reproducer is also superfluous because If you manually go and delete the files on the backend MinIO has no way of knowing. This is true for even MakeBucket() not just HealBucket @vadmeste - so there is no correct or conclusive way to fix it other than making this type of redundant checks all over the place in object layer.

IMO we should enhance posix.go to have this check-in `checkDiskFound()` where we verify if the disk is formatted by doing os.Stat() additionally on `format.json` as well.

2019-09-30 10:14 UTC, vadmeste commented
> The procedure to replace a disk is to take down the concerned server when you are replacing drives for maintenance.

We have a parallel requirement that says that we need to heal a disk automatically when a fresh one is inserted, this implicitly means the server will be up and not down for maintenance. 

I was also about to ask the team about the best way to add a lock to prevent formatting disks & healing objects at the same time because it doesn't seem this is done in xl layer (now I understand why)

2019-09-30 10:14 UTC, vadmeste commented
Let's discuss this

2019-09-30 16:15 UTC, harshavardhana commented
That is not how you should interpret that it is not replacing drives on the running server. It is basically for other servers to heal the drive. If you replace drives underneath on a running system anything can happen.

There are many ways it can fail, to make it fool proof you have to move format validation to backend. Not do it from top level.

2019-10-01 22:04 UTC, harshavardhana commented
We should close this PR @vadmeste since the proper fix is being sent by @krishnasrinivas

2019-10-02 10:40 UTC, vadmeste commented
> We should close this PR @vadmeste since the proper fix is being sent by @krishnasrinivas

Closing..

2019-10-02 10:40 UTC, closed without merging