posix: unify ReadFile storage API
minio/minio pull request #8379
Opened 2019-10-10 21:57 UTC by aead

# Description
This commit unifies the ReadFile storage API
such that "legacy" and streaming bitrot uses
the same `ReadFile` API.

This is a refactoring that makes future changes
to bitrot verification and erasure coding easier.
In particular, it simplifies moving streaming
bitrot verification to the "server side" / posix
layer.

With the `ecc` package this commit tries to organize
and simplify the structure of the erasure coding and
content verification layers in the MinIO server.

## Motivation and Context
Bitrot

## How to test this PR?
unit tests

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-10-10 22:30 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#99d6ccf9-363d-4ee9-a778-b5a4827b3e6b) |
| mint-compression-dist-xl.sh | :x: [more...](#47e53cc8-b962-4acd-839a-516969e2f2b2) |
<a name="47e53cc8-b962-4acd-839a-516969e2f2b2"></a>
### 8379-3473ea1/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:30164
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6dedf06d2383:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 45 seconds
(8/14) Running minio-dotnet tests ... done in 57 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 26 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 21 seconds
(11/14) Running minio-js tests ... done in 53 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 44 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "args": {
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>390bbaf2-bce2-412f-893c-3029afc8e18e</Key><BucketName>minio-py-test-74d7f304-9fee-4820-a4fa-a366d12c941c</BucketName><Resource>/minio-py-test-74d7f304-9fee-4820-a4fa-a366d12c941c/390bbaf2-bce2-412f-893c-3029afc8e18e</Resource><RequestId>15CC69A61341FDA1</RequestId><HostId>1545c14d-c04e-480a-bfe0-ae8492b58980</HostId></Error>",
    "response.status": 403,
    "bucket_name": "minio-py-test-74d7f304-9fee-4820-a4fa-a366d12c941c",
    "object_name": "390bbaf2-bce2-412f-893c-3029afc8e18e",
    "presigned_get_object_url": "http://72.28.97.60:30164/minio-py-test-74d7f304-9fee-4820-a4fa-a366d12c941c/390bbaf2-bce2-412f-893c-3029afc8e18e?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191010%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191010T222842Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=6a43db106109a86051ad92f69a068734281f8d5fea49d27f1ecb804ab31b0a1d",
    "response.reason": "Forbidden",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-10T21-57-13Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CC69A61341FDA1\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Thu, 10 Oct 2019 22:28:52 GMT\"]}}"
  },
  "duration": 116,
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL"
}

Executed 11 out of 14 tests successfully.
```
<a name="99d6ccf9-363d-4ee9-a778-b5a4827b3e6b"></a>
### 8379-3473ea1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32151
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4455dfaefcda:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 21 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 21 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 12 seconds
{
  "args": {},
  "duration": 105131,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-3473ea1

2019-10-10 23:03 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#954d84fa-8b65-4d7c-8e86-5d21e6070b40) |
| mint-large-bucket.sh | :x: [more...](#061e9ec0-d86a-4c74-b5db-5dfbce38b8f4) |
| mint-compression-dist-xl.sh | :x: [more...](#7d3f3c9e-dce6-4948-b534-e615dc692bec) |
<a name="954d84fa-8b65-4d7c-8e86-5d21e6070b40"></a>
### 8379-a17e722/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32217
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9434ae8a8dc1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 50 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 47 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 48 seconds
(10/14) Running minio-java tests ... done in 19 seconds
(11/14) Running minio-js tests ... done in 47 seconds
(12/14) Running minio-py tests ... done in 1 minutes and 15 seconds
(13/14) Running s3cmd tests ... FAILED in 5 minutes and 8 seconds
{
  "name": "s3cmd",
  "duration": "303109",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-12280/s3cfg get s3://s3cmd-test-bucket-12813/s3cmd-test-object-4306 s3cmd-test-object-4306.downloaded\nProblem: timeout: timed out\nS3cmd:   2.0.2\npython:   3.5.2 (default, Jul 10 2019, 11:58:48) \n[GCC 5.4.0 20160609]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3092, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3001, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 590, in cmd_object_get\n    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 716, in object_get\n    response = self.recv_file(request, stream, labels, start_position)\n  File \"/usr/local/lib/python3.5/dist-packages/S3/S3.py\", line 1742, in recv_file\n    data = http_response.read(this_chunk)\n  File \"/usr/lib/python3.5/http/client.py\", line 458, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.5/http/client.py\", line 498, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.5/socket.py\", line 575, in readinto\n    return self._sock.recv_into(b)\nsocket.timeout: timed out\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}

Executed 12 out of 14 tests successfully.
```
<a name="061e9ec0-d86a-4c74-b5db-5dfbce38b8f4"></a>
### 8379-a17e722/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32563
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d7179afde203:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 3 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 15 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 1 seconds
{
  "args": {},
  "duration": 80504,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="7d3f3c9e-dce6-4948-b534-e615dc692bec"></a>
### 8379-a17e722/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31457
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d09f64cbc47:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 2 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 53 seconds
(8/14) Running minio-dotnet tests ... done in 48 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 10 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 11 seconds
(11/14) Running minio-js tests ... done in 57 seconds
(12/14) Running minio-py tests ... FAILED in 4 minutes and 14 seconds
{
  "args": {
    "presigned_get_object_url": "http://72.28.97.54:31457/minio-py-test-937d47af-097f-415f-abaf-402ef9390b17/58344ad4-2d9f-45d3-ba16-440bd3199ac2?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191010%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191010T230244Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=5332eaf5d3cadff49f23b33b0f60277257b6216542013cf3c5369c48a2fe2fbe",
    "bucket_name": "minio-py-test-937d47af-097f-415f-abaf-402ef9390b17",
    "object_name": "58344ad4-2d9f-45d3-ba16-440bd3199ac2"
  },
  "name": "minio-py:test_presigned_get_object_response_headers",
  "duration": 103,
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "message": "'content-language'",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent ca [...]

2019-10-11 00:08 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#0eca13df-6f8e-4d79-abad-bc0bb627a7b1) |
| mint-large-bucket.sh | :x: [more...](#91ca87e1-f498-4726-829f-c4cf9f0c7f83) |
<a name="91ca87e1-f498-4726-829f-c4cf9f0c7f83"></a>
### 8379-5aba132/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31621
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ef59bc1de4a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 54 seconds
(4/14) Running aws-sdk-ruby tests ... done in 19 seconds
(5/14) Running awscli tests ... done in 2 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 9 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 20 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 5 seconds
{
  "args": {},
  "duration": 74524,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="0eca13df-6f8e-4d79-abad-bc0bb627a7b1"></a>
### 8379-5aba132/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:32192
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp eb2fd253c624:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 1 seconds
(5/14) Running awscli tests ... done in 58 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 8 seconds
{
  "name": "mc",
  "duration": "4128",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-22358 --quiet --no-color cp myminio/mc-test-bucket-9462/mc-test-object-29468 mc-test-object-29468.downloaded  >>> \n`myminio/mc-test-bucket-9462/mc-test-object-29468` -> `mc-test-object-29468.downloaded`\nmc: <ERROR> Failed to copy `http://72.28.97.54:32192/mc-test-bucket-9462/mc-test-object-29468`. read tcp 172.17.0.6:60582->72.28.97.54:32192: read: connection reset by peer\nmc: <ERROR> Session safely terminated. To resume session `mc session resume BWLMyCrp`"
}

Executed 6 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-5aba132

2019-10-11 00:39 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0700da29-8095-438b-b66a-59eb1281d397) |
<a name="0700da29-8095-438b-b66a-59eb1281d397"></a>
### 8379-e362e8d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31026
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d0e03a23e676:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 4 seconds
(7/14) Running mc tests ... done in 1 minutes and 10 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 18 seconds
{
  "args": {},
  "duration": 103551,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-e362e8d

2019-10-11 01:42 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ff467ce2-6551-45cb-8230-55eeccaa4bff) |
| mint-fs.sh | :x: [more...](#b28da283-ff0d-4d5d-9c5d-413a0a94ff3b) |
<a name="ff467ce2-6551-45cb-8230-55eeccaa4bff"></a>
### 8379-0a42b28/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31844
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bd873765c9b1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 3 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 15 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 56 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 35 seconds
{
  "args": {},
  "duration": 102540,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="b28da283-ff0d-4d5d-9c5d-413a0a94ff3b"></a>
### 8379-0a42b28/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31244
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 23c2874a7d94:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 41 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 48 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 45 seconds
(10/14) Running minio-java tests ... done in 48 seconds
(11/14) Running minio-js tests ... done in 43 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 0 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "args": {
    "bucket_name": "minio-py-test-3dd68664-c163-46bb-a0c5-605cac4f602c",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>10d35ad9-2339-43ff-8664-e67aab0a4d49</Key><BucketName>minio-py-test-3dd68664-c163-46bb-a0c5-605cac4f602c</BucketName><Resource>/minio-py-test-3dd68664-c163-46bb-a0c5-605cac4f602c/10d35ad9-2339-43ff-8664-e67aab0a4d49</Resource><RequestId>15CC73E583B9D8AA</RequestId><HostId>e8710421-8a66-4188-bfcf-76a4e20b20d6</HostId></Error>",
    "response.status": 403,
    "object_name": "10d35ad9-2339-43ff-8664-e67aab0a4d49",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-11T01-09-29Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CC73E583B9D8AA\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 11 Oct 2019 01:36:39 GMT\"]}}",
    "presigned_get_object_url": "http://72.28.97.60:31244/minio-py-test-3dd68664-c163-46bb-a0c5-605cac4f602c/10d35ad9-2339-43ff-8664-e67aab0a4d49?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T013630Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=8840b561441cea560cf85e6ad652233b66607cd0c1634cfcb9a36dace2add38b"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "duration": 60,
  "name": "minio-py:test_presigned_get_object_expiry_5sec"
}

Executed 11 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-0a42b28

2019-10-11 02:30 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#009c5ccd-f9b6-414d-ba96-b3fb1db07418) |
| mint-large-bucket.sh | :x: [more...](#6ccf1593-bc60-4b99-9e67-14d41ef106d2) |
| mint-compression-dist-xl.sh | :x: [more...](#bfdd8a82-91ac-4678-94e1-507345ba2b6d) |
<a name="bfdd8a82-91ac-4678-94e1-507345ba2b6d"></a>
### 8379-7d46042/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32213
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2783b610a559:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 38 seconds
(8/14) Running minio-dotnet tests ... done in 41 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 8 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 25 seconds
(11/14) Running minio-js tests ... done in 51 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 17 seconds
{
  "args": {
    "object_name": "86d9a249-7f97-4c94-ad31-56692ed7e1bd",
    "bucket_name": "minio-py-test-a4591ef7-cbd3-45b8-a554-7de1851efdaf",
    "presigned_get_object_url": "http://72.28.97.58:32213/minio-py-test-a4591ef7-cbd3-45b8-a554-7de1851efdaf/86d9a249-7f97-4c94-ad31-56692ed7e1bd?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T021301Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=3038b819af59f986cacb3fb6a6cca7b4df2e4cb84c5bff2660b05536bf4f9831"
  },
  "message": "'content-language'",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_response_headers",
  "status": "FAIL",
  "duration": 104
}

Executed 11 out of 14 tests successfully.
```
<a name="6ccf1593-bc60-4b99-9e67-14d41ef106d2"></a>
### 8379-7d46042/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30000
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0d7034ba6434:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 32 seconds
(2/14) Running aws-sdk-java tests ... done in 12 seconds
(3/14) Running aws-sdk-php tests ... done in 3 minutes and 11 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 20 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... FAILED in 3 minutes and 21 seconds
{
  "name": "mc",
  "duration": "129667",
  "function": "test_presigned_post_policy_error",
  "status": "FAIL",
  "error": "unknown failure in upload of /mint/data/datafile-1-MB using presigned post policy"
}

Executed 6 out of 14 tests successfully.
```
<a name="009c5ccd-f9b6-414d-ba96-b3fb1db07418"></a>
### 8379-7d46042/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31979
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a7a5ce7f0ed8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-gyfe1c3hhxmczy",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365982,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15CC75A082D15285, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-7d46042

2019-10-11 03:02 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c999dbef-6cfb-4bc6-9a5c-7201cd3ba5e0) |
| mint-compression-dist-xl.sh | :x: [more...](#d5d45168-b625-499d-9a0b-60b39b5530d5) |
| mint-fs.sh | :x: [more...](#eb205028-4087-46b8-914b-a9ea4e61eeb4) |
<a name="d5d45168-b625-499d-9a0b-60b39b5530d5"></a>
### 8379-9954ddb/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:32334
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f4533d95f68a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 0 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 9 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 22 seconds
(11/14) Running minio-js tests ... done in 54 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 20 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "status": "FAIL",
  "duration": 143,
  "message": "'content-language'",
  "args": {
    "bucket_name": "minio-py-test-f6ea6324-216f-4e4b-8981-43c601023220",
    "object_name": "200fe595-c4cb-4a0c-b362-c18f062791d0",
    "presigned_get_object_url": "http://72.28.97.60:32334/minio-py-test-f6ea6324-216f-4e4b-8981-43c601023220/200fe595-c4cb-4a0c-b362-c18f062791d0?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T030131Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=8ccb435f0b4219e76c9a8bddf682029079ac345e1e2ff0470b1b2627b5375228"
  },
  "name": "minio-py:test_presigned_get_object_response_headers"
}

Executed 11 out of 14 tests successfully.
```
<a name="c999dbef-6cfb-4bc6-9a5c-7201cd3ba5e0"></a>
### 8379-9954ddb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31834
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ac78cb712c8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 1 minutes and 23 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 35 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 30 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 35 seconds
{
  "args": {},
  "duration": 108357,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="eb205028-4087-46b8-914b-a9ea4e61eeb4"></a>
### 8379-9954ddb/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31412
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c9d98c0ffc96:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 28 seconds
(9/14) Running minio-go tests ... done in 38 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 8 seconds
(11/14) Running minio-js tests ... done in 42 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 19 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "status": "FAIL",
  "args": {
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>a5ac9ed3-1f46-4bc6-9565-072bbdfc3c64</Key><BucketName>minio-py-test-f7cff15a-e5df-4e01-96de-8ae52586a79c</BucketName><Resource>/minio-py-test-f7cff15a-e5df-4e01-96de-8ae52586a79c/a5ac9ed3-1f46-4bc6-9565-072bbdfc3c64</Resource><RequestId>15CC78580B67BB6E</RequestId><HostId>d7f4338f-6c10-4a14-95b9-4fdd92d5dc87</HostId></Error>",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-11T02-30-24Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CC78580B67BB6E\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 11 Oct 2019 02:58:09 GMT\"]}}",
    "response.status": 403,
    "object_name": "a5ac9ed3-1f46-4bc6-9565-072bbdfc3c64",
    "presigned_get_object_url": "http://72.28.97.52:31412/minio-py-test-f7cff15a-e5df-4e01-96de-8ae52586a79c/a5ac9ed3-1f46-4bc6-9565-072bbdfc3c64?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T025800Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=9dc796981cd0f52d1573ba34c35e5617e0de53c99133c4b635b29050a371c8c1",
    "bucket_name": "minio-py-test-f7cff15a-e5df-4e01-96de-8ae52586a79c"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\ [...]

2019-10-11 04:36 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#67864ffa-6827-4f76-af71-f648c9f2a896) |
| mint-dist-xl.sh | :x: [more...](#30925b23-f54b-413d-9fd6-bd6e68efb557) |
<a name="30925b23-f54b-413d-9fd6-bd6e68efb557"></a>
### 8379-a07ae75/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.60:31235
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 90cd231e1190:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 50 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 13 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 44 seconds
(11/14) Running minio-js tests ... done in 54 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 38 seconds
{
  "message": "AccessDenied: message: Access Denied",
  "duration": 128,
  "args": {
    "response.status": 403,
    "bucket_name": "minio-py-test-96468e75-4491-47d4-8dcf-7968ae815f15",
    "object_name": "e0c67515-e32e-4fdd-97a6-5f18750acd97",
    "presigned_get_object_url": "http://72.28.97.60:31235/minio-py-test-96468e75-4491-47d4-8dcf-7968ae815f15/e0c67515-e32e-4fdd-97a6-5f18750acd97?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T043552Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=eef4e33eeea73885352f1910006ed8731fcff031cf1929b881c1781fa3ea873e",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-11T04-04-41Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CC7DAF35ACCD20\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Fri, 11 Oct 2019 04:36:01 GMT\"]}}",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>e0c67515-e32e-4fdd-97a6-5f18750acd97</Key><BucketName>minio-py-test-96468e75-4491-47d4-8dcf-7968ae815f15</BucketName><Resource>/minio-py-test-96468e75-4491-47d4-8dcf-7968ae815f15/e0c67515-e32e-4fdd-97a6-5f18750acd97</Resource><RequestId>15CC7DAF35ACCD20</RequestId><HostId>13590e4b-cf12-4b60-add2-91900eaa19db</HostId></Error>"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "status": "FAIL",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n"
}

Executed 11 out of 14 tests successfully.
```
<a name="67864ffa-6827-4f76-af71-f648c9f2a896"></a>
### 8379-a07ae75/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32546
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 25f61a182330:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 22 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 16 seconds
{
  "args": {},
  "duration": 46898,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-a07ae75

2019-10-11 18:39 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0bb912cf-a51c-4f12-9bf7-56ccd1d15746) |
| mint-compression-dist-xl.sh | :x: [more...](#6be3c56b-bd08-4018-a91f-2602411d83e9) |
<a name="6be3c56b-bd08-4018-a91f-2602411d83e9"></a>
### 8379-d36d604/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30167
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6512bb4ea2b3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 0 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 5 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 39 seconds
(11/14) Running minio-js tests ... done in 51 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 35 seconds
{
  "message": "'content-language'",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_response_headers",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "args": {
    "bucket_name": "minio-py-test-6c321a6f-f86a-4a80-bccb-f7c2110f6cc1",
    "presigned_get_object_url": "http://72.28.97.54:30167/minio-py-test-6c321a6f-f86a-4a80-bccb-f7c2110f6cc1/3c9bfe8c-75b3-4272-abd9-4c5e77953940?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191011%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191011T183901Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=1d8a8007e22a8282b823395dd7548e62663ca827c615d43f14d5902fe3d9f3a2",
    "object_name": "3c9bfe8c-75b3-4272-abd9-4c5e77953940"
  },
  "duration": 112
}

Executed 11 out of 14 tests successfully.
```
<a name="0bb912cf-a51c-4f12-9bf7-56ccd1d15746"></a>
### 8379-d36d604/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30614
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 87c2cc9b4e16:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 24 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 13 seconds
{
  "args": {},
  "duration": 102303,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-d36d604

2019-10-11 22:16 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#46e76604-cfe9-4d49-b849-d92a7a2c2f9f) |
<a name="46e76604-cfe9-4d49-b849-d92a7a2c2f9f"></a>
### 8379-0289f47/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30808
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0725a4e7c31f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 29 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 27 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 53 seconds
{
  "args": {},
  "duration": 128439,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-0289f47

2019-10-14 13:58 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2dda89dc-18aa-461c-9d54-eced2cf514fc) |
| mint-compression-dist-xl.sh | :x: [more...](#e2bb9a76-83f0-45fd-877a-a8bcea05e471) |
<a name="e2bb9a76-83f0-45fd-877a-a8bcea05e471"></a>
### 8379-1ec45cc/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32563
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 579c89fb28b5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 35 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 44 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 46 seconds
(11/14) Running minio-js tests ... done in 1 minutes and 0 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 29 seconds
{
  "status": "FAIL",
  "message": "'content-language'",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "duration": 122,
  "args": {
    "presigned_get_object_url": "http://72.28.97.51:32563/minio-py-test-a12a697e-7e4b-488d-902e-ce681ee8e81c/1b814051-c35b-43bc-ad08-0c8da7d48e92?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191014%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191014T135756Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=a2fe791eb8c763229ef1fc3b695aa18493447a6792fc99b4b620166dfabc8ee3",
    "bucket_name": "minio-py-test-a12a697e-7e4b-488d-902e-ce681ee8e81c",
    "object_name": "1b814051-c35b-43bc-ad08-0c8da7d48e92"
  },
  "name": "minio-py:test_presigned_get_object_response_headers",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="2dda89dc-18aa-461c-9d54-eced2cf514fc"></a>
### 8379-1ec45cc/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32042
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 70b910b88c0f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 23 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 22 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 24 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 46 seconds
{
  "args": {},
  "duration": 91774,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-1ec45cc

2019-10-14 14:32 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#89355577-03c8-4c24-9aaf-10afce2c8dd1) |
| mint-large-bucket.sh | :x: [more...](#8cb83df5-6d14-4265-84c1-e5a2df20bf26) |
| mint-compression-dist-xl.sh | :x: [more...](#2d4bfc9f-ef83-482c-a403-be6696779ae1) |
| mint-compression-fs.sh | :x: [more...](#66348316-0a01-49d8-8720-78af4a9e7fe0) |
<a name="2d4bfc9f-ef83-482c-a403-be6696779ae1"></a>
### 8379-742a275/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31265
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 855e69ee8e05:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 47 seconds
(8/14) Running minio-dotnet tests ... done in 51 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 4 seconds
(10/14) Running minio-java tests ... done in 2 minutes and 21 seconds
(11/14) Running minio-js tests ... done in 57 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 27 seconds
{
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "args": {
    "bucket_name": "minio-py-test-b2f1ebf8-4c33-42ae-bf6d-d9fa45209eb3",
    "response.reason": "Forbidden",
    "response.status": 403,
    "presigned_get_object_url": "http://72.28.97.53:31265/minio-py-test-b2f1ebf8-4c33-42ae-bf6d-d9fa45209eb3/858a2a35-5102-4637-afca-34c4916b31d1?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191014%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191014T143027Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=df961f08e8e96decf7f4d07132648e32f7ba1a84d21dcacb9108083ff6ba390a",
    "object_name": "858a2a35-5102-4637-afca-34c4916b31d1",
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-14T13-59-02Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CD89DF5D86BCCE\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Mon, 14 Oct 2019 14:30:37 GMT\"]}}",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>858a2a35-5102-4637-afca-34c4916b31d1</Key><BucketName>minio-py-test-b2f1ebf8-4c33-42ae-bf6d-d9fa45209eb3</BucketName><Resource>/minio-py-test-b2f1ebf8-4c33-42ae-bf6d-d9fa45209eb3/858a2a35-5102-4637-afca-34c4916b31d1</Resource><RequestId>15CD89DF5D86BCCE</RequestId><HostId>a5a85e08-aa3f-43ca-b1ce-fc5b9007a2d6</HostId></Error>"
  },
  "duration": 173,
  "message": "AccessDenied: message: Access Denied",
  "status": "FAIL",
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)"
}

Executed 11 out of 14 tests successfully.
```
<a name="89355577-03c8-4c24-9aaf-10afce2c8dd1"></a>
### 8379-742a275/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32722
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58c8f7f75117:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-r92kcsu1wwbwpj",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365767,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15CD8984C9B7440B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="8cb83df5-6d14-4265-84c1-e5a2df20bf26"></a>
### 8379-742a275/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30411
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 63027ee5e102:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 15 seconds
(5/14) Running awscli tests ... done in 2 minutes and 29 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 13 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 26 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 26 seconds
{
  "args": {},
  "duration": 55316,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="66348316-0a01-49d8-8720-78af4a9e7fe0"></a>
### 8379-742a275/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:31511
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3eac7294e7e9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 57 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 41 seconds
(8/14) Running minio-dotnet tests ... done in 28 seconds
(9/14) Running minio-go tests ... done in 46 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 18 seconds
(11/14) Running minio-js tests ... done in 45 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 33 seconds
{
  "args": {
    "bucket_name": "minio-py-test-ec1ba4e2-ed63-445a-abd9-cb04e3ead176",
    "response.reason": "Forbidden",
    "object_name": "ab52225e-0032-4d8f-9e5c-eaa30e993c17",
    "presigned_get_object_url": "http://72.28.97.54:31511/minio-py-test-ec1ba4e2-ed63-445a-abd9-cb04e3ead176/ab [...]

2019-10-14 16:29 UTC, harshavardhana requested changes
Everything else LGTM please update the storage rest version, since we are breaking rolling upgrade here due to change in API.

2019-10-15 15:24 UTC, aead commented
> Everything else LGTM please update the storage rest version, since we are breaking rolling upgrade here due to change in API.

@harshavardhana I updated the version to `10`. As a general question, is it expected that adding a field is a major breaking change to the REST API?

2019-10-15 15:55 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#e59cd5e9-4852-4923-9a33-2e3bad2f4036) |
| mint-large-bucket.sh | :x: [more...](#bc30e2d6-4189-4365-a437-a50552c74b5c) |
| mint-compression-dist-xl.sh | :x: [more...](#3c3da108-3fa4-4661-9356-d20539c6e9c3) |
| mint-dist-xl.sh | :x: [more...](#ebab5e5b-772f-44fb-87b5-9833782d7dd1) |
<a name="ebab5e5b-772f-44fb-87b5-9833782d7dd1"></a>
### 8379-ec1bc0f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30115
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9909dc5098f6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-unkbn0vdmgekxu",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 353,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.59:30115/aws-sdk-go-test-unkbn0vdmgekxu: dial tcp 72.28.97.59:30115: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="3c3da108-3fa4-4661-9356-d20539c6e9c3"></a>
### 8379-ec1bc0f/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31360
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 60fdacf419ed:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-uemu3umi4gvkw1",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 4402,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31360/aws-sdk-go-test-uemu3umi4gvkw1: dial tcp 72.28.97.55:31360: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="e59cd5e9-4852-4923-9a33-2e3bad2f4036"></a>
### 8379-ec1bc0f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30628
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 203f07135af3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-e1uhqjzwy21cuf",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 388,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.53:30628/aws-sdk-go-test-e1uhqjzwy21cuf: dial tcp 72.28.97.53:30628: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="bc30e2d6-4189-4365-a437-a50552c74b5c"></a>
### 8379-ec1bc0f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32022
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cce62f68f1f5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-k0wak4ikzrce5t",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 319,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.61:32022/aws-sdk-go-test-k0wak4ikzrce5t: dial tcp 72.28.97.61:32022: connect: connection refused",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-ec1bc0f

2019-10-15 16:31 UTC, harshavardhana commented
Yes because since this PR removes and adds APIs we have to make such a change @aead - with this change we can't guarantee rolling upgrade process. If we need to keep rolling upgrades we need to provide backward compatible APIs which is a bit of a baggage. But ATM our intention is not to do that.

2019-10-16 20:58 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#c34309c5-6048-4e09-97f1-16d7fa15e492) |
| mint-large-bucket.sh | :x: [more...](#7c8f1495-5d9e-42b5-91db-b09ae1244fc6) |
| mint-dist-xl.sh | :x: [more...](#d216a423-59e8-48a8-947c-006ef04880b1) |
<a name="c34309c5-6048-4e09-97f1-16d7fa15e492"></a>
### 8379-2e7bddb/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30354
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8a8d8189bfaf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-5ea66f22vp6yuy",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365574,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15CE3BD849F7B216, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="d216a423-59e8-48a8-947c-006ef04880b1"></a>
### 8379-2e7bddb/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31164
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d2fa1dfbe0c9:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 38 seconds
(8/14) Running minio-dotnet tests ... done in 34 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 19 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 30 seconds
(11/14) Running minio-js tests ... done in 51 seconds
(12/14) Running minio-py tests ... FAILED in 3 minutes and 10 seconds
{
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "args": {
    "presigned_get_object_url": "http://72.28.97.56:31164/minio-py-test-ec643ccf-6fd8-4659-9abe-c39aae3b14c5/0da71580-d70d-4e78-ba66-fd41eadaebb9?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191016%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191016T205549Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&response-content-language=en_US&response-content-type=text%2Fplain&X-Amz-Signature=e135c3d42152f62f2d477500382024b56aadedf98ca41e547182789592e1ba21",
    "bucket_name": "minio-py-test-ec643ccf-6fd8-4659-9abe-c39aae3b14c5",
    "object_name": "0da71580-d70d-4e78-ba66-fd41eadaebb9"
  },
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1396, in test_presigned_get_object_response_headers\n    returned_content_language = response.headers['Content-Language']\n  File \"/usr/local/lib/python3.5/dist-packages/urllib3/_collections.py\", line 156, in __getitem__\n    val = self._container[key.lower()]\nKeyError: 'content-language'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2039, in main\n    test_presigned_get_object_response_headers(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1414, in test_presigned_get_object_response_headers\n    raise Exception(err)\nException: 'content-language'\n",
  "name": "minio-py:test_presigned_get_object_response_headers",
  "status": "FAIL",
  "message": "'content-language'",
  "duration": 88
}

Executed 11 out of 14 tests successfully.
```
<a name="7c8f1495-5d9e-42b5-91db-b09ae1244fc6"></a>
### 8379-2e7bddb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32499
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9cd2bf28dafd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 30 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 15 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 53 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 14 seconds
{
  "args": {},
  "duration": 103362,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-2e7bddb

2019-10-16 21:30 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2af1638d-56ae-49ed-b8d7-05196cad262f) |
<a name="2af1638d-56ae-49ed-b8d7-05196cad262f"></a>
### 8379-e43f5d9/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31906
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 042ca819b70c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 4 seconds
(3/14) Running aws-sdk-php tests ... done in 59 seconds
(4/14) Running aws-sdk-ruby tests ... done in 16 seconds
(5/14) Running awscli tests ... done in 2 minutes and 19 seconds
(6/14) Running healthcheck tests ... done in 2 seconds
(7/14) Running mc tests ... done in 1 minutes and 11 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 29 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 57 seconds
{
  "args": {},
  "duration": 89786,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-e43f5d9

2019-10-17 06:31 UTC, harshavardhana submitted a review, later dismissed

2019-10-24 07:50 UTC, harshavardhana commented
ping @krishnasrinivas

2019-10-30 15:36 UTC, aead commented
Rebased to solve conflicts - ping @krishnasrinivas

2019-10-30 18:32 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#2d7b0e8f-9692-4e19-b2c5-58e932c47f22) |
<a name="2d7b0e8f-9692-4e19-b2c5-58e932c47f22"></a>
### 8379-a157b13/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30280
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 29d180a5cd7d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 57 seconds
(4/14) Running aws-sdk-ruby tests ... done in 20 seconds
(5/14) Running awscli tests ... done in 2 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 12 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 9 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 34 seconds
{
  "args": {},
  "duration": 82246,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8379-a157b13

2019-10-30 19:35 UTC, harshavardhana approved these changes

2020-01-29 02:14 UTC, closed without merging