Fix regression in admin router when no route matches
minio/minio pull request #8409
Opened 2019-10-16 22:44 UTC by poornas

When `mc admin user add` is attempted in gateway mode without
etcd setup, NoSuchBucket error is returned instead of MethodNotAllowed.
Regression from commit - e48005ddc72d0a26f689a77962a15d8eaa99bfe2

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-10-16 22:48 UTC, harshavardhana requested changes
Actually @Praveenrajmani said NotFound is never called - so it was moved to methodnotallowed instead. 

IMO we should keep both.

2019-10-16 23:03 UTC, poornas commented
> Actually @Praveenrajmani said NotFound is never called - so it was moved to methodnotallowed instead.
> 
> IMO we should keep both.

ok,done.

2019-10-16 23:15 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ad3b9e22-186a-49eb-8b45-b9b42ce7c359) |
<a name="ad3b9e22-186a-49eb-8b45-b9b42ce7c359"></a>
### 8409-df4c465/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30727
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp faf11fdb2890:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 20 seconds
(5/14) Running awscli tests ... done in 2 minutes and 27 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 21 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 38 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 7 seconds
{
  "args": {},
  "duration": 98402,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8409-df4c465

2019-10-16 23:47 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e3333026-ddd7-4098-93a9-ccfe0f5db1c4) |
| mint-compression-fs.sh | :x: [more...](#e0958141-ad4c-49c6-9959-6099633f63e0) |
<a name="e0958141-ad4c-49c6-9959-6099633f63e0"></a>
### 8409-6b9d8af/mint-compression-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30582
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 34cdae0a0e90:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 42 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 10 seconds
(8/14) Running minio-dotnet tests ... done in 24 seconds
(9/14) Running minio-go tests ... done in 54 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 5 seconds
(11/14) Running minio-js tests ... done in 43 seconds
(12/14) Running minio-py tests ... FAILED in 2 minutes and 12 seconds
{
  "duration": 52,
  "args": {
    "bucket_name": "minio-py-test-38b13de2-ed7f-4ffa-b159-a6bc74282a54",
    "object_name": "435f7b6e-2ce5-4cef-82cf-654604bdcc16",
    "response.status": 403,
    "response.headers": "{\"_container\": {\"accept-ranges\": [\"Accept-Ranges\", \"bytes\"], \"content-length\": [\"Content-Length\", \"440\"], \"content-security-policy\": [\"Content-Security-Policy\", \"block-all-mixed-content\"], \"content-type\": [\"Content-Type\", \"application/xml\"], \"server\": [\"Server\", \"MinIO/DEVELOPMENT.2019-10-16T23-15-48Z\"], \"vary\": [\"Vary\", \"Origin\"], \"x-amz-request-id\": [\"X-Amz-Request-Id\", \"15CE453D2C160222\"], \"x-xss-protection\": [\"X-Xss-Protection\", \"1; mode=block\"], \"date\": [\"Date\", \"Wed, 16 Oct 2019 23:44:09 GMT\"]}}",
    "presigned_get_object_url": "http://72.28.97.55:30582/minio-py-test-38b13de2-ed7f-4ffa-b159-a6bc74282a54/435f7b6e-2ce5-4cef-82cf-654604bdcc16?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20191016%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20191016T234358Z&X-Amz-Expires=5&X-Amz-SignedHeaders=host&X-Amz-Signature=09a277f0126b896e5d254085e03c65a8eeed4b7437dfaf467f3e06caa061482d",
    "response.reason": "Forbidden",
    "response._body": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AccessDenied</Code><Message>Request has expired</Message><Key>435f7b6e-2ce5-4cef-82cf-654604bdcc16</Key><BucketName>minio-py-test-38b13de2-ed7f-4ffa-b159-a6bc74282a54</BucketName><Resource>/minio-py-test-38b13de2-ed7f-4ffa-b159-a6bc74282a54/435f7b6e-2ce5-4cef-82cf-654604bdcc16</Resource><RequestId>15CE453D2C160222</RequestId><HostId>0ea446f6-91c6-4782-ac09-014968be4653</HostId></Error>"
  },
  "function": "presigned_get_object(bucket_name, object_name, expires, response_headers, request_date)",
  "status": "FAIL",
  "name": "minio-py:test_presigned_get_object_expiry_5sec",
  "error": "Traceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 1341, in test_presigned_get_object_expiry_5sec\n    object_name).get_exception()\nminio.error.AccessDenied: AccessDenied: message: Access Denied\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/mint/run/core/minio-py/tests.py\", line 2036, in main\n    test_presigned_get_object_expiry_5sec(client, log_output)\n  File \"/mint/run/core/minio-py/tests.py\", line 1355, in test_presigned_get_object_expiry_5sec\n    raise Exception(err)\nException: AccessDenied: message: Access Denied\n",
  "message": "AccessDenied: message: Access Denied"
}

Executed 11 out of 14 tests successfully.
```
<a name="e3333026-ddd7-4098-93a9-ccfe0f5db1c4"></a>
### 8409-6b9d8af/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32031
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fba458221dad:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 23 seconds
(5/14) Running awscli tests ... done in 2 minutes and 36 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 30 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 10 seconds
{
  "args": {},
  "duration": 82379,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
{"name": "8409-6b9d8af", "full_size": 34542606, "images": [{"size": 34542606, "architecture": "amd64", "variant": null, "features": null, "os": "linux", "os_version": null, "os_features": null}], "id": 72829780, "repository": 757613, "creator": 21164, "last_updater": 21164, "last_updated": "2019-10-16T23:16:40.522001Z", "image_id": null, "v2": true}Error: No such image: minio/minio:8409-6b9d8af

2019-10-17 01:11 UTC, harshavardhana approved these changes

2019-10-17 03:00 UTC, Praveenrajmani approved these changes
Agreed. NotFoundHandler should be configured for those routes whose handlerFunc is not defined at all. Like user routes will be registered only if `globalEtcdClient != nil`

2019-10-17 03:39 UTC, merged