Fix retention enforcement in Compliance mode
minio/minio pull request #8556
Opened 2019-11-21 22:10 UTC by poornas

In compliance mode, retention date can be extended with governance
bypass permissions

## Description

## Motivation and Context
In Compliance mode, PutObjectRetention API should be allowed to extend the retention date - see
https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock-overview.html#object-lock-retention-modes

## How to test this PR?
```
mc mb myminio/testbucket --with-lock
aws s3api put-object --bucket testbucket --key issue --object-lock-mode COMPLIANCE --object-lock-retain-until-date "2019-11-22"   --body /etc/issue --profile minio  --endpoint-url http://localhost:9000
aws s3api put-object-retention --bucket testbucket --key issue --retention Mode=COMPLIANCE,RetainUntilDate=2019-11-15 --endpoint-url http://localhost:9000 --profile minio --bypass-governance

```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2019-11-21 22:16 UTC, harshavardhana requested changes

2019-11-21 22:16 UTC, harshavardhana commented on docs/retention/README.md
> +- In global WORM mode objects can never be overwritten
can you update the doc about MINIO_NTP_SERVER? @poornas

2019-11-21 22:38 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d2da86c7-4d51-4f44-bd59-9dea65daa398) |
| mint-large-bucket.sh | :x: [more...](#2ad7c443-54fd-4116-82fd-4bb93a68896b) |
| mint-compression-dist-xl.sh | :x: [more...](#1c078268-a736-4e29-b4e3-4063d692340b) |
<a name="1c078268-a736-4e29-b4e3-4063d692340b"></a>
### 8556-a1ce0fa/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32663
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3b7e9bd34cc1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 2 seconds
(5/14) Running awscli tests ... done in 1 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 27 seconds
(8/14) Running minio-dotnet tests ... done in 36 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 10 seconds
(11/14) Running minio-js tests ... FAILED in 5 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 7,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:83:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:153:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:77:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```
<a name="2ad7c443-54fd-4116-82fd-4bb93a68896b"></a>
### 8556-a1ce0fa/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30134
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 69c4b31a88b3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 7 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 2 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 20 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 3 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 5 seconds
{
  "args": {},
  "duration": 130411,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="d2da86c7-4d51-4f44-bd59-9dea65daa398"></a>
### 8556-a1ce0fa/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30109
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 88c67f65ce68:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-grc6kg61q3vouo",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365291,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15D94E1A9F1A5D6B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Error: No such image: minio/minio:8556-a1ce0fa

2019-11-22 00:02 UTC, harshavardhana approved these changes

2019-11-22 00:56 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#634c42b3-db09-47dd-93e8-96a8c19deeb4) |
| mint-dist-xl.sh | :x: [more...](#78d3d378-4ab6-4a89-8ce3-c676ddf83ca7) |
<a name="634c42b3-db09-47dd-93e8-96a8c19deeb4"></a>
### 8556-0e02602/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.54:30398
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bbe009aba117:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 49 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 2 minutes and 32 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 23 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 12 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 11 seconds
{
  "args": {},
  "duration": 94506,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="78d3d378-4ab6-4a89-8ce3-c676ddf83ca7"></a>
### 8556-0e02602/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31446
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9615a2e87cbf:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 11 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 20 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 3 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/14) Running minio-java tests ... done in 1 minutes and 35 seconds
(11/14) Running minio-js tests ... FAILED in 30 minutes and 4 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 14,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:83:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:153:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:77:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:607:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:616:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:629:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:567:22) at IncomingMessage.onend (_stream_readable.js:514:10) at endReadableNT (_stream_readable.js:978:12) at _combinedTickCallback (internal/process/next_tick.js:80:11) at process._tickCallback (internal/process/next_tick.js:104:9)"
}

Executed 10 out of 14 tests successfully.
```
Error: No such image: minio/minio:8556-0e02602

2019-11-22 01:52 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d1ada121-db96-42e5-a444-dde8a69a65e6) |
| mint-large-bucket.sh | :x: [more...](#191b1763-9963-4b58-a52c-d0487537bdad) |
<a name="191b1763-9963-4b58-a52c-d0487537bdad"></a>
### 8556-ece287d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31706
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e2901c35f435:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 1 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 26 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 25 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 31 seconds
{
  "args": {},
  "duration": 107046,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="d1ada121-db96-42e5-a444-dde8a69a65e6"></a>
### 8556-ece287d/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30665
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 36436a959e34:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-h5moh10ryy45o0",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365291,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15D958A4B7CE3B2F, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Error: No such image: minio/minio:8556-ece287d

2019-11-22 02:52 UTC, kannappanr commented on cmd/object-lock.go
> +		if objRetention != nil && (objRetention.Mode != Compliance || objRetention.RetainUntilDate.Before(ret.RetainUntilDate.Time)) {
This needs to be fixed correctly.

2019-11-22 07:20 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#09a75a35-f06f-4f2a-8220-5619b2895b6c) |
| mint-xl.sh | :x: [more...](#8fbfafd9-e4c4-4a69-85fb-7e2cac28607f) |
| mint-large-bucket.sh | :x: [more...](#fd216bb4-479c-42c7-ad20-ea0f2f7fdd96) |
<a name="09a75a35-f06f-4f2a-8220-5619b2895b6c"></a>
### 8556-dbf067d/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31521
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b59a03149f35:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-izcm3llttajbmg",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365415,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15D96A8D77FAE893, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="8fbfafd9-e4c4-4a69-85fb-7e2cac28607f"></a>
### 8556-dbf067d/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32010
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2371d431fa7e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ut1armx451ulce",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364769,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15D96A8D664D4AF6, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="fd216bb4-479c-42c7-ad20-ea0f2f7fdd96"></a>
### 8556-dbf067d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31526
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 86fbe61ca040:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 2 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 20 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 26 seconds
{
  "args": {},
  "duration": 86040,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8556-dbf067d

2019-11-22 09:18 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#1f4a193c-bc11-44b5-baee-6092020eab49) |
<a name="1f4a193c-bc11-44b5-baee-6092020eab49"></a>
### 8556-4620e2c/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32567
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1b259473a3b1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 12 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 17 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 10 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 36 seconds
{
  "args": {},
  "duration": 127199,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8556-4620e2c

2019-11-22 09:42 UTC, kanagarajkm approved these changes

2019-11-22 10:55 UTC, klauspost approved these changes
LGTM.

2019-11-22 12:30 UTC, kannappanr commented
```
$ mc retention myminio/test/kgf COMPLIANCE 5d
Retention was successfully set for prefix myminio/test/kgf
$ mc rm myminio/test/kgf
Removing `myminio/test/kgf`.
mc: <ERROR> Failed to remove `myminio/test/kgf`. Access Denied.
```
Previously, the error message would say that the delete failed because of object WORM being applied to the object. We can enhance it to say that this is happening because COMPLIANCE is set or we go back to the original error. This is very generic and not useful to the user.

2019-11-22 12:43 UTC, kannappanr commented
Have tested simple delete, without any retention being set and that works.
With retention being set, it fails to delete properly. The only thing is to fix the error message to give a clue to the user as to why he is unable to delete the object.
With expired retention, it deletes correctly.

Setting retention on an object without any form of retention works as expected.
extending compliance on an object with compliance already set works as expected.
setting a shortened compliance on an object with compliance already set, fails as expected.

2019-11-22 18:11 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#c203a98c-4069-4dbe-a545-86b770b4176b) |
| mint-large-bucket.sh | :x: [more...](#bff8cf7c-a8ab-4481-a6b2-dfcced8916b0) |
<a name="bff8cf7c-a8ab-4481-a6b2-dfcced8916b0"></a>
### 8556-b82d1aa/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31290
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 687ae073f23e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 4 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 10 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 21 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 3 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 10 seconds
{
  "args": {},
  "duration": 106029,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="c203a98c-4069-4dbe-a545-86b770b4176b"></a>
### 8556-b82d1aa/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32125
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0fb1313c7ca8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 7 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-be5sz3ks2jkn6a",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 366280,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15D98E0AE7582964, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Error: No such image: minio/minio:8556-b82d1aa

2019-11-22 18:39 UTC, poornas commented
> ```
> $ mc retention myminio/test/kgf COMPLIANCE 5d
> Retention was successfully set for prefix myminio/test/kgf
> $ mc rm myminio/test/kgf
> Removing `myminio/test/kgf`.
> mc: <ERROR> Failed to remove `myminio/test/kgf`. Access Denied.
> ```
> 
> Previously, the error message would say that the delete failed because of object WORM being applied to the object. We can enhance it to say that this is happening because COMPLIANCE is set or we go back to the original error. This is very generic and not useful to the user.

ok, fixed this.

2019-11-22 19:42 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#80053404-a7de-4ff9-a0f5-d6559d8cb07b) |
<a name="80053404-a7de-4ff9-a0f5-d6559d8cb07b"></a>
### 8556-00b5dcc/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31980
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d10b0c1ed93:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 minutes and 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 1 minutes and 10 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 13 seconds
(6/14) Running healthcheck tests ... done in 2 seconds
(7/14) Running mc tests ... done in 1 minutes and 6 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 0 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 55 seconds
{
  "args": {},
  "duration": 112802,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8556-00b5dcc

2019-11-25 18:58 UTC, merged