Add encryption buffer
minio/minio pull request #8626
Opened 2019-12-10 13:46 UTC by klauspost

## Motivation and Context

We are seeing degraded performance on encrypted content but with no real time spent on actual encryption.

The encryption reads in blocks of 64KB.
We add a buffer on bigger files to reduce the number of syscalls upstream (from HTTP reader).

Quite hard to measure difference:

```
λ warp cmp put-before.csv.zst put-after2.csv.zst
Operation: PUT
Operations: 340 -> 353
* Average: +4.11% (+22.7 MB/s) throughput, +4.11% (+0.2) obj/s
* 50% Median: +1.58% (+7.3 MB/s) throughput, +1.58% (+0.1) obj/s
```

Difference is likely bigger on Intel platforms due to higher syscall costs.

## How to test this PR?

Functionality should be unaffected.

## Types of changes
- [x] Optimization

2019-12-10 14:19 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#59e029dd-0cf0-473f-bd1f-3b62255d0036) |
| mint-compression-dist-xl.sh | :x: [more...](#6737a811-43e9-49d0-ae57-bcb2a3b3f91f) |
<a name="6737a811-43e9-49d0-ae57-bcb2a3b3f91f"></a>
### 8626-16770ff/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32558
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 122886c16335:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 14 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 43 seconds
(8/14) Running minio-dotnet tests ... done in 35 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 17 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 7 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 59236,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2ve0fjo, objectName=minio-java-test-r8h03l, resource=/minio-java-test-2ve0fjo/minio-java-test-r8h03l, requestId=15DF07EB2CC5B05C, hostId=a884d691-8b69-48a1-b626-f14c8f696540)\nrequest={method=PUT, url=http://72.28.97.52:32558/minio-java-test-2ve0fjo/minio-java-test-r8h03l, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.52:32558\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191210T141141Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191210/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-10T13-46-41Z\nVary: Origin\nX-Amz-Request-Id: 15DF07EB2CC5B05C\nX-Xss-Protection: 1; mode=block\nDate: Tue, 10 Dec 2019 14:11:41 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="59e029dd-0cf0-473f-bd1f-3b62255d0036"></a>
### 8626-16770ff/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30123
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 13f7f0be92c8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 27 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 2 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 39 seconds
{
  "args": {},
  "duration": 85936,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8626-16770ff

2019-12-11 10:39 UTC, aead approved these changes
LGTM - Is there a specific reason for the 4 MB barrier? Seems arbitrary to me. Can't we use a `bufio.Reader` in any case. We may allocate a buffer for small objects but wouldn't it be more obvious then to do:
```
if size > 1<<20 {
	// The encryption reads in blocks of 64KB.
	// We add a buffer on bigger files to reduce the number of syscalls upstream.
	in = bufio.NewReaderSize(hashReader, 1<<20)
}
```

2019-12-11 12:25 UTC, klauspost commented
> LGTM - Is there a specific reason for the 4 MB barrier?

You are right, it is arbitrary, basically I'm just trying to guess where the tradeoff point is. I changed it to 1MB, no problem.

2019-12-11 12:52 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#7851d529-ca7d-4854-a325-08d18d7e4717) |
| mint-large-bucket.sh | :x: [more...](#bd3e0bc5-c21d-4336-a813-1e78f637495b) |
| mint-compression-dist-xl.sh | :x: [more...](#b9f1414a-d430-4ce2-8376-ca5a19fc7e53) |
| mint-dist-xl.sh | :x: [more...](#97b863f9-dca4-4fc3-af9c-1ee585158338) |
<a name="bd3e0bc5-c21d-4336-a813-1e78f637495b"></a>
### 8626-4e0a814/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31930
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ce50c0afa1fc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 58 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 1 minutes and 22 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 14 seconds
(9/14) Running minio-go tests ... FAILED in 1 minutes and 32 seconds
{
  "args": {
    "bucketName": "minio-go-test-vikach1sxp0eggly"
  },
  "duration": 44415,
  "error": "Please reduce your request",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="b9f1414a-d430-4ce2-8376-ca5a19fc7e53"></a>
### 8626-4e0a814/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30330
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5015ceb6507c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 44 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 1 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 53 seconds
(8/14) Running minio-dotnet tests ... done in 33 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 4 seconds
(10/14) Running minio-java tests ... FAILED in 35 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 28200,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3dusb7g, objectName=minio-java-test-72nr57, resource=/minio-java-test-3dusb7g/minio-java-test-72nr57, requestId=15DF520A42FA4788, hostId=9e0afea7-87fb-424a-af25-154e327c77c0)\nrequest={method=PUT, url=http://72.28.97.55:30330/minio-java-test-3dusb7g/minio-java-test-72nr57, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.55:30330\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191211T124958Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191211/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-11T12-24-52Z\nVary: Origin\nX-Amz-Request-Id: 15DF520A42FA4788\nX-Xss-Protection: 1; mode=block\nDate: Wed, 11 Dec 2019 12:49:58 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="7851d529-ca7d-4854-a325-08d18d7e4717"></a>
### 8626-4e0a814/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32524
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 96b44978215e:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-wqw2rmbsxd0xmz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364707,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15DF520C7E28D44B, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="97b863f9-dca4-4fc3-af9c-1ee585158338"></a>
### 8626-4e0a814/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31889
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 53ecf1c8d9c2:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 51 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 2 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 32 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 16 seconds
(10/14) Running minio-java tests ... FAILED in 8 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 3125,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-3qkua8v, objectName=minio-java-test-1ktlrl6, resource=/minio-java-test-3qkua8v/minio-java-test-1ktlrl6, requestId=15DF520D7202211F, hostId=3abbff66-de2c-40cf-8b2c-25c92cc4060f)\nrequest={method=PUT, url=http://72.28.97.55:31889/minio-java-test-3qkua8v/minio-java-test-1ktlrl6, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.55:31889\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191211T124951Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191211/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, he [...]

2019-12-11 14:56 UTC, krisis approved these changes

2019-12-11 16:11 UTC, harshavardhana requested changes
We need to do this also for PutObjectPartHandler? Also perhaps do this at one generic place in EncryptRequest?

2019-12-12 10:52 UTC, aead commented
> We need to do this also for PutObjectPartHandler? Also perhaps do this at one generic place in EncryptRequest?

Regarding PutObjectPart, yes. Klaus and I had a conversation about whether we can / should do this as a generic solution. Summery: We can do it (IMO we should) but other parts of the code that already deals with this problem (e.g. `fs` allocating a read buffer) should then not allocate buffers to avoid unnecessary copying/allocations. Maybe a separate PR?!

2019-12-12 11:03 UTC, minio-ops commented
```
Error running mint automation
+ mkdir -p 8626-cd99a8c/gopath/src/github.com/minio
+ git -C 8626-cd99a8c/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 8626-cd99a8c/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 8626-cd99a8c/gopath/src/github.com/minio/minio fetch --quiet minio pull/8626/head:pr8626
+ git -C 8626-cd99a8c/gopath/src/github.com/minio/minio checkout --quiet pr8626
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/8626-cd99a8c/gopath
+ make -C 8626-cd99a8c/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/minio/minio-go v0.0.0-20190327203652-5325257a208f
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading google.golang.org/api v0.4.0
go: downloading github.com/minio/mc v0.0.0-20191012041914-735aa139b19c
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: extracting github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/minio/cli v1.22.0
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/minio/minio-go v0.0.0-20190327203652-5325257a208f
go: downloading github.com/minio/minio-go/v6 v6.0.39
go: extracting github.com/minio/mc v0.0.0-20191012041914-735aa139b19c
go: downloading github.com/json-iterator/go v1.1.7
go: extracting github.com/json-iterator/go v1.1.7
go: extracting github.com/minio/minio-go/v6 v6.0.39
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading github.com/shirou/gopsutil v2.18.12+incompatible
go: downloading golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
go: downloading go.uber.org/atomic v1.3.2
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting go.uber.org/atomic v1.3.2
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/minio/lsync v1.0.1
go: downloading github.com/rs/cors v1.6.0
go: extracting github.com/mattn/go-isatty v0.0.7
go: extracting github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/minio/sio v0.2.0
go: extracting github.com/shirou/gopsutil v2.18.12+incompatible
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/rs/cors v1.6.0
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/minio/lsync v1.0.1
go: downloading github.com/klauspost/compress v1.8.3
go: extracting github.com/go-sql-driver/mysql v1.4.1
go: downloading cloud.google.com/go v0.37.2
go: extracting github.com/minio/sio v0.2.0
go: downloading github.com/pkg/errors v0.8.1
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading gopkg.in/ini.v1 v1.48.0
go: extracting github.com/pkg/errors v0.8.1
go: downloading github.com/minio/highwayhash v1.0.0
go: extracting golang.org/x/crypto v0.0.0-20190923035154-9ee001bba392
go: downloading github.com/dustin/go-humanize v1.0.0
go: extracting gopkg.in/ini.v1 v1.48.0
go: downloading github.com/nats-io/stan.go v0.4.5
go: extracting github.com/minio/highwayhash v1.0.0
go: extracting github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/dustin/go-humanize v1.0.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: extracting github.com/nats-io/stan.go v0.4.5
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/mattn/go-colorable v0.1.1
go: extracting github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/pkg/profile v1.3.0
go: extracting github.com/mattn/go-colorable v0.1.1
go: downloading gopkg.in/ldap.v3 v3.0.3
go: extracting github.com/minio/sha256-simd v0.1.1
go: downloading github.com/miekg/dns v1.1.8
go: extracting gopkg.in/ldap.v3 v3.0.3
go: extracting github.com/pkg/profile v1.3.0
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/lib/pq v1.0.0
go: extracting github.com/lib/pq v1.0.0
go: downloading github.com/gorilla/rpc v1.2.0
go: extracting github.com/gorilla/rpc v1.2.0
go: extracting github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/streadway/amqp v0.0.0-20190402114354-16ed540749f6
go: downloading github.com/gorilla/handlers v1.4.0
go: extracting github.com/gorilla/handlers v1.4.0
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: extracting cloud.google.com/go v0.37.2
go: extracting github.com/miekg/dns v1.1.8
go: downloading github.com/djherbis/atime v1.0.0
go: extracting github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting github.com/streadway/amqp v0.0.0-20190402114354-16ed540749f6
go: extracting github.com/djherbis/atime v1.0.0
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/gorilla/mux v1.7.0
go: extracting github.com/nats-io/nuid v1.0.1
go: extracting github.com/gorilla/mux v1.7.0
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: extracting gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: downloading google.golang.org/grpc v1.20.1
go: extracting google.golang.org/grpc v1.20.1
go: downloading github.com/klauspost/pgzip v1.2.1
go: extracting github.com/klauspost/pgzip v1.2.1
go: extracting golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: downloading github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: extracting github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/prometheus/common v0.2.0
go: extracting github.com/prometheus/common v0.2.0
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: extracting github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: extracting github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: downloading github.com/nats-io/nats.go v1.9.1
go: extracting github.com/nats-io/nats.go v1.9.1
go: downloading github.com/Shopify/sarama v1.24.1
go: extracting github.com/Shopify/sarama v1.24.1
go: downloading github.com/klauspost/readahead v1.3.1
go: extracting github.com/klauspost/readahead v1.3.1
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: extracting github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: extracting google.golang.org/api v0.4.0
go: extracting github.com/klauspost/compress v1.8.3
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/fatih/structs v1.1.0
go: extracting github.com/davecgh/go-spew v1.1.1
go: extracting github.com/fatih/structs v1.1.0
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: extracting gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/che [...]

2019-12-12 11:19 UTC, aead requested changes

2019-12-12 11:19 UTC, aead commented on cmd/web-handlers.go
> +			pReader = NewPutObjReader(nil, hashReader, objectEncryptionKey)
Here, the same problem exists with SSE-C vs. SSE-S3

2019-12-12 11:23 UTC, aead approved these changes
LGTM

2019-12-12 11:43 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-compression-xl.sh | :x: [more...](#a73c8d01-f186-4701-9dfe-493c086dd245) |
| mint-large-bucket.sh | :x: [more...](#20380e98-07f6-4ef6-9d0a-650a96c742b2) |
| mint-compression-dist-xl.sh | :x: [more...](#27f2ea34-f2f0-412d-85c9-ee34fde079d4) |
| mint-dist-xl.sh | :x: [more...](#c1dd362f-52f7-4d63-9d15-8885919655ea) |
<a name="20380e98-07f6-4ef6-9d0a-650a96c742b2"></a>
### 8626-f1f38bf/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31283
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 636c4f61a257:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 50 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 27 seconds
(9/14) Running minio-go tests ... FAILED in 4 minutes and 51 seconds
{
  "args": {},
  "duration": 107681,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="a73c8d01-f186-4701-9dfe-493c086dd245"></a>
### 8626-f1f38bf/mint-compression-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31263
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7739d73300fb:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-qvfmlis0gfnxg4",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365284,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15DF9CB747ABFEA7, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="c1dd362f-52f7-4d63-9d15-8885919655ea"></a>
### 8626-f1f38bf/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31927
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp aae2b64b3ead:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 0 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 45 seconds
(4/14) Running aws-sdk-ruby tests ... done in 4 seconds
(5/14) Running awscli tests ... done in 1 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 32 seconds
(8/14) Running minio-dotnet tests ... done in 51 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 57 seconds
(10/14) Running minio-java tests ... FAILED in 15 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 5349,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-1adbsf0, objectName=minio-java-test-2repaom, resource=/minio-java-test-1adbsf0/minio-java-test-2repaom, requestId=15DF9CB165BA7087, hostId=c431e5c7-bea9-456f-a6f1-8ee553dc3c0a)\nrequest={method=PUT, url=http://72.28.97.53:31927/minio-java-test-1adbsf0/minio-java-test-2repaom, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.53:31927\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191212T113800Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191212/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-12T11-13-06Z\nVary: Origin\nX-Amz-Request-Id: 15DF9CB165BA7087\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Dec 2019 11:38:00 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="27f2ea34-f2f0-412d-85c9-ee34fde079d4"></a>
### 8626-f1f38bf/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30829
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 810d6bec6f7b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 8 seconds
(5/14) Running awscli tests ... done in 2 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 58 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... FAILED in 1 minutes and 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-gn2tv64v9o5o50ig"
  },
  "duration": 30260,
  "error": "Please reduce your request",
  "function": "RemoveObjects(bucketName, objectsCh)",
  "message": "Unexpected error",
  "name": "minio-go: testRemoveMultipleObjects",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Error: No such image: minio/minio:8626-f1f38bf

2019-12-12 12:19 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-xl.sh | :heavy_check_mark: |
| mint-compression-dist-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#6e3e7033-e207-4b4b-92d8-a51e45f52953) |
<a name="6e3e7033-e207-4b4b-92d8-a51e45f52953"></a>
### 8626-9b71b20/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32686
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f60a0aaf3c06:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 53 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 2 minutes and 52 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 1 minutes and 9 seconds
(8/14) Running minio-dotnet tests ... FAILED in 40 seconds

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (MinIO API responded with message=Please reduce your request) (MinIO API responded with message=Please reduce your request) (MinIO API responded with message=Please reduce your request) (MinIO API responded with message=Please reduce your request)) ---> System.AggregateException: One or more errors occurred. (MinIO API responded with message=Please reduce your request) (MinIO API responded with message=Please reduce your request) (MinIO API responded with message=Please reduce your request) (MinIO API responded with message=Please reduce your request) ---> Minio.Exceptions.MinioException: MinIO API responded with message=Please reduce your request
   at Minio.MinioClient.ParseError(IRestResponse response) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 381
   at Minio.MinioClient.HandleIfErrorResponse(IRestResponse response, IEnumerable`1 handlers, DateTime startTime) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 526
   at Minio.MinioClient.ExecuteTaskAsync(IEnumerable`1 errorHandlers, IRestRequest request, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/MinioClient.cs:line 370
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, String uploadId, Int32 partNumber, Byte[] data, Dictionary`2 metaData, Dictionary`2 sseHeaders, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 489
   at Minio.MinioClient.PutObjectAsync(String bucketName, String objectName, Stream data, Int64 size, String contentType, Dictionary`2 metaData, ServerSideEncryption sse, CancellationToken cancellationToken) in /q/.q/sources/minio-dotnet/Minio/ApiEndpoints/ObjectOperations.cs:line 254
   at Minio.Functional.Tests.FunctionalTest.PutObject_Task(MinioClient minio, String bucketName, String objectName, String fileName, String contentType, Int64 size, Dictionary`2 metaData, MemoryStream mstream) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 812
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.FunctionalTest.RemoveObjects_Test2(MinioClient minio) in /mint/run/core/minio-dotnet/FunctionalTest.cs:line 2054
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Minio.Functional.Tests.Program.Main(String[] args) in /mint/run/core/minio-dotnet/Program.cs:line 113

Executed 7 out of 14 tests successfully.
```
Error: No such image: minio/minio:8626-9b71b20

2019-12-12 12:49 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-compression-xl.sh | :heavy_check_mark: |
| mint-compression-fs.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#f63bfa8f-cf20-4053-ad57-7ea216cceff1) |
| mint-large-bucket.sh | :x: [more...](#9b850ab8-126a-48ce-b5c9-689c69d3b2f4) |
| mint-compression-dist-xl.sh | :x: [more...](#ce67b7b6-f313-4542-a5d0-43e7e97baf22) |
| mint-dist-xl.sh | :x: [more...](#463febc9-8823-419e-81e1-e0bb2aaed0c1) |
<a name="9b850ab8-126a-48ce-b5c9-689c69d3b2f4"></a>
### 8626-512fe39/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32486
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fa0effa00813:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 28 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 1 minutes and 16 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 7 seconds
(9/14) Running minio-go tests ... FAILED in 3 minutes and 37 seconds
{
  "args": {},
  "duration": 89485,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="ce67b7b6-f313-4542-a5d0-43e7e97baf22"></a>
### 8626-512fe39/mint-compression-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31516
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bfc8d3c8eb8a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 16 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 48 seconds
(8/14) Running minio-dotnet tests ... done in 48 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 29 seconds
(10/14) Running minio-java tests ... FAILED in 36 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 29823,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-11fqf4t, objectName=minio-java-test-27k3uo7, resource=/minio-java-test-11fqf4t/minio-java-test-27k3uo7, requestId=15DFA057924A2EC5, hostId=4eba542b-86d0-4ce7-9f25-1b28a9bc1e78)\nrequest={method=PUT, url=http://72.28.97.56:31516/minio-java-test-11fqf4t/minio-java-test-27k3uo7, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.56:31516\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191212T124452Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191212/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-12T12-19-42Z\nVary: Origin\nX-Amz-Request-Id: 15DFA057924A2EC5\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Dec 2019 12:44:52 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="463febc9-8823-419e-81e1-e0bb2aaed0c1"></a>
### 8626-512fe39/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32267
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2f9368c9e0f7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 1 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 43 seconds
(4/14) Running aws-sdk-ruby tests ... done in 3 seconds
(5/14) Running awscli tests ... done in 1 minutes and 9 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 38 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... done in 1 minutes and 23 seconds
(10/14) Running minio-java tests ... FAILED in 1 minutes and 1 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName, final String prefix, final boolean recursive)",
  "args": "prefix :minio, recursive: true",
  "duration": 55784,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=SlowDown, message=Please reduce your request, bucketName=minio-java-test-2el4fs0, objectName=minio-java-test-gdikoo, resource=/minio-java-test-2el4fs0/minio-java-test-gdikoo, requestId=15DFA055A788760F, hostId=c780c88e-39e8-4aaf-a884-322a307c3bae)\nrequest={method=PUT, url=http://72.28.97.52:32267/minio-java-test-2el4fs0/minio-java-test-gdikoo, headers=Content-Type: application/octet-stream\nContent-Encoding: aws-chunked\nx-amz-decoded-content-length: 1\nHost: 72.28.97.52:32267\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: STREAMING-AWS4-HMAC-SHA256-PAYLOAD\nx-amz-date: 20191212T124444Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20191212/us-east-1/s3/aws4_request, SignedHeaders=content-encoding;host;x-amz-content-sha256;x-amz-date;x-amz-decoded-content-length, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 361\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2019-12-12T12-19-42Z\nVary: Origin\nX-Amz-Request-Id: 15DFA055A788760F\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Dec 2019 12:44:44 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1204), io.minio.MinioClient.execute(MinioClient.java:1066), io.minio.MinioClient.executePut(MinioClient.java:1430), io.minio.MinioClient.executePut(MinioClient.java:1452), io.minio.MinioClient.putObject(MinioClient.java:4511), io.minio.MinioClient.putObject(MinioClient.java:4564), io.minio.MinioClient.putObject(MinioClient.java:4478), FunctionalTest.listObject_test5(FunctionalTest.java:1485), FunctionalTest.runTests(FunctionalTest.java:3010), FunctionalTest.main(FunctionalTest.java:3148)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="f63bfa8f-cf20-4053-ad57-7ea216cceff1"></a>
### 8626-512fe39/mint-xl.sh.log [...]

2019-12-12 16:50 UTC, harshavardhana approved these changes

2019-12-12 16:54 UTC, krisis approved these changes

2019-12-12 18:01 UTC, merged