Fix group add/remove membership bug
minio/minio pull request #8877
Opened 2020-01-21 23:17 UTC by donatello

## Description

Fix https://github.com/minio/minio/issues/8841

## How to test this PR?

Same steps as in the linked issue.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-01-21 23:18 UTC, donatello commented
The changes to go.mod and go.sum appeared automatically on `make`.

2020-01-21 23:19 UTC, donatello commented on cmd/iam.go
> -	}
The 3 lines above are the cause of the bug. `group` is not a valid key type for this map.

2020-01-21 23:21 UTC, harshavardhana requested changes

2020-01-21 23:21 UTC, harshavardhana commented on go.mod
> +	golang.org/x/tools/gopls v0.2.2 // indirect
This doesn't look like we directly depend `// indirects` can be removed.

2020-01-22 00:52 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#95841bc5-5f7a-42ec-901b-12e2f342408c) |
<a name="95841bc5-5f7a-42ec-901b-12e2f342408c"></a>
### 8877-9ceaa61/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30238
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 39b5b3c698a7:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 52 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 8 seconds
(4/13) Running mc tests ... done in 56 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 53 seconds
{
  "args": {},
  "duration": 106271,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-22 01:03 UTC, harshavardhana approved these changes

2020-01-22 01:56 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#7cb87143-081d-4d10-8eef-8b9aebd6b08c) |
| mint-large-bucket.sh | :x: [more...](#e886e5e2-0f12-436e-ad86-81c5bc4b18a9) |
<a name="7cb87143-081d-4d10-8eef-8b9aebd6b08c"></a>
### 8877-e9f800d/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31389
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1c7f5ccbd033:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 12 seconds
{
  "name": "awscli",
  "duration": 9645,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="e886e5e2-0f12-436e-ad86-81c5bc4b18a9"></a>
### 8877-e9f800d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32122
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 712c07452fd5:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 11 seconds
{
  "name": "awscli",
  "duration": 8924,
  "function": "delete_bucket\n",
  "status": "FAIL",
  "error": "fatal error: An error occurred (XMinioServerNotInitialized) when calling the ListObjectsV2 operation (reached max retries: 4): Server not initialized, please try again.remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-22 02:27 UTC, poornas approved these changes
LGTM

2020-01-22 03:00 UTC, merged