Set retention  namespace for ObjectRetention
minio/minio pull request #8903
Opened 2020-01-28 16:57 UTC by sinhaashish

## Description
 Set retention  namespace for ObjectRetention
The name space is correct as per AWS  . Refer https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectRetention.html.

This PR is on the very same line as  PR https://github.com/minio/minio/pull/6789 which was to resolve the issue https://github.com/minio/minio-java/issues/710

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-01-28 17:05 UTC, harshavardhana approved these changes
LGTM

2020-01-28 17:13 UTC, harshavardhana commented
@sinhaashish I think more than this the right fix is like this

```diff
diff --git a/pkg/bucket/object/lock/lock.go b/pkg/bucket/object/lock/lock.go
index ec19c0321..626f4356d 100644
--- a/pkg/bucket/object/lock/lock.go
+++ b/pkg/bucket/object/lock/lock.go
@@ -233,8 +233,7 @@ func (dr *DefaultRetention) UnmarshalXML(d *xml.Decoder, start xml.StartElement)
 // Config - object lock configuration specified in
 // https://docs.aws.amazon.com/AmazonS3/latest/API/Type_API_ObjectLockConfiguration.html
 type Config struct {
-       XMLNS             string   `xml:"xmlns,attr,omitempty"`
-       XMLName           xml.Name `xml:"ObjectLockConfiguration"`
+       XMLName           xml.Name `xml:"http://s3.amazonaws.com/doc/2006-03-01/ ObjectLockConfiguration"`
        ObjectLockEnabled string   `xml:"ObjectLockEnabled"`
        Rule              *struct {
                DefaultRetention DefaultRetention `xml:"DefaultRetention"`
@@ -336,8 +335,7 @@ func (rDate *RetentionDate) MarshalXML(e *xml.Encoder, startElement xml.StartEle
 // ObjectRetention specified in
 // https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectRetention.html
 type ObjectRetention struct {
-       XMLNS           string        `xml:"xmlns,attr,omitempty"`
-       XMLName         xml.Name      `xml:"Retention"`
+       XMLName         xml.Name      `xml:"http://s3.amazonaws.com/doc/2006-03-01/ Retention"`
        Mode            Mode          `xml:"Mode,omitempty"`
        RetainUntilDate RetentionDate `xml:"RetainUntilDate,omitempty"`
 }
@@ -470,8 +468,7 @@ func ParseObjectLockLegalHoldHeaders(h http.Header) (lhold ObjectLegalHold, err
 // ObjectLegalHold specified in
 // https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectLegalHold.html
 type ObjectLegalHold struct {
-       XMLNS   string          `xml:"xmlns,attr,omitempty"`
-       XMLName xml.Name        `xml:"LegalHold"`
+       XMLName xml.Name        `xml:"http://s3.amazonaws.com/doc/2006-03-01/ LegalHold"`
        Status  LegalHoldStatus `xml:"Status,omitempty"`
 }
 
```

2020-01-28 17:14 UTC, harshavardhana commented
you may also change 

```diff
diff --git a/pkg/event/config.go b/pkg/event/config.go
index 7a31fdc47..8bf7f8c71 100644
--- a/pkg/event/config.go
+++ b/pkg/event/config.go
@@ -209,8 +209,7 @@ type topic struct {
 // Config - notification configuration described in
 // http://docs.aws.amazon.com/AmazonS3/latest/dev/NotificationHowTo.html
 type Config struct {
-       XMLNS      string   `xml:"xmlns,attr,omitempty"`
-       XMLName    xml.Name `xml:"NotificationConfiguration"`
+       XMLName    xml.Name `xml:"http://s3.amazonaws.com/doc/2006-03-01/ NotificationConfiguration"`
        QueueList  []Queue  `xml:"QueueConfiguration,omitempty"`
        LambdaList []lambda `xml:"CloudFunctionConfiguration,omitempty"`
        TopicList  []topic  `xml:"TopicConfiguration,omitempty"`
@@ -292,10 +291,5 @@ func ParseConfig(reader io.Reader, region string, targetList *TargetList) (*Conf
 
        config.SetRegion(region)
 
-       // If xml namespace is empty, set a default value before returning.
-       if config.XMLNS == "" {
-               config.XMLNS = "http://s3.amazonaws.com/doc/2006-03-01/"
-       }
-
        return &config, nil
 }
```

2020-01-28 17:39 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#0050af0f-1c77-464c-90f4-f2bfbc0a8fd6) |
| mint-worm.sh | :x: [more...](#368bf101-8ba1-446a-9b63-665d993af714) |
| mint-dist-xl.sh | :x: [more...](#855fa7ea-ed64-4d57-b0d4-dd27572cb4b6) |
| mint-gateway-azure.sh | :x: [more...](#81cae2ef-f5ce-41e7-8bcc-e0959d3f1bfd) |
<a name="855fa7ea-ed64-4d57-b0d4-dd27572cb4b6"></a>
### 8903-43e3a1b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32655
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1a53e1ceee75:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305473, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32655/awscli-mint-test-bucket-26751""}

Executed 0 out of 13 tests successfully.
```
<a name="81cae2ef-f5ce-41e7-8bcc-e0959d3f1bfd"></a>
### 8903-43e3a1b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32388
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c53413685d4:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 51 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 17 seconds
(4/13) Running mc tests ... done in 6 minutes and 32 seconds
(5/13) Running minio-go tests ... FAILED in 11 minutes and 43 seconds
{
  "args": {
    "bucketName": "minio-go-test-bqrfqbx0z2icrsgf",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 233,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="0050af0f-1c77-464c-90f4-f2bfbc0a8fd6"></a>
### 8903-43e3a1b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31523
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 87e387900b26:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 30 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 2 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 35 seconds
{
  "args": {},
  "duration": 87394,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="368bf101-8ba1-446a-9b63-665d993af714"></a>
### 8903-43e3a1b/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30238
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0817cc88e488:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-t9zju9eqmak1hlh7n66q2jvw3gbk4hcx8v9us8e1kht6q2w06mi4gos",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120260,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30238/bucket-t9zju9eqmak1hlh7n66q2jvw3gbk4hcx8v9us8e1kht6q2w06mi4gos: dial tcp 72.28.97.55:30238: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-28 19:30 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#1608499e-736e-439c-b157-252dddef2b9b) |
| mint-large-bucket.sh | :x: [more...](#d1146a35-8d50-46cf-99a5-6dac0f2ec984) |
| mint-gateway-azure.sh | :x: [more...](#06afff77-acab-4377-b63f-2541ea6156de) |
<a name="d1146a35-8d50-46cf-99a5-6dac0f2ec984"></a>
### 8903-4c8e0d5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32194
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e59e04ff7c96:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 55 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 3 seconds
{
  "args": {},
  "duration": 72685,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="06afff77-acab-4377-b63f-2541ea6156de"></a>
### 8903-4c8e0d5/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31461
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 24704aa0c3a9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 25 seconds
{
  "name": "awscli",
  "duration": 1526,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 0 out of 13 tests successfully.
```
<a name="1608499e-736e-439c-b157-252dddef2b9b"></a>
### 8903-4c8e0d5/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31803
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4df0c241f63c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 15 seconds
{
  "name": "awscli",
  "duration": 13509,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-28 20:13 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#e0ca1e57-f13d-4567-b282-68737915fdb9) |
| mint-large-bucket.sh | :x: [more...](#cc7ecff6-d642-46b9-be3d-3321cb85e3a8) |
| mint-gateway-azure.sh | :x: [more...](#2520aa8f-e33e-4f39-a474-20a628a406ca) |
<a name="e0ca1e57-f13d-4567-b282-68737915fdb9"></a>
### 8903-447c0c1/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31745
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 532f94ba9e8d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 11 seconds
{"name": "awscli", "duration": 308529, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31745/awscli-mint-test-bucket-4359""}

Executed 0 out of 13 tests successfully.
```
<a name="cc7ecff6-d642-46b9-be3d-3321cb85e3a8"></a>
### 8903-447c0c1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30701
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1a0245ed1fde:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 20 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 52 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 28 seconds
{
  "args": {},
  "duration": 90805,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="2520aa8f-e33e-4f39-a474-20a628a406ca"></a>
### 8903-447c0c1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31049
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d85cc915d5f1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 26 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 7 minutes and 28 seconds
(5/13) Running minio-go tests ... FAILED in 11 minutes and 4 seconds
{
  "args": {
    "bucketName": "minio-go-test-gbudi6jeeu0qubge",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 233,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-28 21:03 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e4cee16f-c253-4e90-8731-36e22f924644) |
| mint-gateway-azure.sh | :x: [more...](#3ffda710-476f-410c-ac65-5be4a85192ca) |
<a name="e4cee16f-c253-4e90-8731-36e22f924644"></a>
### 8903-ee174df/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30164
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 35769250929e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 36 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 1 minutes and 4 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 35 seconds
{
  "args": {},
  "duration": 75082,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="3ffda710-476f-410c-ac65-5be4a85192ca"></a>
### 8903-ee174df/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30550
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d61d9c4e1810:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 58 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 0 seconds
(5/13) Running minio-go tests ... FAILED in 20 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-rtlbrr94leepmclr",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 233,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-28 21:23 UTC, poornas requested changes
Can you remove staticcheck_linux_amd64.tar.gz from the commit?

2020-01-28 21:44 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#db5fd474-2ca9-414a-92d8-47933df828a1) |
| mint-gateway-azure.sh | :x: [more...](#fdac561a-2232-4c34-898d-abeb4fc290e0) |
<a name="db5fd474-2ca9-414a-92d8-47933df828a1"></a>
### 8903-29478df/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32133
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a68e5187500c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 32 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 58 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 7 seconds
{
  "args": {},
  "duration": 56665,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="fdac561a-2232-4c34-898d-abeb4fc290e0"></a>
### 8903-29478df/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30479
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f291a639a2e5:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 6 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 59 seconds
(5/13) Running minio-go tests ... FAILED in 10 minutes and 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-yvgfqqcc36l9kdav",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 272,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-29 01:49 UTC, poornas approved these changes

2020-01-29 02:26 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#c8e9d3d0-bd64-4985-8069-94d033250612) |
| mint-gateway-azure.sh | :x: [more...](#7358dcf9-71e0-42ad-9b06-d0027ca6e622) |
<a name="7358dcf9-71e0-42ad-9b06-d0027ca6e622"></a>
### 8903-b21df4a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30961
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8a45c85d67be:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 5 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 45 seconds
(5/13) Running minio-go tests ... FAILED in 11 minutes and 18 seconds
{
  "args": {
    "bucketName": "minio-go-test-lca59a30e9fzbdax",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 295,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="c8e9d3d0-bd64-4985-8069-94d033250612"></a>
### 8903-b21df4a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30864
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 01cc21131a4f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305437, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30864/awscli-mint-test-bucket-7014""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-29 04:02 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#512a9012-bccc-43da-b779-ee912b2bf87d) |
| mint-dist-xl.sh | :x: [more...](#e7120a87-d9f0-431c-a78b-9b1318f226f5) |
| mint-gateway-azure.sh | :x: [more...](#2034e4e2-108e-4a1e-be32-496cc9984797) |
<a name="2034e4e2-108e-4a1e-be32-496cc9984797"></a>
### 8903-5f5f53a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:32575
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e7ce360b3268:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 57 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 17 seconds
(4/13) Running mc tests ... done in 7 minutes and 40 seconds
(5/13) Running minio-go tests ... FAILED in 10 minutes and 30 seconds
{
  "args": {
    "bucketName": "minio-go-test-seuw6y03dsh5sd6u",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 324,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="512a9012-bccc-43da-b779-ee912b2bf87d"></a>
### 8903-5f5f53a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31441
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6740b9b5c6ba:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 23 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 50 seconds
(5/13) Running minio-go tests ... FAILED in 3 minutes and 38 seconds
{
  "args": {},
  "duration": 53586,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="e7120a87-d9f0-431c-a78b-9b1318f226f5"></a>
### 8903-5f5f53a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32562
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d53e357ed984:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 306594, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32562/awscli-mint-test-bucket-20488""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-29 04:49 UTC, merged