Use user CAs in checkEndpoint() call
minio/minio pull request #8911
Opened 2020-01-30 10:53 UTC by vadmeste

## Description
The server info handler makes a http connection to other nodes
to check if they are up but does not load the custom CAs in
~/.minio/certs/CAs.

This commit fix it.

## Motivation and Context
mc admin info returns incorrect number of online nodes when the user uses a self signed certificate 

## How to test this PR?
- Create a self signed certificate and put it in ~/.minio/certs/ of all nodes
- Put the public certificate in ~/.minio/certs/CAs of all nodes
- Start the cluster
- Run `mc admin info myminio/` and inspect the output of Network

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-01-30 11:54 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#1fac4865-3182-4273-9e47-99515926d781) |
| mint-gateway-azure.sh | :x: [more...](#fa888600-65aa-411e-b5e6-3c44afc4b822) |
<a name="1fac4865-3182-4273-9e47-99515926d781"></a>
### 8911-db45906/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31510
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 899adcbcd862:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 32 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 3 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 26 seconds
{
  "args": {},
  "duration": 79186,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="fa888600-65aa-411e-b5e6-3c44afc4b822"></a>
### 8911-db45906/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30785
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e20610ae5e1d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 20 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 40 seconds
(5/13) Running minio-go tests ... FAILED in 30 minutes and 45 seconds
{
  "args": {
    "bucketName": "minio-go-test-cxjymxh3jjutiyf3",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 240,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-30 17:43 UTC, harshavardhana requested changes

2020-01-30 17:43 UTC, harshavardhana commented on cmd/admin-server-info.go
> +func toNodeName(endpoint Endpoint) string {
This is doing too many things @vadmeste an endpoint is already url.URL parsed value we can simply use endpoint.Host to get the relevant value

```diff
diff --git a/cmd/admin-server-info.go b/cmd/admin-server-info.go
index 9916ebbb1..ca6327665 100644
--- a/cmd/admin-server-info.go
+++ b/cmd/admin-server-info.go
@@ -20,7 +20,6 @@ import (
        "net"
        "net/http"
        "os"
-       "strings"
 
        "github.com/minio/minio-go/v6/pkg/set"
        "github.com/minio/minio/pkg/cpu"
@@ -190,51 +189,41 @@ func getLocalNetworkInfo(endpointZones EndpointZones, r *http.Request) madmin.Se
 // getLocalServerProperty - returns ServerDrivesPerfInfo for only the
 // local endpoints from given list of endpoints
 func getLocalServerProperty(endpointZones EndpointZones, r *http.Request) madmin.ServerProperties {
-       var di madmin.Disk
        var disks []madmin.Disk
        addr := r.Host
        if globalIsDistXL {
                addr = GetLocalPeer(endpointZones)
        }
        network := make(map[string]string)
-       hosts := set.NewStringSet()
        for _, ep := range endpointZones {
                for _, endpoint := range ep.Endpoints {
-
-                       url := strings.Replace(endpoint.URL.String(), endpoint.Path, "", -1)
-                       if url == "" {
-                               url = r.Host
-                       }
-                       hosts.Add(url)
-
                        // Only proceed for local endpoints
                        if endpoint.IsLocal {
-                               url = fetchAddress(url)
-                               network[url] = "online"
-                               if _, err := os.Stat(endpoint.Path); err != nil {
-                                       continue
+                               network[endpoint.Host] = "online"
+                               var di = madmin.Disk{
+                                       DrivePath: endpoint.Path,
+                               }
+                               diInfo, err := disk.GetInfo(endpoint.Path)
+                               if err != nil {
+                                       if os.IsNotExist(err) || isSysErrPathNotFound(err) {
+                                               di.State = madmin.DriveStateMissing
+                                       } else {
+                                               di.State = madmin.DriveStateCorrupt
+                                       }
+                               } else {
+                                       di.State = madmin.DriveStateOk
+                                       di.TotalSpace = diInfo.Total
+                                       di.UsedSpace = diInfo.Total - diInfo.Free
+                                       di.Utilization = float64((diInfo.Total - diInfo.Free) / diInfo.Total * 100)
                                }
-
-                               diInfo, _ := disk.GetInfo(endpoint.Path)
-                               di.State = "ok"
-                               di.DrivePath = endpoint.Path
-                               di.TotalSpace = diInfo.Total
-                               di.UsedSpace = diInfo.Total - diInfo.Free
-                               di.Utilization = float64((diInfo.Total - diInfo.Free) / diInfo.Total * 100)
                                disks = append(disks, di)
-                       }
-               }
-       }
-
-       for host := range hosts {
-               _, present := network[host]
-               if !present {
-                       err := checkConnection(host)
-                       host = fetchAddress(host)
-                       if err != nil {
-                               network[host] = "offline"
                        } else {
-                               network[host] = "online"
+                               err := IsServerResolvable(endpoint)
+                               if err != nil {
+                                       network[endpoint.Host] = "offline"
+                               } else {
+                                       network[endpoint.Host] = "online"
+                               }
                        }
                }
        }
@@ -249,13 +238,3 @@ func getLocalServerProperty(endpointZones EndpointZones, r *http.Request) madmin
                Disks:    disks,
        }
 }
-
-// Replaces http and https from address
-func fetchAddress(address string) string {
-       if strings.Contains(address, "http://") {
-               address = strings.Replace(address, "http://", "", -1)
-       } else if strings.Contains(address, "https://") {
-               address = strings.Replace(address, "https://", "", -1)
-       }
-       return address
-}
```

This should be enough

2020-01-30 19:04 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#01db3117-45e2-4c54-9466-044d0566c2df) |
| mint-large-bucket.sh | :x: [more...](#5d9b6075-b475-49e6-83ca-f19063da2084) |
| mint-gateway-azure.sh | :x: [more...](#5099ebd7-25b5-4e26-be49-798d2d6d5f45) |
<a name="01db3117-45e2-4c54-9466-044d0566c2df"></a>
### 8911-1629dee/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31340
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fb93d6c7926f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 6 seconds
{"name": "awscli", "duration": 304477, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31340/awscli-mint-test-bucket-4559""}

Executed 0 out of 13 tests successfully.
```
<a name="5d9b6075-b475-49e6-83ca-f19063da2084"></a>
### 8911-1629dee/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32255
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ac845d0a83c9:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 24 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 8 seconds
(4/13) Running mc tests ... done in 1 minutes and 16 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 42 seconds
{
  "args": {},
  "duration": 130285,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="5099ebd7-25b5-4e26-be49-798d2d6d5f45"></a>
### 8911-1629dee/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31777
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cd9472a65ae1:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 4 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 20 seconds
(5/13) Running minio-go tests ... FAILED in 20 minutes and 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-tkp1t9qp4ls34n0f",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 235,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-30 19:57 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#7f380b90-aaba-4368-adae-3d0a9bc457fd) |
| mint-large-bucket.sh | :x: [more...](#36c64fd4-4029-4e28-a1de-85c4d039e525) |
| mint-dist-xl.sh | :x: [more...](#af03ca70-c35e-44c0-939d-0bb4775e4163) |
| mint-gateway-azure.sh | :x: [more...](#c5a699c5-aa9c-4283-807c-b71619ef0fe4) |
<a name="7f380b90-aaba-4368-adae-3d0a9bc457fd"></a>
### 8911-c9ecca0/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:30612
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e9f79ead9605:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 8 seconds
{
  "name": "awscli",
  "duration": 5826,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="af03ca70-c35e-44c0-939d-0bb4775e4163"></a>
### 8911-c9ecca0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32708
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 15fd35d82e2c:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 305973, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32708/awscli-mint-test-bucket-19220""}

Executed 0 out of 13 tests successfully.
```
<a name="c5a699c5-aa9c-4283-807c-b71619ef0fe4"></a>
### 8911-c9ecca0/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31199
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cc6de37f12ef:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 3 minutes and 2 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 17 seconds
(4/13) Running mc tests ... done in 7 minutes and 12 seconds
(5/13) Running minio-go tests ... FAILED in 22 minutes and 56 seconds
{
  "args": {
    "bucketName": "minio-go-test-964vvduqceimcgea",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 251,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="36c64fd4-4029-4e28-a1de-85c4d039e525"></a>
### 8911-c9ecca0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30881
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0ad8e6bf2497:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 23 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 5 seconds
(4/13) Running mc tests ... done in 43 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 32 seconds
{
  "args": {},
  "duration": 106848,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-31 03:38 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#70a9ba96-ab6f-410f-bc28-7a83585a53b8) |
| mint-dist-xl.sh | :x: [more...](#0b786395-c580-436d-82dd-33666cfd66ea) |
| mint-gateway-azure.sh | :x: [more...](#9491c515-3302-4830-a042-ed0aa11dcd3a) |
<a name="0b786395-c580-436d-82dd-33666cfd66ea"></a>
### 8911-f8db2af/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32433
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f1c77f57f435:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 25 seconds
(2/13) Running aws-sdk-java tests ... done in 2 seconds
(3/13) Running aws-sdk-ruby tests ... done in 3 seconds
(4/13) Running mc tests ... done in 33 seconds
(5/13) Running minio-go tests ... done in 12 minutes and 38 seconds
(6/13) Running minio-js tests ... FAILED in 17 seconds
{
  "name": "minio-js",
  "function": "listObjects(bucketName, prefix, recursive)",
  "args": "bucketName:minio-js-test-8fc1deb0-5fd5-4769-9d79-40ed6c55c935, recursive:false",
  "duration": 213,
  "status": "FAIL",
  "error": "Error: done() called multiple times at /mint/run/core/minio-js/node_modules/mocha-steps/lib/step.js:67:11 at /mint/run/core/minio-js/test/functional-tests.js:1161:13 at wrapper (node_modules/minio/node_modules/async/dist/async.js:273:20) at iterateeCallback (node_modules/minio/node_modules/async/dist/async.js:418:21) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:326:20 at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:1846:25 at DestroyableTransform.<anonymous> (node_modules/minio/dist/main/minio.js:514:15) at done (node_modules/readable-stream/lib/_stream_transform.js:192:25) at /mint/run/core/minio-js/node_modules/readable-stream/lib/_stream_transform.js:130:7 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:7) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 5 out of 13 tests successfully.
```
<a name="9491c515-3302-4830-a042-ed0aa11dcd3a"></a>
### 8911-f8db2af/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32557
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e9e56d6079a3:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 13 seconds
{"name": "awscli", "duration": 310638, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32557/awscli-mint-test-bucket-3490""}

Executed 0 out of 13 tests successfully.
```
<a name="70a9ba96-ab6f-410f-bc28-7a83585a53b8"></a>
### 8911-f8db2af/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31464
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2723d5c35956:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 43 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 42 seconds
{
  "args": {},
  "duration": 102950,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-31 11:19 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#b679ceeb-303a-4ba4-9c77-89f8e617a5b4) |
| mint-large-bucket.sh | :x: [more...](#1edaba30-dce2-429d-85e2-f9cce3b5503b) |
| mint-dist-xl.sh | :x: [more...](#e6a868a6-a92c-4ff6-996e-054e681382b8) |
| mint-gateway-azure.sh | :x: [more...](#89fd9c7a-2e51-442f-b29f-847cf725de52) |
<a name="e6a868a6-a92c-4ff6-996e-054e681382b8"></a>
### 8911-0cfa5ec/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31367
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cf2297f7c73f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 6 seconds
{"name": "awscli", "duration": 304389, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31367/awscli-mint-test-bucket-31538""}

Executed 0 out of 13 tests successfully.
```
<a name="89fd9c7a-2e51-442f-b29f-847cf725de52"></a>
### 8911-0cfa5ec/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32410
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5e704049028f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 56 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 16 seconds
(4/13) Running mc tests ... done in 6 minutes and 10 seconds
(5/13) Running minio-go tests ... FAILED in 18 minutes and 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-aq5dh9crfg0xivwj",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 240,
  "error": "The specified bucket is not valid.",
  "function": "ListObjects(bucketName, objectPrefix, recursive, doneCh)",
  "message": "PutObject 1 call failed",
  "name": "minio-go: testListObjects",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="b679ceeb-303a-4ba4-9c77-89f8e617a5b4"></a>
### 8911-0cfa5ec/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32375
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8f3748cbc76f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 8 seconds
{
  "name": "awscli",
  "duration": 6354,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
<a name="1edaba30-dce2-429d-85e2-f9cce3b5503b"></a>
### 8911-0cfa5ec/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32059
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fdabdb2e6279:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 41 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 29 seconds
{
  "args": {},
  "duration": 90483,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-01-31 14:38 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#11d6f268-6d93-442e-b47f-a6bfa8df7e73) |
| mint-fs.sh | :x: [more...](#dbe72b99-b1a2-4a2c-94f8-5a05b7777a1d) |
| mint-dist-xl.sh | :x: [more...](#58b45e18-f045-4178-846a-a13d2990fbbb) |
| mint-gateway-azure.sh | :x: [more...](#2f8b1231-85cd-4c93-8336-670be8904a92) |
<a name="11d6f268-6d93-442e-b47f-a6bfa8df7e73"></a>
### 8911-a539f5f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31826
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7306f885f74f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 20 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 48 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 35 seconds
{
  "args": {},
  "duration": 86211,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="2f8b1231-85cd-4c93-8336-670be8904a92"></a>
### 8911-a539f5f/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32322
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8b78e9d68622:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 14 seconds
{"name": "awscli", "duration": 311978, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32322/awscli-mint-test-bucket-5216""}

Executed 0 out of 13 tests successfully.
```
<a name="dbe72b99-b1a2-4a2c-94f8-5a05b7777a1d"></a>
### 8911-a539f5f/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30291
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 55e8af7b7f95:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 309236, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30291/awscli-mint-test-bucket-16829""}

Executed 0 out of 13 tests successfully.
```
<a name="58b45e18-f045-4178-846a-a13d2990fbbb"></a>
### 8911-a539f5f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31375
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp af6438e3059d:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 16 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 4 seconds
(4/13) Running mc tests ... done in 36 seconds
(5/13) Running minio-go tests ... done in 13 minutes and 21 seconds
(6/13) Running minio-js tests ... FAILED in 40 seconds
{
  "name": "minio-js",
  "function": "listObjects(bucketName, prefix, recursive)",
  "args": "bucketName:minio-js-test-8084a9c8-3d89-4f95-9d7b-6ba48d2e9184, recursive:false",
  "duration": 275,
  "status": "FAIL",
  "error": "Error: done() called multiple times at /mint/run/core/minio-js/node_modules/mocha-steps/lib/step.js:67:11 at /mint/run/core/minio-js/test/functional-tests.js:1161:13 at wrapper (node_modules/minio/node_modules/async/dist/async.js:273:20) at iterateeCallback (node_modules/minio/node_modules/async/dist/async.js:418:21) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:326:20 at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:1846:25 at DestroyableTransform.<anonymous> (node_modules/minio/dist/main/minio.js:514:15) at done (node_modules/readable-stream/lib/_stream_transform.js:192:25) at /mint/run/core/minio-js/node_modules/readable-stream/lib/_stream_transform.js:130:7 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:7) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 5 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-01 05:25 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#faa8642c-f6e9-43f3-8e20-57137850adf3) |
| mint-worm.sh | :x: [more...](#7ea197ff-fc4b-47d6-ba72-f9bd7c30d89e) |
| mint-dist-xl.sh | :x: [more...](#3ea7aa41-6abe-4a4a-82c8-4dde0bcdf4d4) |
| mint-gateway-azure.sh | :x: [more...](#cb846b63-4d12-4d8e-88f7-b2b98f29b545) |
<a name="cb846b63-4d12-4d8e-88f7-b2b98f29b545"></a>
### 8911-7ba505b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31719
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp df78ad79a154:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 306793, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31719/awscli-mint-test-bucket-1269""}

Executed 0 out of 13 tests successfully.
```
<a name="3ea7aa41-6abe-4a4a-82c8-4dde0bcdf4d4"></a>
### 8911-7ba505b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31366
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fdcc1ecfde3b:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 17 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 4 seconds
(4/13) Running mc tests ... done in 39 seconds
(5/13) Running minio-go tests ... done in 11 minutes and 10 seconds
(6/13) Running minio-js tests ... FAILED in 18 seconds
{
  "name": "minio-js",
  "function": "listObjects(bucketName, prefix, recursive)",
  "args": "bucketName:minio-js-test-fab0f914-90f9-4a72-86ed-df6dad6cfca3, recursive:false",
  "duration": 282,
  "status": "FAIL",
  "error": "Error: done() called multiple times at /mint/run/core/minio-js/node_modules/mocha-steps/lib/step.js:67:11 at /mint/run/core/minio-js/test/functional-tests.js:1161:13 at wrapper (node_modules/minio/node_modules/async/dist/async.js:273:20) at iterateeCallback (node_modules/minio/node_modules/async/dist/async.js:418:21) at /mint/run/core/minio-js/node_modules/minio/node_modules/async/dist/async.js:326:20 at /mint/run/core/minio-js/node_modules/minio/dist/main/minio.js:1846:25 at DestroyableTransform.<anonymous> (node_modules/minio/dist/main/minio.js:514:15) at done (node_modules/readable-stream/lib/_stream_transform.js:192:25) at /mint/run/core/minio-js/node_modules/readable-stream/lib/_stream_transform.js:130:7 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:79:7) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 5 out of 13 tests successfully.
```
<a name="7ea197ff-fc4b-47d6-ba72-f9bd7c30d89e"></a>
### 8911-7ba505b/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30080
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1d8ffd6dfdd7:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-57ui0oz58byejfzzsid7sqi1fwzaq7tanai0egr910s8qnuhy01ctvy",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120268,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30080/bucket-57ui0oz58byejfzzsid7sqi1fwzaq7tanai0egr910s8qnuhy01ctvy: dial tcp 72.28.97.55:30080: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="faa8642c-f6e9-43f3-8e20-57137850adf3"></a>
### 8911-7ba505b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30983
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8c5ec3f36e23:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 57 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 37 seconds
{
  "args": {},
  "duration": 117839,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-01 06:34 UTC, harshavardhana approved these changes

2020-02-02 01:37 UTC, aead approved these changes

2020-02-02 01:45 UTC, merged