Fix an issue where MinIO was logging every error twice
minio/minio pull request #8953
Opened 2020-02-06 07:25 UTC by nitisht

## Description
The logging subsystem was initialised under init() method in
both gateway-main.go and server-main.go which are part of
same package. This created two logging targets and hence
errors were logged twice. This PR removes the init() method
from gateway-main.go

## Motivation and Context
Fix error logging on console.

## How to test this PR?
Start MinIO server and create a sitation where MinIO would 
log the error on console. Before this PR, you'd notice two error 
logs per error. With this PR, you should get a single error log
on console

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-02-06 07:45 UTC, harshavardhana commented
Are you sure can remove the GOPATH/GOROOT constants @nitisht we have to avoid further init of the console target..

2020-02-06 08:00 UTC, nitisht commented
> Are you sure can remove the GOPATH/GOROOT constants @nitisht we have to avoid further init of the console target..

My understanding is the constants are being set here https://github.com/minio/minio/blob/master/cmd/server-main.go#L41 anyways so we can remove it.

2020-02-06 08:06 UTC, harshavardhana commented
init is better in this scenario.. rather than in cli.Main()

2020-02-06 08:27 UTC, nitisht commented
@harshavardhana done

2020-02-06 09:36 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d668d966-5de2-43af-9638-53129f67484c) |
| mint-large-bucket.sh | :x: [more...](#1b2f8f0e-e518-4492-97e2-8b816e1c7ff2) |
| mint-dist-xl.sh | :x: [more...](#ad408bfe-cdbb-455f-a02a-b77df5816de9) |
| mint-gateway-azure.sh | :x: [more...](#bff69ab8-6bc5-48d6-a0b2-3790f960de72) |
<a name="bff69ab8-6bc5-48d6-a0b2-3790f960de72"></a>
### 8953-01fb55d/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32580
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8d1b1e70b8fe:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 3 minutes and 16 seconds
{
  "name": "awscli",
  "duration": 1543,
  "function": "make_bucket_with_lock\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 0 out of 13 tests successfully.
```
<a name="1b2f8f0e-e518-4492-97e2-8b816e1c7ff2"></a>
### 8953-01fb55d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31250
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a8a296e2437f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 309744, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31250/awscli-mint-test-bucket-21016""}

Executed 0 out of 13 tests successfully.
```
<a name="ad408bfe-cdbb-455f-a02a-b77df5816de9"></a>
### 8953-01fb55d/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30425
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 24c982f60639:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 15 seconds
{"name": "awscli", "duration": 313183, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30425/awscli-mint-test-bucket-32444""}

Executed 0 out of 13 tests successfully.
```
<a name="d668d966-5de2-43af-9638-53129f67484c"></a>
### 8953-01fb55d/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30103
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 037306058d8f:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 12 seconds
{
  "name": "awscli",
  "duration": 9480,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-06 12:16 UTC, Praveenrajmani approved these changes
LGTM

2020-02-06 12:19 UTC, harshavardhana approved these changes

2020-02-06 12:22 UTC, harshavardhana requested changes
I think this was added on purpose can you check @nitisht with `git blame` to ensure that you are not introducing regression?

2020-02-06 12:26 UTC, nitisht commented
It was added in #8654

2020-02-06 12:44 UTC, harshavardhana commented
Correct so you cannot change that @nitisht what I suggest is remove the double reference elsewhere in the code and keep the init()

We should also move initAllSubsystems() also into init()

2020-02-06 13:01 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#c7668a6f-4131-45fa-b801-31c249ba83c0) |
| mint-large-bucket.sh | :x: [more...](#f01c1e60-d350-4696-be8e-c43e821c1c12) |
| mint-gateway-azure.sh | :x: [more...](#110bb3d5-3daa-40ed-ac61-5e25da3a7139) |
<a name="f01c1e60-d350-4696-be8e-c43e821c1c12"></a>
### 8953-f738ef3/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30327
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0581a1fda394:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 20 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 8 seconds
(4/13) Running mc tests ... done in 46 seconds
(5/13) Running minio-go tests ... FAILED in 12 minutes and 18 seconds
{
  "args": {},
  "duration": 62812,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="110bb3d5-3daa-40ed-ac61-5e25da3a7139"></a>
### 8953-f738ef3/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32119
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 75e3fc912193:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 26 seconds
{
  "name": "awscli",
  "duration": 2247,
  "function": "aws --endpoint-url http://72.28.97.56:32119 s3api put-object --body /mint/data/datafile-0-b --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-0-b\n",
  "status": "FAIL",
  "error": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"
}

Executed 0 out of 13 tests successfully.
```
<a name="c7668a6f-4131-45fa-b801-31c249ba83c0"></a>
### 8953-f738ef3/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31649
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cd990c09d1b8:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 12 seconds
{
  "name": "awscli",
  "duration": 9991,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-06 13:39 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ebc1d62d-bf3a-44b2-a965-9607cf0ddc1d) |
| mint-worm.sh | :x: [more...](#f9158089-16af-47b8-a418-91377c5c6e14) |
| mint-gateway-azure.sh | :x: [more...](#e49238dc-d372-4abf-adfc-65c186062654) |
<a name="f9158089-16af-47b8-a418-91377c5c6e14"></a>
### 8953-b71c014/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30702
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bf45647bce1f:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-j57jfm5dpk1nm1u7wv8vt8ecq4w4hv2kavrcivm5l9yy7e4v3fdq45s",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120356,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30702/bucket-j57jfm5dpk1nm1u7wv8vt8ecq4w4hv2kavrcivm5l9yy7e4v3fdq45s: dial tcp 72.28.97.55:30702: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="ebc1d62d-bf3a-44b2-a965-9607cf0ddc1d"></a>
### 8953-b71c014/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32152
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 45454e4543cf:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 310352, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:32152/awscli-mint-test-bucket-26367""}

Executed 0 out of 13 tests successfully.
```
<a name="e49238dc-d372-4abf-adfc-65c186062654"></a>
### 8953-b71c014/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31673
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a5e129e9c173:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 8 seconds
{"name": "awscli", "duration": 306267, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31673/awscli-mint-test-bucket-5473""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-06 14:20 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#8f1dcb5a-e8a7-4961-aeab-66763e5d3179) |
| mint-large-bucket.sh | :x: [more...](#b08b0e53-888b-4fb7-82c1-d7964cde0c98) |
| mint-fs.sh | :x: [more...](#932ff5c3-2912-4f07-95d9-05b16885baee) |
| mint-gateway-azure.sh | :x: [more...](#67290ada-09a0-49a7-a2c9-bf711a252bdc) |
<a name="b08b0e53-888b-4fb7-82c1-d7964cde0c98"></a>
### 8953-0a8f5bb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:30018
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4e92a1ad99c0:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 20 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 50 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 29 seconds
{
  "args": {},
  "duration": 93962,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="932ff5c3-2912-4f07-95d9-05b16885baee"></a>
### 8953-0a8f5bb/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31933
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e70adb8f1c44:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 9 seconds
{"name": "awscli", "duration": 307331, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:31933/awscli-mint-test-bucket-11730""}

Executed 0 out of 13 tests successfully.
```
<a name="67290ada-09a0-49a7-a2c9-bf711a252bdc"></a>
### 8953-0a8f5bb/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32082
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a986a23063ca:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 1 minutes and 46 seconds
{
  "name": "awscli",
  "duration": 1539,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 0 out of 13 tests successfully.
```
<a name="8f1dcb5a-e8a7-4961-aeab-66763e5d3179"></a>
### 8953-0a8f5bb/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31191
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 906cfbaff41e:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 13 seconds
{
  "name": "awscli",
  "duration": 10886,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-06 15:40 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a29da339-0e15-4986-b5da-8a6184d4b8b8) |
| mint-fs.sh | :x: [more...](#9fd3914d-e025-4947-b2ef-9662b4f0aae5) |
<a name="a29da339-0e15-4986-b5da-8a6184d4b8b8"></a>
### 8953-9c93fe4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30220
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f28d567ea751:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 8 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 28 seconds
(4/13) Running mc tests ... done in 1 minutes and 22 seconds
(5/13) Running minio-go tests ... FAILED in 22 minutes and 6 seconds
{
  "args": {},
  "duration": 104686,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="9fd3914d-e025-4947-b2ef-9662b4f0aae5"></a>
### 8953-9c93fe4/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30437
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d3c3f7215178:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 7 seconds
{"name": "awscli", "duration": 304876, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30437/awscli-mint-test-bucket-2264""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-07 06:55 UTC, nitisht commented
Updated. @harshavardhana PTAL

2020-02-07 06:56 UTC, harshavardhana approved these changes
LGTM & tested

2020-02-07 08:18 UTC, merged

2020-02-07 09:36 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#97f2f6e8-85cd-449d-841f-dba3591acdb4) |
| mint-worm.sh | :x: [more...](#343944d7-a803-4543-99a2-af80a218ea24) |
<a name="343944d7-a803-4543-99a2-af80a218ea24"></a>
### 8953-f0ba07a/mint-worm.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31959
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            worm
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fa2416f5c495:/mint/log /tmp/mint-logs'

(1/1) Running worm tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "bucket-hdrr2kabwlln9kixw8pdwr1n2dc9om9n6ti559ozm6tdkl4anr2xxed",
    "expiry": 60000000000,
    "objectName": "testObject"
  },
  "duration": 120339,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31959/bucket-hdrr2kabwlln9kixw8pdwr1n2dc9om9n6ti559ozm6tdkl4anr2xxed: dial tcp 72.28.97.55:31959: i/o timeout",
  "function": "PutAndDelete",
  "message": "WORM_MODE ON  - CreateBucket Failed",
  "name": "test worm mode",
  "status": "FAIL"
}

Executed 0 out of 1 tests successfully.
```
<a name="97f2f6e8-85cd-449d-841f-dba3591acdb4"></a>
### 8953-f0ba07a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31489
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f8e968ee5b57:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 26 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 8 seconds
(4/13) Running mc tests ... done in 51 seconds
(5/13) Running minio-go tests ... FAILED in 15 minutes and 6 seconds
{
  "args": {},
  "duration": 92001,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-07 11:01 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3e81d4d3-2dae-4db4-9a58-598a34caeb13) |
| mint-gateway-nas.sh | :x: [more...](#23e58772-ef02-428b-9c0d-5377051197a1) |
<a name="23e58772-ef02-428b-9c0d-5377051197a1"></a>
### 8953-d0239e0/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30933
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp df9d686aba04:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 11 seconds
{"name": "awscli", "duration": 308672, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30933/awscli-mint-test-bucket-17810""}

Executed 0 out of 13 tests successfully.
```
<a name="3e81d4d3-2dae-4db4-9a58-598a34caeb13"></a>
### 8953-d0239e0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:31802
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 45591eb1fa35:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 22 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 50 seconds
(5/13) Running minio-go tests ... FAILED in 15 minutes and 46 seconds
{
  "args": {},
  "duration": 99962,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-07 12:22 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a9ce599e-d8b4-4bb0-a571-1b3d6bbaeed2) |
| mint-large-bucket.sh | :x: [more...](#19620049-e65a-4fd6-90b2-f08777604f5d) |
<a name="19620049-e65a-4fd6-90b2-f08777604f5d"></a>
### 8953-ee560fd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30129
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4a2f8c9f7b49:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 21 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 49 seconds
(5/13) Running minio-go tests ... FAILED in 14 minutes and 35 seconds
{
  "args": {},
  "duration": 102235,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="a9ce599e-d8b4-4bb0-a571-1b3d6bbaeed2"></a>
### 8953-ee560fd/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30319
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e7fc02212db6:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 5 minutes and 12 seconds
{"name": "awscli", "duration": 309307, "function": "make_bucket\n", "status": "FAIL", "error": "Connect timeout on endpoint URL: "http://72.28.97.55:30319/awscli-mint-test-bucket-29554""}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally