Fix Error Codes for incorrect ObjectTagging fields
minio/minio pull request #8971
Opened 2020-02-10 07:10 UTC by nitisht

## Description
Fix Error Codes for incorrect ObjectTagging fields

## Motivation and Context
MinIO responded with different error code and messages as compared to AWS S3, when ObjectTagging Input Fields when parsed and found incorrect. This PR fixes the behaviour.

## How to test this PR?
Test 4 scenarios against AWS S3 and MinIO, the error code and message should match.
- Too many tags > 10
- Duplicate Tag Keys
- Long Tag Key > 128 Chars
- Long Tag Value > 256 Chars

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-02-10 09:25 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#127fa464-aa97-42a4-a15e-a5b4aa414db4) |
| mint-large-bucket.sh | :x: [more...](#86f1f488-0e3a-4852-9fb8-9e015a2dec33) |
<a name="86f1f488-0e3a-4852-9fb8-9e015a2dec33"></a>
### 8971-7a184bb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:31849
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ae4d3db0692:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 32 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 7 seconds
(4/13) Running mc tests ... done in 56 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 45 seconds
{
  "args": {},
  "duration": 79211,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
<a name="127fa464-aa97-42a4-a15e-a5b4aa414db4"></a>
### 8971-7a184bb/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30614
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3847e1286495:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... FAILED in 18 seconds
{
  "name": "awscli",
  "duration": 15111,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (XMinioServerNotInitialized) when calling the CreateBucket operation (reached max retries: 4): Server not initialized, please try again."
}

Executed 0 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-10 17:34 UTC, harshavardhana requested changes
Perhaps we can take this opportunity to add tests in mint?

2020-02-11 05:06 UTC, nitisht commented
> Perhaps we can take this opportunity to add tests in mint?

Done

2020-02-11 08:36 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#095e6465-012e-41e1-a7f8-9d4eb1ad84ee) |
<a name="095e6465-012e-41e1-a7f8-9d4eb1ad84ee"></a>
### 8971-c9a17cd/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31657
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 735125f95453:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 2 minutes and 23 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 1 minutes and 3 seconds
(5/13) Running minio-go tests ... FAILED in 12 minutes and 45 seconds
{
  "args": {},
  "duration": 103215,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-11 11:34 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a705dfb5-4c94-425b-8340-fd57c3f69918) |
<a name="a705dfb5-4c94-425b-8340-fd57c3f69918"></a>
### 8971-ee35ab5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31841
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e997f775b0cb:/mint/log /tmp/mint-logs'

(1/13) Running awscli tests ... done in 1 minutes and 33 seconds
(2/13) Running aws-sdk-java tests ... done in 1 seconds
(3/13) Running aws-sdk-ruby tests ... done in 6 seconds
(4/13) Running mc tests ... done in 52 seconds
(5/13) Running minio-go tests ... FAILED in 13 minutes and 16 seconds
{
  "args": {},
  "duration": 68442,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 4 out of 13 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-11 23:08 UTC, kannappanr approved these changes

2020-02-12 00:57 UTC, BigUstad approved these changes
LGTM

2020-02-12 01:42 UTC, merged