acl: Support PUT calls with success for 'private' ACL's
minio/minio pull request #9000
Opened 2020-02-14 17:02 UTC by harshavardhana

## Description
acl: Support PUT calls with success for 'private' ACL's

## Motivation and Context
Add dummy calls which respond success when ACL's
are set to be private and fails, if user tries
to change them from their default 'private'

Some applications such as nuxeo may have an
unnecessary requirement for this operation,
we support this anyways such that don't have
to fully implement the functionality just that
we can respond with success for default ACLs

## How to test this PR?
You would need a Nuxeo deployment, upon init when the bucket doesn't exist such a bucket is created, subsequently, the caller calls https://github.com/nuxeo/nuxeo/blob/master/addons/nuxeo-core-binarymanager-cloud/nuxeo-core-binarymanager-s3/src/main/java/org/nuxeo/ecm/core/storage/sql/S3BinaryManager.java#L366

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-02-14 18:06 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#e8d2312b-4cc0-4fce-80ad-645ae629d1a6) |
| mint-large-bucket.sh | :x: [more...](#f522c2aa-8578-4b2c-913c-924239a5e3e1) |
| mint-gateway-azure.sh | :x: [more...](#341cabaf-4671-43e0-9c09-49d22731ba82) |
<a name="f522c2aa-8578-4b2c-913c-924239a5e3e1"></a>
### 9000-e89b182/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31642
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c529df4af9b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 44 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... FAILED in 15 minutes and 23 seconds
{
  "args": {},
  "duration": 93603,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="341cabaf-4671-43e0-9c09-49d22731ba82"></a>
### 9000-e89b182/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:32334
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3dc29754cdb6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 13 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 5 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 27 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... done in 19 minutes and 3 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 19 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11811,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-21pgprn, objectName=minio-java-test-b6cd7m, resource=/minio-java-test-21pgprn/minio-java-test-b6cd7m, requestId=15F356F8C845E9D8, hostId=5a88b54d-0a1c-4fd6-b470-aeb77de07f81)\nrequest={method=PUT, url=http://72.28.97.52:32334/minio-java-test-21pgprn/minio-java-test-b6cd7m?uploadId=4b81753cf6060ed8&partNumber=1, headers=x-amz-copy-source-if-match: 56ecb3e1361a9ed74793bd681c2e7dc9-2\nx-amz-copy-source: minio-java-test-21pgprn/minio-java-test-230236j\nAccept-Encoding: identity\nHost: 72.28.97.52:32334\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200214T180520Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200214/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-14T17-02-47Z\nVary: Origin\nX-Amz-Request-Id: 15F356F8C845E9D8\nX-Xss-Protection: 1; mode=block\nDate: Fri, 14 Feb 2020 18:05:20 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="e8d2312b-4cc0-4fce-80ad-645ae629d1a6"></a>
### 9000-e89b182/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30682
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b441a044a4bd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-ahrvmzif6oeoo5",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364394,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F354F5D849F33A, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-14 18:54 UTC, poornas requested changes

2020-02-14 18:54 UTC, poornas commented on cmd/acl-handlers.go
> +	xhttp "github.com/minio/minio/cmd/http"
can you update the license header on the files in this patch to include 2020?

2020-02-14 21:03 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#510e6518-8c39-4772-acc8-79774d44ed14) |
| mint-large-bucket.sh | :x: [more...](#c27d378f-7b7a-46e4-ae41-7abfbc91b133) |
| mint-gateway-azure.sh | :x: [more...](#12289972-a38c-4058-bdc4-3866a4d495bd) |
<a name="c27d378f-7b7a-46e4-ae41-7abfbc91b133"></a>
### 9000-66d5f46/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32416
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d39148ff8002:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 46 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 19 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 47 seconds
(8/14) Running minio-dotnet tests ... done in 39 seconds
(9/14) Running minio-go tests ... FAILED in 13 minutes and 58 seconds
{
  "args": {},
  "duration": 64460,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="510e6518-8c39-4772-acc8-79774d44ed14"></a>
### 9000-66d5f46/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31224
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 90a6d55a43a3:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-025bffpufrwdex",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365435,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F35E6A6B8089F6, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="12289972-a38c-4058-bdc4-3866a4d495bd"></a>
### 9000-66d5f46/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32292
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 96f2ad132022:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 11 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 15 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 7 minutes and 30 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 46 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 26 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11636,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-2rcj2gb, objectName=minio-java-test-3klc813, resource=/minio-java-test-2rcj2gb/minio-java-test-3klc813, requestId=15F360A5ABA3292C, hostId=cb966430-2f9b-480e-9173-a5de2b76a626)\nrequest={method=PUT, url=http://72.28.97.56:32292/minio-java-test-2rcj2gb/minio-java-test-3klc813?uploadId=81d7bb9a217e99a4&partNumber=1, headers=x-amz-copy-source-if-match: e259b0943fa67412944dfdef602f447f-2\nx-amz-copy-source: minio-java-test-2rcj2gb/minio-java-test-1lfhdmr\nAccept-Encoding: identity\nHost: 72.28.97.56:32292\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200214T210238Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200214/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-14T19-56-20Z\nVary: Origin\nX-Amz-Request-Id: 15F360A5ABA3292C\nX-Xss-Protection: 1; mode=block\nDate: Fri, 14 Feb 2020 21:02:39 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-14 21:46 UTC, poornas approved these changes
LGTM

2020-02-14 22:09 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#051fd5b2-2e89-4fef-a993-dbb6dd561098) |
| mint-large-bucket.sh | :x: [more...](#f6cda650-3b36-48ec-a1d7-185c84450ad3) |
| mint-gateway-azure.sh | :x: [more...](#3d2d921a-04d5-4e9d-a2a4-a86ca9f6abf7) |
<a name="f6cda650-3b36-48ec-a1d7-185c84450ad3"></a>
### 9000-683ad43/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31329
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 788b8a2322cc:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 48 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... FAILED in 13 minutes and 15 seconds
{
  "args": {},
  "duration": 102959,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="051fd5b2-2e89-4fef-a993-dbb6dd561098"></a>
### 9000-683ad43/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:32663
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8d127c57a8a8:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fyjd3kvzwlls53",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 364996,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F362160C9C9724, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="3d2d921a-04d5-4e9d-a2a4-a86ca9f6abf7"></a>
### 9000-683ad43/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:31246
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2986d02afe5f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 17 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 35 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 34 seconds
(9/14) Running minio-go tests ... done in 20 minutes and 57 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 28 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 12796,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-19k7jli, objectName=minio-java-test-g3a0og, resource=/minio-java-test-19k7jli/minio-java-test-g3a0og, requestId=15F3643A5BBC9B20, hostId=efe57103-f589-4269-bdea-8a0e37df932c)\nrequest={method=PUT, url=http://72.28.97.61:31246/minio-java-test-19k7jli/minio-java-test-g3a0og?uploadId=a448e0c600091156&partNumber=1, headers=x-amz-copy-source-if-match: 9a6c945136fad96004c4e711ac148248-2\nx-amz-copy-source: minio-java-test-19k7jli/minio-java-test-15m2pbd\nAccept-Encoding: identity\nHost: 72.28.97.61:31246\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200214T220815Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200214/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-14T21-03-46Z\nVary: Origin\nX-Amz-Request-Id: 15F3643A5BBC9B20\nX-Xss-Protection: 1; mode=block\nDate: Fri, 14 Feb 2020 22:08:16 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-15 02:32 UTC, krisis approved these changes

2020-02-15 02:38 UTC, harshavardhana commented
Doing some tests, will unblock here soon

2020-02-15 03:48 UTC, harshavardhana commented
Unblocked

2020-02-15 04:26 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#62e50855-79c8-4c51-98df-70e39d35f4a4) |
| mint-gateway-azure.sh | :x: [more...](#5f170456-57c1-4632-8e60-6002bd510ad7) |
<a name="62e50855-79c8-4c51-98df-70e39d35f4a4"></a>
### 9000-144c44e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30424
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 375a3488c3f6:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 49 seconds
(8/14) Running minio-dotnet tests ... done in 41 seconds
(9/14) Running minio-go tests ... FAILED in 13 minutes and 38 seconds
{
  "args": {},
  "duration": 97346,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="5f170456-57c1-4632-8e60-6002bd510ad7"></a>
### 9000-144c44e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30014
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ff9681f1ffa0:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 15 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... FAILED in 3 minutes and 6 seconds
{
  "name": "awscli",
  "duration": 1527,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "delete: s3://awscli-mint-test-bucket-25766/datafile-1-kBremove_bucket: awscli-mint-test-bucket-25766"
}

Executed 4 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-15 10:26 UTC, harshavardhana commented
Looks like all our SimpleCI tests might fail the DNS resolution failure

```
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/96/96da9143fb1848141472255c4ae8b0b3885072a598921ab8e0793dc32a674f77/data?verify=1581743540-mZlu9z%2Fn4VyRVx7r3YfzxnYtLMc%3D: dial tcp: lookup production.cloudflare.docker.com on 10.43.0.10:53: server misbehaving
5142
error running ci task for minio/minio:144c44e91661e69dee86b26df13adc06c755a6b3: exit status 1
```

2020-02-15 12:25 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#3c80b2a5-ab86-466b-b6e6-0e9190290d13) |
| mint-gateway-azure.sh | :x: [more...](#17204390-c025-4e4a-b71b-2f62c463c0a5) |
<a name="17204390-c025-4e4a-b71b-2f62c463c0a5"></a>
### 9000-cc6ad77/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30114
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6559c97fde9a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 17 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 30 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 11 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11580,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3jfkf33, objectName=minio-java-test-4sdabi, resource=/minio-java-test-3jfkf33/minio-java-test-4sdabi, requestId=15F392F71482C4AD, hostId=04db89d9-2e65-4bec-bd59-42c2e9afaa65)\nrequest={method=PUT, url=http://72.28.97.58:30114/minio-java-test-3jfkf33/minio-java-test-4sdabi?uploadId=b75381c379ceccf3&partNumber=1, headers=x-amz-copy-source-if-match: 659f40b3aa496b8929844082d39c7248-2\nx-amz-copy-source: minio-java-test-3jfkf33/minio-java-test-735v3p\nAccept-Encoding: identity\nHost: 72.28.97.58:30114\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200215T122444Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200215/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-15T11-19-35Z\nVary: Origin\nX-Amz-Request-Id: 15F392F71482C4AD\nX-Xss-Protection: 1; mode=block\nDate: Sat, 15 Feb 2020 12:24:44 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="3c80b2a5-ab86-466b-b6e6-0e9190290d13"></a>
### 9000-cc6ad77/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30913
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 56c75a31b489:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-yjj2l9jricdxhq",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120339,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30913/aws-sdk-go-test-yjj2l9jricdxhq: dial tcp 72.28.97.55:30913: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-15 17:00 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#feb6d339-05e7-4703-80a8-5382f50ab1f9) |
| mint-dist-xl.sh | :x: [more...](#e2c190e2-71e2-4122-87b0-6f56e4c37c36) |
| mint-gateway-azure.sh | :x: [more...](#31842596-d08e-40a4-89e2-d5b31a2f0bd7) |
<a name="31842596-d08e-40a4-89e2-d5b31a2f0bd7"></a>
### 9000-21516d2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32192
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0809c23c70bd:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 17 seconds
(4/14) Running aws-sdk-ruby tests ... done in 19 seconds
(5/14) Running awscli tests ... done in 3 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 15 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 26 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 56 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11980,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-2uq816v, objectName=minio-java-test-3goibvs, resource=/minio-java-test-2uq816v/minio-java-test-3goibvs, requestId=15F3A1F732F8B084, hostId=b5bebe94-6c4a-4ff1-bcac-4b7c455c6cd1)\nrequest={method=PUT, url=http://72.28.97.56:32192/minio-java-test-2uq816v/minio-java-test-3goibvs?uploadId=3d8f80f31920258b&partNumber=1, headers=x-amz-copy-source-if-match: d3ba52f884ae26da0c277313ff0c515f-2\nx-amz-copy-source: minio-java-test-2uq816v/minio-java-test-b1snkv\nAccept-Encoding: identity\nHost: 72.28.97.56:32192\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200215T165937Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200215/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-15T15-53-55Z\nVary: Origin\nX-Amz-Request-Id: 15F3A1F732F8B084\nX-Xss-Protection: 1; mode=block\nDate: Sat, 15 Feb 2020 16:59:37 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="e2c190e2-71e2-4122-87b0-6f56e4c37c36"></a>
### 9000-21516d2/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32131
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4d63cf084bb1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 5 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2qabr4c6wnh40e",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365131,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F39FC6B3EEDBBD, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="feb6d339-05e7-4703-80a8-5382f50ab1f9"></a>
### 9000-21516d2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:30773
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c915ecec8df1:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-et956o6y5vlkv9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 363836,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F39FC67F2F9028, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-15 20:14 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3d65fdd0-94e1-4b14-9d59-f7c95532095d) |
| mint-large-bucket.sh | :x: [more...](#76fc0ee0-ffae-4481-a5fd-5cd2bad262fa) |
| mint-fs.sh | :x: [more...](#98a9d2ea-4ea5-4f1f-b370-001ade376316) |
| mint-gateway-azure.sh | :x: [more...](#1be85aec-c068-45cb-a51f-a588be752c35) |
<a name="98a9d2ea-4ea5-4f1f-b370-001ade376316"></a>
### 9000-f2bdfab/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32450
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 40339cc30be4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-zin9pxo9v9kvao",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120378,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32450/aws-sdk-go-test-zin9pxo9v9kvao: dial tcp 72.28.97.55:32450: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="76fc0ee0-ffae-4481-a5fd-5cd2bad262fa"></a>
### 9000-f2bdfab/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:32038
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5f28a5df69f7:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 44 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... FAILED in 13 minutes and 24 seconds
{
  "args": {},
  "duration": 80722,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="3d65fdd0-94e1-4b14-9d59-f7c95532095d"></a>
### 9000-f2bdfab/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31988
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dc326022ae5b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 6 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-d2wyxc9jrxcqf9",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 365934,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15F3AA8C280CD99D, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="1be85aec-c068-45cb-a51f-a588be752c35"></a>
### 9000-f2bdfab/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.51:30619
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9319e4d6394a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 4 minutes and 20 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 7 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 8 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/14) Running minio-go tests ... done in 19 minutes and 51 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 17 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11384,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3mdk4jv, objectName=minio-java-test-398kt0t, resource=/minio-java-test-3mdk4jv/minio-java-test-398kt0t, requestId=15F3AC9636EC380B, hostId=996c061f-00eb-46da-b3d8-e726cd5d6f61)\nrequest={method=PUT, url=http://72.28.97.51:30619/minio-java-test-3mdk4jv/minio-java-test-398kt0t?uploadId=bc7569365f7c517c&partNumber=1, headers=x-amz-copy-source-if-match: 74a9738b6fdc8780b311aeb1e6bbcdac-2\nx-amz-copy-source: minio-java-test-3mdk4jv/minio-java-test-15h5cfv\nAccept-Encoding: identity\nHost: 72.28.97.51:30619\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200215T201415Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200215/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-15T19-11-27Z\nVary: Origin\nX-Amz-Request-Id: 15F3AC9636EC380B\nX-Xss-Protection: 1; mode=block\nDate: Sat, 15 Feb 2020 20:14:15 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-16 06:07 UTC, merged