Support `version` key in the Kafka config
minio/minio pull request #9001
Opened 2020-02-14 18:43 UTC by Praveenrajmani

## Description
Add a field for the Kafka version in the config. The user can explicitly set the
version of the Kafka cluster.

## Motivation and Context
Fixes #8768

## How to test this PR?
With `mc admin get/set`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-02-14 23:33 UTC, poornas approved these changes
LGTM

2020-02-15 02:56 UTC, harshavardhana requested changes

2020-02-15 02:56 UTC, harshavardhana commented on cmd/config/notify/help.go
> +			Description: "version of the Kafka cluster",
```suggestion
			Description: "specify version of the Kafka cluster",
```

2020-02-15 02:56 UTC, harshavardhana commented on docs/bucket/notifications/README.md
> +version          (string)    version of the Kafka cluster e.g '2.2.0'
```suggestion
version          (string)    specify version of the Kafka cluster e.g '2.2.0'
```

2020-02-15 11:19 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#a5b98bf4-b906-4fdf-b2fa-610afca58e1d) |
| mint-gateway-azure.sh | :x: [more...](#82b334ec-746a-4f5c-85b1-1453455c822e) |
<a name="82b334ec-746a-4f5c-85b1-1453455c822e"></a>
### 9001-491d3b4/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32140
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ec4f2d2544c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-w0a1yv0u2ufxe3",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120273,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32140/aws-sdk-go-test-w0a1yv0u2ufxe3: dial tcp 72.28.97.55:32140: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="a5b98bf4-b906-4fdf-b2fa-610afca58e1d"></a>
### 9001-491d3b4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31351
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b2c1ec6073a4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 41 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... FAILED in 14 minutes and 9 seconds
{
  "args": {},
  "duration": 89614,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-16 06:43 UTC, harshavardhana approved these changes

2020-02-17 02:26 UTC, merged