Add all supported scopes from discovery doc
minio/minio pull request #9015
Opened 2020-02-19 05:04 UTC by harshavardhana

## Description
Add all supported scopes from discovery doc

## Motivation and Context
Fixes #9010

## How to test this PR?
As mentioned in the issue #9010 

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-02-19 07:47 UTC, minio-ops commented
```
Error running mint automation
+ mkdir -p 9015-a202b2c/gopath/src/github.com/minio
+ git -C 9015-a202b2c/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9015-a202b2c/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9015-a202b2c/gopath/src/github.com/minio/minio fetch --quiet minio pull/9015/head:pr9015
+ git -C 9015-a202b2c/gopath/src/github.com/minio/minio checkout --quiet pr9015
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/9015-a202b2c/gopath
+ make -C 9015-a202b2c/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading github.com/minio/minio-go/v6 v6.0.45
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/gorilla/mux v1.7.0
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/gorilla/mux v1.7.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/nats-io/stan.go v0.4.5
go: extracting github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: extracting github.com/nats-io/stan.go v0.4.5
go: downloading github.com/klauspost/compress v1.9.8
go: extracting github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: downloading github.com/Shopify/sarama v1.24.1
go: extracting github.com/coreos/etcd v3.3.12+incompatible
go: downloading go.uber.org/atomic v1.3.2
go: extracting github.com/Shopify/sarama v1.24.1
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: extracting github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: extracting go.uber.org/atomic v1.3.2
go: extracting github.com/minio/minio-go/v6 v6.0.45
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/gorilla/handlers v1.4.0
go: extracting github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: extracting github.com/gorilla/handlers v1.4.0
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/json-iterator/go v1.1.9
go: extracting cloud.google.com/go v0.39.0
go: extracting github.com/minio/highwayhash v1.0.0
go: extracting github.com/json-iterator/go v1.1.9
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: extracting github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/klauspost/readahead v1.3.1
go: extracting github.com/klauspost/readahead v1.3.1
go: extracting gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: extracting github.com/klauspost/compress v1.9.8
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: extracting github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/eapache/go-resiliency v1.2.0
go: extracting github.com/eapache/go-resiliency v1.2.0
go: downloading golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: extracting github.com/googleapis/gax-go/v2 v2.0.4
go: extracting github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/prometheus/common v0.2.0
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting github.com/ncw/directio v1.0.5
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: extracting github.com/minio/cli v1.22.0
go: downloading github.com/cheggaaa/pb v1.0.28
go: extracting github.com/prometheus/common v0.2.0
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: extracting golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting github.com/cheggaaa/pb v1.0.28
go: downloading github.com/gorilla/rpc v1.2.0
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/lib/pq v1.1.1
go: extracting github.com/gorilla/rpc v1.2.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: extracting github.com/lib/pq v1.1.1
go: downloading github.com/mattn/go-isatty v0.0.7
go: extracting golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: downloading github.com/mattn/go-runewidth v0.0.4
go: extracting github.com/mattn/go-isatty v0.0.7
go: extracting github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/beevik/ntp v0.2.0
go: extracting github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/nats-io/nuid v1.0.1
go: extracting github.com/minio/hdfs/v3 v3.0.1
go: extracting github.com/beevik/ntp v0.2.0
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: extracting github.com/nats-io/nuid v1.0.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: extracting github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/rs/cors v1.6.0
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: extracting github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/gogo/protobuf v1.2.1
go: extracting gopkg.in/jcmturner/rpc.v1 v1.1.0
go: extracting github.com/rs/cors v1.6.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading github.com/pkg/errors v0.8.1
go: extracting gopkg.in/olivere/elastic.v5 v5.0.80
go: extracting github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: extracting github.com/pkg/errors v0.8.1
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/minio/sio v0.2.0
go: extracting github.com/fatih/color v1.7.0
go: extracting github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/minio/simdjson-go v0.1.3
go: extracting github.com/minio/sio v0.2.0
go: downloading github.com/golang/protobuf v1.3.2
go: extracting google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: extracting gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: extracting github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading github.com/minio/parquet-go v0.0.0-20200125064549-a1e49702e174
go: extracting github.com/golang/protobuf v1.3.2
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: extracting github.com/minio/parquet-go v0.0.0-20200125064549-a1e49702e174
go: extracting github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/mattn/go-colorable v0.1 [...]

2020-02-19 07:48 UTC, minio-ops commented
```
Error running mint automation
+ mkdir -p 9015-7ec0a49/gopath/src/github.com/minio
+ git -C 9015-7ec0a49/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9015-7ec0a49/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9015-7ec0a49/gopath/src/github.com/minio/minio fetch --quiet minio pull/9015/head:pr9015
+ git -C 9015-7ec0a49/gopath/src/github.com/minio/minio checkout --quiet pr9015
+ GO111MODULE=on
+ GOPATH=/mnt/nvme/mint-auto/9015-7ec0a49/gopath
+ make -C 9015-7ec0a49/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading google.golang.org/api v0.5.0
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: downloading github.com/minio/minio-go/v6 v6.0.45
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading github.com/rs/cors v1.6.0
go: extracting github.com/dustin/go-humanize v1.0.0
go: extracting github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: extracting github.com/minio/cli v1.22.0
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/json-iterator/go v1.1.9
go: extracting gopkg.in/ldap.v3 v3.0.3
go: extracting github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: extracting github.com/minio/minio-go/v6 v6.0.45
go: extracting github.com/json-iterator/go v1.1.9
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: downloading github.com/gorilla/mux v1.7.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/minio/simdjson-go v0.1.3
go: extracting github.com/rs/cors v1.6.0
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: extracting github.com/gorilla/mux v1.7.0
go: extracting github.com/fatih/structs v1.1.0
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: extracting github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: extracting github.com/alecthomas/participle v0.2.1
go: downloading github.com/klauspost/compress v1.9.8
go: downloading gopkg.in/ini.v1 v1.48.0
go: extracting github.com/minio/hdfs/v3 v3.0.1
go: extracting github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: extracting gopkg.in/ini.v1 v1.48.0
go: downloading github.com/gorilla/handlers v1.4.0
go: extracting github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: extracting github.com/gorilla/handlers v1.4.0
go: extracting github.com/minio/simdjson-go v0.1.3
go: extracting github.com/klauspost/reedsolomon v1.9.3
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/prometheus/common v0.2.0
go: extracting github.com/prometheus/common v0.2.0
go: downloading golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/ncw/directio v1.0.5
go: extracting github.com/ncw/directio v1.0.5
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: extracting cloud.google.com/go v0.39.0
go: downloading github.com/beevik/ntp v0.2.0
go: extracting github.com/klauspost/compress v1.9.8
go: downloading go.uber.org/atomic v1.3.2
go: extracting go.uber.org/atomic v1.3.2
go: downloading github.com/gogo/protobuf v1.2.1
go: extracting github.com/beevik/ntp v0.2.0
go: extracting github.com/coreos/etcd v3.3.12+incompatible
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/minio/sha256-simd v0.1.1
go: extracting github.com/minio/sha256-simd v0.1.1
go: extracting github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading google.golang.org/grpc v1.22.0
go: extracting google.golang.org/api v0.5.0
go: extracting golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting github.com/gogo/protobuf v1.2.1
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: extracting github.com/mattn/go-colorable v0.1.1
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: extracting gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: extracting google.golang.org/grpc v1.22.0
go: extracting github.com/googleapis/gax-go/v2 v2.0.4
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: extracting github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/nats-io/nats.go v1.9.1
go: extracting github.com/hashicorp/vault/api v1.0.4
go: extracting github.com/minio/highwayhash v1.0.0
go: downloading gopkg.in/yaml.v2 v2.2.4
go: extracting gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/fatih/color v1.7.0
go: extracting github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: extracting github.com/nats-io/nats.go v1.9.1
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: extracting github.com/fatih/color v1.7.0
go: downloading github.com/klauspost/pgzip v1.2.1
go: extracting github.com/eclipse/paho.mqtt.golang v1.2.0
go: extracting gopkg.in/yaml.v2 v2.2.4
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: extracting github.com/mattn/go-isatty v0.0.7
go: downloading github.com/cheggaaa/pb v1.0.28
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: extracting github.com/klauspost/pgzip v1.2.1
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: extracting github.com/cheggaaa/pb v1.0.28
go: extracting github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: extracting github.com/minio/sio v0.2.0
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/klauspost/cpuid v1.2.2
go: extracting golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting github.com/secure-io/sio-go v0.3.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/hashicorp/vault/sdk v0.1.13
go: extracting github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/lib/pq v1.1.1
go: extracting golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/nats-io/jwt v0.3.2
go: extracting github.com/klauspost/cpuid v1.2.2
go: extracting github.com/lib/pq v1.1.1
go: downloading github.com/nats-io/nkeys v0.1.3
go: extracting github.com/nats-io/jwt v0.3.2
go: extracting github.com/nats-io [...]

2020-02-19 09:43 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#66258218-dc94-4659-894e-2c7ca87145b8) |
| mint-gateway-azure.sh | :x: [more...](#738f727f-59e6-4cc8-a4ae-9abee7a8bc61) |
<a name="66258218-dc94-4659-894e-2c7ca87145b8"></a>
### 9015-0c7304c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31647
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cdb6264d9f21:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-a32ouz0sgsi4bu",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120353,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31647/aws-sdk-go-test-a32ouz0sgsi4bu: dial tcp 72.28.97.55:31647: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="738f727f-59e6-4cc8-a4ae-9abee7a8bc61"></a>
### 9015-0c7304c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32550
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5fd7cef88375:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-q16530qeibny2l",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120275,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32550/aws-sdk-go-test-q16530qeibny2l: dial tcp 72.28.97.55:32550: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-20 03:48 UTC, harshavardhana commented
PTAL @kanagarajkm @Praveenrajmani

2020-02-20 10:17 UTC, kanagarajkm requested changes

2020-02-20 10:17 UTC, kanagarajkm commented on browser/app/js/browser/Login.js
> +                    authScopes={this.state.discoveryDoc.supported_scopes}
It should be `scopes_supported`.
Example configuration is here https://mk-dev1.auth0.com/.well-known/openid-configuration

2020-02-20 14:50 UTC, harshavardhana commented
Updated the PR PTAL @kanagarajkm @Praveenrajmani

2020-02-20 16:48 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#4c188579-af09-4007-84d6-7c48fc68c2bd) |
<a name="4c188579-af09-4007-84d6-7c48fc68c2bd"></a>
### 9015-5c129fa/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32628
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0835af919cc4:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 25 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 12 minutes and 58 seconds
(4/14) Running aws-sdk-ruby tests ... done in 45 seconds
(5/14) Running awscli tests ... done in 4 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 16 minutes and 24 seconds
(8/14) Running minio-dotnet tests ... done in 4 minutes and 18 seconds
(9/14) Running minio-go tests ... done in 37 minutes and 24 seconds
(10/14) Running minio-java tests ... FAILED in 25 minutes and 47 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 35134,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-2bc6kn3, objectName=minio-java-test-1pn6k2j, resource=/minio-java-test-2bc6kn3/minio-java-test-1pn6k2j, requestId=15F52A3DF021E5BC, hostId=21de49ee-b625-490e-ba06-d2893c6a1462)\nrequest={method=PUT, url=http://72.28.97.53:32628/minio-java-test-2bc6kn3/minio-java-test-1pn6k2j?uploadId=7a08bb0b59a595ba&partNumber=1, headers=x-amz-copy-source-if-match: 0978de27f84aed73a881e30c6b3d530f-2\nx-amz-copy-source: minio-java-test-2bc6kn3/minio-java-test-181mn74\nAccept-Encoding: identity\nHost: 72.28.97.53:32628\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200220T164809Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200220/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-20T14-46-14Z\nVary: Origin\nX-Amz-Request-Id: 15F52A3DF021E5BC\nX-Xss-Protection: 1; mode=block\nDate: Thu, 20 Feb 2020 16:48:10 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-20 18:23 UTC, Praveenrajmani approved these changes

2020-02-21 01:40 UTC, kanagarajkm approved these changes

2020-02-21 02:36 UTC, merged