cpu package fails to build on illumos
minio/minio pull request #9036
Opened 2020-02-24 19:44 UTC by KodyKantor

## Description
Building minio currently fails on illumos systems. One problem is that the `cpu` package fails to build. It appears the problem is that the `solaris` build target is missing for the `counter_other.go` file. Adding the solaris build target allows the cpu package to compile.

## Motivation and Context
On the current minio master branch:
```
$ go build
# github.com/minio/minio/pkg/cpu
pkg/cpu/cpu.go:105:22: undefined: newCounter
```

## How to test this PR?

minio still does not build on illumos without a few patches to minio's dependencies. After applying those patches (which are not to the minio/minio project's tree) and this patch, we can run a build on an illumos machine:
```
$ uname -a
SunOS rust.kkantor.com 5.11 joyent_20191122T201258Z i86pc i386 i86pc illumos
$ git branch --show-current
illumos_build
$ go build
$ echo $?
0
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-02-24 19:47 UTC, harshavardhana requested changes

2020-02-24 19:47 UTC, harshavardhana commented on pkg/cpu/counter_other.go
> +// +build darwin freebsd openbsd netbsd dragonfly windows solaris
Better yet add `// +build !linux` since this file is not implemented anyways

2020-02-24 19:47 UTC, harshavardhana requested changes

2020-02-24 19:47 UTC, harshavardhana commented on pkg/cpu/counter_other.go
>   * MinIO Cloud Storage, (C) 2019 MinIO, Inc.
Also please update the copyright to be 2019-2020

2020-02-24 20:32 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#1ed39f2c-2d9d-47f1-b0a0-912bc775cf45) |
<a name="1ed39f2c-2d9d-47f1-b0a0-912bc775cf45"></a>
### 9036-7a0a181/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:32751
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1dcbc50b8689:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 15 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... FAILED in 10 seconds
{
  "name": "awscli",
  "duration": 1521,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-24 23:10 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#81344574-131a-4cbc-b36c-3229638f9eea) |
| mint-gateway-azure.sh | :x: [more...](#84050f6e-e277-48f1-86a4-840a4396ebe4) |
<a name="84050f6e-e277-48f1-86a4-840a4396ebe4"></a>
### 9036-65260e2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32338
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e42f24026195:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 12 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 46 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 6 minutes and 34 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... FAILED in 15 minutes and 59 seconds
{
  "args": {
    "bucketName": "minio-go-test-q33znfh342tahht5",
    "objectName": "gxx6baxzipf59vm0tc5462llxwmtc5"
  },
  "duration": 102267,
  "error": "Get http://72.28.97.61:32338/minio-go-test-q33znfh342tahht5/gxx6baxzipf59vm0tc5462llxwmtc5: Connection closed by foreign host http://72.28.97.61:32338/minio-go-test-q33znfh342tahht5/gxx6baxzipf59vm0tc5462llxwmtc5. Retry again.",
  "function": "GetObject(bucketName, objectName)",
  "message": "ReadAt failed",
  "name": "minio-go: testGetObjectReadAtWhenEOFWasReached",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="81344574-131a-4cbc-b36c-3229638f9eea"></a>
### 9036-65260e2/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.52:31877
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 63ac241676ef:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 2 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 21 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 42 seconds
(8/14) Running minio-dotnet tests ... done in 38 seconds
(9/14) Running minio-go tests ... FAILED in 14 minutes and 21 seconds
{
  "args": {},
  "duration": 85962,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-25 03:03 UTC, harshavardhana approved these changes

2020-02-25 14:55 UTC, KodyKantor commented
Thank you for your review comments, @harshavardhana! Please do let me know who else I should ask to take a look at this change.

2020-02-25 18:57 UTC, kannappanr approved these changes

2020-02-25 18:58 UTC, merged