Skip building directio on platforms that don't support Direct IO
minio/minio pull request #9059
Opened 2020-02-27 22:14 UTC by KodyKantor

## Description
The minio server does not properly compile on illumos due to the inclusion of the `directio` package.

## Motivation and Context
illumos does not expose an O_DIRECT symbol under normal operation, and the illumos version of ZFS does not support O_DIRECT at this time. This causes the minio server build to fail since the `directio` package is always pulled in.

Rather than changing the upstream `directio` package to not send the O_DIRECT flag on platforms like illumos we should instead just abstract away the use of the `directio` package in minio. This results in `directio` only being pulled in on platforms that support it.

## How to test this PR?
I fixed the minio `cmd` test suite for illumos and ran the test suite on illumos and linux (debian) systems. I'll submit a PR for the illumos `cmd` test suite fixes once this PR lands.

I also did some basic smoke testing by uploading/downloading files to/from a local minio instance on illumos.

```
$ uname -a
SunOS rust.kkantor.com 5.11 joyent_20191122T201258Z i86pc i386 i86pc illumos

$ go test
PASS
ok      github.com/minio/minio/cmd      245.030s
```

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-02-27 23:20 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#98f0b875-d0a8-462f-b1b6-effad4b421ab) |
| mint-gateway-azure.sh | :x: [more...](#0acf398d-7c19-4e6a-8022-b250c96cb858) |
<a name="98f0b875-d0a8-462f-b1b6-effad4b421ab"></a>
### 9059-559bd6e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31363
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 893404c47b8a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2mfau61ikwktlb",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120358,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31363/aws-sdk-go-test-2mfau61ikwktlb: dial tcp 72.28.97.55:31363: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="0acf398d-7c19-4e6a-8022-b250c96cb858"></a>
### 9059-559bd6e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:30427
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 04cc4d78503c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 23 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 3 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 23 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 20 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 16 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11449,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3utcuth, objectName=minio-java-test-3kek9p, resource=/minio-java-test-3utcuth/minio-java-test-3kek9p, requestId=15F765AD5CB1069A, hostId=92e475c9-01ef-4efe-8e4b-13a9558643bb)\nrequest={method=PUT, url=http://72.28.97.58:30427/minio-java-test-3utcuth/minio-java-test-3kek9p?uploadId=6cb79b64b51e34a7&partNumber=1, headers=x-amz-copy-source-if-match: 1aaabc95c8d30451ba5379a0c9a8c9d9-2\nx-amz-copy-source: minio-java-test-3utcuth/minio-java-test-g5mthh\nAccept-Encoding: identity\nHost: 72.28.97.58:30427\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200227T231949Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200227/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-02-27T22-14-29Z\nVary: Origin\nX-Amz-Request-Id: 15F765AD5CB1069A\nX-Xss-Protection: 1; mode=block\nDate: Thu, 27 Feb 2020 23:19:49 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-02-28 04:32 UTC, harshavardhana commented
It is better to fix the upstream library here @KodyKantor to ignore illumos platform properly.

2020-02-28 14:44 UTC, KodyKantor commented
Hi @harshavardhana, thanks for taking a look.

Changing the `directio` package to not send the O_DIRECT flag when doing file operations on illumos is certainly another approach. I believe changing MinIO in the way described by this PR is a better approach, however.

When a user installs and uses the `directio` package they assume that they are doing DirectIO operations and that these operations have a little more durability than when not using DirectIO. If we change the `directio` package to silently ignore the request to do DirectIO then users may be frustrated when they encounter data loss on an illumos or solaris platform (when using MinIO or another storage system that uses the `directio` package). Refusing to build a package that provides DirectIO capabilities on illumos and solaris is the best approach to avoid this situation.

It's a better approach to have MinIO decide how best to store user data. Since we can't do DirectIO on illumos or solaris we need not attempt to build the `directio` package (which should always fail on these platforms to ensure programmers do not mistakenly use it).

Please let me know what you think about this.

2020-02-28 17:04 UTC, harshavardhana commented
> When a user installs and uses the `directio` package they assume that they are doing DirectIO operations and that these operations have a little more durability on Linux than when not using DirectIO. If we change the `directio` package to silently ignore the request to do DirectIO then users may be frustrated when they see files not being opened with an O_DIRECT flag on illumos or solaris platforms (when using MinIO or another storage system that uses the `directio` package). Refusing to build a package that provides DirectIO capabilities on illumos and solaris is the best approach to avoid this situation.

Correct that means that MinIO shouldn't run on illumos if we cannot guarantee O_DIRECT semantics. The point is disabling that essentially means that we are not guaranteeing our users on illumos their data is durable as it is on Linux. 

So I would suggest it is okay that MinIO erasure coding won't run on illumos platform, once illumos platform has O_DIRECT support we will happily work. Until that time it is not worth the effort supporting erasure coding on illumos, while short handling the durability guarantees.

2020-03-02 15:35 UTC, KodyKantor commented
Hi @harshavardhana.
> Correct that means that MinIO shouldn't run on illumos if we cannot guarantee O_DIRECT semantics. The point is disabling that essentially means that we are not guaranteeing our users on illumos their data is durable as it is on Linux.

The open(2) man page it states this about O_DIRECT:
> O_DIRECT (since Linux 2.4.10)
              Try to minimize cache effects of the I/O to and from this
              file.  In general this will degrade performance, but it is
              useful in special situations, such as when applications do
              their own caching.  File I/O is done directly to/from user-
              space buffers.  The O_DIRECT flag on its own makes an effort
              to transfer data synchronously, but does not give the
              guarantees of the O_SYNC flag that data and necessary metadata
              are transferred.  To guarantee synchronous I/O, O_SYNC must be
              used in addition to O_DIRECT.  See NOTES below for further
              discussion.

The `NOTES` section goes on to say
> In summary, O_DIRECT is a potentially powerful tool that should be
       used with caution.  It is recommended that applications treat use of
       O_DIRECT as a performance option which is disabled by default.

The O_DIRECT flag is foremost a performance flag, and does not offer durability guarantees. It simply means that IO buffers will not be copied into the kernel for use in the page cache as a potential performance optimization.

As noted in the man page the only way to guarantee (from an OS perspective) durable data storage is to do synchronous IO. MinIO already appears to do this for metadata, and I believe the MinIO devs also recommend using XFS with the `sync` mount option as another way to accomplish this.

Data stored on ZFS is guaranteed to be just as durable as it is on Linux with or without the O_DIRECT flag since O_DIRECT offers no durability guarantees. Further, ZFS effectively implements O_DIRECT semantics by default, which is why the `directio` library is not necessary.

If you would still prefer to have the upstream library modified I can surely submit that change to the author to have O_DIRECT not be sent to illumos. However I still believe this simple change uses the existing MinIO abstractions for platform support to accomplish our goal in a more clear and correct manner. Thank you for working with me on this initiative.

2020-03-06 23:13 UTC, harshavardhana commented
> The O_DIRECT flag is foremost a performance flag, and does not offer durability guarantees. It simply means that IO buffers will not be copied into the kernel for use in the page cache as a potential performance optimization.
> 
> As noted in the man page the only way to guarantee (from an OS perspective) durable data storage is to do synchronous IO. MinIO already appears to do this for metadata, and I believe the MinIO devs also recommend using XFS with the `sync` mount option as another way to accomplish this.
> 
> Data stored on ZFS is guaranteed to be just as durable as it is on Linux with or without the O_DIRECT flag since O_DIRECT offers no durability guarantees. Further, ZFS effectively implements O_DIRECT semantics by default, which is why the `directio` library is not necessary.
> 
> If you would still prefer to have the upstream library modified I can surely submit that change to the author to have O_DIRECT not be sent to illumos. However I still believe this simple change uses the existing MinIO abstractions for platform support to accomplish our goal in a more clear and correct manner. Thank you for working with me on this initiative.

That is definitely true - I am not trying to debate that - but O_DIRECT is a way to for us to avoid page-cache which allows us to hit the drives directly, not for performance reasons directly but it does help in performance for us on JBODs. 

`xl.json` is considered to be the source of truth that is why we avoid `fsync` for data parts but only do O_DIRECT anyways to avoid page-cache.

O_DIRECT allows us to be a good combination of durable `xl.json` and non-page cached items such that during the crash the I/O that is persisted on drives is not for some reason acknowledged by the kernel for being successfully written to disks.

So you are saying that ZFS guarantees all of that somehow, perhaps because llumos is not Linux and perhaps don't have the same requirements.

Can you make this a bit more explicit with a comment in the code? perhaps even point to the documentation where it says O_DIRECT is not needed?  Once this is done can you also fix the tests which are failing? @KodyKantor 

Thanks for the PR and bearing with our review process.

2020-03-09 23:57 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#8a937152-4601-4480-921b-c2a4c1dea270) |
| mint-gateway-azure.sh | :x: [more...](#27c74b3c-7ae6-44fb-bc57-4e09ce69ce5e) |
<a name="27c74b3c-7ae6-44fb-bc57-4e09ce69ce5e"></a>
### 9059-58c5248/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:30939
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 55c51311e22c:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 26 seconds
(4/14) Running aws-sdk-ruby tests ... done in 19 seconds
(5/14) Running awscli tests ... done in 3 minutes and 3 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 3 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 42 seconds
(9/14) Running minio-go tests ... done in 20 minutes and 49 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 32 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11203,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-17o6nvo, objectName=minio-java-test-3847uj2, resource=/minio-java-test-17o6nvo/minio-java-test-3847uj2, requestId=15FAC80ACA30355B, hostId=4d9f84e6-6130-49b6-99d6-74d38af00556)\nrequest={method=PUT, url=http://72.28.97.61:30939/minio-java-test-17o6nvo/minio-java-test-3847uj2?uploadId=7d397f4eeb4af1a8&partNumber=1, headers=x-amz-copy-source-if-match: 50bbf3a10d1384023b7d94bbbbdc9cc2-2\nx-amz-copy-source: minio-java-test-17o6nvo/minio-java-test-1g8ngbh\nAccept-Encoding: identity\nHost: 72.28.97.61:30939\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200309T235607Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200309/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-09T22-50-06Z\nVary: Origin\nX-Amz-Request-Id: 15FAC80ACA30355B\nX-Xss-Protection: 1; mode=block\nDate: Mon, 09 Mar 2020 23:56:07 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
<a name="8a937152-4601-4480-921b-c2a4c1dea270"></a>
### 9059-58c5248/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:32394
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b8a0ad617bea:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 6 seconds
(5/14) Running awscli tests ... done in 2 minutes and 20 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 48 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... FAILED in 19 minutes and 12 seconds
{
  "args": {},
  "duration": 75395,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataPutObject()",
  "message": "PutObject failed",
  "name": "minio-go: testStorageClassMetadataPutObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-10 01:07 UTC, harshavardhana approved these changes

2020-03-10 01:08 UTC, harshavardhana requested changes
```
Can you fix
$ diff -au <(gofmt -s -d pkg) <(printf "")
```

2020-03-10 14:33 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#6a1cfe81-ad6f-4c05-bbcb-47faaa2673d8) |
| mint-large-bucket.sh | :x: [more...](#7dbad059-b41a-42a2-8eee-d43921905cbe) |
| mint-gateway-azure.sh | :x: [more...](#04b1f5ac-8e99-41d4-bb86-b21edf93d55c) |
<a name="7dbad059-b41a-42a2-8eee-d43921905cbe"></a>
### 9059-74b28a5/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32459
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 29dfa807391a:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 3 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 47 seconds
(4/14) Running aws-sdk-ruby tests ... done in 5 seconds
(5/14) Running awscli tests ... done in 2 minutes and 17 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 46 seconds
(8/14) Running minio-dotnet tests ... done in 40 seconds
(9/14) Running minio-go tests ... FAILED in 15 minutes and 17 seconds
{
  "args": {},
  "duration": 119270,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 14 tests successfully.
```
<a name="04b1f5ac-8e99-41d4-bb86-b21edf93d55c"></a>
### 9059-74b28a5/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32376
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9514feb409ba:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-2puupmlw30zczw",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120255,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32376/aws-sdk-go-test-2puupmlw30zczw: dial tcp 72.28.97.55:32376: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="6a1cfe81-ad6f-4c05-bbcb-47faaa2673d8"></a>
### 9059-74b28a5/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31002
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b242378ab07f:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 6 minutes and 4 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-fltafal6ky0v3r",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 363956,
  "error": "XMinioServerNotInitialized: Server not initialized, please try again.\n\tstatus code: 503, request id: 15FAF710A8D90101, host id: ",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-10 15:59 UTC, harshavardhana approved these changes
Thanks for working with us. LGTM

2020-03-12 11:51 UTC, kannappanr commented on pkg/disk/directio_darwin.go
> + * Minio Cloud Storage, (C) 2020 Minio, Inc.
```suggestion
 * Minio Cloud Storage, (C) 2019-2020 Minio, Inc.
```

2020-03-12 11:52 UTC, kannappanr commented on pkg/disk/directio_unix.go
> + * Minio Cloud Storage, (C) 2020 Minio, Inc.
```suggestion
 * Minio Cloud Storage, (C) 2019-2020 Minio, Inc.
```

2020-03-12 11:52 UTC, kannappanr commented on pkg/disk/directio_unsupported.go
> + * Minio Cloud Storage, (C) 2020 Minio, Inc.
```suggestion
 * Minio Cloud Storage, (C) 2019-2020 Minio, Inc.
```

2020-03-12 19:22 UTC, KodyKantor commented
Thanks for reviewing! Should I rebase and squash this commit now?

2020-03-12 19:34 UTC, harshavardhana commented
yes please @KodyKantor

2020-03-12 20:58 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#d1cdfe81-ccf2-4f96-8668-406027f0e06c) |
| mint-gateway-azure.sh | :x: [more...](#f65ebcd0-a9c4-47bc-b5e4-7c7d455a7d3b) |
<a name="f65ebcd0-a9c4-47bc-b5e4-7c7d455a7d3b"></a>
### 9059-4b17ae9/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.58:31206
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 48af3f411bbe:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 25 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... FAILED in 51 seconds
{
  "name": "awscli",
  "duration": 1449,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 14 tests successfully.
```
<a name="d1cdfe81-ccf2-4f96-8668-406027f0e06c"></a>
### 9059-4b17ae9/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30345
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 69d33d83cc6b:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-3izvi40i6dq3je",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120344,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30345/aws-sdk-go-test-3izvi40i6dq3je: dial tcp 72.28.97.55:30345: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-13 01:14 UTC, kannappanr approved these changes

2020-03-13 01:24 UTC, kannappanr approved these changes
LGTM

2020-03-13 01:57 UTC, merged