xl: Fix counting offline disks in StorageInfo
minio/minio pull request #9082
Opened 2020-03-04 02:02 UTC by vadmeste

## Description
Recent modification in the code led to incorrect calculation
of offline disks.

This commit saves the endpoint list in a xlObjects then we know
the name of each disk.

## Motivation and Context
Fix counting offline disks when there is one or more offline nodes

## How to test this PR?
Run a cluster of multiple nodes where one node is down

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] Fixes a regression (https://github.com/minio/minio/commit/d4dcf1d7225a38ecf94abe7cbe7c69a93dc7c0b0)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-04 03:06 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#ba12bd27-f376-4a2e-9cb7-cae33050f2b9) |
<a name="ba12bd27-f376-4a2e-9cb7-cae33050f2b9"></a>
### 9082-15a6a90/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.56:31129
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp af6b3b49b030:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 27 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 6 minutes and 16 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/14) Running minio-go tests ... done in 19 minutes and 28 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 15 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11845,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-11mv5s0, objectName=minio-java-test-2gedmlg, resource=/minio-java-test-11mv5s0/minio-java-test-2gedmlg, requestId=15F8FAE8803FF99E, hostId=a7c41409-204e-4411-8341-a6988fd6e7ca)\nrequest={method=PUT, url=http://72.28.97.56:31129/minio-java-test-11mv5s0/minio-java-test-2gedmlg?uploadId=661755b10a05f26a&partNumber=1, headers=x-amz-copy-source-if-match: bc859953e1ea65a738ae5876af7ad2d1-2\nx-amz-copy-source: minio-java-test-11mv5s0/minio-java-test-3c28dvt\nAccept-Encoding: identity\nHost: 72.28.97.56:31129\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200304T030545Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200304/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-04T02-02-29Z\nVary: Origin\nX-Amz-Request-Id: 15F8FAE8803FF99E\nX-Xss-Protection: 1; mode=block\nDate: Wed, 04 Mar 2020 03:05:45 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-04 04:13 UTC, harshavardhana requested changes
Does this still work with stand-alone erasure coding..

2020-03-05 00:04 UTC, harshavardhana approved these changes

2020-03-05 00:10 UTC, vadmeste commented
> Does this still work with stand-alone erasure coding..

Number of disks online/offline is reported correctly. In case of standalone erasure, the peer address is empty, but mc is smart enough to show the address of the server (from the endpoint url)

I think it is okay for now

2020-03-05 00:18 UTC, kannappanr approved these changes
LGTM

2020-03-05 00:18 UTC, merged