Add option to disable data usage crawling
minio/minio pull request #9086
Opened 2020-03-04 20:55 UTC by kannappanr

## Description
Add option to disable data usage crawling

## Motivation and Context

## How to test this PR?
Use env variable `MINIO_DISK_USAGE_CRAWL` and set it's value to `off`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-04 21:15 UTC, poornas commented on cmd/data-usage.go
> +	if os.Getenv(dataUsageCrawlConf) == "off" {
@kannappanr , recommend using ParseBool here

2020-03-04 21:30 UTC, harshavardhana requested changes

2020-03-04 21:30 UTC, harshavardhana commented on cmd/data-usage.go
> +	if os.Getenv(dataUsageCrawlConf) == "off" {
Yes something like

```
        dataUsageEnabled, err = config.ParseBool(env.Get(dataUsageCrawlConf, config.EnableOn))
```

2020-03-04 22:34 UTC, kannappanr commented on cmd/data-usage.go
> +	if os.Getenv(dataUsageCrawlConf) == "off" {
done

2020-03-04 22:38 UTC, poornas approved these changes
LGTM

2020-03-04 23:05 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c845e330-534d-4c2e-9cb2-f14d3f437634) |
<a name="c845e330-534d-4c2e-9cb2-f14d3f437634"></a>
### 9086-de348f8/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.53:32171
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3d9462465740:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 32 seconds
(4/14) Running aws-sdk-ruby tests ... done in 17 seconds
(5/14) Running awscli tests ... done in 3 minutes and 26 seconds
(6/14) Running healthcheck tests ... done in 0 seconds
(7/14) Running mc tests ... done in 6 minutes and 41 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 43 seconds
(9/14) Running minio-go tests ... done in 19 minutes and 41 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 28 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 14284,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3acsp5v, objectName=minio-java-test-160gau, resource=/minio-java-test-3acsp5v/minio-java-test-160gau, requestId=15F93C6114028977, hostId=8dff45a8-3474-43b5-a04b-6fc73e556f8c)\nrequest={method=PUT, url=http://72.28.97.53:32171/minio-java-test-3acsp5v/minio-java-test-160gau?uploadId=71acb657f3213191&partNumber=1, headers=x-amz-copy-source-if-match: 15bda3dfe30f62c9706bd7851d8247e1-2\nx-amz-copy-source: minio-java-test-3acsp5v/minio-java-test-c1tvnk\nAccept-Encoding: identity\nHost: 72.28.97.53:32171\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200304T230531Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200304/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-04T22-01-20Z\nVary: Origin\nX-Amz-Request-Id: 15F93C6114028977\nX-Xss-Protection: 1; mode=block\nDate: Wed, 04 Mar 2020 23:05:31 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-04 23:08 UTC, harshavardhana approved these changes

2020-03-04 23:51 UTC, merged

2020-03-04 23:58 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#08b4a50a-d87f-4e73-b16b-1f14ba0fb46c) |
| mint-gateway-azure.sh | :x: [more...](#411f0a66-7bfb-4db0-8437-b2f812004b04) |
<a name="08b4a50a-d87f-4e73-b16b-1f14ba0fb46c"></a>
### 9086-d1dedc3/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:30240
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fc21f81c0fa5:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-r5zu1kh0u31i04",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120269,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:30240/aws-sdk-go-test-r5zu1kh0u31i04: dial tcp 72.28.97.55:30240: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="411f0a66-7bfb-4db0-8437-b2f812004b04"></a>
### 9086-d1dedc3/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31523
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0bd869790547:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-rxxxsfy194zecz",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120366,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31523/aws-sdk-go-test-rxxxsfy194zecz: dial tcp 72.28.97.55:31523: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-05 01:04 UTC, minio-ops commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-fs.sh | :x: [more...](#f701ce9d-1fc4-454c-a7ac-2eed330d4be0) |
| mint-gateway-azure.sh | :x: [more...](#bdcef707-263a-4ed8-80bf-50f2966432c8) |
<a name="f701ce9d-1fc4-454c-a7ac-2eed330d4be0"></a>
### 9086-3ea9fbd/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31432
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d255bdba5847:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-kl25bc21qewc1w",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120332,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31432/aws-sdk-go-test-kl25bc21qewc1w: dial tcp 72.28.97.55:31432: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="bdcef707-263a-4ed8-80bf-50f2966432c8"></a>
### 9086-3ea9fbd/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.61:32753
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2d6c311dd497:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 5 minutes and 52 seconds
(4/14) Running aws-sdk-ruby tests ... done in 19 seconds
(5/14) Running awscli tests ... done in 3 minutes and 27 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 6 minutes and 31 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/14) Running minio-go tests ... done in 20 minutes and 23 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 47 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11982,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3qhobog, objectName=minio-java-test-3hm57pj, resource=/minio-java-test-3qhobog/minio-java-test-3hm57pj, requestId=15F942D3123572FE, hostId=414a89fb-1a25-4d05-8e0a-25b5a0b97185)\nrequest={method=PUT, url=http://72.28.97.61:32753/minio-java-test-3qhobog/minio-java-test-3hm57pj?uploadId=56d6f41fd36895ba&partNumber=1, headers=x-amz-copy-source-if-match: 37206e71b64437011345648ee544af8a-2\nx-amz-copy-source: minio-java-test-3qhobog/minio-java-test-2245erh\nAccept-Encoding: identity\nHost: 72.28.97.61:32753\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200305T010338Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200305/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-04T23-58-24Z\nVary: Origin\nX-Amz-Request-Id: 15F942D3123572FE\nX-Xss-Protection: 1; mode=block\nDate: Thu, 05 Mar 2020 01:03:38 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally