heal: Avoid setting last heal activity when starting self healing
minio/minio pull request #9122
Opened 2020-03-11 22:16 UTC by vadmeste

## Description
This can be confusing to users thinking that the self healing
cycle was already performed.

## Motivation and Context
More clarity in the output of `mc admin heal alias`. Basically it returns the start time of the server which is not correct.

## How to test this PR?
`mc admin heal alias`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-11 22:30 UTC, harshavardhana requested changes
we should also enable when heal is intended to run @vadmeste

2020-03-11 23:02 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 9122-36f620d/gopath/src/github.com/minio
+ git -C 9122-36f620d/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9122-36f620d/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9122-36f620d/gopath/src/github.com/minio/minio fetch --quiet minio pull/9122/head:pr9122
+ git -C 9122-36f620d/gopath/src/github.com/minio/minio checkout --quiet pr9122
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/9122-36f620d/gopath
+ make -C 9122-36f620d/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/minio/minio-go/v6 v6.0.50-0.20200306231101-b882ba63d570
go: downloading github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: downloading github.com/ncw/directio v1.0.5
go: extracting github.com/ncw/directio v1.0.5
go: downloading github.com/secure-io/sio-go v0.3.0
go: extracting github.com/dustin/go-humanize v1.0.0
go: extracting github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: extracting github.com/minio/sha256-simd v0.1.1
go: extracting github.com/secure-io/sio-go v0.3.0
go: downloading github.com/gorilla/mux v1.7.0
go: downloading github.com/djherbis/atime v1.0.0
go: extracting github.com/minio/hdfs/v3 v3.0.1
go: extracting github.com/gorilla/mux v1.7.0
go: extracting github.com/djherbis/atime v1.0.0
go: extracting github.com/minio/minio-go/v6 v6.0.50-0.20200306231101-b882ba63d570
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/minio/cli v1.22.0
go: downloading github.com/gorilla/handlers v1.4.0
go: extracting github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: extracting github.com/gorilla/rpc v1.2.0
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading github.com/klauspost/compress v1.10.1
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/gorilla/handlers v1.4.0
go: downloading github.com/cheggaaa/pb v1.0.28
go: extracting github.com/cheggaaa/pb v1.0.28
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: extracting github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/gogo/protobuf v1.2.1
go: extracting golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: extracting golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: extracting github.com/coreos/etcd v3.3.12+incompatible
go: downloading github.com/shirou/gopsutil v2.18.12+incompatible
go: extracting github.com/shirou/gopsutil v2.18.12+incompatible
go: downloading gopkg.in/ldap.v3 v3.0.3
go: extracting gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/prometheus/common v0.2.0
go: downloading github.com/hashicorp/vault/api v1.0.4
go: extracting github.com/prometheus/common v0.2.0
go: extracting github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: extracting github.com/rjeczalik/notify v0.9.2
go: downloading github.com/minio/sio v0.2.0
go: extracting github.com/klauspost/reedsolomon v1.9.3
go: extracting github.com/minio/sio v0.2.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/miekg/dns v1.1.8
go: extracting github.com/hashicorp/vault/sdk v0.1.13
go: extracting github.com/miekg/dns v1.1.8
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading go.uber.org/atomic v1.3.2
go: extracting go.uber.org/atomic v1.3.2
go: extracting github.com/hashicorp/hcl v1.0.0
go: downloading github.com/mattn/go-runewidth v0.0.4
go: extracting github.com/mattn/go-runewidth v0.0.4
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: extracting github.com/mitchellh/go-homedir v1.1.0
go: downloading google.golang.org/grpc v1.22.0
go: extracting gopkg.in/square/go-jose.v2 v2.3.1
go: extracting google.golang.org/grpc v1.22.0
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: extracting github.com/klauspost/readahead v1.3.1
go: extracting github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading github.com/json-iterator/go v1.1.9
go: extracting github.com/json-iterator/go v1.1.9
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: extracting github.com/klauspost/compress v1.10.1
go: extracting github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: downloading github.com/hashicorp/errwrap v1.0.0
go: extracting github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/fatih/color v1.7.0
go: extracting github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: extracting google.golang.org/api v0.5.0
go: extracting github.com/fatih/color v1.7.0
go: downloading github.com/coredns/coredns v1.4.0
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: extracting google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: extracting github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: extracting github.com/coredns/coredns v1.4.0
go: downloading github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading cloud.google.com/go v0.39.0
go: extracting github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading gopkg.in/yaml.v2 v2.2.4
go: extracting golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: downloading github.com/rs/cors v1.6.0
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: extracting gopkg.in/yaml.v2 v2.2.4
go: downloading github.com/minio/parquet-go v0.0.0-20200125064549-a1e49702e174
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/mattn/go-colorable v0.1.1
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/golang/protobuf v1.3.2
go: extracting github.com/minio/parquet-go v0.0.0- [...]

2020-03-11 23:04 UTC, vadmeste commented
> we should also enable when heal is intended to run @vadmeste

Done

2020-03-11 23:40 UTC, harshavardhana approved these changes
Awesome thanks

2020-03-11 23:55 UTC, vadmeste commented
Found one issue, let's hold merging this for few minutes

2020-03-12 00:56 UTC, vadmeste commented
> Found one issue, let's hold merging this for few minutes

Done, issue fixed !

2020-03-12 01:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c1757b02-b974-4e7e-8d3c-924211ee7756) |
<a name="c1757b02-b974-4e7e-8d3c-924211ee7756"></a>
### 9122-9165f64/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:31683
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 70241300135d:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 13 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... done in 3 minutes and 8 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 6 minutes and 20 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/14) Running minio-go tests ... done in 20 minutes and 29 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 45 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11733,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3fks1am, objectName=minio-java-test-2e1qhqs, resource=/minio-java-test-3fks1am/minio-java-test-2e1qhqs, requestId=15FB698401189AAB, hostId=5e06ec52-6709-4eb4-b132-9617e11faa17)\nrequest={method=PUT, url=http://72.28.97.59:31683/minio-java-test-3fks1am/minio-java-test-2e1qhqs?uploadId=547e1a24b0120c3a&partNumber=1, headers=x-amz-copy-source-if-match: 1f8f8d6a4bf667305e3709b446681868-2\nx-amz-copy-source: minio-java-test-3fks1am/minio-java-test-2gm7nm9\nAccept-Encoding: identity\nHost: 72.28.97.59:31683\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200312T011509Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200312/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-12T00-15-13Z\nVary: Origin\nX-Amz-Request-Id: 15FB698401189AAB\nX-Xss-Protection: 1; mode=block\nDate: Thu, 12 Mar 2020 01:15:09 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-12 01:36 UTC, harshavardhana approved these changes

2020-03-12 02:57 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3b6e5902-b1cb-4491-af17-689776487765) |
| mint-gateway-azure.sh | :x: [more...](#98e9bb88-da1c-42e7-9444-c9a368762b09) |
<a name="3b6e5902-b1cb-4491-af17-689776487765"></a>
### 9122-9b3f2f2/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:31619
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9c3b11367061:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-bqhz0opid09x10",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120344,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:31619/aws-sdk-go-test-bqhz0opid09x10: dial tcp 72.28.97.55:31619: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="98e9bb88-da1c-42e7-9444-c9a368762b09"></a>
### 9122-9b3f2f2/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.57:31566
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4c98752cb8db:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 23 seconds
(4/14) Running aws-sdk-ruby tests ... done in 18 seconds
(5/14) Running awscli tests ... FAILED in 23 seconds
{
  "name": "awscli",
  "duration": 2073,
  "function": "aws --endpoint-url http://72.28.97.57:31566 s3api put-object --body /mint/data/datafile-0-b --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-0-b\n",
  "status": "FAIL",
  "error": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"
}

Executed 4 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-12 05:57 UTC, poornas approved these changes

2020-03-12 06:00 UTC, merged