admin: Change the type of backend description in server info
minio/minio pull request #9131
Opened 2020-03-13 01:37 UTC by vadmeste

## Description
It is hard for a library using madmin package to detect the type
of the backend in the response of Server Info admin API.

This commit cleary adds the type of the backend in the response.

## Motivation and Context
Simple enhancement in the code

## How to test this PR?
No testing

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-13 01:40 UTC, harshavardhana approved these changes
Thanks, awesome!

2020-03-13 01:41 UTC, harshavardhana requested changes
Do we need to update the admin API version number? to use this with older clients?

2020-03-13 02:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#c55b9fc6-941a-40fc-a988-ab7ffce9d455) |
| mint-gateway-azure.sh | :x: [more...](#08de36aa-2159-4f3f-b962-8b018ede6379) |
<a name="c55b9fc6-941a-40fc-a988-ab7ffce9d455"></a>
### 9131-b1f0453/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.55:32342
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b022f60dcc46:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... FAILED in 2 minutes and 0 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-mlktavzr0ol1op",
    "expiry": 60000000000,
    "objectName": "presignedTest"
  },
  "duration": 120335,
  "error": "RequestError: send request failed\ncaused by: Put http://72.28.97.55:32342/aws-sdk-go-test-mlktavzr0ol1op: dial tcp 72.28.97.55:32342: i/o timeout",
  "function": "PresignedPut",
  "message": "AWS SDK Go CreateBucket Failed",
  "name": "aws-sdk-go",
  "status": "FAIL"
}

Executed 0 out of 14 tests successfully.
```
<a name="08de36aa-2159-4f3f-b962-8b018ede6379"></a>
### 9131-b1f0453/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      72.28.97.59:30626
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2056daa7b178:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 9 seconds
(2/14) Running aws-sdk-java tests ... done in 1 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 24 seconds
(4/14) Running aws-sdk-ruby tests ... done in 20 seconds
(5/14) Running awscli tests ... done in 2 minutes and 32 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 6 minutes and 28 seconds
(8/14) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(9/14) Running minio-go tests ... done in 18 minutes and 44 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 27 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10897,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-2ohh82u, objectName=minio-java-test-113hor5, resource=/minio-java-test-2ohh82u/minio-java-test-113hor5, requestId=15FBBC741F421827, hostId=b2fecb79-1119-471c-b3ce-b9f214045d9d)\nrequest={method=PUT, url=http://72.28.97.59:30626/minio-java-test-2ohh82u/minio-java-test-113hor5?uploadId=2c9d926170f910d2&partNumber=1, headers=x-amz-copy-source-if-match: 3bc59cec0f93ca4823a7bd5df7044e8b-2\nx-amz-copy-source: minio-java-test-2ohh82u/minio-java-test-2edg2hb\nAccept-Encoding: identity\nHost: 72.28.97.59:30626\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200313T023500Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200313/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-13T01-37-17Z\nVary: Origin\nX-Amz-Request-Id: 15FBBC741F421827\nX-Xss-Protection: 1; mode=block\nDate: Fri, 13 Mar 2020 02:35:01 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-13 21:41 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#e178f2e5-6bc1-438b-bc2f-88656d23ebb8) |
<a name="e178f2e5-6bc1-438b-bc2f-88656d23ebb8"></a>
### 9131-7151c44/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:31923
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 02b5ef966c69:/mint/log /tmp/mint-logs'

(1/14) Running aws-sdk-go tests ... done in 8 seconds
(2/14) Running aws-sdk-java tests ... done in 2 seconds
(3/14) Running aws-sdk-php tests ... done in 6 minutes and 23 seconds
(4/14) Running aws-sdk-ruby tests ... done in 19 seconds
(5/14) Running awscli tests ... done in 3 minutes and 18 seconds
(6/14) Running healthcheck tests ... done in 1 seconds
(7/14) Running mc tests ... done in 6 minutes and 26 seconds
(8/14) Running minio-dotnet tests ... done in 2 minutes and 44 seconds
(9/14) Running minio-go tests ... done in 21 minutes and 40 seconds
(10/14) Running minio-java tests ... FAILED in 8 minutes and 24 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11601,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-87nieh, objectName=minio-java-test-2bbn467, resource=/minio-java-test-87nieh/minio-java-test-2bbn467, requestId=15FBFAF997D0E4BD, hostId=1e73d0c4-9d3f-4d3e-aef6-c7c27e4b0df5)\nrequest={method=PUT, url=http://minio-c4.minio.io:31923/minio-java-test-87nieh/minio-java-test-2bbn467?uploadId=b41c6d1f8400152d&partNumber=1, headers=x-amz-copy-source-if-match: b045c3e42e29dbaedc0080287e4c19ce-2\nx-amz-copy-source: minio-java-test-87nieh/minio-java-test-1jrspck\nAccept-Encoding: identity\nHost: minio-c4.minio.io:31923\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200313T214043Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200313/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-13T20-38-15Z\nVary: Origin\nX-Amz-Request-Id: 15FBFAF997D0E4BD\nX-Xss-Protection: 1; mode=block\nDate: Fri, 13 Mar 2020 21:40:44 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 14 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-14 00:12 UTC, harshavardhana requested changes
This PR is pending backward compatibility changes, which needs to be present to avoid breaking `mc`

2020-03-14 10:51 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#196edd27-c75e-4448-8fb1-e63b7a1cb411) |
<a name="196edd27-c75e-4448-8fb1-e63b7a1cb411"></a>
### 9131-f997662/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31228
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 81d33bf5c6b4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 34 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 40 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 55 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 44 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 24 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11139,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-30lcr6b, objectName=minio-java-test-1q7n51c, resource=/minio-java-test-30lcr6b/minio-java-test-1q7n51c, requestId=15FC261CF72CCE12, hostId=05f2c2f5-c210-4396-ae1e-7e2fb2b94377)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31228/minio-java-test-30lcr6b/minio-java-test-1q7n51c?uploadId=7859456e42517f2f&partNumber=1, headers=x-amz-copy-source-if-match: dab073df9eaa4b602cf7d9e6cf1f2511-2\nx-amz-copy-source: minio-java-test-30lcr6b/minio-java-test-o2b6a8\nAccept-Encoding: identity\nHost: minio-dev6.minio.io:31228\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200314T105114Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200314/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-14T09-49-07Z\nVary: Origin\nX-Amz-Request-Id: 15FC261CF72CCE12\nX-Xss-Protection: 1; mode=block\nDate: Sat, 14 Mar 2020 10:51:15 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-29 00:38 UTC, harshavardhana commented
@vadmeste will you able to address this? we can change this along with the change in policies where we break `mc` version, or keep backward compatibility for few releases.

2020-03-31 10:28 UTC, vadmeste commented
> we can change this along with the change in policies where we break `mc` version

If we are going to break, let's add this PR to the list of breaking change

2020-03-31 11:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#7d764a4a-4db6-4fc4-a1ab-548b4171992d) |
<a name="7d764a4a-4db6-4fc4-a1ab-548b4171992d"></a>
### 9131-0cdd7bb/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32078
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d7aef276e3f2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 8 minutes and 33 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 35 seconds
{
  "name": "awscli",
  "duration": 1677,
  "function": "make_bucket_with_lock\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-04-07 20:29 UTC, harshavardhana commented
We need to keep backward compatibility @vadmeste we shall take the `admin` policy PR first.

2020-04-22 23:15 UTC, harshavardhana commented
Will change this in Bucket versioning PR, lets close this out.

2020-04-22 23:15 UTC, closed without merging