Support multiple LDAP OU's, smAccountName support
minio/minio pull request #9139
Opened 2020-03-15 19:49 UTC by harshavardhana

## Description
Support multiple LDAP OU's, smAccountName support

## Motivation and Context
Fixes #8532 

## How to test this PR?
You need an LDAP server with multiple hierarchies.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [x] Documentation needed
- [x] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-15 20:50 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#4f77fd06-2cdc-45a6-83fe-3225a0be701d) |
<a name="4f77fd06-2cdc-45a6-83fe-3225a0be701d"></a>
### 9139-4f1a884/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31837
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp bf5c0b32258e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 52 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 9 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 17 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 1 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 4 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 19 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10989,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-371nile, objectName=minio-java-test-18s21q8, resource=/minio-java-test-371nile/minio-java-test-18s21q8, requestId=15FC9557A46B6CDA, hostId=d90d79c2-00e9-4587-a9dc-86f6fe26452e)\nrequest={method=PUT, url=http://minio-dev4.minio.io:31837/minio-java-test-371nile/minio-java-test-18s21q8?uploadId=063f98f90ff00385&partNumber=1, headers=x-amz-copy-source-if-match: 795e82b74ab23961164b1ceb54b867a5-2\nx-amz-copy-source: minio-java-test-371nile/minio-java-test-7rh339\nAccept-Encoding: identity\nHost: minio-dev4.minio.io:31837\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200315T204932Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200315/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-15T19-49-21Z\nVary: Origin\nX-Amz-Request-Id: 15FC9557A46B6CDA\nX-Xss-Protection: 1; mode=block\nDate: Sun, 15 Mar 2020 20:49:32 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-16 18:08 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#5ddbeae0-629e-42e6-ad45-fb24ac34ba94) |
<a name="5ddbeae0-629e-42e6-ad45-fb24ac34ba94"></a>
### 9139-1df2e8f/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30398
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fb971e8cd45a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 52 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 41 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 31 seconds
(9/15) Running minio-go tests ... done in 21 minutes and 14 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11758,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-skbofu, objectName=minio-java-test-3m7pd4m, resource=/minio-java-test-skbofu/minio-java-test-3m7pd4m, requestId=15FCDB19C8130E18, hostId=a9cdbbd6-e3ba-42e8-b6a4-67baac12c6a6)\nrequest={method=PUT, url=http://minio-dev4.minio.io:30398/minio-java-test-skbofu/minio-java-test-3m7pd4m?uploadId=ce90e22389aeb6c0&partNumber=1, headers=x-amz-copy-source-if-match: 74feb628f59fe52c70287bc7f5fe7570-2\nx-amz-copy-source: minio-java-test-skbofu/minio-java-test-3dbqctk\nAccept-Encoding: identity\nHost: minio-dev4.minio.io:30398\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200316T180752Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200316/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-16T17-05-27Z\nVary: Origin\nX-Amz-Request-Id: 15FCDB19C8130E18\nX-Xss-Protection: 1; mode=block\nDate: Mon, 16 Mar 2020 18:07:53 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-17 19:31 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#dd2b1136-f504-4a0e-9b34-5d770df4c05d) |
| mint-gateway-azure.sh | :x: [more...](#de7c8802-0b5e-430a-81f4-936ac9ec1bed) |
<a name="de7c8802-0b5e-430a-81f4-936ac9ec1bed"></a>
### 9139-caf384d/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30147
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6fa54a3673d8:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 17 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 44 seconds
{
  "name": "awscli",
  "duration": 1422,
  "function": "make_bucket_with_lock\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
<a name="dd2b1136-f504-4a0e-9b34-5d770df4c05d"></a>
### 9139-caf384d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31017
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8116c07007f7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 14 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 52 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 2 seconds
(9/15) Running minio-go tests ... FAILED in 12 minutes and 52 seconds
{
  "args": {},
  "duration": 104697,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:9139-caf384d

2020-03-18 03:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ce1fc12c-56dd-469c-b1b7-c9be175f242b) |
| mint-gateway-azure.sh | :x: [more...](#dca1766a-b673-4d1b-8edc-e0791ae19538) |
<a name="ce1fc12c-56dd-469c-b1b7-c9be175f242b"></a>
### 9139-681904d/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30559
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d2feeeb0a08a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 51 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 16 seconds
(9/15) Running minio-go tests ... FAILED in 14 minutes and 50 seconds
{
  "args": {},
  "duration": 109863,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 15 tests successfully.
```
<a name="dca1766a-b673-4d1b-8edc-e0791ae19538"></a>
### 9139-681904d/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31355
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2a203a218146:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 13 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 43 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 37 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 1 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 25 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11171,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3iiefv9, objectName=minio-java-test-2gi98ck, resource=/minio-java-test-3iiefv9/minio-java-test-2gi98ck, requestId=15FD4853181D2109, hostId=bf0de2da-0d38-4bac-a5a9-de5fd237428c)\nrequest={method=PUT, url=http://minio-c3.minio.io:31355/minio-java-test-3iiefv9/minio-java-test-2gi98ck?uploadId=1ac4297ece8c5f03&partNumber=1, headers=x-amz-copy-source-if-match: f95a16fe640c7eadbcd72beb535dad23-2\nx-amz-copy-source: minio-java-test-3iiefv9/minio-java-test-3nvt665\nAccept-Encoding: identity\nHost: minio-c3.minio.io:31355\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200318T032925Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200318/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-18T02-20-28Z\nVary: Origin\nX-Amz-Request-Id: 15FD4853181D2109\nX-Xss-Protection: 1; mode=block\nDate: Wed, 18 Mar 2020 03:29:25 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:9139-681904d

2020-03-20 06:37 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 9139-4869af4/gopath/src/github.com/minio
+ git -C 9139-4869af4/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9139-4869af4/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9139-4869af4/gopath/src/github.com/minio/minio fetch --quiet minio pull/9139/head:pr9139
+ git -C 9139-4869af4/gopath/src/github.com/minio/minio checkout --quiet pr9139
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/9139-4869af4/gopath
+ make -C 9139-4869af4/gopath/src/github.com/minio/minio --quiet
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/minio/minio-go/v6 v6.0.50-0.20200306231101-b882ba63d570
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/kurin/blazer v0.5.4-0.20190613185654-cf2f27cc0be3
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/shirou/gopsutil v2.18.12+incompatible
go: downloading github.com/klauspost/compress v1.10.3
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/json-iterator/go v1.1.9
go: downloading github.com/skyrings/skyring-common v0.0.0-20160929130248-d1c0bb1cbd5e
go: downloading github.com/gorilla/mux v1.7.0
go: downloading github.com/nats-io/stan.go v0.4.5
go: downloading github.com/rs/cors v1.6.0
go: downloading go.uber.org/atomic v1.3.2
go: downloading github.com/minio/lsync v1.0.1
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading github.com/nats-io/nats.go v1.9.1
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading golang.org/x/sys v0.0.0-20190922100055-0a153f010e69
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading google.golang.org/grpc v1.22.0
go: downloading github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/klauspost/cpuid v1.2.2
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/gorilla/handlers v1.4.0
go: downloading github.com/aliyun/aliyun-oss-go-sdk v0.0.0-20190307165228-86c17b95fcd5
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/fatih/structs v1.1.0
go: downloading gopkg.in/ini.v1 v1.48.0
go: downloading github.com/lib/pq v1.1.1
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: downloading github.com/klauspost/pgzip v1.2.1
go: downloading github.com/tinylib/msgp v1.1.1
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/cheggaaa/pb v1.0.28
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading github.com/nats-io/nkeys v0.1.3
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/beevik/ntp v0.2.0
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/prometheus/common v0.2.0
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/golang/snappy v0.0.1
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/miekg/dns v1.1.8
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading go.opencensus.io v0.21.0
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/minio/parquet-go v0.0.0-20200125064549-a1e49702e174
go: downloading gopkg.in/yaml.v2 v2.2.4
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading github.com/tidwall/match v1.0.1
# github.com/minio/minio/cmd/config/identity/ldap
cmd/config/identity/ldap/config.go:87:2: EnvServerInsecure redeclared in this block
	previous declaration at cmd/config/identity/ldap/config.go:80:28
make: *** [build] [...]

2020-03-20 07:20 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#9f659d7a-cc73-42b0-b42d-a5c2537b4e92) |
<a name="9f659d7a-cc73-42b0-b42d-a5c2537b4e92"></a>
### 9139-4f2f86c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31017
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 61569b2338da:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 57 seconds
{
  "name": "awscli",
  "duration": 1483,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-20 08:24 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#996964a6-24ae-488b-be6e-319f556ca209) |
<a name="996964a6-24ae-488b-be6e-319f556ca209"></a>
### 9139-ddb5f14/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32394
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cc239786ae66:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 13 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 3 minutes and 10 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 11 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 51 seconds
(9/15) Running minio-go tests ... done in 21 minutes and 46 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 54 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 16078,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-1dl4pd9, objectName=minio-java-test-177v4u6, resource=/minio-java-test-1dl4pd9/minio-java-test-177v4u6, requestId=15FDF58DF935243C, hostId=41ec70dd-63e7-409e-85df-2a679dd3894b)\nrequest={method=PUT, url=http://minio-dev6.minio.io:32394/minio-java-test-1dl4pd9/minio-java-test-177v4u6?uploadId=6c0e6dd5924d1d12&partNumber=1, headers=x-amz-copy-source-if-match: abc1e9eb5ccd882c8e543d7d18e775b0-2\nx-amz-copy-source: minio-java-test-1dl4pd9/minio-java-test-qvvkd2\nAccept-Encoding: identity\nHost: minio-dev6.minio.io:32394\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200320T082354Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200320/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 15FDF58DF935243C\nX-Xss-Protection: 1; mode=block\nDate: Fri, 20 Mar 2020 08:23:54 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-20 19:24 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#0a19e627-6987-4a01-ad08-b4a8541b90b3) |
<a name="0a19e627-6987-4a01-ad08-b4a8541b90b3"></a>
### 9139-55439fe/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32132
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3a51b5932fb2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 10 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 21 seconds
{
  "name": "awscli",
  "duration": 1462,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-22 02:18 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#27af409a-06f5-4e18-bb21-3b2ba5159eb2) |
<a name="27af409a-06f5-4e18-bb21-3b2ba5159eb2"></a>
### 9139-d99111a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31379
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ff95bf000e9c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 12 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 11 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 47 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 27 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11035,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-28krduv, objectName=minio-java-test-178jlh5, resource=/minio-java-test-28krduv/minio-java-test-178jlh5, requestId=15FE7EBE7F6C8146, hostId=6d5d0a5a-0e15-48ef-bb58-c59209dfa92c)\nrequest={method=PUT, url=http://minio-dev3.minio.io:31379/minio-java-test-28krduv/minio-java-test-178jlh5?uploadId=a886f26b63871cd2&partNumber=1, headers=x-amz-copy-source-if-match: ccab326830b1cde4813ccf906a8cc08c-2\nx-amz-copy-source: minio-java-test-28krduv/minio-java-test-1f3bsvf\nAccept-Encoding: identity\nHost: minio-dev3.minio.io:31379\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200322T021755Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200322/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 15FE7EBE7F6C8146\nX-Xss-Protection: 1; mode=block\nDate: Sun, 22 Mar 2020 02:17:55 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-22 03:04 UTC, nitisht requested changes
Tested, works fine. Thanks for the help in testing! Some documentation comments

2020-03-22 03:04 UTC, nitisht commented on cmd/config/identity/ldap/help.go
> +			Description: `";" separated list of username bind DNs e.g. "uid=%s,cn=accounts,dc=myldapserver,dc=com"`,
```suggestion
			Description: `"," separated list of username bind DNs e.g. "uid=%s,cn=accounts,dc=myldapserver,dc=com"`,
```

2020-03-22 03:04 UTC, nitisht commented on docs/sts/ldap.md
> +MINIO_IDENTITY_LDAP_USERNAME_FORMAT*         (list)      ";" separated list of username bind DNs e.g. "uid=%s,cn=accounts,dc=myldapserver,dc=com"
```suggestion
MINIO_IDENTITY_LDAP_USERNAME_FORMAT*         (list)      "," separated list of username bind DNs e.g. "uid=%s,cn=accounts,dc=myldapserver,dc=com"
```

2020-03-22 03:04 UTC, nitisht commented on docs/sts/ldap.md
> +MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN*    (list)      ";" sepatated list of group search base DNs e.g. "dc=myldapserver,dc=com"
```suggestion
MINIO_IDENTITY_LDAP_GROUP_SEARCH_BASE_DN*    (list)      "," separated list of group search base DNs e.g. "dc=myldapserver,dc=com"
```

2020-03-22 03:04 UTC, nitisht commented on docs/sts/ldap.md
> +MINIO_IDENTITY_LDAP_USERNAME_SEARCH_BASE_DN  (list)      ";" separated list of username search DNs
```suggestion
MINIO_IDENTITY_LDAP_USERNAME_SEARCH_BASE_DN  (list)      "," separated list of username search DNs
```

2020-03-22 03:04 UTC, nitisht commented on docs/sts/ldap.md
Markdown table is gone here, it renders strangely now

2020-03-22 03:04 UTC, nitisht commented on cmd/config/identity/ldap/help.go
> +			Description: `";" sepatated list of group search base DNs e.g. "dc=myldapserver,dc=com"`,
```suggestion
			Description: `"," separated list of group search base DNs e.g. "dc=myldapserver,dc=com"`,
```

2020-03-22 03:04 UTC, nitisht commented on cmd/config/identity/ldap/help.go
> +			Description: `";" separated list of username search DNs`,
```suggestion
			Description: `"," separated list of username search DNs`,
```

2020-03-22 03:11 UTC, nitisht approved these changes
LGTM

2020-03-22 04:18 UTC, harshavardhana commented
Thanks to @nitisht here is the gist on how to test https://gist.github.com/nitisht/47884f43bdf245531ef21376d21630e3

2020-03-22 04:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#b87f4f5e-697c-4899-b39f-73a653003130) |
<a name="b87f4f5e-697c-4899-b39f-73a653003130"></a>
### 9139-95836e5/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31809
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 90f987b6cff1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 33 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 2 minutes and 34 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 30 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 46 seconds
(9/15) Running minio-go tests ... done in 21 minutes and 8 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 32 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11572,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-1opjp2, objectName=minio-java-test-213mgiq, resource=/minio-java-test-1opjp2/minio-java-test-213mgiq, requestId=15FE86663C9F3BD5, hostId=62e82504-f0cb-49cc-8b4b-b4bbe99ad956)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31809/minio-java-test-1opjp2/minio-java-test-213mgiq?uploadId=b22e0904d3099493&partNumber=1, headers=x-amz-copy-source-if-match: fd9b0a4344944057d2db7f5f411098df-2\nx-amz-copy-source: minio-java-test-1opjp2/minio-java-test-180lbdr\nAccept-Encoding: identity\nHost: minio-dev7.minio.io:31809\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200322T043812Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200322/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 15FE86663C9F3BD5\nX-Xss-Protection: 1; mode=block\nDate: Sun, 22 Mar 2020 04:38:12 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-22 05:34 UTC, kannappanr approved these changes
LGTM

2020-03-22 05:47 UTC, merged