Add an option to allow plaintext connection to LDAP/AD Server
minio/minio pull request #9151
Opened 2020-03-17 07:55 UTC by nitisht

## Description
This PR adds an option to configure MinIO with LDAP/AD Server 
over plain text connection instead of TLS.

## Motivation and Context
This is needed to support an edge case where TLS may not be 
available with the LDAP Server. 

## How to test this PR?
Configure LDAP without TLS and try connection MinIO server with
the LDAP server as explained here 
https://github.com/minio/minio/blob/master/docs/sts/ldap.md

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-17 08:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c6b66850-de15-478e-a36b-f24efe51c48d) |
<a name="c6b66850-de15-478e-a36b-f24efe51c48d"></a>
### 9151-55ba113/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30699
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d200410a6808:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 27 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 2 minutes and 59 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 0 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 56 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 7 seconds
(10/15) Running minio-java tests ... FAILED in 7 minutes and 52 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10590,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3qdntoc, objectName=minio-java-test-396dcj0, resource=/minio-java-test-3qdntoc/minio-java-test-396dcj0, requestId=15FD0BBB06851E8F, hostId=b462b7c1-8d65-4ee7-b2fa-d3778cca950d)\nrequest={method=PUT, url=http://minio-dev3.minio.io:30699/minio-java-test-3qdntoc/minio-java-test-396dcj0?uploadId=4298e125bb779ba7&partNumber=1, headers=x-amz-copy-source-if-match: 39be2adf8ba8435f102440986c083ea9-2\nx-amz-copy-source: minio-java-test-3qdntoc/minio-java-test-2m2gdpb\nAccept-Encoding: identity\nHost: minio-dev3.minio.io:30699\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200317T085901Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200317/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-17T07-55-14Z\nVary: Origin\nX-Amz-Request-Id: 15FD0BBB06851E8F\nX-Xss-Protection: 1; mode=block\nDate: Tue, 17 Mar 2020 08:59:02 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-17 10:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#5f4e02eb-0dfa-4fa9-9881-11a91a6a33fe) |
<a name="5f4e02eb-0dfa-4fa9-9881-11a91a6a33fe"></a>
### 9151-49a4235/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:30510
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dca4a8024556:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... done in 2 minutes and 57 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 21 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 9 seconds
(9/15) Running minio-go tests ... done in 19 minutes and 54 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 31 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 13480,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-30qvsdh, objectName=minio-java-test-197f2ii, resource=/minio-java-test-30qvsdh/minio-java-test-197f2ii, requestId=15FD0FDFA048E3E2, hostId=d0c74de8-bf10-44d7-96cc-c51afcc1cef5)\nrequest={method=PUT, url=http://minio-c4.minio.io:30510/minio-java-test-30qvsdh/minio-java-test-197f2ii?uploadId=318dd0421c867e43&partNumber=1, headers=x-amz-copy-source-if-match: 5626100fabae5850bc8b414f3c4f3952-2\nx-amz-copy-source: minio-java-test-30qvsdh/minio-java-test-2t298kq\nAccept-Encoding: identity\nHost: minio-c4.minio.io:30510\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200317T101457Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200317/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-17T09-13-38Z\nVary: Origin\nX-Amz-Request-Id: 15FD0FDFA048E3E2\nX-Xss-Protection: 1; mode=block\nDate: Tue, 17 Mar 2020 10:14:57 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-17 12:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#a4af36b1-5ab8-4e67-a706-f5eee278825e) |
<a name="a4af36b1-5ab8-4e67-a706-f5eee278825e"></a>
### 9151-7366320/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30993
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c47b83728657:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 37 seconds
{
  "name": "awscli",
  "duration": 2142,
  "function": "aws --endpoint-url http://minio-c3.minio.io:30993 s3api put-object --body /mint/data/datafile-1-kB --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-1-kB\n",
  "status": "FAIL",
  "error": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-18 04:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#b0b90b03-7f03-4987-9213-b5a33509e70a) |
| mint-gateway-azure.sh | :x: [more...](#da53630c-a72e-4c7c-be08-52808c22f701) |
<a name="b0b90b03-7f03-4987-9213-b5a33509e70a"></a>
### 9151-e2f6ce1/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32451
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1da5b60e1d1e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 26 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 42 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 8 seconds
(9/15) Running minio-go tests ... FAILED in 14 minutes and 28 seconds
{
  "args": {},
  "duration": 108993,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 15 tests successfully.
```
<a name="da53630c-a72e-4c7c-be08-52808c22f701"></a>
### 9151-e2f6ce1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31604
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8dbb1142455f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 50 seconds
(4/15) Running aws-sdk-ruby tests ... done in 24 seconds
(5/15) Running awscli tests ... done in 2 minutes and 40 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 36 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 44 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 35 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 3 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10797,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3kav46i, objectName=minio-java-test-15ra46g, resource=/minio-java-test-3kav46i/minio-java-test-15ra46g, requestId=15FD4C1C591B21FD, hostId=7f5c5fc0-31cc-481f-ad43-4e2c90f50cf5)\nrequest={method=PUT, url=http://minio-c3.minio.io:31604/minio-java-test-3kav46i/minio-java-test-15ra46g?uploadId=33d5a94526422b34&partNumber=1, headers=x-amz-copy-source-if-match: 7f0019843b2d2c5bfe42f7b5f07c8732-2\nx-amz-copy-source: minio-java-test-3kav46i/minio-java-test-2pu1214\nAccept-Encoding: identity\nHost: minio-c3.minio.io:31604\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200318T043848Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200318/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-18T03-30-24Z\nVary: Origin\nX-Amz-Request-Id: 15FD4C1C591B21FD\nX-Xss-Protection: 1; mode=block\nDate: Wed, 18 Mar 2020 04:38:48 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:9151-e2f6ce1

2020-03-18 09:38 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#ae222561-c6e5-4e22-86d0-4b85af082c97) |
| mint-gateway-azure.sh | :x: [more...](#384d24c2-75e5-4f7f-b247-1ef8c7a27f9e) |
<a name="384d24c2-75e5-4f7f-b247-1ef8c7a27f9e"></a>
### 9151-630d5cb/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:32044
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 51153fc12263:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 55 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 14 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 34 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 20 seconds
(9/15) Running minio-go tests ... done in 21 minutes and 1 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 27 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11306,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-3ulqp9, objectName=minio-java-test-147b3uv, resource=/minio-java-test-3ulqp9/minio-java-test-147b3uv, requestId=15FD5C6EE927DEFB, hostId=447b0765-da95-4889-8513-36d0188b5f94)\nrequest={method=PUT, url=http://minio-dev4.minio.io:32044/minio-java-test-3ulqp9/minio-java-test-147b3uv?uploadId=8e7fd41ae1df8dac&partNumber=1, headers=x-amz-copy-source-if-match: 7f7357ac0fc26eecb0d589c29e349ea1-2\nx-amz-copy-source: minio-java-test-3ulqp9/minio-java-test-d00jes\nAccept-Encoding: identity\nHost: minio-dev4.minio.io:32044\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200318T093755Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200318/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-18T08-27-53Z\nVary: Origin\nX-Amz-Request-Id: 15FD5C6EE927DEFB\nX-Xss-Protection: 1; mode=block\nDate: Wed, 18 Mar 2020 09:37:55 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
<a name="ae222561-c6e5-4e22-86d0-4b85af082c97"></a>
### 9151-630d5cb/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31962
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f583300daf29:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 23 seconds
(6/15) Running healthcheck tests ... done in 5 seconds
(7/15) Running mc tests ... done in 51 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 17 seconds
(9/15) Running minio-go tests ... FAILED in 13 minutes and 55 seconds
{
  "args": {},
  "duration": 99810,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:9151-630d5cb

2020-03-18 10:21 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#55abd878-96ca-4c42-a0a7-adcf5750aff8) |
| mint-gateway-azure.sh | :x: [more...](#a0618702-63a8-4440-b7c7-9f4b44a41668) |
<a name="a0618702-63a8-4440-b7c7-9f4b44a41668"></a>
### 9151-bec9a86/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30001
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a310986a93e5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 57 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 45 seconds
{
  "name": "awscli",
  "duration": 1489,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
<a name="55abd878-96ca-4c42-a0a7-adcf5750aff8"></a>
### 9151-bec9a86/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32281
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 48ea21284bd5:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 25 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 45 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 24 seconds
(9/15) Running minio-go tests ... FAILED in 11 minutes and 44 seconds
{
  "args": {},
  "duration": 113779,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:9151-bec9a86

2020-03-18 22:50 UTC, harshavardhana requested changes

2020-03-18 22:50 UTC, harshavardhana commented on cmd/config/identity/ldap/config.go
> +	PlainTextConn      = "plain_text_connection"
key should match env name

2020-03-18 22:50 UTC, harshavardhana commented on cmd/config/identity/ldap/config.go
> +	EnvPlainTextConn      = "MINIO_IDENTITY_LDAP_SERVER_INSECURE"
can the variable name be same as env,

2020-03-19 02:06 UTC, nitisht commented on cmd/config/identity/ldap/config.go
> +	PlainTextConn      = "plain_text_connection"
done

2020-03-19 02:06 UTC, nitisht commented on cmd/config/identity/ldap/config.go
> +	EnvPlainTextConn      = "MINIO_IDENTITY_LDAP_SERVER_INSECURE"
done

2020-03-19 03:40 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#25c6cdf9-093c-4671-befa-001f8b3d5253) |
| mint-gateway-azure.sh | :x: [more...](#a6d873f7-ba78-4681-80c3-e8b72dfc15eb) |
<a name="a6d873f7-ba78-4681-80c3-e8b72dfc15eb"></a>
### 9151-1af2d7b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30694
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8f8df1378cce:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 50 seconds
{
  "name": "awscli",
  "duration": 1582,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
<a name="25c6cdf9-093c-4671-befa-001f8b3d5253"></a>
### 9151-1af2d7b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30848
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d05f2ec01c3f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 19 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 34 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 4 seconds
(9/15) Running minio-go tests ... done in 11 minutes and 16 seconds
(10/15) Running minio-java tests ... done in 58 seconds
(11/15) Running minio-js tests ... FAILED in 3 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 21,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-19 08:47 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#8ad30839-4b1b-4ea2-86a1-ccb400a7a97d) |
<a name="8ad30839-4b1b-4ea2-86a1-ccb400a7a97d"></a>
### 9151-f560a49/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30747
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 840f2002e67a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 50 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 1 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 5 minutes and 50 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 13 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 39 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 26 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10856,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-6ubagk, objectName=minio-java-test-1659jcs, resource=/minio-java-test-6ubagk/minio-java-test-1659jcs, requestId=15FDA8360BDF4958, hostId=66adf994-9eca-4577-b857-8b3cd7a5482f)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30747/minio-java-test-6ubagk/minio-java-test-1659jcs?uploadId=b7390a2f01c4f3cd&partNumber=1, headers=x-amz-copy-source-if-match: 26c3bf3887e78fc6bf412bac7c24b5e7-2\nx-amz-copy-source: minio-java-test-6ubagk/minio-java-test-9gith8\nAccept-Encoding: identity\nHost: minio-dev6.minio.io:30747\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200319T084633Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200319/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-19T07-46-05Z\nVary: Origin\nX-Amz-Request-Id: 15FDA8360BDF4958\nX-Xss-Protection: 1; mode=block\nDate: Thu, 19 Mar 2020 08:46:34 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-20 02:13 UTC, kannappanr approved these changes
LGTM

2020-03-20 02:20 UTC, harshavardhana approved these changes

2020-03-20 02:20 UTC, merged