heal: Pass all objects to XL healing to scan and heal
minio/minio pull request #9159
Opened 2020-03-18 15:36 UTC by vadmeste

## Description
XL zones decides if an object is worth passing to XL healing
if its quorum is equal to the number of disks of the corresponding
set.

However this fails with deep scan and probably other cases.

HealObject() scans and decides whether to heal a particular object
or not since there are many cases when an object needs healing,
such as, missing, empty, corrupted parts.

This commit fixes the behavior by sending all objects to healing
module even if objects has complete quorum on disks.

## Motivation and Context
Deep scan with mc does not heal corrupted parts

## How to test this PR?
1. Start from a fresh 4 disks
2. Upload an object
3. Corrupt a part in the backend
4. mc admin heal --scan=deep -r myminio/
5. Check if the part is fixed or not

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-18 16:48 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e221b6db-bc14-4a40-879e-3a39e5600469) |
| mint-gateway-azure.sh | :x: [more...](#0c302468-35b8-4ba5-a430-03f2d0fe0164) |
<a name="0c302468-35b8-4ba5-a430-03f2d0fe0164"></a>
### 9159-e250c04/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31810
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp e8c5a21b1259:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 6 minutes and 55 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 3 minutes and 14 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 33 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 39 seconds
(9/15) Running minio-go tests ... done in 21 minutes and 5 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 30 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 10952,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-8e6blq, objectName=minio-java-test-1ug78d5, resource=/minio-java-test-8e6blq/minio-java-test-1ug78d5, requestId=15FD73DD2E93D6CE, hostId=b4ab8c0e-2c1b-4b34-a370-b93662960676)\nrequest={method=PUT, url=http://minio-dev7.minio.io:31810/minio-java-test-8e6blq/minio-java-test-1ug78d5?uploadId=194172bccda044e6&partNumber=1, headers=x-amz-copy-source-if-match: fdfde20ad0260115057a25b9c618211f-2\nx-amz-copy-source: minio-java-test-8e6blq/minio-java-test-3e6kkb5\nAccept-Encoding: identity\nHost: minio-dev7.minio.io:31810\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200318T164717Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200318/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-03-18T15-37-11Z\nVary: Origin\nX-Amz-Request-Id: 15FD73DD2E93D6CE\nX-Xss-Protection: 1; mode=block\nDate: Wed, 18 Mar 2020 16:47:18 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
<a name="e221b6db-bc14-4a40-879e-3a39e5600469"></a>
### 9159-e250c04/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31223
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a2b9ac1d72a3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 24 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 11 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 5 seconds
(9/15) Running minio-go tests ... FAILED in 13 minutes and 59 seconds
{
  "args": {},
  "duration": 105131,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:9159-e250c04

2020-03-18 17:37 UTC, harshavardhana requested changes
This is not a good idea @vadmeste this makes the healing horribly slow. Quorum should be honored if it's a normal heal, only under deep scan we should heal all objects.

2020-03-18 23:01 UTC, vadmeste commented
> This is not a good idea @vadmeste this makes the healing horribly slow. Quorum should be honored if it's a normal heal, only under deep scan we should heal all objects.

Fixed, I did what you suggested @harshavardhana

2020-03-18 23:12 UTC, harshavardhana approved these changes

2020-03-19 00:34 UTC, poornas approved these changes
LGTM

2020-03-19 00:43 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#340ed362-3a97-460b-a556-e34a8a53e2ee) |
| mint-gateway-azure.sh | :x: [more...](#d45107f9-b41c-4d7c-94dd-d4bd9820c412) |
<a name="d45107f9-b41c-4d7c-94dd-d4bd9820c412"></a>
### 9159-f1b610a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30293
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 98e3ce023901:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 0 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... FAILED in 4 seconds
{
  "name": "awscli",
  "duration": 1480,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
<a name="340ed362-3a97-460b-a556-e34a8a53e2ee"></a>
### 9159-f1b610a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31030
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9e1ca18e06ff:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 46 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 25 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 58 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 41 seconds
(9/15) Running minio-go tests ... FAILED in 15 minutes and 13 seconds
{
  "args": {},
  "duration": 95018,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}

Executed 8 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally
Error: No such image: minio/minio:9159-f1b610a

2020-03-19 00:50 UTC, merged