lifecycle: Get returns the XML directly from the backend
minio/minio pull request #9201
Opened 2020-03-24 20:14 UTC by vadmeste

## Description
A response from MinIO server can make AWS SDK .net complain about the lifecycle format as described in https://github.com/minio/minio/issues/9147.

Instead of implementing a marshal custom XML and to avoid other similar issues in the future, this PR will just store the lifecycle xml document received from the client and store it in the backend as it is after validating it.

Getting the bucket lifecycle configuration will just read from the backend and sends it as it is to the client

## Motivation and Context
https://github.com/minio/minio/issues/9147

## How to test this PR?
See docs/lifecycle/*

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-24 21:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#f2447602-5017-4df6-9901-105e2292e69c) |
<a name="f2447602-5017-4df6-9901-105e2292e69c"></a>
### 9201-312b71b/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30820
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp dae3c5ad90c1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 32 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 27 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 48 seconds
(9/15) Running minio-go tests ... done in 22 minutes and 9 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 12214,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-149j1ia, objectName=minio-java-test-2s081nj, resource=/minio-java-test-149j1ia/minio-java-test-2s081nj, requestId=15FF5A2883413258, hostId=05731fe2-526d-4b4e-bdb0-c068eaf3a0db)\nrequest={method=PUT, url=http://minio-dev6.minio.io:30820/minio-java-test-149j1ia/minio-java-test-2s081nj?uploadId=227204caddb3f99b&partNumber=1, headers=x-amz-copy-source-if-match: f736438f314b0546c3a7ffb31cec9431-2\nx-amz-copy-source: minio-java-test-149j1ia/minio-java-test-eqmo3l\nAccept-Encoding: identity\nHost: minio-dev6.minio.io:30820\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200324T211843Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200324/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 15FF5A2883413258\nX-Xss-Protection: 1; mode=block\nDate: Tue, 24 Mar 2020 21:18:44 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-24 22:21 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#c02cadc3-08be-4324-b262-ab4f13601964) |
<a name="c02cadc3-08be-4324-b262-ab4f13601964"></a>
### 9201-1881390/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30979
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4214fbb832a3:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 35 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 2 minutes and 30 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 24 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 44 seconds
(9/15) Running minio-go tests ... done in 21 minutes and 27 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 40 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11862,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-26a3m6e, objectName=minio-java-test-3gof3u9, resource=/minio-java-test-26a3m6e/minio-java-test-3gof3u9, requestId=15FF5D9471E708AE, hostId=e5b59cfb-e40c-4637-b3c0-8d612e78f164)\nrequest={method=PUT, url=http://minio-dev7.minio.io:30979/minio-java-test-26a3m6e/minio-java-test-3gof3u9?uploadId=3883a3b98d02cbc3&partNumber=1, headers=x-amz-copy-source-if-match: ed664d120651f21a6a8f276776f104fa-2\nx-amz-copy-source: minio-java-test-26a3m6e/minio-java-test-e6e8rk\nAccept-Encoding: identity\nHost: minio-dev7.minio.io:30979\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200324T222126Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200324/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 410\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 15FF5D9471E708AE\nX-Xss-Protection: 1; mode=block\nDate: Tue, 24 Mar 2020 22:21:26 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-25 15:02 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :x: [more...](#d6fe0520-dae0-4ecb-993d-b4d6446443b6) |
| mint-gateway-azure.sh | :x: [more...](#718e8ac5-5989-45c4-a342-c36cb4a71560) |
<a name="d6fe0520-dae0-4ecb-993d-b4d6446443b6"></a>
### 9201-9f957de/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:30084
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1bbf1a922905:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 50 seconds
(8/15) Running minio-dotnet tests ... done in 35 seconds
(9/15) Running minio-go tests ... done in 10 minutes and 57 seconds
(10/15) Running minio-java tests ... done in 51 seconds
(11/15) Running minio-js tests ... FAILED in 13 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 5,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 10 out of 15 tests successfully.
```
<a name="718e8ac5-5989-45c4-a342-c36cb4a71560"></a>
### 9201-9f957de/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31837
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c2d554bcd9e4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 8 minutes and 1 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 6 seconds
{
  "name": "awscli",
  "duration": 1469,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-25 16:35 UTC, harshavardhana requested changes
I think the reason for sending lifecycle as a data structure to Object layer was to make sure that we can interpret or translate the meaning for other gateways such as azure/gcs and do an equivalent API translation if any.

The ideal fix would be to avoid changing this and instead fix the XML Marshal to generate the correct style needed.

2020-03-25 17:58 UTC, krisis commented
If we decide to use `pkg.Lifecycle` type to generate the XML response to the clients, we need to change `Filter` type as below,
```go
type Filter struct {
	XMLName xml.Name    `xml:"Filter"`
	Prefix  string      `xml:"Prefix,omitempty"`
	And     *And         `xml:"And,omitempty"`
	Tag     *tagging.Tag `xml:"Tag,omitempty"`
}
```
because,
> a field with a tag including the "omitempty" option is omitted
  if the field value is empty. The empty values are false, 0, any
  nil pointer or interface value, and any array, slice, map, or
  string of length zero.

2020-03-25 18:04 UTC, vadmeste commented
@krisis yeah, thanks.

There is another tip that I found in another projects:

```golang
type tag struct {
        XMLName xml.Name `xml:"Tag"`
        Key     string   `xml:"Key,omitempty"`
        Value   string   `xml:"Value,omitempty"`
}

// Tag - a tag for a lifecycle configuration Rule filter.
type Tag tag

// MarshalXML is extended to leave out <Tag></Tag> tags
func (t Tag) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
        if t.isEmpty() {
                return nil
        }
        # Casing from Tag to tag is needed to avoid infinite
        # recursive call of MarshalXML()
        return e.EncodeElement(tag(t), start)
} 
```

2020-03-25 19:29 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#b97476a8-fc0e-4a81-bdc8-c1cf5ce6c497) |
<a name="b97476a8-fc0e-4a81-bdc8-c1cf5ce6c497"></a>
### 9201-1b70362/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30103
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 65aa518b65c0:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 10 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 54 seconds
(4/15) Running aws-sdk-ruby tests ... done in 35 seconds
(5/15) Running awscli tests ... done in 3 minutes and 49 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 8 minutes and 29 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 2 seconds
(9/15) Running minio-go tests ... done in 27 minutes and 27 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11842,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-epn4f, objectName=minio-java-test-2gq4qrk, resource=/minio-java-test-epn4f/minio-java-test-2gq4qrk, requestId=15FFA2BE4167BA05, hostId=c59c5ba6-1cfe-43d0-97fa-73baface242f)\nrequest={method=PUT, url=http://minio-dev3.minio.io:30103/minio-java-test-epn4f/minio-java-test-2gq4qrk?uploadId=9ccc2518eaf198d9&partNumber=1, headers=x-amz-copy-source-if-match: 50c6d1321d6ebe400c837ecb87a7488f-2\nx-amz-copy-source: minio-java-test-epn4f/minio-java-test-3bensd1\nAccept-Encoding: identity\nHost: minio-dev3.minio.io:30103\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200325T192851Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200325/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 406\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 15FFA2BE4167BA05\nX-Xss-Protection: 1; mode=block\nDate: Wed, 25 Mar 2020 19:28:52 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-25 20:44 UTC, krisis approved these changes

2020-03-25 20:47 UTC, harshavardhana approved these changes
Nice LGTM

2020-03-25 20:48 UTC, harshavardhana commented
Can you also add `mint` tests for lifecycle configuration? @vadmeste

2020-03-25 20:51 UTC, vadmeste commented
> Can you also add `mint` tests for lifecycle configuration? @vadmeste

I will, but not for testing expiry feature because it is only executed each 24 hours. For that we need another kind of testing which can also help testing crawling/healing

2020-03-25 21:13 UTC, harshavardhana commented
What I meant is just API testing, not if expiry itself works which is another testing we need to add later.

2020-03-25 21:24 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#b4163870-a432-4585-930b-0ac1c6776a57) |
<a name="b4163870-a432-4585-930b-0ac1c6776a57"></a>
### 9201-3f45017/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30860
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 87d955b208a1:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 50 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... done in 3 minutes and 6 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 9 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 43 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 3 seconds
(10/15) Running minio-java tests ... FAILED in 8 minutes and 33 seconds
{
  "name": "minio-java",
  "function": "composeObject(String bucketName, String objectName,List<ComposeSource> composeSources, Map <String,String > headerMap, ServerSideEncryption sseTarget)",
  "args": "size: 6 MB & 6 MB",
  "duration": 11760,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code=NotImplemented, message=A header you provided implies functionality that is not implemented, bucketName=minio-java-test-uksek0, objectName=minio-java-test-26ge0eb, resource=/minio-java-test-uksek0/minio-java-test-26ge0eb, requestId=15FFA90338B0F8A0, hostId=23e9028b-4e76-41af-ae0c-7878911bf398)\nrequest={method=PUT, url=http://minio-dev7.minio.io:30860/minio-java-test-uksek0/minio-java-test-26ge0eb?uploadId=975976f4f0d4aa0c&partNumber=1, headers=x-amz-copy-source-if-match: ed49a1bd4dbce601cf1e9cedebfb39ea-2\nx-amz-copy-source: minio-java-test-uksek0/minio-java-test-ndoo5j\nAccept-Encoding: identity\nHost: minio-dev7.minio.io:30860\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200325T212345Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200325/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;host;x-amz-content-sha256;x-amz-copy-source;x-amz-copy-source-if-match;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=501, headers=Accept-Ranges: bytes\nContent-Length: 408\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 15FFA90338B0F8A0\nX-Xss-Protection: 1; mode=block\nDate: Wed, 25 Mar 2020 21:23:45 GMT\n}\n >>> [io.minio.MinioClient.executeReq(MinioClient.java:1220), io.minio.MinioClient.execute(MinioClient.java:1082), io.minio.MinioClient.executePut(MinioClient.java:1446), io.minio.MinioClient.executePut(MinioClient.java:1468), io.minio.MinioClient.uploadPartCopy(MinioClient.java:2619), io.minio.MinioClient.composeObject(MinioClient.java:2572), FunctionalTest.composeObject_test1(FunctionalTest.java:2587), FunctionalTest.runTests(FunctionalTest.java:3396), FunctionalTest.main(FunctionalTest.java:3514)]"
}

Executed 9 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-25 23:44 UTC, vadmeste commented
> Can you also add `mint` tests for lifecycle configuration? @vadmeste

Done !

2020-03-26 00:20 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#97c011ca-31a1-4921-aa0c-f7447273283b) |
<a name="97c011ca-31a1-4921-aa0c-f7447273283b"></a>
### 9201-93d48e1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30858
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 045e00787523:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 7 minutes and 54 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 3 seconds
{
  "name": "awscli",
  "duration": 1453,
  "function": "make_bucket\n",
  "status": "FAIL",
  "error": "An error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it."
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-26 00:53 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :x: [more...](#e2c1a482-14f7-48d9-a18d-4814a14650d3) |
| mint-gateway-azure.sh | :x: [more...](#c2681700-f647-42e4-a73d-cc3986d21cb8) |
<a name="c2681700-f647-42e4-a73d-cc3986d21cb8"></a>
### 9201-edbaa7e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30552
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c4045a4ea64b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 8 minutes and 1 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 1951,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:30552 s3api put-object --body /mint/data/datafile-1-kB --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-1-kB\n",
  "status": "FAIL",
  "error": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"
}

Executed 4 out of 15 tests successfully.
```
<a name="e2c1a482-14f7-48d9-a18d-4814a14650d3"></a>
### 9201-edbaa7e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:30110
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7d759a3cddc2:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 3 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 1 seconds
PHP Fatal error:  Uncaught exception 'Aws\S3\Exception\S3Exception' with message 'Error executing "DeleteObject" on "http://minio-c4.minio.io:30110/aws-sdk-php-5e7bf850c691b/obj1"; AWS HTTP error: Server error: `DELETE http://minio-c4.minio.io:30110/aws-sdk-php-5e7bf850c691b/obj1` resulted in a `503 Service Unavailable` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, pl (truncated...)
 XMinioServerNotInitialized (server): Server not initialized, please try again. - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>XMinioServerNotInitialized</Code><Message>Server not initialized, please try again.</Message><Key>obj1</Key><BucketName>aws-sdk-php-5e7bf850c691b</BucketName><Resource>/aws-sdk-php-5e7bf850c691b/obj1</Resource><RequestId>15FFB35BFE85CB4F</RequestId><HostId>e22e4a4d-11e0-4c81-9684-521ea45f0367</HostId></Error>'

GuzzleHttp\Exception\ServerException: Server error: `PUT http://minio-c4.minio.io:30110/aws-sdk-php-5e7bf850c691b` resulted in  in /mint/run/core/aws-sdk-php/vendor/aws/aws-sdk-php/src/WrappedHttpHandler.php on line 195

Executed 2 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-26 01:26 UTC, harshavardhana approved these changes

2020-03-26 04:06 UTC, merged