localized jstream library and fix for incompatible behaviors
minio/minio pull request #9218
Opened 2020-03-27 12:30 UTC by ebozduman

## Description
`mc sql -e="SELECT ...` command for files in `json` and/or in `gz` or `bz2` formats behave differently than amazon s3 version. The error messages thrown was not helpful and incompatible with the s3 counterparts in certain conditions like incorrect `.gz` and `.bz2` files and etc.
Also localized the jstream library.
## Motivation and Context
We need to be compatible with Amazon s3.

## How to test this PR?
Run the following commands with correct and incorrect formatted json, gzipped json and bzip2'ed json files and make sure MinIO AND s3 results match.

```
- mc sql -e="SELECT * from s3object LIMIT 1" --json-input type="document" myminio/test/incorrect.bz2
- mc sql -e="SELECT * from s3object LIMIT 1" --json-input type="document" s3/test/incorrect.bz2
```
## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-03-27 13:11 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#d10d583d-6b79-4c33-aa24-e865a2c6f5f5) |
<a name="d10d583d-6b79-4c33-aa24-e865a2c6f5f5"></a>
### 9218-7fa9018/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32023
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d69b00584b7e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 8 minutes and 13 seconds
(4/15) Running aws-sdk-ruby tests ... done in 20 seconds
(5/15) Running awscli tests ... FAILED in 31 seconds
{
  "name": "awscli",
  "duration": 2126,
  "function": "aws --endpoint-url http://minio-dev6.minio.io:32023 s3api put-object --body /mint/data/datafile-1-kB --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key datafile-1-kB\n",
  "status": "FAIL",
  "error": "usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]To see help text, you can run:  aws help  aws <command> help  aws <command> <subcommand> helpUnknown options: occurred, (BucketAlreadyOwnedByYou), when, calling, the, CreateBucket, operation:, Your, previous, request, to, create, the, named, bucket, succeeded, and, you, already, own, it., error"
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-03-27 17:57 UTC, harshavardhana requested changes
Add a NOTICE file in jstream directory about why we forked and what this fork has @ebozduman

2020-03-27 22:28 UTC, kannappanr commented
@ebozduman PTAL build failures

2020-03-28 23:43 UTC, harshavardhana commented
No need for this fork @ebozduman , please check the latest communication with jstream maintainer

2020-05-14 19:06 UTC, harshavardhana commented
Lets close this PR @ebozduman please resubmit when you have fixed and found time to rebase this with master.

2020-05-14 19:06 UTC, closed without merging