Add SHA-3 support
minio/minio pull request #9308
Opened 2020-04-09 15:15 UTC by Lopastvertoleta

## Description
This merge request adds SHA3 support for JWT validation

## Motivation and Context
We only use SHA3 in our company for security reasons and would like to use minio as our object storage solution, but unfortunately it doesn't support SHA3, so the solution was to fork the repo, add SHA3 support and send the PR

## How to test this PR?
Generate a JWT with RSA-SHA3 or ECDSA-SHA3 and try to use any minio client.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [*] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-04-09 16:18 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#1bcf295b-3b19-41a5-8947-889b520d08f4) |
| mint-large-bucket.sh | :x: [more...](#a89782c0-96f5-4fd6-b1f6-4122221e5fc3) |
| mint-fs.sh | :x: [more...](#ace684c8-3e59-4e42-9263-a72a000074b2) |
| mint-dist-xl.sh | :x: [more...](#3db6b966-6862-4950-989d-abed10ee3a79) |
| mint-gateway-azure.sh | :x: [more...](#352dc57a-56c4-4af5-9d9a-7491c3e63fff) |
| mint-gateway-nas.sh | :x: [more...](#64e2e163-3470-409d-900c-cbe2ce7d1145) |
<a name="352dc57a-56c4-4af5-9d9a-7491c3e63fff"></a>
### 9308-7730c13/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31689
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 933c731e557e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 9 minutes and 38 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 3 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 7 minutes and 13 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 43 seconds
(9/15) Running minio-go tests ... done in 20 minutes and 15 seconds
(10/15) Running minio-java tests ... FAILED in 53 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName)",
  "duration": 4449,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=StorageClass, data=false, type=void, required=true) on field 'storageClass' private java.lang.String io.minio.messages.Item.storageClass in class io.minio.messages.Item at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioClient.listObjectsV2(MinioClient.java:3018), io.minio.MinioClient.access$100(MinioClient.java:152), io.minio.MinioClient$2$1.populate(MinioClient.java:2879), io.minio.MinioClient$2$1.hasNext(MinioClient.java:2910), FunctionalTest.listObject_test1(FunctionalTest.java:1436), FunctionalTest.runTests(FunctionalTest.java:3817), FunctionalTest.main(FunctionalTest.java:3963)]"
}

Executed 9 out of 15 tests successfully.
```
<a name="ace684c8-3e59-4e42-9263-a72a000074b2"></a>
### 9308-7730c13/mint-fs.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30263
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 270dfdde9993:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 2 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 33 seconds
(8/15) Running minio-dotnet tests ... done in 31 seconds
(9/15) Running minio-go tests ... done in 12 minutes and 18 seconds
(10/15) Running minio-java tests ... done in 27 seconds
(11/15) Running minio-js tests ... done in 41 seconds
(12/15) Running minio-py tests ... done in 58 seconds
(13/15) Running s3cmd tests ... done in 14 seconds
(14/15) Running s3select tests ... FAILED in 1 seconds
{
  "function": "select_object_content(bucket_name, object_name, opts)",
  "name": "minio-py:test_csv_input_quote_char",
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 180, in test_csv_input_custom_quote_char\n    raise ValueError('Test {}: data mismatch. Expected : {}, Received {}'.format(idx+1, expected_output, got_output))\nValueError: Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./tests.py\", line 310, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"./tests.py\", line 183, in test_csv_input_custom_quote_char\n    raise Exception(err)\nException: Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'\n",
  "args": {
    "bucket_name": "s3select-test-101d6c13-77aa-4c61-9c61-cdf197acbe5f",
    "object_name": "00b28151-8e0d-401b-8b3f-b3b27585ffee"
  },
  "status": "FAIL",
  "duration": 326,
  "message": "Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'"
}

Executed 13 out of 15 tests successfully.
```
<a name="64e2e163-3470-409d-900c-cbe2ce7d1145"></a>
### 9308-7730c13/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30024
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5a45a395ec9b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 0 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 32 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... done in 10 minutes and 49 seconds
(10/15) Running minio-java tests ... done in 19 seconds
(11/15) Running minio-js tests ... done in 30 seconds
(12/15) Running minio-py tests ... done in 57 seconds
(13/15) Running s3cmd tests ... done in 15 seconds
(14/15) Running s3select tests ... FAILED in 0 seconds
{
  "args": {
    "bucket_name": "s3select-test-0c9f66a3-97e7-44f8-a62c-1f621aec03a4",
    "object_name": "25ec1f8b-2650-4585-805e-0004d01aae90"
  },
  "status": "FAIL",
  "message": "Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'",
  "function": "select_object_content(bucket_name, object_name, opts)",
  "name": "minio-py:test_csv_input_quote_char",
  "duration": 263,
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 180, in test_csv_input_custom_quote_char\n    raise ValueError('Test {}: data mismatch. Expected : {}, Received {}'.format(idx+1, expected_output, got_output))\nValueError: Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./tests.py\", line 310, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"./tests.py\", line 183, in test_csv_input_custom_quote_char\n    raise Exception(err)\nException: Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'\n"
}

Executed 13 out of 15 tests successfully.
```
<a name="1bcf295b-3b19-41a5-8947-889b520d08f4"></a>
### 9308-7730c13/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30977
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 755d5460abf4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tes [...]

2020-04-09 17:11 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-worm.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#8761870a-cd89-4523-a669-c1a742add2f8) |
| mint-large-bucket.sh | :x: [more...](#fbb35bad-f499-4422-bee3-35dd32572d11) |
| mint-fs.sh | :x: [more...](#4e1517b5-d081-49e2-85eb-337343fd3dfc) |
| mint-dist-xl.sh | :x: [more...](#85c7f09e-0ada-4ba8-82c5-22c4904a2405) |
| mint-gateway-azure.sh | :x: [more...](#fed5a5e1-2f51-496e-8d1f-28d4d3642a38) |
| mint-gateway-nas.sh | :x: [more...](#73b69fdc-cb0d-41eb-a702-c01507ba38d3) |
<a name="fed5a5e1-2f51-496e-8d1f-28d4d3642a38"></a>
### 9308-be743f7/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32275
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8fee0142c1ad:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 10 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 10 minutes and 6 seconds
(4/15) Running aws-sdk-ruby tests ... done in 19 seconds
(5/15) Running awscli tests ... done in 2 minutes and 36 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 6 minutes and 35 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 45 seconds
(9/15) Running minio-go tests ... done in 22 minutes and 36 seconds
(10/15) Running minio-java tests ... FAILED in 1 minutes and 0 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName)",
  "duration": 4426,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Empty value for @org.simpleframework.xml.Element(name=StorageClass, data=false, type=void, required=true) on field 'storageClass' private java.lang.String io.minio.messages.Item.storageClass in class io.minio.messages.Item at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:55), io.minio.MinioClient.listObjectsV2(MinioClient.java:3018), io.minio.MinioClient.access$100(MinioClient.java:152), io.minio.MinioClient$2$1.populate(MinioClient.java:2879), io.minio.MinioClient$2$1.hasNext(MinioClient.java:2910), FunctionalTest.listObject_test1(FunctionalTest.java:1436), FunctionalTest.runTests(FunctionalTest.java:3817), FunctionalTest.main(FunctionalTest.java:3963)]"
}

Executed 9 out of 15 tests successfully.
```
<a name="73b69fdc-cb0d-41eb-a702-c01507ba38d3"></a>
### 9308-be743f7/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:30181
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4b2af81715fc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 0 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 19 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... done in 9 minutes and 31 seconds
(10/15) Running minio-java tests ... done in 21 seconds
(11/15) Running minio-js tests ... done in 31 seconds
(12/15) Running minio-py tests ... done in 56 seconds
(13/15) Running s3cmd tests ... done in 15 seconds
(14/15) Running s3select tests ... FAILED in 1 seconds
{
  "args": {
    "bucket_name": "s3select-test-16cc8e80-5959-4e4d-bf68-2bb6cfde39c8",
    "object_name": "2ac9cd68-d144-4c21-a631-d342915f148b"
  },
  "message": "Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'",
  "name": "minio-py:test_csv_input_quote_char",
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 180, in test_csv_input_custom_quote_char\n    raise ValueError('Test {}: data mismatch. Expected : {}, Received {}'.format(idx+1, expected_output, got_output))\nValueError: Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./tests.py\", line 310, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"./tests.py\", line 183, in test_csv_input_custom_quote_char\n    raise Exception(err)\nException: Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'\n",
  "status": "FAIL",
  "duration": 277,
  "function": "select_object_content(bucket_name, object_name, opts)"
}

Executed 13 out of 15 tests successfully.
```
<a name="fbb35bad-f499-4422-bee3-35dd32572d11"></a>
### 9308-be743f7/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30649
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 86b6cc5b8f44:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 6 seconds
(5/15) Running awscli tests ... done in 2 minutes and 24 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 41 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 8 seconds
(9/15) Running minio-go tests ... done in 13 minutes and 20 seconds
(10/15) Running minio-java tests ... done in 12 minutes and 16 seconds
(11/15) Running minio-js tests ... done in 55 seconds
(12/15) Running minio-py tests ... done in 7 minutes and 20 seconds
(13/15) Running s3cmd tests ... done in 38 seconds
(14/15) Running s3select tests ... FAILED in 7 seconds
{
  "error": "Traceback (most recent call last):\n  File \"./tests.py\", line 180, in test_csv_input_custom_quote_char\n    raise ValueError('Test {}: data mismatch. Expected : {}, Received {}'.format(idx+1, expected_output, got_output))\nValueError: Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"./tests.py\", line 310, in main\n    test_csv_input_custom_quote_char(client, log_output)\n  File \"./tests.py\", line 183, in test_csv_input_custom_quote_char\n    raise Exception(err)\nException: Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'\n",
  "args": {
    "object_name": "96351c22-886a-43cf-a6ed-3fba28683bef",
    "bucket_name": "s3select-test-8b14e555-1716-4093-b3b9-886b24209e87"
  },
  "message": "Test 14: data mismatch. Expected : b'{\"_1\":\"AB\",\"_2\":\"CD\"}\\n', Received b'{\"_1\":\"A\\\\\\\\B\",\"_2\":\"CD\"}\\n'",
  "name": "minio-py:test_csv_input_quote_char",
  "function": "select_object_content(bucket_name, object_name, opts)",
  "status": "FAIL",
  "duration": 6537
}

Executed 13 out of 15 tests successfully.
```
<a name="85c7f09e-0ada-4ba8-82c5-22c4904a2405"></a>
### 9308-be743f7/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31907
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker  [...]

2020-04-09 18:15 UTC, Lopastvertoleta commented
@harshavardhana could you tell me what can I do to fix these errors? Or should I fix them at all?

2020-04-09 18:18 UTC, harshavardhana commented
> @harshavardhana could you tell me what can I do to fix these errors? Or should I fix them at all?

Always send PR with the master branch as base, which is why you see these errors.

2020-04-09 18:20 UTC, Lopastvertoleta commented
Sorry, I thought I did :/

2020-04-09 19:35 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#1dfa3596-ddba-41a4-94b9-f47fd1c9c04e) |
<a name="1dfa3596-ddba-41a4-94b9-f47fd1c9c04e"></a>
### 9308-efd8386/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c4.minio.io:32368
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2ac7c389e5f7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 10 minutes and 0 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 6 minutes and 35 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/15) Running minio-go tests ... done in 17 minutes and 49 seconds
(10/15) Running minio-java tests ... done in 26 minutes and 37 seconds
(11/15) Running minio-js tests ... FAILED in 3 minutes and 59 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-528d50ad-a2a1-4b02-9a95-ee3874bb4629, recursive:true",
  "duration": 214,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}

Executed 10 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-04-09 20:51 UTC, harshavardhana requested changes

2020-04-09 20:51 UTC, harshavardhana commented on pkg/jwt/ecdsa-sha3.go
> +package jwt
Please copyright to MinIO @Lopastvertoleta

2020-04-09 20:51 UTC, harshavardhana commented on pkg/jwt/rsa-sha3.go
> +package jwt
add copy right to MinIO @Lopastvertoleta

2020-04-09 20:51 UTC, harshavardhana commented on pkg/jwt/ecdsa-sha3.go
> +import (
Please don't add a new package called `pkg/jwt` move this code directly into `cmd/config/identity/openid/jwt`

2020-04-10 07:15 UTC, harshavardhana approved these changes

2020-04-10 08:09 UTC, Lopastvertoleta commented
@kannappanr could you review the pull request?

2020-04-10 08:13 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-worm.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#77a5ec93-c2db-4ae1-b1c7-800e7cfe266e) |
<a name="77a5ec93-c2db-4ae1-b1c7-800e7cfe266e"></a>
### 9308-50c7de1/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30670
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9ab7fff915ec:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 9 minutes and 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 18 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 1 seconds
{
  "name": "awscli",
  "duration": 1991,
  "function": "aws --endpoint-url http://minio-dev4.minio.io:30670 s3api create-multipart-upload --bucket \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it. --key \nAn error occurred (BucketAlreadyOwnedByYou) when calling the CreateBucket operation: Your previous request to create the named bucket succeeded and you already own it.-object\n",
  "status": "FAIL",
  "error": ""
}

Executed 4 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-04-10 19:06 UTC, aead reviewed
Apart from the really minor comment LGTM - thanks @Lopastvertoleta

2020-04-10 19:06 UTC, aead commented on cmd/config/identity/openid/ecdsa-sha3.go
> +	// Needed for SHA3 to work
```suggestion
	// Needed for SHA3 to work - See: https://golang.org/src/crypto/crypto.go?s=1034:1288
```

2020-04-10 19:06 UTC, aead commented on cmd/config/identity/openid/rsa-sha3.go
> +	// Needed for SHA3 to work
```suggestion
	// Needed for SHA3 to work - See: https://golang.org/src/crypto/crypto.go?s=1034:1288
```

2020-04-10 19:13 UTC, Lopastvertoleta commented
> Apart from the really minor comment LGTM - thanks @Lopastvertoleta

Thank you for the review, I've committed your suggestions

2020-04-10 19:17 UTC, aead approved these changes
LGTM

2020-04-10 21:59 UTC, merged