Fix ndjson unsupported
minio/minio pull request #9500
Opened 2020-04-30 19:19 UTC by fwessels

## Description
Prevent simdjson tests from running on non-amd64 architectures.

## Motivation and Context
Fixes https://github.com/minio/simdjson-go/issues/14

## How to test this PR?
make test now succeeds on non-amd64 platforms (tested on arm64)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

2020-04-30 19:33 UTC, klauspost requested changes
This will still try to run on non AVX2 machines.

Instead use a `t.Skip("unsupported cpu")` if the simdjson package cpu detection fails. There is a public function for that.

2020-04-30 22:39 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#78318094-1227-4875-aeec-4c5f0ff6762f) |
| mint-gateway-azure.sh | :x: [more...](#17b032a9-3f79-4d2e-ada5-814c48ffa371) |
| mint-gateway-nas.sh | :x: [more...](#58c99940-5fca-4f9f-b14e-5d9340dce6e7) |
<a name="17b032a9-3f79-4d2e-ada5-814c48ffa371"></a>
### 9500-4ca2566/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32340
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5d0b7113c085:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 0 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... FAILED in 49 seconds
{
  "name": "awscli",
  "duration": 3857,
  "function": "aws --endpoint-url http://minio-dev3.minio.io:32340 s3api copy-object --bucket awscli-mint-test-bucket-9273 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-9273/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 3 minutes and 34 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 26 seconds
(8/15) Running minio-go tests ... FAILED in 4 minutes and 19 seconds
{}
(8/15) Running minio-java tests ... FAILED in 27 minutes and 59 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1681,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-1ruvh68, objectName = minio-java-test-2norb9h, resource = /minio-java-test-1ruvh68/minio-java-test-2norb9h, requestId = 160AB94E9B111C3A, hostId = 0fe77ee8-f313-4cc7-9aaa-8cd992b4ee31)\nrequest={method=PUT, url=http://minio-dev3.minio.io:32340/minio-java-test-1ruvh68/minio-java-test-2norb9h?legal-hold=, headers=Host: minio-dev3.minio.io:32340\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200430T222605Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200430/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 384\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160AB94E9B111C3A\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 Apr 2020 22:26:05 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... FAILED in 2 minutes and 7 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-ea6e7276-f2aa-4824-843f-11a8c0ce83dd, recursive:true",
  "duration": 209,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(8/15) Running minio-py tests ... done in 10 minutes and 9 seconds
(9/15) Running s3cmd tests ... FAILED in 44 seconds
{
  "name": "s3cmd",
  "duration": "1953",
  "function": "test_copy_object",
  "status": "FAIL",
  "error": ""
}
(9/15) Running s3select tests ... done in 21 seconds
(10/15) Running security tests ... done in 0 seconds

Executed 10 out of 15 tests successfully.
```
<a name="78318094-1227-4875-aeec-4c5f0ff6762f"></a>
### 9500-4ca2566/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30915
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 224f9545f762:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 5 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 50 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 46 seconds
{}
(9/15) Running minio-java tests ... FAILED in 49 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 48,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-1hc4bhm, objectName = minio-java-test-gsiotn, resource = /minio-java-test-1hc4bhm/minio-java-test-gsiotn, requestId = 160AB75B61899F6E, hostId = fb5007ce-fea9-49b1-b788-f94ae8e9a19f)\nrequest={method=PUT, url=http://minio-c3.minio.io:30915/minio-java-test-1hc4bhm/minio-java-test-gsiotn?legal-hold=, headers=Host: minio-c3.minio.io:30915\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200430T215021Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200430/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 382\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160AB75B61899F6E\nX-Xss-Protection: 1; mode=block\nDate: Thu, 30 Apr 2020 21:50:21 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio. [...]

2020-05-01 14:27 UTC, klauspost approved these changes

2020-05-01 15:05 UTC, kannappanr approved these changes
LGTM

2020-05-01 15:06 UTC, merged