Update docs for bucket quota
minio/minio pull request #9503
Opened 2020-05-01 00:11 UTC by poornas

- This PR also adds a check to not enforce
bucket quota for server side metadata copy
of an object onto itself.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-05-01 00:14 UTC, harshavardhana requested changes
This should be merged after the `mc` PR has been merged. 

We should also perhaps bring in a diagram to show fifo v/s regular quota and what is the overall behavior, also lets move the docs to `docs/bucket/quota/README.md`

2020-05-01 02:36 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#7736d906-42e2-469e-bdcf-ec37b4e4d703) |
| mint-gateway-azure.sh | :x: [more...](#2f143d02-453a-4853-98e7-ab743feb4e85) |
| mint-gateway-nas.sh | :x: [more...](#27e7bb48-3cea-4682-8501-9414dc8fec16) |
<a name="7736d906-42e2-469e-bdcf-ec37b4e4d703"></a>
### 9503-ef47dd3/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32318
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4af256b636fc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 4 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 48 seconds
(8/15) Running minio-dotnet tests ... done in 30 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 2 seconds
{}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 3 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 140,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-og6b, objectName = minio-java-test-2snh00l, resource = /minio-java-test-og6b/minio-java-test-2snh00l, requestId = 160AC489E44A5811, hostId = 38119783-34ea-418b-9b6f-c94ead3f2387)\nrequest={method=PUT, url=http://minio-c3.minio.io:32318/minio-java-test-og6b/minio-java-test-2snh00l?legal-hold=, headers=Host: minio-c3.minio.io:32318\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200501T015155Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200501/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 378\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160AC489E44A5811\nX-Xss-Protection: 1; mode=block\nDate: Fri, 01 May 2020 01:51:55 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 41 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 4 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 2 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="2f143d02-453a-4853-98e7-ab743feb4e85"></a>
### 9503-ef47dd3/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32518
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8b474dfdca33:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... FAILED in 48 seconds
{
  "name": "awscli",
  "duration": 3720,
  "function": "aws --endpoint-url http://minio-c3.minio.io:32518 s3api copy-object --bucket awscli-mint-test-bucket-18967 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-18967/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (NotImplemented) when calling the CopyObject operation: A header you provided implies functionality that is not implemented"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... done in 3 minutes and 5 seconds
(7/15) Running minio-dotnet tests ... done in 1 minutes and 21 seconds
(8/15) Running minio-go tests ... FAILED in 4 minutes and 9 seconds
{}
(8/15) Running minio-java tests ... FAILED in 24 minutes and 53 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1691,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidRequest, message = Bucket is missing ObjectLockConfiguration, bucketName = minio-java-test-98j1f3, objectName = minio-java-test-apuogg, resource = /minio-java-test-98j1f3/minio-java-test-apuogg, requestId = 160AC642A878C740, hostId = a930e395-36a5-4c4f-99f7-d4818a750d33)\nrequest={method=PUT, url=http://minio-c3.minio.io:32518/minio-java-test-98j1f3/minio-java-test-apuogg?legal-hold=, headers=Host: minio-c3.minio.io:32518\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: erOisiAmIIzsh/Ze2QqGXw==\nx-amz-content-sha256: 96b73c95a8d33e664ab2170e095025b47ebd55978bb71cebd6a51e394bf96722\nx-amz-date: 20200501T022328Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200501/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 380\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.GOGET\nVary: Origin\nX-Amz-Request-Id: 160AC642A878C740\nX-Xss-Protection: 1; mode=block\nDate: Fri, 01 May 2020 02:23:28 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.enableObjectLegalHold(MinioClient.java:3568), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3303), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-js tests ... FAILED in 2 minutes and 6 seconds
{
  "name": "minio-js",
  "function": "listObjectsV2WithMetadata(bucketName, prefix, recursive, startAfter)",
  "args": "bucketName:minio-js-test-1acf84ab-6494-479c-ae2d-e7be47483b81, recursive:true",
  "duration": 209,
  "status": "FAIL",
  "error": "TypeError: Cannot read property '0' of undefined at /mint/run/core/minio-js/node_modules/minio/dist/main/xml-parsers.js:414:42 at Array.forEach (<anonymous>) at parseListObjectsV2WithMetadata (node_modules/minio/dist/main/xml-parsers.js:409:21) at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:88:19) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writa [...]

2020-05-06 18:19 UTC, eco-minio approved these changes
Same comment as Harsha that we could use some more detail around FIFO usage, assuming that is addressed then LGTM

2020-05-14 19:07 UTC, harshavardhana requested changes
Can you update the image shared by @belvid ?

2020-05-14 21:08 UTC, belvid commented
@harshavardhana I need to make some changes. I'll upload as soon as I can

2020-05-16 02:42 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 9503-8f31cbf/gopath/src/github.com/minio
+ git -C 9503-8f31cbf/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9503-8f31cbf/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9503-8f31cbf/gopath/src/github.com/minio/minio fetch --quiet minio pull/9503/head:pr9503
+ git -C 9503-8f31cbf/gopath/src/github.com/minio/minio checkout --quiet pr9503
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/9503-8f31cbf/gopath
+ make -C 9503-8f31cbf/gopath/src/github.com/minio/minio --quiet
go: downloading cloud.google.com/go v0.39.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: downloading github.com/minio/hdfs/v3 v3.0.1
go: downloading github.com/minio/minio-go/v6 v6.0.55-0.20200424204115-7506d2996b22
go: downloading github.com/montanaflynn/stats v0.5.0
go: downloading github.com/minio/cli v1.22.0
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/rs/cors v1.6.0
go: downloading github.com/miekg/dns v1.1.8
go: downloading go.uber.org/atomic v1.3.2
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: downloading github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: downloading github.com/minio/lsync v1.0.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/minio/gokrb5/v7 v7.2.5
go: downloading golang.org/x/net v0.0.0-20200324143707-d3edc9973b7e
go: downloading github.com/minio/highwayhash v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20191117063200-497ca9f6d64f
go: downloading github.com/prometheus/client_golang v0.9.3-0.20190127221311-3c4408c8b829
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/kurin/blazer v0.5.4-0.20200327014341-8f90a40f8af7
go: downloading github.com/klauspost/reedsolomon v1.9.3
go: downloading github.com/klauspost/compress v1.10.3
go: downloading gopkg.in/yaml.v2 v2.2.4
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading github.com/gorilla/handlers v1.4.0
go: downloading github.com/gorilla/mux v1.7.0
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/rjeczalik/notify v0.9.2
go: downloading github.com/secure-io/sio-go v0.3.0
go: downloading google.golang.org/grpc v1.22.0
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/minio/sha256-simd v0.1.1
go: downloading github.com/json-iterator/go v1.1.9
go: downloading github.com/gogo/protobuf v1.2.1
go: downloading github.com/beorn7/perks v0.0.0-20180321164747-3a771d992973
go: downloading github.com/tinylib/msgp v1.1.1
go: downloading github.com/minio/sio v0.2.0
go: downloading github.com/klauspost/cpuid v1.2.2
go: downloading github.com/googleapis/gax-go/v2 v2.0.4
go: downloading github.com/philhofer/fwd v1.0.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/cheggaaa/pb v1.0.28
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading github.com/prometheus/common v0.2.0
go: downloading github.com/beevik/ntp v0.2.0
go: downloading gopkg.in/ldap.v3 v3.0.3
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/djherbis/atime v1.0.0
go: downloading github.com/lib/pq v1.1.1
go: downloading go.opencensus.io v0.21.0
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/Shopify/sarama v1.24.1
go: downloading github.com/minio/simdjson-go v0.1.5-0.20200303142138-b17fe061ea37
go: downloading github.com/eclipse/paho.mqtt.golang v1.2.0
go: downloading github.com/gorilla/rpc v1.2.0
go: downloading github.com/Azure/azure-storage-blob-go v0.8.0
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/coredns/coredns v1.4.0
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/go-sql-driver/mysql v1.4.1
go: downloading github.com/hashicorp/vault/api v1.0.4
go: downloading github.com/mattn/go-colorable v0.1.1
go: downloading github.com/hashicorp/hcl v1.0.0
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading github.com/minio/parquet-go v0.0.0-20200414234858-838cfa8aae61
go: downloading github.com/hashicorp/go-sockaddr v1.0.2
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading git.apache.org/thrift.git v0.13.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/pierrec/lz4 v2.4.0+incompatible
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: downloading gopkg.in/ini.v1 v1.48.0
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/mattn/go-isatty v0.0.7
go: downloading github.com/prometheus/procfs v0.0.0-20190117184657-bf6a532e95b1
go: downloading github.com/fatih/structs v1.1.0
go: downloading github.com/nats-io/nats.go v1.9.1
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/golang/snappy v0.0.1
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: downloading github.com/eapache/go-xerial-snappy v0.0.0-20180814174437-776d5712da21
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.2.3
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/hashicorp/go-retryablehttp v0.5.4
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/tidwall/sjson v1.0.4
go: downloading github.com/klauspost/pgzip v1.2.1
go: downloading github.com/eapache/go-resiliency v1.2.0
go: downloading github.com/alecthomas/participle v0.2.1
go: downloading github.com/ncw/directio v1.0.5
go: downloading github.com/fatih/color v1.7.0
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: downloading github.com/mattn/go-runewidth v0.0.4
go: downloading github.com/rcrowley/go-metrics v0.0.0-20190704165056-9c2d0518ed81
go: downloading github.com/mailru/easyjson v0.0.0-20180730094502-03f2033d19d5
go: downloading github.com/nats-io/nuid v1.0.1
go: downloading github.com/bcicen/jstream v0.0.0-20190220045926-16c1f8af81c2
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/eapache/queue v1.1.0
go: downloading github.com/nats-io/nkeys v0.1.3
go: downloading github.com/hashicorp/go-cleanhttp v0.5.1
go: downloading gopkg.in/asn1-ber.v1 v1.0.0-20181015200546-f715ec2f112d
go: downloading gopkg.in/jcmturner/dnsutils.v1 v1.0.1
go: downloading github.com/jcmturner/gofork v0.0.0-20190328161633-dc7c13fece03
go: downloading github.com/tidwall/gjson v1.3.5
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: downloading github.com/spaolacci/murmur3 v1.1.0
go: downloading github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/tidwall/match v1.0.1
go: downloading gopkg.in/jcmturner/goidentity.v3 v3.0.0
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/xdg/scram v0.0.0-20180814205039-7eeb5667e42c
go: downloading github.com/willf/bitset v1.1.10
go: downloading github.com/nats-io/stan.go v0.4.5
go: downloading github.com/tidwall/pretty v1.0.0
go: downloading gopkg.in/jcmturner/rpc.v1 v1.1.0
go: downloading github.com/gomodule/redigo v2.0.0+incompatible
go: downloading golang.org/x/text v0.3.2
go: downloading github.com/ryanuber/go-glob v1.0.0
go: downloading github.com/nats-io/jwt v0.3.2
go: downloading gopkg.in/jcmturner/aescts.v1 v1.0.1
go: downloading github.com/xdg/ [...]

2020-05-16 02:55 UTC, harshavardhana requested changes

2020-05-16 02:55 UTC, harshavardhana commented on docs/bucket/quota/README.md
> +![quota](bucketquota.png)
Add the raw link .. we need this for our docs website

2020-05-16 05:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :x: [more...](#9721240e-d788-41ba-804b-612b8c15ff5e) |
<a name="9721240e-d788-41ba-804b-612b8c15ff5e"></a>
### 9503-cb26e26/mint-gateway-s3.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31045
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c13b9e821dcf:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... done in 1 minutes and 14 seconds
(10/15) Running minio-java tests ... done in 39 seconds
(11/15) Running minio-js tests ... done in 35 seconds
(12/15) Running minio-py tests ... done in 1 minutes and 20 seconds
(13/15) Running s3cmd tests ... FAILED in 54 seconds
{
  "name": "s3cmd",
  "duration": "1854",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  following lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n\nInvoked as: /usr/local/bin/s3cmd --config /tmp/.s3cmd-13867/s3cfg get s3://s3cmd-test-bucket-14761/s3cmd-test-object-3830 s3cmd-test-object-3830.downloaded\nProblem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer\nS3cmd:   2.1.0\npython:   3.6.9 (default, Apr 18 2020, 01:56:04) \n[GCC 8.4.0]\nenvironment LANG=C.UTF-8\n\nTraceback (most recent call last):\n  File \"/usr/local/bin/s3cmd\", line 3121, in <module>\n    rc = main()\n  File \"/usr/local/bin/s3cmd\", line 3030, in main\n    rc = cmd_func(args)\n  File \"/usr/local/bin/s3cmd\", line 604, in cmd_object_get\n    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)\n  File \"/usr/local/lib/python3.6/dist-packages/S3/S3.py\", line 726, in object_get\n    response = self.recv_file(request, stream, labels, start_position)\n  File \"/usr/local/lib/python3.6/dist-packages/S3/S3.py\", line 1733, in recv_file\n    data = http_response.read(this_chunk)\n  File \"/usr/lib/python3.6/http/client.py\", line 459, in read\n    n = self.readinto(b)\n  File \"/usr/lib/python3.6/http/client.py\", line 503, in readinto\n    n = self.fp.readinto(b)\n  File \"/usr/lib/python3.6/socket.py\", line 586, in readinto\n    return self._sock.recv_into(b)\nConnectionResetError: [Errno 104] Connection reset by peer\n\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!\n    An unexpected error has occurred.\n  Please try reproducing the error using\n  the latest s3cmd code from the git master\n  branch found at:\n    https://github.com/s3tools/s3cmd\n  and have a look at the known issues list:\n    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions\n  If the error persists, please report the\n  above lines (removing any private\n  info as necessary) to:\n   s3tools-bugs@lists.sourceforge.net\n!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
}
(13/15) Running s3select tests ... done in 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-05-17 02:26 UTC, harshavardhana approved these changes

2020-05-17 02:27 UTC, harshavardhana commented on docs/bucket/quota/README.md
> +![quota](bucketquota.png)
Please fix in the next PR iteration @poornas

2020-05-17 02:27 UTC, merged