azure: Show better message when credentials are wrong
minio/minio pull request #9748
Opened 2020-06-01 14:43 UTC by vadmeste

## Description
The current error is:
`ERROR Unable to initialize gateway backend: illegal base64 data at input byte 8`

The new error is:
`ERROR Unable to initialize gateway backend: erroneous credentials`

## Motivation and Context
Better error message

## How to test this PR?
Use random secret key when running `MINIO_ACCESS_KEY=foobar MINIO_SECRET_KEY=foobarfoobar minio gateway azure`

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-06-01 14:46 UTC, harshavardhana requested changes

2020-06-01 14:46 UTC, harshavardhana commented on cmd/gateway/azure/gateway-azure.go
> +		}
Can the error be nicer like

```
invalid azure credentials
```

2020-06-01 16:26 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#522bb621-cd09-4dc5-8b9e-dda03bc9c2ab) |
<a name="522bb621-cd09-4dc5-8b9e-dda03bc9c2ab"></a>
### 9748-b4e4101/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30516
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f8a2e6a440dc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 40 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... done in 2 minutes and 40 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 29 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 25 seconds
(9/15) Running minio-go tests ... done in 4 minutes and 1 seconds
(10/15) Running minio-java tests ... FAILED in 24 minutes and 47 seconds
error occurred
ErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-3g701fa, objectName = null, resource = /minio-java-test-3g701fa, requestId = 16147760E23C1093, hostId = d5e0aeca-46e0-41a7-a3d0-2b12deef3d24)
request={method=DELETE, url=http://minio-c3.minio.io:30516/minio-java-test-3g701fa, headers=Host: minio-c3.minio.io:30516
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/dev
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200601T161026Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200601/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=409, headers=Accept-Ranges: bytes
Content-Length: 328
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 16147760E23C1093
X-Xss-Protection: 1; mode=block
Date: Mon, 01 Jun 2020 16:10:26 GMT
}

	at io.minio.MinioClient.execute(MinioClient.java:1211)
	at io.minio.MinioClient.execute(MinioClient.java:1236)
	at io.minio.MinioClient.executeDelete(MinioClient.java:1366)
	at io.minio.MinioClient.removeBucket(MinioClient.java:3686)
	at FunctionalTest.teardown(FunctionalTest.java:414)
	at FunctionalTest.runTests(FunctionalTest.java:4122)
	at FunctionalTest.main(FunctionalTest.java:4192)
(10/15) Running minio-js tests ... done in 2 minutes and 41 seconds
(11/15) Running minio-py tests ... done in 10 minutes and 2 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 28 seconds
(13/15) Running s3select tests ... done in 1 minutes and 2 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-06-01 23:42 UTC, harshavardhana approved these changes

2020-06-02 00:05 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#2f7b4a10-296f-4cab-9b3e-b6cf9d1d95ae) |
<a name="2f7b4a10-296f-4cab-9b3e-b6cf9d1d95ae"></a>
### 9748-1447f0a/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30729
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 627818903f48:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 48 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 50 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 24 seconds
(9/15) Running minio-go tests ... done in 3 minutes and 51 seconds
(10/15) Running minio-java tests ... FAILED in 26 minutes and 17 seconds
error occurred
ErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty, bucketName = minio-java-test-2magtbj, objectName = null, resource = /minio-java-test-2magtbj, requestId = 1614907502583E0F, hostId = a48823f5-4886-4bfd-9225-ca73121ccbaf)
request={method=DELETE, url=http://minio-dev4.minio.io:30729/minio-java-test-2magtbj, headers=Host: minio-dev4.minio.io:30729
Accept-Encoding: identity
User-Agent: MinIO (amd64; amd64) minio-java/dev
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
x-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date: 20200601T235000Z
Authorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200601/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*
}
response={code=409, headers=Accept-Ranges: bytes
Content-Length: 328
Content-Security-Policy: block-all-mixed-content
Content-Type: application/xml
Server: MinIO/DEVELOPMENT.GOGET
Vary: Origin
X-Amz-Request-Id: 1614907502583E0F
X-Xss-Protection: 1; mode=block
Date: Mon, 01 Jun 2020 23:50:00 GMT
}

	at io.minio.MinioClient.execute(MinioClient.java:1211)
	at io.minio.MinioClient.execute(MinioClient.java:1236)
	at io.minio.MinioClient.executeDelete(MinioClient.java:1366)
	at io.minio.MinioClient.removeBucket(MinioClient.java:3686)
	at FunctionalTest.teardown(FunctionalTest.java:414)
	at FunctionalTest.runTests(FunctionalTest.java:4122)
	at FunctionalTest.main(FunctionalTest.java:4192)
(10/15) Running minio-js tests ... done in 2 minutes and 37 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 41 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 27 seconds
(13/15) Running s3select tests ... done in 1 minutes and 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-06-02 01:23 UTC, kannappanr approved these changes
LGTM

2020-06-02 01:23 UTC, merged