Fix formatting and wording.
minio/minio pull request #9784
Opened 2020-06-08 19:58 UTC by kerneltime

The formatted page https://docs.min.io/docs/distributed-minio-quickstart-guide.html is not formatted correctly. Trying out this formatting to see if it fixes it.
Also, altering the wording.

## Description

## Motivation and Context

## How to test this PR?

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-06-08 20:47 UTC, harshavardhana approved these changes

2020-06-08 23:16 UTC, eco-minio requested changes

2020-06-08 23:16 UTC, eco-minio commented on docs/distributed/README.md
> +Now the server has expanded total storage by _(o\*m)_ more disks, taking the total count to _(n\*m)+(o\*m)_ disks, new object upload requests automatically start using the least used cluster. This ex
```suggestion
Now the server has expanded total storage by _(o\*m)_ more disks, taking the total count to _(n\*m)+(o\*m)_ disks. New object upload requests automatically start using the least used cluster. This expansion strategy works endlessly, so you can perpetually expand your clusters as needed.  When you restart, it is immediate and non-disruptive to the applications. Each group of servers in the command-line is called a zone. There are 2 zones in this example. New objects are placed in zones in proportion to the amount of free space in each zone. Within each zone, the location of the erasure-set of drives is determined based on a deterministic hashing algorithm.
```

2020-06-09 00:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
Deleting image on docker hub
Deleting image locally

2020-06-09 01:00 UTC, eco-minio approved these changes
LGTM

2020-06-09 01:03 UTC, merged