Reconnect rest client async
minio/minio pull request #9799
Opened 2020-06-10 11:46 UTC by klauspost

## Motivation and Context

Currently marking a client as offline has no other effect than all calls trying to reconnect anyway, so it is a waste of resources.

When encountering a rest network error we spawn a goroutine that will attempt to reconnect every 200ms and reject requests until the server is reconnected.

Closing a client will also keep the connection closed whereas now it has no effect.

The effect should be that an offline server will make the rest of the cluster behave much better since requests will fail instantly and not put additional pressure on the system.

## How to test this PR?

Start cluster, kill a server.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2020-06-10 13:47 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_check_mark: |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :x: [more...](#6606f5f9-024e-48b5-a710-656c519f8dfd) |
<a name="6606f5f9-024e-48b5-a710-656c519f8dfd"></a>
### 9799-22ff258/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31890
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 39a4050cc9de:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 9 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 11 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 2 minutes and 55 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 31 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 20 seconds
(10/15) Running minio-java tests ... done in 24 minutes and 32 seconds
(11/15) Running minio-js tests ... FAILED in 1 minutes and 32 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 81,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 9 minutes and 38 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 42 seconds
(13/15) Running s3select tests ... done in 1 minutes and 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
Deleting image on docker hub
Deleting image locally

2020-06-10 15:04 UTC, harshavardhana requested changes

2020-06-10 15:04 UTC, harshavardhana commented on cmd/peer-rest-client.go
> +				respBody, err := client.callWithContext(ctx, peerRESTMethodServerInfo, nil, nil, -1)
Rather than server info we should perhaps bring a new call which simply does peer is online check, or you can use the function GetLockDiskIDs which is more faster and lighter call.

@klauspost there are other underlying calls which require quick disconnect, not sure just disconnecting here would disconnect everywhere. 

Are you saying since the transport is same this is automatically taken care of?

2020-06-10 15:27 UTC, klauspost commented on cmd/peer-rest-client.go
> +				respBody, err := client.callWithContext(ctx, peerRESTMethodServerInfo, nil, nil, -1)
@harshavardhana It can be any call, should I try GetLockDiskIDs?

2020-06-10 15:34 UTC, harshavardhana commented on cmd/peer-rest-client.go
> +				respBody, err := client.callWithContext(ctx, peerRESTMethodServerInfo, nil, nil, -1)
yes just client.callWithContex(ctx, peerRESTMethodGetLocalDiskIDs) would work here too @klauspost

2020-06-10 16:28 UTC, klauspost commented on cmd/peer-rest-client.go
> +				respBody, err := client.callWithContext(ctx, peerRESTMethodServerInfo, nil, nil, -1)
Updated.

2020-06-11 09:01 UTC, harshavardhana approved these changes

2020-06-11 15:08 UTC, harshavardhana requested changes
@klauspost is exploring a more intricate behavior here

2020-06-11 15:28 UTC, klauspost commented
Yeah. Alternative pr incoming

2020-06-12 12:08 UTC, klauspost commented
Replaced by https://github.com/minio/minio/pull/9808

2020-06-12 12:08 UTC, closed without merging