Add enable="on" to set compression command
minio/minio pull request #9811
Opened 2020-06-11 23:13 UTC by dpgarrick

## Description
Compression doc update

## Motivation and Context
The previously documented command didn't work for me on Minio release 2020-06-03T22:13:49Z, it needed enable="on" added

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)

2020-06-11 23:20 UTC, harshavardhana requested changes
@dpgarrick `enable="on"` is implicit with proper options

2020-06-11 23:28 UTC, dpgarrick commented
Well my assumption is that the documentation would reflect how to enable compression when starting a minio server with default options for compression (i.e. no MINIO_COMPRESS_* options are set).

So, can you define what you mean by proper options? 

I set up a minio server with default options.

Using mc on that server,

```
mc admin config get myminio compression
```
gives
```
compression enable=off extensions=.txt,.log,.csv,.json,.tar,.xml,.bin mime_types=text/*,application/json,application/xml
```

Running 
```
mc admin config set myminio compression
```
outputs
```
KEY:
compression  enable server side compression of objects

ARGS:
extensions  (csv)       comma separated file extensions e.g. ".txt,.log,.csv"
mime_types  (csv)       comma separated wildcard mime-types e.g. "text/*,application/json,application/xml"
comment     (sentence)  optionally add a comment to this setting
```

But does not result in compression being enabled.

If I then run
```
mc admin config set myminio compression enable="on"
```
I get output of
```
Setting new key has been successful.
Please restart your server with `mc admin service restart myminio`
```
Running the restart command and mc admin get shows compression is then enabled.

2020-06-11 23:34 UTC, harshavardhana commented
> Following the current documentation, running
> 
> ```
> mc admin config set myminio compression
> ```
> 
> outputs
> 
> ```
> KEY:
> compression  enable server side compression of objects
> 
> ARGS:
> extensions  (csv)       comma separated file extensions e.g. ".txt,.log,.csv"
> mime_types  (csv)       comma separated wildcard mime-types e.g. "text/*,application/json,application/xml"
> comment     (sentence)  optionally add a comment to this setting
> ```

This is added in the doc to indicate how to show the help @dpgarrick your PR is not correct.

2020-06-11 23:49 UTC, dpgarrick commented
> > Following the current documentation, running
> > ```
> > mc admin config set myminio compression
> > ```
> > 
> > 
> > outputs
> > ```
> > KEY:
> > compression  enable server side compression of objects
> > 
> > ARGS:
> > extensions  (csv)       comma separated file extensions e.g. ".txt,.log,.csv"
> > mime_types  (csv)       comma separated wildcard mime-types e.g. "text/*,application/json,application/xml"
> > comment     (sentence)  optionally add a comment to this setting
> > ```
> 
> This is added in the doc to indicate how to show the help @dpgarrick your PR is not correct.

The current docs say this:
```
To enable compression for all content, with default extensions and mime-types.

~ mc admin config set myminio compression
```
which is incorrect because that command does not enable compression but shows help.

I clarified in the latest commit  - will leave it to you from there.

2020-06-11 23:53 UTC, harshavardhana approved these changes
LGTM

2020-06-12 01:11 UTC, poornas approved these changes

2020-06-12 01:14 UTC, merged

2020-06-12 01:15 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#02354486-b2e5-4adc-b49f-7492aae464b1) |
<a name="02354486-b2e5-4adc-b49f-7492aae464b1"></a>
### 9811-b7d1aeb/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32154
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1314563e999f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 0 seconds
{"name": "awscli", "duration": 12042, "function": "aws --endpoint-url http://minio-c3.minio.io:32154 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-3346/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (8.2 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (10.6 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (11.0 MiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (4.5 MiB/s) with 1 file(s) remaining   
Completed 1.5 MiB/65.0 MiB (5.4 MiB/s) with 1 file(s) remaining   
Completed 1.8 MiB/65.0 MiB (6.1 MiB/s) with 1 file(s) remaining   
Completed 2.0 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining   
Completed 2.2 MiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining   
Completed 2.5 MiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining   
Completed 2.8 MiB/65.0 MiB (7.0 MiB/s) with 1 file(s) remaining   
Completed 3.0 MiB/65.0 MiB (7.3 MiB/s) with 1 file(s) remaining   
Completed 3.2 MiB/65.0 MiB (7.6 MiB/s) with 1 file(s) remaining   
Completed 3.5 MiB/65.0 MiB (7.9 MiB/s) with 1 file(s) remaining   
Completed 3.8 MiB/65.0 MiB (8.1 MiB/s) with 1 file(s) remaining   
Completed 4.0 MiB/65.0 MiB (8.1 MiB/s) with 1 file(s) remaining   
Completed 4.2 MiB/65.0 MiB (8.2 MiB/s) with 1 file(s) remaining   
Completed 4.5 MiB/65.0 MiB (8.4 MiB/s) with 1 file(s) remaining   
Completed 4.8 MiB/65.0 MiB (8.5 MiB/s) with 1 file(s) remaining   
Completed 5.0 MiB/65.0 MiB (8.7 MiB/s) with 1 file(s) remaining   
Completed 5.2 MiB/65.0 MiB (8.6 MiB/s) with 1 file(s) remaining   
Completed 5.5 MiB/65.0 MiB (8.8 MiB/s) with 1 file(s) remaining   
Completed 5.8 MiB/65.0 MiB (8.8 MiB/s) with 1 file(s) remaining   
Completed 6.0 MiB/65.0 MiB (8.9 MiB/s) with 1 file(s) remaining   
Completed 6.2 MiB/65.0 MiB (9.0 MiB/s) with 1 file(s) remaining   
Completed 6.5 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining   
Completed 6.8 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining   
Completed 7.0 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining   
Completed 7.2 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining   
Completed 7.5 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining   
Completed 7.8 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining   
Completed 8.0 MiB/65.0 MiB (9.2 MiB/s) with 1 file(s) remaining   
Completed 8.2 MiB/65.0 MiB (9.3 MiB/s) with 1 file(s) remaining   
Completed 8.5 MiB/65.0 MiB (9.4 MiB/s) with 1 file(s) remaining   
Completed 8.8 MiB/65.0 MiB (9.3 MiB/s) with 1 file(s) remaining   
Completed 9.0 MiB/65.0 MiB (9.3 MiB/s) with 1 file(s) remaining   
Completed 9.2 MiB/65.0 MiB (7.9 MiB/s) with 1 file(s) remaining   
Completed 9.5 MiB/65.0 MiB (8.1 MiB/s) with 1 file(s) remaining   
Completed 9.8 MiB/65.0 MiB (8.2 MiB/s) with 1 file(s) remaining   
Completed 10.0 MiB/65.0 MiB (8.3 MiB/s) with 1 file(s) remaining  
Completed 10.2 MiB/65.0 MiB (8.3 MiB/s) with 1 file(s) remaining  
Completed 10.5 MiB/65.0 MiB (8.5 MiB/s) with 1 file(s) remaining  
Completed 10.8 MiB/65.0 MiB (8.5 MiB/s) with 1 file(s) remaining  
Completed 11.0 MiB/65.0 MiB (8.7 MiB/s) with 1 file(s) remaining  
Completed 11.2 MiB/65.0 MiB (8.8 MiB/s) with 1 file(s) remaining  
Completed 11.5 MiB/65.0 MiB (8.9 MiB/s) with 1 file(s) remaining  
Completed 11.8 MiB/65.0 MiB (9.0 MiB/s) with 1 file(s) remaining  
Completed 12.0 MiB/65.0 MiB (9.1 MiB/s) with 1 file(s) remaining  
Completed 12.2 MiB/65.0 MiB (9.3 MiB/s) with 1 file(s) remaining  
Completed 12.5 MiB/65.0 MiB (9.4 MiB/s) with 1 file(s) remaining  
Completed 12.8 MiB/65.0 MiB (9.4 MiB/s) with 1 file(s) remaining  
Completed 13.0 MiB/65.0 MiB (9.5 MiB/s) with 1 file(s) remaining  
Completed 13.2 MiB/65.0 MiB (9.6 MiB/s) with 1 file(s) remaining  
Completed 13.5 MiB/65.0 MiB (9.7 MiB/s) with 1 file(s) remaining  
Completed 13.8 MiB/65.0 MiB (9.7 MiB/s) with 1 file(s) remaining  
Completed 14.0 MiB/65.0 MiB (9.7 MiB/s) with 1 file(s) remaining  
Completed 14.2 MiB/65.0 MiB (9.8 MiB/s) with 1 file(s) remaining  
Completed 14.5 MiB/65.0 MiB (9.9 MiB/s) with 1 file(s) remaining  
Completed 14.8 MiB/65.0 MiB (9.9 MiB/s) with 1 file(s) remaining  
Completed 15.0 MiB/65.0 MiB (9.9 MiB/s) with 1 file(s) remaining  
Completed 15.2 MiB/65.0 MiB (9.9 MiB/s) with 1 file(s) remaining  
Completed 15.5 MiB/65.0 MiB (9.8 MiB/s) with 1 file(s) remaining  
Completed 15.8 MiB/65.0 MiB (9.8 MiB/s) with 1 file(s) remaining  
Completed 16.0 MiB/65.0 MiB (9.8 MiB/s) with 1 file(s) remaining  
Completed 16.2 MiB/65.0 MiB (9.7 MiB/s) with 1 file(s) remaining  
Completed 16.5 MiB/65.0 MiB (9.7 MiB/s) with 1 file(s) remaining  
Completed 16.8 MiB/65.0 MiB (9.6 MiB/s) with 1 file(s) remaining  
Completed 17.0 MiB/65.0 MiB (9.2 MiB/s) with 1 file(s) remaining  
Completed 17.2 MiB/65.0 MiB (7.7 MiB/s) with 1 file(s) remaining  
Completed 17.5 MiB/65.0 MiB (7.8 MiB/s) with 1 file(s) remaining  
Completed 17.8 MiB/65.0 MiB (7.9 MiB/s) with 1 file(s) remaining  
Completed 18.0 MiB/65.0 MiB (7.8 MiB/s) with 1 file(s) remaining  
Completed 18.2 MiB/65.0 MiB (7.7 MiB/s) with 1 file(s) remaining  
Completed 18.5 MiB/65.0 MiB (7.7 MiB/s) with 1 file(s) remaining  
Completed 18.8 MiB/65.0 MiB (7.6 MiB/s) with 1 file(s) remaining  
Completed 19.0 MiB/65.0 MiB (7.4 MiB/s) with 1 file(s) remaining  
Completed 19.2 MiB/65.0 MiB (7.3 MiB/s) with 1 file(s) remaining  
Completed 19.5 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining  
Completed 19.8 MiB/65.0 MiB (7.2 MiB/s) with 1 file(s) remaining  
Completed 20.0 MiB/65.0 MiB (7.1 MiB/s) with 1 file(s) remaining  
Completed 20.2 MiB/65.0 MiB (7.0 MiB/s) with 1 file(s) remaining  
Completed 20.5 MiB/65.0 MiB (7.0 MiB/s) with 1 file(s) remaining  
Completed 20.8 MiB/65.0 MiB (6.9 MiB/s) with 1 file(s) remaining  
Completed 21.0 MiB/65.0 MiB (6.9 MiB/s) with 1 file(s) remaining  
Completed 21.2 MiB/65.0 MiB (6.8 MiB/s) with 1 file(s) remaining  
Completed 21.5 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining  
Completed 21.8 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining  
Completed 22.0 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining  
Completed 22.2 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining  
Completed 22.5 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining  
Completed 22.8 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining  
Completed 23.0 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining  
Completed 23.2 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining  
Completed 23.5 MiB/65.0 MiB (6.5 MiB/s) with 1 file(s) remaining  
Completed 23.8 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining  
Completed 24.0 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining  
Completed 24.2 MiB/65.0 MiB (6.7 MiB/s) with 1 file(s) remaining  
Completed 24.5 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining  
Completed 24.8 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining  
Completed 25.0 MiB/65.0 MiB (6.6 MiB/s) with 1 file(s) remaining  [...]

2020-06-12 02:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-large-bucket.sh | :heavy_check_mark: |
| mint-fs.sh | :heavy_check_mark: |
| mint-dist-xl.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d1e84790-9d39-415d-bab6-a374c1d0820c) |
<a name="d1e84790-9d39-415d-bab6-a374c1d0820c"></a>
### 9811-0535387/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30125
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2f3e4b930a5c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 6 seconds
{"name": "awscli", "duration": 18212, "function": "aws --endpoint-url http://minio-dev7.minio.io:30125 s3 cp /mint/data/datafile-65-MB s3://awscli-mint-test-bucket-6296/datafile-65-MB\n", "status": "FAIL", "error": "Completed 256.0 KiB/65.0 MiB (4.2 MiB/s) with 1 file(s) remaining
Completed 512.0 KiB/65.0 MiB (7.8 MiB/s) with 1 file(s) remaining
Completed 768.0 KiB/65.0 MiB (11.2 MiB/s) with 1 file(s) remaining
Completed 1.0 MiB/65.0 MiB (13.3 MiB/s) with 1 file(s) remaining  
Completed 1.2 MiB/65.0 MiB (10.0 MiB/s) with 1 file(s) remaining  
Completed 1.5 MiB/65.0 MiB (11.7 MiB/s) with 1 file(s) remaining  
Completed 1.8 MiB/65.0 MiB (13.3 MiB/s) with 1 file(s) remaining  
Completed 2.0 MiB/65.0 MiB (15.0 MiB/s) with 1 file(s) remaining  
Completed 2.2 MiB/65.0 MiB (16.6 MiB/s) with 1 file(s) remaining  
Completed 2.5 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining  
Completed 2.8 MiB/65.0 MiB (19.7 MiB/s) with 1 file(s) remaining  
Completed 3.0 MiB/65.0 MiB (21.1 MiB/s) with 1 file(s) remaining  
Completed 3.2 MiB/65.0 MiB (22.6 MiB/s) with 1 file(s) remaining  
Completed 3.5 MiB/65.0 MiB (23.8 MiB/s) with 1 file(s) remaining  
Completed 3.8 MiB/65.0 MiB (25.2 MiB/s) with 1 file(s) remaining  
Completed 4.0 MiB/65.0 MiB (26.7 MiB/s) with 1 file(s) remaining  
Completed 4.2 MiB/65.0 MiB (27.9 MiB/s) with 1 file(s) remaining  
Completed 4.5 MiB/65.0 MiB (29.2 MiB/s) with 1 file(s) remaining  
Completed 4.8 MiB/65.0 MiB (30.4 MiB/s) with 1 file(s) remaining  
Completed 5.0 MiB/65.0 MiB (31.6 MiB/s) with 1 file(s) remaining  
Completed 5.2 MiB/65.0 MiB (32.7 MiB/s) with 1 file(s) remaining  
Completed 5.5 MiB/65.0 MiB (33.8 MiB/s) with 1 file(s) remaining  
Completed 5.8 MiB/65.0 MiB (34.9 MiB/s) with 1 file(s) remaining  
Completed 6.0 MiB/65.0 MiB (36.0 MiB/s) with 1 file(s) remaining  
Completed 6.2 MiB/65.0 MiB (37.0 MiB/s) with 1 file(s) remaining  
Completed 6.5 MiB/65.0 MiB (38.0 MiB/s) with 1 file(s) remaining  
Completed 6.8 MiB/65.0 MiB (39.0 MiB/s) with 1 file(s) remaining  
Completed 7.0 MiB/65.0 MiB (40.0 MiB/s) with 1 file(s) remaining  
Completed 7.2 MiB/65.0 MiB (41.0 MiB/s) with 1 file(s) remaining  
Completed 7.5 MiB/65.0 MiB (41.9 MiB/s) with 1 file(s) remaining  
Completed 7.8 MiB/65.0 MiB (42.8 MiB/s) with 1 file(s) remaining  
Completed 8.0 MiB/65.0 MiB (43.6 MiB/s) with 1 file(s) remaining  
Completed 8.2 MiB/65.0 MiB (44.5 MiB/s) with 1 file(s) remaining  
Completed 8.5 MiB/65.0 MiB (45.3 MiB/s) with 1 file(s) remaining  
Completed 8.8 MiB/65.0 MiB (46.2 MiB/s) with 1 file(s) remaining  
Completed 9.0 MiB/65.0 MiB (47.0 MiB/s) with 1 file(s) remaining  
Completed 9.2 MiB/65.0 MiB (12.2 MiB/s) with 1 file(s) remaining  
Completed 9.5 MiB/65.0 MiB (12.5 MiB/s) with 1 file(s) remaining  
Completed 9.8 MiB/65.0 MiB (12.8 MiB/s) with 1 file(s) remaining  
Completed 10.0 MiB/65.0 MiB (13.1 MiB/s) with 1 file(s) remaining 
Completed 10.2 MiB/65.0 MiB (13.4 MiB/s) with 1 file(s) remaining 
Completed 10.5 MiB/65.0 MiB (13.7 MiB/s) with 1 file(s) remaining 
Completed 10.8 MiB/65.0 MiB (14.0 MiB/s) with 1 file(s) remaining 
Completed 11.0 MiB/65.0 MiB (14.3 MiB/s) with 1 file(s) remaining 
Completed 11.2 MiB/65.0 MiB (14.6 MiB/s) with 1 file(s) remaining 
Completed 11.5 MiB/65.0 MiB (14.8 MiB/s) with 1 file(s) remaining 
Completed 11.8 MiB/65.0 MiB (15.1 MiB/s) with 1 file(s) remaining 
Completed 12.0 MiB/65.0 MiB (15.4 MiB/s) with 1 file(s) remaining 
Completed 12.2 MiB/65.0 MiB (15.7 MiB/s) with 1 file(s) remaining 
Completed 12.5 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining 
Completed 12.8 MiB/65.0 MiB (16.2 MiB/s) with 1 file(s) remaining 
Completed 13.0 MiB/65.0 MiB (16.5 MiB/s) with 1 file(s) remaining 
Completed 13.2 MiB/65.0 MiB (16.8 MiB/s) with 1 file(s) remaining 
Completed 13.5 MiB/65.0 MiB (17.1 MiB/s) with 1 file(s) remaining 
Completed 13.8 MiB/65.0 MiB (17.3 MiB/s) with 1 file(s) remaining 
Completed 14.0 MiB/65.0 MiB (17.6 MiB/s) with 1 file(s) remaining 
Completed 14.2 MiB/65.0 MiB (17.9 MiB/s) with 1 file(s) remaining 
Completed 14.5 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining 
Completed 14.8 MiB/65.0 MiB (18.4 MiB/s) with 1 file(s) remaining 
Completed 15.0 MiB/65.0 MiB (18.7 MiB/s) with 1 file(s) remaining 
Completed 15.2 MiB/65.0 MiB (18.9 MiB/s) with 1 file(s) remaining 
Completed 15.5 MiB/65.0 MiB (19.2 MiB/s) with 1 file(s) remaining 
Completed 15.8 MiB/65.0 MiB (19.4 MiB/s) with 1 file(s) remaining 
Completed 16.0 MiB/65.0 MiB (19.7 MiB/s) with 1 file(s) remaining 
Completed 16.2 MiB/65.0 MiB (20.0 MiB/s) with 1 file(s) remaining 
Completed 16.5 MiB/65.0 MiB (20.2 MiB/s) with 1 file(s) remaining 
Completed 16.8 MiB/65.0 MiB (20.5 MiB/s) with 1 file(s) remaining 
Completed 17.0 MiB/65.0 MiB (20.7 MiB/s) with 1 file(s) remaining 
Completed 17.2 MiB/65.0 MiB (15.6 MiB/s) with 1 file(s) remaining 
Completed 17.5 MiB/65.0 MiB (15.8 MiB/s) with 1 file(s) remaining 
Completed 17.8 MiB/65.0 MiB (16.0 MiB/s) with 1 file(s) remaining 
Completed 18.0 MiB/65.0 MiB (16.1 MiB/s) with 1 file(s) remaining 
Completed 18.2 MiB/65.0 MiB (16.3 MiB/s) with 1 file(s) remaining 
Completed 18.5 MiB/65.0 MiB (16.5 MiB/s) with 1 file(s) remaining 
Completed 18.8 MiB/65.0 MiB (16.7 MiB/s) with 1 file(s) remaining 
Completed 19.0 MiB/65.0 MiB (16.9 MiB/s) with 1 file(s) remaining 
Completed 19.2 MiB/65.0 MiB (17.1 MiB/s) with 1 file(s) remaining 
Completed 19.5 MiB/65.0 MiB (17.3 MiB/s) with 1 file(s) remaining 
Completed 19.8 MiB/65.0 MiB (17.5 MiB/s) with 1 file(s) remaining 
Completed 20.0 MiB/65.0 MiB (17.7 MiB/s) with 1 file(s) remaining 
Completed 20.2 MiB/65.0 MiB (17.9 MiB/s) with 1 file(s) remaining 
Completed 20.5 MiB/65.0 MiB (18.1 MiB/s) with 1 file(s) remaining 
Completed 20.8 MiB/65.0 MiB (18.2 MiB/s) with 1 file(s) remaining 
Completed 21.0 MiB/65.0 MiB (18.4 MiB/s) with 1 file(s) remaining 
Completed 21.2 MiB/65.0 MiB (18.6 MiB/s) with 1 file(s) remaining 
Completed 21.5 MiB/65.0 MiB (18.8 MiB/s) with 1 file(s) remaining 
Completed 21.8 MiB/65.0 MiB (19.0 MiB/s) with 1 file(s) remaining 
Completed 22.0 MiB/65.0 MiB (19.1 MiB/s) with 1 file(s) remaining 
Completed 22.2 MiB/65.0 MiB (19.3 MiB/s) with 1 file(s) remaining 
Completed 22.5 MiB/65.0 MiB (19.5 MiB/s) with 1 file(s) remaining 
Completed 22.8 MiB/65.0 MiB (19.7 MiB/s) with 1 file(s) remaining 
Completed 23.0 MiB/65.0 MiB (19.9 MiB/s) with 1 file(s) remaining 
Completed 23.2 MiB/65.0 MiB (20.1 MiB/s) with 1 file(s) remaining 
Completed 23.5 MiB/65.0 MiB (20.2 MiB/s) with 1 file(s) remaining 
Completed 23.8 MiB/65.0 MiB (20.4 MiB/s) with 1 file(s) remaining 
Completed 24.0 MiB/65.0 MiB (20.6 MiB/s) with 1 file(s) remaining 
Completed 24.2 MiB/65.0 MiB (20.8 MiB/s) with 1 file(s) remaining 
Completed 24.5 MiB/65.0 MiB (21.0 MiB/s) with 1 file(s) remaining 
Completed 24.8 MiB/65.0 MiB (21.1 MiB/s) with 1 file(s) remaining 
Completed 25.0 MiB/65.0 MiB (21.3 MiB/s) with 1 file(s) remai [...]