Refactored ETCD usage to allow a pluggable backend
minio/minio pull request #9829
Opened 2020-06-14 15:17 UTC by chilicat

## Description
Refactored ETCD usage to allow a pluggable backends 

## Motivation and Context
Hiding Etcd behind a simple key/value store interface allows implementing different backends

## How to test this PR?
Start minio using the experimental inmemory backend:

`MINIO_IAM_BACKEND=inmemory  minio gateway nas /my/data`

The changes are backward compatible and use Etcd of configured:

`MINIO_ETCD_ENDPOINTS=http://etcd:23234 minio gateway nas /my/data`

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-06-14 16:18 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#bcc1b2e2-892f-491d-8ade-31432e61a856) |
| mint-large-bucket.sh | :x: [more...](#30435e1d-831e-464b-9538-41e9c5abb7a9) |
| mint-dist-xl.sh | :x: [more...](#64334025-4a8c-442d-a5cb-9d60b97b87fe) |
<a name="64334025-4a8c-442d-a5cb-9d60b97b87fe"></a>
### 9829-5805de5/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31633
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a650f67a4f62:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 57 seconds
(8/15) Running minio-dotnet tests ... done in 41 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 6 seconds
{
  "args": {
    "bucketName": "minio-go-test-qs6ndm3s1iyzgyj6",
    "objectName": "xqf6d35hsfqyes512pyb5vtc9dd5mg",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 2758,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 7 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 223,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2a5v6hc, objectName = null, resource = /minio-java-test-2a5v6hc, requestId = 161872CCAADE38B1, hostId = c53fad40-dee3-4c76-b4ac-54a2b7f8e3f7)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:31633/minio-java-test-2a5v6hc, headers=Host: minio-dev7.minio.io:31633\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200614T153131Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200614/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-14T15-17-38Z\nVary: Origin\nX-Amz-Request-Id: 161872CCAADE38B1\nX-Xss-Protection: 1; mode=block\nDate: Sun, 14 Jun 2020 15:31:31 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 48 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 40 seconds
(11/15) Running s3cmd tests ... done in 25 seconds
(12/15) Running s3select tests ... done in 8 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="bcc1b2e2-892f-491d-8ade-31432e61a856"></a>
### 9829-5805de5/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31277
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fb1356ac2381:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... FAILED in 1 minutes and 14 seconds
{
  "name": "awscli",
  "duration": 11553,
  "function": "aws --endpoint-url http://minio-c3.minio.io:31277 s3 sync --no-progress /mint/data s3://awscli-mint-test-bucket-25090/\n",
  "status": "FAIL",
  "error": "upload: ../../../data/datafile-0-b to s3://awscli-mint-test-bucket-25090/datafile-0-bupload: ../../../data/datafile-1-kB to s3://awscli-mint-test-bucket-25090/datafile-1-kBupload: ../../../data/datafile-1-b to s3://awscli-mint-test-bucket-25090/datafile-1-bupload: ../../../data/datafile-10-kB to s3://awscli-mint-test-bucket-25090/datafile-10-kBupload: ../../../data/datafile-33-kB to s3://awscli-mint-test-bucket-25090/datafile-33-kBupload: ../../../data/datafile-100-kB to s3://awscli-mint-test-bucket-25090/datafile-100-kBupload: ../../../data/datafile-1.03-MB to s3://awscli-mint-test-bucket-25090/datafile-1.03-MBupload: ../../../data/datafile-1-MB to s3://awscli-mint-test-bucket-25090/datafile-1-MBupload: ../../../data/datafile-5-MB to s3://awscli-mint-test-bucket-25090/datafile-5-MBupload: ../../../data/datafile-5243880-b to s3://awscli-mint-test-bucket-25090/datafile-5243880-bupload: ../../../data/datafile-6-MB to s3://awscli-mint-test-bucket-25090/datafile-6-MBupload: ../../../data/datafile-10-MB to s3://awscli-mint-test-bucket-25090/datafile-10-MBupload: ../../../data/datafile-11-MB to s3://awscli-mint-test-bucket-25090/datafile-11-MBupload: ../../../data/datafile-65-MB to s3://awscli-mint-test-bucket-25090/datafile-65-MBupload failed: ../../../data/datafile-129-MB to s3://awscli-mint-test-bucket-25090/datafile-129-MB An error occurred (RequestTimeout) when calling the UploadPart operation (reached max retries: 4): A timeout occurred while trying to lock a resource, please reduce your request rate"
}
(5/15) Running healthcheck tests ... done in 0 seconds
(6/15) Running mc tests ... done in 23 seconds
(7/15) Running minio-dotnet tests ... done in 29 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 5 seconds
{
  "args": {
    "bucketName": "minio-go-test-arqzhjprp49d6dx0",
    "objectName": "52gp0picfp0yek04bqbt95lgdh9ph6",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5437,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 54 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 122,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-182tpa8, objectName = null, resource = /minio-java-test-182tpa8, requestId = 161872A04978F7AE, hostId = 40f5a5e0-4b1a-4f95-a188-8b0ca26959dc)\nrequest={method=DELETE, url=http://minio-c3.minio.io:31277/minio-java-test-182tpa8, headers=Host: minio-c3.minio.io:31277\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c442 [...]

2020-06-14 17:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#2725fab9-b42b-4215-b606-76387871c24e) |
| mint-large-bucket.sh | :x: [more...](#d56cfe7a-8a82-4e1b-b452-4a4652d18489) |
| mint-dist-xl.sh | :x: [more...](#d230434a-277b-4ecd-9f6b-5af6526f4248) |
<a name="d56cfe7a-8a82-4e1b-b452-4a4652d18489"></a>
### 9829-84172c4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31704
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f0318cf25238:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 6 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 10 seconds
(5/15) Running awscli tests ... done in 2 minutes and 42 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 47 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 27 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 14 seconds
{
  "args": {
    "bucketName": "minio-go-test-xt000rqfljz5lwyh",
    "objectName": "tqvuujfei4x5ghpu5gp2wbuya4car3",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3964,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 7 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 935,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-36a4n29, objectName = null, resource = /minio-java-test-36a4n29, requestId = 1618771885669501, hostId = b7333798-96f8-46ce-b570-0e91e68c11b4)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:31704/minio-java-test-36a4n29, headers=Host: minio-dev3.minio.io:31704\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200614T165015Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200614/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-14T16-28-45Z\nVary: Origin\nX-Amz-Request-Id: 1618771885669501\nX-Xss-Protection: 1; mode=block\nDate: Sun, 14 Jun 2020 16:50:15 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 57 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 34 seconds
(11/15) Running s3cmd tests ... done in 26 seconds
(12/15) Running s3select tests ... done in 14 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="2725fab9-b42b-4215-b606-76387871c24e"></a>
### 9829-84172c4/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32199
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp c642a8a977ce:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 17 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 1 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... FAILED in 52 seconds
{
  "args": {
    "bucketName": "minio-go-test-fras5luo22qczctx",
    "objectName": "0ilrjcl6bnsmyjs43k69t6myrjd01v",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3659,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 19 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 251,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3j02qub, objectName = null, resource = /minio-java-test-3j02qub, requestId = 1618769CED58CC5D, hostId = 0e648cb3-2863-466b-ab91-ea97f34e4026)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:32199/minio-java-test-3j02qub, headers=Host: minio-dev6.minio.io:32199\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200614T164124Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200614/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-14T16-28-45Z\nVary: Origin\nX-Amz-Request-Id: 1618769CED58CC5D\nX-Xss-Protection: 1; mode=block\nDate: Sun, 14 Jun 2020 16:41:24 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 50 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 20 seconds
(11/15) Running s3cmd tests ... done in 24 seconds
(12/15) Running s3select tests ... done in 3 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="d230434a-277b-4ecd-9f6b-5af6526f4248"></a>
### 9829-84172c4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31838
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get log [...]

2020-06-14 18:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#31d970fd-a692-480e-bebb-71006e89bc1f) |
| mint-large-bucket.sh | :x: [more...](#9bf3084d-7fae-43f0-ac4b-14cf837a7303) |
| mint-dist-xl.sh | :x: [more...](#dabc7303-9d87-4370-a2f6-24205108f94d) |
<a name="dabc7303-9d87-4370-a2f6-24205108f94d"></a>
### 9829-fbb68b4/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30293
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0594363ff38f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 5 seconds
(5/15) Running awscli tests ... done in 2 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 48 seconds
(8/15) Running minio-dotnet tests ... done in 45 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 23 seconds
{
  "args": {
    "bucketName": "minio-go-test-acylnvt1y1io545f",
    "objectName": "hwqe06ax4awunfwyjppleauo21sbbk",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5052,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 24 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 259,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-317057a, objectName = null, resource = /minio-java-test-317057a, requestId = 16187A190CA8D68F, hostId = 634aec85-6112-42af-8d78-5f099d3085a6)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:30293/minio-java-test-317057a, headers=Host: minio-dev4.minio.io:30293\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200614T174516Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200614/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-14T17-30-57Z\nVary: Origin\nX-Amz-Request-Id: 16187A190CA8D68F\nX-Xss-Protection: 1; mode=block\nDate: Sun, 14 Jun 2020 17:45:16 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 47 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 0 seconds
(11/15) Running s3cmd tests ... done in 20 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="9bf3084d-7fae-43f0-ac4b-14cf837a7303"></a>
### 9829-fbb68b4/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30913
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a4284aaabe9a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 10 seconds
(5/15) Running awscli tests ... done in 2 minutes and 39 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 47 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 25 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 4 seconds
{
  "args": {
    "bucketName": "minio-go-test-m3a1esoj3l3cuki3",
    "objectName": "49f5s115gmfmlaykn59pusz350nwse",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4029,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 6 minutes and 41 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1658,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3miampj, objectName = null, resource = /minio-java-test-3miampj, requestId = 16187A6ED68A7B38, hostId = 0d2a570f-b6ea-4f30-9800-4194bdd077f2)\nrequest={method=DELETE, url=http://minio-c3.minio.io:30913/minio-java-test-3miampj, headers=Host: minio-c3.minio.io:30913\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200614T175124Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200614/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-14T17-30-57Z\nVary: Origin\nX-Amz-Request-Id: 16187A6ED68A7B38\nX-Xss-Protection: 1; mode=block\nDate: Sun, 14 Jun 2020 17:51:24 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 56 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 9 seconds
(11/15) Running s3cmd tests ... done in 27 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="31d970fd-a692-480e-bebb-71006e89bc1f"></a>
### 9829-fbb68b4/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31180
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run  [...]

2020-06-15 23:10 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#130d6cb0-ade1-4b44-95ec-681c68303076) |
| mint-large-bucket.sh | :x: [more...](#4a307c46-0a33-4ca7-b661-342c772ae729) |
| mint-dist-xl.sh | :x: [more...](#b2d7f822-3fb8-415d-8fdd-4530f1b65afa) |
| mint-gateway-azure.sh | :x: [more...](#3f4ef7ce-5014-4857-919e-3e10df8314f7) |
<a name="4a307c46-0a33-4ca7-b661-342c772ae729"></a>
### 9829-0341f39/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:30641
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 66e247f8ef40:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 9 seconds
(5/15) Running awscli tests ... done in 2 minutes and 37 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 49 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 10 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 24 seconds
{
  "args": {
    "bucketName": "minio-go-test-sxx0yiuk2yfhi1h0",
    "objectName": "3obbypbfv0lfoyw23plqzk5y1kfcn0",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4187,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 6 minutes and 23 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 843,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3c78dlr, objectName = null, resource = /minio-java-test-3c78dlr, requestId = 1618D8561F789EED, hostId = 9b3d7e9b-1da3-4d09-950b-cb0251225a88)\nrequest={method=DELETE, url=http://minio-c3.minio.io:30641/minio-java-test-3c78dlr, headers=Host: minio-c3.minio.io:30641\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200615T223212Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200615/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-15T22-11-51Z\nVary: Origin\nX-Amz-Request-Id: 1618D8561F789EED\nX-Xss-Protection: 1; mode=block\nDate: Mon, 15 Jun 2020 22:32:12 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 55 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 16 seconds
(11/15) Running s3cmd tests ... done in 27 seconds
(12/15) Running s3select tests ... done in 13 seconds
(13/15) Running security tests ... done in 1 seconds

Executed 13 out of 15 tests successfully.
```
<a name="3f4ef7ce-5014-4857-919e-3e10df8314f7"></a>
### 9829-0341f39/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30804
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2b3e5b10da1d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 8 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 29 seconds
(4/15) Running aws-sdk-ruby tests ... done in 17 seconds
(5/15) Running awscli tests ... done in 2 minutes and 52 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 3 minutes and 18 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 35 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 31 seconds
(10/15) Running minio-java tests ... done in 25 minutes and 1 seconds
(11/15) Running minio-js tests ... FAILED in 42 seconds
{
  "name": "minio-js",
  "function": "makeBucket(bucketName, region)",
  "args": "bucketName:minio-js-test-32183329-8d64-4bd9-a8bf-fdf6457c4689-region, region:us-east-1",
  "duration": 40308,
  "status": "FAIL",
  "error": "S3Error: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go:42 ===== RESPONSE ERROR (ServiceCode=ContainerBeingDeleted) ===== Description=The specified container is being deleted. Try operation later. RequestId:0b15340a-b01e-00e2-6668-43099c000000 Time:2020-06-15T22:58:39.3430143Z, Details: Code: ContainerBeingDeleted PUT https://minioazure.blob.core.windows.net/minio-js-test-32183329-8d64-4bd9-a8bf-fdf6457c4689-region?restype=container&timeout=1501 Authorization: REDACTED User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-06-15T22:11:51Z] X-Ms-Client-Request-Id: [22b9d389-d690-4023-64cc-c487f4c1b1d9] X-Ms-Date: [Mon, 15 Jun 2020 22:58:39 GMT] X-Ms-Version: [2018-11-09] -------------------------------------------------------------------------------- RESPONSE Status: 409 The specified container is being deleted. Try operation later. Content-Length: [252] Content-Type: [application/xml] Date: [Mon, 15 Jun 2020 22:58:38 GMT] Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0] X-Ms-Error-Code: [ContainerBeingDeleted] X-Ms-Request-Id: [0b15340a-b01e-00e2-6668-43099c000000] X-Ms-Version: [2018-11-09] at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(11/15) Running minio-py tests ... done in 9 minutes and 47 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 20 seconds
(13/15) Running s3select tests ... done in 1 minutes and 1 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="130d6cb0-ade1-4b44-95ec-681c68303076"></a>
### 9829-0341f39/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32455
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_RE [...]

2020-06-15 23:35 UTC, harshavardhana requested changes
Thanks for the PR @chilicat - I am not sure what is the benefit of bringing this change. The problem I will state a few 

- Increase in the ways to configure MinIO is against our design principles, we add features with some
  careful discussion and also when it makes practical sense i.e there is a viable deployment strategy
  around it.
- Too much modularity is not needed, it leads to the path of too many ways to configure the same thing
  adding to bugs, maintenance headache as someone might end up depending on the feature.

  To give you example etcd is one such feature, we have no hard dependency on it, we implemented it
  as a way to support coreDNS based bucket DNS support in the past - but since we implemented
  we have moved on to better deployment strategies, we have also been actively discouraging setups
  to avoid etcd unless you must use it for needs like gateway where you need to share some common 
  state.
- We are actively trying to get rid of etcd dependency as well - in-turn remove it completely in future. 
  so adding this code more flexible/extending makes it harder for us to remove it in future. 

Now adding in-memory based pluggable backend is too much of modularity which we really cannot take. I am generally conflicted to say "no" because you would have spent the time to work on this feature :1st_place_medal: .  

It is generally advised that speak to us before you write code and to align with our design goals on our public slack. The amount of complexity this brings to the code it is really not worth adding this as part of MinIO, as it is going against our fundamentals here.

2020-06-16 00:14 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#cdda5924-2909-47f5-b97b-0e1395a839e1) |
| mint-large-bucket.sh | :x: [more...](#9472b697-140e-4dd3-9705-55325b68a90e) |
| mint-dist-xl.sh | :x: [more...](#b21f07fa-f844-4681-91a2-de1f40db6e8f) |
<a name="9472b697-140e-4dd3-9705-55325b68a90e"></a>
### 9829-331451e/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30370
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 2adf27df05ea:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 4 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 10 seconds
(5/15) Running awscli tests ... done in 2 minutes and 37 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 56 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 6 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 14 seconds
{
  "args": {
    "bucketName": "minio-go-test-o4163bmw9crkm4tn",
    "objectName": "0sjkieasjrqswhur616fwdboqexnhu",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 6123,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 7 minutes and 9 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 903,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-292knll, objectName = null, resource = /minio-java-test-292knll, requestId = 1618DB9A4DCFFF20, hostId = 845aaa0c-31cc-408a-a8c4-a7e133217a5d)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:30370/minio-java-test-292knll, headers=Host: minio-dev4.minio.io:30370\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200615T233204Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200615/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-15T23-11-09Z\nVary: Origin\nX-Amz-Request-Id: 1618DB9A4DCFFF20\nX-Xss-Protection: 1; mode=block\nDate: Mon, 15 Jun 2020 23:32:04 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 0 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 17 seconds
(11/15) Running s3cmd tests ... done in 27 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="b21f07fa-f844-4681-91a2-de1f40db6e8f"></a>
### 9829-331451e/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31627
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f2a00f375c1e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 19 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 5 seconds
(8/15) Running minio-dotnet tests ... done in 46 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 2 seconds
{
  "args": {
    "bucketName": "minio-go-test-zle02xb53dzf0yf5",
    "objectName": "sl9luf4frl42uaj0cczyuw4eyre922",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5129,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 51 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 294,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-sh5q31, objectName = null, resource = /minio-java-test-sh5q31, requestId = 1618DB4394351983, hostId = cb69d78c-1f6e-4038-85f7-fb6ef1fea206)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:31627/minio-java-test-sh5q31, headers=Host: minio-dev3.minio.io:31627\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200615T232551Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200615/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-15T23-11-09Z\nVary: Origin\nX-Amz-Request-Id: 1618DB4394351983\nX-Xss-Protection: 1; mode=block\nDate: Mon, 15 Jun 2020 23:25:51 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 48 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 44 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 6 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="cdda5924-2909-47f5-b97b-0e1395a839e1"></a>
### 9829-331451e/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31717
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL [...]

2020-06-16 09:07 UTC, chilicat commented
@harshavardhana thank you for your feedback

We are considering using Minio as a gateway in our solutions and we probably also need the IAM functionality. Since we always have to look out in regards to the overall platform footprint we would prefer to reuse existing databases in our ecosystem. 

In regards to the in-memory backend: I totally understand the concern. It was just an example implementation to demonstrate that an easy key-value store interface would allow the community to implement its own backends for the IAM functionality (e.g. Mongo, Consul, Vault).

Can you elaborate I little bit on the plans in regards of:
>> We are actively trying to get rid of etcd dependency as well 

For my understanding, Etcd is needed to have IAM functionality for the Gateway modes (e.g. Azure or Nas). What is the plan in the future? Remove the functionality completely? Alternative backend?

2020-06-16 15:06 UTC, harshavardhana commented
> @harshavardhana thank you for your feedback
> 
> We are considering using Minio as a gateway in our solutions and we probably also need the IAM functionality. Since we always have to look out in regards to the overall platform footprint we would prefer to reuse existing databases in our ecosystem.
> 

Yes that is a valid requirement, but it is not something we want to extend

> In regards to the in-memory backend: I totally understand the concern. It was just an example implementation to demonstrate that an easy key-value store interface would allow the community to implement its own backends for the IAM functionality (e.g. Mongo, Consul, Vault).

That is exactly which we want to avoid. As I explained this PR is doing a bit too much, we didn't design it to be used in this manner.

> 
> Can you elaborate I little bit on the plans in regards of:
> 
> > > We are actively trying to get rid of etcd dependency as well
> 
> For my understanding, Etcd is needed to have IAM functionality for the Gateway modes (e.g. Azure or Nas). What is the plan in the future? Remove the functionality completely? Alternative backend?

It is a possibility, so we don't know yet we are evaluating options.

2020-06-16 15:13 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#431cfffe-9424-41a4-b01c-68e7d49fac17) |
| mint-large-bucket.sh | :x: [more...](#4bc3b292-9ce1-46ae-ac12-d3559211bad8) |
| mint-dist-xl.sh | :x: [more...](#a785be7a-f1cf-4e92-8dcc-b8d07fabc0e5) |
<a name="431cfffe-9424-41a4-b01c-68e7d49fac17"></a>
### 9829-ef6fa02/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32387
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 99dc1ce9e748:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 17 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 38 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... FAILED in 49 seconds
{
  "args": {
    "bucketName": "minio-go-test-oglfymorufbcnq64",
    "objectName": "nsgipufotk24auzioshxhgvym9bgyc",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3233,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 48 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 118,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-1evpmj3, objectName = null, resource = /minio-java-test-1evpmj3, requestId = 16190C329C63578D, hostId = c43dd7b1-b337-4c86-a61f-b37612a61425)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:32387/minio-java-test-1evpmj3, headers=Host: minio-dev3.minio.io:32387\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T142234Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T14-10-52Z\nVary: Origin\nX-Amz-Request-Id: 16190C329C63578D\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 14:22:34 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 48 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 14 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="a785be7a-f1cf-4e92-8dcc-b8d07fabc0e5"></a>
### 9829-ef6fa02/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32682
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 58eb637b1480:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 25 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 0 seconds
(8/15) Running minio-dotnet tests ... done in 45 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 12 seconds
{
  "args": {
    "bucketName": "minio-go-test-owuixmcc04qrnem6",
    "objectName": "spchlx60fngoas6t4wqkq5ochooga4",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 2878,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 26 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 222,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-8usgeq, objectName = null, resource = /minio-java-test-8usgeq, requestId = 16190C59B05A70A9, hostId = 792665d3-2fcf-4d53-bfef-2c8ba8b2bf35)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:32682/minio-java-test-8usgeq, headers=Host: minio-dev6.minio.io:32682\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T142522Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T14-10-52Z\nVary: Origin\nX-Amz-Request-Id: 16190C59B05A70A9\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 14:25:22 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 48 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 48 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="4bc3b292-9ce1-46ae-ac12-d3559211bad8"></a>
### 9829-ef6fa02/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32454
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 8960cfd7b8ae:/m [...]

2020-06-16 18:30 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#3020f348-fb1a-48e5-ae30-0ed38f88b072) |
| mint-large-bucket.sh | :x: [more...](#eb3f4a02-f787-47f1-bb44-1d460e164dd9) |
| mint-dist-xl.sh | :x: [more...](#98e75ed3-f9a8-44b1-8fff-8ab321de6867) |
| mint-gateway-azure.sh | :x: [more...](#f54d15ff-1e17-45a9-85f2-c8e126181503) |
<a name="98e75ed3-f9a8-44b1-8fff-8ab321de6867"></a>
### 9829-a5fa261/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30154
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp abc5d22d9ce8:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 21 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 49 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 29 seconds
{
  "args": {
    "bucketName": "minio-go-test-y4s5hem6honkq4hp",
    "objectName": "62mar3zi1ujcrqtdh1iqcsc9y5grwu",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5727,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 8 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 214,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2ocosub, objectName = null, resource = /minio-java-test-2ocosub, requestId = 1619174353955391, hostId = 33bc7234-48db-449d-a3bf-157ccbe9dcab)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:30154/minio-java-test-2ocosub, headers=Host: minio-dev7.minio.io:30154\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T174521Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T17-31-06Z\nVary: Origin\nX-Amz-Request-Id: 1619174353955391\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 17:45:21 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 50 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 58 seconds
(11/15) Running s3cmd tests ... done in 23 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="eb3f4a02-f787-47f1-bb44-1d460e164dd9"></a>
### 9829-a5fa261/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32720
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d03dc4e83144:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... FAILED in 45 seconds
{
  "name": "awscli",
  "duration": 7741,
  "function": "aws --endpoint-url http://minio-dev7.minio.io:32720 s3api copy-object --bucket awscli-mint-test-bucket-2136 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-2136/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (SlowDown) when calling the CopyObject operation (reached max retries: 4): Please reduce your request"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... FAILED in 1 minutes and 20 seconds
{
  "name": "mc",
  "duration": "76313",
  "function": "test_put_object_with_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-6918 --quiet --no-color cp --storage-class REDUCED_REDUNDANCY /mint/data/datafile-1-MB myminio/mc-test-bucket-16760/mc-test-object-2264  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-16760/mc-test-object-2264`\nmc: <ERROR> Failed to copy `/mint/data/datafile-1-MB`. Please reduce your request\nTotal: 0 B, Transferred: 10.00 MiB, Speed: 134.51 KiB/s"
}
(6/15) Running minio-dotnet tests ... done in 1 minutes and 21 seconds
(7/15) Running minio-go tests ... FAILED in 3 minutes and 50 seconds
{
  "args": {},
  "duration": 103155,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataPutObject()",
  "message": "PutObject failed",
  "name": "minio-go: testStorageClassMetadataPutObject",
  "status": "FAIL"
}
(7/15) Running minio-java tests ... FAILED in 9 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream stream, PutObjectOptions options)",
  "args": "X-Amz-Storage-Class: REDUCED_REDUNDANCY",
  "duration": 128,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = SlowDown, message = Please reduce your request, bucketName = minio-java-test-35hic0q, objectName = minio-java-test-38bcsqd, resource = /minio-java-test-35hic0q/minio-java-test-38bcsqd, requestId = 161917460E3504F0, hostId = 7c57ef07-91db-4400-bc03-e4106e1481be)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:32720/minio-java-test-35hic0q/minio-java-test-38bcsqd?uploadId=cef656d2-c278-4954-b016-bf0b555ba252, headers=Host: minio-dev7.minio.io:32720\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T174532Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=503, headers=Accept-Ranges: bytes\nContent-Length: 363\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nRetry-After: 120\nServer: MinIO/DEVELOPMENT.2020-06-16T17-31-06Z\nVary: Origin\nX-Amz-Request-Id: 161917460E3504F0\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 17:45:32 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioC [...]

2020-06-16 20:33 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#75329c97-42fb-47ed-b53c-dad3b81fee76) |
| mint-large-bucket.sh | :x: [more...](#3a27c0ef-87d8-4a42-8492-d6d68a9a9a53) |
| mint-dist-xl.sh | :x: [more...](#ec8c8e44-602d-4e7e-9f53-0df06cbbac3c) |
<a name="3a27c0ef-87d8-4a42-8492-d6d68a9a9a53"></a>
### 9829-8ee587f/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30684
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1ad51b7b4419:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 4 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 2 minutes and 44 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 1 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 36 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 10 seconds
{
  "args": {
    "bucketName": "minio-go-test-rtgmvpncj19cw3dc",
    "objectName": "sehwh91bydp59os3kc6cbxkqukghel",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4276,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 7 minutes and 31 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 834,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2aot40c, objectName = null, resource = /minio-java-test-2aot40c, requestId = 16191E43BF1A24A1, hostId = 34f443a1-03c3-4ee5-a5c4-161544573333)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:30684/minio-java-test-2aot40c, headers=Host: minio-dev3.minio.io:30684\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T195339Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T19-31-41Z\nVary: Origin\nX-Amz-Request-Id: 16191E43BF1A24A1\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 19:53:39 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 55 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 20 seconds
(11/15) Running s3cmd tests ... done in 26 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="75329c97-42fb-47ed-b53c-dad3b81fee76"></a>
### 9829-8ee587f/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31836
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f384b2f5352c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 16 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 8 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... FAILED in 55 seconds
{
  "args": {
    "bucketName": "minio-go-test-u613i9btbo5b4f9v",
    "objectName": "da45wtc1qjtoxwr5ym6nr651d1a940",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3859,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 55 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 106,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-lp7mqi, objectName = null, resource = /minio-java-test-lp7mqi, requestId = 16191DBDEE67F6E0, hostId = 3f541178-7143-4172-9ad9-c4f6be6dfd32)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:31836/minio-java-test-lp7mqi, headers=Host: minio-dev6.minio.io:31836\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T194404Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T19-31-41Z\nVary: Origin\nX-Amz-Request-Id: 16191DBDEE67F6E0\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 19:44:04 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 53 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 15 seconds
(11/15) Running s3cmd tests ... done in 18 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="ec8c8e44-602d-4e7e-9f53-0df06cbbac3c"></a>
### 9829-8ee587f/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32515
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run [...]

2020-08-15 18:33 UTC, closed without merging