[feat] Preserve version supplied by client
minio/minio pull request #9854
Opened 2020-06-16 22:17 UTC by harshavardhana

## Description
[feat] Preserve version supplied by the client

## Motivation and Context
Just like GET/DELETE APIs it is possible to preserve
client-supplied versionId's, of course, the versionIds
have to be uuid, if an existing versionId is found
it is overwritten if no object locking policies
are found.

- PUT /bucketname/objectname?versionId=<id>
- POST /bucketname/objectname?uploads=&versionId=<id>
- PUT /bucketname/objectname?verisonId=<id> (with x-amz-copy-source)

## How to test this PR?
Needs a custom API where versionId is added as part of the PUT request

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-06-16 23:07 UTC, poornas requested changes

2020-06-16 23:07 UTC, poornas commented on cmd/erasure-object.go
> +	if opts.Versioned && opts.VersionID == "" {
```suggestion
	if opts.Versioned {
	        fi.VersionID = opts.VersionID
	        if opts.VersionID == "" {
                    fi.VersionID = mustGetUUID()
               }       
      }
```

2020-06-16 23:07 UTC, poornas commented on cmd/erasure-multipart.go
> +	if opts.Versioned && opts.VersionID == "" {
```suggestion
	if opts.Versioned {
	      fi.VersionID = opts.VersionID
	      if opts.VersionID == "" {
		fi.VersionID = mustGetUUID()
	    }
	}
```

2020-06-16 23:19 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d298d6d9-05dd-4afd-9a12-c94e33987732) |
| mint-large-bucket.sh | :x: [more...](#50ecce7e-a7a3-4c36-8c02-db82a37d21a1) |
| mint-dist-xl.sh | :x: [more...](#0be89d90-b6d8-4a42-bf4c-4bd2f71f0b47) |
<a name="50ecce7e-a7a3-4c36-8c02-db82a37d21a1"></a>
### 9854-e365ccf/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32026
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1714f866e12a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 5 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 2 minutes and 36 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 1 minutes and 0 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 21 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 17 seconds
{
  "args": {
    "bucketName": "minio-go-test-jfv3cmk1qfsz0n9q",
    "objectName": "mefeknkpoot2e4ycmorilspfprlk3w",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4244,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 7 minutes and 11 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 979,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-tdvek3, objectName = null, resource = /minio-java-test-tdvek3, requestId = 1619274639CEB4D4, hostId = 16a62b32-a329-479b-aef3-c0ff9444521f)\nrequest={method=DELETE, url=http://minio-c3.minio.io:32026/minio-java-test-tdvek3, headers=Host: minio-c3.minio.io:32026\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T223845Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T22-17-19Z\nVary: Origin\nX-Amz-Request-Id: 1619274639CEB4D4\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 22:38:45 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 57 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 28 seconds
(11/15) Running s3cmd tests ... done in 27 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="d298d6d9-05dd-4afd-9a12-c94e33987732"></a>
### 9854-e365ccf/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:32460
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp f771e43438c6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 17 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 52 seconds
(8/15) Running minio-dotnet tests ... done in 33 seconds
(9/15) Running minio-go tests ... FAILED in 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-fqoh4o0tu06yytcq",
    "objectName": "ee3qiel0j39t4c593facqiifdxyqir",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 6051,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 53 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 170,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3gilajs, objectName = null, resource = /minio-java-test-3gilajs, requestId = 161926C3047F6367, hostId = 8d9491b9-b44f-407f-b6b6-9c0afb57f789)\nrequest={method=DELETE, url=http://minio-c3.minio.io:32460/minio-java-test-3gilajs, headers=Host: minio-c3.minio.io:32460\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200616T222922Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200616/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-16T22-17-19Z\nVary: Origin\nX-Amz-Request-Id: 161926C3047F6367\nX-Xss-Protection: 1; mode=block\nDate: Tue, 16 Jun 2020 22:29:22 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 1 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 17 seconds
(11/15) Running s3cmd tests ... done in 18 seconds
(12/15) Running s3select tests ... done in 3 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="0be89d90-b6d8-4a42-bf4c-4bd2f71f0b47"></a>
### 9854-e365ccf/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30293
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker c [...]

2020-06-17 01:25 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#d39e12af-0bac-4368-850c-139521435920) |
| mint-large-bucket.sh | :x: [more...](#4eadfd73-d9f6-4a5e-a60a-4eccf4784c7e) |
| mint-dist-xl.sh | :x: [more...](#e5070f68-bbbb-48e2-b972-adcf9a683525) |
<a name="e5070f68-bbbb-48e2-b972-adcf9a683525"></a>
### 9854-9896e63/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31318
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp a4670e7afb79:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 11 seconds
(8/15) Running minio-dotnet tests ... done in 43 seconds
(9/15) Running minio-go tests ... FAILED in 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-cuvme0wns9nlfehl",
    "objectName": "nl0uxhzz1gl49pcsq9rbku4gvvgpz3",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3417,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 56 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 623,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-8g9urg, objectName = null, resource = /minio-java-test-8g9urg, requestId = 16192DA67EA58EC4, hostId = 207ae3ad-e64a-4fe9-a9cf-534b2422b667)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:31318/minio-java-test-8g9urg, headers=Host: minio-dev7.minio.io:31318\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200617T003536Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200617/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-17T00-21-48Z\nVary: Origin\nX-Amz-Request-Id: 16192DA67EA58EC4\nX-Xss-Protection: 1; mode=block\nDate: Wed, 17 Jun 2020 00:35:36 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 53 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 13 seconds
(11/15) Running s3cmd tests ... done in 20 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="4eadfd73-d9f6-4a5e-a60a-4eccf4784c7e"></a>
### 9854-9896e63/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31012
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7857f4c6f373:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 6 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 2 minutes and 39 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 59 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 6 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-g2s60s9kmptfqp2x",
    "objectName": "35w1xa0ftyitqe91xcf24uoyf0ktdg",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5086,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 7 minutes and 55 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 1514,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-15deg0n, objectName = null, resource = /minio-java-test-15deg0n, requestId = 16192E10F7BE2959, hostId = 795c73dc-2712-400a-957d-5c8a2dc65537)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:31012/minio-java-test-15deg0n, headers=Host: minio-dev4.minio.io:31012\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200617T004313Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200617/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-17T00-21-48Z\nVary: Origin\nX-Amz-Request-Id: 16192E10F7BE2959\nX-Xss-Protection: 1; mode=block\nDate: Wed, 17 Jun 2020 00:43:13 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 7 seconds
(10/15) Running minio-py tests ... done in 5 minutes and 31 seconds
(11/15) Running s3cmd tests ... done in 27 seconds
(12/15) Running s3select tests ... done in 15 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="d39e12af-0bac-4368-850c-139521435920"></a>
### 9854-9896e63/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30703
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0
 [...]

2020-06-17 07:40 UTC, kannappanr approved these changes
LGTM

2020-06-17 09:38 UTC, klauspost approved these changes
LGTM

2020-06-17 16:08 UTC, poornas approved these changes
LGTM

2020-06-17 18:13 UTC, merged