Do not select zones with <5% free after upload
minio/minio pull request #9877
Opened 2020-06-19 13:02 UTC by klauspost

## Motivation and Context

In zoned setups `Storage backend has reached its minimum free disk threshold` is more common than it should be.

Looking into full disk errors on zoned setup. We don't take the 5% space requirement into account when selecting a zone. That is easy to fix.

The interesting part is that even considering this we don't know the size of the object the user wants to upload when they do multipart uploads.

It seems quite defensive and sub-optimal to always upload multiparts to the zone where there is the most space since all load will be directed to a part of the cluster.
In these cases we make sure it can at least hold a 100MiB file and we disadvantage fuller zones more by subtracting the expected size before weighing.

Furthermore, if cluster is indeed full, we reject the upload at once instead of having it attempt to start.

## How to test this PR?

In a heavily unbalanced zoned setup, upload files.

If multiparts are < 100MiB it should not be possible for uploads to fail.

## Types of changes
- [x] Bug fix/feature - you decide.

2020-06-19 15:26 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#efe6fe90-2cc8-43e1-8c2d-87f19a42807d) |
| mint-large-bucket.sh | :x: [more...](#98327b49-1c41-46ef-bed6-046133d257c9) |
| mint-dist-xl.sh | :x: [more...](#a9b6611f-adfd-4f47-9b1f-eac08623f31e) |
<a name="efe6fe90-2cc8-43e1-8c2d-87f19a42807d"></a>
### 9877-320e52b/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:31612
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 0ba1805cac16:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 1 minutes and 15 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 19 seconds
(8/15) Running minio-dotnet tests ... done in 29 seconds
(9/15) Running minio-go tests ... FAILED in 30 seconds
{
  "args": {
    "bucketName": "minio-go-test-6ntwj6cgp1rvio0x",
    "objectName": "xh2zhpejtonjxaqyw1iw1st11xyt0a",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 2038,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 50 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 110,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-dssf1i, objectName = null, resource = /minio-java-test-dssf1i, requestId = 1619F8A3C3BD5F41, hostId = 76502fbb-e8f8-4d5b-9810-00208e705838)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:31612/minio-java-test-dssf1i, headers=Host: minio-dev7.minio.io:31612\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200619T143525Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200619/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-19T14-25-22Z\nVary: Origin\nX-Amz-Request-Id: 1619F8A3C3BD5F41\nX-Xss-Protection: 1; mode=block\nDate: Fri, 19 Jun 2020 14:35:25 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 45 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 14 seconds
(11/15) Running s3cmd tests ... done in 17 seconds
(12/15) Running s3select tests ... done in 3 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="a9b6611f-adfd-4f47-9b1f-eac08623f31e"></a>
### 9877-320e52b/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31402
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 3760af0efaff:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 1 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 1 minutes and 24 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 32 seconds
(8/15) Running minio-dotnet tests ... done in 45 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 23 seconds
{
  "args": {
    "bucketName": "minio-go-test-5ahoaqar1mvtzzyz",
    "objectName": "9az9oijm0hfq1rbpr45ggbdppp6py5",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3309,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 223,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3mslete, objectName = null, resource = /minio-java-test-3mslete, requestId = 1619F8CEBF463A13, hostId = 53886070-5292-4796-9419-7d423f1b5ba2)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:31402/minio-java-test-3mslete, headers=Host: minio-dev4.minio.io:31402\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200619T143830Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200619/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-19T14-25-22Z\nVary: Origin\nX-Amz-Request-Id: 1619F8CEBF463A13\nX-Xss-Protection: 1; mode=block\nDate: Fri, 19 Jun 2020 14:38:30 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 51 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 54 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 7 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="98327b49-1c41-46ef-bed6-046133d257c9"></a>
### 9877-320e52b/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32349
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 81764649c983:/mint/log /tmp/ [...]

2020-06-19 18:11 UTC, harshavardhana requested changes
Rest of the changes LGTM

2020-06-19 18:11 UTC, harshavardhana commented on cmd/erasure-zones.go
> +		return -1, errDiskFull
We should return a higher-level error here `toObjectErr(errDiskFull)`  would be needed

2020-06-19 18:11 UTC, harshavardhana commented on cmd/erasure-zones.go
> +	idx, err := z.getZoneIdx(ctx, bucket, object, opts, 100<<20)
For multipart perhaps we can assume 1GiB minimum @klauspost

2020-06-19 22:04 UTC, krisis approved these changes

2020-06-20 09:51 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#31434e13-d49a-4361-a9ff-f81c53029a3a) |
| mint-large-bucket.sh | :x: [more...](#456f7ee9-a345-4b19-a5a3-56e2c038273e) |
| mint-dist-xl.sh | :x: [more...](#dde24d20-bc47-402a-a66f-3c0394d58121) |
<a name="31434e13-d49a-4361-a9ff-f81c53029a3a"></a>
### 9877-f6897fc/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30386
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7292c19d167b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 11 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 46 seconds
(8/15) Running minio-dotnet tests ... done in 38 seconds
(9/15) Running minio-go tests ... FAILED in 49 seconds
{
  "args": {
    "bucketName": "minio-go-test-2b6l2m0ym0hh5pa6",
    "objectName": "ptl5tfo41k092sp609rdaz9av6i59u",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3544,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 51 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 132,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-244ieg4, objectName = null, resource = /minio-java-test-244ieg4, requestId = 161A34B5BFEACA65, hostId = fc1f4629-4a9c-4836-a82c-2be4b09bb1f3)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:30386/minio-java-test-244ieg4, headers=Host: minio-dev4.minio.io:30386\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200620T085613Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200620/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-20T08-44-20Z\nVary: Origin\nX-Amz-Request-Id: 161A34B5BFEACA65\nX-Xss-Protection: 1; mode=block\nDate: Sat, 20 Jun 2020 08:56:13 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 47 seconds
(10/15) Running minio-py tests ... done in 1 minutes and 14 seconds
(11/15) Running s3cmd tests ... done in 22 seconds
(12/15) Running s3select tests ... done in 2 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="dde24d20-bc47-402a-a66f-3c0394d58121"></a>
### 9877-f6897fc/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32439
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp ccdab1700468:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 2 minutes and 23 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 11 seconds
(8/15) Running minio-dotnet tests ... done in 48 seconds
(9/15) Running minio-go tests ... FAILED in 57 seconds
{
  "args": {
    "bucketName": "minio-go-test-u4quz3vnogk5t3ar",
    "objectName": "0zo6d350b5vqluf52t3yfwzvmgt9p6",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4536,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 54 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 246,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-1elbinb, objectName = null, resource = /minio-java-test-1elbinb, requestId = 161A34D228AA6022, hostId = 40f602fe-7985-41ca-848d-7683861119d2)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:32439/minio-java-test-1elbinb, headers=Host: minio-dev3.minio.io:32439\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200620T085815Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200620/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-20T08-44-20Z\nVary: Origin\nX-Amz-Request-Id: 161A34D228AA6022\nX-Xss-Protection: 1; mode=block\nDate: Sat, 20 Jun 2020 08:58:15 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 51 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 0 seconds
(11/15) Running s3cmd tests ... done in 23 seconds
(12/15) Running s3select tests ... done in 6 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="456f7ee9-a345-4b19-a5a3-56e2c038273e"></a>
### 9877-f6897fc/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31246
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5ae4e2593616:/mint/log /tm [...]

2020-06-20 13:33 UTC, harshavardhana approved these changes

2020-06-20 13:36 UTC, merged