Proxy ListObjects request to the server holding the paginated state
minio/minio pull request #9881
Opened 2020-06-19 22:57 UTC by krishnasrinivas

## Description
ListObjects API is paginated, i.e the client can request for the list batch-by-batch. To serve the list request, MinIO holds state in memory to serve the paginated requests. This PR is to ensure that the request is proxied to the right minio server.

## Motivation and Context
This will make sure that if the client sends list requests to different minio servers, it is handled properly at the server side.

## How to test this PR?
Set bucket to public. Send hand crafted list requests to different servers.
Look at `mc admin trace` and see that list is getting proxied to the right server.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-06-20 00:01 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#fb4267d8-ab6e-4074-86d9-1e6acad6af96) |
| mint-large-bucket.sh | :x: [more...](#c3284b23-e838-4481-a9ee-de0a7e3a0dc7) |
| mint-dist-xl.sh | :x: [more...](#8945bcae-5a96-46fb-9e02-a8c61d40490d) |
<a name="c3284b23-e838-4481-a9ee-de0a7e3a0dc7"></a>
### 9881-4dbbe5a/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32495
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 1e7a692093c6:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 27 seconds
(2/15) Running aws-sdk-java tests ... done in 4 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 6 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 minutes and 13 seconds
(5/15) Running awscli tests ... done in 3 minutes and 44 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 16 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 41 seconds
(9/15) Running minio-go tests ... FAILED in 4 minutes and 44 seconds
{
  "args": {
    "bucketName": "minio-go-test-ngl66wom49rxblu1",
    "objectName": "3tczysufstlk1jl1r2ycku0st5ig1e",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 7087,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 10 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 3651,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-2ve0t2q, objectName = null, resource = /minio-java-test-2ve0t2q, requestId = 161A15CC204FA855, hostId = 586adf9e-43e3-4ed3-9ef0-326a4d1b4d55)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:32495/minio-java-test-2ve0t2q, headers=Host: minio-dev6.minio.io:32495\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200619T232944Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200619/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-19T22-57-15Z\nVary: Origin\nX-Amz-Request-Id: 161A15CC204FA855\nX-Xss-Protection: 1; mode=block\nDate: Fri, 19 Jun 2020 23:29:44 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 12 seconds
(10/15) Running minio-py tests ... done in 12 minutes and 56 seconds
(11/15) Running s3cmd tests ... done in 39 seconds
(12/15) Running s3select tests ... done in 47 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="fb4267d8-ab6e-4074-86d9-1e6acad6af96"></a>
### 9881-4dbbe5a/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30309
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp b3bec07f0064:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 14 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 seconds
(8/15) Running minio-dotnet tests ... done in 32 seconds
(9/15) Running minio-go tests ... FAILED in 52 seconds
{
  "args": {
    "bucketName": "minio-go-test-5qprdxoo2v66mgoj",
    "objectName": "19lt0srec3wc9zrq0dfo413ekh521s",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5640,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 33 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 128,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3iovlje, objectName = null, resource = /minio-java-test-3iovlje, requestId = 161A14B25F3C282B, hostId = 5ba66b84-d791-4d61-92c8-d1895eb99863)\nrequest={method=DELETE, url=http://minio-dev4.minio.io:30309/minio-java-test-3iovlje, headers=Host: minio-dev4.minio.io:30309\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200619T230934Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200619/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-19T22-57-15Z\nVary: Origin\nX-Amz-Request-Id: 161A14B25F3C282B\nX-Xss-Protection: 1; mode=block\nDate: Fri, 19 Jun 2020 23:09:34 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 47 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 55 seconds
(11/15) Running s3cmd tests ... done in 19 seconds
(12/15) Running s3select tests ... done in 7 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="8945bcae-5a96-46fb-9e02-a8c61d40490d"></a>
### 9881-4dbbe5a/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:31135
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:       [...]

2020-06-20 01:04 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#a47f6d2c-9603-448b-b4f1-b66c44781edc) |
| mint-large-bucket.sh | :x: [more...](#68b204c3-546e-405b-8941-c07e8073431d) |
| mint-dist-xl.sh | :x: [more...](#c7fb877e-9d72-40a9-a4cc-38ffe027ee06) |
| mint-gateway-azure.sh | :x: [more...](#b0ae9366-dde3-442f-922c-3a5b3e7866ce) |
<a name="a47f6d2c-9603-448b-b4f1-b66c44781edc"></a>
### 9881-1ca3c91/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:32537
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 97684ddc581e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 28 seconds
(8/15) Running minio-dotnet tests ... done in 52 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-43zaan24wpflouhs",
    "objectName": "wpvw5lx1dt93ueaeiwzmuaycpwqupb",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5320,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 56 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 956,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3tdun7b, objectName = null, resource = /minio-java-test-3tdun7b, requestId = 161A184668355085, hostId = a93394a3-7a98-496d-b090-0cd44e7c198d)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:32537/minio-java-test-3tdun7b, headers=Host: minio-dev3.minio.io:32537\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200620T001508Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200620/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-20T00-01-43Z\nVary: Origin\nX-Amz-Request-Id: 161A184668355085\nX-Xss-Protection: 1; mode=block\nDate: Sat, 20 Jun 2020 00:15:08 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 58 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 59 seconds
(11/15) Running s3cmd tests ... done in 22 seconds
(12/15) Running s3select tests ... done in 5 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="b0ae9366-dde3-442f-922c-3a5b3e7866ce"></a>
### 9881-1ca3c91/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30284
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d683e61ee67c:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 51 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... done in 3 minutes and 3 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 32 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 37 seconds
(9/15) Running minio-go tests ... done in 8 minutes and 12 seconds
(10/15) Running minio-java tests ... FAILED in 23 minutes and 44 seconds
{
  "name": "minio-java",
  "function": "listIncompleteUploads(String bucketName, String prefix)",
  "duration": 954,
  "status": "FAIL",
  "error": "java.io.EOFException >>> [okio.RealBufferedSink.write(RealBufferedSink.java:115), io.minio.HttpRequestBody.writeTo(HttpRequestBody.java:78), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:83), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264), okhttp3.RealCall.execute(RealCall.java:93), io.minio.MinioClient.execute(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executePut(MinioClient.java:1410), io.minio.MinioClient.executePut(MinioClient.java:1424), io.minio.MinioClient.uploadPart(MinioClient.java:5492), io.minio.MinioClient.putObject(MinioClient.java:3740), io.minio.MinioClient.putObject(MinioClient.java:3870), FunctionalTest.listIncompleteUploads_test2(FunctionalTest.java:1790), FunctionalTest.runTests(FunctionalTest.java:4052), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(10/15) Running minio-js tests ... FAILED in 1 minutes and 47 seconds
{
  "name": "minio-js",
  "function": "fPutObject(bucketName, objectName, filePath, metaData)",
  "args": "bucketName:minio-js-test-2d120b80-7ff8-4ffc-98be-e4b24db3e6fd, objectName:datafile-65-MB, filePath:/tmp/datafile-65-MB",
  "duration": 1122,
  "status": "FAIL",
  "error": "Error: read ECONNRESET at TCP.onStreamRead (internal/stream_base_commons.js:205:27)"
}
(10/15) Running minio-py tests ... done in 9 minutes and 59 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 21 seconds
(12/15) Running s3select tests ... done in 1 minutes and 0 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="68b204c3-546e-405b-8941-c07e8073431d"></a>
### 9881-1ca3c91/mint-large-bucket. [...]

2020-06-20 03:14 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#54f20bed-51d2-4732-b7a9-ddbdb8bb3f8f) |
| mint-large-bucket.sh | :x: [more...](#5acadbf5-c408-4c27-a442-b4d51ee5b6df) |
| mint-dist-xl.sh | :x: [more...](#61da5739-8882-4f07-9c41-9063ec88d49a) |
<a name="5acadbf5-c408-4c27-a442-b4d51ee5b6df"></a>
### 9881-05ecbd8/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32031
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6b577e33c2f7:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 28 seconds
(2/15) Running aws-sdk-java tests ... done in 4 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 5 seconds
(4/15) Running aws-sdk-ruby tests ... done in 1 minutes and 11 seconds
(5/15) Running awscli tests ... done in 4 minutes and 34 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 11 seconds
(8/15) Running minio-dotnet tests ... done in 3 minutes and 52 seconds
(9/15) Running minio-go tests ... FAILED in 5 minutes and 3 seconds
{
  "args": {
    "bucketName": "minio-go-test-3cr2rreg5l166wln",
    "objectName": "qxr4qzugdweo0lavmxgdobi3scadhq",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 7104,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 10 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 3497,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3ihtq3g, objectName = null, resource = /minio-java-test-3ihtq3g, requestId = 161A20639407D8AE, hostId = 55402f37-acb1-4af2-bc76-d4c39362ca18)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:32031/minio-java-test-3ihtq3g, headers=Host: minio-dev6.minio.io:32031\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200620T024350Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200620/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-20T02-10-11Z\nVary: Origin\nX-Amz-Request-Id: 161A20639407D8AE\nX-Xss-Protection: 1; mode=block\nDate: Sat, 20 Jun 2020 02:43:50 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 1 minutes and 12 seconds
(10/15) Running minio-py tests ... done in 13 minutes and 44 seconds
(11/15) Running s3cmd tests ... done in 40 seconds
(12/15) Running s3select tests ... done in 51 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="61da5739-8882-4f07-9c41-9063ec88d49a"></a>
### 9881-05ecbd8/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31736
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d3ffd9ad6071:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 44 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 seconds
(5/15) Running awscli tests ... done in 3 minutes and 13 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... FAILED in 30 seconds
{
  "name": "mc",
  "duration": "4207",
  "function": "test_get_object_multipart",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-5004 --quiet --no-color cp myminio/mc-test-bucket-9636/mc-test-object-7960 mc-test-object-7960.downloaded  >>> \n`myminio/mc-test-bucket-9636/mc-test-object-7960` -> `mc-test-object-7960.downloaded`\nmc: <ERROR> Failed to copy `http://minio-dev3.minio.io:31736/mc-test-bucket-9636/mc-test-object-7960`. read tcp 172.17.0.7:53240->72.28.97.52:31736: read: connection reset by peer\nTotal: 0 B, Transferred: 38.91 MiB, Speed: 30.83 MiB/s"
}
(7/15) Running minio-dotnet tests ... done in 2 minutes and 52 seconds
(8/15) Running minio-go tests ... FAILED in 1 minutes and 58 seconds
{
  "args": {
    "bucketName": "minio-go-test-ytx092gukxdaottq",
    "objectName": "whfkwyrhaybz1smma4o3i3kmzzt62y",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 2686,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(8/15) Running minio-java tests ... FAILED in 2 minutes and 29 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 353,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-sk96ou, objectName = null, resource = /minio-java-test-sk96ou, requestId = 161A1F869B467DC5, hostId = f7aee66a-ce1d-4ded-bef3-fe2da0f404e4)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:31736/minio-java-test-sk96ou, headers=Host: minio-dev3.minio.io:31736\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200620T022801Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200620/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 371\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-20T02-10-11Z\nVary: Origin\nX-Amz-Request-Id: 161A1F869B467DC5\nX-Xss-Protection: 1; mode=block\nDate: Sat, 20 Jun 2020 02:28:01 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(8/15) Running minio-j [...]

2020-06-20 08:57 UTC, klauspost requested changes
Instead of querying all servers why not simply make it deterministic?

`server = hash(bucket name) % server` will always contain the listing. This way this implementation is simply "serve locally" or "proxy request".

2020-06-20 16:37 UTC, harshavardhana requested changes
> Instead of querying all servers why not simply make it deterministic?
> 
> `server = hash(bucket name) % server` will always contain the listing. This way this implementation is simply "serve locally" or "proxy request".

Yes this is good idea, if we can avoid making peer requests..

2020-06-20 16:37 UTC, harshavardhana commented on cmd/peer-rest-common.go
> +	peerRESTListPrefix    = "listprefix"
perhaps list-prefix, list-marker, list-delimiter?

2020-06-22 05:38 UTC, krishnasrinivas commented
> `server = hash(bucket name) % server` will always contain the listing. This way this implementation is simply "serve locally" or "proxy request".

Code wise it will get complicated as it needs to handle a lot of cases. i.e we will have to do this
1) For fresh requests (marker as empty string) we will have to hash(bucket_name) and send the request to the hashed server. If the request to hashed server fails serve the request locally.

2) For requests (marker as non-empty string), first check locally, if not available then send the request to the hashed server. If that also fails, then query all the peers and then resend the request to the peer that responds +vely.

The current approach is simpler code wise.

2020-06-22 09:13 UTC, klauspost commented
@krishnasrinivas No, AFAICT you don't have to do 2). Only doing 1) is required.

For ANY request: 

a) Find server based on bucket.
b) Proxy request to server (or handle locally, if server is me).
c) If remote server does not respond, do it locally.

Much simpler. No synchronization needed and no chattiness. You never need to ask all servers.

In 99% case (all servers operating normally) we always hit the same server. If a sever is down we are no worse off than what we do now which is ok.

If you want you can include the prefix in the hash. That will distribute requests more.

In terms of complexity you can remove the new RPC call you added.

2020-06-23 06:07 UTC, krishnasrinivas commented
@klauspost I see how you are thinking, good idea.

2020-07-01 06:32 UTC, krishnasrinivas commented
@klauspost @harshavardhana can you review now?

2020-07-01 11:59 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :x: [more...](#d6aed473-229b-4467-a49f-a18a09285f30) |
| mint-large-bucket.sh | :x: [more...](#d31f6ff5-c451-4865-aa6d-85272994c295) |
| mint-fs.sh | :x: [more...](#b85e64b2-0722-4955-88d5-5fef3add663e) |
| mint-dist-xl.sh | :x: [more...](#a5489fc6-7b63-4a9f-bc63-c0365763ca3e) |
| mint-gateway-s3.sh | :x: [more...](#1b97d784-4afa-421d-b488-11f694cb6b65) |
| mint-gateway-azure.sh | :x: [more...](#3405296c-8af1-4a10-97c5-6ba6ab18d450) |
| mint-zoned.sh | :x: [more...](#328e4d59-d582-4719-a365-59fbbb73208a) |
| mint-gateway-nas.sh | :x: [more...](#1647ea36-2e12-4743-a2b5-e3ecf0811b43) |
<a name="3405296c-8af1-4a10-97c5-6ba6ab18d450"></a>
### 9881-44ea75e/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30048
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 5a533250d8cc:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-a60azuzfr34ryl",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 433,
  "error": "RequestError: send request failed\ncaused by: Get http://minio-c2.minio.io:30048/aws-sdk-go-test-a60azuzfr34ryl?list-type=2&max-keys=1000&prefix=: EOF",
  "function": "testListObjects",
  "message": "AWS SDK Go listobjects expected to success but got RequestError: send request failed\ncaused by: Get http://minio-c2.minio.io:30048/aws-sdk-go-test-a60azuzfr34ryl?list-type=2&max-keys=1000&prefix=: EOF",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-java tests ... FAILED in 3 seconds
{
  "alert": "",
  "args": {
    "bucketName": "aws-sdk-go-test-a60azuzfr34ryl",
    "expiry": 60000000000,
    "objectName1": "testObject1",
    "objectName2": "testObject2"
  },
  "duration": 433,
  "error": "RequestError: send request failed\ncaused by: Get http://minio-c2.minio.io:30048/aws-sdk-go-test-a60azuzfr34ryl?list-type=2&max-keys=1000&prefix=: EOF",
  "function": "testListObjects",
  "message": "AWS SDK Go listobjects expected to success but got RequestError: send request failed\ncaused by: Get http://minio-c2.minio.io:30048/aws-sdk-go-test-a60azuzfr34ryl?list-type=2&max-keys=1000&prefix=: EOF",
  "name": "aws-sdk-go",
  "status": "FAIL"
}
(1/15) Running aws-sdk-php tests ... FAILED in 4 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5efc5b785ef53",
    "Object": "obj1"
  },
  "duration": "2806",
  "status": "FAIL",
  "error": "Error executing \"ListObjects\" on \"http://minio-c2.minio.io:30048/aws-sdk-php-5efc5b785ef53?encoding-type=url\"; AWS HTTP error: cURL error 52: Empty reply from server (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"
}
(1/15) Running aws-sdk-ruby tests ... FAILED in 4 seconds
{
  "name": "aws-sdk-ruby",
  "function": "removeObjects(bucket_name)",
  "args": {
    "bucket_name": "aws-sdk-ruby-bucket-1a55261186ad"
  },
  "duration": 3146.73,
  "error": "Failed to clean-up bucket 'aws-sdk-ruby-bucket-1a55261186ad', File name: '', end of file reached",
  "status": "FAIL"
}
(1/15) Running awscli tests ... FAILED in 16 seconds
{"name": "awscli", "duration": 13956, "function": "delete_bucket\n", "status": "FAIL", "error": "fatal error: Connection was closed before we received a valid response from endpoint URL: "http://minio-c2.minio.io:30048/awscli-mint-test-bucket-31928?list-type=2&prefix=&encoding-type=url".remove_bucket failed: Unable to delete all objects in the bucket, bucket will not be deleted."}
(1/15) Running healthcheck tests ... done in 1 seconds
(2/15) Running mc tests ... FAILED in 1 minutes and 21 seconds
{
  "name": "mc",
  "duration": "80604",
  "function": "test_make_bucket",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-23655 --quiet --no-color rb myminio/mc-test-bucket-12467  >>> \nmc: <ERROR> `myminio/mc-test-bucket-12467` is not empty. Retry this command with ���--force��� flag if you want to remove `myminio/mc-test-bucket-12467` and all its contents "
}
(2/15) Running minio-dotnet tests ... done in 1 minutes and 32 seconds
(3/15) Running minio-go tests ... FAILED in 1 minutes and 43 seconds
{
  "args": {
    "bucketName": "minio-go-test-i9uja916wvp0qroz",
    "objectName": "s0uhh2yilzsel4oguzi6bcdblsssqa",
    "region": "eu-west-1"
  },
  "duration": 102372,
  "error": "Get http://minio-c2.minio.io:30048/minio-go-test-i9uja916wvp0qroz/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=: Connection closed by foreign host http://minio-c2.minio.io:30048/minio-go-test-i9uja916wvp0qroz/?delimiter=&encoding-type=url&fetch-owner=true&list-type=2&prefix=. Retry again.",
  "function": "MakeBucket(bucketName, region)",
  "message": "Cleanup failed",
  "name": "minio-go: testGetObjectClosedTwiceV2",
  "status": "FAIL"
}
(3/15) Running minio-java tests ... FAILED in 42 seconds
{
  "name": "minio-java",
  "function": "listObjects(final String bucketName)",
  "duration": 3887,
  "status": "FAIL",
  "error": "java.io.IOException: unexpected end of stream on Connection{minio-c2.minio.io:30048, proxy=DIRECT hostAddress=minio-c2.minio.io/72.28.97.58:30048 cipherSuite=none protocol=http/1.1} >>> [okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:221), okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:101), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264), okhttp3.RealCall.execute(RealCall.java:93), io.minio.MinioClient.execute(MinioClient.java:1097), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeGet(MinioClient.java:1295), io.minio.MinioClient.listObjectsV2(MinioClient.java:5224), io.minio.MinioClient$2$1.populate(MinioClient.java:2854), io.minio.MinioClient$2$1.hasNext(MinioClient.java:2892), FunctionalTest.listObject_test1(FunctionalTest.java:1436), FunctionalTest.runTests(FunctionalTest.java:4041), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(3/15) Running minio-js tests ... FAILED in 2 minutes and 14 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 87,
  "status": "FAIL",
  "error": "S3Error: The bucket you tried to delete is not empty at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable [...]

2020-07-01 15:14 UTC, harshavardhana commented
Looks like the implementation is not working @krishnasrinivas almost all tests have failed across mint can you PTAL?

2020-07-02 02:18 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#4a895147-81c2-4dc5-a656-a2a31f8a6764) |
| mint-large-bucket.sh | :x: [more...](#90e23469-a23b-40c8-82f7-bccb5c6aff73) |
| mint-dist-xl.sh | :x: [more...](#2e89f374-06e3-41eb-a63f-4079a0504506) |
| mint-zoned.sh | :x: [more...](#54cd199f-eff3-40d0-ba0f-bd9b4e6113e8) |
<a name="4a895147-81c2-4dc5-a656-a2a31f8a6764"></a>
### 9881-dacdc46/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:30116
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp d4c45c4bb875:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 20 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 35 seconds
(8/15) Running minio-dotnet tests ... done in 48 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 33 seconds
{
  "args": {
    "bucketName": "minio-go-test-p5yuiiuv6k1fbsan",
    "objectName": "nyzj4m24orts53nwwa0dz0fek2rivy",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3661,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 18 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 146,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3qeqvem, objectName = null, resource = /minio-java-test-3qeqvem, requestId = 161DC5086A21637F, hostId = 306852f9-6ff2-4317-ab4c-a2987f9ddcc7)\nrequest={method=DELETE, url=http://minio-dev3.minio.io:30116/minio-java-test-3qeqvem, headers=Host: minio-dev3.minio.io:30116\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200701T233443Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200701/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-07-01T23-20-28Z\nVary: Origin\nX-Amz-Request-Id: 161DC5086A21637F\nX-Xss-Protection: 1; mode=block\nDate: Wed, 01 Jul 2020 23:34:43 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 46 seconds
(10/15) Running minio-py tests ... done in 2 minutes and 18 seconds
(11/15) Running s3cmd tests ... done in 20 seconds
(12/15) Running s3select tests ... done in 3 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="54cd199f-eff3-40d0-ba0f-bd9b4e6113e8"></a>
### 9881-dacdc46/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:32621
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6ea045b8724f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 2 minutes and 39 seconds
(2/15) Running aws-sdk-java tests ... done in 17 seconds
(3/15) Running aws-sdk-php tests ... done in 3 minutes and 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 minutes and 34 seconds
(5/15) Running awscli tests ... done in 8 minutes and 31 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 45 seconds
(8/15) Running minio-dotnet tests ... done in 18 minutes and 23 seconds
(9/15) Running minio-go tests ... FAILED in 23 minutes and 15 seconds
{
  "args": {},
  "duration": 93358,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "CopyObject failed on RRS",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 47 minutes and 13 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 19821,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-1te4mdj, objectName = null, resource = /minio-java-test-1te4mdj, requestId = 161DCAB4F8AD8E89, hostId = 2c373155-e41d-47a1-9f9c-851ce35ad2e5)\nrequest={method=DELETE, url=http://minio-dev7.minio.io:32621/minio-java-test-1te4mdj, headers=Host: minio-dev7.minio.io:32621\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200702T011841Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200702/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-07-01T23-20-28Z\nVary: Origin\nX-Amz-Request-Id: 161DCAB4F8AD8E89\nX-Xss-Protection: 1; mode=block\nDate: Thu, 02 Jul 2020 01:18:41 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 3 minutes and 13 seconds
(10/15) Running minio-py tests ... done in 51 minutes and 45 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 28 seconds
(12/15) Running s3select tests ... done in 2 minutes and 53 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="90e23469-a23b-40c8-82f7-bccb5c6aff73"></a>
### 9881-dacdc46/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32611
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 087ffbf6c5ce:/mint/lo [...]

2020-07-02 04:00 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :x: [more...](#99a466c9-e9de-4b5a-b02e-a33bb5387363) |
| mint-large-bucket.sh | :x: [more...](#f90d6758-392d-4b1c-8ec3-471f993da9bb) |
| mint-fs.sh | :x: [more...](#3c56a249-cc89-463d-a763-d0d12d2223b4) |
| mint-dist-xl.sh | :x: [more...](#8ed502cf-7ba5-4e87-a2d7-0c08086e0a53) |
| mint-gateway-s3.sh | :x: [more...](#e5b070a9-2d8f-413f-8d31-307af61c4c8a) |
| mint-gateway-azure.sh | :x: [more...](#8f731a7a-2509-4e88-b46c-3dfc9b665129) |
| mint-zoned.sh | :x: [more...](#e4530bec-b278-4a56-bd90-a0652c46b6af) |
| mint-gateway-nas.sh | :x: [more...](#90eff05a-20de-4fda-bfe2-e51d23b8ae64) |
<a name="90eff05a-20de-4fda-bfe2-e51d23b8ae64"></a>
### 9881-97af8b0/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c3.minio.io:31684
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 284221e78860:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 1 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 30 seconds
(8/15) Running minio-dotnet tests ... done in 28 seconds
(9/15) Running minio-go tests ... done in 46 seconds
(10/15) Running minio-java tests ... FAILED in 4 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[SSE-S3]",
  "duration": 11,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-2vbv1bs, objectName = minio-java-test-3a9gejt, resource = /minio-java-test-2vbv1bs/minio-java-test-3a9gejt, requestId = 161DCE83AE9F7B9D, hostId = 648cf49f-71b9-4d61-931c-683e2d7a7516)\nrequest={method=PUT, url=http://minio-c3.minio.io:31684/minio-java-test-2vbv1bs/minio-java-test-3a9gejt, headers=X-Amz-Server-Side-Encryption: AES256\nContent-Type: application/javascript\nHost: minio-c3.minio.io:31684\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/7.1.0\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20200702T022828Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200702/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-server-side-encryption, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 402\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-07-02T02-18-53Z\nVary: Origin\nX-Amz-Request-Id: 161DCE83AE9F7B9D\nX-Xss-Protection: 1; mode=block\nDate: Thu, 02 Jul 2020 02:28:28 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1135), io.minio.MinioClient.putObject(MinioClient.java:7582), io.minio.MinioClient.putObject(MinioClient.java:4682), io.minio.MinioClient.putObject(MinioClient.java:4881), FunctionalTest.testPutObject(FunctionalTest.java:740), FunctionalTest.putObject_test(FunctionalTest.java:887), FunctionalTest.runTests(FunctionalTest.java:3789), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 41 seconds
(11/15) Running minio-py tests ... done in 1 minutes and 33 seconds
(12/15) Running s3cmd tests ... done in 23 seconds
(13/15) Running s3select tests ... done in 4 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="f90d6758-392d-4b1c-8ec3-471f993da9bb"></a>
### 9881-97af8b0/mint-large-bucket.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31365
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp fcac0e9e0274:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 minutes and 35 seconds
(2/15) Running aws-sdk-java tests ... done in 18 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 4 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 minutes and 26 seconds
(5/15) Running awscli tests ... done in 4 minutes and 22 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 56 seconds
(8/15) Running minio-dotnet tests ... done in 11 minutes and 4 seconds
(9/15) Running minio-go tests ... FAILED in 13 minutes and 41 seconds
{
  "args": {
    "bucketName": "minio-go-test-tyuvvnvhlpcr10lh",
    "objectName": "6kl341cwt9iwlgy9jnjxqccz0shrcs",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 14746,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 2 minutes and 20 seconds
{
  "name": "minio-java",
  "function": "putObject()",
  "args": "[SSE-S3]",
  "duration": 16,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = InvalidArgument, message = Server side encryption specified but KMS is not configured, bucketName = minio-java-test-30o2ek, objectName = minio-java-test-s6rtog, resource = /minio-java-test-30o2ek/minio-java-test-s6rtog, requestId = 161DD07B23243FFB, hostId = 4278d2d8-f48c-4901-bd36-99894a0bd84c)\nrequest={method=PUT, url=http://minio-dev6.minio.io:31365/minio-java-test-30o2ek/minio-java-test-s6rtog, headers=X-Amz-Server-Side-Encryption: AES256\nContent-Type: application/javascript\nHost: minio-dev6.minio.io:31365\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/7.1.0\nContent-MD5: A9oFTxee7YVcJ9fWsgQeKg==\nx-amz-content-sha256: 1ff7959f86334ddc5c188a5083268f600146328b2b6c5185e75bf7d9387d6b74\nx-amz-date: 20200702T030430Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200702/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date;x-amz-server-side-encryption, Signature=*REDACTED*\n}\nresponse={code=400, headers=Accept-Ranges: bytes\nContent-Length: 398\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-07-02T02-18-53Z\nVary: Origin\nX-Amz-Request-Id: 161DD07B23243FFB\nX-Xss-Protection: 1; mode=block\nDate: Thu, 02 Jul 2020 03:04:30 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1135), io.minio.MinioClient.putObject(MinioClient.java:7582), io.minio.MinioClient.putObject(MinioClient.java:4682), io.minio.MinioClient.putObject(MinioClient.java:4881), FunctionalTest.testPutObject(FunctionalTest.java:740), FunctionalTest.putObject_test(FunctionalTest.java:887), FunctionalTest.runTests(FunctionalTest.java:3789), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(9/15) Running minio-js tests ... done in 2 minutes and 11 seconds
(10/15) Running minio-py tests ... done in 34 minutes and 36 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 7 seconds
(12/15) Running s3select tests ... done in 2 minutes and 27 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="8ed502cf-7ba5-4e87-a2d7-0c08086e0a53"></a>
### 9881-97af8b0/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32304
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:     [...]

2020-07-02 07:12 UTC, krishnasrinivas commented
@harshavardhana @klauspost can you check now.

2020-07-02 08:55 UTC, klauspost approved these changes
Beautiful. Even cleaner than I imagined. Awesome! 👍

2020-07-02 17:55 UTC, harshavardhana approved these changes

2020-07-02 17:55 UTC, harshavardhana commented
@krishnasrinivas can you also do the ListObjectsV2 change in a subsequent PR which we discussed about continuation-token?

2020-07-02 17:56 UTC, merged

2020-07-06 05:08 UTC, krishnasrinivas commented
> @krishnasrinivas can you also do the ListObjectsV2 change in a subsequent PR which we discussed about continuation-token?

yes