heal: Redirect heal request based on client token
minio/minio pull request #9939
Opened 2020-06-29 15:41 UTC by vadmeste

## Description
When a manual healing is triggered, one node in a cluster will take care
of that. mc regularly sends new admin requests to fetch the status of
the going healing process, but a load balancer could land the heal
request to a node that is not doing the healing request and not aware
about it.

This PR will redirect a request to the node having the heal client token
so mc can receive the appropriate heal response.

## Motivation and Context
Fixes https://github.com/minio/minio/issues/9878

## How to test this PR?
*) Run a 4 nodes with a reverse proxy with round robin
*) Run mc admin heal command

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-06-29 15:43 UTC, harshavardhana approved these changes
Thank you for doing this! @vadmeste

2020-06-30 00:51 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-azure.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#dbe9e6ee-f9ea-48c1-9733-53ffbb3f9a69) |
| mint-large-bucket.sh | :x: [more...](#a7fe67e1-1b16-45ef-aa3f-0154652d5299) |
| mint-dist-xl.sh | :x: [more...](#fc112b41-ce49-4991-aa6e-49205009dca3) |
| mint-zoned.sh | :x: [more...](#201afb10-540c-4946-8cb9-9db35d0c3b30) |
<a name="dbe9e6ee-f9ea-48c1-9733-53ffbb3f9a69"></a>
### 9939-1bf3da3/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:32347
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 682332f6386f:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 42 seconds
(4/15) Running aws-sdk-ruby tests ... done in 2 seconds
(5/15) Running awscli tests ... done in 2 minutes and 17 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 29 seconds
(8/15) Running minio-dotnet tests ... done in 34 seconds
(9/15) Running minio-go tests ... FAILED in 47 seconds
{
  "args": {
    "bucketName": "minio-go-test-v0vqewwkc1dol0t5",
    "objectName": "zmvj4n63dad1r9bzf5bqpshunrxue3",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 3780,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... FAILED in 1 minutes and 47 seconds
{
  "name": "minio-java",
  "function": "enableObjectLegalHold(String bucketName, String objectName, String versionId)",
  "duration": 295,
  "status": "FAIL",
  "error": "error occurred\nErrorResponse(code = BucketNotEmpty, message = The bucket you tried to delete is not empty. You must delete all versions in the bucket., bucketName = minio-java-test-3n2i2v4, objectName = null, resource = /minio-java-test-3n2i2v4, requestId = 161D2886229A4DBE, hostId = 40cdf17b-6688-45bf-9d1b-11d95ae8df13)\nrequest={method=DELETE, url=http://minio-dev6.minio.io:32347/minio-java-test-3n2i2v4, headers=Host: minio-dev6.minio.io:32347\nAccept-Encoding: identity\nUser-Agent: MinIO (amd64; amd64) minio-java/dev\nContent-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==\nx-amz-content-sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date: 20200629T234639Z\nAuthorization: AWS4-HMAC-SHA256 Credential=*REDACTED*/20200629/us-east-1/s3/aws4_request, SignedHeaders=accept-encoding;content-md5;host;x-amz-content-sha256;x-amz-date, Signature=*REDACTED*\n}\nresponse={code=409, headers=Accept-Ranges: bytes\nContent-Length: 373\nContent-Security-Policy: block-all-mixed-content\nContent-Type: application/xml\nServer: MinIO/DEVELOPMENT.2020-06-29T23-34-04Z\nVary: Origin\nX-Amz-Request-Id: 161D2886229A4DBE\nX-Xss-Protection: 1; mode=block\nDate: Mon, 29 Jun 2020 23:46:39 GMT\n}\n >>> [io.minio.MinioClient.execute(MinioClient.java:1211), io.minio.MinioClient.execute(MinioClient.java:1236), io.minio.MinioClient.executeDelete(MinioClient.java:1366), io.minio.MinioClient.removeBucket(MinioClient.java:3686), FunctionalTest.enableObjectLegalHold_test(FunctionalTest.java:3314), FunctionalTest.runTests(FunctionalTest.java:4079), FunctionalTest.main(FunctionalTest.java:4192)]"
}
(9/15) Running minio-js tests ... done in 48 seconds
(10/15) Running minio-py tests ... done in 3 minutes and 6 seconds
(11/15) Running s3cmd tests ... done in 21 seconds
(12/15) Running s3select tests ... done in 6 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="201afb10-540c-4946-8cb9-9db35d0c3b30"></a>
### 9939-1bf3da3/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31901
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 7c258833af8a:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 minutes and 15 seconds
(2/15) Running aws-sdk-java tests ... done in 8 seconds
(3/15) Running aws-sdk-php tests ... done in 1 minutes and 33 seconds
(4/15) Running aws-sdk-ruby tests ... done in 4 minutes and 5 seconds
(5/15) Running awscli tests ... FAILED in 2 minutes and 15 seconds
{
  "name": "awscli",
  "duration": 23995,
  "function": "aws --endpoint-url http://minio-dev3.minio.io:31901 s3api copy-object --bucket awscli-mint-test-bucket-5755 --storage-class REDUCED_REDUNDANCY --key datafile-1-kB-copy --copy-source awscli-mint-test-bucket-5755/datafile-1-kB\n",
  "status": "FAIL",
  "error": "An error occurred (SlowDown) when calling the CopyObject operation (reached max retries: 4): Please reduce your request"
}
(5/15) Running healthcheck tests ... done in 1 seconds
(6/15) Running mc tests ... FAILED in 3 minutes and 33 seconds
{
  "name": "mc",
  "duration": "135761",
  "function": "test_mirror_list_objects_storage_class",
  "status": "FAIL",
  "error": "/mint/run/core/mc/mc --config-dir /tmp/.mc-7351 --quiet --no-color mirror --storage-class REDUCED_REDUNDANCY /mint/data myminio/mc-test-bucket-14946  >>> \n`/mint/data/datafile-1-MB` -> `myminio/mc-test-bucket-14946/datafile-1-MB`\n`/mint/data/datafile-0-b` -> `myminio/mc-test-bucket-14946/datafile-0-b`\n`/mint/data/datafile-1-b` -> `myminio/mc-test-bucket-14946/datafile-1-b`\n`/mint/data/datafile-1-kB` -> `myminio/mc-test-bucket-14946/datafile-1-kB`\n`/mint/data/datafile-1.03-MB` -> `myminio/mc-test-bucket-14946/datafile-1.03-MB`\n`/mint/data/datafile-10-kB` -> `myminio/mc-test-bucket-14946/datafile-10-kB`\n`/mint/data/datafile-10-MB` -> `myminio/mc-test-bucket-14946/datafile-10-MB`\n`/mint/data/datafile-11-MB` -> `myminio/mc-test-bucket-14946/datafile-11-MB`\n`/mint/data/datafile-100-kB` -> `myminio/mc-test-bucket-14946/datafile-100-kB`\n`/mint/data/datafile-5243880-b` -> `myminio/mc-test-bucket-14946/datafile-5243880-b`\n`/mint/data/datafile-5-MB` -> `myminio/mc-test-bucket-14946/datafile-5-MB`\n`/mint/data/datafile-129-MB` -> `myminio/mc-test-bucket-14946/datafile-129-MB`\n`/mint/data/datafile-65-MB` -> `myminio/mc-test-bucket-14946/datafile-65-MB`\n`/mint/data/datafile-6-MB` -> `myminio/mc-test-bucket-14946/datafile-6-MB`\n`/mint/data/datafile-33-kB` -> `myminio/mc-test-bucket-14946/datafile-33-kB`\nmc: <ERROR> Failed to copy `/mint/data/datafile-129-MB`. One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.\nmc: <ERROR> Failed to copy `/mint/data/datafile-0-b`. Please reduce your request\nmc: <ERROR> Failed to copy `/mint/data/datafile-5243880-b`. Please reduce your request\nTotal: 0 B, Transferred: 615.53 MiB, Speed: 4.91 MiB/s"
}
(6/15) Running minio-dotnet tests ... done in 8 minutes and 23 seconds
(7/15) Running minio-go tests ... FAILED in 11 minutes and 24 seconds
{
  "args": {},
  "duration": 92383,
  "error": "Please reduce your request",
  "function": "testStorageClassMetadataCopyObject()",
  "message": "PutObject failed",
  "name": "minio-go: testStorageClassMetadataCopyObject",
  "status": "FAIL"
}
(7/15) Running minio-java tests ... FAILED in 49 seconds
{
  "name": "minio-java",
  "function": "putObject(String bucketName, String objectName, InputStream stream, PutObjectOptions options)",
  "args": "X-Amz-Storage-Class: REDUCED_REDUNDANCY",
  "duration": 730,
  "status": "FAIL",
  "error": "error occurred [...]

2020-06-30 03:02 UTC, krishnasrinivas reviewed
@vadmeste instead of asking peer "give me all your tokens" isnt it better to ask "do you have this particular token?" ?

2020-06-30 03:13 UTC, harshavardhana commented
> @vadmeste instead of asking peer "give me all your tokens" isn't it better to ask "do you have this particular token?" ?

I personally thought that having `give me all your tokens` will help in getting a list of active heals in progress, which can be leveraged in the future.  Asking for a token is a simpler call but either way they are not expensive..

2020-06-30 09:39 UTC, vadmeste commented
> I personally thought that having `give me all your tokens` will help in getting a list of active heals in progress, which can be leveraged in the future. Asking for a token is a simpler call but either way they are not expensive..

yeah, I tend to make generic APIs to avoid breaking it in the future

2020-06-30 11:05 UTC, klauspost commented
Can't the token just include which server it originates from?

I tried looking at it, but it should be an index and not the host name since including the host name is problematic for security reasons.

```
// newHealToken generates a new healing ID.
func newHealToken(idx int) string {
	return fmt.Sprintf("%d+%s", idx, mustGetUUID())
}

// getHealTokenServer returns the server of a healing id.
// If the token is corrupted -1 is returned.
func getHealTokenServer(token string) int {
	s := strings.Split(token, "+")
	if len(s) < 2 {
		return -1
	}
	res, err := strconv.Atoi(s[0])
	if err != nil || res < 0 {
		return -1
	}
	return res
}
```
The main thing I can't figure out is how to get a server index. But maybe you are more clever than me at that.

Not objecting to this - it just seems a bit un-needed, so maybe .

2020-07-01 19:03 UTC, harshavardhana commented
> Can't the token just include which server it originates from?
> 
> I tried looking at it, but it should be an index and not the host name since including the host name is problematic for security reasons.
> 
> ```go
> // newHealToken generates a new healing ID.
> func newHealToken(idx int) string {
> 	return fmt.Sprintf("%d+%s", idx, mustGetUUID())
> }
> 
> // getHealTokenServer returns the server of a healing id.
> // If the token is corrupted -1 is returned.
> func getHealTokenServer(token string) int {
> 	s := strings.Split(token, "+")
> 	if len(s) < 2 {
> 		return -1
> 	}
> 	res, err := strconv.Atoi(s[0])
> 	if err != nil || res < 0 {
> 		return -1
> 	}
> 	return res
> }
> ```
> 
> The main thing I can't figure out is how to get a server index. But maybe you are more clever than me at that.
> 
> Not objecting to this - it just seems a bit un-needed, so maybe .

In a group of servers participating it is possible to achieve this, the token itself should tell which server 
index it belongs to - since a given list of endpoints is same across all the servers - achieving deterministic
approach is possible and maybe more performant here. 

As suggested by @klauspost @vadmeste we can add the server index like 

`index:uuid`

The token is always encoded in this form, this allows for the handler to directly
route the requests properly, if token is mangled then we reject such tokens
otherwise this makes it super easy. 

A similar technique can be done with ListObjectsV2 continuation-token @krishnasrinivas 
where client sends the continuation-token for the next batch, which should indicate
the serverIndex where the last state is stored. This allows for automatic routing as
the client indicates the state rather than guessing it on the server-side. 

ListObjectsV1, however, cannot take advantage of this, unless we sort of allowing
piggy-backing on `marker` similar to continuation token. Continuation token is an
opaque value but the marker is not so it is a bit tricky for V1 ListObjects.

To simplify this further we can simply say all clients should use ListObjectsV2 to
get the best performance otherwise, ListObjectsV1 will be slower when running
against a load balancer.

2020-07-02 16:40 UTC, vadmeste commented
Done.

The heal token has this format now: xxxx-xxxx-xxxx-xxx@index, and heal requests are routed accordingly.

2020-07-02 18:03 UTC, harshavardhana requested changes

2020-07-02 18:03 UTC, harshavardhana commented on cmd/admin-handlers.go
> +	if i := strings.Index(hip.clientToken, "@"); i >= 0 {
We should fail if the format is invalid with `invalidToken` error @vadmeste

2020-07-02 18:03 UTC, harshavardhana commented on cmd/admin-handlers.go
> +		if err == nil {
we should throw this as an error to client

2020-07-02 18:03 UTC, harshavardhana commented on cmd/endpoint.go
> +	var (
index cannot be `-1` you should add some validation for that or make sure this function panics.

2020-07-02 18:03 UTC, harshavardhana commented on cmd/endpoint.go
> +			if i == index {
Now that @krishnasrinivas PR is merged you can use `globalListEndpoints` to do this @vadmeste

2020-07-02 20:23 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :heavy_exclamation_mark: [more...](#f07c4362-125f-47d0-b1c8-c61a1183e709) |
| mint-large-bucket.sh | :heavy_exclamation_mark: [more...](#767f91d9-9162-4d4e-ab01-3f9f369a7381) |
| mint-fs.sh | :heavy_exclamation_mark: [more...](#d967f977-d1c4-4ff6-bfd4-4f1a0a39c5da) |
| mint-dist-xl.sh | :heavy_exclamation_mark: [more...](#cc722d14-f320-4c1a-afa3-26980c1c93d3) |
| mint-gateway-s3.sh | :heavy_exclamation_mark: [more...](#1b648a4a-2a2d-4b9e-b266-ff60e4a06c55) |
| mint-gateway-azure.sh | :x: [more...](#c780b3fc-465f-499d-9b8f-f78d2bfc2735) |
| mint-zoned.sh | :heavy_exclamation_mark: [more...](#aeeacbb8-87ee-4ac8-907d-5c0ee7af76a4) |
| mint-gateway-nas.sh | :heavy_exclamation_mark: [more...](#c2f7b8c7-3912-4cb7-adf5-114dce76cb60) |
<a name="c780b3fc-465f-499d-9b8f-f78d2bfc2735"></a>
### 9939-066a8ad/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev3.minio.io:31820
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 245a690b0c6b:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 38 seconds
(4/15) Running aws-sdk-ruby tests ... done in 15 seconds
(5/15) Running awscli tests ... done in 2 minutes and 46 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 2 minutes and 56 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 31 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 23 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 6 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1216,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... FAILED in 43 seconds
{
  "name": "minio-js",
  "function": "makeBucket(bucketName, region)",
  "args": "bucketName:minio-js-test-8ee01e1f-7dd5-41d6-b1a7-ca35c3d9a1fd-region, region:us-east-1",
  "duration": 40246,
  "status": "FAIL",
  "error": "S3Error: -> github.com/Azure/azure-storage-blob-go/azblob.newStorageError, github.com/Azure/azure-storage-blob-go@v0.8.0/azblob/zc_storage_error.go:42 ===== RESPONSE ERROR (ServiceCode=ContainerBeingDeleted) ===== Description=The specified container is being deleted. Try operation later. RequestId:62579fb1-a01e-0117-18ac-506bd8000000 Time:2020-07-02T20:10:54.2586878Z, Details: Code: ContainerBeingDeleted PUT https://minioazure.blob.core.windows.net/minio-js-test-8ee01e1f-7dd5-41d6-b1a7-ca35c3d9a1fd-region?restype=container&timeout=1501 Authorization: REDACTED User-Agent: [APN/1.0 MinIO/1.0 MinIO/2020-07-02T19:43:34Z] X-Ms-Client-Request-Id: [09fc208a-1db3-431d-6321-eb875fcd4833] X-Ms-Date: [Thu, 02 Jul 2020 20:10:54 GMT] X-Ms-Version: [2018-11-09] -------------------------------------------------------------------------------- RESPONSE Status: 409 The specified container is being deleted. Try operation later. Content-Length: [252] Content-Type: [application/xml] Date: [Thu, 02 Jul 2020 20:10:53 GMT] Server: [Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0] X-Ms-Error-Code: [ContainerBeingDeleted] X-Ms-Request-Id: [62579fb1-a01e-0117-18ac-506bd8000000] X-Ms-Version: [2018-11-09] at Object.parseError (node_modules/minio/dist/main/xml-parsers.js:86:11) at /mint/run/core/minio-js/node_modules/minio/dist/main/transformers.js:156:22 at DestroyableTransform._flush (node_modules/minio/dist/main/transformers.js:80:10) at DestroyableTransform.prefinish (node_modules/readable-stream/lib/_stream_transform.js:129:10) at prefinish (node_modules/readable-stream/lib/_stream_writable.js:611:14) at finishMaybe (node_modules/readable-stream/lib/_stream_writable.js:620:5) at endWritable (node_modules/readable-stream/lib/_stream_writable.js:643:3) at DestroyableTransform.Writable.end (node_modules/readable-stream/lib/_stream_writable.js:571:22) at IncomingMessage.onend (_stream_readable.js:673:10) at endReadableNT (_stream_readable.js:1201:12) at processTicksAndRejections (internal/process/task_queues.js:84:21)"
}
(10/15) Running minio-py tests ... done in 9 minutes and 39 seconds
(11/15) Running s3cmd tests ... done in 1 minutes and 19 seconds
(12/15) Running s3select tests ... done in 1 minutes and 4 seconds
(13/15) Running security tests ... done in 0 seconds

Executed 13 out of 15 tests successfully.
```
<a name="c2f7b8c7-3912-4cb7-adf5-114dce76cb60"></a>
### 9939-066a8ad/mint-gateway-nas.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="f07c4362-125f-47d0-b1c8-c61a1183e709"></a>
### 9939-066a8ad/mint-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="767f91d9-9162-4d4e-ab01-3f9f369a7381"></a>
### 9939-066a8ad/mint-large-bucket.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="d967f977-d1c4-4ff6-bfd4-4f1a0a39c5da"></a>
### 9939-066a8ad/mint-fs.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="cc722d14-f320-4c1a-afa3-26980c1c93d3"></a>
### 9939-066a8ad/mint-dist-xl.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="1b648a4a-2a2d-4b9e-b266-ff60e4a06c55"></a>
### 9939-066a8ad/mint-gateway-s3.sh.xtrace:
```
DISABLED TIME BEING
```
<a name="aeeacbb8-87ee-4ac8-907d-5c0ee7af76a4"></a>
### 9939-066a8ad/mint-zoned.sh.xtrace:
```
DISABLED TIME BEING
```
Deleting image on docker hub
Deleting image locally

2020-07-02 21:48 UTC, harshavardhana approved these changes

2020-07-03 08:58 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-fs.sh | :heavy_check_mark: |
| mint-gateway-s3.sh | :heavy_check_mark: |
| mint-gateway-nas.sh | :heavy_check_mark: |
| mint-xl.sh | :x: [more...](#af702a0c-7b31-4ab4-9f74-66c9649956a8) |
| mint-large-bucket.sh | :x: [more...](#8ddea04f-acc8-4d0b-8028-a8c33357ef94) |
| mint-dist-xl.sh | :x: [more...](#b7d47d5d-6790-445f-9ea4-3dd1c4256509) |
| mint-gateway-azure.sh | :x: [more...](#204f3930-5ad5-4091-935c-2b5f00f56e3e) |
| mint-zoned.sh | :x: [more...](#d59d4215-42fb-422b-ae1e-35ad84bc0b08) |
<a name="b7d47d5d-6790-445f-9ea4-3dd1c4256509"></a>
### 9939-7ae792c/mint-dist-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-c2.minio.io:30826
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 9d32ce10078e:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 10 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 47 seconds
(4/15) Running aws-sdk-ruby tests ... done in 8 seconds
(5/15) Running awscli tests ... done in 2 minutes and 35 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 30 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 58 seconds
(9/15) Running minio-go tests ... FAILED in 2 minutes and 3 seconds
{
  "args": {
    "bucketName": "minio-go-test-4kapfpi6ba3pycib",
    "objectName": "5rvjs1x9wly6tiur2yug3ghcfo432t",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4377,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 3 minutes and 59 seconds
(10/15) Running minio-js tests ... done in 57 seconds
(11/15) Running minio-py tests ... done in 5 minutes and 27 seconds
(12/15) Running s3cmd tests ... done in 26 seconds
(13/15) Running s3select tests ... done in 19 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="d59d4215-42fb-422b-ae1e-35ad84bc0b08"></a>
### 9939-7ae792c/mint-zoned.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev4.minio.io:30273
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp be754db94a52:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 16 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 48 seconds
(4/15) Running aws-sdk-ruby tests ... done in 11 seconds
(5/15) Running awscli tests ... done in 2 minutes and 14 seconds
(6/15) Running healthcheck tests ... done in 0 seconds
(7/15) Running mc tests ... done in 1 minutes and 40 seconds
(8/15) Running minio-dotnet tests ... done in 2 minutes and 39 seconds
(9/15) Running minio-go tests ... FAILED in 3 minutes and 9 seconds
{
  "args": {
    "bucketName": "minio-go-test-1jhsoo545j96d105",
    "objectName": "pix9ovwlkms0wwn9xrhsytcejcvorw",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 4950,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 4 minutes and 51 seconds
(10/15) Running minio-js tests ... done in 1 minutes and 3 seconds
(11/15) Running minio-py tests ... done in 6 minutes and 27 seconds
(12/15) Running s3cmd tests ... done in 22 seconds
(13/15) Running s3select tests ... done in 19 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="204f3930-5ad5-4091-935c-2b5f00f56e3e"></a>
### 9939-7ae792c/mint-gateway-azure.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:30700
ACCESS_KEY:           minioazure
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 6edf184e84b4:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 7 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... done in 2 minutes and 41 seconds
(4/15) Running aws-sdk-ruby tests ... done in 16 seconds
(5/15) Running awscli tests ... done in 3 minutes and 50 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 3 minutes and 7 seconds
(8/15) Running minio-dotnet tests ... done in 1 minutes and 33 seconds
(9/15) Running minio-go tests ... done in 5 minutes and 15 seconds
(10/15) Running minio-java tests ... FAILED in 5 minutes and 16 seconds
{
  "name": "minio-java",
  "function": "removeObjects(RemoveObjectsArgs args)",
  "duration": 1226,
  "status": "FAIL",
  "error": "org.simpleframework.xml.core.ValueRequiredException: Unable to satisfy @org.simpleframework.xml.Element(name=\"Key\", type=void.class, data=false, required=true) on field 'name' private java.lang.String io.minio.messages.DeletedObject.name for class io.minio.messages.DeletedObject at line 2 >>> [io.minio.Xml.unmarshal(Xml.java:68), io.minio.MinioClient.deleteObjects(MinioClient.java:7354), io.minio.MinioClient$1$1.populate(MinioClient.java:2945), io.minio.MinioClient$1$1.hasNext(MinioClient.java:2977), FunctionalTest.removeObjects(FunctionalTest.java:1395), FunctionalTest.removeObjects_test1(FunctionalTest.java:1534), FunctionalTest.runTests(FunctionalTest.java:3812), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(10/15) Running minio-js tests ... done in 2 minutes and 35 seconds
(11/15) Running minio-py tests ... done in 9 minutes and 52 seconds
(12/15) Running s3cmd tests ... done in 1 minutes and 28 seconds
(13/15) Running s3select tests ... done in 1 minutes and 3 seconds
(14/15) Running security tests ... done in 0 seconds

Executed 14 out of 15 tests successfully.
```
<a name="af702a0c-7b31-4ab4-9f74-66c9649956a8"></a>
### 9939-7ae792c/mint-xl.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev6.minio.io:31154
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp 4b7c02ed891d:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 1 seconds
(2/15) Running aws-sdk-java tests ... done in 3 seconds
(3/15) Running aws-sdk-php tests ... done in 43 seconds
(4/15) Running aws-sdk-ruby tests ... done in 3 seconds
(5/15) Running awscli tests ... done in 2 minutes and 8 seconds
(6/15) Running healthcheck tests ... done in 1 seconds
(7/15) Running mc tests ... done in 42 seconds
(8/15) Running minio-dotnet tests ... done in 38 seconds
(9/15) Running minio-go tests ... FAILED in 1 minutes and 41 seconds
{
  "args": {
    "bucketName": "minio-go-test-akqbnpr2n1evkzn9",
    "objectName": "sqgamtbkbda1ori2tguu4lvgzcyx34",
    "objectPrefix": "",
    "recursive": "true"
  },
  "duration": 5578,
  "error": "The bucket you tried to delete is not empty. You must delete all versions in the bucket.",
  "function": "RemoveObjectsWithOptions(bucketName, objectsCh, opts)",
  "message": "Cleanup failed",
  "name": "minio-go: testRemoveObjectsWithOptions",
  "status": "FAIL"
}
(9/15) Running minio-java tests ... done in 1 minutes and 6 [...]

2020-07-03 15:39 UTC, harshavardhana requested changes

2020-07-03 15:39 UTC, harshavardhana commented on cmd/handler-utils.go
> +		RoundTripper: NewGatewayHTTPTransport(),
Use ep.Transport @vadmeste

2020-07-03 17:21 UTC, harshavardhana approved these changes

2020-07-03 18:53 UTC, merged

2020-07-03 21:48 UTC, minio-trusted commented
## Mint Automation
| Test | Result |
|:--- |:--- |
| mint-xl.sh | :x: [more...](#5a072ed2-23d3-4e9d-a940-eb408a75d833) |
| mint-large-bucket.sh | :x: [more...](#12d9c421-9697-4c8d-bbd2-2a1ed3adab7c) |
| mint-fs.sh | :x: [more...](#8e12a191-42b1-4a3d-aa0e-ed2e6765a322) |
| mint-dist-xl.sh | :x: [more...](#32497644-4ce5-43f9-b17d-e2a5661709fc) |
| mint-gateway-s3.sh | :x: [more...](#05788252-5809-4ece-83d9-9b207b56462d) |
| mint-gateway-azure.sh | :x: [more...](#63978668-8003-4354-b50b-49c4fabab1e9) |
| mint-zoned.sh | :x: [more...](#2e66dd9d-25f6-445f-b464-b89fc1241f2c) |
| mint-gateway-nas.sh | :x: [more...](#abf43752-13ee-42f0-b485-6bc53afd18bb) |
<a name="abf43752-13ee-42f0-b485-6bc53afd18bb"></a>
### 9939-a07eb33/mint-gateway-nas.sh.log:
```
Running with
SERVER_ENDPOINT:      minio-dev7.minio.io:30970
ACCESS_KEY:           minio
SECRET_KEY:           ***REDACTED***
ENABLE_HTTPS:         0
SERVER_REGION:        us-east-1
MINT_DATA_DIR:        /mint/data
MINT_MODE:            full
ENABLE_VIRTUAL_STYLE: 0

To get logs, run 'docker cp cdefbeaee738:/mint/log /tmp/mint-logs'

(1/15) Running aws-sdk-go tests ... done in 0 seconds
(2/15) Running aws-sdk-java tests ... done in 2 seconds
(3/15) Running aws-sdk-php tests ... FAILED in 3 hours 26 minutes and 31 seconds
{
  "name": "aws-sdk-php",
  "function": "listObjects ( array $params = [] )",
  "args": {
    "Bucket": "aws-sdk-php-5eff76a9f254b",
    "Object": "obj1"
  },
  "duration": "12390567",
  "status": "FAIL",
  "error": "Error executing \"DeleteObjects\" on \"http://minio-dev7.minio.io:30970/aws-sdk-php-5eff76a9f254b?delete\"; AWS HTTP error: cURL error 7: Failed to connect to minio-dev7.minio.io port 30970: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html)"
}
(3/15) Running aws-sdk-ruby tests ... FAILED in 11 seconds
{
  "name": "aws-sdk-ruby",
  "function": "listBuckets",
  "args": {},
  "duration": 9425.05,
  "error": "Failed to open TCP connection to minio-dev7.minio.io:30970 (Connection refused - connect(2) for \"minio-dev7.minio.io\" port 30970)",
  "status": "FAIL"
}
(3/15) Running awscli tests ... FAILED in 9 seconds
{"name": "awscli", "duration": 7454, "function": "make_bucket\n", "status": "FAIL", "error": "Could not connect to the endpoint URL: "http://minio-dev7.minio.io:30970/awscli-mint-test-bucket-2991""}
(3/15) Running healthcheck tests ... FAILED in 0 seconds
{
  "alert": "",
  "args": null,
  "duration": 13,
  "error": "Get http://minio-dev7.minio.io:30970/minio/health/live: dial tcp 72.28.97.56:30970: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(3/15) Running mc tests ... FAILED in 1 seconds
{
  "alert": "",
  "args": null,
  "duration": 13,
  "error": "Get http://minio-dev7.minio.io:30970/minio/health/live: dial tcp 72.28.97.56:30970: connect: connection refused",
  "function": "testLivenessEndpoint",
  "message": "GET request failed",
  "name": "healthcheck",
  "status": "FAIL"
}
(3/15) Running minio-dotnet tests ... done in 2 seconds
(4/15) Running minio-go tests ... FAILED in 1 minutes and 29 seconds
{
  "args": {
    "bucketName": "minio-go-test-nkov2edpcdlo0t1a",
    "region": "eu-west-1"
  },
  "duration": 89138,
  "error": "Put http://minio-dev7.minio.io:30970/minio-go-test-nkov2edpcdlo0t1a/: dial tcp 72.28.97.56:30970: connect: connection refused",
  "function": "MakeBucket(bucketName, region)",
  "message": "MakeBucket failed",
  "name": "minio-go: testGetObjectClosedTwiceV2",
  "status": "FAIL"
}
(4/15) Running minio-java tests ... FAILED in 1 seconds
{
  "name": "minio-java",
  "function": "makeBucket(MakeBucketArgs args)",
  "duration": 92,
  "status": "FAIL",
  "error": "java.net.ConnectException: Failed to connect to minio-dev7.minio.io/72.28.97.56:30970 >>> [okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:265), okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183), okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224), okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108), okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88), okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169), okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142), okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117), okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229), okhttp3.RealCall.execute(RealCall.java:81), io.minio.MinioClient.execute(MinioClient.java:1014), io.minio.MinioClient.makeBucket(MinioClient.java:3773), FunctionalTest.makeBucket_test1(FunctionalTest.java:435), FunctionalTest.runTests(FunctionalTest.java:3772), FunctionalTest.main(FunctionalTest.java:4056)]"
}
(4/15) Running minio-js tests ... FAILED in 1 seconds
{
  "name": "minio-js",
  "function": "\"after all\" hook in \"functional tests\"",
  "duration": 8,
  "status": "FAIL",
  "error": "Error: connect ECONNREFUSED 72.28.97.56:30970 at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"
}
(4/15) Running minio-py tests ... FAILED in 6 seconds
{
  "name": "minio-py:test_make_bucket_default_region",
  "function": "make_bucket(bucket_name, location)",
  "args": {
    "bucket_name": "minio-py-test-72c6763a-c9f5-4bd2-99dd-55473d6ac7f8",
    "location": "default value ('us-east-1')"
  },
  "duration": 6059,
  "message": "HTTPConnectionPool(host='minio-dev7.minio.io', port=30970): Max retries exceeded with url: /minio-py-test-72c6763a-c9f5-4bd2-99dd-55473d6ac7f8/ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f57ce690780>: Failed to establish a new connection: [Errno 111] Connection refused',))",
  "error": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connection.py\", line 160, in _new_conn\n    (self._dns_host, self.port), self.timeout, **extra_kw\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py\", line 84, in create_connection\n    raise err\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/util/connection.py\", line 74, in create_connection\n    sock.connect(sa)\nConnectionRefusedError: [Errno 111] Connection refused\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 677, in urlopen\n    chunked=chunked,\n  File \"/usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py\", line 392, in _make_request\n    conn.request(method, url, **httplib_request_kw)\n  File \"/usr/lib/python3.6/http/client.py\", line 1264, in request\n    self._send_request(method, url, body, headers, encode_chunked)\n  File \"/usr/lib/python3.6/http/client.py\", line 1310, in _send_request\n    self.endheaders(body, encode_chunked=encode_chunked)\n  File \"/usr/lib/python3.6/http/client.py\", line 1259, in endheaders\n    self._send_output(message_body, encode_chunked=encode_chunked)\n  File \"/usr/lib/python3.6/http/client.py\", line 1038, in _send_output\n    self.send(msg)\n  File \"/usr/lib/py [...]