Add Readiness Cache
minio/minio pull request #9940
Opened 2020-06-29 16:52 UTC by kerneltime

## Description
Allow an eager probing of readiness value while controlling chattiness if the last status was ready.

## Motivation and Context
This is to allow faster detection of readiness by probes such as those that are included in k8s.

## How to test this PR?
Bring up minio using operator

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] Fixes a regression (If yes, please add `commit-id` or `PR #` here)
- [ ] Documentation needed
- [ ] Unit tests needed
- [ ] Functional tests needed (If yes, add [mint](https://github.com/minio/mint) PR # here: )

2020-06-29 16:52 UTC, kerneltime commented
corresponding operator changes: https://github.com/minio/minio-operator/pull/158

2020-06-29 17:11 UTC, harshavardhana requested changes

2020-06-29 17:11 UTC, harshavardhana commented on cmd/object-api-common.go
> +//Global cached readiness flag
```suggestion
// Global cached readiness flag
```

2020-06-29 17:11 UTC, harshavardhana commented on cmd/utils.go
> +// ForceUpdates the value and caches it.
```suggestion
// ForceUpdate the value and caches it.
```

2020-06-29 17:11 UTC, harshavardhana commented on cmd/healthcheck-handler.go
> +		if !objLayer.IsReady(ctx) && newObjectLayerFn() == nil {
can be written in a single line

```suggestion
		return objLayer.IsReady(ctx)
```

2020-06-29 17:11 UTC, harshavardhana commented on cmd/healthcheck-handler.go
> +	if v.(bool) == true {
```suggestion
	if v.(bool) {
```

2020-06-29 17:11 UTC, harshavardhana commented on cmd/healthcheck-handler.go
> +	if v.(bool) == true {
```suggestion
	if v.(bool) {
```

2020-06-29 23:33 UTC, minio-trusted commented
```
Error running mint automation
+ mkdir -p 9940-1f230f5/gopath/src/github.com/minio
+ git -C 9940-1f230f5/gopath/src/github.com/minio clone --quiet https://github.com/minio/minio.git
+ git -C 9940-1f230f5/gopath/src/github.com/minio/minio remote add minio https://github.com/minio/minio.git
+ git -C 9940-1f230f5/gopath/src/github.com/minio/minio fetch --quiet minio pull/9940/head:pr9940
+ git -C 9940-1f230f5/gopath/src/github.com/minio/minio checkout --quiet pr9940
+ GO111MODULE=on
+ GOPATH=/home/mint-auto/mint-auto/9940-1f230f5/gopath
+ make -C 9940-1f230f5/gopath/src/github.com/minio/minio --quiet
go: downloading github.com/minio/cli v1.22.0
go: downloading github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading google.golang.org/api v0.5.0
go: downloading github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/minio/minio-go/v6 v6.0.58-0.20200612001654-a57fec8037ec
go: downloading github.com/json-iterator/go v1.1.10
go: downloading gopkg.in/jcmturner/gokrb5.v7 v7.3.0
go: downloading github.com/klauspost/compress v1.10.3
go: extracting github.com/Azure/azure-pipeline-go v0.2.1
go: downloading github.com/gorilla/rpc v1.2.0
go: extracting github.com/gorilla/rpc v1.2.0
go: extracting github.com/minio/cli v1.22.0
go: downloading github.com/dustin/go-humanize v1.0.0
go: extracting github.com/json-iterator/go v1.1.10
go: downloading github.com/cespare/xxhash v1.1.0
go: extracting github.com/cespare/xxhash v1.1.0
go: extracting github.com/dustin/go-humanize v1.0.0
go: downloading github.com/cespare/xxhash/v2 v2.1.1
go: extracting github.com/cespare/xxhash/v2 v2.1.1
go: downloading github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: extracting github.com/colinmarc/hdfs/v2 v2.1.1
go: downloading github.com/djherbis/atime v1.0.0
go: extracting github.com/minio/minio-go/v6 v6.0.58-0.20200612001654-a57fec8037ec
go: extracting github.com/djherbis/atime v1.0.0
go: downloading github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading github.com/rs/cors v1.7.0
go: downloading github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: downloading github.com/golang/protobuf v1.3.2
go: extracting github.com/valyala/tcplisten v0.0.0-20161114210144-ceec8f93295a
go: downloading gopkg.in/ini.v1 v1.57.0
go: extracting github.com/rs/cors v1.7.0
go: extracting github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: extracting gopkg.in/ini.v1 v1.57.0
go: downloading github.com/minio/md5-simd v1.1.0
go: extracting github.com/shirou/gopsutil v2.20.3-0.20200314133625-53cec6b37e6a+incompatible
go: extracting github.com/golang/protobuf v1.3.2
go: downloading github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/tinylib/msgp v1.1.1
go: downloading github.com/willf/bloom v2.0.3+incompatible
go: extracting github.com/minio/md5-simd v1.1.0
go: extracting github.com/willf/bloom v2.0.3+incompatible
go: extracting github.com/mattn/go-ieproxy v0.0.0-20190805055040-f9202b1cfdeb
go: downloading github.com/dchest/siphash v1.2.1
go: extracting github.com/tinylib/msgp v1.1.1
go: extracting github.com/dchest/siphash v1.2.1
go: downloading github.com/miekg/dns v1.1.8
go: downloading github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/miekg/dns v1.1.8
go: downloading github.com/minio/sio v0.2.0
go: extracting github.com/coreos/etcd v3.3.12+incompatible
go: extracting github.com/minio/sio v0.2.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/willf/bitset v1.1.10
go: extracting github.com/willf/bitset v1.1.10
go: downloading github.com/klauspost/readahead v1.3.1
go: downloading github.com/philhofer/fwd v1.0.0
go: extracting github.com/philhofer/fwd v1.0.0
go: downloading github.com/minio/highwayhash v1.0.0
go: extracting github.com/klauspost/readahead v1.3.1
go: downloading github.com/beevik/ntp v0.2.0
go: extracting github.com/minio/highwayhash v1.0.0
go: downloading github.com/mattn/go-isatty v0.0.8
go: extracting github.com/mattn/go-isatty v0.0.8
go: downloading github.com/fatih/color v1.7.0
go: extracting github.com/fatih/color v1.7.0
go: downloading github.com/lib/pq v1.1.1
go: extracting github.com/beevik/ntp v0.2.0
go: extracting github.com/lib/pq v1.1.1
go: downloading cloud.google.com/go v0.39.0
go: extracting google.golang.org/api v0.5.0
go: extracting cloud.google.com/go v0.39.0
go: downloading github.com/nats-io/nats.go v1.9.1
go: extracting github.com/nats-io/nats.go v1.9.1
go: downloading github.com/nats-io/nuid v1.0.1
go: extracting github.com/nats-io/nuid v1.0.1
go: downloading github.com/nsqio/go-nsq v1.0.7
go: extracting github.com/nsqio/go-nsq v1.0.7
go: downloading github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: extracting github.com/inconshreveable/go-update v0.0.0-20160112193335-8152e7eb6ccf
go: downloading github.com/hashicorp/vault/api v1.0.4
go: extracting github.com/klauspost/compress v1.10.3
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading golang.org/x/sys v0.0.0-20200610111108-226ff32320da
go: downloading github.com/google/uuid v1.1.1
go: extracting github.com/hashicorp/vault/api v1.0.4
go: downloading golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: extracting github.com/google/uuid v1.1.1
go: downloading github.com/klauspost/cpuid v1.3.0
go: extracting gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/hashicorp/vault/sdk v0.1.13
go: downloading golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/modern-go/reflect2 v1.0.1
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/hashicorp/go-rootcerts v1.0.1
go: extracting github.com/hashicorp/vault/sdk v0.1.13
go: extracting golang.org/x/net v0.0.0-20200602114024-627f9648deb9
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/nats-io/stan.go v0.4.5
go: downloading github.com/gorilla/handlers v1.4.2
go: downloading github.com/hashicorp/go-multierror v1.0.0
go: extracting golang.org/x/crypto v0.0.0-20200604202706-70a84ac30bf9
go: extracting github.com/hashicorp/go-rootcerts v1.0.1
go: downloading github.com/prometheus/client_golang v0.9.3
go: extracting github.com/klauspost/cpuid v1.3.0
go: downloading google.golang.org/genproto v0.0.0-20190513181449-d00d292a067c
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: extracting github.com/gorilla/handlers v1.4.2
go: downloading github.com/minio/sha256-simd v0.1.1
go: extracting github.com/nats-io/stan.go v0.4.5
go: downloading github.com/ncw/directio v1.0.5
go: extracting github.com/hashicorp/go-multierror v1.0.0
go: downloading gopkg.in/olivere/elastic.v5 v5.0.80
go: extracting github.com/mitchellh/mapstructure v1.1.2
go: downloading gopkg.in/square/go-jose.v2 v2.3.1
go: extracting github.com/prometheus/client_golang v0.9.3
go: extracting github.com/ncw/directio v1.0.5
go: downloading github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: extracting github.com/minio/sha256-simd v0.1.1
go: downloading github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading github.com/nats-io/jwt v0.3.2
go: extracting golang.org/x/sys v0.0.0-20200610111108-226ff32320da
go: downloading golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: extracting github.com/elazarl/go-bindata-assetfs v1.0.0
go: downloading google.golang.org/grpc v1.22.0
go: extracting github.com/nats-io/jwt v0.3.2
go: downloading github.com/alecthomas/participle v0.2.1
go: extracting github.com/streadway/amqp v0.0.0-20190404075320-75d898a42a94
go: extracting golang.org/x/oauth2 v0.0.0-20190402181905-9f3314589c9a
go: downloading github.com/go-sql-driver/mysql v1.5.0
go: extracting gopkg.in/square/go-jose.v2 v2.3.1
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/alecthomas/participl [...]

2020-06-30 04:10 UTC, harshavardhana commented
As discussed you can close this PR @kerneltime

2020-06-30 16:54 UTC, kerneltime commented
#9941 supersedes this one

2020-06-30 16:54 UTC, closed without merging